AudiusProject/apps

- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/web/src/common/store/social/users/sagas.ts
Migrate subscribeToUser, unsubscribeToUser to sdk.
Tested both sub/unsub on local web stage
> [PAY-3631] Migrate sub/unsubscribe to user to sdk

- packages/common/src/services/auth/authService.ts
- packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFooter.tsx
- packages/web/src/components/track/desktop/TrackTile.tsx
- packages/web/src/components/track/mobile/TrackTile.tsx
- packages/web/src/pages/sign-up-page/pages/CreatePasswordPage.tsx
Fixes issue due to importing @audius/common/src.
> Fix src imports leading to web type errors

- pkg/mediorum/server/audio_analysis.go
- pkg/mediorum/server/serve_upload.go
- adds optional ability to analyze a track that's not in a done state
> add analyze flag to individual tracks

- packages/mobile/ios/Podfile.lock
- packages/mobile/package.json
- packages/mobile/src/screens/edit-track-screen/EditTrackFormPreviewContext.tsx
> [C-5461] Add small sound library and update preview context to play previews for file replace

- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/common/src/store/ui/vip-discord-modal/sagas.ts
- packages/common/src/utils/streaming.ts
- packages/mobile/src/components/audio/AudioPlayer.tsx
- packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts
- packages/web/src/common/store/player/sagas.ts
- packages/web/src/common/store/player/store.test.ts
- packages/web/src/common/store/social/tracks/sagas.ts
Migrate `AudiusBackend.getSignature` to use sdk.
Tested streaming on mobile stage (with purchased, unpurchased tracks)
Tested discord role upgrade button on mobile stage
> [PAY-3636] Migrate getSignature to sdk

- packages/web/src/components/collection/CollectionTileMetrics.tsx
- packages/web/src/components/track/TrackTileMetrics.tsx
Realized the gap spacing between repost avatar list and repost text was much too large
> [C-5469] Fix repost avatar-list spacing

- packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
- packages/web/src/components/edit-track/EditTrackForm.tsx
Update download function on web and mobile to use the established patterns for downloading. 
Manually tested on web and mobile
> [C-5468, C-5470] Update downloads for file-replace

- packages/mobile/ios/Podfile.lock
- packages/mobile/package.json
- packages/mobile/src/screens/edit-track-screen/EditTrackFormPreviewContext.tsx
No more sound player, hopefully no more app crashes
Tested in the simulator
> [C-5475] Update mobile track replace previews to use video lib

- packages/discovery-provider/src/api/v1/users.py
- packages/web/src/common/store/cache/users/sagas.ts
- packages/web/src/common/store/profile/fetchProfileCollectionsSaga.ts
- packages/web/src/pages/dashboard-page/store/sagas.ts
Invalid fetches because authed_user_id was not compared to user_id on the server side, and on the client side we were sending the dupe user id along with each request
Stack comes up and endpoint returns successfully, will confirm on staging with more data
> Fix invalid playlist fetching

- packages/web/src/common/store/upload/sagas.ts
Lost some functionality in the sdk migration. Added it back
Manually tested on web and simulator
> Fix track audio replace edits

- packages/web/src/common/store/pages/signon/sagas.ts
Setup audius backend with correct wallet on signup. Otherwise, you need a refresh to setup w the right wallet.
Confirmed the libs and account wallet match. The user bank derived after signup is correct.
> Setup backend on sdk signup

- packages/discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
- packages/web/src/pages/chat-page/components/InboxUnavailableMessage.tsx
* Prettier wanted to format something in `dmNotifications.ts`
* Added a missing space in the `ChatUnavailable` UI
> Two small cleanups

- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/common/src/store/playlist-updates/playlistUpdatesSagas.ts
- packages/sdk/src/sdk/api/notifications/NotificationsApi.test.ts
- packages/sdk/src/sdk/api/notifications/NotificationsApi.ts
- packages/sdk/src/sdk/api/notifications/types.ts
- packages/sdk/src/sdk/sdk.ts
- packages/web/src/common/store/notifications/sagas.ts
Move notification writes to sdk
- Some minimal unit tests for notifications api
- Marked notif as read & marked playlist as viewed on stage, confirmed in db
> [PAY-2936] Move notification writes to sdk

- packages/sdk/src/sdk/api/notifications/NotificationsApi.ts
- packages/sdk/src/sdk/sdk.ts
#10540 and #10629 collided, this fixes a semantic merge conflict
> Fix NotificationsApi to not require authService dep

- packages/common/src/adapters/user.ts
- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/sdk/src/sdk/api/users/UsersApi.ts
- packages/sdk/src/sdk/api/users/types.ts
This will require a lot of testing!
I also need to check to see if indexing will support metadata containing changes to playlist_library, collectibles, and associated_wallets.
Some trivial updates on staging with simple metadata.
More to test:
- Associated wallets
- Collectibles
- Playlist library
> [PAY-3634] Move updateCreator to sdk

- packages/mobile/src/components/action-drawer/ActionDrawer.tsx
- packages/mobile/src/components/block-messages-drawer/BlockMessagesDrawer.tsx
- packages/mobile/src/components/chat-actions-drawer/ChatActionsDrawer.tsx
- packages/mobile/src/components/create-chat-actions-drawer/CreateChatActionsDrawer.tsx
- packages/mobile/src/components/delete-chat-drawer/DeleteChatDrawer.tsx
- packages/mobile/src/components/drawer/NativeDrawer.tsx
Originally fixing issue where message overflow drawers weren't fully clickable (only over the text), and then went ahead and refactored them all to common components, simplifying our code in the process
> [C-5472] Refactor message drawers to use common drawers

- packages/sdk/src/sdk/api/notifications/NotificationsApi.test.ts
> Fix NotificationsApiTest

- packages/web/src/pages/audio-rewards-page/Tiers.tsx
When I updated the rewards page, I had forgotten that we made this change a few months back:
https://github.com/AudiusProject/audius-protocol/pull/7979
Local staging
> Correct rewards page collectibles gating

- packages/mobile/android/app/build.gradle
- packages/mobile/ios/AudiusReactNative/Info.plist
Upgrade mobile apps to lastest to fix mobile builds. Lets see what happens with the Friday release, curious if it bumps again
> Upgrade mobile apps to v1.1.128

- packages/discovery-provider/src/challenges/challenges.dev.json
- packages/discovery-provider/src/challenges/challenges.json
- packages/discovery-provider/src/challenges/challenges.stage.json
Add cushion so we can retry incorrect disbursements
n/a
> Up weekly pool for trending challenges

- packages/harmony/src/foundations/color/primitiveV2.ts
- packages/mobile/src/harmony-native/components/Button/Button/Button.tsx
- packages/mobile/src/harmony-native/components/Button/EntityActionButton/EntityActionButton.tsx
- packages/mobile/src/harmony-native/components/Button/IconButton/IconButton.tsx
- packages/mobile/src/harmony-native/components/Button/PlainButton/PlainButton.tsx
- packages/mobile/src/harmony-native/components/TextLink/TextPressable.tsx
- packages/mobile/src/harmony-native/components/input/SelectablePill/SelectablePill.tsx
- packages/mobile/src/harmony-native/components/input/TextInput/TextInput.tsx
- packages/mobile/src/harmony-native/components/layout/Paper/Paper.tsx
- packages/mobile/src/harmony-native/constants.ts
- packages/mobile/src/styles/makeAnimations.ts
- packages/mobile/src/utils/themeV2.ts
Addresses issues in mobile theme.
Primary changes:
- Ensure useAnimated hooks respond to theme change
- Add hit-slop to selectable pill
- Add secondary static to fix splash screen loading 
- Fix makeAnimations for some lottie files.
> [C-5481] Mobile harmony-theme-v2 QA

- pkg/core/console/uptime.go
- pkg/core/console/views/pages/uptime_page.templ
- pkg/core/console/views/pages/uptime_page_templ.go
- pkg/core/db/reads.sql.go
- pkg/core/db/sql/reads.sql
Provides much more clarity in the use and design of SLA rollups.
Thresholds for sla hit or miss are currently arbitrary but can be finalized later.
[Working on stage](https://discoveryprovider2.staging.audius.co/console/uptime/144)
> Improve uptime console page

- packages/mobile/src/hooks/useTikTokAuth.ts
- packages/web/src/common/store/pages/signon/sagas.ts
- packages/web/src/components/twitter-auth/TwitterAuthButton.tsx
has PR feedback I forgot to commit before merging + classified a bunch of errors as `Fatal` in sign up saga
web:staeg
> Sign Up Hardening 2.5

- packages/discovery-provider/integration_tests/tasks/test_get_feed_es.py
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/tmp.txt
- packages/discovery-provider/src/queries/get_feed_es.py
- packages/discovery-provider/src/queries/query_helpers.py
- packages/discovery-provider/src/utils/elasticdsl.py
- packages/web/src/common/store/lineup/sagas.ts
- packages/web/src/common/store/pages/feed/lineup/sagas.ts
This reverts commit 09f2da901b8c848f76ff4ca78b24d5c43d709ed1.
I have no idea why it doesn't work, but it's feeling kind of non-trivial
> Revert "[PAY-3643] Improve feed performance (#10661)"

- packages/common/src/store/ui/modals/replace-track-progress-modal/index.ts
- packages/mobile/src/screens/edit-track-screen/components/ReplaceTrackProgressDrawer.tsx
- packages/web/src/common/store/upload/sagas.ts
- packages/web/src/components/replace-track-progress-modal/ReplaceTrackProgressModal.tsx
> [C-5479] Add error states for track replace progress

- packages/mobile/src/screens/edit-track-screen/components/ReplaceTrackProgressDrawer.tsx
- packages/web/src/common/store/upload/sagas.ts
- packages/web/src/components/edit-track/EditTrackForm.tsx
- packages/web/src/components/replace-track-progress-modal/ReplaceTrackProgressModal.tsx
* Fix Margins
* Fix logo color
* Stop previews on unmount
* Shorten wait time
* Download name was fixed in another thing
Manually tested on web and simulator
> [C-5464] Track Replace QA 1

- packages/common/src/store/storeContext.ts
- packages/mobile/src/store/storeContext.ts
- packages/web/src/common/store/account/sagas.js
- packages/web/src/store/storeContext.ts
currentScope callback is deprecated. use recommended `getCurrentScope`
Local simulator
> Fix sentry mobile scope issue

- packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
Was not actually full width because of the container. On RC
> Fix buy button width

- packages/common/src/services/audius-backend/AudiusBackend.ts
Was previously trying to fetch the balance treating the wallet address as an eth wallet. Use solana methods instead.
local web prod
> Fix connected wallet wAUDIO balance fetching

- pkg/orchestration/docker.go
adds redis volume from audius-docker-compose to audius-d
> add redis volume to audius-d

- packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
Reverting 
https://github.com/AudiusProject/audius-protocol/pull/10683/files#diff-cf85d0df29e179238abd9166437df9546cfe14cac447278e84ff7be780c55e5dL178-L186
Fixes premium modal footer showing guest checkout state.
> Fix premium modal footer for signed in users

- pkg/orchestration/docker.go
> fix go linter

- packages/common/src/services/remote-config/feature-flags.ts
- packages/web/src/components/track/mobile/TrackTile.tsx
- packages/web/src/pages/sign-up-page/hooks/useFastReferral.ts
- packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
- packages/web/src/pages/sign-up-page/pages/LoadingAccountPage.tsx
- packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx
- packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
- packages/web/src/pages/sign-up-page/pages/SelectGenresPage.tsx
- packages/web/src/pages/sign-up-page/utils/useDetermineAllowedRoutes.ts
Gates fast referral behind feature flag so we can selectively turn on/off
> Feature flag fast referral signup

- packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/claimableReward.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/claimableReward.ts
- packages/web/src/pages/sign-on-page/SignOnPage.tsx
Adds guest mode UI to claim rewards email:
- Updates header for case where guest account doesn't have handle
- Adds "Complete Account & Claim Rewards" button that links to sign up and has a "routeOnCompletion" param that sends the user to the audio page after signup
> [C-5519, C-5521] Add guest mode UI in claim rewards email

- packages/common/src/models/Analytics.ts
- packages/web/src/common/store/pages/signon/sagas.ts
- packages/web/src/common/store/upload/sagas.ts
- packages/web/src/store/analytics/sagas.ts
- packages/web/src/store/errors/sagas.ts
Just some things I found needing improvement
> Misc client analytics tweaks

- packages/common/src/hooks/purchaseContent/usePurchaseContentFormConfiguration.ts
- packages/common/src/store/account/sagas.ts
- packages/common/src/store/purchase-content/sagas.ts
- packages/identity-service/src/authMiddleware.js
- packages/web/package.json
- packages/web/src/components/nav/desktop/AccountDetails.tsx
- packages/web/src/components/nav/desktop/LeftNav.tsx
- packages/web/src/components/premium-content-purchase-modal/pages/GuestCheckoutPage.tsx
Various improvements:
* Mark isGuest false when account is completed
* Smoothly sync changes when email is submit without left nav disappearing.
* Don't favorite on guest purchases
Ran guest checkout and profile completion against stage and identity stage
> [C-5524] Sync account details when guest account is created

- .circleci/src/jobs/@audiusd-jobs.yml
- .circleci/src/workflows/audiusd.yml
- .circleci/src/workflows/core.yml
- pkg/conf/override.go
Add audius-ctl config ports to audiusd env
CI
> Fix audiusd ci

- packages/web/src/pages/private-key-exporter-page/AdvancedWalletDetails.tsx
- packages/web/src/services/audius-backend/BuyAudio.ts
- packages/web/src/services/solana/solana.ts
Getting rid of a few extra libs references related to solana stuff that was missed in previous PRs.
Local client against staging
> Remove a few miscellaneous libs references

- .circleci/src/jobs/@audiusd-jobs.yml
- .circleci/src/workflows/audiusd.yml
- pkg/conf/override.go
Fix audiusd ci workflow deps
self-hosted server for audiusd build
> More CI fixes for audiusd

- .circleci/src/jobs/@audiusd-jobs.yml
- .circleci/src/workflows/audiusd.yml
- Makefile
- cmd/audiusd/Dockerfile
- cmd/audiusd/Dockerfile.cpp
Splits cpp part of build into its own dockerfile since it almost never needs rebuilding. Also uses self-hosted circleci server for docker build to take advantage of cache.
CI
> Make audiusd ci build faster

- pkg/core/config/genesis/stage.json
> Bump stage core version

- pkg/core/chain/abci.go
- pkg/core/chain/register_node.go
core panics when duplicate validator updates are found, and some of our stage nodes are reusing the same keys. This might fix that.
Local dev
> Remove duplicate validator updates

- packages/mobile/ios/Podfile.lock
- packages/mobile/src/components/navigation-container/NavigationContainer.tsx
- packages/mobile/src/screens/app-drawer-screen/AppDrawerScreen.tsx
- packages/mobile/src/screens/root-screen/RootScreen.tsx
- packages/mobile/src/screens/sign-on-screen/SignOnStack.tsx
- packages/mobile/src/screens/sign-on-screen/components/GuestEmailHint.tsx
- packages/mobile/src/screens/sign-on-screen/components/NewEmailField.tsx
- packages/mobile/src/screens/sign-on-screen/screens/CreateEmailScreen.tsx
- packages/mobile/src/screens/sign-on-screen/screens/CreateLoginDetailsScreen.tsx
- packages/mobile/src/screens/sign-on-screen/screens/CreatePasswordScreen.tsx
- packages/mobile/src/screens/sign-on-screen/screens/FinishProfileScreen.tsx
- packages/mobile/src/screens/sign-on-screen/screens/PickHandleScreen.tsx
- packages/mobile/src/screens/sign-on-screen/screens/ReviewHandleScreen.tsx
- packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/SelectArtistsScreen.tsx
- packages/mobile/src/screens/sign-on-screen/screens/SelectGenresScreen.tsx
- packages/mobile/src/screens/sign-on-screen/screens/SignInScreen.tsx
- packages/mobile/src/screens/sign-on-screen/screens/SignOnScreen.tsx
- packages/mobile/src/screens/sign-on-screen/screens/types.ts
- packages/mobile/src/screens/sign-on-screen/types.ts
- packages/mobile/src/screens/sign-on-screen/useRoute.ts
- packages/mobile/src/screens/sign-on-screen/utils/useTrackScreen.ts
- packages/web/src/pages/sign-on-page/SignOnPage.tsx
Adds sign-on deep links for mobile:
1. handle signin route deeplink
2. handle signup route deeplink
3. handle guestEmail param by autofilling guest email and running validation to prove it's a guest email.
5. handle all deep links for logged out users by redirecting to deep link after sign up
6. Refactors guest email hint to be used in sign-in and sign-up.
> [C-5522] Add mobile sign up deep links

- packages/identity-service/src/routes/notificationSettings.js
Add back routes removed in https://github.com/AudiusProject/audius-protocol/pull/10531/files# that are still needed
Tested on staging
> Add back notification settings

- packages/common/src/api/tan-query/comments.ts
- packages/common/src/models/ErrorReporting.ts
- packages/common/src/store/pages/chat/sagas.ts
- packages/common/src/store/purchase-content/sagas.ts
Adds tags for comments, chats, and purchase sagas
Still some more left to do in next PR
> [C-5534] Add more feature tags reportToSentry

- packages/web/src/common/store/pages/signon/sagas.ts
> Dedupe welcome email

- packages/mobile/src/components/collectible-details-drawer/CollectibleDetailsDrawer.tsx
- packages/mobile/src/components/drawer/DrawerHeader.tsx
Fix issue where in the collectibles drawer the close button wasn't pressable because it was occluded by the image. Also increase hitSlop for button
> [PAY-3700] Improve drawer close button

- packages/mobile/src/screens/settings-screen/NotificationSettingsScreen.tsx
Add scroll view because we never had one!
> [PAY-3672] Add scroll view for notifications

- packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/udr.ts
Adds UserType + Price Point column to UDR per updated spec.
Some questions:
* UserType is hardcoded to `Free Trial`.  Not sure if we should try to separate out purchases as separate row and use the `Paid` type there.
* Similarly, `Price Point` will be the track price, but I think that listening to the 30s preview will create listen rows that will have a Price Point even if there is no actual purchase for the track.
If we do want to break out purchases as separate rows, probably will make sense to add a separate query from the `usdc_purchases` table and UNION ALL it with the existing query.
> Add UserType + Price Point column to UDR

- packages/web/src/pages/upload-page/forms/UploadTrackForm.tsx
Update upload form submit value to respect updated file from file replace
Manually tested on web
> [C-5500] Fix upload flow track replace

- packages/web/src/pages/collection-page/components/desktop/CollectionPage.module.css
Spacing on the divider was off. Fix it
Local web
> [PAY-3671] Fix divider spacing before 'Add some tracks'

- packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx
> [PAY-3664] Avoid showing green buy btn when insufficient balance

- packages/discovery-provider/ddl/data/0109_stage_one_shot/stage_one_shot.csv
- packages/discovery-provider/ddl/migrations/0109_stage_one_shot.sql
Testing out one shot migration on stage. Based off this backfill migration https://github.com/AudiusProject/audius-protocol/pull/8768 and AUDIO match.
Ran successfully on sandbox and created 
```
"challenge_id","user_id","specifier","is_complete","current_step_count","completed_blocknumber","amount","created_at","completed_at"
"o",176022,"2af96:1",TRUE,0,86936986,42,"2024-12-17 23:21:31.002605+00","2024-12-17 23:21:31.002605"
"o",54432,"d4a0:1",TRUE,0,86936986,100,"2024-12-17 23:21:31.002605+00","2024-12-17 23:21:31.002605"
```
> [PAY-3682] Create stage one shot migration

- packages/web/src/pages/trending-page/components/desktop/TrendingPageContent.tsx
- packages/web/src/pages/trending-page/components/mobile/TrendingPageContent.tsx
Key doesn't take into account genre and should
Local web + mobile web
> [PAY-3654] Fix trending image flashing

- packages/common/src/services/audius-backend/AudiusBackend.ts
Just getting rid of some libs references in unused backend functions.
Typecheck and code search for usages only.
> Remove some unused things in audiusBackend

- package.json
- packages/mobile/ios/Podfile.lock
- packages/mobile/package.json
My attempt to fix CI being weird on main ... I was seeing this error trying to repro locally 
https://github.com/software-mansion/react-native-screens/issues/2108
and upgrading react-native-svg fixes it
> Fix local turbo by upgrading react-native-svg

- cmd/core/main.go
- pkg/core/server/abci.go
- pkg/core/server/grpc.go
- pkg/core/server/mempool.go
- pkg/core/server/registry_bridge.go
> Fix panic on empty public key

- packages/common/src/services/audius-backend/solana.ts
- packages/common/src/store/buy-usdc/sagas.ts
> Migrate createTransferToUserBankTransaction to SDK

- packages/common/src/hooks/useGeneratePlaylistArtwork.ts
- packages/common/src/utils/updatePlaylistArtwork.ts
- packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts
- packages/web/src/common/store/cache/collections/commonSagas.ts
Remove libs/audius backend from addTrackToPlaylist
Locally added a bunch of tracks to a playlist on staging and reordered, sorted, etc.
> Use sdk for metadata time on addTrackToPlaylist

- .changeset/tiny-mangos-cough.md
- packages/common/package.json
- packages/common/src/services/wallet-client/WalletClient.ts
- packages/eth/src/audius-wormhole/audiusWormhole.ts
- packages/sdk/src/sdk/services/Ethereum/contracts/AudiusToken/AudiusTokenClient.ts
- packages/sdk/src/sdk/services/Ethereum/contracts/AudiusWormhole/AudiusWormholeClient.ts
- packages/web/src/services/audius-sdk/audiusSdk.ts
Sent AUDIO successfully to the Wormhole.
TODO: Get AUDIO out of Wormhole
> Fix Wormhole contract typehash and deadline, fix RPC request signature

- packages/web/src/utils/Moods.tsx
> [QA-1892] Fix aggressive emoji

- packages/discovery-provider/plugins/pedalboard/apps/mri/README.md
- packages/discovery-provider/plugins/pedalboard/apps/mri/src/config.ts
- packages/discovery-provider/plugins/pedalboard/apps/mri/src/index.ts
- packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/clm.ts
- packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/mrvr.ts
- packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/udr.ts
- packages/discovery-provider/plugins/pedalboard/apps/mri/src/s3.ts
- packages/discovery-provider/plugins/pedalboard/apps/mri/src/server.ts
Removes affirmative report, and adds columns to CBS report for the combined MRVR.
Second commit contains the actual column changes.
> Combined MRVR report

- packages/web/src/app/App.tsx
Removes test pages for now which where leading to issues
> Remove react query test pages

- pkg/core/config/genesis/stage.json
> Bump stage chain to 16

- packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/rewards.ts
Oops on the in/of issue lol. Otherwise working well, minus some env config.
Ran, and posted results correctly.
> Fix trending rewards bugs: s/in/of and add log

- packages/web/src/hooks/useLocalStorage.ts
> [PAY-3733] Fix localStorage set

- pkg/core/config/genesis/stage.json
- pkg/core/config/setup.go
> rm stage dn3 from genesis and use the same connection settings for all nodes

- pkg/mediorum/mediorum.go
- pkg/mediorum/server/server.go
> use correct host for audiusd grpc

- packages/discovery-provider/ddl/migrations/0110_stage_core_cutover.sql
> fix stage migration

- packages/dotenv-linter/package.json
The error is a bit difficult to parse, but i believe this should help
> Fix dotenv-linter build script

- packages/sdk/src/sdk/api/users/types.ts
Make `associatedWallets` and `associatedSolWallets` nullable
> [PAY-3660] Fix associated wallets zod error

- packages/common/src/api/tan-query/useCollection.ts
- packages/common/src/api/tan-query/useCollections.ts
- packages/common/src/api/tan-query/useTrack.ts
- packages/common/src/api/tan-query/useTracks.ts
- packages/common/src/api/tan-query/useUser.ts
- packages/common/src/api/tan-query/useUsers.ts
- packages/common/src/audius-query/createApi.ts
- packages/common/src/store/cache/reducer.ts
- packages/common/src/store/cache/syncWithReactQuery.ts
- packages/common/src/store/cache/types.ts
- packages/web/src/utils/route/userRouteParser.ts
Fixes issues with addEntries types. Went ahead and reverted the change introduced in the cache-sync pr, but updated the types to be correct moving forward
> [QA-1894] Fix addEntries metadata types

- dev-tools/compose/docker-compose.legacy.dev.yml
- dev-tools/compose/docker-compose.legacy.prod.yml
> add custom legacy profile to core and mediorum

- packages/discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts
> only relay em in dev

- packages/ddex/entrypoint/src/App.tsx
- packages/ddex/entrypoint/src/distributors/prod.json
> Add DashGo

- packages/mobile/src/components/fields/PickArtworkField.tsx
- packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
Small fix to make sure that the artwork is visible on the upload form. It was hidden on edit to try to fix another image related issue
> Small fix to mobile edit trackform to show artwork on upload

- packages/sdk/src/sdk/services/AudiusWalletClient/createHedgehogWalletClient.ts
- packages/web/src/services/audius-sdk/audiusSdk.ts
> Use custom error

- packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistFolderNavItem.tsx
Not sure when this started showing up, but this fixes the underlying issue where on `main` we can't expand folders.
> [PAY-3739] Fix folder expansion

- packages/web/src/components/track/GatedConditionsPill.tsx
Clicks on gated conditions pill trigger playback, so stop propagation to fix
Local web player
> [PAY-3740] Stop propagation on gated conditions pill

- packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/main.ts
12:05 is too early, I suppose
```
npm run build
npm run start
```
> Update tcr cron

- pkg/mediorum/server/repair.go
> delete resized Qm image variatns.

- packages/web/src/app/AppProviders.tsx
Fixes issue where theme would not persist between refresh due to not setting initial redux state correctly. This was mistakenly dropped
> [C-3613] Fix issue with theme persistence

- packages/common/src/store/pages/explore/types.ts
- packages/mobile/src/screens/explore-screen/ExploreScreen.tsx
- packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
- packages/mobile/src/screens/profile-screen/ProfileTabs/ProfileTabNavigator.tsx
- packages/mobile/src/screens/trending-screen/TrendingScreen.tsx
- packages/web/src/pages/explore-page/components/mobile/ExplorePage.tsx
- packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
Fixes lowercase tabs across web and mobile to use Capcase. Using the Tab enums is kinda slick, so went with that.
> [C-5596] Fix lowercase tabs

- packages/mobile/src/screens/profile-screen/ProfileTabs/CollectiblesTab.tsx
Fixes weird issue where useProxySelector freaks out when trying to edit a track. This may be part of a bigger issue, but i went ahead and cleaned up the implementation anyway and it worked out.
> [QA-1903] Fix collections tab

- .changeset/wicked-sloths-develop.md
- packages/sdk/src/sdk/services/Solana/programs/types.ts
- packages/web/src/components/buy-audio-modal/components/PurchaseQuote.tsx
- packages/web/src/services/audius-backend/BuyAudio.ts
- packages/web/src/services/audius-backend/Jupiter.ts
- packages/web/src/store/application/ui/buy-audio/sagas.ts
PAY-3732
There were several bugs here:
- `buildTransaction` in SDK used `instanceof` to check `TransactionInstruction` and `AddressTableLookupAccount` params, [which breaks if the class is being imported from somewhere else](https://stackoverflow.com/a/75977756).
- Updated this to instead check for custom schemas that represent constructor args, and autotransform to the class that's bundled with the SDK
- The fees were being miscalculated as the existing wallet balance of SOL was being added rather than subtracted. Additionally, the transactions used to calculate fees were different than the actual transactions used in the buy audio purchase.
- Fixed it so the current balance of the wallet is subtracted instead, and simplified the fees calculation to share from the same transaction …
> [PAY-3732] Fix BuyAudio flow with SDK

- packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
- packages/web/src/components/edit-track/EditTrackForm.tsx
Ensures we always reference the initialValue track_id for download
> [C-5627] Fix download track after replace

- packages/discovery-provider/src/queries/get_track_signature.py
Adds feature to download endpoint to allow downloads from track owner regardless of download status
> [C-5547] Fix track download

- packages/common/src/models/Analytics.ts
- packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
- packages/mobile/src/screens/edit-track-screen/components/FileReplaceContainer.tsx
- packages/mobile/src/screens/edit-track-screen/components/ReplaceTrackConfirmationDrawer.tsx
- packages/web/src/components/edit-track/EditTrackForm.tsx
Adds events for previewing, replacing, and downloading for both web and mobile
> [C-5630] Add track replace analytics

- packages/harmony/src/components/button/BaseButton/BaseButton.tsx
- packages/harmony/src/components/button/PlainButton/PlainButton.tsx
- packages/mobile/src/harmony-native/components/Button/BaseButton/BaseButton.tsx
- packages/mobile/src/harmony-native/components/Button/PlainButton/PlainButton.tsx
- packages/mobile/src/screens/edit-track-screen/components/FileReplaceContainer.tsx
- packages/mobile/src/screens/edit-track-screen/components/ReplaceTrackProgressDrawer.tsx
- packages/web/src/components/file-replace-container/FileReplaceContainer.tsx
- packages/web/src/components/replace-track-progress-modal/ReplaceTrackProgressModal.tsx
Handles case where long track file names overflowed edit container.
> [C-5498] Fix track file name overflow

- packages/mobile/src/components/skeletons/EntitySkeleton.tsx
FIxes issue where the mobile entity image skeletons was misaligned, leading to large CLS on load
> [C-5624] Fix entity image skeleton

- packages/web/src/components/edit-track/EditTrackForm.tsx
Small dependency issue i missed that could lead to many unecessary rerenders
> Fix track replace dependencies

- packages/common/src/hooks/useTwitterButtonStatus.ts
- packages/common/src/store/cache/users/actions.ts
- packages/common/src/store/pages/profile/actions.ts
- packages/mobile/src/components/twitter-button/TwitterButton.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
- packages/web/src/common/store/cache/users/sagas.ts
- packages/web/src/common/store/profile/sagas.js
- packages/web/src/components/ai-attribution-modal/SearchBarResult.jsx
- packages/web/src/components/notification/Notification/components/TwitterShareButton.tsx
- packages/web/src/components/twitter-share-button/TwitterShareButton.tsx
- packages/web/src/pages/profile-page/ProfilePageProvider.tsx
We don't need to do any of this social fetching because all users come with the social data with sdk
> [C-5618] Remove social fetching

- packages/discovery-provider/src/tasks/index_core.py
> fix reversed core health check

- packages/web/src/app/AppProviders.tsx
Fixes critical issue where mainContentRef was not set due to missing provider. This is on me
> Fix pagination due to missing main-contont-context-provider

- packages/harmony/src/components/expandable-nav-item/ExpandableNavItem.tsx
- packages/harmony/src/components/expandable-nav-item/types.ts
- packages/harmony/src/components/nav-item/NavItem.tsx
- packages/harmony/src/components/notification-count/NotificationCount.tsx
- packages/harmony/src/components/notification-count/types.ts
- packages/web/src/components/nav/desktop/LeftNav.tsx
- packages/web/src/components/nav/desktop/useNavConfig.tsx
- packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
This PR introduces several improvements to the navigation system and rewards UI, focusing on better visual feedback, accessibility, and user experience.
- Added `canUnfurl` prop to `ExpandableNavItem` to control whether items can be expanded
- Improved hover states with consistent border styling
- Fixed icon size shifting by standardizing icon container dimensions
- Refactored icon rendering logic for better maintainability
- Added support for multiple size variants ('s' and 'm')
- Introduced `hasBorder` prop for flexible styling
- Improved positioning and dimensions calculation
- Fixed hover state styling inconsistencies
- Replaced `undisbursedUserChallenges` with `useChallengeCooldownSchedule` hook for better rewards tracking
- Updated notification count to show claimable amount instead …
> [PAY-3765][PAY-3761][PAY-3759][PAY-3757][PAY-3756][PAY-3755] Address navbar comments

- packages/web/src/store/reload/sagas.ts
We should not refresh if you're doing something important
Added logs to verify state
> [QA-1907] Refresh only if not playing/uploading

- packages/discovery-provider/scripts/start.sh
- packages/discovery-provider/src/app.py
- packages/discovery-provider/src/tasks/index_core.py
> add index_core celery queue

- packages/discovery-provider/nginx_conf/nginx_container.conf
Pass args to plugins, which currently don't get them
Not fully tested, but will confirm on stage
> Pass args to plugins

- packages/discovery-provider/src/tasks/index_core_plays.py
removes some logs and fixes the missing slot on the return, unsure why this worked in local dev
> fix next_slot

- .circleci/src/workflows/release.yml
> rm mediorum in releases

- packages/common/src/store/pages/chat/sagas.ts
This reverts commit dc64fb87ed4b24672ebe625a8f912811966ddde5.
This logic was a temp fix to always mark a chat as read no matter what. the underlying issue should be fixed and we can remove the logic now.
tested on local web stage
> [PAY-3593] Revert "[PAY-3592] Always mark chat as read (temp fix) (#10397)"

- .circleci/src/workflows/discovery.yml
> rm unused plugins from ci

- .circleci/src/workflows/release.yml
> Add missing plugin build

- .circleci/src/commands/@docker-commands.yml
> rm mediorum from docker tag

- .circleci/src/commands/@docker-commands.yml
- .circleci/src/workflows/release.yml
> Remove sla-auditor from ci

- packages/web/src/common/store/cache/collections/commonSagas.ts
- packages/web/src/components/edit-track/EditTrackForm.tsx
- packages/web/src/components/upload/UploadArtwork.module.css
* Updating playlist & track artwork broken in sdk migration
* Spinner broken in lottie upgrade
local stage
> Fix updating playlist/track artwork

- packages/common/src/schemas/metadata.ts
> Default private playlist

- packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/mrvr.ts
Start with country list, left join sales for MRVR.
> MRVR: start from country list

- monitoring/vector/vector.toml
Capture audiusd container logs
> Add audiusd container to vector log capture

- packages/web/src/components/track/GatedContentSection.tsx
- packages/web/src/pages/sign-in-page/ConfirmEmailPage.tsx
- packages/web/src/pages/sign-up-page/pages/CreateEmailPage.tsx
Fixes OTP padding
Fixes mobile-web gated-content-section layout
> [C-5557 C-5554] Guest checkout ui fixes

- packages/mobile/src/components/top-tab-bar/CollapsibleTopTabNavigator.tsx
Add some margin to the top of the tab icon to conform with the design
> [C-5655] Fix the margin on the mobile profile screen tabs

- packages/mobile/android/app/build.gradle
Need to upgrade to fix:
https://github.com/vantuan88291/react-native-ota-hot-update/issues/10
release-client-v1.5.116
> Bump android to 1.1.462

- package-lock.json
- packages/web/package.json
- packages/web/src/components/coinflow-onramp-modal/CoinflowOnrampModal.tsx
- packages/web/src/components/withdraw-usdc-modal/components/CoinflowWithdrawModal.tsx
Doing the web update separately because mobile will need a little more love and want to make these separately revertable.
Needs to be tested on a subdomain to do the full flow. I spun up the production web build and tested an end-to-end purchase with Coinflow. Did not observe any issues.
> [PAY-3694] Update coinflow on web

- packages/mobile/src/screens/audio-screen/AudioScreen.tsx
- packages/mobile/src/screens/rewards-screen/ChallengeRewardsTile.tsx
- packages/mobile/src/screens/rewards-screen/ClaimAllRewardsTile.tsx
- packages/mobile/src/screens/rewards-screen/RewardsScreen.tsx
Fix minor padding issue + rename component
> Rename to ClaimAllRewardsTile + fix padding

- packages/common/src/api/suggestedTracks.ts
- packages/common/src/api/tan-query/useAudioTransactions.ts
- packages/common/src/api/tan-query/useFollowers.ts
- packages/common/src/api/tan-query/usePurchases.ts
- packages/common/src/api/tan-query/useSales.ts
- packages/common/src/api/tan-query/useTopArtistsInGenre.ts
- packages/common/src/api/tan-query/useTrending.ts
- packages/common/src/hooks/chats/useAudienceUsers.ts
- packages/mobile/src/components/comments/CommentDrawer.tsx
- packages/mobile/src/screens/user-list-screen/UserListV2.tsx
- packages/web/src/components/composer-input/components/UserMentionAutocompleteText.tsx
- packages/web/src/components/user-list-modal/components/lists/FollowersUserList.tsx
- packages/web/src/pages/audio-transactions-page/AudioWalletTransactions.tsx
- packages/web/src/pages/pay-and-earn-page/components/PurchasesTab.tsx
- packages/web/src/pages/pay-and-earn-page/components/SalesTab.tsx
- packages/web/src/pages/pay-and-earn-page/desktop/PayAndEarnPage.tsx
- packages/web/src/pages/pay-and-earn-page/mobile/PayAndEarnPage.tsx
- useInfiniteQuery hooks just return the query results
- move from `loadMore -> fetchNextPage` `hasMore -> hasNextPage`, etc.
Note: Not going infinitely deep here. We can change more props across components when we're ready
> [C-5657] Adopt standard useInfiniteQuery props

- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/web/src/common/store/player/sagas.ts
Fix unauthenticated playback and safeguard the signData method in audiusbackend when no wallet is present. Add a sentry alert.
Unauthed playback working
> Fix playback in unauthenticated state

- packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/requestManager.ts
> Upgrade year in discovery notif tests

- package-lock.json
- packages/mobile/package.json
- packages/mobile/src/components/coinflow-onramp-drawer/CoinflowOnrampDrawer.tsx
This PR depends on #11026 being merged first.
Updates to the latest coinflowlabs/react-native on mobile. Only change required on our side is updating how we pass the amount.
Needs to be tested on RC, unfortunately. But making sure a track purchase with CC works correctly is sufficient.
> [PAY-3801] Update coinflow on mobile

- packages/harmony/src/components/expandable-nav-item/ExpandableNavItem.tsx
- packages/harmony/src/components/expandable-nav-item/types.ts
- packages/web/src/components/nav/desktop/PlaylistLibrary/CreatePlaylistLibraryItemButton.tsx
- packages/web/src/components/nav/desktop/RestrictedExpandableNavItem.tsx
- Independent hover/active states for left/main side of ExpandableNavItem, and rightIcon
- right icon `color='default'` when active/hovered
Logged-out state is also working
https://github.com/user-attachments/assets/95e6b0b6-c0e9-42b3-b6fb-82c6096a4a55
https://github.com/user-attachments/assets/ef22984f-ffb0-4645-820a-42a1686c68f4
> [PAY-3803] Fix web nav item hover/active states

- packages/common/src/models/Analytics.ts
- packages/web/src/components/nav/desktop/LeftNavLink.tsx
Adds analytics on nav item clicks
> Add analytics on nav link clicks

- packages/web/src/components/nav/desktop/NavHeader.tsx
Conditionally render dashboard button
> [QA-1917] Conditional render for dashboard button

- packages/sdk/src/sdk/api/tracks/TracksApi.ts
> Add missing query params

- packages/common/src/utils/challenges.ts
- packages/mobile/src/components/challenge-rewards-drawer/ChallengeDescription.tsx
- packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerContent.tsx
- packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
- packages/mobile/src/screens/rewards-screen/Panel.tsx
Mobile changes to match this https://github.com/AudiusProject/audius-protocol/pull/10788
and cleaning up my mess.
Made sure values look correct for ineligible and eligible users.
> Mobile one shot UI

- packages/discovery-provider/ddl/data/0109_stage_one_shot/stage_one_shot.csv
- packages/discovery-provider/ddl/migrations/0109_stage_one_shot.sql
> Add stage one shot handles for QA

- package-lock.json
- packages/mobile/package.json
Pulling in a patch upgrade to fix some potential iframe issues.
N/A. Should be a no-op on our end, will verify functionality in RC.
> [PAY-3822] Update coinflowlabs/react-native to 4.0.1

- packages/sdk/src/sdk/services/EntityManager/EntityManagerClient.ts
Add entity manager decode method
> Add entity manager decode method

- docs/docs/developers/guides/create-audius-app.mdx
> Fix typo on create-audius-app docs

- packages/discovery-provider/src/api/v1/models/users.py
- packages/discovery-provider/src/queries/download_csv.py
- packages/sdk/src/sdk/api/generated/default/models/SaleJson.ts
Need this to check which key to decrypt emails with with on the FE
> Add 'is_initial' to json response

- packages/web/src/services/audius-sdk/auth.ts
Moves checking the connected wallet address against local storage before waiting for wallet to connect so that users using Hedgehog but having installed wallets don't see any delay initializing SDK.
Prior to this change, wagmi would sense the wallets and wait for them to connect before determining whether to use them as the auth wallet. Notably, wagmi has the account information available prior to connecting if you've connected before, which you would have if you clicked "Sign in with MetaMask", so we can simply use that check first to ensure we don't wait erroneously.
An alternative here would be to check for existence of Hedgehog in localstorage but that's about the same.
> Fix delay loading SDK when users have wallets installed

- packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/AudioMatchingRewardsModalContent.tsx
> Fix web audio matching challenge modal alignment

- packages/web/src/app/web-player/WebPlayer.jsx
- packages/web/src/components/banner/TanQueryFeedbackBanner.tsx
> (Tan-query) Add a feedback banner

- .circleci/config.yml
> Add integration test to main workflow

- packages/web/src/services/audio-player/AudioPlayer.ts
Fixes interesting issue where multiple audius tabs can both play at the same time. Now whichever tab is active gets priority.
This callout was based on comment on discord!
> [C-5592] Prevent multiple tabs from playing audio

- .circleci/src/workflows/protocol-dashboard.yml
Fix protocol dashboard deploy 
Used to deploy current prod and then removed the rj- prefix from deploy branches
> Fix misc protocol dashboard deploy issues

- packages/sdk/src/sdk/api/notifications/NotificationsApi.ts
Fixes issue where playlist-seen was not being indexed, due to malformed EntityType and Action
> [QA-1943] Fix playlist seen

- packages/web/src/components/search-bar/SearchBarResult.module.css
Fixes issue where search-bar hover text color is incorrect
https://github.com/user-attachments/assets/7681829d-95e5-4fc4-8603-df30eb3615df
> [QA-1937] Fix search bar hover text

- .changeset/swift-bears-judge.md
- monitoring/healthz/src/pages/Nodes.tsx
- packages/sdk/src/sdk/config/production.ts
- packages/sdk/src/sdk/scripts/generateServicesConfig.ts
Update healthz
Update bootstrap sdk config
```
npm run sdk:config
```
and then ran prod client
```
```
> Migrate dn2.monophonic to new architecture

- packages/web/src/components/dev-mode-manager/DevModeManager.tsx
- packages/web/src/hooks/useDevModeHotkey.ts
Just clear up the local state so this doesn't show for existing users on prod.
Figured to do this first before nuking it in that env
> Update dev mode local storage value

- packages/common/src/models/Analytics.ts
- packages/common/src/store/purchase-content/sagas.ts
- packages/web/src/common/store/pages/signon/sagas.ts
A few metrics that will help produce clearer charts for guest checkout.
Verified metrics on stage.
> Add guest checkout metrics

- packages/web/src/common/store/cache/collections/commonSagas.ts
- packages/web/src/common/store/cache/collections/createAlbumSaga.ts
QA-1950
Fixes editing of playlists when created in the same session.
Tested manually locally against dev env on chrome
> [QA-1950] Fix album edits

- .changeset/rude-bees-bathe.md
> Retrigger harmony release

- .changeset/rude-bees-bathe.md
- .github/workflows/publish-packages.yml
Add .changesets to filter to trigger build. Modified one of the changesets again
> Add changesets to publish-packages filter

- .github/workflows/publish-packages.yml
Fixes publish-package include from changsets to changeset
> Fix publish-package changeset include

- packages/discovery-provider/src/api/v1/helpers.py
Response should be None to be less misleading
```
cd packages/sdk
npm run gen:dev
```
> [PAY-3837] Fix response for missing cover art/photo

- package-lock.json
- packages/mobile/ios/Podfile.lock
- packages/mobile/package.json
- packages/mobile/patches/react-native-tiktok+1.1.1.patch
- packages/mobile/patches/react-native-tiktok+1.1.2.patch
Reintroduces react-native-tiktok patch file for 1.1.2, since 1.1.1 still not available
> Reintroduce react-native-tiktok patch file

- packages/discovery-provider/src/challenges/listen_streak_endless_challenge.py
Should hex-ify user id in challenge specifier
integration tests
> Use hex in endless listen streak specifier

- .changeset/young-teachers-tap.md
- packages/sdk/src/sdk/api/playlists/PlaylistsApi.ts
Re-land https://github.com/AudiusProject/audius-protocol/pull/11103
Needs to wait until all DNs include https://github.com/AudiusProject/audius-protocol/pull/11091/commits/f2ede43fdf58850b4256178db9aad0c29a6f07c6
N/A
> [PAY-3398] Use new playlist contents format

- packages/web/src/components/alt-button/FavoriteButton.module.css
Updated the size to 24px to match the other icons
> [QA-1966] Update track tile heart icon to 24px

- .circleci/src/workflows/discovery.yml
- dev-tools/compose/docker-compose.discovery.dev.yml
- dev-tools/compose/docker-compose.test.yml
> Make pushing DN images into one single job instead of 10

- packages/common/src/api/tan-query/useTrackHistory.ts
- packages/common/src/api/tan-query/utils/primeCollectionData.ts
- packages/common/src/api/tan-query/utils/primeTrackData.ts
- packages/common/src/api/tan-query/utils/primeUserData.ts
- packages/web/src/components/skeleton/Skeleton.module.css
- packages/web/src/components/skeleton/Skeleton.tsx
- packages/web/src/components/table/Table.tsx
- packages/web/src/components/tracks-table/TrackTableLineup.tsx
Adds to improvements to history table preformance:
- Skips react-query cache priming
- Adds no-shimmer to skeletons
> Improve history table performance

- .circleci/src/jobs/test.yml
Edit the test job so that multiple services can be tested at once.
See also #11240
> Allow testing multiple services at once in CI

- .circleci/src/jobs/push-docker-image.yml
- .circleci/src/jobs/test.yml
#11246 edited the name, not the command, and was for test, not for push image 🤦 
Runs on main, that's the easiest
> Allow multiple services to be pushed at once

- packages/common/src/api/tan-query/useCollection.ts
- packages/common/src/api/tan-query/useCurrentAccount.ts
- packages/common/src/api/tan-query/useLibraryCollections.ts
- packages/common/src/api/tan-query/useLibraryTracks.ts
- packages/common/src/api/tan-query/useTrack.ts
- packages/common/src/api/tan-query/useUser.ts
- packages/common/src/api/tan-query/utils/primeCollectionData.ts
- packages/mobile/src/services/query-client.ts
- packages/web/src/services/query-client.ts
Adds work from https://github.com/AudiusProject/audius-protocol/pull/11244 to main
> [C-5719] Add default cache invalidation behavior (#11244)

- packages/web/src/components/tracks-table/EmptyTable.tsx
- packages/web/src/pages/history-page/components/desktop/HistoryPage.tsx
Fixes issue where empty filter state drops the filter and shows the wrong empty table
> Fix history page filter empty state

- .changeset/quick-rules-tie.md
- packages/sdk/src/sdk/api/challenges/types.ts
Need to get sdk to allow this challenge to be claimed.
> Add 'e' to sdk challenge enum

- packages/sdk/src/sdk/services/Solana/programs/ClaimableTokensClient/ClaimableTokensClient.ts
> Stop adding ComputeBudget limits in ClaimableTokensClient

- dev-tools/compose/docker-compose.yml
Adding some missing env vars needed for core to pick up DN registrations
Confirmed DN registration on local dev
> Fix discovery node registration for core on local dev

- packages/common/src/api/tan-query/comments.ts
> [QA-1972] Fix a bug in the mutate function of the post comment tan-query hook

- packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/AudioMatchingRewardsModalContent.tsx
- packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
- packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ListenStreakChallengeModalContent.tsx
- packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ProgressReward.tsx
> [PAY-3896] Fix large reward amount text getting clipped

- .circleci/src/jobs/@integration-jobs.yml
> Fix for npm run protocol up --prod

- packages/discovery-provider/src/queries/get_challenges.py
Reverts AudiusProject/audius-protocol#11234
> Revert "Return aggregate challenges regardless of completion state"

- packages/mobile/src/components/challenge-rewards-drawer/ChallengeReward.tsx
- packages/mobile/src/components/challenge-rewards-drawer/styles.ts
> [PAY-3911] Center align mobile reward drawer text

- packages/common/src/utils/challenges.ts
- packages/discovery-provider/plugins/notifications/src/email/notifications/components/notifications/Notification.tsx
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/challengeReward.ts
- packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx
Update airdrop month and fix intermittent doubling on progress reward amount. 
Resolves PAY-3931, PAY-3930
Tested against stage and confirmed amounts are correct.
> Change airdrop month and fix progress reward amount

- packages/web/src/pages/rewards-page/components/ChallengeRewards/RewardPanel.tsx
- packages/web/src/pages/rewards-page/components/Tile.module.css
- packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ListenStreakChallengeModalContent.tsx
Local web & mobile web
```
```
> [PAY-3924][PAY-3925] Misc. small rewards page UI fixes

- .circleci/src/workflows/discovery.yml
> rm notifs tests for stage deploy

- packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerContent.tsx
> [PAY-3929] Fix claiming reward button state on mobile

- packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
- packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ProgressDescription.tsx
> [PAY-3899] Fix reward modal padding and claim progress styling on web

- dev-tools/compose/docker-compose.dev-tools.prod.yml
- dev-tools/compose/docker-compose.pedalboard.prod.yml
- packages/commands/Dockerfile.prod
> Add turbo remote caching to solana-relay, verified-notifications, and audius-cmd

- packages/web/src/components/ai-generated-button/AiGeneratedCallout.tsx
- packages/web/src/pages/profile-page/components/desktop/ProfilePictureListTile.tsx
- packages/web/src/pages/profile-page/components/desktop/SupportingList.tsx
- packages/web/src/pages/profile-page/components/desktop/TopSupporters.tsx
Fixes zero state for supporters
Fixes ai-attribute padding
Fixes profile-list cursor
> [C-5765] Profile nav fixes

- packages/common/src/api/tan-query/useCollections.ts
- packages/common/src/api/tan-query/useTracks.ts
- packages/common/src/api/tan-query/useUsers.ts
Fixes issue where bulk fetching entities did not preserve id order
> Fix bulk query fetching order

- packages/web/src/components/nav/mobile/NavBar.module.css
- packages/web/src/components/nav/mobile/NavBar.tsx
> [PAY-3926] Fix mobile-web header notif/reward count positions

- dev-tools/compose/docker-compose.dev-tools.prod.yml
> Fix audius-cmd turbo args

- packages/discovery-provider/src/tasks/entity_manager/entities/user.py
Small update to remove the correct wallets instead of all previous wallets
> Small fix for the associated wallet logic update

- .circleci/src/commands/@mobile-commands.yml
- .circleci/src/jobs/@mobile-jobs.yml
Bump instance sizes because builds timeout
CI on this branch
> Bump android resources for CI

- packages/mobile/android/app/build.gradle
Bumps android version one more time due to two android releases last week
> Bump android version to 468

- packages/harmony/src/icons/Logos.stories.mdx
- packages/web/src/pages/rewards-page/components/ChallengeRewards/ChallengeRewardsTile.tsx
Fixes small lint regressions in harmony and web
> Fix harmony and web lint

- packages/mobile/src/components/drawer/DrawerHeader.tsx
- packages/mobile/src/components/now-playing-drawer/TitleBar.tsx
- packages/mobile/src/harmony-native/components/Button/IconButton/IconButton.tsx
Improves now-playing close arrow hit target, and harmonizes a few things along the way.
> [QA-1768] Improve now playing drawer close arrow

- packages/common/src/services/remote-config/feature-flags.ts
- packages/discovery-provider/plugins/notifications/src/email/notifications/components/notifications/Notification.tsx
- packages/web/src/pages/audio-page/AudioPage.tsx
- packages/web/src/pages/rewards-page/components/ChallengeRewards/ChallengeRewardsTile.tsx
Adds feature flag on claim all button and updates airdrop notif copy.
> Feature flag on claim all button

- packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerContent.tsx
> Ineligible oneshot instead of incomplete on mobile

- packages/discovery-provider/src/queries/get_health.py
> filter chain health on these nodes

- packages/discovery-provider/src/queries/get_health.py
Reverts AudiusProject/audius-protocol#11354
> Revert "filter chain health on these nodes"

- packages/common/src/messages/comments.ts
- packages/harmony/src/components/button/IconButton/IconButton.tsx
- packages/harmony/src/components/icon-text/IconText.tsx
- packages/harmony/src/components/send-icon/SendIcon.tsx
- packages/mobile/src/components/comments/CommentBlock.tsx
- packages/mobile/src/components/comments/CommentPreview.tsx
- packages/mobile/src/harmony-native/components/IconText/IconText.tsx
- packages/web/src/components/comments/CommentActionBar.tsx
- packages/web/src/components/comments/CommentBlock.tsx
- packages/web/src/components/comments/NoComments.tsx
- packages/web/src/components/data-entry/TextAreaV2.module.css
- packages/web/src/components/data-entry/TextAreaV2.tsx
- packages/web/src/components/link/UserLink.tsx
Improves various comment layout values based on feedback and figma
> [C-5270 C-5269 C-5268 C-5629] Comment layout improvements

- .changeset/honest-swans-share.md
- packages/harmony/src/components/button/IconButton/IconButton.tsx
- packages/web/src/components/nav/desktop/NavHeaderButton.tsx
Adds isActive state for icon-buttons
Adds activeColor state for icon-buttons, making this requirement much easier to configure
> [C-1984] Improve left-nav buttons with IconButton improvements

- packages/common/src/api/tan-query/useCollectionFavorites.ts
- packages/common/src/api/tan-query/useCollectionReposts.ts
- packages/common/src/api/tan-query/useFollowers.ts
- packages/common/src/api/tan-query/useFollowing.ts
- packages/common/src/api/tan-query/useLibraryCollections.ts
- packages/common/src/api/tan-query/useMutualFollowers.ts
- packages/common/src/api/tan-query/usePurchasers.ts
- packages/common/src/api/tan-query/useRelatedArtists.ts
- packages/common/src/api/tan-query/useRemixers.ts
- packages/common/src/api/tan-query/useTopArtistsInGenre.ts
- packages/common/src/api/tan-query/useTrackFavorites.ts
- packages/common/src/api/tan-query/useTrackReposts.ts
Fixes infinite query return args to include "fetchMore" etc. We may want to consider merging status's, but can do that later
> Fix infinite query return args

- packages/common/src/api/tan-query/useUserCollectibles.ts
Clicking the "Complete Upload" button would cause a full screen error to occur. This happened because we were returning undefined from a `queryFn` 
`npm run web:dev`
- Go to upload a song
- Click the "Complete Upload" button
- Ensure that page navigation works
> Fix "Complete Upload" crash

- packages/common/src/api/tan-query/useTopTags.ts
Page was crashing on dev if the request failed. Adding empty array on failure
`npm run web:dev`
- Create a new account
- Navigate to profile page
- Ensure that page does not do full screen crash
> Fix top tracks

- packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx
Continuation of this https://github.com/AudiusProject/audius-protocol/pull/11379 but for mobile
> Add mobile notification for endless streak

- packages/mobile/src/screens/notifications-screen/Notification/NotificationHeader.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/ListenStreakReminderNotification.tsx
> [PAY-3949] Add fire emoji to notification 

- packages/mobile/src/components/challenge-rewards-drawer/ListenStreakEndlessChallengeDrawerContent.tsx
- packages/mobile/src/screens/rewards-screen/Panel.tsx
> Fix text clipping for rewards text

- packages/discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/listenStreakReminder.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/mapNotifications.ts
- packages/discovery-provider/plugins/notifications/src/remoteConfig.ts
- packages/discovery-provider/plugins/notifications/src/types/notifications.ts
> Listen streak push notification

- packages/sdk/src/sdk/services/StorageNodeSelector/StorageNodeSelector.test.ts
- packages/sdk/src/sdk/services/StorageNodeSelector/getNStorageNodes.ts
* Skips full nodes
* Skips nodes with slow transcode times (> 3 minutes)
Uses fields from: https://github.com/AudiusProject/audiusd/pull/60
But will still work if those fields are absent.
> upload: skip nodes that are full or slow to transcode.

- packages/common/src/hooks/purchaseContent/useChallengeCooldownSchedule.ts
- packages/common/src/services/remote-config/feature-flags.ts
- packages/mobile/src/screens/rewards-screen/ChallengeRewardsTile.tsx
- packages/web/src/common/store/notifications/fetchNotifications.ts
- packages/web/src/components/banner/AirdropAppBanner.tsx
- packages/web/src/pages/rewards-page/components/ChallengeRewards/ChallengeRewardsTile.tsx
> Remove one shot and listen streak feature flags

- packages/discovery-provider/src/challenges/listen_streak_endless_challenge.py
Lower stage listen streak value for easier testing
> Lower stage listen streak 

- package-lock.json
- package.json
- packages/libs/package.json
https://github.com/indutny/elliptic/security/advisories/GHSA-vjh7-7g9h-fjfh
> Upgrade elliptic package to 6.6.1

- packages/discovery-provider/src/queries/search_es.py
Problem:
- Searching "noah m" results in no noah matches near the top, and noahmusic123 is totally missing
Solution:
- Added a cross-fields match with "AND" operator
- Give a moderate boost (0.5x query length) to not overshadow the original algorithm
> [C-5128] Improve cross-fields match in user search

- packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/OneShotChallengeModalContent.tsx
- packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/challengeContentRegistry.ts
- packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/types.ts
Custom component so we can modify the reward amount
> Custom component for web oneshot challenge

- packages/web/src/pages/comment-history/components/desktop/CommentHistoryPage.tsx
> [C-5796] Add empty state for comment history

- packages/common/src/services/remote-config/feature-flags.ts
- packages/common/src/utils/constants.ts
- packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeader/ExpandHeaderToggleButton.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileInfoTiles.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileTierTile.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeader/SocialLink.tsx
- packages/mobile/src/screens/user-list-screen/TopSupportersScreen.tsx
- packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
- packages/web/src/pages/profile-page/components/desktop/RecentComments.tsx
- packages/web/src/pages/profile-page/components/desktop/SupportingList.tsx
- packages/web/src/utils/route.ts
Includes web and mobile together
* Added a feature flag for recent comments
* Added sidebar item on web
* Added profile tile on mobile
* Various cleanup related to layout and mock mismatching
Tested local web and simulator against staging on accounts with and without comments to verify it matches the mocks.
> [C-5780][C-5781][C-5793] Adds recent comments section to profile page/screen

- packages/mobile/src/screens/notifications-screen/Notifications/ListenStreakReminderNotification.tsx
We already log this on web but forgot to log it on mobile.
> [PAY-3940] Listen streak reminder mobile notif analytics

- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/listen.ts
Reverts AudiusProject/audius-protocol#11125
> Revert "shutoff sol relay for plays"

- packages/discovery-provider/integration_tests/challenges/test_audio_matching_challenges.py
- packages/discovery-provider/src/challenges/audio_matching_challenge.py
Updated audio match logic to just use `update_user_challenges`
`npm run web:dev`
> Update audio match logic

- packages/discovery-provider/integration_tests/queries/test_get_total_plays.py
- packages/discovery-provider/src/api/v1/metrics.py
- packages/discovery-provider/src/api/v1/models/metrics.py
- packages/discovery-provider/src/queries/get_total_plays.py
Add endpoint to get total count of plays
```
curl http://audius-protocol-discovery-provider-1/v1/metrics/total_plays
```
```
{
data: {
total: 0
}
}
```
> Add total plays endpoint

- package-lock.json
- packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/package.json
> Fix aao plugin build

- .changeset/empty-gorillas-lie.md
- packages/create-audius-app/examples/react-hono/package.json
- packages/create-audius-app/examples/react-hono/vite.config.ts
- packages/create-audius-app/examples/react/package.json
- packages/create-audius-app/examples/react/vite.config.ts
Need to use https://www.npmjs.com/package/esbuild-plugin-react-virtualized to support react-virtualized
Also set explicit versions
```
npm run dev
``` 
in react and react-hono
> Fix create-audius-app with latest harmony

- packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/AudioMatchingRewardsModalContent.tsx
- packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/DefaultChallengeContent.tsx
- packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ListenStreakChallengeModalContent.tsx
Got burned by the AI refactor. Needed to pass in undisbursedChallenges + claimStatus.
Think mobile is good on this front as specifiers are making it to the saga
Tested on local web prod
> Fix challenge claiming on web

- packages/discovery-provider/src/challenges/challenges.dev.json
- packages/discovery-provider/src/challenges/challenges.stage.json
Bumped the reward amount for trending track and trending underground 
> Bump trending on dev & stage

- .cursor/rules/challenges.mdc
Added cursor project rule for challenges. This helped me create https://github.com/AudiusProject/audius-protocol/pull/11473
Was in a md file previously, just @ it in Cursor
> Add cursor project rule for challenges

- packages/discovery-provider/nginx_conf/nginx_container.conf
- packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/index.ts
- packages/discovery-provider/src/api_helpers.py
Enables attestations on stage `https://discoveryprovider.staging.audius.co/attestations` 
Successfully claimed on stage with AAO plugin
> Setup AAO plugin routing

- .changeset/famous-buses-teach.md
- packages/sdk/src/sdk/api/users/UsersApi.ts
Keys need to be snake case before passing to entity manager
Testing in progress...
> Fix casing in sdk UpdateProfile

- packages/discovery-provider/src/challenges/challenges.dev.json
- packages/discovery-provider/src/challenges/challenges.stage.json
> No cooldown days on dev/stage for first weekly comment challenge

- packages/discovery-provider/src/api_helpers.py
- packages/discovery-provider/src/gated_content/signature.py
- packages/discovery-provider/src/tasks/index_core.py
- packages/discovery-provider/src/tasks/index_core_side_effects.py
- packages/discovery-provider/src/utils/helpers.py
- adds back the trending calculation from index_nethermind that was missing in index_core
- adds back the delist status indexing from index_nethermind that was missing from index_core
> indexing side effects

- packages/discovery-provider/src/api_helpers.py
- packages/mobile/src/services/env/env.stage.ts
- packages/sdk/src/sdk/config/staging.ts
- packages/sdk/src/sdk/scripts/generateServicesConfig.ts
- packages/sdk/src/sdk/services/AntiAbuseOracle/types.ts
- packages/sdk/src/sdk/services/AntiAbuseOracleSelector/AntiAbuseOracleSelector.ts
- packages/web/src/services/env/env.stage.ts
> Enable stage AAO plugin config

- package-lock.json
- packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/package.json
- packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/actionLog.ts
> Use cross fetch in AAO plugin

- packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsLayout.tsx
- packages/mobile/src/components/challenge-rewards-drawer/ClaimError.tsx
- packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsLayout.tsx
- packages/web/src/pages/rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
Match figma designs + copy updates
> [PAY-3947] Fix challenge error UI

- packages/discovery-provider/src/challenges/challenges.stage.json
- packages/discovery-provider/src/challenges/first_weekly_comment_challenge.py
For QA next week to match prod exactly
Test with QA!
> Make stage first weekly comment backend match prod

- .changeset/four-foxes-beg.md
- packages/sdk/src/sdk/api/generated/full/models/CreatePlaylistNotificationActionData.ts
- packages/sdk/src/sdk/api/generated/full/models/CreateTrackNotificationActionData.ts
Forgot to generate SDK in my last PR and broke CI.
N/A
> Remove unused notification data fields from sdk

- .circleci/src/commands/@docker-commands.yml
- .circleci/src/workflows/discovery.yml
- .circleci/src/workflows/release.yml
- dev-tools/compose/docker-compose.pedalboard.dev.yml
- dev-tools/compose/docker-compose.pedalboard.prod.yml
Renaming to avoid conflicting with legacy AAO docker image
> Rename AAO plugin docker image

- packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/actionLog.ts
- packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/identity.ts
- packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/server.tsx
Add cors and fix some env vars
Running on stage
> Add cors to attestation plugin

- dev-tools/compose/docker-compose.yml
> Fix audius compose up for AAO plugin

- packages/web/src/components/menu/CollectionMenu.tsx
- packages/web/src/components/menu/TrackMenu.tsx
Fixes issue where overflow menu share just copies link and doesn't open share modal. Additionally share was just not working for collections
> [QA-2003] Fix overflow menu share

- packages/discovery-provider/src/tasks/index_core.py
> only update blocks when indexing em

- package-lock.json
- packages/protocol-dashboard/package.json
- packages/protocol-dashboard/src/components/ProfileInfoCard/ProfileInfoCard.tsx
- packages/protocol-dashboard/src/components/Stat/Stat.tsx
- packages/protocol-dashboard/vite.config.ts
- Fixes dashboard stat shadows due to unnecessary Paper wrapping
- Fixes "go to audius" links by unsetting all inner link styles
- Fixes builds due to react-virtualized. Fix for this in a another pr
> [QA-1999] Fix dashboard shadows and link styles

- packages/discovery-provider/src/api/v1/helpers.py
- packages/discovery-provider/src/api/v1/playlists.py
- packages/discovery-provider/src/api/v1/tracks.py
- packages/discovery-provider/src/api/v1/users.py
- packages/sdk/src/sdk/api/generated/default/apis/PlaylistsApi.ts
- packages/sdk/src/sdk/api/generated/default/apis/TracksApi.ts
- packages/sdk/src/sdk/api/generated/default/apis/UsersApi.ts
Add limit offset to user / track / playlist search endpoints.
> Search pagination

- packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/main.ts
want to buffer a few minutes here given that this has been a bit glitchy last couple of weeks
> Move trending job to 12:15 pt

- packages/web/src/pages/trending-page/components/RewardsBanner.tsx
> Use paper component

- packages/web/src/pages/trending-page/components/RewardsBanner.tsx
> Add breakpoint on rewards banner

- packages/mobile/android/app/src/main/AndroidManifest.xml
Reverts AudiusProject/audius-protocol#11212
> Revert "[PAY-3865] Don't deeplink on android oauth"

- packages/harmony/src/components/button/IconButton/IconButton.tsx
- packages/web/src/components/nav/desktop/NowPlayingArtworkTile.tsx
Fixes spacing issue and uses new activeColor prop
Drops focus-visible, separate issue but noticed it's not great
> Fix now playing artwork visualizer button

- packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
1. create account
2. upload track
3. delete track
4. view profile
should now see the "Upload a track" chip
> [PAY-3699] Show upload chip if you have deleted all your tracks

- packages/discovery-provider/src/queries/get_health.py
- packages/discovery-provider/src/queries/get_health_unit_test.py
Temporarily disable this. Need to find a better way to not spam ES in health checks too
just a comment out
> Remove ES from health check

- packages/web/src/components/track/GatedContentSection.tsx
Random UI fix i noticed on prod
before:
after:
> Fix unlocked gated content section on web

- packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/server.tsx
> fix attest endpoint

- package-lock.json
- package.json
- packages/mobile/android/app/build.gradle
- packages/mobile/ios/AudiusReactNative/Info.plist
- packages/mobile/package.json
- packages/web/package.json
[41279da494] [PAY-3992] Improve suggested follows loading (#11543) Raymond Jacobson
[2791db851e] [PAY-3699] Show upload chip if you have deleted all your tracks (#11518) Raymond Jacobson [2b2b1db212] Hotfix advanced search filters not working (#11554) JD Francis [3abf34337e] Fix useDeleteTrack, sagas,  and confirmation modal (#11553) Andrew Mendelsohn [42323a7991] [C-5826] Add combineQueryStatuses helper (#11551) Dylan Jeffers [5c389a4bb9] [C-5759] DeleteTrack to tan-query (#11510) Andrew Mendelsohn [00cc46f871] Fix now playing artwork visualizer button (#11540) Dylan Jeffers [3a260241c2] Revert "[PAY-3865] Don't deeplink on android oauth" (#11549) Farid Salau [073188c3c5] Fix now playing jitter and nav icon spacing in mobile web (#11548) Raymond Jacobson [fe74995a62] Add breakpoint on …
> Audius Client (Web and Mobile) v1.5.125

- monitoring/healthz/src/pages/Nodes.tsx
- updates and removes unneeded things for healthz discprov
looks like this now
> change up discprov healthz to reflect core

- packages/discovery-provider/src/queries/get_health.py
- removes acdc from the health check because we are on core now
- works on local dev
- will delete acdc on stage and test there too
> rm acdc from health check

- .circleci/src/workflows/protocol-dashboard.yml
Was missing .* before
this CI run
> Fix dashboard job on release

- packages/discovery-provider/src/queries/get_health.py
- packages/discovery-provider/src/tasks/index_core.py
- packages/discovery-provider/src/utils/core.py
> core stuck health check

- monitoring/healthz/src/pages/Nodes.tsx
> put correct total chain blocks in healthz

- packages/discovery-provider/ddl/functions/handle_follow.sql
- packages/discovery-provider/ddl/functions/handle_repost.sql
- packages/discovery-provider/ddl/functions/handle_save.sql
- packages/discovery-provider/src/queries/get_notifications.py
Shadowban via trigger for performance.
local ddl tests
> Shadowban notifs via trigger

- packages/discovery-provider/plugins/pedalboard/apps/relay/src/config/config.ts
- packages/discovery-provider/plugins/pedalboard/apps/relay/src/index.ts
adjusts relay to work in other envs besides dev without acdc
> adjust relay to work in non dev without acdc

- comms/discovery/pubkeystore/backfill.go
Since acdc-relay is gone, chain recovery fails 100% of time. Since it also took a while to fail, this also made backfill process slow. So, just fetch from peer straigh away.
Need to add new recovery for core pubkeys.
Running this on DN4
> Remove chain pubkey recovery.

- packages/common/src/api/tan-query/useCollections.ts
- packages/common/src/api/tan-query/useTracks.ts
- packages/common/src/api/tan-query/useUsers.ts
- packages/common/src/api/tan-query/utils/combineQueryStatuses.ts
- packages/web/src/pages/explore-page/components/desktop/FeaturedPlaylists.tsx
- packages/web/src/pages/explore-page/components/mobile/ExplorePage.tsx
This reverts commit b70578a2ed807f83897abc2b5ed093083365314c.
> Revert "[C-5833] Avoid spreading queryResults (#11601)"

- packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/identity.ts
- packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/server.tsx
* Put Recent Users on front page
* Add some nice UI colors
* Cleanup
* Remove legacy AAO dependency
> Improve AAO tool UI

- packages/mobile/src/components/challenge-rewards-drawer/TastemakerChallengeContent.tsx
oops
test on stage - hard to test bc hard to make a user get the tastemaker challenge.
> Add summary table to tastemaker mobile UI

- packages/common/src/api/tan-query/useProfileReposts.ts
- packages/common/src/api/tan-query/useProfileTracks.ts
- packages/web/src/pages/explore-page/components/desktop/FeaturedPlaylists.tsx
My PR build passed but failed typecheck after merged to main 😵
typecheck
> Fix type errors that slipped through to main

- comms/discovery/server/server.go
> Check cache before trying to get key from peers.

- packages/discovery-provider/ddl/migrations/0125_listen_streak_comment_challenges.sql
- dn3 is stuck on a foreign key constraint, this should pass over in that event
yeet
> add on conflict fix 

- packages/discovery-provider/src/app.py
- packages/discovery-provider/src/tasks/index_challenges.py
* Re-queue celery task
* 1000 iterations per task
on prod dn2
> Batch events better

- packages/mobile/android/app/build.gradle
- packages/mobile/ios/AudiusReactNative/Info.plist
> Bump iOS and Android build numbers

- packages/discovery-provider/src/tasks/index_core.py
- adds a try around this release, it sometimes seems to throw
> add try around lock release in index_core.py

- packages/discovery-provider/src/utils/web3_provider.py
- since the removing web3_provider pr isn't tested yet this will unblock trending calculations
a version of this was ran on prod dn1 last friday
> always use local web3 provider

- packages/discovery-provider/src/tasks/create_engagement_notifications.py
- seeing this have the most lock issues, wrapping in a try
> add try wrap to engagement task lock

- packages/web/src/components/track/GatedContentSection.tsx
Noticed this layout bug
fixed:
before:
> Fix purchase button layout on web track page

- packages/discovery-provider/src/tasks/entity_manager/entities/track.py
> Dedupe track download indexing

- packages/discovery-provider/src/challenges/tastemaker_challenge.py
- packages/discovery-provider/src/queries/get_health.py
Only start creating tastemaker `user_challenge` rows after the given block has passed.
Test tomorrow on stage.
> [PAY-4039] Start tastemaker challenge only after certain block

- .cursor/rules/run-always.mdc
Added cursor rules to run before each request. Found these on tweeterrr and they seem to work well
> Add run-always cursor rules

- .circleci/src/commands/@docker-commands.yml
- .circleci/src/workflows/discovery.yml
- .circleci/src/workflows/release.yml
Can't deploy this because prerelease images aren't being generated/pushed for the archiver image.
N/A
> Add archiver to image builds

- package-lock.json
- packages/discovery-provider/plugins/pedalboard/apps/archiver/package.json
Should unblock pushing images for archiver.
`audius-compose build archiver`
> fix missing types for archiver

- packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/actionLog.ts
- packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/server.tsx
Manual block / allow button on AAO user page. Creates a table if plugin is running. Add some details to UI to make it more self-explanatory.
Resolves PAY-4036.
Blocked / unblocked on stage
> Manual block/allow from AAO

- monitoring/healthz/src/pages/Nodes.tsx
core health could've been null
already deployed
> potential undefined

- packages/mobile/src/screens/app-screen/AppTabsScreen.tsx
- packages/mobile/src/screens/app-screen/usePrefetchNotifications.ts
Adds prefetch to mobile notifications to improve first time experience, since that first fetch can take a while
> Add prefetch for mobile notifications

- packages/discovery-provider/src/challenges/tastemaker_challenge.py
Put this gating logic in the wrong place
> Tastemaker challenge block-gating fix

- packages/discovery-provider/integration_tests/challenges/test_cosign_challenge.py
- packages/discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
- packages/discovery-provider/src/challenges/challenge_event.py
- packages/discovery-provider/src/challenges/challenge_event_bus.py
- packages/discovery-provider/src/challenges/challenges.dev.json
- packages/discovery-provider/src/challenges/challenges.json
- packages/discovery-provider/src/challenges/challenges.stage.json
- packages/discovery-provider/src/challenges/cosign_challenge.py
- packages/discovery-provider/src/tasks/entity_manager/entities/social_features.py
Add a challenge for remixers when they get a cosign from a verified artist.
Added integration tests for indexing cosigns and dispatching cosign events.
> Add cosign challenge in discovery

- packages/discovery-provider/ddl/migrations/0128_patch_user_handle.sql
Counterpart PR https://github.com/AudiusProject/audius-protocol/pull/11686
tested on prod db
> Fix manual verification rows

- packages/web/src/pages/settings-page/components/desktop/SettingsPage.module.css
- packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
Fixes issue where settings page container incorrectly used inline-flex
> Fix settings page layout

- packages/discovery-provider/src/challenges/challenge_event_bus.py
- packages/discovery-provider/src/challenges/cosign_challenge.py
- packages/discovery-provider/src/tasks/entity_manager/entities/social_features.py
This should work e2e now. Fixing some minor bugs around indexing cosign challenges. Also, I think we need to add scope around dispatching events. 
> Fix cosign indexing listener type

- .circleci/config.yml
> rm content from auto-upgrade check

- packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/rewards.ts
- packages/sdk/src/sdk/api/chats/ChatsApi.ts
Thank you @rickyrombo for catching this
```
cd packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards
npm run build
npm run start
```
> Remove websocket init from chats api ctor

- .changeset/strange-taxis-work.md
- packages/sdk/src/sdk/sdk.ts
Fixes sdk initialization for events endpoint
Adds minor version changeset for new events feature
> Fix sdk init

- packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/rewardInCooldown.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/rewardInCooldown.ts
> Add cosign cooldown reward email

- packages/discovery-provider/requirements.txt
unsure why we needed to add this dep now but it works
> add types to protobuf for mypy

- packages/common/src/utils/email.ts
- packages/common/src/utils/handle.ts
- packages/web/src/components/composer-input/ComposerInput.tsx
- packages/web/src/components/user-generated-text/UserGeneratedTextV2.tsx
1. Fixes issue where emails are incorrectly read as mentions.
2. Fixes issue where typing @ in the middle of a word opens the mention popover
3. Fixes issue where emails get munged into a weird code on mobile
4. Ensures emails are clickable, opening email
> [QA-2030] Fix email and mentions in DMs

- packages/sdk/src/sdk/config/development.ts
- packages/sdk/src/sdk/scripts/generateServicesConfig.ts
Not sure when this changed but the health checks were using https instead of http for local dev.
Updated `generateServicesConfig.ts` and run using `npm run sdk:config`
audius-cmd works on local stack
> Fix local dev use http not https

- packages/discovery-provider/nginx_conf/nginx_container.conf
- packages/discovery-provider/src/queries/get_health.py
- packages/discovery-provider/src/utils/helpers.py
- packages/sdk/src/sdk/services/DiscoveryNodeSelector/healthCheckTypes.ts
Lua rsa dependency is old and contains a bug. We don't need this code anyway, so eliminating it from nginx is best.
Monitor staging
> Disable lua scripts in nginx_container.conf

- packages/web/src/pages/search-page/search-results/ProfileResults.tsx
Found a small bug making the user cards not show loading correctly
> Fix user card bug

- .cursor/rules/run-always.mdc
Suggestion for additions to our `run-always` cursor rule.
Should I remove my name?
Hard to test but I've at least confirmed that cursor has stopped deleting my console logs due to the "Preserve Debug Console Log" rule.
> Updates to run-always cursor rule

- packages/common/src/api/tan-query/useNotifications.ts
- packages/mobile/src/screens/notifications-screen/NotificationList.tsx
- packages/web/src/components/notification/NotificationPage.tsx
- packages/web/src/components/notification/NotificationPanel.tsx
Fixes issue where notification loading state was not taking entity fetch loading into account
> [QA-2034] Fix notification loading state

- packages/web/src/components/lineup/TanQueryLineup.tsx
Found a bug related to my latest lineup changes
This fixes it. Not my favorite solve but the component layout/styles needs an overhaul at some point anyways
web:stage mobile & desktop
> Fix mobile tile layout bug

- packages/mobile/src/components/comments/CommentBlock.tsx
- packages/web/src/components/comments/CommentBlock.tsx
Small fix to show artist badges in preview mode, even if artist pinned or favorited
> Show comment-badges in preview

- packages/web/src/components/track/GatedContentSection.tsx
- packages/web/src/components/track/GiantTrackTile.module.css
Small changes to improve UI for successful follow gate.
Before:
After:
> Fix follow artist gate ui

- packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeader/SocialLink.tsx
> [QA-2038] Fix mobile social link text truncation

- packages/discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
Accidentally merged the previous PR https://github.com/AudiusProject/audius-protocol/pull/11728. Meant to merge another. Left this part out
> Fix shadowban push notif using pg function

- packages/common/src/api/tan-query/README.md
Still WIP, but splitting up the reviews in phases
Docs for core tan-query usage
> Am tq docs

- packages/discovery-provider/ddl/functions/user_scores.sql
Dock any users with `audius` in their name or handle. Will shadowban / block them from DMs.
> Penalize audius impersonators

- packages/mobile/src/screens/profile-screen/ProfileTabs/RepostsTab.tsx
- packages/mobile/src/screens/profile-screen/ProfileTabs/TracksTab.tsx
Fixes infinite load on tracks/reposts on mobile
ios:stage
> Hotfix tracks/reposts infinite load on mobile

- packages/discovery-provider/ddl/functions/user_scores.sql
create or replace isn't enough when the return type for a function changes + undo revert https://github.com/AudiusProject/audius-protocol/pull/11763
prod deployed ok
> Drop user_score function before replacing

- packages/web/src/components/notification/NotificationPanel.tsx
Fixes issue where notification panel was closing incorrectly. It should only close when the user clicks outside the panel
> [QA-2041] Fix notification panel closing

- packages/discovery-provider/ddl/migrations/0130_update_challenge_specifier_format.sql
Re-landing https://github.com/AudiusProject/audius-protocol/pull/11756 now with duplicate detection.
Ran a dry-run on Prod DN 4, looks ok
> [PE-5919] Migration to change challenge specifiers from _ to :

- packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/actionLog.ts
- packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/server.tsx
Includes new rule for accounts that impersonate audius. Also clean up recent users page now that there's so many factors which will require less maintenance. 
> Update anti abuse UI to include impersonator

- packages/mobile/android/app/build.gradle
- packages/mobile/ios/AudiusReactNative/Info.plist
Bumping this weeks mobile versions since we had to do an extra release over the weekend to fix a bug. Will cherry-pick this onto this weeks release branch as well
> Update mobile versions to 148

- packages/discovery-provider/src/challenges/challenges.json
> Enable cosign reward

- packages/mobile/src/screens/audio-screen/AudioScreen.tsx
Updates audio-balance text to work with most audio balances
> [QA-2039] Fix audio balance display

- packages/web/src/components/host-remix-contest-modal/HostRemixContestModal.tsx
- packages/web/src/components/track/GiantTrackTile.tsx
* Update to use the user's local timezone for the time display and input
* Updated the modal to remove the default value
Manually Tested on web
Checking mobile now and will update if necessary
> [PE-5928] Event modal quality of life fixes

- packages/web/src/components/notification/Notification/components/ProfilePicture.module.css
- packages/web/src/pages/profile-page/components/desktop/ProfilePictureListTile.tsx
Update profile left-nav tiles to Paper component.
Updates profile-picture-list-border to 1px
> [QA-2047] Fix profile left nav tile shadow

- packages/web/src/components/track/GatedContentSection.tsx
Fixes issue related introduced by trying to harmonize this section. Note this sections was very busted before which was why there was a change here in the first place, but this shouldn't have been missed
> [QA-2050] Fix gated access UI

- packages/common/src/hooks/purchaseContent/useChallengeCooldownSchedule.ts
- packages/mobile/src/components/challenge-rewards-drawer/ClaimAllRewardsDrawer.tsx
- packages/web/src/components/rewards/modals/ClaimAllRewardsModal.tsx
> [QA-2052] Format number commas on claim all rewards

- packages/mobile/src/components/challenge-rewards-drawer/PinnedCommentChallengeContent.tsx
- packages/mobile/src/components/challenge-rewards-drawer/challengeContentRegistry.ts
- packages/mobile/src/screens/rewards-screen/ChallengeRewardsTile.tsx
Apparently I didn't ever toss this up 😅
> [PE-5936] Add mobile for pinned comment

- packages/common/src/api/tan-query/events/useCreateEvent.ts
- packages/common/src/api/tan-query/events/useEventsByEntityId.ts
- packages/common/src/api/tan-query/events/useUpdateEvent.ts
- packages/common/src/api/tan-query/events/utils.ts
- packages/mobile/src/components/host-remix-contest-drawer/HostRemixContestDrawer.tsx
- packages/mobile/src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx
- packages/web/src/components/host-remix-contest-modal/HostRemixContestModal.tsx
- packages/web/src/components/menu/TrackMenu.tsx
- packages/web/src/components/track/GiantTrackTile.tsx
Update the mutation hooks to properly update the entity id query keys and have the UI update
> [PE-5927] Update event mutation hooks

- .github/workflows/publish-packages.yml
Try to fix publish packages
Not sure how to really test this
> Try to fix publish packages command

- packages/discovery-provider/ddl/functions/handle_play.sql
Oops. We should not return this count into new_listen_count and deliver milestones on this.
will wait for CI here. and think about some kind of e2e
> Fix milestone bug

- packages/common/src/adapters/event.ts
- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
- packages/web/src/components/host-remix-contest-modal/HostRemixContestModal.tsx
- packages/web/src/components/track/GiantTrackTile.tsx
Updated the format that dates are adapted as from the backend and this fixed the timezone issues on web and mobile
> [PE-5938] Fix timezone issues for events

- packages/web/src/components/data-entry/ContextualMenu.module.css
- packages/web/src/components/edit/fields/RemixSettingsField/RemixSettingsField.module.css
- packages/web/src/components/edit/fields/RemixSettingsField/TrackInfo.tsx
- packages/web/src/components/track/TrackArtwork.tsx
Fixes issue where long track names overflow weirdly in upload form:
> [QA-2054] Fix overflowing remix text

- packages/mobile/src/screens/search-screen/SearchBar.tsx
Debounces mobile app search input similar to desktop, and im noticing a big performance improvement
> Debounce mobile search input

- package-lock.json
- packages/discovery-provider/plugins/pedalboard/apps/archiver/package.json
Imported directly in package, but not available in modules
npm i
> Add missing package

- packages/discovery-provider/src/tasks/entity_manager/entities/track.py
Validation doesn't cover the case where splits could be undefined
Cherry picked to production indexer
> Add splits validation in usdc purchases check

- packages/discovery-provider/src/queries/get_health.py
- packages/discovery-provider/src/queries/get_health_unit_test.py
- packages/discovery-provider/src/tasks/index_core.py
1. Get latest block number from core tip, regardless of indexer being stuck
2. Remove expiry on redis keys
audius-dn1.tikilabs.com
> Improve core health check block diff

- packages/common/src/utils/dayjs.ts
- packages/mobile/src/components/host-remix-contest-drawer/HostRemixContestDrawer.tsx
- packages/web/src/components/host-remix-contest-modal/HostRemixContestModal.tsx
- packages/web/src/components/track/GiantTrackTile.tsx
- packages/web/src/utils/dayjs.ts
Fixes:
* Invalid times allowed in the web time input
* Redirects to sign up flow now if user is not signed in and tries to submit to a contest
> [PE-5958, PE-5960] Events QA 2

- packages/discovery-provider/src/challenges/challenges.stage.json
Add stage starting block for pinned comment staging challenge so we can test the functionality on stage.
Calculated the block by:
- getting the current block from https://discoveryprovider.staging.audius.co/console/overview
- calculating the avg time between blocks 
```sql
WITH recent_blocks AS (
SELECT 
height,
created_at,
LAG(created_at) OVER (ORDER BY height) AS prev_created_at
FROM core_blocks
WHERE created_at >= NOW() - INTERVAL '24 hours'
)
SELECT 
COUNT(*) AS block_count,
AVG(EXTRACT(EPOCH FROM (created_at - prev_created_at))) AS avg_time_diff_seconds
FROM recent_blocks
WHERE prev_created_at IS NOT NULL;
```
- Running this script to calculate future block
```js
// Given data
const data = [
{
"block_count": "98497",
"avg_time_diff_seconds": "0.87717501703605185945"
}
];
// Current …
```
> Add stage starting block for pinned comment staging challenge

- packages/mobile/src/components/core/VirtualizedScrollView.tsx
- packages/mobile/src/screens/track-screen/TrackDescription.tsx
- packages/mobile/src/screens/track-screen/TrackScreen.tsx
- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Mobile equivalent to https://github.com/AudiusProject/audius-protocol/pull/11825
Tested on device so no recording, but it works!
> Mobile track description scrolls to toggle button on collapse

- packages/discovery-provider/src/queries/get_health.py
https://github.com/AudiusProject/audius-protocol/pull/6065
Added here
I don't think this provides value to us currently, though I understand where it came from.
will confirm on staging
> Remove api check

- packages/web/src/components/track/desktop/TrackListItem.tsx
> [QA-2064] Fix deactivated showing on playlist tiles

- packages/mobile/src/components/host-remix-contest-drawer/HostRemixContestDrawer.tsx
- packages/web/src/components/host-remix-contest-modal/HostRemixContestModal.tsx
Add an option on web and mobile to turn off the contest if there are no submissions
> [PE-5940] Add turn off option for remix contests

- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
- packages/web/src/components/track/GiantTrackTile.tsx
> [PE-5951] Remix contest ended UI

- packages/discovery-provider/ddl/migrations/0134_ddex_majors_fields.sql
- packages/discovery-provider/src/models/tracks/track.py
Add 3 fields
* no_ai_use
* parental_warning
* territory_codes
locally:
```
pg_migrate.sh
```
> [API-2] Add additional ddex fields to tracks data model

- packages/mobile/src/screens/track-screen/DownloadRow.tsx
- packages/mobile/src/screens/track-screen/DownloadSection.tsx
Some UI fixes for mobile download section
> [PE-5972] Mobile download all alignment fix

- packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/server.tsx
Sometimes timestamp is missing which causes an `internal server error`
> Fix AAO error on missing timestamp

- packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Contest end date + upload submission button
https://github.com/user-attachments/assets/48198838-d670-4b1b-b319-c3352a11a505
> [PE-5984] Mobile web remix contest track page UI

- packages/discovery-provider/src/queries/get_users.py
- packages/discovery-provider/src/utils/auth_middleware.py
- packages/web/src/common/store/pages/signon/sagas.ts
- Adds reporting for incomplete accounts in weird edge case
- Fixes issue where a user wasn't authenticated due to using a different user ID than what the middleware expected
QA-2060
reference: https://github.com/AudiusProject/audius-protocol/pull/11667
> QA-2060 Fix middleware to have same account fetching logic as the account endpoint

- packages/common/src/api/tan-query/events/useCreateEvent.ts
- packages/common/src/api/tan-query/events/useDeleteEvent.ts
- packages/common/src/api/tan-query/events/useEventsByEntityId.ts
- packages/common/src/api/tan-query/events/useRemixContest.ts
- packages/common/src/api/tan-query/events/useUpdateEvent.ts
- packages/common/src/api/tan-query/events/utils.ts
Updated the eventsByEntityId state to use ids so that updates are more correct and fixes optimistic updates
> [PE-5978] Update events tan-query state to be more normalized

- packages/web/src/components/edit/fields/StemFilesView.tsx
Noticed this bug while QA-ing the other day
web stage
> [PE-5988] Disable upload more stems dropzone when max stems

- packages/harmony/src/components/popup-menu/PopupMenu.tsx
- packages/mobile/src/screens/edit-track-screen/components/RemixTrackPill.tsx
Small updates to fix the wrong popup menu color and the remix-of overflow on mobile
> [PE-5959, PE-5969] Fix some small styling issues around remix contests

- packages/web/src/pages/track-page/components/mobile/TrackDescription.tsx
- packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Expandable description for mobile-web.
https://github.com/user-attachments/assets/1e1f8442-432d-491e-972e-de22727a2cbb
> [PE-5986] Mobile-web expandable description

- packages/discovery-provider/ddl/functions/user_scores.sql
Penalize users who play the same track over and over again
> Add distinct tracks played to AAO score

- packages/harmony/src/components/select/Select/Select.tsx
Small fix to harmony select value positioning when label is hidden
> [PE-5961] Fix event form AM/PM value position

- packages/web/src/common/store/upload/sagas.ts
- packages/web/src/components/lineup/TanQueryLineup.tsx
- packages/web/src/pages/track-page/components/TrackPageLineup.tsx
Fixes issue where submission disappears after upload by invalidating the relevant queries.
Improves tan-query-lineup skeletons by taking maxEntries into account.
> [PE-5999] Fix submission disappearing

- packages/common/src/api/tan-query/useRemixes.ts
- packages/web/src/pages/remixes-page/components/desktop/NewRemixesPage.tsx
Add count to useRemixes hook and use in the web remixes page
> [PE-6006] Fix remix page counts

- packages/web/src/components/host-remix-contest-modal/TimeInput.tsx
Fixes issue where typing 830 didnt result in 8:30
> Fix hour input on time input

- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/listen.ts
> Early exist listen on solana relay

- packages/web/src/pages/remixes-page/RemixesPageProvider.tsx
- packages/web/src/pages/remixes-page/components/desktop/NewRemixesPage.tsx
Fix remix page title and remove contest entries button when not a contest
> [PE-6008] Remix Page fixes 2

- packages/web/src/common/store/upload/sagas.test.ts
Main tests are broken on web, added query client to test to fix
`npm run web:test`
> Add query client to tests

- packages/web/src/components/link/UserLink.tsx
- packages/web/src/components/user-badges/UserBadges.tsx
- packages/web/src/components/user-badges/UserBadgesV2.tsx
- packages/web/src/pages/profile-page/components/EditableName.tsx
- Decided to gate the user-link changes behind the wallet-ui feature flag since they introduce a few sizeable changes.
- Brought back legacy user-badges to enable this
> Gate new user-badges in user-link behind wallet-ui flag

- packages/common/src/adapters/event.ts
- packages/web/src/components/host-remix-contest-modal/HostRemixContestModal.tsx
Add description and prize fields for remix contests and save the data into the remix contest event data
> [PE-6014] Add description and prize fields for remix contests

- packages/discovery-provider/src/queries/confirm_indexing_transaction_error.py
Allow skips on 5%
just a config change
> [API-43] Allow skips on 5%

- packages/web/src/components/host-remix-contest-modal/HostRemixContestModal.tsx
Small fix to check the proper thing for the ternary
> Small remix contest modal fix

- packages/common/src/api/index.ts
- packages/common/src/store/cache/tracks/actions.ts
- packages/web/src/common/store/cache/tracks/sagas.ts
- packages/web/src/pages/edit-page/EditTrackPage.tsx
Fixes issue where user unable to edit track artwork
Fixes issue where user unable to delete stems
Fixes issue where deleted stems don't disappear in download section after deletion
> [PE-6034, PE 6033] Fix edit track

- packages/discovery-provider/plugins/pedalboard/apps/archiver/src/workers/createStemsArchive/createStemsArchive.ts
Use storeall node flag for archiver after following redirect
Deployed to prod dn1, download time from 5 min -> 1 min
> Use storeall for archiver

- packages/create-audius-app/README.md
- packages/create-audius-app/playwright.config.ts
* Improve readme
* Fix tests by identifying user agent
```
EXAMPLE=react npm run test:e2e      
EXAMPLE=react-hono npm run test:e2e      
```
> Fix create audius app playwright tests

- packages/discovery-provider/ddl/migrations/0136_index_cleanup_saves_reposts_remixes.sql
ensure index can cover the most common queries without heap fetch... especially for related data in `get_tracks.sql`
> index cleanup for saves, reposts, remixes.

- packages/web/src/test/mocks/app-context.ts
- packages/web/src/test/mocks/local-storage.ts
- packages/web/src/test/mocks/remote-config.ts
- packages/web/src/test/test-utils.tsx
- Adds feature flag option to test suite
- Fixes existing error due to `useFeatureFlag` call in CollectionCard that didn't have access to `useAppContext`
> Add feature flags to tests, fix collection-card

- packages/common/src/utils/challenges.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/rewardInCooldown.ts
Now that we have a limit on cosign we want to adjust this copy.
> Adjust cosign copy post limit

- packages/mobile/src/screens/track-screen/RemixContestSubmissionsTab.tsx
- packages/mobile/src/screens/track-screen/TrackScreenLineup.tsx
* Fill in the submissions section in the remix contest container on mobile
* Update the track screen to not show the remixes section when the track is a remix contest
> [PE-6020] Add submissions section to remix contest container on mobile

- packages/discovery-provider/src/queries/get_attestation.py
> Fix CN attestations

- packages/web/src/pages/track-page/components/desktop/RemixContestSubmissionsTab.tsx
- packages/web/src/pages/track-page/components/mobile/remix-contests/RemixContestSubmissionsTab.tsx
Update the artwork in the submission section to navigate to the track page
> [PE-6067] Update submission artwork to go to track page

- packages/web/src/components/collapsible-content/CollapsibleContent.tsx
Conditionally show the collapse/expand button only when the content height exceeds the min threshold.
https://github.com/user-attachments/assets/3c666586-d48d-4344-88e2-1b933e85c910
> [PE-6072] CollapsibleContent conditionally shows expand button

- packages/mobile/src/components/comments/CommentPreview.tsx
- packages/mobile/src/screens/track-screen/RemixContestDetailsTab.tsx
- packages/mobile/src/screens/track-screen/RemixContestPrizesTab.tsx
- packages/mobile/src/screens/track-screen/RemixContestSection.tsx
- packages/mobile/src/screens/track-screen/RemixContestSubmissionsTab.tsx
- packages/web/src/components/comments/CommentPreview.tsx
- packages/web/src/components/comments/CommentSection.tsx
- packages/web/src/pages/track-page/components/desktop/RemixContestSection.tsx
- packages/web/src/pages/track-page/components/mobile/remix-contests/RemixContestSection.tsx
Add borders and make slight styling updates as needed
There were slight issues with the styling on mobile with the tabs and the addition of the border so needed to update some things
> [PE-6078] Add borders to remix contest info and comment sections

- packages/mobile/src/screens/track-screen/RemixContestSection.tsx
- packages/web/src/pages/track-page/components/desktop/RemixContestSection.tsx
- packages/web/src/pages/track-page/components/mobile/remix-contests/RemixContestSection.tsx
> [PE-6077] Conditionally hide prizes tab in remix contest section

- packages/web/src/pages/track-page/components/desktop/RemixContestSubmissionsTab.tsx
Just adding the gap back bc it got lost somewhere
> Add gap back to the submissions tab

- packages/common/src/store/stems-upload/selectors.ts
- packages/web/src/components/unsaved-changes-dialog/UnsavedChangesDialog.tsx
- packages/web/src/pages/modals/Modals.tsx
Improves upload and stem upload by ensuring user is warned when trying to refresh.
Updates UI to use ConfirmationModal
> [PE-6090] Add upload warning to unsaved-changes-dialog

- packages/mobile/ios/Podfile.lock
- packages/mobile/package.json
- packages/mobile/patches/react-native-pager-view+6.7.1.patch
> Improve remix contest info scrolling inside a scroll-view

- packages/common/src/api/suggestedTracks.ts
- packages/common/src/api/track.ts
- packages/common/src/hooks/chats/usePurchasersAudience.ts
- packages/mobile/src/screens/chat-screen/ChatMessagePlaylist.tsx
- packages/web/src/pages/chat-page/components/ChatMessagePlaylist.tsx
- Replace useGetTracksByIds with useTracks
web:stage
> [PE-6075] Remove useGetTracksByIds from a-query

- packages/mobile/src/screens/track-screen/RemixContestSubmissionsTab.tsx
- packages/web/src/pages/track-page/components/desktop/RemixContestSubmissionsTab.tsx
Small styling updates for mobile remix contest submissions tab
> Small fixes to submission tab styling

- packages/common/src/utils/constants.ts
- packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx
- packages/web/src/components/premium-content-purchase-modal/pages/PurchaseContentPage.tsx
> Fix earn 5  purchase flow message on mobile

- packages/web/src/pages/track-page/components/desktop/RemixContestSubmissionsTab.tsx
Change the formatting of the submissions tab to better match the designs
> Change submissions tab formatting

- packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py
This value can be UGC and crashes python when trying to do utcfromtimestamp.
Requires more investigation. this is a ~quick fix.
Prod dn123
> Fix last added to playlist bug

- packages/discovery-provider/src/tasks/core/core_client.py
> rm debug logs

- packages/mobile/src/screens/track-screen/RemixContestSubmissionsTab.tsx
Pressable track artwork
tested on ios stage
https://github.com/user-attachments/assets/64b0f07f-8620-49d0-b315-dd28e2d017e8
> Mobile remix section submission artwork pressable

- packages/web/src/components/user-badges/UserBadges.module.css
- packages/web/src/components/user-card/UserCard.tsx
- packages/web/src/pages/explore-page/components/desktop/UserArtCard.module.css
Small updates to fix the called out visual regressions for user links and badges. 
> [QA-2084] Small fixes for UserLinks and bedges

- packages/discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
- packages/discovery-provider/src/tasks/entity_manager/entities/user.py
This causes us enough problems! Let's stop it from being a thing.
New integ test file & existing em tests pass
> [API-103] Prevent multiple users with the same wallet address

- packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/clm.ts
UI allows you to add a track to multiple albums.  But downstream reporting assumes a track is contained in an album and doesn't appear associated with different albums.
So for our UGC, choose the oldest public album containing this track.
> CLM report: use first album.

- packages/web/src/components/collection/CollectionCard.tsx
- packages/web/src/components/collection/desktop/CollectionHeader.tsx
- packages/web/src/components/link/UserLink.tsx
- packages/web/src/components/nav/desktop/AccountDetails.tsx
- packages/web/src/components/user-card/UserCard.tsx
- packages/web/src/pages/explore-page/components/desktop/CollectionArtCard.tsx
Update UserLink to match container size to properly contain and center text
There is a small chance that these changes will cause a visual bug somewhere but I couldn't find any
> Update UserLinks to correctly contain and center text

- .changeset/fair-ears-look.md
- packages/sdk/src/sdk/api/challenges/types.ts
> Add pinned comment challenge to valid challenges enum

- packages/sdk/src/sdk/scripts/manageRewardsLookupTable.ts
Content Nodes are Validators too, and can attest for rewards. Add them to the script that updates the reward manager lookup table.
> Add content nodes to lookup table script

- packages/web/src/components/track/GiantTrackTile.tsx
- packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Issue due to UserLink taking up 100% width
> Fix formatting issues for artist links on web and mobile web

- packages/discovery-provider/integration_tests/tasks/test_remix_contest_started_notification.py
Changed the specifier for this notif but forgot to change the test
Test passes locally
> Fix remix contest started notif test

- packages/discovery-provider/integration_tests/tasks/test_remix_contest_ended_notification.py
- packages/discovery-provider/integration_tests/tasks/test_remix_contest_ending_soon_notification.py
- packages/discovery-provider/src/app.py
- packages/discovery-provider/src/tasks/create_remix_contest_notifications.py
- packages/discovery-provider/src/tasks/remix_contest_notifications/fan_remix_contest_ended.py
- packages/discovery-provider/src/tasks/remix_contest_notifications/fan_remix_contest_ending_soon.py
Re-land [#12041](https://github.com/AudiusProject/audius-protocol/pull/12041)
lint passes!
> Refactor remix contest notifications to single task V2

- packages/discovery-provider/integration_tests/tasks/test_create_engagement_notifications.py
- packages/discovery-provider/integration_tests/utils.py
- packages/discovery-provider/src/api/v1/utils/extend_notification.py
Discovery CI was broken for a while because of a React Native upgrade so this https://github.com/AudiusProject/audius-protocol/pull/12023 was silently failing. Removing cooldown days broke these tests.
Also there's a type error from https://github.com/AudiusProject/audius-protocol/pull/12044
Discovery tests pass, will wait for CI to confirm
> Fix notif test with missing cooldown days and fix remix contest typing

- packages/harmony/src/components/layout/Box/Box.tsx
- packages/harmony/src/foundations/color/semantic.ts
Sounds like we dont need this for explore page anymore, but good to have
> [PE-6113] Add linear gradient background to paper

- packages/discovery-provider/ddl/functions/get_user_score.sql
The values in the AAO UI tool were swapped around. It had no impact on the actual score though. 
Deployed in DN1 and confirmed values look correct.
> Fix challenge count num in AAO UI

- packages/mobile/src/screens/notifications-screen/Notifications/FanRemixContestEndedNotification.tsx
- packages/web/src/components/notification/Notification/FanRemixContestEndedNotification.tsx
> [PE-6130] Small notif copy change

- packages/commands/src/index.ts
- packages/commands/src/misc/aao.ts
- packages/commands/src/utils.ts
Adds easier CLI to block/unblock users from AAO on local dev
> [API-112] Add AAO block/unblock commands to audius-cmd

- packages/discovery-provider/src/app.py
To make it easier to test on stage. Can change this back later.
> 30 second interval for remix notifs

- packages/web/src/components/notification/Notification/ArtistRemixContestEndedNotification.tsx
- packages/web/src/components/notification/Notification/ArtistRemixContestEndingSoonNotification.tsx
- packages/web/src/components/notification/Notification/ArtistRemixContestSubmissionsNotification.tsx
- packages/web/src/components/notification/Notification/FanRemixContestEndedNotification.tsx
- packages/web/src/components/notification/Notification/FanRemixContestEndingSoonNotification.tsx
- packages/web/src/components/notification/Notification/FanRemixContestStartedNotification.tsx
Using more modern navigation and `TrackLink`.
> Fix remix contest web notif links

- packages/discovery-provider/plugins/notifications/package.json
- packages/discovery-provider/plugins/notifications/src/__tests__/mappings/artistRemixContestEnded.test.ts
- packages/discovery-provider/plugins/notifications/src/__tests__/mappings/artistRemixContestEndingSoon.test.ts
- packages/discovery-provider/plugins/notifications/src/__tests__/mappings/artistRemixContestSubmissions.test.ts
- packages/discovery-provider/plugins/notifications/src/__tests__/mappings/fanRemixContestEnded.test.ts
- packages/discovery-provider/plugins/notifications/src/__tests__/mappings/fanRemixContestEndingSoon.test.ts
- packages/discovery-provider/plugins/notifications/src/__tests__/mappings/fanRemixContestStarted.test.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/artistRemixContestEnded.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/artistRemixContestEndingSoon.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/artistRemixContestSubmissions.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/fanRemixContestEnded.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/fanRemixContestEndingSoon.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/fanRemixContestStarted.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/mapNotifications.ts
- packages/discovery-provider/plugins/notifications/src/remoteConfig.ts
- packages/discovery-provider/plugins/notifications/src/types/notifications.ts
Push notifications for all the remix contest notifications we added
Tests pass
> [PE-6158] Remix contest push notifications

- packages/mobile/src/screens/notifications-screen/Notifications/ArtistRemixContestEndedNotification.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/ArtistRemixContestEndingSoonNotification.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/ArtistRemixContestSubmissionsNotification.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/FanRemixContestEndedNotification.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/FanRemixContestEndingSoonNotification.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/FanRemixContestStartedNotification.tsx
Didn't get to actually test these so these are fixes that should get them working.
Tested on local ios stage
> Fix mobile remix contest notifs

- packages/mobile/src/screens/track-screen/DownloadSection.tsx
- packages/web/src/components/track/DownloadSection.tsx
- packages/web/src/pages/track-page/components/mobile/DownloadSection.tsx
Small update to make sure that the download all button for follow gated extras is disabled
> Fix download all follow gated logic on web

- packages/web/src/pages/track-page/components/desktop/RemixContestSubmissionsTab.tsx
Forgot to add a commit in this PR: https://github.com/AudiusProject/audius-protocol/pull/12117/files
> Include contest entries param in remix submissions tab

- packages/common/src/api/tan-query/saga-utils/queryUser.ts
- packages/common/src/api/tan-query/users/useUser.ts
- put was not working as I expected, instead using dispatch from the saga context is what we needed
web:stage incognito profile page
> Fix bug where queryUser was not priming old cache

- packages/common/src/api/tan-query/utils/defaultConfig.ts
Needed to drill one more level
on our bug from earlier
> Fix tan-query 400 retry logic

- packages/web/src/components/nav/desktop/NowPlayingArtworkTile.tsx
Quick improvement to now-playing artwork. drops top margin and refactors it to be a bit simpler. Also improves computed color box shadow
> [PE-6165] Remove now-playing artwork top margin

- packages/mobile/src/screens/track-screen/RemixContestSection.tsx
- packages/mobile/src/screens/track-screen/RemixContestWinnersTab.tsx
- packages/mobile/src/screens/track-screen/RemixSubmissionCard.tsx
Replace the submissions tab with the winners tab
Display winners
> [PE-6195] Add winners section to remix contest container on mobile

- packages/web/src/components/edit/fields/RemixSettingsField/RemixSettingsMenuFields.tsx
Disable throw on error for this particular query
integration:test should pass
> Fix pw remix upload test throwing on 404

- packages/common/src/services/remote-config/feature-flags.ts
- packages/mobile/src/screens/track-screen/RemixContestSection.tsx
- packages/web/src/pages/remixes-page/components/desktop/NewRemixesPage.tsx
- packages/web/src/pages/track-page/components/desktop/RemixContestSection.tsx
- packages/web/src/pages/track-page/components/mobile/remix-contests/RemixContestSection.tsx
Added a feature flag bc this milestone will take more than one week
> [PE-6201] Add feature flag for pick winners milestone

- packages/mobile/src/components/core/UserGeneratedText.tsx
- packages/mobile/src/hooks/useNotificationNavigation.ts
- packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx
Fixes issue where track navigation params used id instead of trackId
> [QA-2106] Fix mobile track navigation params

- packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
- packages/web/src/pages/pick-winners-page/PickWinnersPage.tsx
- packages/web/src/store/dragndrop/slice.ts
> [PE-6193] Update winners tiles to be reorderable

- packages/mobile/package.json
Fixes issue with ios import not working due to old version
> Fix ios date picker import

- packages/mobile/src/app/Drawers.tsx
- packages/mobile/src/harmony-native/components/Button/Button/Button.tsx
- packages/mobile/src/screens/track-screen/PickWinnersDrawer.tsx
- packages/mobile/src/screens/track-screen/RemixContestDetailsTab.tsx
- packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
- packages/mobile/src/store/drawers/slice.ts
* Add the drawer and button to display it
* Small update to display 'Contest Ended' on mobile when the contest is over
* Small update to correct the text color of the primary button text
> [PE-6169] Add PickWinners drawer for mobile

- packages/common/src/api/tan-query/tracks/useTrackByPermalink.ts
- packages/common/src/api/tan-query/types.ts
> Passthru throwOnError for trackByPermalink query

- packages/mobile/src/screens/notifications-screen/Notifications/RemixCreateNotification.tsx
- packages/web/src/components/notification/Notification/RemixCreateNotification.tsx
> Remove parent track title from new remix notif

- packages/web/src/components/buy-sell-modal/BuyTab.tsx
- packages/web/src/components/buy-sell-modal/SwapTab.tsx
- packages/web/src/components/buy-sell-modal/TokenAmountSection.tsx
- packages/web/src/components/buy-sell-modal/constants.ts
- packages/web/src/components/buy-sell-modal/types.ts
Made updates to show token price instead of exchange rate and refactored a to match figma UI state
`npm run web:prod` and compare to Prod
> [PE-6188] Address comments from M2 bugbash 

- packages/discovery-provider/integration_tests/tasks/test_artist_remix_contest_ended_notification.py
- packages/discovery-provider/integration_tests/tasks/test_artist_remix_contest_ending_soon_notification.py
- packages/discovery-provider/integration_tests/tasks/test_fan_remix_contest_ended_notification.py
- packages/discovery-provider/integration_tests/tasks/test_fan_remix_contest_ending_soon_notification.py
- packages/discovery-provider/src/tasks/remix_contest_notifications/artist_remix_contest_ended.py
- packages/discovery-provider/src/tasks/remix_contest_notifications/artist_remix_contest_ending_soon.py
- packages/discovery-provider/src/tasks/remix_contest_notifications/fan_remix_contest_ended.py
- packages/discovery-provider/src/tasks/remix_contest_notifications/fan_remix_contest_ending_soon.py
Did this for fan remix contest started notifs but forgot to do the same for the other ones!
Local tests pass
> Don't send remix contest notifs for private tracks

- .circleci/src/commands/@mobile-commands.yml
Broken builds on staging due to caching issue
> Retrigger pod install

- packages/mobile/src/services/env/env.prod.ts
- packages/web/src/services/env/env.prod.ts
Sign in with MetaMask failing because I configured this wrong 🤦
> Use HTTPS for api.audius.co

- packages/web/src/components/notification/Notification/ArtistRemixContestEndedNotification.tsx
Update artist facing contest ended notif to display pick winners button and copy
> [PE-6170] Update contest ended notif to navigate to pick winners

- packages/mobile/mobile-patches/react-native+0.76.9.patch
- scripts/patch-package.sh
Fixes issue where animated-event triggers app-wide crash. This was previously patched and i thought we might not need it anymore after upgrading
> Fix animated-event error leading to crash

- packages/common/src/messages/walletMessages.ts
- packages/mobile/src/components/add-funds-drawer/AddCashDrawer.tsx
- packages/web/src/components/add-cash-modal/AddCashModal.tsx
> [PE-6229] Link by Stripe logo on web add cash modal

- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/redis.ts
Add logs to rate limit on solana relay
> Add logs to rate limit 

- packages/mobile/src/components/lineup/TanQueryLineup.tsx
- packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
- packages/web/src/components/lineup/TanQueryLineup.tsx
- packages/web/src/pages/remixes-page/components/mobile/NewRemixesPage.tsx
Add and display the winners on the remixes screen
> [PE-6194] Add winners to remixes page on mobile

- packages/common/src/messages/walletMessages.ts
- packages/mobile/src/components/add-funds-drawer/AddCashDrawer.tsx
- packages/mobile/src/components/usdc-manual-transfer/USDCManualTransfer.tsx
- packages/web/src/components/add-cash-modal/AddCashModal.tsx
- packages/web/src/components/usdc-manual-transfer/USDCManualTransfer.tsx
- packages/web/src/pages/pay-and-earn-page/components/CashWallet.tsx
> Add Cash QA feedback

- packages/common/src/messages/remixes.ts
- packages/mobile/src/screens/track-screen/TrackRemixesScreen.tsx
- packages/web/src/pages/remixes-page/components/desktop/NewRemixesPage.tsx
Small update to the button text
> Update pick winners button text to edit winners

- packages/common/src/api/tan-query/lineups/useLineupQuery.ts
- packages/common/src/api/tan-query/remixes/useRemixes.ts
Small update to the dependencies of the useCallback to make sure that the changes in the lineupData were being passed correctly
> [PE-6256] Update callback dependencies to properly update lineup data

- .circleci/src/commands/@mobile-commands.yml
Temporarily dropping pod cache due to weird issues building on cached pods
> Remove ci pod cache

- .circleci/config.yml
Resets npm i cache, which i think is causing issues with mobile apps.
Improves cache paths
Handles case for node versions to avoid footguns when we eventually upgrade
> Improve CI install cache

- packages/common/src/api/tan-query/saga-utils/queryTrack.ts
- packages/web/src/common/store/upload/sagas.ts
Fixes issue where queryTrack wasn't caching leading to slowness when playing tracks
> Fix query track gc time

- .circleci/config.yml
Drops unnecessary fallback cache keys
> Drop fallback cache keys

- .circleci/config.yml
> Fix cache key save

- packages/common/src/store/queue/selectors.ts
- packages/web/src/components/play-bar/desktop/PlayBar.jsx
- packages/web/src/pages/feed-page/FeedPageProvider.jsx
- packages/web/src/pages/trending-page/TrendingPageProvider.jsx
Fixes player controls due to missed refactors on jsx code
> [PE-6301] Fix player controls

- packages/web/src/components/buy-sell-modal/BuySellFlow.tsx
- packages/web/src/pages/pay-and-earn-page/components/CashWallet.styles.ts
- packages/web/src/pages/pay-and-earn-page/components/CashWallet.tsx
Fixes issue where transaction history link doesn't stay vertically aligned at small breakpoints
Fixes issue with button sizing in mobile
> [PE-6294] Fix wallet UI breakpoint

- packages/web/src/components/nav/desktop/AccountDetails.tsx
Small change to make the border='thin' on signed-out avataru
> [PE-6272] Fix signed-out avatar account border

- packages/web/src/hooks/useConnectAndAssociateWallets.ts
Quick mitigation to fix connected wallets modal crash...
> Fix crash in connectedWallets modal

- packages/common/src/api/tan-query/tracks/useTrackByPermalink.ts
This was supposed to default to false 🙈 
> Hotfix 400 messages crash

- packages/discovery-provider/integration_tests/queries/test_get_tracks.py
- packages/discovery-provider/src/queries/get_remixes_of.py
Remix section for this track was showing 6 remixes when in fact there were only 3 (checked db):
https://audius.co/lowswimmer/nosebleeds
problem was there were 2 duplicate events that were both ongoing remix competitions, and the query in get_remixes.py was double-counting them because of this.
Fix is to only select the most recent event in the event join
Added integration test
> [PE-6305] Fix double-counting remixes when two active events

- packages/discovery-provider/src/challenges/challenges.stage.json
> No cooldown for remix winner challenge on stage

- packages/common/src/api/tan-query/lineups/useLineupQuery.ts
- packages/common/src/api/tan-query/remixes/useRemixesLineup.ts
Fixes loading issues for contests with many entries, introduced by pick-winners optimistic updates work.
> Fix remix submission page loading

- packages/discovery-provider/integration_tests/tasks/entity_manager/test_event.py
- packages/discovery-provider/src/tasks/entity_manager/entities/event.py
We were preventing events with the same event id from being created, but not remix contest events pointing to the same track! Need to go grab events from the db to do that.
Had to change the first test test_create_event as well as it was actually trying to create another remix contest for track 2, for which there was already a remix contest in the mock data.
Added a test.
> [PE-6309] Prevent dup remix contests being created for the same track

- packages/common/src/api/tan-query/notifications/useNotificationEntities.ts
Fixes single track upload notif not linking out to the track correctly
web:stage
TODO: I started making an integration test here, will work on that some more while sending this out
> [QA-2121] Fix track upload notification not linking to track page

- packages/discovery-provider/ddl/migrations/0141_user_profile_type.sql
- packages/discovery-provider/src/api/v1/models/users.py
- packages/discovery-provider/src/models/users/user.py
Adds `profile_type` column to users table.  The desire is it is returned in API response.  But I'm not sure if this is sufficient for that.
> Add user profile_type column + enum

- packages/discovery-provider/ddl/functions/get_user_scores.sql
Fixes
```
ERROR:  return type mismatch in function declared to return record
DETAIL:  Final statement returns too many columns.
```
> Add karma to user scores

- packages/harmony/src/components/artwork/Artwork.tsx
Fixes issue where initial load doesn't animate from skeleton to image.
https://github.com/user-attachments/assets/376f675d-f1d7-4728-80f8-ef159fedac2b
> [PE-6249] Improve artwork loading animation

- packages/web/src/components/search-bar/DesktopSearchBar.module.css
- packages/web/src/components/search-bar/DesktopSearchBar.tsx
Add dropdown scrollbar and prevent it from propagating.
Fixes PE-6313
> Add search dropdown scrollbar

- packages/web/src/components/link/TrackLink.tsx
> Fix track link

- packages/common/src/messages/walletMessages.ts
- packages/web/src/components/add-cash/CashBalanceSection.tsx
- packages/web/src/components/tooltip/Tooltip.module.css
- packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.tsx
- packages/web/src/components/withdraw-usdc-modal/components/EnterTransferDetails.tsx
- Added tooltip - had to decrease zindex in tooltip css file
- copy + small UI changes to the coinflow branch of the web withdraw flow
> [PE-6257] Web coinflow withdraw UI updates

- packages/web/src/components/embed-modal/EmbedModal.tsx
Fallout from tanquery migration
> [PE-6318] Fix album embed

- packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistNavItem.tsx
This was breaking local web prod
Local web prod works now
> Fix accountCollection is undefined

- packages/mobile/src/screens/track-screen/UploadRemixFooter.tsx
- packages/web/src/pages/remixes-page/components/desktop/NewRemixesPage.tsx
- packages/web/src/pages/track-page/components/desktop/RemixContestSection.tsx
Pass along the artwork and genre to the upload form
NOTE: Does not pass the artwork on mobile bc there was an error, will look into a fix
> [PE-6323] Pass track artwork and genre to upload form for remix contest entries

- packages/common/src/api/tan-query/remixes/useRemixesLineup.ts
Updated to display the winners in the submissions section. Easier than it looked.
> [PE-6320] Update remixes page to display winners in the submissions section

- packages/web/src/pages/upload-page/UploadPage.tsx
- packages/web/src/pages/upload-page/pages/SelectPage.tsx
Skip the upload type choice and also go back to the remix contest page when hitting back
> [PE-6324] Skip select upload type step when submitting to contest

- packages/mobile/src/screens/track-screen/UploadRemixFooter.tsx
> Update mobile to take remix contest image when submitting

- packages/mobile/src/screens/root-screen/RootScreen.tsx
Fixes the mobile app going to sign up when you're signed in
ios:stage sim
> [PE-6339] (account fix) Fix mobile app taking you to sign up when signed in 

- packages/web/src/components/track/TrackArtwork.tsx
- packages/web/src/pages/track-page/components/mobile/TrackHeader.module.css
- packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Fixes small issue where there is no skeleton for mobile web track artwork. Replaces dynamic-image with track-artwork and adds flair support to track-artwork
> Fix mobile web track artwork loading

- packages/discovery-provider/integration_tests/tasks/entity_manager/test_comment.py
- packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
Prevents issue where user reacts to nonexistent/deleted comment
> [PE-6143] Fix comment reaction indexing

- packages/mobile/src/screens/upload-screen/screens/UploadingTracksScreen.tsx
Kinda a terrible solve for the stalled mobile upload, but imo this is not the worst way to fix 80/20 cases
> Fix mobile upload stuck at 100%

- packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx
Small fix to show the track tile in the upload complete section even if there was a stall issue
> Fix missing track in upload complete screen

- packages/mobile/src/components/core/CardList.tsx
- packages/mobile/src/screens/explore-screen/SearchExploreScreen.tsx
- packages/mobile/src/screens/explore-screen/components/ArtistSpotlight.tsx
- packages/mobile/src/screens/explore-screen/components/BestOfAudiusTiles.tsx
- packages/mobile/src/screens/explore-screen/components/ExploreContent.tsx
- packages/mobile/src/screens/explore-screen/components/ExploreSection.tsx
- packages/mobile/src/screens/explore-screen/components/FeaturedPlaylists.tsx
- packages/mobile/src/screens/explore-screen/components/FeaturedRemixContests.tsx
- packages/mobile/src/screens/explore-screen/components/LabelSpotlight.tsx
- packages/mobile/src/screens/explore-screen/components/MoodsGrid.tsx
- packages/mobile/src/screens/explore-screen/components/ProgressiveScrollView.tsx
- packages/mobile/src/screens/explore-screen/components/SearchExploreHeader.tsx
- packages/mobile/src/screens/explore-screen/components/SearchInput.tsx
- packages/mobile/src/screens/search-screen/RecentSearches.tsx
- packages/mobile/src/screens/search-screen/SearchScreen.tsx
- packages/mobile/src/screens/search-screen/searchState.tsx
Refactors components into smaller chunks
Adds ProgressiveScrollView to roll out content
> [PE-6389] Explore screen refactor and performance

- .circleci/src/commands/@mobile-commands.yml
Reverts AudiusProject/audius-protocol#12209
> Revert "Update bundler version to fix android builds"

- packages/common/src/api/tan-query/users/account/useWalletUser.ts
- packages/common/src/context/comments/commentsHooks.ts
- packages/common/src/hooks/useAccountSwitcher.ts
- packages/common/src/hooks/useCanSendChatBlast.ts
- packages/mobile/src/components/share-drawer/useShareToStory.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/CommentMentionNotification.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/CommentReactionNotification.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/CommentThreadNotification.tsx
- packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/selectArtistPreviewContext.tsx
- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
- packages/web/src/components/ai-attribution-modal/AiAttributionDropdown.tsx
- packages/web/src/components/collection/desktop/CollectionHeader.tsx
- packages/web/src/components/collections-table/CollectionsTableOverflowMenuButton.tsx
- packages/web/src/components/nav/desktop/AccountSwitcher/AccountSwitcher.tsx
- packages/web/src/components/notification/Notification/CommentMentionNotification.tsx
- packages/web/src/components/notification/Notification/CommentReactionNotification.tsx
- packages/web/src/components/notification/Notification/CommentThreadNotification.tsx
- packages/web/src/components/stat-banner/StatBanner.tsx
- packages/web/src/components/track/TrackStats.tsx
- packages/web/src/pages/collection-page/CollectionPageProvider.tsx
- packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx
- Fixes bug where premium albums were showing "unlocked" to the owner user
- Fixes bug where AI attribution search dropdown crashed
- Removes references to `useGetCurrentUserId` - this is a duped version of `useCurrentUserId`
web:stage
> Misc staging fixes (integration-test)

- packages/common/src/adapters/collection.ts
- packages/sdk/src/sdk/api/albums/types.ts
- packages/web/src/common/store/cache/collections/commonSagas.ts
- packages/web/src/common/store/cache/collections/createAlbumSaga.ts
- packages/web/src/common/store/upload/sagas.ts
- packages/web/src/pages/edit-collection-page/desktop/EditCollectionPage.tsx
- packages/web/src/pages/edit-collection-page/utils.ts
> [QA-2148] Fix album track reorder, improve edit-collection loading

- packages/common/src/api/tan-query/wallets/useAudioBalance.ts
- packages/common/src/store/wallet/utils.ts
- packages/mobile/src/screens/rewards-screen/RewardsScreen.tsx
- packages/mobile/src/screens/rewards-screen/TiersTile.tsx
- packages/web/src/components/ai-attribution-modal/AiAttributionDropdown.tsx
- packages/web/src/components/collection/desktop/CollectionHeader.tsx
- packages/web/src/components/tipping/tip-audio/SendTip.tsx
- use `fixed-decimal` in relevant places instead of old formatting utils
- use the audio balance hook
- fix playwright test for failing ai-attributed uploads (credit to @DejayJD)
Compared web/mobile UI against current stage, confirmed all consistent
> Use fixed-decimal and new hooks for tiers

- packages/mobile/src/screens/notifications-screen/Notifications/ArtistRemixContestSubmissionsNotification.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/TastemakerNotification.tsx
Fallout from https://github.com/AudiusProject/audius-protocol/pull/12164
Also fixing a different remix contest notification as well.
> [QA-2155] Fix mobile tastemaker notif

- packages/mobile/src/screens/upload-screen/screens/UploadCompleteScreen.tsx
- packages/mobile/src/screens/upload-screen/screens/UploadingTracksScreen.tsx
Fixes bad runtime issue due to me being silly
> Fix missing permalink runtime issue in upload complete screen

- packages/mobile/android/app/build.gradle
Updates android build version to current prod so next release is correct
> Upgrade android build in prep for next release

- packages/mobile/src/components/audio/AudioPlayer.tsx
Fixes issue with mobile playback due to some incorrect types in AudioPlayer around track owners
> [QA-2166] Fix broken mobile playback

- packages/common/src/services/audius-backend/solana.ts
Bug:
During withdraw flow, if the user pasted in a USDC user bank address (say from the "add cash" flow from a different audius account), the funds would disappear as they would land in an ATA of the user bank, which is inaccessible according to our current claimable tokens solana program.
This PR adds a check to see if the withdraw destination is already an ATA, and if so skip the ATA creation step.
Tested withdrawing to a different audius account user bank address, as well as to a normal solana address from phantom.
> [PE-6383] Fix ATA of ATA bug in withdraw flow

- packages/discovery-provider/plugins/pedalboard/apps/anti-abuse-oracle/src/actionLog.ts
- packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/config.ts
- packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/rewards.ts
- packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/sdk.ts
Bigger override score to compensate for proportional score threshold
deployed to box, ran attestations via postman
```
POST
{
"challengeId": "tt",
"challengeSpecifier": "2025-06-20:1",
"amount": 1000
}
```
https://discoveryprovider.audius.co/attestation/handle
> Increase aao override score

- packages/mobile/src/harmony-native/components/input/SelectablePill/SelectablePill.tsx
Fixes issue where isSelected and isControlled shouldn't change color on press
> [PE-6435] Fix selectable pill isSelected color

- packages/web/src/pages/explore-page/components/mobile/ColorTile.module.css
- packages/web/src/pages/explore-page/components/mobile/ExplorePage.tsx
Reduces number of explore page tiles since we are dropping smart collections anyway.
Also fixes tile title colors
> [PE-6432] Reduce mobile web explore page tiles

- packages/mobile/src/harmony-native/components/Button/Button/Button.tsx
- packages/mobile/src/harmony-native/components/Button/EntityActionButton/EntityActionButton.tsx
- packages/mobile/src/harmony-native/components/Button/PlainButton/PlainButton.tsx
Due to inconsistencies with how android handles animated-props, ive opted to disable them for android platform. Still doing a bit of research to see if there are fixes out there in the RN community. perhaps upgrading to latest may help here as well.
> [QA-2160 PE-6438] Fix Android icon colors

- packages/web/src/components/play-bar/desktop/PlayBar.tsx
The best way to improve performance would be to use refs, but this is a simple enough fix that is still more performant than what was there
> [PE-6427] Fix play bar duration

- packages/mobile/.eslintrc.js
- packages/mobile/REACTOTRON_SETUP.md
- packages/mobile/README.md
- packages/mobile/ReactotronConfig.js
- packages/mobile/index.js
- packages/mobile/package.json
Added [Reactotron](https://github.com/infinitered/reactotron) for RN network debugging
> Add reactotron for RN network debugging

- packages/web/src/common/store/cache/collections/createAlbumSaga.ts
- packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
- packages/web/src/common/store/pages/collection/sagas.js
- packages/web/src/pages/collection-page/CollectionPageProvider.tsx
Fixes createAlbum and createPlaylist by ensuring optimistic update calls "primeCollection" instead of "updateCollection"
Also fixes small bug where collections with no-tracks weren't calling fetchCollectionTracks
> [PE-6441] Fix create new collection

- packages/common/src/api/tan-query/search/useSearchResults.ts
- packages/mobile/src/screens/explore-screen/components/BestOfAudiusTiles.tsx
- packages/web/e2e/search.test.ts
Fixes issue where enabled false when no currentUserId. Also fixed useCallback dependency in mobile
> [PE-6433] Fix signed out search

- packages/common/src/api/tan-query/batchers/getUsersBatcher.ts
- packages/common/src/api/tan-query/tracks/useTrackByPermalink.ts
- packages/common/src/api/tan-query/users/useUserAlbums.ts
- packages/common/src/api/tan-query/users/useUserByHandle.ts
- packages/common/src/api/tan-query/users/useUserCollectibles.ts
- packages/common/src/api/tan-query/users/useUserPlaylists.ts
- packages/common/src/api/tan-query/users/useUserTracksByHandle.ts
- Fixes useUserByHandle causing unintentional extra API calls due to the fact that we weren't priming the userByHandle slice correctly
web:stage
> [PE-6431] Fix extra user/handle API calls

- packages/common/src/hooks/useFormattedAudioBalance.ts
- packages/mobile/src/screens/audio-screen/AudioScreen.tsx
Fix formatting on mobile $AUDIO screen (just match what web does)
Tested on local ios stage
> [PE-6450] Fix mobile audio balance formatting

- packages/mobile/src/components/audio-breakdown-drawer/AudioBreakdownDrawer.tsx
- packages/mobile/src/components/audio-breakdown-drawer/Wallet.tsx
Use new audio balance hooks + harmonize
after:
before:
> Update AudioBreakdownDrawer to use balance hooks and harmony

- packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFooter.tsx
> [QA-2184] Fix double $ signs in purchase flow

- packages/web/src/store/application/ui/buy-audio/sagas.ts
> Fix another incorrect instance of waitForValue

- packages/mobile/src/components/details-tile/DetailsTileHasAccess.tsx
- packages/web/src/components/track/GatedContentSection.tsx
> Remove extra dollar signs

- packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
- packages/web/src/components/track/GatedContentSection.tsx
> Fix more double dollar signs

- packages/common/src/api/tan-query/collection/useCollectionTracksWithUid.ts
- packages/harmony/src/components/scrollbar/Scrollbar.module.css
- packages/web/src/components/track/desktop/CollectionTile.tsx
- packages/web/src/components/track/desktop/TrackListItem.tsx
Fix clicking on track list item
> [QA-2198] Fix collection tile play/pause

- packages/web/src/components/track/desktop/CollectionTile.tsx
Missed issue where clicking collection tile should link to non-full route
> Fix collection tile link

- packages/common/src/api/tan-query/jupiter/constants.ts
- packages/common/src/api/tan-query/jupiter/useSwapTokens.ts
- packages/common/src/store/ui/buy-audio/constants.ts
- packages/common/src/store/ui/buy-sell/constants.ts
- packages/common/src/store/ui/buy-sell/useBuySellSwap.ts
- packages/common/src/store/ui/shared/tokenConstants.ts
Enable staging env for buy/sell flow
> [PE-6489] Make buy/sell work on stage

- packages/web/src/components/link/UserLink.tsx
- packages/web/src/components/track/desktop/CollectionTile.tsx
- packages/web/src/components/track/desktop/TrackTile.tsx
- packages/web/src/components/track/mobile/CollectionTile.tsx
- packages/web/src/components/track/mobile/TrackTile.tsx
- Fix trending playlist indices starting at 0
- Fix UserLink margin off centered on track pages
web:stage desktop & mobile
> [HOTFIX] Small ui bugs - UserLink margin & trending playlist indices

- packages/web/src/app/web-player/WebPlayer.jsx
Remove ToS banner update. To be re-enabled with another ToS change.
Local
> Remove ToS banner update

- packages/mobile/src/components/audio/AudioPlayer.tsx
- packages/mobile/src/components/now-playing-drawer/TrackingBar.tsx
- packages/mobile/src/components/scrubber/Slider.tsx
- packages/mobile/src/components/scrubber/usePosition.ts
Fixes issue where the scrubber and playback-position did not respect track 1x playback rate when playback rate is set differently for podcasts
> Fix podcast playback rate on mobile

- .circleci/src/jobs/@integration-jobs.yml
- .circleci/src/workflows/e2e.yml
> Rename integration-test to e2e-test

- packages/distro/src/distributors/prod.json
> Add more distros to distro.audius.co

- packages/discovery-provider/src/challenges/challenges.stage.json
> Temporarily change staging rewards cd to 0

- .circleci/src/jobs/@integration-jobs.yml
- .circleci/src/workflows/e2e.yml
> Fix e2e-init

- packages/common/src/store/account/sagas.ts
- packages/common/src/store/account/slice.ts
- packages/web/src/common/store/pages/signon/sagas.ts
- packages/web/src/pages/sign-up-page/utils/useDetermineAllowedRoutes.ts
Found several issues with guest account 
web:stage
> Fix guest account issues

- packages/common/src/api/tan-query/comments/useComment.ts
- packages/common/src/api/tan-query/comments/useHighlightComment.ts
- packages/common/src/api/tan-query/comments/utils.ts
Made a last second change to add a hook and didn't test it without the searchParam
> Fix useHighlightComment hook

- packages/common/src/utils/formatUtil.test.ts
- packages/common/src/utils/formatUtil.ts
also updated the unit test
_before_
_after_
web:prod
> Fix follower count formatting

- packages/common/src/store/buy-usdc/sagas.ts
Fixes issue where we are unnecessarily throwing when hitting TOKEN_ACCOUNT_NOT_FOUND
Should make a big difference with total sentry calls
> Fix TOKEN_ACCOUNT_NOT_FOUND events

- packages/web/src/components/comments/CommentSection.tsx
Update comment section to not display comments from other tracks when incorrect commentId param is set
> Fix incorrect comment display

- packages/fixed-decimal/README.md
- packages/fixed-decimal/examples/audio.ts
- packages/fixed-decimal/examples/fixedDecimal.ts
- packages/fixed-decimal/examples/math.ts
- packages/fixed-decimal/examples/usdc.ts
I feel like we should have something like this as a playground to make sure you know what you're doing
```
npx tsx examples/audio.ts
npx tsx examples/usdc.ts
npx tsx examples/fixedDecimal.ts
npx tsx examples/math.ts
```
> Add examples to @packages/fixed-decimal

- packages/web/src/components/nav/mobile/ConnectedNavBar.tsx
- packages/web/src/components/nav/mobile/NavBar.tsx
- packages/web/src/components/nav/mobile/NavBarActionDrawer.tsx
- packages/web/src/components/nav/mobile/NavContext.tsx
- packages/web/src/pages/audio-page/AudioPage.tsx
- packages/web/src/pages/collection-page/components/mobile/CollectionPage.tsx
- packages/web/src/pages/deactivate-account-page/components/mobile/DeactivateAccountPage.tsx
- packages/web/src/pages/not-found-page/NotFoundPage.tsx
- packages/web/src/pages/rewards-page/RewardsPage.tsx
- packages/web/src/pages/search-page/SearchPage.tsx
- packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
- packages/web/src/pages/trending-page/components/mobile/TrendingPageContent.tsx
- packages/web/src/pages/wallet-page/WalletPage.tsx
Change top right menu of mobile web to kebab that opens drawer to navigate to rewards, wallet, settings.
https://github.com/user-attachments/assets/9386758b-0cef-4443-b6f0-2cf575d6f3c7
> Mobile web top right menu

- packages/common/src/messages/comments.ts
- packages/mobile/src/components/comments/CommentBlock.tsx
- packages/mobile/src/components/comments/CommentDrawer.tsx
- packages/mobile/src/components/comments/CommentOverflowMenu.tsx
- packages/mobile/src/components/comments/CommentPreview.tsx
- packages/mobile/src/components/comments/CommentThread.tsx
- packages/mobile/src/screens/app-screen/AppTabScreen.tsx
Add highlighting and reordering for comment and comment replies on mobile
> [PE-6502, PE-6504] Add comment highlighting for mobile

- packages/web/src/components/artist/ArtistCard.tsx
- packages/web/src/components/artist/ArtistCardCover.module.css
- packages/web/src/components/artist/ArtistCardCover.tsx
- Color was wrong
- Didn't show 'label' for label accounts
```
```
> [QA-2218] Fix artist popover badge

- packages/web/src/components/comments/CommentSection.tsx
> [PE-6524] Add scroll to comment section on comment link

- packages/common/src/utils/route.ts
- packages/web/package.json
- packages/web/public/mockServiceWorker.js
- packages/web/src/app/web-player/WebPlayer.jsx
- packages/web/src/components/CoinApiMocks.tsx
- packages/web/src/components/WalletApiTest.tsx
- packages/web/src/index.tsx
- packages/web/src/pages/dev-tools/DevTools.tsx
- packages/web/src/pages/dev-tools/messages.ts
- packages/web/src/test/mocks/browser.js
- packages/web/src/test/mocks/wallet-api.ts
Adds mock endpoints for new coin endpoints to add in ui development
> Add msw for coin endpoints

- packages/discovery-provider/ddl/migrations/0150_bonk_artist_coin_stage.sql
For testing token holder message blasts on stage
> Create bonk artist coin account on stage

- packages/web/src/components/user-badges/UserBadges.tsx
> [PE-6539] Fix artist coin badge showing when 0 balance

- packages/mobile/src/app/App.tsx
> Restore gesture handler

- packages/common/src/adapters/notification.ts
While we wait for backend to update, adding this temporary fix to unblock staging notifications
> Temp fix missing comment_id in notification endpoint

- packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
- packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
Unable to start new chats on RC due to artist-coin UI leaking without a feature flag
> [QA-2239] Fix unable to start new chat

- packages/web/public/.well-known/apple-app-site-association
- packages/web/public/.well-known/apple-app-site-association-stage
Should not open in app and do mobile web instead
Will confirm on stage
> [PAY-3974] Add NOT /check to ASA

- packages/common/src/adapters/notification.ts
- packages/common/src/store/notifications/types.ts
- packages/mobile/src/components/comments/CommentPreview.tsx
- packages/mobile/src/hooks/useNotificationNavigation.ts
- packages/mobile/src/screens/notifications-screen/Notifications/CommentNotification.tsx
- packages/mobile/src/screens/notifications-screen/Notifications/CommentThreadNotification.tsx
- packages/sdk/src/sdk/api/generated/full/models/CommentMentionNotificationActionData.ts
- packages/sdk/src/sdk/api/generated/full/models/CommentNotificationActionData.ts
- packages/sdk/src/sdk/api/generated/full/models/CommentReactionNotificationActionData.ts
- packages/sdk/src/sdk/api/generated/full/models/CommentThreadNotificationActionData.ts
- packages/web/src/components/notification/Notification/CommentMentionNotification.tsx
- packages/web/src/components/notification/Notification/CommentNotification.tsx
- packages/web/src/components/notification/Notification/CommentReactionNotification.tsx
- packages/web/src/components/notification/Notification/CommentThreadNotification.tsx
- packages/web/src/components/notification/Notification/components/EntityLink.tsx
Updates comment notification commentIds to be optional.
Fixes mobile notification linking
> Update commentId types and fix mobile notification linking

- packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/validator.ts
> Lowercase wallet in relay recovery check

- eth-contracts/migrations/14_eth_rewards_manager_v2_migration.js
Copied this migration and didn't update the comment
n/a
> Fix comment on eth rewards manager v2 migration file

- packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
> Remove more coins section 

- packages/web/scripts/workers-site/index.js
https://developers.facebook.com/docs/sharing/webmasters/web-crawlers
worth a shot
> Add meta-externalfetcher to isBot check

- packages/common/src/hooks/useGatedContent.ts
- packages/web/src/components/link/UserLink.tsx
- packages/web/src/components/track/GatedContentSection.tsx
- packages/web/src/components/track/desktop/TrackTile.tsx
Fix issue with special access track tiles where hasPreview was true even when it should be "isPreviewable" which should only be true for premium tracks. Also fixed text-link issues introduced with search-explore "fixes"
> [QA-2229] Fix special access track tile

- packages/mobile/src/screens/app-screen/AppTabScreen.tsx
- packages/mobile/src/screens/user-list-screen/CoinLeaderboardScreen.tsx
- packages/mobile/src/screens/user-list-screen/UserList.tsx
- packages/mobile/src/screens/user-list-screen/UserListItem.tsx
- packages/mobile/src/screens/user-list-screen/index.ts
- packages/mobile/src/screens/wallet-screen/WalletScreen.tsx
- packages/mobile/src/screens/wallet-screen/components/BonkLeaderboardButton.tsx
> [PE-6574] Mobile Token Leaderboard

- packages/common/src/hooks/chats/useTrackPlayer.ts
- packages/web/src/pages/chat-page/components/ChatMessagePlaylist.tsx
Small update to pass along the uid with the play action so that playback will not break when playing playlist tiles in the ChatPage
> [QA-2241] Fix DMs playlist tile playback

- packages/discovery-provider/plugins/notifications/src/__tests__/mappings/comment.test.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/comment.ts
- packages/discovery-provider/plugins/notifications/src/utils/env.ts
Small change to add imageUrl to comment notifications to test rich push
> [PE-6591] Add imageUrl to comment notification

- packages/discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
Fixes issue where every user was considered shadowbanned
> Filter for actually shadow banned users

- packages/mobile/src/screens/app-screen/AccountPictureHeader.tsx
- packages/mobile/src/screens/explore-screen/SearchExploreScreen.tsx
- packages/mobile/src/screens/explore-screen/components/SearchExploreHeader.tsx
Improves various aspects of the mobile search/explore header. Reference ticket for list of all improvements
> [PE-6589] Improve mobile search/explore header

- packages/web/src/components/link/UserLink.tsx
- packages/web/src/pages/chat-page/components/ChatListItem.module.css
- packages/web/src/pages/chat-page/components/ChatListItem.tsx
- packages/web/src/pages/chat-page/components/ChatUser.tsx
Added indicator for minimized chat items and small update to the user link to make the full with prop work to fix the test overflow here
> [QA-2217] Add unread indicator for minimized chat list items

- .circleci/src/workflows/release.yml
To replace with audiusd release notes
> Disable discord release message

- packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
I clicked the drop down and clicked the one that was already pre-selected and I guess that changed something...
Ran on device with xcode
> Fix provisioning profiles for local dev

- packages/mobile/src/components/share-drawer/messages.ts
Copy looked weird, quick chat with Julian yielded this copy update
> Update copy for sharing with X

- packages/web/src/components/collection/CollectionCard.tsx
- packages/web/src/components/remix-contest-card/RemixContestCard.tsx
- packages/web/src/components/track/TrackCard.tsx
- packages/web/src/components/user-card/UserCard.tsx
Fixes issue where user-links were overflowing on cards
> Fix web card user links

- packages/mobile/src/components/enable-push-notifications-drawer/EnablePushNotificationsDrawer.tsx
- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Harmonize + improve renderImage flow on track screens
> [QA-2274] Fix cosign icon

- packages/common/src/messages/sign-on/socialMediaMessages.ts
- packages/common/src/models/User.ts
- packages/common/src/schemas/sign-on/pickHandleSchema.ts
- packages/harmony/src/components/button/SocialButton/SocialButton.stories.tsx
- packages/harmony/src/components/button/SocialButton/SocialButton.tsx
- packages/mobile/src/harmony-native/components/Button/SocialButton/SocialButton.tsx
- packages/mobile/src/screens/sign-on-screen/components/SignUpFlowXAuth.tsx
- packages/mobile/src/screens/sign-on-screen/components/SocialMediaSignUpButtons.tsx
- packages/mobile/src/screens/sign-on-screen/utils/socialMediaMessages.ts
- packages/web/src/components/first-upload-modal/FirstUploadModal.tsx
- packages/web/src/components/social-proof/SocialProof.tsx
- packages/web/src/components/x-auth/XAuthButton.tsx
- packages/web/src/pages/profile-page/components/SocialLink.tsx
- packages/web/src/pages/profile-page/components/SocialLinkInput.tsx
- packages/web/src/pages/profile-page/components/desktop/ProfileBio.tsx
- packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx
- packages/web/src/pages/profile-page/components/mobile/EditProfile.tsx
- packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
- packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
- packages/web/src/pages/rewards-page/components/modals/VerifiedUpload.tsx
- packages/web/src/pages/settings-page/components/desktop/VerificationModal.tsx
- packages/web/src/pages/settings-page/components/mobile/VerificationPage.tsx
- packages/web/src/pages/sign-up-page/components/HandleField.tsx
- packages/web/src/pages/sign-up-page/components/SignupFlowXAuth.tsx
- packages/web/src/pages/sign-up-page/components/SocialMediaLoginOptions.tsx
- packages/web/src/pages/sign-up-page/hooks/useSocialMediaLoader.ts
Update the signup buttons to use X instead of Twitter.
> [QA-2268] Fix X sign-up button

- .changeset/wet-cycles-look.md
- packages/harmony/src/components/button/SocialButton/SocialButton.tsx
> Fix race condition of social icons not being loaded before being used

- .circleci/config.yml
- .circleci/src/@continue_config.yml
- .circleci/src/jobs/@harmony-jobs.yml
- .circleci/src/workflows/harmony.yml
This reverts commit e0ed36bd62bf95aeb8d93f39458de82835eb69cc.
> Revert "Remove harmony workflow (#10314)"

- packages/web/src/pages/chat-page/components/CreateChatModal.tsx
Small update to increase the debounce time of the dms chat user search
> Increase the debounce time of the chat user search

- packages/web/src/components/search-users-modal/SearchUsersModal.tsx
- packages/web/src/pages/chat-page/components/CreateChatModal.tsx
Update the createChatModal to fetch the chat permissions for users so that the blocked chat flairs can be displayed and the user doesn't hit errors trying to create chats
> Update create chat modal to fetch chat permissions for user results

- packages/web/scripts/workers-site/index.js
- packages/web/src/components/meta-tags/MetaTags.tsx
- packages/web/wrangler.toml
Tested using ngrok and iframely
> Add support for oembeds

- packages/common/src/utils/decimal.ts
- packages/harmony/src/components/hover-card/HoverCardHeader.tsx
- packages/harmony/src/components/hover-card/types.ts
- packages/web/src/components/hover-card/ArtistCoinHoverCard.tsx
- packages/web/src/components/hover-card/AudioHoverCard.tsx
- packages/web/src/utils/coinMetrics.ts
* Update token insights currency formatting
* Add user badge hover card navigation
> [PE-6637, PE-6639] Artist Coin QA 1

- packages/web/src/components/artist/ArtistChip.module.css
- packages/web/src/components/artist/ArtistChip.tsx
- packages/web/src/components/user-list/UserList.tsx
Couple of updates to make the text ellipses work properly for user lists
> [PE-6638] Update coin leaderboard user list to handle long user names

- packages/discovery-provider/plugins/pedalboard/apps/relay/src/coreRelay.ts
No longer needed b/c the grpc is sunset.
Additionally fixes issue where each tx causes a setInterval to try to re-connect
Tested on staging discoveryprovider.staging.audius.co
> Remove grpc from client connections

- packages/common/src/api/tan-query/coins/useArtistCoin.ts
- packages/common/src/api/tan-query/coins/useArtistCoinInsights.ts
- packages/common/src/api/tan-query/coins/useArtistCoins.ts
- packages/common/src/api/tan-query/coins/useUserCoin.ts
Fixes issues where options was spread after enabled, negating it. This was causing lots of console errors
> Fix coin options

- packages/discovery-provider/integration_tests/tasks/test_index_user_bank.py
Accidentally broke lint things in my haste last night to fix prod issue
> Fix sort order

- dev-tools/compose/docker-compose.api.yml
- dev-tools/compose/docker-compose.yml
- dev-tools/environment/api.env
Adds an elasticsearch container for API to use in local dev, and has api reindex esindexer on start
> Setup elasticsearch for bridge in local dev

- packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx
Fixes issue where notification drawer top inset is incorrect after swiping down to open notification panel when drawer is open
> [QA-1076] Fix notification drawer top inset

- packages/mobile/src/screens/notifications-screen/Notifications/TipReceivedNotification.tsx
- packages/mobile/src/screens/notifications-screen/Reaction/Reaction.tsx
- packages/web/src/components/notification/Notification/TipReceivedNotification.tsx
Fixes issue where selected tip is not highlighting
> [QA-2182] Fix selected tip reaction

- packages/mobile/src/components/audio/AudioPlayer.tsx
React side effect race condition hell 🤮 
ios:prod + android:prod
> [QA-2255] Fix android playback issue

- packages/web/src/pages/chat-page/components/ChatHeader.tsx
Small update to fix the right side of the DMs Header.
> [PE-6681] Fix DMs Header right padding issue

- packages/web/src/pages/pick-winners-page/PickWinnersPage.tsx
- packages/web/src/pages/remixes-page/components/desktop/NewRemixesPage.tsx
> [PE-6745] Change 'likes' to 'favorites' on remix sort dropdown

- packages/mobile/src/components/comments/CommentDrawerContext.tsx
- packages/mobile/src/components/fields/PickArtworkField.tsx
- Fix cover art not showing on playlist edit
- Fix comment user links not closing drawer
ios sim
> [QA-2296|QA-2298] RC QA Fixes

- packages/mobile/src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx
- packages/web/src/components/menu/TrackMenu.tsx
- packages/web/src/components/menu/UserMenu.tsx
- packages/web/src/components/track-overflow-modal/components/MobileOverflowModal.tsx
> [QA-2299] "View Profile" instead of "Artist Page"

- packages/common/src/api/tan-query/jupiter/indirectSwapViaAudio.ts
- packages/common/src/api/tan-query/jupiter/useSwapTokens.ts
- packages/common/src/api/tan-query/jupiter/useTokenExchangeRate.ts
- packages/common/src/api/tan-query/jupiter/utils.ts
- packages/common/src/store/ui/buy-sell/useBuySellSwap.ts
- packages/web/src/components/buy-sell-modal/BuySellFlow.tsx
- packages/web/src/components/buy-sell-modal/TransactionSuccessScreen.tsx
- Introduced `executeIndirectSwap` to handle token swaps without a direct route
- Added fallback mechanism for token exchange rates when direct routes fail
- Implemented indirect quote calculation via AUDIO token
- Improved error handling and retry logic in swap transactions
- Refactored utility functions for token exchange rate and swap operations
`npm run web:prod` and play with swap flow
> [PE-6752][PE-6697] Swap flow QA updates

- packages/mobile/src/components/user-badges/UserBadges.tsx
- packages/web/src/components/user-badges/UserBadges.tsx
Let's disable these hooks when the artist coin feature flag is disabled.
Disabled feature flag on stage, confirmed both web and mobile look good + no broken functionality.
> Disable coin hooks in UserBadges when ff disabled

- packages/common/src/services/remote-config/feature-flags.ts
- packages/mobile/src/screens/explore-screen/SearchExploreScreen.tsx
- packages/mobile/src/screens/explore-screen/components/ExploreContent.tsx
- packages/mobile/src/screens/explore-screen/components/ForYouTracks.tsx
- packages/mobile/src/screens/explore-screen/components/SearchExploreHeader.tsx
Enables "for you", recently played, and quick links on mobile
Adds feature flag to turn off header animations to see how it feels with it off.
> Mobile explore improvements

- packages/mobile/android/build.gradle
Needed for prod deploy, Play Store now requires 35
> Upgrade android sdk target to 35

- packages/sdk/src/sdk/api/generated/default/apis/CoinsApi.ts
> Update SDK with /coins/ticker/:ticker change

- packages/web/src/components/user-token-badge/UserTokenBadge.tsx
Added interaction states to user token badge component and made clicking it navigate to profile page. 
`npm run web:prod` and hover over
> [PE-6771] Add hover states to user token badge component

- packages/common/src/store/ui/buy-sell/useGroupCoinPairs.ts
[This](https://github.com/AudiusProject/audius-protocol/pull/12876) PR caused a regression that caused non-AUDIO cards to be shown when the feature flag is off. This is incorrect behavior. Remedying 
`npm run web:prod` and turn off feature flag
> Only show audio card when feature flag is disabled

- packages/web/src/components/buy-sell-modal/components/InputTokenSection.tsx
Tooltip was rendering incorrectly in modal and flickering on hover. Needed to be mounted to body
`npm run web:prod` and hover over tooltip
> Fix tooltip positioning in buy/sell modal

- packages/commands/src/misc/claim-reward.ts
- packages/web/src/common/store/pages/audio-rewards/sagas.ts
Blocked by https://github.com/AudiusProject/audiusd/pull/194
claimed my rewards locally
> [API-100] Integrate new Rewards endpoint with client

- packages/web/src/components/hover-card/ArtistCoinHoverCard.tsx
> Use correct route on artist coin hover card

- packages/web/src/components/track/GatedConditionsPill.tsx
- packages/web/src/components/track/GatedContentSection.tsx
Small update to change the 'Buy Artist Coin' button behavior on web
> Update buy artist coin button to open buy sell modal on web

- packages/mobile/src/screens/artist-coins-explore-screen/ArtistCoinsExploreScreen.tsx
- packages/web/src/pages/artist-coins-explore-page/MobileArtistCoinsExplorePage.tsx
- packages/web/src/pages/artist-coins-launchpad-page/components/ArtistCoinsTable.tsx
> Filter $AUDIO from artist coins tables

- packages/mobile/src/components/details-tile/DetailsTileGatedAccess.tsx
- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
> small mobile lint fix for useArtistCoin hook

- packages/harmony/src/components/pill/Pill.tsx
- packages/web/src/pages/artist-coins-explore-page/ArtistCoinsExplorePage.tsx
- packages/web/src/pages/artist-coins-launchpad-page/components/ConnectedWalletHeader.tsx
- packages/web/src/pages/artist-coins-launchpad-page/components/ImageUploadArea.tsx
- packages/web/src/pages/artist-coins-launchpad-page/components/TokenInfoRow.tsx
- packages/web/src/pages/artist-coins-launchpad-page/components/WhyCreateCard.tsx
- packages/web/src/pages/artist-coins-launchpad-page/pages/BuyCoinPage.tsx
- packages/web/src/pages/artist-coins-launchpad-page/pages/ReviewPage.tsx
Fixes various launchpad QA items and updates launchpad review page values
> [PE-6791, PE-6838] Launchpad QA and updates

- packages/harmony/src/components/input/TextInput/TextInput.module.css
- packages/harmony/src/foundations/color/primitive.css
- packages/harmony/src/foundations/color/primitive.ts
- packages/harmony/src/foundations/color/semantic.ts
- packages/mobile/src/components/audio-rewards/RewardsBanner.tsx
- packages/mobile/src/components/core/LockedStatusBadge.tsx
- packages/mobile/src/components/details-tile/DetailsTileGatedAccess.tsx
- packages/mobile/src/components/lineup-tile/LineupTileAccessStatus.tsx
- packages/mobile/src/harmony-native/foundations/color/color.ts
- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
- packages/mobile/src/utils/theme.ts
- packages/web/src/pages/artist-coins-explore-page/ArtistCoinsExplorePage.tsx
- packages/web/src/pages/artist-coins-launchpad-page/components/LaunchPanel.tsx
Fixes artist-coin gradient in dark and matrix mode
> [PE-6852] Fix artist coin gradient

- packages/sdk/src/sdk/api/generated/default/models/Coin.ts
- packages/sdk/src/sdk/api/generated/default/models/UserCoin.ts
- packages/web/src/pages/asset-detail-page/components/AssetInfoSection.tsx
See https://github.com/AudiusProject/api/pull/402
Also, if website is missing, direct Learn More to the artist profile. Better than nothing.
> [PE-6856] Add check to see if the coin has a discord before rendering

- packages/common/src/store/ui/buy-sell/useBuySellSwap.ts
- packages/web/src/components/track/GatedConditionsPill.tsx
> Invalidate token owner tracks on token swap

- packages/common/src/messages/coinDetailsMessages.ts
- packages/web/src/pages/artist-coins-launchpad-page/components/TokenInfoRow.tsx
- packages/web/src/pages/asset-detail-page/components/ArtistCoinDetailsModal.tsx
- packages/web/src/pages/asset-detail-page/components/AssetInsightsOverflowMenu.tsx
> [PE-6870] Add artist coin details modal

- packages/web/src/components/profile-picture/ProfilePicture.jsx
> Fix profile picture lint

- packages/common/src/utils/coinMetrics.ts
> [PE-6854] Use bonding curve price before graduation

- packages/common/src/store/ui/buy-sell/hooks/useTokenData.ts
small update to fix the useTokenData hook from crashing with 0 value balances.
Open Question: Will there be an issue here with huge balances?
> Fix token data fixed decimal display decimals bug

- packages/web/src/pages/artist-coins-launchpad-page/LaunchpadPage.tsx
- packages/web/src/pages/artist-coins-launchpad-page/components/LaunchpadModals.tsx
- Refresh wallet balance on "get started" button click
web:prod
> [PE-6872] Make the balance refresh + clean up modal

- packages/discovery-provider/ddl/functions/chat_blast_audience.sql
- packages/discovery-provider/ddl/migrations/0163_remove_pool.sql
Porting over remix audience blast change and bonus extra migration
> sync ddl from api

- packages/web/src/pages/artist-coins-launchpad-page/pages/SetupPage.tsx
- packages/web/src/utils/imageProcessingUtil.ts
Provides better error messages when adding files that are too big and when trying to add invalid image file formats
> [PE-6873] Add file validation to launchpad

- packages/web/src/pages/profile-page/components/desktop/BuyArtistCoinCard.tsx
Problem is now the other boxes look weird without borders. Rabbit hole tho.
> [PE-6933] Border for buy buttons section on profile

- packages/harmony/src/components/modal/Modal.module.css
Fixes modal border-radius, color, and shadow. looks much better:
> [PE-6890] Improve nested modal styling

- packages/common/src/services/audius-backend/solana.ts
accidentally left out of https://github.com/AudiusProject/audius-protocol/pull/12976
> Improve ATA check

- packages/common/src/utils/formatUtil.ts
- packages/web/src/components/buy-sell-modal/BuySellFlow.tsx
- packages/web/src/components/hover-card/ArtistCoinHoverCard.tsx
- packages/web/src/components/hover-card/AudioHoverCard.tsx
- packages/web/src/components/profile-picture/ProfilePicture.jsx
- packages/web/src/pages/artist-coins-explore-page/MobileArtistCoinsExplorePage.tsx
- packages/web/src/pages/artist-coins-launchpad-page/components/ArtistCoinsTable.tsx
- packages/web/src/pages/asset-detail-page/AssetDetailPage.tsx
- packages/web/src/pages/asset-detail-page/components/AssetInsightsOverflowMenu.tsx
- packages/web/src/pages/asset-detail-page/components/BalanceSection.tsx
- packages/web/src/pages/asset-detail-page/components/mobile/ArtistCoinDetailsPage.tsx
- packages/web/src/pages/pay-and-earn-page/components/AudioCoinCard.tsx
- packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
- packages/web/src/pages/profile-page/components/desktop/BuyArtistCoinCard.tsx
> [PE-6878] Remove dollar sign from /coins/:ticker routes

- packages/web/src/pages/profile-page/components/desktop/BuyArtistCoinCard.tsx
> [PE-6929] Update buy coin card to pass the coin ticker

- packages/discovery-provider/nginx_conf/nginx_container.conf
nginx doesn't have access to env vars in the way you'd think
ran on stage box
> Fix broken nginx code

- packages/common/src/messages/coinDetailsMessages.ts
- packages/common/src/utils/coinMetrics.ts
> Add market cap to insights section

- packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
> Add top border to last element in "Your Coins" on odd number of coins

- packages/common/src/api/tan-query/jupiter/utils.ts
- packages/common/src/services/audius-backend/solana.ts
- packages/discovery-provider/plugins/notifications/package-lock.json
- packages/discovery-provider/plugins/notifications/src/__tests__/mappings/usdcTransfer.test.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcTransfer.ts
- packages/discovery-provider/plugins/notifications/src/types/notifications.ts
- packages/discovery-provider/plugins/pedalboard/apps/mri/.gitignore
- packages/discovery-provider/src/models/users/usdc_transactions_history.py
- packages/discovery-provider/src/tasks/index_user_bank.py
My original change in #12994 didn't cut it. This is a transfer from user bank -> root wallet (not user bank -> user bank DUH!). Please review second + third commits only, first is just a revert.
Real fix (for now) is adding memo. Also fix constant refreshing on Withdrawals tab of USDC history, and filter out internal_transfers from query response.
Longer term fix should be to index & store root wallet alongside a user. That's a thing for another day.
FE code works: https://explorer.solana.com/tx/41SZvaazRieWD2qXAuN3hZFakzzpx993tLyQwEf4juzn3eauUatsBTS7QdQkZuAnDUHSxZcokBpLHDKoPDYYuJrW
BE code is super simple, will validate against stage
> [PE-6607] Skip usdc transfer email for internal tranfers

- packages/web/src/pages/artist-coins-launchpad-page/components/ArtistCoinsTable.tsx
> [PE-6961] Artist coins table sizing

- packages/web/src/pages/asset-detail-page/components/AssetInfoSection.tsx
> [PE-6974] Fix infinite spinning on artist coin details

- packages/common/src/adapters/coin.ts
- packages/common/src/api/tan-query/coins/useUserCoins.ts
- packages/common/src/store/ui/buy-sell/useBuySellSwap.ts
Fixes issue where an optimistic update was trying to hashid.parse a number, which was introduced when i updated the coin types from sdk to common/coin. Also added an adapter to useUserCoins
> Fix swap due to invalid optimistic update

- packages/web/src/pages/artist-coins-launchpad-page/LaunchpadPage.tsx
- packages/web/src/pages/artist-coins-launchpad-page/constants.ts
Two small launchpad fixes
- on chain desc no longer links to /$ticker
- Success modal showing lowercase ticker
> [PE-6913] Small launchpad fixes

- packages/web/src/components/page/Page.module.css
- packages/web/src/pages/artist-coins-launchpad-page/components/ArtistCoinsTable.tsx
1. Table missing number column
2. Table collapsing weirdly, etc.  - fixed by adjusting numbers
3. Wallet page min width
Lots of resizing of browser window
> [PE-6095][PE-6909][PE-6913][PE-6975] Fix misc layout issues

- packages/common/src/api/tan-query/wallets/useSendTokens.ts
- packages/common/src/api/tan-query/wallets/useTokenBalance.ts
- packages/common/src/store/ui/buy-sell/hooks/useTokenData.ts
- packages/web/src/components/hover-card/AudioHoverCard.tsx
- packages/web/src/components/send-tokens-modal/SendTokensConfirmation.tsx
- packages/web/src/components/send-tokens-modal/SendTokensFailure.tsx
- packages/web/src/components/send-tokens-modal/SendTokensInput.tsx
- packages/web/src/components/send-tokens-modal/SendTokensSuccess.tsx
> [PE-7001] Include staked AUDIO in the coin hover, exclude connected wallets from send modal

- packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
- packages/mobile/src/components/lineup-tile/LineupTileAccessStatus.tsx
> [PE-6988] Update mobile buy coins button to open the swap modal

- packages/mobile/src/components/user-link/UserLink.tsx
> [PE-6986] Mobile userbadges pressable

- packages/common/src/adapters/coin.ts
- packages/common/src/api/tan-query/coins/useArtistCoinByTicker.ts
- packages/common/src/messages/coinDetailsMessages.ts
- packages/mobile/src/screens/coin-details-screen/components/AssetInsightsOverflowMenu.tsx
- packages/web/src/components/CoinSuccessModal.tsx
- packages/web/src/pages/asset-detail-page/components/AssetInsightsOverflowMenu.tsx
Adds share coin to x ui for web and mobile
Also fixes issue with coin banner not loading due to byTicker not running "coinFromSdk". this was also needed for share to x logic to work
> [PE-6976 PE-6980] Share coin to X

- packages/common/src/messages/buySell.ts
- packages/common/src/messages/walletMessages.ts
- packages/mobile/src/screens/wallet-screen/components/LinkedWallets.tsx
- packages/mobile/src/screens/wallet-screen/components/YourCoins.tsx
- packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
Adds "discover artist coins" cta to your-coins section
Updates mobile ui up to spec
> [PE-7003] Add discover artist coins CTA to your coins section

- packages/web/src/components/send-tokens-modal/SendTokensConfirmation.tsx
- packages/web/src/components/send-tokens-modal/SendTokensInput.tsx
> [PE-7005] Fix send tokens confirmation balance

- .circleci/src/commands/@embed-commands.yml
- packages/embed/package.json
- packages/embed/src/components/titles/Titles.jsx
- Fix bug in decimal computation
- Fix the fact that `npm i @cf/wrangler` installs a version we aren't compatible with
```
npm run build
mv build-production build
npm run deploy:prod
```
> Fix embed player builds

- .circleci/src/commands/@embed-commands.yml
- .circleci/src/jobs/@embed-jobs.yml
💢 prod/production bug
build-production vs command of npm run build:prod
> Fix build params for embed deploy

- packages/web/src/pages/artist-coins-launchpad-page/components/TokenInfoRow.tsx
- packages/web/src/pages/asset-detail-page/components/ArtistCoinDetailsModal.tsx
> Remove information icons that don't have tooltip assigned

- packages/common/src/models/Analytics.ts
- packages/web/src/common/store/pages/signon/sagas.ts
> [QA-2285] Update sign in flow to handle deactivated accounts

- packages/web/src/components/buy-sell-modal/components/TokenDropdown.tsx
> [QA-2352] Increase size of dropdown to avoid wrapping

- packages/mobile/src/screens/coin-details-screen/components/CoinInfoCard.tsx
- packages/mobile/src/screens/profile-screen/BuyArtistCoinButton.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
- packages/web/src/pages/profile-page/components/mobile/BuyArtistCoinButton.tsx
- packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx
Adds buy button to mobile and mobile-web profile pages
> [PE-6989] Add buy artist coin to mobile profile page

- packages/web/src/pages/profile-page/components/desktop/BuyArtistCoinCard.tsx
Updates coin tile by adding name and dropping description
> [PE-6991] Update profile page buy artist coin card

- comms/discovery/pubkeystore/recover_core.go
see description here https://github.com/AudiusProject/audiusd/pull/206
> trim prefix for comms pubkey recover

- packages/common/src/hooks/useAccessAndRemixSettings.test.ts
- packages/create-audius-app/examples/react-hono/package.json
- packages/create-audius-app/examples/react/package.json
- packages/mobile/src/screens/user-list-screen/UserList.tsx
- packages/sdk/src/sdk/config/development.ts
- packages/sdk/src/sdk/config/production.ts
- packages/sdk/src/sdk/config/staging.ts
- packages/web/src/pages/profile-page/ProfilePage.test.tsx
* Fix web test
* Fix common test
* Fix mobile lint
* Somewhat fix create-audius-app, though some API change may be necessary too.
Ran tests locally
> Fix misc CI issues

- packages/common/src/utils/route.ts
- packages/web/src/pages/artist-coins-launchpad-page/components/LaunchpadModals.tsx
> [PE-6851] Add link for artist coin help in insufficient balance modal

- packages/web/src/pages/asset-detail-page/components/BalanceSection.tsx
- packages/web/src/pages/asset-detail-page/components/OpenAppDrawer.tsx
- packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
- packages/web/src/pages/wallet-page/WalletPage.tsx
> [PE-6848] Update YourCoins buy button to show open app drawer on mobile web

- .changeset/witty-wasps-search.md
- packages/create-audius-app/examples/react-hono/src/client/App.tsx
- packages/create-audius-app/examples/react-hono/src/index.tsx
- packages/create-audius-app/examples/react-hono/vite.config.ts
- packages/create-audius-app/examples/react/src/App.tsx
- packages/create-audius-app/examples/react/src/hooks/useSdk.ts
- packages/sdk/src/sdk/api/notifications/NotificationsApi.test.ts
- packages/sdk/src/sdk/api/playlists/PlaylistsApi.test.ts
- packages/sdk/src/sdk/api/tracks/TracksApi.test.ts
- packages/sdk/src/sdk/middleware/addAppInfoMiddleware.ts
- packages/sdk/src/sdk/middleware/addRequestSignatureMiddleware.ts
- packages/sdk/src/sdk/sdk.ts
- packages/sdk/src/sdk/services/EntityManager/EntityManager.test.ts
* OAuth / create audius app not working due to missing basePath when hitting developer apps
* Add apiKey/apiSecret signing when no hedgehog login is present
replace @audius/sdk in create-audius-app with file:../../../sdk
```
cd packages/create-audius-app/examples/react-hono
npm i
npm run build
npm start
```
```
cd packages/create-audius-app/examples/react
npm i
npm run build
npm start
```
Test logging in, loading tracks, etc.
> Fix app signing & create-audius-app

- packages/web/src/hooks/useLaunchCoin.ts
- packages/web/src/pages/artist-coins-launchpad-page/constants.ts
- packages/web/src/pages/artist-coins-launchpad-page/pages/BuyCoinPage.tsx
Tested:
Ran through create flow + first buy
> [PE-7056] Misc fixes

- packages/web/src/pages/pay-and-earn-page/components/AudioCoinCard.tsx
- packages/web/src/pages/pay-and-earn-page/components/CoinCard.tsx
> Fix double $$ on $AUDIO

- packages/common/src/models/Launchpad.ts
- packages/web/src/pages/artist-coins-launchpad-page/LaunchpadPage.tsx
- packages/web/src/pages/artist-coins-launchpad-page/components/AgreeToTerms.tsx
- packages/web/src/pages/artist-coins-launchpad-page/pages/ReviewPage.tsx
- packages/web/src/pages/artist-coins-launchpad-page/pages/SplashPage.tsx
- packages/web/src/pages/artist-coins-launchpad-page/validation.ts
> [PE-7022] Add checkbox to agree to artist-coin terms

- .changeset/clean-hotels-end.md
- packages/sdk/src/sdk/sdk.ts
Fix comms failing to connect due to /v1 being added to URLs
`npm run web:stage` and ensure DMs work
> fix comms base endpoint

- packages/common/src/services/remote-config/feature-flags.ts
- packages/web/src/pages/artist-coins-explore-page/ArtistCoinsExplorePage.tsx
- packages/web/src/pages/artist-coins-launchpad-page/LaunchpadPage.tsx
- packages/web/src/pages/artist-coins-launchpad-page/pages/SplashPage.tsx
- packages/web/src/pages/sign-up-page/components/layout.tsx
- packages/web/src/pages/sign-up-page/utils/useDetermineAllowedRoutes.ts
> Add feature flag for launchpad verification check

- packages/common/src/schemas/sign-on/finishProfileSchema.ts
- packages/mobile/src/screens/sign-on-screen/screens/FinishProfileScreen.tsx
- packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
Dont allow empty profile image during sign-up
> [PE-7090] Don't allow empty profile image

- packages/web/src/components/buy-sell-modal/components/InputTokenSection.tsx
- packages/web/src/components/buy-sell-modal/components/OutputTokenSection.tsx
- packages/web/src/components/buy-sell-modal/components/TokenDropdown.tsx
Turned isSearchable on. Also added some missing dollar signs to input adornment texts
https://github.com/user-attachments/assets/cd659d5b-427b-4b14-a5ba-432f8a6cfe19
> [PE-7084] Add filter to token dropdown

- packages/web/src/hooks/useExternalWalletSwap.ts
- packages/web/src/pages/artist-coins-launchpad-page/components/LaunchpadBuyModal.tsx
Fix buy audio on launchpad showing optimistic change that gets cleared out by polling (them comes back)
Fix here is to wait for the balance hook to show updates
Note: this means it takes like 10~15s more time in the loading modal but oh well
> Launchpad buy audio flow fix

- packages/common/src/store/ui/buy-sell/useBuySellSwap.ts
idk why this changed but we were accessing the tq data incorrectly
local web prod
https://github.com/user-attachments/assets/5768487e-03d1-4273-8ed0-b00af0538b80
> [PE-7104] Fix optimistic token gate unlock

- packages/mobile/src/screens/artist-coins-explore-screen/ArtistCoinsExploreScreen.tsx
With page size 10:
https://github.com/user-attachments/assets/f3631cfc-6aea-4747-9aca-d0c2fb999745
> [PE-6843] Mobile artist coin explore pagination

- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/launchpad/getKeypair.ts
- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/launchpad/launch_coin.ts
- packages/discovery-provider/plugins/pedalboard/packages/storage/src/index.ts
Use keypairs from table if available, default to Keypair.generate()
TBA!
> [PE-6779] Use sol_keypairs table to populate artist coin mints

- packages/web/src/components/buy-sell-modal/components/InputTokenSection.tsx
- packages/web/src/components/buy-sell-modal/components/OutputTokenSection.tsx
- packages/web/src/components/buy-sell-modal/components/TokenDropdown.tsx
This reverts commit e2efd3d5a8a86756ea0e9a918d72e9bd42ea165d.
> Reapply "[PE-7084] Add filter to token dropdown (#13135)" (#13141)

- packages/web/src/app/web-player/WebPlayer.jsx
Enable ToS banner. To be reverted 10.8.25.
> Enable ToS banner

- packages/web/src/components/frosted/Frosted.tsx
> Fix layout in frosted component

- packages/mobile/src/screens/buy-sell-screen/ConfirmSwapScreen.tsx
Small change to drop title while confirmation in progress
> [PE-7038] Remove confirm details title

- packages/common/src/store/ui/buy-sell/constants.ts
- packages/common/src/utils/route.ts
- packages/mobile/src/screens/coin-details-screen/components/AssetInsightsOverflowMenu.tsx
- packages/web/src/components/CoinSuccessModal.tsx
- packages/web/src/components/hover-card/ArtistCoinHoverCard.tsx
- packages/web/src/components/hover-card/AudioHoverCard.tsx
- packages/web/src/components/profile-picture/ProfilePicture.jsx
- packages/web/src/pages/artist-coins-explore-page/MobileArtistCoinsExplorePage.tsx
- packages/web/src/pages/artist-coins-launchpad-page/LaunchpadPage.tsx
- packages/web/src/pages/artist-coins-launchpad-page/components/ArtistCoinsTable.tsx
- packages/web/src/pages/asset-detail-page/components/AssetInsightsOverflowMenu.tsx
- packages/web/src/pages/edit-coin-details-page/EditCoinDetailsPage.tsx
- packages/web/src/pages/pay-and-earn-page/components/AudioCoinCard.tsx
- packages/web/src/pages/pay-and-earn-page/components/YourCoins.tsx
- packages/web/src/pages/profile-page/components/desktop/BuyArtistCoinCard.tsx
Fixes issue where $$ showed up for AUDIO since the ticker constant had a $. went ahead and cleaned up a bunch of coinPage routes in the process
> [PE-7115] Remove $ from AUDIO_TICKER

- packages/common/src/api/tan-query/coins/useUserCreatedCoins.ts
- packages/common/src/messages/buySell.ts
- packages/mobile/src/components/artist-coin-details-drawer/ArtistCoinDetailsDrawer.tsx
- packages/mobile/src/components/buy-sell/CryptoBalanceSection.tsx
- packages/mobile/src/components/core/BalanceSection.tsx
- packages/mobile/src/components/send-tokens-drawer/components/SendTokensConfirmation.tsx
- packages/mobile/src/components/send-tokens-drawer/components/SendTokensFailure.tsx
- packages/mobile/src/components/send-tokens-drawer/components/SendTokensInput.tsx
- packages/mobile/src/components/send-tokens-drawer/components/SendTokensSuccess.tsx
- packages/mobile/src/screens/buy-sell-screen/components/PoweredByJupiter.tsx
- packages/web/src/components/buy-sell-modal/CryptoBalanceSection.tsx
- packages/web/src/components/send-tokens-modal/SendTokensConfirmation.tsx
- packages/web/src/components/send-tokens-modal/SendTokensFailure.tsx
- packages/web/src/components/send-tokens-modal/SendTokensInput.tsx
- packages/web/src/components/send-tokens-modal/SendTokensSuccess.tsx
- packages/web/src/pages/asset-detail-page/components/ArtistCoinDetailsModal.tsx
- packages/web/src/pages/asset-detail-page/components/BalanceSection.tsx
- packages/web/src/pages/edit-coin-details-page/EditCoinDetailsPage.tsx
Adds a bunch of missing $ and updates some text styles
> Various UI fixes

- packages/mobile/src/screens/wallet-screen/components/AudioCoinCard.tsx
- packages/mobile/src/screens/wallet-screen/components/YourCoins.tsx
Also noticed Audio icon was wrong size
> [PE-7118] Caret in mobile artist coin discover

- packages/web/src/components/buy-sell-modal/components/TokenDropdown.tsx
Slight restructuring of the TokenDropdown component to add the filter input
https://github.com/user-attachments/assets/0e070346-cfee-4100-b235-6bafdbe91b4f
> Add filter input to token dropdown

- packages/common/src/messages/buySell.ts
- packages/mobile/src/components/buy-sell/InputTokenSection.tsx
- packages/web/src/components/buy-sell-modal/components/InputTokenSection.tsx
- packages/web/src/pages/artist-coins-launchpad-page/components/LaunchpadBuyModal.tsx
> [PE-7120] Update available to trade tooltip copy

- packages/mobile/src/components/artist-coin-details-drawer/ArtistCoinDetailsDrawer.tsx
- packages/web/src/pages/asset-detail-page/components/ArtistCoinDetailsModal.tsx
Fixes audio details on mobile to use coingecko data, matching web
> [PE-7130] Fix mobile audio details

- packages/mobile/src/components/navigation-container/NavigationContainer.tsx
Fixes subtle issue where /wallet-connect matched with /wallet, redirecting us to /wallet page. Added a check to ensure exact match for /wallet, /wallet/..., and wallet?param=
> [PE-7131] Fix wallet connect

- eth-contracts/Dockerfile
- eth-contracts/scripts/setup-dev.js
As title
Used image locally to test devnet
> Add validator service type to ganache dev container

- packages/web/src/components/mobile-page-container/MobilePageContainer.tsx
- packages/web/src/components/page/Page.tsx
- packages/web/src/pages/asset-detail-page/AssetDetailPage.tsx
Fixes issue where the ogTitle should be different from the visual title
> Fix artist coin details title
