AudiusProject/apps

libs/package-lock.json
libs/package.json

#1747 1747
1. Test 1
2. Test 2
3. Test 3\
...

Libs 1.2.17

---

discovery-provider/src/queries/get_attestation.py
discovery-provider/tests/test_get_attestation.py
discovery-provider/tests/test_get_challenges.py

Updates the get_attestation logic and updates the corresponding test to verify the wallet
Fixes AUD-822
Same test with updated logic
manually

Fix attestation logic

---

identity-service/src/notifications/sendNotificationEmails.js
identity-service/src/routes/tiktok.js

1. Test 1
2. Test 2
3. Test 3\
...

Use logger.info in email notification logs

---

identity-service/src/notifications/sendNotificationEmails.js

1. Test 1
2. Test 2
3. Test 3\
...

Fix zero email notifs log

---

libs/src/services/creatorNode/index.js

Add polling
1. Run client against stage & upload track/blocked request to status and then unblocked and saw successful upload
...
For features that are critical or could fail silently please …

Add try catch to polling upload logic

---

discovery-provider/src/tasks/index_solana_plays.py

Fix minor reference error
Validated manually

Correct ref to event bus in Solana plays

---

solana-programs/reward-manager/cli/src/main.rs

* Add CLI functionality to confirm removal of a given sender from multi party ack
Tested on devnet
For features that are critical or could fail silently please describe the …

RewardManager CLI - Multisig Delete Sender

---

libs/src/api/track.js
libs/src/services/creatorNode/index.js

Adds retries:
- Single track upload
- Associate track calls
- Increased upload file retries 2 -> 3
- General creator node makeRequest
Linked libs to client
1. Create account
2. Upload track
3. Upload album
4. Set profile pic / cover photo 
...
If this PR touches a critical flow (such as Indexing, Uploads, Gateway or the Filesystem), make sure to add the …

Add more retries

---

identity-service/sequelize/migrations/20210813190309-add-tiktok-link.js
identity-service/src/models/socialhandles.js
identity-service/src/routes/socialHandles.js

This PR adds TikTok to `SocialHandles`
1. Test 1
2. Test 2
3. Test 3\
...

AUD-756 Add tiktok to social handles

---

libs/package-lock.json
libs/package.json

Libs 1.2.18

---

identity-service/src/routes/healthCheck.js

The check is slow => The check is not slow
1. Ran stack locally and hit /eth_balance_check
...
For features that are critical or could fail silently please describe the monitoring/alerting …

Parallelize balance check

---

service-commands/src/commands/service-commands.json
solana-programs/reward-manager/cli/src/main.rs

Changing reward manager authority successfully:
```jsx
cargo run change-reward-manager-authority --current-authority 2HYDf9XvHRKhquxK1z4ETJ8ywueZcqEazyFZdRfLqGcT --new-authority 23rFqPVKroFf68u8nj8FoKHE6XL4nsmgV8zZQsMr23X3 --reward-manager FSKZ8aMEXt3dk7U6Z2anNPy26Ddp4CW8xLZVgykYQZfW
Finished dev [unoptimized + debuginfo] target(s) in 0.19s
Running `target/debug/audius-cli change-reward-manager-authority …
```

Enable authority update in CLI

---

libs/src/index.js
libs/src/services/discoveryProvider/index.js

1. Test 1
2. Test 2
3. Test 3\
...

Update reselection timeouts

---

libs/package-lock.json
libs/package.json

1. Test 1
2. Test 2
3. Test 3\
...

Bump libs to 1.2.20

---

discovery-provider/src/models/models.py
discovery-provider/src/queries/get_remixable_tracks.py
discovery-provider/tests/test_get_tracks.py

Updated the remixables query to filter tracks with deleted stems
Updated the test

Update remixables query to filter tracks with deleted stems and update test

---

creator-node/.version.json
discovery-provider/.version.json

1. Test 1
2. Test 2
3. Test 3\
...

Bump version to 0.3.42

---

identity-service/src/routes/healthCheck.js

Following up https://github.com/AudiusProject/audius-protocol/pull/1753 but for POA balance checks.
1. Ran locally and hit /balance_check
For features that are critical or could fail …

Parallelize poa balance check

---

service-commands/scripts/init-repos.sh

1. Test 1
2. Test 2
3. Test 3\
...

Link libs on init repos

---

service-commands/scripts/A

1. Test 1
2. Test 2
3. Test 3\
...

Change default instance, add sleep before ssh

---

.circleci/config.yml
mad-dog/package.json
service-commands/package.json
service-commands/scripts/rewardManagerLocal.js
service-commands/src/commands/service-commands.json

* Enable local script to CreateSender, pulls appropriate wallet number + eth address, enables generic eth address
* Validated locally
For features that are critical or could fail silently …

RewardManager - CreateSender Local

---

.github/pull_request_template.md

1. Test 1
2. Test 2
3. Test 3\
...
How long did it take to notice I didn't fill out …

Update PR template to not show boilerplate

---

identity-service/sequelize/migrations/20210824180845-add-email-index-users-table.js

This PR adds an index for the email column in the Users table in identity. This is to prevent the query in the `user` endpoint from being slow
The default name of the index is `users_email`
1. Test 1
2. Test 2
3. Test 3\
...

Index email column in Users table

---

mad-dog/src/operations.js
mad-dog/src/tests/test_integration.js
service-commands/src/commands/tracks.js
service-commands/src/libs.js

Improve test coverage, expanding on what is currently present in coreIntegration by adding social actions starting with reposts.

Add repost to core integration test

---

discovery-provider/src/solana/solana_parser.py
discovery-provider/tests/test_index_rewards_manager.py

Fixes the solana parsing of the eth address
Updated the test
manually

Fix parsing solana tx eth addr

---

creator-node/.version.json
discovery-provider/.version.json

Bump .version.json to v0.3.43

---

discovery-provider/default_config.ini
discovery-provider/src/queries/get_health.py
discovery-provider/src/queries/get_health_test.py
discovery-provider/src/utils/config.py

We want to add flags to our protocol dashboard to show which country a service is based out of. In order to do that we need the latitude/longitude.
Added latitude and longitude to health check verbose test.

[ASI-607] Add latitude and longitude to discovery health check

---

discovery-provider/alembic/versions/b40b074a75be_add_related_artists.py

Add IF NOT EXISTS in case providers already have the extension

---

service-commands/src/commands/service-commands.json

* Keep history longer for convenience in dev
* Tx history maintained for >1 day on remote box

Extend ledger size (Test Validator)

---

discovery-provider/src/solana/solana_client_manager.py

Add more logs to solana client manager for better diagnosability

Add more logs to solana client manager

---

libs/package-lock.json
libs/package.json
libs/src/index.js
libs/src/services/solanaWeb3Manager/index.js
libs/src/services/solanaWeb3Manager/rewards.js
libs/src/services/solanaWeb3Manager/transfer.js
libs/src/services/solanaWeb3Manager/utils.js
service-commands/scripts/rewardManagerLocal.js

Needed to surface some Solana internals for use in AAO. Also cleaned up some duplicate code.
Tested in AAO.

[AUD-915] Break out Solana utils for AAO

---

identity-service/scripts/fundSolanaFeePayer.js

Script to fund fee payer in identity. I'm open to suggestions on location of the script
Ran script to fund on prod

Solana fee payer fund script

---

solana-programs/claimable-tokens/program/src/processor.rs
solana-programs/claimable-tokens/program/tests/tests.rs

Remove default transfer condition for claimable tokens processing

Fix 0 condition - ClaimableToken

---

libs/scripts/test.sh

not sure why this fails but this lines up the order of operations with `circleci-test.sh`, which always succeeds
didn't catch this bug in CI bc it runs `circleci-test.sh` but locally calling `npm test` will run `test.sh` which deterministically fails in the same spot (see below)
guessing that the unit tests now have a dependency on contract migration 🤷‍♂️
```
{"indexed":false,"name":"_address","type":"address"}],"name":"ContractRemoved","type":"event","signature":"0x266f45300baf5abcdb8653dcec68c843b20fb984df2fae4cd1e3fecaf4619952"},{"anonymous":false,"inputs":[{"indexed":false,"name":"_name","type":"bytes32"},{"indexed":false,"name":"_oldAddress","type":"address"},{"indexed":false,"name":"_newAddress","type":"address"}],"name":"ContractUpgraded","type":"event","signature":"0x8b3c9342e23b53 …
```

Fix libs non-ci tests

---

.circleci/config.yml
discovery-provider/src/models/models.py
discovery-provider/src/schemas/playlist_schema.json

Indexing stalled for playlist because field contained \x00 character which wasn't stripped out before db write. We validate in other models, but not playlists. I added extremely basic type validation.
Tested on prod

Playlist indexing hotfix 09/01

---

creator-node/src/snapbackSM/peerSetManager.js

This is to update err msgs for more clarity. 
No tests necessary.
These updated msgs will be helpful when observing reconfig logs in loggly.

Add thresholds for err msgs in peerSetManager

---

mad-dog/package.json
mad-dog/src/operations.js
mad-dog/src/tests/test_integration.js
service-commands/src/commands/playlists.js
service-commands/src/commands/tracks.js
service-commands/src/libs.js

Add playlist operations to mad dog, including playlist creation and adding tracks to those playlists.

Add playlist actions to mad dog

---

.circleci/config.yml
discovery-provider/alembic/versions/169519f975c2_set_eth_start_block.py
discovery-provider/src/app.py
discovery-provider/src/eth_indexing/event_scanner.py
discovery-provider/src/tasks/cache_user_balance.py
discovery-provider/src/tasks/index_challenges.py
discovery-provider/src/tasks/index_eth.py
discovery-provider/src/tasks/index_oracles.py
discovery-provider/src/tasks/index_rewards_manager.py

Create User balance if it does not exists
Sandbox production node
discovery node 4 & release onto foundation nodes

Fix add non-existing user balances

---

discovery-provider/src/eth_indexing/event_scanner.py

Rename last indexed eth block redis key
Manual

Rename last indexed eth block redis key

---

libs/package-lock.json
libs/package.json

Bump Libs 1.2.21

---

libs/src/services/solanaWeb3Manager/rewards.js

I made some simplifications to the function signature to create oracle attestations, but forgot to propagate this to the other places that use the function.
Tested E2E

Fix oracle attestation format

---

.circleci/config.yml

See also:
- [https://about.gitlab.com/blog/2019/09/11/how-to-avoid-broken-master-with-pipelines-for-merge-requests/](https://about.gitlab.com/blog/2019/09/11/how-to-avoid-broken-master-with-pipelines-for-merge-requests/)
- [https://devops.stackexchange.com/questions/4411/should-i-run-ci-on-merge-state-or-head-of-branch-in-a-pr](https://devops.stackexchange.com/questions/4411/should-i-run-ci-on-merge-state-or-head-of-branch-in-a-pr)
- [https://ideas.circleci.com/cloud-feature-requests/p/show-test-results-for-prospective-merge-of-a-github-pr](https://ideas.circleci.com/cloud-feature-requests/p/show-test-results-for-prospective-merge-of-a-github-pr)
-

After checkout, merge with parent to test changes against latest master

---

.circleci/config.yml

Fixes #1816 for the master branch by not merging with parent on that branch

Don't merge with parent in CI on master branch

---

discovery-provider/src/solana/solana_parser.py
discovery-provider/src/tasks/index_user_bank.py
discovery-provider/tests/test_index_rewards_manager.py
service-commands/src/commands/service-commands.json
solana-programs/claimable-tokens/cli/src/main.rs
solana-programs/claimable-tokens/program/src/processor.rs
solana-programs/claimable-tokens/program/src/utils/program.rs
solana-programs/claimable-tokens/program/tests/tests.rs

* Deserialize instruction data during user bank indexing and remove superfluous log
* Additional account verification

ClaimableTokens - rm msg! pubkey bytes, refactor indexing

---

mad-dog/src/tests/test_integration.js

Follow up to: https://github.com/AudiusProject/audius-protocol/pull/1834. 
Randomly emit multiple requests on each tick.  Verify thresholds at the end. Inject randomization in operations.

Add Mad Dog randomization

---

discovery-provider/src/tasks/index_rewards_manager.py
discovery-provider/tests/test_index_rewards_manager.py
eth-contracts/migrations/11_eth_rewards_manager_migration.js
libs/initScripts/configureLocalDiscProv.js
service-commands/config/convict.json
service-commands/scripts/registerAAO.sh
service-commands/scripts/rewardManagerLocal.js
service-commands/scripts/setup.js
service-commands/src/commands/service-commands.json
service-commands/src/setup.js
solana-programs/start.sh

- Adds service commands to bring up AAO
- Adds service command to register AAO with Solana Reward Mgr
- Brings all eth contracts, including eth rewards manager
- Writes out AAO config in eth rewards manager for consumption in AAO
- Writes out rewards config for discovery provider to consume for indexing
- Sets bash as default shell for exec-ing scripts from node (@hareeshnagaraj I think this is safe?)
- Trigger balance refresh on disbursement

[AUD-903] Fix local integration issues

---

solana-programs/reward-manager/program/src/error.rs
solana-programs/reward-manager/program/src/instruction.rs
solana-programs/reward-manager/program/src/processor.rs
solana-programs/reward-manager/program/src/state/sender_account.rs
solana-programs/reward-manager/program/src/state/verified_messages.rs
solana-programs/reward-manager/program/src/utils/mod.rs
solana-programs/reward-manager/program/src/utils/signs.rs

Add comments and cleanups to RewardManager

---

creator-node/default-config.json
creator-node/src/routes/users.js
creator-node/test/users.test.js
libs/src/services/creatorNode/index.js

Remove legacy user login, no change in behavior. 
No tests.

Remove legacy user login

---

discovery-provider/src/eth_indexing/event_scanner.py

Query user balance refresh by normal & lower case.
Is this the right change?
Pros -- it will work, for sure
Cons -- we store whatever the client spits to us as the wallet so long as the signature is valid. it maybe is lower cased? it maybe isn't lower cased? in either event, we could store everything as lower case in the db. that change would mean changes to the client as well, which depends on being able to query by wallet. https://github.com/AudiusProject/audius-client/blob/21ea3f3b68c52d7a6ce3165b062751916a5e75a7/src/store/token-dashboard/sagas.ts#L508
It also runs into the weirdness around solana wallets, which are invalid if they are lowercased unlike eth which are chill

Query by lower case

---

.circleci/config.yml
mad-dog/src/emitter.js
mad-dog/src/index.js
mad-dog/src/tests/test_integration.js

Follow up: https://github.com/AudiusProject/audius-protocol/pull/1843
Adds configuration for a longer test in the nightly workflow. However, it currently fails with `Max sync monitoring timeout reached for user`. This problem seems to come from extending the test from 100 seconds to 1000 but I'm not sure how to resolve it. The other user syncs fine. I've tried extending the timeout which didn't help.

Add mad dog nightly runs

---

discovery-provider/src/challenges/trending_challenge.py
discovery-provider/tests/test_trending_challenge.py

Update trending challenge specifier to be the date and rank
Also updated the test to reflect this
manually

Add date to challenge specifier

---

discovery-provider/src/queries/get_skipped_transactions.py
discovery-provider/src/utils/redis_cache.py
discovery-provider/tests/test_set_indexing_error.py

Update indexing error cache to use json serialize in place of pickle
Wrote a test to verify that you can still access the objects
manually

Use json serialize instead of pickle

---

service-commands/scripts/A

A script was hanging when waiting for instance to start. This PR is to properly check the response code. 
The response object: 
```
CompletedProcess(args=['ssh', '<host-name>, ':'], returncode=0)
```

Grab responsecode off of response

---

creator-node/.version.json
discovery-provider/.version.json

Bump release to v0.3.44

---

solana-programs/reward-manager/program/src/processor.rs
solana-programs/reward-manager/program/tests/transfer.rs
solana-programs/reward-manager/program/tests/utils.rs
solana-programs/reward-manager/program/tests/verify_transfer_signature.rs

Ensure occupation of verified messages account is not possible

---

solana-programs/reward-manager/program/src/error.rs
solana-programs/reward-manager/program/src/processor.rs
solana-programs/reward-manager/program/src/utils/mod.rs
solana-programs/reward-manager/program/tests/create_sender_public.rs
solana-programs/reward-manager/program/tests/transfer.rs
solana-programs/reward-manager/program/tests/utils.rs
solana-programs/reward-manager/program/tests/verify_transfer_signature.rs

More tests, fixes bug with duplicate operators

Add additional rewards manager tests

---

creator-node/src/components/healthCheck/healthCheckComponentService.js
creator-node/src/components/healthCheck/healthCheckComponentService.test.js
creator-node/src/components/healthCheck/healthCheckController.js
discovery-provider/src/queries/get_health_test.py

Add verbose health check data into normal health check. No data should be lost. This should allow the verbose health check to be deprecated.
1. Local test
2. Modified existing unit tests
health_check before
```
{
"data": {
"version": "0.3.43",
"service": "content-node",
"healthy": true,
"git": "",
"selectedDiscoveryProvider": "http://dn1_web-server_1:5000",
"creatorNodeEndpoint": "http://cn1_creator-node_1:4000",
"spID": 1,
"spOwnerWallet": "0xf3e979893e33ce47b35c3feec2cf548a1bb228cb",
"isRegisteredOnURSM": true,
"numberOfCPUs": 4,
"totalMemory": 16783568896,
"storagePathSize": 103880232960,
"meetsMinRequirements": false
},
"signer": "0xf3e979893e33ce47b35c3feec2cf548a1bb228cb",
"timestamp": "2021-09-13T20:13:55.047Z",
"signature": …
```

Combine verbose data into default content node health check

---

discovery-provider/requirements.txt

Fix discovery duplicate req
na
na

Fix discovery requirements.txt

---

discovery-provider/default_config.ini
discovery-provider/src/queries/notifications.py
discovery-provider/src/queries/response_name_constants.py
identity-service/default-config.json
identity-service/sequelize/migrations/20210830143757-create-solana-notifications.js
identity-service/sequelize/migrations/20210830144243-create-solana-notification-actions.js
identity-service/src/config.js
identity-service/src/models/solanaNotification.js
identity-service/src/models/solanaNotificationAction.js
identity-service/src/notifications/constants.js
identity-service/src/notifications/fetchNotificationMetadata.js
identity-service/src/notifications/formatNotificationMetadata.js
identity-service/src/notifications/index.js
identity-service/src/notifications/milestoneProcessing.js
identity-service/src/notifications/notificationProcessing.js
identity-service/src/notifications/notificationQueue.js
identity-service/src/notifications/processNotifications/challengeRewardNotification.js
identity-service/src/notifications/processNotifications/index.js
identity-service/src/notifications/sendNotifications/formatNotification.js
identity-service/src/notifications/sendNotifications/index.js
identity-service/src/notifications/sendNotifications/publishNotifications.js
identity-service/src/notifications/trendingTrackProcessing.js
identity-service/src/notifications/utils.js
identity-service/src/routes/notifications.js
libs/src/services/discoveryProvider/index.js
libs/src/services/discoveryProvider/requests.js

[WIP] [AUD-832]
Adding flow for indexing notifications from Solana to be able to handle notifications for things like challenge rewards

[WIP] [AUD-832] Add Solana notifications flow

---

eth-contracts/contracts/EthRewardsManager.sol
eth-contracts/contracts/IWormhole.sol
eth-contracts/contracts/WormholeClient.sol

Remove duplicate interface declaration

IWormhole.sol - Consume single interface

---

service-commands/scripts/A

Force A to use python 3.9

---

service-commands/scripts/A

Change default disk size to 256gb

---

creator-node/src/logging.js
libs/src/services/creatorNode/index.js

Reverts AudiusProject/audius-protocol#1879
Checking whether mad dog e2e tests can pass with this change reverted.

Revert "[ASI-615] X-Prefix CN user-generated req headers"

---

discovery-provider/src/tasks/index_solana_plays.py

* Explicitly log anon listen, reduce level to warning from error

Update anon listen log

---

discovery-provider/src/queries/get_users_cnode.py
discovery-provider/src/utils/session_manager.py

Maybe we should consider using sqlcommenter with Flask and sqlalchemy: https://google.github.io/sqlcommenter/python/flask/.
Tested locally and hit health_check verbose. Confirmed query comment. 
```
{ "levelno": 20,
"level": "INFO",
"msg": "SELECT\n            *\n            FROM\n            (\n                SELECT\n                \"user_id\",\n                \"wallet\",  ... - get_users_cnode",
"timestamp": "2021-09-22 00:47:54,723" }
```

Add query comments

---

libs/src/api/challenge.js
libs/src/index.js

- New single function to perform the entire challenge attestation flow
Tested against dev box

Add libs functionality for E2E challenge attestation flow

---

discovery-provider/alembic/versions/561ba1eca13a_add_slot_index.py

Fixes a merge "conflict" causing two alembic migrations to be the "heads"

Fix down revision for alembic head

---

libs/package-lock.json
libs/package.json

Bump libs 1.2.24

---

creator-node/.version.json
discovery-provider/.version.json

Bump version to 0.3.45

---

libs/src/api/user.js
libs/src/api/user.test.js

Fixes sorter on updateUserOps. I don't believe this is actually causing breakage, but it is absolutely the wrong behavior and hard to be totally sure :)
New unit tests

Update latest block sorter in user.js

---

discovery-provider/src/challenges/challenge_event_bus.py
discovery-provider/src/tasks/index.py

Enable trending challenge
reverts #1916 and adds the fix for registering the challenge

Enable trending challenge

---

solana-programs/reward-manager/program/src/error.rs
solana-programs/reward-manager/program/src/processor.rs
solana-programs/reward-manager/program/src/utils/mod.rs
solana-programs/reward-manager/program/src/utils/signs.rs
solana-programs/reward-manager/program/tests/transfer.rs
solana-programs/reward-manager/program/tests/verify_transfer_signature.rs

Fixes:
- Arbitrary reward recipient issue
- instructions_info spoofing issue

Add additional rewards manager fixes

---

libs/package-lock.json
libs/package.json

Fixes https://github.com/AudiusProject/audius-protocol/pull/1927

Libs 1.2.26

---

discovery-provider/scripts/openresty_log_convertor.py
discovery-provider/scripts/prod-server.sh

This PR ensures that the openresty access and error logs are piped to loggly
This has been tested on stage
Will continue monitoring this on prod

Pipe OpenResty logs to loggly for DP

---

discovery-provider/src/queries/get_repost_feed_for_user.py
discovery-provider/tests/test_get_repost_feed_for_user.py
discovery-provider/tests/utils.py

Fixes pagination in the `get_repost_feed_for_user` query and add corresponding tests. The primary issue here was that the pagination only took into account limit/offset on the query over the reposts table. If a track was found to be deleted later on, it would apply incorrectly towards the limit. A client could request 5 tracks, but only get back 4 (5th being deleted), so unless the lineup thought that things could be deleted, it would stop pagination thinking it had reached the EOL (end of lineup!).
This PR can be reviewed 1 commit at a time:
1 -- some typing and trivial test case
2 -- new test case that breaks
3 -- fix so the text case works
Also, this query runs in 50ms
```
select
"reposts"."repost_item_id",
"tracks"."title",
"playlists"."playlist_name"
from "reposts"
left outer join …
```

[AUD-992] Fix repost feed pagination

---

identity-service/src/routes/authentication.js
identity-service/test/authenticationTest.js

Restore an existing password if the user changes their password back to one they already used.
Added a test case

Restore existing Authentication records on change password

---

libs/package-lock.json
libs/package.json

Will include the new Solana relay changes.

Bump libs to 1.2.28

---

libs/package.json

Update libs version

---

libs/src/services/discoveryProvider/index.js

Fix v1 api retry storm, add comment

Fix retry storm

---

libs/package-lock.json
libs/package.json

Libs v1.2.30

---

discovery-provider/src/utils/helpers.py

OR fix for local dev: Add OR timeout, catch request errors.

---

discovery-provider/default_config.ini
discovery-provider/src/app.py

Add an env var to DP for hostname

---

creator-node/src/reqLimiter.js

the `batch_cids_exist` and `batch_image_cids_exist` routes were created specifically for consumption by sauron's KPI monitoring scripts. They have aggressive rate limits to prevent DOSing at 1 req / IP / 5sec. As a result, the monitoring scripts end up running much more slowly and retrying more frequently.
This PR adds a signature verification step to bypass this rate limit, to speed up the monitoring script run without compromising DOS security.

[ASI-711] Add rate limit override for valid SP on batch_cid routes, for use by sauron

---

discovery-provider/default_config.ini
discovery-provider/src/challenges/trending_challenge.py
identity-service/package-lock.json
identity-service/package.json
identity-service/src/config.js
identity-service/src/notifications/index.js

Update identity audius libs dependency for solana notifications api endpoint

Update identity @audius libs dep

---

discovery-provider/src/app.py

Hostname Fix for OpenResty

---

.circleci/config.yml
discovery-provider/src/app.py

Removes the hostname override we have on Flask
https://stackoverflow.com/questions/47002617/flasks-built-in-server-always-404-with-server-name-set/50854646
Tested on Stage

Remove override for Flask hostname

---

service-commands/scripts/setup.js

Default local setup to run sequentially until we fix race condition bringing up parallel nodes

Default no-parallel to true

---

discovery-provider/src/api/v1/models/users.py
discovery-provider/src/api/v1/users.py
discovery-provider/src/queries/get_track_history.py
discovery-provider/tests/test_get_history_for_user.py
discovery-provider/tests/utils.py

Expose a user's track history in discovery, the source of truth for plays post sol plays.
Tested locally. 
Example response `/v1/full/users/0MMZ6/history/tracks?user_id=0MMZ6&limit=44&offset=0`
```
{
"latest_chain_block": 134,
"latest_indexed_block": 24108743,
"signature": "0x05e64d0752c92a3a4941c69e94b055154ab921752b36b045c1b9e804ce75ae66469a30f088acb1ef41a25d276681aeeda04177acc9e9a546e592c78f7525063e1c",
"timestamp": "2021-11-09T17:12:50.409Z",
"version": {
"service": "discovery-node",
"version": "0.3.46"
},
"data": [
{
"timestamp": "2021-11-02 22:06:50",
"item_type": "track",
"item": {
"artwork": {
"150x150": "https://creatornode.audius.co/ipfs/QmcsvivZjMUT8MVBkv6LFsMJqcZspYBDuAmtyyrAwAymGc/150x150.jpg",
"480x480": "https://creatornode.audius.co/ipfs/QmcsvivZjMUT8MVBkv6LFsMJqcZspYBDuAmt …
```

Add user's track history endpoint 

---

discovery-provider/src/schemas/user_schema.json
discovery-provider/src/tasks/metadata.py
libs/src/api/user.js
libs/src/services/schemaValidator/schemas/userSchema.json

Update the Libs and DN schema to allow for the new `is_deactivated` flag and allow it to be indexed.
Tested E2E using libs to trigger indexing and verifying via the DN API.

Update User Schema with new is_deactivated flag

---

creator-node/.version.json
discovery-provider/.version.json

Bump to v0.3.47

---

service-commands/scripts/A

Add -y flag to apt install to facilitate provisioning

---

discovery-provider/src/queries/confirm_indexing_transaction_error.py
discovery-provider/src/tasks/index_metrics.py

Use endpoints from returned tuple instead of the tuple itself

Fix other node endpoints calls

---

libs/initScripts/helpers/version.js
libs/initScripts/mainnet.js
libs/src/services/ethContracts/serviceTypeManagerClient.js
libs/tests/governanceTest.js

Add the ability to "dry run" setting service version on chain to make generating data for Governance proposals via the dashboard easier.
Ran the script to generate values to use for the dashboard

Make generating data for governance proposals easier

---

service-commands/README.md
service-commands/scripts/A
service-commands/scripts/provision-dev-env.sh

rolls in `--fast` provisioning fixes while I am troubleshooting `--up` and bake in https://github.com/AudiusProject/audius-protocol/pull/2071

fixes for provisioning remote dev host with --fast flag

---

discovery-provider/tests/test_index_rewards_manager.py

Fix discovery node test broken in #1808 by adding reward manager account info to test data
Ran test

Fix discovery test broken in #1808

---

discovery-provider/.test.env
discovery-provider/src/queries/get_attestation.py
discovery-provider/src/utils/get_all_other_nodes.py
discovery-provider/tests/test_get_attestation.py
discovery-provider/tests/test_index_rewards_manager.py
libs/initScripts/local.js
service-commands/scripts/rewardManagerLocal.js
service-commands/src/commands/service-commands.json

Adds a dependency that wasn't in the config map. Updated code to be tolerant of that missing dependency.
Deployed to sandbox

Revert - revert AUD-726

---

creator-node/package-lock.json
creator-node/package.json
identity-service/package-lock.json
identity-service/package.json
service-commands/package-lock.json
service-commands/package.json

ASI-587 consume libs 1.2.31

---

identity-service/src/app.js

Update error handler in notification processor to continue on error

Update error handler in notification processor to continue on error

---

libs/src/services/identity/index.js

So that we don't make an unnecessarily large number of captcha requests and avoid exceeding the quota

Sample half relay captchas

---

discovery-provider/alembic/versions/591a66d44e5b_create_user_balance_changes_table.py

Fixes a multiple heads error because of conflict with https://github.com/AudiusProject/audius-protocol/pull/2034.

Fix user balance changes down revision

---

libs/src/services/solanaWeb3Manager/errors.js
libs/src/services/solanaWeb3Manager/index.js
libs/src/services/solanaWeb3Manager/rewards.js
libs/src/services/solanaWeb3Manager/transactionHandler.js
libs/src/services/solanaWeb3Manager/transfer.js
libs/src/services/solanaWeb3Manager/utils.js

Adds nonce to transfer 
Ran locally and transferred between two user bank accounts - also checked that nonce increased

Update libs transfer solana

---

creator-node/.version.json
discovery-provider/.version.json

Bump CN and DN version to 0.3.48

Bump version to 0.3.48

---

.circleci/config.yml
service-commands/scripts/setup.js
service-commands/src/setup.js

Some folks mentioned to me that `--no-parallel` false by default wasn't working so this implements a fix to that while parallelization is still being figured out.

Fix no-parallel default

---

libs/package-lock.json
libs/package.json

Bump Libs
Changes:
#2117 
#2114

bump libs v1.2.35

---

discovery-provider/src/api/v1/users.py
discovery-provider/src/queries/get_track_history.py

Just noticed some copy + paste mistakes. No impact on function. Unit tests would've caught that.

Rename listening history variables

---

discovery-provider/src/queries/get_sol_plays.py
discovery-provider/src/queries/queries.py
discovery-provider/src/queries/query_helpers.py
mad-dog/src/tests/test_plays.js

Following up on https://github.com/AudiusProject/audius-protocol/pull/2106#pullrequestreview-818485450. Adding test for aggregate play counts.

Add mad dog test for aggregate plays

---

libs/eth-contracts/ABIs/EthRewardsManager.json
libs/package-lock.json
libs/package.json
libs/scripts/communityRewards/transferCommunityRewardsToSolana.js

Re-opening PR, GitGuardian has now detected the wormhole address as a "secret" which it is not

Add script to transfer community rewards to solana (+config update)

---

discovery-provider/src/tasks/calculate_trending_challenges.py
discovery-provider/src/trending_strategies/aSPET_trending_tracks_strategy.py
discovery-provider/src/trending_strategies/ePWJD_trending_playlists_strategy.py
discovery-provider/src/trending_strategies/trending_strategy_factory.py
discovery-provider/tests/test_trending_challenge.py
discovery-provider/tests/test_update_trending.py

* Removes the old trending algorithm
* Moves the parameters of the old trending into the new trending file
* Also had to update the tests the compared old trending to the new trending to ensure that they are consistent
Ran it locally and it was working.
Logs

Remove old trending

---

service-commands/scripts/setup-instance.sh

Minor bug fix for A

---

.circleci/config.yml
discovery-provider/default_config.ini
discovery-provider/src/tasks/cache_user_balance.py
discovery-provider/src/tasks/index_user_bank.py
libs/initScripts/configureLocalDiscProv.js
solana-programs/start.sh

Fixes two issues with balance indexing:
- Web3.eth is undefined
- int() conversion fails with undefined values
Also fixes Solana issues:
- Confused Mint & Mint Authority
- Bad token precision in local dev
Tested locally, also will test on stage
Need to discuss balance indexing monitoring

Fix DN balance indexing and Solana config

---

service-commands/scripts/A

Pointed out by Marcus, fixes issue with https://github.com/AudiusProject/audius-protocol/pull/2066/files 
Tested manually

Fix seed CLI parsing

---

discovery-provider/src/api/v1/users.py
discovery-provider/src/queries/get_tracks.py
discovery-provider/src/utils/auth_middleware.py
discovery-provider/tests/test_get_tracks.py

Support unlisted tracks via ec-recover and passed signature data to discovery node
- Unit test
- Local stack, tested a signed request using client
- Deployed to stage node and verified that stage node is healthy https://discoveryprovider.staging.audius.co/health_check & can serve a signed request
Existing endpoint is unaffected: https://discoveryprovider.staging.audius.co/v1/full/users/handle/ray/tracks
Not immediately in use in production until unlisted UI is built

[AUD-1139] Support ec recover and signed request for unlisted tracks

---

creator-node/.version.json
discovery-provider/.version.json

Bump version to 0.3.49

---

libs/package.json
service-commands/scripts/bake-dev-image.sh
service-commands/scripts/create-instance.sh
service-commands/scripts/init-repos.sh
service-commands/scripts/provision-dev-env.sh
service-commands/scripts/registerAAO.sh
service-commands/scripts/set-git-refs.sh
service-commands/scripts/setup-instance.sh
service-commands/scripts/setup-k8s-manifests.sh
service-commands/scripts/utils.sh

* some fixes for things I found while testing... 
* since --up will not work via ssh, trying something new - baking when provisioning.

ASI-738 fixes for provisioning remote dev host easily; bake image script

---

service-commands/scripts/setup-instance.sh

Remove configuring of etc/hosts and gitconfig

---

discovery-provider/integration_tests/tasks/test_index_user_listening_history.py

Fix import in user listening history

---

libs/package-lock.json
libs/package.json

Libs v1.2.38

---

discovery-provider/src/utils/helpers.py

AUD-1111 Add " and {} to url slug exclusion list

---

identity-service/sequelize/migrations/20211223183608-add-solana-notification-indexes.js

Added indexes
Testing migration and revert and both work 👍

Add migration to add SolanaNotifications andSolanaNotificationActions indexes

---

libs/package-lock.json
libs/package.json
libs/src/services/solanaWeb3Manager/index.js
libs/src/services/solanaWeb3Manager/transactionHandler.js

Some necessary plumbing for solana client
None
n/a

[AUD-1150] [AUD-1152] Add additional Solana libs config

---

libs/src/services/solanaWeb3Manager/rewards.js

Signatures starting with 0 from DN would break attestation flow
Tested from client
n/a

[AUD-1184] Properly pad attestation signatures

---

libs/package-lock.json
libs/package.json

Includes attestation fix: https://github.com/AudiusProject/audius-protocol/pull/2210
Tested via client
n/a

Bump libs to 1.2.42

---

identity-service/package-lock.json
identity-service/package.json

Gets https://github.com/AudiusProject/audius-protocol/pull/2210
Locally
n/a

Consume libs 1.2.42 in Identity

---

discovery-provider/default_config.ini
discovery-provider/src/challenges/challenges.stage.json
discovery-provider/src/challenges/create_new_challenges.py

Gives the ability to set individual challenge fields per environment
Tested on my remote box, manually set env to stage
n/a

[AUD-1110] Add rewards config overrides for staging DN

---

libs/package-lock.json
libs/package.json

[7c3c8483] [AUD-1186] Add 404 safety check to discovery node selection (#2220) Raymond Jacobson

Libs v1.2.43

---

solana-programs/anchor/audius-data/cli/main.ts
solana-programs/anchor/audius-data/lib/lib.ts
solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
solana-programs/anchor/audius-data/tests/audius-data.ts

* Assigns a monotonically increasing track ID argument as tracks are uploaded
* Tests updated to pass

Incrementing trackID

---

creator-node/package-lock.json
creator-node/package.json
creator-node/src/routes/tracks.js
libs/package.json
libs/src/index.js
libs/src/services/creatorNode/index.js

Resumable upload does not work with CloudFlare unless you pay for their premium services. This PR is to remove the unused code for the time being. We can revisit this in the future if an accessible solution is an option again.
Tested creating a user and that uploading a track still works.
No monitoring necessary.

Remove resumable upload

---

libs/package-lock.json
libs/package.json

Libs version patch
* Identity wormhole #2151
* Remove resumable upload #2222

Libs version patch v1.2.44

---

identity-service/package-lock.json
identity-service/package.json

Fix identity wormhole endpoint. 
Should have been done atomically in #2151 with new libs method published in v1.2.44

Bump identity libs version

---

libs/package-lock.json
libs/package.json

Includes https://github.com/AudiusProject/audius-protocol/pull/2232

Libs 1.2.45

---

identity-service/package-lock.json
identity-service/package.json

Gets us fixed Sol balance detection for rewards: https://github.com/AudiusProject/audius-protocol/pull/2232
Tested on client

Consume libs 1.2.45 in Identity

---

libs/src/services/solanaWeb3Manager/index.js

Update the `getWAudioBalance` method to check if root account and derived associated token account has an audio balance
Related to https://github.com/AudiusProject/audius-client/pull/734
Ran with linked libs locally against prod

Libs get sol wrapped audio check associated token acct

---

libs/package-lock.json
libs/package.json

This libs bump includes:
[00956060] Libs get sol wrapped audio check associated token acct (#2235) Joseph Lee
[901d796b] Remove legacy track upload route (#2223) vicky :)

Bump libs 1.2.46

---

discovery-provider/src/challenges/create_new_challenges.py
discovery-provider/src/tasks/index.py
libs/src/services/solanaWeb3Manager/rewardsAttester.js

Commits should describe the various fixes
Tested all of this on stage already

Add misc rewards fixes

---

libs/package-lock.json
libs/package.json

Libs 1.2.47

---

identity-service/package-lock.json
identity-service/package.json

Gets us https://github.com/AudiusProject/audius-protocol/commit/9801a782f7629345cfb1dcd39d3ef6ed922cc3a4

Consume libs 1.2.47 in identity

---

libs/package-lock.json
libs/package.json

Gets us https://github.com/AudiusProject/audius-protocol/pull/2251

Libs 1.2.48

---

identity-service/package-lock.json
identity-service/package.json

Gets us https://github.com/AudiusProject/audius-protocol/pull/2251
Tested on staging

Consume libs 1.2.48 in Identity

---

libs/src/services/solanaWeb3Manager/index.js

Should return response / error

Fix libs waudio transfer method

---

libs/package-lock.json
libs/package.json

Libs 1.2.49

---

discovery-provider/integration_tests/challenges/test_connect_verified_challenge.py
discovery-provider/integration_tests/challenges/test_listen_streak_challenge.py
discovery-provider/integration_tests/challenges/test_mobile_install_challenge.py
discovery-provider/integration_tests/challenges/test_profile_completion_challenge.py
discovery-provider/integration_tests/challenges/test_referral_challenge.py
discovery-provider/integration_tests/challenges/test_trending_challenge.py
discovery-provider/integration_tests/utils.py

Updates challenge tests to override the config for starting block and to use a constant instead of magic numbers
These are tests.
CI

Update challenge tests to set start block for testing

---

creator-node/src/routes/healthCheck.js
service-commands/scripts/setup.js

Vg add ip check back

---

libs/src/services/solanaWeb3Manager/rewardsAttester.js

Fix bad log

---

.circleci/config.yml

Remove build requirements for CircleCI

---

creator-node/src/blacklistManager.js

Add track check to isServable

---

libs/src/api/file.js

Updates public gateways (comments out) default usage.
In prod we see lots of 429s given the volume request and generally the public gateways are providing little utility.
Linked client
No requests to public gateways

[AUD-1089] Update public gateways list

---

libs/package-lock.json
libs/package.json

Gets us https://github.com/AudiusProject/audius-protocol/commit/44404a46e1461507e6155371b9224570139b9ea0

Libs 1.2.50

---

identity-service/package-lock.json
identity-service/package.json
identity-service/src/app.js

Add a start block override to reward attester
Tested via local stack
* Setting via redis
* Seeing logs show that attester is updated
* See that redis is unset after start block applies
Monitored in running of the rewards stack

[AUD-1255] Add redis startblock override

---

libs/package-lock.json
libs/package.json

Includes: https://github.com/AudiusProject/audius-protocol/commit/aa15844e3f12812fe8aaa81e2cb6e5c5fa89ff51

Libs 1.2.51

---

creator-node/.version.json
discovery-provider/.version.json

Bump version to v0.3.50

---

identity-service/package-lock.json
identity-service/package.json
identity-service/src/routes/solana.js

To get proper error codes on the client, need to consume latest libs and handle the skipPreflight option

[AUD-1271] Handle skipPreflight in identity Solana relay

---

discovery-provider/src/challenges/challenges.json

Accidentally set as non-retroactive

Set connect-verified challenge to retroactive

---

creator-node/src/apiHelpers.js

We were printing excessive logs bc the method was not used correctly. This PR is to fix that. Routes like `requestUrl=/users/batch_clock_status` will no longer log out the actual response.  
Reference PR: https://github.com/AudiusProject/audius-protocol/pull/2140/files
Incorrect log:
```
[2022-01-13T18:56:06.926Z]  INFO: audius_creator_node/195776 on 36133ce9bf9c: Begin processing request (requestID=2EvX_PWL7z, requestMethod=POST, requestHostname=cn2_creator-node_1, requestUrl=/users/batch_clock_status)
requestQueryParams: spID=4&timestamp=2022-01-13T18:56:06.090Z&signature=0x6785c7d0ab1f616cc536836e98822d886581c77be893b53ab0c4141d7bffb8b1137e7332baedb2a6d18270a6e31703acf3bb2a97c39b987bbca7c29289f16bca1b
Executing (default): SELECT "cnodeUserUUID", "walletPublicKey", "lastLogin", …
```

Remove extra param passed in to log setting fn

---

creator-node/src/routes/files.js

Remove log from serving file

---

libs/package-lock.json
libs/package.json

[74c0add3] Make createUserBank to fire & forget (#2293) Raymond Jacobson
[d83b2ee8] [AUD-1170] Support uniquely owned discovery node selection (#2298) Raymond Jacobson
[a888258a] Removing Duplicate code | Updating account.js (#2292) Rahul

Libs 1.2.52

---

creator-node/src/app.js
discovery-provider/src/utils/helpers.py
discovery-provider/src/utils/ipfs_lib.py
discovery-provider/src/utils/redis_cache.py

Change info to debug logs, cuts down number of logs by ~25% on production.

Log level cleanup to ease logger load

---

discovery-provider/alembic/versions/7104383ac0fe_drop_old_trending_challenges.py

Update trending challenge revision

---

solana-programs/anchor/audius-data/cli/README.md
solana-programs/anchor/audius-data/cli/main.ts
solana-programs/anchor/audius-data/lib/lib.ts
solana-programs/anchor/audius-data/lib/utils.ts
solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
solana-programs/anchor/audius-data/tests/audius-data.ts
solana-programs/anchor/audius-data/tests/playlist.ts
solana-programs/anchor/audius-data/tests/test-helpers.ts

- add rust code playlist create, update, delete
- add their respective tests
- add cli functions
create playlist, update playlist, delete playlist in `tests/audius-data.ts`

Add playlist create, update, delete, and their tests

---

discovery-provider/src/queries/get_undisbursed_challenges.py

Undisbursed endpoint should filter out deactivated accounts
TBD against stage

Filter deactivated accounts from the undisbursed endpoint

---

discovery-provider/nginx_conf/nginx.conf

Adds an exception to indexing/skipped_transactions in OpenResty
Test on sandbox pending

Bypass indexing skipped transactions

---

libs/package-lock.json
libs/package.json

Includes attester changes: https://github.com/AudiusProject/audius-protocol/pull/2332

Libs 1.2.53

---

libs/package-lock.json
libs/package.json

Bump libs version to v0.1.2.54

Bump libs version to v0.1.2.54

---

identity-service/package-lock.json
identity-service/package.json

Gets https://github.com/AudiusProject/audius-protocol/pull/2332

Consume libs 1.2.53 in identity

---

libs/package-lock.json
libs/package.json

Gets us: https://github.com/AudiusProject/audius-protocol/pull/2340

Libs 1.2.55

---

libs/src/services/solanaWeb3Manager/rewardsAttester.js

Fix libs lint error

---

libs/package-lock.json
libs/package.json

Gets us https://github.com/AudiusProject/audius-protocol/pull/2342/

Libs 1.2.56

---

identity-service/package-lock.json
identity-service/package.json
identity-service/src/app.js
identity-service/src/remoteConfig.js

Gets us https://github.com/AudiusProject/audius-protocol/pull/2340
Tested on stage with beta libs

Consume latest libs in identity

---

discovery-provider/scripts/lint.sh
discovery-provider/scripts/test.sh
service-commands/scripts/provision-dev-env.sh

Allow manual control of fixing lint changes, choosing when the full test suite is run, and pre-installing python-dev and pre-commit.

better manual control over linting and testing

---

discovery-provider/integration_tests/tasks/test_update_trending.py
discovery-provider/src/queries/get_trending_tracks.py
discovery-provider/src/trending_strategies/ML51L_trending_tracks_strategy.py
discovery-provider/src/trending_strategies/aSPET_trending_tracks_strategy.py

This reverts commit d422cc67023455eb474c98bb781baab28cc13f19.
Bug in new experiment so this change will now be a part of a separate experiment.

Revert "Update trending strategy to use all time play count (#2267)"

---

libs/package-lock.json
libs/package.json

Gets https://github.com/AudiusProject/audius-protocol/pull/2353

Libs 1.2.57

---

identity-service/package.json
identity-service/src/audiusLibsInstance.js
identity-service/src/config.js
identity-service/src/routes/healthCheck.js
identity-service/src/routes/trackListens.js
identity-service/src/solana-client.js
libs/src/index.js

Propagate confirmation timeout config in libs and identity service
Validated manually on staging

[AUD-1347] - Enable Confirmation Timeout Config

---

discovery-provider/src/challenges/challenges.stage.json

Currently untestable on stage due to non-overridden startblock

Override stage startblock for verified referrals

---

creator-node/test/ensureStorageMiddleware.test.js
creator-node/test/nodesync.test.js

Remove .only in CN test suite + fix test

---

identity-service/src/app.js
identity-service/src/config.js
identity-service/src/routes/wormhole.js
identity-service/src/utils/rewardsReporter.js

Update slack reporter to have separate success and error reporters
Closes AUD-1308

Update slack reporter

---

libs/package.json

[80f0a162] Bump libs to 1.2.58 Hareesh Nagaraj
[61833300] [AUD-1347] - Enable Confirmation Timeout Config (#2363) Hareesh Nagaraj
[c07b1003] [AUD-1251] Add protocol check on service registration (#2349) Dylan Jeffers
Validated manually on staging

Libs 1.2.58

---

libs/package-lock.json
libs/package.json

(Fixing the 1.2.58 by adding package lock)
[a7036926] Rebump w/package lock updated Hareesh Nagaraj

Libs 1.2.59

---

identity-service/package.json
package-lock.json

* Propagates config for timeout seconds
* Updates package lock

Identity Service - Consuming libs 1.2.59

---

identity-service/src/routes/trackListens.js

Use req.logger.info explicitly

Identity retry tx log

---

discovery-provider/src/tasks/index.py
discovery-provider/src/utils/constants.py
discovery-provider/src/utils/helpers.py

Tests pass

---

creator-node/.version.json
discovery-provider/.version.json

Bump version to v0.3.51

---

identity-service/src/routes/trackListens.js

Address key mismatch introduced in [this commit](https://github.com/AudiusProject/audius-protocol/pull/2383/commits/852256aff2d66da5b750eb06fd92c626bfea3d13)

[AUD-1340] Fix redisExpiryKey mismatch

---

libs/src/api/account.js

Allow tracking of user bank outcomes via the signup method in libs
Move the try catch within the async called function in libs signup for create user bank to catch the error and log/track
Fixes AUD-1324
ran locally

Add handle user bank to signup

---

libs/package-lock.json
libs/package.json

[c428c9de] Libs 1.2.60 Raymond Jacobson
[ed63705b] Add update endpoints and aao in rewards attester (#2401) Raymond Jacobson
[adf899dd] Add handle user bank to signup (#2387) Joseph Lee

Libs 1.2.60

---

libs/package-lock.json
libs/package.json

Includes https://github.com/AudiusProject/audius-protocol/pull/2403

Libs 1.2.61

---

discovery-provider/src/queries/notifications.py

Improve /notification endpoint performance by filtering saves
Ran on sandbox node

Fix playlist save query

---

identity-service/src/notifications/index.js

Experienced timeout issues with 2m. Bump this to 5m

Bump timeout to 5m for indexAll processing

---

libs/package-lock.json
libs/package.json

Bumps lib patch version 
Includes PR:
* Refactor FileProcessingQueue to AsyncProcessingQueue #2399 
* Fix wormhole rpc hosts #2421

Bump libs version to v1.2.62

---

discovery-provider/integration_tests/queries/test_get_prev_track_entries.py
discovery-provider/src/queries/get_prev_track_entries.py
discovery-provider/src/queries/notifications.py

Added `get_prev_track_entries` query for notifications to batch calls to get previous tracks for notifications
Added a test. it passed 👍

Add get_prev_track_entries query to batch query for notifications and add basic test

---

discovery-provider/integration_tests/queries/test_get_prev_track_entries.py
discovery-provider/src/queries/get_prev_track_entries.py

Fixing lint errors. Why doesn't python like spaces before and after curly braces?

Fix linting errors

---

identity-service/package-lock.json
identity-service/package.json

Update libs dep in identity for wormhole fix

Update libs dep

---

libs/src/api/rewards.js
libs/src/services/solanaWeb3Manager/index.js
libs/src/services/solanaWeb3Manager/rewardsAttester.js
libs/tests/rewardsAttesterTest.js

- Adds configurable delay to rewards attester
- Added unit tests

Add delay to rewardsAttester

---

libs/package-lock.json
libs/package.json

Includes https://github.com/AudiusProject/audius-protocol/commit/a403280a5c00f477f04cc461f17deaea95c852b3

Libs 1.2.63

---

discovery-provider/src/queries/notifications.py

Quick fix to pass in the session to the call

Fix get-prev-track-entries call

---

identity-service/src/app.js
identity-service/src/routes/wormhole.js

Fixes the estimated gas
Fixes the slack reporter url

Identity wormhole fix

---

libs/package-lock.json
libs/package.json

Includes https://github.com/AudiusProject/audius-protocol/pull/2456

Libs 1.2.64

---

solana-programs/anchor/audius-data/lib/lib.ts
solana-programs/anchor/audius-data/tests/audius-data.ts

This reverts commit 48287acd918de1c7245bcabb8e223a89dd113755.
Revert accidental push to master

Revert "Add missing functions and use them"

---

libs/package-lock.json
libs/package.json

Includes https://github.com/AudiusProject/audius-protocol/pull/2468

Libs 1.2.66

---

identity-service/package-lock.json
identity-service/package.json

Have identity use libs 1.2.67 to support multiple solana fee payers

Bump libs in identity

---

libs/package-lock.json
libs/package.json

Includes https://github.com/AudiusProject/audius-protocol/pull/2476

Libs 1.2.68

---

libs/src/api/rewards.js
libs/src/services/identity/index.js
libs/src/services/solanaWeb3Manager/rewardsAttester.js

- New identity endpoint
- Also pass specifiers to the reporters

Wire up sendAttestationResult in libs

---

libs/package-lock.json
libs/package.json

Includes https://github.com/AudiusProject/audius-protocol/pull/2478

Libs 1.2.69

---

identity-service/package-lock.json
identity-service/package.json
identity-service/src/routes/rewards.js
identity-service/src/utils/configureAttester.js
identity-service/src/utils/rewardsReporter.js

- Adds new route to report attestation results
- Also adds specifier + source to logs everywhere

Add attestation_result route

---

libs/src/services/solanaWeb3Manager/rewardsAttester.js
libs/src/services/solanaWeb3Manager/transactionHandler.js

Fix fee payer bug
Deploy commit on identity stage and test that rewards are being disbursed.

[AUD-1516] Fix fee payer bug

---

identity-service/package-lock.json
identity-service/package.json

Consume libs 1.2.71 in identity

Consume libs 1.2.71 in identity

---

identity-service/src/notifications/processNotifications/playlistUpdateNotification.js

Add more logs for playlist update notifications

Add logs for playlist update notifications

---

identity-service/package-lock.json
identity-service/package.json
identity-service/src/analytics.js
identity-service/src/config.js
identity-service/src/utils/rewardsReporter.js
libs/src/services/solanaWeb3Manager/rewardsAttester.js

Wires up Identity Automatic attestation to amplitude to get a better sense of error rates

Add analytics for Identity Attesting

---

identity-service/Dockerfile

Use Alpine Linux mirror for Identity

---

libs/package-lock.json
libs/package.json

Includes https://github.com/AudiusProject/audius-protocol/pull/2492

Libs 1.2.72

---

identity-service/package-lock.json
identity-service/package.json

Includes https://github.com/AudiusProject/audius-protocol/pull/2492

Consume libs 1.2.72 in Identity

---

identity-service/src/routes/rewards.js
identity-service/src/utils/rewardsReporter.js

Remove client analytics tracking for rewards to avoid double-tracking

---

libs/package-lock.json
libs/package.json

Gets us https://github.com/AudiusProject/audius-protocol/commit/8a4a44b8498d0dcb49e4c1b671d44617d956c8f8

Libs 1.2.74

---

identity-service/package-lock.json
identity-service/package.json

Gets us https://github.com/AudiusProject/audius-protocol/commit/8a4a44b8498d0dcb49e4c1b671d44617d956c8f8

Consume libs 1.2.74

---

discovery-provider/nginx_conf/nginx.conf

Comment explains
To cherry pick onto release

Do not redirect challenges

---

libs/src/services/solanaWeb3Manager/rewards.js
libs/src/services/solanaWeb3Manager/transactionHandler.js

Less dependence on the fe rpc pool

Stop sending blockhash for rewards

---

libs/package-lock.json
libs/package.json

Includes https://github.com/AudiusProject/audius-protocol/pull/2509

Libs 1.2.75

---

discovery-provider/alembic/versions/d3325cbc0bec_backfill_mobile_app_install_challenge.py

Ran against staging snap db and verified user challenges were created

Migration to backfill mobile install

---

discovery-provider/src/queries/get_challenges.py

- Don't override step counts if challenge is complete
- Don't update existing model
- Still testing, trying to start remote dev DN.... standby

[AUD-1536] Don't override step count if complete

---

libs/src/services/solanaWeb3Manager/rewardsAttester.js

We weren't wiping out the existing challenges queue

Fix attester starting block

---

libs/package-lock.json
libs/package.json

Gets https://github.com/AudiusProject/audius-protocol/commit/a486f2e519b14277c717cf549adc885b8a17ffd0

Libs 1.2.76

---

libs/package-lock.json
libs/package.json

Includes https://github.com/AudiusProject/audius-protocol/commit/48f83d4675a390b8266a21fbdfdf7875ea511da8

Libs 1.2.77

---

identity-service/package-lock.json
identity-service/package.json

Relevant:
- https://github.com/AudiusProject/audius-protocol/commit/48f83d4675a390b8266a21fbdfdf7875ea511da8
- https://github.com/AudiusProject/audius-protocol/commit/a486f2e519b14277c717cf549adc885b8a17ffd0
Stage

Consume libs 1.2.77

---

identity-service/src/app.js
identity-service/src/config.js
identity-service/src/routes/wormhole.js

Update wormhole error slack url to match new channel
Sent curl requests to the webhook to make sure it works. Unfortunately need to hit the fail flow for wormhole transfer to really test

Update wormhole error slack url to match new channel

---

discovery-provider/integration_tests/tasks/test_index_users.py
discovery-provider/src/tasks/users.py

Fix referrals challenge

---

discovery-provider/src/queries/get_user_history.py
discovery-provider/src/tasks/index.py
discovery-provider/src/tasks/users.py

* Fix is current
* Fix user history
* Fix revert case
* Fix or query
* Lint
Co-authored-by: Dheeraj Manjunath <dheerajmanju1@gmail.com>

Fix current user query (#2531)

---

libs/src/index.js
libs/src/services/discoveryProvider/DiscoveryProviderSelection.js
libs/src/services/discoveryProvider/DiscoveryProviderSelection.test.js
libs/src/services/discoveryProvider/constants.js
libs/src/services/discoveryProvider/index.js

Add unhealthy block diff and param to libs discovery service 
Added a setter method as well in case we want to differentiate the healthy block diff number for users signed in / not signed in 
Libs linked locally and checked that the value was set

Add unhealthy block diff to libs

---

libs/package-lock.json
libs/package.json

Bump libs version
Only contains this PR: https://github.com/AudiusProject/audius-protocol/pull/2529

Bump libs version to v1.2.78

---

discovery-provider/src/tasks/users.py

Add is_current in additional missing spot

---

identity-service/src/utils/configureAttester.js
libs/src/services/solanaWeb3Manager/rewardsAttester.js

No sense in having identity wait 40s for DNs to get synced since it now runs 15min behind

Decrease reward aggregation attempts in Identity

---

libs/package-lock.json
libs/package.json

Includes https://github.com/AudiusProject/audius-protocol/pull/2540

Libs 1.2.79

---

identity-service/package-lock.json
identity-service/package.json

Consume libs 1.2.79

---

creator-node/package-lock.json
creator-node/package.json
creator-node/src/serviceRegistry.js

Upgrade libs in content-node to 1.2.80

Upgrade libs in content-node to 1.2.80

---

libs/src/api/rewards.js
libs/src/api/serviceProvider.js
libs/src/service-selection/ServiceSelection.js
libs/src/services/solanaWeb3Manager/rewardsAttester.js

Use selection logic on whitelist

---

libs/package.json

Bump libs to 1.2.82

---

libs/package-lock.json
libs/package.json

Libs 1.2.82

---

libs/package-lock.json
libs/package.json

[6aad6f47] Support signing sol relay (#2561) Raymond Jacobson

Libs 1.2.85

---

discovery-provider/requirements.txt
discovery-provider/src/queries/get_balances.py
discovery-provider/src/tasks/cache_user_balance.py
discovery-provider/src/utils/spl_audio.py

Associated spl wallet indexing never worked because our version of spl token does not support get_account_info.
Need to run local stack and test this all out. @jowlee  for input

Fix total balance & user balance indexing

---

discovery-provider/src/tasks/index.py
discovery-provider/src/tasks/tracks.py
discovery-provider/src/tasks/users.py
discovery-provider/src/utils/ipfs_lib.py

Process user operations in parallel, ensuring that _per_ user operations are still handled serially to negate potential inconsistencies
Existing tests pass, validated on prod sandbox

[AUD-1584] Parallel user tx processing

---

discovery-provider/default_config.ini
discovery-provider/src/tasks/index.py
discovery-provider/src/tasks/users.py
discovery-provider/src/utils/ipfs_lib.py

Improve timeouts

---

creator-node/src/routes/files.js

Timing decision tree logging for getCID

---

identity-service/src/routes/instagram.js

Fix for insta social proof
Testing on stage as this branch builds

Allow non verified insta link

---

creator-node/src/diskManager.js
creator-node/src/routes/files.js

CN CID fetch - do FS check before DB check

---

identity-service/package-lock.json
identity-service/package.json

Gets us https://github.com/AudiusProject/audius-protocol/commit/00281f2014976dc102c10f473fc5a9e6db7587b1, among others

Consume libs 1.2.85 in Identity

---

creator-node/src/routes/files.js

Fix CID fetch invalid CID hanging

---

service-commands/scripts/provision-dev-env.sh

install yq for load-test-tools

---

libs/package-lock.json
libs/package.json

Includes:
- #2591 
Tested on stage identity, tailed logs, saw DNs successfully selected.
Amplitude and tailing logs in identity

Update libs to 1.2.86

---

identity-service/package-lock.json
identity-service/package.json

Consume libs 1.2.86 in Identity

---

identity-service/src/notifications/processNotifications/playlistUpdateNotification.js

Improve performance by switching to for loops.

Speed up playlist updates by removing reduce

---

discovery-provider/scripts/prod-server.sh
discovery-provider/src/queries/notifications.py

Update timeout to 600s to be consistent with load balancer settings.
Tested on prod DN and saw timeout go away

Increase gunicorn timeout and add notif logging

---

identity-service/src/routes/cognito.js

Use lightning verification values for identity

Use lightning verification values for identity

---

.github/pull_request_template.md

Surface reminder to add sufficient logs on each PR
N/A
N/A

Add logging reminder to PR template

---

discovery-provider/src/tasks/index.py

Add a log for indexing commit time
Lint
`logs -f worker | grep 'session committed to db'`

Add log for indexing commit time

---

discovery-provider/src/tasks/index.py

Add logs for each milestone
Ran on sandbox
This is a logs change

Add more logs to index_blocks

---

identity-service/src/models/notificationemail.js
identity-service/src/notifications/sendNotificationEmails.js
identity-service/test/sendNotifications/sendNotificationEmail.js

Updated the send email identity flow to not try to log an undefined variable (ref https://github.com/AudiusProject/audius-protocol/pull/2472/files#diff-b608ca66fc364c8bdf8399c6a7f533de2abe6177a5cc79a319c1703ffc7b314dR310)
Updated the send email test to test for the error case so this doesn't happen again 
Updated the send email model so that id is auto-incrementing & doesn't error the flow & break tests (ref: https://github.com/AudiusProject/audius-protocol/commit/055e0d22707e83e5f77ac97a2606523fb348e950#diff-3ee39ef0288650abd694c6177246dec430df95cc50949dec4271f084f8b146f3R4)
Wrote a new test for the error flow and validated that the logs were there
There are now more logs to check for in identity

Fix send email logs / model

---

discovery-provider/integration_tests/tasks/test_index_operations.py

Fix indexing integration tests

---

identity-service/src/routes/rewards.js
identity-service/src/utils/configureAttester.js
identity-service/src/utils/rewardsReporter.js
libs/src/api/rewards.js
libs/src/services/identity/index.js
libs/src/services/solanaWeb3Manager/rewardsAttester.js

- Do AAO attestation before DN
- Remove some logs
- Add some error types

Improve rewards logging and other fixes

---

libs/package-lock.json
libs/package.json

Includes https://github.com/AudiusProject/audius-protocol/commit/58071415410ccb736f36399a13a6da4e6b3c9298, https://github.com/AudiusProject/audius-protocol/commit/f9fe015299db698e1e96135d074758f38163c4a5

Libs 1.2.87

---

identity-service/package-lock.json
identity-service/package.json

Improves rewards error handling + logs
Logs are improved – change will be monitored by new errors (hcaptcha, cognito) appearing in Amplitude, as well as manually monitoring the identity logs and confirming that DNs are reselected in the case of drift

Consume libs 1.2.87 in Identity

---

solana-programs/anchor/audius-data/lib/lib.ts
solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
solana-programs/anchor/audius-data/tests/audius-data.ts
solana-programs/anchor/audius-data/tests/follows.ts
solana-programs/anchor/audius-data/tests/playlist.ts
solana-programs/anchor/audius-data/tests/test-helpers.ts

Add authenticator key to audius admin
Adds method that validates authenticator and logs verified user eth addr
Wrote a test to check for logs

[ASI-894] Add verify user

---

solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
solana-programs/anchor/audius-data/tests/follows.ts

Clean up follow to use the user handle struct - grouping the associated seed and bump
Updated the tests to use it as well

Cleanup user handle

---

discovery-provider/src/queries/notifications.py

Seeing this block of code hang in the notif playlist updates flow
Will cherry-pick onto release & test.

Remove reduce to speed up notif processing

---

solana-programs/anchor/audius-data/.eslintignore
solana-programs/anchor/audius-data/.eslintrc.js
solana-programs/anchor/audius-data/cli/main.ts
solana-programs/anchor/audius-data/lib/lib.ts
solana-programs/anchor/audius-data/lib/utils.ts
solana-programs/anchor/audius-data/migrations/deploy.ts
solana-programs/anchor/audius-data/package.json
solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
solana-programs/anchor/audius-data/tests/audius-data.ts
solana-programs/anchor/audius-data/tests/follows.ts
solana-programs/anchor/audius-data/tests/playlist.ts
solana-programs/anchor/audius-data/tests/test-helpers.ts
solana-programs/anchor/audius-data/tsconfig.json
solana-programs/anchor/audius-data/yarn.lock

Add ESLint to anchor workspace and fix any lint errors.
Tests all pass.
No monitoring.

[ASI-913] Add ESLint to anchor workspace

---

libs/package-lock.json
libs/package.json

Changelog:
[9c03fc06] add id to playlist folder (#2610) nicoback2

Update libs to 1.2.88

---

creator-node/.version.json
discovery-provider/.version.json

Bump version to v0.3.53

---

creator-node/src/app.js
creator-node/src/components/contentBlacklist/contentBlacklistController.js
creator-node/src/config.js
creator-node/src/index.ts
creator-node/src/routes/cm.js
creator-node/src/routes/contact.js
creator-node/src/serviceRegistry.js
creator-node/src/services/TrustedNotifierManager.js
creator-node/test/contentBlacklist.test.js
creator-node/test/lib/app.js
creator-node/test/snapbackSM.test.js
libs/initScripts/local.js
service-commands/scripts/hosts.js
service-commands/scripts/provision-dev-env.sh
service-commands/src/commands/service-commands.json
service-commands/src/setup.js

TN Final integration

---

libs/package-lock.json
libs/package.json

Contains
https://github.com/AudiusProject/audius-protocol/commit/8bd9c93a3fad81623ad4bcccac6b23d31f9f9e36
https://github.com/AudiusProject/audius-protocol/commit/447389eed01faa7b2370a76537d9a2630eab5d19
Bump libs to v1.2.89
No CI necessary
No monitoring necessary

Bump libs to v1.2.89

---

libs/package-lock.json
libs/package.json

Bump libs to 1.2.90

---

creator-node/package-lock.json
creator-node/package.json

Bump content node libs version to v1.2.89
Ran mad-dog locally and it passed
Regular monitoring through loggly + amplitude

Bump content node to libs v1.2.89

---

identity-service/src/routes/cognito.js

so that deduping is more effective
Test on staging
No additional logs

Use lowercase identity name

---

discovery-provider/alembic/versions/58c87cf2c7e6_create_spl_token_transaction.py
discovery-provider/integration_tests/tasks/test_index_spl_token.py
discovery-provider/integration_tests/utils.py
discovery-provider/src/app.py
discovery-provider/src/models/__init__.py
discovery-provider/src/models/spl_token_transaction.py
discovery-provider/src/queries/get_health.py
discovery-provider/src/queries/get_health_unit_test.py
discovery-provider/src/queries/get_sol_rewards_manager.py
discovery-provider/src/queries/get_sol_user_bank.py
discovery-provider/src/queries/get_spl_audio.py
discovery-provider/src/solana/solana_client_manager.py
discovery-provider/src/solana/solana_transaction_types.py
discovery-provider/src/tasks/index_spl_token.py
discovery-provider/src/utils/redis_constants.py
discovery-provider/src/utils/solana_indexing_logger.py

* Adds indexer for spl audio
* Has test with mock tx info
* Adds migration & model for `SPLTokenTransaction` holding one row for the most recent processed tx
* Adds a class logger helper `SolanaIndexingLogger` to log everything at end 
Wrote test and ran against prod - it keeps up, but is a constant small lag behind because of the incoming throughput of the transactions to this program 
Logs: ex log
```
{"levelno": 20, "level": "INFO", "msg": "index_spl_token.py", "timestamp": "2022-03-03 20:41:17,417", 
"job": "index_spl_token", 
"logs": "
latest used slot: None (duration 0.25536537170410156 sec),
Requesting transactions before None (duration 9.298324584960938e-06 sec),
Retrieved transactions before None (duration 0.5871326923370361 sec),
intersection_found=True, …
```

Index spl audio

---

libs/src/services/solanaWeb3Manager/transfer.js

Pass fee payer key through transfer override
Manually running against prod

transfer with override

---

libs/package-lock.json
libs/package.json

[360ac5c6] transfer with override (#2669) Joseph Lee

Libs 1.2.91

---

discovery-provider/alembic/versions/d321f0a00721_partial_indexes.py

Clean version of: https://github.com/AudiusProject/audius-protocol/pull/2664

partial indexes migration

---

discovery-provider/src/queries/notifications.py

Cherry-picks https://github.com/AudiusProject/audius-protocol/pull/2642 from master over to the release branch.
Tested via cherry-pick deployment to prod node
Notification processing logs , server logs `grep notifications.py`

Remove reduce to speed up notif processing (#2642)

---

solana-programs/anchor/audius-data/programs/audius-data/src/constants.rs
solana-programs/anchor/audius-data/programs/audius-data/src/error.rs
solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs

Clean up code since lib.rs is getting long.
Current tests pass.
No monitoring.

[ASI-919] Split lib functionality into multiple files

---

identity-service/src/routes/cognito.js

For better deduping
Manually
Log already exists

Make docs unique

---

discovery-provider/src/utils/redis_metrics.py
service-commands/scripts/provision-dev-env.sh

Capture Flask's HTTP response codes into the grafana metrics.
Useful when performing load tests.
Grafana shows code labels.
N/A

capture flask http response codes

---

discovery-provider/src/queries/get_unpopulated_playlists.py
discovery-provider/src/queries/get_unpopulated_tracks.py
discovery-provider/src/queries/get_unpopulated_users.py

Fixes de-serialization for the unpopulated pulls from redis.
I think this was a fair compromise, but overall don't loooove it. I scanned over all the places we do this serialization and I think this is the only spot that's necessary. Need to soak on staging though.
Ran local stack, created a feed with playlists in it (the way to exercise the bug) and made sure that it returned properly after this change was included.
Monitor on staging

[AUD-1690] Properly parse unpopulated tracks, users, playlists

---

identity-service/src/authMiddleware.js
identity-service/src/routes/idSignals.js
identity-service/src/userHandleMiddleware.js

Instead of adding yet another endpoint and having to make too many requests to identity
Manual
Responses and middleware are descriptive enough. No other logs.

Add endpoint to return id signals

---

libs/scripts/communityRewards/transferCommunityRewardsToSolana.js

Exports the `transferCommunityRewardsToSolana` script to be consumed in `claim.js` so that upon initiating each round of funding we can call it automatically

Export "transfer rewards to Solana" script to enable automatic transfer

---

identity-service/src/routes/fp.js
identity-service/src/routes/idSignals.js
identity-service/src/utils/fpHelpers.js

Include device user count in signals
Manually on staging
Api response should be enough atm

Include device user count in signals

---

discovery-provider/src/utils/redis_metrics.py

extract status codes from werkzeug Responses
Follow up to:
* #2693 
* #2685
Monitor staging and soaking production nodes for error logs.
N/A

extract status codes from werkzeug Responses

---

discovery-provider/src/queries/get_underground_trending.py
discovery-provider/src/queries/get_unpopulated_playlists.py
discovery-provider/src/queries/get_unpopulated_tracks.py
discovery-provider/src/queries/get_unpopulated_users.py
discovery-provider/src/tasks/cache_trending_playlists.py
discovery-provider/src/tasks/index_trending.py
discovery-provider/src/tasks/user_replica_set.py
discovery-provider/src/utils/eth_contracts_helpers.py
discovery-provider/src/utils/redis_cache.py
discovery-provider/src/utils/redis_cache_unit_test.py

Reverts changes in
https://github.com/AudiusProject/audius-protocol/pull/2687
https://github.com/AudiusProject/audius-protocol/pull/2658
For safety. 
Roll forward fix is here: https://github.com/AudiusProject/audius-protocol/pull/2714
Staging nodes (this is also a revert with no downstream deps)

Revert json changes in release branch

---

diff.sh
service-commands/src/commands/service-commands.json

Remove misc. reference to old content-service
N/A
N/A

Remove content-service remnants

---

solana-programs/anchor/audius-data/cli/main.ts
solana-programs/anchor/audius-data/lib/lib.ts
solana-programs/anchor/audius-data/programs/audius-data/src/constants.rs
solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
solana-programs/anchor/audius-data/tests/audius-data.ts
solana-programs/anchor/audius-data/tests/follows.ts
solana-programs/anchor/audius-data/tests/playlist-social-actions.ts
solana-programs/anchor/audius-data/tests/playlist.ts
solana-programs/anchor/audius-data/tests/test-helpers.ts
solana-programs/anchor/audius-data/tests/track-social-actions.ts

Remove playlist account storage. Refactor libs to simplify ManageEntity. Rewrote playlists to be identical to track create / update / delete tests in audius-data.ts.
Modified existing tests.
No monitoring.

[ASI-936] Remove playlist account and refactor lib

---

creator-node/.version.json
discovery-provider/.version.json

Bump version to v0.3.54

---

.circleci/config.yml
libs/package-lock.json
libs/package.json
libs/rollup.config.js
libs/scripts/communityRewards/transferCommunityRewardsToSolana.js
libs/src/index.js
libs/src/services/wormhole/index.js
service-commands/scripts/init-repos.sh

Fixes issue where wormhole would not bundle correctly when building libs with rollup. Upgrading to 0.1.1 fixes this, since they now have esm and cjs builds
- Additionally fixes rollup issue where named and default exports were not compiling correctly
To test this properly, we need to transfer audio with prod env

[AUD-1737] Fix wormhole compilation issue

---

libs/package-lock.json
libs/package.json

Bumping libs to take out to Identity
- #2725 by Dylan Jeffers
- #2730 by Dylan Jeffers
- #2705 by Dylan Jeffers
- #2722 by Dylan Jeffers
- #2733 by Marcus Pasell
- #2719 by Marcus Pasell
- #2704 by Dylan Jeffers
- #2675 by Marcus Pasell

Bump libs to v1.2.93

---

identity-service/package-lock.json
identity-service/package.json

Consume libs 1.2.93 in identity

---

solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
solana-programs/anchor/audius-data/tests/test-helpers.ts

* For UserHandle move from size 16 to 32
Existing tests pass

[ASI-965] Increase handle size

---

.circleci/config.yml
creator-node/package-lock.json
creator-node/package.json
creator-node/scripts/start.sh
creator-node/src/snapbackSM/snapbackSM.js
identity-service/scripts/dev-server.sh
service-commands/scripts/init-repos.sh

- Fixes case where linked @audius/libs wasn't hot-reloading creator-node and identity-service on change.
- Also fixes issue where creator-node was not importing `CreatorNode` class from @audius/libs entrypoint, which isn't supported now that src files include ts
A up with devMode=true and link_libs=true works

[AUD-1763] Fix dev-mode with linked @audius/libs

---

solana-programs/anchor/audius-data/lib/lib.ts
solana-programs/anchor/audius-data/lib/utils.ts
solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
solana-programs/anchor/audius-data/tests/audius-data.ts
solana-programs/anchor/audius-data/tests/playlist.ts
solana-programs/anchor/audius-data/tests/test-helpers.ts

Add bn id to user and entity
Updated tests

Add bn id to user and entity

---

libs/package-lock.json
libs/package.json

[82463a77] v1.2.94 Vicky
[2ad6dc61] Use async_processing_status (#2710) vicky :)
[3457a3ee] [ASI-943] Make discovery node unhealthy block diff configurable (#2743) Theo Ilie
[00b5bb5a] Attach Utils to libs instance (#2740) Michael Piazza
[3cb3cb81] Fix create sender public (#2735) Michael Piazza

Bump libs to v1.2.94

---

discovery-provider/scripts/test.sh

Creates the prometheus_data folder needed for running integration tests locally.
Follow up of #2757 using the correct envars.

set PROMETHEUS_MULTIPROC_DIR for local tests

---

identity-service/src/routes/healthCheck.js
identity-service/src/utils/configureAttester.js
libs/src/services/solanaWeb3Manager/rewardsAttester.js

- Adds a concept of `phase` to the attester
- Adds last completedChallenge, lastSuccessfulChallenge to healthcheck
Will wire up to pingdom

Add phase to attester, improve healthcheck

---

libs/package-lock.json
libs/package.json

Includes https://github.com/AudiusProject/audius-protocol/pull/2761

Libs 1.2.95

---

identity-service/package-lock.json
identity-service/package.json

Gets https://github.com/AudiusProject/audius-protocol/pull/2761

Consume libs 1.2.95

---

libs/package-lock.json
libs/package.json

Upgrade libs to 1.2.96 to fix wormhole compilation issue

Libs 1.2.96

---

creator-node/.version.json
discovery-provider/.version.json

Bump release version to v0.3.55
NA
NA

Bump version to v0.3.55

---

libs/package-lock.json
libs/package.json

Bump the libs version to 1.2.97.
- #2800 by Theo Ilie
- #2736 by Dylan Jeffers
- #2752 by C.S. Jiang
N/A - just a version bump
N/A - just a version bump

Bump libs to v1.2.97

---

discovery-provider/src/api/v1/resolve.py

- Prefer @api.expects() over @api.doc() params
- Fix decorator order
N/A
N/A

Prepare Resolve API for Type gen

---

libs/package-lock.json
libs/package.json

Includes these changes https://github.com/AudiusProject/audius-protocol/pull/2801
n/a
n/a

Bump libs to 1.2.98

---

libs/package-lock.json
libs/package.json

for this one https://github.com/AudiusProject/audius-protocol/pull/2811
n/a
n/a

Bump libs to 1.2.99

---

discovery-provider/src/api/v1/helpers.py
discovery-provider/src/api/v1/search.py

- Make IDs cleaner
- Reorder decorators
- Reuse parser

Prepare Search API for type gen

---

libs/examples/initAudiusLibs.js

Mad dog tests do not work without this import change. This is so that we can use typescript in libs and not have mad dog worry about typing
Ran mad-dog and test does not err on import anymore

Fix ts import

---

discovery-provider/src/api/v1/helpers.py
discovery-provider/src/api/v1/playlists.py
discovery-provider/src/api/v1/search.py
discovery-provider/src/api/v1/tracks.py
discovery-provider/src/api/v1/users.py

Found more issues after running tests:
- Fixes the summary in the search endpoint
- Adds description to listening history
- Adds description to `/playlists/{id}/reposts`
- Adds documentation to smart playlists
- Adds description to `/users/search`
- Updates `current_user_parser` to use `description` not `help` arg
- Adds description to `/tracks/by_ids`

More API documentation cleanup

---

libs/package-lock.json
libs/package.json

for this one https://github.com/AudiusProject/audius-protocol/pull/2817

Bump libs to 1.2.100

---

libs/package-lock.json
libs/package.json

Forgot to run `npm run build` before publishing previous version, and can't override it 😞

Bump libs to 101

---

identity-service/package-lock.json
identity-service/package.json
libs/package.json

Update attestation responses based on new AAO
test on staging
n/a

Consume libs 1.2.101

---

solana-programs/anchor/audius-data/lib/lib.ts
solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
solana-programs/anchor/audius-data/tests/audius-data.ts
solana-programs/anchor/audius-data/tests/test-helpers.ts

Add missing delegation functions to lib and reorganize lib co-loclating types and functions. 
Fixes ASI-1020.
Updated existing tests to use lib instead of RPC.
No monitoring.

Add delegation functions to lib

---

libs/src/api/account.js

- Needs new libs version and client changes

Remove userbank creation signup feature flag

---

libs/package-lock.json
libs/package.json

Gets us https://github.com/AudiusProject/audius-protocol/commit/71b35a477d0160714959e8200fb9143132eb3681

Libs 1.2.102

---

libs/src/services/creatorNode/index.js

[] fix typo

---

libs/package.json

Fixes libs browser config by re-enabling util, which is web compatible and required!
Also bumps libs version to prepare for new release

Fix libs browser config

---

.circleci/config.yml
solana-programs/anchor/audius-data/cli/main.ts
solana-programs/anchor/audius-data/lib/lib.ts
solana-programs/anchor/audius-data/tests/audius-data.ts
solana-programs/anchor/audius-data/tests/playlist-social-actions.ts
solana-programs/anchor/audius-data/tests/playlist.ts
solana-programs/anchor/audius-data/tests/test-helpers.ts
solana-programs/anchor/audius-data/tests/track-social-actions.ts
solana-programs/anchor/audius-data/tests/ursm.ts
solana-programs/anchor/audius-data/tests/user-social-actions.ts

Update anchor libs to return transactions - so can be exported and used in libs to proxy via identity
Updated the tests too

Update libs to return transactions

---

discovery-provider/integration_tests/tasks/test_anchor_program_indexer.py

Small fix for broken test from https://github.com/AudiusProject/audius-protocol/pull/2867.
Tests pass.
No monitoring.

Fix anchor program indexer test by passing admin key

---

identity-service/src/routes/healthCheck.js
libs/src/services/solanaWeb3Manager/rewardsAttester.ts

Add healthcheck for if the reward attester stops taking actions
None

Fix attester stall

---

libs/package-lock.json
libs/package.json

Gets https://github.com/AudiusProject/audius-protocol/pull/2874 and https://github.com/AudiusProject/audius-protocol/pull/2877

Libs 1.2.105

---

identity-service/package-lock.json
identity-service/package.json
identity-service/src/routes/healthCheck.js

Gets https://github.com/AudiusProject/audius-protocol/pull/2874 and https://github.com/AudiusProject/audius-protocol/pull/2877
Tested beta libs on stage

Consume Libs 1.2.105 in Identity

---

service-commands/scripts/.zshrc

Remove `aup` -- not necessary anymore!

Update .zshrc to remove `aup` alias

---

libs/package-lock.json
libs/package.json

Bump libs to 1.2.106
Includes: 
- https://github.com/AudiusProject/audius-protocol/pull/2881
- https://github.com/AudiusProject/audius-protocol/pull/2889
- https://github.com/AudiusProject/audius-protocol/pull/2893
- https://github.com/AudiusProject/audius-protocol/pull/2879
- https://github.com/AudiusProject/audius-protocol/pull/2897

Bump @audius/libs v1.2.106

---

discovery-provider/integration_tests/tasks/test_anchor_program_indexer.py
discovery-provider/src/solana/anchor_program_indexer.py
solana-programs/anchor/audius-data/lib/lib.ts
solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
solana-programs/anchor/audius-data/tests/user-social-actions.ts

Make the admin account name consistent in the program to simplify instruction validation.
Created separate instruction validation test. 
No monitoring.

Update admin account name to be consistent for instruction validation

---

creator-node/.version.json
discovery-provider/.version.json

Bump to v0.3.56

---

creator-node/src/blacklistManager.js

Paginate insert into redis

---

discovery-provider/integration_tests/tasks/test_anchor_program_indexer.py
discovery-provider/src/solana/anchor_parser.py
discovery-provider/src/solana/anchor_program_indexer.py
discovery-provider/src/solana/audius_data_transaction_handlers.py
discovery-provider/src/solana/solana_program_indexer.py
discovery-provider/src/utils/cid_metadata_client.py

Update indexing in discovery to create a user record
NOTE: this will break with the pending program changes for ID
manually created user and viewed record in DB

Update index user

---

libs/package-lock.json
libs/package.json

Includes https://github.com/AudiusProject/audius-protocol/commit/557cae60afa221f8440a7903c3f3a40c2427d62f
Tested locally with client attestations

Libs 1.2.107

---

identity-service/package-lock.json
identity-service/package.json

Gets https://github.com/AudiusProject/audius-protocol/commit/557cae60afa221f8440a7903c3f3a40c2427d62f

Consume libs 1.2.107 in Identity

---

solana-programs/anchor/audius-data/lib/lib.ts
solana-programs/anchor/audius-data/package.json

Export types for libs to be consumed in @audius/libs

Export types from libs

---

libs/package-lock.json
libs/package.json

* Increase libs version to latest
* Required to consume connection getLatestBlockhash
Validated e2e locally with new message

Bump solana/web3.js

---

solana-programs/anchor/audius-data/cli/main.ts

Cleans up cli to not use anonymous async methods

Reformat audius-data cli

---

libs/package-lock.json
libs/package.json

Hareesh Nagaraj v1.2.108
Hareesh Nagaraj Bump solana/web3.js (#2919)

Bump Libs to v1.2.108

---

solana-programs/anchor/audius-data/cli/main.ts

CLI options were coming in as strings and not converting to booleans. This change fixes the boolean options. 
```
var myBool = Boolean("false");  // == true
```
https://stackoverflow.com/questions/263965/how-can-i-convert-a-string-to-boolean-in-javascript
Updated admin to true/false and ran createUser to see if admin was blocking the transaction.
No monitoring.

Fix audius data cli boolean options

---

libs/package-lock.json
libs/package.json

1.2.109 Raymond Jacobson
- #2945 by Raymond Jacobson
- #2939 by C.S. Jiang
- #2885) vicky : by
- #2934 by Hareesh Nagaraj

Libs 1.2.109

---

libs/package-lock.json
libs/package.json

Replay 1.2.109 -- version was published w/o anchor dep.
https://github.com/AudiusProject/audius-protocol/pull/2946

Libs 1.2.110

---

creator-node/compose/docker-compose.yml
identity-service/compose/docker-compose.full.yml

* Properly mount solana programs directory in order to support new libs downstream dependencies
* Validating locally by bringing up system

Mount solana-programs volume in identity-service and creator-node

---

libs/src/api/file.js
libs/src/utils/network.ts

Pass-through 403s on getCID to client
Local client visited several track pages and observed behavior on segment fetch
Nominally should have no impact, but playback could be impacted if 403s across entire replica set is erroneous.

[AUD-1930] Pass-through file 403 to client

---

service-commands/scripts/init-repos.sh

Remove local link step to prevent setup errors

---

identity-service/src/solana-client.js

* Ensure elapsed variable is properly updated for timeouts
* Tested on staging

Fix elapsed measurement bug in TrackListen tx submission

---

identity-service/src/notifications/emails/welcomeDownload.html

Fix email -- this PR https://github.com/AudiusProject/audius-protocol/pull/2967 missed one spot

Fix welcome download email

---

discovery-provider/integration_tests/tasks/test_index_users.py

Fix lint issues with test_index_users.py
Was able to pass pre-commit hook locally
Follow-up in INF-74 and INF-75

Fix lint issues

---

libs/package-lock.json
libs/package.json

v1.2.112 Dylan Jeffers
- #2844 by Dylan Jeffers
- #2962 by Theo Ilie
- #2943 by Dylan Jeffers
- #2941 by C.S. Jiang
Major change: added identity/requests to dist/core.js for consumption by audius-client AudiusBackend, which previously referenced source.

Bump libs to v1.2.112

---

creator-node/src/routes/files.js

This log makes us think the expected and actual paths are not consistent, but really it's just comparing current and legacy paths (which are going to be different).
This PR is to remove this log as it does not provide us much context in storage paths
No tests, just removing log
-1 log sorry 🌚

Remove error log comparing new and legacy paths

---

creator-node/src/TranscodingQueue.js
creator-node/src/components/healthCheck/healthCheckComponentService.js
creator-node/src/components/healthCheck/healthCheckComponentService.test.js
creator-node/src/components/healthCheck/healthCheckController.js

Exposes the health check to include data about the transcode queue
Example new health check:
```
"transcodeQueueIsAvailable": true,
"shouldHandleTranscode": true,
```
Updated the health check tests to include these fields
Should not need more logs

Expose transcode load balancing details

---

service-commands/scripts/.env/README.md

tabs != spaces

---

identity-service/src/utils/relayHelpers.js

- CreateTokenAccount was explicitly disallowed

Fix claimable relay check

---

discovery-provider/src/tasks/index_solana_plays.py

Eliminate batch resize, forcibly wipe cache to avoid intersect loop

---

identity-service/src/notifications/processNotifications/tierChangeNotification.js

Return notifications after processing tier changes
N/A - test on stage

Return the notifications after processing tierChange

---

creator-node/src/routes/tracks.js

Holding off track transcode load balancing until content node v0.3.58

Hold off track transcode load balancing

---

creator-node/.version.json
discovery-provider/.version.json

This PR bumps the version to 0.3.57
NA
NA

Bump to v0.3.57

---

creator-node/src/snapbackSM/peerSetManager.js

Fix an error related to the function signature for `asyncRetry()` updating.

[CON-70](bug fix): `asyncRetry()` signature update in `getNodeUsers()`

---

identity-service/sequelize/migrations/20220428223149-add_reactions.js
identity-service/src/authMiddleware.js
identity-service/src/models/reaction.js
identity-service/src/routes/reactions.js

- POST route to create a reaction
- GET route to index reactions
Tested E2E with seed commands

Support reactions in identity

---

discovery-provider/Dockerfile
service-commands/scripts/.env/.aliases/10.audius_aliases
service-commands/scripts/provision-dev-env.sh

Update outdated version comments and fix python path to use 3.9.
Updated docker image uses 3.9
https://pkgs.alpinelinux.org/packages?name=python3&branch=v3.15&repo=main&arch=x86_64&maintainer=Natanael+Copa
Tested change lines on my own dev machine. Opened new terminal and all aliases are working.
No monitoring.

Fix dev env python path and update version comments

---

libs/package.json

Bump libs version to `1.2.113` to support the new optional logger

[CON-76] Bump libs to v1.2.113

---

libs/package-lock.json
libs/package.json

Adds DiscoveryAPI to core entrypoint for audius-client
e1e80e02 * origin/master Export DiscoveryAPI in libs core entrypoint (#3038)

Libs v1.2.114

---

discovery-provider/scripts/start.sh

Fix missing fi

---

.circleci/config.yml

Have CircleCI match https://github.com/AudiusProject/audius-protocol/pull/3005.
Ensure builds still pass on this PR.

prune with -f within CircleCI

---

discovery-provider/alembic/versions/35198266d709_index_reactions.py
discovery-provider/src/app.py
discovery-provider/src/models/models.py
discovery-provider/src/models/reaction.py
discovery-provider/src/tasks/index_reactions.py

- Indexes reactions from Identity
- Introduces `RepresentableMixin` to we never have to hand write __repr__ again
Tested manually E2E. Real tests coming; tracking issue on linear.
Real monitoring coming. Will have a healthcheck /last timestamp in Redis. Tracking on linear.

[PAY-152] Discovery Node: Index Reactions

---

identity-service/package-lock.json
identity-service/package.json
identity-service/src/config.js
identity-service/src/routes/solana.js
identity-service/src/utils/relayHelpers.js

Pending libs integration with transaction handler update for adding signatures
Ran locally

Add identity relay with signature sol

---

libs/src/api/base.js

This param was not passed into in the Base class properly and broke libs
https://github.com/AudiusProject/audius-protocol/blame/fb3568d0e8ca1f987579c14c15ffe8f65400aa06/libs/src/index.js#L542
Prior to fix
```
$ A seed create-user
Got signup error: Requires the following services: Creator Node,Identity Service at phase: 
(node:301554) UnhandledPromiseRejectionWarning: Error: Requires the following services: Creator Node,Identity Service
```
Post-fix
```
Successfully seeded user with id: 3 and alias: 86fe7afcae75b313b638bbbadfb083e5
Created user!
Created 1 user(s) successfully!
```

Pass in anchorAudiusData

---

libs/package-lock.json
libs/package.json

- #3056 vicky : by
- #3043 by nicoback2 Add

Bump libs to v1.2.116

---

identity-service/src/notifications/fetchNotificationMetadata.js

Found this weird log when debugging identity. IDs were all joined together.
No testing.
No monitoring.

Fix fetch notification metadata log

---

discovery-provider/src/tasks/aggregates/__init__.py
discovery-provider/src/tasks/aggregates/index_aggregate_plays.py
discovery-provider/src/tasks/aggregates/index_aggregate_track.py
discovery-provider/src/tasks/index_aggregate_user.py

Fixes bug I introduced in #2993.
I [added Redis](https://github.com/AudiusProject/audius-protocol/pull/2993/files#diff-313206fb545abf8a6c07aebdcafa37b6040e4b332b83a07d96c78b135c483fbeR46) to the params of the `aggregate_func` so other callers needed to update their callback to fit the new contract.
Tested on remote

Fix aggregate functions

---

.circleci/config.yml

Forgot to checkout the right branch on the remove box before running mad-dog 🤦 
Ran mad-dog on CI and verified that it checks out the correct branch, which it does.
CI only feature, validated on CI that it printed out the git checkout <branch> logs.

Forgot to checkout the right branch before running mad dog

---

discovery-provider/requirements.txt
discovery-provider/src/api/v1/helpers.py
discovery-provider/src/queries/get_attestation.py
discovery-provider/src/utils/spl_audio.py

- SPL Token has 10^8 decimals, Wei $AUDIO has 10^18. Multiply by 10^10 for consistency
- Update `black` for consistency with pre-commit
Remote dev
N/A

Convert SPL to Wei for tip amounts

---

discovery-provider/scripts/seed.py
discovery-provider/src/tasks/index_aggregate_tips.py
discovery-provider/src/tasks/index_user_bank.py

- Fixes bug where tips are negative on staging
- Fixes bug where indexing aggregate_user_tips stalls
- Fixes seed script to not violate FK constraint on clear
Tested on remote, will test again on stage
No new logging

Fix negative tips, aggregate_tips

---

discovery-provider/src/api/v1/models/support.py
discovery-provider/src/api/v1/users.py

Adds `/v1/full/users/<id>/supporters` and `/v1/full/users/<id>/supporting`
Tested on remote with seeded users
No new logs necessary, recording metrics though

Add supporter/supporting endpoints to full ns

---

discovery-provider/src/queries/get_health.py

Add some tries in case indexes don't exist yet.
Ran locally and worked with/without ES.
Check if verbose health check works and has elasticsearch.

Add tries to es indexer health check

---

.circleci/config.yml
discovery-provider/es-indexer/src/indexNames.ts
discovery-provider/es-indexer/src/main.ts
discovery-provider/integration_tests/tasks/test_es_indexer.py
discovery-provider/scripts/test.sh
discovery-provider/src/queries/get_health.py

Add integration tests for the ES indexer in the extremely rare chance there's a bug.
Test catchup and new updates states.
N/A

Add ES indexer integration test

---

discovery-provider/integration_tests/challenges/test_first_tip_challenge.py
discovery-provider/src/challenges/challenge_event.py
discovery-provider/src/challenges/challenge_event_bus.py
discovery-provider/src/challenges/challenges.dev.json
discovery-provider/src/challenges/challenges.json
discovery-provider/src/challenges/challenges.stage.json
discovery-provider/src/challenges/send_first_tip_challenge.py
discovery-provider/src/tasks/index_user_bank.py

Adds a challenge for sending your first tip
Tested on my remote box with sending a tip and watching the challenge state change
UNit tests
Regular challenge monitoring mechanisms

[PAY-192] Add send first tip challenge

---

discovery-provider/src/api/v1/users.py

Fixes issue where #3091 forgot to make the full response have the block info etc

Make full supporter/supporting response fuller

---

discovery-provider/src/queries/notifications.py

Accidentally imported the wrong User model, causing the query for Reaction notifications to break. 
Testing on remote box.

Discovery: Fix Solana Notifications

---

discovery-provider/src/tasks/index_user_bank.py

Fixes negative tips
Keeping existing logging

Use correct sender/receiver account indexes

---

discovery-provider/src/queries/get_feed_es.py

metadata helper function was updated to return a copy, but calling code wasn't updated to collect it.

get_feed_es: user metadata fn returns copy

---

service-commands/scripts/provision-dev-env.sh

Add the GCP monitoring agent to the provisioning of new dev boxes
Tested by running the two commands on a fresh box

[INF-81] Add install of GCP monitoring agent to new box

---

creator-node/src/snapbackSM/snapbackSM.js

We [noticed some error logs](https://audius.loggly.com/search#terms=%22%5BissueUpdateReplicaSetOp%5D%20Reconfig%20%5BERROR%5D%22%20AND%20%22Request%20failed%20with%20status%20code%20500%22&from=2022-05-10T02:39:53.436Z&until=2022-05-17T02:39:53.436Z&source_group=) from `issueUpdateReplicaSetOp()`.
Most likely culprit is the identity relay for `UserReplicaSetManagerClient.updateReplicaSet()`, so just added a try-catch there with a better error msg
Existing tests should ensure no regressions
Currently we have no test coverage for this exact error case, but its in the works
Instances of error log `UserReplicaSetManagerClient.updateReplicaSet() Failed`

Wrap StateMachine:updateReplicaSet() call in try-catch [Content Node]

---

creator-node/src/routes/files.js

Replaces individual log with a decision tree stage for easier log investigation
N/A
Logs containing `EMPTY_FILE_FOUND_AND_REMOVED`

replace empty file removal log with decision tree stage [Content Node]

---

creator-node/.version.json
discovery-provider/.version.json

Upgrade to v0.3.58 in preparation for upcoming release

Upgrade to v0.3.58

---

creator-node/test/snapbackSM.test.js

Simple refactoring of snapback tests to group by function tested for better readability. The contents of the actual tests are unchanged.
N/A -- just modified test file and made sure it passes.
N/A -- just modified test file and made sure it passes.

Group snapback tests into describe blocks

---

creator-node/src/snapbackSM/snapbackSM.js
creator-node/test/snapbackSM.test.js

- Minor refactor: move selecting new replica set out of issueUpdateReplicaSetOp so it can be a more single-purpose function that's easier to test
- Fix test that was mocking snapback.endpointToSPIdMap instead of peerSetManager.endpointToSPIdMap
All tests pass.
Search for errors containing `[issueUpdateReplicaSetOp]` or `ERROR issuing update replica set op`.

Break selecting replica set out of issuing update

---

creator-node/src/components/contentBlacklist/contentBlacklistComponentService.js

Used to return array of strings. this makes it so the route returns array of numbers
existing test suite
downstream services will catch err

Return number type for ids

---

.circleci/config.yml

Move `build-contracts`, `build-eth-contracts`, and `build-solana-programs` CI steps to nightly workflow
N/A
N/A

Move contract and solana build CI steps to nightly workflow

---

libs/src/services/contracts/ContractClient.ts

Re-land https://github.com/AudiusProject/audius-protocol/compare/hn_libs_initialized_update?expand=1
This was cherry-picked onto prod

[PLAT-129] Only init contract if there is an address

---

discovery-provider/src/api/v1/helpers.py

Return wei string for supporting amount to make the UI consistent
Will deploy to a stage DN and check
n/a

Return wei string for supporting amount

---

identity-service/compose/.env
identity-service/sequelize/migrations/20220512172226-add_notification_json_b.js
identity-service/src/models/solanaNotification.js
identity-service/src/notifications/constants.js
identity-service/src/notifications/processNotifications/index.js
identity-service/src/notifications/processNotifications/reactionNotification.js
identity-service/src/notifications/processNotifications/supporterRankChangeNotification.js
identity-service/src/notifications/processNotifications/tipNotification.js
identity-service/src/routes/notifications.js

- Adds 5 new notification types
- Adds new JSONB metadata column on SolanaNotifications
- Tested extensively E2E

[PAY-120] Consume tipping notifications in Identity

---

identity-service/src/routes/solana.js
libs/src/services/solanaWeb3Manager/transactionHandler.js
service-commands/scripts/seed.js
service-commands/src/commands/seed/SeedSession.js
service-commands/src/utils/seed.js

- Follows same pattern as listens, but with some minor refactors, improved logging, etc
- Tested locally and on stage

Add retries to transaction handler

---

libs/package-lock.json
libs/package.json
libs/src/services/solanaWeb3Manager/transactionHandler.js

Gets https://github.com/AudiusProject/audius-protocol/commit/d95cb722bfe8372defdb7f8e5ea70898cfd4c045

Libs 1.2.117

---

identity-service/package-lock.json
identity-service/package.json

Gets https://github.com/AudiusProject/audius-protocol/commit/d95cb722bfe8372defdb7f8e5ea70898cfd4c045

Consume libs 1.2.117 in Identity

---

libs/src/services/solanaWeb3Manager/transactionHandler.js

- Fixes bug where error wasn't being propagated properly through promise rejection
- Fixes bug where error code wasn't being parsed correctly, regression from 3 wks ago
- Fixes logging bugs
- Tested extensively on stage

Fix Solana Retry Bugs

---

libs/package-lock.json
libs/package.json

Includes https://github.com/AudiusProject/audius-protocol/commit/84d30bd833fbf723d0292fe7fce3dff5aa2e0e0d

Libs 1.2.118

---

identity-service/package-lock.json
identity-service/package.json

Gets https://github.com/AudiusProject/audius-protocol/commit/84d30bd833fbf723d0292fe7fce3dff5aa2e0e0d

Consume Libs 1.2.118 in Identity

---

discovery-provider/flake8_plugins/flask_decorator_plugin/visitor_helpers.py

Fixes the Flake8 plugin I wrote to detect multiple route parameters by modifying the regex used to parse them.
Tested against incoming changes for the users/<id>/supporters/<id> route
N/A, will rely on dev feedback

Flake8 Plugin: Fix multiple route parameter detection

---

creator-node/.version.json
discovery-provider/.version.json

Bump version to v0.3.59

---

discovery-provider/src/api/v1/reactions.py
discovery-provider/src/queries/reactions.py

Only fetch the reaction with the highest slot #

Fix reactions endpoint for multiple reactions

---

discovery-provider/src/api/v1/reactions.py
discovery-provider/src/queries/reactions.py

- This endpoint was not properly handling the no reaction case

Fix reactions endpoint 404 case

---

identity-service/src/notifications/processNotifications/reactionNotification.js
identity-service/src/routes/notifications.js

- Consume latest DN changes (react_to_entity)

[PAY-297] Change reaction notification handling on Identity

---

identity-service/src/notifications/index.js

Temporarily halting sending out these emails. Got a msg about high bounce rates.
Tested with mad dog that identity runs with no issues.
We have statistics from mailgun

Disable download app email

---

discovery-provider/src/queries/reactions.py

Add optional to allow None return value. 
No test
N/A

Fix reaction lint

---

service-commands/scripts/setup-instance.sh
service-commands/scripts/utils.sh

Get rid of /etc/host modification since we now use smarter ssh_config settings.
`A setup remote-dev` should work without issues.

Remove /etc/hosts modification

---

.github/pull_request_template.md

Tweaked PR template for clarity (this PR description is using proposed template)
n/a
n/a

Improve GH pull request template readability/usability

---

monitoring/grafana/dashboards/discovery-provider.json
monitoring/grafana/dashboards/load-test.json

Updates to the newest dashboards.

update to new dashboards

---

discovery-provider/alembic/versions/cdf1f6197fc6_add_play_geolocation.py

Fix alembic migration conflict.
CI passes
N/A

Fix geolocation play migration conflict

---

.circleci/config.yml
discovery-provider/src/tasks/index_solana_plays.py
identity-service/src/solana-client.js

Allow identity to gate location feature based on the API key. Make sure all DPs are upgraded before updating the API key.
Tested on staging.
Verify plays are being indexed.

Fix identity feature flag for location

---

discovery-provider/src/api/v1/playlists.py
discovery-provider/src/api/v1/tracks.py
discovery-provider/src/api/v1/users.py

Fixes null response 
```
{
"data": [
{
"album_count": null,
"bio": null,
"cover_photo": null,
"followee_count": null,
"follower_count": null,
"does_follow_current_user": null,
"handle": null,
"id": null,
"is_verified": null,
"location": null,
"name": null,
"playlist_count": null,
"profile_picture": null,
"repost_count": null,
"track_count": null,
"is_deactivated": null,
"erc_wallet": null,
"spl_wallet": null,
"supporter_count": null,
"supporting_count": null
}
]
}
```
Testing on sandbox.
users
```
{
"album_count": 0,
"bio": null,
"cover_photo": null,
"followee_count": 4,
"follower_count": 17,
"does_follow_current_user": false,
"handle": "Isaac",
"id": "DrdKN",
"is_verified": false,
"location": "Mexico City, CMX",
...
```
tracks
```
"artwork": {
"150x150": …
```

Fix v1 search APIs on elasticsearch

---

creator-node/.version.json
discovery-provider/.version.json

Bump CN and DP version to 0.3.60
NA
NA

Bump to version 0.3.60

---

discovery-provider/Dockerfile
discovery-provider/compose/.test.env
discovery-provider/scripts/test.sh
discovery-provider/scripts/up.sh

* fix `es-indexer/build` in Dockerfile
* start es container in `test.sh`
did a `docker build .` and ran `test.sh`

fix test.sh and Dockerfile

---

creator-node/scripts/start.sh

Remove watchtower from Creator Node startup
NA
NA

Remove watchtower

---

discovery-provider/alembic/versions/38642fb2948d_add_pg_triggers.py

Fix play trigger name

---

contracts/migrations/5_audius_data_migration.js

Deploys local contract for testing purposes, will be used in production as well
Validated manually on local stack

[PLAT-196] Simple data migration

---

identity-service/src/featureFlag.js
identity-service/src/notifications/fetchNotificationMetadata.js
identity-service/src/notifications/formatNotificationMetadata.js
identity-service/src/notifications/processNotifications/utils.js
identity-service/src/notifications/sendNotifications/formatNotification.js
identity-service/src/notifications/sendNotifications/index.js
identity-service/src/notifications/sendNotifications/publishNotifications.js

Adds push notifications for tipping related features:
- TipReceived
- SupportingRankUp
- SupporterRankUp
- Reaction
Tested on remote box via logs. Testing on stage.

[PAY-299] Add Tipping Push Notifications

---

discovery-provider/plugins/network-monitoring/src/db/index.ts
discovery-provider/plugins/network-monitoring/src/db/migrations/create_foreign_connection.ts
discovery-provider/plugins/network-monitoring/src/utils.ts
monitoring/prometheus/ymls/stage.yml

This PR includes changes I've made based on my experience deploying network monitoring onto staging.
Major changes are:
* Updating env to add the foreign DB env vars
* changing the prometheus target host for network monitoring to be an IP address rather than a DNS name
Tested by running locally and on staging node
Changes will be monitored with data being populated in prometheus and grafana.

Network Monitoring Staging Refactor

---

monitoring/grafana/dashboards/audius-boilerplate.json
monitoring/grafana/dashboards/audius-internal-health.json
monitoring/grafana/dashboards/discovery-provider.json
monitoring/grafana/dashboards/load-test.json
monitoring/grafana/dashboards/network-monitoring.json

Running `./grafana/bin/save-dashboards.sh` against Production and saving current state.
None required.

INF-139 saving newest dashboards

---

identity-service/Dockerfile

Add bash to dependencies so that we can run via docker compose
Dependency addition -> no code changes
NA

Add bash to identity service

---

discovery-provider/plugins/network-monitoring/src/content/index.ts
discovery-provider/plugins/network-monitoring/src/content/queries.ts
discovery-provider/plugins/network-monitoring/src/db/index.ts
discovery-provider/plugins/network-monitoring/src/prometheus.ts

This PR fixes a bug with updating user clock values where transactions would timeout trying to acquire a connection.
This PR also renames the prometheus gauges with a `network_monitoring_` prefix
Tested locally by running a job and viewing logs for `timeout` issues
A prometheus metrics `network_monitoring_missed_users_count` was added to see if a significant number of users is being skipped.

Network Monitoring DB Timeout Fix

---

libs/README.md
libs/package.json

@audius/sdk v0.0.5

---

libs/package-lock.json
libs/package.json

This is part of the fix for the local setup issues we are seeing
(Bump to 0.0.7 because I already published 0.0.6)

Bump libs and @types/async-retry

---

creator-node/.version.json
discovery-provider/.version.json

Bump to v0.3.61

---

discovery-provider/default_config.ini

Increase discovery db conn pool for local env from 20 to 200
N/A
N/A

Increase discovery db conn pool for local env from 20 to 200

---

discovery-provider/default_config.ini

This reverts commit f0b7e85410aad46cfffc26dd34b0bb6320e17df7.

Revert "Increase discovery db conn pool for local env from 20 to 200 (3342)"

---

discovery-provider/alembic/versions/38642fb2948d_add_pg_triggers.py

Wrap sql in `sqlalchemy.text` call
actually ran the tests this time 😢

add sqlalchemy text call

---

creator-node/src/services/stateMachineManager/stateMonitoring/index.js

This is required since snapback monitoring was disabled in recent commit https://github.com/AudiusProject/audius-protocol/commit/59420a47ceaabe05fb7fbce8526e2044a6d8a162
Existing regression tests sufficient
Bull dashboard at `<cn>/health/bull/queue/state-monitoring-queue` should be non-empty

Enable stateMonitoring by default on local env

---

libs/src/utils/network.ts

Return full response in allRequests helper.
https://linear.app/audius/issue/C-647/make-ga-return-only-versioned-discovery-nodes
Locally vs. prod in linked general admission

[C-467] Return full service response

---

libs/package-lock.json
libs/package.json

[8ac2cf81] SDK 0.0.10 Raymond Jacobson
[408fc851] Return full service response (#3360) Raymond Jacobson

SDK 0.0.10

---

discovery-provider/src/challenges/challenges.dev.json
discovery-provider/src/challenges/challenges.json
discovery-provider/src/challenges/challenges.stage.json

Updated reward amount for send-first-tip challenge to 2 (from 3) $AUDIO.
Per @julianbaker's copy:
https://docs.google.com/document/d/1tedZ74A-BrwXtCS6YXp0NRuikn9TLOJg-eU6Pq7veRA/edit#

[PAY-385] Updated Send First Tip Reward Amount

---

discovery-provider/src/tasks/update_track_is_available.py

Let's add metrics for the `update_track_is_available` worker! 
Grafana dashboards on celery tasks with this `update_track_is_available` label

Add update_track_is_available metrics

---

discovery-provider/src/app.py
discovery-provider/src/database_task.py
discovery-provider/src/tasks/cache_trending_playlists.py

Add read replica to celery task and trending playlist cache job.

[AUD-1964] Add read replica to celery and trending cache job

---

libs/src/services/discoveryProvider/DiscoveryProvider.ts
libs/src/services/discoveryProvider/requests.ts

Update to pr: #3354 to update name to avoid confusion with playlist trending endpoint

Update libs name

---

discovery-provider/integration_tests/challenges/test_first_playlist_challenge.py
discovery-provider/src/challenges/challenge_event.py
discovery-provider/src/challenges/challenge_event_bus.py
discovery-provider/src/challenges/challenges.dev.json
discovery-provider/src/challenges/challenges.json
discovery-provider/src/challenges/challenges.stage.json
discovery-provider/src/challenges/first_playlist_challenge.py
discovery-provider/src/tasks/playlists.py

Adds challenge for creating your first playlist and adding a track to it.
Note - due to some git snafu I am opening a new pull request. Please see the previous discussion for this commit at:
https://github.com/AudiusProject/audius-protocol/pull/3375
Unit test - test_first_playlist_challenge.py
Ran local web client against DN on my remote box and confirmed that challenge completion row gets added to user_challenges db.
Regular challenge monitoring mechanisms

[PAY-385] Added First Playlist Challenge

---

libs/README.md

Fixes README. Docs need to be updated.

Update SDK README

---

libs/package-lock.json
libs/package.json

[b78092274] Update SDK README (#3392) Raymond Jacobson
[e7d76e028] Refactor libs base.js and serviceProvider.js classes to Typescript (#3363) Michael Piazza
[c66164c64] Rename method to avoid confusion (#3366) Joseph Lee
[2ace9457f] Add libs explore endpoints (#3354) Joseph Lee
[30e53c826] [PAY-401] Fix Solana Node registration script (#3362) Michael Piazza

SDK 0.0.11

---

discovery-provider/src/tasks/audius_data.py
discovery-provider/src/tasks/index.py
libs/src/api/audiusData.ts

Deletes a playlist.
Ran locally and deleted a playlist.

Add delete playlist to audius data libs + indexing

---

discovery-provider/src/queries/get_trending_playlists.py

Use aggregates in playlist trending query for better db perf

Use aggregate calls

---

monitoring/grafana/dashboards/dheeraj-content-node-dashboard-test.json

Snapshot of changes from production.
A concise version of #3413 that only includes changes we want into master.
None

Grafana Production Dashboard Snapshot

---

identity-service/src/notifications/index.js

This reverts commit f53ad548cf9a538fe891a8444b282d95d612bc92.

Revert "Disable 2 day download app email (#3204)"

---

discovery-provider/src/queries/notifications.py

Filter out notifications for track added to playlist where the track is unlisted or deleted

Update notifications track added to playlist

---

identity-service/sequelize/migrations/20220711214812-add-deliverability.js
identity-service/src/models/user.js
identity-service/src/notifications/sendDownloadAppEmails.js
identity-service/src/notifications/sendNotificationEmails.js
identity-service/src/routes/user.js

* Add col to users for email deliverability - which is checked on user signup
* Update 2 day emails to use upper bound of 5 days

Identity verify email

---

libs/package-lock.json
libs/package.json

Includes change to fix export https://github.com/AudiusProject/audius-protocol/commit/a26dcc697bd43c6e874220412f85a1c0b3057d60

@audius/sdk 0.0.12

---

libs/package-lock.json
libs/package.json

Includes https://github.com/AudiusProject/audius-protocol/pull/3435

@audius/sdk v0.0.13

---

creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js

Fixes logs `Duplicate sync request: [Object object]` and `Failed to create manual sync request: undefined`
N/A
Logs containing `Duplicate sync request` or `Failed to create manual sync request`

issueSyncRequestsUntilSynced - log nit

---

creator-node/.version.json
discovery-provider/.version.json

Bump to version 0.3.62

---

libs/README.md

Adds a note to the sdk readme to use the web3 script tag when using create-react-app v5

Add note to sdk readme about web3 polyfill

---

libs/package-lock.json
libs/src/utils/types.ts

`console.verbose()` is not valid, removing
Confirmed this function is not called anywhere
N/A
N/A

Libs - Remove invalid Logger.verbose

---

libs/package-lock.json
libs/package.json

Johannes Naylor v0.0.15
Sid Sethi Remove Logger.verbose type (#3456)
Johannes Naylor [CON-183] Fix libs logger issue in CN by consuming latest typed libs
Sebastian Klingler Add note about web3 polyfill (#3451)
Sebastian Klingler [C-655] Make localStorage configurable in libs & sdk (#3373)

Bump sdk to v0.0.15

---

creator-node/package.json

Bump @audius/sdk to v0.0.15 to consume the new logger bug fixes
tested by running locally
These changes can be monitored with loggly, namely making sure the error "`_this2.logger.log()` is not a function" is gone.

Bump sdk version on content node to 0.0.15

---

libs/package-lock.json
libs/package.json
libs/src/api/account.js
libs/src/libs.js
libs/src/services/hedgehog/Hedgehog.ts
libs/types/@audius-hedgehog/index.d.ts

Adjust usage of Hedgehog based on changes in this PR (major version change) https://github.com/AudiusProject/hedgehog/pull/46/files
Need to link hedgehog + libs locally and test in browser; will update this when done

Use new Hedgehog custom local storage option

---

libs/package-lock.json
libs/package.json

Changelog:
nicoback2 Use new Hedgehog custom local storage option (#3420)
Cheran [INF-76] New Local Deployment Setup with docker-compose (#2988)

Bump SDK to version 0.0.16

---

contracts/contracts/EntityManager.sol
contracts/migrations/5_entity_manager_migration.js
contracts/signature_schemas/signatureSchemas.js
contracts/test/_lib/artifacts.js
contracts/test/entityManager.js

* Renaming AudiusData to EntityManager contract layer
* Requires a follow up w/new pre-baked image to fully propagate, this is an intermediate step
* Existing tests pass
* Extensively testing with `hn_audius_data_write_path` prior to merge

Renaming AudiusData Contract to EntityManager

---

libs/package-lock.json
libs/package.json

No changes to SDK but v0.0.16 seemed to be missing something.

Bump @audius/sdk to v0.0.17

---

discovery-provider/scripts/start.sh

Increase timeout until we separate the containers and space out migrations from celery worker

Increase start.sh timeout

---

discovery-provider/alembic/versions/08becec375f3_remove_is_creator.py

Fix migration ordering

---

contracts/Dockerfile.dev
contracts/package-lock.json
contracts/package.json
contracts/scripts/setup-predeployed-ganache.sh
contracts/truffle-config.js
dev-tools/startup/poa-ganache.sh
docker-compose.yml

Verify POA contracts so that the local block explorer lets us interact with a GUI
Works with local block explorer
NA

[INF-188] Verify contracts on POA for block explorer

---

contracts/Dockerfile.dev
contracts/scripts/setup-predeployed-ganache.sh

Adds network id to POA contracts, this was missing and caused transactions to fail on POA.
Works with https://github.com/AudiusProject/audius-client/pull/1577
NA

Add chain network id for client fixes

---

dev-tools/startup/poa-ganache.sh

Cleans up some output when verifying contracts on local explorer
NA
NA

Cleanup output

---

libs/src/services/wormhole/index.js

Combed through libs looking for `window` and `process.env` references; this was the last one I could find that did not have an undefined check. 
Context:
Making libs compatible for all platforms (e.g.  browser, node, react native)

C-662 Throw error for function requiring window

---

libs/types/@audius-hedgehog/index.d.ts

Fix Hedgehog "set" function types to avoid this error:
https://audius-internal.slack.com/archives/C03C2V84A1L/p1658242439771759

Fix Hedgehog fn types

---

identity-service/src/routes/notifications.js

Unread count not working for tipping notifs

Fix unread count for tipping notifs

---

.circleci/config.yml

Add missing npm cred required to push packages.
Test manually on this branch followed by releasing via master:
* https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/25262/workflows/63cb89ea-656f-478a-b349-027fce5da7ea/jobs/301179

Add npmrc credential

---

.circleci/config.yml
libs/scripts/release.sh

The manual changes that were required to release 0.0.18.
Once merged, we will kick off one more test.

INF-86 working publishing of audius-sdk

---

creator-node/src/middlewares.js

The inspiration from this PR was when we were doing our workshop on debugging user state, and I did not have context as to the actual error. So this is adding the error msg to have more clarity.
No tests, just adding error msg
See this write quorum prefix error in the logs `issueAndWaitForSecondarySyncRequests Error - Failed to reach 2/3 write quorum for user`

Add error msg to write quorum error logging

---

identity-service/src/notifications/sendNotifications/publishNotifications.js

Skip bad notifs
checking logs against stage identity. and check that bad notifs not being sent
yes

Skip bad notifs

---

creator-node/src/services/prometheusMonitoring/prometheus.constants.js

A bad merge caused an error in CI. This PR fixes that error
This PR fixes tests
This'll be monitored with CI

Fix prometheus metrics name error

---

discovery-provider/scripts/start.sh

Do not use the mounted celereybeat.pid file, so when restarting the container, we recreate

Add container-side pidfile for celery

---

.circleci/config.yml
libs/scripts/verify-types.sh

Fixes a couple issues with the test-sdk ci job, including properly diffing for disc-prov changes and moving the conditional logic into a shell script
Was working on using a leaner discovery provider up, was having some luck with a combination of the `circle-ci.sh` and `up.sh` scripts but there were just too many dependencies to get working properly. Didn't want to sink too much time into it so decided to stick with the `A up` method that is already working, albeit a little more expensive

Small improvements to the test-sdk ci job

---

creator-node/.version.json
discovery-provider/.version.json

Bump to version 0.3.63

---

.circleci/config.yml

Resolve [this error](https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/25792/workflows/99fe0be6-6af0-4b0c-bb25-94d13a3d7bc2/jobs/307784) that was looking for a circle job, not command.
Running through a few deployments on master currently.

INF-210 skip usage of slack/basic for now

---

libs/package.json

Libs failed to bump previously due to a merge conflict.
Manually verifying releases currently.

INF-210 Bump libs

---

.circleci/config.yml

INF-210 only slack after setup

---

libs/package.json

Prime the first value to allow CI/CD to work as intended.
Manually testing SDK releases on master.

INF-210 Prime audius.releaseSHA in libs/package.json

---

libs/scripts/release.sh

Squash merge commit and display URLs to confirm release status.
Manually testing publishing SDK on master.

INF-210 Squash merge commits when publishing SDK

---

.circleci/config.yml
libs/examples/initAudiusLibs.js

Two bugfixes here
1. --fast option wasn't being properly applied because of brackets
2. Change libs from dist/index to dist/index.cjs.js. Couldn't find dist/index.js in the directory
Tested on CircleCI
CircleCI will be successful

Fix GCP Image bake and local service registration

---

creator-node/scripts/register.js
dev-tools/startup/creator-node.sh

Rename libs to sdk

---

discovery-provider/alembic/trigger_sql/handle_follow.sql
discovery-provider/alembic/trigger_sql/handle_playlist.sql
discovery-provider/alembic/trigger_sql/handle_repost.sql
discovery-provider/alembic/trigger_sql/handle_save.sql
discovery-provider/alembic/trigger_sql/handle_track.sql
discovery-provider/alembic/trigger_sql/handle_user.sql
discovery-provider/alembic/versions/90ad232bfe92_triggers_count_from_scratch.py

Instead of increment / decrement trigger behavior, count records from scratch every time.
* Currently running `test.sh`
* Will test manually

triggers count from scratch

---

dev-tools/startup/build-audius-libs.sh

Change path due to recent libs change

---

discovery-provider/alembic/versions/35584b65c55e_related_artists_index.py
discovery-provider/src/models/users/related_artist.py

* removes redundant index (same as pk)
* adds reverse index
Updated version of: https://github.com/AudiusProject/audius-protocol/pull/3466

Related artists index2

---

.circleci/triggers/__init__.py
.circleci/triggers/deploy-sdk.py
libs/scripts/release.sh

Left over tweaks for cleaner SDK publishing workflow.
Manually releasing off `master`.

INF-210 Finishing changes

---

discovery-provider/alembic/trigger_sql/handle_follow.sql
discovery-provider/alembic/trigger_sql/handle_playlist.sql
discovery-provider/alembic/trigger_sql/handle_repost.sql
discovery-provider/alembic/trigger_sql/handle_save.sql
discovery-provider/alembic/trigger_sql/handle_track.sql
discovery-provider/alembic/versions/d0dfb103535b_update_triggers_to_remove_duplicate_.py
discovery-provider/integration_tests/models/test_aggregate_counters.py
discovery-provider/src/utils/alembic_helpers.py

adds basic tests for trigger counters
✅

Tests for aggregate table triggers

---

creator-node/src/services/sync/syncImmediateQueue.js

We need to throw the error if syncImmediateQueue does not succeed.
Tested on CI via maddog and on staging
Logs

Throw error in syncImmediateQueue

---

libs/rollup.config.js
libs/src/NativeAudiusLibs.ts
libs/src/native-libs.ts

Adds native libs entrypoint that can run on native environment
- Adds `NativeAudiusLibs` and `native-libs` file so the import is `@audius/sdk/dist/native-libs`
Test pass
Native app can import

[C-765] Add native libs entrypoint

---

identity-service/package-lock.json
identity-service/package.json

Updates Identity SDK version to get latest node registration job: https://github.com/AudiusProject/audius-protocol/pull/3362
Hopefully fixes ```(node:233) UnhandledPromiseRejectionWarning: ReplyError: ERR value is not an integer or out of range
at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14)```
Tests on staging

[PAY-401] Update Identity SDK to fix Solana Node Registration Job

---

libs/scripts/release.sh

Include v as part of $VERSION
Manually testing off `master`.

INF-210 include v as VERSION prefix

---

creator-node/src/services/sync/secondarySyncFromPrimary.js

A wallet can get into a deadlocked state when an initial sync fails but returns without committing or rolling back the Postgres transaction. This causes the table to have blocked rows for the wallet, which makes queries from subsequent sync jobs hang.
The solution in this PR is to re-throw any error encountered during syncs so that we always reach the transaction rollback in the catch block.
Tests+mad dog pass, and manual Postgres inspection shows no more blocked queries when issuing a sync. To find blocked queries:
```sql
select pid, 
usename, 
pg_blocking_pids(pid) as blocked_by, 
query as blocked_query
from pg_stat_activity
where cardinality(pg_blocking_pids(pid)) > 0
```
- Check if prod CN2 has hanging jobs in the sync-processing-queue, since that's where we noticed this issue
- To be …

Make syncs release locks when short circuiting

---

creator-node/scripts/register.js

Fix local CN register due to missing delegateOwnerWalet
NA

Add delegateOwnerWallet to CN register

---

identity-service/package-lock.json
identity-service/package.json
identity-service/src/relay/ethTxRelay.js
identity-service/src/relay/txRelay.js

It sounds like chainId is a required field to comply with https://eips.ethereum.org/EIPS/eip-155#example and alchemy will be strictly enforcing EIP 155 compliance end of month.
I believe upping to 2.x.x of EthereumTx will get us what we need https://github.com/ethereumjs/ethereumjs-tx/releases/tag/v2.0.0
This nicely also matches version with what we have in sdk
Local stack works, but better to test on staging vs. ropsten.

[PLAT-259] Upgrade EthereumTx version

---

discovery-provider/alembic/trigger_sql/handle_repost.sql
discovery-provider/alembic/trigger_sql/handle_save.sql

Didn't realize repost also trigger a cosign notification, adding that here

Add remix cosign

---

discovery-provider/integration_tests/queries/test_get_playlist_id_occupied.py
discovery-provider/src/api/v1/models/common.py
discovery-provider/src/api/v1/playlists.py
discovery-provider/src/queries/get_playlist_is_occupied.py
libs/src/services/discoveryProvider/DiscoveryProvider.ts
libs/src/services/discoveryProvider/requests.ts

available playlist ID endpoint

---

creator-node/src/components/replicaSet/replicaSetController.js
creator-node/src/components/replicaSet/syncQueueComponentService.js
creator-node/src/services/sync/syncImmediateQueue.js

Rename processImmediateSync to processManualImmediateSync to clear up confusion with naming.
Test with sync locally and un mad-dog on CI
Jobs should be getting added and processed on bull dashboard

Rename processImmediateSync to processManualImmediateSync for clarity

---

discovery-provider/alembic/env.py

don't attempt to kill superuser queries.
* manually ran alembic down / up
* should also be tested as part of the alembic idempotent up / down test.

safer kill_running_queries_sql

---

service-commands/package-lock.json
service-commands/package.json

Upgrade service-commands sdk to default to latest version.
Tested locally without sdk linked by running `A seed create-user`
`A seed` should work

Upgrade service-commands to latest sdk

---

discovery-provider/alembic/trigger_sql/handle_challenge_disbursements.sql
discovery-provider/alembic/trigger_sql/handle_follow.sql
discovery-provider/alembic/trigger_sql/handle_play.sql
discovery-provider/alembic/trigger_sql/handle_playlist.sql
discovery-provider/alembic/trigger_sql/handle_reaction.sql
discovery-provider/alembic/trigger_sql/handle_repost.sql
discovery-provider/alembic/trigger_sql/handle_save.sql
discovery-provider/alembic/trigger_sql/handle_supporter_rank_ups.sql
discovery-provider/alembic/trigger_sql/handle_track.sql
discovery-provider/alembic/trigger_sql/handle_user_tip.sql
discovery-provider/alembic/versions/9931f7fd118f_migrate_miletones_to_notifications.py
discovery-provider/alembic/versions/b0623220e904_create_notifications_table.py
discovery-provider/integration_tests/notifications/test_challenge_disbursement.py
discovery-provider/integration_tests/notifications/test_follow.py
discovery-provider/integration_tests/notifications/test_play_milestone.py
discovery-provider/integration_tests/notifications/test_playlist.py
discovery-provider/integration_tests/notifications/test_reaction.py
discovery-provider/integration_tests/notifications/test_repost.py
discovery-provider/integration_tests/notifications/test_save.py
discovery-provider/integration_tests/notifications/test_supporter_rank_ups.py
discovery-provider/integration_tests/notifications/test_track.py
discovery-provider/integration_tests/notifications/test_user_tip.py
discovery-provider/src/models/notifications/notification.py
discovery-provider/src/tasks/index_rewards_manager.py

Add a unique constraint to notification tbl and update tests

Add unique constraint to notification

---

creator-node/.version.json
discovery-provider/.version.json

Bump to version 0.3.64

---

libs/src/sdk/sdk.ts

Fixes issue with calling `full` endpoints via the sdk. The `default` configuration was being used which had the wrong base path

Use correct configuration for full endpoints

---

discovery-provider/alembic/versions/9931f7fd118f_migrate_miletones_to_notifications.py
discovery-provider/alembic/versions/b0623220e904_create_notifications_table.py
discovery-provider/integration_tests/notifications/test_reaction.py

Fix downgrades

---

libs/src/api/Rewards.ts
libs/src/services/solana/rewardsAttester.ts

Expose AAO error codes in rewardsAttester.
Manually tested on web client.

[PAY-506] Exposes AAO error code

---

creator-node/src/services/sync/secondarySyncFromPrimary.js

Just a log to warn if a resync is about to occur
No tests, just a log
This log message `[secondarySyncFromPrimary][wallet=${wallet}] Forcing resync..`

Add a log before force resync happens

---

identity-service/package-lock.json
identity-service/package.json
identity-service/src/relay/ethTxRelay.js
identity-service/src/relay/txRelay.js

This reverts commit 21fc91b10563fb51f934142f065a0ea7c5803828.
Breaking relay potentially

Revert "[PLAT-259] Upgrade EthereumTx version (#3606)"

---

identity-service/sequelize/migrations/20220811205355-add-abusive-error-code.js
identity-service/src/featureFlag.js
identity-service/src/routes/relay.js
identity-service/src/utils/antiAbuse.js

Use abuse scores more in relay

Use abuse error codes in relay

---

discovery-provider/integration_tests/tasks/test_entity_manager.py
discovery-provider/integration_tests/tasks/test_track_entity_manager.py
discovery-provider/src/api/v1/models/common.py
discovery-provider/src/tasks/entity_manager/entity_manager.py
discovery-provider/src/tasks/entity_manager/playlist.py
discovery-provider/src/tasks/entity_manager/track.py
discovery-provider/src/tasks/entity_manager/types.py
discovery-provider/src/tasks/index.py
discovery-provider/src/tasks/playlists.py
discovery-provider/src/tasks/tracks.py

Adds track processing via the entity manager
copied over playlists, but for tracks, also tested that track routes were produced

add track entity manager

---

identity-service/src/models/user.js
identity-service/src/utils/antiAbuse.js

Forgot to handle 0 error code here https://github.com/AudiusProject/audius-protocol/pull/3683

Handle zero error code

---

libs/package-lock.json
libs/package.json

Updates @solana/spl-token to 0.1.8 to match client peer dep (in next release) so that `Token.createTransferCheckedInstruction` is in the `.d.ts` file

[Libs]: Update @solana/spl-token to 0.1.8

---

identity-service/src/notifications/sendNotifications/publishNotifications.js

- Was missing in a list of allowed push notif types

[PAY-530] Fix dethroned push notifs

---

identity-service/src/routes/relay.js

Allow abusive user redemption by firing abuse detection, even if current relay returns a forbidden response.

Allow abusive user redemption

---

discovery-provider/build/contracts/EntityManager.json

Add entity manager contract ABI

---

libs/src/sdk/api/generated/full/models/PlaylistAddedTimestamp.ts

Add missing type that's used in EntityManager: https://github.com/AudiusProject/audius-protocol/blob/12ecc4fac3b9cef546359aad86a5dd796ee1c0e8/libs/src/api/entityManager.ts#L64-L65.

Add playlist metadata timestamp type

---

identity-service/src/routes/relay.js

So we don't block relay for users who don't meet the block criteria.

Update block error codes

---

identity-service/src/routes/recovery.js
identity-service/src/routes/welcomeEmail.js

Avoid sending welcome or recovery on deliverability issues
Checked db and the field is being set well
Logs added for both cases.

Avoid sending recovery and welcome emails

---

discovery-provider/src/queries/get_user_listening_history.py

The original way I wrote this query wasn't sitting right with me.
I also think it's (inconsistently) slow.
Here are the query plans--
before:
```
Nested Loop Left Join  (cost=2.27..4665.63 rows=350 width=2227)
->  Nested Loop Left Join  (cost=1.71..3058.90 rows=113 width=1426)
->  Nested Loop Left Join  (cost=1.28..2217.15 rows=100 width=1242)
->  Nested Loop Left Join  (cost=0.85..1380.90 rows=100 width=1230)
->  Limit  (cost=0.43..539.65 rows=100 width=1218)
->  Nested Loop  (cost=0.43..1186.71 rows=220 width=1218)
->  Function Scan on unnest t  (cost=0.00..1.00 rows=100 width=12)
->  Index Scan using fix_tracks_status_flags_idx on tracks  (cost=0.43..11.84 rows=2 width=1210)
Index Cond: ((is_current = true) AND (track_id = t.id))
Filter: is_current
->  Index Scan using …
```

Improve history query

---

discovery-provider/integration_tests/tasks/test_get_feed_es.py
discovery-provider/src/queries/get_feed_es.py

Quick fix from #3684 actually broke feed with a playlist in it, causing `get_feed` to fallback to slow `get_feed_sql`.  Classic.
Also fixes bug that would break feed if you appear in your own feed (replace `.pop` with `.get`)
✅

Fix get_feed_es save_count, add test

---

discovery-provider/src/tasks/index.py

This was a part of the last PR, but was somehow removed.
reference: https://github.com/AudiusProject/audius-protocol/pull/3675/files#diff-6dde29301df9398b2acb2eb86113c63bdfd2548aab56d795aa1e7c69e97b014c
ran locally and it worked

Add track entity cid type

---

identity-service/src/notifications/formatNotificationMetadata.js

Fix dethroned push notif copy

---

identity-service/package-lock.json
identity-service/package.json

Bumping SDK version so identity has the EntityManager ABI.

Bump identity audius sdk version 0.0.35

---

identity-service/src/notifications/sendDownloadAppEmails.js

Do not deliver download app email to bad addresses

Do not send bad download app emails

---

creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts

To reduce extra reconfigs caused by stale job data (when the job was enqueued but then another update happened before the job got processed), we short-circuited the reconfig when the user's replica set SP IDs from the job mismatch the user's replica set SP IDs from on chain.
This PR fixes an edge case where a Service Provider deregistered their node, which causes a mismatch because our endpoint->spID mapping can't find the SP ID, but the chain still has the deregistered SP ID in the user's replica set.
Tests should pass, and we'll follow the monitoring section to make sure replica set updates with deregistered SP IDs are actually issuing reconfigs now. The room for negative impact is minimal since it's just an extra check -- the chain call would fail if the old replica set mismatches. …

Allow RS update when node is deregistered

---

dev-tools/README.md

Add some setup instructions

---

discovery-provider/integration_tests/tasks/test_track_entity_manager.py
discovery-provider/src/tasks/entity_manager/entity_manager.py

* Explicitly enable a development mode for entity manager + tests

[PLAT-294] Falsey flag in entity manager indexing

---

libs/src/NativeAudiusLibs.ts

Context here, will push out a client PR in a sec:
https://audius-internal.slack.com/archives/C03UEDXTN1E/p1661180012358859

Add entity manager address param to configInternalWeb3 native

---

discovery-provider/integration_tests/challenges/test_track_upload_challenge.py

Previously made default config use dev env so local env would use dev challenges: https://github.com/AudiusProject/audius-protocol/pull/3737#pullrequestreview-1081109177.
However, that change broke this test which relied on the prod config.
Updated test and confirm it passes this time.

Fix track upload challenge integration test

---

discovery-provider/src/tasks/entity_manager/entity_manager.py

Params could be undefined which would stall indexing.

Avoid stalling entity manager with undefined params

---

libs/src/sdk/sdk.ts
libs/src/services/identity/IdentityService.ts

Fixes some type issues with the sdk config. Ran into this when trying to pass staging values to the sdk

Improve sdk config types

---

identity-service/src/routes/wormhole.js

Removing duplicate logs in relayWormhole method of the identity service.

Removing duplicate logs

---

creator-node/.version.json
discovery-provider/.version.json

Bump to version 0.3.65

---

libs/src/AudiusLibs.ts
libs/src/services/wormhole/Wormhole.ts

The more elegant solution here would be to separate wormhole into two separate singleton-like classes in the libs/sdk. I think this is a nicer stop-gap though. Just pushing those dependencies down a bit into the functions and also get some better logging around it. The types here are huge. Big help.
Ran local stack, confirmed identity initializes wormhole client now.
`#wormhole-incidents-prod`

[PLAT-308] Fix wormhole on identity

---

creator-node/package-lock.json
creator-node/src/logging.js
creator-node/src/services/sync/syncImmediateQueue.js
creator-node/src/services/sync/syncQueue.js

Log on `secondarySyncFromPrimary()` success since currently no log is emitted
Standardize above logging
n/a
Look for logs containing `secondarySyncFromPrimary`, with loglevel `info` or `error`
Specifically `secondarySyncFromPrimary Success` and `secondarySyncFromPrimary Error`

CON-366 CN - Log on secondarySyncFromPrimary() success + logging cleanup

---

identity-service/package-lock.json
identity-service/package.json

Gets https://github.com/AudiusProject/audius-protocol/commit/879b906795b80f0850cc932b87b1c3d4171d3fad on identity to repair wormhole transactions.
No great way to test without prod here unfortunately, but this will not have adverse impact since it already doesn't work.

Fix wormhole with upgraded libs

---

libs/src/services/solana/SolanaWeb3Manager.ts
libs/src/services/solana/tokenAccount.ts
libs/src/services/wormhole/Wormhole.ts

Renamed to getTokenAccountInfo and deriveUserBank
Tested by sending WAudio via UI and confirming balance was correct.

[PAY-586] Rename getAssociatedTokenAccountInfo and getUserBank

---

discovery-provider/scripts/start.sh
identity-service/Dockerfile
identity-service/scripts/start.sh

Remove rsyslogd transport to Loggly from identity
Ran identity locally to make sure it boots up
Logs for identity should be sent via logspout.

Remove rsyslogd from identity

---

.circleci/config.yml

It was getting stuck upgrading packages. Switching to noninteractive works.

Fix failing test-solana-programs-anchor CI

---

creator-node/src/services/sync/primarySyncFromSecondary.js

just adding a single log
n/a
n/a

PrimarySyncFromSecondary log nit

---

dev-tools/commands/src/utils.mjs
docker-compose.yml

Fixes userbank creation on audius-cmd and fixes solana relay for local compose
Tested with account creation
NA

Final fixes for E2E local compose

---

libs/src/api/Account.ts
libs/src/services/identity/IdentityService.ts
libs/src/services/web3Manager/Web3Manager.ts

Make 0x prefix behave in native environment. Should have no impact on web env.
Tested web via localhost and mobile via simulator

[C-927] Fix 0x prefix in native

---

creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
creator-node/test/issueSyncRequest.jobProcessor.test.js

In issueSyncRequest, there is a reference to `SyncType.MANUAL` but the actual enum value is `SyncType.Manual`
unit tests, type checking, maddog
n/a

Fix typo in enum value

---

libs/src/services/identity/IdentityService.ts

- Adds an endpoint to identityService in libs to save transaction metadata

[PAY-603] Add a libs function to save transaction metadata

---

creator-node/src/config.js

Update prod configs for updateReplicaSet and recurringSyncRequest queues
Integration tests pass
Bull dashboard should show higher number of concurrent jobs process, less jobs in waiting state

Update replica set and sync concurrency

---

creator-node/nodemon.json
dev-tools/startup/creator-node.sh
dev-tools/startup/discovery-provider.sh
libs/src/data-contracts/ABIs/Context.json
libs/src/data-contracts/ABIs/TestEntityManager.json

Fix registration on dev setup

---

discovery-provider/integration_tests/notifications/test_reaction.py

In the test, there's sometimes a trailing zero in the decimal so it fails - this strips off the zero

fix inconsistency with trailing zero

---

creator-node/src/components/healthCheck/healthCheckComponentService.js
creator-node/src/routes/audiusUsers.js
creator-node/src/routes/playlists.js
creator-node/src/utils/index.ts
creator-node/src/utils/legacyUtils.js
creator-node/src/utils/validateAudiusUserMetadata.js

This PR removes `utils.js` and adds it into the `utils` module. This is so there isn't anymore confusion when importing utils.
The file was moved into the module, renamed `legacyUtils`, and has all of it's members exported 
No new tests, just integration tests to make sure the change didn't break previous tests.
n/a

remove utils.js

---

creator-node/src/services/stateMachineManager/index.js

Increase recurring sync queue waiting size from 1000 to 10000
Unit tests and mad dog should pass
Bull queue dashboard

Increase recurring sync queue waiting size from 1000 to 10000

---

discovery-provider/src/tasks/entity_manager/entity_manager.py

Avoid select * queries when there are no entities to fetch.

Optimize Entity Manager DB fetch

---

creator-node/src/fileManager.js

Move bail() up one level

---

creator-node/.version.json
discovery-provider/.version.json

Bump to version 0.3.66

---

libs/src/api/entityManager.ts

Add social features to libs + some refactoring. We will do reactions later.
Related indexing changes:  https://github.com/AudiusProject/audius-protocol/pull/3795
Tested locally with client changes.
These TXs will not be indexed until development features are enabled.

Add entity manager social features to libs

---

creator-node/src/services/stateMachineManager/stateMachineConstants.ts

Decrease sync monitoring retry time from 15s to 5s
Unit tests and mad dog pass
Duration of the jobs in this queue should decrease

Decrease sync monitoring retry time from 15s to 5s

---

libs/src/services/solana/rewards.ts
libs/src/services/solana/transfer.ts

This fixes an issue with tipping on native mobile. The borsh package doesn't have a default export but rollup is smart enough to make it work. React native metro is not smart enough, so using named imports instead
Tested tipping on web & mobile

Change borsh imports to named imports

---

libs/src/services/solana/tokenAccount.ts

Fix TS error

---

identity-service/src/routes/userBankTransactionMetadata.js

Updates purchase metadata to include setup/cleanup transaction IDs, and clarifies that the fields are IDs.

UserBankTransaction purchase metadata v2

---

creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts

This is to give us more context on the 502/500s we've been seeing in this flow.
No tests, just extra log
See error surrounding `UserReplicaSetManagerClient._updateReplicaSet() Failed..`

Print out err stack trace in reconfig

---

discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
discovery-provider/src/tasks/entity_manager/entity_manager.py

* Enable social features because as a prereq for playlists, tracks, users.
* Flush session before bulk saving to correct aggregate triggers.
Tested locally

Enable social features on entity manager

---

libs/src/services/solana/userBank.ts

Related to #3848, I missed one of the imports. This is what's causing the userbank error on native mobile sign in

Fix remaining borsh serialize import

---

creator-node/src/config.js

Enable all reconfig modes on prod by default
N/A
Metrics for `update-replica-set-queue` with syncmode = `primary_and_or_secondaries`

Enable all reconfig modes on prod by default

---

creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts

This is to debug why we're getting the 500/502s. I suspect it's this libs call.
n/a
look for `[_issueUpdateReplicaSetOp] Could not initialize libs`

Breakup try/catch

---

creator-node/scripts/start.sh

Potential to reduce queue load

Increase node mem in cnode

---

identity-service/src/notifications/components/notifications/Icons.jsx
identity-service/src/notifications/components/notifications/Notification.jsx
identity-service/src/notifications/formatNotificationMetadata.js
identity-service/src/notifications/renderEmail/notifications/Icons.js
identity-service/src/notifications/renderEmail/notifications/Notification.js
identity-service/test/emailNotifications/renderEmail.js
identity-service/test/sendNotifications/index.js
identity-service/test/sendNotifications/mockNotifications/challengeReward.json

Implement notifications for first playlist and first tip challenges.

First Playlist Challenge Playlist Notifications

---

creator-node/.eslintrc.js
creator-node/.prettierrc.js
creator-node/package-lock.json
creator-node/package.json
creator-node/src/config.js
creator-node/src/index.ts
creator-node/src/routes/audiusUsers.js
creator-node/src/routes/files.js
creator-node/src/routes/tracks.js
creator-node/src/serviceRegistry.js
creator-node/src/services/stateMachineManager/stateReconciliation/types.ts
creator-node/src/tracer.ts

This PR adds eslint rules to make our codebase more consistent and prevent easy errors
The main way this is done is by adding `node/recommended` to our .eslintrc file
Just integration tests to make sure these new rules don't break our existing code
Not a functional change

Add ESLint rules to prevent easy errors

---

dev-tools/commands/src/auth-headers.mjs
dev-tools/commands/src/index.mjs

Adds the auth-headers cmd for local dev
Can also do the following
```sh
curl -H @<(audius-cmd auth-headers)
```
cli change
NA

Add auth headers cmd for local dev

---

identity-service/src/routes/user.js

Fix email delieverable

---

creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts

We added aborts for issuing syncs. We should also log if aborts occur so we can trace the prometheus result to the log. 
Just a log, no functionality changes.
See `Issuing sync request error` and `Issuing sync request abort`

Also log aborts in issuing sync flow

---

creator-node/.eslintrc.js

Without change error:
This changes the root dir to read the file properly and resolves the issue
No more import errors
Look for this error

Change tsconfig root dir

---

discovery-provider/src/api/v1/tracks.py
discovery-provider/src/queries/get_random_tracks.py

Add feeling lucky route to get random tracks.

Add feeling lucky route

---

.circleci/bin/deploy-ci.py
.circleci/config.yml

Add support for automating production deployments (via dry runs at the moment).

INF-251 Automate Production Deployments

---

.circleci/bin/deploy-ci.py
.circleci/config.yml

Rename emojis to words for Github.
N/A

INF deploy-master-hold

---

discovery-provider/plugins/network-monitoring/src/db/index.ts

This PR bumped the number of max db connections to 250
Since we're using a managed DB now, we aren't limited to 100
Just a minor env var bump, verified on the gcp console that we can handle that many connections
We'll be able to monitor this change using the gcp console dashboard for the DB.

bump network monitoring connection pool max

---

discovery-provider/src/queries/get_save_tracks.py
discovery-provider/src/queries/get_tracks.py
discovery-provider/src/queries/get_user_listening_history.py

Fixes artist name sorter by updating Users in sort_fn
Ran on staging node

Fix artist name sorter

---

creator-node/.version.json
discovery-provider/.version.json

Bump to version 0.3.67
n/a
n/a

Bump to version 0.3.67

---

.circleci/config.yml

Don't block releases for test-eth-contracts since these are not part of our normal deployment flow.
Test on `master`.
Keep a close eye on first run.

INF-251 don't block releases for test-eth-contracts

---

dev-tools/audius-cmd
dev-tools/commands/Dockerfile
dev-tools/commands/src/index.mjs
dev-tools/commands/src/upload-track.mjs

Add upload track to audius-cmd

---

.circleci/config.yml

Reorg flow for design doc screenshots. Any actionable jobs are behind hold-jobs.
N/A, primarily checking design flow.
N/A

INF-251 reorg production deployment flow w/release-day lessons

---

identity-service/src/utils/antiAbuse.js

More closely match old AAO abuse handling on identity

Block notifs on error 7

---

.circleci/bin/deploy-ci.py

Additional visibility for CircleCI logs.
Monitor production deployments.
Added logs.

INF-251 add host to post-health check logs

---

.circleci/config.yml

New flows that unblock services from each other.
* Feature branch: https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/28253/workflows/93c305d9-9579-4854-b43c-e1d1b61ff1c7
* Release branch: https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/28254/workflows/44b65282-a1e3-406d-9658-dc508797431f
* Master: tbd post-merge
The two tests above.
Verified all non-auto-master-stage deploy jobs are still behind hold-jobs.
Will monitor new `master` workflow post-merge.

INF-251 Streamlined reorg for Deployment Pipeline

---

discovery-provider/src/tasks/index_trending.py

Add Hyperpop to trending

---

README.md

Update readme for audius-compose

---

.circleci/bin/deploy-ci.py
.circleci/config.yml

Allows us to see the current Reserved and available Staging nodes.
Can be run via the command line with colors, or using CircleCI with the output being stored as an artifact.
Ran locally, testing.
#eng-infrastructure for feedback.

INF-255 Reservation CLI Tool

---

libs/scripts/release.sh

Fix libs release script to update path because we are already in the libs folder

Fix path in libs release script

---

.circleci/config.yml

Add a trailing space to see if Slack's renderer is able to correctly parse @joe.
Monitor the next sdk deploy job.
Monitor the next sdk deploy job.

INF Attempt to get @mentions working for @joe

---

docs/docs/token/running-a-node/hardware-requirements.md

remove deadlink to gov.audius.org
None.
N/A

INF remove deadlink to gov.audius.org

---

libs/src/services/identity/IdentityService.ts

This will be relevant when doing transaction history table/modal
Tested by linking locally

[PAY-660] Add a getter for userBankTransactionMetadata in libs

---

.circleci/bin/deploy-ci.py

Change buffer window to 30 minutes per node in production.
None
Will monitor during the next release.

INF Increase production buffer time between nodes to 30 minutes

---

creator-node/scripts/register.js
dev-tools/audius-cmd

Register CNs on local before they are healthy
`audius-compose up`
NA

Register CN before healthy

---

identity-service/package-lock.json
identity-service/package.json

Upgrade libs in identity.
https://github.com/AudiusProject/audius-protocol/pull/3965

Upgrade identity libs to 1.0.8

---

creator-node/package-lock.json
creator-node/package.json

Upgrade libs for CN.
https://github.com/AudiusProject/audius-protocol/pull/3965

Upgrade CN libs to 1.0.8

---

identity-service/.gitignore
identity-service/Dockerfile
identity-service/nodemon.json
identity-service/package-lock.json
identity-service/package.json
identity-service/scripts/dev-server.sh
identity-service/scripts/start.sh
identity-service/src/index.ts
identity-service/tsconfig.base.json
identity-service/tsconfig.build.json
identity-service/tsconfig.json

Allows you to write TS code in Identity. Copied the setup in CN as much as possible. 
In subsequent PRs:

Add Identity Typescript Support

---

discovery-provider/integration_tests/premium_content/test_access.py
discovery-provider/src/api/v1/models/tracks.py
discovery-provider/src/premium_content/helpers.py
discovery-provider/src/premium_content/premium_content_access_checker.py
discovery-provider/src/premium_content/premium_content_types.py
discovery-provider/src/schemas/track_schema.json
libs/src/api/File.ts
libs/src/sdk/api/generated/full/models/PremiumConditions.ts
libs/src/services/schemaValidator/schemas/trackSchema.json
libs/src/utils/types.ts

Add follow gate for premium content. Simply checks whether the user id follows the track owner id.
Manually with premium track having a follow condition, and seeing whether a user that follows the track owner will have access to the track, while also making sure that a user NOT following the track owner does not have access.
Some updated logs and previously existing logs for other parts of the flow.
================ REMINDER: ================
If this PR touches a critical flow (such as Indexing, Uploads, Gateway or the Filesystem), make sure to add the `requires-special-attention` label.
** Add relevant labels as necessary. **
-->

[PAY-649] Add premium follow gate logic

---

creator-node/package-lock.json
creator-node/package.json
creator-node/src/index.ts

This PR changes a good chunk of the `require` statements in content node's `index.ts` to be `import`. 
This was tested by running locally to make sure there wasn't any unexpected errors caused by the slightly different semantic 
This change will be monitoring using our typescript compiler which will now more effectively be able to typecheck out code

Change Content Node `index.ts` `require`s to `import`s

---

.circleci/config.yml

cut-releases is blocked on manual input. Let's confirm github.com as a known known host automatically.
Testing on `master`.
#eng-deploy-announcements

INF-272 run ssh-keyscan before cloning

---

.circleci/config.yml

Cutting the release should be a trigger-based job since we'll want this to run via cron in the future, not through a manual approval job.
Testing on master.
#eng-deploy

INF-272 Convert cut-release job to trigger job

---

.circleci/config.yml

Run ssh-keyscan during appropriate job.
On master.
#eng-deploys

INF-272 ssh-keyscan for release-scripts, not deploy

---

.circleci/config.yml

cd into audius-tooling to use relative script paths
on master
#eng-deploys

INF-272 cd audius-tooling

---

.circleci/config.yml

Place audius-infra ssh_keys into expected path.
On master.
#eng-deploys

INF-272 cp ssh_keys

---

.circleci/config.yml

Add missing details as to why the release failed.
Example: https://audius-internal.slack.com/archives/C03EK0C69QD/p1664836931540429
Monitor #eng-deploys.
Monitor #eng-deploys.

INF-251 add Slack details on failed deploy

---

.circleci/config.yml

Generate text used for release checklist.
Testing on branch pre- 0d1efb8eab7705cfc328619369ac2cfd8600c68a using Triggers. Full test during next release.
#eng-deploy

INF-273 automate release checklist text

---

.circleci/config.yml

Export $SLACK_DETAIL, even on failures, so the details are included in the slack notification.
Monitor #eng-deploys.
Monitor #eng-deploys.

INF-251 Always store $SLACK_DETAIL

---

dev-tools/audius-cloud

Remove default image in audius cloud create
NA
NA

Remove default image in audius cloud create

---

dev-tools/audius-cloud
dev-tools/audius-compose
dev-tools/setup.sh

Add prune and default to SSD
NA
NA

Add prune to audius-compose

---

creator-node/package-lock.json
creator-node/package.json
creator-node/src/app.ts
creator-node/src/components/healthCheck/healthCheckComponentService.js
creator-node/src/index.ts
creator-node/src/services/prometheusMonitoring/prometheusUtils.ts
creator-node/test/expressApp.test.js
creator-node/test/lib/app.js

This PR types `app.js` and updates the tests to accommodate 
This PR just updates the original tests so that they work this the new typescript and import semantic
These changes will be monitored with the typechecking system in the TS compiler

Convert `app.js` -> `app.ts`

---

discovery-provider/integration_tests/queries/test_search_track_tags.py
discovery-provider/integration_tests/queries/test_search_user_tags.py
discovery-provider/src/queries/search_es.py

* fix DSL when exclude_premium=True
* sort tags results by popularity
* add tests
✅

Fix ES tag search, add tests.

---

dev-tools/setup.sh

Increase system file watcher count so that nodemon doesn't crash
```
```
NA

Increase file watchers for nodemon

---

dev-tools/README.md

Remove unneeded build step
NA
NA

Remove build from README

---

dev-tools/audius-compose

Change default number of creator nodes on local to 4
NA
NA

Change local creator nodes default to 4

---

.circleci/config.yml

Send a slack message at 10am CT (Monday-Friday) with the list of Staging Reservations.
Tested manually here:
* https://audius-internal.slack.com/archives/C03STD3UXMG/p1664924444821329
#eng-deploys

INF-276 Send reservation information to Slack

---

.circleci/config.yml

Add notifications from CircleCI to Discord. Hook up discord notification when we create new governance proposals.
Using this orb:
* https://circleci.com/developer/orbs/orb/antonioned/discord
* https://github.com/antonioned/circleci-discord-orb#usage
* Removing test case commit: b01532e56a93ce85aef48c36c58c317d41645911
* Workflow test: https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/28778/workflows/60fa0f79-ec02-482d-9626-06f7e99ee73f/jobs/352404
* Slack alert: https://audius-internal.slack.com/archives/C03STD3UXMG/p1664927694665859
* Discord alert: https://discord.com/channels/557662127305785361/1026998576066342942/1027005931504017408
Monitoring in #audius-alerts-text, then we'll move to #node-operators by updating the `discord` [CircleCI …

INF-274 Add Discord notifications

---

creator-node/src/apiHelpers.ts
creator-node/src/logging.js
creator-node/src/utils/requestRange.ts

This PR convert the `apiHelper.js` file to typescript. I tried my best to add basic type checking without changing the overall functionality of the function in the file.
This PR uses the original tests to make sure original functionality didn't break
This change will be Monitored with then typechecker

Convert `apiHelper.js` to typescript

---

monitoring/grafana/dashboards/audius-content-node-bull-queue.json
monitoring/grafana/dashboards/audius-content-node-overview.json
monitoring/grafana/dashboards/audius-content-node-profiling.json
monitoring/grafana/dashboards/audius-content-node-syncs.json
monitoring/grafana/dashboards/audius-content-node-update-replica-set.json
monitoring/grafana/dashboards/audius-entity-manager.json
monitoring/grafana/dashboards/audius-network-monitoring.json
monitoring/grafana/dashboards/ray-test.json
monitoring/grafana/metadata/contact-points.json
monitoring/grafana/metadata/templates.json

Snapshot of what's running in prod

INF production Grafana snapshot

---

discovery-provider/plugins/network-monitoring/src/db/sql/scratch_pad.sql
discovery-provider/plugins/network-monitoring/src/metrics/index.ts
discovery-provider/plugins/network-monitoring/src/metrics/queries.ts
discovery-provider/plugins/network-monitoring/src/prometheus.ts

This PR adds metrics to get a user's status by replica
This was tested on staging network monitoring and the query was also tested on prod network monitoring
This change will be monitored with a new panel on the network monitoring grafana dashboard

[CON-429] Network Monitoring: user status by replica

---

creator-node/src/apiHelpers.ts

This PR exports an error that was mistakenly un-exported when converting to typescript
Original tests to make sure original functionality didn't break
Monitored with the typechecker

export ErrorBadRequest
