service-commands/src/utils/seed.js

I think when I rebased before pushing seed stuff, missed this line - double parses due to vestigial check for `'random'` that I didn't take out -- this was the original planned API but I decided to make random metadata generation implicit instead. Pointed out by @rickyrombo - thanks!

Fix seed CLI track metadata parsing

---

discovery-provider/src/app.py

Bug fix web server failed with `ModuleNotFoundError: No module named 'src.tasks.index_user_listening_history'`.
Ran disc prov locally and confirmed index_user_listening_history ran completely.

Fix user listen history import

---

creator-node/src/routes/files.js

Move the duration log before res.end() for successful log message.
Example:
```
{"name":"audius_creator_node","hostname":"creator-node-backend-78b7c7b964-7kxs8","pid":18,"requestID":"eeHhKvahFL","requestMethod":"GET","requestHostname":"creatornode7.staging.audius.co","requestUrl":"/ipfs/QmZdQmuimnRjmj2rsgeoBRjJRRdtWDbo5bhLpjEPVsLjyn","level":30,"duration":22,"msg":"Successfully served from fs!","time":"2021-12-15T23:59:04.494Z","v":0}
```

Switch log duration order

---

discovery-provider/alembic/versions/6b5186e7d28f_replace_aggregate_plays_mat_view_with_.py
discovery-provider/tests/test_index_aggregate_plays.py
discovery-provider/tests/utils.py

Bug fix. Previously when migrating aggregate_plays from mat view to table, the migration would copy the table without updating indexing_checkpoints. Then the indexing task would assume the table needs to be repopulated and increment on top of existing counts.
The new migrations calculates aggregate_plays and saves the indexing checkpoint so the indexing task would pick up where the migration left off. This is safe assuming no plays are pruned.
Updated unit tests to avoid play_item_id 0 and clear indexing_checkpoints before populating mock.
Ran migration against a prod snapshot and confirmed indexing_checkpoints was updated and aggregate_plays_table and aggregate_plays were identical.

Fix aggregate plays double count when migrating

---

service-commands/scripts/provision-dev-env.sh
service-commands/scripts/setup-instance.sh
service-commands/scripts/utils.sh

* Fixes A `remote-dev` provisioning early exit due to non-interactive shell allocated by ssh in python
* Disables pg auto-start which conflicts with DN provisioning
Tested by manually provisioning an instance.

Fix reboot instance and disable pg auto-start 

---

libs/src/services/discoveryProvider/index.js

In order to pass headers from audius-client to discovery provider, need to make these changes.
Tested working with a /users/handle/<handle>/tracks request to discovery node to ensure the correct headers were being passed. Tested that response was as expected (returned hidden tracks)

Add headers to send when making discovery node request

---

creator-node/scripts/start.sh

Get debugger mode to work with typescript `index.ts` file. 
Reference https://github.com/remy/nodemon/issues/1565#issuecomment-494643872
Brought up a local CN with `link_libs` true and false.

Add inspect flag for debugger mode CN

---

.circleci/config.yml

PR #2157 introduced a potential bug where it didn't build all docker tags that changed and no tags on master. Reverting that behavior.

Remove diff before building docker tags, reverting to original behavior

---

creator-node/nginx_conf/nginx.conf

With the Content Node CID proxy layer enabled, the default max upload size is 1MB. This causes any content (images, tracks) upload greater than 1MB from the client fail.
Example error message in proxy logs: `client intended to send too large body: 4051550 bytes` (~4.05MB)
The intention of this PR is to bump the size to 1GB -- the current max size for audio uploads. 
reference: https://stackoverflow.com/a/66777762
Uploaded 11MB track to local node with proxy on successfully
Lovely probers and sentry alerts 😬

Set client upload max size to 1000mb (1gb)

---

creator-node/nginx_conf/nginx.conf

Previously, this value was set to mimic the value in `maxAudioFileSizeBytes`. It is better to actually disable this upload size checking so we can allow the app to decide if an upload size is too big, rather than have two sources that check the upload size
Reference:
http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
Uploaded a 195.1MB track locally successfully 
Probers and sentry alerts!!

Disable client max body limit

---

libs/src/services/discoveryProvider/index.js

#flare-51
Possible for discovery nodes to sometimes not index data due to POA RPC issues. This allows 404s to be retried with a different discovery node up to a maximum number of times in which case we decide that it is a true 404 (returning null).
Ran client against prod & tested breaking tracks

[AUD-1186] Add 404 safety check to discovery node selection

---

discovery-provider/integration_tests/test_index_hourly_play_counts.py
discovery-provider/src/tasks/index_hourly_play_counts.py

Fix bug when plays table is empty.

Fix play metrics indexing on empty plays case

---

identity-service/package.json
identity-service/src/app.js
identity-service/src/audiusLibsInstance.js
identity-service/src/config.js
identity-service/src/relay/ethTxRelay.js
identity-service/src/routes/wormhole.js
identity-service/src/utils/rewardsReporter.js
libs/package-lock.json
libs/package.json
libs/src/api/account.js
libs/src/constants.js
libs/src/index.js
libs/src/services/ethWeb3Manager/index.js
libs/src/services/identity/index.js
libs/src/services/solanaWeb3Manager/index.js
libs/src/services/wormhole/index.js

Moves logic into identity service for wormhole transfer
* Adds an endpoint in identity service to relay all operations of the wormhole transfer of AUDIO to WAUDIO
* The post body contains the signed permit tx and signed transfer tx
* The endpoint relays both requests (re-estimates the gas for the second request)
* Using the eth transfer tx, the endpoint continue to gather attestations from wormhole VAA and completes the transfer of tokens
* Adds wormhole config to identity service
* Update libs to expose the `attestAndCompleteTransferEthToSol` method for identity to use
* downgrades the npm wormhole version bc the newer version do not work with node
* Adds a generic slack reporter to identity to post for failed wormhole transfers
Ran everything locally with prod eth and sol relay configs …

Identity wormhole

---

libs/src/services/solanaWeb3Manager/index.js

`connection.getBalance` returns in lamports, but callers expected SOL
Testing locally in client

[AUD-1206] Fix SolanaWeb3Manager getBalance method

---

discovery-provider/integration_tests/tasks/test_index_operations.py
discovery-provider/src/tasks/index.py

This PR resolves an issue where a DN can accidentally mark a block as processed even when it is un-or under-processed, when it runs into a parsing or other issue during the core indexing task. 
The root cause was that we were parsing metadata and other transactions outside of the scoped session that was creating the Block to be added to db, and therefore errors thrown during parsing would not cause the Block commit to DB to roll back. Having erroneously marked the block as processed, the next run of the indexing task would continue with the NEXT block and state would get out of sync with other DNs.  
The solution involves fixing scoping and writing the block to DB as processed only after all other data has been processed and is ready to be committed. 
Added integration test assertion to …

[AUD-1186] Resolve DN divergence issue

---

discovery-provider/alembic/versions/132955202f03_update_connect_verified_challenge_.py

Discovery alembic migration for redo of connect verified challenge with `completed_blocknumber`
Closes AUD-1211
Ran manually against prod db

Add alembic revision - connect verified challenge

---

discovery-provider/src/challenges/challenges.json

- Set challenges on
- Set amount to 1 everywhere
- Set start block as per calculations: https://www.notion.so/audiusproject/Crossing-the-Finish-Line-3ac40b8e79f7470081de172a6b9f6a22#617af514a8bf49f6a2040451c9877de6

Configure prod challenges

---

creator-node/scripts/prod-server.sh
discovery-provider/nginx_conf/nginx.conf

Increase the worker connections count to 4096. This also cleans up an unused content node file.
This has been hotfixed onto prod for the last week.

Up worker connections + delete unused file

---

identity-service/sequelize/migrations/20211223183608-add-solana-notification-indexes.js

Updated index for SolanaNotifications and SolanaNotificationActions to have names to prevent collisions with the current indexes and make it easier to remove them if needed
Manually tested, adding and removing indexes works
After this PR goes in and these indexes are created, the duplicate ones in prod DB will be removed

Update indexes for SolanaNotifications and SolanaNotificationActions to have names

---

discovery-provider/src/challenges/challenges.json
discovery-provider/src/challenges/challenges.stage.json

- Fix: Accidentally turned off retroactive profile completion challenge
- Fix: Also turned off every stage challenge 🤦‍♂️

Fix retroactive profile completion start block

---

discovery-provider/alembic/versions/85680793a611_remove_disbursement_fk.py

Discovery Nodes that are missing a UserChallenge for some reason (i.e. they update late) will throw an error indexing a corresponding disbursement, as the disbursement table had an FK referencing UserChallenges
Testing on stage DP2

Remove disbursements FK

---

discovery-provider/src/utils/helpers.py
discovery-provider/src/utils/redis_metrics.py

Some logs show up too often and make it hard to read DN logs when inspecting an incident. This PR changes those logs to only show up in debug vs info mode.

Cleanup discovery log

---

identity-service/src/routes/notifications.js

`/notifications` route not returning solana notifications because it did not have a formatter, so was filtered out
Ran system locally against staging db and checked that notification appeared with local client against staging identity db

Fix notifications route solana

---

identity-service/src/notifications/sendNotifications/publishNotifications.js
identity-service/test/sendNotifications/index.js

Fix push notifications for reward challenges - the notif type was not checked for and filtered out before sending.
Added test for this case as well
Updated test
Manually

Fix push notifs for identity challenges

---

discovery-provider/integration_tests/tasks/test_index_operations.py
discovery-provider/src/tasks/index.py

This reverts commit 4b34b1f99a0b04fd6ab73a1462289c32c1a5ce1d.
This PR can lead to inadvertent indexing stalls when a discovery node is in a state where it is missing certain transactions. E.g. playlist create and the node is processing a playlist update. This change can be re-merged along-side the changes in https://github.com/AudiusProject/audius-protocol/pull/2282 when those are finished.
CI
Revert -- should see no indexing impact or stalls.

Revert "[AUD-1186] Resolve DN divergence issue (#2230)"

---

discovery-provider/scripts/dev-server.sh
discovery-provider/scripts/prod-server.sh
discovery-provider/scripts/start.sh

Move migrations back to corresponding -server.sh files. Previously they were in both start.sh AND -server.sh files. This was changed in https://github.com/AudiusProject/audius-protocol/pull/1842 to be only in start.sh, but since start.sh is not the uniform tool SPs use, this can cause migrations to never run.

Move migrations back into server.sh

---

identity-service/compose/.env
identity-service/src/config.js
identity-service/src/routes/cognito.js
identity-service/src/utils/cognitoHelpers.js

In order to enable a WebView for the Cognito Flow on mobile, we need to get the `shareable_url` of the the Flow.
This is the "server-side" setup of the [Mobile Integration](https://cognitohq.com/docs/flow/mobile-integration) guide. It uses the [Authentication Guide](https://cognitohq.com/docs/guides/authenticating) as well.
❗  **Note:** this adds two more config variables to identity ❗ 
Tested manually against a local iOS emulator and with Fiddler requests.
Added logging on failure that includes the request being made and the response, with any errors that Cognito sends back. Should I add an alert via Loggly?

Get Shareable URL for Cognito Flow

---

libs/src/api/account.js
libs/src/services/solanaWeb3Manager/index.js
libs/src/services/solanaWeb3Manager/rewardsAttester.js

- Better handle Solana userbank fails in signup
- Add escape hatch for setting start block in RewardsAttester

Add additional rewards fixes to libs

---

discovery-provider/default_config.ini
discovery-provider/src/utils/config.py

Rewards config for prod
Tested with live ammo on prod

Set production rewards config

---

discovery-provider/src/queries/get_alembic_version.py
discovery-provider/src/queries/health_check.py

Add /alembic_version endpoint that prints out
```
{
data: {
version_num: "be27a2794f75"
},
latest_chain_block: 3159,
latest_chain_slot_plays: 102,
latest_indexed_block: 3159,
latest_indexed_slot_plays: null,
signature: "0x99cb83eacfd3781d5319b83b9232d7257b44e15ba2fb3a3e8d3113f316e485097ed9cde1b8d49cc90e82717fa4161847279d872a1818834c190e9c2a4c84adfd1b",
signer: "0x15712a65ac707ae2ee3328c84fdca16b06d944c2",
success: true,
timestamp: "2022-01-11T07:38:32.172Z",
version: {
service: "discovery-node",
version: "0.3.49"
}
}
```
Local stack
Endpoint in prod

Add alembic version endpoint

---

libs/src/services/solanaWeb3Manager/rewards.js
libs/src/services/solanaWeb3Manager/transactionHandler.js
libs/src/services/solanaWeb3Manager/transfer.js
libs/src/services/solanaWeb3Manager/userBank.js

- Client wasn't getting error codes from Solana relays because there was no way to tell identity to not skip preflight, which is required for proper error code handling. 
- Also refactor to use non-positional args

Pipe skipPreflight out to relay

---

libs/src/api/rewards.js
libs/src/api/serviceProvider.js
libs/src/index.js
libs/src/service-selection/ServiceSelection.js
libs/src/services/discoveryProvider/DiscoveryProviderSelection.js
libs/src/services/discoveryProvider/DiscoveryProviderSelection.test.js

Adds ability in Rewards.js API for discovery nodes to be selected using unique owner as criteria.
Ran
`await audiusLibs.Rewards.aggregateAttestations({ quorumSize: 3})`
`await audiusLibs.Rewards.createSenderPublic({ numAttestations: 3 })`
And logged out the endpoints selected
Rewards attestations succeeding

[AUD-1170] Support uniquely owned discovery node selection

---

libs/src/api/account.js

Move user bank to fire & forget
Linked client vs. staging. Added artificial 60s delay in create user bank and was able to finish acct creation first.
Sign up success rate

[AUD-1265] Make createUserBank to fire & forget

---

discovery-provider/integration_tests/tasks/test_index_aggregate_plays.py
discovery-provider/src/tasks/index_aggregate_plays.py

When plays is empty, aggregate_plays will throw an exception. This change makes it skip gracefully. 
Adjusted unit test.
Can only repro error in dev box. Prod and stage wouldn't be empty.

Fix aggregate_plays on empty plays case

---

service-commands/scripts/bake-dev-image.sh
service-commands/scripts/utils.sh

Automated nightly/master commit bake is WIP but I heard some folks were having dev provisioning issues so I baked anew and added the ref. With this update you can just run `A setup remote-dev <name-of-box> --fast` and you will be able to ssh in and run `A up` without additional setup.

Add ref to newly baked image and fix bake script

---

discovery-provider/src/tasks/tracks.py

Adds a MissingRequired exception when the user for a track is not found as a part of the indexing flow. The handle is necessary to retrieve to create the track permalink (handle/track-name) and if we somehow failed to index that user, we need to skip ahead of this tx.
Deployed on prod discovery 2 and fixed stall

Raise MissingRequired error when no handle is found for a track

---

identity-service/src/featureFlag.js
identity-service/src/notifications/index.js
identity-service/src/notifications/sendNotifications/index.js
identity-service/src/notifications/sendNotifications/publishNotifications.js
identity-service/src/routes/notifications.js

Feature flag for rewards notifications in identity service
* Add feature flag to identity service
* Stop sending push notifications for rewards notifications based off feature flag - but still stored in db
* Stop sending notifications as part of `GET /notifications` endpoint unless query params passed `withRewards`
* Removes legacy query params for /notifications endpoint for `withRemix` and `withTrendingTrack`
NOTE: Still requires a client pass in query param based off of feature flag
Closes AUD-1272
Tested against staging

Identity rewards notifications feature flag

---

libs/src/services/solanaWeb3Manager/rewardsAttester.js

- Keep a longer lived cache of recently disbursed entries, instead of resetting it on each disbursement batch
- Include specifier in the cache key, to handle trending edge-cases
- Tested on staging

[AUD-1309][AUD-1291] Improve Identity challenge attestation

---

libs/src/services/solanaWeb3Manager/rewardsAttester.js

Lets attester use remote-config endpoints instead of auto-selecting DN

Wire up remoteconfig to attester

---

discovery-provider/default_config.ini
discovery-provider/src/queries/get_health.py
discovery-provider/src/queries/get_health_unit_test.py
discovery-provider/src/utils/config.py

Adds country flag to discovery health-check endpoint, to add consistency between content-node and discovery-node health-checks. This also makes it easy for the protocol-dashboard to display country flags for each node.
Added assertion for health-check payload

[AUD-73] Add country field to discovery health-check

---

creator-node/nginx_conf/nginx.conf

This PR is to bump the read timeout to 1 hour (3600 seconds). This is the timeout set at the load balancer level. The default timeout is 60s. ([reference](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout))
Set the proxy read timeout to 4s:
```
proxy_read_timeout 4;
```
Created a route that waits n ms:
```
app.get(
'/test',
handleResponse(async (req, res) => {
await new Promise((resolve) => setTimeout(resolve, req.query.duration))
return successResponse({
msg: `you should see this after ${req.query.duration}ms`
})
})
)
```
Hit route at `duration=100` (under read timeout):
```
{
"data": {
"msg": "you should see this after 100ms"
},
"signer": "0x11e486b1532e3f5a0090266e550a7e15d9721acf",
"timestamp": "2022-01-20T18:56:33.759Z",
"signature": …
```

Set proxy read timeout to 1 hour

---

discovery-provider/scripts/prod-server.sh
discovery-provider/scripts/start.sh

This PR changes Discovery Provider log level from debug to info, and also adds and env var to control this.
Testing on Sandbox

Change prod-server log level to info

---

discovery-provider/integration_tests/tasks/test_index_rewards_manager.py
discovery-provider/src/exceptions.py
discovery-provider/src/tasks/index_rewards_manager.py

Removes `continue` statement if missing the user's eth address from the users tbl or a matching user challenge while processing a rewards manager challenge disbursement.
This should help the discovery nodes have a consistent challenge_disbursements table
Closes AUD-1321

Remove skipping of disbursement on foreign user address / user challenge

---

libs/src/services/discoveryProvider/index.js
libs/src/services/solanaWeb3Manager/rewardsAttester.js

- Empty recently disbursed queue if we override startBlock
- Fix a bug where we crash if discover undisbursed endpoint fails to return a value (not sure why this happens, but I've seen it)
None

Improve startBlock override for attester

---

creator-node/src/dbManager.js
creator-node/src/routes/users.js
creator-node/test/pollingTracks.test.js

1.  Standardizes response of /users/clock_status with /users/batch_clock_status in case where no user exists for provided wallet. Ensures value for filesHash if returnFilesHash = true always defaults to null if not found
2. Fix bug where `/users/clock_status` route 500s when no files found for requested clockRange. There's no reason for route to error, it should instead 200 and return `filesHashForClockRange = null`
Additional unit test coverage

[ASI-800] PR 2.5 - `/users/clock_status` route bugfixes

---

discovery-provider/integration_tests/challenges/test_track_upload_challenge.py
discovery-provider/src/challenges/track_upload_challenge.py

Stop counting unlisted tracks towards track upload completion.

Fix unlisted tracks in track upload challenge

---

identity-service/src/awsSNS.js
identity-service/src/notifications/notificationQueue.js
identity-service/src/webPush.js

In some scenarios, identity logs incorrectly show `NaN` value for a number
```
{"name":"audius_identity_service","hostname":"identity-backend-7b485f9f96-fct4q","pid":17,"level":30,"msg":"notifications main indexAll job - drainPublishedMessages complete - processed NaN notifs in 3653ms","time":"2022-01-26T15:56:32.115Z","v":0}
{"name":"audius_identity_service","hostname":"identity-backend-7b485f9f96-fct4q","pid":17,"level":30,"msg":"notifications main indexAll job - drainPublishedMessages complete - processed NaN notifs in 2724ms","time":"2022-01-26T15:55:57.402Z","v":0}
```
Fixed this to ensure number value is always returned, also added a 0 default

Identity logging - fixing NaN value log

---

libs/src/api/rewards.js
libs/src/services/solanaWeb3Manager/rewardsAttester.js

Improve attestation flow by having attestation aggregation occur in a loop, and only retrying failed nodes. Incorporate changes into the identity attester as well.
Tested against stage

Improve attestation aggregation flow

---

discovery-provider/src/tasks/index.py

* When fetching metadata for users that do not exist due to skipped blocks/tx, we run into a KeyError due to optimization around URSM fetching. 
* This adds an existence check to bypass the error and continue indexing.

Quickfix for ursm dict missing key

---

discovery-provider/integration_tests/challenges/test_referral_challenge.py
discovery-provider/integration_tests/queries/test_get_challenges.py
discovery-provider/src/challenges/challenges.json
discovery-provider/src/challenges/challenges.stage.json
discovery-provider/src/challenges/referral_challenge.py

Specifier breaks on prod with 6 digit user IDs

Fix referrals-verified length

---

discovery-provider/nginx_conf/nginx.conf

The default proxy read timeout was too low, was failing fetching notifications. This bumps it up to 10m
Pushed to prod via hotfix and it progressed past the notifications block

Set proxy_read_timeout to 10m

---

discovery-provider/src/tasks/index.py

We never want to not submit a get_metadata function call for any CID. If the CID is unavailable the TPE would go into the except block and raise IndexingError. This statement was just meant to optimize the lookup of user_replica_set. It should never stop the call from happening.

Always submit get_metadata function to ThreadPoolExecutor

---

discovery-provider/nginx_conf/nginx.conf

Notifications endpoint is currently quite slow (20s-2min). If we redirect to another discovery node it may not (yet) have proper origin timeout params
Tested on prod discovery node
Identity notif indexing

Do not redirect /notifications requests

---

identity-service/src/routes/trackListens.js

Extend listen tracking in redis to a week of data and provide health check cutoffs configurable by request arguments to identity. Eliminates dependence on sauron as well for automated health checks

Modify listen tracking window and key lifetime

---

libs/src/index.js

Fix the wormhole rpc config - broke when changing the env name from `rpcHost` to `rpcHosts` in #2151

Fix wormhole rpc hosts

---

creator-node/nginx_conf/nginx.conf

Noticed this error log in proxy:
```
2022/02/02 22:17:15 [alert] 19#19: *2258131 1024 worker_connections are not enough while connecting to upstream,
```
PR is to bump to `4096`.  This is also done in Discovery Node. Reference: https://github.com/AudiusProject/audius-protocol/blob/ca3867b0ffbd415a7261f47f1a54b79a2a18ae10/discovery-provider/nginx_conf/nginx.conf#L19

Bump worker connections to 4096

---

identity-service/default-config.json
identity-service/src/audiusLibsInstance.js
identity-service/src/config.js
identity-service/src/routes/healthCheck.js
identity-service/src/routes/solana.js
identity-service/src/routes/wormhole.js
identity-service/src/solana-client.js
identity-service/test/configTest.js
libs/src/api/account.js
libs/src/api/rewards.js
libs/src/index.js
libs/src/services/identity/index.js
libs/src/services/solanaWeb3Manager/index.js
libs/src/services/solanaWeb3Manager/rewards.js
libs/src/services/solanaWeb3Manager/rewardsAttester.js
libs/src/services/solanaWeb3Manager/transactionHandler.js
libs/src/services/solanaWeb3Manager/userBank.js
libs/src/services/solanaWeb3Manager/utils.js
service-commands/scripts/createSolanaUserBanks.js
service-commands/scripts/rewardManagerLocal.js
service-commands/src/utils/constants.js
service-commands/src/utils/seed.js
solana-programs/.gitignore
solana-programs/reward-manager/README.md
solana-programs/start.sh

Keep track of multiple fee payers and expose endpoint that returns a random one so that clients can override which fee payer to use for solana transactions. Update functions to accept a fee payer override.
Here is the client counterpart PR: https://github.com/AudiusProject/audius-client/pull/880
Locally by spinning up all the services and client.

Support Multiple Fee Payers

---

libs/src/services/solanaWeb3Manager/rewardsAttester.js
libs/src/services/solanaWeb3Manager/transactionHandler.js

- Stringify fee payer before sending
- Correctly construct RewardsAttester with feePayerOverride

Fix fee payer

---

discovery-provider/integration_tests/tasks/test_index_listen_count_milestone.py
discovery-provider/src/tasks/index_listen_count_milestones.py

Ignore track_ids that are not in the play counts dictionary.
Note this was causing a KeyError previously where we would try to index a dictionary that did not have the key
Update the test to use a track_id that is not in the tracks or aggregate tracks tbl and check that it doesn't error

Ignore non-existant tracks while calc listen count milestones

---

libs/src/services/solanaWeb3Manager/transactionHandler.js

- If feePayerOverride was null, we call .toString() on null

Fix transaction handler bug

---

discovery-provider/nginx_conf/main.lua
discovery-provider/nginx_conf/nginx.conf
discovery-provider/src/queries/get_redirect_weights.py

OpenResty is hitting timeouts when fetching redirect weights
https://discoveryprovider3.audius.co/redirect_weights

Harden openresty code

---

identity-service/src/analytics.js
identity-service/src/routes/rewards.js
identity-service/src/utils/rewardsReporter.js
libs/src/services/solanaWeb3Manager/rewardsAttester.js

- Fix user_id as number instead of string in amplitude
- Log retries distinct from errors

Improve attestation logging

---

discovery-provider/integration_tests/tasks/test_index_rewards_manager.py
discovery-provider/src/tasks/index_rewards_manager.py

* Explicitly log transactions where a user is not found, and set user_id = 0
* Can be rectified in a follow up, but unblocks indexing while still maintaining a record of disbursement

[AUD-1540] Skip if user not found instead of error (reward manager)

---

discovery-provider/src/tasks/index.py

Currently there's no timeout property in the redis lock. This means that the timeout can be held indefinitely. Here's my theory as to what happens to some discovery nodes
- node1 is running
- node2 comes up and deletes disc_prov_lock
- node1 acquires indexing lock (it's still up because we do rolling updates)
- node1 gets terminated
- node2 can never acquire the lock
Confirmed this task has no expiry in redis
```
127.0.0.1:6379> TTL disc_prov_lock
(integer) -1
```
Tested this locally by verifying TTL of key
block_difference in health check

Add timeout to discovery indexing redis lock

---

discovery-provider/src/queries/get_user_history.py
discovery-provider/src/tasks/index.py
discovery-provider/src/tasks/users.py

Composite index is not being used by only the query on user id

Fix current user query

---

creator-node/src/services/sync/processSync.js

Currently there are cases where the secondary will wipe it's own DB state in order to sync from a primary. This was an early attempt at divergent state recovery by preferring content on the primary, but if there's only one piece of content on the network in a content node before the replica set is failed over, we can no longer access that through the IPFS gateway. This allows the network to access it until proper divergent state recovery.

Dont wipe state on secondary until divergent state merged

---

libs/src/api/user.js
libs/src/utils/utils.js

Uses chain call for URSM updates instead of waiting for discovery.
Linked client
- create account
- upload track
- update creator

Shift libs user signup from Discprov indexing to direct chain call

---

discovery-provider/src/tasks/index.py
discovery-provider/src/tasks/users.py

a couple changes to make indexing faster:
- fetch_ipfs_metadata often hangs for minutes and should only take a couple seconds this adds a timeout for 3 secs.
- also, this change removes extra queries in user indexing to check if users exist.
manually tested and verified timeouts come up and speeds up indexing.
also tested on user indexing.
monitor indexing is completing and timeouts are happening when necessary. 
monitor user indexing.

Add fetch ipfs timeout and optimize user indexing

---

discovery-provider/src/api/v1/helpers.py

Autocomplete search doesn't contain `spl_wallet` because it doesn't hit `populate_user_metadata`

Fix autocomplete search regression

---

identity-service/src/authMiddleware.js
identity-service/src/routes/solana.js
identity-service/test/routes/solanaTest.js

A user will not exist for all /solana/relays. We actually want authMiddleware to give us a user IFF this is a user bank relay (checked later on).
Offer a parameterized auth middleware that will only attach req.user and *not* return bad response so it can be checked downstream.
Need to test on staging.

Fix auth middleware bug in solana relay

---

discovery-provider/src/queries/get_health.py
discovery-provider/src/tasks/index.py
discovery-provider/src/utils/index_blocks_performance.py

Tracks index_blocks perf over time ranges in redis. Prunes every day things are are older than 30 days
Ran indexing locally and verified responses. Looks like this:
```
index_blocks_avg_ms: {
day: 37.666666666666664,
hour: 37.666666666666664,
minute: 37.666666666666664,
six_hours: 37.666666666666664,
ten_minutes: 37.666666666666664,
twelve_hours: 37.666666666666664
},
```

Index perf tracking

---

libs/src/services/ethWeb3Manager/index.js

Currently the max limit is 2M but we've seen prod tx's go as high as 3.7M. Set to 5M just in case

Increase ethWeb3Manager max gas limit

---

creator-node/src/routes/files.js

[recent change to check FS before DB](https://github.com/AudiusProject/audius-protocol/commit/7426dc7f201ac340cf1a8ff5bbbae98b031a0ae3) introduced regression where any file at legacy storage path (/file_storage/Qm...) would not be correctly served.
This removes regression by always using storagePath returned from DB

fix getCID Regression

---

identity-service/src/utils/configureAttester.js

- Passing in an empty array here was causing us to get INSUFFICIENT_DISCOVERY_COUNT errors, and then reselect constantly

Fix attester endpoint bug

---

discovery-provider/src/queries/get_health.py

SMEMBERS returns a list of set members and can take several seconds for a large set. This updates the health check to call SCARD which returns the number of members, which is what we want.

Change SMEMBERS to SCARD in discovery health check

---

creator-node/src/routes/audiusUsers.js
creator-node/src/routes/tracks.js

Issues sync requests to secondaries on metadata upload to improve data availability during indexing
Previously syncs were issued only after chain write which creates unavailability risk
Calls existing function in same manner on a different route, that flow has already been tested
No direct way but should see fewer indexing stalls due to content unavail

issue sync requests on metadata upload

---

discovery-provider/src/queries/get_top_playlists.py

Replaces count subquery with join on aggregate table for `get_top_playlists`.
Loaded API JSON before and after change and confirmed same items in same order.
GCP SQL panel

top playlists uses aggregate table

---

identity-service/src/cognitoFlowMiddleware.js
identity-service/src/config.js
identity-service/src/routes/cognito.js

- Add endpoint to retry flow session for handle
- Add endpoint to check whether recent cognito entry exists
- Also add log for webhook error for more visibility.
Tested manually by deploying to stage identity and calling the endpoints
Added logs fr when it passes / fails

Add endpoint to retry flow session for handle

---

discovery-provider/src/queries/get_top_followee_windowed.py

Makes `get_top_followee_windowed` use `aggregate_track` table
Save before and after JSON responses compare results
```
time curl -H "X-User-ID: 1" "http://localhost:5000/top_followee_windowed/track/month?limit=25&with_users=true" > before.json
time curl -H "X-User-ID: 1" "http://localhost:5000/top_followee_windowed/track/month?limit=25&with_users=true" > after.json
```
GCP SQL
Note: `type` is always `track`, so the previous subquery didn't do any additional filtering.

fix windowed track query

---

libs/src/utils/utils.js
libs/src/utils/utils.test.js

Adds a function to convert from AudiusABIDecoder.decodeMethod's multihashDigest property to a CID. Required for a companion notion page that finds all CIDs from the multihashDigest from on chain logs https://www.notion.so/audiusproject/Find-all-CIDs-in-block-ddbb3aac4c5143fdac9c991a4f7b78c6. Simple explanation of what this code does:
```
{
name: 'updateMultihash',
params: [
{ name: '_userId', value: '1234', type: 'uint256' },
{
name: '_multihashDigest',
value: '0x4a7a53...',
type: 'bytes32'
},
{
name: '_nonce',
value: '0x7816f...',
type: 'bytes32'
},
{
name: '_subjectSig',
value: '0x1ef...',
type: 'bytes'
}
]
}
utils.encodeMultihash(_multihashDigest) returns Qm...
```
Added unit tests
Dev only feature, no logs or monitoring

Add util in libs to convert from on chain digest -> CID

---

discovery-provider/src/tasks/index.py
discovery-provider/src/tasks/playlists.py
discovery-provider/src/tasks/social_features.py
discovery-provider/src/tasks/tracks.py
discovery-provider/src/tasks/user_library.py
discovery-provider/src/tasks/user_replica_set.py
discovery-provider/src/tasks/users.py

Move contract init to save a network calls during core indexing flow. This is the most expensive part of indexing and is totally needless!
Tested against sandbox discovery node.
https://discoveryprovider.sandbox.audius.co/health_check
Index_block time in verbose health check

Move contract init to start of indexing

---

discovery-provider/src/queries/prometheus_metrics_exporter.py

Rename the new prometheus /metrics to be /prometheus_metrics to avoid logical collisions with our internal metrics.
N/A
Running a load test while actively monitoring the new endpoint.

Rename /metrics -> /prometheus_metrics

---

solana-programs/anchor/audius-data/lib/utils.ts

No op. Error was not reproducible, might be fixed in new web3 version. Ensure array length is 20 to be consistent with [solanaWeb3Manager](https://github.com/AudiusProject/audius-protocol/blob/master/libs/src/services/solanaWeb3Manager/utils.js#L153).
All tests pass.
No monitoring needed.

[ASI-901] Ensure eth address array always has 20 bytes length

---

libs/src/api/rewards.js
libs/src/services/solanaWeb3Manager/rewardsAttester.js

- Fixes an recently introduced bug where we don't reselect off of INCOMPLETE/MISSING errors, because they were considered not retryable.
- Also breaks this code down to be more readable
- Testing on stage, will fast follow with a unit test 
- Same level of Reporter logs

Fix attestation reselection logic

---

solana-programs/anchor/audius-data/lib/lib.ts

* The convention for typescript type name is `PascalCase` - https://basarat.gitbook.io/typescript/styleguide#type
* Update all param types to use suffix of params instead of args in som places
* Updated method `initUser` type to be correct - converted buffer to array

Lint and consistency in solana anchor lib

---

discovery-provider/src/tasks/index.py

The naming schema for `index_blocks` was accidentally set to `index_metrics` for our new Prometheus metrics.
We should see `*index_blocks*` metrics in Grafana.
We should see `*index_blocks*` metrics in Grafana.

fix prometheus metric name

---

discovery-provider/src/utils/redis_metrics.py

The official docs state that we should not use labels with high-cardinality:
> CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.
> 
> Source: https://prometheus.io/docs/practices/naming/
We were including our flask parameters as labels and have thus introduced high-cardinality dimensions.
We should continue to see flask metrics within Grafana.
We should continue to see flask metrics within Grafana.

Reduce high-cardinality Prometheus metric labels from flask routes

---

discovery-provider/src/utils/redis_metrics.py

There were quite a few unique flask routes being recorded from discoveryprovider3.audius.co. Since discoveryprovider3.audius.co just had a memory leak + high CPU, we'll further restrict the flask-generated metrics for this first release.
Ensure each node produces few unique urls via Grafana.
Ensure each node produces few unique urls via Grafana.

further limit the amount of metrics generated

---

libs/src/api/account.js

During testing, I don't care if recovery links are able to be generated, but I also see a lot of noise when recovery links couldn't be generated. To make things cleaner, I've added an optional parameter to allow us to skip the skip generating recovery links.
The default logic continues to generate recovery links. My test cases should no longer see recovery links being generated.
Tests should see cleaner logs.

allow skipping recovery link generation for test purposes

---

discovery-provider/src/tasks/index_materialized_views.py

Skip vacuum when updating search mat views to reduce DB load.  There is still a daily `vacuum` task that should be sufficient.
Tested on sandbox-3.
GCP SQL panel

skip vacuum after updating search tables

---

discovery-provider/src/utils/redis_metrics.py
service-commands/scripts/provision-dev-env.sh

We saw issues where result was a `Response` that raised a `TypeError` which does not include a `message`.
We no longer extract messages for the log message and extract status codes from `Response`s correctly.
Monitor staging and soaking production nodes for error logs.
N/A

accept different result types for @record_metrics

---

discovery-provider/src/api/v1/models/playlist_library.py

Fixes issue where discovery node full user endpoint would fail for any user that had a playlist folder in their library due to incorrect Flask model. 
Full context here:
https://audius-internal.slack.com/archives/CA80RCL77/p1647017223805299
I thought [my last PR](https://audius-internal.slack.com/archives/CA80RCL77/p1647021978829119?thread_ts=1647017223.805299&cid=CA80RCL77) would have fixed this but turns out there was one last issue here.
Tested in browser running client against remote dev box

Fix folder model again

---

libs/.gitignore
libs/package-lock.json
libs/package.json
libs/rollup.config.js

Adds base rollup config to libs. This helps ensure libs is compiled in a performant way, and paves the way towards a typescript + es-modules refactor.
Since libs needs to be built before publish, not sure what the best approach is for that

[AUD-1725] Add base rollup config to libs

---

discovery-provider/src/queries/get_unpopulated_playlists.py
discovery-provider/src/queries/get_unpopulated_tracks.py
discovery-provider/src/queries/get_unpopulated_users.py
discovery-provider/src/utils/redis_cache.py
discovery-provider/src/utils/redis_cache_unit_test.py

Two issues fixed in this PR:
* playlists contain a nullable datetime field called `last_added_to,` which was trying to be parsed as `None`
* The underlying assumption in the original PR to use the flask JSONEncoder was incorrect. It appears as if our stack does default str(datetime) in python. This was leading to all sorts of weird behavior where sometimes datetime would be cached as `2022-03-15 21:43:50` and sometimes as `Tue, 15 Mar 2022 21:43:50 GMT` (the former being our desired response).
Worth noting that the client is "smart enough" to handle either date format, but the inconsistency is really bad.
Ran local stack verified queries (cached and uncached) for:
* users
* tracks
* playlists
* autocomplete
Tested against staging node with previously failing queries:
* autocomplete
This …

Fix datetime caching

---

creator-node/compose/env/base.env
creator-node/src/config.js
creator-node/src/serviceRegistry.js
libs/src/index.js
libs/src/services/discoveryProvider/index.js

Changes content-node's hardcoded `unhealthyBlockDiff` into an env var with a default value of 500.
Related tests should pass.

[ASI-943] Make discovery node unhealthy block diff configurable

---

creator-node/scripts/start.sh

Link libs in local CN dev by default to ensure early detection of issues
Identity service already does this locally, so also makes the two consistent
Ran locally and confirmed libs were correcty linked by default
Only impacts local dev

Link libs in CN by default

---

creator-node/src/snapbackSM/snapbackSM.js

Fixes an issue with Snapback that is currently preventing it from running
At start of each run, each node fetches all its replica set users, grouped by other replica, and makes a single `/users/batch_clock_status` POST req to each replica, passing the entire wallet set in the body. This has gotten so large that it now far exceeds the max body size
This PR changes the request to be made in sequential batches
Also includes some minor renaming / cleanup
Example of the current error:
```
{"name":"audius_creator_node","hostname":"creator-node-backend-89fd4f86b-8q57b","pid":28,"requestID":"L3jRRj_nr","requestMethod":"POST","requestHostname":"127.0.0.1","requestUrl":"/users/batch_clock_status","requestQueryParams":"spID=7&timestamp=2022-03-23T16:43:40.506Z&signature=0xe383dfd6167d15f446c8666ea4ac …
```

[CN] Change batch_clock_status requests to batches

---

service-commands/scripts/utils.sh

Newly baked image 
- has latest git SHA for client and protocol
- starts w bash, not zsh
- has latest libs / identity changes

Update fast provision with new bake

---

solana-programs/anchor/audius-data/cli/main.ts
solana-programs/anchor/audius-data/lib/lib.ts
solana-programs/anchor/audius-data/programs/audius-data/Cargo.toml
solana-programs/anchor/audius-data/programs/audius-data/src/constants.rs
solana-programs/anchor/audius-data/programs/audius-data/src/lib.rs
solana-programs/anchor/audius-data/tests/audius-data.ts
solana-programs/anchor/audius-data/tests/follows.ts
solana-programs/anchor/audius-data/tests/playlist-social-actions.ts
solana-programs/anchor/audius-data/tests/playlist.ts
solana-programs/anchor/audius-data/tests/test-helpers.ts
solana-programs/anchor/audius-data/tests/track-social-actions.ts
solana-programs/anchor/audius-data/tests/ursm.ts

Adds usrm to solana 
Methods:
* CreateContentNode - creates a content node with the audius admin authority
* PublicCreateContentNode - creates a content node with 3 proposers (existing content nodes)
* PublicUpdateContentNode - Updates a content node's authority - in the case where their delegator wallet is changed -  needs 3 proposers
* PublicDeleteContentNode - Deletes a content node account with 3 proposers and sends the funds to the audius admin account
* UpdateUserReplicaSet - updates a user's replica set - permissioned to the user's authority or any of the current ursm content nodes 
Updates the createUser method to add 3 ursm nodes
Updates the initUser method to add 3 ursm nodes
URSM tests

Add solana ursm

---

discovery-provider/src/queries/get_health.py

#2770 was missing a positional argument which is currently breaking the `/prometheus_metrics` endpoint.

missing get_health() argument

---

identity-service/package.json
identity-service/src/audiusLibsInstance.js
libs/src/services/wormhole/index.js

Fixes weird issue where our original wormhole fix for node results in a compilation issue for the mobile web app, since it is not able to correctly pull wasm files, which our node fix for some reason requires. The fix here is to remove the node compatible wormhole fix from libs and put it in identity service.

[AUD-1796] Fix wormhole compilation issue

---

discovery-provider/src/utils/prometheus_metric.py

The interface for gauges and counters is different than the interface for histograms and summaries since it uses `.set()` instead of `.observe()`.
A ticket has been filed to do basic checking on the `/prometheus_exporter` endpoint: 
* https://linear.app/audius/issue/ASI-996/add-mad-dog-test-to-hit-prometheus-metrics
Today's manual test looks good:
```
$ curl http://localhost:5000/prometheus_metrics
audius_dn_health_check_block_difference_current{pid="ser"} 0.0
audius_dn_health_check_latest_indexed_block_num_current{pid="ser"} 292.0
...
```

Fix how PrometheusMetrics sets Gauge metrics

---

discovery-provider/requirements.txt

werkzeug added this 23 hours ago:
```
the 2.0.x branch will become a tag marking the end of support for that branch
```
-- https://github.com/pallets/werkzeug/releases/tag/2.1.0
This change allows us to satisfy dependencies for `flask-restx`, for example.
click did the same 23 hours ago:
```
the 8.0.x branch will become a tag marking the end of support for that branch
```
-- https://github.com/pallets/click/releases/tag/8.1.0
Running `$ A run discovery-provider restart` to ensure the build process still works:
```
$ curl http://localhost:5000/prometheus_metrics
...
audius_dn_health_check_block_difference_current{pid="ser"} 11483.0
audius_dn_health_check_latest_indexed_block_num_current{pid="ser"} 11483.0
```

pin werkzeug

---

service-commands/package-lock.json
service-commands/package.json

Bump service-commands' libs dependency to v1.2.96
N/A - no breaking changes in this upgrade
N/A

Bump service-commands libs to v1.2.96

---

libs/package.json
libs/src/services/creatorNode/index.js

Fix mad dog failing due to the following error:
```
uploadTrackContent retry error:  TypeError: wait is not a function
at CreatorNode$5.pollProcessingStatus (/home/ubuntu/audius-protocol/libs/dist/index.js:37904:13)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async Promise.all (index 0)
at async CreatorNode$5.uploadTrackContent (/home/ubuntu/audius-protocol/libs/dist/index.js:37791:46)
at async Track.uploadTrack (/home/ubuntu/audius-protocol/libs/dist/index.js:43140:11)
at async LibsWrapper.uploadTrack (/home/ubuntu/audius-protocol/service-commands/src/libs.js:222:32)
at async Track.uploadTrack (/home/ubuntu/audius-protocol/service-commands/src/commands/tracks.js:9:19)
at async …
```

Fix changed utils import in libs

---

discovery-provider/alembic/versions/37a4458bb72c_fix_alembic_indexes.py

3 indexes created with alembic's API incorrectly omitted index name parameter... something that is _impossible to do_ when you use real sql haha.
* https://github.com/AudiusProject/audius-protocol/blob/master/discovery-provider/alembic/versions/301b1e42dc4b_create_track_routes_table.py#L35
* https://github.com/AudiusProject/audius-protocol/blob/master/discovery-provider/alembic/versions/6cf091d52869_user_events.py#L29
* https://github.com/AudiusProject/audius-protocol/blob/master/discovery-provider/alembic/versions/8bc5bac6711b_add_milestone.py#L28
Plan to test response times on sandbox env.
GCP SQL panel

fix alembic indexes

---

discovery-provider/src/api/v1/helpers.py
discovery-provider/src/api/v1/playlists.py

- Fixes duplicate operation ID
- Fixes reference to Tracks in trending_parser documentation
- Adds docs where missing
- Normalizes decorator order
- Prefers @api.expects() over @api.doc() params

Prepare Playlist API for Typegen

---

libs/src/api/rewards.js
libs/src/services/solanaWeb3Manager/rewardsAttester.ts

Update AAO error types for rewards
Manually on staging
Exisiting logs should be okay

Update AAO error types for rewards

---

libs/src/services/solanaWeb3Manager/rewardsAttester.ts

Include AAO rejection as error type so that libs knows attestation failed
Local client dapp with linked libs
n/a

Update AAO error types

---

discovery-provider/src/solana/solana_client_manager.py
discovery-provider/src/solana/solana_client_manager_unit_test.py

* Use updated RPC method as the currently consumed one is being deprecated https://docs.solana.com/developing/clients/jsonrpc-api#getconfirmedtransaction
Existing tests pass

Updating solana web3py to get_transaction from get_confirmed_transaction

---

contracts/package-lock.json
mad-dog/package.json
service-commands/scripts/init-repos.sh

The #fry_kek was needed because we were doing an `npm install` in the audius-client directory after linking libs, which tree-shook the deps out of lodash that we did not need (same with web3). The correct way to do this setup is to install *everything* first, then link the things we care about so installing doesn't impact deps.
```
cd service-commands
npm install
A run init-repos up
A up
```
Monitored via dev envs

[ASI-1021] Fix init-repos installation and linking

---

identity-service/package-lock.json
identity-service/package.json

Did a dumb merge order thing and forgot to include https://github.com/AudiusProject/audius-protocol/commit/93d91b3a392ccc2c69ba59448b0e5c2025fd2266 in version 103, so consuming latest here

Consume libs 1.2.104 in Identity

---

solana-programs/anchor/audius-data/cli/main.ts

Add bindings to the CLI for update admin and create user
NOTE: update admin is needed to set enable_write to false so that create user can work
ran locally

Add create user and udpate admin cli bindings

---

creator-node/src/components/healthCheck/healthCheckController.js

Fixes bug in CN health check on new functionality (not consumed anywhere) - calling `<CNurl>/health_check?enforceStateMachineQueueHealth=true` currently breaks. Just need to cast to Date object.
Manually tested health check with and without flag
Should be able to successfully call `<CNurl>/health_check?enforceStateMachineQueueHealth=true`

Fix stateMachineQueue health check

---

libs/babel.config.js
libs/package-lock.json
libs/package.json
libs/rollup.config.js

FIxes issue where rollup was compiling typescript to es6, which isn't compatible with many browsers. Adds babel and babel-preset to further transpile libs to a web compatible format.

Fix rollup babel config

---

discovery-provider/src/queries/get_trending_playlists.py
discovery-provider/src/trending_strategies/BDNxn_trending_playlists_strategy.py
discovery-provider/src/trending_strategies/trending_strategy_factory.py
discovery-provider/src/trending_strategies/trending_type_and_version.py

New strategy that disallows self-owned.
* Local cluster, created two playlists that should be trending, one of them has only self owned tracks. It is filtered out until there are 3 unowned (on the new experiment http://dn1_web-server_1:5000/v1/full/playlists/trending/BDNxn only)
Staging & prod via experiment

[AUD-1451] Add new playlist trending strategy

---

identity-service/src/solana-client.js

* Explicitly set maxRetries to 0 when retrying in sendRawTransaction (RPC level retries to 0 in favor of code level retries)
* Tested on staging, behavior does seem to improve

[ASI-1024] Max retries explicitly to 0 in TrackListen sendRawTransaction

---

libs/src/api/playlist.js
libs/src/api/user.js
libs/src/services/creatorNode/CreatorNode.ts
mad-dog/src/tests/test_ipldBlacklist.js
service-commands/src/commands/playlists.js
service-commands/src/commands/tracks.js
service-commands/src/commands/users.js
service-commands/src/libs.js

Fixes failing mad dog blacklist test:
- Verifies non-blacklisted CID for each scenario to rule out false positives (this is important because some CIDs that were being generated locally didn’t match what CN returned without extra logic – e.g., cleaning user metadata)
- Adds and exposes service command functions to: upload cover art, update track metadata, and upload playlist cover photo
- Upload and hash actual data for each scenario (user data, track cover art, playlist cover, profile photo, etc…) instead of hashing random text, which was breaking indexing. DN looked up the hash of the random text and couldn’t find any file for it, so then it would enter regressed mode and not allow other tests to pass
- Modify the cover_art_sizes/profile_picture_sizes/cover_photo_sizes/playlist_image_siz …

Fix ipld blacklist tests

---

service-commands/scripts/init-repos.sh

We see the error "ModuleNotFoundError: No module named 'pre_commit'". This seems to be a much more accurate way of checking if pre-commit exists
Tested on remote dev box and it was successful

Tweak pre-commit logic in init-repos.sh

---

discovery-provider/src/queries/get_feed.py

If a playlist is created with an unlisted track on it (which is possible right after upload) it will cause the feed to crash.
Instead skip the track
Failing request works locally after change

skip playlist track if unlisted

---

solana-programs/start.sh

Content nodes were not initialized on solana-programs start up. This change fixes a couple bugs.
* init content nodes with keypair paths not actual keypairs
* use solana validator not localhost
Verified solana-programs inited content nodes with confirmation logs in start.sh.
No monitoring.

Fix content node init in solana-programs

---

discovery-provider/requirements.txt
discovery-provider/scripts/start.sh

Uses watchdog to restart the celery task when doing local dev: https://www.distributedpython.com/2019/04/23/celery-reload/
Tested locally
N/A

Reload celery tasks when python files change

---

libs/src/services/solanaWeb3Manager/tokenAccount.js
libs/src/services/solanaWeb3Manager/transactionHandler.js
libs/src/services/wormhole/index.js
service-commands/package.json
service-commands/scripts/rewardManagerLocal.js

* Propagate change initialized in https://github.com/AudiusProject/audius-protocol/pull/2929
* https://docs.solana.com/developing/clients/jsonrpc-api#getrecentblockhash <-- Is being deprecated
* Bump svc cmds solana/web3js version
* Tested on staging with relay for listens, can test additionally if needed for these flows

Finalize deprecating recentBlockhash

---

mad-dog/README.md
mad-dog/package-lock.json
mad-dog/package.json
mad-dog/src/index.js
service-commands/scripts/init-repos.sh
service-commands/src/utils/constants.js

- Update/simplify local linking instructions in readme
- Make @audius/libs dependency explicit
- Remove `up` and `down` commands (they’re not used anymore, so we can reduce surface area)
- Update available test names in failure message
- Add `mkdir` to service commands to fix the following error: `[_addUsers] Error fetching random image: ENOENT: no such file or directory, mkdir '/home/ubuntu/audius/audius-protocol/mad-dog/local-storage/tmp-imgs`
Verified that the updated README instructions can be followed to successfully run (in order):
- `npm run start test`
- `npm run start test-snapback 2`
- `npm run start test-ursm`
- `npm run start test-ursm-sat`
- `npm run start test-listencount` (still takes over 30 minutes 😞 )
- `npm run start test-blacklist`
- `npm run start test-ursm-nodes` ❌ …

Mad-dog QoL: 5 minor improvements

---

service-commands/scripts/init-repos.sh
solana-programs/anchor/audius-data/scripts/install-dev-dependencies.sh

* Makes Anchor's `install-dev` script source newly-installed commands instead of reloading the shell via `exec`, which was completely replacing the existing shell process and breaking stdout from init-repos
* Fixes `install-dev` appending duplicate export PATH lines to ~/.profile
* Makes init-repos change to branch main in audius-client before running `npm run init` (this command is only on main, but our pre-baked image is still using branch master which causes the script to abort early when it can't find the command)
* Run `A up` and verify that this only adds a few extra seconds if the dependencies are already installed
* Run `npm run install-dev` in audius-data more than once and verify that ~/.profile doesn't have duplicate export lines at the bottom
Impacts dev flow -- keep an eye …

[PLAT-111] Install Anchor deps in init-repos

---

discovery-provider/es-indexer/src/listener.ts

Repost handler for playlist was marking track ID stale.  Classic copy paste bug.

Fix es-indexer repost handler for playlist.

---

service-commands/src/commands/service-commands.json

Currently, bringing down services will be stuck indefinitely. 
```
/home/ubuntu/.audius/eth-config.json
Bringing down services...
all - down
```
It's actually waiting for a confirmation prompt. This is only apparent when running `A down --verbose`. 
```
cd /home/ubuntu/Documents/Audius/audius-protocol; docker image prune --filter 'dangling=true' --filter 'until=360h'
WARNING! This will remove all dangling images.
Are you sure you want to continue? [y/N] 
```
We just need to add a `-f` flag like the other commands to skip confirmation.
Ran locally and `A down` is unblocked.
No monitoring.

Unblock bringing down services because of prune

---

identity-service/src/solana-client.js

When SOL validator clocks diverge from real clocks due to the network halting, we see listen transactions fail to be confirmed. This checks the relative time from SOL and passes the time into the listen transaction, so it shouldn't diverge enough to be fail a transaction.
Tested via a script locally
If listens are successfully submitted, this change is successful

Cache latest timestamp from SOL and pass it into listen transactions

---

discovery-provider/src/tasks/index_solana_plays.py

* Explicitly do not insert if `Plays` array is empty
* Exposed during incident on 5-1-21 due to clock skew issues resulting in thousands of failed transactions for which no `Play` is added to array but a commit of empty array fails with the following
```
Failing row contains (109243114, null, null, null, 2022-05-01 13:03:29.303709, 2022-05-01 13:03:29.303709, null, null)
```

Conditional on empty Plays insert

---

solana-programs/anchor/audius-data/cli/main.ts
solana-programs/anchor/audius-data/scripts/seed-tx.sh
solana-programs/start.sh

Currently, solana-programs container is broken and doesn't seed the first solana transactions. This change fixes that but leaves the rest of the naming aside for https://github.com/AudiusProject/audius-protocol/pull/3011/files.
solana-programs start works.
No monitoring.

Fix solana programs admin key naming

---

service-commands/src/setup.js

Moves the wait for health check in service commands to be _after_ the first check (if it fails), since we might want to run health check outside the main `A up` and don't necessarily need to wait 10 seconds

Wait 10 seconds after trying health check instead of before

---

discovery-provider/src/tasks/index_aggregate_tips.py

`func.max()` will always return a row, but the value of the row might be `None`
No tests - only affects databases with 0 UserTips
N/A

Fix max_slot_result None check

---

discovery-provider/src/tasks/index_user_bank.py

Stage has the account key for the receiver as the _third_ index, not the second, so we can't rely on the order of the account keys to match the instruction's expected order. Instead, the instruction gives a list of indices for the accounts in the order we expect. Map those values back to the indices we're looking for.
Example response:
```json
{
"jsonrpc":"2.0",
"result":{
"blockTime":1651617197,
"meta":{
// ...
},
"slot":132363703,
"transaction":{
"message":{
"accountKeys":[
"E3CfijtAJwBSHfwFEViAUd3xp7c8TBxwC1eXn1Fgxp8h",
"28rwvHiKkkzF6VMA4dUeZKoucC8MvXd2S8WVss6W4v4n",
"8QMHVdJrcGeQ8drbW1U4BVTuxNAR3WjACVojb7vocGUz",
"FgFEBnR5Teu4FEtqsVnrsviAQUvQ4NL2FJJ1kfWQ1Q9p",
"11111111111111111111111111111111",
"2sjQNmUfkV6yKKi4dPR8gWRgtyma5aiymE3aXL2RAZww", …
```

Find the sender/receiver indices

---

solana-programs/cli/src/main.rs

This allows specifying signer group's keypair when creating; if not provided it default to a randomly generated keypair (original behavior) 
Manual testing, by setting keypair in setup.sh as well as making sure that current setup.sh

Allow specifying signer group keypair

---

creator-node/src/snapbackSM/snapbackSM.js

Simple change to give up on issuing a new replica set after 5 attempts instead of trying 100 times.
This is overly time consuming to test for how small of a change it is. Will make sure CircleCI passes and add an extra reviewer.
Search for `Not enough healthy nodes found to issue new replica set after 100 attempts` in the logs. It should no longer appear and instead log `Not enough healthy nodes found to issue new replica set after 5 attempts`.

[CON-138] Lower retry attempts for issuing new replica set

---

discovery-provider/scripts/start.sh

There is a small bug that results in loggly tags being read incorrectly sometimes.
Tested by setting tags on local docker image

Fix loggly tag generation on discprov

---

creator-node/src/routes/users.js
creator-node/src/snapbackSM/secondarySyncHealthTracker.js
creator-node/src/snapbackSM/snapbackSM.js
creator-node/test/secondarySyncHealthTracker.test.js
creator-node/test/snapbackSM.test.js

- Change fetching sync metrics via 1 redis call per nodeUser to instead fetching sync metrics for all users at once
- Fix bug that caused sync outcomes to be read improperly, which caused the sync success rate to always be 100%
- Add tests for redis batching + making sure that bug doesn't come back. Increased Content Node coverage:
- line coverage 64.00% -> 66.85%
- branch coverage 50.85% -> 52.78%
The latest commit has integration tests, and if you go back to the first commit there are logs that help with manually verifying functionality -- it performs the original redis check and throws an error with the message `[theo] ERROR MISMATCHED METRICS` if the original metric doesn't match the metric pulled from the new unified redis call.
Steps I followed to test:
1. Use the first commit in …

[CON-131] Refactor state machine redis metrics to reduce calls

---

discovery-provider/src/queries/get_celery_tasks.py
discovery-provider/src/utils/prometheus_metric.py

Our prometheus endpoints are currently seeing this:
```
{"error":["Something caused the server to crash."],"success":false}
```
Our logs are showing this:
```
{"levelno": 40, "level": "ERROR", "msg": "Non Audius-derived exception\nTraceback (most recent call last):\n  File \"/usr/lib/python3.9/site-packages/flask/app.py\", line 1838, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/lib/python3.9/site-packages/flask/app.py\", line 1824, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/audius-discovery-provider/src/queries/prometheus_metrics_exporter.py\", line 43, in prometheus_metrics_exporter\n    PrometheusMetric.populate_collectors()\n  File \"/audius-discovery-provider/src/utils/prometheus_metric.py\", line 77, in …
```

Handle exceptions from collectors

---

discovery-provider/src/queries/notifications.py
discovery-provider/src/queries/response_name_constants.py

Include notifications for tips on the DN's `/solana_notifications` endpoint
Initiator is receiver, entity_id is sender, consistent with rank ups
Tested manually using seed commands.

Tip Notifications

---

discovery-provider/src/api/v1/helpers.py
discovery-provider/src/api/v1/models/support.py
discovery-provider/src/api/v1/users.py
discovery-provider/src/queries/get_support_for_user.py

Adds `v1/users/<id>/supporters` and `v1/users/<id>/supporting` routes to the Discovery Node API
Tested on remote using seed commands
Ideas? Added `@record_metrics` to the endpoints

[PAY-126] [PAY-114] Add supporters/supporting API

---

libs/package-lock.json
libs/package.json

Bump libs version
Has changes from #2966
Ran locally linked with client and identity

Bump libs version v1.2.115

---

identity-service/src/routes/user.js
libs/src/api/account.js
libs/src/services/identity/IdentityService.ts

See title
This will be called after a user authenticates via the Oauth popup - the email will be passed back to the app
Tested by calling the new libs method in client

Add Identity route to get user's email

---

creator-node/Dockerfile
discovery-provider/Dockerfile
identity-service/Dockerfile

Installs curl and adds a health check to the Dockerfile directly so that we don't need to have health checks managed by docker-compose
Tested by bringing up the docker container
```sh
ubuntu@cheran-gcp:~$ docker ps | grep healthy
30fc8d0c274d   cn1_creator-node                                                              "bash scripts/start.…"   About a minute ago   Up About a minute (healthy)   0.0.0.0:4000->4000/tcp, :::4000->4000/tcp, 0.0.0.0:9230->9230/tcp, :::9230->9230/tcp               cn1_creator-node_1
ffbab9abfc3d   dn1_web-server                                                                "bash scripts/start.…"   3 minutes ago        Up 3 minutes (healthy)        0.0.0.0:5000->5000/tcp, :::5000->5000/tcp …
```

[INF-80] Add health check to Dockerfile

---

contracts/Dockerfile.cacheLedger
contracts/contract-config.js
contracts/migrations/4_user_replica_set_migration.js
eth-contracts/Dockerfile.cacheLedger
libs/initScripts/local.js
service-commands/scripts/bootstrap-eth-contracts-docker.js
service-commands/scripts/setup.js
service-commands/src/commands/service-commands.json
service-commands/src/setup.js

Bake in the Data and Eth contracts into a docker container to speed up A up
Ran locally

Docker Data and Eth contracts baked in 

---

identity-service/src/notifications/fetchNotificationMetadata.js
identity-service/test/sendNotifications/index.js

While oncall, I saw repeatedly failing getTracks calls in identity. The problem was large request lines.
```
Failed to make Discovery Provider request, attempt #56, error undefined, request: {"endpoint":"tracks","queryParams":{"limit":825,"offset":0,"id":[1010155,1009092,1008536,1006575
```
The failure looks like a getTracks request and testing out getTracks requests of various sizes showed similar behavior where a large request fails across DPs.
```
await audiusLibs.Track.getTracks(1, 0, [1010155,1009092,1008536,1006575,1005979,1004040,1003166,1002312,1000521,998842,997053,995835,993672,992021,991205,988384,986632,986628,984389,983886,982682,978171,977159,
```
Modifying the DP gunicorn limit is probably not the best solution and I ended up seeing another limit hit from nginx. …

Batch track metadata notification fetches

---

discovery-provider/scripts/start.sh

Removes IPFS from `start.sh` so that we don't see IPFS logs when starting DP

Remove IPFS from DP start.sh

---

service-commands/scripts/provision-dev-env.sh

Recording some things @rickyrombo and I worked through provisioning a new box that had some issues running DP tests. 
* Parity with using upgraded pip similar to the docker image: https://github.com/AudiusProject/audius-protocol/blob/bdd6fa037ce0524d952211dbb8d47e0950dc933c/discovery-provider/Dockerfile#L40. Avoids weird issues where installs work in CI but not dev.
* Install packages for the correct version of python.
This change should help avoid others experiencing the same thing but we probably still want to use some package manager: pipenv, poetry, etc.

Provision dev with upgraded pip

---

.circleci/config.yml

In CI, GCP fails to create an instance if the name contains uppercase characters. Was useful for debugging, but this isn't really even necessary anymore since the instance will be deleted right after and the logs contain the name of the instance. For now we should be able to delete
Testing on CI with this branch which contains uppercase characters.
CI jobs won't pass in this branch if this code doesn't work

Fix mad-dog to GCP invalid name errors

---

creator-node/scripts/start.sh

Use the suggested MaxMessageSize of 64kb:
* [solarwinds.com](https://documentation.solarwinds.com/en/success_center/loggly/content/admin/rsyslog-manual-configuration.htm)
* [rsyslog.com](https://www.rsyslog.com/doc/master/configuration/global/index.html)
After running `A run creator-node restart`, `docker logs cn1_creator-node_1 --since 1s --follow` still worked as expected and the change was confirmed in `rsyslog.conf`.
```
❯ docker exec -ti cn1_creator-node_1 bash -c "head -n 2 /etc/rsyslog.conf"
$MaxMessageSize 64k
```
We should now be able to import messages longer than 8k, which was the default.

Use loggly's recommended MaxMessageSize of 64k

---

discovery-provider/src/queries/notifications.py
discovery-provider/src/tasks/index_listen_count_milestones.py
discovery-provider/src/tasks/index_rewards_manager.py
discovery-provider/src/tasks/index_solana_plays.py
discovery-provider/src/utils/redis_constants.py

Use the global slot (block height) for tracking the solana indexing progress as it relates to notifications, otherwise notifications will be gated on the most recent transaction in each program
Related: #2993 
Manually tested on remote
Can check redis but also logging out the result of `get_max_slot()`

Use global slot for solana notifications

---

discovery-provider/compose/docker-compose.redis.yml
discovery-provider/es-indexer/README.md
discovery-provider/scripts/dev-server.sh

Adds the Kibana container so we can use the console with the dev Elasticsearch. A few other things that might be nice to have for easier ES dev.
Ran discovery-provider on remote and accessed Kibana from local machine.
No monitoring.

Add kibana contain + update ES dev env

---

creator-node/src/components/healthCheck/healthCheckComponentService.js
creator-node/src/components/healthCheck/healthCheckComponentService.test.js
creator-node/src/config.js
creator-node/src/snapbackSM/peerSetManager.js
creator-node/src/snapbackSM/snapbackSM.js
creator-node/src/utils.js

- Add pagination to Discovery Node for `/v1/full/users/content_node` route and SQL query
- Update Content Node to use the pagination
- Expose new config option `snapbackUsersPerJob` via health check
Verified query by execing into Postgres container and running it. Also hit the endpoint manually with different params, and ran Snapback locally, and tested on staging (e.g. https://discoveryprovider2.staging.audius.co/v1/full/users/content_node/all?creator_node_endpoint=https://creatornode11.staging.audius.co&prev_user_id=0&max_users=100)
- Search for `v1/full/users/content_node/all` in Discovery Node logs
- Look through Content Node logs containing `processStateMachineOperation` or `StateMachineQueue`

[CON-118] (Content Node) Paginate getNodeUsers in snapback

---

discovery-provider/es-indexer/src/indexNames.ts
discovery-provider/es-indexer/src/indexers/BaseIndexer.ts
discovery-provider/es-indexer/src/indexers/PlaylistIndexer.ts
discovery-provider/es-indexer/src/indexers/RepostIndexer.ts
discovery-provider/es-indexer/src/indexers/SaveIndexer.ts
discovery-provider/es-indexer/src/indexers/TrackIndexer.ts
discovery-provider/es-indexer/src/indexers/UserIndexer.ts
discovery-provider/es-indexer/src/logger.ts

* Retry with linear backoff if indexing a batch encounters errors
* User indexer loads followers per-batch to make the cold start query cheaper
* Adds some new denormalized fields + mappings
* Rolls forward to v2 indexes.
Built index on local ES

es-indexer: retry + load following IDs in batches

---

service-commands/scripts/create-instance.sh
service-commands/scripts/utils.sh

Move to SSDs from HDDs for new remote-dev boxes for better random read/write patterns to contend with:
* the solana-validator writing about 10 Mb/s of data
* dockerd writing logs
* ganache writing blocks to disk
* postgres maintaining its database
* elasticsearch maintaining its database
* vscode-server's remote-ssh filewatchers
* git integration for certain p10k.sh shells
* normal terminal usage
Ideally, we would separate data for the solana-validator, ganache, postgres, and elasticsearch into a separate mounted/attached disk to lessen disk pressure on the boot disk allowing for a more responsive terminal and IDE experience.
If this change does not show vast improvement, we can try the `pd-ssd` disk type before considering a dedicated mounted disk as recommended by …

use balanced ssds instead of spinning disks for remote-dev

---

discovery-provider/scripts/seed.py
discovery-provider/src/api/v1/api.py
discovery-provider/src/api/v1/helpers.py
discovery-provider/src/api/v1/models/tips.py
discovery-provider/src/api/v1/tips.py
discovery-provider/src/queries/get_tips.py
discovery-provider/src/tasks/aggregates/__init__.py

Add endpoint(s) to get tips. Used for the feed tile.
Also updates `seed.py` to be a bit more useable
Tested using a seeded db with 2mil follows and 2mil tips with 200k users. I think the performance looked decentish? < 5s according to prometheus
TODO: Write unittests/integration tests for this gargantuan query. Will come in a fast-follow along with whatever metrics we want to record

[PAY-127] Tips API Endpoint

---

discovery-provider/src/tasks/index_solana_plays.py

Fixes:
```
{"levelno": 40, "level": "ERROR", "msg": "index_solana_plays.py | Fatal error in main loop\nTraceback (most recent call last):\n  File \"/audius-discovery-provider/src/tasks/index_solana_plays.py\", line 665, in index_solana_plays\n    process_solana_plays(solana_client_manager, redis)\n  File \"/audius-discovery-provider/src/tasks/index_solana_plays.py\", line 632, in process_solana_plays\n    if last_tx:\nUnboundLocalError: local variable 'last_tx' referenced before assignment", "timestamp": "2022-05-13 17:14:45,243"}
```
Which occurs when there are no plays to process.
Tested locally on remote

Declare last_tx

---

discovery-provider/src/api/v1/helpers.py
discovery-provider/src/api/v1/models/users.py
discovery-provider/src/api/v1/users.py
discovery-provider/src/queries/get_user_with_wallet.py

Add route to Discovery:
-Accepts JWT from read-only OAuth flow
-Gives success response with decoded JWT payload if the JWT is valid
-Otherwise returns error (404 or 400)
-Tested by calling the endpoint in browser console with JWTs generated from /oauth/auth client page

Add route to Discovery for verifying JWT C-445

---

discovery-provider/alembic/versions/a83814aeb4a1_add_updated_at_to_usertip.py
discovery-provider/src/api/v1/tips.py
discovery-provider/src/models/aggregate_user_tips.py
discovery-provider/src/models/user_tip.py
discovery-provider/src/queries/get_tips.py
discovery-provider/src/tasks/index_user_bank.py

- Fixes spacing on `__repr__` functions in models
- Adds `updated_at` to `UserTIp` model
- Makes `created_at` on `UserTip` model use the timestamp from the chain
- Adds `max_slot` to `v1/full/tips` endpoint for better indexed pagination
- Removes second offset/limit to fix a bug where the offset would be applied twice and undercut the limit
- Fixes crash when no tips are returned from the query
- Add debug logging for visibility when tips are created
Tested on remote

Fix various bugs with tips endpoint

---

discovery-provider/alembic/versions/a83814aeb4a1_add_updated_at_to_usertip.py

Fixes a bug in the migration if there are already tips in the DB:
```
psycopg2.errors.NotNullViolation: column “updated_at” contains null values
```
Down/upped alembic migration on remote. Will test on master

Use a default for updated_at column

---

creator-node/src/snapbackSM/snapbackSM.js
creator-node/src/utils.js
creator-node/test/snapbackSM.test.js

- Change custom random function to lodash's random function, and change the max from the magic number of 10M to the actual current newest user dynamically fetched from the `/latest/user` endpoint
- Change unhealthyReplicas from Array to Set since the logs showed that duplicate endpoints were being pushed to the array
- Add time loggings for updateReplicaSet and for awaiting Queue#add since that's a suspected bottleneck (there's a correlation between Redis memory usage and time spent on code that calls Queue#add)
- See https://github.com/OptimalBits/bull/blob/develop/lib/commands/addJob-6.lua for Redis calls during Queue#add
- See related issues https://github.com/OptimalBits/bull/issues/629 and https://github.com/OptimalBits/bull/issues/2054 
I ran Content Node locally to verify that I …

Clean up state machine and add timing logs

---

discovery-provider/src/queries/get_health.py
discovery-provider/src/queries/health_check.py

Adds separate `/location` endpoint to the discovery node.
The verbose health check takes a while and the location is not relevant to the node's health check, so this breaks it out. 
The location is used by the protocol dashboard to fetch their country for country flags next to the nodes.  
Ran locally and was able to hit `/health_check?verbose=true` and `/location` and see the country, lat, and long in both
Fixes PLAT-136

Add location endpoint to discovery

---

discovery-provider/src/tasks/index_trending.py

Adds `"Lo-Fi"` genre
N/A - this is the only place genres are defined 
N/A

AUD-1172 Add Lo-Fi Genre

---

creator-node/package-lock.json
creator-node/src/components/tracks/TrackTranscodeHandoffManager.js
creator-node/src/snapbackSM/peerSetManager.js
creator-node/src/snapbackSM/snapbackSM.js
creator-node/src/utils.js
creator-node/test/utils.test.js

- Adds default logger for `asyncRetry` wrapper
- Adds log boolean to optionally disable `asyncRetry` logging
- renames `asyncFnLabel` to `logLabel` for naming consistency
Existing regression tests
Logs containing `asyncRetry`

Add default logger + log boolean to CN asyncretry wrapper + renaming [Content Node]

---

discovery-provider/src/solana/solana_client_manager.py
discovery-provider/src/tasks/index_rewards_manager.py
discovery-provider/src/tasks/index_solana_plays.py
discovery-provider/src/tasks/index_user_bank.py

Two issues with our global slot approach:
- We were calling getBlockHeight instead of getSlot - the block # lags behind slot # due to the way blocks are inconsistently produced on Solana
- We weren't storing out global slot on supporter rank ups or on listen milestones
- Tested on my remote and on stage DN2

Fix Solana global slot logic

---

creator-node/package-lock.json
creator-node/package.json
creator-node/src/snapbackSM/StateMachineConstants.js
creator-node/src/snapbackSM/snapbackSM.js
creator-node/test/snapbackSM.test.js

- Increase snapbackSM branch coverage: 54.61% -> 69.5%
- Increase snapbackSM line coverage: 63.25% -> 76%
- Increase total Content Node branch coverage: 53.23% -> 54.44%
- Increase total Content Node line coverage: 66.63% -> 67.86%
- Add coverage for `issueSyncRequestsToSecondaries`, `processStateMachineOperation`, `additionalSyncIsRequired`, and `computeUserSecondarySyncSuccessRatesMap`
- Add Chai library for more flexible and easier-to-understand assertions
Before
After
N/A

[CON-149] Test more of snapback

---

creator-node/src/snapbackSM/snapbackSM.js
creator-node/test/snapbackSM.test.js

- Break apart `determineNewReplicaSet`
- Refactor `retrieveClockStatusesForUsersAcrossReplicaSet` to not take in a param and modify it
- Clean up some unnecessary `nock` usage in tests and change some built-in assertions to more human-readable Chai assertions
Tests pass. `determineNewReplicaSet` was already covered, so we can be pretty sure it's still working as expected.
Look for any unexpected replica sets ("`new replica set=`") in logs containing `issueUpdateReplicaSetOp`.

[CON-150] Break apart determineNewReplicaSet + cleanup

---

creator-node/src/blacklistManager.js

In this usage of the chunking method, the track id was not passed in in an array, causing the iteration logic to not occur. This PR is to put the track id into an array. 
No functionality changes, just bug fix
There are logs surrounding this method. We can check the error logs if it occurs

Fix redis chunk add use

---

service-commands/scripts/create-instance.sh

We were throwing away the output from the gcloud create instance command, print that out in case there's an error.
Tested locally and verified it prints errors if invalid. Here's an example
```
➜  audius-docker-compose git:(main) A create-instance --machine-type n2-custom-8-16384 "<test>"
Provider: gcp
OS Image: project=ubuntu-os-cloud,family=ubuntu-2004-lts
Disk Size: 256
Machine Type: n2-custom-8-16384
Name: <test>
Spot Instance: false
Account: <email>
Project: <project>
Confirm Options? [y/N] y
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
- Invalid value for field 'resource.name': '<test>'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'
```

Print errors while creating GCP instances

---

.circleci/config.yml

I was able to ssh into a CircleCI VM and force the build by hand and it succeeded after over an hour and it's been cached now. However, given that we don't use contracts containers from branches for any purpose, I propose moving contract container builds to only run on master.
Tested on CircleCI
Checks provide monitoring on CircleCI

Make contracts docker containers build only on master

---

discovery-provider/src/queries/notifications.py
discovery-provider/src/queries/response_name_constants.py

- The Tip notification was missing the tx_signature field; this is needed for identity to join between Reactions and Tips, where Reaction has the tip tx_signature as the 'reacted_to' field. 
Tested on remote box

Add additional field to tip notification

---

.circleci/config.yml
contracts/Dockerfile
eth-contracts/Dockerfile

This upgrades the poa contracts and eth contracts Dockerfile node version to 16 to resolve npm hanging on build.
Circle CI tests

[INF-104] Upgrade to node 16 to fix build errors

---

discovery-provider/src/tasks/index_aggregate_tips.py

- Found a bug where an early return in index_aggregate_tips would cause the userbank max slot to not be propagated properly

Fix aggregate tip indexing bug

---

discovery-provider/src/tasks/index_materialized_views.py

Currently the lock for the materialized view worker frequently expires on DP3 after 30 minutes. This is just a bandaid to increase that to 6 hours. Longer term we should not have jobs that run this long unbounded.
Calculated the new timeout in seconds is equal to the desired timeout.
We can see if multiple tasks are running in the /celery_workers_check endpoint

Increase materialized view timeout to 6 hours

---

creator-node/package-lock.json
creator-node/package.json
creator-node/src/snapbackSM/StateMachineConstants.js
creator-node/src/snapbackSM/peerSetManager.js
creator-node/test/peerSetManager.test.js

- Add cancel token to getNodeUsers in snapback. It looks like an issue with the state-machine queue getting stuck is caused by axios hanging and not timing out or succeeding/failing. Related issues:
- https://github.com/axios/axios/issues/2527
- https://github.com/axios/axios/issues/124
- Add test coverage for getNodeUsers and group other peerSetManager tests into `describe` blocks
- Ran `A up` locally and made sure it wasn't causing any errors
- Added tests that mock the request taking long enough to make the cancel token kick in, and verify that the request/function fails as expected in that scenario. Logs: 
- Search logs for `getNodeUsers request canceled` or `getNodeUsers took more than` to see when the cancel token had to be used
- Search for `getNodeUsers` to see general …

[CON-145] Add cancel token and test coverage to getNodeUsers

---

creator-node/compose/env/commonEnv.sh
creator-node/src/config.js
creator-node/src/logging.js

Have Creator Node logs match the `level` keys of Discovery Provider logs within [`audius-protocol/discovery-provider/src/utils/helpers.py`](https://github.com/AudiusProject/audius-protocol/blob/1c613132530c52c66601a2fd99f1614e69ae5ae2/discovery-provider/src/utils/helpers.py#L207).
Previously, this was handled by [fluentd](https://github.com/AudiusProject/audius-k8s-manifests/blob/aac600fbfb123486f6ef07e8e323e2fa93b429a9/audius/logger/logger.yaml#L41).
Currently, Creator Node uses Bunyan for sending json-formatted logs that are parsable by log forwarders like Logspout. Bunyan, however, only outputs the `level` key as an integer while Discovery Provider outputs a string-based `level` key and integer-based `levelno` key.
Without standardizing on a string-based `level`-key, we would have to: …

Add string-based `level` keys to Bunyan logger

---

creator-node/src/logging.js

* Create a copy of the log object by using the format: `const clonedLog = { ...log }`
* Add comments to Bunyan's code to clarify `safeCycles()`'s functionality for `JSON.stringify()`'s `replacer`.
* Remove the `new` keyword for cleaner object references.
This is a follow up PR for the comments on #3136 to match current coding practices.
Locally running logs.
Loggly logs.

[INF-93] Follow up code cleanliness for Bunyan changes

---

discovery-provider/src/utils/auth_middleware.py

Fixes auth_middleware query to enforce ordering in results when two users clash with the same wallet.
Rare occurrence and the culprit of that is user error (running audiusLibs.contracts.addUser when already authenticated with an audius account / wallet).
Tested on stage discovery 1! Hidden tracks show as expected. Will re-test when it lands on prod in the next release with my user account
Hidden tracks viewable

[PLAT-149] Enforce wallet fetch ordering in discovery auth_middleware

---

creator-node/package-lock.json
creator-node/src/apiHelpers.js
creator-node/src/logging.js
creator-node/test/lib/reqMock.js

- simplify `setFieldsInChildLogger` logic
- change name to `createChildLogger` for accuracy
- update calls
working example https://replit.com/@SidSethi/Child-logging#index.js
existing CN tests failed until final commit
Ensure logs called by `sendResponse` and `sendResponseWithHeartbeatTerminator` look correct:
- `sendResponse` is called by `handleResponse` which is used in `/health_check`
```
[2022-05-25T15:22:20.070Z]  INFO: audius_creator_node/67 on 0d34096fabb8: Success (requestID=8BX5ROjBy, requestMethod=GET, requestHostname=cn1_creator-node_1, requestUrl=/health_check, duration=34, statusCode=200, logLevel=info)
```
- `sendResponseWithHeartbeatTerminator` is called by `handleResponseWithHeartbeat` which is used in `/health_check/duration/heartbeat`
```
[2022-05-25T15:25:08.934Z] …
```

Simplify CN child logger pattern

---

discovery-provider/src/queries/get_health.py

Refactor health check on discovery such that it will not crash if web3 is unavailable.
Doing this work made me think that in the future, we probably want to have discovery node report only its latest block and have clients determine whether it is an acceptable number of blocks behind given its view of the world. It would be easy for a discovery node to get network-partitioned from the chain layer it's communicating with and then report 0 blocks behind indefinitely. I get around this in this PR by making the block diff = maximum_healthy + 1.
Local stack, if missing reports
```
block_difference: 101,
web: {
blockhash: null,
blocknumber: null
}
```
Health checks / pingdom

[PLAT-146] Make health check respond when web3 is unhealthy

---

libs/src/index.js
libs/src/services/discoveryProvider/DiscoveryProvider.ts
libs/src/services/discoveryProvider/requests.ts
libs/src/services/oauth/Oauth.ts
libs/src/services/oauth/index.ts

Adds OAuth utility to libs (to be moved to SDK)
On client side, the implementation looks like this:
```
<-- JS -->
libs.oauth.init('App name');
const onLoginSuccess = (profile) => {console.log('success!', profile)}
const onLoginError = (error) => {console.log('error', error)}
libs.renderButton(document.getElementById('oauth-button'), onLoginSuccess, onLoginError, {size: 'small'})
<-- HTML -->
<div id="oauth-button"></div>
```
Tested in browser by changing the AUDIUS_OAUTH_URL to point to localhost and using corresponding client changes (in PR: https://github.com/AudiusProject/audius-client/pull/1354)

Add OAuth to libs (to be moved to SDK) C-353

---

creator-node/src/services/stateMachineManager/CNodeHealthManager.js
creator-node/src/services/stateMachineManager/CNodeToSpIdMapManager.js
creator-node/src/services/stateMachineManager/index.js
creator-node/src/services/stateMachineManager/stateMachineUtils.js
creator-node/src/services/stateMachineManager/stateMonitoring/processStateMonitoringJob.js
creator-node/src/services/stateMachineManager/stateMonitoring/stateMonitoringUtils.js
creator-node/test/CNodeToSpIdMapManager.test.js
creator-node/test/StateMonitoringQueue.test.js
creator-node/test/peerSetManager.test.js
creator-node/test/processStateMonitoringJob.test.js
creator-node/test/snapbackSM.test.js
creator-node/test/stateMachineUtils.test.js
creator-node/test/stateMonitoringUtils.test.js

- Add tests for:
- stateMachineUtils.js (100%):
- `retrieveClockStatusesForUsersAcrossReplicaSet()` – existing test changed to use more readable nock instead of mocking the axios import
- `retrieveClockValueForUserFromReplica()` – new tests
- CNodeToSpIdMapManager.js (100%):
- `updateCnodeEndpointToSpIdMap()` and `getCNodeEndpointToSpIdMap()` – new tests
- Make nock disable other axios requests for all state machine + snapback tests that use nock, and assert `nock.isDone()` to verify all mocked endpoints were hit. This prevents false positives where other endpoints are hit and our mocked requests are silently ignored
- Rename nodeHealthManager to CNodeHealthManager
- Rename cNodeToSpIdMapManager to CNodeToSpIdMapManager
- Ran `A up` locally to make sure the renamings didn't cause any …

Test stateMachineUtils and CNodeToSpIdMapManager

---

discovery-provider/src/queries/get_tracks.py

Update the get tracks response to check for download dict before updating
validate that the query for a deleted track does not 500
This happened because legacy track records have the download column set to none instead of the default object. 
Not sure if I was supposed to keep the download field as `None` (which it was before) or set to the default json object
Ran the system locally and validated the response did not 500
Fixes: PLAT-150

Add check if download is none

---

creator-node/src/services/stateMachineManager/stateMonitoring/StateMonitoringQueue.js
creator-node/test/CNodeHealthManager.test.js
creator-node/test/StateMonitoringQueue.test.js

Add tests for:
- CNodeHealthManager.js:
- `getUnhealthyPeers()` – new tests
- `getNodeUsers()` – new tests
- `queryVerboseHealthCheck()` – new tests
- `determinePeerHealth()` – new tests
- `isPrimaryHealthy()` – new tests
- `_computeContentNodePeerSet()` – new tests
- Queue job processor logic
Made sure running locally didn't show any errors and verified that state machine manager tests are now very green!
Nothing new to monitor -- just tests.

Add coverage for CNodeHealthManager

---

discovery-provider/src/tasks/index_materialized_views.py

With this search flag enabled, we can disable mat views but not yet tags mat view. We will do that https://linear.app/audius/issue/PLAT-154/search-tags.
Fast follow up from https://github.com/AudiusProject/audius-protocol/pull/3093/files.
Tested on sandbox and verified only tag matview is refreshed.
```
{"levelno": 20, "level": "INFO", "msg": "index_materialized_views.py | Finished updating tag_track_user in: 61.29243063926697 sec.", "timestamp": "2022-05-27 20:08:45,323"}
```
Checking the log above.

Leave tags mat view on with search flag enabled

---

creator-node/README.md
eth-contracts/README.md

Badge currently is not accurate since it shows the coverage % for the entire repo, as opposed to by service
Can add this later, but doesn't seem worthwhile to do now, so just removing
N/A
N/A

CON-180 Remove CI coverage status from READMEs

---

discovery-provider/src/tasks/index_solana_plays.py

There was a bug here, predominantly exercised on staging due to low tx volume, where `last_tx` would be not None even though we processed no transactions, causing us to never set a global slot. This is the case when there is only one tx in the `transactions_array`, and that tx itself already exists in the db, causing us to bail out immediately and not process any transactions.
This wasn't an issue in the other Solana indexing tasks because `last_tx` corresponds to the last actually processed tx in those.  
Tested on stage DN1.

Fix last_tx bug in Discovery index_solana_plays.py

---

creator-node/src/snapbackSM/snapbackSM.js
creator-node/test/snapbackSM.test.js

Logs show some staging nodes (e.g., 8 and 10 currently) failing to initialize because no discovery node is connected, which causes a retry. The retry then fails forever because it calls `Queue#process`, which is only supposed to be called once. This PR makes sure `Queue#process` is only ever called once and re-creates PeerSetManager to attempt to re-connect a discovery provider.
Made sure the queue initializes locally with no errors.
If you can reach every staging node's `/health/bull` endpoint, then everything initialized correctly. Otherwise, search the logs for `_initSnapbackSM Error` and see if `No discovery provider currently selected, exiting` is the first error, followed by infinite retries with the error message `Cannot define the same handler twice __default__`.

Fix snapback init error

---

logspout/start.sh

Currently we're only adding discovery provider formatted tags and ignoring content node tags. This will ensure we use both sets of tags for our Loggly logspout integration.
Confirm accurate logs in Loggly.
Confirm accurate logs in Loggly.

Use logglyTags for CN nodes (logspout)

---

discovery-provider/src/utils/helpers.py

We added a service key to our logger for logspout, but k8s doesn't set this key. Instead, we will default this key for k8s as "k8s".
Confirm that DP1 is healthy and Loggly shows our logs.
Confirm that DP1 is healthy and Loggly shows our logs.

Set service key to k8s when not present

---

discovery-provider/src/queries/notifications.py
discovery-provider/src/queries/response_name_constants.py
identity-service/src/routes/notifications.js

- Adds reacted_to_entity in reaction notification, including amount and recipient
- Properly pad amounts
- Alter shape of Identity notifications to be more consistent with what client expects

Notification Fixes

---

discovery-provider/src/api/v1/users.py
discovery-provider/src/queries/get_support_for_user.py

- Adds route `/users/<id>/supporters/<supporter_user_id>` to get a specific supporter for a user
- Adds route `/users/<id>/supporting/<supported_user_id>` to get the support by a user to another user
- Both routes 404 if the supporter/supportee doesn't exist
- Updates the query to use SQLAlchemy to compose, added comments to show SQL version
- Fixes some minor full/non-full namespacing issues
Tested manually on remote
TBD

[PAY-272] Add API routes for individual user supporter/supporting

---

discovery-provider/scripts/prod-server.sh
discovery-provider/scripts/start.sh

Moves alembic migrations to start.sh instead of prod-server.sh

Move alembic migrations

---

identity-service/src/notifications/emails/downloadMobileApp.html
identity-service/src/notifications/emails/recovery.html
identity-service/src/notifications/emails/welcome.html
identity-service/src/notifications/emails/welcomeDownload.html

Add unsubscribe link to all emails in identity. Fixed the recovery email unsubscribe link which took you nowhere.
Link to mailgun docs - https://help.mailgun.com/hc/en-us/articles/203306610-Do-I-control-the-unsubscribe-handling-or-does-Mailgun-
Updated UI
Ran via the mailgun template test, got the email in my inbox, clicked through "Unsubscribe" and verified it took me to a page where I could unsubscribe.
Mailgun's dashboard has analytics for unsubscribes

Add unsubscribe link to welcomeDownload.html

---

.circleci/config.yml

We have coveralls since uploading to Coveralls which shows the little red X in github checks. Comment out for now until we can fix. 
Verified on this branch that it no longer publishes to coveralls
Coveralls doesn't fail the git status checks anymore

Comment out coveralls upload from content-node tests

---

discovery-provider/src/models/models.py
discovery-provider/src/queries/notifications.py
discovery-provider/src/queries/response_name_constants.py

Add a notification for users who have their track added to a playlist. Finished + tested these changes from @raymondjacobson. Identity / client changes WIP.
Manually tested on local services. 
Notifications response:
```
{
"blocknumber": 4445, 
"initiator": 1, 
"metadata": {
"entity_id": 2, 
"entity_owner_id": 2, 
"entity_type": "track"
}, 
"timestamp": "2022-06-07T17:52:20 Z", 
"type": "TrackAddedToPlaylist"
}
```
Check `/notifications` response. Validate TrackAddedToPlaylist entry.

Support notif for track added to playlist

---

discovery-provider/src/tasks/index.py
discovery-provider/src/tasks/index_metrics.py
discovery-provider/src/tasks/index_trending.py
discovery-provider/src/tasks/tracks.py
discovery-provider/src/tasks/users.py

Match Prometheus' official leaning towards `duration` over `runtime` nomenclature.
Grafana should still show the same metrics using updated panels:
* https://github.com/AudiusProject/load-test-tools/pull/16

use duration, not runtime, keyword for Prometheus metrics

---

discovery-provider/src/api/v1/models/tracks.py

This is to expose the tracks field `is_available` to the api response.
- Hit `http://<my remote box ip>:5000/v1/full/tracks/lebQD` and the `is_available` flag exists
```
// 20220607234337
// http://<my remote box ip>:5000/v1/full/tracks/lebQD
{
"latest_chain_block": 20439,
"latest_indexed_block": 20439,
"latest_chain_slot_plays": null,
"latest_indexed_slot_plays": null,
"signature": "0xd0ea03e3b17ef2c0dacb3dfc4c16e92e6210d52631c229216b6f679109d1756001aa223c4a65f482abcf869c67352699417a9b9b9a52a79351def8d99a41a5381b",
"timestamp": "2022-06-08T03:43:37.594Z",
"version": {
"service": "discovery-node",
"version": "0.3.59"
},
"data": {
"artwork": null,
"description": "description_vpHekC",
"genre": "SomeGenre",
"id": "lebQD",
"mood": "Dope",
"release_date": "",
"remix_of": {
"tracks": null
}, …
```

Add is_available field to tracks api resp

---

discovery-provider/integration_tests/tasks/test_es_indexer.py

This should fix some intermittent errors in the catchup test. Looks like not all items are indexed by the time the tests end. I'll keep an eye out if this still happens.
```
search_res = esclient.search(index="*", query={"match_all": {}})["hits"]["hits"]
>       assert len(search_res) == 6
E       assert 2 == 6
E         +2
E         -6
```
Extended test duration.
Check CI test status.

Extend ES indexer test

---

discovery-provider/src/app.py
discovery-provider/src/tasks/update_track_is_available.py

Looks like `crontab` doesn't work for midnight jobs after some debugging? Since this cadence is arbitrary and this job only took 2 seconds on staging (granted will be much longer on prod), let's just use `timedelta` to run every 12 hours instead.
health check
```
"last_track_unavailability_job_end_time": "2022-06-08 18:57:03.178968 UTC",
"last_track_unavailability_job_start_time": "2022-06-08 18:57:01.293707 UTC",
```
Using `timedelta` on local and staging worked as expected
Can check discovery health check for the start and end timestamps for the job

Set update track is available cadence to every 12 hours 

---

discovery-provider/src/queries/get_health.py

Upon testing, realized that if fetching the end timestamp fails, then the start would come up as `None`. This is to make the fetches exclusive
Ran the health check locally and the timestamps were shown.
No logs needed as the current update_track_is_available logs should be sufficient. Also added an exclusive exception log for each of the try/excepts.

Make exclusive try/except blocks for fetching ts

---

discovery-provider/alembic/versions/88daa6a4f269_index_repair.py

It was observed that the partial indexes added in https://github.com/AudiusProject/audius-protocol/pull/2673 caused needless seq scans for reason not fully understood.
This PR drops any temporary indexes added while experimenting and makes all indexes full indexes.
This query should _not_ do a seq scan:
```sql
explain
select
follower_user_id,
followee_user_id
from
follows f
where
f.is_current is true
and is_delete is false
and followee_user_id = 10;
```
Will check GCP SQL panel after deploy

migration to undo partial and temporary indexes

---

creator-node/compose/env/base.env
creator-node/src/components/healthCheck/healthCheckController.js
creator-node/src/config.js

Previously, snapback health check used a hardcoded value, which is not sufficient for stage or prod nodes
Changing this to be configurable + increasing prod default value
Note - this is a temporary fix until larger stateMachine redesign ships
Existing test coverage is sufficient
This is already live and working correctly on https://creatornode11.staging.audius.co/health_check?enforceStateMachineQueueHealth=true
Any errors containing `StateMachineQueue not healthy - last successful run`
Slack alerts (via pingdom) for stateMachineQueue health, or directly checking `<endpoint>/health_check?enforceStateMachineQueueHealth=true`

CON-200 Make snapbackMaxLastSuccessfulRunDelayMs configurable

---

.circleci/config.yml

We have 2 jobs in our main CI workflow that are on-hold until manually approved. As a result we never get a green success marker on successful CI flows. Since we pretty much never need these jobs, I'm disabling them. Just commented out for now so infra can keep as reference and proceed as they see fit
See CI status for below commit
n/a

INF-128 Remove on-hold jobs from main ci workflow to get dat ✅

---

monitoring/README.md
monitoring/deploy.sh
monitoring/docker-compose.yml
monitoring/prometheus/generate-prom.js

We currently only monitor nodes that are listed via audiusLibs. DP4 has useful metrics as a canary node.
This PR manually adds prod-dp4 to the list of nodes Prometheus listens to.
Currently built, tested, and running on `prometheus-grafana-metrics`.
Who monitors the monitor? :thinking:

[INF-122] Track metrics for dp4

---

discovery-provider/src/api/v1/search.py
discovery-provider/src/utils/redis_metrics.py

`src/api/v1/search.py` did not use the `@record_metrics` decorator previously. Without this decorator, we were not exporting metrics for latency and request counts for search queries.
We are now exporting these metrics in advance of our search rework.
```
audius_dn_flask_route_latency_seconds_sum{code="200",route="/playlists"} 0.059265851974487305
audius_dn_flask_route_latency_seconds_sum{code="200",route="/v1/full/search"} 0.2101149559020996
audius_dn_flask_route_latency_seconds_sum{code="200",route="/v1/full/search/autocomplete"} 0.12108540534973145
audius_dn_flask_route_latency_seconds_bucket{code="200",le="0.005",route="/playlists"} 0.0
audius_dn_flask_route_latency_seconds_bucket{code="200",le="0.01",route="/playlists"} 0.0
audius_dn_flask_route_latency_seconds_bucket{code="200",le="0 …
```

[INF-122] Export search queries metrics to Prometheus

---

discovery-provider/Dockerfile
discovery-provider/integration_tests/queries/test_search.py
discovery-provider/scripts/start.sh
discovery-provider/scripts/test.sh
discovery-provider/scripts/up.sh

A few different test fixes:
* `scripts/test.sh` does `npm i` in `es-indexer` so that tests that call es-indexer will work
* `scripts/up.sh` does `npm i` in `es-indexer` to ensure node_modules stashing works
* fixes `test_search.py` to not rely on timeouts
ran the tests

Ci node modules fix

---

creator-node/src/blacklistManager.js
creator-node/test/contentBlacklist.test.js

Fetching all CIDs for all tracks was causing the content node process to OOM (and also take an absurdly long time to come up during init). This is a fix meant to carry us through until this codepath is fully refactored.
Tested on CN2 and CN3 on production. The tests that were commented in this PR are part of the functionality that no longer works because of these changes
Can hit the /ipfs/ route for CIDs and test whether content is served

Skip fetching all CIDs for all tracks

---

libs/src/services/solanaWeb3Manager/transfer.js

- Back to back tips would break because we would fetch an out of date nonce.
- Solution: use more permissive commitment level for fetching nonce account
Tested locally

[PAY-256] Fix back to back tip nonce error

---

libs/package-lock.json
libs/package.json

Add xmlhttprequest dependency to fix error:
```
Failed to compile.
./node_modules/@audius/sdk/dist/legacy.js
Module not found: Can't resolve 'xmlhttprequest' in '/Users/saliou/Documents/Audius/audius-client/packages/web/node_modules/@audius/sdk/dist'
```
testing with local client using the sdk with this change

Add xmlhttprequest dependency

---

creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.js
creator-node/test/StateMonitoringManager.test.js
creator-node/test/findSyncRequests.jobProcessor.test.js
creator-node/test/monitorState.jobProcessor.test.js
creator-node/test/processJob.test.js

- Test job processors:
- monitorState: update 8/8 failing tests
- findSyncRequests: add 6 new tests
- Fix a typo and bugs that were breaking syncs and duplicates: destructured `syncRequestsToEnqueue` with an extra "s" at the end of the variable name and checked for truthy arrays instead of empty arrays
- monitorState.jobProcessor.js: 92.11% line coverage
- findSyncRequests.jobProcessor.js: 91.8% line coverage
N/A -- tests

Test monitorState and findSyncRequests job processors

---

creator-node/src/blacklistManager.js
creator-node/src/redis.js
creator-node/test/blacklistManager.test.js
creator-node/test/contentBlacklist.test.js
creator-node/test/lib/blacklistManager.js
creator-node/test/lib/utils.js

There is no point to clear the BL on init. This operation is unnecessary adding time and complexity. If adding same keys, redis should override the existing values. Also, the BL is able to handle removing so changes can be made. 
Fix tests to manually clear the BlacklistManager now
Existing logs should be sufficient.

[CON-214] - Removing clearing BL on init

---

creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.js
creator-node/test/StateReconciliationManager.test.js
creator-node/test/issueSyncRequest.jobProcessor.test.js

- Test state reconciliation manager (add 4 new tests)
- Test issueSyncRequest job processor (port over 2 tests from snapback and add 4 new tests)
- Add additional parameter validation to issueSyncRequest job processor
- Fix bug where a sync issuing an additional sync returned an improperly formatted job
- stateReconciliation/index.js: 79.41% line coverage (the rest is untestable and unimportant logger callbacks)
- issueSyncRequest.jobProcessor.js: 93.75% line coverage
N/A

[CON-203] Test reconciliation manager + issueSyncRequest job processor

---

creator-node/src/services/stateMachineManager/stateMonitoring/findReplicaSetUpdates.jobProcessor.js
creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.js
creator-node/test/findReplicaSetUpdates.jobProcessor.test.js

- Fix findReplicaSetUpdates job processor bug where I forgot to pass logger
- Fix passing Set through Bull (it doesn't serialize it properly) by changing it to an array
- Add 7 new tests for findReplicaSetUpdates job processor (90.67% line coverage)
N/A
N/A

[CON-203] Test findReplicaSetUpdates job processor

---

discovery-provider/default_config.ini
discovery-provider/src/tasks/index.py
discovery-provider/src/tasks/sort_block_transactions.py
discovery-provider/src/tasks/sort_block_transactions_unit_test.py

Switches sort by hash to sort by transactionIndex.
We would like this to happen in unison across all nodes. Given release cycle, July 11 seems like a good date. This translates to `392727` blocks ahead for prod (5.5s production rate).
The target blocks for this activation are:
prod: 28344410
staging: as soon as code is merged, pick block number ~100 ahead.
This should be watched closely on staging for side effects.
This should be watched closely on staging for side effects.

[PLAT-181] Sort by transactionIndex instead of hash

---

creator-node/src/serviceRegistry.js
creator-node/src/services/stateMachineManager/stateMonitoring/findReplicaSetUpdates.jobProcessor.js
creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.js
creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.js
creator-node/test/findReplicaSetUpdates.jobProcessor.test.js

- Change `replicaSetNodesToUserClockStatusesMap` sent to updateReplicaSet job from a map of node => wallet => clockValue to just node => clockValue (it doesn't need all wallets - just the one for the user whose replica set is being updated)
- Fix validating healthyNodes before creating it in updateReplicaSet job
- Truncate large Bull job data and result objects - see https://github.com/felixmosh/bull-board/pull/414#issuecomment-1134874761 
- Fix empty sync request getting enqueued (it was a no-op but pollutes queue history)
- Updated findReplicaSetUpdates test to make sure filtering other wallets works
- Ran `A up` locally to make sure truncating didn't break Bull Board ~~(will need more data from staging to verify actual functionality)~~ and tested with a max of 10 characters (instead of …

Fix miscellaneous state machine bugs

---

creator-node/src/serviceRegistry.js
creator-node/src/services/stateMachineManager/makeCompletedJobEnqueueOtherJobs.js
creator-node/src/services/stateMachineManager/stateMonitoring/monitorState.jobProcessor.js
creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.js
creator-node/test/StateReconciliationManager.test.js
creator-node/test/updateReplicaSet.jobProcessor.test.js

- Make truncated data show length and truncate after 100 keys/elements instead of stringifying arrays and checking for 10,000 characters
- 10,000 characters was still too large to be readable for some data, and not doing a keys/elements check means large nested properties cause the whole parent object to be truncated
- Fix updateReplicaSet job processor bugs:
- Function taking regular params when it's passed an object
- Validating unhealthyReplicas as a set instead of array
- Not being passed reconfig modes array
- Returning extra nested jobsToEnqueue
- Return updateReplicaSet error in job data (previously it was only logged but not viewable on the dashboard) and do other cleanup in that job processor
- Add basic tests for updateReplicaSet since basic errors like these should really be …

Fix updateReplicaSet, add a few tests, and improve dashboard truncation

---

discovery-provider/src/queries/notifications.py

- Min Slot needs to be exclusive, otherwise Identity will repeat the same push notifs (not great, but hopefully addressed in notifs v2 @jowlee). This matches the behavior for regular non-solana notifications
- Push notifs were broken, made this change, now they work

Fix Solana Notification generation cutoff

---

identity-service/src/notifications/processNotifications/reactionNotification.js

- Only show a single reaction notification per tip
- Tested on remote box, sent multiple reactions, saw we weren't creating new notification rows
- Will test push notifs on stage

[PAY-370] Dedupe reaction notifications

---

creator-node/compose/docker-compose.yml
creator-node/compose/env/shellEnv1.sh
creator-node/nginx_conf/nginx.conf
creator-node/scripts/start.sh
creator-node/src/config.js
creator-node/src/index.ts
creator-node/test/contentBlacklist.test.js

The purpose of this PR is to cache the content that is served from `/ipfs/<cid>` and `/content/<cid>`. This is part of the work to reduce load on Content Nodes, and was originally slated 6 months ago before the [bug fix](https://github.com/AudiusProject/audius-protocol/pull/3046) was merged to not serve empty content.
- Hit a route that responded with 200 and 404 (non 200) to see if content was cached, and it is since the `x-cache-status` header was appended to the response.
If there are some issues, we can debug by checking `/usr/local/openresty/logs/error.log` and `/usr/local/openresty/logs/access.log`

[CON-224] - Re-enable nginx cache

---

discovery-provider/es-indexer/src/helpers/splitTags.ts
discovery-provider/es-indexer/src/indexNames.ts
discovery-provider/es-indexer/src/indexers/PlaylistIndexer.ts
discovery-provider/es-indexer/src/indexers/TrackIndexer.ts
discovery-provider/es-indexer/src/indexers/UserIndexer.ts
discovery-provider/es-indexer/src/indexers/sharedIndexSettings.ts
discovery-provider/es-indexer/src/types/docs.ts
discovery-provider/src/queries/search_es.py
discovery-provider/src/queries/search_queries.py
discovery-provider/src/tasks/index_materialized_views.py
discovery-provider/src/utils/elasticdsl.py

Tag search endpoint uses elasticsearch
Actually some TODOs:
```
export DEV=http://1.2.3.4:5000
curl -H "X-User-ID: 1" "$DEV/search/tags?kind=all&limit=15&offset=0&query=hybrid&user_tag_count=1"  | jq '.data.followed_users'
```

tag search on elasticsearch

---

creator-node/compose/env/base.env
creator-node/default-config.json
creator-node/src/config.js
creator-node/test/StateMonitoringManager.test.js

Changes config defaults to disable snapback and enable the refactored state machine at a rate of 3 monitoring jobs per minute. Note that this change doesn't stop the manual sync queue, which snapback will continue to run regardless of the config options.
These are the values that staging nodes have been using for a few days with no known issues. Check the monitoring steps below on staging.
Check (on staging but also prod since this changes default configs for prod):
- Queues are healthy -- `/health/bull` endpoint shows:
- `state-monitoring-queue` and `state-reconciliation-queue` queues are processing jobs that show inputs (jobData) and outputs (returnValue). Spot check some of each job type to make sure they look reasonable
- `state-machine` and `recurring-sync-queue` queues are not …

Disable snapback, enable refactored state machine

---

discovery-provider/src/tasks/index_trending.py

pg_dump will block the matview refresh...
and then multiple instances of this job will start running
keep an eye on discovery blockdiff + postgres queries that are waiting for locks

update trending lock timeout to 24h

---

creator-node/src/services/stateMachineManager/CNodeToSpIdMapManager.js

saw this log
```
[2022-06-27T19:07:40.478Z]  INFO: audius_creator_node/13166 on 5bb7a1ff2882: updateEndpointToSpIdMap Success. Size: undefined (logLevel=info)
```
realized that we didnt need to `.length` a length var 😉 
- no additional tests needed
- manual test log output
```
[2022-06-27T19:13:28.911Z]  INFO: audius_creator_node/13786 on 5bb7a1ff2882: updateEndpointToSpIdMap Success. Size: 4 (logLevel=info)
```
monitoring the same log

Dont need to .length a length

---

creator-node/compose/env/base.env
creator-node/src/components/healthCheck/healthCheckComponentService.js
creator-node/src/components/healthCheck/healthCheckComponentService.test.js
creator-node/src/components/healthCheck/healthCheckController.js
creator-node/src/config.js
creator-node/src/monitors/monitors.js
creator-node/src/monitors/stateMachine.js
creator-node/src/services/stateMachineManager/processJob.js
creator-node/test/processJob.test.js

- Remove `snapbackMaxLastSuccessfulRunDelayMs` env var
- Add an env var for each of the 3 state monitoring queue jobs: `monitorStateJobLastSuccessfulRunDelayMs`, `findSyncRequestsJobLastSuccessfulRunDelayMs`, and `findReplicaSetUpdatesJobLastSuccessfulRunDelayMs`
- Record last job start and success for each state machine queue job in redis
- Make `health_check?enforceStateMachineQueueHealth=true` route enforce env vars for max time since last successful job run for each state monitoring job
**Health Check Response When Healthy**
**Health Check Response When Unhealthy**
Updated health check tests to reflect new vars, and checked the route locally with a disabled and enabled queue (verified that disabling the monitoring queue makes the health check fail after 10 minutes since no jobs run). …

[CON-195] Update health check for new queues

---

identity-service/src/notifications/sendNotificationEmails.js

For weekly email users, get notifications more recent than a week ago (rather than a day ago).
none
none

Update timestamp for weekly email users and fix typo

---

creator-node/nginx_conf/nginx.conf

Might as well bump the cache ttl to 12h from 30m, since the cn5 cache enabled soak is working out well.
No change in functionality, just bumping the ttl
Can still check the nginx access.log and error.log
Also if `x-cache-status` is in the response headers, then the nginx cache is enabled

[CON-230] - Bump nginx cache ttl

---

creator-node/nginx_conf/nginx.conf
creator-node/src/routes/files.js

We only want to cache on 404, but for some reason, content was still cached. Turns out it is because we were setting the `cache-control` header to `public, max-age=2592000` even if content was not servable (e.g. 404-ing). The keyword `public` implies that content can be cached on client or server side.
So, this PR is to only set the the download/cache headers if content is definitely served.
Before, if the `ipfs/<cid>` route was getting a 404, it would result in a cache miss, then a cache hit.
After, all 404s will only result in a cache miss.
We will still monitor nginx logs in the logs file, and can observe the `x-cache-status` header

[CON-229] - Fix content caching

---

.circleci/config.yml

Have `--fast` launched nodes start with a clean `git status` output.
Manually run these commands on first boot.

Start remote-dev with a clean `git status`

---

creator-node/src/snapbackSM/snapbackSM.js
creator-node/test/snapbackSM.test.js

Make the `disableSnapback` env var prevent the snapback recurring sync queue from processing jobs.
Updated a relevant snapback test to pass (it failed at first due to the change, which is good). Checked locally to make sure the `recurring-sync-queue` queue doesn't process jobs with `disableSnapback` set to `true`.
Make sure the `recurring-sync-queue` queue doesn't process jobs on any staging nodes (check this from the `/health/bull` dashboard).

Disable recurring sync processing in snapback

---

discovery-provider/alembic/versions/38642fb2948d_add_pg_triggers.py

Running queries can hold up alembic migration for a long time, but celery is stopped already so should be safe to kill them.

Kill running queries before migration

---

creator-node/src/routes/files.js

There was an error `Cannot set headers after they are sent to the client` with moving the headers right after creating the stream because on the `end` event, we call `res.end()`. This prevents us from adding headers cus the response is closed. 
So, this fix is to add the the cache-control header + content-disposition header before creating the stream, and on err, remove the cache-control
- hit ipfs/cid route with cid that responds with 200
- hit ipfs/cid route with cid that responds with 404
- hit ipfs/cid route with cid that responds with 200, and the file is empty (original scenario for source of bug)
See `[getCID]` decision tree logs, or see `requestUrl: /ipfs/<cid>` in logs

Fix streaming via /ipfs/<cid> and /content/<cid>

---

creator-node/src/services/stateMachineManager/stateMachineUtils.js

spID value was 0 because it was fetched before it was set. Updated to only fetch inside function call instead of at top of file to always get latest value
Currently we see errors like
```
{"name":"audius_creator_node","hostname":"b2bbeffbdeff","pid":13,"requestID":"iJObYqi7Cz","requestMethod":"GET","requestHostname":"127.0.0.1","requestUrl":"/users/clock_status/0x2d7f378c77239e652834b750fc18d6711699a5e6","requestQueryParams":"spID=0&timestamp=2022-06-29T22:38:43.574Z&signature=0x34af4918dcf7bb39d7b1d28953b96fafd3697f217f616caf5cdd37721650b27950465e96b3a9f18f7428ff1faf737cd138cfaf889359a0af71634057213eb9eb1b","level":30,"msg":"Begin processing request","time":"2022-06-29T22:38:43.638Z","v":0,"logLevel":"info"}
{"name":"audius_creator_node","hostname":"b2bbeffbdeff","pid":13,"level":30,"msg" …
```

Fetch CN spID config after it has been set

---

discovery-provider/src/api/v1/playlists.py
discovery-provider/src/queries/get_top_playlists.py

Updates the `/v1/full/playlists/top` endpoint to return the score and pass the mood parameter to underlying method
Manually ran
Fixes PLAT-233

top playlists endpoint

---

creator-node/src/routes/files.js

Since the stream fn actually sets and unsets the header, these manual setting/unsetting shouldn't be necessary anymore
- Deployed this hash to stage cn5 and it looks good https://creatornode5.staging.audius.co/ipfs/QmWut8nyZmVftG2ASeLzssULBbbXLnb59ZmTKencJH7nU2/original.jpg
For making dir cid requests, check to see if `cache-control` is properly set on 200s and non-200s (e.g. should be set on 200s, not set on 200s)

Remove redundant header setting/unsetting

---

identity-service/src/solanaNodeRegistration.js
libs/src/api/rewards.js
libs/src/api/serviceProvider.js
libs/src/services/solanaWeb3Manager/rewardsAttester.ts
libs/tests/rewardsAttesterTest.js

- Was seeing an error on prod identity trying to register solana nodes; the internal whitelist of a single DN would prevent Identity from selecting a quorum of nodes in `getUniquelyOwnedDiscoveryNodes`. This fixes that
- Add try catches to the bull queue code on identity; if there are errors here, as it is right now we get a vague redis parsing error.
TBH I think there's more going on here; but it's very hard to test this. This should strictly be better than what we have, and I'm hopeful the additional try catch logs should shed some more light on what's going on.
Tested this on a local stack. Seems to work - I'm seeing a borsh IO error though, which should be unrelated to anything we touched. I'm not sure when / if ever we tried using create-sender locally, so I suspect that simply isn't …

[PAY-401] Fix Solana Node registration script

---

libs/src/services/discoveryProvider/DiscoveryProvider.ts
libs/src/services/discoveryProvider/requests.ts

Updates libs to add discovery endpoints: top playlists, best new releases, and most loved tracks
reference discovery pr: #3353
Ran locally against linked libs
Fixes PLAT-233

Add libs explore endpoints

---

discovery-provider/default_config.ini
discovery-provider/src/api/v1/users.py

Sets caching for the `/v1/full/users/content_node/all` route to be 5 seconds on local by default. See audius-docker-compose and audius-k8s PRs to make this 5 minutes on staging/prod:
- https://github.com/AudiusProject/audius-docker-compose/pull/32
- https://github.com/AudiusProject/audius-k8s/pull/403
The state machine on Content Nodes uses this route with pagination queryparams to fetch a page of users who have the Content Node in their replica set.
If each staging/prod node has (very roughly) ~100K users and fetches in pages of 1000 users every 3 minutes (that's the current configuration), then 5 minutes is very conservative -- it gives enough time to make sure the state machine won't cycle back to the same users and fetch stale data that doesn't reflect updates it performed during its …

Make get_users_cnode cache configurable

---

creator-node/src/services/stateMachineManager/index.js
creator-node/src/services/stateMachineManager/stateMonitoring/index.js

I resolved merge conflicts on the last 2 PRs without re-testing, and they had a little error that completely broke the state machine queues. This fixes that by making sure `prometheusRegistry` is passed to all job processors.
Tested locally to make sure jobs aren't failing anymore. They were failing when I deployed to staging because `prometheusRegistry` couldn't be found.
I'll deploy to staging shortly to make sure jobs start completing successfully again on the `/health/bull` endpoint.

Fix prometheusRegistry not being passed to state machine job processor

---

creator-node/src/services/stateMachineManager/index.js

Same thing as [last PR](https://github.com/AudiusProject/audius-protocol/pull/3369) but for the reconciliation queue instead of just the monitoring queue. Whoops.

Oops fix reconciliation prometheusRegistry too

---

discovery-provider/src/tasks/update_track_is_available.py

The track availability job takes longer than 30 seconds, and the lock is getting released before the end time stamp gets fulfilled. This is as shown as the key value is null for all discovery prod nodes.
```
"last_track_unavailability_job_end_time": null,
```
This PR is to reorder when the redis timestamp gets filled
No new tests since there is no change in functionality, just reordering operations.
See log for `Could not get latest track unavailability job end timestamp` in discovery node.

Reorder try/catch for start/finish redis key

---

monitoring/prometheus/generateProm.js

Previously prometheus.yml did not include content nodes as prometheus targets, this PR adds support for that.
Ran the script to generate prometheus.yml and verified it works.
`PROM_ENV=prod node generateProm.js`
Hosts should be visible in Grafana after adding these targets

Add support for content nodes as prometheus targets

---

discovery-provider/src/tasks/update_track_is_available.py

Update the prometheus metric tracking according to standard. Thanks @joaquincasares for guiding me here!
Checked the `/prometheus_metrics` route for the `update_track_is_available` worker
```
audius_dn_update_track_is_available_duration_seconds_sum{success="true",task_name="update_track_is_available"} 0.36917924880981445
audius_dn_update_track_is_available_duration_seconds_bucket{le="0.005",success="true",task_name="update_track_is_available"} 1.0
audius_dn_update_track_is_available_duration_seconds_bucket{le="0.01",success="true",task_name="update_track_is_available"} 7.0
audius_dn_update_track_is_available_duration_seconds_bucket{le="0.025",success="true",task_name="update_track_is_available"} 8.0
audius_dn_update_track_is_available_duration_seconds_bucket{le="0.05",success="true",task_n …
```

Add success true and false metrics w prometheus

---

creator-node/src/services/prometheusMonitoring/prometheus.constants.js
creator-node/src/services/stateMachineManager/makeOnCompleteCallback.js
creator-node/src/services/stateMachineManager/stateMachineUtils.js
creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.js
creator-node/src/services/stateMachineManager/stateReconciliation/index.js
creator-node/test/findSyncRequests.jobProcessor.test.js
creator-node/test/issueSyncRequest.jobProcessor.test.js

- Add prometheus gauge `audius_cn_find_sync_request_counts` for finding syncs. This will give us insight into when monitoring jobs find or don't find syncs for any of the following reasons:
- `not_checked`: Default value -- means the logic short-circuited before checking if the primary should sync to the secondary. This can be expected if this node wasn't the user's primary
- `no_sync_already_marked_unhealthy`; Sync not found because the secondary was marked unhealthy before being passed to the find-sync-requests job
- `no_sync_sp_id_mismatch`: Sync not found because the secondary's spID mismatched what the chain reported
- `no_sync_success_rate_too_low`: Sync not found because the success rate of syncing to this secondary is below the acceptable threshold
- …

Add metric for find-syncs and fix reconciliation queue history

---

discovery-provider/src/tasks/index.py

Perhaps these expected error|warn statements should in fact be info statements so we have cleaner logs.
None.

demote error|warn logs

---

creator-node/src/serviceRegistry.js
mad-dog/src/index.js

Part of the task to handle graceful shut down include closing out jobs in all queues. To do this, we need to know which queues exist in the Content Node. No one knows before hand unless they (1) have all the queues memorized to heart, (2) scavenge through ServiceRegistry, and/or (3) look for all files with the word `Queue` appended to them. 
ServiceRegistry needed some love anyway 🤷‍♀️ 
This PR is to:
- expose **every** member variable in the constructor of the ServiceRegistry
- clean some some conflated initializations
- update comments
No tests, just reordering member variables + cleaning up initialize service calls
No new logs

Initialize everything in ServiceRegistry constructor

---

discovery-provider/src/tasks/index_network_peers.py

Remove query to retrieve peers from db as it's not needed because we do not rely on ipfs anymore
Notes: on prod dn2 it's the 5th most expensive query over the last week and 3rd most on dn3 when viewing load by time

Remove retrieve peers from db

---

discovery-provider/src/api/v1/users.py
libs/src/services/discoveryProvider/DiscoveryProvider.ts

Have verifyToken endpoint expect either hashid or integer user id. This is in anticipation of [this PR](https://github.com/AudiusProject/audius-client/pull/1557) on the client side being released. After both PRs are released, we should change this to just expect hashid user ids.

Make `verifyToken` endpoint expect either hashid or int user id (eventually just hashid)

---

discovery-provider/src/queries/get_celery_tasks.py
discovery-provider/src/queries/get_health.py
discovery-provider/src/tasks/aggregates/__init__.py
discovery-provider/src/tasks/index.py
discovery-provider/src/tasks/index_metrics.py
discovery-provider/src/tasks/index_trending.py
discovery-provider/src/tasks/tracks.py
discovery-provider/src/tasks/update_track_is_available.py
discovery-provider/src/tasks/users.py
discovery-provider/src/utils/prometheus_metric.py
discovery-provider/src/utils/redis_metrics.py
monitoring/README.md
monitoring/grafana/dashboards/audius-boilerplate.json
monitoring/grafana/dashboards/audius-discovery-provider-blockchain-indexing.json
monitoring/grafana/dashboards/audius-discovery-provider-celery-task-details.json
monitoring/grafana/dashboards/audius-discovery-provider-celery-tasks.json
monitoring/grafana/dashboards/audius-discovery-provider-overview.json
monitoring/grafana/dashboards/audius-network-monitoring.json
monitoring/grafana/dashboards/dheeraj-content-node-dashboard-test.json
monitoring/grafana/dashboards/joaquin-network-monitoring-v2.json
monitoring/grafana/dashboards/joaquin-playground.json

* Consolidate where metrics are created/defined.
* Change pattern to this: 328e8c3ca5c3cb35741a77f6fbff535d19518b08.
* Follow standardized naming scheme.
* Update related dashboards with new metric names.
Release checklist:
Ensure existing dashboards continue to populate with new data.
#eng-infrastructure

Create a CN-like metric registry for DN's Prometheus metrics

---

creator-node/nginx_conf/nginx.conf

Lower the cache max size from 10g -> 4gb since the min requirement for sps is 16gb
No new tests as this is just reducing the size of the cache
Check nginx access and error logs

Lower cache size to 4gb

---

discovery-provider/src/tasks/update_track_is_available.py
discovery-provider/src/utils/prometheus_metric.py

Remove unused label that is consuming unneeded space/load on Prometheus.
However, once we have a use case for different labels, we can revisit this metric and add these labels back in.
Run locally and confirmed that `update_track_is_available_duration_seconds` metrics are still being produced.
#eng-infrastructure for any issues.

INF Cleanup unused label

---

creator-node/src/fileManager.js

When writing files to disk from metadata uploads, we never validate the contents of the file. This adds content verification + retries similar to how the saveFileForMultihashToFS does.
Tested by running A seed create-user and making sure the metadata object is stored on disk and stored via the /ipfs route. Also forced the retry logic by forcing failure inside the try clause if numRetries > 3 to make sure it correctly retries and eventually succeeds correctly. 
We can search the logs for "Error during content verification for multihash". Note, this log is the same as the saveFileForMultihashToFS error log since they represent the same underlying issue.

Add content verification + retries for metadata writes

---

libs/rollup.config.js

Ran into a build issue in a project using the SDK:
```
Module not found: Error: Can't resolve 'url' in '/Users/Reed/audius/faucet/node_modules/xmlhttprequest/lib'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "url": require.resolve("url/") }'
- install 'url'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { "url": false }
```
which was resolved by adding xmlhttprequest to the SDK's internal bundle so that it would be polyfilled. Webpack 5 removed node.js polyfills.
npm linked local libs to the project that was importing …

Added xmlhttprequest to internal browser bundle

---

discovery-provider/src/queries/search_es.py

negative follower_count was causing ES ranking to break:
```
field value function must not produce negative scores, but got: [-Infinity] for field value: [-2.0]
```
This uses a script_score script to clamp values to 0.
Really should not have negative values,
but trigger counters need to be fixed to avoid bad data in a later commit.
```
/v1/full/search/autocomplete?limit=3&offset=0&query=a&user_id=aNzoj
```
works afterwards

handle negative values in ranking field

---

identity-service/src/notifications/processNotifications/reactionNotification.js
identity-service/src/routes/reactions.js

- Fixes an error with parseInt
- Properly deletes Reaction notifications if a reaction is unsent
**Note** this also requires a small client change to complete the issue - currently waiting for better WIFI before putting up a PR.
Tested on staging.

[PAY-414] Fix unsending reactions

---

discovery-provider/src/queries/health_check.py

We are now including both active and registered tasks when getting all celery tasks ([code](https://github.com/AudiusProject/audius-protocol/blob/012150482a15b0105d1e12864a9372d6a0530b6a/discovery-provider/src/monitors/celery.py#L66-L69)).
This PR updates /celery_tasks_check to only look at the active tasks, as it used to.
Release locally and ensure /celery_tasks_check is fixed.
Check /celery_tasks_check during staging and production releases.

fix /celery_tasks_check

---

libs/src/services/contracts/ContractClient.ts
libs/src/utils/types.ts

This PR remove `.log()` from the logger type and removes any `logger.log()` calls in favor of something more descriptive. 
This is fixing the type error from content node of "`_this2.logger.log()` is not a function" because bunyan doesn't have a logger (thank you @dylanjeffers for helping debug)
tested locally by running locally
These changes will be monitored on loggly

[CON-183] Fix libs logger issue in CN by consuming latest typed libs

---

creator-node/compose/env/base.env
creator-node/src/config.js

Forgot in the last PR -- we also want write quorum to be enforced by default locally for testing. Only prod needs to default to off.
N/A -- this is what it was set to before a few hours ago
N/A

Default write quorum to on for local

---

dev-tools/audius-compose
dev-tools/startup/discovery-provider.sh
dev-tools/startup/socks5-proxy-pac.py
discovery-provider/scripts/start.sh
docker-compose.yml

This PR adds a SOCKS5 proxy so that we can connect the audius-client to our local development stack 
To use the proxy from a mac:
```
networksetup -setautoproxyurl "Wi-Fi" "http://<instance ip>:8080/proxy.pac"
```
Change "Wi-Fi" to network interface name you find in system settings
Then on your local machine you can go to http://audius-protocol-creator-node-2:4000/health_check
Pending working client
NA

[INF-180] Add SOCKS5 proxy for use with client

---

creator-node/src/serviceRegistry.js

This was mistakenly moved outside initServices() in serviceRegistry. The reason this is a problem is the result of serviceRegistry right after initServices get set in express as global variables as app.set(...) and the notifier service was not initialized at the time it was set which was causing problems.
Pushed out hotfix onto cn3 and verified it works
Planning to expose trusted notifier id and wallet in a follow up PR, merging this just to unblock prod deploy

Move trusted notifier init back to await-ed init

---

.circleci/config.yml

Image bake has been failing in CI for a few days, it's been stuck on "Too long with no output (exceeded 10m0s): context deadline exceeded" after `A run monitoring up;`. I removed `A run monitoring up;` and it seems to be passing now, not sure why it's causing bake to fail.
Example of failing bake https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/25197/workflows/b8b7d08d-f618-4bf5-9328-27afd6c57afb/jobs/300858. This has been happening for several days, not just a one off
Working bake in this CI run https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/25235/workflows/5f1c3f53-2f7a-4e64-84ec-ea7d5d3ec602/jobs/300918
Image bake will fail in CI

Run image bake without monitoring

---

creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js
creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.js
creator-node/test/updateReplicaSet.jobProcessor.test.js

SyncMode wasn't always passed in so issueSyncRequest.jobProcessor/_validateJobData threw an error ````Invalid type ("${typeof syncMode}") or value ("${syncMode}") of syncMode param````
Tested locally by running mad-dog
Added a new check in getNewOrExistingSyncReq in StateReconciliationUtils to make sure we error if syncMode is not passed in. Error message is "getNewOrExistingSyncReq missing parameter"

Always require syncMode to be defined

---

creator-node/src/services/stateMachineManager/makeOnCompleteCallback.js
creator-node/src/services/stateMachineManager/stateMonitoring/index.js
creator-node/src/services/stateMachineManager/stateMonitoring/monitorState.jobProcessor.js
creator-node/src/services/stateMachineManager/stateMonitoring/stateMonitoringUtils.js
creator-node/src/services/stateMachineManager/stateReconciliation/index.js
creator-node/src/snapbackSM/secondarySyncHealthTracker.js

Some changes from QA + digging through the logs a bit:
- Fix a rename bug for reconciliation queue history
- Consolidate job status logging so we can filter by jobId. Searching for "Queue Job Completed" wasn't ideal
- Log error stack traces in monitor-state jobs. I'm trying to debug an error in one of the steps, and it's hard to pin point without the stack trace
- Add some default values to fix rare `Cannot convert undefined or null to object` error in the `computeUserSecondarySyncSuccessRatesMap` step of some monitor-state jobs (seen on prod)
Made sure queues are running locally with correct logs. Will be more valuable to test on staging with many users.
- We should be able to track any one job more thoroughly now by filtering in Loggly for `json.jobId:<JOB_ID>`. These logs should …

Misc state machine improvements / bug fixes

---

creator-node/Dockerfile

```
------
> [audius-protocol_creator-node base 4/8] RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.10/main' >> /etc/apk/repositories &&     apk update &&     apk add         bash=5.1.16-r0         curl         docker=20.10.3-r1         libpq=11.12-r0         nodejs=14.19.0-r0         npm         postgresql-client=11.12-r0         postgresql-contrib=11.12-r0         postgresql-libs=11.12-r0         postgresql=11.12-r0         py3-pip         python3         python3-dev         redis=6.0.16-r0         rsyslog=8.2012.0-r3         sudo=1.9.5p2-r0:
#0 0.369 fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
#0 0.551 fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
#0 0.718 fetch …
```

Fix CN nodejs version

---

.circleci/config.yml

Use the new audius-infra key for Github access.
Manually testing our automated deploy script for Audius sdk.

INF-86 use new audius-infra ssh key for merging audius-sdk branches

---

creator-node/package-lock.json
creator-node/src/fileManager.js
creator-node/src/middlewares.js
creator-node/src/serviceRegistry.js
creator-node/src/services/initAudiusLibs.js
creator-node/src/services/sync/primarySyncFromSecondary.js
creator-node/src/services/sync/secondarySyncFromPrimary.js
creator-node/src/services/sync/skippedCIDsRetryService.js
creator-node/test/sync.test.js

**Problem**
circular dependency between `primarySyncFromSecondary` and `serviceRegistry`: `primarySyncFromSecondary` imports `serviceRegistry`, which imports `stateMachineManager`, which eventually imports `issueSyncRequest.jobProcessor` which imports `primarySyncFromSecondary`
**Solution**
- Move `serviceRegistry._initAudiusLibs()` to separate file
- update `serviceRegistry` to consume above
- update `saveFileForMultihashToFS()` and `getCreatorNodeEndpoints()` to accept `libs` instead of `serviceRegistry`
- same changes to other files
Existing test coverage
TODO maddog regression test
Error log containing `[primarySyncFromSecondary]` and `InitAudiusLibs Error`
Logs containing `circular dependency` or `initAudiusLibs`

Fix primarySyncFromSecondary circular dep by moving initAudiusLibs to separate file

---

creator-node/src/config.js

Increase timeout for write quorum to wait 1 minute for a sync to complete to at least 1 secondary. This will impact the buckets for the `audius_cn_write_quorum_duration_seconds` metric, so I confirmed with @jonaylor89 that this will be OK for Prometheus since it's NoSQL.
N/A
Timeouts in the logs should show 1 minute (or stop timing out) instead of 5 seconds. The log message `"Failed to reach 2/3 write quorum for user <WALLET> in <TIME>ms"` should have a <TIME> larger than 5000.

Increase write quorum timeout to 1m

---

creator-node/src/components/replicaSet/exportComponentService.js
creator-node/src/routes/nodeSync.js
creator-node/test/sync.test.js

This PR splits the `/export` route into two functions, one for handling the request and one for performing business logic called `exportComponentService`. 
A new test was added for the `exportComponentService` to make sure that the correct error is thrown when the database returns inconsistent clock values.
The current logs are sufficient for monitoring these changes.

[CON-262] Add more test coverage for /export

---

creator-node/default-config.json
creator-node/src/services/stateMachineManager/stateMachineUtils.js
creator-node/src/services/stateMachineManager/stateMonitoring/index.js
creator-node/src/services/stateMachineManager/stateReconciliation/index.js
creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.js

- Extract making queues and common loggers into 2 functions and make sure they're applied to all state machine queues (this is especially important for debugging manual syncs since that queue didn't have the stalled logs)
- Lower the write quorum wait time on staging to 5 seconds
Made sure existing tests pass and queues run correctly on local (these changes mostly impact the queue setup).
As part of debugging manual sync jobs failing, check logs for: `json.queue:"manual-sync-queue" AND json.logLevel:"error"`

More state machine cleanup

---

creator-node/src/AsyncProcessingQueue.js
creator-node/src/ImageProcessingQueue.js
creator-node/src/TranscodingQueue.js
creator-node/src/monitors/MonitoringQueue.js
creator-node/src/services/sync/skippedCIDsRetryService.js
creator-node/src/services/sync/syncQueue.js

This PR adds queue history (both onComplete and onFail) to every queue that didn't already have it 
* ImageProcessingQueue
* AsyncProcessingQueue
* SyncQueue
* SkippedCIDRetryQueue
* MonitoringQueue
* TranscodingQueue
We'll be able to monitor these changes on the bull dashboards

[CON-233] Add queue history for all remaining queues

---

libs/package-lock.json
libs/src/api/user.js
libs/src/sanityChecks/index.js
libs/src/sanityChecks/setIsCreatorToTrue.js
libs/src/services/dataContracts/UserFactoryClient.ts

Add sanity check to set `is_creator` to `true` to help along old clients that have not updated to >=1.1.13. Flare-97
Tested locally with new web and old client and verified that user is able to update metadata on the old client

Sanity check setIsCreatorToTrue

---

creator-node/src/app.js
creator-node/src/components/healthCheck/healthCheckController.js
creator-node/src/routes/audiusUsers.js
creator-node/src/routes/contact.js
creator-node/src/routes/files.js
creator-node/src/routes/healthCheck.js
creator-node/src/routes/index.js
creator-node/src/routes/nodeSync.js
creator-node/src/routes/playlists.js
creator-node/src/routes/prometheusMetricsRoutes.js
creator-node/src/routes/tracks.js
creator-node/src/routes/users.js
creator-node/src/serviceRegistry.js
creator-node/src/services/prometheusMonitoring/prometheusRegistry.js
creator-node/test/prometheus.test.js

All routes that hit CN get registered, which is not we want. This is to only track registered routes in prometheus. 
To know which routes to track before hand, we needed to convert routes instantiated in `app` as a `router` object instead (to which is the largest chunk of the delta in this PR)
- hit regular routes -> was tracked
- hit routes with route params -> was tracked
- hit random routes -> not tracked
Check to see if `/prometheus_metrics` tracks any routes that are not explicitly tracked when hit

Only track metrics for explicit routes

---

discovery-provider/alembic/versions/ab56e2d974a6_fix_ray_account.py

Ray had created a test user (named "hardforktest1", user_id: 987591) and mistakenly used the same wallet address as in his nomal prod account. This breaks our assumption that users have a 1-1 relationship to wallets which tip indexing relies on. This migration changes the wallet address of hardforktest1 to a garbage value.
Tested on remote dev box: created fake user in users table, then ran migration and visually confirmed the wallet value changed.
Before:
After:
Once the migration is run I will confirm with Ray that he is able to send tips. Should also keep an eye out for any unexpected behavior on his prod account.

[PAY-433] Fixed Ray's broken prod account

---

discovery-provider/plugins/network-monitoring/src/metrics/index.ts
discovery-provider/plugins/network-monitoring/src/metrics/queries.ts
discovery-provider/plugins/network-monitoring/src/prometheus.ts

This PR adds the metric `userCount` which is just the total number of users on Audius during that run. Having this metric will let us calculate percentages for things in grafana.
This PR also adds the number of users entirely on foundation nodes into the slack report which was something I forgot to do in my original PR.
Ran a network monitoring job locally
This will be monitored with slack, prometheus and grafana

[CON-265] Add percentage based metrics to network monitoring

---

creator-node/src/components/replicaSet/exportComponentService.js
creator-node/test/sync.test.js

**Problem**
[Recent commit](https://github.com/AudiusProject/audius-protocol/commit/c6ad867e5fb433f49bae4d66466cc8eba170e5b7#diff-603c68a5c307de706249f27b45a7499857db7ed1402ac39b6aefa0ca0fae3e1cR137) introduced bug in export
Example:
https://creatornode9.staging.audius.co/export?wallet_public_key[]=0x33b11f3273523704fecbc7eed7c11bd4a8e4dc4f&clock_range_min=37&source_endpoint=https:%2F%2Fcreatornode5.staging.audius.co
```
Error: Cannot export - exported data is not consistent. Exported max clock val = 36 and exported max ClockRecord val -Infinity
```
[All instances on loggly](https://audius.loggly.com/search#terms=%22Cannot%20export%20-%20exported%20data%20is%20not%20consistent%22%20tag:audius-stage-creator-*&from=2022-07-20T18:41:39.803Z&until=2022-07-22T18:41:39.803Z&source_group=)
This …

CN - Fix export bug

---

creator-node/src/components/replicaSet/exportComponentService.js
creator-node/src/routes/nodeSync.js
creator-node/src/services/sync/primarySyncFromSecondary.js
creator-node/test/sync.test.js

**Problem**
If any corrupted state in a node, it currently rejects any export with error, which breaks the MergePrimaryAndSecondary flow. A primary should be able to merge secondary content over regardless of any corrupted state (in fact, this is when it really matters)
**Solution**
Add an optional `force_export` query param to export route to return user info instead of throwing error
Existing test coverage
Ensure no `/export` routes with non-200 status code and `force_export` query param

Add force_export query param to /export route for MergePrimaryAndSecondary

---

creator-node/src/services/prometheusMonitoring/prometheus.constants.js
creator-node/src/services/prometheusMonitoring/prometheusUtils.js

This is to remove duplicate bucketing if this occurs in creating the buckets. Also rename a variable to constant form
```
console.log(exponentialBucketsRange(1, 5000 / 1000, 5))
~/audius-protocol master *30 !4 ?6 ❯ node creator-node/src/services/prometheusMonitoring/prometheusUtils.js
[ 1, 1, 2, 3, 5 ]
~/audius-protocol master *30 !4 ?6 ❯ node creator-node/src/services/prometheusMonitoring/prometheusUtils.js
[ 1, 2, 3, 5 ]
```
Check in `/prometheus_metrics` if there are duplicate buckets

Fix bucketing fn + variable name change

---

creator-node/src/components/replicaSet/replicaSetController.js
creator-node/src/services/prometheusMonitoring/prometheus.constants.js
creator-node/src/services/sync/secondarySyncFromPrimary.js
creator-node/test/lib/app.js
creator-node/test/sync.test.js

This PR adds a prometheus metric for `secondarySyncFromPrimary`. 
Example metric below
```
audius_cn_secondary_sync_from_primary_duration_seconds_bucket{le="0.005",result="success"} 0
audius_cn_secondary_sync_from_primary_duration_seconds_bucket{le="0.01",result="success"} 0
audius_cn_secondary_sync_from_primary_duration_seconds_bucket{le="0.025",result="success"} 0
audius_cn_secondary_sync_from_primary_duration_seconds_bucket{le="0.05",result="success"} 0
audius_cn_secondary_sync_from_primary_duration_seconds_bucket{le="0.1",result="success"} 0
audius_cn_secondary_sync_from_primary_duration_seconds_bucket{le="0.25",result="success"} 2
audius_cn_secondary_sync_from_primary_duration_seconds_bucket{le="0.5",result="success"} 2
audius_cn_secondary_sync_from_primary_duration_seconds_bucket{le= …
```

Add prometheus metrics for `secondarySyncFromPrimary`

---

creator-node/compose/env/commonEnv.sh
creator-node/default-config.json
creator-node/src/components/replicaSet/replicaSetController.js
creator-node/src/monitors/stateMachine.js
creator-node/src/serviceRegistry.js
creator-node/src/services/prometheusMonitoring/prometheus.constants.js
creator-node/src/services/stateMachineManager/index.js
creator-node/src/services/stateMachineManager/makeOnCompleteCallback.js
creator-node/src/services/stateMachineManager/processJob.js
creator-node/src/services/stateMachineManager/stateMachineConstants.js
creator-node/src/services/stateMachineManager/stateMachineUtils.js
creator-node/src/services/stateMachineManager/stateMonitoring/findReplicaSetUpdates.jobProcessor.js
creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.js
creator-node/src/services/stateMachineManager/stateMonitoring/index.js
creator-node/src/services/stateMachineManager/stateMonitoring/monitorState.jobProcessor.js
creator-node/src/services/stateMachineManager/stateReconciliation/index.js
creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.js
creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js
creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.js
creator-node/src/snapbackSM/snapbackSM.js
creator-node/test/StateMonitoringManager.test.js
creator-node/test/StateReconciliationManager.test.js
creator-node/test/findReplicaSetUpdates.jobProcessor.test.js
creator-node/test/findSyncRequests.jobProcessor.test.js
creator-node/test/issueSyncRequest.jobProcessor.test.js
creator-node/test/monitorState.jobProcessor.test.js
creator-node/test/processJob.test.js
creator-node/test/snapbackSM.test.js
creator-node/test/updateReplicaSet.jobProcessor.test.js

Bug fixes:
- Fix bug that enqueued a sync with missing some params in an edge retry case
- Fix manual syncs from jobs being enqueued in the reconciliation queue (this was missed when refactoring them to their own queue)
- Fix default-config overriding write quorum timeout to 5s on stage (should be 1m)
Other changes:
- Break apart monitoring and reconciliation queues so that each job type has its own queue and queues don't use named jobs (see Bull issue https://github.com/OptimalBits/bull/issues/1334 regarding named jobs – this is the error message we were having that's now resolved) (also see Linear card https://linear.app/audius/issue/CON-242/break-up-statereconciliationqueue-into-recurringsyncqueue-and)
- Add debug for rare /sync error: `TypeError: Cannot read property 'enqueueSync' of …

State machine - split queues and fix many bugs

---

creator-node/src/services/stateMachineManager/CNodeToSpIdMapManager.js
creator-node/src/services/stateMachineManager/stateMonitoring/fetchCNodeEndpointToSpIdMap.jobProcessor.js
creator-node/src/services/stateMachineManager/stateMonitoring/findReplicaSetUpdates.jobProcessor.js

There's some interesting mismatched spID errors on staging, so this PR is to log state around. This is also to await the job (though this shouldnt impact anything really)
Just logs, no big changes.
See `_findReplicaSetUpdatesForUser` logs

Log cnode to sp id map when determining replica set updates

---

creator-node/src/services/stateMachineManager/stateMachineConstants.js
creator-node/src/services/stateMachineManager/stateMonitoring/findReplicaSetUpdates.jobProcessor.js
creator-node/src/services/stateMachineManager/stateReconciliation/index.js
creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.js
creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js

- Add option to use different # of max retries for manual and recurring syncs and set them both to 2 (previously was 3, but sync queues are getting backed up)
- Make lack of sync request deduplication explicit for manual syncs so we can parallelize those jobs (actually don't think this is necessary for higher concurrency – only for sandboxed workers – but it doesn't hurt in case we want to try sandboxed workers in the future)
- Change manual sync concurrency from 1 back to its config value (default 15)
Create a user and make sure their manual syncs go through. The real testing will need to be on staging to see if the manual and recurring sync queues get less backed up.
Deploy to staging and monitor the number of waiting jobs at the `/health/bull/queue/manual-sync-queue` endpoint.

[CON-294] Make manual sync queue less backed up

---

creator-node/src/services/stateMachineManager/index.js
creator-node/src/services/stateMachineManager/makeOnCompleteCallback.js
creator-node/test/CNodeToSpIdMapManager.test.js

On deploy, the cadence of which bull adds jobs does not change. Therefore, even though the logic is correct, the job wouldnt run immediately on deploy. This was thus causing the class to not have the proper data to perform reconfig and propagating false negatives that there are mismatched spIDs on staging.
This PR is to always init the class on `stateMachineManager` init
Deployed to stage content node 8 with no change in fetch cnode to spID mapping and no more mismatch spIDs occurred following the deploy. 
look for the prefix `_findReplicaSetUpdatesForUser():` and `mismatched spID`log

[CON-281] - Add CNodeToSpIdMapManager init in stateMachineManager init

---

discovery-provider/src/queries/search_es.py

In a `script_score` you have to actually factor in `_score` if you want it to behave like `field_value_factor`
Ran search_quality script thusly:
```
A up
docker exec -it dn1_web-server_1 bash
PYTHONPATH=. python3 scripts/search_quality.py
```
Confirmed results look correct.

Factor _score in to script_score script

---

discovery-provider/Dockerfile

Discovery Provider no longer builds on master due to a bug in our build image. Contrary to popular believe alpine images pull from public (read changing) repos and therefore are not reliable even if you pin the repo.
https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/25614/workflows/db5c4e1a-cba5-4803-9039-4972ed1fb737/jobs/305567
See successful CI build below
NA

Unpin Python to fix discovery build

---

creator-node/Dockerfile
creator-node/src/config.js

Setting the `contentCacheLayerEnabled` flag inside the application means it doesn't get propogated up to the start script where OpenResty gets called to start the process. This means there's no process running on 4000, but the content node runs at 3000 so the Docker container can't run the health check and it thinks the application is unhealthy. Fix is to set contentCacheLayerEnabled in the Dockerfile.
Test on staging on nodes with contentCacheLayerEnabled flag set to true, false and not set
Content node will not come up if this causes an error

Don't set the nginx cache in the application layer

---

.circleci/config.yml

GCP Image bake was broken with this error `ERROR: (gcloud.compute.images.delete) argument IMAGE_NAME [IMAGE_NAME ...]: Must be specified.` https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/25604/workflows/7e7259e2-c830-4107-91b5-96756c1c2ded/jobs/305432
I think this var was just deleted by accident.
Do a full CI run for image bake successfully https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/25663/workflows/22e17fb5-6f39-45dc-8cfe-681482c8a5e6/jobs/306068.
CircleCI nightly image bake will fail

CircleCI GCP image bake env var was undefined

---

discovery-provider/Dockerfile
discovery-provider/requirements.txt

Due to a recent change in alpine repos, the Python version we pull is either not compatible with our requirements.txt or not present.
This PR downgrades Python to 3.9.5 so that we can still use the same version of other python requirements.
This PR also cleans up our Dockerfile and pins the repos so that we only have to pin packages that require to be pinned.
https://discoveryprovider3.staging.audius.co/health_check
NA

Fixes for Discovery Dockerfile following alpine update

---

creator-node/src/AsyncProcessingQueue.js
creator-node/src/services/prometheusMonitoring/prometheusRegistry.ts

Uploads were failing after this PR was merged https://github.com/AudiusProject/audius-protocol/pull/3546
This was the error
```
Error: Missing process handler for job type trackContentUpload
at Queue.processJob (/usr/src/app/node_modules/bull/lib/queue.js:1155:7)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
It's because we added a task name when we do not process tasks by job name. This is to revert named job processes but still maintain prom metrics for queues.
- Created user + uploaded track locally successfully
- Checked /prometheus_metrics route for metrics and appears
```
audius_cn_jobs_duration_milliseconds_bucket{le="1",status="completed",job_name="trackContentUpload",queue_name="asyncProcessing",queue_prefix="bull"} 0 …
```

Fix upload track w prom metrics

---

libs/src/services/wormhole/index.js
service-commands/src/commands/seed/SeedSession.js

The recent hedgehog upgraded included upgraded ethereum dependencies. With that came a new Wallet type that replaced var `_privKey` with `privateKey`. This pr updates usages of _privKey in audius-protocol
Tested wormhole access and service commands
service-commands users will ensure it works

Fix hedgehog privateKey access

---

creator-node/src/config.js
creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js

Seeing excessive number of waiting jobs in manual sync queue on bull. Theory is that since write quorum continues to add jobs every few seconds for up to 5 minutes, if there's ever a backlog on manual sync it accelerates a problem and makes it much, much worse. The two fixes here are:
1. Only issue one manual sync request as part of write quorum (this will be retried up to 2 times)
2. Have a separate write quorum timeout. Since write quorum has a max timeout of 1 min, i set the monitoring time to 45 seconds
- Create a user and upload track to make sure those operations are successful
- Run mad dog on local and CI successfully
- Clear state on stage CN7 and let this soak and make sure manual sync queue waiting numbers are reasonable
Number of jobs in manual sync queue

Dont reissue manual syncs + separate manual sync timeout

---

creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
creator-node/test/updateReplicaSet.jobProcessor.test.js

- Allow nodes that already have state to be selected during reconfigs. Previously, we didn't want to choose nodes that the user previously had state on in, but we can now rely on recurring syncs to reconcile any state differences between nodes that get removed and subsequently added back to a user's replica set.
- On step 5 of the below tests, I noticed that a user's unhealthy primary got set as their secondary during a replica set update. This is because we get healthy nodes from `ServiceProvider.autoSelectCreatorNodes` during the replica set update, so this ignores our previous health checks from the monitoring job. I changed it to bias toward treating a node as unhealthy (i.e., make our previous health checks take precedence over `ServiceProvider.autoSelectCreatorNodes`).
1. Create 2 …

[CON-293] Allow selecting nodes with pre-existing state

---

discovery-provider/Dockerfile

Removes wget and uses curl to handle the OpenResty install
CI Build
NA

Remove wget as a dependency from DP Dockerfile

---

libs/package-lock.json
libs/package.json
libs/rollup.config.js

* Update rollup config to expose esm & cjs bundles for node & browser
* Update type file format to `es`
* Remove file paths from the package.json, basically following solana's lead here: 
https://github.com/solana-labs/solana/blob/master/web3.js/package.json
https://github.com/solana-labs/solana/blob/master/web3.js/rollup.config.js
* Keep legacy export as cjs only, difficulties getting this one to bundle as es but should be ok because it's only for internal use
Tested in main bundle in test app
Tested legacy bundle in audius-client

[C-738] Expose esm bundles for sdk

---

.circleci/config.yml
libs/scripts/release.sh

Pull master before merging our version bump change (to minimize race conditions when someone merges in parallel with the build).
Use the new slack-secrets context that was lost as PRs for INF-209 and INF-210 were separated.
Manually testing releases at the moment.

INF-210 use slack-secrets and better handling of commits coming into master

---

.circleci/config.yml

Properly working `slack-basic` command, instead of `slack/basic` job, since the `slack/` prefix seems to be orb-specific and a command, not a job, was required during the previous attempt.
Manually testing right now.

INF-210 Send pre-deploy messages

---

creator-node/src/services/stateMachineManager/index.js
creator-node/src/services/stateMachineManager/makeOnCompleteCallback.ts

We inject an `enqueuedBy` field into each job's data to track which queue and job ID caused the new job to be enqueued. The queue named being used was incorrect, so this PR fixes that.
I looked at some jobs (e.g., `find-sync-requests-queue`) and verified that their `enqueuedBy` field used the correct queue name (e.g., `monitor-state-queue`).
N/A -- this is for tracking the flow of jobs between queues.

Fix enqueuedBy job data field using wrong queue name

---

creator-node/src/config.js

On production our normal connection timeout is 1 min. Having the write quorum timeout set to 1m can sometimes cause a race and if the metadata polling takes longer than 1 min, there's no connection to send a response back to.
Observed bug on prod content nodes, pushed out a fix and tested directly on prod content node
Upload success rate should stay high

Update write quorum monitoring timeout to less than connection timeout

---

creator-node/src/monitors/MonitoringQueue.js
creator-node/src/routes/healthCheck.js

We occasionally see errors when upgrading content nodes where disk_check shows NaN%. This is because the underlying monitors values are null. This causes two problems
1. We don't properly handle invalid values in disk_check (should not return 200)
2. User actions fail because ensureStorageMiddleware can't access the same values from disk_check so writes get rejected
I've fixed disk_check to handle NaN values and forced the MonitoringQueue to populate storage metrics on init to prevent the user actions from failing
Tested disk_check route by deleting the monitors value in redis and it returns 500
Tested immediate population of monitors upon init by commenting out the recurring process function and only allowing the initialize to run and looked for the logs that it successfully populated …

Handle invalid health check values + seed important monitors on init

---

creator-node/src/config.js

UpdateReplicaSet initialized libs with content node selection with a concurrency of 15, I think that might be too high, lowering to 3 until we optimize that flow.
Tested on prod
Bull queue health dashboard

Concurrency of 15 for updateReplicaSet might be too high for the network

---

.circleci/config.yml
.circleci/triggers/deploy-sdk.py
libs/scripts/release.sh

Followup to a few issues seen when testing SDK releases last Friday.
Changes include:
* customized slack notifications
* cuts down on vertical slack noise
* adds ability to include Slack @mentions in Slack alerts
* track `package.json:audius.releaseSHA` to simplify race conditions on change-log when releasing non-HEAD commits
* uses this tracked git hash to generate change-log
* ensures each commit will appear in at least one change log
Manually release a few versions of the SDK.

INF-210 Collection of fixes to streamline SDK Publishing job

---

creator-node/src/serviceRegistry.js
creator-node/src/services/initAudiusLibs.js
creator-node/src/services/stateMachineManager/stateMachineConstants.ts
creator-node/src/services/stateMachineManager/stateMonitoring/fetchCNodeEndpointToSpIdMap.jobProcessor.ts
creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js
creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
creator-node/src/services/sync/primarySyncFromSecondary.js

When a replica set update is performed, the job processor has to init libs and check which content nodes are healthy. This puts a lot of strain on other nodes, so this PR caches the healthy nodes in Redis for 10 minutes. It also skips other steps of initializing libs when not necessary in the update replica set job processor.
- Brought down and up nodes a few times to make sure it reconfigured properly and set the right values in redis (verified directly via redis-cli)
- Waited 10 minutes to make sure the key expired properly
Look for errors in replica set update jobs. This can be filtered in Loggly to: `json.queue:"update-replica-set-queue"`

Cache healthy nodes in RS update

---

creator-node/src/services/stateMachineManager/stateReconciliation/index.js

We were using the wrong lock duration time for this queue. This PR is to fix that.
No new tests
Monitor existing queue logs. There should not be any big difference in functionality, since it went from 6m -> 5m.

Change the lock duration to correct time

---

libs/scripts/release.sh

Sponge is not included in CircleCI's image by default. Use `mktemp` instead to redirect `jq` output back to the input.json.
Manually testing on `master`.

INF-210 use mktemp instead of sponge

---

creator-node/src/services/stateMachineManager/stateReconciliation/index.js

State machine should be stateless between restarts, and sometimes it can get into a broken state with many jobs in the backlog. This PR makes it clear all jobs for the recurring/manual sync queues and the update-replica-set queue.
Restart and make sure job data from before the restart is cleared.
Make sure nothing looks off on the Bull dashboard.

Clear all reconciliation jobs on restart

---

.circleci/config.yml
libs/scripts/release.sh

A bash script's global `set -e` does not apply to bash functions() when the output is used as part of an `if` or `&&` conditionals.
In order to "reactivate" `set -e`, it's cleaner to launch a subshell within `merge-bump()` and use `set -e` there. Any errors seen within the subshell will be returned correctly to the `&&` conditional.
Additionally, consolidate CircleCi Slack alerts to use less vertical height for Slack mentions.
Manually deploying the SDK off `master`.

INF-210 Use set -e within merge-bump to catch all errors

---

creator-node/src/components/replicaSet/replicaSetController.js

Short-circuit `/sync` requests before they fail with an UncaughtPromiseException, and remove related debugging logs.
Made sure syncs succeed locally (update profile with manual syncs disabled).
Keep an eye on `Sync Queue is not up and running yet` errors. There should be a few around the time nodes restart.

Short circuit when sync queue hasn't initialized

---

libs/scripts/release.sh

`exit 1` is required to have the subshell return the proper exit code to start the cleanup process.
`set -e` within the subshell should have caught this, but the `&&` conditional will continue to hide the exitcode.
With the combination of `exit 1` within the subshell, we ensure we get the an error code without having the `exit 1` escape into the main script and end the script early.
Manually testing releases off master.

INF-210 explicitly catch errors and exit out of subshell

---

creator-node/src/serviceRegistry.js
creator-node/src/services/stateMachineManager/stateReconciliation/SyncRequestDeDuplicator.js
creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js

Put manual syncs back in the de-dupe flow. I had taken it out to pass mad dog due to timing / uniqueness issues but it looks like lots of duplicate syncs are being triggered if not de-duped.
Tested locally by creating user and uploading track and mad dog on CI
manual-sync-queue should stay clear and secondaries should not be getting multiple syncs for the same user at the same time in the logs.

De-dupe manual syncs in state machine

---

eth-contracts/test/audiusToken.test.js
eth-contracts/test/delegateManagerV2.test.js
eth-contracts/test/governance.test.js
eth-contracts/test/staking.test.js

Add test cases verifying patch functionality
Only tests

[C-739] Re-initialize contract test cases

---

service-commands/src/setup.js

Fixes a bug that prevented A up --with-aao from bringing up aao correctly. Missing pair of square brackets caused the running command to spread 'aao' instead of an array containing ['aao', 'up'].
Tested on remote dev machine.

[PAY-494] Fixes bug in A up --with-aao

---

.circleci/config.yml
libs/scripts/release.sh

Rename publish-libs job to publish-sdk.
Additionally, cleanup info echo and remove unneeded `set -e` code which is unused due to the calling function being used as part of a conditional.
Manually run a release on `master`.

INF-210 Rename publish-libs job to publish-sdk

---

libs/src/services/creatorNode/CreatorNode.ts

Fix runtime includes TypeError

---

docs/docs/developers/log-in-with-audius.md
docs/docs/developers/sdk-oauth-methods.md
docs/docs/developers/sdk/index.md
docs/i18n/en/docusaurus-plugin-content-docs/current/api/log-in-with-audius.md
docs/i18n/en/docusaurus-plugin-content-docs/current/api/sdk-oauth-methods.md
docs/i18n/en/docusaurus-plugin-content-docs/current/api/sdk/index.md
docs/i18n/en/docusaurus-plugin-content-docs/current/developers/log-in-with-audius.md
docs/i18n/en/docusaurus-plugin-content-docs/current/developers/sdk-oauth-methods.md
docs/i18n/en/docusaurus-plugin-content-docs/current/developers/sdk/index.md
docs/i18n/en/docusaurus-plugin-content-docs/current/developers/sdk/index.mdx

https://github.com/AudiusProject/docs.audius.org/pull/21/files
Since the repo moved over here, re-opening this change!
Should be merged after https://github.com/AudiusProject/audius-client/pull/1557 is released

Land #21 from docs.audius.org

---

creator-node/src/services/stateMachineManager/stateMachineConstants.ts
creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
creator-node/src/services/stateMachineManager/stateReconciliation/types.ts

- The order that we spread by was overriding `attemptNumber` to never increment when retrying syncs, so this PR fixes that
- Histories of some queues have been higher without any negative impact (and Redis memory having lots of wiggle room still), so this PR also bumps those histories to allow us to view more completed/failed jobs.
Make sure mad dog passes and verify fewer retries on staging.
Monitor manual sync queue volume on staging.

Fix attemptNumber not getting updated

---

creator-node/src/components/replicaSet/replicaSetController.js
creator-node/src/components/replicaSet/syncQueueComponentService.js
creator-node/src/config.js
creator-node/src/serviceRegistry.js
creator-node/src/services/sync/syncImmediateQueue.js

New SyncImmediateQueue to run all immediate syncs through a bull queue synchronously. Benefits are that we can cap manual sync concurrency and run it through bull instead of calling the secondarySyncFromPrimary directly like [this](https://github.com/AudiusProject/audius-protocol/blob/master/creator-node/src/components/replicaSet/replicaSetController.js#L98).
Tested locally with user signups and mad dog on CI
Bull dashboard under sync-immediate-processing-queue

New queue for immediate sync

---

creator-node/nginx_conf/nginx.conf

Cache 200-status /health_check responses from CN in nginx for 1second
1sec is minimum allowable time in nginx (see open ticket - https://trac.nginx.org/nginx/ticket/1505)
< 1sec would be better probably, but I think 1sec is acceptable - worth consideration tho
Tested manually (see below for HIT and EXPIRED responses)
Existing CN + maddog tests sufficient for regression coverage
Grafana dashboard for CN health check metrics - http://grafana.audius.co/d/q7ZzPaR4k/vickys-dashboard?orgId=1&var-environment=prod&var-host=All&var-path=%2Fhealth_check&var-status_code=All&var-method=GET
Also observe `nginx` logs per this doc - https://www.notion.so/audiusproject/How-to-debug-nginx-cache-layer-e2097937dc0e4a0fae5583054ed417d0

CON-303 Cache CN 200-status /health_check responses for 1sec in nginx

---

creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
creator-node/src/services/sync/secondarySyncFromPrimary.js
creator-node/test/sync.test.js

Remove labels that aren't used in the `audius_cn_secondary_sync_from_primary_duration_seconds_bucket` Prometheus metric. These extraneous labels are confusing when using `prometheus.constants` as a reference for creating Grafana panels.
Make sure mad dog and tests pass -- this was just a cosmetic change.
Look for errors that start with `secondarySyncFromPrimary` or containing `is not included in initial labelset`.

Remove unused labels

---

discovery-provider/src/queries/notifications.py

Fix add track to playlist notification. Currently, the notification timestamp uses the playlist creation date so notification ordering is inaccurate. The new behavior uses the timestamp that the track was added to the playlist. 
Tested on staging.
Check for notification.

Fix add track to playlist notification timestamp

---

libs/scripts/release.sh

Fix tricky logic around using `||`, `set -e`, and `function ||` together.
Now echo what is being checked and simply `exit 1` if the check fails.
Manually deploying on `master`.

INF-210 fix || exit 1 logic

---

creator-node/src/services/sync/secondarySyncFromPrimary.js
creator-node/src/services/sync/syncImmediateQueue.js
creator-node/src/services/sync/syncQueue.js

- Removes the extra `done()` from the sync processing queue to make our pattern consistent with other job processors. We should only use an async function or a `done()` callback in a job processor, but not both since this can potentially cause issues (the Bull dev flagged this previously).
- Adds `result` field to sync processing queue for debugging purposes
- Adds bull option to not reprocess stalled jobs for sync and sync-immediate queues
Make sure mad dog passes.
Monitor logs for `secondarySyncFromPrimary failure for wallets` errors.

Remove extra done() callback

---

libs/scripts/release.sh

VERSION needs to be grabbed again since we now wrap bump-npm() within a subshell for better error detection.
Manually deploy from `master`.

INF-210 grab VERSION after exiting subshell that bumped version

---

libs/rollup.config.js

* Removes the cjs core bundle and only exposes the es one
* Fixes a typo where the cjs browser bundle was actually esm

Fix core libs bundle so it can be consumed in client

---

.circleci/config.yml
.circleci/triggers/__init__.py
.circleci/triggers/deploy-sdk.py
libs/scripts/release.sh

As per @dylanjeffers 's suggestion to not overload the git term "tag".
Updated Notion docs to reflect change as well.
Manually deploying sdk on `master`.

INF-210 rename GIT_TAG to GIT_COMMIT

---

creator-node/src/index.ts
creator-node/src/migrationManager.js

Clear running db migrations on content node server init.
Used psql to print running queries, restarted the server to run the clearRunningQueries() function and confirmed that the previously running queries are no longer running.
Use psql or navicat to check the running queries on a db after init, should be empty

Clear running migrations on server start

---

libs/scripts/release.sh

Because we're making use of a subshell for better error handling, we need to define $CHANGE_LOG outside of a subshell so it propagates to multiple subshells.
Manually releasing off `master`.

INF-210 include change log in commit and tag

---

libs/rollup.config.js
libs/src/AudiusLibs.ts
libs/src/NativeAudiusLibs.ts
libs/src/index.ts
libs/src/legacy.ts
libs/src/services/creatorNode/CreatorNode.ts
libs/src/services/creatorNode/CreatorNodeSelection.ts
libs/src/services/discoveryProvider/DiscoveryProvider.ts
libs/src/services/discoveryProvider/DiscoveryProviderSelection.ts
libs/src/services/types.ts

- Fixes legacy and sdk types (legacy was untyped since it was being reffed by src/index.ts)
- Consolidates monitoringCallback types across libs
- Exports Utils and SanityChecks in native build, and also adds configure stubs

Fix legacy and sdk types, monitoringCallbacks, native exports

---

.circleci/config.yml

Add alerts to #eng-deploys-announcements when a GCP job fails.
Monitor #eng-deploys-announcement.

INF add alerts for failed gcp bake jobs

---

discovery-provider/integration_tests/queries/test_get_tracks.py
discovery-provider/integration_tests/queries/test_get_user_listening_history.py
discovery-provider/src/api/v1/helpers.py
discovery-provider/src/api/v1/users.py
discovery-provider/src/queries/get_save_tracks.py
discovery-provider/src/queries/get_tracks.py
discovery-provider/src/queries/get_trending_tracks.py
discovery-provider/src/queries/get_user_listening_history.py
discovery-provider/src/queries/query_helpers.py
libs/src/sdk/api/generated/default/apis/UsersApi.ts
libs/src/sdk/api/generated/full/apis/UsersApi.ts

Support simple filter on history/faves/tracks for respective table views in client.
The next step is sorters, which is a bit more complex because we don't join with users up front. We should actually change this though -- it should be all in one join RT to the db. This should be possible, but needs a tiny bit of reworking. After this step, we can make the ilike queries here to include artist name, which would be nice. Eventually gql/ES is the way to go here though.
--> EDIT: Part of this was added to this PR b/c we already have the relationship @rickyrombo  added :)
And the third step will be to add total count via the `X-Total-Count` which will be a perf hit b/c that would be a count(*) in addition to the queries. Possibly we don't want that for everything, but it's necessary at least on …

[C-749] Support req pagination and ordering in hist/fav/tracks

---

creator-node/src/services/prometheusMonitoring/prometheusRegistry.ts
creator-node/test/lib/genericBullQueueMock.js
creator-node/test/prometheus.test.js

This PR fixes a metric name mismatch and changes the name of the metric names from
`JOBS_DURATION_MILLISECONDS_HISTOGRAM` => `JOBS_DURATION_SECONDS_HISTOGRAM`
`JOBS_WAITING_DURATION_MILLISECONDS_HISTOGRAM` => `JOBS_WAITING_DURATION_SECONDS_HISTOGRAM`
the new prometheus metrics should look like this when deployed
```
audius_cn_jobs_duration_seconds_bucket{le="1",status="completed",job_name="__default__",queue_name="monitor-state-queue"} 0
audius_cn_jobs_duration_seconds_bucket{le="2",status="completed",job_name="__default__",queue_name="monitor-state-queue"} 0
audius_cn_jobs_duration_seconds_bucket{le="4",status="completed",job_name="__default__",queue_name="monitor-state-queue"} 0
audius_cn_jobs_duration_seconds_bucket{le="8",status="completed",job_name="__default__",queue_name="monitor-st …
```

Fix Prometheus Metric Names for Bull Queue Durations

---

discovery-provider/alembic/versions/3403e008e6c7_repair_missing_wallets.py

Repairs missing wallets due to is_creator bug.
Ran against a production snapshot and re-ran queries to see if all users were fixed, and they were.

Repair missing wallets

---

creator-node/nginx_conf/nginx.conf
creator-node/src/config.js
creator-node/src/utils.js

Two optimizations
1. Ability to turn `findCIDInNetwork` off via env var
2. Add regex support for verbose health check in openresty
Both of these have been tested on production.
For openresty tail access logs by running `tail -f /usr/local/openresty/logs/access.log`

Change openresty location directive from exact match to regex

---

.circleci/config.yml

Expose the `slack-secrets` secrets for the GCP bake job.
Monitor the nightly run.

Add slack-secrets to jobs that use Slack notifications

---

creator-node/src/services/stateMachineManager/makeOnCompleteCallback.ts
creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.ts

- Add default value for each secondary in the userSecondarySyncMetrics mapping to fix an error thrown for destructuring from undefined. We previously had a default for the entire mapping, but that didn't cover the case where the wallet had metrics for only one secondary
- The line where this error was thrown was in findSyncRequests.jobProcessor.ts: `const { successRate, failureCount } = userSecondarySyncMetricsMap[secondary];`
- Add filter for queue name to onComplete logs – combing the logs to verify the cause of this error has been a little more time consuming without this filter
Unit tests pass and jobs in the find-sync-requests-queue complete successfully locally after seeding users.
Search for the following error: `"TypeError: Cannot destructure property 'successRate' of …

Fix TypeError for userSecondarySyncMetrics

---

creator-node/src/services/stateMachineManager/stateMachineConstants.ts
creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts

lots of `Not enough healthy nodes found to issue new replica set after 5 attempts` errors goin on in staging. took a lewk at that and it's cus our attempt count is so low and there might be some redunant selection here
The existing tests suite should cover this change as there is no main functionality change, just an optimization.
The existing logs will suffice

Bump random replica select attempt count + filter out existing nodes from healthy replica set

---

creator-node/src/routes/audiusUsers.js
creator-node/src/routes/tracks.js
creator-node/test/audiusUsers.test.js
creator-node/test/contentBlacklist.test.js
creator-node/test/dbManager.test.js
creator-node/test/pollingTracks.test.js
creator-node/test/sync.test.js

- The following error is caused by load test on staging, so it doesn't impact prod (verify lack of prod impact by searching the following in loggly with and without the audius-stage/prod tag: `"SequelizeUniqueConstraintError" tag:"audius-prod" -"Queue.onFailed" -"secondarySyncFromPrimary failure for wallets" "Tracks_unique"`): `[SequelizeUniqueConstraintError] blockchainId must be unique`
- `blockchainId` is a smart-contract generated global track ID that is supposed to be unique
- Likely something with the load test uploading multiple tracks at the same time caused it to make Content Node's `/tracks` endpoint associate the same track ID with multiple uploads
- The solution to prevent this broken state from being created in the future is to make Content Node's `/tracks` endpoint verify …

[CON-222] Fix SequelizeUniqueConstraintError for blockchain track ID

---

.circleci/config.yml
creator-node/Dockerfile
discovery-provider/Dockerfile
logspout/Dockerfile
logspout/README.md
logspout/start.sh

Add a flag to disable sending logs through logspout.
There's 4 cases that should all work, but we should probably disable the single docker container transport and only do it through logspout sidecar
Logs enabled
- via docker-compose by default
- via single docker container by default (enableRsyslog defaulted to true)
Logs disabled
- via docker-compose with (audius_logging_disabled set to true)
- via single docker container with (audius_logging_disabled set to true)
Tested this on a new docker compose discovery node with audius_logging_disabled both set and unset.
This PR needs to be merged before https://github.com/AudiusProject/audius-docker-compose/pull/50 is merged because of the tag dependency
Logs should be appearing in Loggly for nodes with logging enabled.

Add disable flag to logspout

---

creator-node/src/services/stateMachineManager/stateMachineConstants.ts
creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
creator-node/test/updateReplicaSet.jobProcessor.test.js

There were unnecessary reconfig events being made. To prevent this from happening, we have to pass in the old replica set and call the fn that requires passing in the old replica set.
1. Created user
2. Uploaded 2 tracks
3. Checked existing replica set
4. Stopped a secondary
5. Waited to see if user got rolled onto another secondary
6. Confirmed that one of user's replica set nodes successfully rolled onto another secondary
```
{"name":"audius_creator_node","hostname":"baf7882f9f52","pid":26576,"queue":"update-replica-set-queue","jobId":"2","level":30,"msg":"[_issueUpdateReplicaSetOp] Reconfig SUCCESS: userId=2 wallet=0x3ce45ff75ed2e9e8439dbc57e835bc37bcedd0a2 old replica set=[http://cn2_creator-node_1:4001,http://cn3_creator-node_1:4002,http://cn4_creator-node_1:4003] | new replica …
```

Prevent extra unnecessary reconfig events

---

identity-service/src/notifications/index.js

Filter out notifs from initiators deemed abusive as soon as we get the notifs from DN, for both poa and sol notifs.
Manual
Added logs for number of bad initiators filtered out.

Filter out notifications from bad initiators

---

identity-service/sequelize/migrations/20220809211742-add_supporter_dethroned.js
identity-service/src/featureFlag.js
identity-service/src/notifications/constants.js
identity-service/src/notifications/fetchNotificationMetadata.js
identity-service/src/notifications/formatNotificationMetadata.js
identity-service/src/notifications/processNotifications/supporterRankChangeNotification.js
identity-service/src/notifications/sendNotifications/formatNotification.js
identity-service/src/notifications/sendNotifications/index.js
identity-service/src/notifications/sendNotifications/publishNotifications.js
identity-service/src/routes/notifications.js

- Adds dethroned notification if you lose your top supporter spot
- I'm including the old + new tip amounts in the notification object even though we're not currently using this in the UI/push notif copy, just because they're easily accessible and I wouldn't be surprised if we end up wanting to surface them later on
- Tested locally; push notifications are created and dethroned notifs appear in notifs route

[PAY-459] Add dethroned notifications on Identity

---

identity-service/src/notifications/index.js

Filter out bad notifs from initiators and bad user entities.
Has log.

Fix bad notifs

---

discovery-provider/src/queries/get_feed_es.py

save_count was renamed to favorite_count when working on search but /feed still expects save_count.
Confirmed client showed save count correctly when pointed at a sandbox env.

populate save_count in feed endpoint

---

creator-node/src/components/healthCheck/healthCheckComponentService.js
creator-node/src/components/healthCheck/healthCheckComponentService.test.js
creator-node/src/config.js
creator-node/src/serviceRegistry.js
creator-node/src/services/stateMachineManager/index.js
creator-node/src/services/stateMachineManager/stateMachineConstants.ts
creator-node/src/services/stateMachineManager/stateMonitoring/index.js
creator-node/src/services/stateMachineManager/stateReconciliation/index.js
creator-node/src/services/stateMachineManager/stateReconciliation/recoverOrphanedData.jobProcessor.ts
creator-node/src/services/stateMachineManager/stateReconciliation/types.ts
creator-node/test/StateReconciliationManager.test.js
creator-node/test/recoverOrphanedData.jobProcessor.test.js

- Add queue to process jobs for a node to find+reconcile data that's on it but that belongs to a user who doesn't have the node in their replica set
- Add TODOs for steps of the job (ready to high level review but not implementation details or else this PR would balloon)
- Updated tests for StateReconciliationQueue and added skeleton for future tests to be completed once the job processor is implemented
- Verified that the queue runs locally at the correct rate limit (1 job per minute)
- Search for the queue's logs that will be added in a followup PR (filter by `json.queue:"recover-orphaned-data-queue"`)
- Monitor the queue's Bull dashboard (`/health/bull/queue/recover-orphaned-data-queue` endpoint)

[CON-324] Add orphaned data recovery queue

---

creator-node/src/components/replicaSet/URSMRegistrationComponentService.js
creator-node/src/services/stateMachineManager/CNodeHealthManager.js
creator-node/src/snapbackSM/peerSetManager.js
libs/src/api/ServiceProvider.ts
libs/src/services/creatorNode/CreatorNodeSelection.ts
libs/src/utils/network.ts

In order to better debug bursts of health_check requests between content nodes and from libs, this PR adds identifying 'User-Agent' headers to all axios requests.
Tested locally and observed that headers get displayed in the logs
```
/usr/src/app # tail -f /usr/local/openresty/logs/access.log | grep "verbose"
172.22.0.17 - - [12/Aug/2022:19:42:21 +0000] "GET /health_check/verbose HTTP/1.1" 200 x-cache-status=EXPIRED 2959 "-" "Axios - called in CNodeHealthManager#queryVerboseHealthCheck by http://cn2_creator-node_1:4001" "-"
172.22.0.14 - - [12/Aug/2022:19:42:21 +0000] "GET /health_check/verbose HTTP/1.1" 200 x-cache-status=HIT 2955 "-" "Axios - called in CNodeHealthManager#queryVerboseHealthCheck by http://cn1_creator-node_1:4000" "-"
172.22.0.23 - - [12/Aug/2022:19:42:21 +0000] "GET …
```

Add custom headers to all axios calls to health check in content node

---

discovery-provider/integration_tests/queries/test_get_user_listening_history.py
discovery-provider/src/api/v1/helpers.py
discovery-provider/src/api/v1/users.py
discovery-provider/src/models/tracks/track_with_aggregates.py
discovery-provider/src/queries/get_save_tracks.py
discovery-provider/src/queries/get_tracks.py
discovery-provider/src/queries/get_user_listening_history.py
discovery-provider/src/queries/query_helpers.py
libs/src/sdk/api/generated/default/apis/UsersApi.ts
libs/src/sdk/api/generated/full/apis/UsersApi.ts
service-commands/src/setup.js

Add sorters to endpoints via a string enum w/ "choices."
This hits all of the sorting desires except track length, which is an unindexed field (but we should make it one in future).
New unit test for history, tested also manually requesting each endpoint and setting the sorters
Existing history, favorites, profile, artist dashboard pages
Will confirm new tables work with req. pagination as expected

[C-785] Add request sorters to hist/fav/tracks

---

identity-service/src/featureFlag.js
identity-service/src/notifications/sendNotifications/publishNotifications.js

- Adds a new feature flag specifically for dethroned push notifs, so we can turn dethroned push notifs on in-app on prod without turning on push notifs system wide
None

Add new feature flag for Dethroned push notifs

---

creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts

Log stack traces for update-replica-set job errors to narrow down which network call is resulting in a 502. Currently we just print the error message and are unaware of which inner step actually causes the error.
N/A - just logs. Make sure integration tests pass.
Search for the error `Error initting libs and auto-selecting creator nodes` and look for the new stack trace in `ERROR issuing update replica set op` logs

Log stack traces of update-replica-set errors

---

service-commands/src/setup.js

Enable ELK sidecars to provide ELK-backed logging for all remote-dev boxes.
Additionally, enable Prometheus/Grafana-related sidecars to collect metrics during local development.
Spin up new machine on this branch and run `A up` successfully.
Looking at ELK for new hostnames.

INF-201 Enable local ELK and Grafana-related Sidecars by default for remote-dev

---

creator-node/src/middlewares.js
creator-node/src/services/stateMachineManager/ContentNodeInfoManager.js
creator-node/src/services/sync/primarySyncFromSecondary.js
creator-node/src/services/sync/secondarySyncFromPrimary.js
creator-node/src/utils/decisionTree.ts
creator-node/test/sync/assets/export.json
creator-node/test/sync/assets/realExport.json

Main change here is to add decision tree logging to `primarySyncFromSecondary()`
Also:
- new `utils/decisionTree.ts` module - other decision tree code should eventually be moved over to use this
- rename `getCreatorNodeEndpoints` to `getUserReplicaSetEndpointsFromDiscovery` for clarity
- better error handling for when `primarySyncFromSecondary()` calls `export` and gets no response back
No new functionality, existing tests sufficient
Logs containing `"primarySyncFromSecondary" AND "DecisionTree"`

PrimarySyncFromSecondary() improvements to error handling and logging

---

libs/src/api/entityManager.ts
libs/src/services/web3Manager/Web3Config.ts

Fixes a bug when creating a playlist from an existing track. The image CID already exists so I think we should pass that here. Also adding `entityManagerAddress` to the `Web3Config` type.
Client fix https://github.com/AudiusProject/audius-client/pull/1674/commits/d49d38c0e7cb019d0e34a24671124dfef8858fe9.
Tested against stage.
Check for this playlist creation flow.

Pass cover art when creating a playlist from existing track

---

discovery-provider/src/queries/get_tracks.py

Typo introduced in https://github.com/AudiusProject/audius-protocol/commit/07cf9afca0e0b4a00a6ca977a4e3b2225caa1fd2#diff-e4994c134924a93a214a450637f405270eb4c266df07cb48caa2acb34577eca2
Breaks a few routes that rely on get_tracks.
Tested against local stack
Probers

Fix get_tracks typo

---

discovery-provider/src/api/v1/helpers.py
discovery-provider/src/api/v1/models/tracks.py
libs/src/sdk/api/generated/default/models/Track.ts
libs/src/sdk/api/generated/full/models/TrackFull.ts

Add `is_streamable` to api surface
Checks against is_delete and user's is_deactivated - ref: https://github.com/AudiusProject/audius-protocol/blob/5d719204e9c7c751789730cfe34fe61e6f2a3a2c/discovery-provider/src/api/v1/tracks.py#L384
Fixes PLAT-290
ran locally against staging db

Add is_streamable to api surface

---

discovery-provider/integration_tests/tasks/test_entity_manager.py
discovery-provider/src/tasks/entity_manager/entity_manager.py
discovery-provider/src/tasks/entity_manager/playlist.py

* Swallow errors when processing entity manager tx. Adjust validation to throw exception with message.
* Add last_added_to field which was missing before.
Adjusted integration tests.
Check new logs and confirm valid txs are indexed.

Skip entity manager txs that fail to process

---

discovery-provider/src/tasks/entity_manager/playlist.py

Add first-playlist challenge to entity manager playlists
Ran locally and confirmed playlist challenge record was created in user_challenges table.
Same as test.

Add first playlist challenge to entity manager

---

creator-node/src/fileManager.js
creator-node/src/services/sync/primarySyncFromSecondary.js
creator-node/src/utils/decisionTree.ts

`decisionTree.fullDuration` calculation bug
`decisionTree.recordState` typo
`saveFileForMultihashToFS()` - improve decisionTree logging
N/A
Logs containing `DecisionTree`

CN - Minor decision tree logging fixes

---

creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
creator-node/src/services/sync/secondarySyncFromPrimary.js

- When a sync request was processed on a secondary and clock values already matched, it `continue`d.
- This prevented it from returning a `result` value, which is expected elsewhere.
- This PR makes the sync return a new `success_clocks_already_match` value for the `result` metric label
NOTE: The diff is hard to review because there was a for loop that only ever had one iteration after removing this `continue`. Reviewing commit-by-commit is much easier to follow so that you can skip reviewing the giant linting of the for loop.
Integration tests pass.
- Add the new label value (`success_clocks_already_match`) to Grafana panels that expect successes, and make sure it has some values.
- Make sure there are no more errors like `Cannot destructure property 'error' of '(intermediate value)' as …

Fix not returning result when secondarySyncFromPrimary sync is not required

---

libs/src/api/Track.ts
libs/src/api/entityManager.ts
libs/src/services/dataContracts/EntityManagerClient.ts
libs/src/utils/utils.ts

Adds the boolean `useEntityManager` to the libs Tracks service so that the new contract will conditionally be used based on this boolean.
Note, this updates the method parameters:
`uploadTrack`: Updates arguments to be object detructed
`updateTrack`: Updates arguments to add a second param for the boolean 
`deleteTrack`: Updates arguments to add a second param for the boolean 
Ran locally against linked like with and without the boolean set

Track entity manager

---

libs/src/services/solana/SolanaWeb3Manager.ts

Adds backend function to enable checking SOL balance of a wallet address to be used before sending WAudio to an external wallet.

[PAY-579] Checks associated account or SOL before transfer

---

libs/src/api/Track.ts

undoes change for upload track params in https://github.com/AudiusProject/audius-protocol/pull/3706/files#diff-866586d98c7a27e7761e288ddb9c9863059b8d5737899cfd21ffd494ef63148a
It broke the maddog tests

revert track entity upload

---

discovery-provider/integration_tests/tasks/test_entity_manager.py
discovery-provider/src/tasks/entity_manager/entity_manager.py
discovery-provider/src/tasks/entity_manager/playlist.py

Currently if you update an empty new playlist, no update is made and the existing playlist is marked is_current = False.
* Fix last_added_to is None bug.
* Fix invalidating of old playlists. If entity_manager skips an invalid tx, it needs to ensure at least the existing playlist or last playlist update is marked as current.
Exception is logged if an update fails to process.

Fix playlist entity manager invalid tx logic and last_added_to

---

discovery-provider/src/tasks/entity_manager/entity_manager.py

Invalidate existing playlist only if there's an updated record. The change below removed the invalidating for the existing playlist and assumed the existing_playlist would be in new_records. This adds a lookup of the existing record and updates it.
https://github.com/AudiusProject/audius-protocol/pull/3755

Fix entity manager playlist invalidation

---

creator-node/tsconfig.build.json

A recent tsconfig change was trying to include only index.ts and let it resolve imports recursively from there. However, inspection of the build output revealed it was only including the index file. This PR makes sure it includes all src files while excluding test files (before the previous change we just included the entire src folder with unit tests as well).
- `npm run build` and verify that instead of just having `index.js`, it has all src files but no test files.
- `node build/src/index.js` and verify it starts up correctly instead of showing the previous error
Previous error was:
```bash
Error: Cannot find module './tracer'
Require stack:
- /usr/src/app/build/src/index.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
at Function.Module._load …
```

Make Content Node tsconfig include all src files

---

creator-node/src/services/stateMachineManager/stateMachineConstants.ts
creator-node/src/services/stateMachineManager/stateMonitoring/findReplicaSetUpdates.jobProcessor.ts
creator-node/src/services/stateMachineManager/stateMonitoring/monitorState.jobProcessor.ts

- Skip enqueuing replica set updates in the edge case where a user with a very old client has no replica set on UserReplicaSetManager. This bug will resolve itself via sanity checks the next time the user logs in with a newer client
- This didn't seem worth an entirely new metric since it happens in find-replica-set-updates rather than issue-replica-set-update (so we can't just add a label to an existing metric). We can get an idea of the frequency of these errors by searching logs for `"has null SP IDs for their entire replica set"`
- Log unhealthy peers in the `retrieveUserInfoFromReplicaSet` step of monitor-state job
- Log scenarios in findReplicaSetUpdates where a node is marked unhealthy (having this log would've saved a lot of time during investigation of this bug)
Tests pass. The …

[CON-363] Skip replica set updates for users w/o URSM data

---

creator-node/src/services/sync/syncImmediateQueue.js
creator-node/src/services/sync/syncQueue.js

Fixes bug I introduced in https://github.com/AudiusProject/audius-protocol/commit/e74f72b0955bb9e56c803d70e8fed18ec2c30a8d
Bug caused all syncs to be recorded as failed (even though they succeeded
Larger point - we need to standardize usage of `Date.now()` vs `process.hrtime()` (the latter is preferred i think), and also desperately need typing
Tested on staging already
Check `/health/bull` failed jobs for queues `sync-processing-queue` and `sync-immediate-processing-queue` - Should not see any instances of errors
```
TypeError [ERR_INVALID_ARG_TYPE]: The "time" argument must be an instance of Array. Received type number (1661458777108)
```

CON-368 Fix sync duration logging bug

---

creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts

Fix a bug in DSR+orphaned data recovery flow: libs wasn't told to init ethContracts, which it needed for creator node selection. This was added/broken as part of new sync guardrails to ensure we don't sync between the wrong nodes based on sync mode.
I manually verified that hitting the `/merge_primary_and_secondary` endpoint stopped causing the following error: `Cannot read property 'getCurrentVersion' of null`.
Verify that there are no occurrences of `Cannot read property 'getCurrentVersion' of null` errors.

Fix issueSyncRequest libs not having ethContracts

---

creator-node/src/components/healthCheck/healthCheckController.js
creator-node/src/services/prometheusMonitoring/prometheus.constants.ts

Add a storage size metric in Prometheus. This will allow us to graph % utilized disk across all content nodes and find out how much storage capacity we've used network wide.
Tested locally and verified that metric shows up correctly in prometheus_metrics endpoint
Will add a grafana panel and alert on stage/prod

Add storage path size prometheus gauge

---

creator-node/src/services/prometheusMonitoring/prometheus.constants.ts
creator-node/src/services/stateMachineManager/stateMachineConstants.ts
creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
creator-node/src/services/stateMachineManager/stateReconciliation/recoverOrphanedData.jobProcessor.ts
creator-node/src/services/sync/secondarySyncFromPrimary.js
creator-node/test/recoverOrphanedData.jobProcessor.test.ts

- Fixed `Error: Metric label has invalid value: 'failure_orphan_not_wiped'` - caused by label value missing from prometheus.constants, so the fix was just to add the label to the array of expected values
- Resolved issueSyncRequest job processor thinking orphan node failing to wipe when it did in fact wipe by fixing a clock value check condition in `additionalSyncIsRequired()`
- Batch size was too high – lowered from 10k to 2k (2k users is about 0.5MB, so we shouldn't fetch more than this at once)
- Added a delay between batches of requests to /merge_primary_and_secondary routes. There are >100K users with orphaned data on staging, so to avoid spamming our nodes we now wait 1 second after every 50 requests (effectively rate limiting to 50 requests per second)
- Note that these requests …

Make orphaned data fixes + improvements

---

creator-node/src/services/stateMachineManager/stateReconciliation/recoverOrphanedData.jobProcessor.ts

Adds basic logs to get an idea of what an orphaned data recovery job is doing while the Bull dashboard just says it's active.
None - just logs
Monitor logs from the job by filtering: `json.queue:"recover-orphaned-data-queue"`

Add logs to orphaned data recovery job

---

creator-node/src/config.js
creator-node/src/services/stateMachineManager/stateMachineConstants.ts
creator-node/src/services/stateMachineManager/stateReconciliation/recoverOrphanedData.jobProcessor.ts

Tweaks settings to:
- make recover-orphaned-data jobs stop themselves after issuing requests for 2 hours
- lower rate limiter to 2 hours (this can be increased back to 1 day after rollout since the work is front loaded with a high number of initial orphaned users and very few after that)
- make jobs stall after 3 hours
Will resume testing on staging
Monitor for the log `Gracefully ending job after`. The Bull dashboard should also show jobs completing successfully after ~2 hours with a lower number of syncs issued than number of orphaned users found.

Gracefully stop recover-orphaned-data jobs

---

discovery-provider/integration_tests/tasks/test_entity_manager.py
discovery-provider/src/tasks/entity_manager/playlist.py

last_added_to field needs a date not int for uploading collections.
Added tests around uploading collections.
Indexing stalls without this change when uploading collection.

Fix last_added_to field for uploaded collections

---

creator-node/src/services/stateMachineManager/stateReconciliation/recoverOrphanedData.jobProcessor.ts
creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts

- Fixes tiny bug where query used >= instead of > (no actual impact since values get deduped when adding to a Set, but this is technically correct)
- Adds stack trace to reconfig error logs so we can narrow down the source of error 500s that happen in a relatively large try-catch
Tests pass. We'll monitor the 500 errors on prod.
Look for the stack trace in 500 errors on prod. Search: `"Reconfig ERROR" "status code 500"`

Fix orphaned data gte and log stack for reconfig 500s

---

discovery-provider/src/utils/helpers.py

`model_to_dictionary` attempted to skip unloaded relationships... but would access the property _before_ skipping... causing a n+1 query situation.
Verified fewer queries with sqlalchemy logger turned on.

fix n+1 query bug in model_to_dictionary

---

creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
creator-node/test/updateReplicaSet.jobProcessor.test.js

- Fixes a rare scenario where both of a user's secondaries got deregistered and the user's `creator_node_endpoint` has only a primary and a deregistered secondary (but no other secondary)
- When this happens, the reconfig fails to replace the secondary that was an empty string, so it likely gets rejected on chain (or something that results in a 500 error)
- Search `tag:"audius-prod-creator-1" json.jobId:"1547" json.queue:"update-replica-set-queue"` in the logs to see an example. This is the user from this example: https://discoveryprovider2.audius.co/users?wallet=0x5a591630747ceeac9b6f917e44074b2c3af905db 
- The fix is to ensure that every reconfig replaces empty nodes and throws early if the new replica set is incomplete
- Added a new test for this scenario and slightly increased general …

Fix incomplete replica set for deregistered node

---

creator-node/src/config.js

Changes `snapbackHighestReconfigMode` env var to `ONE_SECONDARY` so Service Providers can start issuing reconfigs.
Will monitor -- tests pass
Watch the Grafana reconfig panel to make sure reconfigs are happening successfully.

Enable reconfigs for one secondary by default

---

discovery-provider/src/tasks/social_features.py
discovery-provider/src/tasks/user_library.py

Temporarily remove track repost and save prevention for premium tracks. Allows mad dog to pass. The correct version of this feature will be re-included in an upcoming PR.
Ran mad-dog tests locally and they passed. Tests should also pass in CI runs.

Temporarily remove track repost and save prevention for premium tracks

---

creator-node/src/services/stateMachineManager/stateMachineConstants.ts
creator-node/src/services/stateMachineManager/stateReconciliation/recoverOrphanedData.jobProcessor.ts
creator-node/test/recoverOrphanedData.jobProcessor.test.ts

- Lowers the number of syncs that orphaned data recovery enqueues from 50 reqs/sec to 2 reqs/min
- Staging is currently getting backed up at 50 reqs/sec (80,000+ jobs waiting in recurring sync queues)
- 2 requests issued really means 6 recurring syncs because each /merge_primary_and_secondary hit enqueues 1 MergePrimaryThenWipeSecondary sync, which enqueues 2 SecondaryFromPrimary syncs
- 6 recurring syncs per minute is reasonable because of some quick maths:
- The p50 for the job that processes a recurring sync is usually around 20 seconds. Let's use 30 seconds to be safe
- So that means 2 syncs per minute. The concurrency for processing these jobs is 5, so each node can handle 5 * 2 = 10 syncs per minute
- If each node issues 6 syncs per minute, then that leaves 4 per minute for state …

Lower orphaned data recovery sync reqs/sec

---

creator-node/src/services/sync/primarySyncFromSecondary.js
creator-node/src/services/sync/syncUtil.ts

Problem: nodes currently have an export bug where they will not indicate in the response `cnodeUser.clockInfo` that there is more data to be fetched, breaking `primarySyncFromSecondary()` calls to those nodes.
This code change circumvents that issue by ensuring that primary will always fetch subsequent export. See code change for details
We don't have sufficient test coverage here, so will rely on manual testing. I did this against a local dev stack:
1. Create user with a track
2. Set `exportMaxClockRange` to < above created user's clock val
3. Set one of the secondaries to return the incorrect export data i.e. `cnodeUser.clockInfo.localClockMax = cnodeUser.clockInfo.requestedClockRangeMax`
4. Call `POST /merge_primary_and_secondary` on primary against the good secondary -> confirm it …

CON-380 CN make primarySyncFromSecondary work for multi-page exports against nodes without export bugfix

---

creator-node/src/services/sync/secondarySyncFromPrimary.js

TL;DR - Code throws not in try/catch/finally. lock never released. thanks @theoilie 
We've been seeing a lot of errors surrounding `Node is not one of the secondaries`
```
[secondarySyncFromPrimary][wallet=0xc7f07925a89df181c92a7f3b0110fa776f982f0a] Sync complete for wallet: 0xc7f07925a89df181c92a7f3b0110fa776f982f0a. Status: Error, message: This node is not one of the user's secondaries. This node: https://creatornode6.staging.audius.co Secondaries: [https://creatornode5.staging.audius.co,https://creatornode11.staging.audius.co]. Duration sync: 190. From endpoint https://creatornode8.staging.audius.co.
```
It's bc sync jobs take a while sometimes, and when a reconfig happens, the sync job will get stale and fail.
But, because we never wrapped the replica set check in the …

Bump try higher so that lock is always released

---

discovery-provider/integration_tests/tasks/test_get_feed_es.py
discovery-provider/src/queries/get_feed.py
discovery-provider/src/queries/get_feed_es.py
discovery-provider/src/queries/search_es.py
discovery-provider/src/utils/elasticdsl.py
discovery-provider/src/utils/helpers.py

* Log out ES error reason when get_feed_es fails
* Fixes fetching of followed save + repost records to use [collapse](https://www.elastic.co/guide/en/elasticsearch/reference/current/collapse-search-results.html) to get most recent 5 saves / reposts for each feed item.
* Fixes bug in search code path that was causing followed saves + reposts to be `extend_favorite` twice.  Makes `encode_int_id` idempotent.
Initial motivation was hitting this error in feed because the overfetching math was wrong and it was overfetching too much:
```
type': 'illegal_argument_exception', 'reason': 'Result window is too large, from + size must be less than or equal to: [10000] but was [40000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the …
```

Better get_feed_es error logging.  Fix fetch related saves + reposts

---

logging/docker-compose.yml

Remove unneeded mount points since we do not activate those modules:
* https://gist.github.com/krainboltgreene/6209955ed4a647e7b936863111c5d62b#file-docker-compose-yml-L388
* https://discuss.elastic.co/t/filebeat-with-services-inside-of-docker-compose-via-autodiscover/154886
Run `A up` and still get logs into ELK.

INF-224 remove unneeded mount, since we don't load these modules

---

identity-service/package.json
identity-service/sequelize/migrations/20220826063452-create-user-bank-transaction-metadata.js
identity-service/src/models/userBankTransactionMetadata.js
identity-service/src/routes/userBankTransactionMetadata.js

TODO:
https://www.notion.so/audiusproject/On-ramp-notes-92eaf6b5f6534489b235d6ed735d1486#202e32d21a144f5b97a577adfcaa831c
- Adds the endpoint `/transaction_metadata` which will be used to save and bulk-retrieve metadatas associated to transaction signatures.
- Adds a new table/model `UserBankTransactionMetadata` to store that metadata
- Uses some minor validation/normalization to enforce a "schema"
Tested on remote using raw requests
Adds error log. No monitoring wired up here! ❗ Open to suggestions

[PAY-587] Add transaction metadata to identity for transaction details

---

creator-node/src/services/stateMachineManager/index.js
creator-node/src/services/stateMachineManager/makeOnCompleteCallback.ts
creator-node/src/services/stateMachineManager/types.ts

Makes queue onComplete logic not enqueue jobs when a queue has too many waiting jobs. Implications:
- State monitoring jobs will skip enqueuing syncs and replica set updates if there are too many. This is okay because they wouldn't get processed in the near future anyway, so we can just cycle back to them later. It also allows us to see what jobs would've been enqueued to verify everything else is working as expected. Alternatives would be:
- Pause the monitoring jobs and resume them once queues clear up
- Enqueue the jobs anyway and let the queues get backed up
- We don't check the exact number of jobs that would be added, so we could add 1000 at a time even if the limit is 10. This is okay because a few extra jobs over the maximum doesn't cause any harm. Also, it keeps the logic simple …

Make queues limit how many jobs they add to each other

---

creator-node/src/index.ts
creator-node/src/redis.js
creator-node/test/redis.test.js

This is to clear sync write locks on app init so in case the app restarts that there won't be pre-existing state on redis on handling syncs.
See `redis.test.js`
If clearing locks fail, look for the error msg `Could not clear write locks. Skipping..:`

Clear write locks on init

---

identity-service/src/routes/idSignals.js
identity-service/src/routes/relay.js
identity-service/src/utils/antiAbuse.js

We've seen instances of AAO requesting signals from Identity and Identity not having the client's IP. 
I tried fruitlessly to repo this on stage but kept getting failed attestations for other reasons (i.e. score too low), but the hypothesis here is that in cases of account signup, we hit AAO on the initial calls to relay before we hit the record_ip endpoint, which doesn't happen until after account fetch.
This change records/updates the user's IP on every call to relay, so there should always be some data for AAO to request from identity. This change also uses a more correct getIP function for the relay endpoint.
Tested on stage ✅

[PAY-549] Write out IP with each call to relay

---

discovery-provider/src/queries/get_tracks.py

Currently get tracks does not include aggregate_tracks and shows incorrect repost / favorite counts because it relies on this shared cache.
Tested against prod snapshot.
Check API
http://dn1_web-server_1:5000/v1/tracks/

Fix get tracks by removing shared cache

---

service-commands/scripts/provision-dev-env.sh

Fixes multiple uses of this undefined envar:
* https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/27296/workflows/dabc7c25-eabf-41d8-aaef-ea30ce2092cb/jobs/328040
```
+ cd /discovery-provider
audius-protocol/service-commands/scripts/provision-dev-env.sh: line 77: cd: /discovery-provider: No such file or directory
...
+ /logging/bin/install-elastic-agent.sh
audius-protocol/service-commands/scripts/provision-dev-env.sh: line 135: /logging/bin/install-elastic-agent.sh: No such file or directory
```
* https://github.com/AudiusProject/audius-protocol/blob/11ab583dd5ff778d9468525111d05af048ed4427/service-commands/scripts/provision-dev-env.sh#L78
* https://github.com/AudiusProject/audius-protocol/blob/11ab583dd5ff778d9468525111d05af048ed4427/service-commands/scripts/provision …

INF-224 Set ${PROTOCOL_DIR} within provision-dev-env.sh

---

creator-node/src/config.js

Lowers the queue limit for orphaned data recovery since it's safe to run 24/7 with the limits it puts on its own outgoing requests.
N/A
Monitor the `/health/bull/queue/recover-orphaned-data-queue` endpoint to make sure the queue is running smoothly.

Let orphaned data recovery run 24/7

---

creator-node/src/components/tracks/TrackTranscodeHandoffManager.js
creator-node/test/TrackTranscodeHandoffManager.test.js
creator-node/test/lib/libsMock.js

The libs mock was interfering with findCIDInNetwork tests because of the actual requests that the tests were making. This PR is to:
- update the selection to use lodash + filtering out the self node immediately
- update the tests associated with selection
- update the libs mock 
`creator-node/test/TrackTranscodeHandoffManager.test.js`
The current logs surrounding random content node selection will suffice. take a look at:
- `Could not select random SPs: `
- `Could not hand off track: state=`

Update random SPs selection

---

creator-node/src/services/sync/secondarySyncFromPrimary.js

it's difficult to correlate the final log msg with a status in Prometheus as well as an error msg in case of a sync failure. This PR cleans this up by:
- Every handleSyncFromPrimary function prints some kind of standardized log at the end
- Include Prometheus status in the log to correlate type of result in metric with log
I was debating a broader refactor like not having nested catch statements but I wanted something we could get out ASAP that would normalize logs and give us correlation between prometheus + loggly. We can continue to refactor this flow for sure.
Unit + integration tests locally and mad dog passed. Ran the system locally, created a user and verified that data was synced to secondaries.
Local log (check out the prometheus result bit)
``` …
```

Better logging after syncs

---

creator-node/src/services/stateMachineManager/stateReconciliation/recoverOrphanedData.jobProcessor.ts
creator-node/test/recoverOrphanedData.jobProcessor.test.ts

Fixes TypeError caused by exporting both CommonJS and ES6 syntax.
Made sure the error was gone when running locally.
Monitor logs to make sure the following error isn't present: `Error processing job: TypeError: jobProcessor is not a function`

Fix duplicate export causing TypeError

---

creator-node/src/utils/legacyUtils.js

Sometimes, writing CIDs get corrupted. We should retry on these errors instead of bailing. This PR is to retry if cid verification fails
No change in functionality, just adding retries to this flow
Monitor the log `CID does not match what is expected to be`

Retry on cid verification

---

creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts

Makes it so that regardless of which reconfig mode is enabled, a reconfig will *not* be issued if:
- The primary is being updated in the reconfig
- The cause of the update is anything except the primary's endpoint changing (as determined by its absence in our CNodeEndpoint->SP_ID map)
- Automated tests pass
- Manual testing of taking down a user's primary locally shows that it skips issuing the reconfig:
```
{
"data": {
"enqueuedBy": "find-replica-set-updates-queue#12",
"wallet": "0x95a670da5e5fa236ddb586c71670cbf88f3b502d",
"userId": 2,
"primary": "http://cn1_creator-node_1:4000",
"secondary1": "http://cn3_creator-node_1:4002",
"secondary2": "http://cn4_creator-node_1:4003",
"unhealthyReplicas": [
"http://cn1_creator-node_1:4000"
],
"replicaToUserInfoMap": { …
```

Gate reconfig of primary to node endpoint changing

---

discovery-provider/src/queries/get_save_tracks.py
discovery-provider/src/queries/get_tracks.py
discovery-provider/src/queries/get_user_listening_history.py

Help with sorting for release_date for favorites

Add coalesce for release date sort for favorites query

---

discovery-provider/integration_tests/tasks/test_prune_plays.py

This test was missing a cutoff param and depends on current times.

Fix prune plays test cutoff time

---

creator-node/package-lock.json
creator-node/package.json
creator-node/src/config.js
creator-node/src/tracer.ts

This PR adds the necessary configs and packages to export trace data to a specified opentelemetry collector.
Tested manually by generating some traces and viewing the traces on Google CloudTrace
These changes will be monitored using a trace exporter (in our case probably CloudTrace).

[CON-353] Add tracing visualization

---

libs/src/NativeAudiusLibs.ts

Adds EntityManager to native-libs to fix native add/edit playlists
(clearly it would be nice to not have this completely separate entrypoint :D)

[C-991] Add entity-manager to native-libs

---

creator-node/src/services/prometheusMonitoring/prometheusRegistry.ts

This is a mathematical error because we're trying to get seconds but we're doing (ms * 1000) instead of (ms / 1000).
Tested locally by running the content node and making sure that queue metrics fit into buckets less than 600. Currently on stage/prod all jobs are in the 600+ bucket.
Grafana panel for job duration

Convert histogram observation from ms to seconds

---

libs/src/services/solana/tokenAccount.ts

We sometimes show out of date token info on reload because we were fetching with a default commitment level that was too high - this allows you to send a tip, refresh, and immediately get the correct value.
Tested locally, confirmed that this is indeed the issue.

[PAY-597] Fetch token account info with 'processed' commitment

---

creator-node/src/config.js
creator-node/src/services/stateMachineManager/index.js

[Enable recoverOrphanedDataQueue (heavily throttled)](https://github.com/AudiusProject/audius-protocol/commit/0a56ee947aaa578d41344ed4666d3e7db9b336b3)
[Increase maxRecurringRequestSyncJobConcurrency on prod from 30 to 50](https://github.com/AudiusProject/audius-protocol/commit/f27264e6ea5221f46ab1512d471a25d3d1f1fe19)
[Increase maxUpdateReplicaSetJobConcurrency prod from 15 to 25](https://github.com/AudiusProject/audius-protocol/commit/1fcb340e14ff5c6c9e564c09609ff9d0944f4747)
[10x prod recurringSyncQueue.maxWaitingJobs from 10k to 100k; 10x prod updateReplicaSetQueue.maxWaitingJobs from 1k to 10k](https://github.com/AudiusProject/audius-protocol/commit/6652cb562be2b03f2f71048cc7fef63c3a00cfb4) 
Just tweaking params, no logical changes

Modify CN state machine params for prod to improve throughput

---

creator-node/src/services/sync/primarySyncFromSecondary.js

Reduce `DB_QUERY_LIMIT` for primarySyncFromSecondary. This is an attempt to reduce server restarts due to primarySyncFromSecondary, although I'm not confident it will materially help
N/A just tweaking param
N/A

Decrease primarySyncFromSecondary db query limit from 10k to 1k

---

discovery-provider/src/api/v1/models/tracks.py
discovery-provider/src/premium_content/signature.py
discovery-provider/src/premium_content/signature_unit_test.py
discovery-provider/src/queries/get_trending_tracks.py
discovery-provider/src/queries/get_underground_trending.py
discovery-provider/src/queries/query_helpers.py

1. Since we may now apply the limit after filtering out premium tracks, it's possible that those tracks don't comprehensively match all the track ids passed in: the number of tracks and the number of track ids may not match. Thus, we recompute the track ids from the tracks after applying the limit.
This bug manifested when looking at my remote DN web server and seeing that building sorted tracks caused a KeyError because it was trying to access a track id which was not in the track map built by the tracks list after filtering out the premium tracks.
2. Also fixed the full track response model to include the premium content signature.
1. Spin up remote DN service and check logs to make sure there is no error when building the sorted tracks from the track map.
2. Made request to get track …

Fix track ids after filtering premium tracks

---

.circleci/config.yml

Seeing `Too many authentication failures` error trying to SSH into GCP machines. I followed [this guide](https://www.tecmint.com/fix-ssh-too-many-authentication-failures-error/) to only use the identity specified in the ssh command vs try all ssh keys and fail. 
Try GCP image bake on CI and make sure it works. CI run to look out for https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/27703/workflows/b98b9c74-0d0d-4c8b-a429-fd7fc2b33496/jobs/333714
We have a slack alert when the image bake fails

Add IdentitiesOnly to config

---

creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
creator-node/test/issueSyncRequest.jobProcessor.test.js

This pr is to standardize error logging like we do in secondary sync from primary where we also log the prometheus result. This is so we can query the logs by error code.
No tests, just updating logs 
This is for monitoring

Add better logging around outgoing syncs

---

audius.code-workspace

Get proper linting in each audius-protocol service while still opening the base Audius-Protocol folder by using `open workspace from file` and using the new `audius.code-workspace` file.
Gone are the days of needing to open discovery-provider as workspace root in order to get proper python formatting!

Add multi-root VSCode workspace

---

discovery-provider/src/queries/get_trending_tracks.py
discovery-provider/src/queries/get_underground_trending.py

Temporary fix so discovery does not run out of memory calculating trending when limiting after

Test apply early limit true

---

creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts

This inner stack trace is more precise, but still not helpful. Removing it so we don't print double logs.

Remove redundant stack trace log log

---

dev-tools/audius-compose
dev-tools/startup/discovery-provider.sh
docker-compose.yml

Launches discovery-provider-elasticsearch as part of local compose
This is extraordinarily slow, and should not be default behavior.
NA

[INF-187] Add elastic search to discovery provider

---

creator-node/src/fileManager.js
creator-node/src/utils/asyncRetry.js
creator-node/src/utils/cidUtils.ts
creator-node/test/asyncRetry.test.js

This is so that if the final err is about failing retries on status code that final message makes more sense. This PR also has more async retry tests
See `asyncRetry.test.js`. Existing functionality does not change.
Look for `Failed to fetch content with statusCode=${e.response?.status} after ${num} retries` log

Update final retry call and add async retry tests

---

creator-node/compose/env/base.env
creator-node/src/config.js
creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts

Adds a configurable blacklist for reconfig via an env var. 
- Manually added the array via config.js to see if in selection that explicitly passed in nodes do not get reconfigured
- Test via setting env var in base.env 
Look for the log `[_selectRandomReplicaSetNodes] wallet=` prefix

Set reconfig blacklist

---

discovery-provider/plugins/network-monitoring/src/metrics/index.ts
discovery-provider/plugins/network-monitoring/src/metrics/queries.ts

This PR adds the run start time to the network monitoring run slack alert
This was tested on the staging network monitoring instance by running a job and console logging the alert
This will be monitoring in the slack channel #eng-network-monitoring-alerts

[CON-395] Add start time to network monitoring slack alert

---

monitoring/exporters/sdk/main.js

Our current exporter keeps a running tally of open proposals, but this tally should be cleared each time we scan all proposals.
Manually running exporter locally and ensuring populated metrics match.
Will have to revisit upon new proposals to ensure running metrics remain valid.

INF clear exporter's tallies for new proposals

---

discovery-provider/src/app.py

Across all nodes, we see this task sometimes taking up to an hour (though nominally only ~5 min on discovery nodes). Bump the interval up quite a bit to remove headaches of content being slow to mark `is_available`
N/A
Monitor via grafana charts
http://grafana.audius.co/d/r_iIq2n4z/ray-test?orgId=1&refresh=30m&from=now-7d&to=now-1m&var-env=prod&var-host=All

Run is_available job every 3 hours

---

discovery-provider/plugins/network-monitoring/src/metrics/index.ts

This PR adds run duration to the slack alert for network monitoring
tested locally in the node REPL to make sure the math was right.
This will be monitored in our slack channel eng-network-monitoring-alert

[CON-395] Add duration to network monitoring metrics

---

creator-node/package-lock.json
creator-node/package.json
creator-node/src/tracer.ts

This PR adds `FsInstrumentation` to content node to get spans on filesystem operations.
Since it's just an extra instrumentation, I've just run integration tests to make sure it didn't break anything.
This PR will be monitored on spans in CloudTrace

Add FsInstrumentation to content node

---

discovery-provider/plugins/network-monitoring/src/metrics/index.ts

This PR remove the start time from the network monitoring slack alert since it isn't needed with "runDuration"
Run a sample network monitoring job on staging
this will be monitored by our slack alerts in eng-network-monitoring-alerts

remove start time from slack alert

---

.circleci/config.yml
discovery-provider/plugins/network-monitoring/src/metrics/index.ts

Allow surgical usage of `./deploy-ci.py` when using Trigger Pipelines that set a String-based `deploy_args` parameter.
This allows us to deploy more complex scenarios like deploying to multiple hosts:
> deploy_args: --environment staging --services creator --hosts stage-creator-4 --hosts stage-creator-5 --git-tag 0a05746523a690d7d2ac586ffd343a9f98b5eee0 --dry-run
Design doc: 
* https://www.notion.so/audiusproject/Automated-Production-Deployments-67f4fb5fb7574320a45dd63082ec4adf#7a7d8deb5335481f81a9ce353de33987
Testing off `master` with `--dry-run` commands first.
Will monitor `#eng-incidents-*`.

INF-251 Allow for surgical deployments via a trigger pipeline

---

.circleci/bin/deploy-ci.py

Update our prod deployment flow to use correct commands.
--dry-runs off `master`.
CircleCI Logs

INF-251 use set-tag for prod

---

creator-node/src/services/stateMachineManager/stateReconciliation/recoverOrphanedData.jobProcessor.ts
creator-node/test/recoverOrphanedData.jobProcessor.test.ts

Randomizes the order of wallets that Orphaned Data Recovery checks. This is important so that jobs don't each attempt the same wallets if there are failures.
Verified that tests cover this scenario and pass.
Monitor for orphaned data recovery errors and progress under the filter `json.queue:"recover-orphaned-data-queue"`. I'll also make a Grafana panel to track overall orphaned wallet trends.

[CON-408] Randomize order of orphaned data recovery

---

.circleci/bin/deploy-ci.py

Let's be careful with prod and:
* Wait 5 minutes between upgrading each node.
* Check health_check every 30 seconds so we can retroactively see how quickly a service fails post-upgrade.
* Ensure the health_check is healthy before moving onto the next node.
* Stop a deployment early if a post-health_check fails.
* Report a failed deployment to CircleCI.
--dry-run on `master`
CircleCI logs

INF-251 throttle prod releases

---

check_secrets.sh

Catch any string in the shape of `postgres://<username>:<password>@<ip address>:<port>/<db_name>`
Long term we should move to something like GitGuardian to get more robust secrets checking - our current system is overly tied to AWS.
Tested against a bad string

Add check for GCP DBs in check-secrets.sh

---

identity-service/src/config.js
identity-service/src/utils/antiAbuse.js

Had some issues with AAO integration:
- Was missing the required config for skipAbuseCheck, causing the recovery flow to get skipped
- Was incorrectly blocking users if they don't have a handle, which is to be expected early on in the signup flow
Tested on prod 😬

Remove handle relay blocking logic

---

.circleci/config.yml

Enable auto-deploying from master to staging (non-force).
Wait until tomorrow morning and be highly aware of the first few commits.
Look at #eng-deploys-announcements.

INF-251 remove hold job for auto-deploying to staging

---

.circleci/bin/deploy-ci.py

Sort the upgradeable list and always place canaries in front, when present.
Running deploy job in CI.
CI Logs

INF-251 always deploy to canaries first

---

creator-node/src/config.js
creator-node/src/services/URSMRegistrationManager.js
creator-node/src/services/initAudiusLibs.js

Due to Goerli eth migration, the delegate owner wallet values for content nodes on EthContracts
To fix this, we add new envvars, only meant to be used on staging
**NOTE: this means no new nodes can be registered on staging until entity manager migration (this is fine)**
Tests pass - this is already running on staging, maddog confirms local dev unaffected, and prod will be unaffected as long as it never sets the oldDelegateOwnerWallet / oldDelegatePrivateKey values
All registered content nodes should show `"isRegisteredOnURSM": true` in health check

Patch staging CN

---

.circleci/config.yml

Always send Slack notifications when:
* "taking over" a node
* deploying to production
* using custom params
* a deployment failed, in all cases
Monitoring #eng-deploys-announcements
Same as above.

INF-251 don't send Starting nor Success slack messages for auto-deploys

---

creator-node/src/index.ts
creator-node/src/serviceRegistry.js

Awaits for more services to come up before starting the Express app. This should resolve an error that I'm seeing on prod (but not locally) where temporarily during startup requests to `/merge_primary_and_secondary` fail because the recurring-sync-queue isn't initialized yet. The requests start to succeed after a while when the queue is initialized.
Tested to make sure initialization works locally.
Search for errors starting with "Cannot" - there should be no logs with this word.

Await CN services before starting server

---

libs/scripts/release.sh

Only show diff in libs folder between versions
Tested the command manually and showed that it only shows the commits that have libs changes.
Will monitor the changelog on the next libs release
================ REMINDER: ================
If this PR touches a critical flow (such as Indexing, Uploads, Gateway or the Filesystem), make sure to add the `requires-special-attention` label.
** Add relevant labels as necessary. **
-->

Only show diff in libs folder between versions

---

.circleci/config.yml

Support deploying content nodes ONLY from release*-patch-* branches.
Remove ability to deploy content nodes from regular release-* branches.
Merge to master and see workflows.

INF-260 restrict cn deploys to release*-patch-* branches

---

creator-node/package-lock.json
creator-node/package.json

Updates the sdk version in content node
Required for functionality around usage of entity manager to validate user replica set and writing to entity manager for replica set updates 
reference pr with libs changes used by cn: #3897
NOTE: These changes only matter if the env var `entityManagerReplicaSetEnabled` is set to true which is currently only done locally via linked libs
Ran everything e2e in the commit #3897

Update @audius/sdk version in content node

---

discovery-provider/src/api/v1/tracks.py
libs/src/sdk/api/generated/default/apis/TracksApi.ts

Add non-full API endpoint for `tracks/trending/underground`
Make sure existing tests pass. Deploy and test endpoint on stage

Add trending/underground non-full endpoint

---

creator-node/src/index.ts

Makes sure tracing is called before everything else in Content Node since that's necessary for it to work properly. This is a followup to https://github.com/AudiusProject/audius-protocol/pull/3939#discussion_r983627595.
This is a minor change so if tests and mad dog pass then it should be good to go.
This would break startup, so monitor deployment to make sure the server starts up.

Set up tracing before anything else

---

discovery-provider/scripts/start.sh

A celery task has a memory leak.  Worker will start at around 200MB of memory usage... after 12 hours will be around 550MB.
We should find the leak, but in the short term celery has a handy setting that will spawn new process when memory usage crosses a threshold:
https://docs.celeryq.dev/en/stable/userguide/workers.html#max-memory-per-child-setting
This will set limit to around 300MB
will test on sandbox machine.

set mem limit for celery workers

---

creator-node/src/services/prometheusMonitoring/prometheus.constants.ts

Sets the `aggregator` property for each metric that we track. This is needed for clustering logic because otherwise it will just sum across all workers by default. This is the general rule of thumb:
* If it's a metric returned by state machine, use `'max'` because only one worker listens for state machine onComplete and subsequently updates each job's metrics. `'sum'` should technically work as well since all workers will report 0 except for the worker that listens for onComplete
* If it's a Bull metric, use `'first'` because each worker has all queues set up and gets Bull info from Redis
* Any other metric where multiple workers will report values should use `'average'`
I ran `A up` spot checked some of these locally. The best tests will be on staging, paying particular attention to …

Add aggregator config to each metric

---

.circleci/bin/deploy-ci.py

We'll start sending failed Slack notifications more often when:
* A production post-health check fails (currently implemented).
* We're unable to SSH into a machine. (+1 vote from me).
* We failed to release to any staging or production node. (+1 vote from me, but we can also limit to only failed releases to production nodes).
None.
#eng-deploys-announcements

INF-259 Alert more often in #eng-deploys-announcements

---

discovery-provider/src/api/v1/helpers.py
discovery-provider/src/api/v1/users.py
discovery-provider/src/queries/get_tracks.py
libs/src/sdk/api/generated/default/apis/UsersApi.ts
libs/src/sdk/api/generated/full/apis/UsersApi.ts

Add `filter_tracks` arg to user tracks endpoints with tertiary values ("all", "public", "unlisted") and filter tracks by specified type.
Affected endpoints:
full users/id/tracks
non-full users/id/tracks
full users/handle/handle/tracks
non-full users/handle/handle/tracks
Make sure unit/integration tests pass; test on staging

Support unlisted track filtering in user tracks api

---

creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts

Fix flag so entity manager txs only go through when URSM fails relay and flag is enabled.

Fix EM flag for replica sets

---

discovery-provider/integration_tests/tasks/test_get_feed_es.py
discovery-provider/src/queries/get_feed_es.py

https://linear.app/audius/issue/C-1030/empty-feed-upon-sign-up
on signup client passes in IDs for initial feed render.
✅

get_feed_es supports explicit IDs

---

discovery-provider/scripts/search_quality.py
discovery-provider/src/queries/search_es.py

* improves search_quality.py tool
* adds a `should` that will boost exact track title match (when all query terms are in track title)
ran search_quality.py
testing on sandbox env

search: boost exact track title match

---

creator-node/src/logging.js

Added a field in our logger that tells us which process in the cluster a log is printed from (master/worker 1,2,3 etc). Added while debugging https://github.com/AudiusProject/audius-protocol/pull/3770 and figured it might be useful more generally
Ran local setup and observed that logs were being printed. Also the CircleCI tests print the clusterWorker property
Sample logs from local dev
```
{"name":"audius_creator_node","clusterWorker":"master","hostname":"2da92482d7b9","pid":365327,"level":30,"msg":"Monitoring Queue: Computed value for usedMemory 18814889984 || active: 0, waiting: 0, failed 0, delayed: 0, completed: 500 ","time":"2022-10-02T18:18:29.406Z","v":0,"logLevel":"info"}
{"name":"audius_creator_node","clusterWorker":"Worker …
```

Add cluster worker number in logger

---

discovery-provider/src/queries/get_health.py
discovery-provider/src/tasks/entity_manager/entity_manager.py
discovery-provider/src/utils/prometheus_metric.py

Export the majority of our health-check metrics using Gauges that do not report metrics from dead pids.
For some of our existing Gauges, where the use case aligns, we will now only keep track of metrics of live processes using:
```
multiprocess_mode="liveall"
```
Prometheus Gauges within the official Python driver do not work as assumed when running in a multiprocess environment:
* Section 4: https://github.com/prometheus/client_python#multiprocess-mode-eg-gunicorn
* Examples/tests in action: https://github.com/prometheus/client_python/blob/master/tests/test_multiprocess.py
As such, we may need to pivot to using Summaries to get the intended functionality that Gauges provide within Node.js' client driver. Basic summary support has been added for future usage after local testing.
We also …

INF-242 Fix Gauge metrics for health-check metrics. Add basic Summary support.

---

.circleci/config.yml

Replace no-op job placeholders with a new release-scripts job that calls `audius-tooling/release-scripts/*.sh`
Will confirm cut-release.sh can get to the last steps before breaking. Will then update `gh-tokens.releases` to use a non-noop token when dry run looks good on Monday.
Look at dry runs of release-scripts, which don't currently push changes to our git repos. Some success messages and all failures will hit #eng-deploys-announcements.

INF-272 Replace noop jobs with new release-scripts jobs

---

creator-node/src/services/URSMRegistrationManager.js

Currently, stage DNs are not indexing Entity Manager replica set updates because the signer is the old ropsten delegate wallet not the new goerli delegate wallet.
We can simply remove the old delegate wallet env var so the goerli wallet is used. Then, we also need to skip the check against the URSM wallet when EM is enabled.
Will test on staging.

Update CN old delegate wallet patch

---

creator-node/package-lock.json
creator-node/src/config.js
creator-node/src/index.ts
creator-node/src/routes/prometheusMetricsRoutes.js
creator-node/src/utils/clusterUtils.ts

Adds `clusterModeEnabled` env var (defaults to true) to fully disable cluster mode (as opposed to running cluster with one primary and one worker). Main changes involved:
* Make all checks for `isThisProcessSpecial()` and `isThisProcessInit()` return true when cluster is disabled because we want to run any gated logic since this is the only process that's running
* Make `/prometheus_metrics` route return data as if it were single-processed like before - skip aggregation when cluster is disabled
* Make startup skip all the cluster parts when the env var is set to false
* Ran with `clusterModeEnabled=false` locally and made sure that the server started up and returned reasonable-looking metrics from `/prometheus_metrics` and Bull jobs completing properly
* Ran CI with …

[CON-437] Add env var to disable cluster mode

---

discovery-provider/integration_tests/queries/test_get_sitemap.py
discovery-provider/requirements.txt
discovery-provider/src/queries/get_sitemap.py
discovery-provider/src/queries/queries.py
discovery-provider/src/utils/get_all_other_nodes.py

Adds sitemap endpoints to the discovery node to generate the xml files for user/track/playlist routes
Adds endpoints:
* `/sitemap/base.xml` returns the base sitemap for the static routes
* `/sitemap/<string:type>/base.xml` Returns a list of links to other sitemaps for that type 
* `/sitemap/<string:type>/<string:file_name>` Returns a list of the urls to index
Wrote some tests with mock data and ran the discovery node against a staging DB to verify the correct links
Can use the google webmaster tool to check
Fixes: PLAT-343
Fixes: PLAT-322

Add Discovery Sitemap Endpoint

---

.circleci/config.yml

Change layout of `release-*-patch-*` workflows to only allow deploying content nodes per host.
While we're moving away from the noop job, we will continue to use `--dry-run` for the time being.
New workflow:
* https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/28491/workflows/31c1163e-31be-493f-af37-6735c00bd133
Run through a few tests using a release

INF-277 Create --dry-run jobs for foundation content nodes

---

.circleci/bin/deploy-ci.py

Stop deploying to cn11 until it has recovered. Lower vertical height of slack notifications.
#eng-deploy
#eng-deploy

INF Skip deploying to cn11 temporarily + short slack notifications

---

creator-node/compose/env/base.env

With https://github.com/AudiusProject/audius-protocol/pull/4005/files, mad dog now fails because this flag is enabled by default. However, service commands is not using entity manager yet. We can make changes https://github.com/AudiusProject/audius-protocol/pull/4013 to enable EM in service commands but this is a lot of work. For now, let's just disable replica set by default and enable when needed locally.
Mad dog passes

Disable EM replica sets in local so mad dog passes

---

libs/src/services/identity/IdentityService.ts

Saving user bank metadata requires the transaction signature of the final transfer instruction, which was being omitted. Also needs the metadata wrapped into a `metadata` subfield.
Tested E2E with Coinbase Pay

[PAY-672] Fix saveUserBankTransactionMetadata in SDK

---

.circleci/bin/deploy-ci.py

Add commit and branch details to `reservations`.
Local runs that look like this:
```
$ reservations
stage-creator-10         master              4dbb42b   master
stage-creator-4          master              4dbb42b   master
stage-creator-5          Joaquin Casares     6e24564   origin/jc-inf-266
stage-creator-6          Sid Sethi           f9c6701   missing
stage-creator-7          master              4dbb42b   master
stage-creator-8          Theo Ilie           9cb8a5c   origin/theo-delete-disk-odr
stage-creator-9          master              4dbb42b   master
stage-discovery-1        master              4dbb42b   master
stage-discovery-2        master              4dbb42b   master
stage-discovery-3        master              4dbb42b   master
stage-discovery-4        master …
```

INF-288 add commit details to `reservations`

---

creator-node/src/services/sync/syncImmediateQueue.js
creator-node/src/services/sync/syncQueue.js

Adds active/waiting job metrics for sync and sync-immediate queues, which we're currently missing from Grafana
Made sure tests pass and I see the appropriate metrics locally at `/prometheus_metrics` after bringing up the stack locally and creating a user to sync
We should see Grafana drop-down options in the Bull dashboard for "sync-processing-queue" and "sync-immediate-processing-queue"

[CON-382] Track metrics for sync queues

---

creator-node/src/config.js
creator-node/src/services/stateMachineManager/stateMachineConstants.ts
creator-node/src/services/stateMachineManager/stateReconciliation/recoverOrphanedData.jobProcessor.ts
creator-node/test/recoverOrphanedData.jobProcessor.test.ts

- Adds env vars to control orphaned data recovery speed instead of relying on code changes to the constants (no change in prod values here)
- Updates config.js defaults to be consistent with env vars in https://github.com/AudiusProject/audius-docker-compose/pull/107
Made sure mad dog passes and orphaned data recovery queue works the same as before
Orphaned data recovery jobs should continue completing. Monitor the metrics for number of orphaned data syncs (at the bottom of the syncs dashboard).

Use env vars for ODR and make other env vars consistent

---

discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
discovery-provider/src/tasks/entity_manager/entity_manager.py
discovery-provider/src/tasks/entity_manager/user.py
discovery-provider/src/tasks/entity_manager/utils.py

Add User verified action via entity manager
Wrote a test to validate that a valid tx updates the user verified and an invalid tx does not update the user model

Discovery indexing user verification

---

service-commands/scripts/auto-delete-gcloud-instance.sh
service-commands/scripts/create-instance.sh

Add auto-cleanup to GCP spot instances triggered via CI from mad-dog/sdk. This auto deletes instances after 12 hours so we don't have a buildup of dozens or more instances in our dashboard.
Tested with a 10 minute window here and I checked the VM and firewall manually and it's been deleted https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/28965/workflows/d9f71e03-d771-4a9b-8bdf-1db26f7b4006/jobs/356241
VM instances and firewall page in GCloud console.

[INF-292] Auto delete CI spot instances

---

identity-service/src/routes/wormhole.js

Current timeout is 10 min, but seems like wormhole always takes longer.

Increase timeout for wormhole relay route

---

.circleci/bin/deploy-ci.py

`ssh stage-creator-9` can take longer than 5 seconds, causing our deployments to this node to fail.
My vote is fix the underlying issues with `stage-creator-9`, but we can also loosen the timeout period before our deployment jobs mark the deployment on this node as failed.
The node has plenty of postgres processes and is running at max CPU:
Testing on master.
#eng-deploys

INF Wait 15 seconds to SSH into a node

---

creator-node/src/utils/clusterUtils.ts

Changes concurrency to use `Math.ceil` instead of `Math.floor`, which makes the global concurrency be a function of the number of workers. Examples:
* 16 workers and min global concurrency of 30 = global concurrency of 32
* 16 workers and min global concurrency of 17 = global concurrency of 32
* 16 workers and min global concurrency of 1 = global concurrency of 16
Mad dog passing is sufficient. I'll take this out to staging to verify higher traffic and concurrency passing.
The number of active jobs when queues are backed up should be a factor of 16 of prod.

[CON-440] Use min concurrency instead of max for Bull

---

discovery-provider/plugins/network-monitoring/src/content/index.ts
discovery-provider/plugins/network-monitoring/src/db/sql/scratch_pad.sql
discovery-provider/plugins/network-monitoring/src/metrics/index.ts
discovery-provider/plugins/network-monitoring/src/metrics/queries.ts
discovery-provider/plugins/network-monitoring/src/prometheus.ts

This PR records the clock value `-2` when a node is unhealthy rather than defaulting to `-1` so we can tell is the user is empty vs if there was an error from the content node.
This was tested on staging network monitoring by doing a test run
This will be monitored on grafana on the network monitoring dashboard as well as from our slack alerts

[CON-313] Network Monitoring: Differentiate between missed users and users with -1 clock values

---

discovery-provider/es-indexer/README.md
discovery-provider/es-indexer/src/indexNames.ts
discovery-provider/es-indexer/src/indexers/PlaylistIndexer.ts
discovery-provider/es-indexer/src/indexers/RepostIndexer.ts
discovery-provider/es-indexer/src/indexers/SaveIndexer.ts
discovery-provider/es-indexer/src/indexers/TrackIndexer.ts
discovery-provider/es-indexer/src/indexers/UserIndexer.ts
discovery-provider/es-indexer/src/indexers/sharedIndexSettings.ts
discovery-provider/scripts/search_quality.py
discovery-provider/src/queries/get_feed_es.py
discovery-provider/src/queries/search_es.py
discovery-provider/src/utils/elasticdsl.py

* centralizes index settings
* sets `max_terms_count` to 1M so that `get_feed_es` doesn't break for users who follow >65k people
* uses `lowerKeyword` for most keyword fields where we want case insensitive matching
* uses `noWhitespaceLowerKeyword` for handle so that `Dillon Francis` search matches `DillonFrancis`
* speeds up `fetch_followed_saves_and_reposts` to use denormalized data to mget instead of doing a "collapsed" msearch 🏇 
Note: this is a "simple" PR for whitespace tolerance in search term.  It only applies to the `handle` field which we know to be spaceless by using a custom analyzer with `char_filter`.  This won't help in a cross field query if the user types `stereo steve guitar garbage` because the `handle` field would attempt to match `stereosteveguitargarbage`.
A better …

ES: whitespace tolerance, faster feed

---

contracts/contract-config.js
contracts/migrations/6_nethermind_entity_manager_migration.js
contracts/scripts/nethermind_entity_manager_tx.js
contracts/truffle-config.js

Deploy EM to chain on stage DN.
`./node_modules/.bin/truffle migrate --f 6 --to 6 --network nethermind --skip-dry-run`
Send transactions to chain, to be randomized later. requires setting env vars for entity manager address and private key for sending txs.
`./node_modules/.bin/truffle --network nethermind exec scripts/nethermind_entity_manager_tx.js`
https://www.notion.so/audiusproject/Nethermind-Truffle-Setup-ba989185ca724b818bc064294dd48357

Deploy EM to nethermind + tx script

---

service-commands/scripts/create-instance.sh

My last PR https://github.com/AudiusProject/audius-protocol/pull/4057 didn't handle if GCP pre-empts the VM and stops it before the cleanup script runs. This adds a flag to set instance termination action to delete (default is stop).
Tested using gcloud API to make a VM and verify termination action in console is terminate.
No dangling instances in CI project

[INF-292] Cleanup GCP VMs created in CI pt. 2

---

discovery-provider/integration_tests/queries/test_get_tracks.py
discovery-provider/integration_tests/utils.py
discovery-provider/src/api/v1/models/users.py
discovery-provider/src/queries/get_tracks.py
libs/src/sdk/api/generated/default/models/User.ts
libs/src/sdk/api/generated/full/models/UserFull.ts

For the track endpoints, return the artist pick first, with the remaining tracks sorted according to the `sort` parameter (`sort` has a default value and setting a different `sort` value is deprecated). However, if the `sort_method` param is defined, sort all tracks according to that.
Also return the `artist_pick_track_id` as part of the user object.
- New integration tests
- Test endpoints locally
Manually updated artist pick value in psql:
Was not able to test user tracks tracks endpoint manually because I couldn't create tracks locally and the artist pick write path in the client is not done yet, but the integration tests should cover this case.

Modify user API endpoints to accommodate artist pick tracks

---

discovery-provider/src/api/v1/helpers.py

Quick fix for followers API. Users without replica sets would fail here when getting their images.
Tested on staging. API returns 500 on other DNs.

Fix followers API for users without replica set

---

discovery-provider/src/schemas/user_schema.json
libs/src/api/Users.ts
libs/src/services/schemaValidator/schemas/userSchema.json
libs/src/utils/types.ts

Add `artist_pick_track_id` field to user metadata types in libs.
Will call `updateCreator` from the client; entity manager path is already implemented in that method.
Make sure existing tests pass.

Add artist pick field to user metadata types in libs

---

discovery-provider/integration_tests/tasks/test_get_feed_es.py
discovery-provider/src/queries/get_feed_es.py

Approximates this [get_feed](https://github.com/AudiusProject/audius-protocol/blob/master/discovery-provider/src/queries/get_feed.py#L103-L123) code.
✅

ES feed: dedupe track uploads that also appear in a playlist

---

creator-node/src/services/stateMachineManager/processJob.ts
creator-node/test/processJob.test.js

Saw another log that printed a gigantic object for bull. Converting to debug since this might be useful for local dev but also open to removing.
https://audius.loggly.com/search#terms=%22new%20job%22&from=2022-10-11T20:20:58.349Z&until=2022-10-12T20:20:58.349Z&source_group=&filter=json.name;audius_creator_node&event=97de548a-4a67-11ed-80da-02ec14fc4836,1665604430000,138848972308370570
Unit tests
Loggly should not show this for stage/prod instances.

Make another gigantic log a debug

---

identity-service/src/routes/healthCheck.js

```
TypeError: Cannot read property 'status' of null
at /usr/src/app/build/src/routes/healthCheck.js:94:35
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async /usr/src/app/build/src/apiHelpers.js:6:26
```
This check would fail when tx receipt is null which happens when tx is pending.
https://web3js.readthedocs.io/en/v1.2.11/web3-eth.html#gettransactionreceipt
We should only mark a tx as failed once it has been mined
Unable to repro error on stage but this change works

Fix health check relay when tx is pending

---

creator-node/package-lock.json
creator-node/src/models/index.js
creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
creator-node/src/utils/clusterUtils.ts

This reverts commit 27cfbea6df97eb8241edb19a5edbdb7fafafe59e.
Broke test-creator CI
n/a
n/a

Revert "Change CN db connection pool to be a function of numWorkers (#4106)"

---

service-commands/src/setup.js

Goes along with index cleanup. Pausing until we get an ILM in place, otherwise we'll autoscale right back to a larger size
A up works and mad dog passes
Elastic instance doesn't grow in size.

Pause sending local dev logs to elk by default

---

creator-node/src/middlewares.js

This bug causes syncs triggered by _issueAndWaitForSecondarySyncRequests to fail because req.session.creatorNodeEndpoints is a mapping not an array. This fixes that.
Tested locally with a create user and verified it syncs. Also tested with mad dog and unit tests
Fully synced users % should stay constant or improve

[CON-468] Fix _issueAndWaitForSecondarySyncRequests bug with creatorNodeEndpoints

---

creator-node/src/components/replicaSet/replicaSetController.js
creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts

Fixes some bugs caused by refactoring scattered SP ID functionality into ContentNodeInfoManager: 
* `ERROR || Failed to retrieve user from EntityManager during sync` - this was caused by not initting libs with contracts, which it needs when URSM is enabled
* `/manually_update_replica_set` route not updating to reflect a type change
Integration tests and mad dog should be sufficient
The error in the description should not be present in logs

Fix SP ID related bugs

---

.circleci/bin/deploy-ci.py

Don't wait for 30 minutes when deploying one node at a time.
This should speed up deploying to foundation nodes.
Testing during the next production release.
#eng-deploys and CircleCI logs.

inf-294 only wait 1 minute when releasing to one node at a time

---

discovery-provider/src/tasks/users.py
libs/src/utils/types.ts

Found some bugs when testing writes E2E. Allow `artist_pick_track_id` to be set to `null` (when removing an artist pick). 
Without this change, we need to be careful to always populate `artist_pick_track_id` on the user in the client correctly so that the default value (`null`) is never accidentally passed to discovery and saved to the user metadata.
Manually test E2E with local client / libs ([client code](https://github.com/AudiusProject/audius-client/pull/2128)) against this commit deployed to staging. Should see correct artist pick when querying the user in the API.

Fix libs type and allow setting null artist pick in backend

---

creator-node/src/services/stateMachineManager/index.js
creator-node/src/services/stateMachineManager/stateMachineConstants.ts
creator-node/src/services/stateMachineManager/stateReconciliation/index.js
creator-node/src/utils/clusterUtils.ts

1. Reduce `maxWaitingJobs` for `recurringSyncQueue` and `updateReplicaSetQueue` by 10x
2. Reduce queue history (num completed/failed jobs) for multiple queues from 100k to 1k
3. set default num workers to half num cores
4. Add ability to pause `recurringSyncQueue` and `updateReplicaSetQueue` based on envvars
automated sufficient
also tested manually on staging node
Easy to monitor all above via bull dashboard, grafana bull dashboard, and grafana profiling dashboard

CN performance stabilization tweaks

---

creator-node/test/contentBlacklist.test.js
creator-node/test/lib/dataSeeds.js
creator-node/test/lib/libsMock.js

There were changes to the /audius_users flow where `libs.contracts.UserFactoryClient.getUser()` was called but not mocked in the content blacklist tests. 
This PR is to:
- assert that creating the user results in status code 200 (e.g. what is expected)
- fix the tests by mocking `libs.contracts.UserFactoryClient.getUser()`
- refactor data seeds to be re-usable
- some styling/lint
This PR is to fix tests.
Unit tests results will reflect if tests are still failing

[CON-455] - Fix content blacklist tests and mocks

---

creator-node/src/segmentDuration.ts
libs/src/api/Users.ts
libs/src/services/discoveryProvider/DiscoveryProvider.ts
libs/src/services/discoveryProvider/requests.ts

This PR adds the endpoint getUserListenCountsMonthly to appropriate libs files to be called by the front end in the artist dashboard.
Also moved an endpoint that was previously tucked in an internal functions section.
I did notice the data is still slightly off from the play count generated for all time listens. E.g. in this example it says there are 140 plays, but the listen counts returned by getUserListenCountsMonthly total to 151.
Ran my client pointed at staging data using my local libs/sdk and loaded the artist dashboard in my local client. Will also put up a PR containing my changes to the client for this.
If anyone has a staging account with listening data that goes back before 2021 that would be super helpful too!
n/a but would love any ideas!

Add getUserListenCountsMonthly to libs for artist dashbaord

---

libs/src/api/File.ts

In fetchCID we are determining whether or not a CID is forbidden by checking if all the errors have status 403. But in some cases the error array is empty, so we need to confirm that the array has a length before assuming it is forbidden

Check that errored array has length when checking for forbidden

---

discovery-provider/src/queries/get_unpopulated_playlists.py
discovery-provider/src/queries/get_unpopulated_tracks.py
discovery-provider/src/queries/get_unpopulated_users.py

Remove redis cache for unpopulated entities. Required because entity manager does not update this cache.
Tested APIs that rely on get_unpopulated.
https://discoveryprovider.staging.audius.co/v1/users/DE2zr
https://discoveryprovider.staging.audius.co/v1/tracks/DE2zr
https://discoveryprovider.staging.audius.co/v1/full/playlists/trending?limit=3&offset=0&time=week&user_id=ebMKb

Remove unpopulated cache for tracks, users, playlists

---

.circleci/config.yml

* Confirm that `release-week` logic works as intended.
* Remove test that confirms `release-week` logic.
* Offset release week to account for off-site.
* Add `release-to-service-providers` job that's triggered by the `sp_release` field.
* Re-enable previously commented jobs.
* Leave `release-to-service-providers-cron` commented out for now.
* https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/30121/workflows/e327d8df-e153-478d-8a71-597bb8033b8e
* https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/30119/workflows/eca0232f-6453-4a3b-a582-cc71ceac152c
Monitoring #eng-deploys

INF-295 Fix release-week logic checking

---

.circleci/config.yml

Nicer #node-operator messages on Discord, by:
* eliminating unfurling
* including semver
Example Discord Message:
```
New service version (0.3.69) is out now!
• [New compose files](https://github.com/AudiusProject/audius-docker-compose)
• [Changelogs](https://github.com/AudiusProject/audius-protocol/releases)
• [Governance Proposals](https://dashboard.audius.org/#/governance) (2 days of voting left)
```
Message in #audius-alerts-text:
* https://discord.com/channels/557662127305785361/1026998576066342942/1034247213888569365
Tested with this commit:
* https://github.com/AudiusProject/audius-protocol/pull/4143/commits/d66f677ed0c6ed4f195a3d554aea9bbf7d587bb9
Monitor #node-operators.

INF-290 Nicer discord messages

---

creator-node/src/config.js

Update reconfigSPIdBlacklistString to include any node > 75% storage utilization
Verified the list of spID's by running a script with libs and hit the health check for each spId and made sure its storage use is over the 75% limit.
update-replica-set should not reconfig onto any of the nodes above

Update reconfigSPIdBlacklistString to include any node > 75% storage utilization

---

creator-node/src/fileManager.js
creator-node/test/fileManager.test.js

Cleans up references to a libs param that is no longer used - no need to pass it in anymore from other consumers and tests.
CI passing is sufficient.
N/A

Clean up unused libs param

---

creator-node/package-lock.json
creator-node/src/config.js
creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts
creator-node/test/updateReplicaSet.jobProcessor.test.js

We want ability to only cycle primary out of replica set. This is not simple in our current reconfig modes pattern, since we calculate "highest reconfig mode enabled" - this config is a quick override to get around that restriction. We should probably refactor this to be discrete reconfig modes, but for now this is fine
Note this override is defaulted to false to ensure no behavior change by default
New test coverage (pls review!)
With this override enabled, we should observe that secondary reconfigs do not occur, and only primary reconfigs are occurring

CN Reconfig mode primary only override

---

creator-node/src/services/stateMachineManager/CNodeHealthManager.ts
creator-node/src/services/stateMachineManager/stateMonitoring/findSyncRequests.jobProcessor.ts
creator-node/src/services/stateMachineManager/stateMonitoring/monitorState.jobProcessor.ts
creator-node/test/monitorState.jobProcessor.test.js

* Fixes invalid reference to NodeHealthManager (it was supposed to be updated to be a named import of CNodeHealthManager). This was causing the error `NodeHealthManager.getUnhealthyPeers is not a function`
* Catches `TypeError: Cannot read property '<any wallet public key>' of undefined at _findSyncsForUser`. This should short-circuit as `no_sync_unexpected_error` and log a more informative tracing error for the individual user instead of failing the whole findSyncRequests job
CI passing is sufficient - just bug fixes.
There shouldn't be any TypeErrors, and find-sync-request-queue jobs should succeed.

Fix TypeError & undefined bugs

---

creator-node/src/services/stateMachineManager/CNodeHealthManager.ts
creator-node/test/CNodeHealthManager.test.js

Remove the distinction between simple and full peer health checks in CNodeHealthManager. All health check requests will check health, storage and file descriptors.
This was necessary to reconfig off primaries that ran out of storage. Without this, we never checked storage available on primaries.
This flow has good test coverage so made sure unit tests all pass.
In bull dashboard unhealthPeers correctly returns unhealthy nodes

Remove performSimpleCheck flag

---

libs/src/services/schemaValidator/schemas/trackSchema.json

Straightforward.
Going to publish new libs on circle ci.
Tested track upload on the local dapp against prod. One upload without the change, another with the change. The latter did not produce the libs validation error.
There is an error log that should no longer appear.
It looked like this before:
```
instrument.js:138 Error validating track metadata Error: TrackSchema validation failed with errors: [{"property":"instance.premium_conditions","message":"is not of a type(s) object","schema":{"type":"object","additionalProperties":false,"properties":{"nft_collection":{"type":"string"},"follow_user_id":{"type":"number"}},"required":[],"title":"PremiumConditions"},"name":"type","argument":["object"],"stack":"instance.premium_conditions is not of a type(s) object"}]
at …
```

Fix premium conditions type in libs trackSchema.json

---

creator-node/src/apiHelpers.ts
creator-node/src/app.ts
creator-node/src/logging.js
creator-node/src/services/stateMachineManager/makeOnCompleteCallback.ts
creator-node/src/services/stateMachineManager/stateMachineUtils.js
creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
creator-node/src/services/stateMachineManager/stateReconciliation/recoverOrphanedData.jobProcessor.ts
creator-node/src/services/stateMachineManager/stateReconciliation/stateReconciliationUtils.js
creator-node/src/services/sync/syncUtil.ts
creator-node/src/utils/cidUtils.ts
creator-node/src/utils/fsUtils.ts
creator-node/src/utils/validateAudiusUserMetadata.ts
creator-node/test/issueSyncRequest.jobProcessor.test.js

This PR removes many of the most frequent logs listed in loggly and moves many to be `debug` in order to lighten the log volume on loggly.
Many of these are either in the top 10 most frequent logs or have big objects logged out.
Just integration tests to make sure nothing broke.
These changes will be monitored on our loggly dashboard to see if it helps with log volume

[CON-389] Remove useless logs and move semi-useful logs to be `debug`

---

creator-node/src/dbManager.js

* Fixes last-minute changes that forgot to remove `.dataValues` since the query result for disk deletion can be used directly
* Adds debug logs for each step of the disk deletion query
Integration tests are planned for disk deletion in the future. I tested locally with a debugger to make sure it's actually deleting now -- no more "Deleted 0/0" on staging
* There shouldn't be any logs that start with `"Deleted 0/0`
* Debug steps of disk deletion by searching for `userFilesQueryResult`, `allUniqueFilesQueryResult`, and `userUniqueFiles`

Fix deletion query and add debug

---

creator-node/scripts/start.sh
creator-node/src/diskManager.js
creator-node/src/index.ts

This PR removes any tmp track artifacts before starting the server in non-devmode. This ensures that the directory is cleared before accepting any uploads.
We should run this as an ad hoc command first before deploying this to make sure it doesn't take forever to clear the directory.
Testing the script locally to make sure nothing breaks and making sure the server actually doesn't start until the command finishes. 
This will partly be monitored with the disk space metrics on our grafana dashboards to see if this makes a difference in clearing disk space

[CON-481] Remove tmp track artifacts on Content Node startup

---

discovery-provider/src/tasks/index.py
discovery-provider/src/utils/redis_cache.py

Removes the removal of cached users/tracks/playlists from indexing
Fixes PLAT-425
Ran locally and tested that indexing still works after user creations, track upload and playlist creation

Remove redis cache indexing

---

creator-node/src/components/replicaSet/replicaSetController.js
creator-node/src/middlewares.js

Skips the storage middleware check for forceWipe syncs because forceWipe syncs free up storage space so it doesn't matter if capacity is already reached.
Tested with debugger to verify that the new code path is hit when data is orphaned (reached the state by creating a user with `A` and updating its replica set with the `/manually_update_replica_set` route).
Syncs with forceWipe should result in success_force_wipe in Grafana. Disk usage should drop on nodes even if they have 95%+ storage utilization.

Skip storage middleware for force wipes

---

creator-node/src/components/replicaSet/replicaSetController.js
creator-node/src/services/stateMachineManager/makeOnCompleteCallback.ts
creator-node/src/services/sync/syncQueue.ts

1. orphaned data queue should enqueue syncs to front (via mergePrimaryAndSecondaryController)
2. recurring sync queue should enqueue to front
3. processSync queue should process at front
4. immediate recurring queue does not ever use forceWipe so no changes needed there
Manually tested with local e2e:
1. `A seed create-user`
2. Confirmed no recurring syncs issued, and replica set created + synced
3. Called `POST <primary>/manually_update_replica_set` and changed 1 secondary
4. Confirmed that primary queue executed merge_primary sync job with `forceWipe = true` and `lifo: true` (see below)
5. Confirmed other sync jobs with forceWipe not set do not use lifo: true
6. Confirmed new secondary received `sync-processing-queue` jobs with `lifo: false` and correctly synced
7. Confirmed old …

CON-482 Prioritize force wipe syncs

---

creator-node/src/services/ContentNodeInfoManager.ts
creator-node/src/utils/asyncRetry.ts

This PR fixes a bug were an exception was never getting rethrown in `asyncRetry` causing things to never delete
Tested locally and with CI
This'll be monitored using the network tab on the client as well as with logs on loggly

Rethrow errors in asyncRetry

---

creator-node/src/diskManager.js
creator-node/src/index.ts

This PR adds the tmp track artifacts dir size to the log for it
https://stackoverflow.com/questions/7529228/how-to-get-totalsize-of-files-in-directory
log sample
```
{"name":"audius_creator_node","clusterWorker":"master","hostname":"df4216f4bd7d","pid":89,"level":30,"msg":"old tmp track artifacts deleted : 4.0K\t/file_storage/files/tmp_track_artifacts\n : 0.054sec","time":"2022-10-26T21:02:38.585Z","v":0,"logLevel":"info"}
```
Testing locally and on CI to make sure the log shows up
This change will be monitored on loggly

Add directory size to tmp track artifacts deletion logs

---

creator-node/src/services/ContentNodeInfoManager.ts

with 10retries would go for 17min, cut that down to 7 retries to stop at (hopefully) 1-2min
n/a
n/a

Lower ensurePrimaryMiddleware maxRetries

---

creator-node/src/config.js
creator-node/src/diskManager.js
creator-node/src/index.ts

This PR adds
- An env var to gate disk pruning
- Removing log volume (only prints files it will delete, the rm command)
- Move where disk pruning gets kicked off. It now starts one minute after all cluster workers have been launched
- Bugfix where weren't iterating over the full list of CIDs
Testing on stage cn7 to verify that it correctly finds and deletes content
Logs prefixed with `diskManager` to list files we're about to delete

Gate disk prune behind env var + logging reductions

---

creator-node/src/fileManager.js
creator-node/src/utils/decisionTree.ts

current `saveFileForMultihashToFS` logs are way too big. Remove big chunk of those logs, plus downgrade to debug
Some associated decisionTree changes but should be fully back-compat
TODO test on staging
Should no longer see any `saveFileForMultihashToFS` logs on loggly, and when tailing logs in container, the logs should be much smaller

CN Clean up `saveFileForMultihashToFS` logs

---

creator-node/src/services/ContentNodeInfoManager.ts

There's no great way to get retry information from asyncRetry (and there probably shouldn't be?) so to make the log message clearer, I removed the retry info

Remove retry info from log msg

---

discovery-provider/scripts/start.sh

before it would attempt to block server + celery start by running in catchup mode, but if this failed it would prevent es-indexer from starting and no indexer would run.
simply start es-indexer normally... if we want more coordination we can do it in application code.  This is how it will be if es-indexer is in a standalone container also.

simplify es-indexer startup behavior

---

discovery-provider/nginx_conf/nginx.conf

Add gzip to discovery endpoints - it's currently not compressed
Fixes PLAT-428
Tested by in 3 cases on stage:
* openresty disabled
* On the box set the env var `audius_openresty_enable=`
* openresty enabled without public url
* On the box set the env var `audius_openresty_enable=true` and `audius_discprov_url=`
* openresty enabled with public url
* On the box set the env var `audius_openresty_enable=true` and `audius_discprov_url=https://discoveryprovider3.staging.audius.co`
In each case made this request and checked for gzip

Add gzip to discovery

---

discovery-provider/src/tasks/user_replica_set.py
discovery-provider/src/utils/eth_contracts_helpers.py

Cache the content node info from the rpc call while indexing
This lead to intermittent indexing processing times of 40+ seconds
Fixes PLAT-427
Ran 2e2 locally and validated that it wrote to redis

Cache cn while indexing replica set

---

creator-node/nginx_conf/nginx.conf

Remove error from proxy_cach_use_stale for /health_check in openresty. What this directive does is return a stale version of the response while the origin server encounters the listed errors. With health_check in particular we never want to return a stale value when the origin server errors after the 1s cache expiry. I left the error in for /ipfs because that's probably fine to cache.
Verified this bug by 
1. with the node server is running, make sure /health_check returns a value
2. kill -9 the node server
3. make sure /health_check returns the same value with the same signature as before
Tested locally by 
1. with the node server is running, make sure /health_check returns a value
2. kill -9 the node server
3. make sure /health_check returns an error
4. bring node server back up
5. make …

Remove error from proxy_cach_use_stale

---

creator-node/src/services/sync/primarySyncFromSecondary.js

Removes redis set fail-safes that were causing secondary->primary syncs to fail for users who have rows that are identical in every column except clock value.
Ran `curl -X POST "http://cn1_creator-node_1:4000/merge_primary_and_secondary?wallet=0x7d273271690538cf855e5b3002a0dd8c154bb060&endpoint=https://audius-content-3.cultur3stake.com&syncEvenIfDisabled=true&forceWipe=true"` to sync from a prod secondary to my local CN1 as primary before and after these changes using a debugger to check each step. I also manually inspected the duplicates to ensure this change doesn't lead to any corrupted state.
We shouldn't see the following error anymore: `Error - Failed to save entries to DB: Failed to add all entries to redis set for FILTER_OUT_ALREADY_PRESENT_DB_ENTRIES_FETCHED_ENTRIES_SET`.

Remove redis primarySyncFromSecondary fail-safes

---

creator-node/src/serviceRegistry.js

Skip L2 registration if entity manager enabled
This prevents initing an unneeded contract in content node while using entity manager
The issue was found when switching from poa to our own nethermind nodes on stage
Ran the system locally and ensured the new log was printed

CN skip l2 registration if entity manager enabled

---

monitoring/exporters/postgres/Dockerfile
monitoring/exporters/postgres/docker-entrypoint.sh
monitoring/exporters/redis/Dockerfile
monitoring/exporters/redis/docker-entrypoint.sh

Splitting off stable changes from: #3959.
N/A. Images were manually built and pushed to docker hub:
* https://hub.docker.com/r/audius/exporter-postgres
* https://hub.docker.com/r/audius/exporter-redis
N/A

INF-266 Add Postgres and Redis Exporter docker images

---

.circleci/config.yml

* Always compare current commit to previous commit, not `main` (since the commit has already been merged into `main`).
* Always provide `git_tag` parameter for deploy jobs, to eliminate race condition where we deploy latest master tag before `master` tag has been built.
* Previous concerns of deploying an old version are no longer valid due to #4024 
Reproduced `git diff` situation locally.
#eng-deploys

INF-298 fix race conditions for autodeploying

---

creator-node/src/utils/decisionTree.ts

Fixes the following error which was caused by not binding the bunyan logger:
```
bunyan usage error: /usr/src/app/build/src/utils/decisionTree.js:49: attempt to log with an unbound log method: `this` is: <ref *1> Object [global] {
global: [Circular *1],
clearInterval: [Function: clearInterval],
clearTimeout: [Function: clearTimeout],
setInterval: [Function: setInterval],
setTimeout: [Function: setTimeout] {
[Symbol(nodejs.util.promisify.custom)]: [Getter]
},
queueMicrotask: [Function: queueMicrotask],
clearImmediate: [Function: clearImmediate],
setImmediate: [Function: setImmediate] {
[Symbol(nodejs.util.promisify.custom)]: [Getter]
},
regeneratorRuntime: {
wrap: [Function: wrap],
isGeneratorFunction: [Function (anonymous)],
mark: [Function (anonymous)],
awrap: [Function (anonymous)], …
```

Fix decision tree logger not bound

---

audius.code-workspace

It's sometimes useful to see some files in the dev-tools folder. Nice to have it in the workspace without having to open a new vscode window.
n/a
n/a

Include dev-tools in the workspace file

---

.circleci/config.yml

Add an additional hold job before exposing all `unreserve-*` jobs. This minimizes the number of pending jobs from 17 to 3 for commits on `main`.
Additionally add the `-all` suffix to denote jobs that deploy to all nodes within a service.
Need to merge into `main` and see Github Status Checks for newer commits.
#eng-deploys

INF-263 minimize status noise on `main`

---

discovery-provider/alembic/versions/42d5afb85d42_create_audio_transactions_history.py
discovery-provider/integration_tests/tasks/test_index_spl_token.py
discovery-provider/integration_tests/utils/test_helpers.py
discovery-provider/src/models/users/audio_transactions_history.py
discovery-provider/src/tasks/index_rewards_manager.py
discovery-provider/src/tasks/index_spl_token.py
discovery-provider/src/tasks/index_user_bank.py
discovery-provider/src/utils/helpers.py

Note: this PR picked up changes in rewards indexing which were already reviewed, please disregard. Please just review the last 2 commits!
spl-token indexing for audio_transactions_history table. Includes external transfer receive instructions and purchase $AUDIO instructions. Ignores create-account instructions.
Also refactored some helper functions for handling solana tx metadata.
Modified/added unit tests.

Index spl-token for audio_tx_history

---

creator-node/src/services/stateMachineManager/index.js
creator-node/src/services/stateMachineManager/stateMachineUtils.js
creator-node/src/services/stateMachineManager/stateMonitoring/index.js
creator-node/src/services/stateMachineManager/stateReconciliation/index.js
creator-node/test/StateMonitoringManager.test.js

- Fixes `onFailure` not being recognized due to calling `queue.on` instead of `worker.on` (this is most likely what made jobs not re-enqueue properly)
- Makes `onError` run the same recovery code as `onFailure` (`onError` catches "missing lock for job" errors, so we want to recover from those instead of only relying on onFailure)
- Adds global `onFailure` and `onError` callbacks using QueueEvents. This should be more reliable than per-worker events because it uses Redis streams instead of pub-sub
Tested 2 failure scenarios with debugger:
1. Job throws an error in its processor - it recovers and re-enqueues
2. Job throws an error in its onComplete callback - it's not able to recover but logs  `Fatal: onComplete errored. Cron queues may be broken`
* Look out for the following error log: …

[CON-487] Make state machine error recovery more reliable

---

creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts

Fixes a TypeError caused by calling a function on `syncStatus`, which is sometimes null - for example, when the processing node expired the redis key.
CI passing should suffice.
Make sure no more errors are logged for: `TypeError: Cannot read property 'startsWith' of null`.

[CON-486] Optional chain potentially null syncStatus

---

creator-node/src/tracer.ts

This PR wraps the bunyan log to send add logs as trace events that'll get send to CloudTrace.
Run locally and used the dev CloudTrace instance to make sure logs were forwarded properly.
These changes will be monitored on our tracing visualization service. Logs are show as events.
Screenshot above for reference

Add hook to bunyan to create tracer events

---

creator-node/src/serviceRegistry.js
creator-node/src/services/sync/syncImmediateQueue.js
creator-node/src/services/sync/syncQueue.ts
creator-node/test/AsyncProcessingQueue.test.js
creator-node/test/lib/app.js
creator-node/test/sync.test.js

This PR adds an extra step in the constructor for the `syncQueue` and `immediateSyncQueue` to clear any old/leftover active queue jobs. 
These active jobs are usually garbage leftover from previous runs when the server restarts or crashes in the middle of a sync. 
Tested locally by looking for the log msg saying active jobs were being deleted. 
Other than that, no new tests were added.
This change will be monitored using the Bull Dashboard on Grafana and we _should_ see a steady decrease in active bull queue jobs to a ore realistic number.
This can also be monitored with logs with the msg
`removing ${oldActiveJobs.length} leftover active sync jobs`

[CON-471] Remove leftover active sync jobs during `syncQueue` start up

---

creator-node/src/components/tracks/tracksComponentService.ts
creator-node/test/dbManager.test.js
creator-node/test/pollingTracks.test.js

While tracing out the upload flow, I've gone ahead and converted vanilla js files to typescript. This is the first PR
Using the original integrations tests to make sure things didn't break
This change will be monitored with the typechecker

Convert `trackComponentService` to typescript

---

creator-node/src/index.ts
creator-node/src/utils/clusterUtils.ts

Some nodes are not appearing to run logic that the init worker is supposed to run, possibly because they're starting on a pid >1. This PR makes init worker detection pid-agnostic by passing an env var to the child process. This is more reliable than only checking pid.
Verified that the first worker's log message shows that it's marked as the init worker and that subsequent workers do not log the init worker's message.
Check the state monitoring queue on nodes that are having issues initializing (like Staked) and make sure they're adding jobs.

Make init worker detection more reliable

---

creator-node/src/config.js
creator-node/src/services/stateMachineManager/stateReconciliation/SecondarySyncHealthTracker.ts
creator-node/test/stateMonitoringUtils.test.js

This is to temporarily disable `SecondarySyncHealthTracker` class from recording and processing syncs because scanning redis for sync data was causing redis to become unavailable. 
In this pr:
- add 2 env vars, `recordSyncResults` and `processSyncResults` to gate `SecondarySyncHealthTracker` logic
- Unit test updated to check hard-codes sync success/fail counts and success rate
- Check `/health/bull` for findSyncRequests and findReplicaSetUpdates queue jobs correctly processing jobs with the hardcoded values
- Check redis to see if `SecondarySyncRequestOutcomes-Daily*` keys exist by running `KEYS *SecondarySyncRequestOutcomes-Daily*` in redis cli
- Check `/health/bull` for findSyncRequests and findReplicaSetUpdates queue jobs correctly processing jobs with the hardcoded values

Add flag to disable sync tracking

---

discovery-provider/src/api/v1/users.py
discovery-provider/src/api/v1/users_unit_test.py

There was a bug in the artist dashboard where empty responses would get marshalled into `{ '*': null }`, which caused the front end to crash. Adding `skip_none=True` to our marshalling model ensures we return an empty dict if there are no responses. Added a regression test as well to ensure this doesn't happen again. 
Note - fixing this uncovered another bug within the indexer for monthly play aggregates. Users are missing data around 2020-2021 which was causing empty results to be sent to the front end in the first place. So even with this PR, users may still see no data for certain years. Isaac is working on the fix for this separately. 
Added unit test. Also deployed changes to staging to make sure it worked appropriately

Fix artist dashboard on no plays

---

creator-node/src/config.js
creator-node/src/fileManager.js

Envvar `trackUploadArtifactDeletionEnabled` to control `diskManager.removeTrackFolder()`, since `backgroundDiskCleanupCheck` now already clears artifacts after some time threshold, so real-time deletion is no longer necessary and unnecessary performance overhead
The main reason for disabling this though, is bc we actually want to keep upload artifacts for a few days for debugging purposes
n/a
n/a

CN - trackUploadArtifactDeletionEnabled

---

.circleci/bin/deploy-ci.py

Sometimes, pulling from Docker Hub can take up to 165 seconds as seen here in a manual deployment:
```
ubuntu@creator-8:~$ audius-cli launch creator-node
ethOwnerWallet is not set
CPUs:	8	(required: 8)
Memory:	31GB	(required: 16GB)
Storage:	247GB	(required: 2048GB)
System does not meet requirements
Do you want to continue? [y/N]: y
[+] Running 19/19
⠿ autoheal Pulled                                                                       0.6s
⠿ logspout Pulled                                                                       0.5s
⠿ exporter_linux Pulled                                                                 0.6s
⠿ db Pulled                                                                             0.6s
⠿ exporter_postgres Pulled …
```

INF Extend timeout for `audius-cli launch`

---

discovery-provider/alembic/versions/3e99d419fd63_add_sig_to_indexing_checkpoints.py
discovery-provider/alembic/versions/93fc0b994aba_spl_token_backfill.py
discovery-provider/alembic/versions/ab4f1c314c43_user_bank_backfill.py
discovery-provider/alembic/versions/fcb40409e0a4_rewards_manager_backfill.py
discovery-provider/default_config.ini
discovery-provider/src/app.py
discovery-provider/src/models/indexing/indexing_checkpoints.py
discovery-provider/src/models/indexing/spl_token_backfill_transaction.py
discovery-provider/src/models/rewards/rewards_manager_backfill.py
discovery-provider/src/models/users/user_bank_backfill.py
discovery-provider/src/tasks/index_rewards_manager_backfill.py
discovery-provider/src/tasks/index_spl_token_backfill.py
discovery-provider/src/tasks/index_user_bank_backfill.py
discovery-provider/src/utils/redis_constants.py

Backfill user bank transaction data into `audio_transactions_history` by making a *duplicates* of `index_user_bank.py` that stops at the transaction whose signature matches the`backfill_stop_sig` arg.
The following commits do the same for `index_rewards_manager.py` and `index_spl_token.py`.
Tested on remote-dev that is indexing prod. Set `backfill_stop_sig` to a known signature and observed the backfilling occurring.
Adds logs for the backfilling indexer.

[PAY-664] Backfill audio_tx_history userbank indexing

---

discovery-provider/es-indexer/src/conn.ts
discovery-provider/es-indexer/src/main.ts

for nodes over 90% disk usage, if a red index is found delete all indexes before starting indexer.
This should provide enough headroom to make new indices.

es-indexer: if red index, delete all indices

---

identity-service/src/config.js
identity-service/src/relay/txRelay.js

The ability to turn reconfigs off in identity was never merged to main, only to release hotfix branch. This cherry picks @raymondjacobson's commits to enable that functionality.
Was running on prod for a week.
There should be zero reconfigs sent to chain.

Ability to filter out reconfigs in identity relays

---

discovery-provider/alembic/versions/f91c041d1d8d_rebuild_aggregate_monthly_plays_table.py

This [migration](https://github.com/AudiusProject/audius-protocol/pull/4252/files) was generated off a stale head and is breaking builds on main. Update to be on top of correct head.
Revision id 3e99d419fd63 is from https://github.com/AudiusProject/audius-protocol/pull/4242/files

Fix multiple migration heads breaking builds on main

---

discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
discovery-provider/integration_tests/utils.py
discovery-provider/src/tasks/entity_manager/entity_manager.py
discovery-provider/src/tasks/entity_manager/social_features.py
discovery-provider/src/tasks/entity_manager/utils.py
libs/src/api/Users.ts
libs/src/api/entityManager.ts
libs/src/services/dataContracts/EntityManagerClient.ts

Add subscriptions to entity manager as a part of social actions (subscribe, unsubscribe).
Create `addUserSubscribe` and `deleteUserSubscribe` in libs user API to call `manageEntity`.
Integration tests.
Uses existing entity manager logs.

Add subscriptions to entity manager

---

creator-node/src/services/sync/secondarySyncFromPrimary.ts

Changes some sync logs from info to debug to avoid log pollution. These logs get printed for every 10 files processed, and a single sync can process thousands of files.
CI passing is sufficient.
We shouldn't see logs for "processing files {X} to {Y}" outside of local dev.

Change frequent sync logs from info to debug

---

discovery-provider/integration_tests/premium_content/test_access.py
discovery-provider/src/abis/ERC1155.json
discovery-provider/src/abis/ERC721.json
discovery-provider/src/api/v1/models/tracks.py
discovery-provider/src/api/v1/tracks.py
discovery-provider/src/premium_content/helpers.py
discovery-provider/src/premium_content/premium_content_access_checker.py
discovery-provider/src/queries/get_premium_track_signatures.py
discovery-provider/src/schemas/track_schema.json
libs/src/sdk/api/generated/full/.openapi-generator/FILES
libs/src/sdk/api/generated/full/apis/TracksApi.ts
libs/src/sdk/api/generated/full/models/TrackFull.ts
libs/src/sdk/api/generated/full/models/index.ts
libs/src/services/schemaValidator/schemas/trackSchema.json
libs/src/utils/types.ts

Add endpoint to get etheurem-nft-gated premium track signatures. It works by checking for a positive balance for any of the user's ethereum wallets for a given ethereum nft collection contract address. For the collections that the user owns, signatures are generated for all premium tracks that are gated by that nft collection.
This PR also updates the premium conditions types accordingly.
Solana nfts access check is not implemented in this PR.
Spun up services on remote box and pointed to the mainnet ethereum chain within the new endpoint helper function, passed in corresponding user wallet <> contract address <> token ids combinations and made sure that signatures were generated accordingly.
Need to test again with the latest parallelization commit added.
Edit: tested with the …

[PAY-489] Add endpoint to get ethereum-nft-gated premium track signatures

---

discovery-provider/src/app.py
discovery-provider/src/queries/get_health.py
discovery-provider/src/tasks/index_rewards_manager_backfill.py
discovery-provider/src/tasks/index_spl_token_backfill.py
discovery-provider/src/tasks/index_user_bank_backfill.py

Adds fields in health check that tell us whether the backfill indexing for `audio_tx_history` is complete by caching the results of each indexer's `check_if_backfilling_complete` fns in redis. Also checks the redis cache in the `check_if_backfilling_complete` functions themselves to return early if we've already determined that indexer is complete.
Observed behavior in remote-dev that is indexing prod.
Lots of error logs if something goes south.

[PAY-722] Check if audio_tx_hist backfilling complete

---

monitoring/prometheus/generateProm.js

Adds scrapers for all upcoming exporters. Lack of a live exporter will not affect prometheus, outside of a ping to an unresponsive URL every 30 seconds.
Compared local runs to production runs. No endpoints were dropped, only new exporter endpoints were added based on the service type.
N/A until the next Prometheus release.

CON-445 add new and future exporter scrapers

---

creator-node/src/components/healthCheck/healthCheckComponentService.js
creator-node/src/components/healthCheck/healthCheckComponentService.test.js
creator-node/src/components/healthCheck/healthCheckController.js
creator-node/src/config.js

Exposes all current config values in a `/config_check` route
Hides all sensitive config values
Marks all sensitive configs accordingly
REVIEWER REQUEST - pls double check that i marked all sensitive envvars appropriately
New unit test
n/a

CON-488 Expose CN config in route (excludes sensitive configs)

---

dev-tools/commands/src/upload-track.mjs

Add ability to make track premium when using `audius-cmd upload-track`
On remote box

Add ability to set premium track with audius-cmd

---

identity-service/src/routes/relay.js

to avoid getting this error:
```
(node:64) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'wallet' of null
at /usr/src/app/build/src/routes/relay.js:76:88
at /usr/src/app/build/src/routes/relay.js:78:15
at async /usr/src/app/build/src/apiHelpers.js:6:26
```

Check for existent of user

---

creator-node/src/components/healthCheck/healthCheckComponentService.js
creator-node/src/components/healthCheck/healthCheckComponentService.test.js
creator-node/src/components/healthCheck/healthCheckController.js
creator-node/test/healthChecks.test.js

1. Route is broken bc missing leading `/`
2. Convert route response from JSON string to JSON object
3. Change route response to JSON object
4. Add integration test for route response
new test
n/a

CON-488 Fix CN GET /config_check route

---

monitoring/docker-compose.yml
monitoring/prometheus/generateProm.js

Group exporter metric names by common prefix.
Also, remove `GF_INSTALL_IMAGE_RENDERER_PLUGIN` since this plugin did not offer the functionality we were looking for (due to the VPN not allowing us to unfurl Grafana previews in Slack) and that plugin is causing current grafana builds to break. 
TODO: Regenerate configs on prod before merging.

CON-445 Add prefixes for new exporters

---

discovery-provider/src/tasks/index_rewards_manager_backfill.py
discovery-provider/src/tasks/index_spl_token_backfill.py

Fixes an issue that breaks the backfilling spl-token indexer - it would fail if the transaction failed. This fix makes it skip the failed transaction instead.
+ a little logging wording change
Observed it working on remote-dev that is indexing prod.

Hotfix index_spl_token_backfill.py

---

discovery-provider/src/queries/get_health.py
discovery-provider/src/queries/get_health_unit_test.py
discovery-provider/src/tasks/index_rewards_manager_backfill.py
discovery-provider/src/tasks/index_spl_token_backfill.py
discovery-provider/src/tasks/index_user_bank_backfill.py

Adds checks in get_health to check progress of each backfill indexer.
For each of the indexers:
`stop_sig` and `stop_slot` are the sig/slot that the backfill indexer should stop at. Taken from IndexingCheckpoints table. Won't exist until the backfill indexer has started.
`latest_processed_sig` and `latest_processed_slot` are the last sig/slot that the backfill indexer has processed. Taken from row in `xxx_backfill_tx` that has the highest slot number. Won't exist until the backfill indexer has started processing txs, which can be a while after it has started.
`min_slot` and `min_sig` come from the row in `AudioTransactionsHistory` that are of the correct type, have the lowest slot number, and are also less than the `stop_slot`. Represents the first row that the backfill indexer added to …

Check backfillers progress

---

creator-node/src/middlewares/readOnly/readOnlyMiddleware.js
creator-node/src/middlewares/readOnly/readOnlyMiddleware.test.js
creator-node/src/serviceRegistry.js

Previously we were in a catch 22 where we needed the server to be up before spID was recovered, but also if the server was up that means we could get incoming requests to POST routes before the spID has been recovered.
In order to alleviate these concerns we're going to make the server read only until spID has been recovered. This should be a safe change to make because for
- incoming GET requests should be resolved and POST requests error, exactly what happens when the server is down
- Outgoing requests, the node on the other end is likely up so should be fine to make requests. Plus if this is a new service it likely has no users in the replica set so likely has no requests to make anyway. In the event an outgoing request triggers an incoming request, it will behave as above.
One thing …

Make server read only until spID has been recovered

---

dev-tools/audius-compose
discovery-provider/integration_tests/conftest.py
docker-compose.test.yml

Will change `audius-compose test` to
- `audius-compose test build`
- `audius-compose test run discovery-provider <pytest args>`
- `audius-compose test down`
However, you only need to run the second command to run tests and it is all inclusive.
See commands above
NA

Speed up local discprov tests

---

libs/src/api/File.ts

When content can't be found on the user's replica set we try the entire network. This means about 60 network calls, one for each registered CN. But, we also make a request for both the new and legacy image formats. So 120 network calls. And then we retry this 3 times. So 480 network calls for each piece of content that is truly unavailable :sweat_smile:
This PR removes the retries of the entire network to limit the number of requests

[C-1454] When content is unavail in replica set, only try entire network once

---

creator-node/nginx_conf/nginx.conf

This PR contains 2 changes
- Do not cache /file_lookup route anymore (route is deprecated, will be deleted after next release)
- Do not serve stale content. This was causing bugs where initially content was unavailable and the server responded with 500 and openresty would return `x-cache-status: STALE` but if the content was subsequently made available it wouldn't serve until it invalidated the stale content and it took a while to do that. I'm sure there's a better fix for this but seems better to disable since this is an simple optimistic cache. 
Tested locally by disabling this option and verifying that we don't see status `STALE` anymore. Also content that was made available is returned immediately.
No easy way to monitor this unfortunately. But can test very thoroughly because content …

Clean up nginx rules for content caching

---

creator-node/src/config.js
creator-node/src/fileManager.js
creator-node/src/routes/files.js
creator-node/src/services/sync/primarySyncFromSecondary.js
creator-node/src/services/sync/secondarySyncFromPrimary.ts
creator-node/src/services/sync/skippedCIDsRetryService.js
creator-node/test/sync.test.js

- rename `saveFileForMultihashToFS()` to `fetchFileFromNetworkAndSaveToFS()` for accuracy
- change return format from `Error?` to `{error?: Error, storagePath?: String}` and update all references
- remove redundant `fs.mkdir` in `getDirCID()`
- remove unnecessary redis cache `getStoragePathQueryCacheKey` step in `getDirCID()`
- minor getDirCID() code cleanup / re-orgs
TODO
TODO

dm-restructure-fetchCIDInNetwork Changes

---

discovery-provider/nginx_conf/nginx.conf

Follow `$upstream` pattern so nginx doesn't die if upstream is down

Fix nethermind reverse proxy config

---

libs/src/sdk/api/generator/README.md

Change OpenAPI generator README gen:dev to point to `localhost`

Change OpenAPI generator README gen:dev to localhost

---

identity-service/src/featureFlag.js
identity-service/src/notifications/index.js
identity-service/src/notifications/processNotifications/createNotification.js
identity-service/src/notifications/processNotifications/index.js
identity-service/src/notifications/sendNotifications/formatNotification.js
identity-service/src/notifications/sendNotifications/index.js
identity-service/src/notifications/utils.js

Read subscriptions from discovery DB in identity behind the `READ_SUBSCRIBERS_FROM_DISCOVERY_ENABLED` flag. If flag is off: reads from `Subscriptions` in identity (current behavior)
Tested against staging DB with debug log statements:
- Turn flag on
- Subscribe account 1 to account 2 and vice versa. Verify subscriptions with API
- On each account:
- Upload a track
- Watch logs to verify discprov path is being hit
- Verify the other account received a notification
- Turn flag off
- Same flow as above. Verify parity.
Fails silently with error in logs. No create notifications are sent.

Read subscriptions from discovery in notifications system in identity

---

creator-node/package-lock.json
creator-node/src/fileManager.js
creator-node/src/routes/files.js

Current flow:
1. client makes getCID (or getDirCID) request to CN
2. CN doesn't have it locally
3. sets attemptedStateFix locally to true
4. sequentially makes getCID (or getDirCID) requests to all other CNs
5. each other CN, if it doesn't have it:
6. sets attemptedStateFix(CID) = true
7. sequentially makes getCID requests to all other CNs
8. these other nodes, if they don't have it:
9. return 404 since attemptedStateFix(CID) = true
This is fine bc of the attemptedStateFix via Redis which ensures each CN only makes network fetches once per day for a given CID/dirCID, but its still 2x number of required requests
New flow:
1. client makes getCID (or getDirCID) request to CN
2. CN doesn't have it locally
3. sets attemptedStateFix locally to true
4. sequentially makes getCID (or getDirCID) …

fetchFileFromNetwork bugfix + Add localOnly queryParam for CN->CN network fetches to prevent additional network fetches internally

---

libs/src/api/Users.ts

Instead of throwing (ha, no pun intended) out all the original error details and throwing our own new error, forward the error details so that the consumer can decide what to do with them. This is necessary for [PAY-724](https://linear.app/audius/issue/PAY-724/account-for-relay-403s-on-signup-analytics) so that we can have the client react differently depending on why the error was thrown.
Tested locally manually with client running changes necessary for PAY-724 against staging

Libs: Expose error details to consumer

---

discovery-provider/src/tasks/entity_manager/entity_manager.py
discovery-provider/src/tasks/entity_manager/playlist.py
discovery-provider/src/tasks/playlists.py

When creating or updating a playlist, premium tracks cannot be included. This PR handles that, both in old indexing flow and entity manager.
Not yet tested but going to... Will update this part afterwards.
Exceptions raised would be included in the logs.

[PAY-646] Prevent the adding of a premium track to playlist in DN indexing

---

creator-node/src/components/replicaSet/replicaSetController.js
creator-node/src/components/replicaSet/syncQueueComponentService.ts
creator-node/src/config.js
creator-node/src/dbManager.js
creator-node/src/services/sync/secondarySyncFromPrimary.ts
creator-node/src/services/sync/secondarySyncFromPrimaryUtils.ts
creator-node/src/services/sync/syncImmediateQueue.js
creator-node/src/services/sync/syncQueue.ts
creator-node/src/services/sync/syncUtil.ts

2 factor authentication for manual sync:
1. spID must be foundation node
2. sync request body must provide password which matches locally stored password string (non-null)
Password string is set as override directly on node, and not exposed anywhere
spID check uses hardcoded IDs
Tested locally e2e:
- rejected if spID mismatch
- rejected if password not provided
- rejected if password mismatch
- succeeds forceResync if password + spID match
- succeeds forceWipe if password + spID match
- succeeds regular sync if password + spID match
- succeeds immediate = true and immediate = false
- confirm password not visible via `/config_check`
Should not introduce any sync regressions - monitor bull dashboards + sync metrics

Foundation node sync override for easier manual syncs for test purposes

---

identity-service/sequelize/migrations/20221115014540-blocked-from-emails-column.js
identity-service/src/models/user.js
identity-service/src/notifications/sendNotificationEmails.js
identity-service/src/routes/relay.js
identity-service/src/routes/welcomeEmail.js
identity-service/src/utils/antiAbuse.js

Prevent welcome emails and other email notifs from being sent to abusive users.
The welcome email is triggered to get sent by the client, right after sign up succeeds. Therefore, we rely on identity and the hereby newly added `isBlockedFromEmails` column to determine whether it is sent.
No test yet. Goal is to test against stage by signing up with a user that would be seen as abusive, determined by the error codes for blocking emails, and making sure that user does not get emails sent to them.
No monitoring outside of noticing much less welcome emails being sent to users, and also seeing how many users have the `isBlockedFromEmails` flag set to true.
Would be a good idea to get more visibility on this, and other blocking reasons for users sooner rather than later.

[PAY-707] Block abusive users from emails

---

identity-service/src/notifications/processNotifications/createNotification.js
identity-service/test/processNotifications/createNotification.js

* Updated the create notification for the subscribers
* NOTE: previously we were iteratively going through each notification and this has been switch to a bulk query instead of individual queries which shows over 10x improvement in time when there were 100k users
Wrote a test for bulk user create action with subscription

Optimize create subscription notifications bulk

---

creator-node/src/routes/files.js
creator-node/src/routes/tracks.js

This PR adds a new route `/batch_id_to_cid` that translates a batch of trackBlockchainIds to copy320 CIDs.
The return schema looks like 
```
{
'trackBlockchainId': 'multihash'
}
```
Tested locally by creating a user, uploading a track, and running curl to fetch the copy320.
And he's a test on the node cli to remove any suspicion that the functional code used to create the actually does work.

[CON-517] Add a route to translate trackBlockchainId to copy320 CID

---

discovery-provider/alembic/versions/1eec1d124caf_create_index_on_users_created_at.py

getting latest user is really slow because of new latest entities change.
https://github.com/AudiusProject/audius-protocol/blob/main/discovery-provider/src/queries/get_latest_entities.py#L46-L47
creating index on both created_at and user_id for deterministic ordering.
Confirmed index scan on stage.

Add user created_at index

---

identity-service/src/notifications/trendingTrackProcessing.js
identity-service/test/processNotifications/trendingTrackNotification.js

This was using latest block from discovery which will cause notifs to skip down the line. Instead set it to the last block identity knows about.

Use max block number for trending notif query

---

discovery-provider/src/api/v1/users.py

We need an endpoint to get all the favorited albums and one for playlists to support offline mode work. The client will need the full list of the user's favorites. We can handle the pagination on client side.
Haven't worked in this repo before, so please lmk if I'm missing steps.

[C-1547] Add favoriteAlbums and favoriteTracks routes

---

discovery-provider/src/api/v1/tracks.py

Allow streaming unlisted tracks so users can listen to their unlisted tracks with `STREAM_MP3` feature flag on.
In the future, premium content will gate the streaming on ownership for unlisted tracks, but for now, we'll expose it to fix the more common use case.

[C-1558] Allow streaming of unlisted tracks

---

creator-node/src/diskManager.ts
creator-node/src/utils/fsUtils.ts
creator-node/src/utils/utils.ts
libs/src/utils/fileHasher.ts

- Changes spammy logs from info to debug
- Removes a testing log that slipped through
- Logs error message when disk deletion fails
N/A - just logs
This is a fast follow that I'll deploy to CN5 to make sure log spam is reduced and deletion errors are informative (expecting them all to be "File not found"). FileHasher log spam won't be reduced until the next libs release.

Clean up storage path logs

---

monitoring/healthz/src/DiscoveryHealth.tsx

Fix storage use % and db size for content nodes in healthz
Current
New
Ran healthz locally and verified the data is consistent with health check.
This is the monitoring 🙂

Update storage properties for content nodes in healthz

---

creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts

This is so that aborted syncs are not recorded. 
Current environment:
```
127.0.0.1:6379> keys PRIMARY*
1) "PRIMARY_TO_SECONDARY_SYNC_FAILURE::2022-11-30::https://creatornode9.staging.audius.co/::0xa722151fdff6dc5c94803b4712d63730ea6feb08"
2) "PRIMARY_TO_SECONDARY_SYNC_FAILURE::2022-11-30::https://creatornode8.staging.audius.co/::0xa722151fdff6dc5c94803b4712d63730ea6feb08"
127.0.0.1:6379> hgetall PRIMARY_TO_SECONDARY_SYNC_FAILURE::2022-11-30::https://creatornode9.staging.audius.co/::0xa722151fdff6dc5c94803b4712d63730ea6feb08
1) "abort_sync_in_progress"
2) "1"
127.0.0.1:6379> hgetall PRIMARY_TO_SECONDARY_SYNC_FAILURE::2022-11-30::https://creatornode8.staging.audius.co/::0xa722151fdff6dc5c94803b4712d63730ea6feb08
1) "abort_sync_in_progress"
2) "1"
```
- forced an abort and observed logs …

Only record sync failures

---

discovery-provider/integration_tests/tasks/test_index_profile_challenge_backfill.py
discovery-provider/src/app.py
discovery-provider/src/queries/health_check.py
discovery-provider/src/tasks/index_profile_challenge_backfill.py

Backfills the social actions from the env var to current - note it will continue to enqueue to the redis rewards manager even after it catches up, but that should be fine
Wrote a test to ensure it dispatches the events

Add profile backfill job

---

creator-node/src/config.js

This is part of the cleanup with the [SecondarySyncHealthTracker refactor](https://github.com/AudiusProject/audius-protocol/pull/4353)
Variables not used so no impact on functionality 
Monitor `SecondarySyncHealthTracker` logs but this change shouldnt impact anything

Remove unused sync env vars

---

creator-node/src/routes/files.js
creator-node/src/utils/index.ts

Fixes an import for a function that was moved. This went unnoticed because it only impacts file retrieval when the file isn't able to be found at the standard path and so it tries to recompute the legacy path for the CID.
CI is sufficient.
There shouldn't be any more errors for `COMPUTE_LEGACY_FILE_PATH_FAILURE`.

Update import for computing legacy CIDs

---

creator-node/src/utils/fsUtils.ts

Fixes `mkdir` being called on the grandparent of a CID instead of the parent when it's nested. This is something I noticed for some legacy CIDs after turning debug logs on for prod CN5. It didn't corrupt any data and only caused some legacy CIDs to fail to be migrated until this is merged.
Relying on CI instead of manual tests and will use debug logs to confirm the path is still correct. It still uses the same path logic that I already double-checked, so the risk for data loss is minimal.
Look for errors with "Failed to copy some legacy files" and "ENOENT"

Fix CN mkdir called on grandparent instead of parent

---

creator-node/src/dbManager.js
creator-node/src/diskManager.ts

Makes storagePath migrations ignore errors and still update the storagePath db column when a skipped legacy path fails to copy or a skipped custom path fails to fetch from network.
I did a sanity check and will do more thorough debugging on prod CN5. No data should be lost, and this will only impact skipped tracks - same logic otherwise.
I'll monitor prod CN5 with debugging enabled to spot check any failed tracks and make sure they're not failing due to being unable to copy over from a skipped track. The logs to search for this are "Failed to copy legacy" and "Error fixing fileRecord"

Update storagePaths for failed blacklisted CIDs

---

discovery-provider/alembic/versions/21e5635c83a9_create_notification_seen.py
discovery-provider/integration_tests/notifications/test_challenge_disbursement.py
discovery-provider/integration_tests/notifications/test_follow.py
discovery-provider/integration_tests/notifications/test_play_milestone.py
discovery-provider/integration_tests/notifications/test_playlist.py
discovery-provider/integration_tests/notifications/test_reaction.py
discovery-provider/integration_tests/notifications/test_repost.py
discovery-provider/integration_tests/notifications/test_save.py
discovery-provider/integration_tests/notifications/test_supporter_rank_ups.py
discovery-provider/integration_tests/notifications/test_track.py
discovery-provider/integration_tests/notifications/test_user_tip.py
discovery-provider/integration_tests/tasks/entity_manager/test_index_notification.py
discovery-provider/src/models/notifications/notification.py
discovery-provider/src/tasks/entity_manager/entity_manager.py
discovery-provider/src/tasks/entity_manager/notification_seen.py
discovery-provider/src/tasks/entity_manager/utils.py

Adds a migration for the notifications seen
Removes the notification_group table - functionality replaced with notification seen
Adds an entity manager jobs to index notification seen 
Test for entity manager to write to the table

Add notification seen table

---

creator-node/src/dbManager.js
creator-node/src/diskManager.ts

The current storagePath migration db query runs for unreasonably long after reaching the `Qmw` cursor because there are too many CIDs that are `>= Qmw`, and it tries to order and match storagePath regex against all of these CIDs. After manually running some queries, I found that an acceptable runtime is when narrowing the window from `>= Qm*` to `BETWEEN Qm**a AND Qm**z`. This limits the number of CIDs that the query has to match storagePath regex against.
[Here's a sandbox](https://codesandbox.io/s/crimson-waterfall-c7rmhw) showing the pagination windows (open console).
I manually tested in the same way the original pagination was tested --
for legacy:
1. `A up; A seed clear; A seed create-user; A seed upload-track`
2. In db: `UPDATE "Files" SET "storagePath" = CONCAT('/file_storage', …

Narrow pagination windows for storagePath migrations

---

identity-service/src/app.js
identity-service/src/rateLimiter.js
identity-service/src/redis.js

Resolves this consistent redis error in identity. Maybe the IP rate limiter was never working? If so, will need to monitor when deploying.
```
UnhandledPromiseRejectionWarning: ReplyError: ERR value is not an integer or out of range
at parseError (/usr/src/app/node_modules/redis-parser/lib/parser.js:179:12)
at parseType (/usr/src/app/node_modules/redis-parser/lib/parser.js:302:14)
```
Used `showFriendlyErrorStack` to help narrow down the issue to the rate limiter and found we were using "Hour" "Day "Week" here.
`showFriendlyErrorStack` has some impact on performance but still seems worth putting on stage.
https://github.com/luin/ioredis/issues/829
Tested locally. Confirmed errors disappeared.

Fix identity redis rate limit error and improve logging

---

creator-node/src/components/replicaSet/replicaSetController.js
libs/src/services/discoveryProvider/DiscoveryProvider.ts

Update manual reconfig route to match `updateReplicaSet.jobProcessor` - it now first tries URSM, then falls back to EM
NOTE - it polls discovery indexing for confirmation, but does not issue syncs to new secondaries (didn't feel like writing this was urgent for now)
I tested this locally with URSM and EM cases, both work
n/a
n/a

Fix manual reconfig route

---

discovery-provider/integration_tests/tasks/entity_manager/test_utils.py
discovery-provider/src/models/playlists/playlist.py
discovery-provider/src/models/tracks/track.py
discovery-provider/src/models/users/user.py
discovery-provider/src/tasks/entity_manager/playlist.py
discovery-provider/src/tasks/entity_manager/track.py
discovery-provider/src/tasks/entity_manager/user.py
discovery-provider/src/tasks/entity_manager/user_replica_set.py
discovery-provider/src/tasks/entity_manager/utils.py

Use getattr to copy sqlalchemy objects in the entity manager rather than manually setting each field when instantiating an object.
Unit test. Will test manually as well.
EM logs

Better EM copying

---

discovery-provider/src/api/v1/playlists.py
discovery-provider/src/api/v1/tracks.py
discovery-provider/src/api/v1/users.py
discovery-provider/src/queries/get_unclaimed.py
discovery-provider/src/queries/get_unclaimed_id.py

Add unclaimed ID API. Will be used in client/libs to fetch an unclaimed ID rather than optimistically generate one. 
After 10 tries if every randomly generated ID exists, it'll return null. The client will error appropriately.
Tested locally

Add unclaimed user ID API

---

creator-node/src/routes/tracks.js

This is used for the data backfill for simplicity in grabbing the cid associated with the copy320.
No tests since it's just adding a header
Hit `/tracks/stream/<encodedId>` and check the headers

Add copy320 cid to header

---

identity-service/src/config.js
identity-service/src/relay/txRelay.js

Adds an optional whitelist for updateReplicaSet for state machine updateReplicaSet ops. This only applies after all existing rules run like is update replica set check, rate limit. Signup and state machine should be the only two places that do updateReplicaSet ops now, and we have a special condition in txRelay for first time signups always allowing it through. 
The utility here is mostly as a safeguard in the event there's a node sending over too many reconfigs or an older content node version sending over unwanted reconfigs etc
Tested locally by setting a wallet to the whitelist and making sure tx's get rejected. Similarly removing the whitelist allows transactions to go through.
Added a new log, can search in loggly if we hit this case. Reconfig success % on grafana will also dip if we …

Add ability to filter updateReplicaSet relays by sender address

---

discovery-provider/src/exceptions.py
discovery-provider/src/solana/solana_client_manager.py
discovery-provider/src/tasks/index_spl_token.py
discovery-provider/src/tasks/index_spl_token_backfill.py

Adds an exception for when an indexer encounters a solana transaction with an unsupported version. Example: https://solscan.io/tx/22sVpjeQ4tm13kSwA8QoiQ5b7q1V3JBqSFbkRoDR87fu834zCzxeCmX894vtPG6ypQLnxxvmZ3KpxwntcL8wyqxL
Tested on remote-dev
Outputs a log line when encountered.

Skip txs with unsupported versions in spl token indexer

---

creator-node/src/dbManager.js
creator-node/src/diskManager.ts
creator-node/src/fileManager.js

Makes legacy non-dir storagePaths fall back to fetching from network when they fail to copy from the legacy file path. So far all spot checks have been available in network (find failed CID and query it via /ipfs on any node), so this should resolve the vast majority of legacy storagePaths that are failing to migrate.
I tested on stage UM and verified that it's now showing a nonzero number of successful legacy files being migrated - previously they were all failing.
Monitor for logs of "Legacy fetch from network fallback error" and "Error fixing fileRecord," and spot check failed files. The nodes that had only failed files should now start seeing some succeeding (verify by making sure the `audius_cn_files_migrated_from_legacy_path{result="success"}` metric is nonzero).

Fall back to network fetch when storagePath doesn't exist

---

discovery-provider/src/app.py

Delete the lock on startup to avoid stalling the indexer.
Tested on remote-dev

Delete spl token indexer lock on startup

---

discovery-provider/alembic/versions/7b843f2d3a0d_load_audio_transactions_csv.py

Deletes all spl-token transactions in `audio_transactions_history` table and backfills them with data from a csv file.
Since v1 of this migration hasn't made it out to foundation nodes or SPs yet, I figured it would be easier to backfill all the data at once, instead of adding a separate migration for just the missing spl token transactions.
Tested v1 of the migration on prod DN 4, so we know downloading, unzipping, and copying the csv data works. Tested the query manually in navicat. Tested e2e on prod DN 4.

Backfill missing spl-token transactions

---

discovery-provider/integration_tests/tasks/test_index_spl_token.py
discovery-provider/src/tasks/index_spl_token.py
discovery-provider/src/tasks/index_user_bank.py
discovery-provider/src/utils/helpers.py

Fix the parsing function in spl token indexer to lookup account indices correctly (same way as we do in `index_user_bank.py`). This was the bug that was causing us to skip certain transactions if `accountKeys` were not in a specific order.
Updated spl token indexer unit test to include 2 purchase transactions with different `accountKeys` ordering.

Fix spl token indexer parsing

---

libs/src/services/schemaValidator/schemas/trackSchema.json
libs/src/utils/types.ts

Libs changes to add extra field to track upload metadata used for notifications
NOTE: There is a corresponding client change to utilize these changes
Fixes PLAT-526
Ran locally and validated that it wrote with the extra field

Add libs is playlist upload to metadata

---

discovery-provider/src/app.py
discovery-provider/src/tasks/index_trending.py

Delete the trending task key in app.py - noticed that when discovery restarted, the trending task did not restart
The lock was also for 24 hours - reduced to 2 hrs
none

Del trending task redis lock key on restart

---

discovery-provider/src/queries/query_helpers.py

Update get_karma query to filter users on is_current flag
Should speed up the query a good amount.
Ref query insights
none

Add is_current to query

---

discovery-provider/requirements.txt

Update version of eventlet
Note current version on stage/prod is broken when used in api request handler
```
File "/usr/lib/python3.9/concurrent/futures/thread.py", line 42, in <module>
after_in_child=_global_shutdown_lock._at_fork_reinit,
AttributeError: 'Semaphore' object has no attribute '_at_fork_reinit'
```
Leads to an error fixed in version 0.30.0 ref: https://eventlet.net/doc/changelog.html#id8
But, we cannot update to latest because of breaking change in 0.30.3 https://eventlet.net/doc/changelog.html#id8 and gunicorn depends on it. (Unless we also update gunicorn)
Ran on staging and validated the get_all_other_nodes works

Eventlet py version

---

discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
discovery-provider/src/utils/get_all_other_nodes.py

Update fetching of nodes on chain to use async instead of mutithreading.
Hoping this fixes the error we're seeing on staging and prod of 
```
File "/audius-discovery-provider/src/utils/get_all_other_nodes.py", line 54, in get_node_endpoint
with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
File "/usr/lib/python3.9/concurrent/futures/__init__.py", line 49, in __getattr__
from .thread import ThreadPoolExecutor as te
File "/usr/lib/python3.9/concurrent/futures/thread.py", line 42, in <module>
after_in_child=_global_shutdown_lock._at_fork_reinit,
AttributeError: 'Semaphore' object has no attribute '_at_fork_reinit'
```
Note, the `get_all_other_nodes` method is used by the following routes:
`/challenges/attest_sender`
`/redirect_weights`
`/sitemaps/<TYPE>/index.xml`
Ran …

Async io fetch nodes

---

discovery-provider/plugins/network-monitoring/package-lock.json
discovery-provider/plugins/network-monitoring/package.json
discovery-provider/plugins/network-monitoring/src/content/index.ts
discovery-provider/plugins/network-monitoring/src/discovery/queries.ts

Fixes the network monitoring query to fetch all content nodes so that even deregistered content nodes get included.
Ran a network monitoring run locally

Network Monitoring: fix query to fetch content nodes

---

identity-service/src/relay/txRelay.js

Add rate limit for replica set updates in EntityManager too. Shares logic with legacy replica set updates.
Initial replica set on creation looks like this: 
https://github.com/AudiusProject/audius-protocol/blob/f9487634378cddd7420ad02df11e571c33867ac4/libs/src/api/Users.ts#L501-L507
EM replica set updates look like this: 
https://github.com/AudiusProject/audius-protocol/blob/f9487634378cddd7420ad02df11e571c33867ac4/libs/src/api/Users.ts#L624-L630
Did not test.

Rate limit EM replica set updates

---

discovery-provider/alembic/trigger_sql/handle_playlist.sql
discovery-provider/alembic/trigger_sql/handle_track.sql
discovery-provider/alembic/versions/f6f009132212_add_track_is_playlist_upload.py
discovery-provider/integration_tests/notifications/test_playlist.py
discovery-provider/integration_tests/notifications/test_track.py
discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
discovery-provider/integration_tests/tasks/test_index_tracks.py
discovery-provider/integration_tests/utils.py
discovery-provider/src/models/tracks/track.py
discovery-provider/src/tasks/metadata.py
discovery-provider/src/tasks/tracks.py
identity-service/src/notifications/notificationQueue.js

Create notifications for new track and playlist uploads
Changes:
* Additional field indexed out of track metadata `is_playlist_upload` indicating if the track is a part of a playlist upload
* Adds that field to the tracks table as a bool column
* In the track/playlist trigger, if new, create a new notification for all the user's subscribers
Fixes PLAT-526
Wrote some tests for the indexing and the notification creation

Discovery notification on track/playlist creation

---

discovery-provider/src/eth_indexing/event_scanner.py
discovery-provider/src/utils/helpers.py

1.) Removes an error log in the redis helper
2.) Seeing lots of error logs for `could not read redis dump file: eth_indexing_last_scanned_block_2_dump`
This is because the event scanner does not store the redis value on disk - This change adds it to be saved on disk

Fix err logs

---

discovery-provider/src/api/v1/tracks.py

Straightforward. If somehow there is not track cid for a given track, and cid streaming is enabled, do not redirect to CN to stream.
none
none

[PAY-765] Prevent redirecting stream to CN if no track_cid

---

creator-node/src/diskManager.ts

Allows files with legacy or custom storagePaths to be migrated even if their recomputed hash of the file doesn't match the CID.
CI passing is sufficient. We still log a warning.
Monitor for the following log to make sure previously blocked files are now migrated successfully: "CID does not match what is expected to be based on contents hash, but contents were copied anyway"

Remove mismatched CID check from storagePath migrations

---

discovery-provider/src/queries/get_remix_track_parents.py
discovery-provider/src/queries/get_remixable_tracks.py
discovery-provider/src/queries/get_remixes_of.py

Prevent premium tracks remixability
related to https://github.com/AudiusProject/audius-client/pull/2422
simply filters out premium tracks
none

[PAY-757] Prevent premium tracks remixability

---

identity-service/src/routes/tiktok.js

Fixes an issue where the access token wasn't correctly being pulled from the response before fetching the tiktok profile. Also prevents getting an access token for a tiktok account that is already associated

Fix TikTok auth + improve association

---

creator-node/package-lock.json
creator-node/src/diskManager.ts
creator-node/src/index.ts
creator-node/src/utils/cluster/clusterUtilsForPrimary.ts

Infinite recursion causes stack too deep, blocks event loop (thsi is why requests never go through), and maxes out CPU usage on all node server processes
Solution:
- replace recursive call with infinite while loop
- add delay btwn while loop iterations
- add short circuit for while loop
[Loggly link of errors](https://audius.loggly.com/search#terms=tag:audius-stage-creator-*%20%22RangeError:%20Maximum%20call%20stack%20size%20exceeded%22&from=2022-12-12T22:22:13.424Z&until=2022-12-19T22:22:13.424Z&source_group=)
```
{"name":"audius_creator_node","clusterWorker":"Worker 2","hostname":"8ef9f0e7d117","pid":116,"requestID":"APF-Z4GMb","requestMethod":"GET","requestHostname":"127.0.0.1","requestUrl":"/prometheus/linux","level":20,"msg":"Begin processing …
```

Fix CN stack too deep error & probably CPU maxing out

---

discovery-provider/src/tasks/index_rewards_manager.py
discovery-provider/src/tasks/index_solana_plays.py
discovery-provider/src/tasks/index_spl_token.py
discovery-provider/src/tasks/index_user_bank.py

- Assuming our indexers spend the majority of their time caught up, we don't need to fetch 1k txs for each pass. Backed out some reasonable upper bounds from previous testing (documented in notion). 
- Added more logs
- Testing on sandbox

[PAY-769] Optimize Solana RPC signature fetching

---

creator-node/src/apiSigning.js
creator-node/src/apiSigning.ts
creator-node/src/components/replicaSet/URSMRegistrationComponentService.js
creator-node/src/middlewares.js
creator-node/src/reqLimiter.js
creator-node/test/apiSigning.test.js
creator-node/test/lib/app.js
creator-node/test/transcodeAndSegment.test.js

every `verifyRequesterIsValidSP` function call was making a direct `SPFactory.getServiceEndpointInfo()` chain call - which is v bad. we already have a caching util built in for this, so just needed to swap the call over
fixed existing tests
ethRPC calls from foundation nodes should go down significantly...hopefully

Cache CN SPFactory calls

---

creator-node/src/dbManager.js
creator-node/src/diskManager.ts
creator-node/src/services/prometheusMonitoring/prometheus.constants.ts

Adds metric to find total entries in the Files table that have a legacy or custom storagePath column.
1. Create a user with a track: `A up; A seed clear; A seed create-user; A seed upload-track`
2. Manually change their files to have a legacy path: `UPDATE "Files" SET "storagePath" = CONCAT('/file_storage', SUBSTRING("storagePath" FROM 20));`
3. Hot reload and look verify that the metric was recorded:
Monitor the metric `audius_cn_total_unmigrated_storage_paths` - it's broken down by type="legacy" and type="custom"
For errors, watch out for:
- "Failed to record total count of unmigrated storagePaths"
- "Failed to reset counts of migrated storagePaths"

Add metrics for total unmigrated files

---

identity-service/src/config.js
identity-service/src/routes/instagram.js
identity-service/src/routes/twitter.js

Update routes for instagram profile checks:
* Remove most code for custom instagram profile fetch
* Retrieve actual account during the oauth code validation
Want to test on stage

[C-1522] Update instagram routes

---

discovery-provider/integration_tests/queries/test_get_user_replica_set.py
discovery-provider/src/queries/get_user_replica_set.py

The endpoint currently 500 errors if the user does not have a primary/secondary id set
The method has been updated to return with None in fields that are not set in the db
Added a test for this

Update Replica set endpoint

---

creator-node/src/routes/tracks.js

Optimize /tracks/stream/:encodedId route. The issue here is if a single user has uploaded the same track multiple times (eg probers) the query for all sourceFiles can return a lot of records, on staging it was 382k records non-distinct and 8900 records distinct. In addition we had some checks in JS which were blocking the event loop, the biggest offender was  
```
const uniqSourceFiles = fileSegmentRecords
.map((record) => record.sourceFile)
.filter((v, i, a) => a.indexOf(v) === i)
```
This does a filter and an indexOf which is an O(n^2) operation on a list of 328k items. I removed these checks and had Postgres return the list of distinct items which saves us all the JS processing.
Hotfix onto stage and tested to make sure stream routes that were previously unplayable now play correctly. …

Tracks stream optimizations pt 2

---

discovery-provider/src/queries/get_premium_track_signatures.py
discovery-provider/src/schemas/track_schema.json
discovery-provider/src/solana/solana_client_manager.py
discovery-provider/src/solana/solana_helpers.py
libs/src/services/schemaValidator/schemas/trackSchema.json
libs/src/utils/types.ts

Produce premium content signatures when user has access to solana-nft-gated premium tracks.
- Add `get_token_accounts_by_owner` and `get_account_info` methods to `SolanaClientManager`
- Add method that parses solana nft collection metadata
- Update track schema json
Tested using solana mainnet RPCs, and tested with solana wallet address which owns an nft from a certain collection. It worked; the signature was generated.
Note: this method is sometimes a bit slow, taking between 5s to 10s, probably because of network conditions which forces retries happening at the `SolanaClientManager` level. Probably should keep an eye on this and make sure it's fast enough for our use case.
n/a

[PAY-747] Handle solana-nft-gated premium content

---

libs/tests/rewardsAttesterTest.js

There's this old test that sometimes breaks in CI. I haven't been able to repro it, but I think this fixes the bug:
- Sometime we'd see 94 instead of 84 as the expected delay slot
- I think this is because the slots are produced on 250ms intervals and the solanaPollingInterval is 500ms, so occasionally it will poll and see a single slot created for 500ms and think the slot production rate is 2 per seconds instead of 4 per second, 104 - 5sec * 2slots/sec = 94

[PAY-123] Fix flaky rewards test

---

comms/db/migrations/20221222050259_add_rpc_log_pk.sql
comms/internal/rpcz/apply.go
comms/server/server_test.go

Check for seq num in `rpc_log`, do not process message if already in the log. This keeps `Apply` idempotent in case messages get redelivered.
Thoughts on making `jetstream_sequence` the PK in `rpc_log`?
Also threw a small unrelated cleanup change to `server_test` in here.

Only process messages once per seq num

---

identity-service/src/routes/tiktok.js

Obvious bug is obvious, fixed by using `username` instead of `display_name`. The TikTok api docs do not surface that `username` is an available field. While testing I was using a tiktok account that did not have a display name and defaulted to the username

Use username instead of display_name for tiktok

---

discovery-provider/src/tasks/entity_manager/user.py

Validate user handle with lowercase cuz that's indexed

Validate user handle with lowercase

---

identity-service/src/relay/txRelay.js

Pass gas value to nethermind to allow for larger transaction sized
NOTE: This is untested, was planning on testing on stage
NOTE: Ran into this limit while testing announcement notifications
none

Add dynamic nethermind gas limit

---

creator-node/src/contentAccess/types.ts
creator-node/test/contentAccessChecker.test.ts

Add `trackId` to one of the required fields for streaming a track. This is part of the work to make TNS and Blacklist Manager work for the new streaming setup.
Updated the unit tests for the accessChecker service to accommodate the new field. 
No major monitoring changes

[CON-534] add new required field to accessChecker `trackId`
