discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
discovery-provider/src/tasks/entity_manager/user.py
discovery-provider/src/tasks/entity_manager/utils.py
discovery-provider/src/tasks/metadata.py
discovery-provider/src/tasks/users.py

- Add artist pick track id to user metadata in entity manger
- Add artist pick field getting/setting to user update logic in entity manager
- Validate that 1.) the artist pick track id is a valid, current track id in the tracks table, and 2.) the user owns the track they are trying to pin before updating the user metadata
Entity manager integration tests

Add artist pick track id to user metadata in entity manager

---

.circleci/bin/deploy-ci.py

Use prod-user-metadata instead of user-metadata.
Testing on master.
Monitor on #eng-deploy

INF-251 use correct prod-user-metadata hostname

---

dev-tools/commands/src/upload-track.mjs

Fix local upload track flow for premium content
`audius-cmd upload-track`
NA

Fix local upload track for premium content

---

.circleci/config.yml

Remove previous fields and use straight text. [Example](https://app.slack.com/block-kit-builder/TA41AKD9B#%7B%22blocks%22:%5B%7B%22type%22:%22header%22,%22text%22:%7B%22type%22:%22plain_text%22,%22text%22:%22%3C%3C%20parameters.text%20%3E%3E%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22text%22:%22*Job*:%20$%7BCIRCLE_JOB%7D%22,%22type%22:%22mrkdwn%22%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22text%22:%22%3C%3C%20parameters.detail%20%3E%3E%20%22,%22type%22:%22mrkdwn%22%7D%7D,%7B%22type%22:%22section%22,%22text%22:%7B%22text%22:%22*Job*:%20%60$CIRCLE_PROJECT_REPONAME%60:%60$CIRCLE_BRANCH%60%20($CIRCLE_USERNAME)%20%3C%3C%20parameters.slack_mentions_user%20%3E%3E%20%22,%22type%22:%22mrkdwn%22%7D,%22accessory%22:%7B%22type%22:%22button%22,%22text%22:%7B%22type%2 …

INF-251 reduce Slack messages' vertical height

---

dev-tools/audius-compose
discovery-provider/default_config.ini
docker-compose.yml
identity-service/compose/.env
identity-service/src/audiusLibsInstance.js
identity-service/src/config.js
identity-service/src/routes/instagram.js
identity-service/src/routes/twitter.js
libs/src/api/Users.ts
libs/src/services/dataContracts/AudiusContracts.ts
libs/src/services/dataContracts/EntityManagerClient.ts

Update libs & identity service to verify user with verifier address via entity manager
Verified user locally.

User verification via entity manager in identity

---

.circleci/config.yml

Consume governance secrets for new proposal scripts.
Running on `master`.
#eng-deploys.

INF-256 consume governance secrets

---

.circleci/config.yml

Remove the discord orb and send custom, cleaner discord messages.
Test on [this branch](https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/28999/workflows/39443b69-c233-45c8-bcad-7513423a67b3/jobs/356900), and off master.
#eng-alerts-debug, #eng-deploys

INF-274 Nicer discord messages

---

dev-tools/README.md

i think this should be the actual hostname

Update sshuttle readme DN hostname

---

libs/src/NativeAudiusLibs.ts
libs/src/services/wormhole/ProxyWormhole.ts
libs/src/services/wormhole/Wormhole.ts
libs/src/services/wormhole/index.ts

This should allow wormhole to work as expected in the react native context.
Need to test still.

[C-1116] Implement proxy wormhole only entrypoint

---

creator-node/package-lock.json
creator-node/package.json
creator-node/src/migrationManager.ts

This PR converts the MigrationManager to typescript
Just original integration and mad dog tests to make sure original functionality didn't break
This will be monitored with the typechecker

Convert MigrationManager to typescript

---

identity-service/package-lock.json
identity-service/package.json

Bump the sdk version in identity to add the entity manager verify action
Tested locally e2e

Bump sdk in identity

---

creator-node/package-lock.json
creator-node/package.json
creator-node/src/components/contentBlacklist/contentBlacklistController.js
creator-node/src/routes/tracks.js
creator-node/test/contentBlacklist.test.js
creator-node/test/dbManager.test.js
creator-node/test/pollingTracks.test.js
creator-node/test/sync.test.js

Update CN to consume new libs getTracksVerbose & implement more intelligent logic + logging
Fix all associated tests
Automated tests have good coverage of this flow
Manual tests - upload track, confirm it first fails before indexing then succeeds
```{"name":"audius_creator_node","clusterWorker":"Worker 1","hostname":"1bc8f6f60886","pid":9192,"requestID":"defad129-4c3e-41b3-8015-7d17560a780c","requestMethod":"POST","requestHostname":"cn4_creator-node_1","requestUrl":"/tracks","requestWallet":"0x1f362cd4ab93b6ec6bdec7e214ca9ec6a448c642","requestBlockchainUserId":"1","level":40,"msg":"[asyncRetry] [attempt #1]:  [validateTrackOwner][trackId: 4][userId: 1][blockNumber: 1154]: targetBlocknumber not indexed. http://dn1_web-server_1:5000 currently at 1153 with blockDiff …
```

CON-451 Reduce CN tracks upload errors by consuming new libs getTracksVerbose & improving logic

---

.circleci/config.yml

This should allow Slack @mentions to work as expected. 🤞 
Testing on master.
#eng-deploys

INF Use only lowercase for slack @mentions

---

creator-node/compose/env/base.env
creator-node/src/routes/tracks.js
creator-node/src/utils/asyncRetry.js

Reduce CN discovery unhealthyBlockDiff from 500 to 10 to very quickly re-select discovery if unhealthy
Remove async-retry maxTimeout of 5s to ensure accurate exponential backoff
mad-dog sufficient
Upload rates

CON-451 CN track upload validation improvements

---

.circleci/bin/deploy-ci.py

INF Remove stg-cn4 from deploy script

---

identity-service/src/routes/relay.js

I was passing 'relay' as the IP 🤦‍♂️ causing errors in AAO

Fix args passed to detectAbuse

---

identity-service/src/routes/relay.js
identity-service/src/routes/user.js
identity-service/src/utils/antiAbuse.js

- Blocks on AAO rule 13
- Allows on 14
- Fixes error with not passing the properly parsed forwarded-for IP to AAO, causing Seon errors 
- Fixes occasional signup validation error with bad email addresses 
**Still to do:**
- Need to set handle sooner

Add new abuse rules and fix bugs

---

creator-node/src/routes/tracks.js

hotfix validateTrackOwner asyncRetry syntax bug
n/a
n/a

Hotfix track upload - Fix CN asyncretry options bug

---

discovery-provider/src/queries/get_tracks.py
discovery-provider/src/queries/queries.py

Add skip unlisted filter

---

creator-node/src/middlewares.js
creator-node/src/services/sync/secondarySyncFromPrimary.ts
creator-node/src/services/sync/syncImmediateQueue.js
creator-node/src/services/sync/syncQueue.js
creator-node/src/services/sync/syncUtil.ts
creator-node/test/sync.test.js

This PR converts the file `secondarySyncFromPrimary` to typescript and adds a type for the params it accepts
I didn't do any major refactoring of the file so maybe a follow up PR can be made to make the file look more organized like `primarySyncFromSecondary`
This just uses the original tests to make sure nothing broke
This will be monitored with the typechecker

Convert `secondarySyncFromPrimary` to typescript

---

discovery-provider/alembic/versions/42d5afb85d42_create_audio_transactions_history.py
discovery-provider/src/models/users/audio_transactions_history.py

Alembic migration to create audio_transactions_history table

[PAY-662] Create audio_transactions_history table

---

discovery-provider/src/tasks/index_user_bank.py

Indexing for tips and external send for audio_transaction_history
No unit test for this yet but should probably add one.

[PAY-666] Indexing user bank for audio_tx_history

---

creator-node/package-lock.json
creator-node/src/models/index.js
creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
creator-node/src/utils/clusterUtils.ts

Problem - DB connections getting overloaded, seeing tons of errors
Seeing max cpu and mem on multiple node SQL instances
Automated tests sufficient
DB monitoring

Change CN db connection pool to be a function of numWorkers

---

creator-node/package-lock.json
creator-node/scripts/run-tests.sh
creator-node/src/ImageProcessingQueue.ts
creator-node/src/models/index.js
creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts
creator-node/src/utils/clusterUtils.ts

Call the transpiled JS code from ImageProcessingQueue for resizeImage.
Tested with unit tests local and stage creator 10
Track uploads should succeed in amplitude

Re-enable "Change CN db connection pool to be a function of numWorkers"

---

identity-service/src/awsSNS.js
identity-service/src/notifications/notificationQueue.js
identity-service/src/notifications/sendNotifications/publishNotifications.js

Small PR to test out adding the notification obj to the push notification payload. 
Want to enable client-side routing based on notification type and data.
N/A
N/A

Update push notifications payload to include the notification object for client side routing

---

discovery-provider/src/tasks/index.py

Update max reversion blocks to 50/100 instead of 500/10000

Update max reversion blocks

---

.circleci/config.yml

* Remove emojis by restructuring job names holistically.
* Remove old manual release jobs.
* Add new cron triggers for release jobs.
* Only auto-deploy services when new changes are seen for the service (logic only runs on `master`).
* Restrict deployment jobs to Github groups, via `restricted-ci-job` CircleCI context.
* Add trigger to slashing proposals for remote triggering.
* WIP branches/PRs:
* Old workflow: https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/29192/workflows/59922d41-a113-484c-9511-4142f5c1275c
* New workflow: https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/29349/workflows/526de2ca-ecc3-456b-b569-f45f4bb2ed06
* `release-v*`:
* Old workflow: https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/29143/workflow …

INF-262 CircleCI: Remove emojis, add new cron triggers, restrict deployment jobs, don't autodeploy needlessly, add slashing trigger

---

creator-node/src/config.js

nodeSyncFileSaveMaxConcurrency from 10 --> 5 (already live on prod)
contentCacheLayerEnabled from false -> true (already live on prod)
n/a
n/a

CN config tweaks - nodeSyncFileSaveMaxConcurrency & contentCacheLayerEnabled

---

.circleci/config.yml

Sets this week to be release week, causing `cut-release` to run at midnight PDT today (Friday/Saturday).
Monitor nightly jobs.
Monitor nightly jobs.

INF-295 Activate cut-release job

---

.circleci/config.yml

Silence cron triggers until we fix the bi-weekly logic.
N/A
N/A

Silence cron triggers until we fix bi-weekly

---

discovery-provider/integration_tests/queries/test_get_user_listen_counts_monthly.py

Removing unused imports that are causing the flake8 hook to fail!

fix failing flake8 hook

---

creator-node/src/segmentDuration.ts

This PR types `segmentDuration` - this is one of the smaller typescript lifts.
This PR uses original PRs to make sure nothing breaks
This will be monitored with the typescript

Convert segmentDuration to typescript

---

discovery-provider/integration_tests/queries/test_get_sitemap.py
discovery-provider/src/queries/get_sitemap.py

Fix base sitemapp

---

creator-node/compose/env/base.env
creator-node/src/config.js

Enable primary-only reconfig and update primary grace period to 10 minutes
Config only changes, unit tests.
Bull queue

Update primary reconfig configs

---

creator-node/compose/env/base.env
creator-node/src/config.js

Set reconfigModePrimaryOnly to false by default in the protocol
Config only change, tested with unit tests

Disable reconfigModePrimaryOnly

---

identity-service/src/notifications/index.js
identity-service/src/notifications/sendDownloadAppEmails.js
identity-service/src/notifications/sendNotificationEmails.js

Switch to debug logs for noisy logs

Switch to debug logs for renderAndSendNotificatoinEmail

---

libs/src/AudiusLibs.ts
libs/src/NativeAudiusLibs.ts
libs/src/api/File.ts

Fall back to fetching CIDs from the whole network in cases where it is not found in the replica set.
Ran linked against client on prod

Fall back to entire network on fetchCID

---

libs/src/api/entityManager.ts
libs/src/services/dataContracts/EntityManagerClient.ts

*Add missing repost playlist actions. Already being used in client. https://github.com/AudiusProject/audius-client/blob/main/packages/common/src/services/audius-backend/AudiusBackend.ts#L1234
* Consolidate EntityType and Action. 
Tested on client pointed to stage. repost and unrepost work.

Add repost playlists on EM to libs

---

discovery-provider/integration_tests/tasks/test_index_rewards_manager.py
discovery-provider/src/tasks/index_rewards_manager.py
discovery-provider/src/tasks/index_user_bank.py
discovery-provider/src/utils/helpers.py

Index rewards for audio_transactions_history
Updated `test_index_rewards_manager.py` to test for audio_transactions_history rows as well.

Rewards indexing for audio_transactions_history

---

creator-node/src/config.js

Default disk prune enabled to false
Config only change

Default disk prune enabled to false

---

creator-node/src/diskManager.js

Verify the DB query actually succeeds by adding a custom row to the results to verify we got a result back from the db and it wasn't an error
Tested locally by commenting out the UNION and making sure it early exits before the disk delete.

Add a sanity check for success of db query

---

creator-node/src/components/healthCheck/syncHealthCheckComponentService.ts

This PR converts the sync health component service to typescript
Just using the original tests
this change will be monitored with the type checker

Convert SyncHealthComponentService to typescript

---

creator-node/src/services/stateMachineManager/stateMonitoring/stateMonitoringUtils.ts
creator-node/src/services/stateMachineManager/stateReconciliation/SecondarySyncHealthTracker.ts
creator-node/src/services/stateMachineManager/stateReconciliation/issueSyncRequest.jobProcessor.ts

This is a stylistic pre-req before changing the functionality of `SecondarySyncHealthTracker`. 
This PR:
- removes the redundant `Getters`, `Setters`, `Utils` labeling
- exports each function as necessary
- rearranges all the public fns at the top of the file and all private fns underneath the public fns
No changes in functionality, just structural changes
Existing tests should be sufficient

Format SecondarySyncHealthTracker to ts structure

---

discovery-provider/src/api/v1/metrics.py
discovery-provider/src/app.py
discovery-provider/src/solana/solana_client_manager.py
discovery-provider/src/tasks/index.py
discovery-provider/src/tasks/index_eth.py
discovery-provider/src/tasks/index_metrics.py
discovery-provider/src/tasks/index_network_peers.py
discovery-provider/src/tasks/index_rewards_manager.py
discovery-provider/src/tasks/index_spl_token.py
discovery-provider/src/tasks/index_user_bank.py
discovery-provider/src/utils/eth_contracts_helpers.py
discovery-provider/src/utils/redis_metrics.py

Removed unneeded logs - to reduce load on loggly
I checked logs in loggly for frequent logs and took a pass at removing or changing from info to debug. 
Other logs that we could remove are:
* celery tracer logs
* openresty logs
* python-requests
* es-indexer
Fixes PLAT-430

Remove logs

---

.circleci/config.yml
discovery-provider/README.md

Fix logic for not deploying unchanged services
Reason for changes:
* CircleCI conditionals do not accept envars.
* diff-if-necessary is pretty heavy and does not accept wildcards. (would be best to rewrite diff.sh separately.)
* Ensure all deploy jobs set `service` for accurate `git diff` output.
Two runs with only discovery changes:
* Passed diff logic for deployment: https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/30536/workflows/3721da13-eac5-4ad6-bfbc-69f6a3291917/jobs/374919
* Failed diff logic when attempting to deploy creator nodes: https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/30536/workflows/1e1bdd4b-da4f-4745-b26f-d57467dc1c57/jobs/374920
Two runs with only discovery changes, post-code cleanup:
* Passing discovery deployment: …

INF-298 Fix logic for not deploying unchanged services

---

creator-node/package.json

This PR adds an `npm` script to typecheck the Content Node codebase.
To typecheck without actually building the project, we would run `npm run typecheck`
tested locally by running `npm run typecheck`
n/a

Add typechecker script

---

creator-node/src/serviceRegistry.js

Bugfix to remove early exit in serviceRegistry init
n/a
n/a

Remove early exit in serviceRegistry

---

identity-service/src/relay/txRelay.js

changed function signature but not the call site 😢

fix nethermind relay call

---

creator-node/src/config.js

Bump ODR num users per batch from 2 -> 5.
Config only change, unit tests only

Bump ODR users per batch to 5

---

libs/initScripts/mainnet.js

Spotted when working on an unrelated ticket. It doesn't seem ideal to ever log the privateKey.
N/A
N/A

INF don't log private key

---

.circleci/config.yml

Sister PR: https://github.com/AudiusProject/audius-tooling/pull/50
Move all recent autodeployment logic to reference audius-tooling's main branch.
N/A, simple branch swap.
#eng-deploys

INF-246 Use audius-tooling:main post merge of audius-tooling:jc-inf-246

---

.circleci/bin/deploy-ci.py

Add monospacing to daily reservation listing.
Will test by triggering a `reservation` build after this PR has merged into `main` and viewing the summary.md artifact.
#eng-deploys

INF monospacing to reservation msg

---

creator-node/src/components/healthCheck/healthCheckController.js

There's been incidents where certain content nodes have issues reaching external networks (due to network controllers, firewall settings etc). This check is to test making outgoing network requests for debugging purposes, has no actual product uses.
Tested locally and made sure the data is correctly returned.
No alerts/logs needed, debug only check

New content node health check to test network ingress and egress

---

identity-service/src/apiHelpers.js
identity-service/src/rateLimiter.js
identity-service/src/routes/trackListens.js

Reduce logs. Most importantly "Success" log on endpoints. I don't think this provides any value really.
Lint?

[INF-304] Reduce identity service logs

---

dev-tools/startup/startup.sh

Configure the discovery provider to connect to external DB / Redis etc by creating
```
dev-tools/startup/discovery-provider-1.sh
```
in this file you can export all env vars required
` audius-compose up -c 0 -d 1 `
NA

Move local startup code

---

discovery-provider/src/utils/web3_provider.py

Health check caching would fail without this middleware during get_health but caching during indexing does have this middleware and would succeed.

Fix health check with web3 poa middleware

---

discovery-provider/src/queries/get_health.py

[INF-305] Add url to discovery health check

---

discovery-provider/integration_tests/tasks/test_index_rewards_manager.py
discovery-provider/src/models/users/audio_transactions_history.py
discovery-provider/src/tasks/index_rewards_manager.py
discovery-provider/src/tasks/index_spl_token.py
discovery-provider/src/utils/helpers.py

Missed some of @rickyrombo 's PR comments from the last one. Again some git weirdness, please only check last commit.

More audio_tx_history rewards indexing

---

discovery-provider/alembic/versions/42d5afb85d42_create_audio_transactions_history.py
discovery-provider/integration_tests/tasks/test_index_rewards_manager.py
discovery-provider/integration_tests/tasks/test_index_spl_token.py
discovery-provider/integration_tests/utils/test_helpers.py
discovery-provider/src/models/users/audio_transactions_history.py
discovery-provider/src/tasks/index_rewards_manager.py
discovery-provider/src/tasks/index_spl_token.py
discovery-provider/src/tasks/index_user_bank.py
discovery-provider/src/utils/helpers.py

All changes have already been reviewed.
Creates audio_transactions_history table and adds indexing for user_bank, rewards, and spl-token transactions.
Added new unit tests for rewards and spl-token indexing.

Indexing for audio_transactions_history

---

discovery-provider/src/queries/get_tracks.py
discovery-provider/src/queries/queries.py

Allow stems to be returned from discovery so content node can validate owner
Ran locally

Add skip stem filter

---

creator-node/src/config.js

Bump maxStorageUsedPercent to 97%

---

identity-service/src/routes/stripe.js

Includes the request IP as a parameter in Stripe session creation

[PAY-693] Include request IP in Stripe session creation

---

identity-service/src/routes/stripe.js

Fixes lint error introduced in #4237

Fix lint error

---

discovery-provider/src/tasks/index_spl_token.py

Fixes audio_tx_hist index_spl_token bug

---

creator-node/src/diskManager.ts

CN - reduce DAYS_BEFORE_PRUNING_ORPHANED_CONTENT from 7 to 4

---

.circleci/config.yml

Use the `$(false)` notation to see if that changes the exit code.
Run on CircleCI SSH session.
Running the job manually.

Update logic for circleci release-week gate

---

.circleci/config.yml

Update one-liner to not rely on bash's built-in `true`, in case that was causing issues.
Local tests within an SSH session into CircleCI:
```
9151493e2b07:~# if [ "false" = true ] ; then
>                   echo 1
>                 fi
9151493e2b07:~# if [ "false" = false ] ; then
>                   echo 1
>                 fi
1
9151493e2b07:~# if [ "true" = true ] ; then
>                   echo 1
>                 fi
1
9151493e2b07:~# if [ "true" = false ] ; then
>                   echo 1
>                 fi
```
Manual deployment.

INF Use full if statements, dont rely on built-in true

---

discovery-provider/src/api/v1/api.py
discovery-provider/src/api/v1/playlists.py
discovery-provider/src/app.py

Adds an m3u playlist API to discovery provider
The endpoint is `/v1/playlists/<id>/stream`
Tested with VLC
NA

[PLAT-375] Add m3u playlist API

---

creator-node/src/AsyncProcessingQueue.ts
creator-node/src/ImageProcessingQueue.ts
creator-node/src/TranscodingQueue.js
creator-node/src/apiHelpers.ts
creator-node/src/components/replicaSet/syncQueueComponentService.ts
creator-node/src/components/tracks/trackContentUploadManager.ts
creator-node/src/components/tracks/tracksComponentService.ts
creator-node/src/ffmpeg.js
creator-node/src/services/stateMachineManager/stateReconciliation/types.ts
creator-node/src/services/sync/secondarySyncFromPrimary.ts
creator-node/src/services/sync/secondarySyncFromPrimaryUtils.ts
creator-node/src/services/sync/syncQueue.ts

This PR converts `trackcontentuploadmanager` to typescript and flattens the class
Original tests to make sure nothing breaks
this will be monitored with the typechecker

Concert `TrackContentUploadManager` to typescript

---

libs/src/sdk/api/generator/gen.js

Small fix to get OpenAPI client generator to work with audius-compose. Courtesy of @rickyrombo

Fixes OpenAPI client gen for audius-compose

---

creator-node/src/fileManager.js
creator-node/src/services/sync/secondarySyncFromPrimary.ts

Gate expensive DB step behind syncForceWipeDiskEnabled + fix lint
n/a
n/a

CN: Gate expensive DB step behind syncForceWipeDiskEnabled + fix lint

---

.circleci/bin/deploy-ci.py

INT Missing commas break lint

---

creator-node/test/fileManager.test.js
dev-tools/audius-compose
discovery-provider/alembic/versions/03dbd1b775c5_create_subscriptions_table.py

Fix:
* A broken cn test
* 2x broken lints
CircleCI
Github Status

fix builds on main

---

creator-node/nginx_conf/nginx.conf
discovery-provider/nginx_conf/nginx.conf

Add our basic exporters to our nginx reverse proxy.
Tested locally via #4207, confirmed CircleCI tests pass, confirmed local audius-docker-compose machines work, confirmed on staging.
N/A

INF-266 add stablized exporters

---

.circleci/config.yml

Add trigger pipeline for slashing jobs.
Comment out actual usage while testing.
Testing will occur via #4280.
CircleCI logs.

INF-280 finish and safeguard slashing trigger pipeline

---

.circleci/config.yml

Since we had a late Tuesday release, let's try evaluating again late Saturday.
N/A
#eng-deploys

INF Evaluate governance proposals on Saturday as well, this week

---

monitoring/slashing-relay/alerts.json

A mapping between `health_check:signer` and discord handles.
In the future, when metrics are seen as out of bounds, we can contact node operators via discord handles.
N/A
N/A

INF-280 Add alerts.json for signer:discord_handle relationships

---

discovery-provider/src/tasks/entity_manager/entity_manager.py
discovery-provider/src/tasks/entity_manager/playlist.py
discovery-provider/src/tasks/entity_manager/social_features.py
discovery-provider/src/tasks/entity_manager/track.py
discovery-provider/src/tasks/entity_manager/user.py
discovery-provider/src/tasks/entity_manager/user_replica_set.py

Just some better logs to help w debugging invalid txs.

Better entity manager validation logs

---

discovery-provider/src/app.py
discovery-provider/src/tasks/index_nethermind.py
discovery-provider/src/utils/helpers.py
discovery-provider/src/utils/web3_provider.py

Only use web3 nethermind when indexing nethermind txs

---

discovery-provider/src/tasks/index_nethermind.py
identity-service/compose/.env
identity-service/default-config.json
identity-service/scripts/run-tests.sh
identity-service/src/config.js
identity-service/src/relay/txRelay.js
identity-service/src/web3.js

* Separate web3 provider for audius (stage is already on audius chain)
* DN needs a separate EM address when parsing TXs
Running on stage

Add separate nethermind web3 provider to identity

---

creator-node/package-lock.json
creator-node/src/TranscodingQueue.js
creator-node/src/monitors/MonitoringQueue.js
creator-node/src/services/SessionExpirationQueue.ts

CN Shorten queue logs

---

creator-node/src/utils/requestRange.test.ts
creator-node/src/utils/requestRange.ts

This PR just converts this unit test to typescript
I made sure the tests inside still pass
this change will be monitored with the typechecker

Convert `requestRange.test.js` to typescript

---

dev-tools/commands/src/upload-track.mjs

Small description fix

---

libs/src/api/Users.ts
libs/src/services/discoveryProvider/DiscoveryProvider.ts
libs/src/services/discoveryProvider/requests.ts

For use when retrieving users' subscribers from discprov in the client and identity service.
Tested discovery endpoints.
N/A

Add subscribers getters to libs

---

identity-service/src/utils/antiAbuse.js

[PAY-729] Block high digit threshold from relay

---

creator-node/src/index.ts

The content node exit log prints as a info log level, it should be error so it's easier to search and find
Unit tests sufficient, log change only
Log will be printed

Change content-node exit log to error

---

identity-service/src/notifications/processNotifications/createNotification.js
identity-service/src/notifications/sendDownloadAppEmails.js
identity-service/src/notifications/sendNotifications/formatNotification.js
identity-service/src/routes/notifications.js
identity-service/src/routes/push_notifications.js
identity-service/src/routes/userEvents.js
identity-service/src/routes/welcomeEmail.js

identity notification upsert

---

creator-node/package-lock.json
creator-node/package.json
creator-node/src/AsyncProcessingQueue.ts
creator-node/src/ImageProcessingQueue.ts
creator-node/src/apiHelpers.ts
creator-node/src/app.ts
creator-node/src/components/replicaSet/syncQueueComponentService.ts
creator-node/src/components/tracks/trackContentUploadManager.ts
creator-node/src/components/tracks/tracksComponentService.ts
creator-node/src/logging.ts
creator-node/src/services/stateMachineManager/stateReconciliation/types.ts
creator-node/src/services/sync/secondarySyncFromPrimary.ts
creator-node/src/services/sync/secondarySyncFromPrimaryUtils.ts
creator-node/src/services/sync/syncQueue.ts
creator-node/src/utils/index.ts
creator-node/src/utils/types.ts
creator-node/src/utils/utils.ts
creator-node/src/utils/validateAudiusUserMetadata.ts

This PR converts the `logging` file to typescript and organizes a few of our more used types into a `types.ts` folder in `utils`.
Just using the normal integration test suite to make sure nothing breaks.
The typechecker will monitor these changes

Convert `logging` to typescript

---

creator-node/src/diskManager.ts

I realized that if `backgroundDiskCleanupDeleteEnabled = false`, we will infinitely run `sweepSubdirectoriesInFiles`, which is a lot of wasteful work, and might be hurting our SP reliability
Also added a delay btwn batches to reduce that load
n/a
n/a

Short circuit background disk deletion

---

discovery-provider/src/tasks/index_rewards_manager_backfill.py
discovery-provider/src/tasks/index_spl_token_backfill.py
discovery-provider/src/tasks/index_user_bank_backfill.py

Fixes db leaks in backfill indexers.

Hotfix backfill indexer db leaks

---

identity-service/src/routes/user.js

This will let us avoid calling settings on every session
Created staging account & ensured that this would do the same thing

Add notification settings to users/update

---

libs/src/sdk/sdk.ts

Pass HTTP headers through to requests in SDK.
Tested on local

[PAY-730] Pass headers to requests in SDK

---

discovery-provider/src/api/v1/models/transactions.py
libs/src/sdk/api/generated/full/models/TransactionDetails.ts

Forgot to add `method` member to the Transactions API.
Tested on remote-dev with insomnia

Add method to transaction API

---

monitoring/healthz/src/DiscoveryHealth.tsx

Add storage to healthz

---

discovery-provider/nginx_conf/nginx.conf

add nginx rule for comms server

add nginx rule for comms server

---

discovery-provider/src/tasks/index_nethermind.py

Avoid a bunch of error logs when nethermind is disabled. No impact on logic.

Swallow nethermind indexing errors when disabled

---

discovery-provider/src/queries/get_feed_es.py
discovery-provider/src/queries/search_es.py
discovery-provider/src/utils/elasticdsl.py

Got the date time format wrong, so all it does is raise.  Just skip this for now.  Dang.

remove raise_if_stale code.

---

identity-service/src/notifications/processNotifications/createNotification.js
identity-service/src/notifications/sendNotifications/formatNotification.js

Skip notifs

---

.circleci/config.yml

We were not pulling so the changelog was not correct.
Tested via SSH-ing into a run of cut-release

Pull before cutting release so checklist is correct

---

discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py
discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
discovery-provider/src/tasks/entity_manager/social_features.py
discovery-provider/src/tasks/entity_manager/user.py

Add missing user challenge for profile update and verify
Updated tests

Add missing user and social feature challenges to entity manager

---

discovery-provider/README.md

Fix audius compose test readme

---

identity-service/src/routes/tiktok.js

Fixes an issue with tiktok auth causing 500 because we are trying to json stringify an axios object that has circular references.
TikTok oauth is not in use right now but will be with the coming Complete Profile w/ TikTok feature

Fix tiktok auth

---

discovery-provider/src/api/v1/tracks.py

Fix latest track default args

---

creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts

don't think we need this gating anymore - it is now safe to issue all reconfigs afaik
n/a
n/a

Remove primary reconfig restrictions that we no longer need

---

creator-node/src/services/stateMachineManager/stateReconciliation/recoverOrphanedData.jobProcessor.ts

CN improve "Error issuing request to recover orphaned data" log

---

creator-node/src/components/replicaSet/replicaSetController.js

Manual reconfig route bug

---

identity-service/src/notifications/milestoneProcessing.js
identity-service/src/notifications/processNotifications/addTrackToPlaylistNotification.js
identity-service/src/notifications/processNotifications/favoriteNotification.js
identity-service/src/notifications/processNotifications/milestoneListenNotification.js
identity-service/src/notifications/processNotifications/supporterRankChangeNotification.js
identity-service/src/notifications/processNotifications/tierChangeNotification.js
identity-service/src/notifications/processNotifications/tipNotification.js
identity-service/src/notifications/utils.js

Pt 2
Identity test suite + manually test

Replace remaining findOrCreates in identity notification system

---

discovery-provider/src/monitors/database.py

[PLAT-521] Add more table data to verbose health

---

discovery-provider/src/api/v1/playlists.py
discovery-provider/src/api/v1/tracks.py
discovery-provider/src/api/v1/users.py

oops forgot this part
tested locally
```
{
"data": "rb20aZz",
"success": true,
"latest_indexed_block": 41,
```

Wrap unclaimed API in proper response

---

creator-node/src/config.js

Added grassfed bc URSM unregistered, removed nodes with < 75% disk util
n/a
n/a

Update CN reconfig blacklist

---

identity-service/src/notifications/notificationQueue.js

Fix bug in https://github.com/AudiusProject/audius-protocol/commit/7cbc551a466b57965edc0e10cc7474c29fc8240c
Ran on staging and got a notification

Fix notification send

---

identity-service/src/notifications/notificationQueue.js

Fix identity lint

---

dev-tools/startup/startup.sh

Fix 
Audius compose up works now

fix file type

---

discovery-provider/src/api/v1/models/common.py
discovery-provider/src/queries/get_saves.py
libs/src/sdk/api/generated/default/models/Favorite.ts
libs/src/sdk/api/generated/full/models/Favorite.ts

Need timestamp data on short favorites fetch for offline mode.

Return favorite timestamp and sort by it

---

identity-service/src/routes/socialHandles.js

Fix typo in socialHandles.js

---

identity-service/src/routes/healthCheck.js

Expose this config through identity not optimizely

Expose EM users config via identity

---

identity-service/test/processNotifications/createNotification.js

Test is not deterministic, so this decreases the amount of load so that the test can complete in time

Lower number of subscribers for load test

---

identity-service/src/config.js
identity-service/src/routes/location.js

- New `/location` endpoint in Identity

[PAY-740] Add new location endpoint to Identity

---

discovery-provider/alembic/versions/3cdcb5e303f8_remove_subscriptions_fk_constraint.py
discovery-provider/src/models/social/subscription.py

Attempted block revert was stalling indexing bc of these FKs

Remove blocks FKs from subscriptions table

---

creator-node/src/diskManager.ts

When looking through files that weren't being migrated, I noticed some CIDs were being missed entirely. After playing around with the pagination queries manually, it turns out the problem has to do with the non-intuitive way SQL handles numbers and letters in string comparisons (explanation below).
The solution is to, at each window, compare in `[Qm**0000000000000000000000000000000000000000000, Qm**zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz]` instead of doing both `[Qm**a, Qm**z]` and `[Qm**0, Qm**9]` (asterisks represent the pagination characters from a-z and 0-9). **This has the nice side effect of also making pagination twice as fast!** (4x as fast overall since the 2x speedup is done twice - once for custom and once for legacy).
Here are some manual SQL queries to show this working …

Catch missing edge cases in storagePath pagination

---

discovery-provider/src/tasks/index_trending.py

Get the right values for final poa block
Currently trending is not working on trending bc of this bug
None

Fix trending final poa

---

libs/Dockerfile
libs/src/AudiusLibs.ts
libs/src/api/Account.ts
libs/src/api/Users.ts
libs/src/services/creatorNode/CreatorNode.ts
libs/src/services/dataContracts/AudiusContracts.ts
libs/src/services/dataContracts/UserFactoryClient.ts
libs/src/services/discoveryProvider/DiscoveryProvider.ts
libs/src/services/wormhole/Wormhole.ts
libs/tests/audiusTokenClientTest.js
libs/tests/stakingTest.js
libs/tsconfig.json

typecheck wasn't being validated in ci for a while
- fixes issues
- adds check to dockerfile

Fix lib types, add CI check

---

discovery-provider/integration_tests/queries/test_notifications/test_follow_notification.py
discovery-provider/integration_tests/queries/test_notifications/test_paginate_notification.py
discovery-provider/integration_tests/queries/test_notifications/test_remix_track_notification.py
discovery-provider/integration_tests/queries/test_notifications/test_repost_notification.py
discovery-provider/integration_tests/queries/test_notifications/test_save_notification.py
discovery-provider/integration_tests/utils.py
discovery-provider/src/queries/get_notifications.py

Add method to fetch notification from discovery
Fixes PLAT-512
Wrote tests for several notifications

Add fetch notifs method

---

discovery-provider/alembic/versions/ec3b20d7bce3_backfill_track_cid.py
discovery-provider/alembic/versions/f6f009132212_add_track_is_playlist_upload.py

Fix track cid backfill alembic version

---

identity-service/src/config.js
identity-service/src/notifications/index.js

Implement solana notifs safer min/max slot logic

---

identity-service/sequelize/migrations/20221219201744-add-indices-to-slot-and-blocknum.js
identity-service/src/notifications/index.js

Avoid updating or publishing already seen notifications

---

discovery-provider/alembic/versions/ec3b20d7bce3_backfill_track_cid.py

Remove tmp dir at the beginning and end of this function. shutil.rmtree is recursive so other os.remove is not necessary.
testing on stage DN

Fix backfill track cid tmp removal

---

identity-service/src/routes/instagram.js
identity-service/src/routes/twitter.js

Add handle check

---

dev-tools/commands/src/upload-track.mjs

Fixes audius-cmd upload
Tested on a remote dev box
NA

Minor fixes for cmd upload

---

discovery-provider/src/api/v1/api.py
discovery-provider/src/api/v1/cid_data.py
libs/src/sdk/api/generated/full/.openapi-generator/FILES
libs/src/sdk/api/generated/full/apis/index.ts

Rename to full_ns from ns for clarity - it is a full endpoint. 
Added doc=False for redundancy, although I believe full endpoints are not documented.

Rename to full for clarity

---

libs/src/services/contracts/ContractClient.ts

Fixes runtime error where we check method existence on a missing _contract object.

[C-1697] Fix contract method check runtime error

---

creator-node/src/config.js

disable backgroundDiskCleanupCheckEnabled

---

creator-node/src/config.js

disable storagePath migrations

---

discovery-provider/nginx_conf/nginx.conf

Remove caching for this API since we want to avoid any collisions.

Remove caching for unclaimed ID

---

creator-node/src/config.js

Re-enable CN background tasks

---

creator-node/src/routes/tracks.js

There's two commits and each of them do one thing, might be best to review each commit individually.
1. Modify how caching works in /tracks/stream to minimize sql queries, discovery lookups
2. Add debug timings for /tracks/stream route to debug long running queries
Tested this on staging by hitting a non-cached /tracks/stream route and making sure it sets the redis key as expected. Then subsequently hitting the stream route uses the cached CID value
I added some logs to observe times for the fallback flow in the event trackBlockchainId doesn't exist (which also seems to cause perf issues). https://audius.loggly.com/search#terms=Track%20stream%20debug%20timings&from=2022-12-21T01:05:21.993Z&until=2022-12-21T01:35:21.993Z&source_group=

Content node /track/stream optimizations

---

identity-service/src/routes/instagram.js

Fix instagram request bug

---

creator-node/src/config.js

Enable EM by default in content nodes in case they're missing the env var.

Default EM users in content node

---

creator-node/src/config.js

Update CN reconfigSPIdBlacklistString

---

discovery-provider/alembic/versions/1b6e405ef358_fix_is_current_for_users_and_tracks_due_.py
discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
discovery-provider/src/tasks/entity_manager/track.py
discovery-provider/src/tasks/entity_manager/user.py
discovery-provider/src/tasks/entity_manager/user_replica_set.py

Fixes a bug where we invalidate an existing record and then raise an exception which leaves the existing record is_current false. Before bulk upserting all records for a block, entity manager correctly updates current values for all new records to be appended and then sets their existing records to be false. So, we shouldn't have any invalidation logic while processing txs.
This bug is particularly vulnerable in user indexing where we validate metadata **after** validating the tx then invalidating the existing record. The metadata validation led to a couple cases where a user / track could be is_current false.
* user updates a track (invalidates the existing track record), sets an artist pick (invalidates the existing user record), user fails metadata validation because the track does not …

Fix entity manager invalidation for user and tracks

---

discovery-provider/src/premium_content/helpers.py
discovery-provider/src/premium_content/premium_content_access_checker.py
discovery-provider/src/premium_content/premium_content_types.py
discovery-provider/src/schemas/track_schema.json
libs/src/services/schemaValidator/schemas/trackSchema.json
libs/src/utils/types.ts

Add ability to gate premium content based on a user tipping an artist.
Remote dev. Upload track gated on a tip to the artist, have a user tip the artist, check that user has access (signature generated). Also check that non-tipper does not have access.
None

[PAY-782] Add tip gate for premium content

---

discovery-provider/src/premium_content/signature.py
discovery-provider/src/premium_content/signature_unit_test.py
discovery-provider/src/queries/get_premium_track_signatures.py
discovery-provider/src/queries/get_track_stream_signature.py
discovery-provider/src/queries/query_helpers.py

To support this PR https://github.com/AudiusProject/audius-protocol/pull/4550 for blacklisting purposes.
Deploy to remote box and made sure that premium content signature was generated with track id.
None

[PAY-802] Add track id to premium content signature data

---

discovery-provider/nginx_conf/main.lua

deny `clique_` RPCs but allow all other for now.
tested on stage dn1 with identity

Sp nethermind web3

---

.circleci/release-scripts/bump-hotfix.sh
.circleci/release-scripts/cut-release.sh
.circleci/release-scripts/dheeraj-test.sh
.circleci/release-scripts/evaluate-proposal.sh
.circleci/release-scripts/release-to-service-providers.sh
.circleci/release-scripts/slash-proposal.sh

These were broken when they were moved into the audius-protocol repo in https://github.com/AudiusProject/audius-protocol/pull/4487

Fix release scripts

---

discovery-provider/src/utils/eth_contracts_helpers.py

Fix CN spid when getting CN info from chain

Fix spid key in availability indexing

---

libs/src/AudiusLibs.ts
libs/src/services/solana/SolanaWeb3Manager.ts

- Removes default audiusDataIdl in SolanaWeb3Manager to fix native-libs.
- Moves default audiusDataIdl into configSolanaWeb3 for web/node libs

Remove default audiusDataIdl from native libs

---

discovery-provider/src/app.py
discovery-provider/src/utils/eth_contracts_helpers.py

Just a little more cleanup.
CI tests

Remove registry contract and clean up log

---

creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts

REmoves reconfig code in CN statemachine that first tries URSM, and goes directly to EM
it also errors if EM config is disabled

Change CN legacy URSM code to not first attempt URSM reconfig, and go straight to EM now that it is rolled out globally

---

libs/src/sanityChecks/index.ts
libs/src/sanityChecks/rolloverNodes.ts

check for blacklist having primary before declaring healthy

---

libs/package.json

Patch Package isn't supported for projects that are consumed as NPM packages. It looks for the deps in the local node_modules, which is not the proper location when the package is installed as a dep. Our particular use case for patch package doesn't involve any real code changes, just type fixes for a package with less strict types. We can safely ignore these patches on a real build.

Move patch-package to prepare

---

libs/src/sanityChecks/rolloverNodes.ts

Use entity manager in rollover

---

discovery-provider/integration_tests/premium_content/test_access.py
discovery-provider/src/schemas/track_schema.json
libs/src/sdk/api/generated/full/models/PremiumConditions.ts
libs/src/services/schemaValidator/schemas/trackSchema.json
libs/src/utils/types.ts

Include nft collection name, slug, and permalink during premium track upload as part of the track schema so that we may later be able to display the nft collection name and link to the collection.
Make sure that the new properties are included in the uploaded track metadata and that it's stored on DN.
None

[PAY-805] Update premium conditions in track schema

---

.circleci/config.yml

Disable CI maddog jobs since it is broken and deprecation is imminent

---

.circleci/config.yml
discovery-provider/alembic/versions/ec3b20d7bce3_backfill_track_cid.py
discovery-provider/alembic/versions/f6f009132212_add_track_is_playlist_upload.py

Fix two migrations that are not idempotent
Prod node deploy
Release

Fix migration idempotency 

---

dev-tools/audius-compose
discovery-provider/alembic/versions/2571ec7593c7_init_db_models.py
discovery-provider/integration_tests/tasks/test_index_operations.py
discovery-provider/integration_tests/utils.py
docker-compose.m1.test.yml

Fixes tests broken in https://github.com/AudiusProject/audius-protocol/pull/4576
CI tests

[PLAT-570] Fix tests broken in prior commit

---

identity-service/package-lock.json
identity-service/package.json
identity-service/src/relay/txRelay.js
identity-service/src/routes/instagram.js
identity-service/src/routes/tiktok.js
identity-service/src/routes/twitter.js

Remove EM gating on identity.
not sure why package-lock diff is so huge.

Use EntityManager only for verify user

---

audius.code-workspace
comms/Makefile
comms/schema/schema.go
comms/schema/schema.ts
libs/src/sdk/api/chats/ChatsApi.ts
libs/src/sdk/api/chats/clientTypes.ts
libs/src/sdk/api/chats/serverTypes.ts

Syncs the schema between SDK and go-comms server. Also adds the comms folder to the workspace.

Update DMs schema

---

docker-compose.test.yml

audius-compose test is broken on main
audius-compose test run discovery-provider
NA

Fixes for audius-compose test run

---

comms/DockerfileFast
comms/Makefile
comms/storage/storage.go
monitoring/healthz/src/DiscoveryHealth.tsx

and healthz content node dashboard

fixes precommit hook

---

discovery-provider/src/utils/cid_metadata_client.py

Fix bad unicode chars

---

discovery-provider/src/tasks/index.py

Mbrier/plat 000/revert subscriptions

---

.circleci/config.yml

Remove solana anchor tests in CI

---

discovery-provider/integration_tests/queries/test_user_playlist_update.py
discovery-provider/src/api/v1/api.py
discovery-provider/src/api/v1/helpers.py
discovery-provider/src/api/v1/models/notifications.py
discovery-provider/src/api/v1/notifications.py
discovery-provider/src/api/v1/utils/extend_notification.py
discovery-provider/src/queries/get_notifications.py
discovery-provider/src/queries/get_user_playlist_update.py

Add the notifications routes as endpoint in the discovery api
Note these methods were already created and tested, this change just exposes them via the api 
Ran e2e locally and hit the endpoints

Fix notifications endpoint

---

.circleci/config.yml

This is failing because of slow eth tx's
https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/33318/workflows/aea1287a-25f3-48c9-9ddf-8879fb3f6a9b/jobs/421133

Increase CI timeout

---

libs/src/sdk/api/chats/ChatsApi.ts

Updates the SDK to allow setting reactions to null
None 👻

Update SDK chats.react to allow null reactions

---

libs/src/sdk/api/chats/clientTypes.ts

Removes the unnecessary chatId param from chats.create(), as that method generates a chatId for the consumer!

Remove unnecessary chatId param from chats.create()

---

dev-tools/README.md

1. add summary of available tools at the top
2. move docker resource reqs step to before startup to ensure run in order
3. add clarity to setup instructions
4. minor other cleanup

dev-tools README improvements for clarity

---

discovery-provider/src/app.py
discovery-provider/src/tasks/index_nethermind.py

Index until the beginning of the new chain after a reset and consider that the intersection with the final_poa_block.

Add indexing after chain reset

---

contracts/migrations/6_nethermind_entity_manager_migration.js
contracts/truffle-config.js
discovery-provider/scripts/reset_chain.sh

Script for resetting chain state on stage. Intended for when stage chain has stopped producing blocks and discovery nodes are stuck at the same block. 
Tested in parts on single nodes but will test across staging within a maintenance window.

Add script to reset stage chain

---

libs/src/sdk/middleware/discoveryNodeSelectorMiddleware.ts

Similar to https://github.com/AudiusProject/audius-protocol/pull/4619. Had to add the empty string check in the API response health check as well.
Tested locally by using `npm link` to link sdk to local client.

Skip API response version check if empty string

---

discovery-provider/alembic/versions/6a9f01e775d5_update_triggers.py

Fix alembic version

---

discovery-provider/src/queries/get_health.py

Add chain health check so we have visibility on all nodes.

Add chain health check

---

comms/db/migrations/20230117200411_add_chat_last_message.sql
comms/db/queries/get_chats.go
comms/db/queries/get_summaries.go
comms/internal/rpcz/chat.go
comms/schema/schema.go
comms/schema/schema.ts
comms/server/response_mapper.go
comms/server/server.go
comms/server/server_test.go
libs/src/sdk/api/chats/serverTypes.ts

- Paginate `/chats`
- Add most recent message to the query response for each chat
Server tests

Comms chats endpoint updates

---

discovery-provider/alembic/versions/a62b4e92b733_fix_nullified_track_cid.py

Updating alembic head. tested by running audius compose and ensuring dn container starts healthy

Fix alembic head

---

discovery-provider/scripts/reset_chain.sh

update chain reset to include all DNs

---

discovery-provider/src/queries/get_premium_track_signatures.py

Realized that account info is sometimes null and this caused an issue.
Also properly handle optional fields in nft metadata.
on canary prod dn4
n/a

Fix nft ownership check

---

creator-node/src/contentAccess/contentAccessChecker.ts
creator-node/src/contentAccess/types.ts
creator-node/src/middlewares/contentAccess/contentAccessMiddleware.ts
creator-node/src/routes/tracks.js
creator-node/test/contentAccessChecker.test.ts

Modify new `/cidstream` route to:
* Add Blacklist check
* Add step to record track listen
Working with @sddioulde to get it tested locally with the new discovery routes.
Extensive testing on staging will be done by Saliou and I as well to ensure a smooth premium content roll out
This route will be monitored using the grafana dashboard for HTTP requests. We'll be able to see how often it's used and how often it fails

[CON-546] Check blacklist and record track listen in stream route

---

creator-node/src/middlewares/readOnly/readOnlyMiddleware.test.ts
creator-node/src/middlewares/readOnly/readOnlyMiddleware.ts

We use POST requests for certain read-only actions in CN. We should ensure those still work even in readOnlyMode
NOTE - i was originally going to add `/blacklist/add` route here but i realized that will modify the db so we don't want to do it. it is safe since no new content will be added anyway
added new test
n/a

CN Ensure certain POST routes still work in readOnlyMode

---

comms/storage/transcode/static/status.html
creator-node/nginx_conf/nginx.conf
discovery-provider/nginx_conf/nginx.conf

nginx config so websockets work
tested on stage CN8

fix comms websocket config

---

libs/src/sdk/api/chats/ChatsApi.ts
libs/src/sdk/api/chats/clientTypes.ts

Properly paginate chats from the SDK side. Also fixes `this` bug introduced this morning

SDK: Paginate getChats

---

monitoring/healthz/src/DiscoveryHealth.tsx

Null means chain is not running. Unhealthy means not processing/producing blocks. Healthy means producing blocks.
Ran locally

Add chain health to healthz

---

docker-compose.yml
identity-service/test/redis.js

We can probably merge this before the bigger CI change, wdyt @cheran-senthil ?
```
audius-compose test up identity-service
> npx mocha
```

Fix audius-compose test identity-service

---

libs/src/api/Account.ts
libs/src/api/Users.ts

Bug in signup where Account.signUp doesn't return userId and block info.
Tested against stage.

Fix account signup return block and userID

---

identity-service/src/routes/user.js

Every page load on stage/prod 400s because of duplicates of this.

Fix identity users/update 400s

---

discovery-provider/src/queries/query_helpers.py

Update 500 to 10K. Prevents absurd usage, but will probably solve our offline woes

Bump max limit

---

identity-service/src/routes/location.js

Switch to IPData API instead of IPAPI.
Tested on remote-dev. However have not tested any consumers to ensure it's working e2e yet.

[PAY-849] Use IPData instead of IPAPI in identity /location

---

discovery-provider/src/exceptions.py
discovery-provider/src/solana/solana_client_manager.py
discovery-provider/src/tasks/index_spl_token.py

Just some minor naming cleanup.
Was not able to test on remote-dev as there don't seem to be many of these transactions coming through right now. But the code changes look pretty straightforward so I'd like to just push to staging and observe behavior.

[PAY-877] Cleanup solana tx fetching errors

---

.circleci/config.yml
creator-node/Dockerfile
creator-node/compose/docker-compose.yml
creator-node/scripts/run-tests.sh
docker-compose.test.yml

Fix redis version for creator build

---

comms/Makefile
comms/bash_scripts/deploy.sh
comms/bash_scripts/deploy_content.sh
comms/bash_scripts/deploy_discovery.sh
comms/bash_scripts/nuke.sh
comms/bash_scripts/nuke_server.sh
comms/discovery/config/config.go
comms/discovery/jetstream/jetstream_client.go
comms/natsd/nats_main.go
comms/natsd/nats_manager.go
comms/natsd/redact_ip.go
comms/natsd/redact_ip_test.go
comms/natsd/self_connection_probe.go
comms/shared/peering/exchange_endpoint.go
comms/shared/peering/info.go
comms/shared/peering/solicit.go
creator-node/Dockerfile

NATS container will do a self connection test on start and only attempt to start nats + join nats cluster if self connection test passes.  This reduces the cluster connection attempts that spammed the logs on the first go around.
Redacts full IP addresses from status debug endpoints.
Adds exponential backoff to polling for peers.

Nats is reachable

---

discovery-provider/plugins/network-monitoring/src/metrics/queries.ts

Some queries on network monitoring have been a little flaky. With this change, if you metrics fails for whatever reason, the other will be fine.
n/a since it's such a small change
We'll be able to monitor this change with traces, metrics on the Network Monitoring grafana dashboard, and the slack alerts.

[CON-566] Add try/catch to all metrics sql queries

---

discovery-provider/src/tasks/entity_manager/social_features.py

Fix Error `discovery-provider/src/tasks/entity_manager/social_features.py:236:9: F821 undefined name 'action_to_record_type'` caused by merge issue of 
#4677 and #4592

Fix social feature undefined

---

discovery-provider/alembic/trigger_sql/handle_repost.sql
discovery-provider/alembic/versions/72b030bb3dcb_handle_repost_fix.py

Add migration for handle repost fix

---

discovery-provider/alembic/trigger_sql/handle_repost.sql
discovery-provider/alembic/versions/72b030bb3dcb_handle_repost_fix.py
discovery-provider/alembic/versions/a62b4e92b733_fix_nullified_track_cid.py

https://github.com/AudiusProject/audius-protocol/pull/4694 was deployed to prod on the release branch.
This change adds it to main and reconciles w the existing migration for 0.3.76. I can set stage back a couple revisions to make sure the migration runs and updates the trigger.
https://github.com/AudiusProject/audius-protocol/pull/4695 should fix root cause.

Cherry pick and reconcile repost fix migration

---

discovery-provider/src/tasks/index.py
discovery-provider/src/tasks/index_nethermind.py

Added this in the wrong place but we probably don't even need it anyway. It was just added earlier today.

Fix autoflush arg in session

---

identity-service/test/routes/trackListensTest.js

small errors in tests with this change https://github.com/AudiusProject/audius-protocol/pull/4609/files#
tests pass

Fix identity solana listen test

---

discovery-provider/src/tasks/prune_plays.py

Archiving more plays so we can clear up disk space. After this goes out, I want to drop the plays_archive entirely and have this job prune up to the past year. 
I reviewed all our uses of the Plays table to make sure this is still safe to do. In the worst case we can move archived plays back. It's just a layer of safety.

Archive plays up to 2022

---

.vscode/settings.json
discovery-provider/.vscode/settings.json

Lint disc prov when opening from root

Apply discprov settings.json from audius-protocol

---

libs/src/api/Account.ts

Remove userbank creation from sign up
https://github.com/AudiusProject/audius-client/pull/2780

Remove user bank from sdk signup

---

discovery-provider/integration_tests/queries/test_get_sitemap.py
discovery-provider/src/queries/get_sitemap.py
discovery-provider/src/queries/get_top_playlists.py

Update sitemap endpoint to use playlist routes 
Can you verify that the route is correct, ie 
route should be `<USER_HANDLE_LOWERCASE> / <ALBUM OR PLAYLIST> / <PLAYLIST_ROUTE_SLUG>`
I forgot the difference between title_slug and slug
Updated test to verify it uses the playlist route

Update playlist sitemap

---

identity-service/src/routes/tiktok.js

Fixes the where clause when looking up a TikTokUser, this is what happens when no typescript :(

Fix TikTok association

---

discovery-provider/src/api/v1/helpers.py
discovery-provider/src/api/v1/models/users.py
libs/package-lock.json

Artist pick track id wasn't encoded...
Deployed and tested API on staging

Encode artist pick track id in API responses

---

discovery-provider/src/app.py

Prune more plays so we can finish pruning by next release.
Tested on canary. Each run completes in less than a second so it's safe to do.

Is more pruning

---

libs/src/services/identity/IdentityService.ts

Adds proper types to `identityService.getUserBankTransactionMetadata`

libs: Use proper types in identityService.getUserBankTransactionMetadata

---

discovery-provider/alembic/versions/6f98e9709e3e_fix_is_available.py
discovery-provider/alembic/versions/988f095a1d43_add_is_repost_repost_column.py

Fix erroneously changed state
```
alembic upgrade head
```

Fix is_available on three tracks

---

libs/src/services/identity/IdentityService.ts

Fixes types for getUserBankTransactionMetadata (again)

[Libs] Fix types for identityservice in libs

---

comms/Dockerfile.v2

Fast follow to remove unused packages added [here](https://github.com/AudiusProject/audius-protocol/pull/4729/files#diff-f7b68c7b436487c21f2597abd8fd0dcf2ce99793e001d2db367108d1ba25f70eR3).
N/A
N/A

Remove unused packages in storage build

---

discovery-provider/src/app.py

Fix crontab import lint error

---

comms/DockerfileM1
dev-tools/audius-compose
docker-compose.yml

Local compose with comms

---

libs/src/sdk/api/generated/default/models/User.ts
libs/src/sdk/api/generated/default/runtime.ts
libs/src/sdk/api/generated/full/models/UserFull.ts
libs/src/sdk/api/generated/full/runtime.ts
libs/src/sdk/api/generator/templates/typescript-fetch/runtime.mustache

Sorts the querystring so that it's deterministic. Useful for signature recovery in DMs land.

SDK: Sort querystring in API requests

---

libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.ts

Fixes bug where SDK reselects every non-full request.

SDK: Succeed API response healthcheck if version field not on response

---

libs/package-lock.json
libs/package.json

Bump SDK to v2.0.2-alpha.0 manually for consumption in client ([CI publish job missing, linear tracking](https://linear.app/audius/issue/INF-348/publish-sdk-via-ci))

SDK v2.0.2-alpha.1

---

comms/Makefile
comms/discovery/config/placement.go
comms/discovery/db/conn.go
comms/discovery/discovery_main.go
comms/discovery/pubkeystore/recover.go
comms/discovery/server/server_test.go
comms/shared/peering/signed_request.go
comms/storage/storageserver/storageserver_test.go
comms/storage/transcode/jobs.go

* fixes DM test to use time query param
* skips e2e upload test that hangs

Fix comms tests

---

libs/src/api/entityManager.ts

Allow metadata to be passed for entity manager social actions in libs. This wil let us send useful metadata for reposts to indicate if a repost is a repost of a repost

Update entity manager libs social actions to accept metadata

---

discovery-provider/src/tasks/index.py
discovery-provider/src/tasks/index_nethermind.py

Skip metadata fetching for social features. In these cases, metadata is not a CID and doesn't require fetching.

No fetching metadata for social features

---

comms/storage/storageserver/static/status.html

Added a event handler to check the input accepted depending on the item selected
Ran locally and tried all the options

[CON-572] change mimetype on input

---

libs/package-lock.json
libs/package.json
libs/src/sdk/api/chats/ChatsApi.ts
libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts

Creates a chat ID deterministically, using the participants. Also fixes reselection for API requests

SDK: Create chat IDs deterministically

---

comms/storage/storageserver/static/status.html

Changing the default selected option on the storage webapp to be audio since that's what we're working with mostly
Run `status.html` and made sure `audio` was the default
```
make storage.dev
```

Change default selected option

---

discovery-provider/integration_tests/tasks/test_update_track_is_available.py
discovery-provider/integration_tests/utils.py
discovery-provider/src/tasks/update_track_is_available.py

Check for CIDs that are blacklisted and mark them as unavailable too.
Updated existing integration test.

Mark blacklisted CIDs as unavailable

---

libs/src/services/solana/SolanaWeb3Manager.ts

[PAY-902] Support adhoc userbank creation

---

creator-node/src/contentAccess/contentAccessChecker.ts

Update signature ttl to 48hours

---

libs/src/api/Notifications.ts
libs/src/services/discoveryProvider/DiscoveryProvider.ts
libs/src/services/discoveryProvider/requests.ts

Ran lint fix in libs
just lint

lint libs notifications

---

dev-tools/audius-compose

Fix some of my stupidity
Circle CI
NA

Remove build from test up

---

discovery-provider/alembic/versions/0f75bcb73b0a_update_triggers_for_notifications.py
discovery-provider/alembic/versions/9b4e12c0c428_21523_track_cids.py

Changes the order of alembic version to patch this version into the current release

change order of alembic for patching to release

---

identity-service/package.json
identity-service/src/config.js
identity-service/src/routes/user.js

Replaces SEON with Sendgrid for email validation API purposes.
Tested on stage node

[INF-354] Move to sendgrid for email validation

---

dev-tools/setup-dev.sh

Remove service cmds and mad dog

---

creator-node/Dockerfile

Alpine 3.14 dropped the node version we were using. See https://pkgs.org/download/nodejs
We also only needed npm for `npx` which is pretty unnecessary.

Fix cn build

---

docker-compose.test.yml

Fix libs tests

---

discovery-provider/alembic/versions/abdb338530cd_add_is_save_of_repost_to_saves_table.py
discovery-provider/src/models/social/save.py

Forgot to add the notification for when someone saves reposted content! Adding column to the table

Add is_save_of_repost to saves table

---

comms/README.md
comms/discovery/db/migrations/20230224160015_chat_indexes.sql
comms/discovery/rpcz/apply.go
comms/shared/config/constants.go

* adds indexes to chat_ tables
* does websocket push in a separate go routine.
* as noted in commit msg this is not ideal... should use a channel and dedicated go routines... but probably fine for now.

DM indexes

---

discovery-provider/src/tasks/index_user_bank.py

Still fetches the transactions in parallel, but processes them sequentially. Seems to work on stage!

[PAY-902] Process userbank transactions sequentially

---

docker-compose.test.yml

Broken in https://github.com/AudiusProject/audius-protocol/pull/4829

Use node_modules instead of npx for test

---

discovery-provider/plugins/notifications/Dockerfile

Remove platform specific build from discovery notifications so local up works

Remove platform

---

discovery-provider/src/tasks/index_user_bank.py

There was no active session :(

Fix broken userbank indexing

---

discovery-provider/alembic/versions/4b3b96d8149b_update_handle_repost_trigger.py

fix migration head on handle repost migration

---

comms/storage/storageserver/storageserver.go

#4850 merged wonky and resulted in code that didn't compile. This fixes that
Ran make to make sure it compiled and worked as expected

fix: Storage Server merge issue

---

comms/shared/peering/peering.go
comms/storage/tests/mock_peering.go

stubbed out a few more NATS mock methods so a bit more completeness. 
These new stubs are used currently for any tests but I reran the tests relying on the current stub to make sure everything still works

house keeping

---

discovery-provider/integration_tests/premium_content/test_access.py
discovery-provider/src/premium_content/helpers.py
discovery-provider/src/premium_content/premium_content_access_checker.py
discovery-provider/src/queries/get_track_stream_signature.py
discovery-provider/src/tasks/entity_manager/social_features.py

Fix save and repost for gated tracks that are unlocked by the user.
FYI, the issue was that the indexer was trying to make a db query but outside of its db context.
deployed on a stage DN and pointed client to it and tested.

Fix social actions on accessible gated tracks

---

discovery-provider/src/api/v1/utils/extend_notification.py

Fix small bug in notifications query. 

Fix notification seen at

---

discovery-provider/src/tasks/entity_manager/social_features.py

Currently, users cannot repost/favorite collectible gated tracks successfully.
This PR makes it so that users can repost/favorite gated tracks they have access to. There will be work done in the future to uncomment this logic and handle the case for collectible gated tracks.

Comment out indexer code that gates social actions

---

discovery-provider/integration_tests/notifications/test_save_of_repost.py
discovery-provider/integration_tests/queries/test_notifications/test_get_unread_notification_count.py
discovery-provider/src/api/v1/models/notifications.py
discovery-provider/src/api/v1/notifications.py
discovery-provider/src/queries/get_notifications.py
discovery-provider/src/utils/helpers.py

Add unread count to /v1/notifications endpoint

Add unread count

---

identity-service/src/routes/healthCheck.js

notifications health check is down and adding logs to debug

Add logs to notifications health check

---

.circleci/commands/gcp-run.yml
.circleci/jobs/gcp-cleanup.yml

Cleanup GCP firewall rules
NA
NA

Improve cleanup flow, and cleanup firewalls

---

identity-service/src/notifications/processNotifications/createNotification.js
identity-service/src/notifications/processNotifications/index.js

Ignore process create notifications

ignore processing 'create' notifications

---

identity-service/src/notifications/sendNotifications/formatNotification.js

Ignore push create track notif

---

creator-node/src/middlewares/contentAccess/contentAccessMiddleware.ts

Fix newline character in track copy320 cid when checking access.

Remove newline char on cid

---

creator-node/src/contentAccess/contentAccessChecker.ts
creator-node/src/middlewares/contentAccess/contentAccessMiddleware.ts

The previous changed failed the signature recovery step. This is a simpler fix.
Going to test on track that previously failed.

Fix cid comparison

---

.circleci/jobs/release-audius-docker-compose.yml
.circleci/jobs/release-discord.yml
.circleci/jobs/release-github-draft.yml
.circleci/jobs/release-github.yml
.circleci/jobs/release-governance.yml

The GitHub release was not following the correct convention and the release URL did was inaccurate, this PR fixes both issues
NA
NA

Fix some release related errors in Circle CI

---

discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/trendingTrack.test.ts.snap
discovery-provider/plugins/notifications/src/__tests__/mappings/trendingTrack.test.ts
discovery-provider/plugins/notifications/src/email/notifications/components/Body.tsx
discovery-provider/plugins/notifications/src/email/notifications/components/notifications/Notification.tsx
discovery-provider/plugins/notifications/src/email/notifications/renderEmail.ts
discovery-provider/plugins/notifications/src/processNotifications/mappers/mapNotifications.ts
discovery-provider/plugins/notifications/src/processNotifications/mappers/trendingTrack.ts
discovery-provider/plugins/notifications/src/types/notifications.ts
discovery-provider/plugins/notifications/src/utils/format.ts
discovery-provider/plugins/notifications/src/utils/populateDB.ts

Add trending track mapping to notifications plugin
I missed this in the previous pass
Added push notification and email render tests

Add trending track

---

identity-service/package-lock.json
identity-service/package.json
identity-service/scripts/dev-server.sh
identity-service/src/index.ts

This reverts commit 6048011eb4072f781e101b4d3518465ac67fa1ee.
Restarts weren't working properly inside the docker container. Will fix and include updates for content node too

Revert "[INF-364] Improve identity reload speed (#4899)"

---

creator-node/package-lock.json
creator-node/package.json
creator-node/scripts/start.sh
creator-node/src/apiSigning.ts
creator-node/src/app.ts
creator-node/src/components/tracks/trackContentUploadManager.ts
creator-node/src/diskManager.ts
creator-node/src/fileManager.js
creator-node/src/index.ts
creator-node/src/resizeImage.js
creator-node/src/serviceRegistry.js
creator-node/src/services/URSMRegistrationManager.js
creator-node/src/services/initAudiusLibs.js
creator-node/src/services/stateMachineManager/stateMachineUtils.js
creator-node/src/utils/cidUtils.ts
creator-node/src/utils/fileHasher.js
discovery-provider/src/api/v1/tracks.py
identity-service/scripts/dev-server.sh
identity-service/src/app.js
identity-service/src/index.ts

Speeds up `audius-compose up` and CN hot reloads:
- Bringing up the whole stack is down to just over 4m instead of 8m. Identity is the bottleneck - it takes well over 3m
- CN hot reloading takes ~45s. Ideally it would only take a few seconds, but this is much better than before when it took multiple minutes to reload a tiny change
Main changes:
CN:
- Import libs asynchronously as early as possible and default to not linking it
- Disable cluster so it only has to load libs once instead of waiting for master to load and then again waiting for a child process to load (significantly speeds up hot reloading)
- Fix a bug that prevented image upload - but only locally - because of a combination of libs and TS transpiling weirdness
```
"Error: computeFilePathAndEnsureItExists is not a function\n …
```

Disable linking libs by default, optimize CN hot reloading, fix bug

---

libs/package-lock.json
libs/package.json

- #4900 by Dylan Jeffers
- #4883 by Michelle Brier
- #4812 by Cheran Revert

Bump sdk to v2.0.2-alpha.4

---

identity-service/src/notifications/processNotifications/createNotification.js
identity-service/src/notifications/sendNotifications/formatNotification.js

Revert track-create push notifs change on Identity

---

identity-service/src/routes/healthCheck.js

Clearing up a lot of cruft here to fix these checks. All we should care about is success, failure, and latency.
Before, we would go check transactions from relayer wallets which we don't really need anymore (ACDC doesn't even use relayer wallets).
Also, the loop to check for total latency didn't work: `const tx in successfulTxsInRedis` should be `const tx of successfulTxsInRedis` and the json string would then need to be parsed.

Fix identity relay checks

---

identity-service/src/relay/txRelay.js
identity-service/src/routes/healthCheck.js

zrange doesn't take -inf inf as args even though documentation says it's valid.
cleaning up some logs too
tested on stage

Fix zrange args and clean up logs

---

.circleci/workflows/main.yml
docker-compose.yml

Push the comms image through Circle CI
Circle CI
NA

Push comms through Circle CI

---

.circleci/workflows/main.yml

Enable auto-deploy stage

---

discovery-provider/nginx_conf/main.lua

client and maybe identity requires net requests to get chain ID.

Allow net /nethermind requests

---

identity-service/src/routes/healthCheck.js

Default values are making this error on stage because there's not enough transactions. I think it's better to have no defaults.  

Remove defaults for relay checks

---

discovery-provider/src/api/v1/notifications.py

Fix timestamp for unread count

Fix unread count

---

discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/follow.test.ts.snap
discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/repost.test.ts.snap
discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/save.test.ts.snap
discovery-provider/plugins/notifications/src/__tests__/mappings/follow.test.ts
discovery-provider/plugins/notifications/src/__tests__/mappings/repost.test.ts
discovery-provider/plugins/notifications/src/__tests__/mappings/save.test.ts
discovery-provider/plugins/notifications/src/email/notifications/components/notifications/MultiUserHeader.tsx
discovery-provider/plugins/notifications/src/email/notifications/components/notifications/Notification.tsx
discovery-provider/plugins/notifications/src/email/notifications/components/notifications/NotificationBody.tsx
discovery-provider/plugins/notifications/src/email/notifications/renderEmail.ts
discovery-provider/plugins/notifications/src/email/notifications/types.ts
discovery-provider/plugins/notifications/src/processNotifications/mappers/challengeReward.ts
discovery-provider/plugins/notifications/src/processNotifications/mappers/create.ts
discovery-provider/plugins/notifications/src/processNotifications/mappers/follow.ts
discovery-provider/plugins/notifications/src/processNotifications/mappers/milestone.ts
discovery-provider/plugins/notifications/src/processNotifications/mappers/reaction.ts
discovery-provider/plugins/notifications/src/processNotifications/mappers/repost.ts
discovery-provider/plugins/notifications/src/processNotifications/mappers/save.ts
discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterDethroned.ts
discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterRankUp.ts
discovery-provider/plugins/notifications/src/processNotifications/mappers/supportingRankUp.ts
discovery-provider/plugins/notifications/src/processNotifications/mappers/tierChange.ts
discovery-provider/plugins/notifications/src/processNotifications/mappers/tipReceive.ts
discovery-provider/plugins/notifications/src/processNotifications/mappers/tipSend.ts

Fix follows, repost, and saves with multi user notifications - ie rollup of notification in email
Added more tests for when the duplicate notification of same type is rolled up

fix mappers and add multi support

---

creator-node/test/dbManager.test.js
creator-node/test/pollingTracks.test.js
creator-node/test/utils.test.js

Fix CN Tests in CI
Circle CI
NA

Fix CN tests

---

.circleci/jobs/gcp-cleanup.yml
.circleci/jobs/release-audius-docker-compose.yml
.circleci/jobs/release-governance.yml

Change cleanup to 3 days (weekend) and patch for automated commit to audius-docker-compose
Sends the slack notification after a governance proposal gets published too
NA
NA

Minor CI fixes

---

discovery-provider/plugins/notifications/src/__tests__/mappings/multipleMappings.test.ts
discovery-provider/plugins/notifications/src/__tests__/mappings/repost.test.ts
discovery-provider/plugins/notifications/src/__tests__/mappings/save.test.ts

Fix notification test type imports

---

.circleci/jobs/deploy.yml
.circleci/workflows/main.yml

Deploy notifications on ci

---

monitoring/healthz/src/Nats.tsx
monitoring/healthz/src/Router.tsx
monitoring/healthz/src/query.ts
monitoring/healthz/src/useServiceProviders.ts

nats healthz

---

discovery-provider/alembic/versions/5b4e01eaebab_remove_revert_constraints.py
discovery-provider/src/tasks/index_nethermind.py

Remove blockhash constraints and add playlist routes to revert logic
cc @sabrina-kiam 
To test / soak on sandbox discovery node

Remove block hash constraints

---

discovery-provider/src/app.py
discovery-provider/src/tasks/index_nethermind.py

Revert by blocknumber since that's indexed. Reverting by hash is very slow. 
Also remove POA indexing scheduling.

Revert by number not hash

---

identity-service/src/relay/txRelay.js

Taking changes from https://github.com/AudiusProject/audius-protocol/commits/release-v0.3.78 we made for ACDC migration.
We'll definitely clean this up soon but want to get this out for 3.80 release.
Running on prod.

ACDC migration relay reconcile with release-v0.3.78

---

discovery-provider/alembic/versions/e97a5ba523fc_fix_available_track.py
discovery-provider/integration_tests/queries/test_search.py
discovery-provider/integration_tests/queries/test_search_track_tags.py
discovery-provider/integration_tests/queries/test_search_user_tags.py
discovery-provider/integration_tests/tasks/test_get_feed_es.py

Verification was not working right and this double uploaded ended up in an odd state

Fix a single track availability post acdc

---

discovery-provider/Dockerfile

Increase DP health check timeout to fix tests
Circle CI
NA

Increase timeout to fix DP tests

---

discovery-provider/es-indexer/src/indexNames.ts
discovery-provider/es-indexer/src/indexers/TrackIndexer.ts

Reindex tracks without is_available

remove is_available true in base track selector

---

discovery-provider/src/app.py
discovery-provider/src/queries/get_health.py
discovery-provider/src/utils/get_all_other_nodes.py

Reverts AudiusProject/audius-protocol#4845

Revert "PLAT-575: include nodes in health query"

---

discovery-provider/src/tasks/entity_manager/entity_manager.py

Bypass notification EM transactions to unblock indexing.

Bypass notification transactions

---

discovery-provider/src/tasks/index.py
discovery-provider/src/tasks/index_nethermind.py

Revert notification seen

---

discovery-provider/alembic/versions/d43a7fd867f3_notification_seen_again.py

Create new revision for adding notification seen table - note that it's the same as file `21e5635c83a9_create_notification_seen.py` but need to be added bc of a bug in alembic versions in a previous deployment

Add notification seen table again

---

discovery-provider/alembic/versions/f008f6f2eee3_add_block_number_index_on_notification_.py

Add index on notification_seen table in discovery for reverts

Add index on notification seen

---

contracts/test/userReplicaSetManager.js
creator-node/.mocharc.js
creator-node/test/CNodeHealthManager.test.js
creator-node/test/StateMonitoringManager.test.js
creator-node/test/dbManager.test.js
creator-node/test/pollingTracks.test.js
creator-node/test/prometheus.test.js

Stop gap solution until content node is replaced. Seems to help.
Also remove flakey POA test that is not needed anymore.
CI tests

[INF-369] Add content node flakey test retries

---

libs/package-lock.json
libs/package.json

Bump SDK to v2.0.3-beta.0

---

discovery-provider/integration_tests/tasks/test_index_trending_underground_notification.py
discovery-provider/integration_tests/tasks/test_trending_playlist_notifications.py
discovery-provider/src/tasks/cache_trending_playlists.py

- Adds trending_playlist notification indexing
- Adds tests

[PLAT-791] Index trending_playlist notifications

---

.circleci/workflows/main.yml

This reverts commit 15deeab84e5f2c7307c863e5cc0d6d6f81724c96.

Revert "Shut off stage autodeploy (#4977)"

---

discovery-provider/nginx_conf/nginx.conf

https://www.raymondcamden.com/2015/07/16/safari-and-http-caching

[Flare-167] Add no-cache to discovery unclaimed ids

---

comms/natsd/self_connection_probe.go

remove early return from selfConnectionProbe to ensure no lingering server / client instances.

safer self connection test

---

.circleci/workflows/main.yml

Remove POA tests

---

.circleci/jobs/release-discord.yml

Current formatting yields 
```
curl: (3) nested brace in URL position 73:
```
Copied from code before CI changes to fix.
Ran on CI.

Fix discord ci curl

---

.circleci/@parameters.yml
.circleci/config.yml
.circleci/jobs/release-audius-sdk.yml
.circleci/workflows/release-audius-sdk.yml

Adds a trigger workflow for releasing the sdk through Circle CI
Pending
NA

Add flow to release sdk through circleci

---

.circleci/jobs/build-gcp-image.yml
.circleci/jobs/push-docker-image.yml
.circleci/jobs/test-audius-cmd.yml
.circleci/jobs/test.yml
dev-tools/audius-compose

Bump disk, cap cache
Circle CI
NA

Isolate CI fixes

---

creator-node/Dockerfile
discovery-provider/Dockerfile

Moves around stages to prevent cache misses. Changing nginx results in re-doing init-db currently.

Improve caching on dockerfiles

---

.circleci/config.yml

Fix sdk release

---

discovery-provider/es-indexer/src/conn.ts

Previously would delete all indices if any red index was present.  This was an attempt to reclaim disk space when disk was filling up.  But that problem has been addressed.
With this change will check several times that an index is red, and only delete red indexes.

Make es-indexer less aggressive about deleting red indexes

---

discovery-provider/integration_tests/queries/test_notifications/test_trending_playlist_notification.py
discovery-provider/integration_tests/queries/test_notifications/test_trending_underground_notification.py

Adds tests for trending-underground and trending-playlist queries

[PLAT-800] Add trending integration tests

---

monitoring/healthz/README.md

update readme with some extra details

add extra details to healthz readme

---

discovery-provider/src/api/v1/utils/extend_notification.py

Fix extend announcement

---

discovery-provider/es-indexer/src/indexNames.ts
discovery-provider/es-indexer/src/setup.ts

cherry-pick from release branch:
https://github.com/AudiusProject/audius-protocol/commits/release-v0.3.80

Es indexer enable triggers

---

discovery-provider/alembic/versions/02295bdb6bca_migrate_identity_last_seen_notification_.py

fix migration revision id

---

docker-compose.dev.yml

Not sure if this will work
Testing pending
NA

Wait for libs

---

discovery-provider/alembic/versions/9f5539bdd5bc_user_is_available.py

Fix down migration

---

discovery-provider/plugins/notifications/Dockerfile

Notification plugin docker image was failing to build due to npm install performing node-gyp and failing on some missing things like python. Adding these dependencies allow node-gyp to run on alpine
Can do `audius-compose up` locally

Fix notification plugin image build

---

libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts
libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
libs/src/sdk/services/DiscoveryNodeSelector/healthCheckTypes.ts

Snake case services list update

SDK: Snake case DN selector services key

---

libs/src/sdk/api/chats/ChatsApi.ts
libs/src/sdk/api/chats/clientTypes.ts

Adds three new chat endpoints (and unfurl, which in theory isn't a "chat" endpoint). Follows https://github.com/AudiusProject/audius-protocol/pull/5037
Tested manually by using a local libs build and running sdk console commands with three different users.

SDK: Add getBlockers(), getBlockees(), unfurl(), and getPermissions()

---

libs/src/sdk/api/chats/ChatsApi.ts

Missed one! This is for _unblocking_ a user

SDK: Chat unblocking

---

identity-service/package-lock.json
identity-service/package.json

Upgrade SDK to avoid trying to init POA contracts

Upgrade identity SDK 2.0.3-beta.4

---

discovery-provider/nginx_conf/nginx.conf

Note that if the plugin isn't running, this will not work. Probably ok?
@alecsavvy curious for your thoughts

Add notifs proxy pass

---

libs/src/sdk/api/chats/clientTypes.ts

Accidentally named this incorrectly

SDK: Type error on Chat Permits

---

discovery-provider/nginx_conf/nginx.conf

Currently /plugin/notification/health_check doesn't map to :6000/health_check

Fix /notifications proxy pass

---

discovery-provider/alembic/trigger_sql/ddl.sql

We don't need this table and it's taking up space.
Maybe I need to remove it from comms as well?
https://github.com/AudiusProject/audius-protocol/blob/main/dev-tools/startup/initdb/00_schema.sql#L3311
https://github.com/AudiusProject/audius-protocol/blob/bbdb2cb498064f8cf48e98128c7fa549614302c6/comms/discovery/db/schema.sql#L2920

Remove blocks_copy table

---

creator-node/src/contentAccess/helpers.ts

So that CN does not incorrectly think that signature is not from registered discovery node.

Add lowercase check

---

discovery-provider/default_config.ini
discovery-provider/src/tasks/index.py
discovery-provider/src/tasks/index_nethermind.py
libs/src/api/File.ts
libs/src/services/discoveryProvider/DiscoveryProvider.ts
libs/src/services/discoveryProvider/requests.ts

Corresponding client changes [here](https://github.com/AudiusProject/audius-client/pull/3181).
Also fix `enable_save_cid` config check... `default_config.ini` values are strings so the condition has been passing for enable_save_config="false" this whole time. Change the value to match reality.
Tested with local client pointed at stage.

Libs changes to read metadata from DNs

---

discovery-provider/src/queries/get_users.py
discovery-provider/src/tasks/update_aggregates.py

Filter null handles. This query affects both v1 and legacy `/users?` query routes.
Also fix misc lint errors

Fix user query filter

---

creator-node/src/config.js
creator-node/src/services/stateMachineManager/stateMachineConstants.ts

Hotfix to lower replica set updates per job (1 job per minute) from 500 to 50.

Lower replica set updates 10x

---

discovery-provider/src/tasks/index_nethermind.py

Revert playlist seen events to prevent indexing halts.
Will test on sandbox.

Revert playlist seen

---

mediorum/Makefile
mediorum/main.go

subset of tlds for which to start mediorum in prod

prod: only start on subset of hosts, tag docker image with git sha.

---

creator-node/src/blacklistManager.js

Skip propagating user delist on tracks

Skip track propagation

---

identity-service/src/logging.js

Add forwarded for header to all logs

Add forwarded for to identity logs

---

creator-node/package-lock.json
creator-node/package.json
creator-node/src/routes/healthCheck.js

To test on service provider machines and determine if suitable

Add request-ip package

---

discovery-provider/plugins/verified-uploads/src/handlers/tracks.js

dont fire a notif on unlisted tracks
deployed on stage and prod

plat 831: return early on unlisted tracks

---

identity-service/src/utils/antiAbuse.js

Relies on: https://github.com/AudiusProject/anti-abuse-oracle/pull/168

Respect AAO rule #17

---

discovery-provider/plugins/notifications/scripts/test-push-notification.ts

updating this to handle sending test pushs to android phones as well. also fixed some prettier errors
tested running on stage

update test push notification script to send android notifs

---

monitoring/vector/start.sh

Add disable logging flag
Cut new image and tested on stage dn1

Add flag to disable logging

---

.circleci/jobs/release-audius-docker-compose.yml

Curious for thoughts on this approach? It's a bit weird, but I think supports what we're trying to do here.
Ran on CI via ssh job

Update release-audius-docker-compose to respect `dev` and reconcile state

---

docker-compose.storagev2.yml
mediorum/main.go
nginx_ingress.conf

fixes mediorum hostname for compose setup

Mediorum hostname

---

.circleci/jobs/release-audius-docker-compose.yml

I suppose we should be using https now
Ran manually on CI

Fix clone command in ci

---

discovery-provider/plugins/verified-uploads/src/db.js

remove log

---

discovery-provider/alembic/trigger_sql/ddl.sql

Fix trigger_sql missing commit

---

identity-service/src/routes/instagram.js

Most of the diff is just removing and unnecessary `else`
Hopefully this mitigates some of the insta issues we see

Add retries to instagram profile fetch

---

monitoring/healthz/src/DMs.tsx

adds websocket connection duration.

Show how long ws was connected.

---

dev-tools/README.md

Include examples for running with elasticsearch container and without libs and solana.

Update README.md to include audius-compose examples

---

discovery-provider/README.md

Remove port from health_check curl, bc this breaks now.

Update discovery-provider README.md

---

identity-service/src/routes/trackListens.js

Change is already hot fixed on released branches. Doing this in case we still haven't resolved this in the future.

Temporarily enable client listen requests in identity

---

discovery-provider/es-indexer/src/conn.ts
discovery-provider/es-indexer/src/indexNames.ts
discovery-provider/es-indexer/src/indexers/PlaylistIndexer.ts
discovery-provider/es-indexer/src/types/docs.ts

Updates postgres to treat int64 as float.
Indexes `playlist.dominant_mood`

Es numbers

---

.circleci/jobs/deploy.yml
.circleci/workflows/main.yml

If you want to freeze staging builds, go to:
https://app.circleci.com/settings/organization/github/AudiusProject/contexts/fe29d5ad-f9a6-4e28-b067-526451b0f684?return-to=https%3A%2F%2Fapp.circleci.com%2Fprojects%2Fproject-dashboard%2Fgithub%2FAudiusProject%2F
Delete & set `FREEZE_BUILD` environment variable to `true`
If you want to unfreeze staging builds, set `FREEZE_BUILD` to `false`
Hard to test, will merge & test and fast-follow if any issues.
Config validation passes at least 🙃

Add CI env to freeze staging deploys

---

discovery-provider/src/api/v1/models/users.py
discovery-provider/src/api/v1/users.py
discovery-provider/src/queries/query_helpers.py
discovery-provider/src/queries/response_name_constants.py
discovery-provider/src/utils/helpers.py

Add a human-readable `total_audio_balance` field to the users non-full API response.
Tested on local dapp + client (injected some numbers to get correct formatting).

[PAY-1161] Add human-readable balance to users API

---

discovery-provider/integration_tests/challenges/test_trending_challenge.py
discovery-provider/src/queries/get_trending_playlists.py

Filter out albums from trending playlists. This should cover the old and new notification system. 
Updated integration test.

Filter out albums from trending playlists

---

discovery-provider/plugins/notifications/src/processNotifications/mappers/follow.ts

Fix follow push notif title copy

---

libs/package-lock.json
libs/package.json

CI publishing method got in a bad state, doing it locally here
- 2023-04-20 [8651801] Create userbanks lazily in Identity Auto-Attester (#5104) [Michael Piazza]
- 2023-04-19 [6c58010] Bump sdk to v2.0.3-beta.8 [audius-infra]

Bump sdk to v2.0.3-beta.11

---

identity-service/package-lock.json
identity-service/package.json
identity-service/src/utils/configureAttester.js

Accounts for FINAL_POA_BLOCK offset properly. Tested on stage. Depends on https://github.com/AudiusProject/audius-protocol/pull/5104

[PAY-1173] Improve identity attester & consume libs

---

discovery-provider/integration_tests/tasks/test_update_user_is_available.py
discovery-provider/src/tasks/update_user_is_available.py

Tiny fix: `session` wouldn't be defined when it's used at the bottom of the function, so we just make a new one.
Existing tests are sufficient.
N/A

Fix session not in scope in update_user_is_available

---

discovery-provider/plugins/notifications/src/__tests__/mappings/follow.test.ts
discovery-provider/plugins/notifications/src/__tests__/mappings/multipleMappings.test.ts
discovery-provider/plugins/notifications/src/processNotifications/mappers/message.ts

Fix follow copy test

---

monitoring/healthz/src/DMs.tsx
monitoring/healthz/src/Mediorum.tsx
monitoring/healthz/src/Router.tsx
monitoring/healthz/src/main.tsx
monitoring/healthz/src/misc.tsx

kind of a placeholder for now... but it's deployed

add mediorum panel to healthz

---

libs/src/sdk/api/chats/ChatsApi.ts
libs/src/sdk/api/chats/clientTypes.ts

Changes types to match https://github.com/AudiusProject/audius-protocol/pull/5101

SDK: Update types in SDK for chats/permissions

---

libs/src/services/discoveryProvider/DiscoveryProvider.ts

Unlike Axios, the FetchAPI doesn't stringify objects automatically

SDK: Stringify fetch POST bodies in V2-land

---

discovery-provider/plugins/notifications/src/__tests__/emailRender.test.ts
discovery-provider/plugins/notifications/src/email/notifications/renderEmail.ts

Dupe live emails were being sent because the subject was rendered incorrectly as weekly.

Dedupe live emails 

---

discovery-provider/src/api/v1/users.py
discovery-provider/src/queries/get_related_artists.py

Related artists endpoint accepts offset but doesn't respect it in the query.
Change is to pass it down and apply it on query

[C-2526] pass offset through to get_related_artists

---

discovery-provider/alembic/trigger_sql/ddl.sql
discovery-provider/integration_tests/tasks/entity_manager/test_delegate_entity_manager.py
discovery-provider/integration_tests/utils.py
discovery-provider/src/models/delegates/app_delegate.py
discovery-provider/src/models/delegates/delegate.py
discovery-provider/src/tasks/entity_manager/app_delegate.py
discovery-provider/src/tasks/entity_manager/delegate.py
discovery-provider/src/tasks/entity_manager/entity_manager.py
discovery-provider/src/tasks/entity_manager/utils.py

Implementation deets:
https://www.notion.so/audiusproject/Write-SDK-Authority-Delegation-7330ea98374a48ebaefb2f7a9476389e?pvs=4#79a2dcb64010467593dee72a5341a0d4
Libs changes reference: https://github.com/AudiusProject/audius-protocol/pull/5150
Tested via integration tests

Add delegates table, create delegate indexing C-2292

---

discovery-provider/alembic/trigger_sql/ddl.sql
discovery-provider/es-indexer/src/indexNames.ts
discovery-provider/es-indexer/src/indexers/TrackIndexer.ts
discovery-provider/es-indexer/src/indexers/UserIndexer.ts
discovery-provider/integration_tests/queries/test_get_tracks.py
discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
discovery-provider/integration_tests/utils.py
discovery-provider/src/api/v1/users.py
discovery-provider/src/models/tracks/track.py
discovery-provider/src/models/users/user.py
discovery-provider/src/queries/get_tracks.py
discovery-provider/src/schemas/track_schema.json
discovery-provider/src/tasks/entity_manager/entity_manager.py
discovery-provider/src/tasks/entity_manager/track.py
discovery-provider/src/tasks/entity_manager/user.py
libs/src/api/Track.ts
libs/src/api/Users.ts
libs/src/services/schemaValidator/schemas/trackSchema.json
libs/src/utils/types.ts

https://www.notion.so/AI-0bfb50f248c64f54ad44d9fa852b2323
Add AI attribution fields.
* Tracks with attribution to a single user ID
* Users with AI attribution enabled.
Added integration tests.

Add AI attribution 

---

discovery-provider/src/api/v1/models/tracks.py
discovery-provider/src/api/v1/models/users.py

Need these fields to expose in responses.

Add AI attribution fields to API

---

.circleci/workflows/main.yml
dev-tools/audius-compose

Disable auto deploy to stage

---

dev-tools/startup/discovery-provider.sh
discovery-provider/scripts/start.sh

Remove export that turns on es indexer

Remove auto start ES

---

discovery-provider/integration_tests/tasks/test_index_helper.py

Fix broken test

---

discovery-provider/alembic/trigger_sql/ddl.sql

Add tracks_ai_attribution index

---

discovery-provider/src/api/v1/models/tracks.py

Make tracks full route allow returning null ai attribution

Allow null ai attribution in tracks full route

---

comms/discovery/rpcz/websocket.go

Keeps all RPCs for all users for the last 10 seconds.  When a user websocket connection opens, sends any events for that user from the last 10s.
This could be made more GC efficient in the future, but this should be good for testing.

Resend recent websocket messages on reconnect.

---

discovery-provider/src/app.py

Increase update aggregate frequency

---

discovery-provider/src/api/v1/tracks.py
discovery-provider/src/api/v1/users.py

We inadvertently had many endpoints generating documentation that we don't want to include in the API. 
Breakdown here: https://docs.google.com/spreadsheets/d/1D-tGF3Cx0r9NTOVl5pwtD2z7xr5b4EQPFyIedRF5xtY/edit#gid=0

[PAY-1206] Remove documentation from DN endpoints not included in API

---

discovery-provider/plugins/verified-uploads/README.md
discovery-provider/plugins/verified-uploads/src/handlers/test.js
discovery-provider/plugins/verified-uploads/src/handlers/tracks.js

if an old upload comes through the verified uploads bot will now ignore it if it's a week late
tests.js

add new guard and test for old uploads

---

discovery-provider/src/api/v1/users.py

We mistakenly decided to remove docs on this route, which was already part of the exposed API. Adding it back in in case clients are depending on it.

Add back doc for UserIdByAssociatedWallet endpoint

---

discovery-provider/alembic/trigger_sql/ddl.sql
discovery-provider/src/api/v1/tracks.py

Strip newline for streaming
Will test on sandbox

Strip cid newline for stream

---

libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts

Doing the retry is causing there to be two endpoints in the request URL
To be tested!

SDK: Prevent double endpoints

---

discovery-provider/alembic/trigger_sql/ddl.sql

Remove whitespace in cid migration

---

.circleci/workflows/main.yml
dev-tools/audius-cmd

Doesn't fix the tests yet.
audius-cmd doesn't crash now

Get audius-cmd to run again

---

discovery-provider/alembic/trigger_sql/ddl.sql
discovery-provider/integration_tests/tasks/entity_manager/test_delegation_entity_manager.py
discovery-provider/integration_tests/utils.py
discovery-provider/src/models/delegates/app_delegate.py
discovery-provider/src/models/delegates/delegation.py
discovery-provider/src/tasks/entity_manager/delegation.py
discovery-provider/src/tasks/entity_manager/entity_manager.py
discovery-provider/src/tasks/entity_manager/utils.py

https://www.notion.so/audiusproject/OAuth-on-Simple-Data-Layer-EVM-b445eb5610ea4c8db4abe713a1766fa0?pvs=4

Add `delegation` table, create delegation C-2293

---

libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts
libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.test.ts

SDK: Update tests to match what context comes back with

---

discovery-provider/integration_tests/tasks/entity_manager/test_delegation_entity_manager.py
discovery-provider/src/tasks/entity_manager/delegation.py
discovery-provider/src/tasks/entity_manager/entity_manager.py

Allow revoking and reactivating delegations
This would be when a user wants a revoke an oauth app's access to their account for example

Add revoke delegation functionality to EM (Discovery) C-2562

---

discovery-provider/src/api/v1/helpers.py

Hot fix duration key error

---

libs/src/sdk/services/EntityManager/EntityManager.ts
libs/src/sdk/utils/web3.ts

This fixes an issue when EntityManager is constructed in a browser env. Might be better to pass in web3 in the future

Use window web3 in sdk when available

---

.circleci/jobs/test-audius-cmd.yml
.circleci/workflows/main.yml
dev-tools/commands/src/create-user.mjs
dev-tools/commands/src/upload-track.mjs
dev-tools/commands/test/create-user.bats
dev-tools/commands/test/upload-track.bats
libs/src/api/Users.ts
libs/src/eth-contracts/ABIs/Wormhole.json

Fix audius-cmd tests.
* Use write metadata to chain (that was broken, no sense in looking back).
* Fix ai attribution
* Bump timeouts
```
audius-compose up -w
audius-cmd test
```

[PLAT-684] Fix audius-cmd tests

---

dev-tools/commands/test/create-user.bats
dev-tools/commands/test/upload-track.bats

Use `npm run` instead of `audius-cmd`
Unsure why this is necessary atm

Use npm for tests

---

.circleci/jobs/test-audius-cmd.yml
dev-tools/commands/src/create-user.mjs
dev-tools/commands/src/utils.mjs

Test to fix

---

discovery-provider/src/api/v1/users.py

As per discussions, leaving these out of the API for now.

Undocument album and playlist favorites routes

---

discovery-provider/src/api/v1/users.py

Removes doc generation for `/<string:id>/supporters/<string:supporter_user_id>` in DN

Remove documentation for supporter user route

---

libs/src/sdk/api/chats/ChatsApi.ts

Expose unread messages count endpoint in sdk.
Tested with local web stage + linked sdk

[PAY-1238] Chats sdk unread messages count

---

monitoring/healthz/package-lock.json
monitoring/healthz/src/DMMatrix.tsx
monitoring/healthz/src/Router.tsx

healthz DM mutual world view matrix

---

mediorum/go.mod
mediorum/go.sum
mediorum/server/serve_blob.go
mediorum/server/signature/signature.go
mediorum/server/signature/signature_test.go

Enforces registered signer for cidstream endpoint.
Need to sort JSON keys and keccack256 the JSON before doing the "personal sign" recovery steps.

sig recovery works

---

discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
discovery-provider/integration_tests/utils.py
discovery-provider/src/tasks/entity_manager/delegation.py
discovery-provider/src/tasks/entity_manager/entity_manager.py
discovery-provider/src/tasks/entity_manager/track.py

Allow signer for track actions to be a valid delegation address
Should be straightforward to do the rest of the entities later

Allow delegated track writes in EM C-2294

---

discovery-provider/integration_tests/queries/test_search.py
discovery-provider/integration_tests/queries/test_search_track_tags.py
discovery-provider/integration_tests/queries/test_search_user_tags.py
discovery-provider/integration_tests/tasks/test_get_feed_es.py
discovery-provider/src/queries/get_health.py
discovery-provider/src/utils/web3_provider.py

Reverts AudiusProject/audius-protocol#5243
lol

Revert "Revert "PLAT-955: default to local RPC and fallback to gateway""

---

identity-service/src/relay/txRelay.js

improve logging on stage identity

---

.circleci/config.yml
.circleci/src/@continue_config.yml
.circleci/src/jobs/release-audius-sdk.yml
.circleci/src/workflows/sdk.yml
contracts/test/userReplicaSetManager.js
dev-tools/compose/docker-compose.test.yml
libs/package.json

Now it really can be like your dreams ✨ 👍 
* Fix path filtering for sdk deployment. We only want to do this when `main` and `main~1` have a diff in libs/*
* Add `audius-compose` harness for testing `audius-sdk` and use it in CI, appropriately blocking steps
Pretend to be `main`

Improve new CI workflows

---

mediorum/ddl/ddl.go
mediorum/server/cid_log_client.go
mediorum/server/cid_log_server.go
mediorum/server/cid_log_test.go
mediorum/server/health.go
mediorum/server/server.go

Limits CID beam to 100k rows.  Trying to do whole table with 30M rows would exceed 1h nginx timeout.
Also adds some code to skip running ddl.

Cid beam limit

---

.circleci/config.yml

Meant to do in prior PR: https://github.com/AudiusProject/audius-protocol/pull/5258

No release on main

---

comms/discovery/rpcz/validator.go

Validate not a <blocker, blockee> pair and check permissions if necessary on chat react.
make test

Validate blocks and permissions on chat react

---

creator-node/src/components/replicaSet/replicaSetController.js

We have similar. code elsewhere https://github.com/AudiusProject/audius-protocol/blob/7ce37469674054e7512c8d8c42ac53cea737c54d/creator-node/src/components/replicaSet/replicaSetController.js#L95

[Flare-178] Add recurring sync queue null check

---

creator-node/src/routes/tracks.js
dev-tools/commands/src/upload-track.mjs
discovery-provider/src/api/v1/tracks.py
discovery-provider/src/queries/get_tracks.py

Add flag to skip play count if necessary.
Passes through from discovery => content
1. audius-compose up
2. audius-cmd create-user
3. audius-cmd upload-track --handle=^
4. confirm no param in content node request
5. manually hit ?skip_play_count=true
6. confirm param is present in content node request
Request logs in axiom should suffice

Add skip_play_count flag

---

discovery-provider/alembic/trigger_sql/ddl.sql

Fixes missing user during ACDC migration.
Data recovered from transactions table & decoded ABIs
Ran on discovery 4 prod

Add skreamizm

---

discovery-provider/plugins/notifications/src/email/notifications/sendEmail.ts

Switch bcc back to audius test email instead of personal email
will test on stage

[PLAT-943] rm personal bcc on email notifications

---

discovery-provider/alembic/trigger_sql/ddl.sql

Fix migration idempotency

---

comms/discovery/discovery_main.go
comms/discovery/rpcz/apply.go
comms/discovery/rpcz/peer_client.go
comms/discovery/server/server.go

marks self unhealthy if apply fails or websocket self connection test fails

Comms health

---

discovery-provider/src/utils/eth_contracts_helpers.py

Remove this /status check to unblock indexing of unavailable tracks.

Remove status check when fetching CNs

---

discovery-provider/alembic/trigger_sql/ddl.sql

check if the skreamizm row exists to avoid duplicate is_current.
tested on sandbox. ran migration repeatedly.

Only apply skreamizm fix once

---

discovery-provider/alembic/trigger_sql/ddl.sql

Only 1 is_current true skreamizm. 
will test on sandbox.

Invalidate old skreamizm records

---

discovery-provider/nginx_conf/nginx.conf
discovery-provider/nginx_conf/port.lua

This can then be used in the audius-docker-compose tooling.
Soft launched on stage discovery 4

[PLAT-951] Add port exposure check

---

discovery-provider/src/utils/web3_provider.py

Reuse web3 instances to avoid recreating every time.

Reuse web3 instance

---

.github/pull_request_template.md

Simple good.
This PR description.

Simple PR template

---

eth-contracts/.eslintrc.js
eth-contracts/migrations/10_wormhole_client_migration.js
eth-contracts/migrations/11_eth_rewards_manager_migration.js
eth-contracts/migrations/12_trusted_notifier_manager_migration.js
eth-contracts/migrations/13_delegate_manager_v2_migration.js
eth-contracts/migrations/1_initial_migration.js
eth-contracts/migrations/2_registry_migration.js
eth-contracts/migrations/3_governance_migration.js
eth-contracts/migrations/4_token_migration.js
eth-contracts/migrations/5_staking_migration.js
eth-contracts/migrations/6_claims_manager_migration.js
eth-contracts/migrations/7_versioning_service_migration.js
eth-contracts/migrations/8_delegate_manager_migration.js
eth-contracts/package.json
eth-contracts/scripts/get-address.js
eth-contracts/scripts/migrate-contracts.js
eth-contracts/scripts/release-governance.js
eth-contracts/scripts/setup-dev.js
eth-contracts/test/claimsManager.test.js
eth-contracts/test/delegateManager.test.js
eth-contracts/test/delegateManagerV2.test.js
eth-contracts/test/random/random.test.js
eth-contracts/test/registry.test.js
eth-contracts/test/serviceProvider.test.js
eth-contracts/test/trustedNotifierManager.test.js
eth-contracts/test/upgradeability.test.js
eth-contracts/utils/lib.js
eth-contracts/utils/signatures.js

Does lint and add `lint:fix` cmd.
CI better pass!

Lint eth contracts js

---

discovery-provider/nginx_conf/nginx.conf

Fix health_check CORS

---

libs/src/sdk/api/developer-apps/DeveloperAppsAPI.ts
libs/src/sdk/api/developer-apps/DeveloperAppsApi.ts
libs/src/sdk/api/developer-apps/constants.ts
libs/src/sdk/api/developer-apps/types.ts
libs/src/sdk/api/grants/GrantsAPI.ts
libs/src/sdk/api/grants/constants.ts
libs/src/sdk/api/grants/types.ts
libs/src/sdk/index.ts
libs/src/sdk/sdk.ts
libs/src/sdk/services/EntityManager/types.ts

Add Developer App (fka app delegate) API and Grants (fka delegations) API
Tested in client PR: https://github.com/AudiusProject/audius-client/pull/3396
Follow up:
-Have SDK accept EntityManager service on init, add staging/prod defaults to bootstrap config

SDK - add developer apps and grants APIs for corresponding EM actions C-2290 C-2291

---

libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts
libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
libs/src/sdk/services/DiscoveryNodeSelector/healthCheckTypes.ts
libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.test.ts
libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.ts

Changes DN selection to only select DNs with healthy comms containers
Tested via unittests

[PLAT-982] SDK: Select DNs with healthy comms

---

comms/discovery/server/server.go

This should allow us to "reset" the matrix to a given point in time.

[PLAT-1019] Add since to comms debug cursors

---

mediorum/ddl/cid_lookup.sql

Uses `old` record only during delete operation

Check tg_op for segments in Files trigger

---

.circleci/src/workflows/discovery.yml

Shut off stage auto deploy

---

monitoring/healthz/src/DiscoveryHealth.tsx
package-lock.json

Move up to the front since it's the most important column. Makes it easier to parse.

Move block diff in healthz

---

monitoring/vector/vector.toml

Add chain logs to axiom
Running on stage DN4

Pipe chain logs

---

.circleci/src/workflows/discovery.yml

This reverts commit 157958710813102df3adbd875eaa311555f27c22.

Revert "Shut off stage auto deploy (#5333)"

---

libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts
libs/src/sdk/services/DiscoveryNodeSelector/healthCheckTypes.ts
libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.test.ts
libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.ts

the `comms` field is at the root, not nested in `data`

SDK: Check comms at root

---

creator-node/nginx_conf/nginx.conf
discovery-provider/nginx_conf/nginx.conf

https://github.com/AudiusProject/audius-docker-compose/pull/295
Ran on sandbox, see:
http://34.72.186.34:5000/prometheus/docker

[PLAT-917] Add docker exporter endpoints

---

discovery-provider/src/tasks/cache_current_nodes.py

Includes delegateOwnerWallet in content-node healthcheck, which is needed for content-node-selector to work correctly

Include delegateOwnerWallet in content node health_check

---

discovery-provider/src/api/v1/utils/extend_notification.py

we introduced a new format without handling previous formats that didn't have `playlist_owner_id`. this allows both types
testing on stage

Update add track to playlist notification to handle previous format

---

.circleci/src/workflows/creator.yml
.circleci/src/workflows/discovery.yml

Flag not working as expected. Taking this insurance policy.

Halt stage deploy manually

---

.circleci/src/workflows/creator.yml
.circleci/src/workflows/discovery.yml

This reverts commit c7d1ed7a6fddd0c7cfed5ca03c70cf8f277de921.

Revert "Halt stage deploy manually (#5362)"

---

libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts
libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
libs/src/sdk/services/DiscoveryNodeSelector/healthCheckTypes.ts
libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.test.ts
libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.ts

Revert comms health checks

---

mediorum/server/cid_log_client.go
mediorum/server/server.go

do one at a time instead of all in parallel to reduce DB contention
deploying to staging...

mediorum cid beam does one peer at a time.

---

discovery-provider/src/api/v1/api.py
discovery-provider/src/api/v1/developer_apps.py
discovery-provider/src/api/v1/helpers.py
discovery-provider/src/api/v1/models/developer_apps.py
discovery-provider/src/api/v1/users.py
discovery-provider/src/queries/get_developer_apps.py

Endpoints for:
-Getting developer apps by owner user id
-Getting grants/authorized apps by user id (
-Getting developer apps by API Key
Tested by curling endpoints

Add Discovery endpoints for developer apps + grants [C-2623]

---

comms/discovery/rpcz/chat.go

Mark chats as read when deleted
Haven't been able to test - @michellebrier can you confirm these changes?

[PAY-1395] DMs: Mark chats as read on delete

---

monitoring/healthz/src/DiscoveryHealth.tsx

It's crucial for discovery nodes to be able to determine the requesting IP of the end user because that IP is then forwarded along to stream content from content nodes and uniquely determine plays. We can't shut off audius.co POST-ing to identity/listen until we can ensure all of audius.co connected discovery nodes have IP tracking properly set up.
local healthz

[PLAT-1040] Add "Your IP" column

---

discovery-provider/ddl/functions/handle_play.sql
discovery-provider/ddl/functions/handle_repost.sql
discovery-provider/ddl/functions/handle_save.sql
discovery-provider/integration_tests/tasks/test_index_listen_count_milestone.py

Add a few additional milestones 
CI

Normalize milestone numbers

---

mediorum/server/serve_blob.go
mediorum/server/serve_legacy.go

Mediorum logs when cid blacklisted, redirected, or served properly

---

discovery-provider/nginx_conf/nginx.conf

Add /chain in addition to /nethermind for acdc endpoints

[PLAT-659] Add /chain

---

discovery-provider/Dockerfile
discovery-provider/nginx_conf/nginx.conf
discovery-provider/nginx_conf/utils.lua

ordering is inconsistent since
https://github.com/AudiusProject/audius-protocol/pull/5313
Note this just sorts the top level. We could extend it to sort otherwise, but now the ordering is at least consistent via using dkjson which lets you do key ordering
Sandbox:
http://34.72.186.34:5000/health_check
Not sure about this comms "error" spam, but perhaps because this node is unregistered.

[PLAT-1026] Sort health check

---

libs/src/services/web3Manager/Web3Manager.ts

Some things have changed since this last worked
See client PR!
https://github.com/AudiusProject/audius-client/pull/3563

[PLAT-659] Fix metamask sign in

---

discovery-provider/src/api/v1/developer_apps.py
discovery-provider/src/api/v1/users.py

... so we can generate API from that

Add developer app endpoints to swagger docs

---

comms/discovery/rpcz/apply.go

DMs: Fix health error output

---

libs/src/sdk/api/tracks/TracksApi.test.ts
libs/src/sdk/api/tracks/TracksApi.ts
libs/src/sdk/api/tracks/types.ts
libs/src/sdk/services/EntityManager/EntityManager.ts
libs/src/sdk/services/EntityManager/types.ts
sdk-consumer/index.ts

* Add `writeOptions` param to sdk writes
* Add `deleteTrack` method
Tested by uploading and deleting tracks via the sdk

[C-2727] Add deleteTrack to sdk

---

discovery-provider/plugins/notifications/src/email/notifications/renderEmail.ts
discovery-provider/plugins/notifications/src/sns.ts
discovery-provider/plugins/notifications/src/tasks/appNotifications.ts
discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
discovery-provider/plugins/notifications/src/web.ts

- log problematic awsARN on push failure
- lint fixes 

Better notifications plugin logs

---

discovery-provider/src/tasks/entity_manager/entity_manager.py

fast follow 
https://github.com/AudiusProject/audius-protocol/pull/5412
forgot a line

Fix params reference before assignment follow on

---

monitoring/healthz/src/DiscoveryHealth.tsx

This is false because the addresses are cased differently.
Ran locally and deployed change.

Fix is signer in healthz

---

comms/discovery/config/config.go
comms/discovery/rpcz/apply.go
comms/discovery/rpcz/peer_client.go
comms/discovery/server/server.go
monitoring/healthz/src/DMMatrix.tsx
monitoring/healthz/src/DiscoveryHealth.tsx
monitoring/healthz/src/index.css
monitoring/healthz/src/query.ts
monitoring/healthz/src/useServiceProviders.ts

Reduce log noise... add some healthz display.

Improve DM logging

---

discovery-provider/nginx_conf/nginx.conf

I had tested this on a sandbox and had the ? there, but did not do this properly in the branch. Apologies.
Going to test exactly this SHA on a sandbox once it builds

Add question mark

---

libs/src/sdk/api/chats/ChatsApi.ts
libs/src/sdk/api/chats/clientTypes.ts

CurrentUserId should be optional for listen()

---

discovery-provider/integration_tests/test_celery.py
discovery-provider/src/tasks/index_eth.py

Add a test to bring up celery. Shocked this didn't already exist. And it also caught another bug.
Previous PR was able to pass CI and commit a celery config for a file that didn't exist
https://github.com/AudiusProject/audius-protocol/pull/5426
Confirmed that this test fails before the fix and passes with the fix.

Add celery test

---

discovery-provider/ddl/migrations/0003_truncate_delist_status_tables.sql
discovery-provider/src/queries/get_health.py
discovery-provider/src/tasks/update_delist_statuses.py
discovery-provider/src/utils/prometheus_metric.py
discovery-provider/src/utils/redis_constants.py

Seeing occasional inconsistencies in is_available in users/tracks and the delist statuses pulled from TN on prod but not on stage. The actual polling is fine, as can be observed in the DN user_delist_statuses and track_delist_statuses tables, but there's something wrong with the subsequent users/tracks table update logic.
The task updates the users/tracks in batches of 1000. There isn't enough data in stage for this batching to apply in stage but there is in prod, so this might be an issue with the update batching. Removed the batch-within-a-batch logic -- just request 500 records from TN at a time.
This bug should not be affecting delists in prod from this point forward unless there are  >1000 new delists at a time, just delists from the initial backfill when first polling and populating …

Fix DN polling of TN

---

identity-service/src/config.js
identity-service/src/routes/healthCheck.js
identity-service/src/routes/relay.js

Removes remaining unused flags
CI

Remove remaining entity mgr flags

---

libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts
libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
libs/src/sdk/services/DiscoveryNodeSelector/healthCheckTypes.ts
libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.test.ts
libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.ts

This reverts commit 10d49984266d4cf75c6e0e807860f4f0769e8c16.
Relands Comms health check

Revert "Revert comms health checks (#5370)"

---

discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts
discovery-provider/plugins/notifications/src/processNotifications/mappers/messageReaction.ts

Include actual emojis in message reaction push notifs

---

discovery-provider/src/app.py
discovery-provider/src/tasks/index_nethermind.py

Make 1033 faster

---

libs/package-lock.json
libs/src/sdk/api/developer-apps/DeveloperAppsApi.ts
libs/src/sdk/api/developer-apps/constants.ts
libs/src/sdk/api/developer-apps/types.ts
libs/src/sdk/api/grants/GrantsApi.ts
libs/src/sdk/api/grants/constants.ts
libs/src/sdk/api/grants/types.ts
libs/src/sdk/services/Auth/AppAuth.ts
libs/src/sdk/services/EntityManager/constants.ts
libs/src/sdk/utils/file.ts

-Create Developer App fixes:
-> Send app_signature instead of address
-> Send description to EM
-> Return/use app wallet address as api key instead of app wallet pub key
-Use Zod for Grants and DeveloperApps apis

[SDK] Fix Create Dev App to match EM changes; use Zod for validation - Grants/Developer Apps

---

mediorum/ethcontracts/compute_address.go
mediorum/httputil/httputil.go
mediorum/main.go
mediorum/server/serve_health.go
mediorum/server/server.go
mediorum/server/server_basic_auth.go

Like https://github.com/AudiusProject/audius-protocol/pull/5446 for mediorum.
* reads private key, computes wallet address
* prints warning if `delegateOwnerWallet` doesn't match
* only starts peer clients if wallet is registered

compute wallet address from private key

---

dev-tools/commands/src/edit-track.mjs
dev-tools/commands/src/index.mjs

v2 edit track
`audius-cmd edit-track "1836358537" -f "michellebrier" -a "tag1" -d "new description" -m "new mood" -g "new genre" -l "new license" -t "new title"`

audius-cmd v2 edit track

---

discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/app.ts
discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/main.ts
discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/queries.ts
discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/server.ts
discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/slack.ts
discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/trending.ts
discovery-provider/plugins/pedalboard/packages/basekit/src/app.ts

adds tweet formatting to trending challenge bot
see #trending-chalenge-reward-notifications channel

PLAT-992: compose friday tweet

---

discovery-provider/src/queries/get_health.py
discovery-provider/src/queries/get_trusted_notifier_discrepancies.py
discovery-provider/src/queries/health_check.py

Move to own endpoint. Will update uptime monitor robots on stage and prod as this change is deployed to each.
Also increase query rate to every 5 mins if there is a discrepancy so that it'll stop erroring / paging soon after the issue is reolved.
Insert discrepancies in db, verify status code and JSON updates appropriately in expected time frames.

DN TN discrepancies endpoint

---

discovery-provider/ddl/functions/handle_challenge_disbursements.sql
discovery-provider/ddl/functions/handle_follow.sql
discovery-provider/ddl/functions/handle_play.sql
discovery-provider/ddl/functions/handle_playlist.sql
discovery-provider/ddl/functions/handle_reaction.sql
discovery-provider/ddl/functions/handle_repost.sql
discovery-provider/ddl/functions/handle_save.sql
discovery-provider/ddl/functions/handle_supporter_rank_ups.sql
discovery-provider/ddl/functions/handle_track.sql
discovery-provider/ddl/functions/handle_user.sql
discovery-provider/ddl/functions/handle_user_balance_changes.sql
discovery-provider/ddl/functions/handle_user_tip.sql

Thoughts on this approach? We will get logs in axiom, etc.
Would be down to change this to INFO/NOTICE/WARNING/ERROR if anyone has preference.
* Make sure that triggers run
* Added some fake exceptions and made sure the notices get logged

[PLAT-932] Add exception logs to triggers

---

mediorum/ddl/ddl.go
mediorum/go.mod
mediorum/go.sum
mediorum/main.go
mediorum/server/repair.go
mediorum/server/serve_health.go
mediorum/server/serve_health_test.go

* fixes panic in `health_check`
* adds source info to slog logs
* skips + deletes old blobs (non-`ba` prefix)

Mediorum fix health panic

---

dev-tools/commands/src/create-user.mjs
dev-tools/commands/src/follow.mjs
dev-tools/commands/src/unfollow.mjs

`audius-cmd follow "551247127" -f "michellebrier"`
`audius-cmd unfollow "551247127" -f "michellebrier"`

audius-cmd follow and unfollow

---

comms/discovery/rpcz/rate_limit_test.go
comms/discovery/rpcz/validator.go
discovery-provider/ddl/migrations/0004_chat_message_index.sql

"burst" rate limits will block messages if you exceed:
* 10 per second for 1s
* 7 per second for 10s
* 5 per second for 60s

burst rate limit for chat messages

---

discovery-provider/src/tasks/entity_manager/entities/user.py
libs/src/api/Account.ts
libs/src/api/Users.ts

Reverting because service changes aren't out yet https://github.com/AudiusProject/audius-protocol/pull/5408

Revert single tx signup in libs

---

libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.test.ts

Got a little trigger happy in #5472 

SDK: Temporarily disable comms api response test

---

discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py

Fixing this conflict in a failing test.

Fix social feature test

---

discovery-provider/plugins/pedalboard/README.md
discovery-provider/plugins/pedalboard/apps/sla-auditor/.eslintrc.js
discovery-provider/plugins/pedalboard/apps/sla-auditor/package.json
discovery-provider/plugins/pedalboard/apps/sla-auditor/src/index.ts
discovery-provider/plugins/pedalboard/apps/sla-auditor/tsconfig.json
discovery-provider/plugins/pedalboard/docker-compose.yml
discovery-provider/plugins/pedalboard/package-lock.json

[PLAT-1078] Add sla-auditor plugin

---

discovery-provider/src/tasks/update_delist_statuses.py

for ease of use when querying axiom

Bump update_delist_statuses log level on error when updating DN db

---

discovery-provider/integration_tests/queries/test_get_attestation.py
discovery-provider/src/queries/confirm_indexing_transaction_error.py
discovery-provider/src/queries/get_attestation.py
discovery-provider/src/queries/get_redirect_weights.py
discovery-provider/src/tasks/cache_current_nodes.py
discovery-provider/src/tasks/index_metrics.py
discovery-provider/src/tasks/update_clique_signers.py
discovery-provider/src/utils/get_all_other_nodes.py

Broken because the cache key doesn't have wallets, just nodes. See https://github.com/AudiusProject/audius-protocol/blob/5802d9adc8a36ee1e993a2d2ad100f353aa5b80c/discovery-provider/src/tasks/cache_current_nodes.py#L35
Will consider migration to backfill data (sum it across other nodes) after this goes out.
Will test thoroughly on staging via logs. No great tests for this atm.

Fix cached node retrieval

---

discovery-provider/ddl/migrations/0005_backfill_unsynced_metrics.sql

Aggregate manually across nodes and backfill data that is incorrect from
https://github.com/AudiusProject/audius-protocol/pull/5486
Migration runs successfully locally, tested migration manually on sandbox

Backfill missing metrics

---

creator-node/package-lock.json
creator-node/package.json

Almost don't even need this codebase anymore...

Upgrade sdk in js content node

---

mediorum/server/repair.go
mediorum/server/repair_test.go

On `main` currently, if a mediorum host is down for extended period (over 5 minutes) the "healthy" rendezvous function will handle this correctly because the unhealthy host will be omitted from rendezvous and the #4 server will become #3 and go and pull the blob.
But when switching from push based to pull based repair, one thing that's not handled now is replicating under-replicated blobs when a top N host might be up but have a full disk or some other issue preventing it from getting a blob it should have.
This adds a step to "cleanup mode" where nodes deeper in the rendezvous order will check to see if a blob is under-replicated and pull it.

repair under-replicated blobs in cleanup mode

---

mediorum/server/repair.go
mediorum/server/repair_test.go

fix bad merge

---

discovery-provider/src/tasks/index_nethermind.py

Add reverts for these things to prevent halting. 

Add reverts for grant and dev apps

---

discovery-provider/src/tasks/entity_manager/entities/track.py
discovery-provider/src/tasks/entity_manager/entity_manager.py
discovery-provider/src/tasks/entity_manager/utils.py
discovery-provider/src/utils/structured_logger.py

Adding structured logs for entity manager events and apps. 
More to do, we should remove utils_logger and only use structured logs in entity manager.
Tested on sandbox. Built dashboards.

EntityManager event and app structured logs

---

identity-service/src/rateLimiter.js

Response was hanging because of this. Idk how this happened haha.

Send response when EM rate limited

---

discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/app.ts
discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/trending.ts

minor adjustments to trending plugin

---

discovery-provider/src/tasks/entity_manager/entities/developer_app.py
discovery-provider/src/tasks/entity_manager/entities/social_features.py

Resolve conflict from https://github.com/AudiusProject/audius-protocol/pull/5480
Fix tests

Fix discovery test conflict with validation error

---

libs/src/AudiusLibs.ts
libs/src/NativeAudiusLibs.ts
libs/src/WebAudiusLibs.ts
libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.test.ts
libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.ts
libs/src/sdk/services/StorageNodeSelector/types.ts

Improves getNodes by removing async requirement, making it faster on web and mobile side

[C-2808] Make getNodes not async

---

monitoring/healthz/package-lock.json
monitoring/healthz/src/DMs.tsx
monitoring/healthz/src/Mediorum.tsx

update DM health panel

---

discovery-provider/src/tasks/index_nethermind.py

Fix linear indexer on local state.
#5400 broke indexer after I had done full testing because of the additional check 
```
if (
next_block
and web3.toHex(next_block.parentHash) != latest_database_block.blockhash
):
block_on_chain = False
```
This  was done to ensure that when the parent hashes do not line up correctly, we revert until they do.
`audius-compose up` indexer works

Fix linear indexer for local state

---

libs/src/sdk/api/chats/ChatsApi.ts

[PAY-1554] Change to less scary error message on decryption failure

---

creator-node/.version.json
discovery-provider/.version.json

This reverts commit c01d86e92ced67a68c9db5b75755eb3535208e54.
Cannot be merged yet. Old libs service selection checks major & minor version for match
https://github.com/AudiusProject/audius-protocol/blob/f188abfbfdc48f74efaa3019e4885e9c16d64c72/libs/src/services/discoveryProvider/DiscoveryProviderSelection.ts#L216

Revert "0.4.0 (#5506)"

---

discovery-provider/integration_tests/tasks/entity_manager/test_developer_app_entity_manager.py
discovery-provider/src/tasks/entity_manager/entities/developer_app.py

Didn't filter out tracks that were deleted when counting # of user apps.
Fixed this + added test

Fix app limit check [EM] C-2805

---

discovery-provider/src/api/v1/tracks.py

Fallback to secondaries when primary fails to stream.
prod

Fallback to secondaries when streaming

---

discovery-provider/src/api/v1/tracks.py

Skip play count for test stream

---

comms/discovery/pubkeystore/recover.go
comms/discovery/pubkeystore/recover_add_user.go
comms/discovery/pubkeystore/recover_test.go
discovery-provider/ddl/migrations/0009_user_pubkeys_reset.sql

Fixes case where two users were created in same POA block

fix pubkey recovery from POA

---

discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/app.ts
discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/libs.ts

adds identity to libs config which is required downstream by submit and evaluate

fix disbursement issue

---

discovery-provider/src/tasks/update_clique_signers.py

To avoid any possible automated clique proposing for now we'll manually add a few singers.
stage

Skip update clique signer for now

---

identity-service/src/notifications/emails/welcome.js

Missed this in QA also 😓 
Was being commented out by the <!--
Rendered as HTML, ensured can click button

Fix twitter link

---

libs/src/sdk/oauth/OAuth.ts

* Invert the conditional so we throw an error when scope is invalid

Fix oauth scope check

---

discovery-provider/integration_tests/tasks/entity_manager/test_developer_app_entity_manager.py
discovery-provider/src/tasks/entity_manager/entities/developer_app.py

Add developer app name length validation C-2794

---

libs/src/sdk/oauth/OAuth.ts

Context: https://audius-internal.slack.com/archives/C05F8KCSASD/p1688167293783269
Add ability to specify environment when initing OAuth so that you can try it against staging

[SDK] Add env option to OAuth

---

libs/src/sdk/services/EntityManager/EntityManager.ts

[SDK] Don't swallow EM relay errors; log detailed message when rate limit hit C-2642

---

mediorum/server/transcode.go

Makes transcode log output from ffmpeg.
`make dev` and upload a file. Progress is logged (when commenting out the progress line), and the full ffmpeg stdout and stderr are logged as well.

[CON-772] Log ffmpeg stdout and stderr

---

libs/src/api/Track.ts

Collection track ids were being saved in the wrong order

[C-2828] Fix collection upload order

---

libs/src/sdk/api/playlists/PlaylistsApi.test.ts
libs/src/sdk/api/playlists/PlaylistsApi.ts
libs/src/sdk/api/playlists/types.ts
sdk-consumer/index.ts

[C-2739] Add deletePlaylist to write sdk

---

discovery-provider/plugins/notifications/src/main.ts

rm spammy log

---

libs/src/sdk/api/playlists/PlaylistsApi.test.ts
libs/src/sdk/api/playlists/PlaylistsApi.ts
libs/src/sdk/api/playlists/types.ts
sdk-consumer/index.ts

* Not yet pulling the image from the first track if it's provided. We should discuss with product if we want this behavior in the sdk, or if the user should provide the image

[C-2732] Add createPlaylist to write sdk

---

mediorum/main.go
mediorum/server/db.go
mediorum/server/transcode.go

mirrors take turns retrying failed transcodes

retry failed transcode

---

discovery-provider/src/tasks/entity_manager/entities/playlist.py

Typo was causing playlist updates to fail

Fix playlist update em

---

discovery-provider/src/tasks/entity_manager/utils.py

Make sure to throw IndexingValidationError so it skips tx.
Tested on sandbox

Fix custom indexing validation

---

discovery-provider/src/queries/get_balances.py
discovery-provider/src/tasks/cache_user_balance.py

Rm undefined self attributes in cache user balance

---

discovery-provider/src/tasks/cache_user_balance.py

Filter users earlier in lazy balance refresh

---

libs/src/api/Account.ts
libs/src/api/Users.ts

This reverts commit 0adb382c5750ea1da6b25a35bb857503ee32420a.
This was reverted because indexing changes weren't out yet. It's all good now.

Revert "Revert single tx signup in libs (#5471)"

---

discovery-provider/src/queries/get_balances.py
discovery-provider/src/tasks/cache_user_balance.py

Comment out lazy refresh on cache user balance ids

---

mediorum/server/serve_blob.go
mediorum/server/serve_legacy.go

- Fixes attempt to log a listen for images (they were failing anyway - I noticed this because I saw logs for "unable to parse signature for request" coming from `logTrackListen()` for image CID requests which don't have a signature)
- Adds log for disallowed mp3 streaming on the legacy path, which was meant to be added in https://github.com/AudiusProject/audius-protocol/pull/5566
It's simple enough to test on staging by playing back a track and viewing an image, which I'll do before deploying.

Only log listen for tracks, and log legacy mp3 stream

---

discovery-provider/src/queries/get_entities_count_check.py
discovery-provider/src/queries/health_check.py

Add counts for each of these entities to ensure consistency.

Add entity counts

---

discovery-provider/src/wsgi.py

Log commit on discovery server start

---

discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
discovery-provider/src/tasks/entity_manager/entities/playlist.py
discovery-provider/src/tasks/entity_manager/entities/social_features.py
discovery-provider/src/tasks/entity_manager/entities/track.py
discovery-provider/src/tasks/entity_manager/entities/user.py
discovery-provider/src/tasks/entity_manager/utils.py

Allow delegated user writes

---

discovery-provider/src/api/v1/models/playlists.py
libs/src/sdk/api/playlists/PlaylistsApi.test.ts
libs/src/sdk/api/playlists/PlaylistsApi.ts
libs/src/sdk/api/playlists/types.ts
libs/src/sdk/services/EntityManager/EntityManager.ts
libs/src/sdk/services/EntityManager/types.ts
sdk-consumer/index.ts

* Add `is_private` to non-full playlist response (This is so that updates can pass the correct value of `is_private`)
* Add `fetchAndUpdatePlaylist` helper
* Add `addTrackToPlaylist`
* Add `removeTrackFromPlaylist`
* Fix "added at" timestamps by using currentBlock

[C-2733] Add addTrackToPlaylist and removeTrackFromPlaylist to sdk

---

discovery-provider/src/tasks/entity_manager/entities/track.py

Invalidate tracks for users without handle. This will unblock some nodes from indexing.
Tested normal flow on sandbox. And tested for user without handle.

Validate user has handle

---

identity-service/src/routes/idSignals.js
identity-service/src/utils/antiAbuse.js

Add new identity signal

---

libs/src/sdk/api/tracks/TracksApi.ts
libs/src/sdk/api/users/UsersApi.test.ts
libs/src/sdk/api/users/UsersApi.ts
libs/src/sdk/api/users/types.ts
libs/src/sdk/sdk.ts
sdk-consumer/index.ts

Add updateProfile to UsersApi
Add tests to the users tests
Manually tested with postman

[C-2740, C-2741] Add update profile to usersApi in SDK and add test

---

libs/src/sdk/api/playlists/PlaylistsApi.test.ts
libs/src/sdk/api/playlists/PlaylistsApi.ts
libs/src/sdk/api/playlists/types.ts
libs/src/sdk/api/tracks/TracksApi.test.ts
libs/src/sdk/api/tracks/TracksApi.ts
libs/src/sdk/api/tracks/types.ts
sdk-consumer/index.ts

Update the naming for the save and unsave endpoint in tracks and playlists apis to favorite and unfavorite
Tests all passed

[C-2845] Update save to favorite for the tracks and playlists endpoints

---

libs/src/sdk/services/Storage/Storage.ts

Fixes an issue audiuscast was running into

Update maxContentLength for sdk uploads

---

libs/src/sdk/sdkBrowserDist.ts

Add mood and genre to browser dist

---

discovery-provider/src/tasks/entity_manager/entities/track.py

load user record for `ai_attribution_user_id`

load ai_attribution_user_id in validation

---

discovery-provider/ddl/migrations/0013_index_cleanup.sql
discovery-provider/ddl/pg_migrate.sh
discovery-provider/ddl/tests/counting.sql

* adds example of sql tests for triggers
* reduces logging output to errors only
* drops indexes that are never used
https://linear.app/audius/issue/PLAT-151/plays-table-index-cleanup

Ddl index cleanup

---

libs/src/sdk/middleware/addAppNameMiddleware.ts
libs/src/sdk/sdk.ts

Update the app name middleware to fetch app name if not provided, but api inputs are provided
Also enforce that the required inputs for the config are not empty strings

[C-2782] Update app name middleware to fetch app name if not provided

---

mediorum/server/serve_legacy.go

instead of adding new route, make client not follow redirects.

Function to do disk check without following redirects.

---

discovery-provider/src/tasks/entity_manager/entities/track.py
discovery-provider/src/tasks/entity_manager/entity_manager.py

EntityManager should fetch before validation. The problem was only track creation would fetch the attribution user. 
Tested on sandbox. Verified track updates with track attribution work.

Fix AI attribute update

---

mediorum/server/serve_legacy.go

Uses GET instead of HEAD when checking for 200 on redirect because HEAD returns 200 when we're expecting 302.
`curl -XHEAD -v 'https://audius-content-10.figment.io/content/QmQAab2S9Wh6WLrGmm6RxDJkdhYw1gbeHfYSFZvLnsE7wj/150x150.jpg?localOnly=true'`
vs
`curl -XGET -v 'https://audius-content-10.figment.io/content/QmQAab2S9Wh6WLrGmm6RxDJkdhYw1gbeHfYSFZvLnsE7wj/150x150.jpg?localOnly=true'`

Use GET for mediorum redirect checks

---

discovery-provider/src/api/v1/users.py

Logging how long these take to monitor performance when dropping is_current.

Add duration log for user endpoints

---

dev-tools/commands/src/edit-track.mjs
libs/src/api/Track.ts
libs/src/sdk/api/tracks/TracksApi.ts
libs/src/sdk/api/tracks/types.ts
libs/src/sdk/services/Auth/AppAuth.ts
libs/src/sdk/services/Auth/Auth.ts
libs/src/sdk/services/Auth/types.ts
libs/src/sdk/services/Auth/utils.ts
libs/src/sdk/services/EntityManager/EntityManager.test.ts
libs/src/sdk/services/Storage/Storage.ts
libs/src/sdk/services/Storage/types.ts
libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.test.ts
libs/src/services/creatorNode/CreatorNode.ts
libs/src/utils/apiSigning.ts
mediorum/server/serve_upload.go
mediorum/server/server_basic_auth.go

Libs + sdk changes to handle retranscoding + updating metadata upon changing a track's preview start time.
audius-cmd upload-track, audius-cmd edit-track with -s flag, make sure new preview start time and cid is persisted in discovery

Libs edit file upload (for editing track previews)

---

discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py

Too zealous https://github.com/AudiusProject/audius-protocol/pull/5655
Passes now

Fix broken playlist_routes test

---

discovery-provider/src/queries/get_track_stream_signature.py

All previews are streamable regardless of the track's `is_premium` bool.

Make all track previews publicly streamable

---

discovery-provider/src/queries/get_skipped_transactions.py

boosts this number because stage hit the limit, push it, push it to the limit

boost max skipped tx

---

discovery-provider/src/tasks/entity_manager/entities/user.py

Get the CIDData row's data value instead of using the whole record.
Tested on stage w user update.

Fix user update merging cid data

---

discovery-provider/src/tasks/entity_manager/entity_manager.py

Log error when skipping tx

---

discovery-provider/nginx_conf/nginx.conf
discovery-provider/nginx_conf/utils.lua
discovery-provider/src/api_helpers.py
discovery-provider/src/queries/health_check.py

I regret trying to do it all in lua/nginx now.
Ordering is now stable again.
http://34.72.186.34:5000/health_check

Move joined health check to python code

---

libs/src/sdk/services/Auth/AppAuth.ts

* Strip 0x from sdk apiKey and secret if present

[C-2865] Strip 0x from apikey

---

mediorum/persistence/README.md

Fix mediorum persistence readme

---

libs/src/sdk/api/tracks/types.ts
libs/src/sdk/api/users/UsersApi.test.ts
libs/src/sdk/api/users/types.ts

Update ids in zod schemas to HashId

[C-2894] Update ids to HashIds

---

mediorum/persistence/persistence.go

Deletes all .tmp files on startup when using CDK's fileblob driver.

Delete CDK .tmp files on startup

---

libs/src/utils/apiSigning.ts

Was preventing client from working on latest SDK
Context: https://audius-internal.slack.com/archives/C03A6GK9ASE/p1690305717156629

Fix Web3 issue C-2900

---

discovery-provider/src/api/v1/helpers.py

V2 only users fail to fetch images
1. deployed to stage https://discoveryprovider.staging.audius.co/v1/users/handle/ray71823
2. confirmed that this link shows profile picture links when it did not before

[CON-801] Fix v2 only user images from public api

---

discovery-provider/src/api/v1/helpers.py
discovery-provider/src/api/v1/transactions.py
discovery-provider/src/api/v1/users.py

Continuing from https://github.com/AudiusProject/audius-protocol/pull/5695. I force pushed but the PR UI is not updating??? So this is just the same branch but renamed...

Add headers to parser for library route (Take Two) C-2906

---

discovery-provider/src/queries/get_authed_user.py

in case there's multiple user IDs for the same wallet, pick the first.
tested on stage. unblocked nikki's streaming.

Fix auth user for multi user wallet

---

discovery-provider/plugins/notifications/src/config.ts
discovery-provider/plugins/notifications/src/processNotifications/mappers/message.ts
discovery-provider/plugins/notifications/src/processNotifications/mappers/messageReaction.ts
discovery-provider/plugins/notifications/src/processNotifications/mappers/userNotificationSettings.ts
discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts

For debugging purposes. Also remove some outdated TODOs

Log when not attempting to push a DM notif

---

libs/src/sdk/api/generated/full/apis/UsersApi.ts

Run SDK gen for library auth headers

---

discovery-provider/ddl/migrations/0014_correct_cid_data_json.sql

Migration to fix this bug
https://github.com/AudiusProject/audius-protocol/pull/5612/files#r1268718847
some fields were stored as strings and not parsed for the data field.
Ran on sandbox.

Fix cid_data json data

---

dev-tools/commands/src/utils.mjs
libs/src/services/solana/SolanaWeb3Manager.ts
libs/src/services/solana/rewardsAttester.ts

* Updates the call signature for user bank functions in `SolanaWeb3Manager` to use a config object since it now has multiple optional properties.
* Adds `mint` support to all of the user bank functions to enable USDC flows.

Update all userbank functions to allow usdc mint

---

discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
discovery-provider/src/tasks/entity_manager/entities/playlist.py

Raise indexing error if track in playlist contents is malformed
Integration tests

Add indexing validation for tracks in playlist

---

libs/src/services/identity/IdentityService.ts

Bug in my last PR, supported currencies should be sol and usdc, not audio.

Change stripe supported currency to sol

---

discovery-provider/src/api/v1/models/activities.py
discovery-provider/src/api/v1/users.py

Returns tracks for tracks, collections for playlists/albums. One question for @nicoback2 in the PR
- This also fixes a swagger test I broke in my last PR :( 
Locally, hit the /full endpoint to inspect generated JSON

[PAY-1659] Improve library endpoint swagger types

---

identity-service/src/utils/antiAbuse.js

revert ID const change

---

discovery-provider/es-indexer/src/indexers/PlaylistIndexer.ts
discovery-provider/es-indexer/src/indexers/TrackIndexer.ts
discovery-provider/integration_tests/queries/test_search.py
discovery-provider/integration_tests/queries/test_search_track_tags.py
discovery-provider/integration_tests/queries/test_search_user_tags.py
discovery-provider/integration_tests/tasks/test_get_feed_es.py

Logs would have made this easy to debug. There was one additional spot using `length`
CI tests

Fix broken es tests and add logs

---

discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/save.test.ts.snap
discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/saveOfRepost.test.ts.snap
discovery-provider/plugins/notifications/src/email/notifications/components/Body.tsx

Fixes copy in email
Has not been, will confirm on stage before release.

Fix email copy for favorited

---

discovery-provider/src/queries/get_feed_es.py

Feed in ES works kind of differently, so we need to take bigger slides to paginate through. Not the best, but we have other feed efforts and this solves the current need.
CI tests

[C-2841] Fix offset for es feed

---

.circleci/src/jobs/release-github-draft.yml

Fix GH draft
Ran on CI to generate latest https://github.com/AudiusProject/audius-protocol/releases

Fix gh draft

---

discovery-provider/src/tasks/index_user_bank.py
libs/src/services/identity/IdentityService.ts

We have this logic in spl indexer, also skip these txs for now in user bank indexer since we are starting to test with v0 txs.
Not tested

Skip v0 txs in user bank indexer

---

discovery-provider/src/tasks/entity_manager/utils.py

* Add logs for appName and userHandle in entity manager

[C-2935] Log dev app details

---

docs/src/css/colors.css
docs/src/css/custom.css

Adjust sdk docs alert colors

---

libs/package.json

Add keywords to sdk package

---

discovery-provider/src/api/v1/tracks.py

Add fallback for rendezvous. Goes down the list of hashes in descending order. Times out after .5 sec.
Tested on sandbox. Able to stream https://audius.co/stereosteve/sunny-side-of-the-street.

Add stream fallback for rendezvous

---

discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
discovery-provider/src/tasks/entity_manager/entities/user.py

My change https://github.com/AudiusProject/audius-protocol/pull/5662 broke user events.
The fix is not on the release yet https://github.com/AudiusProject/audius-protocol/pull/5653.
Integration tests should've caught this, will add one.

Fix user events to use existing records

---

discovery-provider/ddl/migrations/0014_add_revert_blocks.sql
discovery-provider/src/utils/helpers.py

Deleting a record from blocks table should delete the record here in revert_blocks via fkey cascade.
Tested on prod DN1.

Add cascading deletes to revert_block fkey

---

solana-programs/reward-manager/program/src/processor.rs

Merging this change into public repo: https://github.com/AudiusProject/protocol-private/pull/1/files
Not tested - Relying on CI

[PAY-1699] Assert account key patch in rewards manager program

---

discovery-provider/src/tasks/entity_manager/entity_manager.py

Fix bug where duplicate slugs get written to db

---

libs/src/sdk/api/tracks/types.ts

Updating the schema for upload track metadata for the new upload flow
Adding nullable to a few of the fields, but the biggest change being that strict was removed. Wanted to flag in case that would cause issues elsewhere
All of the tests still passed

Update the upload track metadata schema for the new upload flow

---

discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimitConfig.ts

discovery relay callback to this PR https://github.com/AudiusProject/audius-protocol/pull/5759#event-10049692420

block keys with zero or less configured calls

---

libs/src/AudiusLibs.ts
libs/src/NativeAudiusLibs.ts
libs/src/WebAudiusLibs.ts
libs/src/services/creatorNode/CreatorNode.ts
libs/src/utils/getNStorageNodes.ts

Fixes issue with getNStorageNodes where the number of potential nodes to select from were incorrectly set to the number on nodes we wanted back.
Fixes issue where creatorNode fails if the node it selected is unhealthy. Now we retry with the remaining nodes until one works.

[C-2949] Fix creatorNodeSelection, getNStorageNodes

---

discovery-provider/plugins/pedalboard/apps/relay/src/config.ts

relay on stage is continously restarting because this doesn't have a reasonable default, I have a better PR on the way but this'll stop it from restarting for now 

add reasonable default to chain id

---

discovery-provider/plugins/pedalboard/apps/relay/src/config.ts

remove error if undefined

---

discovery-provider/plugins/pedalboard/apps/relay/src/antiAbuse.ts
discovery-provider/plugins/pedalboard/apps/relay/src/config.ts

last one, to keep relay from crashing

handle nonconfigured aao

---

discovery-provider/ddl/migrations/0023_fix_broken_cover_art_sizes.sql

Add migration to fix stored file:/ and blob:/ things
Ran on sandbox node, 6 records modified. sandbox is a lil behind

Add migration to fix broken cover arts

---

discovery-provider/plugins/pedalboard/docker/Dockerfile

Makes it so changing some random ts file doesn't require us to do an npm install from scratch each time
```
docker compose up --build -d
```
After file modification picks up from a bunch of cached steps
```
=> CACHED [trending-challenge-rewards installer 10/14] RUN npm install                                                                                                                                0.0s
=> CACHED [trending-challenge-rewards installer 11/14] COPY --from=builder /app/out/full/ .                                                                                                           0.0s
=> CACHED [trending-challenge-rewards installer 12/14] COPY turbo.json …
```

Improve pedalboard dockerfile

---

.circleci/src/workflows/discovery.yml

Drop stage discovery 2 deploy steps

---

discovery-provider/integration_tests/queries/test_get_sitemap.py
discovery-provider/src/queries/get_sitemap.py

Fix sitemap generation.
* User handle not handle_lc because that is the correct canonical URL
* Ensure that counting is the same methodology as getting slugs (there numbers were not equal before, add a test for it)
* Set limit to 40K
* Add missing static pages to default root
Unit tests

[C-2957] Fix sitemap generation

---

discovery-provider/ddl/migrations/0024_user_count_idx.sql
discovery-provider/nginx_conf/nginx.conf
discovery-provider/src/app.py
discovery-provider/src/queries/get_sitemap.py
discovery-provider/src/tasks/cache_entity_counts.py

Improve perf, removing group bys, adding an index, and caching in nginx

Improve sitemap perf

---

discovery-provider/integration_tests/challenges/test_trending_challenge.py
discovery-provider/src/challenges/trending_challenge.py
discovery-provider/src/tasks/calculate_trending_challenges.py
discovery-provider/src/tasks/index_nethermind.py

Fixes date. Types were lying.
Extend date calculus to 3pm to cover when we need to fix things.
Prod dn2

Fix date check in trending rewards

---

discovery-provider/plugins/pedalboard/apps/sla-auditor/src/audits/version.ts
discovery-provider/plugins/pedalboard/apps/sla-auditor/src/config.ts
discovery-provider/plugins/pedalboard/docker-compose.yml

Add fixes to SLA auditor before prime time
```
docker compose -f dev-tools/compose/docker-compose.yml up db
docker compose up --build -d sla-auditor
docker network connect compose_default sla-auditor
```

Add enough data check to sla auditor

---

docs/docs/token/running-a-node/sla.md
docs/i18n-disabled/en/docusaurus-plugin-content-docs/current/token/running-a-node/sla.md

Add link to governance vote on SLA ratification.
n/a

Add link to SLA

---

mediorum/server/monitor.go

Increase the timeout here since this query can take a while sometimes.

Increase upload count timeout

---

discovery-provider/src/api/v1/helpers.py

Loop wasn't terminating correctly if no 200s
Deploy to stage, test https://discoveryprovider3.staging.audius.co/v1/full/users/handle/seb71923/tracks

fix infinite loop possibility when fetching images in API response

---

solana-programs/payment-router/README.md
solana-programs/payment-router/package.json
solana-programs/payment-router/programs/payment-router/src/lib.rs
solana-programs/payment-router/programs/payment-router/tests/tests.rs
solana-programs/payment-router/tests/payment-router.ts
solana-programs/staking-bridge/README.md
solana-programs/staking-bridge/package.json
solana-programs/staking-bridge/programs/staking-bridge/src/lib.rs
solana-programs/staking-bridge/programs/staking-bridge/tests/raydium_tests.rs
solana-programs/staking-bridge/programs/staking-bridge/tests/utils.rs
solana-programs/staking-bridge/programs/staking-bridge/tests/wormhole_tests.rs
solana-programs/staking-bridge/tests/staking-bridge.ts

* `UncheckedAccount` for `Account<Empty>` for PDAs
* Fix broken tests due to dead code / broken imports
* Update READMEs a little
Payment router
```
cargo test-sbf
./scripts/setupTestEnv.sh id.json
./scripts/testCreatePaymentRouterBalancePda.sh
./scripts/testRoute.sh
```
Staking bridge
```
cargo test-sbf
./scripts/setupTestEnv.sh id.json
./scripts/testCreateStakingBridgeBalancePda.sh
./scripts/testRaydiumSwap.sh
./scripts/testWormholeTransfer.sh
ethProviderUrl=<eth-provider-url> ethPrivateKey=<eth-private-key> node scripts/redeemWormholeTokens.ts <transaction-id>
```

Fix up misc issues in payment router

---

discovery-provider/plugins/notifications/package.json
discovery-provider/plugins/notifications/scripts/test-push-notification.ts
discovery-provider/plugins/notifications/src/__tests__/processEmailNotifications.test.ts
discovery-provider/plugins/notifications/src/email/notifications/index.ts
discovery-provider/plugins/notifications/src/utils/populateDB.ts

this CTE here queries all users in the db which I believe is causing the hang in notifications, the other groups of SQL in this file filter by user ids

PLAT-1126: mod CTE in app notifications so it doesnt query all users

---

discovery-provider/es-indexer/src/indexNames.ts
discovery-provider/es-indexer/src/indexers/UserIndexer.ts
discovery-provider/es-indexer/src/types/docs.ts
discovery-provider/src/api/v1/models/users.py
discovery-provider/src/queries/query_helpers.py
discovery-provider/src/queries/response_name_constants.py
discovery-provider/src/utils/elasticdsl.py
identity-service/test/sendNotifications/mockLibs.js
libs/src/api/Users.ts
libs/src/sdk/api/generated/full/models/UserFull.ts
libs/src/services/discoveryProvider/DiscoveryProvider.ts
libs/src/utils/types.ts

So client can read when loading profiles without issuing a separate network req

Add is_current_user_subscribed to API and es-indexer

---

discovery-provider/ddl/migrations/0026_fix_broken_images.sql

Migrations to fix all user/track/image with
```
x LIKE 'blob%' 
OR x LIKE 'file%' 
OR x LIKE '/data/user/%'
OR x LIKE 'https%'
```
Ran the CTE against prod db
* 32 playlist records
* 0 user records (prof pic and cover photo)
* 0 track records
Could probably remove everything but the playlist one -- just lmk when you review @michellebrier

Fix broken formats

---

solana-programs/payment-router/README.md
solana-programs/payment-router/tests/payment-router.ts
solana-programs/staking-bridge/README.md
solana-programs/staking-bridge/scripts/redeemWormholeTokens.ts

Clean up READMEs and finish up payment router

---

discovery-provider/src/tasks/cache_user_balance.py

Upgraded solana introduction broke this -- there were no types. There should be even more, but as soon as waudio_token was typed, resolving became very easy.
Typechecks & prod dn1

[PAY-1747] Fix balance caching

---

libs/src/AudiusLibs.ts
libs/src/services/solana/SolanaWeb3Manager.ts

Export MintName and DEFAULT_MINT for use on client.
Snuck in an extra comment and a change to make `instructionIndex` on `createTransferInstructionsFromCurrentUser` optional.
Local linked libs

[PAY-1750] Export MintName and DEFAULT_MINT from libs

---

mediorum/server/placement.go

[This change](https://github.com/AudiusProject/audius-protocol/pull/5832/files#diff-de760a5b7ff79ecccace2a24cfbaf28da2b9bdc980fec35e8fc990a98727ebcaR27-R29) removed current host name from list of healthy peers...
but the `rendezvous` function had inadvertently assumed the current hostname would be in that list... and some bad logic caused the `-1` index to cause `isMine` to always be true since current host was missing from the healthy host list.
`make test` works now

quick fix: ensure my host is in healthy host list for rendezvous

---

monitoring/healthz/package-lock.json

Update healthz package lock to version 3 (npm 9)

Update healthz package-lock

---

discovery-provider/ddl/migrations/0021_fix_album_repost_save.sql

This migration was causing a deadlock on foundation DN1. Our migrations are vulnerable to deadlocks or blocking queries that the server container receives as well as lingering processes while deploying new changes. Most of the time this is not an issue but this migration is a big one and locks up the entire repost / saves table so it's more susceptible. 
Tested on sandbox. It killed other active queries and could unblock itself.

Kill active queries when running repost/save migration

---

discovery-provider/plugins/notifications/package-lock.json
discovery-provider/plugins/verified-uploads/Dockerfile
discovery-provider/plugins/verified-uploads/package-lock.json

Upgrade notifications and verified uploads plugins to node 18.17

[INF-438] Upgrade discovery plugins to node 18

---

discovery-provider/src/api/v1/users.py
discovery-provider/src/queries/get_collection_library.py

Filters out deleted collections from the library endpoints
Also snuck in some safer typing refactors
It hasn't

[PAY-1760] Filter deleted collections from library endpoint

---

dev-tools/commands/src/purchase-track.mjs
discovery-provider/src/api/v1/users.py

Fix Purchases Endpoint

---

monitoring/vector/vector.toml

[proto-1145] add relay logs to vector container

---

discovery-provider/src/api/v1/tracks.py

while awaiting Qm migration try all hosts.

try all host for track stream

---

mediorum/ddl/ddl.go

Add min time to partition scheduling

---

discovery-provider/src/queries/get_health.py
discovery-provider/src/queries/health_check.py

Add optional args for rewards manager, user bank, and spl audio drift checks. Similar to other health checks e.g reactions
Against stage dn2

[PAY-1806] Update health checks

---

mediorum/server/monitor.go

Makes the mediorum disk+db check retry a few times more quickly on startup, and allows for a 10 second timeout instead of 1 second when reading db size. I've seen this flake on startup, so it makes sense to be more lenient and not have to wait 5 minutes for the check to re-try in order for the health check to report a 200.

Update mediorum db status more often on startup with longer timeout

---

dev-tools/commands/src/auth-headers.mjs
dev-tools/commands/src/tip-audio.mjs
discovery-provider/src/api/v1/transactions.py

Fixes bugs in the USDC Transactions API PR that broke the AUDIO Transaction History API
Tested locally using Insomnia to mock requests and `audius-cmd` to generate mock data

Reland: USDC Transactions API

---

libs/src/services/discoveryProvider/DiscoveryProvider.ts

I think this may be causing a number of additional relay requests during testing.

Libs Discovery Relay: turn down to 0

---

discovery-provider/src/tasks/index_nethermind.py

Plan on deleting user historical records tomorrow and reverting via fkey. 
https://github.com/AudiusProject/audius-protocol/pull/5811
We still need these manual reverts until then.
Tested on prod sandbox. Reverting unblocked.

Temporarily revert user manually

---

dev-tools/commands/src/create-user.mjs
dev-tools/commands/src/utils.mjs
dev-tools/compose/nginx_ingress.conf
discovery-provider/Dockerfile
discovery-provider/plugins/pedalboard/apps/relay/src/config/config.ts
discovery-provider/plugins/pedalboard/apps/relay/src/error.ts
discovery-provider/plugins/pedalboard/apps/relay/src/middleware/antiAbuse.ts
discovery-provider/plugins/pedalboard/apps/relay/src/middleware/errorHandler.ts
discovery-provider/plugins/pedalboard/apps/relay/src/middleware/logging.ts
discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimiter.ts
discovery-provider/plugins/pedalboard/apps/relay/src/middleware/validator.ts
discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts
discovery-provider/plugins/pedalboard/apps/relay/src/walletManager.ts
discovery-provider/plugins/pedalboard/apps/relay/src/web3.ts
libs/src/api/Account.ts
libs/src/services/identity/IdentityService.ts
libs/src/services/web3Manager/Web3Manager.ts

PROTO-1212: audius-cmd decent relay

---

mediorum/server/serve_blob.go

sets Cache-Control header when serving images

Add cache-control header for images

---

packages/common/src/store/ui/modals/withdraw-usdc-modal/index.ts
packages/common/src/store/ui/withdraw-usdc/selectors.ts
packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.module.css
packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.tsx
packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.tsx
packages/web/src/components/withdraw-usdc-modal/components/Error.module.css
packages/web/src/components/withdraw-usdc-modal/components/Error.tsx
packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.module.css
packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.tsx

Migrating https://github.com/AudiusProject/audius-client/pull/4067

[PAY-1822][PAY-1824][PAY-1825] Address withdrawal QA (#4067)

---

discovery-provider/plugins/notifications/package-lock.json
discovery-provider/plugins/notifications/package.json
discovery-provider/plugins/pedalboard/apps/relay/package.json
discovery-provider/plugins/pedalboard/package-lock.json
discovery-provider/plugins/pedalboard/package.json
identity-service/package-lock.json
identity-service/package.json
monitoring/exporters/sdk/package-lock.json
monitoring/exporters/sdk/package.json
monitoring/healthz/package-lock.json
monitoring/healthz/package.json
package-lock.json
packages/common/package.json
packages/embed/package.json
packages/mobile/package.json
packages/web/package.json
sdk-consumer/package-lock.json
sdk-consumer/package.json

sdk on protocol is pretty old in comparison to where client was, this updates it
N/A

sdk update

---

discovery-provider/src/tasks/index_user_bank.py

Forgot to add the withdrawal to the session 🤦 
Will test again on stage but feels obvious enough to not need to test tbh.

[PAY-1827] Fix withdrawals indexing

---

.circleci/src/@continue_config.yml

Add `run-probers-workflow` argument to CI

---

packages/web/src/pages/upload-page/forms/EditTrackForm.module.css
packages/web/src/pages/upload-page/forms/EditTrackForm.tsx

Use the new preview button style

[C-3072] Update editTrackForm preview button to use the new styles

---

.circleci/config.yml
package-lock.json
package.json
packages/common/package.json
packages/embed/package.json
packages/eslint-config-audius/package.json
packages/mobile/package.json
packages/probers/package.json
packages/stems/package.json
packages/web/package.json

Migrate https://github.com/AudiusProject/audius-client/pull/4068
Also prefix release version tags with `client`

Migrate client release versioning fix

---

.circleci/config.yml

We were trying to trigger pipeline continuation twice (because of the CI merge) but the path-filtering steps we have defined should be sufficient

Fix CI Workflow triggers

---

packages/web/src/components/track/desktop/ConnectedTrackTile.module.css

An absolute hack but it seems to work?
Fixes PAY-1641
Before
After

[PAY-1641] Fix social overlap

---

packages/web/src/components/back-button/BackButton.js
packages/web/src/components/back-button/BackButton.module.css
packages/web/src/pages/upload-page/forms/EditCollectionForm.module.css
packages/web/src/pages/upload-page/forms/EditTrackForm.module.css

Update the min-width of the edit forms
Update the back button to conform to the designs

[C-3042, C-3046, C-3073] Update back button and min-width of edit forms in new upload flow

---

packages/web/src/components/modal-radio/ModalRadioItem.module.css
packages/web/src/components/modal-radio/ModalRadioItem.tsx

Add style to make the cursor default

[C-3066] Update cursor on disabled modal radio items

---

packages/web/src/pages/upload-page/fields/ReleaseDateField.module.css

Updated the hover and focus border colors to match other input fields
Not a great implementation bc it is a custom input component, but works

[C-3064] Update the hover and focus styles for the releaseDateField border

---

.circleci/config.yml

Update circlci continuation config to only run integration tests and gcp on protocol changes

[INF-471] Only run integration and gcp workflows on protocol

---

packages/web/src/pages/saved-page/SavedPageProvider.tsx
packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx

Fix not all tracks being rendered on library tracks page PAY-1831

---

packages/mobile/src/components/drawers/OfflineListeningDrawer.tsx
packages/web/src/components/header/desktop/Header.module.css

[Library QA] Gate offline purchases toggle; add padding to filter pills PAY-1845 PAY-1830

---

packages/web/src/components/upload/TrackPreview.module.css
packages/web/src/components/upload/TrackPreviewNew.tsx

[C-3062] Update track preview item styles

---

packages/web/src/pages/upload-page/validation.ts

Need the create function for the schema to allow the release date validation to work properly

Update Sdk scheme to create function to fix release date validation

---

packages/web/src/pages/upload-page/fields/CollectionTrackFieldArray.tsx
packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx
packages/web/src/pages/upload-page/validation.ts

- Fixes form validation for collections
- Fixes bug where the react element key was based on the track name value and could match
- Adds placeholder to drag and drop for better layout during drag and drop
local web

[C-3081] Fix collection form validation; fix duplicate key bug

---

discovery-provider/src/api/v1/helpers.py
discovery-provider/src/api/v1/models/users.py
discovery-provider/src/api_helpers.py
discovery-provider/src/queries/query_helpers.py
discovery-provider/src/tasks/entity_manager/entities/user.py
discovery-provider/src/utils/elasticdsl.py
discovery-provider/src/utils/helpers.py

This reverts commit 69887da264f90f2ba525823002d39638d6acd7fc.
feed is too slow when there are cache misses. steve working on change to cache on content node instead

Revert "Surface image cid cache in feed endpoints (#5910)"

---

.circleci/src/commands/@mobile-commands.yml
.circleci/src/workflows/mobile.yml

This step isn't needed any more because the structure of ours hoisted deps changed

Fix iOS build-upload ci step

---

identity-service/package-lock.json
identity-service/package.json

Updates sdk in identity so that it consumes the new TransactionHandler from libs.
Deployed to stage-identity, confirm tipping via relay works.

Update sdk on identity (upgraded solana in libs)

---

packages/mobile/src/app/Drawers.tsx

Fixes strange bug where some mobile drawers are visible when interacting with camera roll on android

[C-3087] Fix android drawer overflow

---

packages/web/src/pages/upload-page/components/FinishPage.module.css
packages/web/src/pages/upload-page/components/FinishPageNew.tsx
packages/web/src/pages/upload-page/fields/CollectionTrackField.tsx
packages/web/src/pages/upload-page/forms/EditTrackForm.tsx

Update the visit CTA after upload finish to go to the right places
Also small update to add button types so that preview buttons dont try to submit

[C-3070, C-3074] Add correct visit CTAs to the finish page of the new upload flow

---

packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
packages/web/src/pages/artist-dashboard-page/components/USDCCard.tsx

- PAY-1823 Right align dropdown
- PAY-1782 Fix lineheight in purchase drawer

[PAY-1823][PAY-1782] Minor USDC ui fixes
