libs/src/sanityChecks/rolloverNodes.ts, libs/src/services/creatorNode/CreatorNode.ts
Gets the secondary with the max clockValue in the primary replacement. Since the secondaries are all we have if the primary is down, we just want to pick the best one
=> Check clock values, not blocknumbers, when replacing primary in sanity check

.circleci/config.yml, discovery-provider/compose/docker-compose.redis.yml, discovery-provider/src/eth_indexing/event_scanner.py, discovery-provider/src/queries/get_health.py, discovery-provider/src/queries/get_oldest_unarchived_play.py, discovery-provider/src/tasks/index.py, discovery-provider/src/tasks/index_metrics.py, discovery-provider/src/utils/cache_solana_program.py, discovery-provider/src/utils/helpers.py, discovery-provider/src/utils/redis_metrics.py, discovery-provider/src/utils/test_get_cached_metrics.py, docker-compose.test.yml, docker-compose.yml, identity-service/compose/docker-compose.full.yml, identity-service/scripts/run-tests.sh
Remove custom `redis_set_and_dump` and `redis_get_and_restore`.
Instead of these, we can opt in for the build in redis persistence configurations https://redis.io/docs/management/persistence/
See docker-compose PR: https://github.com/AudiusProject/audius-docker-compose/pull/176
`audius-compose up` & verify health checks
=> [PLAT-538] Remove custom redis disk persistence, upgrade redis

discovery-provider/src/queries/get_health.py, discovery-provider/src/queries/get_latest_play.py, discovery-provider/src/queries/get_oldest_unarchived_play.py
timestamp was in datetime format rather than POSIX float so redis could not set it
tested on stage
=> Fix redis timestamp in health check

comms/internal/rpcz/chat.go, comms/internal/rpcz/chat_test.go, comms/schema/schema.go, comms/schema/schema.ts, libs/src/sdk/api/chats/serverTypes.ts
Support unreacting.
Add unreact case to chat test
=> Allow nil reactions in comms react RPC to unreact

discovery-provider/integration_tests/premium_content/test_access.py, discovery-provider/src/schemas/track_schema.json, libs/src/services/schemaValidator/schemas/trackSchema.json, libs/src/utils/types.ts
So that the client may later know where the nft collection image lives and can fetch it.
Will need to upgrade sdk and client to consume.
None
N/A
=> Include imageUrl for nft collection premium conditions for track

dev-tools/startup/creator-node.sh, docker-compose.yml
For local dev, we define CN envvars in 3 places:
1. `./creator-node/compose/base.env` -> this is for legacy `A` and is deprecated in `audius-compose` stack
2. `./docker-compose.yml`
3. `./dev-tools/startup/creator-node.sh`
#2 and #3 are redundant so I moved all envs from `./docker-compose.yml` into `./dev-tools/startup/creator-node.sh`
Also many of the envvars from `base.env` were not copied over into the new `audius-compose` stack, so I also copied those over
Confirmed below works as expected
```
audius-compose build
audius-cmd create-user
```
n/a
=> Fix & consolidate CN envvars for local dev for audius-compose

comms/Makefile, comms/internal/rpcz/chat_block_test.go, comms/internal/rpcz/chat_delete_test.go, comms/internal/rpcz/chat_permissions_test.go, comms/internal/rpcz/chat_test.go, comms/internal/rpcz/rate_limit_test.go, comms/internal/rpcz/test_utils.go, comms/internal/rpcz/validator.go, comms/server/server.go, comms/server/server_test.go
- Return 400 error on validation failure in `/mutate` 
- Randomize IDs in tests and re-enable package test parallelism. We already rollback tx's at the end of tests.
=> Misc comms cleanup

creator-node/src/blacklistManager.js
Changes un-delist logs from debug to info. These logs are infrequent.
Verified end-to-end delist and un-delist flow for trackId and cid.
Monitor for logs containing `Removed entry with type` or `does not exist in ContentBlacklist`.
=> Change track un-delist logs to info

discovery-provider/integration_tests/tasks/test_index_trending.py, discovery-provider/integration_tests/tasks/test_index_trending_notification.py, discovery-provider/src/queries/get_trending_tracks.py, discovery-provider/src/tasks/index_trending.py
Trending Notification created after each trending job run
Creates a new trending notification when a track is in the top 5 trending (weekly trending, across all genres)
If the track moves up, then create a new notification for the user. 
But do not notify the user within 24 hours of last notification. 
For the timestamps, the trending jobs was previously run every hour, but this has been updated to only run on the hours mark itself, triggered by finding the correct blocknumber/block timestamp corresponding to the point in time when the timestamp crosses over the hour mark
Wrote test to validate it works as intended
=> Add trending notif

libs/src/sdk/middleware/discoveryNodeSelectorMiddleware.ts
Temp fix for bug that is breaking audio transactions page on prod.
`currentVersion` is an empty string in this code path because libs performs services selection, caches result in local storage, which causes SDK to shortcircuit and not perform services selection.
Tested locally by linking libs to local client.
=> Rt sdk fix

creator-node/src/components/healthCheck/healthCheckComponentService.js, creator-node/src/components/healthCheck/healthCheckComponentService.test.js, creator-node/src/components/healthCheck/healthCheckController.js
Ensure health check still returns full response object if `isReadOnlyMode = true`
Also:
- remove unused `sequelize` param for `healthCheck` func
Updated unit tests
Confirmed route returns 500 and `isReadOnlyMode: true` when set:
`<endpoint>/health_check` should return identical response whether `isReadOnlyMode` is true or false, with only exception being http response code of 500 vs 200
=> Fix CN isReadOnlyMode health check

discovery-provider/alembic/versions/36ed02ac38f7_backfill_null_artist_pick_discrepancies_.py
For these 5 users, discprov has artist pick IDs saved while identity has null artist pick IDs. This means it successfully wrote when the users set an artist pick to both discprov and identity, but when they later unset their artist picks, the change wasn't indexed in discprov. I think this is because of optimizely gating weirdness bc of an adblocker, etc, like we were seeing with entity manager, in which case it defaulted to not writing to discprov.
I verified that unsetting an artist pick writes correctly to discprov normally. There are only 5 instances of this out of 12.5k records so it doesn't seem like a bug in the EM flow for artist pick. If it is optimizely, we shouldn't see anymore cases of this since the EM users flag, which the discprov write was gated by, is deleted now.
There …
=> Backfill null artist pick discrepancies in discprov

discovery-provider/alembic/versions/2fad3671bf9f_backfill_artist_pick.py
So as to not overwrite new data being written after the backfill csvs were generated, only update user records before 1/6/23 8:35 UTC (when the backfill data was pulled).
Run up and down on prod clone. Verify no errors, verify that # of non-null artist picks in discprov == # of artist picks in the prod_identity CSV. Edit date, verify number of updated records change.
=> Artist pick backfill: only update records last updated before the csvs were pulled

discovery-provider/alembic/trigger_sql/handle_user_balance_changes.sql, discovery-provider/alembic/versions/6a9f01e775d5_update_triggers.py, discovery-provider/integration_tests/notifications/test_tier_change.py, discovery-provider/integration_tests/queries/test_notifications/test_user_tier_change_notification.py, discovery-provider/integration_tests/utils.py, discovery-provider/src/api/v1/utils/extend_notification.py, discovery-provider/src/queries/get_notifications.py
Adds tier change notification for triggers
Wrote tests to verify that the notification was created on tier change update or insert
=> Add tier change notification via triggers

discovery-provider/nginx_conf/main.lua
Seeing a bunch of these errors
```
{"level": "ERROR", "type": "openresty", "log": "{\"level\": \"ERROR\", \"type\": \"openresty\", \"message\": \"2023/01/18 01:26:06 [error] 22#22: *766 lua entry thread aborted: runtime error: /usr/local/openresty/conf/main.lua:265: bad argument #1 to 'decode' (string expected, got nil)\"}"}
{"level": "ERROR", "type": "openresty", "log": "{\"level\": \"ERROR\", \"type\": \"openresty\", \"message\": \"stack traceback:\"}"}
{"level": "ERROR", "type": "openresty", "log": "{\"level\": \"ERROR\", \"type\": \"openresty\", \"message\": \"coroutine 0:\"}"}
{"level": "ERROR", "type": "openresty", "log": "{\"level\": \"ERROR\", \"type\": \"openresty\", \"message\": \"[C]: in function 'decode'\"}"}
{"level": "ERROR", "type": "openresty", "log": "{\"level\": …
```
=> Handle nil body data in nethermind rpc request

libs/src/api/Notifications.ts, libs/src/services/dataContracts/EntityManagerClient.ts
Add methods to libs notifications to write actions:
Playlist View action to mark when a user views a playlist
Notifications View action to mark when a user views their notifications
Create Notification action to create announcement notifications
Ran the system locally e2e and validated that the client could trigger the action and it was viewed and indexed on discovery
=> Write entity manager notifications in libs

discovery-provider/src/api/v1/tracks.py, discovery-provider/src/queries/get_track_stream_signature.py
Turn on track cid streaming. If track has no cid, use track id streaming.
Was already tested prior. Does need some CN counterpart changes; PR for this should be coming soon.
Should definitely test the combo of this and that PRs though.
None here. There should be existing monitoring on CN side.
=> Use track cid streaming and fallback track id streaming

libs/src/sdk/api/chats/ChatsApi.ts
Ensures the `last_message` in the chats responses are decrypted before being returned by the SDK.
Tested locally with client by linking libs
=> SDK: Decrypt the last message in the getChats response

discovery-provider/src/api/v1/models/playlists.py, discovery-provider/src/models/playlists/playlist.py, libs/src/sdk/api/generated/default/models/Playlist.ts, libs/src/sdk/api/generated/full/models/PlaylistFull.ts
Add permalinks to the playlist model to get returned to the front end when fetching a playlist
ran the /playlists/<playlist_id> endpoint on my remote machine and confirmed permalink is getting returned
=> Update discovery api to return permalink with playlist objects

creator-node/nginx_conf/nginx.conf, discovery-provider/nginx_conf/nginx.conf
add reverse proxy rule for nats container for sake of exchange and health check.
=> nginx config for nats container

discovery-provider/src/api/v1/playlists.py
When anyone goes to the "Let Them DJ" page the same results are given for any user. The correct behavior is that this list is made up of playlists from the followees of the user requesting the page. If you unfollow any of the accounts on the page itself you will see they still show up after a refresh.
This fix makes the filter param available in the downstream query. Previously this was non-existent and falling into the "None" case every time.
I still need to learn how to write API level tests, stay tuned for tomorrow 🙃 
I don't think so. People will see that their "Let Them DJ" page change to reflect who they follow.
=> (WIP) PLAT-339: add filter arg to top parser

discovery-provider/scripts/start.sh
Lots of nodes behind today (healthz.audius.co)
I believe what happens is that the auto restart policy on the indexer docker container can in some cases (maybe OOM) bring it back from the dead by just bringing back the container and not clearing the volume. https://github.com/AudiusProject/audius-docker-compose/blob/main/discovery-provider/docker-compose.yml#L132
This can cause the /var/celerybeat.pid to exist between celery invocations, which will cause the celery tasks to never start. 
One SP for example dn1.materlightblooming.xyz has no logs for `index.py` (our main indexer job) https://audius.loggly.com/search#terms=%22index.py%22&from=2023-01-24T20:49:38.302Z&until=2023-01-24T21:19:38.302Z&source_group=&filter=tag;matterlightblooming
I was able to repro this state by running `docker …
=> Clear beatfile

discovery-provider/src/tasks/entity_manager/utils.py
The reason it’s broken is because the playlist seen primary key constrain is being broken.
Here’s a snapshot of the tbl in stage
```
Table "public.playlist_seen"
Column    |            Type             | Collation | Nullable | Default | Storage  | Stats target | Description
-------------+-----------------------------+-----------+----------+---------+----------+--------------+-------------
user_id     | integer                     |           | not null |         | plain    |              |
playlist_id | integer                     |           | not null |         | plain    |              |
seen_at     | timestamp without time zone |           | not null |         | plain    |              |
is_current  | boolean                     |           | not null |         | plain    | …
```
=> Fix discovery playlist seen indexing

discovery-provider/src/queries/get_users_account.py
Realized user collections get loaded through a different route where playlists get skimmed down to fewer attributes, so made sure to add permalink here as well
Tested against my machine hitting my wallet address
http://34.132.236.109:5000/users/account?wallet=<wallet address>
=> Add permalink to user collections in users/account

libs/src/sdk/middleware/discoveryNodeSelectorMiddleware.ts
Previously, the SDK would fail on healthchecks for services with a blockdiff of 0 due to a falsey check rather than a null/undefined check
=> SDK: Don't fail healthcheck on 0 blockdiff

identity-service/src/routes/location.js
We're switching to ipdata from ipapi for location data for `/location` in identity. Unfortunately ipdata uses a different name for one of the fields we depend on - `is_eu` instead of `in_eu`, so this commit appends an `in_eu` field with the same value so client can stay the same.
Checked response using insomnia.
=> Append in_eu field to location response

libs/src/sdk/api/generator/gen.js
To remove the JDK dependency when generating SDK code.
From the `libs` directory run the sequence of codegen commands via NPM and you should see that the script uses docker to pull the openapi image instead of building with java. You can also remove the jdk from your system to prove it's no longer needed. I never installed the JDK on this machine that I tested on.
The first time you run this you'll need to pull the docker image, afterwards it should be pretty quick.
You can find the full list in the readme next to gen.js.
```
npm run gen:dev
npm run gen:dev:default
npm run gen:dev:full
npm run gen:stage
npm run gen:stage:default
npm run gen:stage:full
npm run gen:prod
npm run gen:prod:default
npm run gen:prod:full
```
I don't think so.
================ REMINDER: ================
Some …
=> PLAT-623: death to the jdk

discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py, discovery-provider/src/tasks/entity_manager/entity_manager.py, discovery-provider/src/tasks/entity_manager/notification.py, discovery-provider/src/tasks/entity_manager/playlist.py, discovery-provider/src/tasks/entity_manager/social_features.py
Subscribe on follow in discovery indexer rather than in the client. This will reduce the time required waiting for relay to complete when following a user (and then auto-subscribing) since the EM events are processed at the same time rather than sequentially. The time delay from doing sequential FOLLOW then SUBSCRIBE events was causing some writes to not be successfully persisted to the subscriptions table in discovery if the user exited the app shortly afterward, since we don't fire and forget relays.
integration + test with local client
=> Subscribe/unsubscribe on follow/unfollow in EM

discovery-provider/es-indexer/src/indexNames.ts, discovery-provider/es-indexer/src/indexers/PlaylistIndexer.ts
Bug in feed endpoint using es where playlist save and repost counts are incorrect. 
The root cause is because entity manger events for save and repost store save_type and repost type as playlist instead of the legacy album field. 
This change allows es to update on either field
=> Playlist es indexer fix

.vscode/launch.json
Adds VSCode launch config to run storage node with a debugger.
N/A
N/A
=> [CON-561] Add launch config to debug storage node

discovery-provider/src/api/v1/tracks.py
This is kind of wild! We don't actually call this api from *anywhere* in the client except for offline mode.
The client fetches single tracks by handle & slug most of the time and that does not filter out deleted tracks.
This however makes it so that trying to download deleted favorites don't work so well (we try a few times because of a 404 and don't actually realize that the track is juts deleted).
I believe this change is safe to make! But it's obviously a big deal.
The other change I would like to make would be to revert https://github.com/AudiusProject/audius-protocol/pull/2220
But I think it's still possible there is missing data somewhere and that warrants a larger convo.
=> [C-2005] Remove filter deleted on individual discovery node tracks

discovery-provider/src/api/v1/playlists.py, discovery-provider/src/queries/get_top_playlists.py, discovery-provider/src/queries/queries.py, libs/src/services/discoveryProvider/DiscoveryProvider.ts, libs/src/services/discoveryProvider/requests.ts
Updates the discovery endpoint /v1/full/playlists/top to accept an encoded user_id
Update the get_top_playlists query to not break on a none filter arg
Update the get_top_playlists query to accept a user_id param in the arg - falling back to the legacy fetching of user_id from x-user-id as an interim backup to not break existing clients
Updates libs binding for this endpoint to allow the user_id param
Ran libs linked locally and checked that the request was made with the correct parameter
=> Fix top playlists with user_id

comms/Makefile
This PR adds a simple load test using `hey` on the `/jobs` route. I image this won't become the idiomatic way of doing this in the future but perhaps this can become a seed for more tests.
Some other potential load testing tools
* ab (Apache Benchmark)
* Fortio (https://github.com/fortio/fortio)
Run `make test.load`
Output should look something like
```
hey -n 10000 -c 50 http://localhost:8926/storage/jobs
Summary:
Total:        0.1930 secs
Slowest:      0.0094 secs
Fastest:      0.0001 secs
Average:      0.0009 secs
Requests/sec: 51818.1588
Total data:   30000 bytes
Size/request: 3 bytes
Response time histogram:
0.000 [1]     |
0.001 [7261]  |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
0.002 [1664]  |■■■■■■■■■
0.003 [829]   |■■■■■
0.004 [156]   |■
0.005 [25]    |
0.006 [10]    |
0.007 [16] …
```
=> [CON-567] Add a simple load test

libs/src/sdk/api/generator/gen.js
Docker didn't have the correct location for the output of template generation. This fixes that.
Delete the `typescript-fetch` in the templates folder, run `node gen.js template typescript-fetch` and it should regenerate correctly now.
None.
=> NO-TICKET: fix link for template generation in SDK

docker-compose.test.yml
Uses a dummy container for solana tests so that up and test can be run simultaneously.
Below commands need to be tested again on MacOS and Linux
```
audius-compose test discovery-provider
```
NA
=> Use dummy container for solana tests

discovery-provider/es-indexer/src/indexNames.ts, discovery-provider/es-indexer/src/indexers/PlaylistIndexer.ts, discovery-provider/src/api/v1/playlists.py, discovery-provider/src/queries/get_top_playlists.py, discovery-provider/src/queries/get_top_playlists_es.py
Queries elasticsearch for top "mood" playlists and also "let them dj".
* `/v1/full/playlists/top?limit=16&mood=upbeat&type=playlist&with_users=true`
Function score might could use some tweaking.
To print out DSL:
```
print("playlist dsl", json.dumps(dsl))
```
=> Serve top playlists from ElasticSearch

discovery-provider/alembic/versions/988f095a1d43_add_is_repost_repost_column.py, discovery-provider/src/models/social/repost.py
Add is_repost_repost column to the reposts table. This will be used for generating is repost of a repost notifications.
one q - existing reposts get backfilled with false rather than null. i figure its better to avoid nulled values when possible but lmk if it's better leave existing reposts' is_repost_repost values with null.
Ran the migration locally and on a prod clone to ensure it ran smoothly
=> Add is_repost_repost column to reposts table

discovery-provider/src/utils/redis_cache.py
X-User-ID is not handled correctly in the cache decorator. This PR adds that to the qualifying criteria of `has_user_id`. There is also checks added so we don't write to the cache when a user id is provided because those will never be read.
Still getting my local env to correctly run tests, tune in later.
No logs or alerts. Cache should have less stored now because there was unnecessary records being put in there.
=> PLAT-618: fix cache decorator

discovery-provider/src/models/social/repost.py
Adding a note to the is_repost_repost column in the reposts table. Hopefully this clarifies the column - ik it isn't the best name but struggled to think of a better one. let me know if you have any suggestions for a different name or better clarification
=> add is_repost_repost comment for clarification

comms/storage/storageserver/storageserver.go
Staging is currently unable to start storage nodes because our config is all over the place with different env vars. This PR makes storage nodes attempt to first read stage/prod env vars for host and private key before falling back to local env vars. This is only a hotfix and will need more work to standardize and ensure that the list of all nodes is also being read instead of what's currently hardcoded.
Tested uploading locally to make sure replication still happens correctly. Will need to make sure this fixes staging as well.
Monitor stage startup.
=> Read private key and host from stage+prod env vars

discovery-provider/src/tasks/index.py, discovery-provider/src/tasks/index_nethermind.py
Reverting 1 block is now more common with 1 second block time. Reverting can take a while and block indexing for a minute so this change makes indexing trail 1 block behind latest to avoid reversions.
=> Index 1 block behind to avoid reverting

creator-node/src/serviceRegistry.js
Prepend https:// to creatorNodeEndpoint env var in case it's missing.
CI passes.
Monitor for `RecoverNodeL1Identity Error` logs.
=> Prepend https:// to creatorNodeEndpoint

libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts, libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts, libs/src/sdk/services/DiscoveryNodeSelector/constants.ts, libs/src/sdk/services/DiscoveryNodeSelector/types.ts, libs/src/sdk/utils/deepPartial.ts
Allows the SDK to have its configuration changed after initialization for a subset of the configuration properties. Useful for eg. setting the allow/blocklists via Optimizely asynchronously, allowing SDK to initialize synchronously with some async config later.
=> SDK: Allow updating DN selector config after initializing

.circleci/config.yml, libs/scripts/release.sh
Updates the CI job to allow the `npm version` parameters to be specified, namely the version and the `--preid` fields, so that we can publish betas etc.
=> SDK: Update CI to allow version, preid to be specified

libs/src/sdk/api/generated/default/models/User.ts, libs/src/sdk/api/generated/default/runtime.ts, libs/src/sdk/api/generated/full/models/UserFull.ts, libs/src/sdk/api/generated/full/runtime.ts, libs/src/sdk/api/generator/templates/typescript-fetch/runtime.mustache
Updates SDK to not `JSON.stringify` strings. Needed for `ChatsApi` to be able to `JSON.stringify` ahead of time and sign the exact payload.
=> SDK: Update template to allow raw string body

discovery-provider/plugins/notifications/src/__tests__/processEmailNotifications.test.ts, discovery-provider/plugins/notifications/src/email/notifications/index.ts, discovery-provider/plugins/notifications/src/utils/populateDB.ts, docker-compose.yml
For live frequency users:
- New DMs don’t trigger a live email, but get included in any other emails that would be scheduled to go out.
- If nothing scheduled to go out, send in daily email.
Also added test coverage for emailed app notifications.
=> Custom DM email notification frequency

discovery-provider/alembic/versions/64e82a907294_delete_plays_archive_table.py, discovery-provider/integration_tests/tasks/test_prune_plays.py, discovery-provider/src/tasks/prune_plays.py
Remove plays archiving and just delete old plays instead. 
Before, we would archive old plays in a separate table. Now that we're confident these old plays are no longer needed, we should just delete these plays to save disk.
Tests pass.
=> Delete old plays instead of archiving

.pre-commit-config.yaml, comms/discovery/rpcz/main_test.go
- Fixes failing `make test` in comms
- Bumps isort version to fix the following errors that prevented me from pushing this commit (more info [here](https://levelup.gitconnected.com/fix-runtimeerror-poetry-isort-5db7c67b60ff)):
```
~/workspace/audius-protocol/comms   theo-fix-disc-tests *19 !1 ❯ git commit -S -m "Fix comms discovery tests"
[INFO] Installing environment for https://github.com/pycqa/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/theo/.cache/pre-commit/repo0z66_cah/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
Processing /Users/theo/.cache/pre-commit/repo0z66_cah
Installing build dependencies: started
Installing build …
```
=> Fix comms discovery tests and bump isort

comms/Makefile, comms/discovery/config/config.go, comms/discovery/discovery_main.go, comms/discovery/em/cid.go, comms/discovery/rpcz/main_test.go, comms/discovery/server/main_test.go, comms/docker-compose.v2.base.yml, comms/docker-compose.v2.dev.yml, comms/docker-compose.v2.multi.yml, comms/docker-compose.yml, comms/natsd/config/config.go, comms/natsd/nats_main.go, comms/shared/config/config.go, comms/shared/peering/exchange_endpoint.go, comms/shared/peering/info_test.go, comms/shared/peering/nats_connection.go, comms/shared/peering/peering.go, comms/shared/peering/solicit.go, comms/shared/peering/sps.go, comms/shared/peering/sps_test.go, comms/storage/config/config.go, comms/storage/storage_main.go, comms/storage/storageserver/storageserver.go, comms/storage/storageserver/storageserver_test.go
Part 3 of comms/storage v2 config (this one is a large enough change and works - there will be a final part 4).
- Adds envconfig struct to discovery and natsd, and extracts duplicated key derivation to shared config
- Discovery's `config.Init()` now accepts a new `KeysConfig` struct that Discovery, Nats, and Storage all have as part of their own configs
- Adds default data to Docker .base file to reduce repetition in .dev and .multi files
- Changes peering to struct that takes top-level params to set up for future work to use more params instead of calling discovery config throughout
- Removes remaining usages of `audius_delegate_private_key` env var in favor of `AUDIUS_DELEGATE_PRIVATE_KEY`
- Nit: Makes env var comments uppercase since the envconfig package transforms everything to …
=> [CON-595] Improve comms/storage config (pt3)

comms/storage/storageserver/storageserver.go
This PR adds content-type checking on the storageserver
Tested locally by disabling content-type checking on the client and sending incorrect files to the server
=> [CON-572] add content-type checking in server

discovery-provider/alembic/trigger_sql/handle_reaction.sql, discovery-provider/alembic/trigger_sql/handle_supporter_rank_ups.sql, discovery-provider/alembic/trigger_sql/handle_track.sql, discovery-provider/alembic/trigger_sql/handle_user_balance_changes.sql, discovery-provider/alembic/trigger_sql/handle_user_tip.sql, discovery-provider/alembic/versions/0f75bcb73b0a_update_triggers_for_notifications.py, discovery-provider/integration_tests/notifications/test_reaction.py, discovery-provider/integration_tests/notifications/test_tier_change.py, discovery-provider/integration_tests/notifications/test_track.py, discovery-provider/integration_tests/notifications/test_user_tip.py, discovery-provider/integration_tests/queries/test_notifications/test_follow_notification.py, discovery-provider/integration_tests/queries/test_notifications/test_paginate_notification.py, discovery-provider/integration_tests/queries/test_notifications/test_remix_track_notification.py, discovery-provider/integration_tests/queries/test_notifications/test_user_tier_change_notification.py, discovery-provider/src/api/v1/models/notifications.py, discovery-provider/src/api/v1/utils/extend_notification.py, discovery-provider/src/queries/get_notifications.py, discovery-provider/src/tasks/index_trending.py, libs/src/api/Notifications.ts, libs/src/services/discoveryProvider/DiscoveryProvider.ts, libs/src/services/discoveryProvider/requests.ts
Fix the discover notifications endpoint
Adds mappings for all notifications to be formatted correctly
Reformats the base notification to add type
Fixes triggers:
* Create track group id is changes so that notifications rollup
* Added dethroned trigger
* fix user balance change notification for correct wei units
* Add extra metadata to tip notification
Added a migration to update these notification and delete all past notifications for these types
Adds libs binding to fetch notifications and add type per each notification
Ran against prod db snapshot and validated each one was sent correctly
=> Fix notifications endpoint

comms/discovery/db/queries/get_chats.go, comms/discovery/db/queries/get_summaries.go, comms/discovery/server/server_test.go
Don't return chats with no messages from the /chats endpoint (leave them for the /chats/<id> endpoint)
Updated server tests
=> Filter chats with no messages in /chats response

discovery-provider/alembic/trigger_sql/handle_repost.sql, discovery-provider/integration_tests/notifications/test_repost_repost.py, discovery-provider/integration_tests/queries/test_notifications/test_repost_repost_notifications.py, discovery-provider/src/queries/get_notifications.py
Didn't realize a valid types criteria was introduced for notifications, so added new repost of a repost notification back in to fix failing test
should fix failing discovery test
=> fix failing repost reposts test and specify repost type in trigger

discovery-provider/src/queries/get_health.py, discovery-provider/src/utils/web3_provider.py
Use local RPC in indexing instead of a gateway.
Ideally, nodes would use their own RPC but we need to make sure their RPC is synced up and on the correct network. Right now `/nethermind` is only available on some nodes so we can't use web3 externally but that should be ok as long as they can peer and sync. Those nodes will still be able to use their RPC internally. This change will confirm that. 
```
"chain_health": {
"block_number": 1114902,
"chain_id": 1056801,
"entries": {
"node-health": {
"data": {},
"description": "The node is now fully synced with a network. Peers: 3. The node stopped producing blocks.",
"duration": "00:00:00.0000302",
"status": "Unhealthy",
"tags": []
}
},
"hash": "0x1b1fc4aaf4b8446606a0fe0a286cb84d17f1428d1b4b0ef5371f3cbbd3cab660",
"status": "Unhealthy", …
```
=> Add network ID and latest block to chain health check

discovery-provider/alembic/versions/9b4e12c0c428_21523_track_cids.py
Fix migration - it errors bc it's comparing an int with a text
The fix is to cast the data_table track_id as an int 
Ran on prod and worked! This is a patch onto main
=> Cast text to int in track cids migration

comms/cmd/seed.go, comms/storage/storageserver/storageserver.go
Updates seed command to use new config since it's currently broken after merging https://github.com/AudiusProject/audius-protocol/pull/4810.
I ran `make` and `make storage.seed.image`, and then uploaded an audio file manually at http://node1-storage/storage and verified that data was where it was supposed to be.
N/A
=> Update storage seed cmd to use new config

comms/storage/storage_main.go, comms/storage/storageserver/storageserver.go, comms/storage/storageserver/storageserver_test.go
Passes `peering.Peering` pointer to storageserver lifetime struct so that the whole application can use peering code without re-initializing it and causing the nodes to do peering exchange again.
`make`, `make test`, and upload flow at http://node1-storage/storage
N/A
=> Keep peering pointer in lifetime struct

comms/docker-compose.v2.base.yml, comms/natsd/nats_manager.go
* only enables jetstream if `NATS_ENABLE_JETSTREAM=true`
* base docker config + staging have this set to true via https://github.com/AudiusProject/audius-docker-compose/pull/215
=> NATS_ENABLE_JETSTREAM flag

discovery-provider/src/queries/get_remixes_of.py
- Returned wrong signature for early exit of gated track remixes retrieval. This fixes it.
deployed change to stage dn5 and tested local dapp against it. it works!
none
=> Fix remixes failure for gated tracks

identity-service/src/routes/tiktok.js
We are getting some cryptic errors when hitting tiktok's `access_token` route and not returning the errors in a useful way. This makes sure we return the code and message
Tested locally, will test on stage
=> [C-2116] Return errors from tiktok access_token endpoint

identity-service/src/routes/tiktok.js
TikTok no longer allows this scope and it's breaking on staging
=> Remove unused TikTok share.sound.create scope

discovery-provider/src/app.py, discovery-provider/src/queries/get_health.py, discovery-provider/src/queries/notifications.py, discovery-provider/src/tasks/index.py, discovery-provider/src/tasks/index_nethermind.py, discovery-provider/src/tasks/index_trending.py, discovery-provider/src/utils/helpers.py, discovery-provider/src/utils/web3_provider.py
Final changes before ACDC migration
* Correct some differences in index.py and index_nethermind.py.
* Depend on identity for final_poa_block and switch to ACDC web3 provider when final_poa_block is indexed.
* Check for this final_poa_block throughout indexing to ensure we don't index past it. 
* Separate redis locks for index.py and index_nethermind.py.
Tested on sandbox nodes and migration worked in various situations:
* when indexing is caught up to POA. 
* when indexing is behind POA. 
confirmed final_poa_block is from POA and final_block_poa+1 is from ACDC.
=> ACDC migraiton: enable identity final_poa_block, improve web3 provider switch, indexing parity

.circleci/workflows/main.yml
Temporarily disabling auto deploy to stage discovery nodes while premium content is QA-ing this week.
=> disable auto deploy to stage discovery nodes

comms/storage/contentaccess/content_access_checker.go, comms/storage/contentaccess/content_access_checker_test.go, comms/storage/contentaccess/content_access_middleware.go, comms/storage/tests/content_access_middleware_test.go
This PR makes content access checking more in line with the current implementation used in production. Signatures are treated has hex encoded strings that're decoded when a request comes in. 
I looked at requests in staging 
e.g.
```
https://creatornode9.staging.audius.co/tracks/cidstream/QmfKLRvcq1hEXvX1vXKgPX9P58orVNg5YE9ioEhCPchwhp?signature=%7B%22data%22%3A%20%22%7B%5C%22trackId%5C%22%3A%2010753%2C%20%5C%22cid%5C%22%3A%20%5C%22QmfKLRvcq1hEXvX1vXKgPX9P58orVNg5YE9ioEhCPchwhp%5C%22%2C%20%5C%22timestamp%5C%22%3A%201677714403243%2C%20%5C%22shouldCache%5C%22%3A%201%7D%22%2C%20%22signature%22%3A%20%220xd3b08c5a0e116d1e76b886763d3d99c9f6c5288b389c908b70bd2cc2645b491d306ba1ce86a0fe863f2b28a8f6c98247bf7b40fec0e08d6e5cb1e48b8e7bb6c91c%22%7D
```
And made sure the middleware was able to parse and …
=> StorageV2: hex encode signature for content access middleware

comms/cmd/nodesToShards.go, comms/storage/client/client.go
Some instances of the /nodes-to-shards endpoint slipped through, so this renames them to /node-statuses.
`make`, `make test`, upload flow at http://node1-storage/storage
N/A
=> Rename leftover nodesToShards to nodeStatuses

comms/cmd/getFile.go, comms/cmd/job.go, comms/cmd/jobs.go, comms/cmd/nodesToShards.go, comms/cmd/results.go
Yesterday some PRs got merged in a weird order so logs didn't get silenced on the new cli cmds. This PR is just a follow up for completeness
Ran the cli cmds locally to make sure logs were actually silenced
=> [CON-625] Silence app logs for new cli cmds

discovery-provider/plugins/notifications/src/__tests__/processEmailNotifications.test.ts, discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts
Some dm tests were failing sometimes... increate timeout between startup and adding/testing for messages in case this is because of timing.
Ran tests 3+ times. No errors
=> Fix flaky dm notifs tests

creator-node/src/services/ContentNodeInfoManager.ts
Fixes Content Node's function that gets a user's replica set by wallet. It used an outdated replica set for users who had previous replica set updates because it assumed sorting in descending order instead of ascending order. I spot checked some users to confirm that the result is sorted in ascending and double-checked discovery code [here](https://github.com/AudiusProject/audius-protocol/blob/main/discovery-provider/src/queries/get_users.py#L48) as well.
Try to perform orphaned data recovery manually in prod after this is deployed:
```
POST https://creatornode.audius.prod-us-west-2.staked.cloud/merge_primary_and_secondary?wallet=0xb35bbd6fba0521c4558f9a3040b0e43b70724a76&endpoint=https://audius-content-1.decentralizeaudio.xyz&forceWipe=true&syncEvenIfDisabled=true
```
Logs for …
=> Use last index instead of 0th for CN getUsers

discovery-provider/src/app.py, discovery-provider/src/utils/helpers.py
Fixes celery_app startup on indexer restart. Before, indexing would halt when the container restarts because it would fail to remove a file.
```
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/audius-discovery-provider/src/worker.py", line 4, in <module>
from src.app import create_celery
File "/audius-discovery-provider/src/app.py", line 26, in <module>
from src.queries import (
File "/audius-discovery-provider/src/queries/prometheus_metrics_exporter.py", line 28, in <module>
remove(f)
FileNotFoundError: [Errno 2] No such file or directory: '//prometheus_data/gauge_all_server_89706.db'
```
Probably because of multiple processes trying to remove the same file? Sometimes indexing …
=> Is fix worker 2

.circleci/workflows/main.yml
Deploys to Prod UM first instead of CN4
NA
NA
=> Remove prod cn4 from deploy pipeline

discovery-provider/src/api/v1/helpers.py, discovery-provider/src/api/v1/tracks.py, discovery-provider/src/queries/get_random_tracks.py, libs/src/sdk/api/generated/full/apis/TracksApi.ts
- Return random tracks from users with at least `min_followers` followers.
Some fixes for existing bugs:
- Use restx's inputs.boolean type for with_users query param because bool doesn't actually work as expected... it parses any input as truthy, even with_users=False. inputs.boolean works correctly. See https://github.com/noirbizarre/flask-restplus/issues/199.
- /tracks/feeling_lucky with no with_users query param was returning a 500 because tracks["user"] from querying Tracks and populating track metadata is a list with 1 element (the track owner). Not sure why. In other places in the code we just do tracks["user"][0] so did that here as well.
Query /tracks/feeling_lucky. Play w query params and make sure responses are correct.
=> Add min followers to feeling lucky query

discovery-provider/src/api/v1/notifications.py, libs/src/api/Notifications.ts, libs/src/services/discoveryProvider/DiscoveryProvider.ts, libs/src/services/discoveryProvider/requests.ts
Fixes discovery-provider get-notifications endpoint to pass through valid_types arg.
Fixes libs getUserNotifications method to also pass through this arg.
Used cloned stage database, found which users have repost_of_repost notifications, and hit this endpoint http://audius-protocol-discovery-provider-1:5000/v1/full/notifications/5epYn?valid_types=repost_of_repost&valid_types=save_of_repost to confirm we get them back.
Still need to test libs e2e, so may reach out on how best to do that
=> [C-2268] Add missing valid_types params to get-notifications endpoint

docker-compose.test.yml
docker requires a second "$" when running scripts because of the way its parser works, this was missing on the echo
ran `audius-compose test run "identity-service"` locally successfully
None
=> double money for docker

comms/discovery/rpcz/apply.go
Postgres timestamps' max precision is microseconds but we format to nanoseconds in comms. Round on read (when not reading from postgres) to avoid issues. Writes and subsequent reads of timestamps from postgres are fine since postgres automatically rounds on write.
Tests will be fixed by https://github.com/AudiusProject/audius-protocol/commit/8a2762a42a96648243c219331b562cb2d3eaeff1
=> Comms: round timestamps to microseconds on read

discovery-provider/src/app.py
I assumed this change had made it to the release but it didn't. Ray merged my PR while I was away https://github.com/AudiusProject/audius-protocol/pull/4879
and it was missing this import removal which is the actual problem. I'm not sure if it'll fix all cases but I've observed a few situations where the indexer restarts but celery is not able to be configured because of this error in app.py
This change is already on main from another PR thanks to linting from this PR https://github.com/AudiusProject/audius-protocol/pull/4872
=> Fix celery worker startup by removing prometheus

discovery-provider/src/api/v1/notifications.py
Removes default timestamp of current datetime bc it gets compared to another datetime.now() which is invalid
Has not been tested, but sure it works
=> Fix discovery notifications endpoint for unread

identity-service/src/relay/txRelay.js
sometimes the identity is the sender for relays and ID is not a user, this sets it as "unknown" for now
=> handle nonexistent user in relay

comms/discovery/discovery_main.go, comms/discovery/server/server.go, comms/go.mod, comms/go.sum
With the [unfurlist](https://pkg.go.dev/github.com/Doist/unfurlist) package. Configured with `WithBlocklistPrefixes` to skip unfurling any urls matching any internal resource IP prefixes (see the security [warning](https://pkg.go.dev/github.com/Doist/unfurlist#hdr-Security)).
`http://localhost:8926/comms/unfurl?content=Check+this+out+https://www.youtube.com/watch?v=dQw4w9WgXcQ`
`http://localhost:8926/comms/unfurl?content=Check+this+http://localhost:8925/comms`,
`http://localhost:8926/comms/unfurl?content=http://localhost:8925/comms`, etc. => do not reveal any info (has `"url_type": "website"` for valid internal URLs without the blocklist prefixes configured)
=> Comms: unfurl urls server-side

creator-node/Dockerfile, creator-node/package-lock.json, creator-node/package.json, creator-node/patches/ts-node-dev+2.0.0.patch, creator-node/scripts/start.sh, dev-tools/setup-dev.sh, identity-service/Dockerfile, identity-service/package-lock.json, identity-service/package.json, identity-service/patches/ts-node-dev+2.0.0.patch, identity-service/scripts/dev-server.sh, identity-service/src/index.ts
* Update `identity-service` and `creator-node` to use `ts-node-dev` instead of `nodemon` for dev. This has a few benefits
* Reloads are much faster. 5 - 10 seconds instead of 1 - 2 minutes
* Only required files are watched
This does not address the cold start times, which are still pretty brutal. Looking at that next
Ran into an issue where the node process simply wouldn't stop when `ts-node-dev` sent it a `SIGTERM` (to restart on changes). Even manually doing `kill -15 <pid>` didn't end the process
This happened specifically when libs was linked and caused a reload during the initial compilation.
I tried everything to fix it and spent way too much time on it.  Eventually went with the brute force method and patched `ts-node-dev` to send a `SIGKILL` instead. This works but means that we …
=> Improve identity and CN dev reload times

libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts, libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts
If we reselect after failing a request, automatically retry the request (once!) with the new discovery node.
Added test to make sure we retry the request
=> SDK: Retry once with new selections on failed requests

discovery-provider/integration_tests/queries/test_get_user_listening_history.py, discovery-provider/integration_tests/tasks/test_index_user_listening_history.py, discovery-provider/src/queries/get_user_listening_history.py, discovery-provider/src/queries/query_helpers.py, discovery-provider/src/tasks/user_listening_history/index_user_listening_history.py, discovery-provider/src/tasks/user_listening_history/listen_history.py
Apologies in advance :') there's a couple changes in here:
1. refactored index_user_listening_history by renaming some things and extracting parts out into functions
2. added ability to count play counts going forward in user listening history entries. this will not backfill for past entries in the column, but anything newly indexed will begin counting. if there is no play count available in an entry, a default of 1 is assumed
3. updated the get_user_listen_history endpoint to handle a new sorting method of most_listens_by_user. rn there is a sorter by plays but its by all plays of the track not by the tracks the logged in user specifically listened to. 
this is all so that we can fix the heavy rotation playlist and move that endpoint from identity into discovery. once this is in prod, we …
=> Add play count to user listening history and allow sorting by play count

comms/discovery/db/migrations/20230315135942_rpc_id.sql, comms/discovery/rpcz/apply.go, comms/discovery/rpcz/chat.go
Adds a new `rpc_log.id` column which is `timestamp + md5(rpc)`.
This way we don't depend on `jetstream_sequence` to be unique and we are unaffected if jetstream is recreated.
We don't actually use `jetstream_sequence` for ordering anywhere, so this should be safe.
=> rpc id is the timestamp + md5(rpc)

discovery-provider/src/queries/notifications.py
The adjustment of the blocknumber was in a loop for acdc which it should not have been 
It led to subtracting too the adjustment amount several times and ultimately this error preventing identity notifications from indexing 
```
ValueError: Value did not match any of the recognized block identifiers: -31375545", "timestamp": "2023-03-16 02:07:04,107", "pathname": "/audius-discovery-provider/src/app.py", "funcName": "handle_exception", "lineno": 190, "service": "server", "otelSpanID": "65baf8030cfff15e", "otelTraceID": "999301702e6a281580c1b3d84c8110d6", "otelServiceName": "discovery-provider"}
```
=> Fix loop of block number adjustment

discovery-provider/plugins/notifications/src/logger.ts
Silences a bunch of redundant-seeming logs when running notification tests. Curious what your thoughts are
=> Silence logs when running notification tests

discovery-provider/src/tasks/entity_manager/social_features.py
Was incorrectly failing EM validations on follow in a specific edge case because of the recent subscriptions backfill. 
For some reason on 1/31/23 in stage when my user unfollowed another user, the corresponding subscriptions row in identity wasn't removed (this is the legacy code path). Then recently I backfilled the subscriptions table in discovery with the subscriptions table in identity as a source of truth. This caused a duplicate create validation error in EM because it was validating both the subscribe and follow records in order for the follow action to succeed. The information in the db for the current follow record was correct - it was an unfollow with `is_delete=True` so EM should have processed the follow event. However, the current subscriptions record was `is_delete=False` …
=> Fix duplicate create EM validation failure on follow 

comms/discovery/db/migrations/20230316193251_pubkey_table.sql, comms/discovery/discovery_main.go, comms/discovery/pubkeystore/backfill.go, comms/discovery/pubkeystore/recover.go, comms/discovery/pubkeystore/recover_test.go, comms/discovery/rpcz/apply.go, comms/discovery/rpcz/websocket.go, comms/discovery/server/server.go, discovery-provider/nginx_conf/nginx.conf
* User can have multiple websocket connections to avoid client reconnect loops
* Sends ws event back to user who performed the action
* User pubkeys stored in postgres.  Code to backfill table when server starts.
=> DMs: Allow multiple websocket connections, backfill pubkeys

identity-service/src/notifications/index.js
Remove unnecessary wait between processing runs of notification in identity service
None
=> Remove wait in identity notifications

discovery-provider/integration_tests/queries/test_notifications/test_get_unread_notification_count.py, discovery-provider/src/api/v1/notifications.py, discovery-provider/src/queries/get_notifications.py
Fixes unread count in the /v1 notifications endpoint
* Adds the valid types param
* Removes timestamp bc we are backfilling
=> Fix unread count

discovery-provider/integration_tests/tasks/test_index_trending_underground_notification.py, discovery-provider/integration_tests/utils.py, discovery-provider/src/api/v1/utils/extend_notification.py, discovery-provider/src/queries/get_notifications.py, discovery-provider/src/queries/get_underground_trending.py, discovery-provider/src/tasks/index_trending.py
- Adds underground-trending notification indexing
- Adds tests
- Updates test-data to reduce warnings
> Note the test is mostly ripped from the index_notifications test, but it could use a bit of work as far as cleanliness. if folks have thoughts im down to update, but also would want to update the trending test too.
After implementing the feature, there are lots of opportunity for code-sharing and cleanup. I can potentially do that as part of this pr, or in a follow-up
Also, it would be good for us to decide on "trending_underground" or "underground_trending" for the notification type before a merge. Both types of naming appear in various places
=> [PLAT-694] Add underground-trending notification indexing

libs/package-lock.json, libs/package.json, libs/src/sdk/api/chats/ChatsApi.ts, libs/src/sdk/api/chats/clientTypes.ts
- Catch errors when decrypting and gracefully exit
- Allow consumers to specify chat message IDs so that they can optimistically update their UIs.
- Not in love with this.. would much prefer the SDK be in charge of how these IDs get generated. However, I'm not sure what a better solution is?
- Use ulid instead of cuid 
Tested by linking libs to a Client PR and throwing fake errors in the decrypt method
=> [PAY-951] SDK: Allow chat messages to have externally specified IDs, gracefully fail decryption

discovery-provider/src/queries/get_unclaimed_id.py
On rare occasions a few users have encounter `No unclaimed track IDs` meaning discovery has tried 10 random IDs and they were all claimed. For now, we can extend this retry.
=> More retries for unclaimed ID

.circleci/workflows/main.yml
See title
Removing stage DP4 from autodeploy and moving to autoupgrade flow
NA
NA
=> Remove prod dp4 from auto deploy

dev-tools/README.md, dev-tools/audius-compose
Removes logic that auto-updates /etc/hosts and instead adds a README instruction to do it once manually.
Make sure audius-compose comes up.
N/A - dev facing
=> Change /etc/hosts update from auto to manual

dev-tools/README.md, dev-tools/audius-compose
Makes `audius-compose connect` update /etc/hosts if it's not already up to date.
Reset my /etc/hosts permissions to be only writeable by root, and ran `audius-compose connect` twice (confirms the update path and the already-exists path).
N/A
=> Update /etc/hosts via audius-compose connect

libs/src/services/discoveryProvider/requests.ts
Uploading multiple tracks would fail because unclaimed ID was being cached on safari. This seems to be the only sure way to get around that.
Uploading a playlist with safari. Confirmed query param used random strings.
=> Fix unclaimed ID caching for safari

creator-node/src/routes/tracks.js, creator-node/src/utils/requestRange.ts
Adds a check on the range header of a request to ensure that we're only tracking listen counts once per byte range request.
Tested on stage cn10
```
curl --header "range: bytes=0-" https://creatornode10.staging.audius.co/tracks/cidstream/QmYvyBQJVpfoLZ6x6LXt7AG3GdZEjJW4KV7F3Fr3YkoMyD\?signature\=%7B%22data%22%3A%20%22%7B%5C%22trackId%5C%22%3A%20439060106%2C%20%5C%22cid%5C%22%3A%20%5C%22QmYvyBQJVpfoLZ6x6LXt7AG3GdZEjJW4KV7F3Fr3YkoMyD%5C%22%2C%20%5C%22timestamp%5C%22%3A%201679963665330%2C%20%5C%22shouldCache%5C%22%3A%201%7D%22%2C%20%22signature%22%3A%20%220xdc33bc35ae3cc8250d2c187873131973e7bfcad33f7ea0947e35713ed7b04ee57db94a9f5cd61c1660091148d5297e045174d790a26bc2e237fb80f9608fd8071c%22%7D
```
> records listen
```
curl https://creatornode10.staging.audius.co/tracks/cidstream/QmYvyBQJVpfoLZ6 …
```
=> Dedupe byte range requests

dev-tools/audius-compose, dev-tools/commands/src/utils.mjs, docker-compose.storagev2.yml, docker-compose.yml, libs/initScripts/local.js, libs/package-lock.json, libs/src/api/Track.ts, libs/src/services/creatorNode/CreatorNode.ts, nginx_ingress.conf
- Adds mediorum containers to protocol repo, gated by --storagev2 flag in `audius-compose up`
- Adds local /mediorum endpoint to match what's on staging and prod
- Adds v2 track upload skeleton to libs (will be moved to SDK later), pointed to the /mediorum endpoint
Caveat: Mediorum currently only supports dev (hardcoded to localhost) or stage/prod, so I need to sync with @stereosteve to see if we should allow the host to be configurable for dev or if it makes sense to set the env var to stage locally since it's pretty similar.
- Make sure the AudiusProject/mediorum repo is cloned at the same level as audius-protocol and audius-client
- Start local stack: `audius-compose up -e 1 --no-libs --no-solana --storagev2` in audius-protocol. `npm run sdk:link` and `npm run web:dev` in audius-client …
=> Use mediorum for storage v2 track upload

comms/discovery/db/queries/get_chat_blocked_users.go, comms/discovery/server/server.go, comms/discovery/server/server_test.go, comms/shared/utils/utils.go
- GET /comms/chats/blockees
- GET /comms/chats/blockers
- Remove /comms/chats/validate-can-chat
- GET /comms/chats/permissions:
- Returns permissions and whether the current user has permission to message each user in the `users` query param. The `current_user_has_permission` field is always true if the user == the current user.
- Usage: send users `/comms/chats/permissions?timestamp=%d&users=%s&users=%s` to query for an array of 2 users
- Response: 
```
{
"data": {
"YYk8w9k": {
"permits": "tippers",
"current_user_has_permission": false
},
"y8d8Ax7": {
"permits": "followees",
"current_user_has_permission": true
}
},
"health": {
"is_healthy": true
}
}
```
server tests
=> Refactor permissions and blocks endpoints

libs/src/services/discoveryProvider/DiscoveryProvider.ts
Fixes issue where fetch response is not parsed
=> Fix discover-node-selector response

libs/src/api/Track.ts, libs/src/api/Users.test.js, libs/src/services/creatorNode/CreatorNode.ts, libs/src/services/dataContracts/AudiusContracts.ts, libs/src/services/discoveryProvider/DiscoveryProvider.ts, libs/src/utils/fileHasher.ts
- Fixes issue where sdk discovery-node-selector was not calling the selection-callback, leading to issue where libs caller using new discovery-node-selector wasn't aware a discovery node was selected.
- Also fixes issue where blocknumber check was not being respected in new _makeRequestInternal
- Fixes lint, we should prob add a ci step for it
=> Add selectionCallback to sdk discovery-node-selector

discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py, discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py, discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py, discovery-provider/integration_tests/tasks/test_index_helper.py, discovery-provider/src/tasks/entity_manager/entity_manager.py, discovery-provider/src/tasks/entity_manager/utils.py, discovery-provider/src/tasks/index.py, discovery-provider/src/tasks/index_nethermind.py, discovery-provider/src/utils/cid_metadata_client.py, identity-service/src/relay/txRelay.js, libs/src/api/Track.ts, libs/src/services/dataContracts/EntityManagerClient.ts
Index metadata from chain via `manageEntity`. Indexer can handle both legacy CID requests and requests with actual metadata.
Still need the CID along with the metadata, so format the `metadata` field in `manageEntity` like this: (JSON stringified)
```
{
"cid": <cid>,
"data": <normal metadata blob>
}
```
The `manageEntity` `entityType` and `action` params remain the same.
Also edit `txRelay` in identity to insert a hash of the nonce + sig in the ABI to the `Transactions` table rather than the entire encoded ABI. For large blobs the encoded ABI is too large to fit in a postgres pkey col, and what really makes it unique is just the nonce and sig anyway. The `Transactions` table is used to avoid re-sending txs we've already sent.
Python integration tests; will deploy to stage and test further …
=> Send metadata blobs through chain

creator-node/src/middlewares/readOnly/readOnlyMiddleware.ts
Allows health check when in read only/no SP id mode (prior to registration).
This unblocks registration from happening, which runs a health check on the service beforehand.
`audius-compose up` without content node registration should still yield healthy nodes -- difficulty testing this.
=> Allow health check when no sp id

creator-node/nginx_conf/nginx.conf
- Removes unused Content Node nginx blocks for /nats and /storage
- Removes Content Node cache for /health_check route
=> Clean up CN nginx and don't serve stale /health_check

identity-service/src/notifications/processNotifications/createNotification.js
Fixes a bug in track create notifications.
Before, if you're subscribed to a user and you have viewed track create notifications from them before and then they upload new tracks, it would add the new notification actions to ALL existing notifications from that user. So the new upload would actually add a track creation to existing track creation notifications.  
Instead, the correct behavior is to add new actions only to the existing unread notification.  
Tested on stage. Uploaded multiple tracks and single tracks. Verified notifications are as expected.
=> Fix duplicate track create notifications

discovery-provider/src/api/v1/tracks.py, discovery-provider/src/queries/get_track_stream_signature.py
Remove CN track id stream redirect. Also include filename query param in case the user is wanting to download the track. Related to https://github.com/AudiusProject/audius-client/pull/3202 and helps us towards deperecating all non-cid DN + CN stream paths.
Deployed to stage DN and tested local web app against it.
=> [PAY-827][PAY-1115] Always use cid streaming and include filename in redirect if exists

discovery-provider/alembic/trigger_sql/ddl.sql, discovery-provider/alembic/trigger_sql/handle_supporter_rank_ups.sql, discovery-provider/integration_tests/notifications/test_supporter_rank_ups.py, discovery-provider/plugins/notifications/src/__tests__/processEmailNotifications.test.ts, discovery-provider/src/models/notifications/notification.py
Swap supporter and supporting rank up notifications via migration. Added another column type_v2, which we use to determine whether a notification needs to be swapped. if type_v2 is null for a supporter or supporting rank up notification, that means the notif was created before this migration, and we want to swap their types and group id.
perhaps further down the line we'll want to delete this migration from the ddl and drop the column so we don't have this extra column that is confusing
updated integration tests
made a prod clone and ran the migration on the clone, added extra rows after the migration ran, re-ran the migration and made sure it didn't update any new supporting/er_rank_up rows
=> [PLAT-868]: Swap supporter rank up vs supporting rank up notifications in trigger

discovery-provider/plugins/notifications/src/sns.ts
Android push notifs were broken because the message structure was wrong. It should be stringified twice like it is for iOS.
Running on prod.
=> Fix android push notif message struct

discovery-provider/alembic/trigger_sql/ddl.sql
Makes notifications supporter/supporting migration have a temp step to avoid UniqueViolation errors. Previous error:
```
audius_discovery-# set type = 'supporter_rank_up', type_v2 = 'supporter_rank_up', group_id = 'supporter_rank_up' || substring(group_id from position(':' in group_id))
audius_discovery-# where type = 'supporting_rank_up' and type_v2 is null;
ERROR:  duplicate key value violates unique constraint "uq_notification"
DETAIL:  Key (group_id, specifier)=(supporter_rank_up:1:slot:185411112, 13) already exists.
```
=> Make notif migration use temp step

discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py, discovery-provider/src/tasks/entity_manager/track.py, discovery-provider/src/tasks/index.py, discovery-provider/src/tasks/index_nethermind.py
Represents whether the track was uploaded as part of a playlist or album so we can create the correct notification. Entity manager wasn't persisting the value correctly.
Tested on stage. Value in db is true for album and playlist tracks, false for standalone.
=> Set is_playlist_upload correctly in EM

discovery-provider/src/queries/get_undisbursed_challenges.py
Stopping creating Userbanks at the time of account creation inadvertently breaks the `undisbursed_challenges` endpoint, which assumes a userbank for every user. The fix is to simply remove this join.
Have not tested this yet. Need to test on stage & do another pass on the DN codebase and see if there are any other sneaky places we assume userbanks exists.
=> Remove join on userbank in undisbursed challenges endpoint

discovery-provider/alembic/trigger_sql/ddl.sql, discovery-provider/integration_tests/tasks/test_update_user_is_available.py, discovery-provider/integration_tests/utils.py, discovery-provider/src/tasks/update_user_is_available.py
Adds index for unavailable users, pulls users in with unavailability and switches them if they're not entirely in the delist working set.
Unit
=> [CON-642] Reindex unavailable users

mediorum/Makefile, mediorum/bash_scripts/deploy.sh, mediorum/bash_scripts/deploy_mediorum.sh, mediorum/bash_scripts/nodes.sh, mediorum/server/beam_client.go, mediorum/server/server.go
* Enables pg_beam for all environments other than prod on 10m interval. 
* Makes `bash_scripts` a bit safer.
Hope to have a better pg_beam tomorrow.
Along with this change makes it so that staging can stay mediorum-frist without branch stuff.
https://github.com/AudiusProject/audius-docker-compose/commit/a9382cc6b7a5ba05489e3dfb622167f8b97d7f24
=> Enable mediorum-first on staging.

libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts, libs/src/sdk/services/DiscoveryNodeSelector/constants.ts, libs/src/sdk/services/DiscoveryNodeSelector/types.ts
SDK-side counterpart to https://github.com/AudiusProject/audius-client/pull/3246. Makes it so the SDK respects DN override set from the client.
Tested on local web + linked libs. Confirmed setting/unsetting DN override works by inspecting comms requests.
=> [PAY-1166] Make SDK respect DN override (sdk-side)

discovery-provider/default_config.ini, discovery-provider/integration_tests/tasks/test_backfill_cid_data.py, discovery-provider/integration_tests/tasks/test_index_helper.py, discovery-provider/src/app.py, discovery-provider/src/queries/get_health.py, discovery-provider/src/tasks/backfill_cid_data.py, discovery-provider/src/tasks/entity_manager/entity_manager.py, discovery-provider/src/tasks/entity_manager/utils.py, discovery-provider/src/tasks/index.py, discovery-provider/src/tasks/index_nethermind.py
- shared_config was not pulling in stage.env vars as expected when testing on stage -- changed to use os.getenv
- cache key in redis to ensure backfill only runs once. expose key in DN /health_check
- Validate metadata structure in tx's if passed in directly. Don't add to the cid_metadata map in the indexer upon validation failure. Downstream, the entity manager will swallow any ensuing errors caused by not finding a metadata entry and skip the tx. cc @theoilie 
Updated integration tests.
Deployed to stage and made sure backfill ran successfully by comparing the before/after record count of cid_data 
Made sure backfilled_cid_data value was in health check and  was set after backfill completion
Restarted indexer, made sure backfill did not run again
=> Stage cid metadata backfill url, validate cid metadata structure in EM txs

discovery-provider/integration_tests/tasks/entity_manager/test_index_create_notification.py, discovery-provider/src/tasks/entity_manager/notification.py
If we send announcements this can cause a very expensive operation to be run on discprov. Since it goes through entity manager it can crash all nodes. This removes it entirely as the plugin will paginate through users on it's own instead.
Running on stage
=> PLAT-725: remove very expensive query

libs/src/api/Rewards.ts, libs/src/services/discoveryProvider/DiscoveryProvider.ts, libs/src/services/solana/rewardsAttester.ts
I want to rip out / rewrite this auto-attesting code... but in the mean time, we need trending to work with lazy-userbanks. So that's this PR.
Other things:
- Fixes a lot of types. Properly types libs in the attester.
Testing on stage identity.
=> Create userbanks lazily in Identity Auto-Attester

identity-service/src/models/userNotificationBrowserSettings.js, identity-service/src/models/userNotificationMobileSettings.js, identity-service/src/routes/push_notifications.js
This POST endpoint was changed a few months ago while trying to hotfix during a flare... but the sequelize syntax was wrong so this has been broken for a few months now, meaning users currently aren't able to toggle specific notification types on/off and have their change persist. (But disabling the top-level notification control still works without this change because that value isn't persisted and is instead handled in the client.)
Deployed and tested on stage
=> Fix mobile notification settings endpoints

libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts, libs/src/sdk/services/DiscoveryNodeSelector/constants.ts, libs/src/sdk/services/DiscoveryNodeSelector/types.ts
This reverts commit 65e2b2662d3c618ef6b2d1e064fc328ea5e55060.
Turns out there was already a way to configure an `initialSelectedNode` in the sdk so these changes were unnecessary.
Tested on local web stage with linked libs.
=> Revert "[PAY-1166] Make SDK respect DN override (sdk-side) (#5124)"

mediorum/Makefile, mediorum/crudr/client.go, mediorum/crudr/crudr.go, mediorum/ddl/cid_lookup.sql, mediorum/ddl/ddl.go, mediorum/ddl/files_trigger.sql, mediorum/ddl/test/cid_lookup_test.sql, mediorum/ddl/test/files_trigger_test.sql, mediorum/go.mod, mediorum/go.sum, mediorum/main.go, mediorum/server/cid_log_client.go, mediorum/server/cid_log_server.go, mediorum/server/cid_log_test.go, mediorum/server/db.go, mediorum/server/repair.go, mediorum/server/replicate.go, mediorum/server/server.go, mediorum/server/test_main_test.go, mediorum/server/transcode.go
* Adds trigger to Files table so we can track CID additions + deletes.
* Consumers have a cursor for polling each peer
* Polls on a 20 - 40 second interval, takes ~1s per poll on staging.
TODO:
=> Better v0 CID sync

discovery-provider/integration_tests/queries/test_get_tips.py, discovery-provider/src/api/v1/tips.py, discovery-provider/src/queries/get_tips.py
This PR updates the `get_tips` query to support filtering out a list of recipient ids and adds a constant list of excluded recipients to the `tips` api (currently containing only the Audius account).
Also added a test file to verify the new behavior and updated the return type of `get_tips()`, since the resulting list has a `User` object in the `sender` and `receiver` fields (not just a user_id).
I'm definitely open to suggestions on better ways to do this. At this point, the plumbing is almost there to allow a list of exclusions through query parameters. But I think we wanted the API to just filter out accounts by default instead of requiring clients to do it.
* Added `integration_tests/queries/test_get_tips.py`, contains one test to verify the with/without behavior of the new filter …
=> [PAY-1120] Filter tips to Audius account from the /tips API

discovery-provider/src/api/v1/tips.py
Follow-up from #5156 . I forgot to add the recipient list to the `full` version of the API. So it wouldn't have the intended effect in the client.
=> [PAY-1120] Apply recipient filtering to full tips api

discovery-provider/plugins/notifications/src/processNotifications/mappers/userNotificationSettings.ts
switches defaults to false for both mobile and browsers settings if not found
N/A
=> Notifs plugin: reasonable defaults

mediorum/crudr/client.go, mediorum/main.go, mediorum/server/db.go, mediorum/server/helpers.go, mediorum/server/serve_blob.go, mediorum/server/serve_legacy.go, mediorum/server/serve_status.go, mediorum/server/server.go, mediorum/server/uis/upload.html, mediorum/server/version.go
Adds a middleware function to `cidstream` route to enforce signatures.
This is fine for now... at some future point we'll want to prevent accessing an mp3 via `/ipfs/` or `/content/` routes.
I think an okay solution would be to look at the mimetype + route and not stream result if mimetype = mp3 and route = ipfs or content...  This would work for both v0 and v1 CIDs without requiring extra lookups and whatnot.
=> [CON-661] mediorum enforces signature on cidstream endpoint

discovery-provider/alembic/trigger_sql/ddl.sql, discovery-provider/es-indexer/src/indexers/TrackIndexer.ts, discovery-provider/integration_tests/tasks/test_index_helper.py, discovery-provider/src/api/v1/helpers.py, discovery-provider/src/models/tracks/track.py, discovery-provider/src/schemas/track_schema.json, discovery-provider/src/tasks/entity_manager/track.py, discovery-provider/src/tasks/metadata.py, libs/src/sdk/services/StorageService/StorageService.ts, libs/src/services/creatorNode/CreatorNode.ts
Makes v2 uploads compute track duration and set it in the track's metadata as `duration`. Legacy uploads instead compute the duration of each track segment in `track_segments`, which clients later sum.
Note that this stores duration as a truncated integer (number of seconds), which I think is a fair tradeoff (ignoring milliseconds, that is). Please comment if you disagree.
- Confirmed that existing tracks have "duration" set from the DN `extend_track` function, but they don't set "length" (which is good because that's a hard name to search for in a JS/TS codebase…). See prod track metadata for example: https://discoveryprovider2.audius.co/v1/full/users/handle/micahofficially/tracks
- Verified that "duration" is now set properly for v2 uploads locally and displays correctly on the track …
=> [CON-660] Set duration metadata property on v2 track uploads

discovery-provider/src/queries/get_related_artists.py, mediorum/server/serve_blob.go, mediorum/server/serve_upload.go, mediorum/server/server.go
Makes mediorum more closely resemble the NodeJS server when streaming tracks via `/tracks/cidstream/:CID` and when downloading images via `/ipfs/:dirCID/:size`
- Seeking now works on mediorum-only uploads (`make pg.bounce && make dev`) and full stack via the Audius web client
- Downloading an image from the /ipfs route with the `filename` queryparam makes the file download with specified name, just like in the existing Content Node. Example: http://localhost:1991/ipfs/23G5DCBU6YD4INJ6BLAHSD2LZGRLSG35/1000x1000.jpg?filename=nameOfDownload.jpg
As we rollout to staging, we should be able to seek during track playback, and requests should return 206 instead of 200
=> [CON-671] Add mediorum track streaming byte ranges and filename downloads

discovery-provider/src/queries/queries.py
v1/users already does this. Don't show anyone's playlist libraries except your own.
=> Validate to show playlist library in non-v1 /users endpoint

discovery-provider/src/app.py, discovery-provider/src/tasks/update_track_is_available.py, discovery-provider/src/tasks/update_user_is_available.py
Lower check to 10 min. This will make life much easier in terms of reasoning about availability state in UI vs. in content nodes.
Increase lock timeout so that we don't end up with overlapping jobs.
Existing requests to blacklist/track and blacklist/users are quite fast (sub-second). Even across all 60+ nodes, it is still very fast.
n/a
=> Lower interval to 10min for availability checks

libs/src/sdk/api/chats/ChatsApi.ts
Add an error message when `userIds` is not included in query params for permissions endpoint.
=> Better error message for getPermissions endpoint

libs/src/api/Track.ts
- Makes track update/edit work for tracks uploaded via storage v2 flow - doesn't write metadata to CN
- Makes track upload use CID of metadata instead of CID of track
Edit a track - separately for hidden->public, name, and cover art
Only affects v2 tracks, so ensure track edit works on staging after these code changes are released in libs
=> [CON-674] Make track edit work for storage v2

creator-node/sequelize/migrations/20181122035259-create-file.js, creator-node/sequelize/migrations/20190711143402-add_uuid_to_users.js, creator-node/sequelize/migrations/20200623002237-add-parent-file-data.js, creator-node/sequelize/migrations/20200918150546-add-clock.js, dev-tools/audius-compose, discovery-provider/src/api/v1/helpers.py, libs/src/api/Track.ts, libs/src/sdk/services/StorageService/StorageService.ts, libs/src/services/creatorNode/CreatorNode.ts, mediorum/.initdb/init.sql, mediorum/cmd/loadtest/client.go, mediorum/cmd/loadtest/metrics.go, mediorum/cmd/loadtest/report.go, mediorum/cmd/loadtest/upload.go, mediorum/ddl/cid_lookup.sql, mediorum/server/server.go, monitoring/healthz/src/Mediorum.tsx
- Gives mediorum a create-if-not-exists query for the Files table so storage v2 can start up via audius-compose without CNs
- Changes CN migrations to have if-not-exists for various Files table alterations so storage v2 can start up _with_ CNs (CN fails on migrations without these changes)
- Note that this involved changing some sequelize to raw SQL. I could've used the `ifNotExists` property that was added [here](https://github.com/sequelize/sequelize/pull/15119), but our sequelize version is 3 major versions behind the version containing this property
- Unrelated fixes: removes /mediorum usages+route rewrite, adds explicit OPTIONS handler for /upload to fix local CORS error, and fix `audius-compose down` (the directory of docker-compose.yml changed in a previous PR, which changed the …
=> Make storage v2 work without CNs in audius-compose

discovery-provider/plugins/notifications/src/processNotifications/mappers/milestone.ts, discovery-provider/plugins/notifications/src/types/notifications.ts
Fixes this error
```
Error in renderAndSendNotificationEmail TypeError: Cannot read property 'title' of undefined\n    at Milestone.formatEmailProps (/notifications/src/processNotifications/mappers/milestone.ts:273:21)\n    at /notifications/src/email/notifications
```
Listen milestone email wasn't implemented.
=> Fix listen milestone email

dev-tools/audius-compose
My guess at the problem:
- Building the image [here](https://github.com/AudiusProject/audius-protocol/blob/main/dev-tools/audius-compose#L213) (triggered by circleci [here](https://github.com/AudiusProject/audius-protocol/blob/main/.circleci/jobs/build-gcp-image.yml#L41)) uses <default_project_name>-<service-name>. Ex: "compose-discovery-provider" because the docker-compose.yml file is in the "compose" directory
- Pushing the image [here](https://github.com/AudiusProject/audius-protocol/blob/main/dev-tools/audius-compose#L251) (triggered by circleci [here](https://github.com/AudiusProject/audius-protocol/blob/main/.circleci/jobs/push-docker-image.yml#L46)) uses <protocol_dir>-<service_name>. Ex: "audius-protocol-discovery-provider)
Solution if this is in fact the problem (lmk what you all …
=> Maybe fix wrong CircleCI images being auto-deployed

discovery-provider/alembic/env.py, discovery-provider/alembic/trigger_sql/ddl.sql
alter table add column if not exists sadly needs to take a table lock even if the column already exists, which can cause ddl.sql to wait for many minutes.
helper function adds some boilerplate to only run alter table if column is missing.
=> Adds function to check for column before trying to add it.

discovery-provider/plugins/notifications/src/processNotifications/mappers/userNotificationSettings.ts
This would throw an error when user doesn't have browsers
```
{"level":50,"time":"2023-05-01T19:02:13.095Z","name":"notifications","msg":"Error in sending Push API browser notifications TypeError: Cannot read property 'browser' of undefined"}
```
Tested in testing environment.
=> Fix browser push when user doesn't have browsers

discovery-provider/alembic/trigger_sql/handle_playlist.sql, discovery-provider/alembic/trigger_sql/handle_track.sql
This wasn't accounted for
Deploy to stage, verify create notifs created when marking a track as unlisted -> listed and a playlist as private -> public.
Verify normal create path still works.
=> Create notifs for newly unlisted tracks or newly public playlists

discovery-provider/src/tasks/index.py, discovery-provider/src/tasks/index_nethermind.py, libs/src/api/Account.ts, libs/src/api/File.ts, libs/src/api/Track.ts, libs/src/api/Users.ts, libs/src/api/entityManager.ts, libs/src/sanityChecks/addSecondaries.ts, libs/src/sanityChecks/assignReplicaSetIfNecessary.ts, libs/src/sanityChecks/index.ts, libs/src/sanityChecks/rolloverNodes.ts, libs/src/services/creatorNode/CreatorNode.ts
For everything currently uploading metadata and sending the CID through `manageEntity` (track, playlist, and user events except create user).
Log when we fall back to CID route for debugging.
Still upload to content nodes.
Deploy to stage, tail logs, edit user, create tracks, create playlists, create albums etc. Make sure all succeed with no fallbacks.
=> Send metadata directly through chain

discovery-provider/plugins/notifications/src/__tests__/mappings/supporterDethroned.test.ts, discovery-provider/plugins/notifications/src/email/notifications/renderEmail.ts, discovery-provider/plugins/notifications/src/email/notifications/sendEmail.ts, discovery-provider/plugins/notifications/src/processNotifications/mappers/supporterDethroned.ts
- remove sending emails from supporter dethroned
- do not send emails if no valid notifications to send (e.g. if all the notifs are supporter dethroned, do not send email) by moving the verification out of renderEmail into sendEmail
updated unit tests
=> [PLAT-963] plugin should not send emails if no valid notifs available

discovery-provider/alembic/trigger_sql/handle_reaction.sql, discovery-provider/integration_tests/notifications/test_reaction.py, discovery-provider/plugins/notifications/src/__tests__/mappings/reaction.test.ts
Undoing and re-sending a reaction would send dupe notifs. Removing timestamp makes it act more like favorite / reposting. Also, undoing a reaction (reaction_value 0) would previously insert into notifs and create a push notif. 
Updated tests
=> Dedupe reaction notifs

discovery-provider/alembic/trigger_sql/ddl.sql, discovery-provider/integration_tests/tasks/entity_manager/test_delegate_entity_manager.py, discovery-provider/integration_tests/utils.py, discovery-provider/src/models/delegates/app_delegate.py, discovery-provider/src/tasks/entity_manager/app_delegate.py, discovery-provider/src/tasks/entity_manager/entity_manager.py
Changes to allow revoking app delegate (i.e. revoking an API key + secret) in Discovery
An app owner would revoke their API key if it was compromised or simply no longer needed. This implicitly invalidates all delegations to that app delegate (we can also do this explicitly, but I felt that that isn't needed - lmk what you think.)
=> Revoke app delegate EM action C-2559

mediorum/server/transcode.go
Makes ffmpeg in storage v2 more closely match v1. The only difference now is that v2 forces the output to mp3 and pipes output, which I think are both desired. [V1 command](https://github.com/AudiusProject/audius-protocol/blob/main/creator-node/src/ffmpeg.ts#L155-L164) vs [V2 command](https://github.com/AudiusProject/audius-protocol/compare/theo-reconcile-ffmpeg?expand=1#diff-0c98ca7458ea2ac5dec8b58db13fb093d2dfad8e20047ff31aa94f0be2404521R249-R259)
Uploaded and played back a transcoded track
V2 uploads on staging should continue working
=> [CON-681] Reconcile storage v2 ffmpeg differences

discovery-provider/plugins/notifications/scripts/test-push-notification.ts, discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts, discovery-provider/plugins/notifications/src/main.ts
- Uncomment flaky tests
- Remove hardcoded redis values on start (so plugin will retroactively send any missed notifs on restart)
audius-compose test run "discovery-provider-notifications" with package.json updated to run processPushNotification.test.js only. Re-run several times, ensure no failures.
=> Fix flaky DMs tests

discovery-provider/src/app.py, discovery-provider/src/tasks/backfill_cid_data.py
Data to backfill on prod. Will run once async on startup.
=> Add prod metadata tsv to backfill

monitoring/healthz/package-lock.json, monitoring/healthz/src/DiscoveryHealth.tsx
Removes old POA stuff from healthz and replaces it with more useful ACDC goodies 🎉
Currently the address of the internal ACDC node isn't exposed through discprovs health check so there's no way to get it from the outside world. We can infer though that a node is a signer because they all default to being able to sign and checking if they can produce blocks tells us if they actually can use signing powers or not. The better way would be to expose this via discprov and do a comparison between the node address and the list of signers in the `clique_snapshot`. This way we at least remove the need for a new discprov version release and still get pretty much the same benefit.
Ran locally against stage and prod
"I am the monitor" - Healthz probably
=> PLAT-781: nm healthz improvements

.circleci/jobs/test.yml, dev-tools/compose/docker-compose.dev.yml
Because ABIs are overwritten by the ones built from the ganache instances that are spun up here: https://github.com/AudiusProject/audius-protocol/blob/a0a3c286ab38ed0427683822cd3fe1df1a05601b/dev-tools/compose/docker-compose.dev.yml#L28, we should make sure to wait for `service_healthy` instead of just `service_started` to prevent a race condition
`audius-compose test run identity-service`
=> Fix libs startup race condition 

monitoring/healthz/src/DiscoveryHealth.tsx
sometimes a .includes was being called on an undefined object which caused healthz to crash
Ran locally against stage / prod
=> handle undefined string

comms/discovery/db/queries/get_chat_permissions.go, comms/discovery/db/queries/get_chats.go, comms/discovery/rpcz/chat_permissions_test.go, comms/discovery/rpcz/validator.go, comms/discovery/schema/schema.go, comms/discovery/schema/schema.ts, comms/discovery/server/response_mapper.go, comms/discovery/server/server.go, comms/discovery/server/server_test.go, dev-tools/compose/docker-compose.comms.yml, libs/src/sdk/api/chats/serverTypes.ts
- Compute new field `recheck_permissions` on chats response (if any chat_member record for that chat has cleared_history_at > last_message_at, true, else false). Client will use to determine whether to recheck permissions after a member has cleared their chat
- Only validate permissions on message send if the computed `recheck_permissions` is true
- Make permissions check on chat create unidirectional
- Fix `make test`
Unit/integration tests
=> DMs permissions updates

discovery-provider/integration_tests/queries/test_search.py, discovery-provider/integration_tests/queries/test_search_track_tags.py, discovery-provider/integration_tests/queries/test_search_user_tags.py, discovery-provider/integration_tests/tasks/test_get_feed_es.py, discovery-provider/src/utils/web3_provider.py
Since ACDC has been functioning correctly for awhile discprov should be using its local node to index. This will reduce network latency and traffic to cloudflare will only be external RPC clients like web and mobile. There is a fallback if the node is unhealthy to use the RPC gateway should one node not report healthy. 
Will run on a node on stage once build is complete.
Logs showing which web3 provider was chosen will appear on startup. This will tell us if discprov thinks its local node is unhealthy and if it fell back to the gateway.
=> PLAT-955: default to local RPC and fallback to gateway

comms/discovery/rpcz/broadcast.go, creator-node/nginx_conf/nginx.conf, mediorum/server/cid_log_client.go, mediorum/server/server.go
make's mediorum's /internal path prefix available even if the node is not mediorum first
so that crudr, replication, cid pg_beam stuff can all work.
=> Add /internal nginx proxy rule. Enable cid beam in prod

.circleci/src/commands/gcp-run.yml, discovery-provider/plugins/notifications/src/__tests__/mappings/announcement.test.ts, discovery-provider/plugins/notifications/src/__tests__/mappings/challengeReward.test.ts, discovery-provider/plugins/notifications/src/__tests__/mappings/cosign.test.ts, discovery-provider/plugins/notifications/src/__tests__/mappings/create.test.ts, discovery-provider/plugins/notifications/src/__tests__/mappings/multipleMappings.test.ts, discovery-provider/plugins/notifications/src/__tests__/mappings/reaction.test.ts, discovery-provider/plugins/notifications/src/__tests__/mappings/remix.test.ts, discovery-provider/plugins/notifications/src/__tests__/mappings/repost.test.ts, discovery-provider/plugins/notifications/src/__tests__/mappings/repostOfRepost.test.ts, discovery-provider/plugins/notifications/src/__tests__/mappings/save.test.ts, discovery-provider/plugins/notifications/src/__tests__/mappings/saveOfRepost.test.ts, discovery-provider/plugins/notifications/src/__tests__/mappings/tip.test.ts, discovery-provider/plugins/notifications/src/__tests__/mappings/userNotificationSettings.test.ts, discovery-provider/plugins/notifications/src/__tests__/processEmailNotifications.test.ts, discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts, discovery-provider/plugins/notifications/src/listener.ts, discovery-provider/plugins/notifications/src/main.ts, discovery-provider/plugins/notifications/src/remoteConfig.ts, discovery-provider/plugins/notifications/src/utils/populateDB.ts
- `toStrictEqual` was failing for me locally because the received was not an instance of Array despite serializing to the same string. Replaced with `toMatchObject`
- We weren't actually stopping the processor when cleaning up after each test. Was continuing to cycle and generating some error logs due to the db connection being destroyed
- Remove some duplicate cleanup logic in some `afterEach` blocks
- Tests were sometimes failing bc of duplicate key violations for tables we were using `randId()` to generate a random primary key value for (`NotificationDeviceTokens` in identity and `users` in discovery). `randId()` generates a random number between 0 - 1000 so there was a 1/1000 chance of conflict between 2 random keys. Fixed by replacing with hardcoded numbers -- since we set up an …
=> Clean up notifications tests

.circleci/config.yml, .circleci/src/jobs/build-gcp-image.yml, .circleci/src/workflows/creator.yml, .circleci/src/workflows/discovery.yml, .circleci/src/workflows/identity.yml, contracts/test/userReplicaSetManager.js, creator-node/test/StateMonitoringManager.test.js, creator-node/test/audiusUsers.test.js, dev-tools/audius-compose
* Improves CI flows further by separating out main & release -- more steps to skip on main
* Fix discovery ES tests -- this was because we ran out of space. I ran a flavor of this branch w/ docker system prune.
* Fix flakey tests in content node with retries (small lint changes)
* Comments out flakey soon to be deleted contracts test
🟢 Give me green 🟢
=> Separate main and release CI flows

monitoring/healthz/src/DiscoveryHealth.tsx
healthz previously only brought in the first character for peers, this broke when on prod there would sometimes be double digit sets of peers
ran in stage and prod mode locally and saw the correct peer count
healthz is the monitor
=> PLAT-981: fix peer count in health z

check_secrets.sh
`git-secrets` was scanning the entire repo before every commit...
* Scan only the staged files for secrets, reducing pre-commit hook time from ~25 secs to ~1 sec
> Shouldn't need to do --no-verify anymore! 🙌
Tested by staging a fake aws secret and attempting to commit
=> [INF-379] Make pre-commit hook fast

discovery-provider/integration_tests/tasks/test_index_helper.py, discovery-provider/src/tasks/index.py, discovery-provider/src/tasks/index_nethermind.py, discovery-provider/src/utils/cid_metadata_client.py
Sanitize metadata blobs from chain the same way /content/<cid> responses are currently sanitized
=> Sanitize cid metadata from chain

mediorum/ddl/ddl.go, mediorum/server/cid_log_client.go, mediorum/server/health.go, mediorum/server/server.go
building the CID index for all CIDs was too big... going to delete that and revisit later to omit track segment CIDs.
* disables cid client polling
* truncates cid_* tables
* lowers interval on health broadcast
=> flare-178: disable cid beam, truncate cid_lookup table.

monitoring/vector/vector.toml
following the instructions on [plat-990](https://linear.app/audius/issue/PLAT-990/add-notifs-logs-to-axiom), i believe this allows the notifications container logs to pipe into axiom as well
=> [PLAT-990] add notifications logs to axiom

discovery-provider/src/api/v1/users.py, discovery-provider/src/queries/get_tracks.py, discovery-provider/src/queries/query_helpers.py
Seeing some duplicate profile results perhaps because we are not tiebreaking order-by's in the `get_tracks` query, then attempting pagination.
https://audius-internal.slack.com/archives/C02JBA52NKZ/p1684948728168179
Also parse sort_direction and sort_method properly
Make sure tracks API queries are working as expected
=> Tiebreak order_bys in get_tracks

mediorum/ddl/ddl.go
We skip the time-consuming cid_lookup table migration but want to run the migration to create delist tables separately
Deploying to staging and should see the tables created
Checking for tables existing on staging
=> Run delist migration separately from cid_lookup

libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts, libs/src/sdk/services/DiscoveryNodeSelector/types.ts
Fixes two issues
-> DN re-selection didn't work if the initial `fetch` request threw an error altogether. We were missing `onError` method.
-> Race condition when making a bunch of failed requests -> URL parsing for the fetch retry would fail since it relied on the old endpoint being constant -> Stuck in retry loop
--> Fixed by only allowing one ongoing reselection at a time + parsing the URL using a regex (maybe will change to URL if compatible w all platforms)
=> Fix DN re-selection in SDK

discovery-provider/alembic/trigger_sql/ddl.sql
`IndexingError(\\'(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint \"users_pkey\"\\\\nDETAIL:  Key (is_current, user_id, txhash)=(f, 433967780, 0xa25516594adc42562e498b2c9f4e4365c9cbfea223a4e55624ae0ac316708a62)`
=> fix indexing stall

creator-node/test/CNodeHealthManager.test.js, dev-tools/commands/src/edit-user.mjs, dev-tools/commands/src/index.mjs, libs/src/api/Users.ts, libs/src/services/creatorNode/CreatorNode.ts, libs/src/services/schemaValidator/schemas/playlistSchema.json, libs/src/services/schemaValidator/schemas/userSchema.json, libs/src/utils/getNStorageNodes.test.ts, libs/src/utils/getNStorageNodes.ts, mediorum/server/transcode.go
- Adds `audius-cmd edit-user [handle]` with only name and bio (can add more metadata fields when needed)
- Fixes bug that set the wrong name for `img_backdrop` on user profiles
- Removes CID schema constraints that cause v2 images to not be allowed during the v1 edit-user flow (probably wouldn't happen in real life anyway - only if v2 gets flipped from off -> on -> off again)
- Miscellaneous minor linting
```
audius-cmd create-user
audius-cmd edit-user [handle] --name "new name"
```
Double-check updating a user profile on staging
=> [CON-678] Add v2 edit-user to audius-cmd

discovery-provider/src/queries/queries.py
Bring back cid in responses to allow for requests to /tracks?id=xyz to find the cid
=> Bring back cid in responses

mediorum/server/delist_statuses.go, mediorum/server/delist_statuses_test.go
Fixes delist-status test to reflect changes to time format that make it match what trusted notifier returns, which is a precision 6 string returned directly from postgres
`make test`
N/A - tests
=> Fix time in delist-status test to match postgres

discovery-provider/integration_tests/queries/test_notifications/test_announcement_notification.py, discovery-provider/src/queries/get_notifications.py
the get_notifications query doesn't know to include an announcement notification in its results for a given user because the announcement notification has an empty user_ids array for users to notify (since the entire user id list would be too large to store)
this updates the query so that we get notifications where a given user id is part of a notifications user_ids OR the notif type is an announcement, in which case it doesn't matter who the user_ids are, we always include
same goes for unread count query
updated tests
=> [PLAT-821]: Fix announcement notification reads from discovery

mediorum/.initdb/init.sql, mediorum/bash_scripts/deploy_mediorum.sh, mediorum/ddl/cid_lookup.sql, mediorum/ddl/ddl.go, mediorum/ddl/test/cid_lookup_test.sql, mediorum/server/cid_log_test.go, mediorum/server/db.go, mediorum/server/server.go
* update `ddl` to only re-run sql if hash changes to avoid slow boot (similar to pg_migrate.sh)
* update trigger + backfill to omit segments this time around
* simplify and fix cid_lookup tests
=> Reenable CID beam, omit tracks (segments) this time.

discovery-provider/src/queries/get_tracks.py
Tests on CI are failing and they don't lie!
https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/37540/workflows/ca5c1575-1fc0-47a8-9e46-ae1f9c8e40b9/jobs/484413
This is because the coalesce here was actually intentional -- it allows for tracks with missing release dates to treat created at as if it was the release date. This order should be stable though with the new tiebreaking.
```
pytest integration_tests/queries/test_get_tracks.py
```
=> [PLAT-1007] Fix sort by coelesce

discovery-provider/nginx_conf/nginx.conf
While this is not the most elegant solution, it works well and doesn't seem to have major performance impact.
It definitely is _less_ performant, but I don't think substantially enough for us to care.
I would like to get out of this world though. Perhaps we think about a way to move health check to a higher level construct or something....
sandbox: http://34.72.186.34:5000/health_check
wraps existing /comms endpoint json into json from health_check
=> [PLAT-982] Join comms and server health checks

libs/scripts/release.sh
`[skip ci]` only works in the first 250 chars:
https://circleci.com/docs/skip-build/?utm_source=google&utm_medium=sem&utm_campaign=sem-google-dg--uscan-en-dsa-tROAS-auth-brand&utm_term=g_-_c__dsa_&utm_content=&gclid=CjwKCAjwvdajBhBEEiwAeMh1U-cpXyrug3PVM23J1EZdn1m_XgvaVRW1bl4HXbbAzFYzYgv7QRca8hoCquMQAvD_BwE
A good guess...
=> Fix skip ci on libs/*

discovery-provider/src/queries/confirm_indexing_transaction_error.py, discovery-provider/src/queries/get_attestation.py, discovery-provider/src/queries/get_health.py, discovery-provider/src/queries/get_redirect_weights.py, discovery-provider/src/tasks/cache_current_nodes.py, discovery-provider/src/tasks/index_metrics.py, discovery-provider/src/tasks/index_network_peers.py, discovery-provider/src/utils/get_all_other_nodes.py
Adds content node endpoints in discovery-node health-check endpoint. this way, we wont need need to hit eth for the content nodes.
Ran locally and confirmed content nodes were present
=> [C-2695] Expose content-nodes in discovery-node health-check

monitoring/healthz/src/DiscoveryHealth.tsx
adds signer comparison to healthz
- run healthz against prod or stage
- the is signer column is now using the correct logic instead of inferring from block production
=> PLAT-1020: add better signer comparison

creator-node/src/logging.ts, creator-node/src/routes/tracks.js, libs/src/api/Track.ts, libs/src/services/creatorNode/CreatorNode.ts
- Removes the `/tracks/download_status` route because it depends on segments being present in db and I didn't see it used anywhere in protocol or client
- Removes enforcing track segments when creating or updating a track
None - passing off to @endline but it's only removing straightforward code so it should be pretty safe.
=> Remove code that depends on or enforces segments

discovery-provider/plugins/notifications/src/processNotifications/mappers/message.ts, discovery-provider/plugins/notifications/src/processNotifications/mappers/messageReaction.ts, discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
Send browser notifs for DM reactions + clean up unused live email clause (DM emails are sent once a day for live-freq users rather than live)
Should, in addition to https://github.com/AudiusProject/audius-protocol/pull/5332, fix DM browser notifs.
=> Fix DM browser notifs

discovery-provider/src/api_helpers.py, discovery-provider/src/queries/get_health.py, discovery-provider/src/queries/get_health_unit_test.py, discovery-provider/src/tasks/index_nethermind.py
I believe discovery node selection does not work entirely because of our POA offset.
See 
https://discoveryprovider.audius.co/health_check
```
latest_chain_block: 6680664,
latest_indexed_block: 38093662,
```
And sdk/libs code (which we have many flavors of): https://github.com/AudiusProject/audius-protocol/blob/ba8bb1a65a813cf1712842ba132c5c2157a1006f/libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.ts#L49
```
pytest src/queries/get_health_unit_test.py
```
Tested on sandbox machine too and verified correct values in health check
=> Fix discovery selector usage of latest_chain_block

mediorum/server/delist_statuses.go, mediorum/server/serve_blob.go, mediorum/server/serve_contact.go, mediorum/server/serve_legacy.go, mediorum/server/server.go
- Makes blacklist check happen for v2 uploads and prior to `logTrackListen()`
- Fixes mediorum /contact route not using trusted notifier email from chain (JS route uses it so it should stay the same for parity)
`/contact` now shows an email, and tracks are now streamable (or return 403 when blacklisted) on prod user-metadata
=> Hotfix mediorum /contact, blacklist v2 tracks, and fix hanging on stream

mediorum/crudr/client.go, mediorum/server/cid_log_server.go, mediorum/server/serve_crud.go
- Crudr sweep (from every node): unlimited rows every minute -> 10k rows every 30s
- cid_lookup beam (from every node until table is built up): 100k rows every 60-90s -> 1k rows every 60-90s
Testing on prod user-metadata, where flare-181 has been most noticeable
=> Nerf crudr sweep and pg_beam

mediorum/server/cid_log_client.go, mediorum/server/cid_log_server.go, mediorum/server/serve_blob.go
- Beaming now allows clients to choose their own batchSize so we can more easily hotfix on prod user-metadata, for example, without having to wait for the whole network to upgrade
- Adds 2m timeout to sql query that @stereosteve had to manually kill otherwise
Testing on prod user-metadata
=> Add timeout to mediorum sql, and make batch a queryparam

discovery-provider/src/api/v1/tracks.py
One does not simply replace urllib.parse.quote with urllib.parse.urlencode in https://github.com/AudiusProject/audius-protocol/pull/5271/files because of course those do different encodings.
```
Note that the urlencode method includes the functionality of the quote function, so you probably rarely need to call quote on its own. Also note that urlencode uses the plus sign to encode a space character in a URL…which is basically as valid as using %20. Again, the confusing rules and standards are yet another reason to delegate this string parsing to the proper Python libraries.
```
Deployed to stage node and verified + is back to being %20
- streaming works
- notifier works
=> Fix urllib parse

libs/src/api/Account.ts, libs/src/api/File.ts, libs/src/api/Track.ts, libs/src/api/Users.ts, libs/src/api/entityManager.ts, libs/src/sanityChecks/addSecondaries.ts, libs/src/sanityChecks/assignReplicaSetIfNecessary.ts, libs/src/sanityChecks/index.ts, libs/src/sanityChecks/rolloverNodes.ts, libs/src/services/creatorNode/CreatorNode.ts
- Remove param flags gating metadata writes through chain. Write through chain for all metadata
- Still upload to CN since there is ensuing association logic that depends on the file UUID returned by CN. Storage v2 will get rid of this soon anyway; it's not worth detangling the dependency in v1. Besides, all metadata reads are from discovery now
- Make sure we are validating schemas for v1 and v2 flows
Accompanying client change: https://github.com/AudiusProject/audius-client/pull/3432
DO NOT MERGE until flags have been on in prod for a while and we are confident everything is working appropriately.
Manually test all user, playlist, and tracks actions
=> Clean up libs writeMetadataThroughChain flags

discovery-provider/requirements.txt, discovery-provider/src/api/v1/tracks.py, discovery-provider/src/utils/eth_contracts_helpers.py, discovery-provider/src/utils/get_all_other_nodes.py, discovery-provider/src/utils/rendezvous.py, discovery-provider/src/utils/rendezvous_unit_test.py
- Adds rendezvous.py and unit tests to make sure it matches the [Go](https://github.com/tysonmote/rendezvous/blob/be0258dbbd3d/rendezvous.go) and [TS](https://github.com/AudiusProject/audius-protocol/blob/main/libs/src/utils/rendezvous.ts) implementations
- Makes Discovery track streaming route use rendezvous instead of `random` to find the Content Node to redirect to
```
audius-compose up -c 3
audius-cmd create-user
audius-cmd upload-track -f <user handle>
hashids encode <track id>
```
Play the encoded ID via audius-protocol-discovery-provider-1/v1/tracks/:encodedId/stream. Do this a few times and make sure the same track gets redirected to the same CN each time.
=> [CON-734] Add discovery rendezvous and use it in /tracks/:encodedId/stream

monitoring/vector/vector.toml
Dedupe this
```
message:{"level":30,"listen":true,"msg":"booting","name":"es-indexer","time":"2023-05-31T19:03:49.095Z"}msg:bootingcontainer_name:indexerlisten:truename:es-indexernode:dn1.stuffisup.comtime:2023-05-31T19:03:49.095Z
```
so there's not a message and msg field
=> Dedupe log messages in vector config

discovery-provider/integration_tests/queries/test_notifications/test_announcement_notification.py, discovery-provider/src/queries/get_notifications.py
Witholds announcements that were created before a given user was created, that way when a user creates an account for the first time and they open their notifications, they will not have a pre existing announcement showing in their notifs
added unit test. going to test on stage too.. im worried about adding this join on users and whether this will affect performance. any ideas for testing?
=> [PLAT-1023] Hide announcements for a user before they were created

discovery-provider/src/queries/get_notifications.py
Follow notifications were duped if they were grouped together.
This is because the ordering would change and trigger a different rendering. This enforces an order on grouped notifications so it's deterministic and doesn't insert additional rows.
=> Dedupe notifications grouped by action

libs/src/sdk/api/tracks/TracksApi.test.ts, libs/src/sdk/config/development.ts, libs/src/sdk/config/production.ts, libs/src/sdk/config/staging.ts, libs/src/sdk/config/types.ts, libs/src/sdk/scripts/generateServicesConfig.ts, libs/src/sdk/sdk.ts, libs/src/sdk/services/DiscoveryNodeSelector/healthCheckTypes.ts, libs/src/sdk/services/EntityManager/EntityManager.test.ts, libs/src/sdk/services/EntityManager/EntityManager.ts, libs/src/sdk/services/EntityManager/constants.ts, libs/src/sdk/services/EntityManager/types.ts, libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.test.ts, libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.ts, libs/src/sdk/services/StorageNodeSelector/constants.ts, libs/src/sdk/services/StorageNodeSelector/contants.ts, libs/src/sdk/services/StorageNodeSelector/types.ts, sdk-consumer/index.ts
* Add `confirmWrite` to EntityManager
This is simply polling discovery node for the block to be passed, the orchestration and sequencing of writes will have to be done in userland
* Add tests for EntityManager
* Pass `discoveryNodeSelector` to `StorageNodeSelector`
* Rename `identityServiceEndpoint` -> `identityServiceUrl` in config (we were already using Url in sdk, Endpoint is old nomenclature from libs)
=> [C-2529] Add confirmer to EntityManager in sdk

mediorum/bash_scripts/deploy_mediorum.sh, mediorum/server/repair.go, mediorum/server/replicate.go, mediorum/server/serve_blob.go, mediorum/server/serve_upload.go, mediorum/server/server.go
When debugging problem blobs on staging, found a few edge cases which caused repair to not work:
* a node would have a blob on disk but no `blob` row in db.  In this case peers would think that node doesn't have the blob and attempt to replicate blob to it repeatedly.
* a blob would be corrupt and the contents would hash to a different CID.  In this case node would try to push blob to peers but CID wouldn't match up and it would reject it, and node would keep retrying.
So this PR addresses it by:
* adding a blob `double_check` endpoint that will only return 200 if: node has blob, CID validates, node has db record for blob.
* making the blob create + delete more like an upsert, where it will write the blob (if missing) and write the db record (if missing) and one or both of those can …
=> repair + replicate handle more edge cases

discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts, discovery-provider/plugins/notifications/src/processNotifications/mappers/message.ts, discovery-provider/plugins/notifications/src/processNotifications/mappers/messageReaction.ts, discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts, discovery-provider/plugins/notifications/src/types/notifications.ts
Send `chat_id` in push notifications so we can deep-link in the app to that chat
Related: https://github.com/AudiusProject/audius-client/pull/3549
It hasn't
=> [PAY-1409] DMs: Include chat_id in push notification

mediorum/server/serve_blob.go, mediorum/server/serve_blob_test.go
Converts millis timestamp to seconds before passing to `time.Unix` in `/tracks/cidstream` `requireSignature` middleware.
Added a couple unit tests, and `make test` passes. If you undo the conversion change then the test fails.
=> Fix mediorum signature timestamp units

discovery-provider/chain/Dockerfile.acdc
1.18 is not usable by us, image is built for 1.17.4 using README
Compose change: https://github.com/AudiusProject/audius-docker-compose/pull/299
Sandbox, but will soak on stage before production deployment
=> Switch acdc version to latest working

dev-tools/compose/docker-compose.storagev2.yml, mediorum/crudr/crudr.go, mediorum/server/monitor.go, mediorum/server/serve_health.go, mediorum/server/serve_health_test.go, mediorum/server/serve_metrics.go, mediorum/server/server.go, monitoring/healthz/src/Mediorum.tsx
- Healthz: adds peer health and makes "started at" compatible with latest health check consolidation commit (currently foundation nodes show empty values in this column)
- Mediorum health check: fixes empty git field and caches cid cursors for 10 seconds to avoid unbounded db requests
- Exposes outbox sizes via `/internal/metrics`
Checked healthz after running locally, and deployed to stage CN6 to confirm view on healthz and /health_check git sha.
=> [CON-744] Update mediorum health_check and healthz

discovery-provider/src/api/v1/developer_apps.py
The check was done out of order with the formatting, so endpoint was returning 500 instead of 404 if developer app with matching address was not found.
=> [Discovery API] Check if developer app was found before trying to format it

discovery-provider/src/api/v1/developer_apps.py
Fixes issue where "developer_app" was being used as a model and as an endpoint
=> Fix name collision with developer_app schema

discovery-provider/integration_tests/tasks/entity_manager/test_developer_app_entity_manager.py, discovery-provider/requirements.txt, discovery-provider/src/tasks/entity_manager/developer_app.py, discovery-provider/src/tasks/entity_manager/entity_manager.py
Make sure whoever's creating a developer app actually owns the wallet address
Instead of passing in an address, they will now pass in a message signed by the developer app private key, and we'll derive the address from that
Integration tests 
=> Verify ownership of developer app wallet C-2528

libs/src/sdk/api/generator/gen.js
* `npm run gen:dev` was failing because openapigenerator couldn't connect to `audius-protocol-discovery-provider-1`. Adding an additional host to the docker command fixes it, thanks @theoilie !
The additional host should have no effect on CI, in stage or prod environments
Generated sdk locally
=> [INF-423] Fix sdk gen with audius-compose

monitoring/healthz/src/Mediorum.tsx
Since repair.go and findHealthyPeers use 5minutes as the threshold for healthy, this makes healthz show healthy nodes in the last 5minutes (in addition the the ones it shows in the last 2 minutes).
Deployed - https://health.audius.workers.dev/#/mediorum
=> Show mediorum healthy nodes in the last 5min

libs/src/sdk/api/chats/ChatsApi.ts, libs/src/sdk/api/chats/clientTypes.ts, libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts, libs/src/sdk/utils/parseRequestParameters.ts
In order to disambiguate since wallets are potentially linked to multiple accounts, we added a `currentUserId` field to each request that the SDK makes in `chats`. Prior to this, we were inferring user ID from signature. Given the bugs in signup, and given delegation coming in the future, we should support explicitly setting a user id to act on behalf of for each request.
Pending changes from @stereosteve for the read endpoints piece of this
Also includes some ESLint cleanup and some doc comments
TBD
=> [PAY-1341] Add optional currentUserId to every chats request

creator-node/src/services/ContentNodeInfoManager.ts, creator-node/src/services/stateMachineManager/stateReconciliation/updateReplicaSet.jobProcessor.ts, creator-node/src/snapbackSM/peerSetManager.js, creator-node/src/snapbackSM/snapbackSM.js, libs/src/api/ServiceProvider.ts, libs/src/services/creatorNode/CreatorNodeSelection.ts
There's a content node <> libs dependency here, but the code should be safe to merge as is and just require a follow up PR to upgrade sdk in content node.
The gist of changes here are to reduce calling to chain *every time* job processors run (which is a lot) and instead try to rely on the unified sp-id mapping that gets refreshed every 10 min.
https://github.com/AudiusProject/audius-protocol/blob/2176ebd90d57e61d4ceeff2017580ca2857c6369/creator-node/src/config.js#L493
This comes at some disadvantages of course, but I think it's safe enough to do, especially given that we are moving off of the system entirely ~soon. From taking a look, it doesn't seem that mediorum drives a ton of eth RPC traffic. As a compromise, down to change the sp-id mapping interval to 1-2 minutes or so.
_Please …
=> [CON-746] Improve content node usage of eth rpc

comms/discovery/config/config.go, comms/discovery/config/constants.go, comms/discovery/discovery_main.go, comms/discovery/server/basic_auth.go, comms/discovery/server/server.go
* computes wallet from private key
* only reads `audius_delegate_private_key` to print warning if it doesn't match
* marks node unhealthy if computed wallet not in registered list
* doesn't start peer client if not registered (cuts down on log spam from sandbox nodes)
* better special case of DN4
=> comms derives wallet address from private key

comms/discovery/rpcz/apply.go, comms/discovery/rpcz/chat_test.go
fixes internal rpc cli
tested on stage discovery 1... verified stage 2 gets the message.
note that it is not "pushed" so is subject to the ~1m polling interval.
=> populate relayed_by and relayed_at (if missing)

discovery-provider/plugins/notifications/Dockerfile
base64url was added in a later version of node which is what's failing for some reason, upgrading to test
this is currently running on stage
=> upgrade node version for notifications

libs/package.json, libs/src/sdk/api/developer-apps/types.ts, libs/src/sdk/api/grants/types.ts, libs/src/sdk/oauth/OAuth.ts, libs/src/sdk/oauth/index.ts, libs/src/sdk/oauth/types.ts, libs/src/sdk/sdk.ts, libs/src/sdk/utils/apiKey.ts, libs/src/sdk/utils/file.ts, libs/src/sdk/utils/oauthScope.ts
Adds to existing OAuth helpers, documented here:
https://docs.audius.org/developers/log-in-with-audius
Now you can pass in scope to oauth.renderButton() or oauth.login() to do an OAuth write authorization using your api key.
This is a BREAKING change for existing OAuth users due to method signature changes
=> Add Write OAuth helpers to SDK C-2784

creator-node/src/components/healthCheck/healthCheckComponentService.js
specify `creatorNodeVersionOverride` in `override.env` instead of maintaining foundation release branch.
will deploy to a stage node and verify works
=> creatorNodeVersionOverride env var

identity-service/src/apiHelpers.js, identity-service/src/rateLimiter.js, identity-service/src/routes/relay.js
Use custom handler to log events and send json. Before, it was just using the default so nothing was logged. Also saving the recovered signer to the req body so we don't rely on senderAddress. 
=> Use relay rate limit custom handler and send json

comms/discovery/discovery_main.go
Removes code that tries to infer host name from wallet... since some hosts re-use wallet, this causes problems.
Both host + wallet must be correct for `comms.healthy` to be true.
Also refreshes registered peer list on interval.
=> DM: validate host + wallet pair

libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.ts
The API response `is_healthy` field is not properly updated to match the `health_check` health response. Until it is, ignore it.
=> SDK: Don't check comms API response health

discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py, discovery-provider/src/tasks/entity_manager/entities/user.py
Removes the null check for user bios so if a user deletes their bio, we can set the bio to that empty string. 
Confirmed this is already the behavior for playlist and track descriptions (we can set empty strings). and checked any other fields that would want this behavior but might not have it but didn't find any
testing end to end on stage, verified results in discovery look correct. added unit test as well
=> [PLAT-861] allow empty string for user bios in em indexing

identity-service/sequelize/migrations/20230626231334-default-messages-on-mobile-notification-settings.js, identity-service/sequelize/migrations/20230626231346-default-messages-on-browser-notification-settings.js, identity-service/src/models/userNotificationBrowserSettings.js, identity-service/src/models/userNotificationMobileSettings.js
In preparation for DMs launch on 7/11, this should go out in the release the week before (week of 7/3).
DM notifs were set to default off during the testing period on prod these past few months out of an abundance of caution.
=> Change DM notifs back to default on

comms/discovery/rpcz/apply.go, comms/discovery/server/main_test.go
validate one time in mutate endpoint... don't re-validate relayed messages at apply time
=> validate in mutate endpoint

comms/discovery/db/queries/get_users.go, comms/discovery/server/mutate_test.go, comms/discovery/server/server_test.go
avoids selecting a errant is_current user row that has null handle... 
as a last resort if there are duplicate valid users with same wallet, sorts by user_id asc to make deterministic.
=> make wallet user_id lookup deterministic

discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py, discovery-provider/src/tasks/entity_manager/entities/social_features.py
Only save repost and save EM transactions for playlists and tracks that are not private/hidden/unlisted. this info will be passed from the front end in a separate diff 
added unit tests, will test e2e on stage 
=> [plat-1085] do not persist save and favorites of hidden tracks and collections

discovery-provider/src/tasks/index_nethermind.py
Free up cycles when block not found. Hopefully reduces nominal CPU usage.
500ms was picked because, I observed "block not found" on stage discovery nodes between these timestamps.
2023-06-27 16:27:17,469
2023-06-27 16:27:18,106
=> [PLAT-1087] Free up cycles when block not found for 500ms

discovery-provider/scripts/start.sh, discovery-provider/src/challenges/challenge_event_bus.py, discovery-provider/src/tasks/index_rewards_manager.py, discovery-provider/src/tasks/index_solana_plays.py
* Remove extremely noisy 0 event challenge bus logs: https://app.axiom.co/audius-Lu52/explorer?did=stage-discovery&qid=PeLgQsmAJmx-rwxa9z
* Set beat logs coming from celery itself to >= WARNING, which will removes logs around "Sending due task" (contributing ~50% of our log volume)
* Early return and cleanup in solana indexers
sandbox
=> [PLAT-1086] Log cleanup

identity-service/src/routes/push_notifications.js
Client posts to this endpoint on signout; we don't want to nuke their notif settings - just want to deregister the token so that we are not sending the device notifications anymore.
This endpoint is hit in 2 places in the client: when disabling all notifs in app settings, and when logging out. When the client handles disabling notifs, it updates mobile settings to false accordingly separately so this change is safe.
=> Do not destroy mobile settings when deregistering device token

discovery-provider/plugins/notifications/src/email/notifications/index.ts, discovery-provider/plugins/notifications/src/main.ts, discovery-provider/plugins/notifications/src/remoteConfig.ts
I think the heap error is caused by values being passed to the callbacks during this large loop. This includes long lived values like the db connection which may be confusing the garbage collector. Announcements works with a for loop and not callbacks so adjusting this to work the same way. 
Will run on stage.
=> PLAT-1096: use for loop instead of callbacks

creator-node/src/app.ts, dev-tools/audius-compose, discovery-provider/plugins/notifications/src/main.ts, discovery-provider/plugins/notifications/src/processNotifications/mappers/announcement.ts, discovery-provider/src/app.py, identity-service/src/app.js
Removes the `--no-cache` option in docker since this is run on the push step. This causes everything to be rebuilt unnecessarily. 
First, added a new log to notifications to show the new build was there. Second, SSHed into running indexer on stage and found my code change was present in the build from this branch.
=> PLAT-1063: docker caching issues

comms/discovery/discovery_main.go, comms/discovery/rpcz/chat.go, comms/discovery/rpcz/chat_create_test.go, comms/discovery/rpcz/peer_client.go, comms/discovery/rpcz/peer_client_test.go, comms/discovery/rpcz/rate_limit_test.go, comms/discovery/rpcz/test_utils.go, comms/discovery/server/server.go, comms/discovery/server/server_test.go, discovery-provider/ddl/migrations/0007_dm_chat_member_created_at.sql, discovery-provider/ddl/migrations/0008_rpc_log_error.sql
Might want to review commits independently.
* First one: don't delete chats on conflict, simply update `chat_member` rows to resolve `invite_code` conflict
* Second one: if sweeper hits apply error, captures rpc into `rpc_error` table and moves on... will retry on subsequent runs up to 30 times.  Also adds endpoint to dump contents of rpc_error table
Deployed to stage DN1... no `rpc_error` rows, but confirmed works.
=> DMs: better retry mechanism

creator-node/src/config.js, dev-tools/startup/creator-node-container.sh
Disables the queues that handle recurring syncs and replica set updates. Leaves manual syncs alone because v1 signups rely on these to sync metadata from primary->secondaries. Leaves the actual code alone so it's reversible in case of emergency.
I'll verify on staging that the `/health/bull` route is showing recurring sync and replica set update queues as not processing any jobs.
=> [CON-770] Turn off state machine

dev-tools/compose/docker-compose.test.yml
Use 5455 for postgres in docker-compose.test.yml so that tests can be run even if the local stack is already up
=> Use unique port for test db

comms/discovery/rpcz/apply.go, comms/discovery/rpcz/peer_client.go, comms/discovery/rpcz/peer_sweeper.go, comms/discovery/rpcz/peer_sweeper_test.go, comms/discovery/rpcz/websocket.go, comms/discovery/server/server.go
Currently on `main` we start a goroutine per peer and sweep only the messages that were relayed by that peer.  This non-gossip style replication has these downsides:
* if there is "no route" between two hosts (due to DNS config) they don't get each other's messages
* if a host re-seeds and the db has an incomplete history... the host's own history will change and become incomplete
* if a host is down, messages it relayed are unavailable while down
This PR makes it more gossip style... it will scroll all messages in `rpc_log` in `applied_at` order instead of using `(relayed_by, relayed_at)`.
This means there is more write amplification, but also ensures all hosts get all messages and `rpc_log` acts like a more reliable grow only set.  Skipping a message you have already seen is cheap, so …
=> DMs: gossip

mediorum/server/monitor.go, mediorum/server/serve_health.go
Returns healthy=false in health check if the db size check fails to connect or is empty. It will never be empty as long as there's even a single table (even if it has no rows yet).
Very small change. We can test on staging.
=> Return unhealthy mediorum if no db connection

libs/src/sdk/api/chats/ChatsApi.ts
Not that this should ever happen... 
This change at least will make the chats list load, and isolate the brokenness to a single chat
Linked SDK against broken account
=> Handle chat secret decryption failure cases more gracefully

discovery-provider/ddl/migrations/0009_nuke_tn_delist_tables.sql, discovery-provider/integration_tests/tasks/test_update_delist_statuses.py, discovery-provider/src/queries/get_trusted_notifier_discrepancies.py, discovery-provider/src/tasks/update_delist_statuses.py, discovery-provider/src/utils/redis_constants.py
Do not update the delist status cursor if there are missing tracks or users in the discovery db that should be updated, so that discovery retries the delist until indexing is caught up. This is what was causing discrepancies in prod DN3, which is slower than the other nodes.
Also check the cursor every 12h to make sure it's caught up.
Nuke the cursors table to make all nodes including SPs go through the delists again. No need to truncate user_delist_statuses and track_delist_statuses, those have an ON CONFLICT DO NOTHING clause on the insert.
Written tests, checked health endpoint on local
=> DN trusted notifier polling: handle slow indexing. add monitor for cursor being behind

identity-service/src/notifications/emails/welcome.js
Following https://github.com/AudiusProject/audius-protocol/pull/5513
Unfortunately on dark mode mobile gmail, unless we used images for the buttons entirely, the text changes color while the icon does not. SVG would perhaps work, but not all emails clients support. Tried a few other things to attempt to fix from SO & this great litmus [blog](https://www.litmus.com/blog/the-ultimate-guide-to-dark-mode-for-email-marketers), but no avail.
Juice not worth the squeeze.
Before
After
=> [C-2811] Drop icons in new welcome email

mediorum/server/serve_blob.go, mediorum/server/server.go
Adds middleware *before* requireSignature so delisted statuses are surfaced instead of invalid signatures. This is a request from non-technical folks to be able to tell if a track is delisted or just a bad signature.
Got a signature and then delisted it. On the node where I'm testing this (stage CN6) it says the track is delisted. On other nodes, it says the signature expired.
Example track that has an expired signature and is delisted: [CN5](https://creatornode5.staging.audius.co/tracks/cidstream/QmUxV2feEgW7nEMMfw9MEStcjHzoQQNqrS1a63v3ztVfZ1?signature=%7B%22data%22%3A%20%22%7B%5C%22trackId%5C%22%3A%201009765850%2C%20%5C%22cid%5C%22%3A%20%5C%22QmUxV2feEgW7nEMMfw9MEStcjHzoQQNqrS1a63v3ztVfZ1%5C%22%2C%20%5C%22timestamp%5C%22%3A%201684364028490%2C%20%5C%22userId%5C%22%3A%20700980330%2C%20%5C% …
=> [CON-769] Return delisted before bad sig

discovery-provider/integration_tests/tasks/entity_manager/test_grant_entity_manager.py, discovery-provider/src/tasks/entity_manager/entities/grant.py, discovery-provider/src/tasks/entity_manager/entity_manager.py, discovery-provider/src/tasks/entity_manager/utils.py
Get rid of the query for users by wallet address, since we don't need it anymore. Hopefully this makes the grant creation faster since anecdotally it has been taking longer than other txs. With this deleted, there's no other reason it should be slower than other tx processing times.
=> Make grant creation faster on EM indexing C-2803

discovery-provider/ddl/migrations/0010_usdc_userbank_tables.sql
Adds tables for USDC related things.
Open Qs:
- Do we want any improvements on existing userbank things? Eg any foreign keys/cascading deletes?
- Do we want `spl_token`-like indexing progress or put each tx in the table like former `user_bank_tx` table?
Tested that migrations ran successfully by pointing DDL script at local db
=> [PAY-1547] Add USDC related tables to DB

identity-service/relay-rate-limit.json
Raise rate limits for social features based on current usage. The owner rate limit is for users taking action with their own wallet.
=> Raise rate limits for social features

libs/src/sdk/services/Storage/Storage.ts, libs/src/services/creatorNode/CreatorNode.ts, mediorum/server/serve_upload.go
- Makes `/uploads/:id` return 422 Unprocessable Entity on error status. Technically this could be a 500 since any server-side error could cause a transcode to fail. However, in practice we've only ever seen transcode errors due to a file that would never succeed no matter how many retries it gets, so I'd call it unprocessable
- Makes client/libs/sdk fail fast if it gets this 422
This is low risk, so I'll test on staging by renaming a random file to have a .mp3 extension and then uploading it.
=> [CON-771] Short circuit when transcode fails

mediorum/server/replicate.go, mediorum/server/serve_blob.go
- Makes `/internal/blobs/info/:cid` return just 404 when not found instead of 500 with a long message about stat
- Changes query for replication so it doesn't cause gorm's default logger to print "record not found" in obnoxious red and purple text
`make dev` and upload a file at localhost:1991. The logs look healthy now.
=> Make mediorum stop looking like it's erroring when it's not

comms/discovery/config/config.go, comms/discovery/discovery_main.go, comms/discovery/misc/trim.go, comms/discovery/rpcz/apply.go, comms/discovery/rpcz/chat_test.go, comms/discovery/rpcz/internal_rpc.go, comms/discovery/rpcz/internal_rpc_test.go, comms/discovery/rpcz/main_test.go, comms/discovery/rpcz/validator.go, discovery-provider/ddl/migrations/0011_chat_ban_timestamps.sql, discovery-provider/ddl/migrations/0012_rpc_log_applied_at_idx.sql
* updates chat_ban table to correctly handle out of order RPCs
* adds brin index to `rpc_log.applied_at`
* infers hostname when safe to do so
=> DMs make internal rpcs idempotent

discovery-provider/src/tasks/entity_manager/entities/playlist.py, discovery-provider/src/tasks/entity_manager/entities/track.py, libs/src/sdk/api/playlists/PlaylistsApi.test.ts, libs/src/sdk/api/playlists/PlaylistsApi.ts, libs/src/sdk/api/playlists/types.ts, libs/src/sdk/api/tracks/TrackUploadHelper.ts, libs/src/sdk/api/tracks/TracksApi.test.ts, libs/src/sdk/api/tracks/TracksApi.ts, libs/src/sdk/api/tracks/TracksUploader.ts, libs/src/sdk/api/tracks/types.ts, libs/src/sdk/sdk.ts, sdk-consumer/index.ts
* Add `audiusSdk.playlists.uploadPlaylist`, this is used for both playlists and albums
* Add delegated writes for playlists in entity manager
*  Update `logger` references to `params.logger` for better logging context
* Add `TrackUploadHelper` to generalize shared logic between `TracksApi` and `PlaylistsApi`
* TODO: add tests
Tested against local audius-protocol, confirmed both playlists and albums upload properly and resulting entities are correct
=> [C-2737] Add collection upload to write sdk

discovery-provider/src/api/v1/tracks.py, mediorum/server/repair.go, mediorum/server/serve_health.go, mediorum/server/server.go
- Makes Discovery track streaming use rendezvous for every request, only using Content Nodes that returned 200 for /health_check
- Makes sure CN returns 500 when unhealthy (including when it can't reach its db)
This fixes the `AttributeError: 'NoneType' object has no attribute 'split'` error when streaming tracks from v2 users. There will be more redirects until Qm CIDs are migrated, but this should effectively be the same latency as now because the extra request for the first byte is removed.
Tested mediorum health check locally and discovery streaming tracks from v2 and non-v2 users on staging.
=> Use rendezvous for all streams

mediorum/server/serve_blob.go
Temporarily log streams that have the x-would-block header.
It's just a log.
=> Log mp3 streams that would be blocked

discovery-provider/ddl/functions/handle_usdc_purchase.sql, discovery-provider/integration_tests/notifications/test_usdc_purchase.py, discovery-provider/integration_tests/utils.py, discovery-provider/src/models/users/usdc_purchase.py
- adds python models for usdc purchases
- includes usdc purchases in the populate_entities db utils function
- add db trigger handle_usdc_purchase that creates two notifs, one for the person buying the music and another for the person selling the music
added unit test
=> [plat-1109] Add db trigger to create usdc purchase notifications

discovery-provider/src/tasks/cache_user_balance.py
Self.<attribute> throws a python error that was preventing users' balances from getting updated in the user_cache_balance task. updated self.tattribute to be hasattr(self, <attribute>)
=> Use hasattr instead of self. in cache user balance

mediorum/server/serve_blob.go, mediorum/server/server.go
Fixes oncall issue where Discovery correctly ignores the node with an unreachable db, but mediorum still redirects to it.
We'd have to take the db offline to test. I think it's safer to just monitor on staging for a while and then release to SPs since the SP with an unreachable db is on auto-upgrade.
=> Make mediorum only redirect if db is reachable

mediorum/server/serve_blob.go, mediorum/server/serve_legacy.go, mediorum/server/serve_upload.go
- Blocks mp3 streaming from /ipfs and /content routes, and removes the corresponding log and x-would-block header
- Fixes file names replacing space chars with plus chars when downloading tracks or stems
Deployed to stage CN6 and tested downloading from it - it doesn't replace spaces with pluses anymore.
Example: https://discoveryprovider.staging.audius.co/v1/tracks/LjNAZ/stream?user_data=Premium%20content%20user%20signature%20at%201689018506695&user_signature=0x204ebcc22352f7003d127c7ffd93fc29057cf770e9e3f111c50a687ff7f35ebe127fac5f30d3d79027036f9f6ac3770b6e704b268965ed5b9fb036c2da9f9fbf1b&filename=birds%20-%20Instrumental%20%20-%20Theo%20(Audius).mp3
=> Disallow non-cidstream mp3s, and fix filename download

discovery-provider/plugins/notifications/Dockerfile, discovery-provider/plugins/notifications/package.json, discovery-provider/plugins/notifications/scripts/create-announcement.ts, discovery-provider/plugins/notifications/src/main.ts, discovery-provider/plugins/notifications/src/server/index.ts, discovery-provider/plugins/notifications/src/server/routes/memStats.ts, discovery-provider/plugins/notifications/src/utils/memStats.ts
Dockerfile has been running `npm run dev` which is bloating the allocated heap size drastically. We should at least run `npm run start` and see if we get memory issues after that.
ran `npm run dev` and `npm run start` on stage and noticed heap total differences of 336mb to 61mb respectively.
=> PLAT-1096: notifs heap fixes

discovery-provider/plugins/notifications/src/__tests__/mappings/announcement.test.ts, discovery-provider/plugins/notifications/src/processNotifications/mappers/announcement.ts
Adds web push notifs to announcements. i think we finished web push before announcements were done, and we forgot to add them back into announcements. adding them back with a test. note its purposefully without an await so we don't block on sending tehm sequentially
added unit test
=> Add web push notifications for announcements

mediorum/server/serve_legacy.go
This makes it easier to track down vague errors like:
```
{
"error": "scanning all: scanning: scanning: doing scan: scanFn: scany: scan row value into a primitive type: can't scan into dest[0]: cannot scan NULL into *string",
"message": "Internal Server Error"
}
```
Just an error line.
=> Make redirect err more informative

mediorum/ddl/add_fields_to_uploads.sql, mediorum/server/db.go, mediorum/server/serve_blob.go, mediorum/server/serve_blob_test.go, mediorum/server/serve_upload.go, mediorum/server/server.go, mediorum/server/server_basic_auth.go, mediorum/server/server_basic_auth_test.go, mediorum/server/signature/signature.go, mediorum/server/transcode.go
1. Transcode preview if a `previewStartSeconds` field is set in the POST multipart from when uploading a track
2. Edit preview via `POST /uploads/:id` with a `previewStartSeconds` field in the POST body. sig from a registered DN required to edit. This sets the upload job status to `retranscode_preview`, which kicks off a retranscode job. Discovery will persist the upload job id for each track to use for this endpoint.
Notes
- Opted to put the preview cid in the upload's `transcode_results` and to not create a new `audio_preview` template. So normal full audio transcodes and audio previews share the same `uploads` record, they're just different entries in `transcode_results`. This made more sense to me from a schema perspective - both the 320kbps downsample and the 30s clip of the …
=> Handle track preview in POST /uploads

libs/src/services/creatorNode/CreatorNodeSelection.test.ts, libs/src/services/creatorNode/CreatorNodeSelection.ts, libs/src/services/discoveryProvider/DiscoveryProviderSelection.test.ts, libs/src/services/discoveryProvider/DiscoveryProviderSelection.ts, libs/src/services/ethContracts/EthContracts.ts
Anything use old "libs" style selection won't pick a service with a minor version higher than what's registered on chain. This makes it so we accept any service with a major/minor version ahead of what's on chain.
Unit
=> [PLAT-1125] Tolerate higher minor/major versions in selection

mediorum/crudr/client.go, mediorum/crudr/crudr.go, mediorum/main.go, mediorum/server/peer_health.go, mediorum/server/serve_crud.go, mediorum/server/serve_health.go, mediorum/server/serve_health_test.go, mediorum/server/server.go
- Makes nodes poll The Graph every 30m to allow signature-gated communication with recently registered nodes. Restarts the server when these change (the alternative would be updating peers and signers variables and worrying about every usage of them now and forever in the future)
- Adds "seeding" phase so new nodes are unhealthy and don't receive requests for files they don't yet have. Seeding is flexible and considered complete when for >50% of nodes there are either no more ulids to sweep or the last ulid swept has a timestamp from the past hour
- Ignores the cid_lookup table because it will be removed soonish and would just cause issues now and later after no new v1 uploads are coming in. Staging cid_cursors are currently days old so would look like they're still "seeding," but that's …
=> [CON-773] support new nodes better

mediorum/server/serve_legacy.go
Checks for existence on disk of `storagePath` from `Files` table, and if not exists falls back to checking:
1. legacy path: `/file_storage/<cid>`
2. re-computed storagePath: `/file_storage/files/<last 3 chars of cid, offset by 1>/<cid>`
Does not try querying the db to get the dirMultihash for re-computing a third possible path because I don't think that's actually used anywhere. We can add this later if we do run into a missing image of this format.
Tested on prod usermetadata and confirmed that the (legacy) pfp is now servable for https://audius.co/audius
=> Try more legacy fallback paths when serving files

discovery-provider/plugins/notifications/src/__tests__/mappings/announcement.test.ts, discovery-provider/plugins/notifications/src/processNotifications/mappers/announcement.ts, discovery-provider/plugins/notifications/src/types/notifications.ts
makes it so we can pass a different push body than the full announcement
ran on stage for DMs
=> add push body to announcement notification

mediorum/server/cid_log_client.go, mediorum/server/monitor.go, mediorum/server/serve_health.go, mediorum/server/serve_health_test.go, mediorum/server/serve_legacy.go, mediorum/server/server.go
- Drops `cid_lookup` and related tables if schema is wrong, and restarts so they'll be re-created correctly
- Logs `Found null host(s) in cid_lookup` when `cid_lookup` has a null host, which should never happen
- Marks node as seeding/unhealthy until it has a cid_cursor to >2023-06-01 for >50% of nodes. This prevents a node from receiving a request and 404ing because it incorrectly thinks there's no other node with the file to redirect to
- Adds back simple `/status` route that was removed too early
Before deploying, I'll test on staging and then a prod node to make sure files are served and nothing is dropped when it's not supposed to.
Search in axiom for `msg` containing:
- `Found null host(s) in cid_lookup`
- `Found invalid cid_lookup schema, dropping and truncating table`
- `Failed to …
=> Fix cid_lookup schema and stay unhealthy while seeding

mediorum/server/serve_metrics.go, mediorum/server/server.go
https://github.com/AudiusProject/audius-protocol/pull/5616 mostly works when testing on prod, but the SQL query for null hosts is too slow and times out because the index on the table first sorts by multihash and then by host (`create unique index if not exists "idx_multihash" on cid_lookup("multihash", "host");`). So this removes that query and fixes an unrelated query that I also noticed "slow sql" logs for on prod.
Deploying prod hotfix.
=> Remove and fix 2 slow mediorum sql queries

libs/src/sdk/config/development.ts, libs/src/sdk/config/production.ts, libs/src/sdk/config/staging.ts, libs/src/sdk/config/types.ts, libs/src/sdk/scripts/generateServicesConfig.ts, libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.ts, libs/src/sdk/services/StorageNodeSelector/constants.ts
* Sets the bootstrapNodes in the default config for `StorageNodeSelector`. This prevents a race condition when trying to perform a write before the response from discovery has returned with a list of storage nodes
* In the case of no nodes in `StorageNodeSelector` (potentially because and `bootstrapNodes` was not passed in), await the initial discovery response before returning a selected node. This times out after 15 seconds
=> Set bootstrap nodes default for StorageNodeSelector

mediorum/server/monitor.go, mediorum/server/serve_health.go, mediorum/server/server.go
Adds health check middleware so user-facing routes return 5xx when they're unhealthy. This is important to fix a race condition where the client uses the bootstrap list of all nodes, so it isn't aware that the node is unhealthy yet.
What's currently happening:
1. Page loads and client requests image from unhealthy node
2. Unhealthy node 404s
3. Client doesn't retry
What will happen after this PR is merged:
1. Page loads and client requests image from unhealthy node
2. Unhealthy node 5xxs
3. Client refreshes list of healthy nodes from Discovery and retries a different node
Fetching images on staging. No staging nodes are unhealthy currently, but it's the same logic as before - just moved to a middleware and put in front of more routes. Should also test an upload.
=> Gate user-facing routes with health check so client knows to retry another node

mediorum/cmd/main.go, mediorum/main.go, mediorum/registrar/audius_api_gateway.go, mediorum/server/serve_legacy.go, mediorum/server/serve_upload.go, mediorum/server/server.go
When a Qm CID can't be found in the cid_lookup table, this PR makes it send a HEAD request to every healthy node to see if anyone else has the file on disk or in their cid_lookup table. In order to avoid an infinite spam loop, these HEAD requests don't do this extra check - they only look at their disk and cid_lookup table.
This is to fix an issue where some nodes have an incomplete cid_lookup table. Their cursor has moved past some CID, so it will never be aware that another node has it.
Confirmed on 2 staging nodes that they send the HEAD requests for track playback and image fetching of only Qm CIDs and that it doesn't cause an infinite loop when it's a fake/missing CID.
=> [CON-778] Mediorum: Check all healthy nodes on 404 and use GA

mediorum/ddl/ddl.go, mediorum/server/cid_log_client.go, mediorum/server/serve_legacy.go, mediorum/server/server.go, monitoring/vector/vector.toml
- Reverts checking every node for Qm CIDs on 404 because this is causing spam that's making nodes go offline (fyi @stereosteve if you have any ideas on how to make this more precise so it doesn't cause too much spam)
- Re-seeds the cid_lookup table for Qm CIDs on every node
- Stops logging from postgres container so we stop killing our logs from culturestake16 (I pushed the vector image already, so it should go out in the next audius-docker-compose update)
- The ways to test this aren't very expedient given the ongoing issue. Will look through it synchronously on staging
- Monitor healthz and the Axiom dashboard to see log spam and 404 HEADs decrease
=> Re-seed cid_lookup instead of falling back to every node

mediorum/registrar/audius_api_gateway.go
I forgot to handle case sensitivity and endpoint normalization when switching the node from The Graph to API Gateway, which I think might've caused a page.
Very simple change - doesn't really need big testing.
=> Make mediorum case insensitive again

discovery-provider/integration_tests/tasks/test_update_delist_statuses.py, discovery-provider/src/tasks/index_nethermind.py, discovery-provider/src/tasks/update_delist_statuses.py
Skip tracks and users with delists created at <= current block's timestamp (task runs after indexing the block). 
This allows delisting to proceed despite missing entities in the db while also accounting for slow indexing. Ideally and theoretically, all nodes should have every one of these track and user in their dbs, as trusted notifier gets these IDs from discovery in the first place, but the reality of the system is there are slight data inconsistencies on every node. 
If the delist timestamp > the current block's timestamp, this node is just behind on indexing and still might index the CREATE USER/TRACK tx later, so don't advance the delist polling cursor. 
If the delist timestamp <= the current block's timestamp and the entity is still not in the node's db, the node has certainly …
=> Check current block timestamp in delist task

discovery-provider/integration_tests/tasks/test_update_delist_statuses.py, discovery-provider/src/tasks/index_nethermind.py, discovery-provider/src/tasks/update_delist_statuses.py
- subtract final_poa_block from the block's number to get the correct number to query with
- only revert if will it will set the delist cursors back in time
- add the endpoint to the revert queries and updates
deploy to stage
=> Fix revert cursor blocknumber logic + misc

dev-tools/compose/docker-compose.pedalboard.yml, dev-tools/compose/docker-compose.yml, discovery-provider/integration_tests/queries/test_get_playlists.py, discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py, discovery-provider/src/queries/get_playlists.py, discovery-provider/src/tasks/entity_manager/entities/playlist.py
* Dual writes to playlist_routes for the interim so fetching by old and new styles will work. Unblocks client.
* Allows for fetches of private playlists via playlist id in API
```
audius-cmd create-playlist "857866038" --private --from ray
```
Confirmed that 
private playlist shows http://audius-protocol-discovery-provider-1/v1/full/playlists/11jkz
Confirmed that fetches work by old and new slug
http://audius-protocol-discovery-provider-1/v1/full/playlists/by_permalink/ray/playlist-d418-30620257
http://audius-protocol-discovery-provider-1/v1/full/playlists/by_permalink/ray/playlist-d418
=> [PLAT-608][PLAT-1129] Add dual playlist route writes and fix private fetches

discovery-provider/src/tasks/entity_manager/entities/playlist.py
https://github.com/AudiusProject/audius-protocol/blob/31b70d294425aa45a03dc794d5a2387966aa7885/discovery-provider/src/queries/get_playlists.py#L64
We are allowed to query by is current is fault, so the dual written migration record should be set to false.
Will test updates thoroughly on stage after
=> Fix migration route for playlists

mediorum/main.go, mediorum/server/placement.go, mediorum/server/repair.go, mediorum/server/replicate.go, mediorum/server/serve_blob.go, mediorum/server/serve_health.go, mediorum/server/serve_health_test.go, mediorum/server/serve_upload.go, mediorum/server/server.go, mediorum/server/test_main_test.go
- Adds `STORE_ALL` env var to make node store all files, including legacy/Qm CIDs, regardless of rendezvous ordering
- Removes unused `/blobs/double_check/:cid` route
Verified that stage CN12 now has all (non-Qm) CIDs in its S3 bucket. Other nodes should still only be storing CIDs when they're in the top 3 by rendezvous score.
=> [CON-733] Implement "full" content node (STORE_ALL)

discovery-provider/src/tasks/entity_manager/entities/user.py, discovery-provider/src/tasks/entity_manager/utils.py
seeing a lot of `error deserializing metadata` errors recently in the [logs](https://app.axiom.co/audius-Lu52/stream/stage-discovery?ig=&q=%7B%22op%22%3A%22and%22%2C%22field%22%3A%22%22%2C%22children%22%3A%5B%7B%22field%22%3A%22msg%22%2C%22op%22%3A%22contains%22%2C%22value%22%3A%22error%20deserializing%20metadata%22%7D%5D%7D) (no impact on write functionality). this was from this [change](https://github.com/AudiusProject/audius-protocol/pull/5406/files#diff-5f2036d31b9e5c951ef78b6688b2a253dff55168fad03a59c7bc76b9ffb992e2).
`parse_metadata` expects the metadata param to be a string and will throw an error if it is a dict. in `validate_user_tx`, `params.metadata` was already deserialized into a dict when building the params for UPDATE USER events, but not for CREATE USER events. this will …
=> Fix noisy metadata deserialization error

discovery-provider/src/tasks/entity_manager/entities/user.py
mutli tx signup will not have metadata on user creation so no prev metadata is found. in this case, just merge with an empty dict.
patched on foundation node.
=> Fix user merge in multi tx signup

mediorum/ddl/ddl.go
Skips moving .tmp files to sharded location during one-time migration. These are artifacts of the fileblob driver.
=> Ignore .tmp files when sharding

discovery-provider/es-indexer/src/indexers/PlaylistIndexer.ts, discovery-provider/src/models/playlists/playlist.py
albums were not properly accounted for in the permalink returned from the backend, updating to return the proper permalink for albums
checking the playlist endpoint returns the correct permalink for an album
=> Add album routes to playlist permalinks project

mediorum/server/transcode.go
Fix using a key with the shard because the path separator isn't allowed in os.CreateTemp.
=> Use tmp file key without slash

discovery-provider/src/api/v1/tracks.py, libs/src/sdk/api/generated/full/apis/TracksApi.ts
Tried this with locally linked libs:
`await audiusSdk.full.tracks.getBulkTracks({ permalink: ['handle3131/title-55f4'] })`
Got this error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'map')
at TrackFullFromJSONTyped (TrackFull.ts:437:1)
at TrackFullFromJSON (TrackFull.ts:399:1)
at FullTrackResponseFromJSONTyped (FullTrackResponse.ts:119:1)
at FullTrackResponseFromJSON (FullTrackResponse.ts:103:1)
at JSONApiResponse.transformer (TracksApi.ts:241:1)
at JSONApiResponse._callee6$ (runtime.ts:389:1)
at tryCatch (regeneratorRuntime.js:86:1)
at Generator._invoke (regeneratorRuntime.js:66:1)
at Generator.next (regeneratorRuntime.js:117:1)
at asyncGeneratorStep$1 (transactionHandler.ts:413:1)
```
Offending line according to error:
`'followeeReposts': …
=> sdk and discovery: Fix full bulk tracks endpoint

discovery-provider/src/api/v1/tracks.py
#5693 introduced a breaking change to DN API by making _every_ type of request to the bulk tracks endpoint return an array. Unfortunately, several clients are already using the bulk tracks endpoint with the deprecated slug+handle approach that only returns a single track. Thus, to keep backwards compatibility, this change changes the documentation of the endpoint to show that it returns an array _without_ marshalling the response into an array format, and instead conditionally use the correct marshallers manually.
Confirmed locally that using slug + handle = object in data field, and using id or permalink = array in data field, and that JSON schema has array as the return type
=> Fix: Don't break existing bulk get tracks endpoint for slug + handle

libs/src/sdk/services/DiscoveryNodeSelector/types.ts, libs/src/sdk/services/EntityManager/EntityManager.ts, libs/src/sdk/services/EntityManager/constants.ts, libs/src/sdk/services/EntityManager/types.ts, libs/src/sdk/services/Storage/Storage.ts, libs/src/sdk/services/Storage/constants.ts, libs/src/sdk/services/Storage/types.ts, libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.ts, libs/src/sdk/services/StorageNodeSelector/constants.ts, libs/src/sdk/services/StorageNodeSelector/types.ts
Makes it optional to specify logger for StorageNodeSelector, and adds some nice comments for the config
=> Add documentation to StorageNodeSelector config, make logger optional

mediorum/cidutil/cidutil.go, mediorum/cidutil/cidutil_test.go, mediorum/server/repair.go
Before rolling out the migration of Qm files to the v2 buckets, repair.go should ignore _all_ Qm keys rather than just ones that are exact CIDs. Otherwise, when repair.go sees a key like "Qmwhatever/150x150.jpg" it will try to replicate it and possibly run out of disk space.
Ran the Qm migration on stage cn9 and and stage usermetadata, and used this PR to confirm that it makes other nodes ignore the migrated files in repair.go (to avoid over replicating and running out of disk space).
=> Ignore non-CID Qm keys in repair.go

libs/src/services/solana/SolanaWeb3Manager.ts
For functions where all objects in the config are optional, we should default init them to empty objects to avoid throwing errors when no config is passed.
=> Default init config objects for userbanks functions

identity-service/src/routes/stripe.js, libs/src/services/identity/IdentityService.ts
Updates `/stripe/session` endpoint on identity to support creating usdc sessions in addition to sol.
Have not been able to test locally - all requests to stripe are hitting 500. Would like to merge and test on stage.
=> [PAY-1666] Update identity stripe endpoint to support usdc

discovery-provider/es-indexer/src/indexNames.ts, discovery-provider/integration_tests/notifications/test_playlist.py, discovery-provider/plugins/notifications/src/__tests__/mappings/addTrackToPlaylist.test.ts, discovery-provider/plugins/notifications/src/processNotifications/mappers/addTrackToPlaylist.ts, discovery-provider/src/tasks/entity_manager/entities/playlist.py
adds a check against old current row for a playlist that if a track exists in the old instance, don't send a push because it was already there
Tested on stage but stage has a bug where playlist rearrangements are not working. Works on production.
=> PLAT-1161: skip push on playlist update and if track already existed

discovery-provider/ddl/migrations/0018_clean_up_subgenre.sql
Mobile uploads were using genre - subgenre. So they'd fail EM indexing genre validation.
Make `Electronic - Tech House` -> `Tech House`.
=> Cleanup subgenre db migration

libs/src/services/discoveryProvider/DiscoveryProviderSelection.ts
This code still lives on as part of the quorum fetching for RewardsAttester. Since we bumped to `0.4.1` but the on-chain version is still `0.3.98`, the patch version of the latter is _more_ than the patch version of the former, yet the former is newer and should still be used.
Thus, since only a single node is still on `0.3.98`, RewardsAttester cannot find 3 uniquely owned DiscoveryNodes and claiming rewards fails.
Not tested
=> Don't only check patch in version check

mediorum/ddl/cid_lookup.sql, mediorum/server/cid_log_client.go
Just removes the backfill instead of the whole migration because this is needed as a hotfix. We can also remove the whole thing soon, though.
~~I'll deploy to prod CN3 before merging. This migration recently ran there and got stuck on the backfill.~~ Works on CN3.
=> Remove expensive cid_lookup backfill and slow down beaming

libs/src/sdk/types/File.ts
* `file-type/browser` was being imported in a node / mobile environment which is causing mobile builds to fail
=> Fix file-type import

libs/src/services/solana/SolanaWeb3Manager.ts
We aren't passing the mint to `getTokenAccountInfo`, so attempt to look up a userbank for USDC will fail due to using the wrong key.
Tested locally against client
=> Fix userbank lookup for USDC

libs/src/sdk/api/chats/ChatsApi.ts
By not setting the chat secret in the memory cache here, the user will have to refetch the chat to get the secret when sending the first message. This ensures the creation of the chat was successful before setting the private key in memory cache
Have not tested. Will need to test with client
=> [PAY-1693] SDK: Don't cache chat secrets on create, make client refetch them

libs/src/services/ethContracts/ServiceProviderFactoryClient.ts, libs/tests/governanceTest.js, libs/tests/helpers.js, libs/tests/stakingTest.js, mediorum/server/serve_health.go
506 for unregistered nodes on health check, and make registration pass `allow_unregistered` query param to bypass.
Deployed to stage CN12 and confirmed that when using an unregistered wallet it returns 200 with `?allow_registered=true` in the `/health_check` and 506 otherwise.
=> Separate health check for registration

mediorum/server/monitor.go, mediorum/server/serve_blob.go, mediorum/server/serve_health.go, mediorum/server/serve_health_test.go, mediorum/server/serve_metrics.go, mediorum/server/server.go
Makes nodes self-mark as unhealthy when they're unable to count the # of upload records in db. Healthz shows that this is a proxy for general db health.
Deployed to stage cn9 and verified that the node was healthy and showed empty upload count errors.
=> [CON-811] Self-mark unhealthy when unable to query upload count

discovery-provider/integration_tests/api/v1/utils/resolve_url_test.py, discovery-provider/src/api/v1/playlists.py, discovery-provider/src/api/v1/tracks.py, discovery-provider/src/api/v1/utils/resolve_url.py
Resolve currently not working because slug/handle route isn't being used.
Probably should go out before client changes, but after/with migration to fix the special characters.
```
audius-cmd create-user freddie_mercury
audius-cmd upload-track --from freddie_mercury --title "Bohemian Rhapsody"
audius-cmd create-playlist 961132438 --from freddie_mercury
curl http://audius-protocol-discovery-provider-1/v1/playlists/by_permalink/freddie_mercury/playlist-7123
curl http://audius-protocol-discovery-provider-1/v1/resolve?url=/freddie_mercury/playlist/playlist-7123
```
=> Fix resolve to use slug/handle for collections

discovery-provider/ddl/migrations/0021_backfill_playlist_routes_fixed.sql
Tested this against a prod clone.
The previous backfill wasn't sanitizing existing strings the way we sanitize in client, causing lookup mismatches for certain playlists (see [here](https://audius-internal.slack.com/archives/CFNP3QBCG/p1691507620317919))
this reruns the migration with more strict sanitizing
=> Fix backfill of playlist routes to sanitize like client

discovery-provider/src/utils/helpers.py, identity-service/src/rateLimiter.js
* Add log for flask requests containing `app_name` param. This will be used to create an axiom chart for top apps sorted by read counts
This could be a pretty big log volume increase, is this ok?
* Add log for rate limiting on developer apps. This will be used to create an axiom chart for apps exceeding rate limits
Checked logs locally
=> [C-2942] Improve logs around developer app rate limits and reads

mediorum/server/cuckoo.go, mediorum/server/replicate.go, mediorum/server/serve_blob.go, mediorum/server/server.go
As we've migrated millions of Qm files to the v2 system, the blobs query on redirect is sometimes slow. This PR makes it so nodes use a cuckoo filter for fast lookup when redirecting for v2 files (or Qm files that were migrated into the v2 system). We still fall back to the existing blobs table query, and we use the same hostHasBlob check before redirecting to ensure we'll never redirect based on a cuckoo false positive.
Also:
- Removes expensive Files table query which briefly maxes out postgres CPU every hour
- Puts CID back at the end of the info route because some SPs' reverse proxies are url-unencoding slashes. Example: [figment8](https://audius-content-8.figment.io/internal/blobs/QmRirCtcym58PJv61nAy23zrcjqa6euT72aEcCN6VPa74t%2F150x150.jpg/location) and …
=> [CON-817] Try cuckoo filter first for faster v2 lookup

mediorum/server/cuckoo.go, mediorum/server/replicate.go, mediorum/server/serve_blob.go
Redirects are still slow in many cases because they wait for a 1 second timeout when checking a node that's supposed to have the CID (but the node doesn't have it because of a cuckoo false-positive or because it's unhealthy but thinks it's healthy). This PR races 3 of these `hostHasBlob` checks at once to avoid this second of added latency from some redirects.
I'll test redirects like I did for https://github.com/AudiusProject/audius-protocol/pull/5764 on staging with CN9 and CN10 before merging.
=> [CON-818] Race mediorum redirects 5 at a time

.circleci/src/jobs/release-audius-sdk.yml, .circleci/src/jobs/release-governance.yml
* Upgrade `release-audius-sdk` and `release-governance` to node 18.17
This one is kinda hard to test, will see if sdk beta releases are successful on main
=> [INF-437] Upgrade ci jobs to node 18.17

libs/src/sdk/api/albums/AlbumsApi.test.ts, libs/src/sdk/api/playlists/PlaylistsApi.test.ts, libs/src/sdk/api/tracks/TracksApi.test.ts, libs/src/sdk/api/users/UsersApi.test.ts, libs/src/sdk/services/EntityManager/EntityManager.ts, libs/src/sdk/services/EntityManager/constants.ts, libs/src/sdk/services/EntityManager/types.ts, libs/src/sdk/services/Storage/Storage.ts, libs/src/sdk/services/Storage/constants.ts, libs/src/sdk/services/Storage/types.ts, libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.ts, libs/src/sdk/services/StorageNodeSelector/constants.ts, libs/src/sdk/services/StorageNodeSelector/types.ts
On staging, we were seeing logs for health checks on production. This is because we create default services _before_ checking if they're needed. 
In `Storage`, we require `StorageNodeSelector`. Despite it not being needed, since we pass in our own `storageNodeSelector` via config, we initialize a new default `StorageNodeSelector` in our `defaultStorageConfig` and then use object spreading to override that default one with our defined one.
In `StorageNodeSelector`, we require a `DiscoveryNodeSelector`, and default to a prod `DiscoveryNodeSelector`, and in `StorageNodeSelector` we immediately invoke `getSelectedNode()`. Though we specified a `DiscoveryNodeSelector` in the SDK config, the _default_ `StorageNodeSelector` initializes a _default_ `DiscoveryNodeSelector`, so we get the …
=> [C-2947] Don't default services (except logger)

discovery-provider/src/api/v1/models/activities.py, discovery-provider/src/api/v1/models/playlists.py, discovery-provider/src/api/v1/users.py
Generated types were not correct for new library endpoints
-ItemType was `object` instead of 'track' or 'playlist'
-CollectionActivity had `tracks` as required but endpoints were returning them as null so the generated SDK methods would fail due to a type error
=> Fix activity sub-types for library endpoints PAY-1679

mediorum/server/serve_upload.go, mediorum/server/server.go, mediorum/server/transcode.go
- Adds cache to avoid hitting the db for every image (only caches the uploads `:jobId/:variant` mapping, not responses)
- Adds timing headers to image requests to expose slow steps. Examples (may need to add queryparam to bypass Cloudflare cache when testing):
- [this](https://usermetadata.audius.co/content/QmWX4bbsPoSikz129PsUu9i6oqqMfZ3Tv1pABjMVY7qiqF/150x150.jpg) has plenty of healthy hosts in the fast, in-memory cuckoo lookup, but it still takes 1.5s to redirect even from a beefy node
- [this](https://audius-content-8.cultur3stake.com/content/01H7DM30TZWPBBTDWJJ614AEYH/150x150.jpg) is extremely slow (8 seconds) because culturestake isn't aware of the upload because another culturestake node did the transcoding and has a messed up DNS or reverse proxy
Check the headers where this is …
=> [CON-819] Cache image lookup and add timing headers

discovery-provider/src/tasks/entity_manager/entity_manager.py
This helper was added here: https://github.com/AudiusProject/audius-protocol/pull/5662/files
Unfortunately, if something gets skipped due to a validation issue, params is not populated and also doesn't really makes sense to use in this case because it was just a shortcut to grab the block information.
1. Pull the block information out of the loop and pass to get_records_to_save
2. Fix some types
Probably deserves another test, but for now will assert CI passes and merge to unblock stage
=> Fix params usage in `get_records_to_save`

discovery-provider/plugins/pedalboard/packages/basekit/src/app.ts, discovery-provider/plugins/pedalboard/packages/basekit/src/db.ts, discovery-provider/plugins/pedalboard/packages/basekit/src/index.ts
moves db initializers to a place where they can be initialized in either app or on their own with ease
=> PLAT-1173: move db initializers around

mediorum/server/serve_legacy.go
Adds simple logs to confirm if any traffic is hitting paths we want to deprecate.
Check the logs for:
- `successfully served image from non-CDK disk`
- `successfully served non-image from non-CDK disk` (also check `isAudioFile` property to see if it was just metadata)
=> [CON-823] Log when serving from non-CDK disk

mediorum/server/serve_blob.go, mediorum/server/serve_health.go, mediorum/server/serve_upload.go, mediorum/server/server.go
- Stops serving content from non-CDK disk, and adds deprecated route to test serving from non-CDK disk if needed
- Allows unhealthy nodes to serve content as a last resort when they're confirmed to have it and able to query their db (required to check for delist status)
Will soak on staging to confirm images and tracks continue to be served as expected.
=> [CON-823] Deprecate serving from non-CDK disk

discovery-provider/ddl/migrations/0022_backfill_playlist_routes_like_client.sql
The first and last slash are escaping the ! and ] punctuation so those two punctuation characters are not getting filtered out in the migration. bc this hasn't been run on prod yet, we can edit the migration in place instead of making a follow on file 
tested against prod clone
=> Rm slashes from playlist routes backfill

discovery-provider/integration_tests/queries/test_get_track_library.py, discovery-provider/src/queries/get_track_library.py
Reimplements the track library query to not fetch tracks until the end, greatly improving perf allowing us to filter again. Also simplifies the query a bit in my opinion, at the cost of losing some typehints
tested with prod clone locally
```sql
SELECT
anon_1.blockhash,
anon_1.blocknumber,
anon_1.user_id,
anon_1.is_current,
anon_1.handle,
anon_1.wallet,
anon_1.name,
anon_1.profile_picture,
anon_1.cover_photo,
anon_1.bio,
anon_1.location,
anon_1.is_storage_v2,
anon_1.metadata_multihash,
anon_1.creator_node_endpoint,
anon_1.is_verified,
anon_1.artist_pick_track_id,
anon_1.created_at,
anon_1.updated_at,
anon_1.handle_lc,
anon_1.cover_photo_sizes,
anon_1.profile_picture_sizes, …
```
=> [PAY-1643] Re-add support for track library filter query

mediorum/server/serve_blob.go, mediorum/server/serve_legacy.go, mediorum/server/serve_metrics.go, mediorum/server/serve_upload.go, mediorum/server/server.go, monitoring/healthz/src/DiscoveryHealth.tsx
- Adds to `/internal/metrics` route a list of CIDs (capped at 100K) that were attempted and successfully returned from a legacy (non-CDK disk) path
- Exposes this new metrics in healthz "Legacy Served" column of format "<attempted> | <successful>"
Deployed to CN10, queried a legacy CID that doesn't exist, and verified that the counter increased on healthz
You can click the link in healthz to easily jump to /internal/metrics:
<hr />
=> [CON-829] Add legacy paths counter & expose in healthz

mediorum/server/serve_legacy.go, mediorum/server/serve_metrics.go, mediorum/server/server.go
- There's a low amount of concurrent reads/writes for tracking legacy serves, which could cause an unexpected panic. Although the foundation nodes haven't had this happen yet, I'm adding this just to be safe.
- Blocks serving segments and metadata through the legacy path. This is pretty safe because these are both supposed to have been stopped being supported a long time ago and because this is only on the fallback legacy path that which we're also aiming to stop supporting.
Re-tested the legacy tracking on stage CN10, and verified the following links:
- (metadata) https://creatornode10.staging.audius.co/content/QmT2SUjUsmbJ4Y1kpbFpjMepTkR3AHrM5231Tn1eoPoTXZ
- (segment) https://creatornode10.staging.audius.co/content/QmXUbQuv5yG7HjK6WBFducdYkX2kabZ6TgUAZYVZb2c7wL
- (mp3 - still streams) …
=> Add RWMutex to legacy path counts, and block segments+metadata

discovery-provider/ddl/migrations/0025_add_track_price_history_fkey.sql
Just add a fkey constraint so we don't have to manually delete from track_price_history on revert. No other change is needed because track_price_history does not maintain is_current.
Existing tests pass. Ran migration on sandbox.
=> Add track_price_history fkey

discovery-provider/ddl/functions/handle_repost.sql, discovery-provider/ddl/functions/handle_save.sql, discovery-provider/ddl/migrations/0021_fix_album_repost_save.sql, discovery-provider/integration_tests/models/test_aggregate_counters.py, discovery-provider/integration_tests/queries/test_get_collections_library.py, discovery-provider/integration_tests/queries/test_populate_playlist_metadata.py, discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py, discovery-provider/integration_tests/tasks/test_update_aggregates.py, discovery-provider/src/utils/helpers.py
My fix https://github.com/AudiusProject/audius-protocol/pull/5467/files wasn't complete. That fix was intended to use album repost_type so the handle_repost trigger would recognize an album vs playlist.
The client still sends playlist entity type so existing reposts wouldn't be found https://github.com/AudiusProject/audius-protocol/blob/main/discovery-provider/src/tasks/entity_manager/entity_manager.py#L736-L737. This allows users to repost multiple times, bypassing the duplicate check.
This change modifies the trigger to just check the playlist table and use that to determine is_album instead of the repost_type. It also cleans up duplicate reposts and ensures we only use playlist repost_type.
Tested on sandbox. Migration took a while but worked ~ 5-10 mins.
_Please describe the tests …
=> Fix album repost triggers

libs/src/sdk/services/Storage/Storage.ts
I introduced a bug when adding browser upload support to the sdk. The content-type header only needs to get set server side, but it was being set to `formData.getBoundary`
Tested upload from server and browser
=> Fix SDK storage upload header

discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py, discovery-provider/src/tasks/entity_manager/entities/social_features.py
Following up 
https://github.com/AudiusProject/audius-protocol/pull/5767/files#diff-ef86d71348b6d07b1d29a5a8f6cb09baa689e87f656e41bfc60b798edd1ccea0
Forgot to make EM always use playlist type instead of album type when indexing repost / saves.
Tested on stage. Confirmed repost/save worked and aggregates, icons looked right. 
=> Follow on fix social feature type

discovery-provider/src/api/v1/helpers.py, discovery-provider/src/queries/query_helpers.py
Client still uses the v0 API in some places, including initial caching of the user, so add cached image cid fields to the v0 endpoints. Also clean up v1.
v1 done in https://github.com/AudiusProject/audius-protocol/pull/5783
Deploy to stage, test against client changes with breakpoints to make sure correct direct links are used
=> Add image cid caching to v0 api

mediorum/server/monitor.go, mediorum/server/peer_health.go, mediorum/server/serve_health.go, mediorum/server/serve_health_test.go, mediorum/server/server.go, monitoring/healthz/src/DiscoveryHealth.css, monitoring/healthz/src/DiscoveryHealth.tsx, monitoring/healthz/src/index.css
- Nodes self-mark as unhealthy when there's any node that they can't reach but that a majority of peers report as reachable
- Nodes mark other nodes as unhealthy when there's any node that the other node can't reach but that a majority of peers report as reachable
- Displays peer reachability in healthz with slightly nicer styling and dark mode
- Deployed to stage CN8 and CN10 while taking CN7 offline
- Will add some unit tests
=> [CON-822] Expose peer reachability in health check

discovery-provider/ddl/functions/handle_playlist.sql, discovery-provider/integration_tests/queries/test_populate_user_metadata.py, discovery-provider/src/queries/notifications.py, discovery-provider/src/tasks/entity_manager/entity_manager.py
Fixes two playlist notification flows impacted by removing historical is_current false records.
* Identity is currently still polling discovery /notifications for indexing to serve scheduled emails. This is deprecated on stage but not on prod yet. Checking for null here is a quick workaround to unblock indexing but some schedule email notifs may be missing. Schedule e-mails should be moved to discovery plugin asap then it'll work correctly. 
* The handle_playlist trigger used to insert into the notifications table is used for reads and push notifs. This also referenced a previous record. We can query the revert_blocks table to get the previous state but this does require modifying the session flush.
Tested on stage DN1. Confirmed playlist notif works.
_Please describe the tests that you …
=> Fix publish playlist notifs

solana-programs/payment-router/Anchor.toml, solana-programs/payment-router/README.md, solana-programs/payment-router/programs/payment-router/Cargo.toml, solana-programs/payment-router/programs/payment-router/src/lib.rs, solana-programs/payment-router/programs/payment-router/src/router.rs, solana-programs/payment-router/programs/payment-router/tests/tests.rs, solana-programs/payment-router/scripts/testCreatePaymentRouterBalanceAta.sh, solana-programs/payment-router/tests/payment-router.ts, solana-programs/staking-bridge/Anchor.toml, solana-programs/staking-bridge/Cargo.lock, solana-programs/staking-bridge/README.md, solana-programs/staking-bridge/programs/staking-bridge/Cargo.toml, solana-programs/staking-bridge/programs/staking-bridge/src/constant.rs, solana-programs/staking-bridge/programs/staking-bridge/src/error.rs, solana-programs/staking-bridge/programs/staking-bridge/src/lib.rs, solana-programs/staking-bridge/programs/staking-bridge/src/raydium.rs, solana-programs/staking-bridge/programs/staking-bridge/src/wormhole.rs, solana-programs/staking-bridge/programs/staking-bridge/tests/raydium_tests.rs, solana-programs/staking-bridge/programs/staking-bridge/tests/utils.rs, solana-programs/staking-bridge/programs/staking-bridge/tests/wormhole_tests.rs, solana-programs/staking-bridge/scripts/testCreateStakingBridgeBalanceAtas.sh, solana-programs/staking-bridge/tests/staking-bridge.ts
Update implementation to use anchor builtin macros for token accounts.
Add rust unit tests for both the payment router and staking bridge programs.
This PR itself has the tests. They all passed.
Note that integration tests already exist via our anchor tests and the scripts I wrote for running them.
To triple check, I redeployed the programs and sent transactions for a raydium swap, a wormhole tranfer, and payment routing. They all succeeded.
=> [PAY-1696][PAY-1697] - Update implementation and add rust unit tests

discovery-provider/src/api/v1/helpers.py
Seeing some `Exception fetching image cids for id: 01H53B3Z8ZBY5ZQ3JNYJRXG957: asyncio.run() cannot be called from a running event loop` in the logs on stage and prod. Not able to trigger this myself when clicking through the client or querying the API but manually creating a new event loop to run `race_requests` like this should fix this.
This exception doesn't impact users -- when this happens the client just falls back to using the old image url format, which redirects.
Deployed to stage, queried API and clicked around the client. No exceptions arose and cid fetching worked as expected.
=> Fix asyncio errors when attempting to fetch image cids in API

discovery-provider/src/queries/query_helpers.py
Querying 1 column (`Subscription.user_id`) directly with sqlalchemy seems to return an array of tuples, which was causing all `does_current_user_subscribe` fields to be false.
(No user impact. This field isn't used by the client yet.)
Tested on stage, verified field populated correctly via client debugger
=> Fix subscriptions api query

discovery-provider/src/queries/get_track_stream_info.py
streaming this delisted track currently causes an internal server error (https://discoveryprovider.audius.co/v1/tracks/jNkgo/stream) because we're trying to get a field from a none type object. we change that none type object to be an empty object 
tested on a sandbox by curling the same stream endpoint for this track and confirming a failed to find resource error message is returned instead of internal server error 
=> [plat-1188] fix bug where delisted tracks cause internal server error

discovery-provider/src/tasks/update_delist_statuses.py
Two nodes (https://audius.w3coins.io/ and https://audius-discovery-7.cultur3stake.com/) are stuck because a delist from February has a slightly different format than the other delist `createdAt` formats
```
update_delist_statuses.py \| exception while processing track delists: time data '2023-02-08 18:09:31+00' does not match format '%Y-%m-%d %H:%M:%S.%f+00'
```
Other nodes are fine because they indexed this record before the `datetime.strptime` logic was introduced (necessary for the comparison to the last indexed block's timestamp). The two nodes must be catching up after being stalled a long time.
Fix to handle timestamps without decimals - these should be the only two formats.
_Please describe the tests that you ran to verify your changes. Provide repro instructions & any …
=> Fix datetime parsing in TN delister

discovery-provider/integration_tests/queries/test_get_usdc_purchases.py, discovery-provider/src/api/v1/users.py, discovery-provider/src/queries/get_usdc_purchases.py, discovery-provider/src/queries/query_helpers.py, libs/src/sdk/api/generated/full/apis/UsersApi.ts
Adds `buyer_name` as a sort method for the sales table usecase of the purchases endpoint
It hasn't!
=> [PAY-1759] Allow Sales endpoint to be sortable buy buyer name

discovery-provider/src/tasks/entity_manager/entities/user.py, discovery-provider/src/tasks/entity_manager/entity_manager.py
Associated wallets indexing is impacted by the migration to index without historical records. This table breaks our typical pattern where 1 transaction -> 1 row because in this case 1 user update can trigger multiple rows per wallet. The bug lies in assuming 1 wallet per user ID and chain and updating is_current false. Now, we just need to fetch every wallet relevant to the user and update associated wallets table to reflect the metadata exactly. This isn't optimal performance wise but it's a quick solution to get it working. Stems / Remixes operate in a similar way.
Tested on a prod sandbox confirmed updating multiple wallets across chains works. Will do more testing before merging.
_Please describe the tests that you ran to verify your changes. Provide repro instructions & any …
=> Fix associated wallets indexing without is_current false

discovery-provider/plugins/notifications/src/__tests__/mappings/tastemaker.test.ts, discovery-provider/plugins/notifications/src/processNotifications/mappers/tastemaker.ts
we weren't sending any data to the client for mobile deep linking to know where to navigate on opening apush notif, adding that data here. matches fav of repost data which also uses the same handler in use notif navigation on the client side
=> Fix tastemaker mobile deep linking from push notif

mediorum/crudr/crudr.go, mediorum/crudr/op.go, mediorum/ddl/ddl.go, mediorum/server/db.go, mediorum/server/serve_metrics.go, mediorum/server/server.go
`ops` is too big to handle this frequently occurring query `SELECT * FROM “ops” WHERE host = ‘https://creatornode2.audius.co/’ AND ulid > ‘01H78V9M1MFQTP91PY8PM8CVQQ’ ORDER BY ulid asc LIMIT 10000`!
so partition by `host`, which seems the most performant way forward (compared to a composite ulid, host index) based on extensive testing by theo and me.
the migration should take ~ 0.3 hrs. stagger start times over a 12h span so entire network isn't down after the release.
deployed to stage and prod node
=> Partition ops

mediorum/ddl/ddl.go
is currently printing in nanoseconds which is kind of annoying
audius-compose up locally, check logs
`{"time":"2023-08-30T19:27:05.31085984Z","level":"INFO","source":{"function":"mediorum/ddl.schedulePartitionOpsMigration","file":"/app/ddl/ddl.go","line":101},"msg":"scheduling partition ops migration","time":"1h50m0s"}`
=> Format time duration string in log

discovery-provider/ddl/migrations/0021_fix_album_repost_save.sql
Killing active queries at the beginning of the transaction didn't completely prevent deadlocks. Server read requests could still block this migration. It seems like postgres will acquire migrations as it goes through the transaction. Explicitly acquiring locks at the beginning will make sure it has priority before another request can acquire a read lock.
I ran this on prod DN3 but added a bogus statement at the end to make sure the transaction rolled back. This did not deadlock.
=> Explicitly lock tables before migration

discovery-provider/src/eth_indexing/event_scanner.py
index_eth is stuck right now. i only happened to notice and investigate but we need better monitoring around celery errors. i'm not sure the scope of the impact this has. i don't think we even need checks here because the EventData should enforce int but this will fix it.
log_index is 0 so it evaluates to false.
```
raised unexpected: Exception('logIndex not found on event 0')
```
tested on sandbox.
=> Fix eth indexing log_index check

mediorum/ddl/ddl.go
cn3 is migrating ops right now and taking longer than expected and we want either cn2 and cn3 to be up at all times, since they store a lot of legacy data. delay cn2's migration time to 4 hours after startup to give cn3 more leeway. right now cn2 tries to migrate 20 minutes after startup, so i have to keep deleting the scheduled migration every 20 minutes until cn3 finishes.
=> delay cn2 migration

discovery-provider/plugins/pedalboard/apps/relay/package.json
updating SDK, this mainly removes those pesky health checks that aren't relevant on stage
ran locally and logs cleared up
```
npm run dev
> relay@0.1.0 dev
> ts-node-dev --respawn ./src/index.ts
[INFO] 11:16:47 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 4.9.5)
{"level":30,"time":"2023-09-01T17:16:49.958Z","name":"relay","msg":"running on dev network"}
{"level":40,"time":"2023-09-01T17:16:49.959Z","name":"relay","msg":"anti abuse not configured and won't be enforced"}
{"level":30,"time":"2023-09-01T17:16:51.225Z","name":"relay","msg":"regenerated all signing wallets"}
processes 5
{"level":30,"time":1693588611255,"pid":60364,"hostname":"alecs-MacBook-Pro","msg":"Server listening at http://0.0.0.0:6001"}
```
=> Relay: update sdk version

discovery-provider/src/api/v1/tracks.py, mediorum/server/replicate.go, mediorum/server/serve_blob.go, mediorum/server/serve_upload.go, mediorum/server/server.go
- Discovery track streaming: try all nodes (including unhealthy) in rendezvous order, 5 at a time, with 2s timeout each. Cache for 10 minutes (up from 2 minutes)
- Mediorum legacy disk check: replace its usage in v2 image route with racing instead of sequential fallbacks, so we can remove the disk check function separately and easily when we're ready to fully remove legacy support
1. Deployed to stage cn9 and stage dn2. On staging client, press "d" and set it to stage dn2
2. Go to a profile and scroll back a bit to find some Qm tracks. They all seem to 302 pretty quickly, even if some of the 206s take a bit longer for whatever reason
=> [CON-846] Race discovery track streams v2 image fallbacks

discovery-provider/src/api/v1/tracks.py
Try all nodes in rendezvous order, following redirects, with a 5s timeout and 30min cache.
=> Increase track stream redirect timeout to 5s and cache 30min

solana-programs/staking-bridge/programs/staking-bridge/src/constant.rs, solana-programs/staking-bridge/programs/staking-bridge/src/error.rs, solana-programs/staking-bridge/programs/staking-bridge/src/lib.rs, solana-programs/staking-bridge/programs/staking-bridge/src/raydium.rs, solana-programs/staking-bridge/programs/staking-bridge/tests/raydium_tests.rs
Explicitly check that the program is being invoked with the expected AMM and market accounts.
```
cargo test-sbf
```
=> Add checks for AMM and serum market addresses in staking-bridge

mediorum/go.mod, mediorum/go.sum, mediorum/server/cuckoo.go, mediorum/server/serve_blob.go, mediorum/server/serve_metrics.go, mediorum/server/server.go
Replaces various cid "lookup" strategies (cuckoo / blobs table / healthy / unhealthy) with a simpler one that simply races all hosts 5 at a time and caches result on success.
Since discovery will ask nodes one at a time in rendezvous order, that means in practice each server should only be caching 1/N of CIDs, which improves cache coherence and eveness.
=> mediorum: redirect cache

discovery-provider/ddl/migrations/0028_fix_non_gated_track_premiun_conditions.sql
Some regression caused a few non-premium tracks to have premium conditions. This migration fixes it by setting those conditions to null, as they should be.
Query looks overly weird because the simple oneliner takes forever. We may be missing indexes, but I didn't want to dive too deep on this at this moment.
Testing on stage DN2.
=> Remove premium conditions for non-premium tracks

mediorum/server/placement.go, mediorum/server/repair.go
Makes repair.go start replicating Qm CIDs.
- `make test` works.
- I'll roll out to staging and then foundation nodes first.
- The headroom cap is still in place (nodes stop replicating when there's <200GB of disk remaining).
=> [CON-828] Replicate Qm CIDs

discovery-provider/src/utils/helpers.py
Current logging of PID is unreliable because the docker container pid namespace is different than the host so we can't map it to the insights on GCP. We can just log the cpu and mem usage on stage to figure out what's causing OOM on stage.
=> Log cpu / mem on stage

discovery-provider/src/tasks/index_rewards_manager.py
If we encounter a bad transaction ([example](https://solscan.io/tx/5FBJZAzd7mvKSncNJiTNoDE2V52yT4Sum13p6EMYa5nTQG7SKy8QV1ms7Ssft2AMccRBXpfQacdBA5u3WVhY3j6x)), the indexer will get stuck in a state where it repeatedly tries to fetch the transaction, errors, then tries to re-fetch the same tx. This will continue until there are enough "good" transactions to fill a whole batch, at which point the indexer will skip the bad tx, but also potentially skip other txs that occurred around the same time as the bad tx.
Not tested
=> Rewards indexer skips solana transaction fetch fails

discovery-provider/nginx_conf/nginx.conf
Catch `nil` value in RPS counter when there haven't been enough requests to endpoints that track RPS.
On sandbox:
http://34.72.186.34:5000/request_count
=> Return 0 rps when undefined

discovery-provider/src/api/v1/helpers.py, discovery-provider/src/api/v1/models/users.py, discovery-provider/src/api_helpers.py, discovery-provider/src/queries/query_helpers.py, discovery-provider/src/tasks/entity_manager/entities/user.py, discovery-provider/src/utils/elasticdsl.py, discovery-provider/src/utils/helpers.py
The user feed in the client is still using non-direct URLs for images because the feed API resp (which uses es-indexer) doesn't have the cached cid fields.
Deployed to stage, tested feed used direct image URLs.
=> Surface image cid cache in feed endpoints

mediorum/server/repair.go
Makes repair.go replicate for nodes that are top 3 rendezvous even when not in cleanup mode.
These still only happen in cleanup mode:
- validating/deleting invalid CIDs
- replicating when not in top 3 rendezvous but when CID is under-replicated
- deleting over-replicated
=> Make repair.go replicate isMine in replicate mode

mediorum/Makefile, mediorum/crudr/client.go, mediorum/ddl/ddl.go, mediorum/ddl/drop_blobs.sql, mediorum/server/db.go, mediorum/server/repair.go, mediorum/server/repair_test.go, mediorum/server/replicate.go, mediorum/server/serve_blob.go, mediorum/server/serve_crud.go, mediorum/server/serve_upload.go
* removes `blobs` table + crudr events.
* create `qm_cids` table with unique full list of historical Qm CIDs (from blobs table)
* repair.go runs in two phases:
* scrolls over all Uploads repairs orig CID and derivative CIDs
* scrolls over `qm_cids` and repairs historical records
* makes crudr `ops` gossip style similar to DMs
* resets crudr cursor to backfill any missing Upload records from nodes without route between them.
todo: deploy to single staging node to double check works with other servers running `main`
=> Drop blobs table, gossip upload crudr events

libs/src/services/solana/transactionHandler.ts
Need this to catch "tx too large" errors on relay.
Tested by manually sending a large tx through `TransactionHandler` and confirming we see the error:
=> Transaction handler: Catch and return tx serialization errors

discovery-provider/ddl/migrations/0029_usdc_transactions_metadata.sql, discovery-provider/src/api/v1/helpers.py, discovery-provider/src/models/users/usdc_transactions_history.py, discovery-provider/src/tasks/index_user_bank.py
Originally when designing the schema for these tables, there was no withdrawals table. Despite planning for one anyway, we still left out the tx metadata as we figured the address only showed up in the modal for $AUDIO tx history, in which case we could load the recipient address via looking up the tx on the Solana RPC instead.
However, the new table has the recipient address in the table row, so it became more efficient and also easier to just have the data in our SQL table instead.
Tested purchases show up correctly. Need to test transfers but there's not a real easy way to do that without running client. Going to merge and test on stage?
=> [PAY-1813] Add metadata to USDC transaction history table

comms/discovery/config/config.go, comms/discovery/discovery_main.go, comms/discovery/server/server.go, dev-tools/compose/docker-compose.discovery.yml
Prior to this PR, comms showed as unhealthy on the discovery health check endpoint. This would cause SDK to fail to select a discovery node. This change simply adds an environment variable that will force the comms server to show as healthy when in dev mode to make development easier, bypassing registration checks etc.
=> comms dev mode: no peers, always healthy

dev-tools/commands/src/auth-headers.mjs, discovery-provider/src/queries/get_collection_library.py
Due to the way saves/reposts are stored for albums as `RepostType.playlist` or `SaveType.playlist`, they were getting filtered out from the library queries.
@isaacsolo I seem to remember you came across this recently as well? Is the savetype/reposttype album ever used?
Tested by using `audius-cmd` to create users and upload tracks etc, and then also running client against dev to upload an album and saving/reposting that. Then double checked the output after pasting headers into the "Try it out!" autogen'd thing on Discovery which was mighty convenient
=> [PAY-1796] Fix reposted/saved albums not showing in library

comms/discovery/rpcz/peer_sweeper.go
repairs made... so this no longer needed.
=> dms: keep peer cursors across restarts

mediorum/server/serve_crud.go, mediorum/server/server.go
1. Set 1 min timeout on sweep query
2. Add mutex to crudr sweeper handler so only 1 of this expensive query runs at a time
Deploy to a stage node
=> Add db conn timeout to mediorum + mutex to crud sweep

mediorum/server/repair.go, mediorum/server/serve_health.go, mediorum/server/serve_health_test.go, mediorum/server/server.go, monitoring/healthz/src/DiscoveryHealth.tsx
Total the expected size of all content stored on a node in `repair.go` and display in healthz
Deploy to a stage node
=> Add expected content size to healthz

mediorum/radix/radix.go
I saw a segfault while soaking radix changes on prod CN2. It's caused by forgetting to check an http response for errors before reading its body - simple fix.
=> Add timeout and fix radix segfault

packages/web/src/services/solana/solana.ts, packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
- Changes the `isSolWallet` check to instead check for a token account
- Sends the final transfer via relay so no SOL is required
Tested against local stack
=> [PAY-1819] Allow transferring to existing USDC ATAs

packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx
Currently there is an intermediary loading state where the dashboard starts rendering, but the table is not ready. Make it so we fail for all the data while we show the spinner. Probably skeletons here would be nice someday.
=> [PAY-1825] Wait to render dashboard on listen data

.circleci/config.yml
Add `init` as a required step before continuing workflows
=> Require init step before triggering workflows

discovery-provider/ddl/migrations/0030_drop_old_block_key.sql
My previous migration only delete fkeys based on the referencing table name like track_price_history_blocknumber_fkey but in this case the existing reference table name was  blocknumber_fkey. This existing fkey would prevent the new fkey to cascade delete.
There are a couple other cases like this: grants and developer_apps.
=> Delete remaining old fkeys on blocks table

caddy/Dockerfile, caddy/README.md
Add http cache module to caddy and build custom image for use in `audius-docker-compose`
https://github.com/AudiusProject/audius-docker-compose/compare/rj-caddy-cache?expand=1
README steps
```
docker buildx build \
--platform linux/arm64,linux/amd64 \
--tag audius/caddy:$(head -n1 Dockerfile | cut -f 2 -d ':' | cut -d '-' -f 1) \
--push \
.
```
https://hub.docker.com/repository/docker/audius/caddy/general
=> Add caddy Dockerfile

packages/web/src/components/image-selection/ImageSelectionButton.js, packages/web/src/components/upload/UploadArtwork.js
Removed the 'Artwork' from the button so that it fit in the image container, change the icon, and move the icon to the left
=> [C-3050] Update the text and icon for the ImageSelectionButton

discovery-provider/scripts/start.sh
Move celery to eventlets from prefork concurrency model.
Set --concurrency to 50 to be >= number of celery tasks we spawn.
tested on stage discovery 1
=> [PROTO-1250] Move celery to eventlets

packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx, packages/web/src/pages/upload-page/validation.ts
Fixed hidden validation error causing the form to be un-submittable.
We were not unpacking the track's `.metadata` before validation. After that, we were failing on `description` which is optional here, so just picked the title field.
local web
=> [C-3071] Fix collection upload validation

packages/web/src/common/store/pages/saved/lineups/sagas.js
- Add track to library upon purchasing
- Fix "local state when favoriting purchased tracks not being tracked correctly" by making sure we only add the track to the current lineup when we're on the relevant category 
=> Add purchased track to library; fix favoriting purchased tracks PAY-1829 PAY-1788

packages/common/src/hooks/chats/useTrackPlayer.ts, packages/mobile/src/screens/chat-screen/ChatMessageTrack.tsx, packages/web/src/components/track/helpers.ts, packages/web/src/components/track/mobile/ConnectedTrackTile.tsx, packages/web/src/components/track/mobile/TrackTile.tsx, packages/web/src/pages/chat-page/components/ChatMessageTrack.tsx
Enables previewing for track tiles in the chat view. This uses a different component and code path to queue things, which needs the previewing flags to be wired up.
=> [PAY-1774] Fix previewing in web chat track tiles

.circleci/src/commands/gcp-run.yml, .circleci/src/jobs/build-gcp-image.yml, .circleci/src/jobs/gcp-cleanup.yml
There is unneeded ambiguity regarding when disks should be deleted in gcp after a CircleCI workflow. We decided to enforce deletion.
Must verify CircleCI workflows delete instances properly
=> Always delete gcp disks after workflow completion and instance removal

packages/mobile/src/components/premium-track-purchase-drawer/PurchaseSuccess.tsx, packages/mobile/src/screens/notifications-screen/Notifications/USDCPurchaseBuyerNotification.tsx, packages/web/src/components/notification/Notification/USDCPurchaseBuyerNotification.tsx, packages/web/src/components/premium-content-purchase-modal/components/PurchaseDetailsPage.tsx
We have a few different patterns for how to pass URLs to twitter share messages 😅 . But the most common seems to be passing a `url` prop to the button and letting it use the built-in utility to add a URL via query param when launching the intent. This seems like the correct behavior[ indicated by the docs](https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/guides/web-intent)
Tested locally in Chrome and simulator against staging
=> [PAY-1842] Update usdc twitter shares to pass track URLs correctly

packages/web/src/pages/upload-page/components/FinishPageNew.tsx
Per design, artwork should be hidden on collection tracks in the upload progress display
=> [C-3080] Hide artwork for collection uploads

packages/web/src/components/upload/TrackPreviewNew.tsx, packages/web/src/pages/upload-page/components/TracksPreviewNew.tsx
Trust the file name to have the correct extension already. Doesn't necessarily have to match the mime type.
Before:
After:
local web
=> [C-3082] Fix track extension on select page

packages/mobile/android/app/src/main/AndroidManifest.xml
Fixes issue where the camera roll would not open on android devices. this is due to the upgraded picker needing an undocumented permission
=> [C-3086] Add missing media android permission

mediorum/server/monitor.go
Check db size before disk size because the disk size check can take a long time when it's storing a lot of files.
=> Check db size before disk size

packages/common/src/schemas/index.ts, packages/web/src/components/track/EditTrackModal.js, packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
1. We need to ignore the > 30 seconds from the end requirement if the track isn't at least 30 seconds long
2. We did not have `preview_start_seconds` as one of the fields in our validation metadata, so it was being stripped during update calls. There is still an issue where the preview stream isn't being updated, but we are at least setting the right metadata now.
Tested locally against staging in Chrome
=> [PAY-1841] Fix some issues with setting preview start times

discovery-provider/src/api/v1/helpers.py
use current event loop to request upload info from content if one exists, otherwise spawn a new event loop.
tested on a stage dn, verified no errors when viewing uncached image
=> Better asyncio event loop handling when caching images in discovery

discovery-provider/src/queries/get_health.py
can just have 1 uptime robot monitor checking `/health_check?enforce_block_diff=true&healthy_block_diff=250` for `errors:[]`
deploy to a stage node
=> Consolidate errors in discovery health check

packages/mobile/src/screens/upload-screen/utils/processTrackFile.ts, packages/web/src/components/upload/InvalidFileType.js, packages/web/src/components/upload/InvalidFileType.module.css, packages/web/src/pages/upload-page/components/SelectPageNew.tsx, packages/web/src/pages/upload-page/fields/SourceFilesField.tsx, packages/web/src/pages/upload-page/store/utils/processFiles.ts
- Adds error when user attempts to upload an empty file
- Covers case where dropbox sync'd files appear as empty files on local disk
local web
am now dropbox pro user 😢
=> [C-3092] Add error on empty file upload

discovery-provider/ddl/migrations/0031_drop_current_indices.sql, discovery-provider/integration_tests/queries/test_undisbursed_challeges.py, discovery-provider/integration_tests/queries/test_user_playlist_update.py
is_current is still referenced from some pkeys and indices even though all rows are is_current true. 
Tested on sandbox. Confirmed migration made the right modifications and indexing is working.
Before
```
audius_discovery=> explain analyze  select * from users where user_id = 1;
QUERY PLAN                                                           
-------------------------------------------------------------------------------------------------------------------------------
Index Scan using users_new_pkey on users  (cost=0.56..192059.25 rows=1 width=781) (actual time=0.013..131.900 rows=1 loops=1)
Index Cond: (user_id = 1)
Planning Time: 0.102 ms
Execution Time: 131.931 ms
(4 rows)
audius_discovery=> SELECT
pg_size_pretty(pg_database_size(current_database())) AS database_size; …
```
=> Optimize pkeys and indices by dropping is_current

discovery-provider/integration_tests/queries/test_get_sitemap.py, discovery-provider/src/queries/get_sitemap.py
Only return users with >= 10 followers in user sitemaps for performance.
=> Filter users by followers in sitemaps

packages/mobile/src/components/lineup-tile/LineupTile.tsx, packages/mobile/src/components/lineup-tile/LineupTileActionButtons.tsx, packages/mobile/src/components/lineup-tile/TrackTile.tsx, packages/mobile/src/components/lineup-tile/types.ts, packages/web/src/components/track/mobile/BottomButtons.tsx, packages/web/src/components/track/mobile/TrackTile.tsx
* Chat track tiles on mobile and web now show the premium conditions pill for USDC tracks when they are locked. This allows the user to tap/click on the pill to open the purchase flow
* Updated some code paths where we were missing logic to allow previews (mostly for chat message tiles)
Fixes PAY-1847
Tested locally in Chrome and simulator against staging
=> [PAY-1847] UX fixes for USDC mobile/chat track tiles

discovery-provider/ddl/migrations/0031_dedupe_repost_saves.sql
Dedupe a couple hundred reposts/saves from the album repost/save bug. Fix was already released https://github.com/AudiusProject/audius-protocol/pull/5767 but this cleans up the data.
Example of dupes. This playlist has aggregates that don't match the actual reposts/saves. This will dedupe and the update_aggregate task will correct the diffs.
https://audius.co/fmonkeyrock/album/sad-64257
Tested on sandbox. Confirmed migration ran in less than a minute and dupes were corrected including the example above.
=> Dedupe reposts/saves from album bug

discovery-provider/src/api/v1/helpers.py
Can cause API responses to be slow.
Prefer `{upload_id}/{variant}.jpg`
due to: https://github.com/AudiusProject/audius-protocol/pull/6043
=> skip API image cid resolution step

packages/stems/src/components/SegmentedControl/SegmentedControl.tsx, packages/stems/src/components/SegmentedControl/types.ts, packages/web/src/pages/upload-page/components/TracksPreviewNew.tsx
The selected tab was loading during the entry animation for the tracks sidebar. This caused the calculation to be based on the wrong width and the tab to be too small.
Defer segmented tab calc until animations finish
https://www.loom.com/share/3a0393788b3b4ccdb6666aadd27a6b85
Less hacky alternate solutions:
- Use a different animation that keeps the size of the entering element constant
- Find a better condition for the useEffect that calculates the tab size (instead of `forceRefreshAfterMs`)
local web
=> [C-3099] Fix bad width calculation on segmented control

packages/web/src/pages/upload-page/UploadPageLegacy.js, packages/web/src/pages/upload-page/UploadPageNew.tsx, packages/web/src/pages/upload-page/components/FinishPageNew.tsx, packages/web/src/pages/upload-page/fields/CollectionTrackFieldArray.tsx, packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx
Fixes several core issues with collection upload:
- We now upload using `uploadCollection` instead of `uploadMultipleTracks` saga path
- We weren't passing the collection upload type all the way through
- Propagating metadata to tracks through the collection form onSubmit
Albums now upload fully and the Visit Album link works properly.
The resulting tracks are part of the album and inherit artwork from the album's art.
=> [C-3108, C-3111] Fix collection upload

discovery-provider/ddl/migrations/0031_drop_current_indices.sql
Explicitly lock tables before this big migration to avoid deadlocks.
Ran on sandbox.
=> Lock tables during pkey index migration

packages/common/src/store/upload/selectors.ts, packages/web/src/pages/upload-page/fields/SourceFilesField.tsx
Artwork upload time was negligible, and it wasn't being tracked for albums. Rather than get a perfect solution, let's just ignore artwork for now.
local web
=> [C-3110] Remove artwork progress from upload progress bar

packages/web/src/components/table/Table.tsx, packages/web/src/pages/saved-page/SavedPageProvider.tsx, packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
Before: After the first batch loads, it only loads one at a time (this is a regression I created in the library work)
After: Fixed
=> Fix tracks table loading one track at a time PAY-1868 PAY-1873

packages/common/src/store/ui/modals/edit-track-modal/index.ts, packages/common/src/store/ui/modals/reducers.ts, packages/web/src/components/edit-track/EditTrackModal.tsx, packages/web/src/components/menu/TrackMenu.tsx
Fixes issue where edit-tractk modal state was referencing the editplaylist modal state, causing crossed wires.
=> [C-3113] Fix edit-track modal state

packages/common/src/services/opensea-client/OpenSeaClient.ts, packages/common/src/utils/allSettled.ts, packages/web/src/pages/visualizer/Visualizer.tsx
This context matters.
Throws:
```
const allSettled = Promise.allSettled;
allSettled([Promise.resolve(1), Promise.reject('error')]).then(console.log);
```
Doesn't throw:
```
Promise.allSettled([Promise.resolve(1), Promise.reject('error')]).then(console.log);
```
What changed? Idk. Something upgraded.
=> Fix staging build web

mediorum/server/db.go, mediorum/server/repair.go, mediorum/server/server.go
Image variants generated dynamically, so repair.go can skip them.
=> repair.go skip image variants

discovery-provider/.version.json, mediorum/.version.json
This reverts commit 8687503b20162d4a51c20942ca357741e4c3446c because I want to re-run the automated job on the next hour (10am PST). It ran into an issue due to dirty workspace earlier, so it didn't get to reach the step where it notifies in Slack (which is the only step I actually wanted to test). I will also want to delete the release-v0.4.10 branch so the next job can re-create it.
=> Revert "Bump version to 0.4.10"

discovery-provider/plugins/notifications/src/email/notifications/index.ts, discovery-provider/plugins/notifications/src/main.ts, discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts, discovery-provider/plugins/notifications/src/tasks/appNotifications.ts, discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
fires and forgets schedules emails so they don't block normal push processing
Ran on stage, you can see in these output logs that a push was sent to Sabrina while the process email notifs task was running. Even though the push itself failed you can see the IOS push attempt meaning that this notif was not a part of the scheduled emails cycle.
https://app.axiom.co/audius-Lu52/stream/stage-discovery?rowId=0cvnvopyb6971-06a6e2503e003fa0-9a07&context=1
=> non blocking notifs

monitoring/healthz/Dockerfile, monitoring/healthz/README.md, monitoring/healthz/package-lock.json, monitoring/healthz/package.json, monitoring/healthz/src/main.tsx, monitoring/healthz/vite.config.ts
Containerize healthz so that it can be deployed on all nodes instead of just centrally at Cloudflare pages. Note: deploying to cloudflare pages should still work as usual.
1. `cd monitoring/healthz && docker build -t healthz . && docker run -d --name healthz -p 9559:80 healthz`
2. `caddy run` with the following sample Caddyfile:
```
:80
reverse_proxy /healthz* :9559
```
3. Visit `localhost/healthz` and confirm webapp works, even when clicking through sub-routes.
=> [PROTO-1189] Containerize healthz to run on nodes

package-lock.json, packages/web/src/pages/upload-page/components/FinishPageNew.tsx
We were showing the upload complete page after all the tracks were uploaded but before the collection upload completed. This allowed the user to click `Visit Album` before the album was ready and would get a blank not found album page.
This change is to match the condition we used in the legacy upload flow.
local web using confirmer popup to check timing of album confirm vs showing the finish page
=> [C-3117] Wait for collection upload before showing complete

packages/mobile/src/screens/edit-track-screen/EditTrackScreen.tsx
Fixes issue where interacting with access + sale screen prevents user from uploading. this has to do with not fully-fleshed out validation for the various premium conditions. When we finalize validation on desktop, we should migrate that over to mobile
=> [C-3079] Fixes blocking mobile upload validation error

monitoring/healthz/Caddyfile, monitoring/healthz/src/DiscoveryHealth.tsx, monitoring/healthz/src/index.css
Display node row in healthz in red if the node is unhealthy.
For DNs, this means if blockdiff > 250, if solana play count drift is > 720, trusted notifier delists are unhealthy, chain is unhealthy, etc. Specific errors will be specified in the errors field of the healthcheck resp.
For CNs, this is if healthy: false in the healthcheck resp.
ran local healthz
dns:
cns:
=> Color unhealthy nodes red in healthz

.circleci/src/commands/@mobile-commands.yml, packages/mobile/android/fastlane/Fastfile
Google playstore upload was failing due to: https://github.com/fastlane/fastlane/issues/21507
* Upload fastlane automatically in android pipeline (we already do this for ios)
* Set retries to 5
Google playstore upload works on CI
=> Fix android fastlane cert issue

.circleci/config.yml
- Fixes missing backslash to escape double quotes in revert commits
- Makes version not hardcoded
- Prints the text that would be sent to the API for easier debugging inside CI
I ran this manually - the Slack message was sent successfully.
=> [PROTO-1269] Hotfix daily deploy script

packages/common/src/models/Analytics.ts, packages/common/src/services/audius-backend/solana.ts, packages/common/src/store/purchase-content/sagas.ts, packages/common/src/store/purchase-content/slice.ts
Adds slice/saga logic for passing an `extraAmount` field and propagating that down to libs to include in the transaction.
fixes PAY-1809
I temporarily modified the purchase modal to pass along a fixed extra amount and verified that it was sent along in the transaction
=> [PAY-1858] Add saga support for 'pay extra'

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/services/remote-config/feature-flags.ts, packages/libs/src/AudiusLibs.ts
Original PR got closed for some reason, this adds it back and is why stage doesn't use discovery relay yet.
In an incognito window went through user sign up flow, successfully created user, then did some things like favorite, repost, etc.
=> Discovery Relay: re-add feature flag

packages/common/src/api/purchases.ts, packages/common/src/api/user.ts, packages/common/src/audius-query/createApi.ts, packages/common/src/audius-query/types.ts, packages/common/src/store/purchase-content/sagas.ts, packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
PAY-1821
Fix stale usdc purchases and withdrawals data after confirmed purchase or withdrawal.
The issue here was that once the data was already fetched, audius-query would always use the cached data for every subsequent render.
This PR introduces a reset action in the reducer that is used in our sagas, so that next time audius-query needs the data, it will have to refetch from the DN.
Local vs stage. Tested both purchases and withdrawals. After purchase/withdrawal, navigating to the purchases/withdrawals renders the loading screen as it refetches the data, then display the fresh data.
=> Fix stale usdc purchases and withdrawals data

discovery-provider/api-tests/Discovery API Tests.postman_collection.json, discovery-provider/api-tests/Test Sandbox.postman_environment.json
this diff contains the json for testing 36 of our read endpoints for latency and json similarity to dn4 via postman. we expect a 95% similarity for json results from dn4 our control and sandbox dn 1 our test.
note that two tests have a looser similarity threshold (search playlist and trending playlists) because it is expected these endpoints tend to differ across nodes 
ran the postman collection via newman
=> [proto-1259] update postman collection to test all read endpoints

mediorum/server/server.go
Healthz info about the last repair run doesn't display until a repair job finishes running because of a bad zeroTime check when fetching recent repair runs on startup.
Tested custom tag on stage CN9 - the last repair run info displays immediately on restart now.
=> Fix zeroTime check for last repair job

identity-service/src/featureFlag.js
Correctly fetches `USDC_PURCHASES` feature flag on relay.
Local dev stack
=> Correctly fetch USDC feature flag to relay

mediorum/server/repair.go
One-line fix for the bug making healthz not show the last successful repair info... it needs to set `FinishedAt` before setting `lastSuccessfulRepair`.
I checked the db of stage CN9 to confirm this.
=> Set FinishedAt before updating lastSuccessfulRepair

packages/libs/src/services/solana/transactionHandler.ts, packages/web/src/services/audius-backend/Jupiter.ts, packages/web/src/services/solana/WithdrawUSDC.ts, packages/web/src/store/application/ui/buy-audio/sagas.ts, packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
Update libs `TransactionHandler` to be able to send v0 transactions, and use the v0 transaction instructions returned by the Jupiter API to complete the swap step of the Buy $AUDIO flow.
- Using name `lookupTableAddresses` instead of `addressLookupTableAddresses` that Jupiter returns.
- Duplicated code to grab `AddressLookupTableAccount`s from a string of lookup table addresses in libs and web. Started going down the path of centralizing into a util fn in libs, but realized it was a lot of plumbing and I wanted slightly different error handling so decided to just go wet. Lmk if you think it's worthwhile to do this.
DRAGON: Noticed a new kind of error during testing - Jupiter `getQuote` frequently 500s with this error message:
```
Invalid caused by plan: [Trade { e: …
```
=> [PAY-1867] Use v0 tx in buy audio flow

.circleci/src/jobs/deploy-stage-nodes.yml
One-line fix for stage deploys with an extra `/` in the path.
=> Fix stage deploy path typo

discovery-provider/ddl/functions/handle_usdc_withdrawal.sql, discovery-provider/ddl/migrations/0025_add_track_price_history_fkey.sql, discovery-provider/integration_tests/notifications/test_usdc_withdrawal.py, discovery-provider/integration_tests/utils.py
Add notification for usdc withdrawal. Note that this will not be consumed in in-app emails, or consumed via push. At the moment the only receiver will the notifications plugin and email processing.
```
audius-compose test discovery-provider
```
=> [PAY-1737] Add notification for usdc withdrawal

.circleci/config.yml
In Slack daily deploy messages:
- Tags commit authors using CIrcleCI secrets to keep Slack user IDs private
- Fixes extra line breaks
I manually tested a large diff all the way back to 0.4.5. This included a commit with "@" in the message to verify that the line delimiter works. It sent to a private channel and tagged people.
=> [PROTO-1294] @Mention Slack users in daily deploy msg

packages/stems/src/components/IconButton/IconButton.tsx
I made this change for other buttons used in the premium content form, but missed `IconButton`. Long term, we should probably make most if not all instances of a raw HTML `<button />` include this attribute to make them safe to use in forms, and/or we should only ever use Harmony components for buttons since they will include the type for us. But this fixes the issue for now.
fixes PAY-1905
Tested locally in Chrome against staging.
=> [PAY-1905] Add type attribute to IconButton to prevent form submission

.circleci/config.yml
Web and mobile workflows are by far our most expensive CI flows:
https://app.circleci.com/insights/gh/AudiusProject/audius-protocol
We currently run `mobile-build-production-ios` for example, on every push to main even when nothing relevant has changed.
This PR updates the CI config to only run web and mobile workflows on main when relevant files have changed. This could be risky if there are hidden dependencies that we aren't capturing in the path filtering. Everything will continue to be run on the release branch as normal
=> [INF-487] Reduce CI cost by filtering web and mobile workflows

packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx, packages/web/src/pages/upload-page/validation.ts
Fixes issue where release_date was a Date instance instead of a string when passed to the saga, resulting in runtime error
=> [C-3143] Fix collection upload release date

packages/stems/src/components/Modal/Modal.tsx, packages/stems/src/components/Modal/ModalContent.tsx, packages/stems/src/components/Modal/ModalContext.tsx, packages/stems/src/components/Scrollbar/Scrollbar.tsx, packages/stems/src/components/Scrollbar/types.ts
Fix the awful vertical & horizontal modal scroll bar behavior we have on prod
Will only work for modals using the <ModalContent> paradigm, but maybe this is where we see it only anyway.
https://github.com/AudiusProject/audius-protocol/assets/2731362/d7984e28-bdd1-4614-b044-d911bac16de2
=> [C-607] Fix modal scroll bar

.circleci/config.yml
Fixes a bug which excluded the final commit in Slack messages for daily deploys (only the Slack message was impacted - the branch was correct). This bug was introduced when changing the looping of commits to replace GitHub usernames with Slack IDs.
I did a dry run with `f49cf2590` checked out and verified before and after this change - it now includes the missing commit.
=> Fix missing commit in Slack daily deploy

discovery-provider/plugins/pedalboard/apps/relay/package-lock.json, discovery-provider/src/utils/helpers.py, packages/web/src/components/actions-tab/ActionsTab.js, packages/web/src/components/card/desktop/Card.tsx, packages/web/src/components/menu/CollectionMenu.tsx, packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
Fixes a bug where collection menu was still routing to playlists by doing playlist name + id as the slug. It should have still worked routing this way, but there was a second deeper issue where we strip `.` on the backend when we save a playlist route, but in the frontend when we encode a playlist name to navigate via playlist name + id, we don't strip `.`. so this wasn't able to fetch the correct playlist bc the slugs didn't match up.
=> Fix visit album page from collection menu

discovery-provider/es-indexer/src/indexNames.ts, discovery-provider/es-indexer/src/indexers/TrackIndexer.ts, discovery-provider/es-indexer/src/types/docs.ts, discovery-provider/integration_tests/queries/test_search.py, discovery-provider/src/api/v1/helpers.py, discovery-provider/src/api/v1/search.py, discovery-provider/src/queries/search_es.py, packages/common/src/services/audius-api-client/AudiusAPIClient.ts, packages/web/src/common/store/pages/search-page/sagas.js, packages/web/src/common/store/search-bar/sagas.ts
Properly gate purchaseable content
* Add data to ES document store and filter in track_dsl based on arg
* Add feature flag query param to API calls
to test the functionality around the flag
```
```
& inspect network
to test es changes:
```
```
Check track es indexing:
```
curl -X GET "http://localhost:9200/tracks16/_search?pretty" -H 'Content-Type: application/json' -d'
{
"size": 1000,
"query": {
"match_all": {}
}
}'
```
```
pytest integration_tests/queries/test_search.py::test_get_tracks_with_purchases
```
=> [PAY-1933] Gate purchaseable content in search

discovery-provider/integration_tests/queries/test_notifications/test_usdc_purchase_notification.py, discovery-provider/plugins/notifications/src/__tests__/mappings/usdcPurchaseBuyer.test.ts, discovery-provider/plugins/notifications/src/__tests__/mappings/usdcPurchaseSeller.test.ts, discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseSeller.ts, discovery-provider/src/api/v1/utils/extend_notification.py, discovery-provider/src/queries/get_notifications.py, packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/store/notifications/types.ts, packages/common/src/utils/wallet.ts, packages/mobile/src/screens/notifications-screen/Notifications/USDCPurchaseSellerNotification.tsx, packages/web/src/components/notification/Notification/USDCPurchaseSellerNotification.tsx
Add pay extra fields to notifications (in app, push, email). Doesn't break current behavior -- may sort out some bugs after merge.
```
```
and confirm that exiting values are correct without extra amount. 
Discovery unit tests pass
=> [PAY-1922] Add pay extra fields to notifications

monitoring/healthz/src/pages/Nodes.tsx
Uses 4TB as an artificial limit for nodes with cloud backends. Removes "extra" storage to make the progress bar clearer.
`npm run dev`
=> Add 4TB visual limit and remove 'extra'

dev-tools/compose/docker-compose.healthz.yml, dev-tools/compose/docker-compose.yml, dev-tools/compose/nginx_ingress.conf, discovery-provider/nginx_conf/nginx.conf, monitoring/healthz/Dockerfile
Some audius deployments rely on Caddy from audius-docker-compose while others route requests directly to the discovery service nginx. This should allow healthz to be reverse proxied in the latter case.
Tested locally with `audius-compose up` and verified that `http://audius-protocol-discovery-provider-1/healthz` works as expected.
=> [PROTO-1293] Proxy to healthz from discovery nginx

packages/web/src/components/drawer/Drawer.tsx
Many drawers were impacted by this on moweb - not entirely sure how this ever worked, but the crux of the issue boils down to not knowing the height to animate to when the animation begins. `setImmediate` is a nice fix. I tried to do DRAF (https://stackoverflow.com/questions/44145740/how-does-double-requestanimationframe-work), but it didn't quite work.
```
```
=> [PAY-1581] Fix moweb drawer

monitoring/healthz/src/pages/Nodes.tsx
For DNs:
- Display reasons why a node is unhealthy to more easily debug using healthz
- Check solana play count as part of health check
ran locally
=> Display DN node health + errors in healthz

discovery-provider/src/api/v1/helpers.py, discovery-provider/src/api/v1/search.py, discovery-provider/src/api/v1/utils/extend_notification.py, discovery-provider/src/queries/search_es.py
* Broken because of improper bool filter
* Add filter to tag search - this is redundant since there's only a client-side lineup view for tag search, but figured for now we could do this and then revert the change down the line.
```
curl 'http://audius-protocol-discovery-provider-1/v1/full/search/autocomplete?includePurchaseable=false&limit=3&offset=0&query=buy&user_id=D809W'
curl 'http://audius-protocol-discovery-provider-1/v1/full/search/autocomplete?includePurchaseable=true&limit=3&offset=0&query=buy&user_id=D809W'
curl 'http://audius-protocol-discovery-provider-1/v1/full/search/autocomplete?limit=3&offset=0&query=buy&user_id=D809W'
```
confirmed via logs that the proper DSL …
=> Fix usdc search filter

mediorum/server/db.go, mediorum/server/server.go, mediorum/server/upload_client.go
Scrolls historical upload records to backfill from the pre-gossip days.
This could eventually replace the crudr ops stuff with something simpler.
Deployed to stage DN 12
=> PROTO-1299: scroll uploads for backfill

package-lock.json, packages/mobile/e2e/signUp.test.ts, packages/mobile/src/screens/root-screen/RootScreen.tsx, packages/mobile/src/screens/sign-up-screen/SignUpRootScreen.tsx, packages/mobile/src/screens/sign-up-screen/screens/CreatePasswordScreen.tsx, packages/mobile/src/screens/sign-up-screen/screens/PickHandleScreen.tsx, packages/mobile/src/screens/sign-up-screen/types.ts, packages/mobile/src/screens/sign-up-screen/useRoute.ts, packages/probers/cypress/e2e/signUp.cy.ts, packages/probers/cypress/support/commands.ts, packages/web/src/common/utils/isMobileWeb.ts, packages/web/src/pages/App.js, packages/web/src/pages/sign-up-page/SignUpRootPage.tsx, packages/web/src/pages/sign-up-page/index.ts, packages/web/src/pages/sign-up-page/pages/CreatePasswordPage.tsx, packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx, packages/web/src/pages/sign-up-page/pages/SignUpPage.tsx, packages/web/src/utils/clientUtil.ts
Implements bare-bones create-password page for sign up redesign
Adds tests for all envs
=> [C-3139] Add create password page

packages/web/src/pages/upload-page/fields/MultiTrackSidebar.tsx, packages/web/src/pages/upload-page/fields/SelectGenreField.tsx
No idea why this broke with latest release build. It works in prod and broken on rc but we haven't found any relevant changes in these files since then.
Local web. Works with type submit and breaks without it
=> [C-3168] Add missing submit type on button

packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/PremiumRadioField/TrackPreviewField.tsx, packages/web/src/pages/upload-page/fields/availability/UsdcPurchaseFields.tsx
=> [PAY-1917] Add parens around seconds

discovery-provider/src/queries/get_trending.py, discovery-provider/src/queries/get_trending_tracks.py
I believe this is at least a 5x improvement on trending requests. The biggest bottleneck in trending is populating metadata. In some cases this can take 14 seconds alone.
```
{"level": "INFO", "msg": "got track play count completed 14.473582744598389", "timestamp": "2023-10-02 22:46:47,515", "service": "server", "otelSpanID": "8d775f5305530e6a", "otelTraceID": "18ac26b35ba35c53c24b3cea00435d6d", "otelServiceName": "discovery-provider", "path": "src.queries.query_helpers", "function": "populate_user_metadata"}
{"level": "INFO", "msg": "populate_track_metadata completed in 14.91640305519104", "timestamp": "2023-10-02 22:46:47,609", "service": "server", "otelSpanID": "8d775f5305530e6a", "otelTraceID": "18ac26b35ba35c53c24b3cea00435d6d", "otelServiceName": "discovery-provider", "path": …
```
=> Optimize trending requests

mediorum/server/server.go
To allow the /healthz endpoint to be accessible on all content nodes that don't use audius-docker-compose Caddy, we will reverse proxy directly from mediorum.
Ran `audius-compose up` and verified that healthz was accessible via `localhost:1991/healthz` including subroutes.
=> [PROTO-1293] Reverse proxy to healthz from mediorum server

packages/mobile/src/components/drawer/Drawer.tsx, packages/mobile/src/components/drawer/DrawerHeader.tsx, packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
This converts the premium content purchase drawer to be full screen. It required a little bit of style tweaking and implementation of a custom header to get the spacing/styling correct. 
fixes PAY-1939
Tested locally on simulator against staging
=> [PAY-1939] Convert purchase content drawer to full screen variant

packages/mobile/src/screens/edit-track-screen/EditTrackScreen.tsx, packages/mobile/src/screens/upload-screen/utils/processTrackFile.ts, packages/web/src/components/data-entry/AccessAndSaleModalLegacy.tsx, packages/web/src/pages/upload-page/components/PreviewButton.tsx, packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx, packages/web/src/pages/upload-page/fields/CollectionTrackField.tsx, packages/web/src/pages/upload-page/forms/EditTrackForm.tsx, packages/web/src/pages/upload-page/store/utils/processFiles.ts
Reader beware of confusing name overloading - using this terminology to help:
* Upload Preview: The preview button shown during upload to help you listen to what you're uploading
* Purchase Preview: The preview that is generated server side to help people listen prior to purchase
The bug:
* You cannot set the purchase review of AIF/FLAC/etc files
Why?
* The upload preview is invalid because the browser cannot play AIF/FLAC/etc files and there for zod/yup validation expects being able to collect the duration of the file to validate the purchase preview.
Solve (nearterm):
* On invalid upload preview, just let the user try
* On invalid upload preview, don't render the upload preview button
* On mobile, use ffmpeg instead of TrackPlayer to get duration. TrackPlayer is unreliable after some on …
=> [PAY-1936] Allow preview timestamps to be set for "unpreviewable" tracks

packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
Cleans up redux state when closing the purchase content modal, so that trying to purchase a different track shows a clean state.
Local web client
=> [PAY-1927] Cleanup redux state on purchase modal close

packages/common/src/api/purchases.ts, packages/common/src/models/USDCTransactions.ts, packages/common/src/utils/wallet.ts, packages/web/src/components/premium-content-purchase-modal/components/PurchaseSummaryTable.tsx, packages/web/src/components/summary-table/SummaryTable.module.css, packages/web/src/components/summary-table/SummaryTable.tsx, packages/web/src/components/summary-table/index.ts, packages/web/src/components/usdc-purchase-details-modal/components/PurchaseModalContent.tsx, packages/web/src/components/usdc-purchase-details-modal/components/SaleModalContent.tsx, packages/web/src/components/usdc-purchase-details-modal/components/TransactionSummary.tsx, packages/web/src/pages/purchases-and-sales/PurchasesTable.tsx, packages/web/src/pages/purchases-and-sales/SalesTable.tsx
This adds the pay extra amounts to the tables and updates the details modals to use a transaction summary table to display the cost breakdown.
Important notes:
* I updated our formatting function to optionally accept a `BN` (since we are adding together values _before_ formatting) and to also stop stripping the negative sign in favor of using `BN`'s built-in `abs()` function. It will correctly parse a negative number string for us!
* I implemented a shared `SummaryTable` component and moved the purchase content modal over to using it. All three modals display the summary in the same format.
fixes PAY-1861
BEFORE
---
AFTER
(Without pay extra)
=> [PAY-1861] Expose Pay Extra details in purchase/sales tables

packages/common/src/utils/sagaHelpers.ts, packages/web/src/common/store/pages/signon/sagas.js, packages/web/src/utils/sagaHelpers.ts
The saga where we follow the selected artists would sometimes execute before the new user's account was successfully loaded due to a race condition. 
Unclear why this race condition showed on mobile but not desktop, as both use the same sign up sagas and start with the same `accountStatus = ERROR` state if user is logged out. Perhaps just a difference in the redux saga or other internals between the two platforms.
Tested on mobile and desktop.
=> Fix flaky follows on sign up, mobile C-2718

.circleci/config.yml, .circleci/src/workflows/mobile.yml
We run `mobile-build-production-ios` and `mobile-build-production-android` on main and they are very expensive. 
* Disable prod builds on main. This in combination with #6142 should put us in a good spot cost-wise
* Stage builds still run (less expensive)
* Prod builds run on release branches
* Ensure web + mobile workflows run on main when harmony changes
=> [INF-501] Disable mobile prod builds on main

packages/libs/src/services/ethContracts/ClaimsManagerClient.ts
Fixes ClaimsManagerClient not having access to web3Manager, which prevents it from initializing. This is a blocker for updating the libs version in protocol dashboard.
`await audiusLibs.ethContracts.ClaimsManagerClient.getLastFundedBlock()` now returns the same number on `npm run web:prod` as on the current protocol dashboard (with outdated libs version). On audius.co, this function causes an error and is unable to return a block number.
=> [PROTO-1239] Fix initting ClaimsManagerClient

package-lock.json, packages/harmony/package.json, packages/harmony/src/components/input/SelectablePill/SelectablePill.tsx, packages/harmony/tsconfig.json
Set tsconfig setting to false to remove checks for indexing into objects to allow for css module classnames without issues. This may be slightly unsafe, but it how web and stems operate currently
Rollup built without error
=> Update harmony tsconfig to allow for css module classnames without errors

discovery-provider/integration_tests/queries/test_get_sitemap.py, discovery-provider/src/app.py, discovery-provider/src/queries/get_sitemap.py
Sitemaps were counting incorrectly after 
https://github.com/AudiusProject/audius-protocol/pull/6015/files
Also update base url to just audius.co / staging.audius.co to respect proxies better. Anyone running a node could override this.
```
>> pytest integration_tests/queries/test_get_sitemap.py
```
=> [PROTO-1317] Fix sitemap counts

packages/identity-service/src/relay/ethTxRelay.js, packages/identity-service/src/routes/ethRelay.js, packages/libs/initScripts/manageProdRelayerWallets.js
ethgasstation.info is defunct, use defaults
see also: https://github.com/AudiusProject/audius-docker-compose/pull/309
none
=> Remove broken ethgasstation.info usage, let default gas be set

discovery-provider/nginx_conf/log_json.lua, discovery-provider/nginx_conf/nginx.conf, discovery-provider/scripts/prod-server.sh
This change structures nginx logs into json so we can query in axiom. It also adds request time. 
I removed gunicorn's access-log and added a tail for the the json formatted access-log to stdout. 
Ran on sandbox and hit a few requests.
=> Add request time in json to server logs

discovery-provider/src/api/v1/tracks.py, discovery-provider/src/queries/get_trending.py
Before, we would populate/cache the entire trending list but this optimization https://github.com/AudiusProject/audius-protocol/pull/6199 made it cache according to a limit and return the cached result no matter the limit / offset.
We still cache unpopulated trending tracks so impact on perf is negligible https://github.com/AudiusProject/audius-protocol/blob/e243d46f682378d72000eab520ae615ce7989a75/discovery-provider/src/queries/get_trending_tracks.py#L342.
Tested on sandbox and paging through trending works.
=> Remove anon v1 full trending tracks cache

.circleci/src/jobs/push-docker-image.yml, dev-tools/audius-compose
Identity hasn't been auto upgrading since #6160
This is because `audius-compose push` runs a full build and wasn't passed the `prod` flag. Thanks @theoilie for help debugging!
* Add `prod` flag to audius-compose push
Confirming push output in CI and then will confirm stage identity auto upgrades
=> Fix identity push

dev-tools/compose/docker-compose.storagev2.yml, dev-tools/compose/docker-compose.test.yml, dev-tools/compose/docker-compose.yml, mediorum/crudr/crudr.go, mediorum/crudr/setup_test_db.go, mediorum/ddl/ddl.go, mediorum/server/db.go, mediorum/server/test_main_test.go
Originally reverted because was breaking CI tests. Updated sql slightly to commit every create table operation + fixed mediorum unit tests.
For the unit tests, I lowered the number of test mediorum replicas since the number of ops tables for 9 replicas was consuming a lot of memory. Also fixed the test container's `dbUrl` to point to its own database rather than using `m1` and interfering with the server test using `m1`.
ran mediorum-unittests and audius-compose up locally, reran ci a few times to make sure tests consistently pass
=> Remove partition migration again

discovery-provider/Dockerfile
Resolves
```
=> ERROR [discovery-provider stage-1  5/17] RUN apk update &&     apk add --no-cache     alpine-sdk     bash     curl     docker     libffi-dev     libseccomp-dev     libxml2-dev     libxslt-dev     linux-headers     nodejs     npm     python3=3.11.5-r0     python3-dev=3.11.5-r0     py3-numpy     py3-pip     py3-scipy     py3-wheel     redis     rsyslo  1.9s
------
> [discovery-provider stage-1  5/17] RUN apk update &&     apk add --no-cache     alpine-sdk     bash     curl     docker     libffi-dev     libseccomp-dev     libxml2-dev     libxslt-dev     linux-headers     nodejs     npm     python3=3.11.5-r0     python3-dev=3.11.5-r0     py3-numpy     py3-pip     py3-scipy     py3-wheel     redis     rsyslog     sudo
gcc     musl-dev     gfortran     openblas-dev:
0.116 fetch …
```
=> bump DN dockerfile python3 dependency to 3.11.6

.circleci/src/workflows/sdk.yml
Currently we are running sdk autopublish after every commit due to #6112 
We don't really need to autopublish now bc most things are npm workspaces. If we need a libs update in something like healthz we will need to manually publish for now
=> Remove sdk autopublish

packages/common/src/hooks/useFeatureFlag.ts, packages/mobile/metro.config.js, packages/mobile/package.json, packages/mobile/src/components/drawer/NativeDrawer.tsx
1. Fixes issue where collections were not loading. This is due to an issue with metro.config.js and storybook. The fix is to only apply the storybook metro changes when user runs `npm run start:storybook`
2. Fixes issue with native drawers not closing, due to an incorrect default `blockClose` prop
3. Fixes issue with feature-flag perf, where we were getting "maximum depth exceeded" errors. Ultimately the fix was to separate the now-async `getLocalFeatureFlag` call from the `getFeatureFlag` on remote config. This reduces the number of rerenders by 3x, bringing it back in line with previous behavior.
Shoutout to @nicoback and @sliptype for debugging help
=> [C-3181, C-3182] Fix collection loading, drawer closing, feature flag perf

discovery-provider/plugins/notifications/src/email/notifications/preRendered/withdrawal.ts, discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseSeller.ts, discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcWithdrawal.ts
=> [PAY-1975] Fix withdrawal email decimals

packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.tsx, packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.tsx, packages/web/src/components/withdraw-usdc-modal/components/EnterTransferDetails.tsx, packages/web/src/components/withdraw-usdc-modal/components/TransferInProgress.tsx, packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.tsx
* Fix up balance decimal places
* Do not render final balance until we get status success in the success screen (so we don't visibly jump from old balance => new balance)
* Reset form / state on modal close
=> [PAY-1960] Clean up withdrawals decimal places

discovery-provider/integration_tests/tasks/test_index_trending_notification.py, discovery-provider/integration_tests/tasks/test_trending_playlist_notifications.py, discovery-provider/src/api/v1/tracks.py, discovery-provider/src/queries/generate_unpopulated_trending.py, discovery-provider/src/queries/generate_unpopulated_trending_tracks.py, discovery-provider/src/queries/get_premium_tracks.py, discovery-provider/src/queries/get_recommended_tracks.py, discovery-provider/src/queries/get_trending.py, discovery-provider/src/queries/get_trending_ids.py, discovery-provider/src/queries/get_trending_playlists.py, discovery-provider/src/queries/get_trending_tracks.py, discovery-provider/src/queries/get_underground_trending.py, discovery-provider/src/tasks/cache_trending_playlists.py, discovery-provider/src/tasks/calculate_trending_challenges.py, discovery-provider/src/tasks/index_trending.py, packages/web/src/pages/premium-tracks-page/PremiumTracksPage.tsx
Issues:
**1. non usdc purchase tracks displaying in premium tracks explore page.**
This is because the trending logic first looks at the cache for the tracks, and if it misses, then it does the db query logic.
I overlooked updating the cache key for usdc purchase tracks so we ended up with non usdc tracks on the explore premium tracks page.
I didn't catch this bug because I mostly tested my original changes against local services, which didn't have enough tracks for me to notice. I did test a bit against stage, but i believe i missed it because of the timing factor between trending updates.
This PR not only fixes that bug, but it decouples the usdc purchase explore tracks from `get_trending_tracks`, and move the generation of unpopulated trending tracks to new file.
Ideally, we also …
=> [PAY-1974] Fix explore premium tracks bugs

packages/web/src/services/solana/WithdrawUSDC.ts
Makes creating the token account for the root wallet idempotent, allowing it to have already existed.
It has not.
=> Make createAssociatedTokenAccount idempotent for root wallet

packages/mobile/src/screens/favorites-screen/useCollectionsScreenData.ts
Before:
If you started app session offline, your offline collections would not load
After:
Fixed
=> Fix offline collections not loading if started offline C-3187

discovery-provider/src/tasks/index_user_bank.py
Dispatch the $AUDIO matching challenges in `index_user_bank.py` but only if the env is not prod, so that we can test on stage and local.
Local stack
=> Dispatch $AUDIO matching challenges in non-prod envs

packages/web/src/pages/upload-page/fields/RemixSettingsField/types.ts
Remix settings modal was failing to save due to the parent remix id being nullable instead of optional
locally against prod
=> [C-3199] Fix Remix Settings Not Saving (Web)

packages/mobile/src/components/core/ContextualMenu.tsx
By using our custom stack navigator push method, we were inadvertently hitting our custom check to see if the navigation was a duplicate (that prevents double navigation on double click) and not cleaning up after the navigation finished. By switching to navigate, we ignore this problem entirely.
tested on sim
=> [C-3197] Fixes being unable to reopen Upload modals on mobile

packages/compose/package.json, packages/compose/start.sh
Fix `npm run protocol`
I believe this is the best we can do without some crazy gymnastics.
`--` is necessary for the args because otherwise they are just params to `npm` itself
```
['/Users/ray/.local/bin/audius-compose', 'up']
npm run protocol up
['/Users/ray/.local/bin/audius-compose', 'up']
npm run protocol test up discovery-provider
['/Users/ray/.local/bin/audius-compose', 'test', 'up', 'discovery-provider']
npm run protocol up -- -d 3
['/Users/ray/.local/bin/audius-compose', 'up', '-d', '-3']
```
=> Make npm run protocol work without up

package-lock.json
The upgrade of ethereumjs-tx wasn't reflected in package-lock, because upgrading that dep changed it from not being hoisted to be hoisted. To resolve this I did:
```
cd packages/identity-service
npm remove ethereumjs-tx
npm install ethereumjs-tx@2.1.2
```
=> Update package-lock to update ethereumjs-tx

eth-contracts/scripts/setup-predeployed-ganache.sh
We are seeing flaky tests when attempting to build eth-ganache due to the setup-predeployed-ganache.sh script failing. [Example](https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/43636/workflows/f277865d-5788-4eae-a631-75deb88e8e89/jobs/561644)
CI
=> Debug ganache flakiness with verbose logging

dev-tools/compose/docker-compose.storagev2.yml, dev-tools/startup/register.py, dev-tools/startup/storagev2.sh, mediorum/Dockerfile, mediorum/Dockerfile.dev, mediorum/server/repair.go
* When unable to find peers, mediorum spams itself to death and eats an entire CPU core. Add a smaller sleep than the normal 10min between repair runs
* Add new Dockerfile.dev for audius-compose. This enables hot-reloading with air (s/o theo for Q&A).
```
```
http://audius-protocol-creator-node-1/health_check
looks good.
```
audius-cmd create-user freddie_mercury
audius-cmd upload-track --from freddie_mercury --title "Bohemian Rhapsody"
```
When modifying a file, we see
```
server/repair.go has changed
building...
running...
```
**CPU Before:**
**CPU After:**
=> Improve local dev mediorum cpu use, enable hot reload

packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx, packages/mobile/src/components/premium-track-purchase-drawer/PurchaseSuccess.tsx
Native mobile.
Navigate to track screen in the background on successful purchase.
Add new "View Track" button below the twitter button on successful purchase.
Tapping on either this new button or closing the drawer with the X icon should take user to the track screen for the track they just purchased.
local native mobile dapp vs stage
=> [PAY-1923] Navigate to track screen in the background on successful purchase

packages/mobile/src/screens/favorites-screen/TracksTab.tsx
Before: Empty state for offline tracks wouldn't show up
After: Empty state now shows up
=> Fix empty state for offline tracks C-3188

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/services/wallet-client/WalletClient.ts, packages/common/src/store/ui/transaction-details/types.ts, packages/common/src/store/wallet/selectors.ts, packages/common/src/store/wallet/slice.ts, packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/AccountDetails.tsx, packages/mobile/src/screens/audio-screen/AudioScreen.tsx, packages/mobile/src/screens/tip-artist-screen/AvailableAudio.tsx, packages/mobile/src/screens/wallet-connect/components/LinkedWallets.tsx, packages/web/src/common/store/pages/token-dashboard/sagas.ts, packages/web/src/common/store/tipping/sagas.ts, packages/web/src/common/store/wallet/sagas.ts, packages/web/src/components/audio-transactions-table/AudioTransactionsTable.tsx, packages/web/src/components/buy-audio-modal/components/SuccessPage.tsx, packages/web/src/components/nav/desktop/NavAudio.module.css, packages/web/src/components/nav/desktop/NavAudio.tsx, packages/web/src/components/tipping/tip-audio/SendTip.tsx, packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.tsx, packages/web/src/pages/audio-rewards-page/Tiles.module.css, packages/web/src/pages/audio-rewards-page/Tiles.tsx, packages/web/src/pages/audio-rewards-page/components/ConnectWalletsBody.tsx, packages/web/src/pages/audio-rewards-page/components/WalletActionsTile.tsx, packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.module.css, packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx, packages/web/src/pages/modals/Modals.tsx, packages/web/src/store/application/ui/buy-audio/sagas.ts
Before:
- If your AUDIO balance was still loading or errored out, we would just show it as 0 in various places, making users think their AUDIO disappeared
- Clicking "Total balance" on Rewards page was a no-op - somehow the Audio Breakdown modal disappeared
After:
- If your AUDIO balance is still loading, show loading state in various places
- In the nav bar, use balance stored on account object as a fallback if it's available (same as before)
- Report errors loading balance to Sentry
- Show error toast on AUDIO page/screen if balance failed to load
- Don't show "Balance" section on Transaction Details modals if we haven't loaded your balance
Future:
- Add loading state for connected wallets (added to backlog https://linear.app/audius/issue/C-3163/add-loading-state-for-connected-wallets-mo …
=> Add loading and error states for AUDIO balance; fix AudioBreakdown modal on web C-3164 C-3162

packages/web/src/pages/modals/Modals.tsx
Looks like AudioBreakdownModal made it into the list twice (probably a bad merge)
`npm run verify`
=> Fix lint on main

packages/mobile/src/screens/signon/FirstFollows.tsx, packages/web/src/common/store/pages/signon/sagas.js, packages/web/src/pages/sign-on/SignOnProvider.tsx
Before:
- Artist follows failed upon signup if you started the session signed into another account
After:
- Fixed
Tested on mobile and web for two cases:
1. Started session fresh (signed out)
2. Started session signed into another account, then sign out or delete account and sign up with new account
=> Actually fix follow artists step in sign up flow C-3206

dev-tools/audius-compose, eth-contracts/Dockerfile, eth-contracts/scripts/setup-dev.sh, packages/identity-service/src/app.js
* Remove identity notifications (no longer used) - @alecsavvy for review there
* Make sure audius-compose up runs audius-compose pull first so you get the latest images. Since we tagged our solana test validator build as :latest, you need to explicitly run pull
* Separate setup-predeployed-ganache.sh from the actual service registration scripts in eth contracts. This will improve our startup time considerably because right now *every day* the discovery/content node version changes and forces you to rerun setup-predeployed-ganache.
```
```
=> [PAY-1999] Improve local stack, figure out issue creating usdc user banks

dev-tools/compose/nginx_ingress.conf, packages/discovery-provider/scripts/register.py, packages/web/src/common/store/pages/audio-rewards/sagas.ts, solana-programs/scripts/deploy.sh
Config to register 2 more DNs and fixes a bug preventing registration.
Dragons:
- Is there any reason we'd need to wait for health check in `register.py`?
- We should probably push a new image with [this](https://github.com/AudiusProject/audius-protocol/blob/0657660ddd18fd7dae558ca7c322220e2e9377c1/solana-programs/scripts/deploy.sh#L218) set to 3 eventually! https://linear.app/audius/issue/PAY-2001/push-new-solana-validator-image-for-local-dev-with-min-votes-set-to-3
Tested local stack + claiming a challenge.
=> Register multiple DNs on local stack

packages/common/src/models/AudioRewards.ts, packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/store/challenges/selectors/optimistic-challenges.ts, packages/common/src/store/pages/audio-rewards/slice.ts, packages/common/src/store/pages/audio-rewards/types.ts, packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx, packages/web/src/common/store/pages/audio-rewards/sagas.ts, packages/web/src/common/store/pages/audio-rewards/store.test.ts, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewards.tsx
Plumbs amount mapped per-specifier down to libs to attempt to claim the correct amounts.
Probably got a bit too fancy with this `SpecifierMap` thing when a `{specifier: string, amount: number}[]` would've been simpler. Not sure I like seeing `Object.entries` everywhere. Thoughts?
Successfully claimed 2 challenges with different amounts on local stack!
=> [PAY-2003] Fix challenge disbursement with variable amounts

packages/discovery-provider/ddl/migrations/0036_add_challenge_disbursement_cap.sql
This migration wasn't idempotent which was causing errors when trying to add another migration.
Ran `pg_migrate.sh` locally.
=> Make weekly cap migration idempotent

packages/web/src/components/data-entry/ContextualMenu.tsx
Improves ContextualMenu submit pattern by associating the "submit" button with the form. If a submit button is in a form, it automatically gets connected, but in this case, the button is outside the form, so we have to manually associate using "id" and "form" props
=> [C-3198] Improve ContextualMenu submit pattern

mediorum/ddl/add_delist_reasons.sql, mediorum/ddl/ddl.go, packages/discovery-provider/ddl/migrations/0037_add_delist_reasons.sql, packages/discovery-provider/plugins/notifications/src/types/dn.ts, packages/discovery-provider/src/models/delisting/track_delist_status.py, packages/sql-ts/res/content-node.ts, packages/sql-ts/res/discovery-node.ts, packages/trpc-server/src/db-tables.ts
Expands enum for track delist reasons in CN and DN.
Checked the db types on stage DN5 and CN6, and confirmed that new track delist statuses get indexed (they infinitely retry on other nodes that don't have the new enums).
```sql
SELECT enumlabel 
FROM pg_enum 
WHERE enumtypid = 'delist_track_reason'::regtype;
```
The main concern is that if some nodes aren't on postgres 11+ then they won't be able to do an `ALTER TYPE` query. I think the solution is that those nodes should just be forced to upgrade.
=> [PROTO-1326] Add more delist reasons

packages/mobile/src/components/track-list/TrackList.tsx, packages/mobile/src/components/track-list/TrackListItem.tsx, packages/mobile/src/screens/favorites-screen/TracksTab.tsx, packages/web/src/components/track/mobile/TrackList.tsx, packages/web/src/components/track/mobile/TrackListItem.tsx, packages/web/src/pages/collection-page/components/mobile/CollectionPage.tsx, packages/web/src/pages/history-page/components/mobile/HistoryPage.tsx, packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
Improves favorites track list ui, by replacing the "favorite" action with kebab menu, giving user more flexibility to interact with their favorited tracks.
- Went ahead and removed that option entirely cause it doesn't really make sense to have an "unfavorite" option in the list of favorited tracks. 90% of the time it's a missclick.
Before:
After:
=> [C-2887] Improve favorites track list ui

packages/discovery-provider/src/queries/get_attestation.py
Don't need this anymore, can just use whether or not `cooldown_days` exists in the challenge.
Claimed challenges on local dev and confirmed they fail with `WAIT_FOR_COOLDOWN`.
=> Remove COOLDOWN_CHALLENGE_IDS in get_attestation.py

packages/common/src/models/AudioRewards.ts, packages/common/src/store/challenges/selectors/optimistic-challenges.ts, packages/common/src/store/pages/audio-rewards/slice.ts, packages/common/src/store/pages/audio-rewards/types.ts, packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx, packages/web/src/common/store/pages/audio-rewards/sagas.ts, packages/web/src/common/store/pages/audio-rewards/store.test.ts, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
Remove the unnecessarily fancy `SpecifierMap` type and use an array of `SpecifierWithAmount` instead (name suggestions?).
Just changing a type from https://github.com/AudiusProject/audius-protocol/pull/6316 really.
Confirmed claiming multiple rewards with varying amounts works on local stack.
=> Simplify claiming variable-amount challenges

mediorum/ddl/add_delist_reasons.sql, packages/discovery-provider/ddl/migrations/0037_add_delist_reasons.sql
For some reason, content nodes are wrapping SQL in transactions even when setting `SkipDefaultTransaction=true`. This changes a migration to work inside a transaction (and to work before postgres 11 because `ALTER TYPE` wasn't supported before then). Also updates the discovery migration for consistency.
- Ran the full tag (not just SQL) on stage CN8 and prod CN5
- `audius-compose test run "mediorum-unittests"` now passes
=> Use more supported migration for mediorum workaround

packages/discovery-provider/plugins/verified-uploads/src/handlers/users.js
=> Fix verified check because of identity time drift

packages/stems/src/components/Button/Button.tsx, packages/stems/src/components/HarmonyButton/HarmonyButton.tsx
Adds deprecation warning to HarmonyButton and updates the suggested use for the stems/Button deprecation warning.
=> [C-3213] Add deprecated label to HarmonyButton

packages/discovery-provider/scripts/start.sh
Follow up to reduce memory usage. If a worker has 7 child processes with max mem of 300 MB each, that single worker can consume 2.1 GB. We've seen cases where a single worker can run out of memory and take down the whole server. This reduces memory usage for other tasks without impacting indexing ACDC.
The downside is it might impact how up to date other tasks are but I'm keeping an eye on that as well.
Tested on sandbox. Confirmed indexing and resource usage is healthy. Typical mem usage went from 2 GB to 1 GB.
=> Tune celery worker concurrency

.circleci/config.yml, .circleci/src/@continue_config.yml, .circleci/src/workflows/healthz.yml, .circleci/src/workflows/release.yml
Keep healthz continuously kept up to date as with all other services.
`audius-compose build --prod healthz`
=> [PROTO-1349] Continuous deployment for healthz

.circleci/config.yml
Updates Slack messages to reflect foundation node auto-deploy moving 1 hour later to 11am PST. After PR approval, I'll change the trigger in CircleCI to be an hour later.
`circleci local execute generate-release` (with some tweaks to run locally and DM on Slack) ~~recognized that today is Friday and sent me the message saying it will run at 11am instead of 10am~~.
=> Delay foundation deploy by 1hr

packages/mobile/src/components/premium-track-purchase-drawer/AudioMatchSection.tsx, packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx, packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.module.css, packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx, packages/web/src/components/premium-content-purchase-modal/components/AudioMatchSection.module.css, packages/web/src/components/premium-content-purchase-modal/components/AudioMatchSection.tsx
Add $AUDIO match to premium purchase drawers to inform users of rewards
web
moweb
mobile
=> [PAY-1982] Add AudioMatchSection in premium purchase modal/drawer

packages/mobile/src/components/premium-track-purchase-drawer/PurchaseSummaryTable.tsx, packages/web/src/components/premium-content-purchase-modal/components/PurchaseSummaryTable.tsx
Fixes PAY-1954
#6317 Changed the check in the web version of the premium content form to show the existing balance line if it's defined. We were leaning on the falsey check to exclude `0`. So this adds an explicit > 0 check and makes it consistent between web/mobile
Tested locally in Chrome against Staging
=> [PAY-1954] Fix display of $0 existing balance on web purchase form

package-lock.json, packages/web/package.json, packages/web/src/components/dragndrop/Draggable.tsx, packages/web/src/components/dragndrop/Droppable.tsx, packages/web/src/components/nav/desktop/LeftNavLink.tsx
Adds `asChild` pattern using @radiux-ui/react-slot. This will be very helpful for harmony components, where we can change the underlying element of our components easily.
This will be used to improve the table render logic, by removing the wrapping divs that drag/drop used to force.
https://medium.com/@bryanmylee/aschild-in-react-svelte-vue-and-solid-for-render-delegation-645c73650ced
=> [C-3216] Add react-slot, implement asChild for drag/drop

packages/mobile/src/components/fields/PriceField.tsx, packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
Fixes PAY-1973
Pretty simple issue: I am not a seasoned RN developer and did not realize that [you shouldn't attempt to read text from `onBlur` events](https://reactnative.dev/docs/textinput#onblur) 😅 . 
I also noticed that the buy button was not showing the correct values on mobile and fixed that while I was at it.
Tested on Pixel 5 and iOS simulator against staging
=> [PAY-1973] Fix Android crash and buy button text for purchase flow

.circleci/src/workflows/discovery.yml
Preemptive fix for [audius-docker-compose PR](https://github.com/AudiusProject/audius-docker-compose/pull/384). If audius-docker-compose is updated with a git sha that healthz hasn't been built for, pull will fail.
Will verify push-healthz is run on main when landed.
=> [PROTO-1349] Build healthz in discovery workflow to ensure staging availability

packages/common/src/store/pages/audio-rewards/selectors.ts, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
Filter out challenges that are not past the cooldown period and don't attempt to claim them.
Local stack with 3 DNs + AAO - confirmed only challenge past cooldown was disbursed, and no errors from trying to claim other challenges that were not past cooldown.
=> [PAY-2035] Only claim challenges past cooldown period

packages/web/src/components/table/Table.tsx
Fixes issue where quickly scrolling through a virtualized table can result in buffer overflow index issue. The fix is to just return null for overflow rows.
=> [C-3215] Fix transaction table error

package-lock.json, packages/web/package.json, packages/web/scripts/dist.js
Apple requires us to move from altool to notarytool for notarizing our macos app. Upgrading to the latest @electron/notarize solves this problem, since they default to using notarytool behind the scenes
=> [C-2769] Migrate from altool to notarytool

packages/web/scripts/dist.js
Updates our mac app build to enable arm64 builds. Should result in major perf improvements for our mac electron app.
=> [C-3169] Make mac app universal

packages/mobile/src/screens/audio-screen/Panel.tsx, packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx, packages/web/src/pages/audio-rewards-page/RewardsTile.module.css
Adds the components for the 'New!' badge on web and mobile, which will show on audio matching challenges if they aren't currently claimable
Tested locally on chrome and iOS simulator against staging
Web
Mobile
=> [PAY-2027] Implement new challenge badge for audio matching challenges

package-lock.json, packages/mobile/README.md, scripts/postinstall.sh
* Run `bundle install` for ios gems in postinstall script. This means we don't need to manually install a global version of `cocoapods`
Tested that remove the globally installed cocoapods and doing an npm i results in the gems & pods being installed correctly
=> Automate bundle install in postinstall script

packages/common/src/models/Track.ts, packages/web/src/pages/upload-page/fields/AttributionField.tsx
We initialize `ai_attribution_user_id` to `null` when the upload page is mounted, but the sub form for attribution erroneously unsets it on submit if ai attribution is not selected. Changing the code to set to `null` fixes it for now, but we probably want a better long term solution
fixes C-3239
=> [C-3239] Fix accidental unset of required prop in upload form

mediorum/server/serve_upload.go
before the created_at OR transcoded_at with small window size means cursor got stuck doing backfill...
so this makes it just use created_at and slightly larger window size
=> mediorum: scroll upload by created_at

dev-tools/setup-dev.sh
* Remove last usage of `npm link`. This is no longer needed due to monorepo & npm workspaces
=> [INF-453] Remove npm link

.circleci/scripts/circleci-startup-script.sh, .circleci/src/jobs/test-audius-cmd.yml, dev-tools/setup.sh
CircleCI Docker Layer Caching does not work. But by hosting our own job runners, we can achieve the same benefits more easily.
This diff enables self-hosted runners only for test-audius-cmd. Other tests will follow if this proves useful. 
[The first time](https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/44263/workflows/81c9da5f-3a1d-48cc-baab-7e7e9ce6b2b7/jobs/570262) the test workflow is run on a machine, there is no cache and the test takes ~20 minutes.
[The second time](https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/44263/workflows/288000a3-aba9-4365-949b-043125680648/jobs/570269), the test takes only ~2 minutes.
=> [PROTO-1356] Use self-hosted gcp runners for circleci

packages/common/src/models/Analytics.ts, packages/common/src/store/pages/chat/middleware.ts, packages/common/src/store/pages/chat/sagas.ts, packages/common/src/store/pages/chat/slice.ts, packages/common/src/store/pages/chat/types.ts
We see a high volume of unhandled errors from the Chats API event emitter. They aren't a useful signal most of the time. But we _do_ want to log errors with a `code` value, since those would indicate unexpected issues with the _data_ sent through the websocket.
Fixes PAY-2036
Tested locally in Chrome against Staging.
=> [PAY-2036] Reduce spam from websocket errors

.circleci/src/jobs/test-audius-cmd.yml
Containers will stay running if we don't perform cleanup at the end of self-hosted tests.
[CI success](https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/44294/workflows/030e57f8-3377-47ad-95d8-846c9c42b09e/jobs/570695)
=> [PROTO-1356] Tear down containers following self-hosted test

.circleci/src/jobs/alert-slack-push-success.yml, .circleci/src/workflows/release.yml
The daily deploy Slack alert job was not able to push the commit message for today's release because I forgot to give it the necessary secrets. Failure message: `Username for 'https://github.com': fatal: could not read Username for 'https://github.com': Success`
I can't test without the secrets, so I plan to run another trigger on the hour to make sure it's able to push the commit this time.
=> Add missing GH context to deploy msg job

packages/common/src/models/Analytics.ts, packages/common/src/services/audius-backend/stripe.ts, packages/common/src/store/buy-usdc/sagas.ts, packages/common/src/store/buy-usdc/slice.ts, packages/common/src/store/ui/stripe-modal/sagas.ts, packages/common/src/store/ui/stripe-modal/slice.ts, packages/common/src/store/ui/stripe-modal/types.ts, packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx
fixes PAY-2038
This cleans up a TODO for catching errors when initializing the Stripe session. We will now pipe them back up to the USDC purchase saga and merge into the error flow there. This has the result of canceling the purchasing state and showing an error at the bottom of the modal. We will log the errors to analytics.
There are future tickets to pipe more detailed information back from the createSession call.
Tested locally on Chrome against staging
=> [PAY-2038] Catch errors creating stripe session and cancel purchase

packages/common/src/models/AudioRewards.ts, packages/common/src/services/audius-api-client/AudiusAPIClient.ts, packages/common/src/utils/challenges.ts, packages/discovery-provider/src/api/v1/models/users.py, packages/discovery-provider/src/queries/get_challenges.py, packages/discovery-provider/src/utils/spl_audio.py, packages/libs/src/services/discoveryProvider/DiscoveryProvider.ts, packages/web/src/common/store/pages/audio-rewards/store.test.ts, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/AudioMatchingRewardsModalContent.tsx
Fixes a bug discovered during QA where the challenge would show a "total claimed so far" amount even before the challenge was claimed, and after claiming the value was also incorrect.
This ended up being more of a rabbit hole than I wanted but it works now! And in the process I discovered that my previous changes had broken referrals (other aggregate challenge that's not $AUDIO matching), which is also fixed now.
Dragon:
I am using `IsAudioMatchingChallenge` as a proxy for whether the challenge has a cooldown period. This works for now because only $AUDIO matching challenges have cooldowns. But if/when that changes this will break. Should really cross-ref with the challenge and whether or not is has a `cooldown_days` field as a way to know whether it has a cooldown period or not, but that …
=> [PAY-2060] Fix wrong challenge claimed so far amounts

packages/common/src/utils/challenges.ts
Make it so that audio matching challenges appear at the top of the challenge list.
Local stack
=> Float audio matching challenges to the top

packages/common/src/hooks/purchaseContent/useChallengeCooldownSchedule.ts
Fixes a bug that AJ caught where 2 challenges from 2 different dates would get lumped together incorrectly.
Tested on local stack. May not have covered all cases but will continue to monitor with AJ.
=> Fix cooldown challenge schedule wrong dates

packages/mobile/src/screens/edit-track-screen/screens/AccessAndSaleScreen.tsx, packages/mobile/src/screens/edit-track-screen/screens/RemixSettingsScreen.tsx, packages/mobile/src/screens/track-screen/TrackScreenDownloadButtons.tsx, packages/web/src/common/store/remix-settings/sagas.ts, packages/web/src/components/download-buttons/DownloadButtons.tsx, packages/web/src/components/remix-settings-modal/RemixSettingsModal.tsx, packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx, packages/web/src/pages/upload-page/fields/RemixSettingsField/RemixSettingsField.tsx, packages/web/src/pages/upload-page/fields/RemixSettingsField/RemixSettingsMenuFields.tsx, packages/web/src/pages/upload-page/fields/RemixSettingsField/types.ts, packages/web/src/pages/upload-page/fields/availability/collectible-gated/CollectibleGatedRadioField.tsx, packages/web/src/pages/upload-page/fields/availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx
- Only allow stems downloads if user has access to track
- Only allow setting a track as a remix of a gated track if user has access to that gated track
- Fix regression on web that made it possible for gated tracks to also be remixes. Gated tracks should not be remixes of other tracks.
There is still a related [linear card](https://linear.app/audius/issue/PAY-2056/[usdc]-editing-premium-track-on-mobile-changing-access-super-broken) that needs to handle the access & sale fields to correctly reflect the selection of the user.
local web and native mobile dapps vs stage
----------
----------
----------
=> [PAY-2019] Update premium content remixes and stems logic

README.md, dev-tools/README.md, packages/commands/README.md, scripts/postinstall.sh, scripts/preinstall.sh
* Update readme to be easier to understand in regards to the monorepo
* The aim here was to keep the top level readme quite simple, with easy to follow setup instructions. Then more detail about each package can be found in the corresponding readme
* Automatically install the proper node, python, and ruby version in the preinstall script
* This means `nvm`, `pyenv`, and `rbenv` are no longer suggestions but requirements
* Automatically run `dev-tools/setup.sh` in the postinstall, this makes it so that `npm run protocol` works out of the box
* Thanks @phelpsdb for making this script idempotent!
Tested by creating a new macos user, and following the readme instructions to set everything up from scratch
=> [INF-490] Update readme

.circleci/config.yml, .circleci/src/jobs/alert-slack-push-success.yml, .circleci/src/jobs/commit-audius-docker-compose-and-notify.yml, .circleci/src/jobs/deploy-stage-nodes.yml, .circleci/src/workflows/release.yml
Fixes a race condition with auto-deploy:
1. Commit on `main` is what triggers CI to update the tag for each service in audius-docker-compose (via the `deploy-stage-nodes` job which runs for every commit on main)
2. Commit on `release-vX.Y.Z` branch is what triggers CI to push a commit to mark the release in audius-docker-compose
- This completes after the tag gets set for CN, but DN takes longer to build so it uses the tag that's right before the commit (same actual code but without the cosmetic version bump)
Fixed by having the release branch CI set the tag when it pushes the commit to mark the release on audius-docker-compose.
=> Fix race condition in compose deploy

protocol-dashboard/package-lock.json, protocol-dashboard/package.json
I was getting VSCode errors as well as errors with local preview and prod build+serve. Making the `@types/react` version match the installed React version fixed it for me. (I also had to wipe my node_modules and package-lock, reinstall with `--legacy-peer-deps`, and then restart VSCode).
Now working for me:
- `npm run start:stage`
- `npm run build:prod && npm run serve`
=> Make proto dash @types/react version consistent

.circleci/scripts/circleci-startup-script.sh
To prevent the docker cache from eventually filling up the disk, we will occasionally prune. Note that this will not remove all cached layers so we still benefit from speedup even on jobs that run following a prune.
Cron job is successfully configured on existing self-hosted runner. Syslog output:
```
Oct 20 04:06:57 circleci-runner-instance-2 dockerprune: Total reclaimed space: 51.77GB
```
=> Disk cleanup cron job for self-hosted runners

sdk-consumer/index.ts
If an SDK action is taken before it's fully initialized, it will use production CNs by default. this passes in a StorageNodeSelector with the correct dev CNs.
Ran locally and confirmed bootstrap nodes are configured and upload track works.
=> Configure bootstrap dev CNs in sdk consumer

packages/common/src/hooks/purchaseContent/useChallengeCooldownSchedule.ts, packages/mobile/src/components/challenge-rewards-drawer/AudioMatchingChallengeDrawerContent.tsx, packages/mobile/src/components/challenge-rewards-drawer/CooldownSummaryTable.tsx, packages/mobile/src/components/premium-track-purchase-drawer/PurchaseSummaryTable.tsx, packages/mobile/src/components/summary-table/SummaryTable.tsx, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/AudioMatchingRewardsModalContent.tsx
Cooldown schedule UI for mobile
Local ios dev
Purchase summary table UI hasn't changed:
New UI:
=> [PAY-2034] Mobile cooldown schedule UI

packages/common/src/store/purchase-content/utils.ts, packages/mobile/src/components/fields/PriceField.tsx, packages/mobile/src/components/premium-track-purchase-drawer/PayExtraFormSection.tsx, packages/web/src/components/form-fields/PriceField.tsx, packages/web/src/components/premium-content-purchase-modal/components/PayExtraFormSection.tsx
Also fixes PAY-2048
Fix a couple issues with pay extra custom amount form validation
Behavior is as follows
1. User clicks custom amount, validation passes at `undefined` input
2. If the user clicks "Buy" validation fails
3. If the user types a 1, validation passes
4. If the user types over 100, validation fails
5. If the user loses input focus, `.00` is added
6. If the user enters a number > 13 chars (len(2^53), if you include the cents), the input stops letting new numbers go in so we don't crash the app on numeric bounds issues
Above use case on web & mobile
=> [PAY-1980] Fix pay extra form validation

.circleci/src/jobs/deploy-foundation-nodes.yml, .circleci/src/jobs/release-audius-docker-compose.yml
Uses a regular merge instead of a hard-reset + force-push for auto-deploys. I thought we needed the hard reset due to merge conflicts in the past, but a regular merge should be fine as long as we go through the flow of merging everything to the `stage` branch and not pushing directly to the `foundation` branch.
Note that we still need to hard-reset audius-docker-compose `main` once to be even with `foundation`. Releases to `main` are blocked until then. From then on, all 3 branches (stage+foundation+main) will have the same history.
=> Use regular merge in deploys

dev-tools/setup.sh
/etc/os-release is not a directory, it will never be properly sourced.
CI
=> Change flag in setup.sh to check file existence, not dir

dev-tools/setup.sh
Fixes `npm i` at root failing due to:
```
+ '[' -f /etc/os-release ']'
+ case "$ID" in
./dev-tools/setup.sh: line 6: ID: unbound variable
npm ERR! code 1
npm ERR! path /Users/theo/workspace/audius-protocol
npm ERR! command failed
npm ERR! command sh -c bash ./scripts/postinstall.sh
```
The fix is to just allow unbounded variables. Probably a better fix would be to only run the `case "$ID" in"` block if `/etc/os-release` was able to be sourced.
```
git clone --branch theo-fix-setupsh https://github.com/AudiusProject/audius-protocol.git
cd audius-protocol
npm i
```
=> Fix failing root npm install

packages/common/src/models/Analytics.ts, packages/common/src/store/purchase-content/sagas.ts
This rounds out the analytics info we want for starting and finishing the purchase flow
fixes PAY-2012
Tested locally against staging in Chrome.
=> [PAY-2012] Add analytics for purchase start/success/failure

packages/mobile/src/components/summary-table/SummaryTable.tsx, packages/web/src/components/summary-table/SummaryTable.module.css, packages/web/src/components/summary-table/SummaryTable.tsx
Because we were using CSS last-child to add the grey background to the last row, the last row was always grayed out. But we don't want to gray out the last row if there is no summary (showing amount that is claimable now).
Also updating "grey" to "gray" in mobile SummaryTable for consistency.
Local web
PurchaseSummaryTable UI stays the same:
CooldownSummaryTable updated:
=> SummaryTable don't gray out last row if no SummaryItem

packages/discovery-provider/src/queries/get_notifications.py, packages/discovery-provider/src/tasks/entity_manager/entities/track.py
This was missing in previous implementations.
It adds an extra query that will slow things down a bit, but generally speaking, it'll all fit within a page size and be good enough to take us through release.
Checked with @sddioulde  about the deleting of premium_conditions fields when a track is deleted
stage dn5
=> Filter out usdc create notifs from endpoint

.circleci/src/@continue_config.yml, .circleci/src/jobs/deploy-foundation-nodes.yml, .circleci/src/jobs/release-audius-docker-compose.yml, .circleci/src/workflows/patch-release.yml
I'm not sure if it's possible for a non-CI GitHub user to deploy a patch to the audius-docker-compose `main` branch due to branch protections. If it's not, this PR gives a way to do off-release patches by manually triggering a job with the parameter `patch-release-commit-sha`=`<desired audius-docker-compose SHA>`.
TODO
=> Add CI workflow to patch a SHA outside of release

packages/common/src/utils/wallet.ts
Previous implementation was broken
https://github.com/AudiusProject/audius-protocol/pull/6037/files#diff-52168295d11e3bce18265ac1c5997dd0242622baf3e6292622807ce73cca1bf4L113
If the value is < 9 decimals (or provided number of decimals), we don't pad the front so we would over charge.
This PR returns the implementation to what it was before, just using the BigInt relevant functions.
Tested via locally running buy audio flow. Values convert as expected.
I really wish we could have working unit tests in client codebase. We'll work on that ASAP.
=> Fix $AUDIO purchase

packages/common/src/hooks/purchaseContent/useChallengeCooldownSchedule.ts, packages/mobile/src/components/challenge-rewards-drawer/CooldownSummaryTable.tsx, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/AudioMatchingRewardsModalContent.tsx
Sometimes the `cooldownChallengesSummary` doesn't exist bc none of the challenges are claimable yet, but there are still challenges waiting for the cooldown period that should be displayed.
How to check if array initialized with `new Array(x)` is empty:
Local web
With no cooldown challenges:
With cooldown challenges:
With summary only:
=> Fix cooldown summary table

.circleci/config.yml, .circleci/src/@continue_config.yml
The `patch-release-commit-sha` pipeline parameter was in the continue config, but in order to be manually triggered it needs to also be in the root config. This fixes that and is tested by triggering the job on this branch.
=> Fix triggering patch-release workflow

packages/harmony/src/components/input/SelectablePill/SelectablePill.module.css, packages/harmony/src/components/input/SelectablePill/SelectablePill.tsx, packages/harmony/src/components/input/SelectablePill/types.ts, packages/mobile/src/components/core/HarmonySelectablePill.tsx, packages/mobile/src/components/premium-track-purchase-drawer/PayExtraFormSection.tsx, packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx, packages/web/src/components/premium-content-purchase-modal/components/PayExtraFormSection.tsx, packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx
Adds disabled variants for `SelectablePill` on mobile and web, display those while the purchase transaction is underway.
Preferring `disabled` instead of `isDisabled`.
confirmed the buttons are not clickable
=> [PAY-1962] Disable selectable pills during purchase

packages/mobile/src/screens/feed-screen/FeedScreen.tsx, packages/web/src/components/lineup/LineupProvider.tsx, packages/web/src/pages/feed-page/components/desktop/FeedPageContent.tsx
Feed tip tile should not show when USDC purchases is on.
```
npm run mobile
```
=> [PAY-1998] Hide feed tip tile when USDC purchases is on

packages/harmony/src/components/button/Button.module.css, packages/harmony/src/components/button/Button.tsx
We were using the :before overlay to set the hover/active colors for buttons. However, this wasn't coloring the border, so we were removing the border on hover and adding a margin to compensate.
In the below usage, we set a margin on the button for layout. On hover, the hover margin hack takes precedence and breaks the layout.
Fix is to switch to using css color-mix to calculate the lightened or darkened background color and use that to set the border color as well.
Is this feature supported well enough for us? https://caniuse.com/?search=color-mix
local storybook matches designs
local web no longer shows the issue on instance where bug was reported
=> [C-3267] Use css color mixing instead of overlay/margin hack

packages/common/src/models/Analytics.ts, packages/common/src/services/audius-backend/solana.ts
The original user bank events were designed for a slightly different flow. The current flow doesn't have a way for us to hook into the "request" part, we just know afterwards if there was an error and whether the userbank had to be created. So I adjusted the code to send a success event if the user bank is created and then send along any failures encountered.
The event structure also didn't match what we are currently sending, which doesn't impact our ability to ingest them. But I updated it to be accurate anyway. We will need to do a bit of an overhaul on events later on.
fixes PAY-2032
=> [PAY-2032] Clean up userbank analytics events

mediorum/crudr/crudr.go
Partitioning `ops` no longer needed because:
* we partitioned on host, but no longer filter on current host, so the partitioning is now detrimental to query performance.
* ops table is much smaller now
Tested locally on a db with partitions and without.
tested on stage CN 12
=> de-partition ops table

packages/common/src/services/remote-config/defaults.ts, packages/common/src/services/remote-config/types.ts, packages/web/src/common/store/lineup/sagas.js
In explore premium tracks page, only show tracks from users that are in an allowlist, which is a remote var named `EXPLORE_PREMIUM_ALLOWED_USERS`.
single handle that appears very far down the unfiltered lineup:
2 handles:
empty (default):
=> [PAY-1972] Filter out spammy accounts from explore premium tracks page

packages/identity-service/src/routes/stripe.js
This catches the code/message/type fields from stripe session creation errors and returns them back as part of the response. This will allow us to catch those errors on the client and report more useful information.
There will be a follow-up PR to consume these messages in the client.
fixes PAY-2041
Tested with local identity service against testing environment for stripe
=> [PAY-2041] Return extended error information when stripe session creation fails

package-lock.json, packages/harmony/package.json, packages/harmony/src/components/button/BaseButton.module.css, packages/harmony/src/components/button/BaseButton.tsx, packages/harmony/src/components/button/Button.stories.tsx, packages/harmony/src/components/button/types.ts
Adds asChild to Button to enable "link" type flows. We may want to build links into our buttons since it is such a common pattern. or potentially build a button-link implementation in web, since it would be based of react-router/dom's Link
=> [C-3263] Add asChild to harmony Button

packages/mobile/.storybook/storybook.requires.ts, packages/mobile/src/harmony-native/components/Link/Link.stories.tsx, packages/mobile/src/harmony-native/components/Text/Text.test.tsx, packages/mobile/src/harmony-native/components/Text/Text.tsx, packages/mobile/src/harmony-native/components/Text/index.ts, packages/mobile/src/harmony-native/foundations/color/color.stories.tsx, packages/mobile/src/harmony-native/foundations/color/color.ts, packages/mobile/src/harmony-native/foundations/color/index.ts, packages/mobile/src/harmony-native/foundations/color/primitive.ts, packages/mobile/src/harmony-native/foundations/color/semantic.ts, packages/mobile/src/harmony-native/foundations/index.ts, packages/mobile/src/harmony-native/foundations/theme/ThemeProvider.tsx, packages/mobile/src/harmony-native/foundations/theme/index.ts, packages/mobile/src/harmony-native/foundations/theme/makeStyles.ts, packages/mobile/src/harmony-native/foundations/theme/theme.ts, packages/mobile/src/harmony-native/foundations/theme/useTheme.ts, packages/mobile/src/harmony-native/foundations/types.ts, packages/mobile/src/harmony-native/foundations/typography/Text.test.tsx, packages/mobile/src/harmony-native/foundations/typography/Text.tsx, packages/mobile/src/harmony-native/foundations/typography/Typography.stories.tsx, packages/mobile/src/harmony-native/foundations/typography/index.ts, packages/mobile/src/harmony-native/foundations/typography/typography.ts
Adds harmony-native typography
Adds harmony-native theming
Updates harmony-native colors
Adds Text story
Adds Text tests
https://github.com/AudiusProject/audius-protocol/assets/8230000/eaad71d6-dd0c-4768-b24f-003e32bc387e
=> [C-2892 C-3253 C-3254] Add harmony-native typography

packages/libs/src/sdk/services/Storage/Storage.ts, packages/libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.test.ts, packages/libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.ts, packages/libs/src/sdk/services/StorageNodeSelector/types.ts, packages/libs/src/services/creatorNode/CreatorNode.ts
Add fallbacks to upload on SDK (only libs had these fallbacks), using reselection to re-use the same healthy node for future requests. Note that the list of nodes comes from Discovery health checks, so they're already filtered to healthy nodes.
=> Add fallbacks to SDK upload

packages/common/src/models/Analytics.ts, packages/common/src/store/buy-usdc/utils.ts, packages/common/src/store/ui/stripe-modal/sagas.ts, packages/common/src/store/ui/stripe-modal/types.ts, packages/libs/src/AudiusLibs.ts, packages/libs/src/services/identity/IdentityService.ts
Follow-up to #6461, this connects the extended error info to analytics so we can track errors in stripe session creation.
* Added a type export from libs so that we have a slight bit more type safety. Identity just re-throws Axios errors, so we need to pull the info out of `response.data`. I'm not using the `AxiosError` type directly because:
1. Axios is not currently a dependency of `common`.
2. I wanted to keep the inner details of how Identity generates errors decoupled.
* Added custom error class for stripe session errors with the fields we get back from the API
* Added analytics event
(Bonus: Fixed a circular dependency that I introduced in a previous PR)
Tested locally in Chrome against staging.
=> [PAY-2041] Connect stripe session creation errors to analytics

packages/mobile/src/components/now-playing-drawer/Artwork.tsx, packages/mobile/src/components/now-playing-drawer/PlayBar.tsx, packages/mobile/src/components/now-playing-drawer/TrackInfo.tsx, packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx, packages/web/src/components/nav/desktop/NowPlayingArtworkTile.tsx, packages/web/src/components/play-bar/desktop/components/PlayingTrackInfo.tsx, packages/web/src/components/play-bar/mobile/PlayBar.tsx, packages/web/src/components/track/LockedStatusBadge.module.css
Fix PAY-2051.
Also fix a bug where if you're on the track page on mobile, clicking the `Preview` button plays and pauses the non preview version.
Local simulator + web, tested tracks, previews, your own tracks, and your own previews
=> [PAY-2051] Show preview UI when playing your own preview

packages/identity-service/src/routes/stripe.js
Changing wallet addresses during the stripe flow isn't something we want to support. Stripe has a session parameter that will lock the address to the value initially provided by us. So this adds that flag to the session creation on identity.
fixes PAY-1986
Tested locally against identity service. Needs to be verified in staging with client.
=> [PAY-1986] Lock wallet address during stripe session creation

packages/harmony/src/components/input/TextInput/TextInput.module.css
- Make the TextInput cursor on disabled be default (no longer not-allowed)
- Placeholder text color changed to `subdued` per design feedback
Manual storybook
=> Harmony Text Input tweaks (design requests)

.circleci/src/jobs/push-docker-image.yml
Self-hosted runners have been working reliably so far. Adding the push-docker-image jobs will further speed up ci while saving circleci credits.
Will monitor CI - push jobs are only active on main.
=> Use self-hosted runners for pushing images

packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx, packages/web/src/components/premium-content-purchase-modal/components/PayToUnlockInfo.module.css, packages/web/src/components/premium-content-purchase-modal/components/PayToUnlockInfo.tsx, packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx
Make ToS unclickable while purchase is in progress. The UI won't look any different but won't be clickable.
Local web stage + ios stage
=> [PAY-2052] Disabled TOS while purchase in progress

package-lock.json, packages/common/package.json, packages/common/src/models/Analytics.ts, packages/common/src/store/purchase-content/sagas.ts, packages/common/src/store/ui/stripe-modal/sagaHelpers.ts, packages/common/src/store/ui/stripe-modal/sagas.ts, packages/common/src/store/ui/stripe-modal/slice.ts, packages/common/src/store/ui/stripe-modal/types.ts, packages/mobile/src/components/stripe-onramp-drawer/StripeOnrampEmbed.tsx, packages/web/src/components/stripe-on-ramp-modal/StripeOnRampModal.tsx
* Rounded out the types for Stripe session info that we're receiving, mostly using the types from `@stripe/crypto` and modifying based on what I observed through logging the session objects.
* Pipe the whole session object to the slice, so we can use it for analytics
* Added saga helper to detect changes in state and pipe events as necessary
* Updated our purchase content events to include the total (price + pay extra) as an explicit field so we don't have to try and merge those values in reports
* Added sentry logging for rejection and error cases. 
Fixes PAY-2014
Tested locally in Chrome and Simulator against staging
Note: I can't finish the flow locally and will fully validate this on staging, but have confidence since we are only tracking a couple of fields and the status.
=> [PAY-2014] Add detailed purchase flow analytics

packages/common/src/services/remote-config/feature-flags.ts, packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx, packages/mobile/src/components/premium-track-purchase-drawer/PurchaseUnavailable.tsx
Added new feature flag IOS_USDC_PURCHASE_ENABLED and set it to 100% (enabled) for both prod and dev environments. Confirmed that setting it to 0 results in the purchase button being hidden and "purchase is unavailable" message being displayed.
=> [PAY-1943] Separate feature flag for IOS USDC Purchase

packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx, packages/web/src/components/premium-content-purchase-modal/components/PayToUnlockInfo.module.css, packages/web/src/components/premium-content-purchase-modal/components/PayToUnlockInfo.tsx, packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx
Hide the ToS completely when the purchase is in progress (spoke with design offline).
https://github.com/AudiusProject/audius-protocol/assets/3893871/84ef795f-4557-4633-a56f-7a70b9594655
https://github.com/AudiusProject/audius-protocol/assets/3893871/247e96a8-4580-4bb2-ab6f-0419930085e5
=> Hide ToS when purchase is in progress

packages/common/src/hooks/purchaseContent/useChallengeCooldownSchedule.ts
The previous implementation had a bug where it was grouping challenges completed _yesterday_ and _today_ together erroneously. This PR fixes the problem by clamping the date used to compare against the challenge completion date to the _end of_ the day.
Local web stage. Logged out completion dates of challenges and confirmed that the claimable dates are as expected.
after:
before:
=> Fix cooldown schedule

packages/common/src/models/Analytics.ts, packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx, packages/web/src/components/premium-content-purchase-modal/components/PayToUnlockInfo.tsx
Adds an event for when the user clicks/presses the TOS link in the purchase flow.
fixes PAY-2013
Tested locally in Chrome and simulator against staging
=> [PAY-2013] Send event when purchase TOS clicked

packages/common/src/models/Analytics.ts, packages/mobile/src/screens/audio-screen/ChallengeRewards.tsx, packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
We already have a lot of eventing around rewards. This adds one more for the opening of the modal.
Fixes PAY-2089
Tested locally in Chrome/simulator against staging
=> [PAY-2089] Add analytics events for users opening rewards claim modal

packages/web/src/common/store/pages/audio-rewards/sagas.ts
Attempting to claim a challenge with amount 0 will result in an error (invalid amount) - filter out these challenges on client side so we never claim them. Theoretically we should never have 0-amount challenges at all but this is a safeguard.
https://github.com/AudiusProject/audius-protocol/assets/3893871/1ede64ee-6671-4d34-bff9-eb031807b2fa
Logging the 0-amount challenges:
=> Filter out 0-amount challenges

packages/harmony/src/assets/styles/border-radius.css, packages/web/src/pages/sign-in-page/SignInPage.tsx, packages/web/src/pages/sign-in-page/SignInPageDesktop.tsx, packages/web/src/pages/sign-in-page/SignInPageMobile.module.css, packages/web/src/pages/sign-in-page/SignInPageMobile.tsx
- Adds UI for mobile web sign in page
- Uses `useMedia` hook to switch between the two depending on screen size
- The navbar does not currently switch out depending on screen size, so we'll get the mobile UI in web nav
- Link styling and functionality (Awaiting harmony Link component)
- Putting the mobile UI in an overlay drawer
- Spacing hacked for visibility above mobile navbar, but this will change when the whole thing is an overlay
=> [C-3261] Add mobile web signin UI

packages/discovery-provider/src/tasks/index_user_bank.py
Previously we were only disbursing $AUDIO matching challenges in stage and dev envs. This PR removes this check to disburse them in prod env too.
Needs to be tested on prod, but the disbursements work fine on stage!
=> [PAY-1987] Remove check for audio matching challenges in non-prod envs

.circleci/scripts/circleci-startup-script.sh
We want arm machines to also be available as self-hosted runners to make pushing arm64 docker images fast and efficient.
Will stand up arm runners once committed.
=> [PROTO-1373] Introduce arm machine type to ci runner bootstrap script

mediorum/server/server.go, packages/discovery-provider/src/api/v1/root_path.py
- Adds missing `#` to protocol dashboard url
- Uses temporary redirect (mediorum already used permanent in the past for /health_check, so it's too late for browsers that already have that cached)
- Other environment issues aren't working on stage even though they work locally. Those will be fixed separately
=> Redirect root with hash routing

packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
No longer showing for premium
Makes logic consistent with https://github.com/AudiusProject/audius-protocol/blob/3acd0665a7fa4d7a621863ee1cf0dbd601f3646c/packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx#L191
=> [PAY-2088] Hide play counts on premium on mobile

packages/common/src/services/Jupiter.ts, packages/common/src/services/audius-backend/solana.ts, packages/common/src/store/buy-crypto/sagas.ts
Adds three retries to Buy Crypto via SOL flow before attempting to salvage what it can for USDC.
Also adjusts the flow to not take existing SOL into account before purchasing SOL
Tested similarly to #6496
=> Add retries to Buy Crypto via SOL flow

packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx, packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx
Hide the advanced manual transfer UI when the purchase is in progress or complete.
Local web stage + ios stage
=> [PAY-2100] Hide manual transfer UI while purchase in progress

protocol-dashboard/src/components/IndividualServiceApiCallsChart/IndividualServiceApiCallsChart.tsx, protocol-dashboard/src/components/IndividualServiceApiCallsChart/index.tsx, protocol-dashboard/src/components/IndividualServiceUniqueUsersChart/IndividualServiceUniqueUsersChart.tsx, protocol-dashboard/src/components/IndividualServiceUniqueUsersChart/index.tsx, protocol-dashboard/src/components/NodeOverview/NodeOverview.module.css, protocol-dashboard/src/components/NodeOverview/NodeOverview.tsx, protocol-dashboard/src/containers/Node/Node.module.css, protocol-dashboard/src/containers/Node/Node.tsx, protocol-dashboard/src/store/cache/analytics/hooks.ts, protocol-dashboard/src/store/cache/analytics/slice.ts
Move https://github.com/AudiusProject/protocol-dashboard/pull/123 to the monorepo.
I didn't rename all src files like in the original PR since all the dashboard source code is already under protocol-dashboard/ in the monorepo.
npm run start:stage
=> Add per service charts to protocol-dashboard

packages/mobile/src/components/lineup-tile/LineupTileAccessStatus.tsx, packages/web/src/components/track/desktop/BottomRow.tsx, packages/web/src/components/track/desktop/ConnectedTrackTile.tsx, packages/web/src/components/track/desktop/TrackTile.tsx, packages/web/src/components/track/mobile/TrackTile.tsx, packages/web/src/components/track/types.ts
Open (non-premium/usdc) locked content modal on track tile locked pill click across web, native mobiel, mobile web.
local web, mobile web, and native mobile dapps vs stage
https://github.com/AudiusProject/audius-protocol/assets/9600175/8581ca06-a064-4205-b1ae-3318e41d2013
https://github.com/AudiusProject/audius-protocol/assets/9600175/219ba0ec-3a3c-48f9-9d13-1da930ec910a
https://github.com/AudiusProject/audius-protocol/assets/9600175/809ad334-c512-459b-a202-343dd6b4ab37
=> [PAY-2102] Fix locked content modal not opening regression bug

protocol-dashboard/src/components/NodeOverview/NodeOverview.tsx, protocol-dashboard/src/containers/Node/Node.tsx
Fixes Content Node style in protocol dashboard services view not showing full width when it doesn't have charts. Also lints to unblock the failing CI init step, which is a prerequisite to deploying.
=> Hotfix Content Node view width and lint for CI

package-lock.json, package.json, packages/eslint-config-audius/package.json, packages/eslint-config-audius/src/index.js, packages/harmony/.eslintrc.js, packages/harmony/.storybook/preview-body.html, packages/harmony/src/components/button/BaseButton/BaseButton.module.css, packages/harmony/src/components/button/BaseButton/BaseButton.tsx, packages/harmony/src/components/button/Button/Button.mdx, packages/harmony/src/components/button/Button/Button.module.css, packages/harmony/src/components/button/Button/Button.stories.tsx, packages/harmony/src/components/button/Button/Button.tsx, packages/harmony/src/components/button/types.ts, packages/harmony/src/components/layout/Box/Box.tsx, packages/harmony/src/components/layout/Box/types.ts, packages/harmony/tsconfig.json
Updates Harmony Button docs up to figma specs
- Also updates eslint and typescript config for css-prop use
=> [C-3286] Finalize harmony button docs

packages/mobile/src/components/stripe-onramp-drawer/StripeOnrampEmbed.tsx
Fixes issue where user is unable to confirm with their bank because it requires scrolling on the page to confirm
=> Enable scroll on StripeOnrampEmbed

packages/mobile/src/components/core/AddressTile.tsx, packages/mobile/src/components/usdc-manual-transfer-drawer/USDCManualTransferDrawer.tsx
`TouchableOpacity` from RNGH doesn't work on android, need to use the react-native one instead.
Also:
- increased hitslop
- fixed alignment of address text on android
- Added tracking when copy button is pressed
https://github.com/AudiusProject/audius-protocol/assets/3893871/97f2be15-6900-4716-86ab-52e589289604
=> Fix manual transfer on android

packages/mobile/src/components/core/AddressTile.tsx, packages/mobile/src/components/lineup/EndOfLineupNotice.tsx, packages/mobile/src/components/lineup/Lineup.tsx, packages/mobile/src/components/lineup/types.ts, packages/mobile/src/components/usdc-manual-transfer-drawer/USDCManualTransferDrawer.tsx, packages/mobile/src/screens/explore-screen/tabs/ForYouTab/PremiumTracksScreen.tsx, packages/mobile/src/screens/feed-screen/FeedScreen.tsx
Adds "end-of-lineup" notice for premium tracks lineup, to help make it clear to folks they are at the end of the list. Also adds a cta to check in later as more premium tracks will be added
=> Add end-of-lineup notice to premium tracks lineup

packages/common/src/hooks/purchaseContent/usePurchaseContentErrorMessage.ts, packages/common/src/store/buy-crypto/sagas.ts, packages/common/src/store/buy-crypto/slice.ts, packages/common/src/store/buy-crypto/types.ts, packages/common/src/store/buy-usdc/sagas.ts, packages/common/src/store/buy-usdc/slice.ts, packages/common/src/store/buy-usdc/types.ts
Show a specific error message when the user attempts to purchase from a country stripe doesn't support.
Local web prod, tested with `BUY_USDC_VIA_SOL` both on and off.
haven't been able to get ios app running, but should share same code path in common.
https://github.com/AudiusProject/audius-protocol/assets/3893871/d29b515a-38b6-410d-8042-cc23fb43e5b8
=> [PAY-2114] Show country is not supported message for purchases

packages/mobile/src/app/Drawers.tsx, packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
We set a higher zIndex on the Stripe drawer, but on Android, this is only working for the first purchase. The second time, it seems to fall back on sibling order. Rather than make _all_ common drawers render after _all_ native drawers to get this to work, we made the tradeoff of not unmounting these drawers to reduce the risk of introducing other zIndex bugs in fixing this one.
See: PAY-2119
Android sim.
Repro:
- Open purchase drawer and subsequent Stripe drawer
- Close both
- Open purchase drawer and subsequent Stripe drawer
=> PAY-2119: Fix Stripe Drawer zIndex on Android

packages/common/src/store/purchase-content/sagas.ts, packages/common/src/store/purchase-content/utils.test.ts, packages/common/src/store/purchase-content/utils.ts, packages/mobile/src/components/premium-track-purchase-drawer/hooks/usePurchaseSummaryValues.ts, packages/web/src/components/premium-content-purchase-modal/hooks/usePurchaseSummaryValues.ts
Our payment onramp has a minimum purchase amount. There are situation where users end up with a small balance that would make them unable to complete checkout. In those situations, we will not attempt to use the balance.
This does introduce some corner cases where you have a larger balance and the math of (price+extraAmount-balance) works out to less than the minimum and forces you to pay the full price or bump up your pay extra amount. But those should be more rare than the current issue and we can land changes later to make it a little more sophisticated.
Fixes PAY-2112
Tested locally in browser and iOS simulator against staging
**Note** I temporarily baseed this on #6549 to get Jest working and ensure my tests pass. But I don't want to necessarily block this PR on that one, so the …
=> [PAY-2112] Don't attempt to use balance if total amount due drops below minimum

.circleci/.hooks/pre-push.json, .circleci/config.yml, .circleci/src/@continue_config.yml, .circleci/src/commands/@common-commands.yml, .circleci/src/jobs/@common-jobs.yml, .circleci/src/jobs/@mobile-jobs.yml, .circleci/src/jobs/@web-jobs.yml, .circleci/src/workflows/common.yml, .gitignore, package-lock.json, package.json, packages/common/babel.config.js, packages/common/package.json, packages/common/src/store/confirmer/store.test.ts, packages/common/src/store/playlist-library/helpers.test.js, packages/common/src/utils/aaoErrorCodes.test.ts, packages/common/src/utils/hashIds.test.js
Adds common tests
Adds better common ci
Adds circleci-config pre-push hooks
=> [C-3308] Enable common tests

packages/mobile/src/app/Drawers.tsx
The USDC manual transfer drawer needs to be above the purchase drawer
=> Fix USDC Manual Transfer Drawer layering

packages/web/src/common/store/pages/collection/sagas.js
Updated track count check from `track_count` field to `playlist_contents.track_ids.length`
Manually tested, playlists load tracks now
=> [C-3307] Fix track count check for collections sagas

packages/common/src/models/Analytics.ts, packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.tsx, packages/web/src/pages/dashboard-page/components/USDCCard.tsx, packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
I noticed while writing some dashboards that some of the withdrawal events are double-dividing the current balance, which is less than helpful 😅 
This should get it in line for now, and I will think about how to structure this going forward to make sure it's easy to provide the right units for cases like this.
=> Fix balance formatting for usdc withdrawal events

packages/web/src/services/audio-player/AudioPlayer.ts
Was noticing a lot of these error messages that we believe was causing occasional crashes (not confirmed).
For posterity:
The error:
Logging the error:
```
this.audio.addEventListener('error', (e) => {
console.debug(e?.target?.error)
})
```
Local web stage (on brave)
=> Fix AudioPlayer missing src bug

packages/web/src/common/store/lineup/sagas.js, packages/web/src/common/store/queue/sagas.ts, packages/web/src/common/utils/isPreview.ts
Previously, previews were skipped in lineups. This PR makes it so that previews can be played and auto-played in a lineup.
Dragon: unsure about usage of generator for `isPreview` and using it with/without `yield`.
Test cases:
3 cases: locked premium track, unlocked premium track, normal track
Click play on a track from each case
Click next/previous through each of the three cases
Let autoplay go to the next track for each of the cases
Test playing through lineup on user's own tracks and confirmed they play the full version and not the preview.
Test explicitly clicking the preview button on a user's own tracks -> play preview and not full track
Test playing tracks while not signed -> play only previews.
Local web stage:
https://github.com/AudiusProject/audius-protocol/assets/3893871/5f1aa4d …
=> [PAY-2121] Don't skip previews in lineups

packages/harmony/src/components/layout/Flex/index.ts, packages/web/src/pages/sign-in-page/SignInPage.module.css, packages/web/src/pages/sign-in-page/SignInPageDesktop.tsx, packages/web/src/pages/sign-on/components/desktop/LeftContentContainer.module.css, packages/web/src/pages/sign-on/components/desktop/LeftContentContainer.tsx, packages/web/src/pages/sign-up-page/pages/CreatePasswordPage.tsx, packages/web/src/pages/sign-up-page/pages/SignUpPage.module.css, packages/web/src/pages/sign-up-page/pages/SignUpPage.tsx, packages/web/src/pages/sign-up-page/styles/CreatePasswordPage.module.css
- Put password and email pages into PageWithAudiusValues
- Create shared LeftContentContainer for the left side of the pages w/ Audius Values
- Add back button to PW page
=> [Sign up] Put password and email pages into PageWithAudiusValues, create generic LeftContentContainer, add back button

packages/mobile/src/app/Drawers.tsx, packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx, packages/mobile/src/components/lineup-tile/LineupTileAccessStatus.tsx, packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx, packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx, packages/mobile/src/components/premium-track-purchase-drawer/PurchaseSuccess.tsx, packages/mobile/src/store/drawers/slice.ts
This updates the `PremiumTrackPurchaseDrawer` to use the CommonDrawer/Modal flow instead of the mobile-only native drawer flow. This makes tracking of events for close/open consistent on all platforms and ensures we are using the same modal management logic driven from the common slice.
Note: We can and probably should rename this drawer to `PurchasePremiumContentDrawer` so that it's consistent with the web version and common modal naming.
fixes PAY-2107
* Changed initialization in the `Drawers` component to use `<Modal />` instead of `<Drawer />` and moved the commented-out code into the correct section. This will likely get removed later when all three modals are in the same section.
* Removed manual event tracking for modal open/close
* Updated all invocations of the modal to use …
=> [PAY-2107] Switch purchase drawer to use common modal slice on mobile

packages/commands/test/common-setup.bash, packages/discovery-provider/plugins/pedalboard/apps/relay/package.json
The extraneous package-lock.json in relay was removed in #6567 . This caused:
```
Cannot find module 'on-exit-leak-free'
```
Even though `pino` declares `on-exit-leak-free` as a dependency, it was nowhere to be found in the root package-lock.json. The only way I was able to get it to properly install is by reinstalling pino (with a minor version upgrade). 
Relay runs properly now
=> Reinstall pino to fix missing on-exit-leak-free in @pedalboard/relay

packages/common/src/utils/challenges.ts, packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
Fixes a bug on mobile where claiming an $AUDIO matching challenge would have attempted to claim challenges not yet past the cooldown period.
Local ios dev, confirmed that only challenges past cooldown are claimed.
=> Only claim challenges past cooldown on mobile

.circleci/scripts/circleci-startup-script.sh, .circleci/scripts/periodic-cleanup
Because the push image workflow involves tagging images, the local docker registry eventually fills up even when `docker system prune` is run. This adds a daily check which runs `docker system prune -a` to mitigate this issue.
Stood up test ci host and stopped/restarted to ensure proper functionality of startup script.
=> [PROTO-1410] Self hosted ci: make startup script idempotent, perform full docker prune.

packages/web/src/common/store/pages/signon/sagas.js, packages/web/src/common/store/social/users/sagas.ts
Before:
Default follow accounts would not render as "followed" in your followed list:
Cause:
The default follow users were not cached and thus we could not optimistically update their `does_current_user_follow` value. The `does_current_user_follow` value from the API would return `false` until the follow was indexed.
After:
This is fixed
Another note:
We finish the sign up loading screen and allow the user to go the feed *before we've confirmed the artist follows*. I think this is by design to prevent issues where sign up hangs too long --- and normally the follows do confirm before the user hits the feed anyway. But this is indeed a race condition we've created, and will lead to more QA tickets in the future of follows not being complete upon new user sign up. 
_Please describe the tests …
=> Fix Audius appearing to be not followed after signup QA-678

packages/discovery-provider/integration_tests/queries/test_undisbursed_challenges.py, packages/discovery-provider/src/api/v1/challenges.py, packages/discovery-provider/src/api/v1/models/challenges.py, packages/discovery-provider/src/queries/get_undisbursed_challenges.py
Add `cooldown_days` to `challenges/undisbursed` and `challenges/<id>/info` endpoints.
Local dev stack
=> Add cooldown_days to challenges api response

packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/styles.module.css
I don't understand how this fixes it.
The elements were all taking 0 height, possibly because the modal had to open first? Not sure how % changes anything. Some CSS expert please explain.
=> Fix rewards layout issues after vite

packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
I had [added a `disbursed_amount` field to the challenge api response](https://github.com/AudiusProject/audius-protocol/pull/6398/files) but had forgotten to use it in this place on client.
=> Fix total audio claimed amount for aggregate challenges

packages/harmony/package.json
Fixes issue where file-loader is missing when trying to run storybook
=> Add file-loader to fix harmony storybook

packages/discovery-provider/src/premium_content/signature.py, packages/discovery-provider/src/tasks/entity_manager/entities/track.py, packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.tsx, packages/web/src/pages/upload-page/fields/RemixSettingsField/RemixSettingsMenuFields.tsx
Only allow premium tracks to which user has access to be set as remix parents in DN indexing.
Also fix bug where hide remixes switch was not modifiable on web.
local web dapp vs stage.
tried uploading bad remix, where remix parent was a track that i dont have access to. it failed with
`"level": "ERROR", "msg": "failed to process transaction error User 14972 does not have access to premium track 2094004801", "timestamp": "2023-11-08 18:36:00,353"`
then uploaded good remix, and it went through
=> [PAY-2096] Validate remixability of premium content in DN indexing

packages/common/src/hooks/useAccountHasClaimableRewards.ts
Previously, if the $AUDIO matching challenges were the only challenges with claimable amounts, the "Claim rewards" pill would not appear.
=> Add  matching challenges to claimable challenges

packages/harmony/src/storybook/components/RelatedComponents.tsx, packages/harmony/src/storybook/components/RelatedFoundations.tsx
Links were getting double prefixed, breaking the navigation
local harmony
=> [C-3338] Fix harmony internal links

packages/web/vite.config.ts
We were seeing `VITE_PUBLIC_URL` undefined on the landing page. This is mainly used for the frontend demo site, because the whole app is nested at a path for each CI branch. But in the case were it wasn't set, errors were being thrown. This pr defaults `VITE_PUBLIC_URL` to empty string, which is the same behavior we had before with react `PUBLIC_URL`
Testes that routing works properly, including landing page. Will confirm the frontend demo works once it builds!
=> [INF-542] Fix vite_public_url

packages/harmony/src/foundations/theme/ThemeProvider.tsx
Fixes issue where css-module classNames at same level of specificity as emotion classNames would always be overridden. This fix ensures emotion styles get "prepended" to the "body" tag, ensuring css-module classnames always come after, resulting in css-modules always overriding.
After applying this code, i created a css module file like this:
```css
.root {
background-color: green;
}
```
and then used in on the harmony button like so: 
```tsx
import {Button} from '@audius/harmony`
import styles from './Test.module.css'
...
<Button className={styles.root}>Green!</Button>
```
=> Fix emotion and css-modules specificity

packages/mobile/src/screens/audio-screen/Panel.tsx
Unclear how this happened but this style was missing from the pill so it didn't have the purple background.
=> Fix wrong bg color in mobile ready to claim pill

packages/harmony/src/components/button/Button/Button.mdx, packages/harmony/src/components/button/Button/Button.stories.tsx, packages/harmony/src/components/button/Button/Button.tsx, packages/harmony/src/storybook/components/ComponentRule.tsx
Made fixes from harmony docs discussion:
- Remove text descriptions above stories
- Loading state story should just be the button in loading state
- Remove css descriptions from ‘color prop applied' stories
- Fix do/don’t height in the last pair
- Tertiary button unclear
=> [C-3341] Clean up Harmony Button docs

packages/harmony/src/storybook/components/ComponentRule.tsx
- Un-capitalize title
- Update spacing between title and description, description and example
Didn't find a good way to make the gap between description and example variable depending on length of text, so just hedged and took the gap down a bit.
storybook
=> [C-3340] Fix do's and don'ts styling

.circleci/src/commands/@mobile-commands.yml, .circleci/src/commands/@web-commands.yml, .circleci/src/jobs/@web-jobs.yml, .circleci/src/workflows/mobile.yml, .circleci/src/workflows/web.yml
Curious for feedback
* Web & desktop won't push if you're trying to push a version behind. In the case where this is necessary we can always comment out the check and push it. Blocking mobile upload is a little trickier because it requires getting the released version and also dealing with codepush considerations
* Add slack notifs after deploys to web, mobile, and desktop. Borrowed from daily deploy bot code @theoilie wrote
Tested by running commands in an ssh'd instance on circleci. Probably not perfect, but will iterate as it gets used.
=> Gate client release version and add slack notifs

packages/harmony/.storybook/docs.tsx, packages/harmony/.storybook/manager-head.html, packages/harmony/.storybook/preview.ts, packages/harmony/src/components/avatar/Avatar.mdx, packages/harmony/src/components/avatar/Avatar.tsx, packages/harmony/src/storybook/components/CardLink.tsx, packages/harmony/src/storybook/components/ComponentRules.tsx, packages/harmony/src/storybook/components/Subtitle.tsx, packages/harmony/src/storybook/theme/colors.css
Improves theme switcher by consolidating `storybook-dark-mode` and `@storybook/addon-themes` into a single user interface (uses addon-themes), but under the hood uses both. Now when user switches to dark or matrix mode, the entire app changes themes appropriately!
Also fixes underlying issue with dark-mode and addon-themes plugins where they weren't consistently updating html/body tags, which are needed for css-variables to change to light/dark mode. We are using our own version now with a div wrapper + data-theme attribute. Kinda annoying but nice and consistent now
https://github.com/AudiusProject/audius-protocol/assets/8230000/bf5220dd-5554-4027-bcab-f223a32d5cbe
=> [C-3343] Simplify and fix theme switcher

packages/discovery-provider/src/tasks/entity_manager/entity_manager.py, packages/discovery-provider/src/tasks/entity_manager/utils.py
Before:
EM developer app transactions were being logged incorrectly - see the dashboard below and Sebastian's comment:
```In Top Developer Apps (Writes) AudiusCast is the only app doing writes. The userHandle column is the user that the write is being performed for (this should maybe be changed to the user who owns the app), but the _signer column has a bunch of different signers. Why would there be 11 different signers for a single app?```
https://app.axiom.co/audius-Lu52/dashboards/TsHgf8G40aTneXKE7w/edit/8566e9dd-b1a3-4009-ae98-00a7314a419f
Problem:
Our logging relies on `validate_signer` to add the proper developer app context for each EM event. But `validate_signer` isn't called in all processing flows such as create/delete grant, and we weren't clearing the developer app context …
=> Fix developer app metrics C-3248

packages/web/src/components/stepped-progress/SteppedProgress.module.css, packages/web/src/components/stepped-progress/SteppedProgress.tsx, packages/web/src/pages/sign-up-page/SignUpRootPage.tsx, packages/web/src/pages/sign-up-page/components/ProgressHeader.module.css, packages/web/src/pages/sign-up-page/components/ProgressHeader.tsx, packages/web/src/pages/sign-up-page/pages/PickHandlePage.module.css, packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx
Add the progress header used on the final 4 sign up pages (includes underline animation)
=> Add sign up white screen progress header C-3320

packages/harmony/src/storybook/components/TypographyPanel.tsx
Fixes odd issue on typography page where some of the text elements render h3, which then gets added into TOC links. Fix was to update all underlying tags to 'p' for that doc
=> [C-3345] Fix TOC links

packages/harmony/src/components/input/TextInput/TextInput.mdx, packages/harmony/src/components/input/TextInput/TextInput.stories.tsx, packages/harmony/src/components/input/TextInput/TextInput.tsx, packages/harmony/src/storybook/components/ComponentRule.tsx
Ensures text-input doesn't need explicit role by adding a storybook test using `getByRole('textbox'..)`
Updates some text-input docs styles
=> [C-3265] Ensure text-input doesn't need explicit role

packages/harmony/README.md
Add README with basic install. setup, and usage sections
Looks good in VS Code markdown preview
=> [C-3274, C-3348] Add README to Harmony

packages/harmony/src/components/text/Text/Text.tsx
Fixes issue where heading text clips at the bottom, since the linear gradient color is a background-image with backgroundClip
=> [C-3244] Fix heading text clipping

packages/web/vite.config.ts
Related to https://github.com/AudiusProject/audius-protocol/pull/6630
Using empty string as the vite `base` works in dev mode but not for prod builds. This updates the vite `base` to `/` when public url is falsey (including empty string)
Tested that TOS and Privacy policy links work properly from landing page in both dev mode and on prod builds
Going to cherry pick once merged
=> [INF-546] Ensure that vite base is set properly in prod builds

packages/harmony/src/foundations/shadows/Shadow.stories.mdx, packages/harmony/src/foundations/shadows/shadows.css, packages/harmony/src/foundations/shadows/shadows.ts, packages/web/src/pages/sign-up-page/SignUpRootPage.module.css, packages/web/src/pages/sign-up-page/SignUpRootPage.tsx, packages/web/src/pages/sign-up-page/components/ContinueFooter.module.css, packages/web/src/pages/sign-up-page/components/ContinueFooter.tsx, packages/web/src/pages/sign-up-page/pages/PickHandlePage.module.css, packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx
- Add mid-inverted shadow to Harmony
- Create footer component for white sign up screens on desktop
=> [Sign up Redesign] Sign up white screens footer (web); add shadow mid inver to Harmony C-3358 C-3359ted

packages/harmony/src/components/text/Text/Text.tsx
Fixes incorrect font-size and line-height for heading xl
Confirmed in figma
=> Fix typography header xl font-size and line-height

packages/common/src/hooks/useAccountHasClaimableRewards.ts
Not sure how typescript didn't catch this, but this should fix for now.
I couldn't repro the bug locally but rewards/nav functions normally for me with this fix.
=> Fix broken useAccountHasClaimableRewards

packages/harmony/src/components/avatar/Avatar.tsx, packages/harmony/src/components/avatar/types.ts, packages/harmony/src/components/text/Text/Text.tsx, packages/harmony/src/components/text/Text/types.ts, packages/harmony/src/foundations/spacing/spacing.ts, packages/harmony/src/foundations/theme/index.ts, packages/harmony/src/foundations/typography/Typography.mdx
Adds a few harmony improvements:
- Adds text-shadow option to Text
- Allows passing css prop into Avatar
- Exports `useTheme` from harmony
- Adds '2xs' spacing option since im seeing some cases where we have gap: 2px
> We likely want to improve text-shadows value to work with existing shadows foundations, but it appears none of those are compatible with text-shadow
=> Add text-shadow, fix avatar className, add 2xs spacing

packages/probers/cypress/config/dev.json, packages/probers/cypress/e2e/uploadTrack.cy.ts
Add cypress test for premium content uploads.
Also re-enable stems, but in a separate tests since download options are probably going to want a few different tests in the future.
```
cd packages/probers npm run cypress:open
```
=> Add pay-gated upload test and re-enable stems test

mediorum/server/server.go, monitoring/uptime/uptime.go
Tiny hotfix for `/up` not loading on mobile for Content Nodes because there are 2 golang echo servers which both set Content-Encoding to gzip (mediorum's echo server reverse proxies to the uptime container's echo server, which serves the static assets). Desktop is able to handle this, but mobile browsers don't dedupe and instead twice, which makes the website look like alien text.
Tested on desktop and mobile for Discovery and Content. Mediorum and Discovery's nginx both set gzip already, so it makes sense to not have it in the uptime container. Now, they both have a single Content-Encoding header set to gzip.
=> Hotfix double gzip on mobile for Content Nodes

packages/harmony/src/storybook/components/SidebarItem.tsx
Fixes issue where updated flex/box components use emotion now, which is not available in storybook manager context leading to runtime error (it worked before cause the css-variables were available).
The fix is to just not use box or flex to build this component
=> Fix harmony docs sidebar-item

packages/harmony/src/components/input/SelectablePill/SelectablePill.mdx, packages/harmony/src/components/input/SelectablePill/SelectablePill.stories.tsx, packages/harmony/src/components/input/SelectablePill/SelectablePill.tsx, packages/harmony/src/components/input/SelectablePill/types.ts, packages/web/src/pages/saved-page/components/desktop/LibraryCategorySelectionMenu.tsx
Adds checkbox/radio type options to SelectablePill, which will change underlying implementation with label + input + all input props.
passing type='button' | 'submit' | 'reset' will render it as a button like existing behavior
=> [C-3369] Add checkbox/radio types to SelectablePill

packages/common/package.json, packages/common/rollup.config.js, packages/common/tsconfig.json, packages/harmony/package.json, packages/harmony/rollup.config.mjs, packages/harmony/src/components/avatar/Avatar.stories.tsx, packages/harmony/src/components/icon/Icon.tsx, packages/harmony/tsconfig.json
Fixes harmony types due to internal absolute imports. The fix, like we did with common, is to add the transform-paths typescript plugin which rewrites absolute imports as relative imports when building
No typescript issues + we get proper type checking in web
=> [C-3370]  Fix harmony types

mediorum/server/server.go, monitoring/uptime/Dockerfile, monitoring/uptime/node-ui/.eslintrc.cjs, monitoring/uptime/node-ui/README.md, monitoring/uptime/node-ui/package-lock.json, monitoring/uptime/node-ui/package.json, monitoring/uptime/node-ui/src/App.tsx, monitoring/uptime/node-ui/src/AppWithProviders.tsx, monitoring/uptime/node-ui/src/hooks/useWeb3Signer.ts, monitoring/uptime/node-ui/src/main.tsx, monitoring/uptime/node-ui/src/providers/AudiusLibsProvider.tsx, monitoring/uptime/node-ui/src/providers/EnvVarsProvider.tsx, monitoring/uptime/node-ui/vite.config.ts, monitoring/uptime/uptime.go, packages/discovery-provider/nginx_conf/nginx.conf
Moves `/up` to `/d`, now with external wallets that Audius Libs can use.
https://github.com/AudiusProject/audius-protocol/assets/4657956/53944b90-3eae-4f0c-af26-165eaa28e0d9
- `npm run stage:preview` plus testing on a stage CN and DN after building linux images
- I haven't explicitly tested connecting non-Metamask wallets, but thanks to a workaround where I directly set libs to a web3 instance, I _think_ they'll work.
Note: Even though libs is now set up, it might be best to call the contracts directly instead of using it. The wagmi and viem packages (now installed as of this PR) make this doable without too much headache.
=> [PROTO-1430] Add external wallets to /d (fka /up)

packages/harmony/src/components/layout/Popup/Popup.mdx, packages/harmony/src/components/layout/Popup/Popup.module.css, packages/harmony/src/components/layout/Popup/Popup.stories.tsx, packages/harmony/src/components/layout/Popup/Popup.tsx, packages/harmony/src/components/layout/Popup/index.ts, packages/harmony/src/components/layout/Popup/types.ts, packages/harmony/src/foundations/motion/motion.ts, packages/harmony/src/foundations/theme/theme.ts, packages/harmony/src/hooks/useClickOutside.ts, packages/harmony/src/utils/getScrollParent.ts
Port Stems Popup componet to harmony.
Actual diff:
https://www.diffchecker.com/WAGLkhwA/
Fixed a couple issues:
* Popup doesn't work when portaled element is what scrolls (e.g. the document.body in the inner iframe in storybook)
* Delete deprecated position
```
npm run storybook
```
=> [C-3362] Port Popup component to Harmony

packages/web/src/services/audio-player/AudioPlayer.ts
It seems like with both these `src` removal methods together, it fixes both the `player/error` bug and the having to wait 15s bug. Not sure why but let's give this a whirl.
Dragon - I noticed once that after leaving my browser tab open for a while and then coming back and hitting play, I got `player/error` + infinite spinner on play button and track never played. Not sure if just a byproduct of some local dev thing, or a real issue, and hard to test so let's try it on staging.
Local web stage - Tried many times to repro and could not.
=> Fix 10th track has 15s wait bug

packages/common/src/store/ui/modals/parentSlice.ts, packages/common/src/store/ui/modals/types.ts, packages/harmony/src/components/button/BaseButton/BaseButton.tsx, packages/harmony/src/components/button/Button/Button.tsx, packages/web/src/components/drawer/Drawer.module.css, packages/web/src/components/welcome-modal/WelcomeModal.tsx, packages/web/src/pages/modals/Modals.tsx, packages/web/src/pages/sign-up-page/SignUpRootPage.tsx, packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
Update the state for modals and added the WelcomeModal component that is used for both desktop and mobile web. (Same content, but renders within a Modal or Drawer depending on desktop vs mobile web)
Note: Dispatching an action to open the drawer when the user continues from the artist select page. Not sure if this is the best way to handle this or if there should be a something else listening on trending or something to open the drawer. Open to suggestions here
Note 2: Tried looking into a scheduler for modals, but it looked like there would some work to handle this case, but also other cases where we do want modals that overlap so making a ticket to look into this later.
Could not accurately test by going through the sign up flow as things were not working for me locally
Tested locally …
=> [C-3353] Add WelcomeModal for the new sign up flow for both web and mobile web

packages/discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py, packages/discovery-provider/src/tasks/entity_manager/entities/user.py
Patches a vulnerability where verified can be set on user creation. Looked through other cases and couldn't find anything else. 
Modified existing integration tests.
=> Patch verified user on creation

monitoring/uptime/node-ui/package-lock.json, monitoring/uptime/node-ui/package.json, monitoring/uptime/node-ui/src/App.tsx, monitoring/uptime/node-ui/src/AppWithProviders.tsx, monitoring/uptime/node-ui/src/hooks/useWagmiConfig.tsx, monitoring/uptime/node-ui/src/hooks/useWeb3Signer.ts
Upgrades wagmi and viem to 2.0 beta (somewhat stable now that it's no longer in alpha - see [announcement](https://twitter.com/wagmi_sh/status/1707476847351468334)).
It's unfortunately still too new for the RainbowKit modal, so MetaMask is back to being a boring old button. We weren't using other wallet connectors in that modal anyway, and it'll be easy to add back once RainbowKit updates.
Note to use the v2 (beta) docs for wagmi: https://beta.wagmi.sh/react/api/hooks
=> Upgrade wagmi to v2 (in /d) 

packages/common/src/utils/formatUtil.test.ts, packages/common/src/utils/wallet.test.ts, packages/fixed-decimal/package.json, packages/fixed-decimal/src/FixedDecimal.ts, packages/fixed-decimal/src/currencies.test.ts, packages/fixed-decimal/src/currencies.ts, packages/fixed-decimal/src/index.ts, packages/fixed-decimal/src/utilityTypes.ts, packages/fixed-decimal/tsconfig.base.json, packages/fixed-decimal/tsconfig.build.cjs.json, packages/fixed-decimal/tsconfig.build.esm.json, packages/fixed-decimal/tsconfig.build.json, packages/fixed-decimal/tsconfig.json
Followup on feedback from https://github.com/AudiusProject/audius-protocol/pull/6662
- Adds types to each `FixedDecimal` constructor helper to brand the `bigint`
- TypeError on using the wrong type in a `FixedDecimal` constructor (eg. using `AudioWei` to initialize a `FixedDecimal<wAudioWei>` or a `BNAudio` to initialize a `FixedDecimal<any, BNWei>`)
- Rename `AudioTokens` etc to `AudioWei` etc to be more clear about the value represented, and updated comments
- Add tsconfigs for linting vs building (linting includes test files, building does not)
Adds tests for using correct branding
=> [PAY-2168] Add better typechecking for FixedDecimal

packages/web/src/components/banner/Web3ErrorBanner.tsx, packages/web/src/pages/sign-on/SignOnProvider.tsx
URL should be
https://help.audius.co/help/Configuring-MetaMask-For-Use-With-Audius-2d446
=> Fix metamask help url

packages/harmony/src/icons/UtilityIcons.stories.mdx
Per the all-hands demo, we should showcase the preset icon sizes
=> Tweak Harmony Icon Docs

packages/fixed-decimal/package.json, packages/fixed-decimal/src/FixedDecimal.test.ts, packages/fixed-decimal/src/FixedDecimal.ts, packages/mobile/metro.config.js, packages/mobile/package.json, packages/mobile/src/components/usdc-balance-pill/UsdcBalancePill.tsx
Updates the `@audius/fixed-decimal` package to run on React Native, and updates the `audius-mobile-client` to know how to link it. Also updates `FixedDecimal` to work with React Native since React Native won't add decimals to `BigInt` when doing `toLocaleString()` (which is annoying but understandable).
EDIT:
Found a bug - Tracking down why this doesn't work (should be $0.04):
Added a usage to mobile. Ran tests.
=> Support FixedDecimal on mobile

packages/libs/rollup.config.ts
The version of `readable-stream` used in libs has circular dependencies that break when vite uses it. Externalize `readable-stream` fixes this
Tested electron app locally
=> Fix electron w/ vite

packages/mobile/src/components/core/AddressTile.tsx, packages/mobile/src/components/usdc-manual-transfer-drawer/USDCManualTransferDrawer.tsx, packages/mobile/src/harmony-native/foundations/typography/Text.tsx
Bring mobile crypto transfer drawer and address tile up to spec
Use new harmony-native <Text> component to get there, which required a tiny change to get Avenir
=> [PAY-2191] Bring crypto transfer drawer and address tile up to spec

packages/common/src/hooks/usePurchaseMethod.ts, packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx, packages/mobile/src/components/premium-track-purchase-drawer/hooks/usePurchaseContentFormState.ts, packages/mobile/src/components/usdc-balance-pill/USDCBalancePill.tsx, packages/mobile/src/components/usdc-manual-transfer-drawer/USDCManualTransferDrawer.tsx, packages/mobile/src/screens/pay-and-earn-screen/USDCCard.tsx, packages/web/src/components/add-funds/AddFunds.tsx, packages/web/src/components/address-tile/AddressTile.tsx, packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx, packages/web/src/components/premium-content-purchase-modal/hooks/usePurchaseContentFormState.ts, packages/web/src/components/usdc-balance-pill/USDCBalancePill.tsx, packages/web/src/components/usdc-manual-transfer/USDCManualTransfer.tsx, packages/web/src/pages/dashboard-page/DashboardPage.tsx, packages/web/src/pages/pay-and-earn-page/desktop/PayAndEarnPage.tsx, packages/web/src/pages/pay-and-earn-page/mobile/PayAndEarnPage.tsx
- Only manual transfer modal/drawer components will poll for USDC balance now.
- use `toLocaleString` for balance UI formatting instead of `toFixed`
=> [PAY-2192] Dedupe USDC balance polling and use FixedDecimal formatting

packages/web/src/app/web-player/WebPlayer.jsx, packages/web/src/components/usdc-balance-fetcher/USDCBalanceFetcher.tsx
Fetches USDC balance on app load
Mobile doesn't have this issue as we're already loading the balance elsewhere (probably from nav)
- confirmed purchase modal now defaults to existing balance option
- confirmed non-signed-in user doesn't experience any errors
=> [PAY-2183] Fetch USDC balance on web app load

packages/web/src/components/add-funds/AddFunds.tsx, packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.module.css, packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx, packages/web/src/components/summary-table/SummaryTable.module.css, packages/web/src/components/summary-table/SummaryTable.tsx
Small UI fix for mobile web purchase flow
Don't think the `rowClassName` and `rowValueClassName` props are needed anymore.
Before:
After:
Non-mobile web still works:
=> Fix mobile web purchase drawer UI

packages/web/src/common/store/pages/signon/actions.ts, packages/web/src/common/store/pages/signon/reducer.js, packages/web/src/common/store/pages/signon/selectors.ts, packages/web/src/common/store/pages/signon/types.ts, packages/web/src/pages/sign-up-page/SignUpPage.tsx, packages/web/src/pages/sign-up-page/components/SocialMediaLoginOptions.tsx, packages/web/src/pages/sign-up-page/pages/CreateEmailPage/CreateEmailPage.tsx, packages/web/src/pages/sign-up-page/pages/CreateEmailPage/CreateEmailPageDesktop.tsx, packages/web/src/pages/sign-up-page/pages/CreateEmailPage/CreateEmailPageMobile.tsx, packages/web/src/pages/sign-up-page/pages/CreatePasswordPage.tsx
-Go to combined email + pw page when socials are connected on the first page of sign up flow
-> Logic so that you see this page again if you hit "back" on the subsequent pages
-Password page clean up
=> Email + pw page for social sign up flow, cleanup,  C-3395

packages/mobile/tsconfig.json
Add `workers` to the tsconfig paths in mobile. Not sure why this was working before, or why it doesn't fail locally
=> Fix mobile init

packages/discovery-provider/plugins/verified-uploads/src/handlers/users.js
Previously, retries were meant to allow some time for identity to catch up https://github.com/AudiusProject/audius-protocol/pull/6306/files.
But we went from a few seconds to practically infinite given the exponential backoff default. Somehow a few from last month managed to finish retrying (not sure how). Some were before a verification patch but some are users in a weird state without social handles (possibly a mobile sign up verify bug) but they have mostly gone unnoticed infinitely retrying. 
https://github.com/tim-kos/node-retry#retrytimeoutsoptions
Also, setTimeout is not necessary since retry takes care of that already as well.
Ran on stage along with some logs to …
=> Default retry for verified user bot

packages/common/src/context/appContext.ts, packages/common/src/hooks/helpers.ts, packages/common/src/hooks/purchaseContent/usePayExtraPresets.ts, packages/common/src/hooks/purchaseContent/usePurchaseContentErrorMessage.ts, packages/common/src/hooks/purchaseContent/useUSDCPurchaseConfig.ts, packages/common/src/hooks/useFeatureFlag.ts, packages/common/src/hooks/useRemoteVar.ts, packages/mobile/src/app/AppContextProvider.tsx, packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx, packages/mobile/src/components/premium-track-purchase-drawer/hooks/usePurchaseSummaryValues.ts, packages/mobile/src/hooks/useIsUSDCEnabled.ts, packages/mobile/src/screens/edit-track-screen/EditTrackScreen.tsx, packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/PremiumRadioField/PremiumRadioField.tsx, packages/mobile/src/screens/edit-track-screen/screens/AccessAndSaleScreen.tsx, packages/mobile/src/screens/feed-screen/FeedScreen.tsx, packages/web/src/app/AppContextProvider.tsx, packages/web/src/components/data-entry/AccessAndSaleTriggerLegacy.tsx, packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx, packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx, packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFooter.tsx, packages/web/src/components/premium-content-purchase-modal/hooks/usePurchaseSummaryValues.ts, packages/web/src/hooks/useIsUSDCEnabled.ts, packages/web/src/pages/feed-page/components/desktop/FeedPageContent.tsx, packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx, packages/web/src/pages/upload-page/fields/availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx
This removes the dependency injection pattern I implemented during the USDC feature in favor of pulling the necessary dependencies from `AppContext` instead. We're already using this pattern in common sagas. We just don't expose the as many dependencies in the React context version. 
The goal is to get away from the `createXHook` pattern where web and mobile generate their own versions of a common hook by passing in the necessary dependencies. This prevents us from writing and exposing hooks in `common` and leads to duplicated code.
fixes PAY-2176
Tested locally in Chrome and Simulator against staging. I updated one usage of the hooks in question to verify that it works correctly. Will follow up in future PRs to migrate usage of derived hooks.
=> [PAY-2176] Implement remote config hooks via context

mediorum/ethcontracts/ethcontracts.go, mediorum/main.go, mediorum/registrar/chain.go, mediorum/registrar/multi.go
- Makes mediorum query chain directly as a fallback for staging+prod (only as a fallback because the other options are more economical)
- Changes the future audius-d `sandbox` entrypoint to use this instead of hardcoding
Leaves the single+cluster dev entrypoints because unit tests and other things need to be able to use them without ganache
- Tested on stage CN5 - the health check shows it using the correct peers and signers when commenting out fallbacks to API Gateway and The Graph
- Haven't tested sandbox entrypoint because it looks like it's not wired up to audius-d yet. But the audius-d config shows that it points `ethProviderUrl` to the local eth ganache container, which is all that's needed. cc @phelpsdb
=> [PROTO-1449] Make mediorum query eth directly for service providers

protocol-dashboard/scripts/updateBuild.cjs
Prod deploy currently broken at the `fs.writeFileSync('./build_cid.txt', cid.IpfsHash)` line: https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/46711/workflows/945defb4-d08d-44db-8f2e-64ba0dac916f/jobs/606059
From the logs, it appears `cid` is just a string. We want to get `IpfsHash` form the result of `pinata.pinFromFS`
=> Fix dashboard prod deploy

packages/web/src/components/welcome-modal/WelcomeModal.tsx, packages/web/src/pages/sign-up-page/components/AccountHeader.tsx, packages/web/src/pages/sign-up-page/components/CoverPhotoBanner.tsx
I noticed our new sign up welcome modal was only showing the blurry profile photo instead of using the cover photo when available. 
I updated it to use existing cover photo logic from the other pages
Tested mobile & desktop web with both cover photo and no cover photo (just profile image)
=> fix: Update welcome modal cover photo to use saved cover photos

packages/discovery-provider/src/queries/get_health.py, packages/discovery-provider/src/queries/health_check.py
Use `slot_diff` for health check instead. This is because if there are no transactions on staging, the time_diff can get high even if it indexing is actually not behind.
Local dev stack
=> [PAY-2220] Use slot_diff in user_bank health

packages/common/src/utils/formatUtil.test.ts, packages/fixed-decimal/src/FixedDecimal.test.ts, packages/fixed-decimal/src/FixedDecimal.ts
Values less than one tenth, eg. 0.04, were incorrectly showing as 10x their value in `toShorthand()`
Added tests
=> Fix FixedDecimal.toShorthand() for numbers less than a tenth

packages/harmony/src/foundations/reset/reset.css
Currently, the Avenir font will render differently on different browsers & in different environments because our reset.css doesn't cover aliasing, etc.
These are standards borrowed from the "create vite app" reset and match similarly what we have done in the web client & protocol dashboard.
```
npm run storybook
```
Confirmed things look consistent -- and this change also fixed the embed player.
Before:
After:
=> Improve harmony font consistency

packages/harmony/src/components/text/Text/Text.tsx, packages/harmony/src/components/text/Text/constants.ts, packages/harmony/src/components/text/Text/index.ts, packages/harmony/src/storybook/components/TypographyPanel.tsx, packages/mobile/src/app/index.ts, packages/mobile/src/harmony-native/foundations/typography/Text.tsx
Update the native harmony text component to use the harmony theme and remove old code
Text looks good in mobile storybook
=> [C-3391] Update native harmony Text component to use harmony theme values
