.circleci/src/workflows/discovery.yml, dev-tools/compose/docker-compose.pedalboard.yml, dev-tools/compose/docker-compose.yml
Add sla auditor build step
```
audius-compose build
```
=> [PROTO-1223] Add sla auditor build step

mediorum/server/serve_upload.go
Return 422 if ffprobe fails for audio upload
=> Return status 422 if ffprobe fails

packages/web/src/components/image-selection/ImageSelectionPopup.js
Move the popup to below the artwork
=> [C-3067] Update upload flow artwork popup position

packages/web/src/components/data-entry/ContextualMenu.tsx
Move the modal footer outside of the modal context so that it sticks to the bottom
=> [C-3065] Update modal footer placement in contextual menu to make the save button sticky

packages/web/src/pages/upload-page/fields/availability/UsdcPurchaseFields.tsx, packages/web/src/utils/tokenInput.ts
Add effect to set the price to form state if we go to a different access condition and back
=> Add effect to re-set the price form value if missing

packages/common/src/utils/linking.ts, packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.tsx, packages/web/src/components/transaction-details-modal/components/TransactionPurchaseMetadata.tsx, packages/web/src/components/usdc-transaction-details-modal/USDCTransactionDetailsModal.tsx, packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.tsx
Normalizes solana transaction links to use solscan and updates all usages to go through a helper function.
Fixes PAY-1846
Tested locally against staging data in Chrome
=> [PAY-1846] Make solana transaction external linking consistent

packages/web/src/pages/upload-page/fields/MultiTrackSidebar.tsx, packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx, packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
Add scrollToTop call to submit buttons for single and multi track forms
=> [C-3034] Add scrollToTop on track upload form submit

packages/stems/src/components/HarmonyButton/BaseButton.module.css, packages/stems/src/components/HarmonyButton/HarmonyButton.module.css
- Fix button transition not animating on hover end
- Fix button text being affected by darkened overlay on press
=> [C-3061] Fix harmony button states

.circleci/src/jobs/deploy.yml
Slack messages not getting sent because errors are propagated.
n/a
=> Remove set -x

mediorum/server/serve_blob.go, mediorum/server/serve_upload.go
Use c.blob for images instead ... but it doesn't work, maybe because our file detection `isAudioFile` doesn't work...?
Test on stage
=> No range images

packages/web/src/common/store/cache/collections/commonSagas.js, packages/web/src/common/store/cache/collections/createPlaylistSaga.ts, packages/web/src/common/store/upload/sagas.js
E.g. when you create a playlist or upload an album, it should show up in your library.
=> Make sure new (or deleted) collections created by user are added (or removed) in library PAY-1832

packages/web/src/common/store/pages/saved/lineups/sagas.js
Small TS error that may have contributed to an error Julian was seeing
=> Fix tracks library bug PAY-1864

discovery-provider/plugins/notifications/src/__tests__/processEmailNotifications.test.ts, discovery-provider/plugins/notifications/src/email/notifications/index.ts, discovery-provider/plugins/notifications/src/utils/populateDB.ts
removes the unnest in favor of the cte operation
ran in a manual script against prod dn4
=> fix app notifs sql

package-lock.json, package.json
This caused the client release cut to fail
=> Add root name to allow release branch generation

packages/web/src/components/track/desktop/ConnectedTrackTile.module.css, packages/web/src/components/track/desktop/stats/Stats.module.css
Fixes PAY-1641 and undoes the previous hack
Checked profile page, track tile, and artist card.. nothing super sketch...
=> PAY-1641 Fix socials overflow

packages/web/src/common/store/search-bar/sagas.ts
Don't show results in search autocomplete unless usdc flag is turned on
Tested on stage, looking for tracks
=> [PAY-1854] Add feature flag check for search autocomplete

.circleci/src/jobs/release-audius-docker-compose.yml
Ensure all compose files get updated tags
```
sed -i "s/{TAG:-.*}/{TAG:-$CIRCLE_SHA1}/" */docker-compose.*.yml
git add */docker-compose.*.yml
```
=> Update tag replacement command

docs/src/css/colors.css, docs/src/theme/dark.js, docs/src/theme/light.js, packages/web/src/assets/styles/colors.css, packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.module.css, packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.tsx, packages/web/src/pages/artist-dashboard-page/components/TotalPlaysChart.js, packages/web/src/utils/theme/dark.ts, packages/web/src/utils/theme/default.ts, packages/web/src/utils/theme/matrix.ts
=> [PAY-1865] Fix colors on dashboard page

packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
Removes reposts from smart collections
=> [C-3094] Remove repost from smart collection

packages/mobile/src/components/share-drawer/ShareDrawer.tsx
Fixes issue where playlist description was showing up for tracks
=> [C-3103] Fix share modal playlist description

packages/web/src/pages/upload-page/components/FinishPageNew.tsx
Upload is empty for the early renders of finish page. We don't show the link until the upload completes, so no issue with returning an empty path here
local web
=> [C-3109] Fix null error in FinishPage

mediorum/server/serve_health.go
Return 200 if server is seeding
=> don't 503 for isSeeding

discovery-provider/plugins/pedalboard/apps/sla-auditor/src/audit.ts, discovery-provider/plugins/pedalboard/apps/sla-auditor/src/audits/version.ts, discovery-provider/plugins/pedalboard/apps/sla-auditor/src/proposal.ts
* Include min version from the node if we aren't able to identify node type (fixes issue where minVersion shows as empty)
* Fix WEI calculus because mul 10*18 require bn.js. Big woops.
Tested pretty thoroughly, ran the auditor locally & verified results
```
Submitting proposal: [SLA] Slash 3000 $AUDIO from 0xredacted
=======DRY RUN=======
{
targetContractRegistryKey: '0x44656c65676174654d616e61676572',
callValue: '0',
functionSignature: 'slash(uint256,address)',
callData: [
'3000000000000000000000',
'0xredacted'
],
name: '[SLA] Slash 3000 $AUDIO from 0xredacted',
description: '\n' +
'This proposal presents recommendation to the community to slash 3000 $AUDIO from\n' +
'\n' + …
```
=> Fix SLA auditor numeric values

packages/web/src/components/header-button/HeaderButton.module.css, packages/web/src/components/header/mobile/Header.module.css, packages/web/src/components/lineup/InfiniteCardLineup.tsx, packages/web/src/hooks/useTabs/useTabs.tsx, packages/web/src/pages/saved-page/SavedPageProvider.tsx, packages/web/src/pages/saved-page/components/desktop/AlbumsTabPage.tsx, packages/web/src/pages/saved-page/components/desktop/LibraryCategorySelectionMenu.tsx, packages/web/src/pages/saved-page/components/desktop/PlaylistsTabPage.tsx, packages/web/src/pages/saved-page/components/mobile/SavedPage.module.css, packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx, packages/web/src/pages/saved-page/hooks/useCollectionsData.tsx
-Implement Library stuff on mobile web
-Several mobile web library fixes because it was basically unusable before:
1. Scroll bar would jitter uncontrollably for many seconds, until which it was impossible to scroll anywhere
2. Scroll bar would not be big enough for the albums tab, cutting off the content
3. Filter input value for playlists was reused for tracks inexplicably
-Fix loading spinner not showing up at bottom of infinite card lineup when new items were loading in
=> Implement new Library feature for mobile web + several bug fixes PAY-1863 C-2985 PAY-1263 C-2604 C-3100

packages/probers/cypress/e2e/uploadTrack.cy.ts, packages/stems/src/components/ProgressBar/ProgressBar.tsx, packages/stems/src/components/ProgressBar/types.ts, packages/web/src/pages/upload-page/UploadPageNew.tsx, packages/web/src/pages/upload-page/components/AnchoredSubmitRow.tsx, packages/web/src/pages/upload-page/components/FinishPageNew.tsx, packages/web/src/pages/upload-page/components/ShareBannerNew.tsx, packages/web/src/pages/upload-page/fields/AttributionField.tsx, packages/web/src/pages/upload-page/fields/DatePickerField.tsx, packages/web/src/pages/upload-page/fields/ReleaseDateField.tsx, packages/web/src/pages/upload-page/fields/SourceFilesField.tsx, packages/web/src/pages/upload-page/fields/availability/HiddenAvailabilityFields.tsx, packages/web/src/pages/upload-page/types.ts, packages/web/src/pages/upload-page/validation.ts
Fixes a multitude of issues related to more complex input flows for upload
Implemented an uploadTrack.cy.ts probers test to catch all these cases
=> [C-3114] Fix complex upload patterns

packages/web/src/common/store/upload/sagas.js, packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx, packages/web/src/pages/upload-page/validation.ts
- Set release date on uploaded tracks from the collection's metadata
- Release date field had the wrong name in validation and initial values
working on local web
=> [C-3116] Pipe collection release_date through to tracks

discovery-provider/scripts/start.sh
This reverts commit 81b3bc017a83bc75659489c4dffa24d6f70a4b03.
=> Revert "[PROTO-1250] Move celery to eventlets (#5975)"

.circleci/src/workflows/discovery.yml, discovery-provider/api-tests/Test Sandbox.postman_environment.json
This job needs to depend on deploying to stage and prod sandbox instead.
Sandbox DNS works now so we can update this here. 
=> Update api test url and workflow dependency

discovery-provider/src/queries/get_health.py
So can have a single uptime robot monitor querying `/health_check?verbose=true&enforce_block_diff=true&healthy_block_diff=250&plays_count_max_drift=720`
Tested locally, saw expected errors
Deployed to healthy stage node, did not see errors
=> Check API in DN verbose healthcheck

dev-tools/compose/docker-compose.storagev2.yml, dev-tools/compose/docker-compose.test.yml, mediorum/crudr/crudr.go, mediorum/ddl/ddl.go, mediorum/server/db.go
all nodes will be updated by the end of this week so we can remove the migration code in next week's deploy
=> remove partition migration

mediorum/server/monitor.go, mediorum/server/peer_health.go, mediorum/server/repair.go, mediorum/server/replicate.go, mediorum/server/serve_blob.go, mediorum/server/serve_image_test.go, mediorum/server/serve_upload.go, mediorum/server/server.go
StoreAll node should skip any deletes
=> fix repair for StoreAll

.gitignore, package-lock.json, package.json, packages/common/package.json, packages/embed/package.json, packages/mobile/package.json, packages/web/package.json, turbo.json
* Add turborepo
Not doing much with it yet but this sets us up to more efficiently build our docker images and cache on CI
* Update `build` script to utilize turbo dependency graph
=> [INF-474] Add turborepo

dev-tools/compose/docker-compose.storagev2.yml, dev-tools/compose/docker-compose.test.yml, mediorum/crudr/crudr.go, mediorum/ddl/ddl.go, mediorum/server/db.go
Is making audius-cmd tests flaky bc mediorum nodes take longer to start up. Will debug further and re-merge
This reverts commit 978e2df4f7f21e0a7599998caceb0eca8e88b6b0.
=> Revert "remove partition migration (#5936)"

discovery-provider/src/queries/download_csv.py
To display correct amounts in CSV
=> Use 6 decimals for withdrawals too

.circleci/src/workflows/creator.yml, dev-tools/compose/docker-compose.test.yml, mediorum/Dockerfile.unittests, mediorum/crudr/setup_test_db.go, mediorum/server/test_main_test.go
As title
works with both `make test` and `audius-compose test run mediorum-unittests`
Verified that [circleci job passed](https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/42070/workflows/00918dbb-88c6-4780-bf5f-b5e7050237c3/jobs/541649).
=> [PROTO-1235] Run mediorum unittests in CI

identity-service/src/routes/solana.js, identity-service/src/utils/relayHelpers.js, identity-service/src/utils/relayUtils.js
Fixes trending rewards disbursement
It hasn't
=> Allow unauthorized relay

.circleci/config.yml, .circleci/src/jobs/deploy-stage-nodes.yml
Whoops. Now staging should work again.
=> Fix service param syntax

packages/web/src/pages/purchases-and-sales/PurchasesPage.tsx, packages/web/src/pages/purchases-and-sales/SalesPage.tsx, packages/web/src/pages/purchases-and-sales/WithdrawalsPage.tsx, packages/web/src/utils/dateUtils.ts
eg `purchases_2023-9-25`, `sales_2023-9-23` `withdrawals_2023-9-23`
local v stage
=> Update CSV download filenames

package-lock.json, packages/libs/package.json
Update `msw` to 1.3.1 because they introduced a breaking change via the `headers-polyfill` which wasn't pinned in version 1.0.0
=> Fix sdk tests by upgrading msw

packages/common/src/services/audius-backend/solana.ts
Fixes balance polling as the initial balance was 0 and the new balance was already ready right away
it hasn't! need to test on prod!
=> Fix falsey check in pollForBalanceChange

identity-service/src/config.js, identity-service/src/routes/user.js
Switch from sendgrid to bouncer for api email validation
Stage identity
`yabuhpvu@gmail.com` = invalid
`ray+92523@audius.co` = valid
=> Switch to bouncer for email validation

packages/libs/scripts/release.sh
Broken because `npm version` gives a ~json object in return instead of just the version now.
On CI via ssh method.
Released at: https://www.npmjs.com/package/@audius/sdk/v/3.0.10-beta.0
=> Fix sdk deploy

.circleci/src/jobs/release-audius-sdk.yml, .circleci/src/workflows/sdk.yml
* node_modules are already cached in the init step, no need to reinstall
Tested that cache is properly restored
=> Use cached node_modules in release-audius-sdk

mediorum/server/replicate.go, mediorum/server/server.go
For large files 10s read deadline was not enough.
=> Longer timeout for blob transfer

packages/common/src/store/purchase-content/sagas.ts, packages/common/src/store/purchase-content/slice.ts, packages/web/src/common/store/pages/saved/lineups/sagas.js
=> Fix add to library after purchase PAY-1898

packages/web/src/pages/purchases-and-sales/PurchasesPage.tsx, packages/web/src/pages/purchases-and-sales/SalesPage.tsx, packages/web/src/pages/purchases-and-sales/WithdrawalsPage.tsx
Disable CSV download buttons for purchases, sales, withdrawals, if the tables have no data.
local dapp vs. stage
=> [PAY-1931] Disable CSV download if no data

.circleci/config.yml, .circleci/src/jobs/@embed-jobs.yml, .circleci/src/jobs/@harmony-jobs.yml, .circleci/src/jobs/@web-jobs.yml, .circleci/src/workflows/harmony.yml, packages/harmony/workers-site/.gitignore, packages/harmony/workers-site/index.js, packages/harmony/workers-site/package-lock.json, packages/harmony/workers-site/package.json, packages/harmony/wrangler.toml
Update ci to build and deploy storybook for harmony when updated
Set up worker in cloudflare for harmony
harmony.audius.co
=> [C-3107] Add Harmony.audius.co workers site

packages/mobile/.hooks/pre-push.json, packages/probers/cypress/support/commands.ts, packages/web/.hooks/pre-push.json
* Fix probers lint with eslint-ignore
* Update hooks to only run relevant workspaces
=> Fix probers lint and improve git hooks

docs/docusaurus.config.js, docs/i18n-disabled/fr/docusaurus-theme-classic/footer.json
Update link in docs footer, also fixes spot in the unused `fr` dir
```
npm run build
npm run serve
```
=> Update twitter link in docs

package-lock.json, packages/mobile/e2e/fixtures/user.json, packages/mobile/e2e/signIn.test.ts, packages/mobile/metro.config.js, packages/mobile/src/components/core/GradientText.tsx, packages/mobile/src/components/core/TextInput.tsx, packages/mobile/src/components/fields/TextField.tsx, packages/mobile/src/harmony-native/components/Link/Link.tsx, packages/mobile/src/screens/app-screen/AppTabScreen.tsx, packages/mobile/src/screens/root-screen/RootScreen.tsx, packages/mobile/src/screens/sign-in-screen/SignInScreen.tsx, packages/mobile/src/screens/sign-up-screen/SignUpScreen.tsx, packages/mobile/tsconfig.json, packages/probers/cypress/e2e/signIn.cy.ts, packages/web/src/common/store/pages/signon/sagas.js, packages/web/src/pages/sign-in-page/SignInPage.tsx, packages/web/src/services/remote-config/featureFlagHelpers.ts
Implements bare-bones sign-in for web and mobile
Adds e2e tests
=> [C-3138] Implement sign-in

packages/web/src/components/image-selection/ImageSelectionPopup.js
Updated that anchoring logic for the artwork popup to change based on the screen size
=> [C-3158] Update artwork popup anchoring logic

packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.tsx, packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.module.css, packages/web/src/pages/artist-dashboard-page/components/ArtistCard.module.css, packages/web/src/pages/artist-dashboard-page/components/USDCCard.module.css
Validation wasn't using the right precision 🦉 
```
```
=> [PAY-1910] Fix withdrawal form validation and dashboard layout

discovery-provider/README.md
=> Update README.md to point to dev containers extension

package.json
* Add turbo-link command to make enabling remote caching easy
=> Add turbo-link command

mediorum/main.go, mediorum/registrar/multi.go
if one fails, try the next
deployed to stage dn 5
=> multiple peer providers with fallback behavior

packages/libs/src/services/discoveryProvider/DiscoveryProvider.ts, packages/trpc-server/src/loaders.ts, packages/trpc-server/src/routers/me-router.ts, packages/web/src/app.tsx, packages/web/src/components/artist/ArtistCardCover.tsx, packages/web/src/components/artist/ArtistChip.tsx, packages/web/src/components/artist/ArtistChipFollowers.tsx, packages/web/src/components/artist/ArtistCover.tsx, packages/web/src/components/user-badges/FollowsYouBadge.tsx, packages/web/src/pages/demo-trpc/DemoTrpcPage.tsx, packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx, packages/web/src/pages/profile-page/components/desktop/ProfileWrapping.tsx, packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx, packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx, packages/web/src/services/trpc.ts
currently you have to manually set `current_user_id` for trpc client:
```
localStorage.setItem('current_user_id', '197005');
```
todo:
=> FollowsYou badge uses trpc

packages/web/src/components/user-badges/FollowsYouBadge.tsx
=> fix import order

discovery-provider/ddl/functions/notify_on_row.sql, discovery-provider/ddl/migrations/0000_schema_failable.sql, discovery-provider/plugins/verified-uploads/publish-bot.sh, discovery-provider/plugins/verified-uploads/src/db.js, discovery-provider/plugins/verified-uploads/src/handlers/tracks.js, discovery-provider/plugins/verified-uploads/src/handlers/users.js
- changes needed after merge
- reverts the db change and puts it in the right place
- doesn't send upload notif if both the time slots are undefined
- adds release script
=> verified bot follow ons

.gitignore, identity-service/local-storage/%40audius%2Flibs%3Adiscovery-node-timestamp
=> Remove erroneous local-storage

packages/common/src/store/purchase-content/slice.ts, packages/mobile/src/components/core/ErrorText.tsx, packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx, packages/mobile/src/components/stripe-onramp-drawer/StripeOnrampDrawer.tsx, packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx, packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/PremiumRadioField/BoxedTextField.tsx, packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/PremiumRadioField/TrackPreviewField.tsx, packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/PremiumRadioField/TrackPriceField.tsx, packages/mobile/src/screens/edit-track-screen/screens/AccessAndSaleScreen.tsx, packages/web/src/components/track/desktop/TrackTile.tsx, packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.tsx, packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.tsx, packages/web/src/components/withdraw-usdc-modal/components/EnterTransferDetails.tsx, packages/web/src/pages/artist-dashboard-page/ArtistDashboardPage.module.css, packages/web/src/pages/artist-dashboard-page/components/TracksTableContainer.tsx, packages/web/src/pages/purchases-and-sales/SalesPage.tsx
PR can be reviewed commit by commit. Most had issues. Couple were things I saw that were unrelated, but easy fixes.
```
npm run mobile
```
=> Fix several USDC purchase related bugs

packages/web/public/index.html
Probably will help a little with js loading/seo
=> Defer jimp.min.js

packages/web/src/pages/upload-page/fields/availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx
Fix coming soon tag - should only show when disabled
```
```
feature flag override UI with `f`
=> Fix coming soon tag

packages/mobile/android/app/build.gradle, packages/mobile/ios/AudiusReactNative/Info.plist
=> Bump app version to trigger full app release

.circleci/src/jobs/@discovery-jobs.yml, .circleci/src/workflows/discovery.yml
Trending and search are giving diff results so let's just make this always pass for now. Still useful to check the report for other diffs.
made a test run pass https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/43183/workflows/5a35ce3a-85c5-436d-af17-b71885dfc6d1/jobs/556281
=> Always pass test-discovery-api 

packages/web/src/pages/modals/Modals.tsx
Where did it go?
<details>
<summary>Details</summary>
</details>
=> [PAY-1944] Bring back AudioBreakdown

discovery-provider/src/queries/download_csv.py
Add pay extra column to purchases and sales csv
local dapp against stage. works. pay extra column is there with correct amount.
=> [PAY-1956] Add pay extra column to purchases and sales csv

packages/libs/src/services/web3Manager/Web3Manager.ts
this is making a lot of things on sentry appear to be an error when they're not
N/A
=> rm unneeded error log

discovery-provider/nginx_conf/nginx.conf
Fix the naming so it's piped correctly to docker logs.
=> Rename access log file

discovery-provider/ddl/migrations/0035_backfill_challenge_amount.sql
I had a similar migration in https://github.com/AudiusProject/audius-protocol/commit/22f2161ed4b3dfb65ccf4166933ce6a1b46772be but I forgot to change the backfill condition to check for `0` instead of `NULL` after changing the default value.
Tested on local stack by manually inserting rows with `amount = 0` and running the migration.
=> Backfill challenges amount migration

packages/harmony/package.json, packages/harmony/tsconfig.json, packages/web/src/components/premium-content-purchase-modal/components/PayExtraFormSection.tsx, packages/web/src/pages/artist-dashboard-page/components/TracksTableContainer.tsx, packages/web/src/pages/saved-page/components/desktop/LibraryCategorySelectionMenu.tsx
Replaced HarmonySelectablePill instances in web with harmony SelectablePill
Looks good on web 👍
=> [C-3175] Replace instances of HarmonySelectablePill in web with harmony component

package-lock.json, packages/mobile/package.json
=> Add react-query to mobile

package-lock.json, packages/identity-service/package.json, packages/identity-service/src/relay/ethTxRelay.js, packages/identity-service/src/relay/txRelay.js
This reverts commit 5e6217f19eb6e12191c75de44c7d28c5e0bfbf7c
=> Revert "Revert "[PLAT-259] Upgrade EthereumTx version (#3606)" (#3682)"

packages/identity-service/src/relay/ethTxRelay.js
Tested a full wormhole locally by pointing local dev to prod using config!
=> Fix gasPrice bug

packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeveloperAppsSettingsCard.tsx, packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
Added periods to various messages, removed one unused.
👀 locally
=> [C-3189] Adding periods + cleanup unused message

discovery-provider/plugins/verified-uploads/src/handlers/users.js
See comment https://github.com/AudiusProject/audius-protocol/pull/6206/files/3b1e0af394d2358bc019b38df5cb9bc57d2a0e35#diff-9f2fa4e2f86e851586191adfdcb5501d3531d9fcebfaa1197c69cc4ca64c8e50
=> Fix verified plugin check to account for new users

discovery-provider/src/queries/get_undisbursed_challenges.py
Forgot to update this endpoint to use the amount from user_challenges instead of challenges table.
Local stack, confirmed redux state now contains the correct amount.
=> Use user_challenges amount in undisbursed endpoint

package.json, packages/compose/package.json, turbo.json
Fwd audius-compose args from run protocol
```
npm run protocol (same as npm run protocol up)
npm run protocol down
npm run protocol test up discovery-provider
```
=> Support better run protocol commands

monitoring/healthz/src/pages/Nodes.tsx
Healthz rows no longer display in red when first loading.
Tested locally and deployed to healthz.audius.co.
=> Use neutral loading color in healthz

packages/discovery-provider/src/queries/get_attestation.py
Need to disburse the right amount during DN attestation.
Not tested but feeling confident/will try to get local stack with 3 DNs working to test attestations!
=> Use user_challenge amount in DN attestation

packages/discovery-provider/integration_tests/queries/test_get_attestation.py, packages/discovery-provider/integration_tests/queries/test_get_disbursed_challenges_amount.py, packages/discovery-provider/src/api/v1/challenges.py, packages/discovery-provider/src/api/v1/helpers.py, packages/discovery-provider/src/api/v1/models/challenges.py, packages/discovery-provider/src/models/rewards/challenge_disbursement.py, packages/discovery-provider/src/queries/get_attestation.py, packages/discovery-provider/src/queries/get_disbursed_challenges_amount.py
* Add challenge info endpoint
* Fix disbursement counting (WEI_DECIMALS)
Unit tests
=> [PAY-1891] Add challenge info endpoint

packages/web/src/common/store/upload/sagaHelpers.ts
Tricky to solve for now, feels safe to punt.
```
npm run web:dev
```
=> Disable usdc bank split in dev mode

.circleci/config.yml, .circleci/src/jobs/@identity-jobs.yml, .circleci/src/workflows/identity.yml, package-lock.json, packages/identity-service/.hooks/pre-push.json, packages/identity-service/package.json, packages/identity-service/src/notifications/index.js, packages/identity-service/src/rateLimiter.js, packages/identity-service/src/routes/push_notifications.js, packages/identity-service/src/utils/antiAbuse.js, turbo.json
* Add identity `lint` and `typecheck` to pre-push
* Add `identity-init` to CI
* Use turbo to verify identity
* Use `--transpile-only` flag when running identity in container, this is much faster but does not do any typechecking
* Fix lint 
Identity comes up properly and is faster to start, CI passes
=> [INF-398] Improve identity typecheck and run with --transpile-only

packages/identity-service/src/relay/ethTxRelay.js, packages/identity-service/src/routes/wormhole.js
Also changes logging to log while in progress
TBD
=> Wormhole: Receive SPL AUDIO in background process, respond early

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/services/wallet-client/WalletClient.ts, packages/common/src/store/wallet/selectors.ts, packages/common/src/store/wallet/slice.ts, packages/common/src/utils/typeUtils.ts, packages/libs/src/services/solana/SolanaWeb3Manager.ts, packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/AccountDetails.tsx, packages/mobile/src/screens/audio-screen/AudioScreen.tsx, packages/mobile/src/screens/tip-artist-screen/AvailableAudio.tsx, packages/web/src/common/store/tipping/sagas.ts, packages/web/src/common/store/wallet/sagas.ts, packages/web/src/components/buy-audio-modal/components/SuccessPage.tsx, packages/web/src/components/nav/desktop/NavAudio.tsx, packages/web/src/components/premium-content-purchase-modal/components/PurchaseSummaryTable.tsx, packages/web/src/components/tipping/tip-audio/SendTip.tsx, packages/web/src/components/transaction-details-modal/components/TransactionDetailsContent.tsx, packages/web/src/pages/audio-rewards-page/Tiles.tsx, packages/web/src/pages/audio-rewards-page/components/WalletActionsTile.tsx, packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.module.css, packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx, packages/web/src/store/application/ui/buy-audio/sagas.ts
Before:
- AUDIO balance load would error out
- Loading spinner was too small
After:
- Fixed
See comments for details.
Tested on web and mobile w multiple accounts w 0 and non-0 AUDIO
=> Fix audio balance error C-3207 C-3208

packages/web/src/components/feature-flag-override-modal/FeatureFlagOverrideModal.tsx
Fixes issue where feature-flag-override modal does not finish loading if triggering when signed out. If signed out, we wait for remote-config, if signed-in we wait for user-remote config
=> Fix feature-flag override when signed-out

packages/common/src/store/buy-usdc/sagas.ts
Only attempt usdc recovery is user is logged in
local dapp vs stage
=> [PAY-1996] Only attempt usdc recovery is user is logged in

.circleci/src/jobs/push-docker-image.yml, .circleci/src/jobs/test-audius-cmd.yml, .circleci/src/jobs/test.yml
After testing in isolation we see that DLC has no effect on our builds. Ticket submitted to CircleCI: [#140558](https://support.circleci.com/hc/requests/140558). In the meantime, we can disable the feature.
CI
=> [PROTO-1329] Disable DLC

packages/common/src/utils/challenges.ts, packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
=> [PAY-1993] Order challenges by claimable amt

packages/web/src/components/table/components/TableRepostButton.module.css, packages/web/src/components/table/components/TableRepostButton.tsx
Fixes table action hover state inconsistency. Updated repost button to act like the repost button on the track tile.
=> [C-3101] Fix table action hover state

.circleci/src/jobs/@harmony-jobs.yml, .circleci/src/workflows/harmony.yml, package-lock.json, packages/harmony/package.json
- add chromatic package
- add script to run chromatic locally
- run chromatic in CI whenever `packages/harmony/*` has changes
- Wondering if there's a way to have the github check rerun automatically when the visual changes are approved
- Can we have it post the storybook preview link on the PR like we do with the web preview?
Working [ci build](https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/44064/workflows/88ee52d4-0917-49f5-bb53-1fb8419667d7/jobs/567232)
=> [C-3217] Add chromatic to harmony and run in CI

packages/web/src/pages/artist-dashboard-page/components/USDCCard.tsx, packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
Allow editing a usdc purchase track into a public track
=> [PAY-1990] Fix premium to public edit bug

packages/web/src/components/leaving-audius-modal/LeavingAudiusModal.tsx, packages/web/src/components/track/PlayPauseButton.tsx, packages/web/src/components/usdc-purchase-details-modal/components/PurchaseModalContent.tsx, packages/web/src/components/usdc-purchase-details-modal/components/SaleModalContent.tsx
Button types have received updated designs. Per Julian's request, moving all current tertiary usages to secondary type
local web
=> [C-3232] Change tertiary button usages to secondary

packages/web/turbo.json
I accidentally made web `build` and `dist` persistent turborepo tasks in the previous PR
=> Make web build and dist non-persistent

packages/web/package.json, packages/web/src/services/audius-sdk/auth.ts
Fix developer app creation
```
```
Create app
use sdk consumer to verify
=> Fix sign typed data issues in develop app creation

package-lock.json
=> Commit package-lock

.circleci/config.yml, dev-tools/setup-dev.sh, dev-tools/setup.sh, scripts/postinstall.sh
`dev-tools/setup.sh` was throwing a couple errors for me:
```
+ source /etc/os-release
dev-tools/setup.sh: line 5: /etc/os-release: No such file or directory
```
```
/Users/sebastian/workspace/audius-protocol/dev-tools/setup-dev.sh: line 10: cd: /Users/sebastian/workspace/audius-protocol/libs: No such file or directory
```
Also, this PR makes it so `dev-tools/setup.sh` isn't run on CI
=> Fix dev-tools setup script

packages/mobile/src/components/premium-track-purchase-drawer/PurchaseSummaryTable.tsx, packages/mobile/src/components/summary-table/SummaryTable.tsx, packages/mobile/src/components/summary-table/index.ts
Refactor `PurchaseSummaryTable` to use a new `SummaryTable` component (in preparation to use `SummaryTable` in cooldown UI).
=> Mobile SummaryTable component

packages/mobile/src/components/now-playing-drawer/TrackInfo.tsx, packages/web/src/components/now-playing/NowPlaying.module.css
Preview pill should be centered
moweb
mobile
=> [PAY-2067] Fix preview now playing drawer layout issues

packages/discovery-provider/src/challenges/audio_matching_challenge.py
This was accidentally filtering buy challenges to non-verified users.
CI
=> [PAY-2059] Make sure we show buyer challenges for verified users

.circleci/src/jobs/test-audius-cmd.yml, .circleci/src/jobs/test.yml, dev-tools/setup.sh
Expand self-hosted test runs to all backend service tests
CI
=> Run all service tests on self-hosted machines

packages/web/src/store/application/ui/buy-audio/sagas.ts
=> Fix jupiter buy-audio flow

packages/mobile/src/components/challenge-rewards-drawer/CooldownSummaryTable.tsx, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/AudioMatchingRewardsModalContent.tsx
=> [PAY-2061] Hide table if no challenges summary

packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/styles.module.css
=> [PAY-2063] Fix border colors

packages/discovery-provider/src/queries/get_notifications.py
* This includes playlist notifications, so check that first
* This was breaking rather than continuing and dropping further notifs
* Set on stage discovery 5, verified fix still loads notifs
* Set on prod discovery 2, verified notifs are loading properly for my user acct with a playlist create
=> Fix notifications

.circleci/src/jobs/release-governance.yml, .circleci/src/workflows/release.yml
* Monorepo install compatible via npm cache restoration
* Missing comma (how did this ever work?)
Created proposals here:
https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/44683/workflows/e6b036eb-fd92-4264-929a-7fdaad57e566/jobs/575766
Not 100% sure about the slack post, and I'd rather not re-trigger the jobs, but I believe the missing comma will fix the last error I got
```
Expected separator between values at line 7, column 14
```
=> Fix governance proposal release script

packages/harmony/src/components/button/BaseButton.module.css, packages/harmony/src/components/button/Button.module.css
Moves psuedoselector into class definition
Also fixes a few dark-mode styles
=> Move psuedoselectors into class definition

packages/probers/cypress/e2e/uploadTrack.cy.ts, packages/probers/cypress/fixtures/aiAttribution.json, packages/web/src/common/store/search-ai-bar/sagas.ts
Upload probers was failing on main due to a name change on the account for ai attribution.
- Added `@probersai` account for use specifically on this test
- Noticed the query was likely to miss due to the small results limit. Raised the limit to increase chance of hitting a match (maybe unnecessary)
works on local cypress run
=> [C-3266] Partially fix upload probers

dev-tools/compose/docker-compose.yml
Update version to 11.4 to avoid changing on re-upping stack
=> Update local stack postgres version

packages/mobile/src/screens/edit-track-screen/components/CollectibleGatedAvailability.tsx, packages/mobile/src/screens/edit-track-screen/components/HiddenAvailability.tsx, packages/mobile/src/screens/edit-track-screen/components/SpecialAccessAvailability.tsx, packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/PremiumRadioField/PremiumRadioField.tsx, packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/PublicAvailabilityRadioField.tsx, packages/mobile/src/screens/edit-track-screen/screens/AccessAndSaleScreen.tsx
Negative margin is a little rough, but would require a larger refactor and this makes it just scoped to the component we need.
```
npm run mobile
```
=> [PAY-2064] Fix misc mobile access & sale ui

.circleci/src/jobs/@harmony-jobs.yml
=> chore: Fix chromatic args not being passed thru

packages/mobile/src/components/premium-track-purchase-drawer/PurchaseUnavailable.tsx
=> Update iOS purchase unavailable copy

packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx, packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/PremiumRadioField/PremiumRadioField.tsx, packages/web/src/components/premium-content-purchase-modal/components/PayToUnlockInfo.tsx, packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.tsx, packages/web/src/components/withdraw-usdc-modal/components/EnterTransferDetails.tsx, packages/web/src/pages/artist-dashboard-page/components/USDCCard.tsx, packages/web/src/pages/upload-page/fields/availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx
Update various links
Stage web & mobile
=> [PAY-1708] Update ToS/Learn More/early access links

mediorum/README.md, mediorum/server/transcode.go
* retry fewer times
* cleanup transcode temp files
* capture ffmpeg output on failure
tested locally with valid and invalid files
=> [PROTO-1210]: better transcode failure handling.

packages/mobile/src/screens/edit-track-screen/screens/RemixSettingsScreen.tsx
On native mobile, disallow user going back to main track upload from bad remix track input.
ios v stage
https://github.com/AudiusProject/audius-protocol/assets/9600175/05a011b8-f709-4b9c-b4fd-0d00a75f3a47
=> Fix remix access bug

packages/mobile/android/app/build.gradle, packages/mobile/ios/AudiusReactNative/Info.plist
iOS:
1.1.75
Android:
1.1.400
On `release-client-v1.5.48`
=> Bump mobile versions

packages/web/src/components/drawer/Drawer.tsx, packages/web/src/components/usdc-manual-transfer-modal/USDCManualTransferModal.tsx, packages/web/src/pages/audio-rewards-page/components/modals/ModalDrawer.tsx
zIndex was not getting passed through in `ModalDrawer`.
Local mobile-web stage.
=> Fix manual transfer UI on mobile web

packages/common/src/models/Analytics.ts, packages/mobile/src/components/usdc-manual-transfer-drawer/USDCManualTransferDrawer.tsx, packages/web/src/components/usdc-manual-transfer-modal/USDCManualTransferModal.tsx
Track when the user copies their USDC user bank address.
=> [PAY-2095] Analytics for USDC manual transfer

packages/web/src/pages/PublicSite.tsx, packages/web/src/pages/download-page/DownloadPage.tsx, packages/web/src/pages/privacy-policy-page/PrivacyPolicyPage.tsx, packages/web/src/pages/service-terms-page/ServiceTermsPage.tsx, packages/web/src/pages/terms-of-use-page/TermsOfUsePage.tsx
Apply v2 landing page changes
local web and mobile web dapp vs stage
=> Uncomment lines to apply v2 landing page

dev-tools/compose/nginx_ingress.conf, protocol-dashboard/src/components/MobileNav/MobileNav.tsx, protocol-dashboard/src/components/Nav/Nav.tsx, protocol-dashboard/src/containers/DiscoveryProviders/DiscoveryProviders.tsx
Fixes bugs:
- Discovery not redirecting to the right path for registered nodes
- Nav not showing active/highlighted state for subroutes of the services tab
- Only local DN1 having nginx setup for /dashboard (not other local DNs or CNs)
=> Fix protocol dashboard bugs

packages/web/src/pages/landing-page-v2/components/CTAStartListening.module.css
Margin bug because Case Studies section is commented out. This fixes it.
local dapps web and mobile web
=> Fix margin

packages/common/src/store/buy-crypto/sagas.ts
Fixes circular dep
Testing in CI my local is borked
=> Remove circular dep

packages/common/src/models/Analytics.ts, packages/web/src/components/banner/CallToActionBanner.module.css, packages/web/src/components/banner/CallToActionBanner.tsx, packages/web/src/components/banner/TermsOfServiceUpdateBanner.tsx, packages/web/src/pages/App.js
=> [PAY-2086] Update TOS banner

packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/create.ts
=> [PAY-1880] Re-enable email summary notifs for purchases

packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
=> [PAY-2115] Remove favorite btn when not purchased

packages/web/scripts/dist.js
https://github.com/electron/notarize#notes-on-your-teamid needed for latest electron/notarize
=> Add teamId to mac dist notarize

packages/mobile/src/components/premium-track-purchase-drawer/PayExtraFormSection.tsx, packages/web/src/components/nav/desktop/NowPlayingArtworkTile.tsx, packages/web/src/components/play-bar/desktop/PlayBar.js, packages/web/src/components/play-bar/desktop/components/PlayingTrackInfo.tsx, packages/web/src/components/table/Table.tsx, packages/web/src/pages/visualizer/VisualizerProvider.tsx
- Remove draggability of premium tracks from now playing artwork
- Remove draggability of premium tracks from now playing title
- Remove draggability of premium tracks from library
- Disable pay extra input when purchase in progress in native mobile
local web dapp and native mobile vs stage
=> [PAY-2109][PAY-2113] Miscellaneous gated track fixes

packages/mobile/src/components/core/AddressTile.tsx, packages/mobile/src/components/lineup/types.ts, packages/mobile/src/components/usdc-manual-transfer-drawer/USDCManualTransferDrawer.tsx
Some lingering lint and typecheck issues
=> Fixes lint and typecheck

packages/harmony/src/components/button/BaseButton/BaseButton.module.css, packages/harmony/src/components/button/Button/Button.module.css, packages/harmony/src/components/button/SocialButton/SocialButton.module.css
Removed the neat new css features so that things work on older chrome versions like the one used on desktop
Tested on desktop
=> [C-3304] Update Button styles to work on desktop and older chrome versions

packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx, packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx, packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx
Also fix error message padding
web and native mobile dapps vs stage
=> [PAY-2116][PAY-2117] Re-enable form elements on USDC purchase error

packages/mobile/src/screens/edit-track-screen/fields/AccessAndSaleField/PremiumRadioField/PremiumRadioField.tsx, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/styles.module.css, packages/web/src/pages/upload-page/fields/availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx
local web and native mobile v stage
=> [PAY-2031][PAY-2081] Fix coming soon message and reward padding

packages/mobile/src/screens/audio-screen/Panel.tsx
Not sure why this fix works but it does.
android:
ios unchanged:
=> Fix challenge new pill on android

packages/harmony/src/components/button/SocialButton/SocialButton.tsx, packages/web/src/pages/AppProviders.tsx, packages/web/src/pages/ThemeProvider.tsx
Adds harmony-theme-provider to web so all our soon-to-be emotionized components render correctly
=> [C-3303] Add harmony-theme-provider to web

packages/mobile/src/app/Drawers.tsx
Fixes some errors that happened due to the drawers now being loaded on start
=> Update the drawer fix to not render on start

package-lock.json, package.json, packages/common/package.json, packages/embed/package.json, packages/eslint-config-audius/package.json, packages/mobile/android/app/build.gradle, packages/mobile/ios/AudiusReactNative/Info.plist, packages/mobile/package.json, packages/probers/package.json, packages/stems/package.json, packages/web/package.json
=> Bump to version 1.5.49

packages/mobile/src/components/core/LockedStatusBadge.tsx
Updates text to static-white for constistency in dark and matrix modes
=> Fix locked-status-badge text color

packages/web/src/components/status-message/StatusMessage.tsx
Fixes issue where sign-in was importing the wrong validation icons from harmony
=> [C-3311] Fix validation icons in sign-in

packages/discovery-provider/src/solana/solana_client_manager.py, packages/discovery-provider/src/tasks/index_user_bank.py
Also fixes wallet that shows up in emails/notifs
to test...
=> [PAY-1976] Use receiver root wallet instead of ATA

packages/web/src/components/share-modal/ShareModal.tsx, packages/web/src/components/track/desktop/TrackListItem.tsx, packages/web/src/components/tracks-table/TracksTable.tsx
Don't show embed option for premium content until it is built out to support
Share premium content doesn't show embed
=> [PAY-2122] Gate embeds for premium content

packages/discovery-provider/nginx_conf/nginx.conf, protocol-dashboard/scripts/updateBuild.cjs
Fixes infinite loop in plugins health check when a plugin is unreachable:
1. `/plugins` route queries `/plugins/sla-auditor/health_check` route
2. However, the sla-auditor container doesn't have a route for `/health_check`, so Discovery falls back to hitting the `/plugins` block again, creating an infinite cycle
We may also want to consider having it be required for every plugin to implement a `/health_check` route.
Ran on stage discovery 1. The `/plugins` route now returns:
```
{
"notifications": {
"lastIndexedReactionRedisKey": "2023-11-02T00:47:32.621Z",
"healthy": true,
"poll": 500,
"dmNotificationDelay": 500,
"lastIndexedMessageRedisKey": "2023-11-02T00:47:32.621Z"
}
}
```
instead of:
```
{
"notifications": {
"lastIndexedReactionRedisKey": "2023-11-01T22:01:34.491Z",
"healthy": true, …
```
=> [PROTO-1386] Fix multiple sla-auditors in health check

packages/harmony/src/foundations/corner-radius/CornerRadius.stories.mdx
Adds corner-radius foundation docs
Was able to most of the coding in mdx which is pretty cool
=> [C-3179] Add corner-radius foundations doc

.circleci/src/workflows/release.yml
fixes relay release and adds mediorum and identity since they were left out
=> fix release for arm

packages/harmony/src/components/button/Button/Button.mdx, packages/harmony/src/components/layout/Box/Box.mdx, packages/harmony/src/components/layout/Flex/Flex.mdx, packages/harmony/src/components/layout/Flex/Flex.stories.tsx, packages/harmony/src/components/layout/Paper/Paper.stories.tsx, packages/harmony/src/components/layout/Paper/types.ts, packages/harmony/src/storybook/components/RelatedComponents.tsx
- Adds docs for Flex and Box
- Adds Paper to RelatedComponents
- Should we add Do's and Don'ts? Should they be code or visual examples?
- These docs are quite simple and short. Do we want more detail, or keep it simple?
- There weren't designs for these docs as they're dev only components, so very open to ideas/feedback
storybook
=> [C-3322, C-3324] Add Box and Flex docs to storybook

docs/docs/developers/log-in-with-audius.md, docs/i18n-disabled/en/docusaurus-plugin-content-docs/current/developers/log-in-with-audius.md, packages/web/src/pages/oauth-login-page/hooks.ts, packages/web/src/pages/oauth-login-page/utils.ts
Enforce https protocol in redirect_uri
=> Assert protocol in oauth redirect_uri

packages/web/src/components/actions-tab/ActionsTab.jsx, packages/web/src/components/actions-tab/ActionsTab.module.css, packages/web/src/components/card/desktop/Card.tsx, packages/web/src/components/card/desktop/CollectionArtCard.tsx, packages/web/src/components/table/components/OverflowMenuButton.tsx, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/styles.module.css
Vite svgr behaves slightly different so assigning a ref to an svg no longer works. This PR adds wrappers divs to fix the broken popups
Tested all known instances of popup, also combed through code for refs being applied to svgs
=> [INF-540] Fix popup location

packages/harmony/.storybook/global.css
Missed adding reset.css to global.css
=> Add reset.css to storybook global.css

packages/harmony/src/components/layout/Divider/Divider.mdx, packages/harmony/src/components/layout/Divider/Divider.stories.tsx, packages/harmony/src/components/layout/Divider/Divider.tsx, packages/harmony/src/storybook/components/RelatedComponents.tsx
=> [C-3323] Add Harmony Divider docs

packages/common/src/hooks/useAccountHasClaimableRewards.ts
Not sure why this was needed, but seems unnecessary now.
Local web stage.
=> Remove unnecessary hardcoded list of challenges

packages/mobile/src/components/challenge-rewards-drawer/AudioMatchingChallengeDrawerContent.tsx, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/AudioMatchingRewardsModalContent.tsx
Color is default, not subdued.
=> [PAY-2150] Make total audio claimed color default

packages/web/index.html
Add metapixel to index.html for web
=> Add meta pixel

packages/web/index.html
Wrong id was used before, sorry!
=> Update meta pixel id

packages/mobile/src/components/now-playing-drawer/PlayBar.tsx
Head kinda hurts, but finally fix now playing drawer's play bar layouts without using some screen width stuff. And fix PAY-2126.
Various real-world data
=> [PAY-2126] Fix now playing play bar layouts

packages/harmony/src/components/input/TextInput/TextInput.mdx, packages/harmony/src/components/input/TextInput/TextInput.module.css, packages/harmony/src/components/input/TextInput/TextInput.stories.tsx, packages/harmony/src/components/input/TextInput/TextInput.tsx, packages/harmony/src/components/input/TextInput/types.ts, packages/harmony/src/storybook/components/ComponentRules.tsx, packages/harmony/src/storybook/components/InformationBox.tsx
=> [C-3287] Add Harmony TextInput docs

packages/harmony/src/storybook/Welcome.stories.mdx, packages/harmony/src/storybook/theme/theme.ts
- Clinking sidebar logo links to harmony root
- Fixed typo
storybook
=> Fix harmony logo link and title

.circleci/src/commands/@mobile-commands.yml, .circleci/src/commands/@web-commands.yml
* Fix v$ issues in link
* Fix linux/win builds by installing jq if missing
* Fix link to pipeline URL
=> Fix small issues with client CI announcements

packages/harmony/src/storybook/Welcome.stories.mdx
Adds link to our internal contributing guide on notion
=> [C-3350] Add contributing guide

packages/embed/src/util/WebWorker.js, packages/web/src/services/WebWorker.js
No VITE_PUBLIC_URL in dev. Is there one in stage/prod?
Can update cover photo
=> Fix vite webworker basename issue

.circleci/src/commands/@mobile-commands.yml
NPM hoisting changes where react-native is installed. Adding back this step and swallowing errors in case react-native already exists at that location
=> Add back react-native symlink step in CI

.circleci/src/commands/@mobile-commands.yml, .circleci/src/commands/@web-commands.yml
=> Only announce prod client deploys

packages/harmony/README.md, packages/web/src/types/emotion.d.ts, packages/web/tsconfig.json, packages/web/vite.config.ts
Fixes emotion support in web after vite migration
Updates harmony readme to remind users to add support for css prop and harmony-theme
=> Fix emotion support in web

package.json, packages/harmony/src/components/button/BaseButton/BaseButton.tsx, packages/harmony/src/components/loading-spinner/LoadingSpinner.tsx
Fixes issue where loading animations triggered chromatic issues every time. the move is to ignore them: https://www.chromatic.com/docs/ignoring-elements/
Chromatic passes
=> Ignore animations in Chromatic

packages/harmony/src/components/button/PlainButton/PlainButton.mdx, packages/harmony/src/components/button/PlainButton/PlainButton.stories.tsx
Added PlainButton Docs
The Controls are having trouble loading so me may want to update to get rid of the ref forwarding
=> [C-3294] Add Harmony PlainButton docs

packages/harmony/rollup.config.mjs, packages/harmony/src/components/layout/Box/Box.tsx, packages/harmony/src/components/layout/Flex/Flex.tsx
Fixes issue where flex props where being attached to the dom nodes (uses isPropValid to filter this)
Fixes issue where harmony build was building-in various emotion deps
Improves Box prop-type pattern
Improves Box implementation using theme
=> Fix Flex prop leaking, Upgrade Box

mediorum/main.go
To make audius-d changes minimally intrusive, we'll just add another startup function separate from existing prod/stage/dev workflows.
CI, built locally and tested with audius-d deployment
=> [PROTO-1398] Add audius-d sandbox-compatible startup to mediorum

docs/docs/developers/sdk/Tracks.md
Just following the docs and came across this little type mismatch. Devotional is a genre not mood. 
=> Update docs for upload track mood

protocol-dashboard/src/components/MobileNav/MobileNav.tsx, protocol-dashboard/src/components/Nav/Nav.tsx, protocol-dashboard/src/utils/routes.ts
Fixes a regression I introduced on mobile when updating the react-router version.
Mobile can now tap through the Services and Governance tabs.
=> Fix protodash mobile nav services & governance

packages/web/src/components/summary-table/SummaryTable.tsx
Not sure why I couldn't figure out how to do this yesterday
Looks great `http://localhost:3001/payandearn` -> add funds
=> Fix icon color/layout in summary table

packages/mobile/src/screens/pay-and-earn-screen/PayAndEarnScreen.tsx, packages/web/src/app/web-player/WebPlayer.jsx, packages/web/src/components/nav/desktop/NavPopupMenu.tsx, packages/web/src/utils/route.ts
=> Rename /payandearn to /payments

packages/harmony/src/components/text/Text/Text.stories.tsx, packages/harmony/src/foundations/color/Color.mdx, packages/harmony/src/foundations/color/semantic.ts, packages/harmony/src/foundations/typography/Typography.mdx
Adds accent color to text and icons to fit with existing designs.
=> Add accent color to text and icons

packages/stems/src/components/Modal/ModalHeader.module.css, packages/web/src/components/ai-attribution-modal/AiAttributionModal.module.css, packages/web/src/components/ai-attribution-modal/AiAttributionModal.tsx, packages/web/src/components/summary-table/SummaryTable.tsx, packages/web/src/components/user-list-modal/components/UserListModal.module.css
Updates modal title and icon to be neutral-light-4, and to be uppercase.
Remove all the unecessary overrides from this.
=> Update modal title and icon colors

packages/web/src/components/table/Table.module.css, packages/web/src/components/tracks-table/TracksTable.module.css
small fix to remove specified background color
manually tested
=> [C-3337] Fix table section end styles

packages/web/src/pages/sign-on/components/desktop/MetaMaskModal.jsx, packages/web/src/pages/sign-on/components/desktop/MetaMaskModal.module.css
MetaMask sign up was not working in most cases because we did not have access to user's MetaMask account(s).
This PR adds a call to request access to the user's MetaMask account(s).
Tested against prod.
=> Fix MetaMask not working C-3386

packages/discovery-provider/src/tasks/entity_manager/entities/user.py, packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
Block developer apps from user creation.
Tested on sandbox with a developer app.
=> Block developer app from user creation

packages/web/src/pages/sign-up-page/SignUpPage.module.css, packages/web/src/pages/sign-up-page/SignUpPage.tsx
Fixes this issue by wrapping the content in a <Paper>:
local web
=> Fix background and spacing for signup container

packages/web/src/pages/sign-up-page/components/AccountHeader.tsx, packages/web/src/pages/sign-up-page/components/FollowArtistTile.tsx, packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
Updated SelectArtistsPage to handle mobile web view. Small updates to account header and FollowArtistTile as well
=> [C-3365] Update SelectArtistsPage to handle mobile web view

packages/common/src/hooks/purchaseContent/constants.ts, packages/common/src/hooks/usePurchaseMethod.ts, packages/mobile/src/components/add-funds-drawer/AddFundsDrawer.tsx, packages/web/src/components/add-funds-modal/AddFundsModal.tsx
Forgot to commit these changes before merging the last PR, whoops
=> Cleanup for PR #6734 (mobile purchase flow)

packages/mobile/src/components/payment-method/PaymentMethod.tsx
Button doesn't render on mobile
=> [PAY-2186] Hide mobile payment method options

packages/common/src/services/remote-config/defaults.ts, packages/mobile/src/components/premium-track-purchase-drawer/AudioMatchSection.tsx, packages/mobile/src/components/premium-track-purchase-drawer/PayExtraFormSection.tsx, packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
Make pay extra pills match design on mobile.
Note: couldn't figure out how to get pills to be same width.
=> [PAY-2189] Mobile pay extra pills on single row

packages/mobile/src/components/premium-track-purchase-drawer/PurchaseSummaryTable.tsx, packages/mobile/src/components/summary-table/SummaryTable.tsx
Mimics web
Tested on iOS and Android, though Android doesn't animate grow even though I added the UIManager thing (even after testing on device)
=> [PAY-2160] Make total summary collapsible

packages/web/src/components/usdc-balance-fetcher/USDCBalanceFetcher.tsx
Received a PR comment right after auto-merge went in on https://github.com/AudiusProject/audius-protocol/pull/6761
=> Return null in USDCBalanceFetcher

packages/embed/index.html
Some (new) dependency expects a window===global. Tried a few vite options, but none of those seemed to work from
https://github.com/vitejs/vite/discussions/5912#discussioncomment-5569850
Pushed stage build locally
=> Fix embed build

packages/harmony/src/assets/icons/Metamask.svg
=> Try to fix Turbo cache?

packages/mobile/metro.config.js, packages/mobile/package.json, packages/mobile/src/app/ThemeProvider.tsx, packages/mobile/src/types/emotion.d.ts
Add the theme provider and the declaration file for the type
logged out some colors from the theme
=> [C-3390] Add Harmony ThemeProvider and theme to mobile

packages/mobile/src/screens/profile-screen/ProfileTabs/RepostsTab.tsx, packages/mobile/src/screens/profile-screen/ProfileTabs/TracksTab.tsx
Add pagination to reposts screen that mimics the pagination from the tracks screen
logged out some pagination calls
=> [C-3351] Add pagination to mobile profile reposts screen

packages/common/src/store/purchase-content/sagas.ts
=> Fix web lint

packages/web/src/components/animated-button/AnimatedIconButton.tsx
This issue popped up since Nov 18 and has been getting thousands of hits per day since on Sentry. I have not been able to repro locally.
Buttons work on local web
=> [PAY-2214] Change require to import in AnimatedIconbutton

packages/web/src/components/usdc-manual-transfer/USDCManualTransfer.tsx
=> [PAY-2210] Change crpyto transfer modal button to secondary

.circleci/config.yml
=> Enable embed ci workflow on main

packages/harmony/src/components/button/BaseButton/BaseButton.tsx
Request from design to change harmony buttons so they don't grow if they are full-width. Keep the hover color change as-is.
https://github.com/AudiusProject/audius-protocol/assets/3893871/86fe0183-51cc-48cb-bf0b-c38e58158ee0
=> [PAY-2212] Don't grow fullWidth buttons

solana-programs/payment-router/README.md, solana-programs/payment-router/tests/payment-router.ts
=> Update payment router readme

.circleci/src/workflows/discovery.yml, .circleci/src/workflows/release.yml
adds arm image to uptime, it's the only image being emulated with local audius-d
N/A
=> add arm builds for uptime

packages/discovery-provider/src/queries/get_underground_trending.py, packages/discovery-provider/src/tasks/generate_trending.py
Use aggregate tables instead of counting from scratch.
next steps (in future pr):
* cheaper karma calculation
* cheaper time window'd save + repost calculation
=> trending: use aggregate tables

packages/web/src/components/add-funds-modal/AddFundsModal.tsx
Close modal correctly. Resetting the page already happens on onClosed.
Stage. Modal closes now.
=> [PAY-2213] Fix closing Add Funds modal

packages/embed/src/components/collection/CollectionPlayerCard.jsx, packages/embed/workers-site/package-lock.json
PausedPopover styling in the last PR broke the playlist version of it. `fillContainer` is no longer needed to make it better.
Lockfile changes are necessary for the wrangler set up -- deployed to staging from local to test.
```
npm run embed:prod
```
=> Fix embed player playlist styles

packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx
Keep track of the list of users chosen to be followed so we can properly check against it later. If we rely on the `selectSuggestedFollowsUsers` selector, it will filter out successfully followed artists and we lose context.
See https://github.com/AudiusProject/audius-protocol/pull/6529 for related fix in web
mobile sim
=> [C-2591] Fix Follow All button on mobile

packages/web/src/app/App.tsx
Fixes issue where /signon links displayed signin page. great catch @sddioulde
=> Fix routing for legacy sign-on

packages/discovery-provider/src/queries/get_remixes_of.py, packages/web/src/pages/upload-page/fields/RemixSettingsField/RemixSettingsField.tsx, packages/web/src/pages/upload-page/fields/RemixSettingsField/RemixSettingsMenuFields.tsx
=> Return remixes for premium tracks

packages/mobile/src/screens/edit-track-screen/screens/RemixSettingsScreen.tsx, packages/web/src/components/remix-settings-modal/RemixSettingsModal.tsx
and also fix it on track edit modal
=> Fix mobile premium track remix visibility

packages/harmony/src/components/icon/Icon.tsx, packages/harmony/src/foundations/theme/theme.ts, packages/web/src/pages/sign-up-page/components/NavHeader.tsx
A couple small tweaks to icons for usability
Locally 👀
=> [C-3385] Harmony icon component tweaks

packages/web/src/app/App.tsx, packages/web/src/hooks/useMedia.ts, packages/web/src/pages/oauth-login-page/index.ts, packages/web/src/pages/sign-on-page/AudiusValues.tsx, packages/web/src/pages/sign-on-page/SignOnPage.tsx, packages/web/src/pages/sign-up-page/SignUpPage.tsx, packages/web/src/pages/sign-up-page/components/layout.tsx, packages/web/src/pages/sign-up-page/pages/CreateLoginDetails.tsx, packages/web/src/pages/sign-up-page/pages/CreatePasswordPage.tsx, packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx, packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx, packages/web/src/pages/sign-up-page/pages/ReviewHandlePage.tsx, packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx, packages/web/src/pages/sign-up-page/pages/SelectGenrePage.tsx, packages/web/src/pages/sign-up-page/utils/RouteContext.tsx, packages/web/src/pages/sign-up-page/utils/determineAllowedRoutes.ts
Improves responsive ui
Adds transitions (still need to figure out forward vs backward transitions)
https://github.com/AudiusProject/audius-protocol/assets/8230000/690d275b-de39-483b-8bcc-98674df06be7
https://github.com/AudiusProject/audius-protocol/assets/8230000/804ced6d-7506-4770-a2ef-a9989340b9a2
=> [C-3459] Improve sign-up responsiveness

packages/discovery-provider/src/tasks/index_user_bank.py, packages/discovery-provider/src/tasks/publish_scheduled_releases.py
This PR is required before https://github.com/AudiusProject/audius-protocol/pull/6846 can be merged
Ran the following with just these changes and also ran the following when rebased on top of https://github.com/AudiusProject/audius-protocol/pull/6846
```
audius-cmd create-user freddie_mercury
audius-cmd create-user bob
audius-cmd mint-tokens --mint usdc --from freddie_mercury 200000000
audius-cmd upload-track --from bob --title "Bohemian Bob" --price 100
audius-cmd purchase-track 934314488 --from freddie_mercury
```
=> [PAY-2237] Allow for purchaser_user_id in memo

packages/web/src/common/store/pages/signon/sagas.js
Before: Profile image and cover photo did not upload if you signed up with social media on mobile
After: Fixed
Signed up for staging account w/ my IG
=> [Mobile] Fix profile + cover pic not uploading upon social sign up [C-3466]

.circleci/src/commands/@mobile-commands.yml, .circleci/src/workflows/mobile.yml
* `sudo apt update` before installing python to resolve "Failed to fetch" error
* Add `slack-secrets` context to mobile workflows so slack announcements work
Will cherry pick onto release branch!
=> [C-3467] Fix python install in mobile ci

packages/libs/src/api/Rewards.ts, packages/libs/src/constants.ts, packages/libs/src/services/solana/SolanaUtils.ts, packages/libs/src/services/solana/SolanaWeb3Manager.ts
Rename `DECMIALS` to `DECIMALS`.
Local web stage functions normally.
=> Fix typo in libs solana decimals constants

packages/discovery-provider/ddl/migrations/0041_repair_indexes.sql
Add migration to reindex any corrupted indexes found by `amcheck`
prod discovery 3 with https://github.com/AudiusProject/audius-docker-compose/pull/413
=> Reindex corrupted discovery indexes

packages/discovery-provider/integration_tests/conftest.py
Uses pg_migrate.sh to create a template database, and each individual tests creates a new database from the template.
This makes tests a lot faster and reduces log output from repeated migrations.
```
audius-compose test run discovery-provider
```
=> PROTO-1474: Discovery uses db tempalte for integration tests

packages/mobile/src/screens/signon/ProfileAuto.tsx, packages/web/src/common/store/pages/signon/sagas.js
Before: IG and Twitter accounts were not being properly associated with the Audius users who signed up with them, see this thread: https://audius-internal.slack.com/archives/C03HJL1GGNP/p1700644383014779.
After: Fixed
Problem: Data was being passed around incorrectly on the frontend, see PR. Also image upload was failing which failed the sign up altogether before we could call `associateAccount`, fixed here: https://github.com/AudiusProject/audius-protocol/pull/6850. 
=> [Mobile] [C-3413] Fix verified sign up on mobile via Twitter/IG

packages/discovery-provider/Dockerfile.dev, packages/discovery-provider/Dockerfile.prod
=> fix openresty version

packages/web/src/common/store/pages/collection/sagas.js
Going to an invalid collection route was not 404ing, just showing a broken empty tile.
* Route to 404 page when fetching collection fails, using the same pattern as the track page
=> [C-3479] 404 on invalid collection url

packages/mobile/src/components/add-funds-drawer/AddFundsDrawer.tsx, packages/mobile/src/components/payment-method/PaymentMethod.tsx, packages/mobile/src/components/summary-table/SummaryTable.tsx, packages/web/src/components/add-funds/AddFunds.tsx, packages/web/src/components/payment-method/PaymentMethod.tsx, packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx, packages/web/src/components/summary-table/SummaryTable.tsx
Use similar pattern as mobile in web summary table.
Make a PaymentMethod component used both by purchase flow and add funds flow.
local web vs stage
local mobile native vs stage
=> [PAY-2194] Update summary tables

packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/antiAbuse.ts
On every relay request AAO will be asked if a user has the correct permissions for the operation. On a user create AAO returns a 500. This is because AAO asks identity if the user exists. Identity then goes to ask a discovery node if the user exists. Discovery (obviously) doesn't have this user yet as we're about to kick off the transaction to create them. This bubbles up in the form of a 400 for identity which AAO then converts to a 500 for some reason. Since relay understands from the 500 that AAO is unreachable it will then abort the request because we shouldn't let writes go through simply because AAO is considered down.
This PR drills down into the ABI of the sent request and determines specifically if the request is of the `UserCreate` type. If it is then the AAO check is bypassed …
=> PROTO-1364: fix relay heavy load

packages/mobile/.storybook/storybook.requires.ts, packages/mobile/src/harmony-native/components/Avatar/Avatar.stories.tsx, packages/mobile/src/harmony-native/components/Avatar/Avatar.tsx, packages/mobile/src/harmony-native/components/index.ts
Add Avatar component and stories
Works in native storybook
=> [C-3423] Add Avatar component to native harmony

packages/mobile/src/screens/feed-screen/FeedScreen.tsx, packages/web/src/pages/feed-page/components/desktop/FeedPageContent.tsx
Previous pr had some test code that got merged by accident
=> Remove extraneous icon imports

packages/harmony/.svgrrc.js, packages/mobile/.svgrrc.js, svgr-template.js
Fixes issue where icon sizes were misconfigured
Also distinguishing between fill and fillColor since they were overriding eachother
=> Address mobile icon issues

packages/commands/src/purchase-track.mjs, packages/common/src/services/audius-backend/solana.ts, packages/common/src/store/purchase-content/sagas.ts, packages/libs/src/services/solana/SolanaWeb3Manager.ts
Authored by @raymondjacobson 
Add `purchaserUserId` to the memo of the purchase transaction.
Not tested..
=> Add memo for purchaser user id

packages/web/src/app/App.tsx, packages/web/src/utils/route.ts
Note that this restricted handles list pulls from ORDERED_ROUTES, so this will also prevent new handles with these names from being created.
=> Add sign in route aliases C-3503

packages/common/src/services/audius-backend/solana.ts, packages/common/src/store/buy-usdc/sagas.ts, packages/common/src/store/purchase-content/sagas.ts
PAY-2241
Adds USDC to a user's user bank using Coinflow.
Tested by setting default amount to 1 and running against prod
=> [PAY-2241][PAY-2259] Add Funds via Coinflow

packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/antiAbuse.ts
Ensures the instruction to be relayed is not deactivation request before rejecting it if the user is blocked from relay.
#6917 but for DN relay
=> [PAY-2263] Always Allow Deactivations on DN Relay

packages/common/src/store/purchase-content/sagas.ts
Fixes bug where the _needed_ balance was being purchased rather than the full price.
Also made some types more clear to avoid 100x prices
=> Fix prices add types for purchases

mediorum/.version.json, packages/discovery-provider/.version.json
=> Bump version to 0.6.0

packages/web/src/pages/pay-and-earn-page/components/NoTransactionsContent.tsx, packages/web/src/pages/pay-and-earn-page/components/WithdrawalsTab.tsx
Change the CTA on withdrawals tab empty state to match design.
local web prod
https://github.com/AudiusProject/audius-protocol/assets/3893871/8da9f692-37e2-45a5-ba7f-5744e0e26b78
=> Remove CTA on withdrawals table empty state

packages/mobile/.storybook/storybook.requires.ts, packages/mobile/src/harmony-native/components/Button/FollowButton/FollowButton.stories.tsx, packages/mobile/src/harmony-native/components/Button/FollowButton/FollowButton.tsx, packages/mobile/src/harmony-native/components/Button/FollowButton/types.ts
Added simple follow button. No animations were really needed for this, but can be added if we want parity with other buttons later
Looks good in native storybook
=> [C-3429] Add FollowButton to native harmony

packages/common/src/hooks/useCoinflowAdapter.ts
Skip preflight in coinflow purchase 
=> [PAY-2271] Skip preflight in coinflow checkout

packages/discovery-provider/ddl/migrations/0043_add_dashboard_wallet_users.sql
Maps wallet addresses to Audius user ids; will be used to associate Audius profile with service providers
=> Add dashboard wallet users table C-3497

packages/mobile/src/screens/feature-flag-override-screen/FeatureFlagOverrideScreen.tsx, packages/mobile/src/screens/feature-flag-override-screen/fuzzySearch.ts
Not sure when this was introduced, but good to fix :)
=> Fix feature flag lint issue

packages/web/src/pages/sign-on/components/mobile/InitialPage.tsx, packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
Fixes issues with legacy sign-in.
Really not sure how it got to be this way... harmony to the rescue on the fix though!
=> [C-3509] Fix sign-in legacy styles

packages/common/src/store/purchase-content/sagas.ts
Was not being passed through
Completed pay extra purchase
=> [PAY-2273] Fix payExtra for coinflow and stripe

packages/mobile/.storybook/storybook.requires.ts, packages/mobile/src/harmony-native/components/CompletionCheck/CompletionCheck.stories.tsx, packages/mobile/src/harmony-native/components/CompletionCheck/CompletionCheck.tsx
Add CompletionCheck to native harmony
=> [C-3435] Add CompletionCheck to native harmony

packages/common/src/store/purchase-content/sagas.ts
Pay extra is in dollars, not cents
=> Extra amount is in dollars

packages/common/src/store/purchase-content/sagas.ts
This reverts commit c4c8b6b42ae2056d40a16e7eeb4626bea921f056.
=> Revert "Extra amount is in dollars (#6949)"

packages/common/src/services/audius-backend/solana.ts
=> Fix pay extra

packages/web/src/components/link/Link.module.css, packages/web/src/components/usdc-purchase-details-modal/components/DetailSection.tsx, packages/web/src/components/usdc-purchase-details-modal/components/PurchaseModalContent.tsx, packages/web/src/components/usdc-purchase-details-modal/components/SaleModalContent.tsx
=> [PAY-2224] Add ExploreTransaction callout to sale/purchase details

packages/mobile/src/screens/sign-on-screen/screens/SelectGenreScreen.tsx
Select genres page had extreme lagginess when selecting pills (exacerbated when clicking multiple quickly).
The main change with this PR is memoizing the `SelectablePill` and making all its props not change on rerender (and letting SelectablePill manage it's selected state)
local iOS simulator w/ built in performance viewer
=> fix: Fix native select genres pill performance issue

packages/discovery-provider/src/app.py
Faster payment router indexer
Will follow on stage and test one discovery node on prod afterwards
=> [PAY-2286] Increase payment router indexer frequency

packages/mobile/android/app/build.gradle, packages/mobile/ios/AudiusReactNative/Info.plist
Some new native code coming in hot this week. This fixes issue with code-push on stage.
=> Bump mobile versions for full release

packages/common/src/hooks/purchaseContent/usePurchaseContentFormConfiguration.ts
Tested locally against prod, stripe modal comes up
=> Default to Stripe

packages/web/src/components/banner/TermsOfServiceUpdateBanner.tsx
In order to re-show the ToS, we need to change the key
Tested on RC, realized this was necessary
=> Update key for tos banner version

packages/web/src/components/animated-button/AnimatedIconButton.tsx, packages/web/src/components/bottom-bar/buttons/ExploreButton.tsx, packages/web/src/components/bottom-bar/buttons/FeedButton.tsx, packages/web/src/components/bottom-bar/buttons/LibraryButton.tsx, packages/web/src/components/bottom-bar/buttons/ProfileButton.tsx, packages/web/src/components/bottom-bar/buttons/TrendingButton.tsx, packages/web/src/components/play-bar/repeat-button/RepeatButtonProvider.tsx, packages/web/src/components/play-bar/shuffle-button/ShuffleButtonProvider.tsx
Fixes vite analysis warnings locally, and prod level sentry issues
=> [C-3519] Fix async absolute lottie imports

packages/commands/package.json, packages/embed/package.json, packages/es-indexer/package.json, packages/harmony/package.json, packages/identity-service/package.json, packages/libs/src/sdk/services/EntityManager/EntityManager.ts, packages/probers/package.json
* Cast chainId to number to fix error being thrown
* Add `private: true` to packages we don't want to publish
* Note: making harmony private for now until we are ready to publish it
=> Fix sdk write w/ vite and fix npm publish

packages/mobile/src/components/add-to-collection-drawer/AddToCollectionDrawer.tsx, packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx, packages/mobile/src/components/track-list/TrackListItem.tsx, packages/web/src/components/now-playing/NowPlaying.tsx
=> Lint fixes for edit album

packages/spl/package.json
* Bump version
* Update paths so that `dist` is included in npm tarball
=> Publish @audius/spl

dev-tools/compose/docker-compose.discovery.prod.yml, dev-tools/compose/docker-compose.test.yml, dev-tools/startup/discovery-provider.sh, packages/discovery-provider/plugins/pedalboard/docker/startup.sh, packages/es-indexer/README.md
Set env variables for es-indexer in dev.
Without, es-indexer would constantly reboot.
=> fix es-indexer for local dev

packages/discovery-provider/plugins/pedalboard/packages/eslint-config-custom/package.json, packages/eslint-config-audius/package.json, packages/libs/package.json
* Bump sdk to 3.0.22 (was published yesterday)
* Fix some things with the "Publish npm packages" workflow (still needs work, going to tackle in https://linear.app/audius/project/better-release-notes-and-changelogs-b26693a83ace/INF
=> Publish sdk and fix publish flow

packages/discovery-provider/integration_tests/tasks/entity_manager/test_dashboard_wallet_user_entity_manager.py, packages/discovery-provider/integration_tests/tasks/test_index_payment_router.py, packages/discovery-provider/integration_tests/utils.py, packages/discovery-provider/src/models/dashboard_wallet_user/dashboard_wallet_user.py, packages/discovery-provider/src/tasks/entity_manager/entities/dashboard_wallet_user.py, packages/discovery-provider/src/tasks/entity_manager/entities/developer_app.py, packages/discovery-provider/src/tasks/entity_manager/entity_manager.py, packages/discovery-provider/src/tasks/entity_manager/utils.py
Adds Dashboard Wallet Users entity to EM and corresponding actions.
Integration tests, will fix issues tomorrow since I can't test reliably on this plane :(
=> Index EM transactions for dashboard wallet users C-3529

packages/discovery-provider/src/api/v1/api.py, packages/discovery-provider/src/api/v1/dashboard_wallet_users.py, packages/discovery-provider/src/api/v1/helpers.py, packages/discovery-provider/src/api/v1/models/dashboard_wallet_user.py, packages/discovery-provider/src/queries/get_dashboard_wallet_users.py
Add route for getting dashboard wallet users by ID (bulk)
=> [Discovery] Add bulk get dashboard wallet users to Discovery Api [C-3532]

packages/libs/src/sdk/api/dashboard-wallet-users/DashboardWalletUsersApi.ts, packages/libs/src/sdk/api/dashboard-wallet-users/types.ts, packages/libs/src/sdk/sdk.ts, packages/libs/src/sdk/services/EntityManager/types.ts, packages/libs/src/sdk/utils/ethAddress.ts
Add SDK APIs for connecting and disconnecting Audius user id from wallet on protocol dashboard
=> [SDK] Add dashboard wallet users API to SDK [C-3530]

packages/discovery-provider/src/api/v1/dashboard_wallet_users.py
=> [Discovery] Fix response marshalling - Dashboard Wallet Users API

packages/discovery-provider/src/api/v1/dashboard_wallet_users.py
=> [Discovery] Discovery lint fix

.circleci/src/jobs/@ddex-jobs.yml, packages/ddex/README.md, packages/ddex/package.json, packages/ddex/scripts/docker-entrypoint.sh, packages/ddex/src/pages/DDEX.tsx
Fix SDK linking so app uses latest SDK fixes for uploading tracks.
Add simple UI to view upload progress and details.
Collapsed done:
Expanded done:
Collapsed in progress:
Expanded in progress:
Ran locally. Made sure app built.
=> Simple upload UI

packages/mobile/src/components/coinflow-onramp-drawer/CoinflowOnrampDrawer.tsx
=> Add chargebackProtectionData

packages/discovery-provider/src/app.py
=> Disable scheduled releases job

packages/libs/src/sdk/api/dashboard-wallet-users/DashboardWalletUsersApi.ts
=> [SDK] Have DashboardWalletUsers extend generated dashboard wallet users API

packages/harmony/src/components/layout/Divider/Divider.tsx, packages/mobile/.storybook/storybook.requires.ts, packages/mobile/src/harmony-native/components/layout/Divider/Divider.stories.tsx, packages/mobile/src/harmony-native/components/layout/Divider/Divider.tsx, packages/mobile/src/harmony-native/components/layout/Divider/types.ts
Added the divider component to native harmony
=> [C-3434] Add Divider to native harmony

packages/libs/src/sdk/utils/ethAddress.ts
=> [SDK] Fix validate ETH address util

packages/mobile/src/components/core/Button.tsx
=> Fix button color darkening

packages/web/src/components/upload/UploadChip.tsx
_Note: This is broken on RC, so planning to cherry-pick onto release_
Before:
After:
local web
=> [C-3566] UploadChip - fix text wrapping

packages/harmony/src/components/text-link/TextLink.tsx, packages/harmony/src/components/text-link/types.ts, packages/harmony/src/foundations/color/semantic.ts, packages/web/src/components/link/Link.module.css, packages/web/src/components/usdc-purchase-details-modal/components/PurchaseModalContent.tsx, packages/web/src/components/usdc-purchase-details-modal/components/SaleModalContent.tsx
Fix explore tx link callouts, replacing component with harmony version.
Current implementation caused a few problems.
Locally
=> [PAY-2320] Fix explore tx link callouts

packages/stems/src/components/Modal/ModalContentPages.module.css, packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.module.css, packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
Fix placement of footer button while purchase is in progress
=> [PAY-2281] Fix mobile web purchase modal footer placement

packages/mobile/src/components/profile-list/ProfileCardSkeleton.tsx, packages/mobile/src/screens/profile-screen/ProfileCoverPhoto.tsx, packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx, packages/mobile/src/screens/profile-screen/ProfileInfo.tsx, packages/mobile/src/screens/profile-screen/ProfilePicture.tsx
Improves profile screen header scrollable area by over 50%
=> [C-3490] Improve profile touch targets

packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx, packages/web/src/components/add-funds-modal/AddFundsModal.tsx, packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
* If stage is start, allow modal to close. This means something crashed trying to open the onramp.
* Close add funds modal after purchase is successful
Locally vs. prod environment.
Will test stripe again after merge.
=> [PAY-2289] Fix premium/usdc modal close issues

packages/web/scripts/workers-site/index.js
Fix SSR XSS issue caused by lack of sanitization on the <h1> tag
release-candidate
=> Sanitize h1

package-lock.json
=> Bust turbo web cache

package-lock.json
Fixes issue where we didnt have esbuild dependencies for intel, on arm... Weird how the lock files are not including all archs...
=> Fix esbuild on intel

package-lock.json
In an attempt to fix web build, i accidently removed a harmony dep needed for building
=> Fix harmony build

packages/discovery-provider/plugins/notifications/jest.config.js, packages/discovery-provider/plugins/notifications/package.json
=> Actually fix discovery notif tests

.circleci/src/jobs/commit-audius-docker-compose-and-notify.yml, package-lock.json, packages/ddex/package.json
Tracks changes to packages/ddex-frontend in Slack notifications, and install the UUID package, which was breaking building the ddex backend.
`audius-compose push --prod ddex` doesn't fail anymore.
=> Track ddex frontend changes and install uuid

package-lock.json, packages/mobile/ios/Podfile.lock, packages/mobile/patches/react-native+0.73.1.patch
https://github.com/boostorg/boost/issues/843#issuecomment-1872943124
=> Fix ios build by patching boost

packages/mobile/android/app/build.gradle, packages/mobile/android/app/src/main/java/co/audius/app/MainApplication.kt, packages/mobile/patches/react-native+0.73.1.patch, packages/mobile/src/components/lineup/Lineup.tsx, packages/mobile/src/screens/app-drawer-screen/AppDrawerScreen.tsx
Fixes issues found during 1.5.59 release qa
=> Fix issues found in 1.5.59 release

packages/mobile/.storybook/storybook.requires.ts, packages/mobile/src/harmony-native/components/Button/BaseButton/BaseButton.tsx, packages/mobile/src/harmony-native/components/Button/PlainButton/PlainButton.stories.tsx, packages/mobile/src/harmony-native/components/Button/PlainButton/PlainButton.tsx, packages/mobile/src/harmony-native/components/Button/types.ts
Add PlainButton component to native harmony
Looks good in native storybook
=> [C-3426] Add PlainButton to native harmony

packages/mobile/src/hooks/useSetTrackAvailabilityFields.ts
=> Fix track-availability hook dependencies

packages/probers/cypress/e2e/flaky-test-jail.md, packages/probers/cypress/e2e/signUp.cy.ts
Gonna address this test later this week, for now just getting things 🟢
=> [C-3593] signUp straight to jail

packages/mobile/.storybook/storybook.requires.ts, packages/mobile/src/harmony-native/components/Button/SocialButton/SocialButton.stories.tsx, packages/mobile/src/harmony-native/components/Button/SocialButton/SocialButton.tsx, packages/mobile/src/harmony-native/components/Button/SocialButton/types.ts
Added SocialButton component to native harmony
NOTE: The gradient for the instagram button was not done perfectly and does not animate like the other ones
Looks good in native storybook
=> [C-3430] Add SocialButton to native harmony

packages/harmony/src/hooks/useControlled.ts, packages/mobile/.storybook/storybook.requires.ts, packages/mobile/src/app/index.ts, packages/mobile/src/harmony-native/components/Button/IconButton/IconButton.tsx, packages/mobile/src/harmony-native/components/input/PasswordInput/PasswordInput.stories.tsx, packages/mobile/src/harmony-native/components/input/PasswordInput/PasswordInput.tsx, packages/mobile/src/harmony-native/components/input/PasswordInput/types.ts, packages/mobile/src/harmony-native/components/input/TextInput/TextInput.tsx, packages/mobile/src/harmony-native/hooks/useControlled.ts
Adds harmony-native password input
Added story
=> [C-3433] Add harmony-native password input

packages/common/src/store/ui/share-modal/types.ts, packages/mobile/src/components/share-drawer/ShareToStorySticker.tsx, packages/mobile/src/components/share-drawer/useShareToStory.tsx, packages/mobile/src/components/share-drawer/utils.ts, packages/stems/src/components/ProgressBar/ProgressBar.module.css, packages/web/src/components/share-modal/utils.ts, packages/web/src/pages/upload-page/components/ShareBanner.tsx, packages/web/src/pages/upload-page/pages/FinishPage.tsx
Fixes upload share-banner options to include sharing track, playlist, and album. This was dropped with the redesign
=> [C-3595 C-3574] Fix Upload share-banner share options

packages/trpc-server/src/db.ts
Accidentally included these changes in my last PR
trpc build and web build passing now
=> Revert unintended trpc changes

protocol-dashboard/src/components/AppBar/AppBar.tsx, protocol-dashboard/src/components/ConnectAudiusProfileModal/ConnectAudiusProfileModal.module.css, protocol-dashboard/src/components/ConnectAudiusProfileModal/ConnectAudiusProfileModal.tsx, protocol-dashboard/src/components/ManageService/ManageService.module.css, protocol-dashboard/src/components/ManageService/ManageService.tsx, protocol-dashboard/src/hooks/useConnectAudiusProfile.ts
Looks big, but a lot of it is just moving things around.
=> [Protocol Dashboard] Add Connect Audius Profile modal before opening OAuth popup [C-3602]

packages/mobile/src/screens/sign-on-screen/components/SignUpFlowTwitterAuth.tsx
- Makes the popup show up even if the authToken isnt there (same as current sign up)
- Tweak the token fetching logic a bit to avoid extra API calls due to local dev rebundling. Found a bug with it not getting API tokens correctly on local rebundles
local iOS stage and prod (works on prod app)
=> [C-3588] Show twitter popup on staging

packages/discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py, packages/discovery-provider/src/api/v1/models/tracks.py, packages/web/src/pages/upload-page/validation.ts
=> Fix lossless fields zod validation

packages/common/src/messages/sign-on/pages.ts, packages/mobile/src/screens/sign-on-screen/components/HandleField.tsx, packages/mobile/src/screens/sign-on-screen/screens/PickHandleScreen.tsx, packages/mobile/src/screens/sign-on-screen/screens/ReviewHandleScreen.tsx, packages/web/src/pages/sign-up-page/components/HandleField.tsx
- Port over the handle field positive validation code to native.
- note: still needs to be harmonized, right now the icon is a bit off and the helper text was just added on top
=> [C-3590] Add handle field positive validation to native

packages/mobile/src/harmony-native/components/Button/BaseButton/BaseButton.tsx
Update native harmony BaseButton to not scale when pressed when full width like the web one
=> Update native harmony BaseButton to not scale when full width

packages/web/src/pages/sign-up-page/components/AccountHeader.tsx, packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
Update the state immediately update change to preserve the images and display name when the user goes back and forth from the handle page
Tested locally
=> [C-3612] Update FinishProfilePage to preserve changes if the user goes back to the handle page

packages/mobile/src/screens/profile-screen/ProfileTabs/AlbumsTab.tsx, packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts, packages/web/src/common/store/cache/collections/commonSagas.js, packages/web/src/components/upload/UploadChip.tsx, packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
Was calling the wrong onClick handler when feature flag is off.
local web
=> [C-3618] Fix callback on upload chip

package-lock.json, packages/mobile/ios/Podfile.lock, packages/mobile/package.json, packages/mobile/src/components/audio/AudioPlayer.tsx, packages/mobile/src/components/audio/RepeatListener.tsx, packages/mobile/src/components/scrubber/usePosition.ts, packages/mobile/src/screens/app-drawer-screen/AppDrawerScreen.tsx, packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/selectArtistPreviewContext.tsx
https://rntp.dev/docs/v4-migration#general-deprecations
Player controls
=> Upgrade react-native-track-player

packages/mobile/android/app/build.gradle, packages/mobile/ios/AudiusReactNative/Info.plist
=> Increment mobile versions

packages/discovery-provider/integration_tests/tasks/test_index_user_bank.py, packages/discovery-provider/src/queries/health_check.py
Add misc volume checks
Stage dn5
=> Add checks for tips/purchases/audio/usdc tx history

packages/web/src/common/store/pages/signon/sagas.js
Reverting so we can get some broken users to test with 😅 
Reverts AudiusProject/audius-protocol#7180
=> Revert "Revert "[Mobile] Fix profile + cover pic not uploading upon social sign up [C-3466]"

packages/web/src/common/store/pages/signon/sagas.js
Re-Re-Revert to get back to the fixed & working state after we have users to test with 🙃 
Reverts AudiusProject/audius-protocol#7188
=> Revert "Revert "Revert "[Mobile] Fix profile + cover pic not uploading upon social sign up [C-3466]""

packages/libs/src/api/Users.ts, packages/web/src/common/store/pages/signon/sagas.js
Fixes users that signed up on mobile with a profile photo and ended up in a broken state.
Tested on iOS sim against staging.
Co-authored by @sddioulde et al.
=> repairEntityManagerUserV2

packages/mobile/android/app/build.gradle, packages/mobile/ios/AudiusReactNative/Info.plist
=> Prepare for full app release 1.1.81

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/identity-service/src/notifications/emails/otp.js, packages/identity-service/src/routes/authentication.js, packages/identity-service/src/utils/otp.js, packages/identity-service/test/authenticationTest.js, packages/libs/src/api/Account.ts, packages/libs/src/services/hedgehog/Hedgehog.ts, packages/libs/src/services/identity/IdentityService.ts, packages/mobile/src/components/track-list/TrackListItem.tsx, packages/mobile/src/screens/signon/SignOn.tsx, packages/web/src/common/store/pages/signon/actions.ts, packages/web/src/common/store/pages/signon/reducer.js, packages/web/src/common/store/pages/signon/sagas.js, packages/web/src/common/store/pages/signon/selectors.ts, packages/web/src/common/store/pages/signon/types.ts, packages/web/src/pages/oauth-login-page/utils.ts, packages/web/src/pages/sign-on/SignOnProvider.tsx, packages/web/src/pages/sign-on/components/desktop/SignInPage.module.css, packages/web/src/pages/sign-on/components/desktop/SignInPage.tsx, packages/web/src/pages/sign-on/components/desktop/SignOnPage.tsx, packages/web/src/pages/sign-on/components/mobile/InitialPage.module.css, packages/web/src/pages/sign-on/components/mobile/InitialPage.tsx, packages/web/src/pages/sign-on/components/mobile/SignOnPage.tsx
Add email otp support
Web, mobile web & mobile vs. local stack:
1. Sign up still works
2. Sign in with wrong password fails with Invalid Credentials
3. Sign in with right password asks for otp
4. Wrong otp fails with invalid credentials
5. Correct otp logs users in
=> [PROTO-1599] Add OTP support

packages/mobile/android/app/build.gradle, packages/mobile/ios/AudiusReactNative/Info.plist
=> Bump app builds

packages/identity-service/src/routes/authentication.js
=> Add sendgrid param

packages/common/src/models/Analytics.ts, packages/web/src/common/store/pages/signon/sagas.js
Confirmed signup works against stage
=> Fix repair signup

packages/commands/src/upload-track.mjs
=> Fix audius-cmd test

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/mobile/src/screens/sign-on-screen/components/AccountHeader.tsx, packages/mobile/src/screens/sign-on-screen/screens/FinishProfileScreen.tsx, packages/mobile/src/screens/sign-on-screen/screens/ReviewHandleScreen.tsx, packages/web/src/common/store/pages/signon/sagas.js, packages/web/src/common/store/pages/signon/types.ts, packages/web/src/components/welcome-modal/WelcomeModal.tsx, packages/web/src/pages/sign-up-page/components/AccountHeader.tsx, packages/web/src/pages/sign-up-page/components/CoverPhotoBanner.tsx, packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx, packages/web/src/pages/sign-up-page/pages/ReviewHandlePage.tsx
Took a bit of debugging, but it was an issue of different types and the js file in the middle messing up type checking.
Updated the new stuff to conform to what the sign up endpoint expects so I dont have to change the older and scarier code
locally tested
=> [C-3614, C-3615] Update image storage for new sign up flow to conform with old structure

packages/web/src/components/add-funds/AddFunds.tsx
=> [PAY-2351] Fix height on add funds

packages/identity-service/src/routes/authentication.js
Sendgrid field dropped here b/c of bad rebase
https://github.com/AudiusProject/audius-protocol/pull/7196/files#diff-495ff7e8cc027e585ec395cc7484211223ad32839bfb79bf8498154a3fc46602L99
=> Fix otp after #7196

packages/web/src/pages/oauth-login-page/OAuthLoginPage.module.css, packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx, packages/web/src/pages/oauth-login-page/messages.ts
=> [Web] Add OTP to OAuth login flow [C-3643]

packages/common/src/store/ui/toast/sagas.ts
Lower all toast durations from 10s to 3s
toast disappears after 3s
=> [C-3640] Reduce toast duration app-wide

packages/libs/src/sdk/oauth/types.ts, packages/libs/src/sdk/utils/oauthScope.ts, packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx, packages/web/src/pages/oauth-login-page/components/CTAButton.tsx, packages/web/src/pages/oauth-login-page/components/PermissionsSection.tsx, packages/web/src/pages/oauth-login-page/hooks.ts, packages/web/src/pages/oauth-login-page/messages.ts, packages/web/src/pages/oauth-login-page/utils.ts, packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Companion to https://github.com/AudiusProject/audius-protocol/pull/7205 (meant to put the two PRs up at the same time, then forgot to make this PR 😅).
Locally against stage
=> [Web] [Libs] Disconnect dashboard wallet - web and SDK changes

packages/discovery-provider/src/queries/query_helpers.py, packages/discovery-provider/src/queries/search_es.py, packages/es-indexer/src/indexNames.ts
They are currently returning null instead of their values in the search endpoint
deployed to stage DN2 and tested the search endpoint
=> [PAY-2361] Fix search es with new gated fields

docs/docs/developers/log-in-with-audius.md, docs/docs/developers/sdk/Playlists.md, docs/docs/token/running-a-node/setup/advanced.md, docs/docs/token/running-a-node/setup/installation.md, docs/docusaurus.config.js
repaired cross reference links between pages
successful local build
=> [DOCS] - repair reference links and set config to throw errors on breaks

packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx, packages/web/src/pages/sign-up-page/components/layout.tsx, packages/web/src/pages/sign-up-page/pages/MobileAppCtaPage.tsx, packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
=> Fix max width issue on select artists page

packages/discovery-provider/src/queries/get_sitemap.py
Add is_unlisted and is_scheduled_release.
Better change would be to generate no-index pages for these.
Probably can roll into Phase II work.
=> Filter sitemaps properly

packages/web/src/common/store/pages/signon/sagas.js
Fixes the issue where sign ups get thru account creation but endlessly stuck on the "ready to rock" page
=> Fix sign ups failing halfway through saga

packages/web/src/components/track/desktop/TrackTile.module.css, packages/web/src/components/track/desktop/TrackTile.tsx, packages/web/src/components/track/mobile/TrackTile.module.css, packages/web/src/components/track/mobile/TrackTile.tsx
Fixes issue where long track title names on desktop did not have ...ellipses. This also fixes issue where long artist name didn't show ellipses on mobile web
=> [C-3597] Add ellipses to track tile titles

packages/mobile/src/screens/track-screen/DownloadRow.tsx
=> Convert mobile DownloadRow to harmony

packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx, packages/mobile/src/screens/chat-screen/ReactionPopup.tsx
Fix the super-small emojis on chat reactions.
I think the root cause is something else - feels like the space around the emoji increased.
=> Increase chat reaction emoji sizes

packages/discovery-provider/src/queries/get_track_signature.py
=> [PAY-2362] Allow offline download

dev-tools/setup.sh
Docker compose [released a bug](https://github.com/docker/compose/issues/11378) and we need to downgrade to unblock CI.
Green CI
=> Attempt to circumvent docker-compose regression

package-lock.json, protocol-dashboard/package.json, protocol-dashboard/src/components/CallToActionBanner/CallToActionBanner.module.css, protocol-dashboard/src/components/Header/Header.module.css, protocol-dashboard/src/components/ManageService/ManageService.module.css, protocol-dashboard/src/components/TransactionStatus/TransactionStatus.module.css, protocol-dashboard/src/components/UserInfo/AudiusProfileBadges.tsx
- Fix verified check color
- Fix layout issue w/ pending transactions
- Fix horizontal scroll issue
- Increase height of banner background image
Before layout fix:
After layout fix:
=> [Protocol Dashboard] QA for Link Wallet with Audius Profile [C-3691] [C-3685] [C-3684] [C-3711]

monitoring/healthz/src/utils/abis.ts, monitoring/healthz/src/utils/abis/Registry.json, monitoring/healthz/src/utils/abis/ServiceProviderFactory.json, monitoring/healthz/src/utils/abis/ServiceTypeManager.json
thought you could reference the abis from libs in healthz, this fixes the healthz build
npm run dev
=> use abis within healthz

package-lock.json, packages/web/package.json, packages/web/src/components/withdraw-usdc-modal/components/CoinflowWithdrawPage.tsx
This updates the version of coinflow/react and adds the new lockAmount flag to prevent confusion in the withdrawal flow.
fixes PAY-2368
Tested locally against production discovery
=> [PAY-2368] Add lockAmount flag to web withdrawals

packages/mobile/index.js
Removes TextInput system font-scaling, similar to Text.
=> [C-3707] Remove text-input font scale

packages/discovery-provider/src/queries/query_helpers.py
Return boolean access fields for tracks while in logged out state
stage web dapp against this code deployed to stage dn
=> Fix logged out state track access

packages/libs/src/sdk/oauth/OAuth.ts, packages/web/src/pages/oauth-login-page/OAuthLoginPage.module.css, packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx, packages/web/src/pages/oauth-login-page/components/ApproveTransactionScreen.module.css, packages/web/src/pages/oauth-login-page/components/ApproveTransactionScreen.tsx, packages/web/src/pages/oauth-login-page/hooks.ts, packages/web/src/pages/oauth-login-page/messages.ts, packages/web/src/pages/oauth-login-page/utils.ts
- Increase height of OAuth popup
- Fix spacing issues with OAuth page
- Add toast asking user to approve the Metamask transaction
- Fix some "disconnect profile from wallet" bugs, e.g. the transaction would be sent even if you logged in with the wrong user
=> [Web][Libs] QA for Link Audius Profile to Dashboard Wallet feature [C-3683] [C-3686]

packages/mobile/src/services/sdk/audius-sdk.ts, packages/web/src/common/store/pages/signon/actions.ts, packages/web/src/common/store/pages/signon/reducer.js, packages/web/src/common/store/pages/signon/selectors.ts, packages/web/src/common/store/pages/signon/types.ts, packages/web/src/pages/sign-up-page/components/AccountHeader.tsx, packages/web/src/pages/sign-up-page/components/PreviewArtistHint.tsx, packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx, packages/web/src/services/audius-sdk/solana.ts
- Ensures preview hint does not appear after dismissing, even after navigating back to genres
- Removes"go back to genres" section since we have the nav-header above
=> [C-3667] Improve preview hint, remove duplicate navigation

packages/web/src/pages/sign-up-page/pages/CreateLoginDetails.tsx
Cant scroll down on create login details on mobile, this should fix how the container handles the button
Local desktop chrome + TODO: test on mobile using preview url
=> [C-3722] Fix scrolling on create login details page

packages/common/src/models/Analytics.ts
=> Fix all caps metric name

packages/web/index.html
Fix check broken in env var change
=> Fix hash routing check in index.html

packages/discovery-provider/src/utils/get_all_nodes.py
Changes redis key to avoid using values with an outdated format which would prevent the server from starting up.
=> Change redis DN key

packages/common/src/api/user.ts
=> Update cash copy

packages/discovery-provider/src/api/v1/challenges.py
Fixes broken discovery attestations for challenge rewards, regressed in #7026 
TBD - will merge and test on stage
=> Fix existing discovery attestations

packages/web/src/common/store/pages/signon/sagas.js
Bug in sign up saga not waiting for remote config properly. Seems to work on web due to localStorage being available or something?
also adds some logging for errors
iOS stage simulator
=> Fix sign up saga bug on native

packages/common/src/api/topArtists.ts, packages/web/src/pages/sign-up-page/components/AccountHeader.tsx, packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
tweak top artists call, restore back to genres button, fix artist cards not showing
=> Misc New Sign Up Select Artist fixes

packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
Hide the whole flow if none of the ramps are enabled
=> Hide audio onramp when all supported providers are not allowed

packages/discovery-provider/src/api/v1/challenges.py
=> Fix Attestations (again)

.circleci/src/commands/@web-commands.yml, .circleci/src/jobs/@web-jobs.yml, .circleci/src/workflows/web.yml, packages/web/turbo.json
I broke staging web deploys with #7213 
Both the spa and ssr bundle need to be deployed now, this pr fixes it!
Confirmed that the stage deploy works properly
=> Fix staging web deploy

.circleci/src/jobs/@protocol-dashboard-jobs.yml, .circleci/src/workflows/protocol-dashboard.yml, protocol-dashboard/scripts/updateBuild.cjs
Removes General Admission calls from the prod CI process of building+pinning protocol dashboard.
=> Remove GA from protodash build process

packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/SelectArtistsScreen.tsx, packages/mobile/src/store/sign-out/sagas.ts, packages/web/src/common/store/pages/signon/reducer.js
- Add call to clear sign up in logout saga
local ios simulator
=> [C-3641] Clear sign up data on log out

packages/ddex/Dockerfile
https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/51051/workflows/fe695fd9-97f8-4830-bdc7-675161fa2536/jobs/667773
Built and ran image on the stage ddex node
=> Fix docker push-ddex

packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
=> [PAY-40] Make Rewards Modal Scrollable

packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.tsx, packages/web/src/components/withdraw-usdc-modal/components/PrepareTransfer.tsx
=> [PAY-2401] Update button/copy of withdrawal

packages/discovery-provider/src/monitors/database.py
=> Limit query length in verbose check

packages/discovery-provider/integration_tests/tasks/test_index_user_bank.py, packages/discovery-provider/integration_tests/tasks/user_bank_mock_transactions.py, packages/discovery-provider/src/tasks/index_user_bank.py
Thank you @schottra for making this easy :)
```
pytest integration_tests/tasks/test_index_user_bank.py
```
=> [PAY-2314] Add audio user bank indexer tests

packages/web/src/components/play-bar/repeat-button/RepeatButtonProvider.tsx, packages/web/src/components/play-bar/shuffle-button/ShuffleButtonProvider.tsx
Updates lottie file imports from require to import, which is needed for our SSR setup. First noticed by @nicoback when switching themes
=> Fix lottie imports

packages/common/src/store/lineup/reducer.ts, packages/common/src/store/pages/collection/actions.ts, packages/common/src/store/pages/collection/lineup/actions.ts, packages/common/src/store/pages/collection/lineup/reducer.ts, packages/common/src/store/pages/collection/reducer.ts, packages/common/src/store/pages/search-results/reducer.ts
Convert the files in the collection page store to ts
No fixes needed
typecheck is passing
=> Convert collection page store js files to ts

packages/common/src/store/pages/feed/actions.ts, packages/common/src/store/pages/feed/lineup/reducer.ts, packages/common/src/store/pages/feed/reducer.ts
Converted to feed page store js files to ts
No fixes needed
=> Convert Feed page store js files to ts

packages/common/src/store/pages/history-page/lineups/tracks/actions.ts, packages/common/src/store/pages/history-page/lineups/tracks/reducer.ts, packages/common/src/store/pages/history-page/reducer.ts
Convert history page store js files to ts
No fixes needed
=> Convert history page store js files to ts

packages/common/src/store/pages/saved-page/lineups/tracks/reducer.ts
Convert saved page store js files to ts
No fixes needed
=> Convert saved page store js files to ts

packages/web/src/common/store/social/tracks/sagas.ts
Not entirely sure why this failed in mobile but passed in web.
`npm run verify` in `packages/mobile` passes.
=> Fix mobile typecheck

packages/common/src/store/pages/profile/actions.ts, packages/common/src/store/pages/profile/lineups/tracks/reducer.ts, packages/common/src/store/pages/profile/reducer.ts, packages/common/src/store/pages/profile/types.ts
Convert profile page store js files to ts
Small updates to the reducer to fix types but maintain functionality
=> Convert profile page store js files to ts

packages/common/src/store/pages/profile/lineups/feed/reducer.ts, packages/common/src/store/pages/profile/reducer.ts, packages/common/src/store/pages/profile/types.ts, packages/common/src/store/pages/trending/actions.ts, packages/common/src/store/pages/trending/lineup/reducer.ts, packages/common/src/store/pages/trending/reducer.ts, packages/common/src/store/pages/trending/types.ts, packages/web/src/common/store/queue/sagas.ts, packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx, packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
Convert trending page store js files to ts
=> Convert trending page store js files to ts

packages/common/src/store/playlist-library/helpers.test.ts, packages/common/src/utils/handleReservedStatus.test.ts, packages/common/src/utils/hashIds.test.ts, packages/common/src/utils/performance.test.ts
Convert common js test tiles to ts
Tests all passed
=> Convert common js test tiles to ts

.circleci/src/workflows/release.yml, packages/ddex/publisher/package.json
Forgot some dependencies.
Remove ddex-publisher as release dependency
=> fix DDEX publisher dependencies and remove from blocking release

packages/web/src/pages/upload-page/fields/StemFilesView.tsx, packages/web/tsconfig.json
Fixes issue with @audius/common auto-imports only showing the ~ versions
=> Fix @audius/common auto-imports

packages/discovery-provider/ddl/functions/handle_usdc_withdrawal.sql, packages/discovery-provider/integration_tests/notifications/test_usdc_withdrawal.py, packages/discovery-provider/plugins/notifications/src/__tests__/emailRender.test.ts, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/usdcTransfer.test.ts, packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/transfer.ts, packages/discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts, packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/mapNotifications.ts, packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcTransfer.ts, packages/discovery-provider/plugins/notifications/src/remoteConfig.ts, packages/discovery-provider/plugins/notifications/src/types/notifications.ts
This adds a distinction between manual transfer and withdrawal flows for our notifications. 
Tested trigger locally by adding row. Otherwise using automated testing to verify. Will try on staging once merged.
=> [PAY-2445] Separate email notifications for manual transfer and withdrawal

packages/discovery-provider/src/tasks/index_user_bank.py
=> Change index_user_bank log to info instead of error

packages/ddex/webapp/README.md, packages/ddex/webapp/client/src/components/AppWithProviders.tsx, packages/ddex/webapp/client/src/pages/Upload/Upload.tsx, packages/ddex/webapp/client/vite.config.ts, packages/ddex/webapp/server/.env.dev, packages/ddex/webapp/server/package.json, packages/ddex/webapp/server/src/app.ts, packages/ddex/webapp/server/src/index.ts, packages/ddex/webapp/server/src/routers/index.ts, packages/ddex/webapp/server/src/routers/uploadRouter.ts, packages/ddex/webapp/server/src/services/s3.ts
- Generates a signed URL for the UI to upload ZIP files directly to S3 (rejects XML)
- Adds instructions on how to setup S3 bucket with IAM role, permission, and CORS
- Cleans up miscellaneous DDEX webapp code, mostly related to tRPC
I tested the S3 instructions as I wrote them and ran the webapp locally to confirm that the upload reaches the bucket.
=> [PROTO-1636] Make ddex UI upload zip files to S3

packages/web/src/pages/private-key-exporter-page/AdvancedWalletDetails.tsx, packages/web/src/pages/private-key-exporter-page/PrivateKeyExporterModal.tsx, packages/web/src/pages/private-key-exporter-page/PrivateKeyExporterPage.tsx
=> Fix mobile styles for pkey export

packages/web/src/components/track/DownloadRow.tsx, packages/web/src/components/track/DownloadSection.tsx
Add `variant` to `Text` components so they have the correct font.
=> [PAY-2425] Fix DownloadRow text styles

package.json
=> Remove common command from root package.json

.circleci/src/commands/@mobile-commands.yml, packages/mobile/dapp-store/package.json, packages/mobile/dapp-store/pnpm-lock.yaml
Upgrades dapp-store cli to latest to fix build issue
=> Upgrade dapp-store cli

packages/common/src/hooks/useGatedContent.ts, packages/mobile/src/screens/track-screen/DownloadSection.tsx, packages/web/src/components/track/DownloadSection.tsx
Add missing copy state for isOwner & downloads are purchaseable
=> [PAY-2436] Add isOwner purchaseable downloads copy

packages/mobile/src/screens/sign-on-screen/screens/FinishProfileScreen.tsx
- Put profile image and cover photo into the store on change + use it in `initialValues`
simulator ios:stage
=> [C-3607] Store & restore profile image and cover photo between new sign up pages

packages/mobile/src/screens/sign-on-screen/SignOnStack.tsx
Unrender the back button and disable swipe gesture on the genres screen
ios:stage
=> [C-3665] - Prevent back on select genres page

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/web/src/common/store/pages/signon/sagas.ts, packages/web/src/components/search-bar/SearchBar.tsx
Fixes issue in sign-on saga breaking main branch ci
=> Fixes signon saga type

packages/web/src/public-site/pages/landing-page/components/CTAGetStarted.tsx
=> [C-3764] Use history in handleClickRoute pt 2

packages/common/src/hooks/purchaseContent/types.ts, packages/common/src/utils/dogEarUtils.ts, packages/mobile/src/components/premium-track-purchase-drawer/PurchaseSuccess.tsx, packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx, packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx, packages/web/src/components/premium-content-purchase-modal/components/PurchaseSummaryTable.tsx, packages/web/src/components/summary-table/SummaryTable.tsx, packages/web/src/components/track/LockedTrackDetailsTile.tsx, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/AudioMatchingRewardsModalContent.tsx
Bring web purchase modal up to spec. Mobile in follow up PR.
=> [PAY-2408][PAY-2443][PAY-2397] Bring web purchase up to lossless spec

packages/web/scripts/workers-site/index.js
SSR worker looks good on prod, this PR enables ssr for the relevant user agents
SSR worker rendering properly for desktop and mobile:
https://audius-web-ssr.audius.workers.dev/Not_Ur_Avrg_Joe/oh-well-prod-pierre-bourne
=> Enable SSR

dev-tools/compose/docker-compose.ddex.yml
This .env file is gitignored and only used for local dev. Will instead just hardcode the env values and update the readme later
=> fix ddex ingester CI

packages/mobile/src/screens/track-screen/DownloadRow.tsx, packages/web/src/components/track/DownloadRow.tsx
=> [PAY-2444] Title case stems

packages/web/src/components/artist-recommendations/ArtistRecommendations.module.css, packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx, packages/web/src/components/data-entry/DropdownInput.jsx, packages/web/src/components/data-entry/DropdownInput.module.css, packages/web/src/components/nav/desktop/NavButton.module.css
=> [Web] Fix upload button icon color and dropdown input caret size [C-3771]

packages/discovery-provider/README.md
Include instructions for running a single test.
I like including a full example.
=> Update DN README.md for testing

packages/discovery-provider/src/api/v1/tracks.py
=> Fix parser

packages/mobile/src/screens/track-screen/DownloadSection.tsx
=> [PAY-2477] Remove blue background from purchased in download section

packages/web/src/pages/audio-rewards-page/components/modals/TrendingRewards.tsx, packages/web/src/pages/trending-page/components/RewardsBanner.tsx
Fix too large right arrow icons after Harmony icons migration.
=> [Web] Fix some weird arrow sizes [C-3801]

packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx, packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx, packages/web/src/components/collection/desktop/OwnerActionButtons.tsx, packages/web/src/components/collection/desktop/PublishButton.tsx, packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx, packages/web/src/pages/collection-page/components/mobile/CollectionPage.tsx
- Fix messages to use the right collection type
- Fix disabled states on share and publish buttons for private albums
looks good on local
=> [C-3783, C-3778] Fix collection screen messages

packages/stems/src/components/Modal/ModalHeader.module.css, svgr-template.js
Addresses a few harmony callouts:
- Hint icon should be static size
- Modal header not centered, incorrect color etc
=> [C-3748] Address harmony callouts

packages/web/src/components/create-playlist/PlaylistForm.tsx, packages/web/src/components/track/GiantTrackTile.tsx, packages/web/src/components/wait-for-download-modal/WaitForDownloadModal.tsx, packages/web/src/pages/upload-page/validation.ts
- Capitalization should match the album title on album links
- Artwork should not be required on playlists because they inherit artwork from the tracks
working on local web
=> [C-3786, C-3787] Fix album link casing; Fix required artwork

packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/main.ts
=> update timings and set dryrun to false on cron

packages/mobile/ios/Podfile.lock, packages/mobile/package.json, packages/mobile/src/harmony-native/components/CompletionCheck/CompletionCheck.tsx, packages/mobile/src/screens/change-email-screen/SubScreens.tsx, packages/mobile/src/screens/change-password-screen/ChangePasswordScreen.tsx, packages/mobile/src/screens/change-password-screen/ResendCodeLink.tsx, packages/mobile/src/screens/change-password-screen/SubScreens.tsx
Welp, I thought these were in the last PR but the push failed due to my lint failing (really need to fix my prettier 😢 )
Also updates Rive hoping to fix the crash on Android (didn't work though)
=> Mobile: Change Email, Change Password CR Fixes

package.json, packages/web/src/app/TrpcProvider.tsx, patches/@trpc+client+10.38.4.patch
* Patches trpc-client to add a batching interval.
* Updates react-query to re-fetch less often.
=> Patch trpc batching

packages/harmony/src/components/button/IconButton/IconButton.tsx, packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.module.css, packages/web/src/components/tipping/feed-tip-tile/FeedTipTile.tsx, packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeveloperAppListItem.module.css, packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeveloperAppListItem.tsx, packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeveloperAppsSettingsModal.module.css, packages/web/src/pages/trending-page/components/RewardsBanner.tsx
Two mas post-harmony icon migration fixes after a comb through of the web app.
=> [Web][Harmony] Forward ref in Harmony IconButtob; Fix red kebab icon and too big tip tile close icon

packages/mobile/android/app/build.gradle, packages/mobile/ios/AudiusReactNative/Info.plist
Updates android version to prepare for full app release this week
=> Upgrade native for full release

packages/mobile/src/screens/sign-on-screen/components/EmailField.tsx, packages/mobile/src/screens/sign-on-screen/screens/CreateLoginDetailsScreen.tsx, packages/mobile/src/screens/sign-on-screen/screens/SignInScreen.tsx, packages/mobile/src/screens/signon/CreatePassword.tsx
I _think_ this should allow password managers to autocomplete stuff?
Unsure if there's a way to test this on simulator? Is there a way to install a password manager on simulator?
=> [C-3666] Add autocomplete fields to new sign up/sign in fields

packages/mobile/src/components/core/AddressTile.tsx, packages/mobile/src/screens/pay-and-earn-screen/USDCCard.tsx, packages/web/src/common/store/lineup/sagas.ts
Noticed some fonts were wrong on android so rewrote this component in harmony-native. There are still some issues with text alignment as well as shadows on the `Paper` component, I've flagged these to client.
Bonus - sneaking in a comment change for the premium content allowlist changing to a denylist.
ios:
android:
=> Rewrite USDCCard in harmony-native to fix android text

docs/docs/token/token.mdx, packages/identity-service/src/routes/tiktok.js
Quick fix for some missing spaces!
=> Fix spacing in Token docs

packages/web/src/common/store/pages/signon/sagas.ts
Small update of call to properly set context
=> [ONC-20] Fix sign on page saga for fetching suggested artists

packages/web/src/common/store/cache/tracks/sagas.ts
Fixes issue where we called editTrack twice
Fixes issue where we call apiClient without context
=> Fix edit/delete track sagas

packages/ddex/ingester/indexer/indexer.go
Fixes DDEX indexer module not maintaining the correct relative file structure when uploading nested resources to S3.
Tested indexing locally to make sure it uploads in the format that the XML expects where it gives a FilePath+FileName.
=> Fix ddex indexer excluding nested resources

packages/web/src/components/track/desktop/TrackListItem.module.css, packages/web/src/components/track/desktop/TrackListItem.tsx
=> [Web] Fix red icon kebab horizontal icon [C-3829]

packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimiter.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/redis.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts
some logs slipped through the last PR to fix the app creation, this cleans them up
N/A
=> relay log cleanup

.circleci/src/jobs/@protocol-dashboard-jobs.yml
=> Fix armada project id

.circleci/config.yml
Currently will not trigger on release branches
=> Run dashboard job on client release

packages/mobile/src/screens/signon/ProfileImage.tsx
Small update to pass the file data with uri to the image component when present
Manually tested on android device
=> [ONC-9] Fix profile image display in old sign up flow

packages/harmony/src/components/segmented-control/SegmentedControl.module.css, packages/harmony/src/components/segmented-control/SegmentedControl.tsx, packages/harmony/src/components/segmented-control/types.ts, packages/web/src/components/data-entry/StemsAndDownloadsTriggerLegacy.tsx, packages/web/src/components/stem-files-modal/StemFilesModal.tsx, packages/web/src/components/upload/TrackPreviewNew.tsx, packages/web/src/pages/upload-page/components/TracksPreview.tsx, packages/web/src/pages/upload-page/fields/StemFilesView.tsx, packages/web/src/pages/upload-page/fields/StemsAndDownloadsField.tsx, packages/web/src/pages/upload-page/fields/StemsAndDownloadsMenuFields.tsx, packages/web/src/pages/upload-page/fields/download-availability/DownloadAvailability.tsx
Add waitlist for premium downloads.
Also add subdued style for disabled segmented control options.
Local web dapp vs stage.
=> [PAY-2492][PAY-2500] Add waitlist for premium downloads

.circleci/config.yml, .circleci/src/workflows/protocol-dashboard.yml
* Deploy staging on main (like client)
* Deploy prod on release-* branches
=> Push protocol dashboard better

packages/discovery-provider/scripts/start.sh
Axiom seems to have gaps in staging so persisting these within the container should help. It's only a few lines every minute.
=> Persist active task log

packages/harmony/src/components/segmented-control/SegmentedControl.mdx, packages/harmony/src/components/segmented-control/SegmentedControl.stories.tsx, packages/harmony/src/components/segmented-control/SegmentedControl.tsx, packages/web/src/components/data-entry/FormTile.jsx, packages/web/src/components/data-entry/StemsAndDownloadsTriggerLegacy.tsx, packages/web/src/components/edit-track/EditTrackModal.tsx, packages/web/src/components/stem-files-modal/StemFilesModal.module.css, packages/web/src/components/stem-files-modal/StemFilesModal.tsx, packages/web/src/components/track/GiantTrackTile.tsx, packages/web/src/components/upload/TrackPreviewNew.tsx, packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx, packages/web/src/pages/upload-page/components/TracksPreview.tsx, packages/web/src/pages/upload-page/fields/StemFilesView.tsx, packages/web/src/pages/upload-page/fields/StemsAndDownloadsField.tsx, packages/web/src/pages/upload-page/fields/StemsAndDownloadsMenuFields.tsx, packages/web/src/pages/upload-page/fields/download-availability/DownloadAvailability.tsx, packages/web/src/pages/upload-page/pages/SelectPage.tsx
- Clean up lossless feature flag use.
- Fix behavior when feature flag is off.
- Fix disabled segmented control option variant.
- Add segmented control config options to storybook.
- Clean up stem preview logic
Local web dapp vs stage.
=> Fix and clean up more lossless downloads issues

mediorum/cidutil/cidutil.go, mediorum/server/serve_upload.go, mediorum/server/transcode.go
Follow up to https://github.com/AudiusProject/audius-protocol/pull/7593 to also mirror orig upload in parallel.
Makes the pause at 50% (before transcode starts) less extreme.  Sorry for the large paws.
=> Mirror orig upload in parallel

packages/mobile/src/services/track-download.ts
Big yuck, but these fixes seem to work across android versions:
https://github.com/RonRadtke/react-native-blob-util/issues/247
1. Download one
2. Download many
On android physical device
=> Fix android downloads

mediorum/server/transcode.go
Increase transcode capacity for larger servers.
=> Use more transcode workers on larger machines

packages/mobile/android/app/build.gradle, packages/mobile/ios/AudiusReactNative/Info.plist
=> Update mobile app versions

packages/mobile/android/app/build.gradle, packages/mobile/ios/AudiusReactNative/Info.plist, packages/mobile/src/services/track-download.ts
Turns out you cannot specify `storeInDownloads` and `path`
or you get
```
ERROR  [Error: Download manager download failed, the file does not downloaded to destination.]
```
which would make sense.
Local device
=> Fix single download

.circleci/config.yml
FIxes issue where the changelog generation script fails to find the correct previous client release
=> Fix generate-client-release script version

packages/common/src/models/Analytics.ts, packages/common/src/store/gated-content/sagas.ts, packages/mobile/src/screens/track-screen/DownloadSection.tsx, packages/mobile/src/services/track-download.ts, packages/web/src/common/store/upload/sagaHelpers.ts, packages/web/src/components/track/DownloadSection.tsx, packages/web/src/pages/upload-page/fields/download-availability/DownloadAvailability.tsx, packages/web/src/services/track-download.ts
Add lossless metrics client-side.
local web and native mobile dapps v stage
=> [PAY-2229] Add lossless UI metrics

packages/mobile/src/screens/sign-on-screen/components/AccountHeader.tsx
Just added the numLines prop to the text holding the handle
=> [C-3870] Update AccountHeader handle text to be one line

packages/common/src/schemas/sign-on/pickHandleSchema.ts, packages/mobile/src/components/fields/HarmonyTextField.tsx, packages/mobile/src/screens/sign-on-screen/components/HandleField.tsx, packages/mobile/src/store/offline-downloads/sagas/migrateOfflineDataPathSaga.ts, packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadFile.ts, packages/mobile/src/store/offline-downloads/sagas/watchRemoveOfflineItems.ts
Fix the handle field flashing messages like "handle is required" and bouncing back/forth on messages.
Also fixes the errors not showing as red
ios:stage
=> [C-3859] Fix mobile handle validation quirks

packages/mobile/src/harmony-native/components/Button/SocialButton/SocialButton.tsx
Update size of social buttons in new sign up flow
=> [C-3854] Update size of social buttons in new sign up flow

packages/mobile/src/screens/root-screen/RootScreen.tsx, packages/mobile/src/screens/sign-on-screen/SignOnStack.tsx
Adds `animation: none` to fix the android "white screen of death"
android:stage and ios:stage
=> [C-3855] Fix android white screen issue on sign up

packages/common/src/models/Analytics.ts, packages/mobile/src/screens/sign-on-screen/components/SignUpFlowInstagramAuth.tsx, packages/mobile/src/screens/sign-on-screen/components/SignUpFlowTikTokAuth.tsx, packages/mobile/src/screens/sign-on-screen/components/SignUpFlowTwitterAuth.tsx, packages/mobile/src/screens/sign-on-screen/components/SocialMediaSignUpButtons.tsx, packages/mobile/src/screens/sign-on-screen/screens/ConfirmEmailScreen.tsx, packages/mobile/src/screens/sign-on-screen/screens/CreateEmailScreen.tsx, packages/mobile/src/screens/sign-on-screen/screens/CreateLoginDetailsScreen.tsx, packages/mobile/src/screens/sign-on-screen/screens/CreatePasswordScreen.tsx, packages/mobile/src/screens/sign-on-screen/screens/FinishProfileScreen.tsx, packages/mobile/src/screens/sign-on-screen/screens/PickHandleScreen.tsx, packages/mobile/src/screens/sign-on-screen/screens/ReviewHandleScreen.tsx, packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/FollowArtistCard.tsx, packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/SelectArtistsScreen.tsx, packages/mobile/src/screens/sign-on-screen/screens/SelectGenresScreen.tsx, packages/mobile/src/screens/sign-on-screen/screens/SignInScreen.tsx, packages/mobile/src/screens/sign-on-screen/utils/useTrackScreen.ts, packages/mobile/src/store/offline-downloads/sagas/migrateOfflineDataPathSaga.ts, packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadFile.ts, packages/mobile/src/store/offline-downloads/sagas/watchRemoveOfflineItems.ts
Add all the relevant sign up analytics events
ios:stage
=> [C-3838] Analytics events for mobile sign up

packages/web/src/pages/upload-page/fields/StemFilesView.module.css, packages/web/src/pages/upload-page/fields/StemFilesView.tsx
=> [PAY-2435] Remove pointer cursor when dropzone at max capacity

packages/web/src/pages/audio-transactions-page/AudioTransactionsPage.module.css, packages/web/src/pages/audio-transactions-page/AudioTransactionsPage.tsx
=> [Web] Fix red caret on Transactions History page

packages/mobile/README.md, packages/mobile/android/app/build.gradle, packages/mobile/android/app/src/main/java/co/audius/app/MainApplication.kt
* Remove flipper from android
* Update readme to reflect new debugger usage
=> Remove flipper from android and update readme

protocol-dashboard/src/components/LineChart/LineChart.tsx, protocol-dashboard/src/components/PlaysChart/PlaysChart.tsx, protocol-dashboard/src/components/TopAppsChart/TopAppsChart.tsx, protocol-dashboard/src/components/TotalApiCallsChart/TotalApiCallsChart.tsx, protocol-dashboard/src/components/TotalStakedChart/TotalStakedChart.tsx, protocol-dashboard/src/components/UniqueUsersChart/UniqueUsersChart.tsx, protocol-dashboard/src/containers/Analytics/Analytics.tsx, protocol-dashboard/src/store/cache/analytics/hooks.ts, protocol-dashboard/src/utils/format.ts
[Figma](https://www.figma.com/file/oGpCnzxeaxxw3DebFOEBTF/%F0%9F%8E%9B%EF%B8%8F-Protocol-Dashboard-Redesign?type=design&node-id=3327-17942&mode=design&t=rp45J0byjeHFb6og-0)
Companion PR: https://github.com/AudiusProject/audius-protocol/pull/7676
This includes:
- Show top line metrics with respective charts + selected time range
- Use trailing metrics API with different time ranges
- Fix chart axes ticks, add area fill and point radius, add date w/ year formatter for "All Time" time range
- Add "year" time range to charts
Follow-ons:
- Tooltips (will do these all in one go)
- Change default to "year" (waiting until companion PR is deployed)
=> [Protocol Dashboard] Analytics Page Updates [C-3753]

packages/mobile/android/app/build.gradle, packages/mobile/ios/AudiusReactNative/Info.plist
Bumps mobile versions for prod release
=> Bump mobile versions for prod release

packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/SelectArtistsScreen.tsx
Some additional padding for the bottom of the sign up artists page
ios:stage and android:stage
=> [C-3858] Additional padding on select artists screen

packages/common/src/schemas/sign-on/finishProfileSchema.ts, packages/mobile/src/screens/root-screen/RootScreen.tsx, packages/mobile/src/screens/sign-on-screen/components/AccountHeader.tsx, packages/mobile/src/screens/sign-on-screen/components/WelcomeDrawer.tsx, packages/mobile/src/screens/sign-on-screen/screens/CreatePasswordScreen.tsx, packages/mobile/src/screens/sign-on-screen/screens/FinishProfileScreen.tsx, packages/mobile/src/screens/sign-on-screen/screens/SelectGenresScreen.tsx, packages/web/src/common/store/pages/signon/actions.ts, packages/web/src/common/store/pages/signon/reducer.js, packages/web/src/common/store/pages/signon/selectors.ts, packages/web/src/common/store/pages/signon/types.ts
Contains fixes for all the "green" status things in this screenshot
ios:stage and android:stage
TODO: more android testing
Also, the keyboard hiding view isnt doing anything on android for some reason
=> Misc Sign Up QA Fixes

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/store/upload/reducer.ts, packages/common/src/store/upload/selectors.ts, packages/web/src/common/store/queue/sagas.ts, packages/web/src/pages/profile-page/components/desktop/ProfilePage.module.css, packages/web/src/pages/profile-page/components/desktop/ProfileWrapping.tsx
- Spacing between and around display name and handle in profile page
- Play preview for premium track in track as part of lineup
local dapp vs stage and prod
=> [QA-779][QA-704] Fix some UI issues

packages/mobile/src/screens/sign-on-screen/SignOnStack.tsx, packages/mobile/src/screens/sign-on-screen/screens/FinishProfileScreen.tsx
Unrender previous screens after reaching select genres page
android:stage
=> [C-3899] Fix android able to go back on signup

packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/challengeReward.ts, packages/identity-service/src/notifications/formatNotificationMetadata.js
=> [C-3909] Fix upload track challenge copy

packages/mobile/src/store/sign-out/sagas.ts
Small update in theme reset placement to have the colors on the sign up screen display properly
=> [C-3866] Update placement of theme reset in mobile sign out to make colors display properly

packages/mobile/src/components/suggested-tracks/SuggestedCollectionTracks.tsx
SuggestedCollectionTracks was erroring as it can't read property is_album of undefined. This fixes it.
local mobile dapp vs stage
=> [ONC-34] Fix bug in mobile suggested collection tracks

packages/mobile/src/screens/feed-screen/FeedScreen.tsx, packages/mobile/src/screens/sign-on-screen/components/SignUpFlowTwitterAuth.tsx, packages/mobile/src/screens/sign-on-screen/components/SocialMediaLoading.tsx, packages/mobile/src/screens/sign-on-screen/components/useSocialMediaLoader.tsx, packages/mobile/src/screens/sign-on-screen/screens/CreateEmailScreen.tsx, packages/mobile/src/screens/sign-on-screen/screens/PickHandleScreen.tsx, packages/mobile/src/screens/trending-screen/TrendingScreen.tsx
Fixes a bug where twitter token isn't refreshing correctly after signing in with it once.
Fixes a bug where the back button gets modified on social login success
Adds url to Trending and Feed to add amplitude metrics for these pages
ios:stage
=> Misc sign up social fixes

packages/discovery-provider/plugins/verified-uploads/src/handlers/tracks.js
Value of `is_download_gated` would not be there because not selecting it.
=> Add download gated column

packages/identity-service/src/utils/otp.js
=> Add others to skip otp

packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
Used to show enabled play button. Now disabled.
loca mobile dapp v stage
=> Disable play button if all collection tracks deleted

packages/web/src/components/stem-files-modal/StemFilesModal.tsx, packages/web/src/pages/upload-page/fields/StemFilesView.tsx
=> Update stem limit to 20

packages/harmony/src/components/hint/Hint.tsx, packages/mobile/src/components/audio-breakdown-drawer/AudioBreakdownDrawer.tsx, packages/mobile/src/components/audio-breakdown-drawer/Wallet.tsx, packages/web/src/pages/settings-page/components/desktop/DeveloperApps/AppDetailsPage.module.css, packages/web/src/pages/settings-page/components/desktop/DeveloperApps/AppDetailsPage.tsx
Fixes mobile audio-breakdown icons
Fixes web developer apps icons + refactors to use harmony hint
Adds "actions" prop to hint component following spec
=> [C-3918] Fix wallet and dev-apps icons

packages/discovery-provider/plugins/pedalboard/apps/relay/src/config/config.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/antiAbuse.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/contextInjector.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimiter.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/validator.ts
=> Add verifier checks to discovery relay

packages/web/src/components/track/LockedTrackDetailsTile.tsx
=> [C-3923] Remove double badges on purchase flow

packages/harmony/src/components/text-link/TextLink.tsx, packages/harmony/src/components/text-link/types.ts, packages/web/src/components/payment-method/PaymentMethod.tsx, packages/web/src/components/premium-content-purchase-modal/components/PayToUnlockInfo.tsx, packages/web/src/components/track/LockedTrackDetailsTile.module.css
Some minor harmony discrepancies still, but that's probably ok. Fix weight/color issues.
Before
After
Reference (Prod)
=> [C-3924] Fix misc font/type issues on purchase flow

packages/mobile/src/screens/sign-on-screen/components/layout.tsx, packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/TopArtistsCardList.tsx, packages/web/src/components/payment-method/PaymentMethod.tsx, packages/web/src/pages/sign-up-page/components/layout.tsx
Fixes issue where eletronic subgeneres were not fetching artists
Fixes issues with follow cont formatting (not yet merged in this pr)
Fixes issue with header shadow being too strong
Fixes issue with desktop read-only field
=> [C-3929] Fix select-artist genres

packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/FollowArtistCard.tsx
Fixes small issue where users with large number of follows are malformed in native sign-up
=> Format artist tracks and followers count

packages/discovery-provider/src/api/v1/tracks.py
Catch exceptions and try next node
=> Catch exceptions to finish rendezvous fallbacks

packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimiter.ts
Setting `response.header` from express is not right
=> Fix rated limiter call in relay

packages/web/src/common/store/pages/signon/sagas.ts, packages/web/src/components/nav/desktop/LeftNav.tsx
Redirect on sign in and link from left nav
=> Add fb redirect

protocol-dashboard/src/components/AppBar/AppBar.tsx, protocol-dashboard/src/components/CallToActionBanner/CallToActionBanner.tsx, protocol-dashboard/src/components/Header/HeaderMobile.module.css, protocol-dashboard/src/components/ManageService/ManageService.tsx, protocol-dashboard/src/components/MobileNav/MobileNav.module.css, protocol-dashboard/src/components/NodeOverview/NodeOverview.tsx, protocol-dashboard/src/components/Page/Page.tsx, protocol-dashboard/src/components/Page/PageMobile.module.css, protocol-dashboard/src/components/ProfileInfoCard/ProfileInfoCard.tsx, protocol-dashboard/src/components/RegisterNodeCard/RegisterNodeCard.tsx, protocol-dashboard/src/components/RewardsTimingCard/RewardsTimingCard.tsx, protocol-dashboard/src/components/Timeline/TimelineEvent.module.css, protocol-dashboard/src/components/Timeline/TimelineEventMobile.module.css, protocol-dashboard/src/components/TotalApiCallsChart/TotalApiCallsChart.tsx, protocol-dashboard/src/containers/Home/Home.tsx, protocol-dashboard/src/containers/Node/NodeMobile.module.css, protocol-dashboard/src/containers/Services/Services.tsx
- Fix mobile stying on protocol dashboard across the board. Also disables some actions when on mobile and fixes some misc. bugs.
=> [Protocol Dashboard] Fix mobile web styling [C-3809] [C-3845]

protocol-dashboard/src/components/AppBar/AppBar.tsx, protocol-dashboard/src/components/CallToActionBanner/CallToActionBanner.tsx, protocol-dashboard/src/components/Header/HeaderMobile.module.css, protocol-dashboard/src/components/ManageService/ManageService.tsx, protocol-dashboard/src/components/MobileNav/MobileNav.module.css, protocol-dashboard/src/components/NodeOverview/NodeOverview.tsx, protocol-dashboard/src/components/Page/Page.tsx, protocol-dashboard/src/components/Page/PageMobile.module.css, protocol-dashboard/src/components/ProfileInfoCard/ProfileInfoCard.tsx, protocol-dashboard/src/components/RegisterNodeCard/RegisterNodeCard.tsx, protocol-dashboard/src/components/RewardsTimingCard/RewardsTimingCard.tsx, protocol-dashboard/src/components/Timeline/TimelineEvent.module.css, protocol-dashboard/src/components/Timeline/TimelineEventMobile.module.css, protocol-dashboard/src/components/TotalApiCallsChart/TotalApiCallsChart.tsx, protocol-dashboard/src/components/TransactionStatus/TransactionStatus.tsx, protocol-dashboard/src/containers/Home/Home.tsx, protocol-dashboard/src/containers/Node/NodeMobile.module.css, protocol-dashboard/src/containers/Services/Services.tsx
- Disable complete undelegation while claim is pending
- Disable request undelegation while another the user has another pending undelegation
=> [Protocol Dashboard] Disable start + complete undelegation under certain conditions [C-3849] [C-3940]

packages/common/src/api/suggestedTracks.ts
Fix deleted or unlisted tracks showing up in suggested tracks
Fix race condition when library hasn't been fetched
=> [C-3887] Update suggested tracks logic to better handle deleted tracks and the race condition

packages/web/src/HarmonyCacheProvider.tsx, packages/web/src/index.tsx, packages/web/src/pages/something-wrong/SomethingWrong.module.css, packages/web/src/ssr/+onRenderClient.tsx, packages/web/src/ssr/+onRenderHtml.tsx, packages/web/src/ssr/index/+onRenderClient.tsx, packages/web/src/ssr/worker.js, packages/web/src/store/reload/sagas.ts
FIxes issue where CSR (what all users see) has an incorrectly configured emotion cache.
Refactors cache usage under one roof to reduce duplication
=> [C-3938] Fix harmony cache for SPA

packages/discovery-provider/src/api/v1/metrics.py
=> [Discovery] Fix metrics APIs for year time range [C-3956]

packages/web/.gitignore
Another miss from #7771 CR changes
=> Add .gitsha to .gitignore

packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/FollowArtistCard.tsx, packages/web/src/components/nav/desktop/ConnectInstagram.tsx, packages/web/src/components/nav/desktop/LeftNav.tsx, packages/web/src/pages/sign-up-page/hooks/useSocialMediaLoader.ts
Add small optional UI to nav to show instagram connection
=> Add connect instagram ui

packages/web/src/components/card/desktop/Card.module.css, packages/web/src/components/card/desktop/Card.tsx
=> [ONC-45] Fix small kebab

protocol-dashboard/src/types.ts
Mistake from past PR: https://github.com/AudiusProject/audius-protocol/pull/7787#discussion_r1522064251
=> Remove idle status in dashboard

packages/web/src/common/store/upload/sagas.js
=> [ONC-47] Fix playlist/album upload stream gating check

packages/harmony/src/icons/SpecialIcons.stories.mdx, packages/harmony/src/icons/UtilityIcons.stories.mdx, packages/harmony/src/icons/specialIcons.ts, packages/harmony/src/icons/utilityIcons.ts
Fixes some import issues and icon import locations
=> Fix harmony icon stories

packages/web/src/services/audius-backend/Jupiter.ts, packages/web/src/services/solana/WithdrawUSDC.ts, packages/web/src/store/application/ui/buy-audio/sagas.ts
We are slipping by 30% instead of 30bps 😱 
Looks much more reasonable
=> [ONC-46] Fix buy audio slippage

packages/discovery-provider/integration_tests/queries/test_get_trending_playlists.py, packages/discovery-provider/src/queries/get_trending_playlists.py
Current filter checks if the playlist contains at least 3 tracks from an owner besides the playlist creator. That was a mistake. It should be 3+ unique owners
Instead now:
1. Ensure at least 3 non-deleted tracks
2. Ensure at least 3 owners besides the playlist creator
Add test case
=> [ONC-30] Fix playlist trending filters

.circleci/src/workflows/discovery.yml, .circleci/src/workflows/release.yml
adds solana-relay to ci builds for stage and release
difficult to test since we don't push on PRs, can modify this commit to do that here I think
=> push solana relay in ci

packages/mobile/patches/@react-native-community+datetimepicker+7.6.2.patch, packages/mobile/patches/README.md
Adds patch file to datepicker to fix issue running on xcode 15.3
=> Fix react-native-datepicker on xcode 15.3

packages/libs/src/services/schemaValidator/schemas/playlistSchema.json
Remove the required fields so validation passes in libs
tested local web against prod
=> [C-3966] Don't require premium album fields

packages/mobile/android/app/build.gradle, packages/mobile/ios/AudiusReactNative/Info.plist
=> Bump mobile app versions for full release

docs/docs/node-operator/setup/advanced.mdx, docs/docs/node-operator/setup/hardware-requirements.mdx, docs/docs/node-operator/setup/installation.mdx
Added Postgres port access warning and specifications.
`npm run build` 
demo site here: [https://sam.audius.co/node-operator/setup/installation](https://sam.audius.co/node-operator/setup/installation)
=> [DVRL-18] - formatting and port warnings

packages/web/src/common/store/account/sagas.js
Fixes issue where checking user wallet fails when user signed out. js strikes again. The fix was a simple conditional check + some lint fixes
=> Fix wallet check

packages/web/.gitignore, packages/web/scripts/workers-site/index.js, packages/web/scripts/writeSHA.sh, packages/web/src/ssr/worker.js, packages/web/src/store/reload/sagas.ts
=> .gitsha => gitsha.json

packages/web/src/components/dynamic-image/DynamicImage.tsx
Fixes issue with dynamic-image background. Locally we have @file instead of data:
=> [C-3743] Fix avatar styles on local

packages/identity-service/src/solana-client.js, packages/libs/src/services/solana/SolanaWeb3Manager.ts, packages/libs/src/services/solana/rewards.ts, packages/libs/src/services/solana/transfer.ts, packages/libs/src/services/solana/userBank.ts, packages/web/public/.gitsha, packages/web/src/services/audius-backend/BuyAudio.ts, packages/web/src/services/audius-backend/Jupiter.ts
Keeping this very "WET" in the interim so we can experiment per transaction.
[x] Tipping
[ ] Buy $AUDIO
[x] Purchase tracks
[x] Create account & list track for sale
[x] Claim reward 
Will test buy $AUDIO once on prod
=> Add more priority fees across all solana transactions

.circleci/src/workflows/release.yml
wrong circular dep was found in release workflow
https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol?branch=release-v0.6.59
=> fix circular dep

packages/harmony/package.json, packages/libs/src/sdk/examples/react/package-lock.json, packages/libs/src/sdk/examples/react/package.json
Published harmony 0.0.29 and consumed it in examples/react
=> Bump harmony and consume in examples/react

packages/common/src/services/remote-config/feature-flags.ts
Adds feature flag for premium albums
Printed feature flag locally
=> [PAY-2557] Add PREMIUM_ALBUMS_ENABLED feature flag

protocol-dashboard/src/components/ManageService/ManageService.tsx, protocol-dashboard/src/components/UpdateDelegationModal/UpdateDelegationModal.tsx
...Or else the user would open the modal and just see UI about how they can't do anything right now.
Locally using fake data
=> [Protocol Dashboard] Disable Manage delegation button when claim is pending [C-4000]

packages/web/src/common/store/pages/signon/sagas.ts
Add the old account creation event into our saga
=> Add amplitude event for account creation

packages/web/src/services/audius-backend/Jupiter.ts
See https://github.com/AudiusProject/audius-protocol/pull/7849/files/573b2f56a503f80cdbc0072c9cd0fb8a0658d41e#r1525750297
=> Fix micro lamports in jupiter

packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/antiAbuse.ts
this error has the wrong data in it, we should be logging the response from AAO
=> fix aao error log

packages/mobile/package.json, packages/mobile/src/screens/sign-on-screen/components/layout.tsx, packages/mobile/src/screens/sign-on-screen/screens/CreatePasswordScreen.tsx, packages/mobile/src/screens/sign-on-screen/screens/FinishProfileScreen.tsx, packages/mobile/src/screens/sign-on-screen/screens/PickHandleScreen.tsx
Loom demo of the fixes
https://www.loom.com/share/d4b4ec10da8f49da97eabec2f403b9ba
Tweak mobile sign up screen spacing & scrolling to make everything look good on small devices
ios:stage on iPhone SE & iPhone 15 & android:stage on small & medium sizes
=> [C-4003] Fix sign up overflow issues on small devices

packages/common/src/models/SsrPageProps.ts, packages/common/src/store/cache/tracks/reducer.ts, packages/common/src/store/cache/users/reducer.ts, packages/common/src/store/pages/profile/actions.ts, packages/common/src/store/pages/profile/reducer.ts, packages/common/src/store/pages/profile/selectors.ts, packages/common/src/store/pages/profile/types.ts, packages/common/src/store/reducers.ts, packages/web/src/pages/profile-page/ProfilePageProvider.tsx, packages/web/src/ssr/profile/+Page.tsx, packages/web/src/ssr/profile/+onBeforeRender.tsx, packages/web/src/ssr/profile/+route.tsx, packages/web/src/ssr/track/+onBeforeRender.tsx, packages/web/src/ssr/track/+route.tsx, packages/web/src/ssr/util.ts
* Add profile page route
* Update user cache reducer to accept server provided data
* Update profile page reducer to accept server provided data
* Update profile page state to do the overwritting fetch after the first ssr render
Manually tested on local
=> [C-4025] Update profile page for ssr

packages/mobile/android/app/build.gradle, packages/mobile/ios/AudiusReactNative/Info.plist
We need to do full app release this week to fix a sign-up bug: https://github.com/AudiusProject/audius-protocol/pull/7868
=> Bump mobile version for full-app-release

packages/web/src/components/lineup/LineupProvider.tsx, packages/web/src/pages/track-page/components/mobile/TrackHeader.module.css
Fixes regression during button refactor
=> [C-4034] Fix feed tip tile

packages/mobile/package.json, packages/mobile/src/components/add-to-collection-drawer/AddToCollectionDrawer.tsx, packages/mobile/src/screens/feature-flag-override-screen/FeatureFlagOverrideScreen.tsx, packages/mobile/src/utils/fuzzySearch.ts, packages/web/src/components/add-to-collection/desktop/AddToCollectionModal.tsx, packages/web/src/pages/track-page/components/mobile/TrackHeader.module.css
Fixes issue where the most recently viewed collection does not appear in the add-to-collection ui.
Also adds fuzzy search to native add-to-collection drawer
=> [C-4031, C-4039] Fix add to collection, Add fuzzy search

mediorum/server/server.go, packages/discovery-provider/src/api/v1/root_path.py
=> [Mediorum] [Discovery] Change `/services` protodash routes to `/nodes`

packages/mobile/src/components/audio/AudioPlayer.tsx
Removes playback delay on mobile, especially when playing a large lineup.
Fixes an issue on previous attempts where we were setting index before awaiting the entire lineup to load.
=> [C-3561] Remove playback delay on native

packages/discovery-provider/src/api/v1/helpers.py
=> Remove is_downloadable from trending query

package-lock.json, packages/web/package.json
Adds markdown-to-jsx to web package now that stems is removed
=> Add markdown-to-jsx to web

packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py, packages/discovery-provider/src/tasks/entity_manager/entities/track.py
Needs to json load text object strings
=> Fix EM parsing of ddex fields

packages/web/src/pages/upload-page/validation.ts
=> fix nullable new fields in collection schema

packages/harmony/src/components/layout/Popup/Popup.tsx, packages/harmony/src/components/modal/Modal.tsx, packages/harmony/src/utils/modalState.ts
Improves modal performance by preventing portalling until actually necessary. Now our dom has wayy fewer elements on the page.
=> [C-4055] Improve modal and popover performance

packages/web/src/components/animated-button/AnimatedButtonProvider.tsx, packages/web/src/components/bottom-bar/BottomBar.tsx, packages/web/src/components/bottom-bar/buttons/ExploreButton.tsx, packages/web/src/components/bottom-bar/buttons/FeedButton.tsx, packages/web/src/components/bottom-bar/buttons/LibraryButton.tsx, packages/web/src/components/bottom-bar/buttons/ProfileButton.tsx, packages/web/src/components/bottom-bar/buttons/TrendingButton.tsx, packages/web/src/components/drawer/Drawer.tsx, packages/web/src/components/nav/desktop/NavHeader.tsx, packages/web/src/components/nav/desktop/NavPopupMenu.tsx, packages/web/src/pages/sign-in-page/SignInPage.tsx
Some improvements/fixes I encountered while trying to write playwright tests.
- Adds accessible labels to nav elements for test navigation (and general accessibility, obviously)
- Fixes mobile web modal not translating properly
web:stage
=> Misc accessibility improvements + mobile drawer fix

packages/discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/web3.ts
=> boost relay retries and address in logging

packages/ddex/ingester/parser/ern38x.go
Makes the DDEX parser first attempt to match SubGenre, and then GenreText. This now works for an arbitrary number of Genre elements because DDEX says there may be more than one.
=> [PROTO-1718] Parse DDEX subgenre and handle multiple genre elements

packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/redis.ts
Expire cached Solana transactions coming from the Solana Relay
=> Expire cached Solana transactions

packages/web/src/components/withdraw-usdc-modal/components/PrepareTransfer.tsx
=> Fix prepare transfer copy

packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/antiAbuse.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/contextInjector.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/errorHandler.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/logging.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimiter.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/validator.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts
adds a child logger to each relay request to make tracking EVEN better
running audius-cmd locally and inspecting relay logs
=> add child logger to relay

packages/web/src/common/store/pages/signon/actions.ts
Accidental testing leftover 🙈 
=> Fix sign up toasts not going away

.circleci/src/jobs/@web-jobs.yml, package.json, packages/web/package.json, packages/web/src/app/web-player/WebPlayer.test.tsx, packages/web/src/common/store/cache/store.test.js, packages/web/src/common/store/pages/audio-rewards/store.test.ts, packages/web/src/common/store/player/store.test.js, packages/web/src/common/store/queue/store.test.js, packages/web/src/common/store/social/collections/store.test.js, packages/web/src/common/store/social/tracks/store.test.js, packages/web/src/common/store/social/users/store.test.js, packages/web/src/common/store/upload/sagas.test.ts, packages/web/src/hooks/useImageSize.test.tsx, packages/web/src/services/audio-player/AudioPlayer.test.js, packages/web/src/store/lineup/store.test.js, packages/web/src/utils/route/collectionRouteParser.test.js, packages/web/src/utils/route/trackRouteParser.test.js, packages/web/src/utils/route/userRouteParser.test.js, packages/web/vite.config.ts
Disables failing web-tests with associated linear tickets to get CI green
=> Disable failing web-tests

packages/web/src/components/data-entry/ContextualMenu.tsx, packages/web/src/components/modal-radio/ModalRadioItem.tsx, packages/web/src/pages/upload-page/components/TracksPreview.tsx, packages/web/src/pages/upload-page/fields/AccessAndSaleMenuFields.tsx, packages/web/src/pages/upload-page/fields/BoxedTextField.tsx, packages/web/src/pages/upload-page/fields/CollectionTrackField.tsx, packages/web/src/pages/upload-page/fields/ReleaseDateField.tsx, packages/web/src/pages/upload-page/fields/ReleaseDateFieldLegacy.tsx, packages/web/src/pages/upload-page/fields/download-availability/DownloadAvailability.tsx, packages/web/src/pages/upload-page/fields/stream-availability/SpecialAccessFields.tsx, packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx
Fixes various issues with upload body text not rendering with the correct values. Our Text component doesn't require variant, which is how these fell through the cracks during the migration
=> Fix upload body text

packages/identity-service/src/solana-client.js
Removes priority fee from track listens due to influx of spending
It has not
=> Remove priority fee from track listens

packages/web/src/components/tooltip/Tooltip.tsx, packages/web/src/hooks/useTabs/useTabs.tsx
Small update to only render the children of the tooltip on the server-side
=> Update Tooltip component to render children on server-side

packages/identity-service/src/solana-client.js
Quick lint fix which was failing the build.
Whitespace change only.
passes `npm run verify`
=> Whitespace lint fix for identity

packages/common/src/models/SsrPageProps.ts, packages/common/src/store/cache/collections/reducer.ts, packages/common/src/store/cache/users/reducer.ts, packages/common/src/store/pages/collection/reducer.ts, packages/common/src/store/pages/profile/reducer.ts, packages/common/src/store/reducers.ts, packages/common/src/utils/urlUtils.ts, packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx, packages/web/src/ssr/collection/+Page.ts, packages/web/src/ssr/collection/+onBeforeRender.ts, packages/web/src/ssr/collection/route.ts, packages/web/src/ssr/profile/+route.tsx, packages/web/src/ssr/track/+route.tsx, packages/web/src/ssr/util.ts
Setting up the server side for rendering the collection page
Manual testing. collections are seeded in the store properly
=> [C-4071] Set up the collection page for SSR

packages/web/src/components/collection/desktop/CollectionHeader.tsx, packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
- Show premium content dog ear on collection page tile
- Add feature flag to `GatedContentSection` on collection page
=> [PAY-2625, PAY-2618] Show dog ear on collection page

packages/web/e2e/auth.setup.ts, packages/web/e2e/signUp.test.ts
=> Disable sign up referral e2e test till it can be refactored

packages/web/src/ssr/util.ts
Small update to make sure that the server is not mistaking certain routes for track routes
=> [C-4211] Add non SSR paths to makePageRoute function

packages/libs/src/services/solana/transactionHandler.ts
I added this log to help debug things in this PR #7910, we should remove it because it's very spammy.
=> Remove spammy log from transaction handler

packages/common/src/services/collectibles-provider/EthereumCollectiblesProvider.ts, packages/common/src/services/collectibles-provider/SolanaCollectiblesProvider.ts, packages/common/src/services/collectibles-provider/ethCollectibleHelpers.ts, packages/common/src/services/collectibles-provider/solCollectibleHelpers.ts, packages/common/src/services/collectibles-provider/types.ts, packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx, packages/mobile/src/screens/profile-screen/constants.ts, packages/mobile/src/screens/profile-screen/utils.ts, packages/web/src/components/collectibles/components/CollectibleDetailsModal.tsx, packages/web/src/components/image-selection/ImageSelectionPopup.jsx, packages/web/src/pages/audio-rewards-page/Tiers.tsx, packages/web/src/pages/profile-page/ProfilePageProvider.tsx, packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx, packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
- Remove silver badge requirement for collectibles
- Block known bad collectibles and collections
- Fix last transferred date
=> [PAY-2648] Improve state of collectibles and their collections

packages/web/src/components/collection/desktop/Artwork.tsx, packages/web/src/components/collection/mobile/CollectionHeader.jsx, packages/web/src/components/profile-picture/ProfilePicture.jsx, packages/web/src/components/track/GiantArtwork.tsx, packages/web/src/pages/profile-page/components/mobile/GrowingCoverPhoto.tsx, packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx, packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Small PR, Forgot to add these before
N/A
=> [C-4225] Add alt text to new StaticImages

packages/discovery-provider/src/api/v1/utils/extend_notification.py, packages/discovery-provider/src/challenges/challenge_event_bus.py, packages/discovery-provider/src/queries/get_collection_library.py, packages/discovery-provider/src/queries/get_feed.py, packages/discovery-provider/src/queries/get_undisbursed_challenges.py, packages/discovery-provider/src/tasks/entity_manager/entities/track.py, packages/discovery-provider/src/tasks/generate_trending.py, packages/discovery-provider/src/tasks/index_payment_router.py, packages/discovery-provider/src/utils/redis_metrics.py, packages/discovery-provider/src/utils/varint.py
Lint-only changes that are automatically applied when running `scripts/lint.sh`
=> Lint changes for discovery-provider

packages/harmony/src/components/text/Text/Text.tsx, packages/harmony/src/components/text/Text/types.ts, packages/mobile/src/harmony-native/components/Text/Text.tsx, packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx
=> Add textTransform prop to harmony Text

packages/discovery-provider/scripts/start.sh, packages/discovery-provider/src/app.py, packages/discovery-provider/src/monitors/monitoring_queue.py, packages/discovery-provider/src/tasks/aggregates/__init__.py, packages/discovery-provider/src/tasks/cache_current_nodes.py, packages/discovery-provider/src/tasks/cache_entity_counts.py, packages/discovery-provider/src/tasks/cache_trending_playlists.py, packages/discovery-provider/src/tasks/cache_user_balance.py, packages/discovery-provider/src/tasks/index_aggregate_monthly_plays.py, packages/discovery-provider/src/tasks/index_challenges.py, packages/discovery-provider/src/tasks/index_eth.py, packages/discovery-provider/src/tasks/index_hourly_play_counts.py, packages/discovery-provider/src/tasks/index_latest_block.py, packages/discovery-provider/src/tasks/index_metrics.py, packages/discovery-provider/src/tasks/index_oracles.py, packages/discovery-provider/src/tasks/index_profile_challenge_backfill.py, packages/discovery-provider/src/tasks/index_rewards_manager.py, packages/discovery-provider/src/tasks/index_solana_plays.py, packages/discovery-provider/src/tasks/index_spl_token.py, packages/discovery-provider/src/tasks/index_trending.py, packages/discovery-provider/src/tasks/prune_plays.py, packages/discovery-provider/src/tasks/publish_scheduled_releases.py, packages/discovery-provider/src/tasks/update_aggregates.py, packages/discovery-provider/src/tasks/update_clique_signers.py, packages/discovery-provider/src/tasks/user_listening_history/index_user_listening_history.py, packages/discovery-provider/src/tasks/vacuum_db.py
This reverts commit 370d127b17a42c23ab45701ede4d0b2e545e77d9.
Reverting because we're seeing instability in these jobs.
=> Revert "ONC-54: indexer concurrency (#7933)"

packages/common/src/utils/dayjs.ts
Need to add this back since we're still using this in web, should fix CI errors.
https://github.com/AudiusProject/audius-protocol/pull/7981#issuecomment-2029987478
=> Add timezone back

packages/common/src/models/Collectible.ts, packages/common/src/services/collectibles-provider/EthereumCollectiblesProvider.ts, packages/common/src/services/collectibles-provider/ethCollectibleHelpers.ts, packages/mobile/src/components/collectible-details-drawer/CollectibleMedia.tsx, packages/web/src/components/collectibles/components/CollectibleDetails.tsx, packages/web/src/components/collectibles/components/CollectiblesPage.tsx, packages/web/src/components/collectibles/ethCollectibleHelpers.ts, packages/web/src/utils/imageProcessingUtil.ts, packages/web/src/workers/gifPreview.worker.js
* Support animated web3 as a new type
* Comment out transfers (they really slow things down and I think it's not very necessary)
* Fix rerendering issues and have collectible details tiles load top to bottom
=> Misc improvements to saliou's nft PR

packages/web/src/ssr/+onRenderClient.tsx, packages/web/src/ssr/+passToClient.tsx, packages/web/src/ssr/index/+route.ts, packages/web/src/ssr/util.ts
Updated to turn off client hydration for crawler, but keeps the toggle to manually turn it off
=> [C-4233] Turn off client side hydration for crawlers

packages/common/src/services/collectibles-provider/solCollectibleHelpers.ts, packages/common/src/utils/dayjs.ts
Block spam nfts
Also fix timezone double import
local web dapp vs prod
=> Block spam nfts

packages/identity-service/src/solana-client.js
=> Priority listens

packages/discovery-provider/ddl/migrations/0065_fix_unlisted_scheduled_releases.sql
Following up https://github.com/AudiusProject/audius-protocol/pull/8012
Correcting tracks that should have been marked as scheduled releases. The publishing job will take care of the rest.
Ran migration on sandbox.
=> Correct unlisted scheduled releases

packages/web/src/app/web-player/WebPlayer.jsx
Small change to remove AppRedirectPopover for crawlers
This works bc we do not hydrate on the client side for crawlers anymore so this will never be rendered
=> [C-4060] Remove Open in Audius App drawer on web mobile for crawlers

docs/docs/distributors/self-serve/run-a-ddex-server.mdx, docs/docusaurus.config.js
+ minor fix to distributors and edit url
=> [DVRL-24] Keep top tab highlighted

packages/mobile/dapp-store/package.json, packages/mobile/dapp-store/pnpm-lock.yaml
Updates dapp-store to latest, which should fix deployment error
=> [C-4241] Upgrade dapp-store-cli to latest

packages/mobile/src/components/core/TextInput.tsx
updated the flex alignment to position it at the end
=> [C-4258] Fix text input end adornment position

.circleci/src/jobs/@web-jobs.yml, .circleci/src/workflows/web.yml
We were using the wrong node version
https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/54568/workflows/a1972686-8185-4a67-bba4-aceeb329aa92/jobs/759467
=> [C-4257] Fix web-dist-win jobs

packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx
=> [PAY-2684] Fix wrap on audio wallet actions

dev-tools/compose/docker-compose.pedalboard.prod.yml, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/config.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/middleware/logging.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/relay.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/tsconfig.json, packages/discovery-provider/plugins/pedalboard/docker/Dockerfile.dev, packages/discovery-provider/plugins/pedalboard/docker/Dockerfile.prod, packages/libs/src/sdk/services/Solana/programs/ClaimableTokensClient/ClaimableTokensClient.ts, packages/web/src/services/audius-sdk/solana.ts
Shotgun blasts the configured RPC nodes every 2s for up to a minute or until the blockhash expires or the nonce is invalid.
Also fixes a myriad of other Solana Relay issues - see commit messages
Tested locally using tipping
=> [PAY-2677] Retries for Discovery Solana Relay

packages/web/src/components/track/DownloadRow.tsx, packages/web/src/components/track/DownloadSection.tsx, packages/web/src/pages/upload-page/fields/StemsAndDownloadsMenuFields.tsx
Remove the toggles in the upload and download flows for the stems and track
Manually tested. Upload and download still works
=> [C-4226] Remove lossless toggle in upload flow and download section on track

packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx, packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Clear results whenever we navigate to the search screen on mobile
(Also small update to fix padding around tags)
=> [C-4252] Update search screen navigation to clear search on mobile

packages/common/src/hooks/purchaseContent/usePurchaseContentFormConfiguration.ts, packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/store/notifications/types.ts, packages/common/src/utils/contentTypeUtils.ts, packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseBuyer.ts, packages/mobile/src/screens/notifications-screen/Notifications/USDCPurchaseBuyerNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/USDCPurchaseSellerNotification.tsx, packages/web/src/common/store/notifications/parseAndProcessNotifications.ts, packages/web/src/components/notification/Notification/USDCPurchaseBuyerNotification.tsx, packages/web/src/components/notification/Notification/USDCPurchaseSellerNotification.tsx
Adds support for album purchase/sale notifications on web + mobile.
web + ios on local stack
web
mobile
=> [PAY-2652] Album purchase/sale notifications

packages/web/e2e/play.test.ts
=> Disable play e2e test

packages/web/src/common/store/player/sagas.ts
Small update to fix hitting the prev button when previewing a premium track
=> [C-4268] Fix player sagas prev functionality for premium track previews

packages/libs/src/sdk/api/users/UsersApi.ts
=> remove unused import

packages/ddex/publisher/src/services/publisherService.ts
https://linear.app/audius/issue/PROTO-1731/retry-logic
=> ddex: limit publisher to 3 retries

packages/common/src/hooks/purchaseContent/usePurchaseContentFormConfiguration.ts
ESLint vscode extension was broken!
=> Fix missing isTrack dependency (lint change)

packages/web/e2e/editCollection.test.ts, packages/web/src/components/usdc-purchase-details-modal/USDCPurchaseDetailsModal.tsx, packages/web/src/components/usdc-purchase-details-modal/components/AlbumSaleModalContent.tsx, packages/web/src/components/usdc-purchase-details-modal/components/TrackSaleModalContent.tsx
Add two small e2e tests for premium album editing since critical path (deals with $$$); albeit a rare one
=> [PAY-2687] E2E tests for premium album edits

packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/validator.ts
protects relay against users with multiple
=> require handle_lc in users query

packages/ddex/ingester/parser/ern38x.go
Use `*int` for preview start and end points. `int` defaults to 0; we don't want to erroneously pass a 0s preview start time if a preview start time was not specified
e2e tests
=> Fix preview start and end point parsing

packages/discovery-provider/src/queries/reactions.py, packages/web/src/common/store/ui/reactions/sagas.ts
discovery only tests didn't catch this
running `npm run web:stage` and seeing indexing complete on discovery
=> ACDC tip notifs: encode hash id

.circleci/config.yml, .circleci/src/@continue_config.yml, .circleci/src/workflows/ddex-e2e.yml, .circleci/src/workflows/ddex-webapp.yml, packages/ddex/ingester/common/sdk_types.go, packages/ddex/ingester/common/types.go, packages/ddex/ingester/e2e_test/e2e_test.go, packages/ddex/ingester/parser/ern38x.go, packages/ddex/ingester/parser/parser.go, packages/ddex/publisher/src/models/pendingReleases.ts, packages/ddex/publisher/src/services/publisherService.ts
Redo https://github.com/AudiusProject/audius-protocol/pull/7987 after latest refactor rather than attempting to rebase.
e2e tests
=> Parse DDEX deals (redo after refactor)

docs/docs/distributors/specification/deal-types.mdx, packages/ddex/README.md
Add instructions for creating external policy & user
Added bash command
=> Add more instructions for external users

packages/mobile/src/components/lineup-tile/TrackTile.tsx, packages/mobile/src/components/track-list/TrackListItem.tsx, packages/mobile/src/screens/collection-screen/CollectionScreen.tsx, packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx, packages/web/src/common/store/pages/audio-rewards/sagas.ts, packages/web/src/common/store/tipping/sagas.ts, packages/web/src/common/store/ui/reactions/sagas.ts, packages/web/src/components/actions-tab/ActionsTab.jsx, packages/web/src/components/collection/desktop/OwnerActionButtons.tsx, packages/web/src/components/track/GiantTrackTile.tsx, packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx
Can anyone confirm if these are showing for everyone or just me? I saw it on @DejayJD's PR https://github.com/AudiusProject/audius-protocol/pull/8111 as well so figured I'd commit them
Lint fixes for web and mobile
passes local lint
=> Lint fixes for main

docs/docs/distributors/specification/deal-types.mdx
=> Fix docs nit

packages/common/src/models/Search.ts, packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
Fixes some collection screen types related to ddex_app and stream_conditions
=> Fix collection screen types

packages/web/src/components/collectibles/components/CollectiblesPage.tsx
Was getting `Uncaught TypeError: Cannot read properties of undefined (reading ‘length’)` for `megrigden` which broke the web dapp
=> Fix nft undefined bug

packages/ddex/webapp/server/.eslintrc.cjs, packages/ddex/webapp/server/src/app.ts, packages/ddex/webapp/server/src/controllers/collectionController.ts, packages/ddex/webapp/server/src/index.ts, packages/ddex/webapp/server/src/routers/collectionRouters.ts, packages/ddex/webapp/server/src/routers/index.ts, packages/ddex/webapp/server/src/routers/uploadRouter.ts, packages/ddex/webapp/server/src/services/dbService.ts, packages/ddex/webapp/server/src/services/s3.ts, packages/ddex/webapp/server/src/services/sdkService.ts, packages/ddex/webapp/server/src/trpc.ts, packages/ddex/webapp/server/src/userSchema.ts
Use audius eslint config in ddex webapp client
Lint passes!
=> Fix ddex webapp client lint

packages/web/src/common/store/upload/sagas.ts
In #8111 I ran into an issue purchasing a track on an album. I realized the issue was that I was trying to call a generator method from a normal fn
Uploaded a prem album and purchased a track within it
=> Fix premium album uploads

packages/mobile/android/app/build.gradle, packages/mobile/ios/AudiusReactNative/Info.plist
Upgrades native app version for full app release
=> Upgrade native version to 1.1.94

packages/discovery-provider/plugins/verified-uploads/src/handlers/tracks.js
To prevent confusion about which tracks have actually been published.
=> Filter out stems and unlisted tracks from verified uploads bot

package-lock.json, packages/harmony/package.json, packages/harmony/src/components/button/Button/Button.stories.tsx, packages/harmony/src/components/input/TextInput/TextInput.stories.tsx
See if chromatic updates figma
=> Test figma code-connect

packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx
Small copy change request to add before this weeks release
web:stage
=> fix: Minor copy change in album upload flow

package-lock.json, packages/harmony/package.json, packages/harmony/src/components/button/Button/Button.stories.tsx, packages/harmony/src/components/input/TextInput/TextInput.stories.tsx
This reverts commit bc84708ab217b73713f4d2acb5a7a46e76b9d5f8.
=> Revert "Test figma code-connect (#8139)"

packages/discovery-provider/src/api/v1/models/users.py, packages/discovery-provider/src/queries/get_challenges.py
Add missing response fields.
Similar to Isaac's https://github.com/AudiusProject/audius-protocol/pull/8144 but strategically don't want to change the challenges.json file just yet. We may be able to use that for release. Will discuss amongs team.
=> Update cooldown days in response

.changeset/lucky-otters-look.md, packages/common/src/api/user.ts, packages/discovery-provider/src/api/v1/helpers.py, packages/discovery-provider/src/api/v1/transactions.py, packages/discovery-provider/src/queries/get_usdc_transactions_history.py, packages/libs/src/sdk/api/generated/default/models/Playlist.ts, packages/libs/src/sdk/api/generated/full/apis/UsersApi.ts, packages/libs/src/sdk/api/generated/full/models/PlaylistFull.ts, packages/libs/src/sdk/api/generated/full/models/PlaylistFullWithoutTracks.ts, packages/web/src/pages/pay-and-earn-page/components/WithdrawalsTab.tsx
Fixed purchases showing on withdrawals tab.
Makes the endpoint filter to withdrawals and "transfers" and updates SDK to allow multiple type filters
=> [PAY-2666] Only show withdrawals on withdrawals tab

monitoring/healthz/src/pages/Nodes.tsx
=> Fix storage progress bar

docs/docs/distributors/specification/metadata.mdx
updated information on metadata spec for `releaseDate` DDEX field mappings
=> DDEX - update releaseDate docs

packages/ddex/ingester/README.md, packages/ddex/ingester/cmd/sync/main.go
Two main in cmd
```
go run ./cmd/sync s3://ddex-prod-x-raw/20240305090456555
```
=> Fix ddex build

packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
=> Fix web-init

dev-tools/setup.sh
These errors were being swallowed. Now they display properly
=> Echo setup.sh errors to stderr 

packages/common/src/store/ui/related-artists/sagas.ts
I changed this line to test out some feature work and did not follow my normal procedure of an obnoxious TODO to stop myself from checking it in. 🤦 
[Source of change](https://github.com/AudiusProject/audius-protocol/commit/e19037a8075f0b47e9e417300783b9a4e354bcd4#diff-d50cb7dec091553fd90fb86da142b1a097cf5b93733407b581121dde06f2e4e2R40)
=> Undo a dev override that got checked in

docs/docs/distributors/specification/overview.mdx
=> [PROTO-1777] Support updates/deletes in ddex docs

packages/web/src/pages/dashboard-page/store/selectors.ts
=> [PAY-2741] Artist dashboard album stat

packages/discovery-provider/scripts/register.py
Forgot to rever this as part of https://github.com/AudiusProject/audius-protocol/pull/8196/files#diff-ff567d30e0a3d8384d28e18d3909608a5f9b8f072ac6b62ffe5431463843ee33
=> Fix register.py ABIs location

packages/web/src/components/tracks-table/TracksTable.tsx
Not sure how this didn't break main
=> TracksTable lint fix

package-lock.json, packages/ddex/publisher/README_SCRATCH.md, packages/ddex/publisher/package.json, packages/ddex/publisher/scratch/cli.ts, packages/ddex/publisher/scratch/s3poller.ts, packages/ddex/publisher/scratch/s3sync.ts
=> DDEX single proc s3 sync addition

packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
Not sure if this was missed in recent PR or... but it is now consistent with mobile and fixes issue Sammie saw.
=> [PAY-2616] Fix CTA for reward panel

packages/discovery-provider/src/tasks/cache_current_nodes.py
Should fix:
```
File "/audius-discovery-provider/src/tasks/cache_current_nodes.py", line 55, in cache_current_nodes_task
content_node_endpoints, content_node_wallets = get_all_content_nodes()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
```
=> cache_current_nodes: Unpack every field from tuple

packages/discovery-provider/integration_tests/tasks/entity_manager/test_grant_entity_manager.py, packages/discovery-provider/src/tasks/entity_manager/entities/grant.py, packages/discovery-provider/src/tasks/entity_manager/entity_manager.py, packages/discovery-provider/src/tasks/entity_manager/utils.py
- Allow parent users to approve/reject/delete grants on behalf of their children users
- Add more tests for grant actions
- Discovery integration tests
=> Allow delegated approve/reject/delete grant, add more grant indexing tests [C-4311]

packages/mobile/android/app/build.gradle, packages/mobile/ios/AudiusReactNative/Info.plist
Bump Android to 1.1.421
Bump iOS to 1.1.95
=> Bump mobile app versions

packages/web/scripts/workers-site/index.js, packages/web/src/ssr/util.ts
=> [C-4275] Add google-inspectiontool to crawler regex

packages/discovery-provider/src/utils/helpers.py
=> Add cloudflare ip check fix

packages/web/src/common/store/notifications/checkForNewNotificationsSaga.ts
If notifs endpoint errors, all sagas & app crash
Local simulator
=> [ONC-84] Add try/catch

packages/harmony/src/components/text-link/TextLink.tsx
Fixes issue where text-link hover and press animations were not transitioning.
=> [C-4270] Fix text-link transition

packages/harmony/src/components/input/TextInput/TextInput.module.css, packages/harmony/src/components/input/TextInput/TextInput.tsx
Fixes regression from https://github.com/AudiusProject/audius-protocol/pull/8176. Essentially reverts and adds the padding fix to the "small" variant
=> Fix text-input spacing

.circleci/src/commands/@web-commands.yml, .circleci/src/workflows/web.yml
Cloudflare is complaining because we hit our 25 MB upload limit. This is because we weren't moving the ssr sourcemaps to the s3 bucket like the spa sourcemaps
=> Fix ssr sourcemap upload

packages/mobile/android/app/build.gradle
Bump for this change https://github.com/AudiusProject/audius-protocol/pull/8279
=> Bump android version for manifest changes

packages/ddex/entrypoint/src/App.tsx, packages/ddex/entrypoint/src/components/DistributorCard.tsx, packages/ddex/entrypoint/src/distributors/stage.json
Minor UI updates:
* prof pic
* hover states on pills
* fix margins
```
npm run start:stage
```
=> [PROTO-1801] Add prof pic, hover states

packages/mobile/android/app/build.gradle
=> Bump android build number for release-client-v1.5.78

packages/ddex/processor/src/publishRelease.ts, packages/embed/src/components/app.jsx, packages/web/src/components/user-card/UserCard.test.tsx
=> Fix lint items

packages/web/src/common/store/player/sagas.ts, packages/web/src/components/user-card/UserCard.test.tsx
=> Jail broken test

packages/common/src/store/purchase-content/sagas.ts
Auto-favorite tracks in a purchased album so they get added to library.
Web stage
=> [PAY-2802] Auto-favorite tracks in purchased album

packages/web/src/app/web-player/ServerWebPlayer.tsx, packages/web/src/components/header/mobile/HeaderContextProvider.tsx, packages/web/src/components/link/ServerUserLink.tsx, packages/web/src/components/mobile-page-container/ServerMobilePageContainer.tsx, packages/web/src/components/nav/ServerNavigator.tsx, packages/web/src/components/nav/mobile/ServerNavBar.tsx, packages/web/src/components/play-bar/desktop/PlayBar.module.css, packages/web/src/components/play-bar/desktop/ServerPlayBar.tsx, packages/web/src/components/scroll-provider/ScrollProvider.tsx, packages/web/src/components/track/ServerGiantTrackTile.tsx, packages/web/src/components/user-generated-text/ServerUserGeneratedText.tsx, packages/web/src/components/user-generated-text/index.ts, packages/web/src/hooks/useInstanceVar.ts, packages/web/src/pages/server-track-page/ServerTrackPage.tsx, packages/web/src/pages/server-track-page/mobile/ServerActionButtonRow.tsx, packages/web/src/pages/server-track-page/mobile/ServerHiddenTrackHeader.tsx, packages/web/src/pages/server-track-page/mobile/ServerStatsButtonRow.tsx, packages/web/src/pages/server-track-page/mobile/ServerTrackPage.tsx, packages/web/src/pages/server-track-page/mobile/ServerTrackPageHeader.tsx, packages/web/src/pages/track-page/utils.ts, packages/web/src/ssr/track/onRenderHtml.tsx
Adding the ssr mobile track page small bundle flow
SSR:
SPA:
Lots of testing and bundle analysis
=> [C-4238, C-4318] Add ssr small bundle flow for mobile track page

packages/common/src/store/playlist-library/helpers.ts, packages/web/src/components/collection/components/AlbumDetailsText.tsx, packages/web/src/components/collection/desktop/Artwork.tsx, packages/web/src/components/collection/desktop/CollectionHeader.tsx, packages/web/src/components/collection/desktop/FavoriteButton.tsx
* No display of name/image
* Broken favorite button
* Icon was not setting gradient props correctly
```
```
http://localhost:3001/explore/most-loved
=> [QA-971] Fix smart collections

packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx, packages/web/src/pages/upload-page/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseFields.tsx
- Show validation errors on albumTrackPrice field during upoad
- Slight hack to allow empty value through validation (this field is optional)
local web working
=> [PAY-2779] Fix validation for albumTrackPrice

packages/web/src/components/link/UserLink.tsx, packages/web/src/components/track/LockedContentDetailsTile.module.css, packages/web/src/components/track/LockedContentDetailsTile.tsx
Updates to match design (previously the artist popover username had wrong font, color).
=> [PAY-2822] Convert LockedContentDetailsTile to Harmony

packages/web/src/components/collection/desktop/CollectionHeader.tsx
=> [PAY-2772] Fix collection description text size

packages/discovery-provider/integration_tests/tasks/entity_manager/test_developer_app_entity_manager.py, packages/discovery-provider/src/tasks/entity_manager/entities/developer_app.py, packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
Implement, mostly copy paste, DeveloperApp update behavior.
```
>> pytest integration_tests/tasks/entity_manager/test_developer_app_entity_manager.py::test_developer_app_update
```
=> [PAY-2764] Implement DeveloperApp Update entity manager action

packages/web/src/pages/pay-and-earn-page/components/PurchasesTable.tsx, packages/web/src/pages/pay-and-earn-page/components/SalesTable.tsx
For proper ellipsization of the artist name column
=> [PAY-2794] Use UserLink for purchases/sales tables

packages/mobile/dapp-store/package.json, packages/mobile/dapp-store/pnpm-lock.yaml
Upgrades dapp-store-cli to latest to fix saga deploy
=> Upgrade dapp-store to 0.8.1

packages/discovery-provider/src/queries/get_collection_library.py, packages/discovery-provider/src/queries/get_track_library.py, packages/web/src/pages/saved-page/components/desktop/AlbumsTabPage.tsx, packages/web/src/pages/saved-page/components/desktop/LibraryCategorySelectionMenu.tsx
Adds a "purchased" selectable filter to the library albums tab.
Local stack
=> [PAY-2801] Purchased selectable filter in library albums

packages/common/src/api/developerApps.ts, packages/web/src/components/preload-image/PreloadImage.tsx, packages/web/src/pages/settings-page/components/desktop/AuthorizedApps/AuthorizedAppListItem.tsx, packages/web/src/pages/settings-page/components/desktop/DeveloperApps/DeveloperAppListItem.tsx, packages/web/src/pages/settings-page/components/desktop/DeveloperApps/EditAppPage.tsx
Small things I noticed on staging
* Wrong image size / wrong border radius
* Edits not persisting on same session (requiring reload)
* Use preload image component for nicer render
```
```
Edited a few apps
=> [PAY-2859] Fix bugs in edit app flow

packages/web/src/components/tracks-table/TracksTable.tsx, packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
As title suggests
Purchaser
Owner
Prem album
=> [PAY-2738] Public album with prem track always shows buy button

packages/web/src/components/card/Card.tsx, packages/web/src/components/collection/CollectionCard.test.tsx, packages/web/src/components/collection/CollectionCard.tsx, packages/web/src/components/notification/Notification/components/UserNameLink.module.css, packages/web/src/components/notification/Notification/components/UserNameLink.tsx, packages/web/src/components/track/GatedContentSection.tsx, packages/web/src/components/track/GiantTrackTile.module.css, packages/web/src/components/user-badges/UserBadges.tsx
Fixes collection card title centering
Fixes collection card owner conditions
Fixes issue with user-badges causing slight centering issue
=> [PAY-2861] CollectionCard fixes

packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ClaimAllRewardsModal.tsx
Was not closing the claim all modal on clicking done.
local v stage
=> Close modal on done

packages/common/src/utils/challenges.ts
=> [PAY-2812] Change spend to earn challenge copy

.circleci/src/commands/@docker-commands.yml, .circleci/src/workflows/discovery.yml, .circleci/src/workflows/release.yml
Add CI steps for pedalboard crm plugin
=> Add CI for crm plugin

dev-tools/compose/docker-compose.yml, packages/compose/package.json
=> Fix crm CI

packages/discovery-provider/plugins/pedalboard/apps/app-template/src/index.ts, packages/discovery-provider/plugins/pedalboard/apps/crm/src/index.ts
This works in dev, but not in a production built container
Tested on prod 😸
=> Fix pedalboard apps template import

packages/web/src/common/store/account/sagas.js
Wallet could be undefined, so this adjusts the logic to account for that
=> Fix wallet matches check

packages/mobile/src/components/track-list/TrackList.tsx, packages/mobile/src/components/track-list/TrackListItem.tsx, packages/mobile/src/components/track-list/TrackListItemSkeleton.tsx, packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx, packages/mobile/src/screens/collection-screen/CollectionScreenSkeleton.tsx, packages/mobile/src/screens/favorites-screen/TracksTab.tsx, packages/mobile/src/screens/settings-screen/ListeningHistoryScreen.tsx
Per new designs for collection screens on mobile
skeletons
tracklist
=> [PAY-2763] Remove dividers on mobile collection screens

packages/harmony/src/components/button/Button/Button.tsx, packages/web/src/assets/styles/ant-overrides.css
Overrides antd default which was setting this buttons color.
Tested on `npm run web:stage` and uploaded a track.
=> QA-1093: fix upload button dark mode

packages/mobile/src/screens/notifications-screen/Notifications/USDCPurchaseBuyerNotification.tsx, packages/web/src/components/notification/Notification/USDCPurchaseBuyerNotification.tsx
Shouldn't capitalize the entity type
=> [PAY-2887] Fix purchase notification twitter share copy

packages/libs/src/sdk/api/users/UsersApi.ts
Missing from https://github.com/AudiusProject/audius-protocol/pull/7774 because these methods are copied
```
```
and download of csv
=> [PAY-2885] Remove require statements on encoded params

packages/mobile/android/app/build.gradle, packages/mobile/ios/AudiusReactNative/Info.plist
Required because of fixes in https://github.com/AudiusProject/audius-protocol/pull/8323
On device
=> Bump versions

packages/web/src/components/play-bar/slider/Slider.module.css
Fixes issue where the track/slider have different border-radius, leading to track appearing over the edge of the slider
=> [QA-1214] Fix slider border radius

packages/web/src/components/collection/desktop/CollectionActionButtons.tsx
=> [PAY-2824] Make Collection play button large

packages/web/src/components/collection/desktop/CollectionHeader.tsx
=> [PAY-2899] Fix collection header title becoming centered

docs/docs/node-operator/setup/installation.mdx
- added notes to confirm ssh and port configuration for migrations [preview](https://55336dfc.docs-eaf.pages.dev/node-operator/setup/installation#overview)
- added link to advanced usage guide for installation topography [preview](https://55336dfc.docs-eaf.pages.dev/node-operator/setup/installation#install-audius-ctl)
=> [Docs] - Node Operator install guide updates

packages/common/src/store/pages/audio-rewards/slice.ts, packages/web/src/common/store/pages/audio-rewards/sagas.ts
Total audio claimed number did not update immediately. This PR fixes that.
local web v stage
=> [PAY-2637] Update audio balance on successful rewards claim

packages/web/src/components/create-playlist/PlaylistForm.tsx, packages/web/src/components/data-entry/ContextualMenu.tsx, packages/web/src/pages/upload-page/fields/StemsAndDownloadsCollectionsField.tsx, packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx
**Before:**
**After:**
styles are fixed on local web
=> [PAY-2900] Fix collection upload/edit layout

packages/discovery-provider/src/queries/get_developer_apps.py
Woops!
Didn't feel necessary but will test on stage
=> Add image url to response for developer app request

packages/web/src/components/collection/mobile/CollectionHeader.module.css, packages/web/src/components/collection/mobile/CollectionHeader.tsx, packages/web/src/components/track/mobile/TrackListItem.tsx, packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
- Add dog ear
- Allow playback of premium tracks by tapping the row
- Disallows play of gated tracks that aren't unlocked
local web behaving as expected
=> [PAY-2865] Mobile web collection page fixes

packages/web/src/components/collection/CollectionCard.tsx
Want hover state even tho it navs to the same collection
=> [PAY-2890] Fix hover state on CollectionCard title

packages/web/src/components/tile/Tile.module.css, packages/web/src/components/tile/Tile.tsx, packages/web/src/pages/collection-page/components/desktop/CollectionPage.module.css
Reverts AudiusProject/audius-protocol#8406
This caused some issues I didn't catch; will re-do this change
(e.g.)
=> Revert "Fix dog ear on track page"

packages/discovery-provider/plugins/pedalboard/apps/solana-relay/package.json, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/config.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/utils/ipData.ts
- adds utils for gathering the ip in solana relay
- modifies the readConfig function so it only gets read in once
=> solana relay ip utils

packages/mobile/src/screens/favorites-screen/LibraryCategorySelectionMenu.tsx, packages/web/src/pages/saved-page/components/desktop/LibraryCategorySelectionMenu.tsx
=> [PAY-2960] Change library filter title to Premium

packages/common/src/api/account.ts, packages/common/src/models/Grant.ts, packages/web/src/components/search-users-modal/SearchUsersModal.tsx, packages/web/src/pages/chat-page/components/CreateChatUserResult.tsx, packages/web/src/pages/chat-page/components/useComposeChat.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountListItem.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsManagingYouHomePage.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageSettingsCard.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageSettingsModal.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/ConfirmAccountManagerPage.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/FindAccountManagerPage.tsx, packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
- Implement Accounts You Manage, full UI and functionality
Missing:
- Remove Manager UI/proper audius-query hook
- "Switch to account"
Designs:
https://www.figma.com/file/CvyTTAuwnGFPW8PYCqDpg9/Manager-Mode?type=design&node-id=0-1&mode=design&t=fh4NmYuIZxWSpgfj-0
Locally against stage.
=> [Web] [Common] Accounts You Manage flows; hook up Accounts Managing You to API

packages/common/src/api/account.ts, packages/web/src/components/search-users-modal/SearchUsersModal.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountListItem.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsManagingYouHomePage.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsManagingYouSettingsModal.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageHomePage.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageSettingsModal.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/ConfirmAccountManagerPage.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/RemoveManagerConfirmationContent.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/RemoveManagerConfirmationPage.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/StopManagingConfirmationPage.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/types.ts
Designs: https://www.figma.com/file/CvyTTAuwnGFPW8PYCqDpg9/Manager-Mode?type=design&node-id=2002-14041&mode=design&t=kmC9Umkvj2A3Q2qZ-0
Implement:
- Remove manager flow in Accounts Managing You settings
- Stop managing flor in Accounts You Manage settings
- Reject request using "remove manager" action (since that's what a reject is now)
Locally against stage
=> [Web] Implement Remove Manager flows [Manager Mode ] [PAY-2827]

.circleci/src/jobs/@web-jobs.yml, packages/web/package.json
Fixes sentry source-maps upload in release step
=> [QA-1268] Fix sentry upload

packages/web/src/components/link/UserLink.tsx, packages/web/src/components/track/mobile/ConnectedPlaylistTile.tsx
Also included a small UI fix for the artist name (only wrong style in mobile-web, not sure why)
Did a small qa to see if there are any places i forgot, didn't find any.
=> [PAY-2975] Fix mobile-web premium album overflow options

packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx
Form resets constantly because object reference changes
https://github.com/AudiusProject/audius-protocol/pull/8295/files#diff-f9513867966a00f6e54cc8acb3948153f340f9bb0629253fb0a1415ce96e1373R239-R241
local simulator
=> Fix coinflow default

packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Fixes issue where playlist table didnt include artist names.
Improves column generation logic
=> [QA-1277] Fix missing artist names on playlist tables

packages/mobile/src/components/collection-list/CollectionCard.tsx, packages/mobile/src/components/core/DogEar.tsx, packages/mobile/src/components/track-list/TrackListItem.tsx, packages/mobile/src/harmony-native/components/layout/Paper/Paper.tsx
Improves collection card touch responsiveness on android. The issue was due to animated styles that are not available on android computing uncessarily, leading to tons of logged errors. Additionally fixes issues due to line-heights.
=> [PAY-2980] Improve collection card touch response

packages/mobile/src/components/details-tile/DetailsTile.tsx, packages/mobile/src/components/details-tile/SecondaryStats.tsx, packages/mobile/src/components/details-tile/types.ts, packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Add missing release dates to track screen
=> [QA-1280] Add missing release dates
