AudiusProject/apps

solana-programs/payment-router/Anchor.toml, solana-programs/payment-router/README.md, solana-programs/payment-router/programs/payment-router/src/lib.rs, solana-programs/payment-router/scripts/testRouteAudio.sh, solana-programs/payment-router/scripts/testRouteUsdc.sh, solana-programs/payment-router/tests/constants.ts, solana-programs/payment-router/tests/payment-router.ts, solana-programs/payment-router/yarn.lock
* Set deploy program id to the latest one
* Make tests fully e2e: feepayer -> payment router PDA -> recipients
* Add USDC flavor of test
This code is useful now to be able to see the e2e flow like we would implement client side
```
anchor build
./scripts/testRouteUsdc.sh
```
=> [PAY-2208] Make payment router test e2e

packages/web/vite.config.ts
Fixes issue where all our trending tweet-embed views were broken. This is due to an issue with vite build incompatibility with node-style `require`, which is used in this node_module
Some documentation on the issue:
https://github.com/saurabhnemade/react-twitter-embed/issues/128
https://github.com/vitejs/vite/issues/3409
The comment this fix is based on: 
https://github.com/vitejs/vite/issues/3409#issuecomment-1138202247
Built locally and confirmed on dylan.audius.co
https://dylan.audius.co/
=> [C-3399] Fix trending links and twitter embed

packages/common/src/hooks/useFeatureFlag.ts, packages/harmony/src/components/button/FollowButton/FollowButton.mdx, packages/harmony/src/components/button/FollowButton/FollowButton.stories.tsx, packages/harmony/src/components/button/FollowButton/FollowButton.tsx, packages/probers/cypress/e2e/flaky-test-jail.md, packages/probers/cypress/e2e/signUp.cy.ts, packages/web/src/app/App.tsx, packages/web/src/components/drawer/Drawer.tsx, packages/web/src/components/welcome-modal/WelcomeModal.tsx, packages/web/src/pages/sign-in-page/SignInPage.tsx, packages/web/src/pages/sign-on-page/SignOnPage.tsx, packages/web/src/pages/sign-up-page/SignUpPage.tsx, packages/web/src/pages/sign-up-page/components/NavHeader.tsx, packages/web/src/pages/sign-up-page/components/layout.tsx, packages/web/src/pages/sign-up-page/pages/CreateEmailPage.tsx, packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
Fixes sign-up e2e
- Improves useFeatureFlag (@schottra lets chat)
- Improves FollowButton (@amendelsohn was tricky here so let's chat)
signUp.cy.ts should pass. Additionally going to tackle the mobile flow tomorrow in this pr
=> [C-3403] Fix sign-up e2e

packages/web/src/common/store/queue/sagas.ts
This fixes a bug on mobile where if you allowed the lineup to play through from saved tracks screen, only previews would play even on purchased tracks.
Not sure why this wasn't an issue on web.
Confirmed playing un-purchased tracks still plays the previews (via either allowing autoplay to go through, or from pressing previous/next) on both web and mobile.
Confirmed user is able to play full tracks of own uploaded premium tracks.
Video of fix here - previously when the next track played, it would be a preview.
https://github.com/AudiusProject/audius-protocol/assets/3893871/6f56ec12-b075-4899-a10b-63ec6455d693
=> [PAY-2215] Play full purchased tracks from mobile library

packages/mobile/src/components/audio-balance-pill/AUDIOBalancePill.tsx, packages/web/src/components/audio-balance-pill/AUDIOBalancePill.module.css, packages/web/src/components/audio-balance-pill/AUDIOBalancePill.tsx, packages/web/src/components/nav/desktop/NavPopupMenu.module.css, packages/web/src/components/nav/desktop/NavPopupMenu.tsx, packages/web/src/components/usdc-balance-pill/USDCBalancePill.module.css
Set a min-width for the NavPopupMenu to prevent it from growing once the balances load in.
Tried to use reasonable values for the various min-width's. It results in a wider-than-necessary popup when the user has low balances, but I think that's ok. Also if the user has super high balances the popup could still grow, but I think this is good enough for the majority of users.
Also noticed the $AUDIO balance pill was slightly too small, updated size to match USDC pill.
https://github.com/AudiusProject/audius-protocol/assets/3893871/69121d4b-6c3b-465e-9e11-4f6e231661b3
with larger $AUDIO pill:
=> [PAY-2227] Set min-width for NavPopupMenu

packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx, packages/mobile/src/components/usdc-manual-transfer/USDCManualTransfer.tsx
Per Design's request, make the buy buttons sticky at the bottom when switching content inside the purchase drawer.
https://github.com/AudiusProject/audius-protocol/assets/3893871/878b539d-80c7-447b-be51-acc6e4a43782
=> Make mobile buy buttons stick to bottom

mediorum/server/serve_metrics.go, mediorum/server/server.go
Adds `/internal/logs/pg-upgrade` to display the results of a postgres upgrade on a Content Node.
=> [PROTO-1458] Expose postgres upgrade logs in mediorum

packages/web/src/pages/upload-page/fields/RemixSettingsField/RemixSettingsField.tsx, packages/web/src/pages/upload-page/fields/RemixSettingsField/RemixSettingsMenuFields.tsx
Allow showing remixes for usdc purchase tracks.
Default to showing remixes for public and usdc purchase tracks. Otherwise, if gated, default to hiding remixes.
On local v stage
=> Fix remixes for usdc purchase tracks

packages/discovery-provider/ddl/migrations/0040_rm_track_segments.sql
track_segments is no longer used.
This pr keeps the column but sets all values to `[]` to ensure no downstream breakage.
Benefits:
* reclaim disk space for both postgres + elasticsearch (cids are mostly uncompressable)
* reduce TOAST overhead when selecting from tracks table
* reduce payload size for sending track records to client (cids are mostly uncompressable)
Tested on isaac sandbox.  Tracks table went from 10 GB to 1.8 GB
=> Remove track_segments data, default to []

packages/discovery-provider/src/queries/get_trusted_notifier_discrepancies.py, packages/discovery-provider/src/tasks/update_delist_statuses.py
Since the delist and indexer tasks run async, there is an edge case possible where the indexer overwrites a delist after reading stale data from the users/tracks table, since the entity manager reads then rewrites the entire record (including is_available) when any field needs to be updated. This leads to a "delist discrepancy" - the tracks/users table says the entity available or unavailable in contrast with what the node's delists table says.
Some context:
We already have a query checking for delist discrepancies using the `user_delist_statuses` / `users` and `track_delist_statuses` / `tracks` tables. If there are no discrepancies, the successful result is cached for 12h; if there are discrepancies, the result is cached for 1m . We use this in the health check to mark a node as …
=> Periodically check for and correct trusted notifier discrepancies in DN

packages/discovery-provider/Dockerfile.dev, packages/discovery-provider/Dockerfile.prod
Follow up fix for: https://github.com/AudiusProject/audius-protocol/pull/6841
=> re-add docker copy

packages/discovery-provider/integration_tests/queries/test_get_personal_route_metrics.py, packages/discovery-provider/integration_tests/utils.py, packages/discovery-provider/src/api/v1/root_path.py, packages/discovery-provider/src/solana/solana_client_manager.py, packages/discovery-provider/src/tasks/update_delist_statuses.py
=> Fix discovery lint err

packages/discovery-provider/plugins/pedalboard/apps/relay/src/config/config.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts
`finalPOABlock` was missing, which causes confirmers to try to confirm the response against the wrong number in the db.
=> [PROTO-1478] Add finalPOABlock support to discovery relay

packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
When creating a playlist from a track, then immediately viewing the playlist the playlist would never load. This was because `requireAllTracks` was causing the cache to be ignored because the optimistic playlist did not have a `tracks` field
Fixed by including the `tracks` field in the optimistic playlist
=> [C-2959] Fix creating playlist from track

packages/web/src/components/create-playlist/PlaylistForm.tsx, packages/web/src/pages/upload-page/validation.ts
Editing a playlist immediately after creating was causing a crash because a formik validation error object was being set as a react child.
* Only set artwork object if we have a coverArtUrl
* Fail validation if artwork url is imageBlank, forcing user to set an image if the playlist image is currently the fallback image
Ran through various playlist edit / creation flows on web
=> [C-3332] Fix playlist edit after create

packages/discovery-provider/plugins/pedalboard/apps/relay/src/abi.ts
Some relays don't have json metadata (follows in particular). This breaks the JSON.parse() even though a blank string is still valid json in the spec. https://www.json.org/json-en.html. Since we don't actually parse through the metadata right now there's no need for this parse anyway.
Ran with sandbox script and verified decode abi no longer crashes on follow events.
=> relay: fix error on no metadata

packages/web/src/common/store/pages/signon/actions.ts, packages/web/src/common/store/pages/signon/reducer.js, packages/web/src/common/store/pages/signon/types.ts, packages/web/src/pages/sign-up-page/components/HandleField.tsx, packages/web/src/pages/sign-up-page/components/SignupFlowInstagramAuth.tsx, packages/web/src/pages/sign-up-page/components/SignupFlowTikTokAuth.tsx, packages/web/src/pages/sign-up-page/components/SignupFlowTwitterAuth.tsx, packages/web/src/pages/sign-up-page/components/SocialMediaLoading.module.css, packages/web/src/pages/sign-up-page/components/SocialMediaLoading.tsx, packages/web/src/pages/sign-up-page/components/SocialMediaLoginOptions.tsx, packages/web/src/pages/sign-up-page/components/layout.tsx, packages/web/src/pages/sign-up-page/hooks/useSocialMediaLoader.ts, packages/web/src/pages/sign-up-page/pages/CreateEmailPage.tsx, packages/web/src/pages/sign-up-page/pages/CreateLoginDetails.tsx, packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx, packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx, packages/web/src/pages/sign-up-page/utils/determineAllowedRoutes.ts, packages/web/src/pages/sign-up-page/utils/handleSchema.ts
- Social media connect loading states on Create Email and Pick Handle pages
- Fix another allowedRoutes issue affecting the social media sign up flow
- If user navigates back to the page where they connected their social media, reset the state (so it’s as if they never connected it on that page)
- Add handle display to Create Login Details page
- Add in proper error message for if the handle is too long
- Fix existing email not loaded in if you nav back to "Create Login Details" page
=> Polish social media flow, other QA [C-3418]

packages/discovery-provider/Dockerfile.dev, packages/discovery-provider/integration_tests/tasks/test_index_rewards_manager.py
It's not needed for the dev container because it is "thin" as they say.
The prod one is "thicc" so make sure it keeps COPY . .
```
```
=> Re-remove copy . . from discovery dev dockerfile

packages/mobile/src/components/payment-method/PaymentMethod.tsx
Previously the radio items in `PurchaseMethod` were not selectable on Android.
Tested that they work on both android and ios emulators.
=> [PAY-2245] Fix purchase radio buttons on android

packages/discovery-provider/src/tasks/index_rewards_manager.py, packages/discovery-provider/src/tasks/index_solana_plays.py
Fixes bug in https://github.com/AudiusProject/audius-protocol/pull/6812 - previously the indexer would throw `SolanaFetchError`, but then that PR try/catch'd it which breaks assumptions downstream: instead of skipping the tx it would cause an infinite error loop.
Untested
=> Fix rewards + plays indexing

svgo.config.js
Fixes svgo viewBox defaults where viewBox is removed if height/width is the same. This totally breaks scaling though...
https://github.com/svg/svgo/issues/1128#issuecomment-1403517189
Tested on harmony, web, and native
=> Fix svgo viewBox defaults

packages/common/src/services/remote-config/defaults.ts, packages/common/src/services/remote-config/types.ts, packages/web/src/common/store/lineup/sagas.js
Change the premium content explore page allowlist to a denylist.
The plan is to leave the allowlist optimizely var around for old clients for a bit.
Current list (which I believe is comprehensive): marcus_audius,dharit,FerrariJetpack,ehwutupdawg,turtle999,utterk,LabyrinthFlamingoPeculiar,ScaryHamburger,KaleidoscopeQuasarCandelabra,elephantspiralharmonica,___l___,confusedcat,professr
Local web stage + prod
Screenshot is stage with reedtest and reed3 on the denylist:
=> [PAY-2132] Premium content explore page denylist

packages/discovery-provider/src/tasks/index_payment_router.py
I missed a `f` prefix on a string and it results in logs which aren't the most useful :-) 
None
=> Fix missing string format on payment router indexing

packages/discovery-provider/src/tasks/publish_scheduled_releases.py
Error was comparing date vs datetime. This just compares datetime to datetime.
Ran in staging environment without error/
=> Fix timestamp comparison for sched releases

packages/mobile/src/harmony-native/icons.ts, packages/mobile/src/types/declarations.d.ts, svgr-template.js
Adds forwardRef to all our icons to enable animated native icons.
This will help with web animated icons and any time we would need to ref the icons, a big win!
Tested on mobile
=> [C-3504] Enable native animated icons

packages/identity-service/src/routes/relay.js
Ensures the instruction to be relayed is not deactivation request before rejecting it if the user is blocked from relay.
** NOT TESTED ** putting up for early feedback on approach
=> [PAY-2263] Decode ABI for blocked users and relay if they're deactivation requests

packages/mobile/src/components/payment-method/CardSelectionButton.tsx, packages/mobile/src/components/payment-method/PaymentMethod.tsx
- When coinflow was disabled, we were still showing coinflow as the default option on mobile because that's what it was set to in initial redux state.
- Android `CardSelectionButton` `TouchableOpacity` wasn't registering the presses probably because it's behind the `Button`, so added the press handler to the Button as well (still works on ios).
Tested both ios and android against prod.
=> Fix defaults when coinflow disabled + android purchase vendor drawer

packages/web/vite.config.ts
This is a nice devx thing because it lets you turn on internet sharing on your mac and then when your phone is connected to the same network, you can access name.local:300x from your phone and test mobile web.
Was very helpful for this PR https://github.com/AudiusProject/audius-protocol/pull/6941
```
```
raymont.local:3002 from my phone :)
=> Use 0.0.0.0 default host for vite app

packages/mobile/src/components/payment-method/PaymentMethod.tsx, packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
Tried to make it match web:
https://github.com/AudiusProject/audius-protocol/blob/0b69f756b99cab53fcc2f1dba21de7134814e9d8/packages/web/src/components/payment-method/PaymentMethod.tsx#L62
Bonus: sneaking in a small bug fix where we forgot to call the `isZero` fn.
=> [PAY-2270] Show vendor button only if more than 1 vendor

packages/stems/src/components/Modal/ModalContentPages.tsx, packages/web/package.json, packages/web/src/components/drawer/Drawer.module.css, packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx, packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
Currently there are a few very broken things with purchase web/mobile web modal/drawer
* Not scrollable (so small screens get wrecked)
* Purchase button isn't floating/fixed anymore, maybe never really was in mobile web drawer
* Body scroll lock is pretty much not working (old version) for mobile web drawers
The fix needed a few things, including a bit of a hack. I spent a long while trying to rework the modal content setup, but at risk of a bigger change and messing with a lot of things, I feel that this is relatively safe.
Extensively on web (chrome & safari)
* Create app modals
* Premium content modals
* Add to playlist modals
* Withdrawal modal
to name a few
Mobile (chrome …
=> [PAY-2277][PAY-2272] Fix purchase modaldrawer scroll and safe areas

packages/common/src/hooks/purchaseContent/usePayExtraPresets.ts, packages/common/src/messages/sign-on/pages.ts, packages/common/src/services/remote-config/defaults.ts, packages/common/src/services/remote-config/types.ts, packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx, packages/mobile/src/components/premium-track-purchase-drawer/hooks/usePurchaseSummaryValues.ts, packages/web/src/components/add-funds-modal/AddFundsModal.tsx, packages/web/src/components/add-funds-modal/constants.ts, packages/web/src/components/add-funds-modal/types.ts, packages/web/src/components/add-funds-modal/validation.ts, packages/web/src/components/add-funds/AddFunds.tsx, packages/web/src/components/payment-method/PaymentMethod.tsx, packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx, packages/web/src/components/premium-content-purchase-modal/components/PayExtraFormSection.tsx, packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx, packages/web/src/components/premium-content-purchase-modal/hooks/usePurchaseSummaryValues.ts, packages/web/src/components/summary-table/SummaryTable.tsx
Implements an amount picker that appears when coinflow is the selected vendor in the add funds modal.
This is somewhat wet and I'm sure could use some cleanup, I took the fastest path to getting a working solution.
Note - this is for web + mobile-web only, didn't have time to get to mobile.
Local web
https://github.com/AudiusProject/audius-protocol/assets/3893871/f052bf94-6504-474e-bf36-e902dc9ef921
=> [PAY-2276] Selectable amounts for coinflow add funds web

packages/discovery-provider/ddl/migrations/0043_add_dashboard_wallet_users.sql
Only one user per wallet, so the pkey should be the wallet
=> Fix primary key for DashboardWalletUsers

packages/common/src/hooks/useCoinflowAdapter.ts, packages/libs/src/services/solana/transactionHandler.ts
Adjusts wallet adapter to use TransactionHandler so that we can use the retry logic. Adjusts TransactionHandler to not need to have the signer if the transaction already is signed.
Tested locally against prod on web.
=> Use retry logic for coinflow

packages/mobile/src/components/premium-track-purchase-drawer/PayExtraFormSection.tsx
Fixes PAY-2274
This adds explicit minWidths to the pills in the "pay extra" section and adds wrapping ability to the container in case the pills take up too much space.
Tested on iOS simulator by increasing system font size and hard-coding larger min widths to trigger wrapping behavior.
=> [PAY-2274] Update minWidths of pay extra pills to prevent clipping

packages/common/src/store/purchase-content/sagas.ts, packages/common/src/store/purchase-content/slice.ts, packages/common/src/store/purchase-content/types.ts, packages/common/src/store/purchase-content/utils.ts, packages/common/src/store/ui/coinflow-modal/slice.ts, packages/web/src/components/coinflow-onramp-modal/CoinflowOnrampModal.tsx
Fixes PAY-2283
Disables the purchase button immediately upon the purchase action being fired.
Tested by commenting out the actual purchase and adding a console log, and verifying that even if I smashed that purchase button as fast as I could that I couldn't get the log to appear twice.
=> [PAY-2283] Disable purchase button immediately after click

packages/discovery-provider/src/monitors/database.py
As per [the docs](https://www.postgresql.org/docs/13/pgstatstatements.html), starting in Postgres 13, the pg_stat_statements mean_time column was split into mean_exec_time and mean_plan_time. This PR updates our query to find slow queries by taking into account the Postgres version and using the appropriate tables.
On a stage node, this code makes slow queries display in the verbose health check - now broken down by planning time vs execution time.
=> Make finding slow queries compatible with pg 13+

.circleci/config.yml
Adds a CircleCI job which notifies Slack about stage nodes that are behind the latest version.
=> Notify Slack when stage nodes aren't updating

packages/harmony/rollup.config.mjs, packages/harmony/src/components/icon.ts, packages/mobile/src/harmony-native/foundations/theme/shadows.ts, packages/mobile/src/harmony-native/foundations/theme/theme.ts, packages/mobile/src/screens/sign-on-screen/components/AudiusValues.tsx, svgr-template.js
Adds icon shadows for web and native. 
Note for now we only use "drop" shadow for icons, wheras mobile we can reuse the same shadow configs for icons. Will follow up with UX on what icon shadow diversity we should have, if any.
=> [C-3494] Add shadow to icon

packages/mobile/src/harmony-native/components/Button/BaseButton/BaseButton.tsx, packages/mobile/src/harmony-native/components/Button/types.ts, packages/mobile/src/harmony-native/components/CompletionCheck/CompletionCheck.stories.tsx
Add simple BaseButton component to native harmony as the base for other button components
I added a story in storybook for this to test, but didn't think it made sense to keep so did not add to the commit
=> [C-3427] Add BaseButton to mobile harmony

packages/discovery-provider/ddl/migrations/0044_set_release_to_created_where_null.sql
Acquires a lock on the tracks table before starting the release_tracks migration. The modified migration was running indefinitely, likely because another container had a lock on the table.
=> Add lock to tracks table for migration

packages/discovery-provider/ddl/migrations/0044_set_release_to_created_where_null.sql
Temporarily disables triggers on the tracks table while a migration is running. Without this, the migration takes unfeasibly long.
Ran on stage DN4.
=> Disable triggers while migration runs

packages/discovery-provider/src/tasks/entity_manager/entities/user.py
Remove legacy image fields in indexing. Client should always use profile_picture_sizes and cover_photo_sizes. If a faulty cover_photo or profile_picture is passed into metadata, ignore.
Tested on stage. Updating images worked.
=> Ignore legacy images in indexing

packages/common/src/store/lineup/actions.ts, packages/mobile/src/components/lineup/Lineup.tsx, packages/mobile/src/screens/profile-screen/ProfileTabs/RepostsTab.tsx, packages/mobile/src/screens/profile-screen/ProfileTabs/TracksTab.tsx, packages/web/src/common/store/lineup/sagas.js
Updates lineup refresh code to invalidate cache on refresh
Also fixes issue were refresh action wasn't getting "additional options"
=> [PROTO-1524] Invalidate cache on refresh

packages/libs/src/sdk/services/Storage/Storage.ts
The retry logic added in https://github.com/AudiusProject/audius-protocol/pull/5970 had the for loop condition inverted. Essentially it was never making a request because `this.storageNodeSelector.triedSelectingAllNodes()` was false so it skipped the loop
Also needed to add a break when it successfully made a request
This underscores the need for better tests on the sdk! That's a top priority for Dev Product next quarter
Successfully uploaded on stage via the sdk:
```
[audius-sdk][tracks-api] Parsing inputs
[audius-sdk][tracks-api] Transforming metadata
[audius-sdk][tracks-api] Uploading track audio and cover art
[audius-sdk][tracks-api] Writing metadata to chain
[audius-sdk][entity-manager] Making relay request to https://identityservice.staging.audius.co/relay …
```
=> Fix sdk Storage retry logic

.circleci/src/workflows/release.yml
I'm working on making DDEX build with audius-compose, but in the meantime this temporarily removes DDEX as being required for CI release.
=> Temporarily remove ddex image as required for releases

packages/mobile/src/components/coinflow-onramp-drawer/CoinflowOnrampDrawer.tsx
We missed adding the explicit cancel/close for the coinflow drawer (we do this for the strip drawer). It causes the purchase form to get stuck in a state where it can't be closed.
fixes PAY-2315
Tested locally on simulator against staging.
=> [PAY-2315] Explicitly cancel transaction when closing coinflow drawer

.circleci/scripts/periodic-cleanup
CI machine disk usage has hit 100% in two instances in the last couple of months, lowering the threshold should make that less likely.
Green builds
=> Lower thresholds for prune and full prune on self-hosted ci machines

.circleci/src/workflows/release.yml, dev-tools/audius-compose, dev-tools/compose/docker-compose.ddex.yml, dev-tools/compose/docker-compose.yml, packages/ddex/.dockerignore, packages/ddex/Dockerfile, packages/ddex/Dockerfile.fast, packages/ddex/scripts/docker-entrypoint.sh
- Makes` audius-compose push --prod ddex` work
- Improves the ddex Dockerfile caching (not reinstalling packages if only the source changes but not packages.json)
- Makes the ddex Dockerfile have a much smaller output (5MB vs 470MB) and use the entrypoint to copy files instead of rebuilding (saves a ton of CPU+memory each time)
Tested on stage DN5, including updating the code to verify that it updates the mounted volume for changes but doesn't do anything when there are no changes.
=> Add ddex to audius-compose and improve its build

.circleci/src/jobs/commit-audius-docker-compose-and-notify.yml, .circleci/src/jobs/deploy-stage-nodes.yml
Makes the tag replacement `sed` command more specific so it doesn't bulldoze tags like [this](https://github.com/AudiusProject/audius-docker-compose/commit/67efc6a70c98991ffb963570e98ddbafc3d78744#diff-227d46fd22bb26c20dc3bc63a7eed90ad0ef1cef6c5a50fd1c6c1b97c413c649L369).
Tested with various examples:
- Basic replacement `echo 'image: audius/dashboard:${TAG:-5652852c216ffdd58b6d3d7e8db54d32a3870209}' | sed "s/\({TAG:-\)[^}]*\}/\1abcdef1234567890}/"`
- Replacement with the tag it bulldozed previously: `echo 'image: audius/dashboard:${TAG:-5652852c216ffdd58b6d3d7e8db54d32a3870209}-${NETWORK:-prod}' | sed "s/\({TAG:-\)[^}]*\}/\1abcdef1234567890}/"`
- Multiple placeholders: `echo 'image: audius/service:${SOME_TAG:-default}-${TAG:-previousvalue}-${NETWORK:-prod}' | sed …
=> Make CI sed more specific

packages/mobile/src/harmony-native/components/Button/FollowButton/FollowButton.tsx, packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/FollowArtistCard.tsx, packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/FollowArtistField.tsx, packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/SelectArtistsScreen.tsx, packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/TopArtistsCardList.tsx, packages/web/src/common/store/pages/signon/reducer.js, packages/web/src/pages/sign-up-page/components/FollowArtistCard.tsx, packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
Updates select artist screen to use redux instead of formik, due to super slow perf. Using redux seemed to be cleanest option, rather than a context + memo approach
=> [C-3526] Select artist screen perf

packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Not sure why we were formatting release dates and created_at differently in this way before (maybe because release_dat was strings before), but I had made this change to format them the same here https://github.com/AudiusProject/audius-protocol/pull/6954. That change didn't get deployed yet. 
However in discovery, we did modify release_dates to default to created_at which has made it to prod, so we should be using release_date all the time. I think this was just an existing bug that hasn't surfaced until now. Still leaving the created_at in here for now even though it shouldn't be necessary. 
Tested on ios:prod. This format is identical to web.
=> Patch mobile release date format

.circleci/src/commands/@mobile-commands.yml, .circleci/src/jobs/@mobile-jobs.yml
Currently a full app release just sends things to the store for review - it doesn't actually deploy it to prod.
In the case of a full release, skip notifying slack.
Will be tested alongside this week's upcoming release-client-v1.5.58
=> Disable slack notify if full release when sent to app store

comms/Dockerfile, comms/discovery/pubkeystore/recover.go, contracts/contracts/EntityManager.sol, contracts/migrations/2_entity_manager_migration.js, dev-tools/compose/docker-compose.discovery.prod.yml, dev-tools/compose/docker-compose.test.yml, dev-tools/compose/docker-compose.yml, dev-tools/compose/nginx_ingress.conf, dev-tools/startup/comms.sh, dev-tools/startup/startup.sh, packages/libs/src/sdk/services/EntityManager/EntityManager.test.ts, packages/libs/src/sdk/services/EntityManager/EntityManager.ts, packages/libs/src/services/contracts/ContractClient.ts, packages/libs/src/services/dataContracts/EntityManagerClient.ts
- Makes comms run as replicated just like DN, and connected to respective DN db
- Adds nginx config to forward /comms requests to the comms container, including websockets
Tested locally by running `audius-compose up -d 2 -p --comms` and sending messages back and forth
> ~~Error I get when trying to do DMs related features (couldn't get pubkey):~~
> 
> ```
> map[_action:Create _entityId:63942403 _entityType:User _metadata:{"cid":"bagaaierayta27sm4vluxs6e3wvfauselncblgepbxc7yrwkl7lzwg7dbgvpa","data":{"is_deactivated":false,"name":"name C979","handle":"handleC979","profile_picture":null,"profile_picture_sizes":null,"cover_photo":null,"cover_photo_sizes":null,"bio":"account generated by audius-cmd C979","location":"locationC979","artist_pick_track_id":null,"creator_node_endpoint":null,"associ …
```
=> Run comms locally via audius-compose

packages/identity-service/relay-rate-limit.json
Rate limits are high because you can only have one wallet per user, and the wallet also has to sign the tx. 
Need to add this or else the relay for these txs fails.
=> Add rate limits for DashboardWalletUser relays

packages/web/src/components/add-to-collection/desktop/AddToCollectionModal.tsx
This toast was not displaying because the action creator for the toast was being called but not dispatched.
Seems like this has never worked in prod?
Did a quick audit of other toast usages in web, and all the others either call dispatch or use the `ToastContext` toast creator which does the dispatch for you.
local web
=> [C-3533] Fix add track to collection toast

packages/common/src/models/Analytics.ts, packages/web/src/components/tile/Tile.tsx, packages/web/src/components/upload/UploadChip.tsx, packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx, packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx, packages/web/src/pages/profile-page/components/desktop/ProfileWrapping.tsx, packages/web/src/pages/saved-page/components/desktop/PlaylistsTabPage.tsx
- Upload Track always takes you to upload with no menu
- Upload Album/Playlist will give you the option to go to upload flow or just create an empty one that you can start editing
- Mobile coming in separate PR
local web
all instances tested and working with the new menu
=> [C-3521] Add option menu to create collection tile (web)

packages/libs/src/sdk/api/tracks/TracksApi.ts, packages/libs/src/sdk/services/EntityManager/EntityManager.ts, packages/libs/src/sdk/services/Storage/Storage.ts, sdk-consumer/index.ts
Add some `info` logs to track upload flow. Would be nice to have granular logging like this on all writes!
Fix sdk-consumer to not use discovery relay until that's up and working
=> Improve sdk track upload logs

packages/mobile/ios/Podfile.lock, packages/mobile/package.json
There is weirdness with react-native-svg 14 in relation to wallet-connect. Reverting to 12.3 in the meantime until we migrate off old wallet-connect
=> Fix react-native-svg version

packages/mobile/src/components/lineup-tile/LineupTile.tsx, packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx, packages/web/src/components/scheduled-release-label/ScheduledReleaseLabel.tsx, packages/web/src/components/track/desktop/TrackTile.tsx
A couple places where scheduled releases gating wasn't properly set or time comparisons were slightly off because of timezone offset.
Will improve on this by adding a field for is_scheduled_release instead of relying on comparisons but wanted to get this in before then.
Tested against stage. Verified create/edit track and track tiles on web/mobile.
=> Fix schedule release gating

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/web/src/components/collection/desktop/OwnerActionButtons.tsx, packages/web/src/components/collection/desktop/PublishButton.tsx, packages/web/src/components/collection/desktop/PublishConfirmationModal.tsx
- Remove guards preventing albums from being private
- Removed guards preventing PublishButton from showing on albums
- Fixed copy
local web
confirmed that uploaded albums are still public (not relying on the libs default)
=> [C-3513] Private albums + show PublishButton for albums

packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx
Otherwise this shows up when balanceBN is null
=> Fix payment method existing balance

packages/common/src/store/upload/selectors.ts
Fixes issue where upload percentage goes above 100, which can happen occasionally since the math calc is not always exact.
=> Clamp upload percentage

.circleci/src/commands/@mobile-commands.yml, packages/mobile/dapp-store/README.md
Since the saga build only targets one phone, we can build an apk specificially for it's architecture, which is arm9. v8a is the corresponding android ABI
=> [C-3565] Reduce saga apk size

packages/web/.svgrrc.js
Fixes issue where podcast playback menu was not anchored on playback icon button. This issue was introduced in the svg refactor from a few weeks ago
=> [C-3492] Fix podcast popup position

packages/mobile/src/services/coinflow.ts
Adds a safety check in case the RN module for nSure isn't available.
Tested locally on simulator by changing the export name for the module so that the lookup results in null.
=> [PAY-2321] Prevent crash if nsure RN module isn't available

packages/discovery-provider/integration_tests/tasks/entity_manager/test_dashboard_wallet_user_entity_manager.py, packages/discovery-provider/src/tasks/entity_manager/entities/dashboard_wallet_user.py
Connecting a protocol dashboard wallet to an Audius user requires two signatures, one from the wallet and one from the Audius user.
Previously, the Audius user had to sign the transaction, and the wallet had to pass a signature in the metadata.
With these changes, this ^ is still possible, but alternatively the wallet can sign the transaction and the user can pass a signature in the metadata. 
Integration test.
=> [EM] Allow dashboard wallet to sign EM CreateDashboardWalletUser tx and user to sign `user_signature` in the metadata C-3568

packages/discovery-provider/ddl/migrations/0046_add_is_scheduled_release.sql, packages/discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py, packages/discovery-provider/integration_tests/tasks/entity_manager/test_utils.py, packages/discovery-provider/src/api/v1/models/tracks.py, packages/discovery-provider/src/models/tracks/track.py, packages/discovery-provider/src/tasks/entity_manager/entities/track.py, packages/discovery-provider/src/tasks/metadata.py
Add is_scheduled_release column. This is safer than relying on release_date > created_at to identify scheduled releases.
Expose this in tracks API.
Existing scheduled releases tests pass.
=> Add is_scheduled_release field

packages/discovery-provider/src/api/v1/models/users.py, packages/discovery-provider/src/api/v1/users.py
The [JWT](https://docs.audius.org/developers/log-in-with-audius#3-verify-the-response) returned by Audius OAuth will now contain a `txSignature` when the user approves of one particular transaction.
For example, the flow to link a protocol dashboard wallet to an Audius user looks like this:
1. Protocol dashboard opens Audius OAuth and requests for user to approve connecting the wallet
2. User approves
3. Protocol dashboard receives and verifies the JWT, which contains the tx signature
4. Protocol dashboard sends `CreateDashboardWalletUser` transaction which requires the tx signature from the user. This tx is signed by the wallet.
=> [Discovery API] Add transaction signature to OAuth JWT payload type

svgr-template.js
Fixes issue where icons without the harmony theme have a run-time error. We could wrap everything in harmony provider, but this seems reasonable too
=> Fix svgr template when no theme

packages/harmony/src/foundations/color/semantic.ts, packages/mobile/.storybook/storybook.requires.ts, packages/mobile/src/components/loading-spinner/LoadingSpinner.tsx, packages/mobile/src/harmony-native/components/Button/BaseButton/BaseButton.tsx, packages/mobile/src/harmony-native/components/Button/Button/Button.stories.tsx, packages/mobile/src/harmony-native/components/Button/Button/Button.tsx, packages/mobile/src/harmony-native/components/Button/types.ts, packages/mobile/src/harmony-native/components/Text/Text.tsx
Added the button component and kept the styles as close to the web designs as possible.
The icon transitions and the blur on the tertiary button is the only things that need update.
=> [C-3425] Add Button component to native harmony

packages/web/src/pages/oauth-login-page/OAuthLoginPage.module.css, packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx, packages/web/src/pages/oauth-login-page/components/CTAButton.tsx, packages/web/src/pages/oauth-login-page/components/ContentWrapper.tsx, packages/web/src/pages/oauth-login-page/components/PermissionsSection.tsx, packages/web/src/pages/oauth-login-page/hooks.ts, packages/web/src/pages/oauth-login-page/messages.ts, packages/web/src/pages/oauth-login-page/utils.ts
1. Move a lot of logic from `OAuthLoginPage` component into a separate hook for cleanliness, since it was getting unwieldy. This is why the PR looks so big, but a lot of it is just copy paste.
3. Introduce changes to support the "Connect User to Wallet" protocol dashboard feature.
- Add new scope, `write_once`, which is to be used when a developer app needs the user to authorize/sign one transaction, which will then be sent by the Audius Client.
- For this scope, the app needs to specify the `tx` in the query params as well as any other params needed for that tx. 
- Add `tx=connect_dashboard_wallet` as the first available transaction for the `write_once` scope. For this tx, the app needs to also specify the `wallet` and `wallet_signature` in the query params.
- Once the user signs in …
=> [Web] Enable connecting wallet to user via new OAuth `write_once` scope [C-3499]

packages/mobile/index.js
Disables font-scaling on react-native apps to awkward ux. Follows the "standard" approach to doing this by updating Text's defaultProps
=> [C-3462] Disable native font scaling

monitoring/uptime/main.go
OPTIMIZELY_SDK_KEY seems to only exist in prod node envs (not stage) and our existing code depends on falling back to a hardcoded key for stage if the value is "". Use os.Getenv rather than mustGetenv so the uptime container doesn't crash on stage.
Deploy to a stage node
=> Fix uptime optimizely env

package-lock.json, packages/ddex/package.json, packages/ddex/src/app.ts, packages/ddex/src/controllers/uploadController.ts, packages/ddex/src/index.ts, packages/ddex/src/services/dbService.ts, packages/ddex/src/services/scheduledReleaseService.ts, packages/ddex/src/services/sdkService.ts
Organizes the backend DDEX code in a way that facilitates persisting the SDK, db, and upload queue.
It's half-baked, but I want to merge sooner than later so no one is blocked. This is written in a way that should make future unit or integration tests easy.
=> Add DDEX MVC + DB scaffolding

.circleci/scripts/circleci-startup-script.sh
We can rely on the thresholds to determine how ofter `docker system prune -a` should run (vs without `-a`) and we don't need to have separate hourly and daily scripts.
Will restart runner 7 when landed.
=> Perform full disk cleanup hourly for self-hosted runners

.circleci/scripts/circleci-startup-script.sh, .circleci/scripts/periodic-cleanup
New resource class for self-hosted runner that will be used with audius-d tests.
Ran the cpus subshell command on the host itself to ensure proper functionality. Ran the whole script through shellcheck utility to check for errors.
=> Add 8cpu resource class to circleci runners

packages/mobile/android/app/build.gradle, packages/mobile/ios/AudiusReactNative/Info.plist
403 & 78 are currently being used to reissue 1.5.55
=> Increment mobile versions ahead of 1.5.59

packages/web/src/components/form-fields/HarmonyTextField.tsx, packages/web/src/components/form-fields/PasswordField.tsx, packages/web/src/pages/sign-in-page/SignInPage.tsx, packages/web/src/pages/sign-up-page/components/EnterPasswordSection.tsx, packages/web/src/pages/sign-up-page/components/HandleField.tsx, packages/web/src/pages/sign-up-page/components/layout.tsx, packages/web/src/pages/sign-up-page/pages/CreateEmailPage.tsx, packages/web/src/pages/sign-up-page/pages/CreatePasswordPage.tsx, packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx, packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx
Interestingly, "autoFocus" a prop used to focus user cursor on an input when it renders, messes up our page transitions, which smoothly animate a page to the left/right as it enters. The fix was to replace autoFocus with a ref-based approach. In this new system we call `ref.current.focus()` when the page animation finishes, which is triggered by the "onRest" method of the react-spring `useSpring` config. Not only does this fix the issue, it actually looks much nicer because we get a nice page transition, and then shortly after we get a nice input focus animation, making it much clearer to the user where their focus should be.
=> [C-3515] Fix desktop sign up page transitions

packages/discovery-provider/src/app.py, packages/discovery-provider/src/tasks/publish_scheduled_releases.py
Re-enable and simplify logic. Only release tracks with is_scheduled_release True and a release_date that has passed.
Running on sandbox and was able to publish scheduled releases. No other tracks are published.
=> Enable schedule release job

packages/ddex/.gitignore
Not needed since we don't use the ddex/uploads folder after https://github.com/AudiusProject/audius-protocol/pull/7102
=> Remove DDEX .gitignore

.circleci/config.yml, package-lock.json, package.json
Fixes issue where trpc-server node_modules cache was not being restored, leading to missing dependencies in the install
=> Fix trpc-server ci cache

packages/mobile/src/screens/chat-screen/ChatMessagePlaylist.tsx, packages/web/src/pages/chat-page/components/ChatMessagePlaylist.tsx
Issue was that we were getting playlists by id, and the way to get the id was brittle. I think there was a project some time ago to migrate to using permalinks, but the UI didn't get updated once the project was done. Fix is simply to get playlist by permalink.
local web vs prod
=> [PAY-2340] Fix dms playlist unfurl

packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx
When a track is a scheduled release, there should be a hint on the Hidden radio that explains scheduled releases cannot be hidden. This was working for the web edit form but in the create form `isInitiallyUnlisted` is undefined so the hint wouldn't show. `isScheduledRelease` alone isn't sufficient because it could be a scheduled release that has since been published.
Tested web create and edit access & sale. Mobile is working correctly.
=> Fix disabled hidden hint for create schedule release

packages/mobile/src/components/collection-list/AddCollectionCard.tsx, packages/mobile/src/components/collection-list/CollectionList.tsx, packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx, packages/mobile/src/screens/profile-screen/ProfileTabs/AlbumsTab.tsx, packages/mobile/src/screens/profile-screen/ProfileTabs/PlaylistsTab.tsx
This reverts commit 087d4a3db725873d3f872e11e056709afa0dd8e7.
We don't support collection upload on mobile yet, so this change is undesirable for now. See [slack thread](https://audius-internal.slack.com/archives/C067P8X5QB1/p1704844578047549)
=> Revert "[C-3523] Add create album card to mobile (#7129)"

packages/discovery-provider/src/challenges/audio_matching_challenge.py
Fixes bug where $AUDIO matching challenge would only be created for non-verified users.
There are 16 purchases across 6 users that didn't get this challenge due to this bug. 2 of them are our own.
shoutout @rickyrombo for spotting the bug.
=> Fix audio matching buyer challenge broken for verified users

dev-tools/compose/docker-compose.ddex.yml, packages/Dockerfile.ddex, packages/Dockerfile.ddex.fast
Required for ddex to build with harmony, which is not yet published to npm.
built Dockerfile.ddex and Dockerfile.ddex.fast locally
audius-compose push --prod "ddex"
built on a stage node
=> DDEX dockerfile uses turbo

packages/discovery-provider/integration_tests/tasks/entity_manager/test_dashboard_wallet_user_entity_manager.py, packages/discovery-provider/src/api/v1/models/users.py, packages/discovery-provider/src/tasks/entity_manager/entities/dashboard_wallet_user.py, packages/libs/src/sdk/api/dashboard-wallet-users/types.ts
Allow the wallet signature message for CreateDashboardWalletUser to be like "Connecting Audius user @handle at 239243".  This way the signer can more easily verify what they are signing (i.e. this improves the UI and security of the feature on the protocol dashboard).
Integration tests
=> [Discovery] Allow `wallet_signature` message in CreateDashboardWalletUser tx metadata to contain user handle

packages/common/src/store/pages/chat/selectors.ts, packages/mobile/src/components/lineup-tile/TrackTile.tsx, packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx, packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx, packages/mobile/src/components/track-list/TrackListItem.tsx, packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx, packages/web/src/components/menu/TrackMenu.tsx, packages/web/src/components/now-playing/NowPlaying.tsx, packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx, packages/web/src/components/track/mobile/ConnectedTrackTile.tsx, packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Add `Visit Album Page` to track overflow menus for web and mobile
local web and ios sim
=> [C-3520] Add Visit Album links to track menus

packages/mobile/src/components/premium-track-purchase-drawer/PremiumTrackPurchaseDrawer.tsx
Don't show existing balance row in mobile payment method if balance is null
=> Fix payment method bug on native mobile

packages/mobile/src/screens/upload-screen/screens/UploadingTracksScreen.tsx, packages/web/src/pages/upload-page/UploadPage.tsx
Was missing the setting of `is_download_gated` and `download_conditions`. These changes are already on web.
Uploaded usdc premium track on ios and it worked. (didn't work before this change)
=> Fix mobile upload download gated fields

packages/web/src/components/welcome-modal/WelcomeModal.tsx
Adding `overflow: hidden` to isolate animations within the body of the welcome modal to not affect the blurred background of the top part.
NOTE: Chrome has a lot of weird visual bugs with blurred background so this is mostly a bandaid solution, but this is conjunction with the buttons not scaling up on hover should fix this well enough.
Tested locally
=> [C-3572] Update WelcomeModal to prevent blur flashing when button is hovered

packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts, packages/web/src/components/track/GiantTrackTile.tsx
- Fix `addToPlaylist` toast message to include the right collection type
- Move Album link to the end of track page detail fields
local web
=> [C-3626, C-3624, C-3628] Fix add to album toast message; Album info to end of track details

packages/web/src/common/store/pages/signon/sagas.js
This reverts commit bc4d099394cd25a6150f9de96c61f05e88c034c6.
Fixes bug where mobile sign-ons with profile pic would fail to create user.
=> Revert "[Mobile] Fix profile + cover pic not uploading upon social sign up [C-3466]

packages/common/src/store/ui/toast/slice.ts, packages/web/src/common/store/cache/collections/commonSagas.js
Add toasts when processing track removal from a collection. This is desirable because the action buttons are disabled while the confirmation is in progress. This helps explain why.
local web and mobile
=> [C-3627] Add toasts to removeTrackFromPlaylist

protocol-dashboard/src/components/ManageService/ManageService.module.css, protocol-dashboard/src/hooks/useConnectAudiusProfile.ts, protocol-dashboard/src/hooks/useDashboardWalletUsers.ts, protocol-dashboard/src/services/Audius/sdk.ts, protocol-dashboard/src/services/Audius/setup.ts, protocol-dashboard/src/store/account/hooks.ts, protocol-dashboard/src/store/account/slice.ts, protocol-dashboard/src/store/cache/user/hooks.ts, protocol-dashboard/src/utils/switchNetwork.ts
See thread for context: https://audius-internal.slack.com/archives/C05L7MGHA3G/p1704765530694239?thread_ts=1704761271.608589&cid=C05L7MGHA3G
Demo:
=> Send EM transaction from Audius client for connect wallet feature [C-3604] [C-3605]

packages/common/src/store/account/types.ts, packages/mobile/src/screens/sign-on-screen/components/SignUpFlowInstagramAuth.tsx, packages/mobile/src/screens/signon/ProfileAuto.tsx, packages/mobile/src/store/oauth/actions.ts, packages/mobile/src/store/oauth/reducer.ts, packages/web/src/common/store/pages/signon/actions.ts, packages/web/src/pages/sign-on/SignOnProvider.tsx, packages/web/src/pages/sign-on/components/ProfilePage.tsx, packages/web/src/pages/sign-on/components/desktop/SignOnPage.tsx, packages/web/src/pages/sign-on/components/mobile/SignOnPage.tsx
- Our native social image uploads were using a different format, so I just standardized the image format coming from the social flows and used the more standard `Image` type
TikTok on iOS simulator staging/prod - was able to sign up and profile pic shows up
Instagram on iOS simulator prod - was able to sign up and profile pic shows up
Twitter on iOS simulator prod - was able to sign up and profile pic shows up
NOTE: having some trouble reusing these socials and getting to the "Handle is already taken" flow 😬
=> [C-3631] Fix social image uploads by reformatting the types

packages/mobile/src/components/track-list/TrackList.tsx, packages/mobile/src/components/track-list/TrackListItem.tsx, packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx, packages/web/src/components/menu/TrackMenu.tsx, packages/web/src/components/tracks-table/TracksTable.tsx, packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Exclude the `Visit Album Page` option for tracks in a tracks table on an album page. In this case you are necessarily already viewing the album.
local web and sim
option appears in other places but not on the album page
same track will show the option elsewhere and now playing track is unaffected even if you're on an album page
=> [C-3622] Exclude 'Visit Album' from menus when already on album page

packages/trpc-server/src/routers/playlist-router.ts, packages/trpc-server/src/routers/track-router.ts, packages/trpc-server/src/routers/user-router.ts, packages/trpc-server/test/router.test.ts
Decided with @stereosteve that we can/should return `null` instead of throwing 404s here.
The 404 errors end up flooding the client logs, and there isn't a great place to put a handler since we're calling the trpc query hooks directly.
local trpc-server build and tests passing
=> [C-3632] Return null instead of NOT_FOUND in trpc-server

packages/mobile/src/app/App.tsx
Fixes a long-standing issue where phone-calls/siri/google assistant interruptions wouldn't pause/play our media correctly. This was a limitation of react-native-track-player v3. Now that we have migrated to v4 to fix an android issue, we can apply this setting! Should result in much better experience for users 🥳
=> [C-2190] Fix track player interruptions

packages/mobile/dapp-store/package.json
Fixes issue where saga ci failed to install because pnpm was not specified in it's package.json. This is needed now that turbo repo specifies npm in root package.json
Was able to deploy last weeks saga with this change
=> [C-3638] Fix saga ci

packages/web/src/common/store/upload/sagas.js
Prevent error in uploading albums due to using yield* on non-typescript file
Unknown if this is the error that our user hit as it doesn't send me to the /error page, but worth fixing!
Made the change on github ui, haven't tested
=> Remove yield* in JS file

packages/web/src/pages/collection-page/CollectionPageProvider.tsx
Fixes issues where addTrackToPlaylist from suggested tracks and drag-n-drop did not add track to collection lineup. This was due to issues with "shouldComponentUpdate" not recognizing differences in the metadata object, most likely because it's a deeply nested object.
=> [C-3149 C-3122 C-3051 C-3625 C-3481] Fix add track to playlist

packages/discovery-provider/nginx_conf/nginx.conf, packages/discovery-provider/nginx_conf/port.lua
Some nodes aren't peering because they are unable to get their public IP. This will help identify these nodes and diagnose their networking issues.
IP sources from
https://github.com/NethermindEth/nethermind/blob/707461293534042bc0e5a402f716b8a518b4cec8/src/Nethermind/Nethermind.Network/IPResolver.cs#L72-L77
Tested on my sandbox. Confirmed fallback works.
=> Get public IP in nginx

packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
Own profile was showing empty state with no cards and no message. Rolling forward to display the new upload chip component that will create an album on click.
local web
=> [C-3639] Fix empty album tab state

packages/web/src/components/upload/UploadChip.tsx
Broke the onclick on the recent refactor of UploadChip. Track was wrongly calling the create collection handler.
now it opens the upload page
=> [C-3677] Fix onclick for upload a track chip

packages/web/src/components/track/GiantTrackTile.tsx
Accidentally deleted these instead of keeping them around before we enable the lossless ff.
Local web stage.
=> [PAY-2363] Re-add downloads when lossless downloads flag disabled

packages/mobile/src/harmony-native/components/RadialGradient/RadialGradient.tsx, packages/mobile/src/screens/sign-on-screen/screens/SignOnScreen.tsx
- Fixes issue where new radial-gradient is incompatible with android. required updating the "center" prop for ios and android differently.
- Fixes issue with sign-up expandible panel's border radius was incompatible with devices with no top screen radius
- Fixes issue with zIndexes on android
=> [C-3678, C-3657] Fix android radial-gradient bug, Fix sign-up panel top border-radius

packages/discovery-provider/src/queries/get_sitemap.py
is_scheduled_release is still true after publishing. Publishing just flips is_unlisted from true to false. This is so we can easily see which tracks were scheduled releases, before and after publishing. 
https://github.com/AudiusProject/audius-protocol/blob/08b678bcc50c877bfe1fc48f8edebcd92126e464/packages/discovery-provider/src/tasks/publish_scheduled_releases.py#L32
=> Remove scheduled release filter from sitemaps

monitoring/vector/vector.toml
Add auto upgrade logs as a source for vector so we can observe in axiom.
This is what it looks like
https://app.axiom.co/audius-Lu52/stream/discovery?caseSensitive=0&ig=&q=%7B%22children%22%3A%5B%7B%22field%22%3A%22file%22%2C%22op%22%3A%22%3D%3D%22%2C%22value%22%3A%22%2Fauto-upgrade.log%22%7D%5D%2C%22field%22%3A%22%22%2C%22op%22%3A%22and%22%7D&qr=1h&rowId=0cyiz2fp7ko7t-06e54b55390043e4-2d1f
=> Add auto upgrade logs to vector

packages/mobile/src/components/details-tile/DetailsTile.tsx, packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx, packages/mobile/src/screens/track-screen/TrackScreenDownloadButtons.tsx
Instead of removing the download buttons entirely I should have kept them around for before the lossless feature flag is enabled.
local ios stage
=> Re-add download buttons to mobile track page

package-lock.json, packages/harmony/src/components/input/TextInput/TextInput.module.css, packages/mobile/package.json, packages/mobile/src/harmony-native/components/input/TextInput/TextInput.tsx
Adds box-shadow to harmony and harmony-native text-inputs to dramatically improve readability and align with figma
@audius/harmony: 
@audius/harmony-native:
=> [C-3651] Add box-shadow to text-input

packages/ddex/.dockerignore, packages/ddex/Dockerfile, packages/ddex/server/src/services/dbService.ts
Makes the Dockerfile for tRPC actually run (it was just "sh" before to unblock CI). Also adds proper permissions to the final runner image and prunes some unnecessary files which were causing bloat.
Tested by building on a stage node and running the image there. The UI has issues, and the backend has issues with the Postgres connection because that's in the process of changing to Mongo.
=> Make ddex tRPC Dockerfile run

protocol-dashboard/src/components/ConnectAudiusProfileModal/ConnectAudiusProfileModal.tsx, protocol-dashboard/src/components/LoadingSpinner/LoadingSpinner.module.css, protocol-dashboard/src/components/LoadingSpinner/LoadingSpinner.tsx, protocol-dashboard/src/hooks/useConnectAudiusProfile.ts, protocol-dashboard/src/hooks/useDashboardWalletUsers.ts, protocol-dashboard/src/services/Audius/sdk.ts, protocol-dashboard/src/services/Audius/setup.ts
=> [Protocol Dashboard] Fix user images not loading when MetaMask not connected; add loading state for OAuth modal [C-3694 C-3693]

packages/web/src/common/store/queue/sagas.ts
Fixes issue where nearly every lineup that has progressive loading gets 20+ recommended songs added to the end when user clicks play. This not only affects performance as we have to load a bunch more data into the queue, it also means after 10ish songs, we continue playing from recommended tracks instead of the next lineup tracks.
I went with "two tracks from the end" as the heuristic to load recommended tracks, to avoid the issue where a user skips quickly to the end before recommended tracks can load, reference: https://github.com/AudiusProject/audius-client/pull/3353
Note there is still an improvement to be made by auto-fetching the next tracks in lineup when the queue gets near the end, but this will come in another pr.
=> [C-3696] Fix lineups and recommendations

packages/web/src/components/track/desktop/TrackTile.module.css, packages/web/src/components/track/mobile/TrackTile.module.css
Fixes issue where ellipses change required the title to be full width, messing with the touch targets. This fix ensures the title only takes up the space it needs, and also adds ellipses when needed.
Mobile web still a little wonky, but i think that's okay for now.
=> Fix desktop track tile title width

packages/web/src/common/store/pages/signon/actions.ts, packages/web/src/common/store/pages/signon/sagas.js, packages/web/src/pages/sign-on/SignOnProvider.tsx, packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
Our current code has logic to trigger artist follows as part of the `signUp` saga. The only actions dispatched to actually "follow" artists is just to update the array of artists in the store (doesn't actually trigger any backend changes directly).
The issue is that if you wait too long and the `signUp` and `followArtists` sagas have both already finished, the artists never get followed.
This fixes it by adding a new saga that retriggers `followArtists` if it has already come and gone.
web stage old & new sign up flows
=> [C-3689] Fix follow artists not happening if you wait too long on sign up (web)

packages/discovery-provider/src/queries/query_helpers.py
Use `.get()` to have a default `None` when checking tracks in the `/v1/trending` endpoint.
=> Use defaults for trending track checks

packages/web/src/pages/sign-in-page/SignInPage.tsx, packages/web/src/pages/sign-up-page/components/layout.tsx, packages/web/src/pages/sign-up-page/pages/CreateEmailPage.tsx, packages/web/src/pages/sign-up-page/pages/ReviewHandlePage.tsx, packages/web/src/pages/sign-up-page/pages/SelectGenresPage.tsx, packages/web/src/pages/sign-up-page/utils/useDetermineAllowedRoutes.ts
Batch of fixes from the internal QA findings
- [C-3695] - cant get back to create email after you've entered an email and go to /sign-in or close the modal
- [C-3673] - Padding on email screens
- [C-3674] - Genres and artists spacing issues
- [C-3662] - Review handle section continue button has weird shadow and floats in the middle of page
Local web
=> Misc Sign Up QA Fixes

packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx
Fixes issue where track pages on mobile due to collection.is_album check, which should only occur when "isCollection" is passed down as a prop.
=> Fix mobile track pages due to collection check

.vscode/settings.json, packages/discovery-provider/.vscode/settings.json
`fixAll` and `organizeImports` on save actions were updated in recent versions of VSCode to use `"explicit"` instead of `true`. This gets auto-fixed every time I open the repo, so I'm persisting it permanently :-)
=> Updates deprecated vscode settings

packages/web/src/common/store/pages/signon/selectors.ts, packages/web/src/common/store/pages/signon/types.ts, packages/web/src/pages/sign-up-page/utils/useDetermineAllowedRoutes.ts
Update the new sign in/sign up flow to allow users to properly fix their account when they've gotten into a bad state (identity record, but no DN record)
=> [C-3716] Update sign up recovery flow for new sign up

packages/common/src/hooks/useGatedContent.ts, packages/web/src/common/store/lineup/sagas.js, packages/web/src/common/store/pages/signon/selectors.ts, packages/web/src/common/store/player/sagas.ts, packages/web/src/common/store/queue/sagas.ts, packages/web/src/components/play-bar/desktop/PlayBar.jsx, packages/web/src/pages/sign-up-page/utils/useDetermineAllowedRoutes.ts
These changes highlight why fully relying on DN for track access is much better/simpler/less prone to bugs for clients.
- Have client check whether track is stream/download gated for access. This fixes the bug where tracks are locked when user is logged out.
- Fix bug where tables incorrectly show tracks as locked.
=> Fix logged out state track access on client

packages/mobile/src/components/download-track-progress-drawer/DownloadTrackProgressDrawer.tsx
Remove download progress tracker due to percentages being totally bonked.
Was only visible on ios.
=> [PAY-2371] Remove download progress on ios

packages/common/src/api/suggestedTracks.ts, packages/web/src/components/suggested-tracks/components/SuggestedTracks.tsx
- Remove usage of `useCustomCompareEffect`
- Fix loading of suggested tracks
- Don't show loading skeletons when there are no more owned tracks to load
- Shrink suggested tracks height on accounts with fewer than 5 tracks to match content
- Reload ownTracks before hitting the last page of the lineup; reshuffle and start over instead
local web and mobile both exhibiting correct loading behavior for suggested tracks
=> [C-3712, C-3719] Fix loading of suggested tracks

packages/common/src/services/audius-backend/solana.ts, packages/common/src/store/buy-usdc/sagas.ts
This changes sends recovery transactions through payment router so that we can leverage the indexing work added by #7249 .
I opted to split out the recovery logic and write a separate transaction generation function for this flow. Though it does lean on the same slightly quirky underlying usage of `getPurchaseContentWithPaymentRouterInstructions`. The other minor change is the addition of the recovery memo.
fixes PAY-2389
Tested locally against production discovery.
=> [PAY-2389] Perform recoveries via payment router to allow indexing

packages/common/src/messages/sign-on/pages.ts, packages/web/src/components/welcome-modal/WelcomeModal.tsx, packages/web/src/pages/sign-up-page/components/AccountHeader.tsx, packages/web/src/pages/sign-up-page/components/CoverPhotoBanner.tsx, packages/web/src/pages/sign-up-page/components/SocialMediaLoginOptions.tsx, packages/web/src/pages/sign-up-page/pages/ReviewHandlePage.tsx
- Fixes issue where welcome-modal cover-photo wasn't blurring. This is due to `useCoverPhoto` returning `shouldBlur` attribute that wasn't being taken into account. Long term we should improve cover-photo to be a component that handles everything correctly
- Fixes issue were "review handle" cover-photo didn't have border-radius. We assumed "isEditing" a sufficient condition for showing border-radius, but it's more to do with being in a Paper component. Don't love the solve, which is to add a `isInPaper` like prop, but given how close we are to launch this was easiest.
- Fixes issue where social buttons don't have scale animation cause `fullWidth` was true... this is a good case of blocking scale animation on fullWidth is wrong. for now just added width: 100% manually, which is what …
=> [C-3702 C-3672] Fix sign-up cover-photo issues

monitoring/healthz/src/useServiceProviders.ts
timeout ga request to five seconds and load from chain, otherwise it's a lot longer to see nodes on healthz
npm run dev, check stage when stage ga is down
=> add timeout to ga for faster healthz response

packages/common/src/api/track.ts, packages/common/src/store/player/slice.ts, packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/selectArtistPreviewContext.tsx, packages/mobile/src/services/sdk/audius-sdk.ts, packages/web/src/common/store/player/sagas.ts, packages/web/src/pages/sign-up-page/utils/selectArtistsPreviewContext.tsx, packages/web/src/services/audius-sdk/solana.ts
- Improves artist previews by starting 30s into a track
- Improves artist previews by limiting the number of tracks we request. for users with lots of tracks this was leading to big delays in playback
- Ensures premium content can be played be completely reworking how we play and pause tracks by going through `playerActions` rather than operating on `audioPlayer` directly.
=> [C-3668] Improve artist previews

.circleci/scripts/circleci-startup-script.sh, .circleci/scripts/periodic-cleanup
Self-hosted CI: We are filling up 150GB disks with docker artifacts in between the hourly cleanup runs, so let's just run the cleanup every 10 minutes.
Verified new commands work on a CI machine, ran scripts through `shellcheck`
=> Prune the docker cache more frequently

packages/discovery-provider/integration_tests/tasks/test_index_payment_router.py, packages/discovery-provider/src/tasks/index_payment_router.py
For external transfers from a user bank, our convention is to use the account owner address as the transaction metadata. However, the unit tests for the recovery logic had mistakenly created "existing transaction" mocks using the USDC token account instead. So while the tests passed, they were not testing the actual behavior.
This change updates the logic for indexing external transfers and recoveries in payment router to use the account owner address in cases where the account is not a user bank. This brings it in line with how the user bank indexer works.
Tested locally using (correct) integration tests 😅
=> Fix payment router recovery indexing using wrong address for comparison

packages/common/src/api/user.ts, packages/web/src/components/withdraw-usdc-modal/WithdrawUSDCModal.tsx, packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.tsx
* Prevent modal from closing when on the "Hold" stages and "Coinflow" stages
* Recognize transfer in withdrawals to root account and display as Cash (wallet)
* Hide the link to the explorer in the success page
```
```
=> [PAY-2394][PAY-2391][PAY-2393] Address misc coinflow withdrawal ux

packages/common/src/store/pages/profile/selectors.ts, packages/web/src/pages/profile-page/ProfilePageProvider.tsx
Wasn't able to repro this bug, so slapping a fix on it for now.
Selector change covers mobile
Provider gets web and mobile web
profiles loading normally
=> [QA-733] Dedupe albums and playlists on profile

.circleci/src/workflows/release.yml
Builds the openresty container in the release workflow and pushes it so that we don't have the following error anymore: `Error response from daemon: manifest for audius/discovery-provider-openresty:e8d15311bb3978c988ef672ceb6b46fc8f6d990d not found: manifest unknown: manifest unknown`
=> Build openresty image on release

packages/web/scripts/publishScripts.sh, packages/web/src/components/meta-tags/MetaTags.tsx, packages/web/src/components/mobile-page-container/MobilePageContainer.tsx, packages/web/src/components/page/Page.tsx, packages/web/src/pages/track-page/components/desktop/TrackPage.tsx, packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
* Add `noindex` tag to hidden track pages 
* Split `MetaTags` into a components so it can be reused across desktop & mobile web
* Fix error being thrown on worker bc of missing `web3.min.js.map`
=> SSR Follow ups

packages/web/src/components/data-entry/ReleaseDateTriggerLegacy.tsx, packages/web/src/pages/upload-page/fields/ReleaseDateField.tsx, packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx, packages/web/src/pages/upload-page/forms/EditTrackForm.tsx
Include the time in the form when uploading tracks and collections so that tracks that have been uploaded on the same day don't mix on the artists profile
NOTE: This PR doesn't fix the issue of the same tracks in an collection appearing in a different order
Locally tested
=> [C-3234] Update today date to include time so that tracks uploaded on the same day don't mix

package-lock.json, packages/web/package.json, packages/web/src/ssr/worker.js, packages/web/src/ssr/wrangler.toml
* Cloudflare has a sentry integration, but it gets overridden every time the worker is deployed 😂
* Use `toucan-js` on the worker as our sentry client instead
Confirmed that errors are reported to sentry and piped to #eng-incidents-ssr
=> [INF-571] Add sentry logging to SSR worker

packages/common/src/hooks/useDownloadTrackButtons.ts, packages/common/src/services/track-download/TrackDownload.ts, packages/common/src/store/social/tracks/actions.ts, packages/discovery-provider/src/queries/get_track_signature.py, packages/mobile/src/screens/track-screen/DownloadRow.tsx, packages/mobile/src/screens/track-screen/DownloadSection.tsx, packages/mobile/src/screens/track-screen/TrackScreenDownloadButtons.tsx, packages/web/src/common/store/social/tracks/sagas.ts, packages/web/src/components/download-buttons/DownloadButtons.tsx, packages/web/src/components/track/DownloadRow.tsx, packages/web/src/components/track/DownloadSection.tsx, packages/web/src/components/track/GiantTrackTile.tsx, packages/web/src/pages/track-page/TrackPageProvider.tsx, packages/web/src/pages/track-page/components/desktop/TrackPage.tsx, packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx, packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
* Adds `original` query param to `download` request to specify quality.
* Hook this up to segmented control quality selector on both web and mobile.
* Change `onDownload` to object args cuz so annoying.
* Change default behavior on DN when no `filename` req param is specified to always use the original file name. Note: this code path is not currently exercised because we always supply the file name query param from client, but was tripping me up while developing.
Tested both web and mobile with lossless feature flag off and on. Confirmed that with ff on, we get original file names, and with ff off, we get old "Audius" file names.
=> [PAY-2354] Specify quality during track download

.circleci/scripts/periodic-cleanup
Periodic cleanup might remove images during long docker builds, so jobs like test-audius-cmd might finish building after a long time and then fail because the cleanup ran in the background before any containers started.
CI
=> Don't prune most recent images

packages/common/src/schemas/sign-on/emailSchema.ts, packages/mobile/src/screens/sign-on-screen/components/NewEmailField.tsx, packages/web/src/pages/sign-up-page/components/EmailField.tsx
Fixes issue where users were being rate-limited unnecessarily due to our validation running too frequently. Additionally, when users were rate limited, they were allowed to go through sign-up which is problematic because they can accidently try and sign up with the email of an existing user
=> Fix sign up rate-limiting issues

packages/discovery-provider/ddl/migrations/0049_dominant_genre.sql, packages/discovery-provider/integration_tests/models/test_aggregate_counters.py, packages/discovery-provider/integration_tests/tasks/test_update_aggregates.py, packages/discovery-provider/integration_tests/utils.py, packages/discovery-provider/src/models/users/aggregate_user.py, packages/discovery-provider/src/tasks/update_aggregates.py
Add dominant genre to each user
```
pytest integration_tests/tasks/test_update_aggregates.py
```
=> [C-3728] Add dominant genre support to aggregate_user

packages/discovery-provider/integration_tests/queries/test_get_top_genre_users.py, packages/discovery-provider/src/api/v1/users.py, packages/discovery-provider/src/queries/get_top_genre_users.py, packages/discovery-provider/src/queries/queries.py, packages/discovery-provider/src/tasks/index_user_bank.py
Move v1/full/users/genre/top?genre=Electronic queries to use the aggregate table.
Should be very fast now. Bring the cache down to an hour. Probably could be lower / zero, but will leave that to future.
```
pytest integration_tests/queries/test_get_top_genre_users.py
```
=> [C-3729] Move top genre query to use aggregates

packages/discovery-provider/Dockerfile.prod
Upgrades pg_restore in the Discovery Dockerfile. The `seed` container uses this version to re-seed, so it must match the version that was used in `pg_dump`. I upgraded the `pg_dump` version 2 days ago, so now restores fail until they're upgraded to match.
Testing on stage DN3, which currently fails to restore: `pg_restore: [archiver] unsupported version (1.14) in file header`. I'll also test to make sure this doesn't break the Discovery image when used in the `server` and `indexer` containers.
=> Update pg_restore to v15

mediorum/server/serve_crud.go
Use rendezvous to reduce crudr sweep traffic.
Deployed to stage creator 8... sweep response was 1/2 the size.
On prod with more nodes, sweep response should be 1/10th the size.
=> Use rendezvous when gossiping ops

packages/web/src/Root.tsx, packages/web/src/public-site/PublicSite.tsx
A bug was introduced with #7213 that prevented popping history state when going from signup to the landing page. The fix was:
1. Use the shared `history` object for routing in PublicSite
2. In the `window.onpopstate` handler, check the value of window.location rather than the history.location. This is because history.location hasn't updated yet
Confirmed that navigation works properly between the PublicSite and app now (specifically sign up)
=> [INF-650] Fix PublicSite history bug

.dockerignore
After noticing that the load build context step takes up to a minute transfering multiple GBs when building images like relay or identity-service ([example here](https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/50915/workflows/245ad248-5582-4457-be15-3da0292e1151/jobs/665301/parallel-runs/0/steps/0-103)), I narrowed down the problem to being that `.git` and `dist` folders are being included in the build context and copied needlessly into images.
This will save us at least 2GB of data being needlessly piped through the docker daemon and stored on container images, speeding up build times and lowering image sizes.
Note that the top-level .gitignore already includes all dist directories.
Green CI
=> Add dist and .git directories to .dockerignore to speedup build times

.circleci/config.yml
- Fixes monorepo package-lock.json so it has the necessary dependencies to build the harmony package
- Makes CI run the SDK and Harmony workflows on any PR branch that changes the root package-lock.json
=> Fix monorepo package lock

packages/common/src/audius-query/createApi.ts, packages/common/src/audius-query/types.ts
Adds a `forceRefresh` callback that the hook's caller can use to trigger a refresh at will.
The `force: true` option is still useful, but only affects the first render on mount of the component instance. Exposing `forceRefresh` allows the user to trigger the wrapped fetch when a user takes a relevant action on the page.
Also refactoring and separating query hook vs mutation hook result types
this isn't called anywhere yet, but tested web to ensure we're not breaking existing fetch behavior
=> [C-3735] Add forceRefresh to audius-query hook results

monitoring/healthz/src/pages/Nodes.css, monitoring/healthz/src/pages/Nodes.tsx, monitoring/healthz/src/useServiceProviders.ts
* Adds unregistered nodes to healthz in yellow at the bottom so we can look there for a full view of the nodes that a change might impact
* Fixes minor alignment issue with loading and error state
Stage:
Prod:
`npm run dev` - see screenshots above
=> [PROTO-1641] Add unregistered nodes to healthz in yellow

packages/ddex/ingester/Dockerfile, packages/ddex/ingester/cmd/main.go, packages/ddex/webapp/client/src/providers/AudiusSdkProvider.tsx, packages/ddex/webapp/client/src/providers/EnvVarsProvider.tsx
Was saving `{ "data": {"ddexKey": ..., ... } }` from the `/api/env` resp as the `envVars` rather than `{"ddexKey": ..., ... }`. Whoops
Determined problem was the env vars by building and pushing some debug logs to the stage node. Ran locally with fix without manual env file passed in. Verified loaded correctly.
=> Fix sdk not initializing on stage ddex

protocol-dashboard/src/components/IndividualNodeUptimeChart/IndividualNodeUptimeChart.tsx, protocol-dashboard/src/components/ServiceTable/ServiceTable.tsx, protocol-dashboard/src/containers/Node/Node.tsx, protocol-dashboard/src/store/cache/analytics/hooks.ts, protocol-dashboard/src/store/cache/analytics/slice.ts
Changes the protocol dashboard from using each node's self-reported uptime to querying a static set of nodes for every other node's uptime. Uses the result of whichever node returns the highest uptime %.
Note that discovery nodes only check uptime of other discovery nodes, and content nodes only check uptime of other content nodes.
`npm run start:prod` shows nearly all green uptimes now.
=> [PROTO-1638] Use static nodes in uptime reporting

packages/discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py, packages/discovery-provider/src/tasks/entity_manager/entities/track.py
PROTO-1633
Ignore future release dates for public tracks. You should only be able to set a future release date on a hidden track. Client-side already behaves this way but this is just a check for indexing.
Added more integration tests.
=> Block future release dates on public tracks

packages/web/src/components/drawer/Drawer.module.css
100dvh will handle the url bar correctly, but may not be supported in every mobile browser. Previously bottom bar was overlapping buy button -- see Linear.
@rickyrombo I think dvh is how we could rewrite modal to be good but leaving for a future date
=> [PAY-2403] Fix purchase drawer height on small iphones

packages/commands/Dockerfile.prod, packages/discovery-provider/plugins/pedalboard/docker/Dockerfile.prod, packages/identity-service/Dockerfile.prod
We're getting too many false negative CI results due to npm ECONNRESET errors. [Example](https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/51392/workflows/ded38c43-6290-4a16-a486-f8f20e3a11b0/jobs/673353/parallel-runs/0/steps/0-103).
According to [this](https://github.com/npm/cli/issues/4652), setting maxsockets to 1 is a potential workaround.
CI
=> Add maxsockets flag as workaround for constant npm ECONNRESET failures

packages/discovery-provider/integration_tests/tasks/payment_router_mock_transactions.py, packages/discovery-provider/integration_tests/tasks/test_index_payment_router.py, packages/discovery-provider/integration_tests/tasks/test_index_user_bank.py, packages/discovery-provider/integration_tests/tasks/user_bank_mock_transactions.py, packages/discovery-provider/src/models/users/usdc_transactions_history.py, packages/discovery-provider/src/tasks/index_payment_router.py, packages/discovery-provider/src/tasks/index_user_bank.py, packages/discovery-provider/src/utils/helpers.py
This updates our indexing code to remove some of the convoluted recovery logic in favor of using extended types that can be filtered in API responses. It also adds support for the modified transaction flow added in #7388, where we will check special memos to indicate transaction types.
fixes PAY-2440
Integration tests run locally
=> [PAY-2440] Update indexers for cleaner withdrawal flow

dev-tools/compose/docker-compose.yml
Forgot to add ddex-publisher to the top level docker compose yml. 
https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/51443/workflows/b15d5091-6bce-48b7-ab79-0be0cdd7522f/jobs/674538
=> fix ddex-publisher ci

packages/web/src/pages/upload-page/fields/AttributionField.tsx
We are too heavy handed about enforcing hyphens and period. Not even the wikidata for ISRC requires them https://www.wikidata.org/wiki/Property:P1243
This change allows for optional hyphens for ISRC and period for ISWC. Additionally, ISWC may contain period which we were not capturing correctly either.
=> Fix isrc/iswc regex

.circleci/config.yml, .circleci/src/@continue_config.yml, .circleci/src/jobs/@ddex-jobs.yml, .circleci/src/workflows/ddex-publisher.yml, .circleci/src/workflows/ddex-webapp.yml, .circleci/src/workflows/ddex.yml, .circleci/src/workflows/release.yml, packages/ddex/publisher/package.json
=> Add DDEX publisher CI workflow

packages/mobile/src/components/enter-password/EnterPassword.tsx, packages/mobile/src/components/status-message/StatusMessage.tsx, packages/mobile/src/screens/change-password-screen/ConfirmCredentials.tsx
- Use Harmony `PasswordInput` for the change password screens
- Fix a lingering icon bug
- Didnt change old sign up since this is going away soon
local ios:stage
=> Refactor to use Harmony PasswordInput in native

packages/web/src/common/store/upload/sagaHelpers.ts, packages/web/src/pages/upload-page/store/utils/processFiles.ts
These fields were missing from the track metadata during upload.
Uploaded locally, confirmed tracks table got correct values:
=> Upload includes download_conditions splits, orig_filename for stems

monitoring/healthz/src/useServiceProviders.ts
When switching back and forth between stage/prod and discovery/content on the healthz nodes overview, duplicate unregistered nodes would show up. This PR fixes the caching issue which caused the duplicate display.
This is deployed to prod healthz.audius.co where the UI now works as expected.
=> Fix duplicate unregistered SPs on healthz overview

packages/discovery-provider/src/api/v1/helpers.py
`orig_filename` was still missing from stem tracks on client cache, think we need to add it here.
Untested - ran into problems with uploading tracks on local dev stack, this seems like a safe change so going to just test on stage.
=> Add orig_filename to track/stems endpoint

packages/discovery-provider/ddl/migrations/0050_backfill_dashboard_metrics.sql
Backfills missing data introduced by the bug this PR fixed https://github.com/AudiusProject/audius-protocol/pull/7365. 
TLDR, this data has to be interpolated for accuracy as the metrics system we have did not keep the information we needed past a day. The method I used to get these numbers can be reproed here from this gist. https://gist.github.com/alecsavvy/4320c1d4cd6105533f47db8ed8f6abdf
The numbers I put in can be found in this table here, interpolated values are in green and should be left out when running with the script.
The issue: When nodes collect metrics there is two high level steps that happen. First a node on an interval will reach out to all other available registered nodes and pull in their metrics, adding it to its personal ones, and coming up with its own network wide …
=> ONC-1: add metrics backfill

packages/mobile/src/components/drawer/Drawer.tsx, packages/mobile/src/components/drawer/DrawerHeader.tsx
- Fix some drawer icon sizing
local ios:stage
=> Fix drawer icon sizing issue

packages/common/src/models/Track.ts, packages/common/src/services/audius-api-client/ResponseAdapter.ts, packages/common/src/services/audius-api-client/types.ts, packages/discovery-provider/src/api/v1/models/tracks.py, packages/web/src/common/store/cache/tracks/utils/fetchAndProcessStems.ts
Add stem tracks' `orig_filename` to the API request and client models.
EDIT: answer is yes
Question - is it safe to add `orig_filename` as a required param? After the migration will orig_filename be a required field in our db model? I believe it's `Optional` now but do we plan to change that / functionally will it be true that every track will have an `orig_filename`? https://github.com/AudiusProject/audius-protocol/blob/90fd1b104e5321d8da8e50715f9472fa0b6185de/packages/discovery-provider/src/tasks/metadata.py#L43
Tested with stage DN 4 and local web:
=> Add stem orig_filename to tracks/<id>/stems

packages/web/src/pages/private-key-exporter-page/AdvancedWalletDetails.tsx, packages/web/src/pages/private-key-exporter-page/PrivateKeyExporterModal.tsx, packages/web/src/pages/private-key-exporter-page/PrivateKeyExporterPage.module.css
Apparently, `<ModalDrawer>` automatically mucks with the path styles of almost everything by default. That's weird.
=> Fix copy icon color

packages/common/src/hooks/useCoinflowAdapter.ts, packages/common/src/hooks/useDownloadTrackButtons.ts, packages/common/src/models/OpenSea.ts, packages/common/src/services/opensea-client/OpenSeaClient.ts, packages/common/src/services/opensea-client/ethCollectibleHelpers.ts, packages/mobile/src/env/env.dev.ts, packages/mobile/src/env/env.prod.ts, packages/mobile/src/env/env.stage.ts, packages/web/src/common/store/pages/token-dashboard/getWalletInfo.ts, packages/web/src/common/store/pages/token-dashboard/removeWalletSaga.ts, packages/web/src/common/store/pages/token-dashboard/sagas.ts, packages/web/src/common/store/profile/sagas.js, packages/web/src/components/track/DownloadRow.tsx, packages/web/src/components/track/DownloadSection.tsx, packages/web/src/pages/private-key-exporter-page/AdvancedWalletDetails.tsx, packages/web/src/pages/private-key-exporter-page/PrivateKeyExporterModal.tsx, packages/web/src/services/env/env.dev.ts, packages/web/src/services/env/env.prod.ts, packages/web/src/services/env/env.stage.ts, packages/web/src/store/token-dashboard/connectNewWalletSaga.ts
Opensea ended their v1 api, so this all breaks for many reasons. It also seems like they got rid of the "created" event, so the only way to detect creation of the nft is transfer from the NULL addr, which we already did have. 
This is a large change, but it has a limited splash damage.
Previously did not load
=> [ONC-7] Move to opensea api v2

packages/mobile/src/screens/signon/SignOn.tsx
Before: In legacy signup, last digit of OTP code would be cut off in mobile. Also the OTP input would disappear when you hit submit.
After: Fixed
https://github.com/AudiusProject/audius-protocol/assets/36916764/d7b02cba-ecb9-4ecb-a022-26ecd33494d3
=> [Native] Fix OTP paste on mobile [C-3692]

packages/common/src/utils/fileUtils.ts, packages/mobile/src/screens/track-screen/DownloadRow.tsx, packages/mobile/src/screens/track-screen/DownloadSection.tsx, packages/web/src/components/track/DownloadRow.tsx, packages/web/src/components/track/DownloadSection.tsx
Display `.mp3` when selecting mp3 quality and the original file extension when selecting original file quality.
https://github.com/AudiusProject/audius-protocol/assets/3893871/7b14d839-147c-4785-ac1b-99d73f834e8b
=> [PAY-2404] Display correct file extensions when selecting download quality

packages/ddex/README.md, packages/ddex/ingester/constants/constants.go, packages/ddex/ingester/indexer/indexer.go, packages/ddex/ingester/parser/parser.go, packages/ddex/publisher/src/index.ts, packages/ddex/publisher/src/models/parsed.ts, packages/ddex/publisher/src/models/published.ts, packages/ddex/publisher/src/services/publisherService.ts
An insert into uploads triggers the DDEX pipeline down to the publisher inserting into the published collection (does not actually upload to audius).
TODO crawler polls s3 and inserts into the uploads. Then the entire pipeline will be complete.
TODO define schemas and update UI.
Ran ingester and publisher services locally, manually inserted into uploads
=> DDEX indexer -> publisher talking

packages/ddex/webapp/README.md, packages/ddex/webapp/client/src/providers/AudiusSdkProvider.tsx
Makes the ddex webapp re-initialize sdk after it reads env vars from the backend. This should fix the error sometimes seen in console on staging (the /env call in the Network tab shows that ddex key isn't actually missing when this error happens):
=> Fix race condition when initting sdk in ddex

packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
Fixes issue where select-artist page for electronic sub genres weren't loading. this is because the request should use the subgenre directly, (trap, not electronic - trap)
=> Fix electric subgenre select-artist requests

packages/web/src/components/search-bar/SearchBar.tsx
Mobile SSR track page was failing to render due to a tooltip trying to render server-side. It's important that mobile renders properly because crawlers crawl as a mobile device. Going to update the Uptime Robot monitor to check for this
Confirmed mobile is render in SSR
=> [INF-654] Fix mobile SSR render

.circleci/src/commands/@web-commands.yml, .circleci/src/jobs/@web-jobs.yml, .circleci/src/workflows/web.yml, packages/web/vite.config.ts
We were doing this before but disabled it during the CRA -> vite migration because the sourcemap size decreases significantly. Now sourcemaps are back over 25 MB so had to re-enable
Confirmed stage deploy works on CI
=> [C-3762] Unblock stage deploy by uploading sourcemaps to s3

packages/web/src/components/search-bar/SearchBar.tsx, packages/web/src/public-site/components/Footer.tsx, packages/web/src/public-site/components/NavOverlay.tsx, packages/web/src/public-site/components/handleClickRoute.ts, packages/web/src/public-site/pages/landing-page/components/CTAGetStarted.tsx, packages/web/src/public-site/pages/landing-page/components/CTAStartListening.tsx, packages/web/src/public-site/pages/landing-page/components/CaseStudies.tsx, packages/web/src/public-site/pages/landing-page/components/FeaturedContent.tsx, packages/web/src/public-site/pages/landing-page/components/Hero.tsx
"Start Listening" on the landing page was redirecting to sign up instead of trending. This was because `handlClickRoute` was still using `window.history` instead of the Context provided `history` object
Similar issue was fixed in #7356 
Confirmed that all links from public site behave properly. Going to cherry pick on 1.5.64 and 1.5.65
=> [C-3764] Use history in handleClickRoute

.circleci/src/jobs/@web-jobs.yml, .circleci/src/workflows/web.yml, packages/web/turbo.json
This had me scratching my head for a while. Every time the web build hit the turbo cache, the cloudflare ssr worker deploy was much smaller and errored with "Could not find server build"
Turns out we need to persist `node_modules/@brillout/vite-plugin-import-build/dist/autoImporter.js` (and include it in the turbo outputs) because vike updates this file to point at the build. I was able to figure this out by temporarily deleting gitignore and looking at the file changes cause by the vike build
Confirmed that ssr worker deploys properly even when turbo cache is hit
=> Fix SSR deploy cache

packages/web/scripts/workers-site/index.js
Update crawler regex to include ahrefs, bing, yahoo, etc. These crawlers will no longer get redirected to GA but instead get the ssr experience which has meta tags for the track page. This should make these crawler results consistent with google
Confirmed that crawler user agents match the regex
=> Update crawler regex to include all crawlers

packages/discovery-provider/src/queries/search_es.py
Fixes PROTO-683
Exact name and handles are currently buried in user search results. This change adds exact matches for handle and name while adjusting existing parameters to even out.
Replacing custom script score with function score simplifies and improves performance.
`v1/full/search/full?query=isaac&kind=users&limit=4&includePurchaseable=true`
Search for various users while adjusting limit 3 (auto complete), 4 (search page), 40 (full user list).
Tuning parameters until there's a fair balance, improving search quality.
=> Improve user search on exact matches

packages/common/src/hooks/useCoinflowAdapter.ts, packages/common/src/models/Analytics.ts, packages/web/src/common/store/account/sagas.js, packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
Adds a few new analytics events specific to the Coinflow offramp, since we perform a few extra steps and launch a sub-flow for sending a transaction.
fixes PAY-2353
Tested locally. Analytics events are a low-impact change, so not overly concerned.
=> [PAY-2353] Adds offramp analytics

packages/web/src/components/withdraw-usdc-modal/components/TransferSuccessful.tsx
The check for whether to show the destination address and transaction link at the end of the withdrawal process got its condition inverted somehow, such that we fail to show the link for a manual transfer and then show the signature for the bank withdrawal flow.
fixes PAY-2457
=> [PAY-2457] Fix bad conditional for showing transaction link

packages/common/src/models/Track.ts, packages/common/src/services/audius-api-client/types.ts, packages/common/src/store/gated-content/sagas.ts, packages/common/src/store/gated-content/slice.ts, packages/discovery-provider/integration_tests/queries/test_get_usdc_transactions_history.py, packages/discovery-provider/integration_tests/tasks/test_index_user_bank.py, packages/discovery-provider/src/queries/get_nft_gated_track_signatures.py, packages/discovery-provider/src/queries/get_track_signature.py, packages/mobile/src/components/audio/AudioPlayer.tsx, packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts, packages/web/src/common/store/player/sagas.ts, packages/web/src/common/store/social/tracks/sagas.ts
DN now returns signatures for both mp3 and original files, which client would later use to check nft gated track access for users and stream or download the correct files.
Local dapp running against a stage DN that has this code deployed.
=> [PAY-2365] Update logic to access nft gated tracks

packages/common/src/services/audius-api-client/helper.ts, packages/web/src/pages/search-page/components/desktop/SearchPageContent.jsx
Fixes PROTO-1656
The client is unnecessarily forcing all saved entities to the top leading to bad results across users, tracks, etc. The intention is to boost personalized results but Elasticsearch already takes care of that here:
https://github.com/AudiusProject/audius-protocol/blob/5ae87faf0e5916157156d5704712bfa29e64f33b/packages/discovery-provider/src/queries/search_es.py#L435-L440
This also allows us to remove an extra round trip to get only saved entities, server-side. 
Before + After running locally against prod
=> Fix search personalization in client

packages/web/src/components/withdraw-usdc-modal/components/ConfirmTransferDetails.tsx
This got missed in the update to switches and doesn't render the correct style when "checked".
=> Add correct type to manual transfer confirmation switch field

packages/common/src/api/purchases.ts, packages/web/src/pages/pay-and-earn-page/components/PurchasesTab.tsx, packages/web/src/pages/pay-and-earn-page/components/SalesTab.tsx, packages/web/src/pages/pay-and-earn-page/components/WithdrawalsTab.tsx
This takes care of a few console errors I've been seeing while testing the Pay and Earn page. None of these cause any actual problems with the experience. But some of them were generating invalid API calls for certain users that would just be useless requests.
* Updated count API usage on all three tabs to be disabled until we've fetched the user. This was generating validation errors since the API implementation uses zod to attempt to parse `null` to a number before making the request. Good news is that the validation served its intended purpose!
* Updated the purchases and sales APIs to only make the eager fetch requests for tracks if the returned list actually had a length. For users with no sales/purchases, this was generating an API call with no `id` list for the tracks, which gets …
=> Miscellaneous data fetching fixes for Pay and Earn page

packages/web/src/components/search-bar/ConnectedSearchBar.jsx
Searching by #hashtags was not performing a Tag Search, it's merely searching as if it wasn't a tag. The only way to Tag Search on web atm is to click on a tag. This is because onSubmit does not structure the history in the tag search form. 
Fixes PROTO-1659
Mobile doesn't have this issue.
Ran locally against prod, comparing tag searches
After vs. Before
Now you get results that don't just have `onss` in the name but actually results relevant to #onss. Users with #onss in their profile or tracks.
=> Fix tag search navigating on web

.circleci/config.yml, .circleci/src/@continue_config.yml, .circleci/src/jobs/commit-audius-docker-compose-and-notify.yml, .circleci/src/jobs/deploy-stage-nodes.yml, .circleci/src/workflows/ddex-stage.yml
Makes DDEX push containers and update audius-docker-compose commit SHAs when:
- commits merge to the `main` brain (for deploying to stage)
- a new release is cut
This is needed for ddex to auto-upgrade now that it's treated as its own node type.
=> Integrate ddex into CI auto-upgrade

packages/web/src/common/store/upload/sagaHelpers.ts
This reverts commit 8cda5499137d85204ba9bb4213b22e589564b0cf.
Seems like usdc on dev env works now, don't totally remember the context for why the original PR existed in the first place.
Uploading premium tracks + purchasing them on local dev works.
=> Revert "Disable usdc bank split in dev mode (#6300)"

packages/discovery-provider/src/tasks/entity_manager/entities/track.py
Minimum work needed to get download-gated purchases working. Indexers look for `track_price_history` row for corresponding track when indexing a purchase - if no row, then no purchase.
Uploading + purchasing download-gated-only content works on local dev stack
=> [PAY-2461] Create track_price_history row for download-gated-only tracks

packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
https://linear.app/audius/issue/ONC-10/[qa]-suggested-artists-modal-missing-profile-pictures
Artist recommendations pictures were not showing up because of a change in DynamicImage to use the harmony box component. `wrapperClassName` needed to be used instead of `className`
=> [ONC-10] Fix styles for ArtistRecommendations pictures

packages/web/src/common/store/pages/history/lineups/sagas.ts
We were calling the api wrong.
Did a search for `yield* call(apiClient.` and this was the only remaining usage.
wasn't working now it's working
=> [C-3780] Fix track history api call

dev-tools/compose/docker-compose.ddex.yml, packages/ddex/README.md, packages/ddex/ingester/common/types.go, packages/ddex/ingester/constants/constants.go, packages/ddex/ingester/crawler/crawler.go, packages/ddex/ingester/indexer/indexer.go, packages/ddex/ingester/parser/parser.go, packages/ddex/publisher/src/index.ts, packages/ddex/publisher/src/models/indexed.ts, packages/ddex/publisher/src/models/parsed.ts, packages/ddex/publisher/src/models/published.ts, packages/ddex/publisher/src/services/publisherService.ts, packages/ddex/webapp/client/src/components/Collection/Collection.module.css, packages/ddex/webapp/client/src/components/Collection/Collection.tsx, packages/ddex/webapp/client/src/pages/Upload/Upload.tsx, packages/ddex/webapp/server/src/controllers/collectionController.ts, packages/ddex/webapp/server/src/routers/collectionRouters.ts
- Organize tables in UI
- Fix UI sort + pagination
- UI polls collections for updates
- Added collection models for readability in ddex ingester + publisher
- Publisher sets delivery status to "published" once all releases in delivery have been published
- Docker compose reads env from directory-level .env (I think this won't break CI... I see this in some other compose ymls)
TODO in follow up PR(s)
- Publisher connects to s3 and downloads image and audio files. Mock out actual sdk upload step
- Change collection names: indexed -> deliveries, parsed -> pending_releases, published -> published_releases
Tested locally
=> Misc DDEX cleanup + publisher sets delivery status

packages/common/src/services/track-download/TrackDownload.ts, packages/common/src/store/social/tracks/actions.ts, packages/common/src/store/ui/modals/wait-for-download-modal/index.ts, packages/mobile/src/components/wait-for-download-drawer/WaitForDownloadDrawer.tsx, packages/mobile/src/screens/track-screen/DownloadSection.tsx, packages/mobile/src/services/track-download.ts, packages/web/src/common/store/social/tracks/sagas.ts, packages/web/src/components/track/DownloadSection.tsx, packages/web/src/components/wait-for-download-modal/WaitForDownloadModal.tsx, packages/web/src/services/track-download.ts
- Allow downloads to be canceled
- Fix the name of the download in the waiting for download modal when it's a zip download, which was previous just the name of the first track in the zip
Web & mobile:
- Single track download can be canceled
- Multi track zip download can be canceled
=> [PAY-2432][PAY-2462] Cancellable downloads

packages/harmony/src/components/segmented-control/SegmentedControl.mdx, packages/harmony/src/components/segmented-control/SegmentedControl.module.css, packages/harmony/src/components/segmented-control/SegmentedControl.stories.tsx, packages/harmony/src/components/segmented-control/SegmentedControl.tsx, packages/harmony/src/components/segmented-control/types.ts, packages/mobile/src/components/core/SegmentedControl.tsx, packages/mobile/src/screens/track-screen/DownloadSection.tsx, packages/web/src/components/track/DownloadSection.tsx
This adds optional behavior to SegmentedControl to force the tabs to be equal width. This is accomplished by measuring the tabs on first layout via the existing refs, storing the max width, and then setting all the tabs to use that width. We then use this new behavior in the `DownloadSection` to make the quality options the same size.
Some notes:
* The migrated SegmentedControl in Harmony doesn't _quite_ implement the standard yet. I updated it a little bit to get closer, but didn't want to change too much at the risk of breaking layout in all places that use it
* The mobile version doesn't use the correct gap. This is harder to fix due to the way we animate the background between items. I've decided to leave it for now
* Due to the way the width is calculated and set, using this will …
=> [PAY-2423] Render download options in equal-sized tabs

packages/common/src/hooks/useDownloadTrackButtons.ts, packages/common/src/store/stems-upload/selectors.ts, packages/mobile/src/screens/edit-track-screen/EditTrackScreen.tsx, packages/mobile/src/screens/upload-screen/screens/UploadingTracksScreen.tsx, packages/web/src/components/edit-track/EditTrackModal.tsx, packages/web/src/components/stem-files-modal/StemFilesModal.module.css, packages/web/src/components/stem-files-modal/StemFilesModal.tsx, packages/web/src/components/track/DownloadRow.module.css, packages/web/src/components/track/DownloadRow.tsx, packages/web/src/components/track/DownloadSection.tsx, packages/web/src/pages/upload-page/fields/StemsAndDownloadsMenuFields.tsx
- Default mobile usdc pruchase gate to make track downloadable and lossless files available, unless track was already download purchase gated, in which case those fields do not change on mobile track edit.
- Show pending stem upload in web track edit
local web and mobile dapps vs stage
=> [PAY-2434][PAY-2427] Fix miscellaneous lossless issues

packages/web/.gitignore, packages/web/src/pages/dashboard-page/store/sagas.ts
https://linear.app/audius/issue/ONC-15/artist-dashboard-showing-incorrect-streams-for-molly-mcphauls-tracks
Play counts looked to be offset by a month on the artist dashboard. The data coming from the api was correct.
We were using `moment(date)` to format the utc dates coming from the server into month strings to bucket the plays. `moment()` is local time so any timezone past utc resulted in the previous month:
Fix was to use `moment.utc(date)`
Confimed play counts match release dates on artist dashboard:
=> [ONC-15] Fix artist dashboard plays bucketing

packages/discovery-provider/src/solana/solana_helpers.py, packages/discovery-provider/src/tasks/index_user_bank.py
If we don't skip this transaction, we may end up sending an email that looks like a withdrawal
```
import json
from solders.signature import Signature
from solana.rpc.api import Client
from solders.pubkey import Pubkey
c = Client('https://solana-mainnet.g.alchemy.com/v2/9j3Y1hc042MCH0_TqunwotlaFLHF6K4l')
s = Signature.from_string('5mxD7bfs6nrDFKzShg8gJGeQHMhujePWYMpNtDEDdLbsgKMFk62dC8spFmCn6WArPGyFDtFhkWsfGZP1Z8teEbZ1')
tx = c.get_transaction(s, 'json', max_supported_transaction_version=0)
Pubkey.from_string('JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4') in tx.value.transaction.transaction.message.account_keys
```
=> Skip jupiter tx in user bank withdrawal indexing

packages/web/src/components/actions-tab/ActionsTab.module.css, packages/web/src/components/banner/Banner.module.css, packages/web/src/components/banner/CallToActionBanner.module.css, packages/web/src/components/card/desktop/Card.module.css, packages/web/src/components/create-playlist/CreatePlaylistButton.module.css, packages/web/src/components/delineator/Delineator.module.css, packages/web/src/components/drawer/Drawer.tsx, packages/web/src/components/more/More.module.css, packages/web/src/components/nav/desktop/RouteNav.module.css, packages/web/src/components/navigation/Dropdown.module.css, packages/web/src/components/notification/Notification/components/icons.module.css, packages/web/src/components/notification/NotificationModal.module.css, packages/web/src/components/pill/Pill.module.css, packages/web/src/components/search/SearchBar.jsx, packages/web/src/components/search/SearchBar.module.css, packages/web/src/components/share-modal/components/ShareDrawer.module.css, packages/web/src/components/table/components/OverflowMenuButton.module.css, packages/web/src/components/tipping/tip-audio/TipAudio.module.css, packages/web/src/components/track/TrackInfo.module.css, packages/web/src/components/track/mobile/TrackListItem.module.css, packages/web/src/components/upload/PreviewButton.jsx, packages/web/src/pages/audio-rewards-page/components/ExplainerTile.module.css, packages/web/src/pages/dashboard-page/components/AchievementTile.module.css, packages/web/src/pages/history-page/components/desktop/HistoryPage.module.css, packages/web/src/pages/profile-page/components/EditableName.module.css, packages/web/src/pages/sign-on/components/desktop/FollowPage.module.css, packages/web/src/pages/sign-on/components/mobile/FollowPage.module.css, packages/web/src/pages/track-page/components/mobile/ActionButtonRow.module.css, packages/web/src/pages/track-page/components/mobile/ActionButtonRow.tsx
- Fixed more issues in [this thread](https://audius-internal.slack.com/archives/C03C2V84A1L/p1707182196651939)
- Fixed a bunch of icons in web by searching for `g path` in the code (which does not work to target Harmony icons) and working from there.
=> [Web] Fix more icon issues after Harmony migration C-3789

packages/mobile/src/harmony-native/components/Button/Button/Button.tsx, packages/mobile/src/harmony-native/components/Text/Text.tsx, packages/mobile/src/harmony-native/components/input/TextInput/TextInput.tsx
Fixes issues with text and button styles on android. I will follow up with a shadow improvement for the buttons eventually, but for now it is very minor. The core issue had to do with mixing fontWeight and fontFamily.
=> [PAY-2426] Fix native harmony text and buttons

packages/mobile/src/components/premium-track-purchase-drawer/AudioMatchSection.tsx, packages/web/src/components/premium-content-purchase-modal/components/AudioMatchSection.tsx
So that it makes sense for both track purchases and downloadable-content purchases.
=> [PAY-2466] Update  banner copy in purchase flow

packages/mobile/src/screens/track-screen/DownloadSection.tsx, packages/web/src/components/track/DownloadSection.tsx
Was there anywhere else we wanted to update this? Perhaps in upload flow?
=> [PAY-2473] Change 'original' copy to 'lossless' in download section

packages/web/src/components/nav/desktop/NavPopupMenu.module.css, packages/web/src/pages/profile-page/components/desktop/ProfileTopTags.tsx, packages/web/src/pages/upload-page/fields/DatePickerField.module.css, packages/web/src/pages/upload-page/fields/DatePickerField.tsx
- Fix upload release date calendar red icon
- Fix top tags red icon
- Fix AUDIO badge fill changing on hovering the popup menu (this was due to changing it from png to SVG and the Stems popup menu component being overzealous in applying icon styles)
=> Fix red icons + badge hover color in popup menu [C-3799] [C-3798]

packages/mobile/src/components/co-sign/CoSign.tsx
Fixes issue where co-sign placement was incorrect on track page: 
before:
after:
=> [C-3775] Fix co-sign placement

docs/docusaurus.config.js, docs/package-lock.json, docs/package.json
Added Google Analytics integration for docs. Uses latest GA4 with [`@docusaurus/plugin-google-gtag`](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-gtag) config
> npm run build
=> [DVRL-14] - Integrate Google Analytics in Docs

packages/mobile/src/screens/app-drawer-screen/left-nav-drawer/AccountDetails.tsx, packages/mobile/src/screens/app-screen/AccountPictureHeader.tsx, packages/mobile/src/screens/chat-screen/ChatScreen.tsx, packages/mobile/src/screens/notifications-screen/Notification/NotificationProfilePicture.tsx, packages/mobile/src/screens/profile-screen/ArtistRecommendations/ArtistRecommendations.tsx, packages/mobile/src/screens/profile-screen/ProfileHeader/SupportingTile.tsx, packages/mobile/src/screens/search-screen/SearchResults/SearchItem.tsx, packages/mobile/src/screens/settings-screen/AccountSettingsRow.tsx
#7404 replaced all non-harmony avatars on native mobile. I came across a few minor styling issues and fixed them:
* The default `strokeWidth` on harmony `Avatar` is thicker than the prod avatar stroke in a lot of places. Use `strokeWidth='thin'` for these cases
* The stacking of top supporters was broken bc `mr` was being used in an emotion `css` call. This only works on Box components I believe!
* Outstanding: The supporting tile avatar has a dark stroke in dark mode, which is not the case on prod. Waiting on design to get back to me on which route to take here
Link to slack discussion: https://audius-internal.slack.com/archives/C05MUGKK4AG/p1707514008364739
Navigated to all changed avatars in #7404 and confirmed styles looked correct in light/dark mode
=> [C-3802] Match Avatar styles more closely to prod

packages/discovery-provider/src/api/v1/users.py, packages/libs/src/sdk/api/generated/full/models/StemFull.ts
Add `auth_middleware` decorator to history routes.
This makes it so that a signed request coming from sdk can be used to fetch track listening history for a given user as opposed to the status quo which allows anyone to fetch it, provided that they pass a "user_id" along, e.g.
https://discoveryprovider.audius.co/v1/users/7eP5n/history/tracks?user_id=7eP5n
We would like to not expose that in the same way and instead ensure that 7eP5n signs a request to the endpoint
https://discoveryprovider.audius.co/v1/users/7eP5n/history/tracks
Generated sdk changes are unrelated, but 
```
cd packages/libs
npm run gen:dev
```
was run to ensure that adding auth_middleware added no other changes.
_Please describe the tests that you ran to verify your changes. Provide repro instructions & any …
=> [DVRL-10] Add auth_middleware to history route

packages/mobile/src/services/track-download.ts
There were a few different issues here:
* The `flush()` call deletes the file downloaded by RNFetchBlob. On iOS this is fine, since the Share dialog ends up making a copy in whatever location the user selects. But on Android, since we're using Download Manager, the file goes straight to the Download folder (where we want it). So flushing the response deletes the file we just downloaded
* In the multi-file case, we don't want to use the download manager, but instead let the library download the blobs silently, then ZIP them, then use `addCompleteDownload` to show the downloaded file notification for the final ZIP.
* In the Android flow, we weren't dispatching the finished action. So the drawer stayed open permanently.
fixes PAY-2430
fixes PAY-2433
Tested locally on physical device (Pixel …
=> [PAY-2430][PAY-2433] Fix android download logic

packages/mobile/ios/Podfile.lock, packages/mobile/src/services/track-download.ts
This cleans up the logic in `downloadTracks` on mobile to make sure we aren't leaving behind any temporary files or directories. I also realized that the `flush` function we were calling just defers to `fs.unlink` under the hood. So we can just remove the file using the path in the iOS implementation of `onFetchComplete`.
fixes PAY-2484
Tested locally on physical Android device and iOS Simulator against staging
=> [PAY-2484] Ensure temporary download files are always deleted

packages/web/src/components/ai-attribution-modal/AiAttributionButton.tsx, packages/web/src/components/ai-attribution-modal/AiAttributionModal.tsx, packages/web/src/components/ai-generated-button/AiGeneratedCallout.module.css, packages/web/src/components/ai-generated-button/AiGeneratedCallout.tsx, packages/web/src/components/app-cta-modal/AppCTAModal.module.css, packages/web/src/components/app-cta-modal/AppCTAModal.tsx, packages/web/src/components/browser-push-confirmation-modal/BrowserPushConfirmationModal.tsx, packages/web/src/components/buy-audio-modal/components/CoinbaseBuyAudioButton.tsx, packages/web/src/components/buy-audio-modal/components/StripeBuyAudioButton.tsx, packages/web/src/components/buy-audio-modal/components/SuccessPage.module.css, packages/web/src/components/buy-audio-modal/components/SuccessPage.tsx, packages/web/src/components/collapsible-content/CollapsibleContent.module.css, packages/web/src/components/collapsible-content/CollapsibleContent.tsx, packages/web/src/components/data-entry/ReleaseDateTriggerLegacy.tsx, packages/web/src/components/download-buttons/DownloadButtons.tsx, packages/web/src/components/on-ramp-button/OnRampButton.tsx, packages/web/src/components/remix-settings-modal/RemixSettingsModalTrigger.tsx, packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx, packages/web/src/pages/trending-page/components/RewardsBanner.tsx
Migrate some buttons to Harmony. 
Note:
Did not migrate the button in `AppRedirectPopover` deliberately, as design wants to leave it as-is for now until they have time to revisit. 
Tested and verified in browser.
=> Migrate some buttons to Harmony [C-3751]

protocol-dashboard/src/components/AppBar/AppBar.module.css, protocol-dashboard/src/components/AppBar/AppBar.tsx, protocol-dashboard/src/components/ConnectMetaMaskModal/ConnectMetaMaskModal.module.css, protocol-dashboard/src/components/ConnectMetaMaskModal/ConnectMetaMaskModal.tsx, protocol-dashboard/src/services/Audius/AudiusClient.ts, protocol-dashboard/src/services/Audius/helpers.ts, protocol-dashboard/src/services/Audius/setup.ts
This PR fixes issues w/ connecting MetaMask to the protocol dashboard when Phantom is installed along with MetaMask, which was previously problematic. It also makes it easier for users to troubleshoot the "MetaMask Misconfigured" state.
Important context:
If both Phantom and MetaMask are installed, Phantom will prompt the user to pick either MetaMask or Phantom as their wallet extension UNLESS the user has their settings set to use Phantom by default or MetaMask by default. If the prompt is ignored, or the user picks Phantom, the protocol dashboard will of course not work correctly.
Changes in this PR:
1. Fixes issue where dashboard didn't think you had MetaMask installed at all if you had both MetaMask and Phantom installed
2. If user has both MetaMask and Phantom installed:
a. If user …
=> Improve Connect MetaMask UX, esp. when both MetaMask and Phantom are installed [C-3750]

packages/mobile/src/services/track-download.ts
We don't need to manually specify mime type for downloads. As we thought, the content type in the fetch request works just fine. I was able to download mp3s for compressed versions and both a WAV and AIFF for lossless versions on Android.
fixes PAY-2414
Tested locally on physical device against staging
=> [PAY-2414] Remove manual mime type specification for Android downloads

packages/mobile/src/screens/change-email-screen/SubScreens.tsx, packages/web/src/components/change-email/ChangeEmailModal.tsx
PAY-2486
- Change copy from "Please enter your current email and password." to "Please enter your current password."
- Add current email on the "new email" screen on mobile (whoops!)
=> [PAY-2486] Change Email: Copy changes and current email screen on mobile

packages/mobile/src/harmony-native/components/input/TextInput/TextInput.tsx
Fixed the harmony handle field floating on the wrong side
ios:stage
=> Fix native handle field floating on the wrong side

packages/mobile/src/components/core/KeyboardAvoidingView.tsx, packages/mobile/src/screens/sign-on-screen/components/layout.tsx, packages/mobile/src/screens/sign-on-screen/screens/ConfirmEmailScreen.tsx
=> [C-3659] Float continue button above keyboard on native OTP

packages/mobile/src/harmony-native/components/input/TextInput/TextInputAccessoryView.tsx
Conditionally not render `InputAccessoryView` based on platform
=> Don't render InputAccessoryView on non-iOS platforms

packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx, packages/web/src/components/usdc-manual-transfer/USDCManualTransfer.tsx
This was never wired up
```
```
1. Visit $2 track w/ $1 in balance
2. Select Manual Crypto Transfer
3. Send $1 when and then click Buy when the button turns green
4. Purchase goes through
=> [PAY-2472] Make USDCManualTransfer modal buy button actually buy

packages/harmony/src/components/segmented-control/SegmentedControl.module.css
The extra padding breaks layout in at least one place that uses SegmentedControl. It's not necessary for now, and all the usages can be updated when we formally migrate SegmentedControl to its Harmony spec.
Verified locally against staging.
=> Remove extra horizontal padding from SegmentedControl tabs

packages/discovery-provider/src/tasks/update_aggregates.py
The `where rg.genre_rank = 1` condition to select the dominant genre would omit updates for any [user with no tracks](https://linear.app/audius/issue/C-3769/%5Bqa%5D-profile-track-number-not-updating)...
Move this instead to a join condition on the left join.
=> [C-3769] Fix where condition for aggregate_user query.

packages/common/src/utils/fileUtils.ts, packages/mobile/src/services/track-download.ts, packages/web/src/services/track-download.ts
Append -1, -2 to filenames when there are multiples with the same name.
Haven't tested with more than 2 dups (upload currently broken on stage).
=> [PAY-2468] Dedup filenames during download

packages/mobile/src/components/drawer/Drawer.tsx
Currently when you close a drawer, there's a decent bit of time for the spring animation for settle and the `onClosed` handler to get called. This can give bugs like the one at hand where errors don't seem to clear from previous incarnations of the same drawer (though they are correctly cleared on the `onClosed` handler).
Adding overshoot clamping to the drawer slide-out animations solves this because `onClosed` fires much sooner (though still after the drawer slides out fully).
I don't think this has any adverse effects... but lmk if you have ideas!
```
```
Manually added a throw new Error() in the coinflow purchase flow and was able to repro the bug when …
=> [PAY-2478] Add overshoot clamping to drawer close

packages/mobile/src/components/core/ContextualMenu.tsx, packages/web/src/pages/upload-page/fields/StemsAndDownloadsField.tsx
Because `value` was used as the key for this react component, you could end up with duplicated line items for stems with the same names.
```
```
=> [PAY-2465] Fix contextual menu stems

packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx
Fixes issue where action-buttons were misaligned due to IconButton and AnimatedButton having different default heights. Temporarily updates IconButton height to be equal to AnimatedButton in the action-button row. Long term, AnimatedButton should have same properties as IconButton.
=> Fix action-button alignment

packages/discovery-provider/src/tasks/index_payment_router.py
I think there's a memory leak in payment router maybe in this change https://github.com/AudiusProject/audius-protocol/pull/7510/files. This task appears to be bringing down the whole discovery node. Adding a hard time_limit to the task to try to prevent this. 5 minutes seems ample.
https://docs.celeryq.dev/en/stable/reference/celery.app.task.html#celery.app.task.Task.time_limit
Tested on stage DN1. index_payment_router is indexing.
=> Add time limit for payment router

packages/discovery-provider/src/queries/get_remixable_tracks.py, packages/discovery-provider/src/queries/get_top_playlists.py
Presumably something changed either in sql alchemy or postgres that leads score to be a `Decimal` class type rather than an integer. Python floats are 64 bit which is plenty, so this is safe.
Manually edited stage dn1 and fixed the query
https://discoveryprovider.staging.audius.co/v1/full/tracks/remixables?limit=1&user_id=bQJdO&with_users=true
=> Patch decimal return type serialization

mediorum/server/transcode.go, mediorum/server/upload_client.go
Quick fix for a situation where #2 mirror was retranscoding the same file repeatedly...
Because R=5 and file is sent to peers one at a time, for a large audio file it can take over a minute to send to all peers, but the  `findMissedJobs` would run and if it had been 1 minute since last update, #2 would restart job.
So increase that timeout a bit.
Some better fixes:
* mirror files in parallel
* add a upload lock in local transcode queue, don't re-add an item if it's in the pipeline
Also:
* only send transcode progress updates if `progress - lastProgress > 0.1` to chill out the crudr push frequency a bit
=> Relax timeout for re-doing transcode

packages/identity-service/src/routes/tiktok.js
* Update our TikTok oauth calls in identity-service to v2
* Ensure compatiblility with old clients
* Remove custom `redirectUrl` query param. This was not compatible with `access_token` call requiring the redirectUrl, and it wasn't used anywhere
Confirmed that tiktok auth is working on local web. Will double check on stage
=> [C-3732] Update tiktok oauth calls in identity-service to v2

packages/mobile/src/screens/track-screen/DownloadRow.tsx, packages/web/src/components/track/DownloadRow.tsx, packages/web/src/components/track/DownloadSection.tsx
Bug was that on tracks with follow-gated downloadable content, the stem rows would show the download button as enabled, while the original track's download button would be disabled. Fix is to pass in `parentTrackId` and calculate the UI flags from that.
=> Fix follow-gated download row on web

packages/ddex/ingester/common/sdk_types.go, packages/ddex/ingester/common/types.go, packages/ddex/ingester/indexer/indexer.go, packages/ddex/ingester/parser/parser.go, packages/ddex/ingester/parser/sony_parser.go, packages/ddex/publisher/package.json, packages/ddex/publisher/src/app.ts, packages/ddex/publisher/src/index.ts, packages/ddex/publisher/src/models/deliveries.ts, packages/ddex/publisher/src/models/pendingReleases.ts, packages/ddex/publisher/src/models/publishedReleases.ts, packages/ddex/publisher/src/services/publisherService.ts, packages/ddex/publisher/src/services/s3Service.ts, packages/ddex/publisher/src/services/sdkService.ts, packages/ddex/webapp/client/src/components/Collection/Collection.tsx
- Makes the DDEX publisher app download files from S3 so it can upload them to Audius
- Fixes miscellaneous type issues to make SDK (mostly) accept uploads
- Improves Mongoose types to be simpler and to be able to compare publish_date vs now() accurately
- There's still an error blocking upload due to relay trying to use the DDEX app's key to find a username (instead of the user's wallet)
Running the publisher locally downloads the correct files and kicks off the SDK upload (gets past previous errors but fails due to unrelated existing relay bug mentioned above).
=> [PROTO-1661] Make ddex download from S3 and publish via Audius SDK

packages/discovery-provider/Dockerfile.prod, packages/discovery-provider/src/queries/get_health.py, packages/discovery-provider/src/queries/health_check.py
Found cases where server container is stuck in a restart loop. If health check has any errors, it restarts from autoheal. The container health should represent if the server is reach-able, regardless of error status as those errors come from indexing. This should make the server container more stable. 
Tested on sandbox. Forced errors and confirmed bypass_errors prevent restart loop.
=> Bypass errors on health check for autoheal

packages/discovery-provider/src/utils/multi_provider.py, packages/libs/src/services/ethWeb3Manager/EthWeb3Manager.ts, packages/libs/src/utils/estimateGas.ts, packages/libs/src/utils/multiProvider.ts, protocol-dashboard/src/components/ConfirmTransactionModal/ConfirmTransactionModal.tsx, protocol-dashboard/src/components/TransactionStatus/TransactionStatus.tsx, protocol-dashboard/src/store/actions/cancelTransaction.ts, protocol-dashboard/src/store/actions/submitTransaction.ts
When you perform certain actions on the protocol dashboard where gas estimation fails (likely because transaction simulation shows that the tx itself would fail), we pass a huge default gas limit along to ensure that the transaction never runs out of gas. In practice, the transaction likely fails anyway because simulation failed and you end up using some small amount of the insanely high gas limit.
Couple changes: 
* ⚠️ estimate gas can throw an error instead of falling back to the default and will do so for all protocol dashboard<>metamask interactions (ethWeb3Manager.sendTransaction with an external wallet). Metamask does their own gas estimation, so don't even pass our estimation along, but try to estimate for the UX benefit of quitting early
* sdk(libs)/discovery: Have multi provider …
=> ⚠️ [ONC-19] Error on failed gas estimation

packages/ddex/ingester/parser/parser.go, packages/ddex/publisher/src/services/publisherService.ts
- Removes an old leftover import which was breaking CI
- Avoids uploading individual tracks when a delivery contains an album release, which is my interpretation of [this](https://kb.ddex.net/implementing-each-standard/best-practices-for-all-ddex-standards/guidance-on-releaseresourcework-metadata/trackreleases/) and [this](https://kb.ddex.net/implementing-each-standard/best-practices-for-all-ddex-standards/guidance-on-releaseresourcework-metadata/release-types-for-trackreleases/). This will have to be more thorough in the future to use the actual `Deal` elements to determine visibility of each track in the album, but the matching up of `DealType`s to our metadata isn't figured out yet.
=> Dedupe tracks in album and fix broken import

packages/harmony/src/components/text/Text/constants.ts, packages/mobile/src/harmony-native/components/Text/Text.tsx
Fixes issue where label text other than medium size has poor alignment. This is due to the configured lineHeight. I updated it to a reasonable value that prevents the issue, and will follow up with design to officially change the line-height in harmony.
Fixes issue where demiBold text in iOS has a weird alignment issue, that is resolved by adding marginTop: 2px. This is pretty awkward so going to check with design if the font asset maybe has an issue.
=> [C-3709 C-3814] Fix native text aligment issues

packages/web/src/components/track/DownloadSection.tsx
Wasn't removed in https://github.com/AudiusProject/audius-protocol/pull/7583 which moved behavior to the wait for download modal.
```
```
+ download all. chrome notif is no longer present for multiple downloads.
=> [PAY-2498] Fix multiple download warning in web

packages/discovery-provider/scripts/start.sh
We're seeing OOM in the indexer container coming from a non index_nethermind celery task. This will help find which tasks have a memory leak.
=> Log active tasks and mem usage

packages/mobile/src/screens/favorites-screen/TracksTab.tsx, packages/web/src/common/store/pages/saved/lineups/sagas.ts, packages/web/src/common/store/pages/signon/sagas.ts
Fixes a few issues where local saves and remote saves can be duplicated.
The first issue was due to an issue where we dont increase the favorited tracks lineup page after the first request, this means that we accidently fire off two "fetchLineup" requests back to back, since the "fetchMore" function always fetches since page is still at 0.
The second issue was related to the saved/lineup/saga.ts always adding localLibrary additions to the beginning of the fetched tracks, meaning every paginated request would unconditionally include localLibrary tracks, which we actually only want on the first fetch.
Additionally we fixed an issue where localLibraryTrackIds was `string[]` and savedTrackIds was `number[]` meaning our `uniq()` call would technically never remove duplicate tracks.
Taken …
=> [C-3821] Fix native double save

packages/discovery-provider/src/solana/solana_client_manager.py
This should be safe and should make indexing grab solana transactions quicker
"confirmed" should work: https://github.com/michaelhly/solana-py/blob/36ab2b5343d3f45cbe562df86e2d04101e101e71/src/solana/rpc/commitment.py#L16
Untested, test on stage
=> Indexers fetch confirmed sol txs instead of finalized

packages/identity-service/src/typed-routes/solana/solanaRelayChecks.ts, packages/libs/src/services/solana/SolanaWeb3Manager.ts
Trying this out to see if this speeds things up.
Tested on stage identity + local web. Did not test coinflow.
=> Add priority fee ixs to purchase txs

packages/mobile/ios/Podfile.lock, packages/mobile/package.json
We see an error on android devices that looks exactly like this when trying to download files:
https://github.com/joltup/rn-fetch-blob/issues/795
Likely due to react native upgrading.
I am personally unable to reproduce this issue, but want to get this change merged, which is a suggested fix in the comments, to test it out.
The long term play is to move to https://github.com/RonRadtke/react-native-blob-util
Doesn't crash when running on device, but I don't know if that's a good test. Will test on stage.
=> [PAY-2493] Upgrade RNFetchBlob to 0.13.0-beta.1

packages/mobile/src/components/audio/AudioPlayer.tsx
This reverts commit 589ed010203d01b61a165ed2c3f38eb7ec86034b.
Will address next week
=> Revert [C-3561] Improve playback delay when playing track on mobile

packages/mobile/src/components/fields/PasswordField.tsx, packages/mobile/src/harmony-native/components/CoverPhoto/CoverPhoto.tsx, packages/mobile/src/harmony-native/components/input/TextInput/TextInput.tsx, packages/mobile/src/screens/root-screen/RootScreen.tsx, packages/mobile/src/screens/sign-on-screen/components/layout.tsx, packages/mobile/src/screens/sign-on-screen/screens/CreatePasswordScreen.tsx, packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/FollowArtistCard.tsx, packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/SelectArtistsScreen.tsx, packages/web/src/common/store/pages/signon/sagas.ts
Addresses all of these:
ios:stage & android:stage
=> Native Sign Up Various QA Fixes

packages/common/src/store/purchase-content/sagas.ts
The real issue was just that we never handled PurchaseMethod.CRYPTO here, but I refactored this code so that it uses a switch statement where the typecheck would have protected us.
```
npm run android:stage
```
=> [PAY-2503] Fix mobile crypto transfer purchase flow

dev-tools/compose/docker-compose.discovery.prod.yml
This PR: https://github.com/AudiusProject/audius-protocol/pull/7582
Most likely broke audius-cmd because there is no health check protecting audius-compose from coming up and resolving before discovery is healthy.
Wait for CI
=> Fix audius-cmd health check

packages/discovery-provider/src/app.py
Match parity with payment router. Most of the runs are no-ops anyways.
=> Make user bank indexer run ever 1s instead of 5

packages/mobile/android/app/src/main/AndroidManifest.xml, packages/mobile/ios/Podfile.lock, packages/mobile/package.json, packages/mobile/src/services/offline-downloader/offline-storage.ts, packages/mobile/src/services/track-download.ts, packages/mobile/src/store/offline-downloads/sagas/migrateOfflineDataPathSaga.ts, packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadCollectionWorker.ts, packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadFile.ts, packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts, packages/mobile/src/store/offline-downloads/sagas/watchRemoveOfflineItems.ts, packages/mobile/src/utils/generatePlaylistArtwork.ts
Migrate RNFetchBlob to ReactNativeBlobUtil. The API is the same because it's a fork, but hopefully this addresses the issue from https://github.com/joltup/rn-fetch-blob/issues/795 that we still see after upgrading to the beta version.
Impacted features (both iOS and android mobile):
* Downloads
* Offline mode
* Playlist artwork
Note that the latest version does not work on android (fun!), so I'm using 0.19.4 here. see https://github.com/RonRadtke/react-native-blob-util/issues/321
Tested both iOS and android on simulator and got working downloads.
* Downloads work
* Create playlist is super broken as is it seems... so hard to test this here.
* Offline mode on a playlist & album
=> ⚠️ [PAY-2493] Replace RNFetchBlob with ReactNativeBlobUtil

packages/ddex/ingester/common/sdk_types.go, packages/ddex/ingester/common/types.go, packages/ddex/ingester/parser/sony_parser.go, packages/ddex/publisher/src/models/pendingReleases.ts, packages/ddex/publisher/src/models/publishedReleases.ts, packages/ddex/publisher/src/services/publisherService.ts, packages/ddex/publisher/src/services/sdkService.ts, packages/ddex/webapp/client/src/components/Banner/Banner.tsx, packages/ddex/webapp/client/src/components/Collection/Collection.tsx, packages/ddex/webapp/client/src/pages/Home/Home.tsx, packages/ddex/webapp/client/src/pages/Upload/Upload.tsx, packages/ddex/webapp/client/src/providers/AudiusSdkProvider.tsx
- Adds failure counts+visibility to pending releases, including flagging for manual intervention when an error is thrown after a track or album was already uploaded
- Changes scope from "read" to "write" (this was making indexing silently fail for DDEX uploads)
- Cleans up imports and schemas for readability and stricter enforcement
Track and album uploads both work on staging, and my local UI displays errors that happen during or after an upload.
=> [PROTO-1665] DDEX: Add failure states, fix write scope, and clean up

packages/mobile/src/components/track-list/TablePlayButton.tsx, packages/mobile/src/components/track-list/TrackArtwork.tsx, packages/mobile/src/components/track-list/TrackListItem.tsx
Fixes two icon colors for native mobile. One of them is fairly obvious, which shows up when user plays a collection on the collection page
=> Fix mobile play icons

packages/mobile/tsconfig.json
Auto imports of common in mobile were going to `~/`. Adding this path fixes it
=> Fix mobile @audius/common auto imports

packages/discovery-provider/ddl/migrations/0052_remove_dashboard_wallet_users_fkey.sql, packages/discovery-provider/src/models/grants/developer_app.py, packages/discovery-provider/src/models/grants/grant.py, packages/discovery-provider/src/models/playlists/playlist.py, packages/discovery-provider/src/models/social/follow.py, packages/discovery-provider/src/models/social/repost.py, packages/discovery-provider/src/models/social/save.py, packages/discovery-provider/src/models/tracks/track.py, packages/discovery-provider/src/models/users/user.py
```
Error in indexing blocks (psycopg2.errors.ForeignKeyViolation) update or delete on table "blocks" violates foreign key constraint "dashboard_wallet_users_blockhash_fkey" on table "dashboard_wallet_users"
DETAIL:  Key (blockhash)=(0x926644ae257bfdd060f45eff0023d2f124910bc8eb70f7471149a18fcdfca957) is still referenced from table "dashboard_wallet_users".
[SQL: DELETE FROM blocks WHERE blocks.blockhash = %(blockhash_1)s]
[parameters: {'blockhash_1': '0x926644ae257bfdd060f45eff0023d2f124910bc8eb70f7471149a18fcdfca957'}]
(Background on this error at: http://sqlalche.me/e/gkpj)
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context
self.dialect.do_execute(
File …
```
=> Drop dashboard wallet users blockhash fkey

packages/web/src/components/track/desktop/TrackTile.module.css, packages/web/src/components/track/desktop/TrackTile.tsx
Small update to the playing volumeIcon on track tile to prevent them from shifting content
=> [ONC-28] Fix track tile icon size

packages/common/src/services/remote-config/feature-flags.ts, packages/mobile/src/hooks/useTikTokAuth.ts
TikTok confirmed that the legacy mobile sdk will continue working after Feb 29 sunset date of v1 auth apis, but I'm adding a feature flag specifically to the native mobile auth just in case we do see something break. This way we can disable native auth and fallback to the web auth flow
Confirmed that the flag enables native auth and falls back to web auth
=> [C-3842] Add feature flag for native TikTok auth

packages/discovery-provider/ddl/migrations/0053_cascade_delete_dashboard_wallet_users.sql
Follow up https://github.com/AudiusProject/audius-protocol/pull/7629
Nvm the node is still blocked, it wasn't working cuz this cascade delete was missing. Confirmed all other fkeys have this cascade delete.
=> Cascade delete on dashboard wallet users fkey

packages/web/src/components/track/DownloadRow.tsx, packages/web/src/components/track/DownloadSection.tsx
Noticed mobile web was bonked.
Before:
After:
Normal web still ok:
=> [PAY-2509] Bring lossless downloads mobile web up to spec

packages/mobile/src/components/bottom-tab-bar/bottom-tab-bar-buttons/BottomTabBarButton.tsx
Fixes issue where android bottom bar buttons don't unset when inactive. It appears there is a big with rive .stop on android. .reset() works for both platforms and looks the same.
=> [C-3852] Fix android bottom bar button colors

packages/common/src/store/cache/collections/reducer.ts
uids were not present in the playlist_contents of certain collections in the cache so they were not playable bc lineups use the uids to queue and play and stuff. This just adds uids if they are not present when the collections are being added to the store
=> [ONC-27] Update collection cache reducer to add track uids to tracks in playlist_contents if not present

packages/web/src/assets/img/phantom-icon-purple.svg, packages/web/src/services/web3-modal/index.ts, packages/web/vite.config.ts
Problem: 
Custom web3 provider logos weren't loading in the wallet connect modal because web3modal (external package) expects a raw image, but we were passing in SVGR SVG components due to adding SVGR to our Vite config a few months ago.
Solution:
Exclude the two logo files in question from SVGR scope so that they are just imported as raw image data.
Before:
After:
=> Fix wallet connect icons [C-3871]

packages/web/src/components/collection/desktop/OwnerActionButtons.tsx
Previously the code was referencing a `track_count` that seems to no longer be returned from the API. You can derive this from playlist_contents though. This was causing the Share button on someones personal album page to be disabled.
Run `npm run web:prod` and navigate to an uploaded album you have. The share button should be functional now.
=> fix self album share button

packages/discovery-provider/src/app.py
This job uses so much memory it takes down nodes running 16 GB. Disabling to prevent this, and will move to elasticsearch.
Currently running on stage.
=> Disable related artists job

packages/discovery-provider/src/api/v1/tracks.py
Weirdness is that this only happened for a few stems, it was not a global lossless mp3 issue. Fix is that the request to get the first byte from content node returned with a status code of 200, whereas we were expecting 204 or 206. Although, it's not clear to me from CN side why it would be 200 only some of the time. It would seem like this line is what returns the data:
`if isAudioFile {
ss.recordMetric(StreamTrack)
http.ServeContent(c.Response(), c.Request(), cid, blob.ModTime(), blob)
return nil
}`
and not clear to me why the blob, gotten from `blob, err := ss.bucket.NewReader(ctx, key, nil)` would do that.
stage web dapp against stage dn2 which had my commit deployed onto it. downloading https://staging.audius.co/raylosslessqa/3-free-lossless-stems lossless mp3 worked; they used to …
=> [PAY-2508] Fix download lossless mp3 failure

packages/discovery-provider/ddl/README.md, packages/discovery-provider/ddl/local-test.sh, packages/discovery-provider/ddl/migrations/0054_nullable_dominant_genre.sql
Follow up to: https://github.com/AudiusProject/audius-protocol/pull/7575#pullrequestreview-1878611988
Prior PR fixed the select, but destination column was not null... so this fixes that.
=> make dominant_genre_count nullable

packages/web/src/components/play-bar/desktop/PlayBar.jsx
There are intermittent cases where the playbar gets unmounted/remounted on initial page load (error boundaries? SSR?). We don't unregister our hotkeys in the playbar component. And the way it's wired up results in a `dispatch()` call in each case. This fixes the bug for now. Longer term fix is to migrate this component to hooks and use `useHotkeys()` which has the correct behavior built in.
fixes ONC-17
Tested locally against prod. Used logpoints to make sure the reproduction case was triggered.
=> [ONC-17] Remove hotkeys on unmount of playbar to prevent double-triggers

.circleci/config.yml
Updates our CI triggers to use workflow name instead of the trigger name. This is more versatile and lets us trigger workflows manually if something doesn't go right in the scheduled trigger.
I have updated all scheduled triggers to include the correct `workflow` param
CI Runs on main, will confirm after merge it works via triggered release
=> Allow CI workflows to be manually triggered

.circleci/config.yml
Fixes how we generate changelog, we need to use tag rather than branch name, because this all needs to happen on main branch
=> Fix release tag reference

packages/mobile/src/harmony-native/components/input/TextInput/TextInput.tsx
Remove all default padding on text inputs so that it doesn't show up on android
=> [C-3861] Remove default padding on text inputs for andoird

packages/discovery-provider/requirements.txt
dnspython upgraded to 2.6.0 which causes server container to get stuck in a restart loop.
```
[2024-02-21 21:07:26 +0000] [20] [ERROR] Exception in worker process
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/eventlet/support/greendns.py", line 456, in resolve
return _proxy.query(name, rdtype, raise_on_no_answer=raises,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/site-packages/eventlet/support/greendns.py", line 412, in query
return end()
^^^^^
File "/usr/lib/python3.11/site-packages/eventlet/support/greendns.py", line 391, in end
raise result[1]
File "/usr/lib/python3.11/site-packages/eventlet/support/greendns.py", line 372, in step
a = fun(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^
File …
```
=> Pin dnspython to version 2.5.0

docs/docs/developers/log-in-with-audius.mdx, docs/docs/developers/sdk-oauth-methods.mdx, packages/web/src/pages/oauth-login-page/hooks.ts, packages/web/src/pages/oauth-login-page/utils.ts
Allows apps to validate that the jwt generated used was from their app (and not forged).
Will test auth flows on stage, but change should be safe. Discovery node verify endpoint simply returns the entire payload.
=> [C-3881] Add apiKey to the jwt payload

packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/PreviewArtistHint.tsx
Increase the touch target of the close a bit
Before: 
After:
=> [C-3863] Increase touch target of close button of artist preview banner

packages/ddex/ingester/common/common.go, packages/ddex/ingester/crawler/crawler.go, packages/ddex/ingester/indexer/indexer.go, packages/ddex/ingester/parser/parser.go
- Makes Mongo change streams catch up where they left off between restarts / offline time
- Cleans up shared code between the DDEX services
- Makes some expected parsing errors recoverable instead of using log.Fatal
=> [PROTO-1669] Find Mongo changes when offline and clean up DDEX

packages/mobile/ios/AudiusReactNative.xcodeproj/xcshareddata/xcschemes/Staging.xcscheme, packages/mobile/ios/Podfile, packages/mobile/ios/Podfile.lock, packages/mobile/package.json
* Remove Flipper (deprecated)
* Set `--experimental-debugger` flag
* Working on doc with debugging instructions: https://www.notion.so/audiusproject/React-Native-Debugging-863813850b7a43c098b48d41acefd825
Next up -> redux dev tools
Confirmed debugger working on ios simulator and android emulator. Going to test on device still
=> [INF-659] Remove flipper and enable experimental debugger

packages/web/src/components/track/DownloadRow.tsx
=> [PAY-2513] Fix file size text wrap on web DownloadRow

.circleci/src/jobs/@mobile-jobs.yml
Co-authored-by: Saliou saliou@audius.co
Co-authored-by: Reed reed@audius.co
Co-authored-by: Ray ray@audius.co
Fixes issue where env key injection fails because some config files don't have a new line. This updates the injection script to ensure we always add a new line before adding env key
=> Fix amplitude key injection on mobile

packages/web/scripts/workers-site/index.js, packages/web/src/ssr/worker.js
Changes in the worker caused `/.well-known/apple-app-site-association` to no longer serve the correct file. Fixed this by including `/.well-known` in the list of asset paths
Edited prod worker to confirm file is served correctly
=> Fix app site association

packages/mobile/src/screens/sign-on-screen/screens/SignOnScreen.tsx
Add bottom padding to avoid the link being covered by android os buttons
Padding looked good on ios simulator and Android device
=> [C-3880] Add bottom padding to the safe area on the sign in screen

packages/web/src/components/page/Page.tsx
Not quite sure what changed and how this actually triggers, but recently on dev, stage, and prod, I've been seeing a partial load of all pages where the opacity never moves from 0.2. It seems like moving to the useSpring hook model instead of the cjs component works.
Can't repro any more, but maybe not a for-sure fix.
=> Fix half-load of spring animation on all <Page> components

packages/web/scripts/workers-site/index.js, packages/web/src/ssr/worker.js
Fixes errors with pages that show assets from the `documents` folder (such as privacy policy and TOS)
This is porting a change already live on CF, so tested in prod! 😅
=> Add documents path to asset url check

packages/mobile/src/screens/sign-on-screen/components/WelcomeDrawer.tsx
Was originally looking into the overlap issue, but noticed this bug.
Just added the open notif drawer call to the onClose of the drawer
=> Update welcome drawer close functionality to always open the notifications drawer

packages/web/src/app/web-player/WebPlayer.jsx, packages/web/src/store/application/ui/theme/sagas.ts, packages/web/src/utils/theme/theme.ts
Fixes issue where systemAppearance is never set properly on web, which results in bug where harmony dark styles are not applied when theme === "AUTO" and user system is dark-mode
=> Fix harmony system-appearance

.circleci/src/jobs/commit-audius-docker-compose-and-notify.yml
In case ci has updated the git hashes before the release job does - allow an empty `release-v0... auto-deploy` commit so the day's release can proceed.
=> Allow empty adc auto-deploy commits

dev-tools/compose/docker-compose.blockchain.yml
Fixes I typo I added which was breaking `audius-compose push`. Tested by confirming that `audius-compose push --prod "mediorum"` no longer errors with `no such service: eth-ganache`.
=> Fix typo breaking audius-compose push

packages/mobile/src/app/navigation/useScreenOptions.tsx, packages/mobile/src/screens/sign-on-screen/SignOnStack.tsx, packages/mobile/src/screens/sign-on-screen/components/SignUpFlowTikTokAuth.tsx, packages/mobile/src/screens/sign-on-screen/components/SocialMediaLoading.tsx, packages/mobile/src/screens/sign-on-screen/components/useSocialMediaLoader.tsx, packages/mobile/src/screens/sign-on-screen/screens/PickHandleScreen.tsx
Adjustments to the "social loading" screen 
- Add a short timer so that it doesn't appear right as the user is going away
- Remove the X on the pick handle page so that there isn't an X and a < button next to each other.
- Instead I modified it so that the "back" button becomes an X while the social loader is up
ios:stage and android:stage
=> [C-3858] Social sign on loading screen adjustments

dev-tools/audius-compose
Followup to fix the same typo as https://github.com/AudiusProject/audius-protocol/pull/7713. This would've been caught by CI, but Circle was having an incident. We'll make sure CI is green to merge this now that the incident is resolved.
=> Fix the same typo in another spot

packages/discovery-provider/ddl/migrations/0056_tracks_placement_hosts.sql, packages/discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py, packages/discovery-provider/integration_tests/tasks/entity_manager/test_utils.py, packages/discovery-provider/src/api/v1/tracks.py, packages/discovery-provider/src/models/tracks/track.py, packages/discovery-provider/src/tasks/metadata.py
Follow on to: https://github.com/AudiusProject/audius-protocol/pull/7668
Adds `placement_hosts` field to tracks table - a comma separated list of host names (e.g. `https://a1.host.com,https://a2.host.com,https://otherhost.com`)
Uses this field instead of rendezvous in the track stream endpoint.
Entity Manager tests that field gets from track metadata to db.  There are no existing tests for the api track stream endpoint, so that part is untested atm.
=> Discovery placement hosts

packages/mobile/src/screens/root-screen/RootScreen.tsx, packages/mobile/src/screens/sign-on-screen/SignOnStack.tsx
Disables animations for android on the genres page.
Also added logic to set animation none only on android
If I'm understanding the "gray screen" problem correctly this should fix it?
Don't have a way to test 😢, need to have Julian or someone try to see if they can still get it after this
=> [C-3898] Fix faded gray screen android on sign up

packages/common/src/hooks/useImageSize.ts, packages/common/src/models/Collection.ts, packages/common/src/models/ImageSizes.ts, packages/common/src/models/Track.ts, packages/common/src/models/User.ts, packages/common/src/services/audius-backend/AudiusBackend.ts, packages/mobile/src/components/image/CollectionImage.tsx, packages/mobile/src/components/image/TrackImage.tsx, packages/mobile/src/components/image/primitiveToImageSource.ts, packages/mobile/src/hooks/useContentNodeImage.ts, packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadCollectionWorker.ts, packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts
React native imports images as numbers, but we weren't handling that for our override image sources. This led to Android crashing.
ONC-35 for details
=> [ONC-35] Fix crash on android due to react native importing images as numbers

.circleci/src/workflows/ddex-stage.yml, .circleci/src/workflows/ddex-webapp.yml, dev-tools/compose/docker-compose.test.yml, dev-tools/compose/docker-compose.yml, packages/ddex/README.md, packages/ddex/ingester/common/common.go, packages/ddex/ingester/e2e_test/e2e_test.go, packages/ddex/ingester/parser/ern381.go, packages/ddex/ingester/parser/parser.go
DDEX choreography affects how files are indexed. This PR doesn't change the indexer but sets up DDEX to run for one choreography at a time with related infra changes:
- Adds `DDEX_CHOREOGRAPHY` env var and pipes it to each service
- Makes integration tests run separately for the 2 choreography types (release-by-release vs batched)
- Enables support for parsing multiple ERN versions by reading the ERN version from XML
- Documents the env vars needed in prod
Running e2e tests for batched and release-by-release choreographies behave as expected locally. CI should also be green before merging.
=> [PROTO-1686] Setup DDEX choreography infra and related improvements

packages/mobile/src/screens/sign-on-screen/screens/CreateEmailScreen.tsx
Found a small but serious bug where twitter sign up was forcefully redirecting to the feed during the last two steps, realized its because we weren't "starting" the sign up with the social flow.
Only noticeable on a fresh session
ios sim with twitter sign up
=> Fix social sign ups redirecting unintentionally

packages/web/src/components/ai-attribution-modal/DropdownInput.jsx
Fixes issue here ai-attribution-dropdown was filtering out values incorrectly. In this case we will just let all search results be present.
=> [C-3897] Fix ai-attribution dropdown

packages/mobile/src/screens/sign-on-screen/screens/SignInScreen.tsx
Add the error message as helper text to the password field
Error from the field automatically is cleared when the field is changed
=> [C-3926] Add error helper text to new sign in password field

packages/web/src/components/track/DownloadRow.tsx
Fixes bug where `!` was accidentally added while doing an icon migration, causing download buttons to show before purchase, and vice versa.
=> Fix download buttons erroneously displaying

packages/discovery-provider/integration_tests/tasks/entity_manager/test_utils.py, packages/discovery-provider/plugins/pedalboard/packages/storage/src/index.ts, packages/discovery-provider/src/api/v1/models/tracks.py, packages/discovery-provider/src/schemas/track_schema.json, packages/discovery-provider/src/tasks/metadata.py
Add `playlists_containing_track` field to all track api returns
local discovery provider returns the field with api results
=> [PAY-2527] Return `playlists_containing_track` from track apis

packages/mobile/src/services/analytics.ts
Make it so that we can filter all amplitude events by `isNativeMobile`
atm cant test locally due to "missing amplitude key" error (need to dig into, I thought we fixed that?), but not worried about it not working out in the wild
=> Add an isNativeMobile prop to amplitude

packages/web/src/pages/pay-and-earn-page/components/WithdrawalsTable.module.css
Slight increase to line height to make sure that the text doesn't clip vertically
I can't test bc i don't have withdrawals, but this fix should work based on testing with Dylan
=> [C-3708] Fix wallet text clipping issue in withdrawals table

packages/common/src/services/audius-backend/AudiusBackend.ts
The parameters changed to an object arg, but since `audiusLibs` is untyped, we didn't catch it.
Created ONC-41 to track better types for that file
=> Fix reset password

packages/web/src/components/collection/desktop/CollectionActionButtons.tsx, packages/web/src/components/collection/desktop/CollectionHeader.tsx, packages/web/src/components/collection/mobile/CollectionHeader.jsx, packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx, packages/web/src/pages/collection-page/components/mobile/CollectionPage.tsx, packages/web/src/pages/track-page/components/mobile/ActionButtonRow.tsx
Handled for mobile. Forgot about web (and mobile web).
Instead of disabling the button, web has logic to remove the play button if playlist empty, so im also removing the button if all playlist tracks deleted.
local web v stage
=> Disable play button if all collection tracks deleted on web

packages/common/src/hooks/useHarmonyField.ts, packages/web/.gitignore, packages/web/scripts/workers-site/index.js, packages/web/scripts/writeSHA.sh, packages/web/src/components/payment-method/PaymentMethod.tsx, packages/web/src/ssr/worker.js, packages/web/src/store/reload/sagas.ts, packages/web/src/store/sagas.ts
ONC-40
Previous iteration used the env var, but on the rare chance that doesn't change, decided for local var instead.
=> [ONC-40] Reload the page if the git sha doesn't match the latest

packages/web/src/ssr/worker.js
In #7771 I made some changes from CR that changed the url to `.gitsha` from `.version` but I missed a spot
=> Hotfix: Serve static .gitsha in cloudflare worker

packages/libs/package.json
After publishing a new version of @audius/sdk it throws an error when consumed:
```
✘ [ERROR] No matching export in "node_modules/@audius/spl/dist/esm/index.js" for import "ClaimableTokensProgram"
node_modules/@audius/sdk/dist/index-b7c375d7.js:27:9:
27 │ import { ClaimableTokensProgram, RewardManagerProgram } from '@audius/spl';
╵          ~~~~~~~~~~~~~~~~~~~~~~
✘ [ERROR] No matching export in "node_modules/@audius/spl/dist/esm/index.js" for import "RewardManagerProgram"
node_modules/@audius/sdk/dist/index-b7c375d7.js:27:33:
27 │ import { ClaimableTokensProgram, RewardManagerProgram } from '@audius/spl';
```
This is because changes in `@audius/spl` had not been published and `@audius/sdk` had wildcard dependencies on `@audius/spl` and `@audius/fixed-decimal`
Resolved by setting these …
=> [INF-663] Fix external package versioning in monorepo

packages/identity-service/src/routes/tiktok.js
TikTok auth was broken because our redirect was missing `user.info.profile` scope. Adding the scope fixes it
Confirmed tiktok auth on staging
=> Add user.info.profile scope to tiktok redirect

packages/web/src/components/add-to-collection/desktop/AddToCollectionModal.module.css, packages/web/src/components/add-to-collection/desktop/AddToCollectionModal.tsx
Fixes issue where add-to-collection list item was missing the "plus" icon. With the new icon layout, the existing styling selectors were incorrect.
=> [C-3937] Fix new-playlist icon

mediorum/server/serve_blob.go
Bumps the logging of play counts in mediorum from 5 seconds to 1 minute because the endpoint it uses will sometimes take more than 5 seconds. This runs in a goroutine, so it doesn't block streaming.
=> Bump mediorum play logging timeout to 60s

packages/common/src/store/wallet/utils.ts, packages/discovery-provider/ddl/functions/handle_user_balance_changes.sql, packages/discovery-provider/integration_tests/notifications/test_tier_change.py, packages/discovery-provider/src/queries/notifications.py, packages/embed/src/components/collectibles/CollectiblesHeader.jsx, packages/mobile/src/screens/audio-screen/AudioScreen.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TierChangeNotification.tsx, packages/web/src/components/notification/Notification/TierChangeNotification.tsx
Switch limits to 1k and 10K.
Noting that notifications can behave slightly weirdly if you are between 1K and 10K at the moment and your balance goes down, but stays over 1K.
Did a global search for 10000 to try to figure this out, but maybe have missed somewhere
=> Move to 1k gold 10k platinum

packages/web/src/components/tipping/tip-audio/TipAudio.module.css, packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx, packages/web/src/public-site/pages/download-page/DownloadPage.module.css
(In screenshot, am hovering over Mac download button. ^)
=> [Web] Fix Send Tip modal header icon and Download Page cloud icons [C-3952]

packages/mobile/src/screens/root-screen/useSyncCodePush.ts
Implement item #2 from [OTA improvements plan](https://www.notion.so/audiusproject/Improving-Latest-Mobile-App-Release-Adoption-w-focus-on-OTA-8abb2e0e67dc4a538724d11b214ca632?pvs=4)
- Install pending Codepush (OTA) updates upon foregrounding the app after 1 hr has passed since last foreground UNLESS user is playing music
On Android device in production mode. Will make sure to test thoroughly in "real" settings too once merged (with staging and RC apps).
Test cases:
- Background for >1 hr -> re open app -> app should restart and new update should be applied
- Play music (like a >1 hr playlist) -> background for >1hr -> re open app -> app should not restart -> stop music -> background for >1 hr -> re open app -> app should restart and new update should be applied
- Force close app …
=> [Mobile] ⚠️ Install pending CodePush update upon foregrounding after 1hr [C-3791]

packages/mobile/src/services/track-download.ts
Add random number to download temp dir to avoid combined lossless and mp3 files in same folder in android
=> [PAY-2518] Fix android bug for combined downloads file in same folder 

packages/web/src/components/stem-files-modal/StemFilesModal.tsx, packages/web/src/pages/upload-page/fields/StemsAndDownloadsMenuFields.tsx, packages/web/src/pages/upload-page/fields/SwitchRowField.tsx
Text descriptions style was wrong, probably due to switching from old Text component to Harmony one.
now 
before
=> [PAY-2546] Fix stems and downloads text variant

packages/web/src/common/store/account/sagas.js
We never got to this fix last ONC rotation.
If we do not log a user out cleanly, this check will ensure that the wallet in local storage matches the cached user in local storage.
This whole section of our codebase deserves a project and a rewrite.
```
```
Logged in as a user and then after logging in, updated hh entropy key to be another user. Refreshed page and watched account only load in once the discovery node req completed, versus loading from local storage.
=> [ONC-39] Check that signed in user matches wallet

packages/discovery-provider/ddl/migrations/0060_aggregate_monthly_plays_country.sql, packages/discovery-provider/src/models/social/aggregate_monthly_plays.py, packages/discovery-provider/src/queries/get_user_listen_counts_monthly.py, packages/discovery-provider/src/tasks/index_aggregate_monthly_plays.py
* Adds country column (`default ''`) to `aggregate_monthly_plays`.
* Updates primary key to be `(play_item_id, timestamp, country)`
* Updates `index_aggregate_monthly_plays` to include the `country` column.
* Updates existing endpoint to ignore `country` by doing a `sum(count)` with a `group by play_item_id, timestamp`
=> Add country column to aggregate_monthly_plays

packages/harmony/README.md, packages/harmony/package.json, packages/harmony/rollup.config.mjs
Keeping peerDeps up to date for this many packages is going to be very painful. It also adds extra friction to the harmony install process.
I was attempting to use harmony in a brand new react 18 app and peerDeps were failing to resolve because of an outdated `react-use` version. This problem is exacerbated by the fact the we use `legacy-peer-deps` in the monorepo but external users may not want to do that
Material UI only has 2 peer deps, `react` and `react-use` which I think is more reasonable. But in our case I think it makes sense to remove all peerDeps and then use overrides in our client if we want/need to reduce bundle size due to multiple versions of packages being installed
I will publish a new version of harmony once this is merged!
Confirmed things build
=> [INF-668] Remove peerDeps from @audius/harmony

packages/discovery-provider/plugins/pedalboard/apps/relay/src/error.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/antiAbuse.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/errorHandler.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/logging.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimiter.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/validator.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/redis.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/utils.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/web3.ts
adds more verbose logging and request id tracking to relay
adds better try / catches around the redis helpers as well as txRelay where the app could be throwing
adds better error to string conversion so we can see what actual errors are being logged
=> PROTO-1720: relay logging

packages/web/src/services/sentry.ts
By default, Sentry will use the stack trace when available to group issues together. This seems like it might work better than what we have today, which is a `toString()` on the error object.
https://docs.sentry.io/product/data-management-settings/event-grouping/#grouping-by-stack-trace
The goal is hopefully sentry is smart enough to group the myriad of similar issues with different messages but same stack trace/cause into the same issues, reducing issue noise on sentry.
Will test on staging
=> Remove custom Sentry fingerprint

packages/web/src/services/audius-backend/Jupiter.ts
This one was done incorrectly
```
```
& buy $AUDIO
=> Fix jupiter instruction

packages/discovery-provider/ddl/migrations/0061_aggregate_monthly_plays_country_backfill.sql
Backfills aggregate_monthly_plays `country` from plays table where possible.
Tested in a transaction on staging node, confirmed numbers looked correct, did `rollback`
=> Add aggregate_monthly_plays_country_backfill

packages/discovery-provider/src/app.py, packages/discovery-provider/src/tasks/index_payment_router.py, packages/discovery-provider/src/tasks/index_user_bank.py
* Makes the index_user_bank and index_payment_router celery tasks re-enqueue themselves when finished instead of enqueuing every second regardless of if the previous job hadn't run yet
* Moves index_user_bank and index_payment_router to the dedicated ACDC queue instead of being in a shared queue with all tasks
The aim of this is to reduce the buildup of tasks in the shared queue, which was too much to keep up with when enqueuing these tasks every second.
Indexing works locally and with test-audius-cmd on CI. User bank and payment router need to also be more explicitly tested.
=> [ONC-52] Self-re-enqueue user_bank and payment_router indexing tasks

packages/ddex/ingester/artistutils/artistutils.go, packages/ddex/ingester/common/sdk_types.go, packages/ddex/ingester/e2e_test/e2e_test.go, packages/ddex/ingester/parser/ern38x.go, packages/ddex/ingester/parser/parser.go
- `ResourceContributor` + SeqNos
- `IndirectResourceContributor` + SeqNos
- All `DisplayArtist`s + SeqNos
- Find and use 1st `DisplayArtist` that is oauthed for sdk upload
- `RightsController`
- CLine/Year, CLine/CLineText
- CLine/Year, CLine/CLineText
- `ParentalWarningType`
Left out  `IsInstrumental` for now. Doesn't seem very important.
Will follow up with the sdk / discovery changes to persist these new fields.
e2e test
=> Parse more ddex fields

packages/discovery-provider/scripts/start.sh, packages/discovery-provider/src/app.py, packages/discovery-provider/src/tasks/index_payment_router.py, packages/discovery-provider/src/tasks/index_user_bank.py
Moves user bank and payment router indexing off of the acdc worker and into their own (new) worker. Let me know if this seems like too many workers, but having them share with the acdc worker is causing staging to fall behind.
This is running on stage DN2 and able to index ACDC quickly enough now.
=> Move some tasks to new standalone index_sol worker

packages/discovery-provider/src/api/v1/tracks.py, packages/discovery-provider/src/gated_content/content_access_checker.py, packages/discovery-provider/src/queries/get_tracks.py, packages/discovery-provider/src/tasks/index_payment_router.py, packages/discovery-provider/src/tasks/index_user_bank.py
Prior to this PR,`v1/full/tracks/<id>`, `v1/tracks?id=<id1>&id=<id2>...`, `v1/full/tracks?id=<id1>&id=<id2>...` all filtered out unlisted tracks unless the user was logged in. The `v1/full/tracks/<id>` endpoint specifically had a check for two parameters that detail knowledge of the track's title and owner _even if the owner was the one requesting_, which was breaking my fetch for a freshly uploaded track at the end of the upload flow. 
With this PR we're deciding that filtering unlisted tracks from the API when requesting by ID alone is unnecessary, as we no longer use monotonically increasing IDs anyway so the ID is something that's obscure enough to know.
Did not adjust at the query level because getting tracks by user should still not reveal unlisted tracks, lest we show unlisted …
=> Allow querying for unlisted tracks by ID

packages/libs/package.json, packages/web/package.json
* Adds `@audius/fixed-decimal` as a dependency in `packages/web`
* Update version of `@audius/fixed-decimal` in `packages/libs`
In a clean working dir, `npm i` followed by `npm run web:stage` works without building `@audius/fixed-decimal` manually.
=> Add fixed-decimal to web deps and update version in libs

packages/web/src/components/static-image/StaticImage.tsx, packages/web/src/components/track/GiantArtwork.tsx, packages/web/src/components/track/GiantTrackTile.tsx, packages/web/src/pages/track-page/components/mobile/TrackHeader.module.css, packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx, packages/web/src/ssr/track/+route.tsx
Added very minimal StaticImage component to handle rendering an img tag based on a provided src to kick off the img fetch sooner in the start up, and then split the image logic on web and mobile-web track pages to conditionally render the static image based on if SSR is enabled
Drops LCP time drop from 26 - 29 sec to 6 - 8 sec which is pretty neat
Lots of manual testing on kj.audius.co
=> [C-3958] Add StaticImage component and update track artwork rendering on web and mobile-web track pages for ssr

packages/libs/src/services/solana/transactionHandler.ts
We might be missing `logger.warn` logs from identity and we need these to confirm the behavior of `_locallyConfirmTransaction` to see if we are actually retrying `sendRawTransaction` if the initial send on line 285 fails.
=> Change loglevel to error in TransactionHandler _locallyConfirmTransaction

packages/web/src/services/sentry.ts
Sentry Errors are ignored from probers user agent
=> Ignore sentry errors for probers

packages/mobile/src/components/lineup-tile/LineupTileMetadata.tsx, packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Fixes issue where pressing play causes layout shift of track title due to icon being too large.
Fixes issue where pressing play on track screen when another track is already playing triggered a pause when`isPreview` and `isPreviewing` are false.
=> [C-4040, C-4032] Fix play cls, Fix pause on track screen

dev-tools/compose/docker-compose.yml
Adds back missing web and publisher containers for CI to be able to build DDEX.
I ran `audius-compose build ddex-web` and `audius-compose build ddex-publisher` locally.
=> Add missing containers for DDEX Docker build

packages/common/src/store/pages/search-results/selectors.ts
Collection search results are ranked by playlist ID instead of maintaining the relevancy order. 
Autocomplete results differ from search results page because of this.
Tested locally against prod
=> Fix collection search ranking in common

packages/web/src/pages/profile-page/ProfilePage.tsx, packages/web/src/services/sentry.ts, packages/web/src/ssr/profile/route.tsx
* Update +route to route for profile page to not render profile page on the server until more work is done there
* Add an undefined check on navigator in sentry.ts to not break server-side rendering
Tested locally
=> Add undefined check to sentry navigator and remove profile page route

packages/common/src/models/OpenSea.ts, packages/common/src/services/opensea-client/ethCollectibleHelpers.ts, packages/common/src/services/solana-client/solCollectibleHelpers.ts, packages/libs/src/sdk/api/tracks/types.ts
Eth side:
- opensea v2 contract address lives in different field
Sol side:
- nft properties file is sometimes `{}`, causing `file.type` to be undefined, causing any chained function calls from it to break
General:
- make external links nullable
- remove unused fields
Note:
nfts very slow to load. should look more into that
local vs prod
upload flow collectibles didn't load nft collections, because of issues on both eth and sol sides.
collectibles page sol nfts also would not load.
with these fixes, they load properly now. collectibles page
=> [PAY-2577] Fix nft issues

dev-tools/setup.sh
[Docker released a patch to fix a vulnerability](https://github.com/moby/moby/security/advisories/GHSA-mq39-4gv4-mvpx), but this creates a regression in the build process by not allowing connections to local services. This broke the build for eth-contracts and in turn broke the test-audius-cmd integration workflow.
This will pin docker to an earlier version not impacted by the vulnerability or the regression.
CI
=> Pin docker to older version to fix regression

packages/web/src/index.tsx, packages/web/src/ssr/+onRenderClient.tsx, packages/web/src/ssr/+onRenderHtml.tsx, packages/web/src/ssr/RootWithProviders.tsx, packages/web/src/ssr/index/+onRenderClient.tsx
Added a RootWithProviders component to allow for easy dynamic importing
This allows for a large reduction in js parsing when HYDRATE_CLIENT is set to false and a large drop in the Total Blocking Time metric on the Lighthouse test
Manually tested on kj.audius.co
=> [C-4024] Update SSR to dynamically import Root based on HYDRATE_CLIENT

packages/discovery-provider/src/api/v1/helpers.py
Re-adds `download` field in track api response for clients on old versions. This will be removed later once we force upgrade on mobile.
Related to
https://github.com/AudiusProject/audius-protocol/pull/7784
https://github.com/AudiusProject/audius-protocol/pull/7896
Passes integration tests.
Ran web client against local stack, confirmed all-time trending works and `download` field is present in track response.
=> Re-add download to track api response for old clients

packages/discovery-provider/ddl/migrations/0063_ddex_jsonb_columns.sql, packages/discovery-provider/src/models/playlists/playlist.py, packages/discovery-provider/src/models/tracks/track.py, packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py, packages/discovery-provider/src/tasks/entity_manager/entities/track.py
Indexing stalled because sqlalchemy could not out of the box handle inserting an array of dicts into a jsonb[] type postgresql column. However these columns should actually just be jsonb cols, which can handle arrays of jsonb blobs and also keeps all the postgres jsonb functionality.
Change these cols from jsonb[] -> jsonb. Add validation to the tracks entity manager to match the other jsonb columns' validation. Playlists do not seem to have this. 
It appears to be a larger problem that the entity manager in general doesn't validate types before inserting into the db, and if the db insert errors, indexing stalls.
Verified this unblocked stage DN3 which was stuck trying to index a DDEX track
=> Fix ddex indexing

packages/web/src/components/search/SearchBar.jsx
Fixes PROTO-1721
Fixes PROTO-1725
This fixes a race condition in the autocomplete search. When typing quickly, the shouldComponentUpdate forces the dropdown to stay open even if the users hits `Enter`. The component is rendering new results after the search is already submitted so the autocomplete pops up in a broken state where it's open half-rendered but not in focus so unable to be blurred/dismissed.
Not entirely sure why this was necessary in the first place, considering autocomplete should probably only open onFocus. 
Search seems pretty smooth now even when typing fast.
https://github.com/AudiusProject/audius-protocol/assets/6413636/b35b3a64-ec2c-4c50-8da4-17a151b158eb
=> Fix search autocomplete race condition

packages/web/src/app/web-player/WebPlayer.jsx, packages/web/src/components/client-only/ClientOnly.tsx
Combination of 2 things were causing empty lineups on feed + trending pages
- Modals were being lazy-loaded, but not wrapped in a suspense causing the "pause" to be bubbled up to the root level Suspense (in App.tsx).
- ClientOnly component was using a useEffect + useState to determine whether it was client- or server-side, triggering a page reload.
This PR addresses both of those:
- Wrap `Modals` in its own `Suspense`.
- Change `ClientOnly` to use `SsrContext` instead of `useEffect` which avoids the re-render
=> ⚠️ [C-4064] Fix empty feed/trending pages

packages/mobile/src/screens/search-screen/SearchScreen.tsx
On mobile, performing tag search, then going back to the previous page shows autocomplete results. This change prevents those autocomplete results so recent searches can show instead, in line with web behavior. 
https://github.com/AudiusProject/audius-protocol/assets/6413636/7ebb5288-5c4e-4abb-8837-2aba0e57995d
Tested locally against prod
=> [PROTO-1693] Fix tag search triggering autocomplete

packages/web/src/common/store/pages/signon/actions.ts, packages/web/src/common/store/pages/signon/reducer.js, packages/web/src/common/store/pages/signon/sagas.ts, packages/web/src/common/store/pages/signon/selectors.ts, packages/web/src/common/store/pages/signon/types.ts, packages/web/src/components/toast/ToastContext.module.css, packages/web/src/components/toast/ToastContext.tsx, packages/web/src/components/toast/mobile/Toast.module.css
Fixes the "you need an account" toast trigger logic.
Also fixes a bug where the toast takes up 100% width and as a result covers stuff like the modal X button
- Remove the one-off and now unused toast logic in sign on and replace with the standard toast logic
- Modify the toast css to use left:50% + translate(-50%) to position rather than width: 100% 
- Position and size should be unchanged, its just now absolute
web:stage on desktop and mobile sizes (chrome)
=> [C-3961] Fix sign up modal toast triggers

packages/web/src/components/cover-photo/CoverPhoto.module.css, packages/web/src/components/cover-photo/CoverPhoto.tsx, packages/web/src/components/nav-banner/NavBanner.module.css, packages/web/src/components/nav-banner/NavBanner.tsx, packages/web/src/components/profile-picture/ProfilePicture.jsx, packages/web/src/components/profile-picture/ProfilePicture.module.css, packages/web/src/components/stat-banner/StatBanner.tsx, packages/web/src/components/static-image/StaticImage.tsx, packages/web/src/pages/profile-page/components/desktop/ProfileLeftNav.tsx, packages/web/src/pages/profile-page/components/desktop/ProfilePage.module.css, packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx, packages/web/src/pages/profile-page/components/mobile/GrowingCoverPhoto.tsx, packages/web/src/pages/profile-page/components/mobile/ProfileHeader.module.css, packages/web/src/pages/profile-page/components/mobile/ProfileHeader.tsx, packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx, packages/web/src/ssr/profile/+route.tsx
Add back the route for profile pages
Render profile pages on web with basic user info (user name, handle, profile pic, etc.)
Render profile page header on web mobile with cover photo as well
Lots of manual testing, but there is a timeout issue happening on main that I need to look into to get a full test and lighthouse score for these changes
=> [C-4026, C-4059] Update profile page to render basic info and pictures on the server side

package-lock.json, packages/libs/package.json
The client release branch failed to cut because of some strange npm behavior. We had `"@audius/fixed-decimal": ^0.0.21` in the sdk package.json, which I presumed would pull the local version as long as the semver range was satisfied. However when CI bumped the version in `@audius/fixed-decimal` to 0.0.22, sdk attempted to pull this from the npm registry instead of from local.
Temporary fix is to go back to wildcard versions. We will need to change this if we want to publish sdk! Coming changes in the Better Releases & Changelogs project will address this with a more permanent process change + fix
Confirmed bumping versions and doing npm i works locally
=> Change internal sdk deps back to wildcard version

packages/web/src/components/collectibles/components/CollectiblesPage.tsx
Fixes margin around the confirm button in the edit collectibles modal
=> [C-4066] Fix edit-collectibles modal spacing

packages/web/src/components/track/GiantTrackTile.tsx, packages/web/src/components/track/desktop/ConnectedTrackTile.tsx, packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Fixes issue where track options were inconsistent on track tiles and track pages
=> [C-4019] Fix web track menu options

packages/common/src/services/opensea-client/OpenSeaClient.ts
Upgrade to v2 opensea api left off the next param: https://github.com/AudiusProject/audius-protocol/pull/7449
This worked fine for profiles with a single page of nfts, but profiles with many nfts had infinite loop
Gramatik's profile stops making requests and the collectibles tab shows up
=>  [ONC-58] Add next param to opensea requests

packages/web/src/ssr/profile/+onBeforeRender.tsx, packages/web/src/ssr/sdk.ts, packages/web/src/ssr/track/+onBeforeRender.tsx, packages/web/src/ssr/util.ts
Small fix to create separate instances in the files where they are needed
This fix also got rid of the timeout issue which makes sense if the sdk instance was not being set up properly
Manually tested and tested on kj.audius.co
=> [C-4065, C-4067] Update sdk instances in ssr files to avoid http provider errors

packages/ddex/ingester/e2e_test/e2e_test.go
Cleans up DDEX e2e tests and converts them to more readable table tests with less duplicated boilerplate.
Both batched and release-by-release pass locally:
* `audius-compose test down && audius-compose test run ddex-e2e-release-by-release`
* `audius-compose test down && audius-compose test run ddex-e2e-batched`
=> [PROTO-1717] Clean up DDEX e2e with table tests

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/store/pages/search-results/selectors.ts, packages/web/src/common/store/cache/collections/commonSagas.ts
Historically the intended behavior when deleting an album was to delete the tracks. However, now that we have editable albums that allow users to add existing tracks, deleting the album can unintentionally delete tracks.
This PR makes albums behave similarly to playlists in the deleting the collection does not delete the tracks.
Was able to remove `deleteAlbum` codepath in AudiusBackend, but needed to keep `confirmDeleteAlbum` because it's slightly different from `confirmDeletePlaylist`
Tested that deleting album does not delete tracks
=> [ONC-60] Don't delete tracks when deleting album

packages/harmony/src/components/button/FollowButton/FollowButton.tsx, packages/harmony/src/components/button/IconButton/IconButton.tsx, packages/web/src/components/image-selection/ImageSelectionButton.jsx, packages/web/src/components/nav/desktop/NavMenuButton.module.css, packages/web/src/components/profile-picture/ProfilePicture.jsx, packages/web/src/components/profile-picture/ProfilePicture.module.css, packages/web/src/pages/profile-page/components/desktop/ProfileBio.tsx
Addresses three remaining issues:
1. Fixes edit profile tertiary button size and spacing
2. Fixes icon button hover and applies that to nav buttons
3. Fixes issue with show-more show-less button appearing on small bios
4. Fix issue with missing hover style on follow button
=> [C-4075] Harmony qa round 2

packages/discovery-provider/integration_tests/gated_content/test_access.py, packages/discovery-provider/integration_tests/utils.py, packages/discovery-provider/src/gated_content/helpers.py
* Access checker now grants access if the user purchased an album that previously contained the track, and the purchase occurred before the track was removed from the album
* Cleaned up `test_batch_access` so that the test cases match `test_access` 1-to-1.
Added integration test cases
=> [PAY-2566] Check playlists_previously_containing_track in access checker

packages/common/src/utils/genres.ts, packages/ddex/ingester/common/sdk_types.go, packages/discovery-provider/src/utils/hardcoded_data.py, packages/libs/src/sdk/types/Genre.ts
=> [C-4074] Add Dancehall genre

packages/harmony/src/hooks/useHotKeys.ts, packages/web/src/hooks/useDevModeHotkey.ts
Fixes issue where hotkeys do not respect meta-keys. For example if I press `command-f`, the feature flag modal appears. This fix checks that if a hot-key does not require a meta-key, we dont trigger it if a meta-key is present.
=> [C-4015] Fix hotkeys with modifiers

packages/mobile/src/components/core/ProfilePicture.tsx, packages/mobile/src/components/image/UserImage.tsx, packages/mobile/src/screens/search-screen/SearchResults/SearchItem.tsx
Fixes issue where profile search results images weren't rendering. This was due to ProfilePicture looking into the cache for the user, and not finding it because search user is not a part of the cache. The fix is to allow "user" object as another way to configure the profilepicture.
=> [C-4076] Fix search results profile images

packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
This PR broke pause: https://github.com/AudiusProject/audius-protocol/pull/7888
```
isPreviewing === isPreview
```
is required because `isPreviewing` will only ever be true for previews. We needed to add a check for `currentQueueItem.uid === uid` to allow other tracks to play immediately without pausing
Pause and play works properly locally
=> [ONC-62] Fix pause on track screen

packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Use playingId instead of uid to determine if the track is playing. This is the same way the state of the button is determined
Tested:
* Playing from feed and pausing from track screen
* Playing from track screen and pausing from track screen
* Playing one track and pressing play on another track screen
=> Fix pause button pt 2

packages/discovery-provider/src/api/v1/challenges.py
fixes json error
```
{
"message": "Object of type Decimal is not JSON serializable"
}
```
tested against prod sandbox
```
{
"data": {
"challenge_id": "b",
"type": "aggregate",
"amount": "1",
"active": true,
"step_count": 2147483647,
"starting_block": 220157041,
"weekly_pool": "25000",
"weekly_pool_remaining": "52.0",
"cooldown_days": 7
}
}
```
=> Fix challenge info decimal

.circleci/src/workflows/identity.yml, packages/libs/src/services/solana/transactionHandler.ts
If the initial send for a relayed transaction fails, currently we will just return an error response. It would be better if we would continue to retry even if the first send fails.
Tested by logging value of `txid` on prod and stage identity to confirm the value was correct for both v0 and legacy transactions.
=> [PAY-2576] Solana relay retries if initial send fails

packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
We had this feature flag `IOS_GATED_CONTENT_ENABLED_2` that didn't seem used
=> Disable buy button on ios

packages/web/src/components/search/SearchBar.jsx
Reverts https://github.com/AudiusProject/audius-protocol/pull/7913
Also closes https://linear.app/audius/issue/C-4089/[qa]-search-results-modal-stuck-on-screen
Add `focused` state to keep track of whether or not the search bar is focused. Only open the auto suggestions when the search bar is focused
Confirmed suggestions appear properly and don't get stuck on screen with fast searches
=> [ONC-65] Fix search auto suggest

packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.module.css
Noticed this small UI bug.
Before:
After:
=> Make secondary buy $AUDIO button full-width

packages/common/src/models/AudioRewards.ts, packages/common/src/services/remote-config/feature-flags.ts, packages/common/src/store/challenges/selectors/optimistic-challenges.ts, packages/web/src/common/store/pages/audio-rewards/store.test.ts, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/CooldownRewardsModalContent.tsx
Adding a generic cooldown rewards modal based off the existing audio match one. This is a first pass hidden behind a feature flag. Previously, a separate cooldown modal is shown based on the specific challenge. Now, it relies on the cooldown value which need to be added to the user challenges response.
Discovery changes are WIP on https://github.com/AudiusProject/audius-protocol/tree/is-more-cooldown. 
Confirmed rewards are working the same when feature flag disabled.
When feature flag is enabled and pointed to a sandbox, it will show cooldowns for any rewards.
=> [C-4079] Add rewards cooldown to web

packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj, packages/mobile/ios/PrivacyInfo.xcprivacy
* Add `PrivacyInfo.xcprivacy` following steps outlined [here](https://jochen-holzer.medium.com/embrace-the-evolution-preparing-your-ios-app-for-the-required-reason-api-38f2d12bbce5) and [here](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)
* For `NSPrivacyAccessedAPICategoryFileTimestamp` added the `C617.1` reason which reads as:
> Declare this reason to access the timestamps, size, or other metadata of files inside the app container, app group container, or the app’s CloudKit container.
* For `NSPrivacyAccessedAPICategoryDiskSpace` added the `E174.1` reason which reads as:
> Declare this reason to check whether there is sufficient disk space to write files, or to check whether the disk space is low so that the app …
=> [C-3996] Add Privacy manifest with privacy api reasons

packages/libs/src/sdk/middleware/addRequestSignatureMiddleware.ts
This fixes an issue where going directly to https://audius.co/library would not load your library.
Interesting bug with the auth middleware added to sdk in https://github.com/AudiusProject/audius-protocol/pull/7724
Multiple requests were running in parallel and `message` got set before an `await `call, while `signature` got set after. This caused some requests to have mismatched `message` and `signature` resulting in a 403
Confirmed that library, history, and other requests that require auth work properly.
=> [C-4087] Fix library not loading

packages/web/src/components/collectibles/components/CollectibleDetails.tsx, packages/web/src/components/collectibles/components/CollectibleDetailsModal.tsx
Sometimes an audio url is returned for what we think is a video. In this case, the audio nft should display the nft image (if it's there) as the thumbnail. This PR does that.
local web dapp with nfts on eth and sol prod
=> [PAY-2651] Fix nft video thumbnail

packages/discovery-provider/requirements.txt, packages/discovery-provider/src/api_helpers.py
Hexbytes upgraded from 0.3.1 to 1.2.0 in the image built with commit ffc165c7656d5ea3f90dfc69d199d9d231b151cc. Stream signatures used to start with 0x which content nodes expect, but the new version doesn't have this prrefix.
Fixed streaming on stage and confirmed delisting indexing works.
=> [ONC-68] Fix stream hex signature and delisting by downgrading hexbytes

packages/discovery-provider/scripts/start.sh
Discovery nodes are getting stuck, losing connection with redis. Started over the weekend without any code release or dependency changes. 
```
missed heartbeat from celery@index_nethermind
missed heartbeat from celery@db062c57dbd0	
missed heartbeat from celery@index_sol	
```
I noticed the nodes that missed heartbeats the most had higher CPUs so they have more concurrency in the default worker and the default worker missed more heartbeats than the others. I'm guessing lowering may be a mitigation for now. Nodes at min requirement will not be affected.
=> Lower default celery worker concurrency

packages/discovery-provider/ddl/functions/handle_track.sql, packages/discovery-provider/integration_tests/models/test_aggregate_counters.py, packages/discovery-provider/integration_tests/notifications/test_track.py, packages/discovery-provider/integration_tests/utils.py
Due to a bug in how track counts were being reported,  we can opt to update aggregate counts for user tracks in the handle_track psql trigger to have more timely and accurate track counts.
Unit tests in CI with some additions.
=> [ONC-67] Update aggregates counts with more straightforward logic

packages/ddex/publisher/Dockerfile, packages/ddex/webapp/Dockerfile
We've seen [this issue](https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/54178/workflows/d3cc1bb7-47e8-4415-90f8-eae5ec76bd99/jobs/749621) in the past where npm i randomly fails due to `ECONNRESET`. For some reason, this flag helps make the build more reliable. We're already doing this for other Dockerfiles, see #7397 
CI
=> Add '--maxsockets 1' flag to make ddex build more reliable

packages/mobile/src/screens/profile-screen/CollectiblesCard.tsx
A version has been cherry picked to 1.5.73 -- we will want this one on 1.5.74 as well once it goes in
1. Never had support for svg+xml on mobile since it does not work when put into an `<Image>` as is
2. Support more than mp4 for video types. We can't trust that it will have an extension
```
npm run mobile:prod
```
* sceretpanda007
* rayjacobson
* forrest
* eeeeqanft
=> Fix mobile collectible svg+xml and video display

packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Noticed this while dev-ing other stuff, quick fix
Before:
After:
=> Fix mobile AI-generated track header

packages/mobile/android/app/build.gradle, packages/mobile/ios/AudiusReactNative/Info.plist
Bumps mobile version for full app release. Needed due to changes to pods for collectibles
=> Bump mobile version to 1.1.93 for release

packages/identity-service/src/solana-client.js, packages/libs/src/services/solana/transactionHandler.ts
Slow down retries for solana transactions and revert priority listens as it's not necessary at the moment.
Running in prod identity confirmed tansactions.
=> Slow down solana tx retries

packages/mobile/src/components/fields/HarmonyTextField.tsx, packages/mobile/src/components/fields/PasswordField.tsx
Fixes issue where we used onChangeText instead of onChange, meaning field.onChange was silently passed to password-fields onChange, resulting in a bunch of warnings
=> [C-4083] Fix native password perf

packages/harmony/src/components/text/Text/Text.tsx, packages/mobile/src/components/details-tile/DetailsTileAiAttribution.tsx, packages/mobile/src/harmony-native/components/Text/Text.tsx
Fixes issue where ai-attribution details title looked misaligned. Migrated most things to harmony and added a paddingTop: 2px to make it nicer visually.
Also fixes harmony text issue where `textTransform` prop was always setting textTransform to undefined, which negated the textTransform: uppercase applied to the label variant.
=> [C-4329] Fix ai-attribution-details styles

packages/discovery-provider/src/app.py, packages/discovery-provider/src/tasks/cache_current_nodes.py, packages/discovery-provider/src/tasks/index_rewards_manager.py, packages/discovery-provider/src/tasks/user_listening_history/index_user_listening_history.py
Avoids a 20-30min downtime on fresh startup while we wait for content nodes cache to populate on the discovery node. This is because no celery tasks on the main queue are processed during the first 20-30 minutes for reasons not yet clear.
Successfully tested on stage dn5
=> Cache content nodes immediately at startup

packages/mobile/src/components/details-tile/DetailsTile.tsx, packages/mobile/src/components/image/CollectionImage.tsx, packages/mobile/src/components/image/TrackImage.tsx, packages/mobile/src/hooks/useContentNodeImage.ts
Fixes issue where some playlists images looked missing due to a weird issue where OVERRIDE image is the fallback image, but our hook doesn't recognize it should render the fallback image:
Also cleans up Collection and Track image render
=> [C-4038] Fix missing playlist image

packages/discovery-provider/ddl/pg_migrate.sh, packages/libs/src/services/solana/SolanaWeb3Manager.ts, packages/libs/src/services/solana/transactionHandler.ts
https://github.com/AudiusProject/audius-protocol/pull/8024 instantiates libs w a random RPC endpoint on startup, but doesn't rotate after that. This change allows RPCs to fallback on error.
Tested on stage, confirmed errors cause RPCs to rotate.
```
transactionHandler: finished sending txid 5cEkdyHhpCwYYG2MBH2cUhBF8gsDJ7ps1nuhNwWsyobg8BU2xsKuLfgpb4JpQwCAsP88oac5tKmHcmVUSk71EAyH with 17 retries to https://audius.rpcpool.com/a9a724f9717b3395117350265c4e in 33218 ms
transactionHandler: Timed out in await, HqKrbfXGJ2Y5Bk5u18XziMHJmsyVsZVz9zM92Pj8GMWs51XMQtpTvs3EAmXYF7fbujdvoyojrHdHcJHFdt7QuT2
transactionHandler: error in awaitTransactionSignature: {}, …
```
=> RPC fallback on error

packages/web/src/components/link/ExternalLink.tsx, packages/web/src/components/link/ExternalTextLink.tsx, packages/web/src/components/link/index.ts, packages/web/src/components/track/DynamicTrackArtwork.module.css, packages/web/src/components/track/DynamicTrackArtwork.tsx, packages/web/src/components/usdc-purchase-details-modal/components/DetailSection.tsx, packages/web/src/components/usdc-purchase-details-modal/components/PurchaseModalContent.tsx, packages/web/src/components/usdc-purchase-details-modal/components/SaleModalContent.tsx, packages/web/src/components/usdc-purchase-details-modal/components/TrackLink.tsx, packages/web/src/components/usdc-purchase-details-modal/components/styles.module.css, packages/web/src/components/usdc-transaction-details-modal/USDCTransactionDetailsModal.tsx, packages/web/src/components/user-generated-text/UserGeneratedText.tsx, packages/web/src/pages/profile-page/components/SocialLink.tsx, packages/web/src/pages/profile-page/components/mobile/SocialLink.tsx, packages/web/src/pages/settings-page/components/desktop/DeveloperApps/AppDetailsPage.tsx, packages/web/src/pages/upload-page/fields/stream-availability/collectible-gated/CollectibleGatedDescription.tsx, packages/web/src/pages/upload-page/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx
UI updates gated on premium album feature flag.
Will follow up with support for album purchases/sales, and that `ExternalLink` change you requested @dylanjeffers .
With ellipses:
=> [PAY-2675] New Purchase/Sale details modal UI

packages/mobile/src/components/details-tile/DetailsTile.tsx, packages/mobile/src/components/lineup-tile/LineupTile.tsx, packages/mobile/src/components/lineup-tile/LineupTileAccessStatus.tsx, packages/mobile/src/components/lineup-tile/LineupTileActionButtons.tsx
Sibling of https://github.com/AudiusProject/audius-protocol/pull/8029
- Show purchase button on playlist feed tiles
- Open purchase modal on click
- Add dog ear to playlist feed tiles
working on ios sim
=> [PAY-2671] Add purchase button to native mobile playlist feed tiles

packages/web/src/common/store/upload/sagas.ts
Found a very easy-to-miss issue here since The `collectionMetadata.artwork` is an object like `{url: '', file: null}`.
This is just reverting back to the way it way before this PR:
https://github.com/AudiusProject/audius-protocol/pull/7723/files#diff-cd2a776f8ad4b4f879367d7b620db02fdf59a71b27f5e0289b557c8e60d47e65L75
=> Hotfix tracks not getting artwork

packages/discovery-provider/ddl/migrations/0066_hotfix_blank_track_images.sql
On March 26th I introduced a bug that caused track artwork not to inherit the parent collection artwork. This restores images to those. A [different PR](https://github.com/AudiusProject/audius-protocol/pull/8043) has the client fix.
I capped the migration to not run for newer tracks to keep it relatively safe, although it's probably fine to continue to run in the future (and possibly wanted!).
Tested on a sandbox and then a sample on DN 4, which worked.
=> Fix tracks uploaded without cover art

packages/ddex/ingester/common/sdk_types.go, packages/ddex/ingester/common/types.go, packages/ddex/ingester/e2e_test/e2e_test.go, packages/ddex/ingester/parser/ern38x.go, packages/ddex/publisher/src/models/pendingReleases.ts, packages/ddex/publisher/src/models/publishedReleases.ts, packages/ddex/publisher/src/services/publisherService.ts, packages/ddex/webapp/client/src/components/Collection/Collection.tsx
Adds all the types and logic updates to the DDEX publisher and web app to get back to a working state after the latest refactor.
The OAuth + upload flow resulted in a successful stage upload:
1. `audius-compose up --ddex-release-by-release`, go to localhost:9000, and login with Audius
2. `aws --endpoint=http://ingress:4566 s3 mb s3://audius-test-raw && aws --endpoint=http://ingress:4566 s3 mb s3://audius-test-crawled`
3. `aws --endpoint=http://ingress:4566 s3 cp ./ingester/e2e_test/fixtures/release_by_release/ern381/sony1.zip s3://audius-test-raw`
=> [PROTO-1753] Make ddex publisher+web work with refactored parser

packages/web/e2e/test.ts, packages/web/e2e/uploadCollection.test.ts, packages/web/e2e/uploadTrack.test.ts
Upload tests were failing due to the user not being loaded by the time the test clicks continue.
Also removes redundant hydration checks.
=> Fix failing E2E upload tests

.circleci/src/workflows/web.yml
This job accounts for a majority of our credit spend, and we don't typically run desktop apps from staging.
=> Skip Mac staging desktop build

packages/ddex/ingester/e2e_test/e2e_test.go, packages/ddex/ingester/parser/ern38x.go, packages/ddex/publisher/src/services/publisherService.ts, packages/discovery-provider/src/api/v1/models/playlists.py, packages/discovery-provider/src/schemas/playlist_schema.json, packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py, packages/discovery-provider/src/tasks/metadata.py
- Persists UPC and ISWC as top-level identifiers in addition to where they were currently stored (within metadata under `ddex_release_ids`).
- Fixes Discovery bug which was ignoring UPC. Now Discovery persists UPC when passed during album creation.
- UPC is top-level in DDEX and passed through to Discovery when tested locally
- Tested on a stage node, including updating the album after to ensure this didn't overwrite the UPC field to be null
=> [PROTO-1760] Ensure UPC and ISWC are persisted top-level

packages/libs/src/services/solana/transactionHandler.ts
Reduce potential log spam. Basically reverts https://github.com/AudiusProject/audius-protocol/pull/7878.
=> [PAY-2579] Change tx handler logs back to warn

packages/discovery-provider/integration_tests/challenges/test_audio_matching_challenges.py, packages/discovery-provider/src/tasks/index_payment_router.py
Move $AUDIO matching challenge event dispatch to inside the valid purchase branch - so that we only ever dispatch these events on valid purchases.
Bonus - a test was misnamed.
Untested - will test on local stack tmr
=> [PAY-2343] Only dispatch audio matching challenges for valid purchases

packages/web/src/components/track/desktop/stats/Stats.module.css, packages/web/src/components/track/desktop/stats/StatsText.module.css
Small fix to apply the same line-height to all of the stats text
(Shoutout AJ with the eagle eyes)
=> [C-4253] Fix stats test line-height

packages/harmony/src/components/layout/Paper/Paper.mdx, packages/harmony/src/components/layout/Paper/Paper.stories.tsx, packages/harmony/src/components/layout/Paper/Paper.tsx, packages/harmony/src/components/layout/Paper/types.ts, packages/mobile/src/harmony-native/components/layout/Paper/Paper.stories.tsx, packages/mobile/src/harmony-native/components/layout/Paper/Paper.tsx, packages/mobile/src/harmony-native/components/layout/Paper/types.ts, packages/mobile/src/harmony-native/foundations/shadows/shadows.ts
Adds interactive paper variant when user provides onClick prop. This will form the basis for "card" and "tile"
=> [C-4001] Add interacive paper variant

packages/web/src/components/track/GiantTrackTile.module.css
Small update to fix the alignment of the badge and the text
=> [C-4256] Fix misaligned artist badge in premium content unlock section

packages/libs/src/services/solana/transactionHandler.ts
send solana txs to an RPC every 2 seconds, going down the list of known RPCs, rather than trying 1 RPC for 60s then falling back to the others one at a time
=> increase solana RPC reselect freq

packages/ddex/webapp/Dockerfile, packages/ddex/webapp/Dockerfile.fast, packages/ddex/webapp/server/package.json, packages/ddex/webapp/server/src/app.ts
Adds the following standard production aspects to the DDEX Express server:
- [Helmet](https://www.npmjs.com/package/helmet) for security-related HTTP headers
- Removing exposing of config that isn't necessary anymore
- Ensuring running in prod uses NODE_ENV=production (the npm script had this, but the Dockerfile wasn't using it)
I'm ensuring requests still work on a stage node and locally before merging.
=> Productionize DDEX webserver

packages/web/src/components/track/desktop/PlaylistTile.tsx
The border was too strong here. Bumping it down to keep things visually balanced.
The change is subtle, but the strong border stands out when viewed in context of the feed.
local web
=> Reduce border on playlist tile track list

packages/common/src/services/audius-backend/solana.ts
Removes ComputeBudget instructions from the withdrawal transaction we get back from Coinflow, since the budget will change according to the new set of instructions.
Tested against prod. Successfully withdrew.
=> Remove ComputeBudget from Withdrawals

packages/discovery-provider/src/schemas/playlist_schema.json, packages/discovery-provider/src/tasks/entity_manager/utils.py, packages/discovery-provider/src/tasks/metadata.py
- Fixes DDEX albums being editable by the artist (I think this was due to case-sensitivity)
- Fixes other DDEX fields not being persisted for albums due to metadata filtering in Discovery
I tested on stage DN3 and verified that the fields now persist in Postgres.
=> [PROTO-1754] Fix DDEX albums being editable, fields not persisting

packages/mobile/src/screens/notifications-screen/NotificationListItem.tsx, packages/mobile/src/screens/notifications-screen/Notifications/TrackAddedToPurchasedAlbumNotification.tsx
This concludes all work on PAY-2657
- Add support for new `TrackAddedToPurchasedAlbum` notification type in mobile
working on ios against local stack
=> [PAY-2685] Render TrackAddedToPurchasedAlbumNotification on mobile

.circleci/src/jobs/@common-jobs.yml
Seeing common test failures: https://app.circleci.com/pipelines/gh/AudiusProject/audius-protocol/54838/workflows/5544563e-a493-47c6-aadf-318c2b3f937d/jobs/767847 seemingly because we do not persist the libs node_modules in common ci
=> Restore common deps in CI

packages/mobile/metro.config.js
Fixes an issue running mobile locally due to `unstable_enablePackageExports: true,`
Can run and build mobile locally
=> Fix metro support for @metaplex-foundation/umi

packages/discovery-provider/src/tasks/index_nethermind.py
As shown in the linked axiom chart (see ticket), trending rewards sometimes get missed when backed up in the queue and the rewards bot can't calculate. Since this is normally a part of the index_nethermind indexing process anyways I added it to that queue for priority so rewards are calculated in a timely manner.
=> PROTO-1768: add trending challenges to index_nethermind queue for priority

monitoring/vector/start.sh, monitoring/vector/vector.toml
- Sends logs to Axiom for DDEX containers except for mongo and mongo-init (up for debate, but I don't see them being very useful compared to their spam)
- Uses `DDEX_URL` as the `node` field because otherwise it was empty, and we want a way to differentiate prod DDEX instances
- I already added the Vector container to the DDEX audius-docker-compose yaml separately
I pushed a Docker image with these changes and confirmed that the logs show up in Axiom with the correct `node` field.
=> [PROTO-1764] Pipe vector logs for ddex containers

.circleci/config.yml
Update `generate-client-release` command to only bump web and mobile versions instead of every package. Changesets will handle bumping everything else for us
=> Only bump web and mobile versions on release branch

packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimiter.ts
Removes rate limit locally for relay. This can block audius-cmd if you use it a lot for the same command.
audius-cmd create-user a bunch of times
=> skip relay rate limit on dev

dev-tools/compose/docker-compose.pedalboard.prod.yml, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/index.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/health/health.ts
Adds a /health_check route to solana relay and uses this to gauge health in the docker container. More data can be added to this in the future as we build out solana relay for plays and such.
Docker container won't come up as healthy if this is down. `audius-compose up`
```
docker ps
CONTAINER ID   IMAGE                                                 COMMAND                  CREATED         STATUS                   PORTS                                            NAMES
39717cc92f50   audius-protocol-discovery-provider                    "sh -c '. /tmp/dev-t…"   5 minutes ago   Up 5 minutes (healthy)   5000/tcp                                         audius-protocol-discovery-provider-1
d637f609a1b7   audius-protocol-solana-relay                          "docker-entrypoint.s…"   5 minutes …
```
=> PAY-2563: add solana relay health check

packages/mobile/src/components/lineup-tile/LineupTile.tsx, packages/mobile/src/components/lineup-tile/LineupTileStats.tsx, packages/web/src/components/track/desktop/TrackTile.tsx, packages/web/src/components/track/mobile/TrackTile.tsx
- Adds the purchase button to unfurled albums in DMs
- Relocates the button to match designs on tracks as well
Looks good on public and private albums of various types
=> [PAY-2698] Add purchase button do album DMs (mobile)

packages/libs/src/sdk/types/File.ts
When calling `uploadTrack` with a flac file in node you get:
```
{ "code": "custom", "message": "Audio file has invalid file type. Supported file types are: audio/mpeg, audio/mp3, audio/aiff, audio/flac, audio/ogg, audio/wav, audio/vnd.wave", "path": [ "trackFiles", 0 ] }, { "code": "custom", "message": "Audio file has invalid file type. Supported file types are: audio/mpeg, audio/mp3, audio/aiff, audio/flac, audio/ogg, audio/wav, audio/vnd.wave", "path": [ "trackFiles", 1 ] },
```
because `file-type` package gives audio/x-flac for flac
=> Allow audio/x-flac mime type

packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
PrivacyInfo didn't have a target specified for AudiusReactNative. This may be why apple is still complaining
=> Add target for iOS privacy manifest

packages/discovery-provider/integration_tests/tasks/entity_manager/test_developer_app_entity_manager.py, packages/discovery-provider/src/tasks/entity_manager/entities/developer_app.py, packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
Avoid unwanted behaviors by disallowing creating a developer app if the address belongs to a user (i.e. matches a user's erc wallet)
=> Don't allow creating developer app with user wallet as address [C-4041

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/identity-service/src/routes/instagram.js, packages/identity-service/src/routes/tiktok.js, packages/identity-service/src/routes/twitter.js, packages/identity-service/src/utils/waitForUser.js, packages/identity-service/src/utils/waitForUser.ts, packages/libs/src/api/Account.ts, packages/libs/src/services/identity/IdentityService.ts, packages/web/src/common/store/pages/signon/sagas.ts
Request users from DN instead of from the Identity db, since the Identity db won't have handles at the time of association request and these endpoints aren't hitting the auth middleware which would populate it. Continuously request until the blocknumber is hit.
Tested the instagram endpoint waits until blocknumber is passed. Didn't test the rest...
=> [ONC-74] Fix social account association

packages/ddex/ingester/common/sdk_types.go, packages/ddex/ingester/common/types.go, packages/ddex/ingester/e2e_test/e2e_test.go, packages/ddex/ingester/parser/ern38x.go, packages/ddex/ingester/parser/parser.go, packages/ddex/publisher/src/models/pendingReleases.ts, packages/ddex/publisher/src/services/publisherService.ts
Parse and persist release date (from the release details) and validity start date (from the corr. deal) separately. Poll for `max(release_date, validity_start_date) >= current_date` in the publisher. If no `<ReleaseDate>` or `<GlobalOriginalReleaseDate>` is provided, `release_date` gets set to the validity start date, which is required. The `release_date` is what gets displayed in the UI.
e2e tests, upload an xml locally
=> DDEX separate release date and validity start date

.github/workflows/publish-packages.yml, scripts/publish-packages.sh, scripts/version-packages.sh
I noticed that the changeset github action failed to create a pr after @rickyrombo merged a changeset. This pr fixes it and adds some logs!
Created a test branch and confirmed things are working
=> Fix changeset github action

package-lock.json, packages/mobile/android/app/build.gradle, packages/mobile/ios/Podfile.lock, packages/mobile/package.json
Now that we have our own `PrivacyInfo.xcprivacy` file, we're running into this bug: https://github.com/getsentry/sentry-react-native/issues/3599
So this upgrades us to the version of sentry which fixes the issue.
Tested locally on iOS emulator. Will need a test on staging before we send it out to make sure sentry logs are still propagating.
=> Upgrade sentry to fix iOS build errors

packages/mobile/src/harmony-native/components/layout/Box/Box.tsx
This fixes an issue where components using `Paper` on mobile don't correctly apply background colors on iOS. I think the underlying issue here might be a bug with RN, but I couldn't find any in their repo.
The way this works is:
* `Paper` renders a styled `Flex`, passing `white` as the `backgroundColor`
* `Flex` renders a styled `Box`, passing the `backgroundColor` prop through
* `Box` checks the passed value against `theme.colors.background` to see if it's a valid background color and maps it accordingly.
* `Box` renders a `View` and passes all "valid" props through, based on a filter list.
Since `backgroundColor` is not in the filter list for `Box`, it ends up being passed down to `View`. We then pass a `style` object which _should_ override the `backgroundColor` value. For some reason, …
=> [ONC-76] Exclude backgroundColor from forwardedProps for Box

packages/discovery-provider/src/app.py
We are still seeing a backlog of celery messages on some nodes. Since we're not distributing celery in the way it normally would be used purging the queue and letting beats + self queued tasks startup cleanly is probably all we need to keep these under control for now. With at least daily releases this will make sure tasks don't build up longer than 24 hours and then on a new deploy they'll start up as normal.
This ran with the initial celery concurrency change so all tasks do correctly start back up.
=> PROTO-1755: purge celery messages on startup

scripts/install-git-secrets.sh
Installing git-secrets fails for some reason. _Could be that re-running the secrets and not changing the config returns a non-zero code and that made it fail ...  unsure_.
The fix removes the `[secrets]` section from the ./git/config file so that postinstall could freshly re-add it.
locally
=> Fix git secrets

packages/discovery-provider/src/challenges/challenges.dev.json, packages/discovery-provider/src/challenges/challenges.stage.json, packages/discovery-provider/src/challenges/create_new_challenges.py
Update challenge jsons only for dev and stage envs, _not prod_.
Note: for some reason, `profile-completion` is only on the prod challenge json file. maybe they should be added to the other env json files to. _at any rate, cooldown days will need to be added to `profile-completion` whenever we do this update for the prod json file_
Need to test
=> [C-4293] Add cooldown days to challenge definitions in jsons for dev and stage envs

packages/web/src/pages/pay-and-earn-page/components/WithdrawalsTable.tsx
* Updates header from 'Destination' to 'Method'
* Updates the contents of the cell to be 'Cash' or 'Crypto', with the destination address being found in the details modal
fixes PAY-2399
---
=> [PAY-2399] Update header and cell contents for withdrawals table

packages/common/src/store/buy-usdc/sagas.ts
Two small issues fixed here:
1. The saga we use to check for a recoverable balance attempts to read the user immediately without using `waitForRead()`. So if this is triggered early in the app lifecycle, the `user` will almost always be empty and cause it to exit early
2. We have a separate saga that runs on page load to check for recovery, but it can run in parallel. I updated this to `put` the same action we use for other flows, so that the `takeLeading` will keep us from running it concurrently if you happen to navigate directly to any page that checks for recovery on mount.
Fixes PAY-2720
=> [PAY-2720] Fixes issues with checking for recovery on load

packages/harmony/src/components/input/TextInput/TextInput.module.css, packages/harmony/src/components/input/TextInput/TextInput.tsx
Padding to left of start icon in harmony `TextInput` was too large.
Small before:
Small after:
Large after:
=> Fix web TextInput small variant icon left padding

packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/middleware/signerRecovery.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/redis.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/relay.ts
When this code was first written, the `all-discovery-nodes` cache key looked like `["endpoint1", "endpoint2"...]` etc. Now it's an array of objects that looks like `[{"delegateOwnerWallet": "0x123", "endpoint": "endpoint1"} ...]` etc
=> Fix Solana Relay Discovery Node cache parsing

packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
Was incorrectly showing the label without formatting.
=> [ONC-79] Fix reward formatting bug

.changeset/new-taxis-trade.md, .changeset/plenty-toes-report.md, packages/spl/src/reward-manager/RewardManagerProgram.ts, packages/spl/src/reward-manager/types.ts, packages/web/src/common/store/pages/audio-rewards/sagas.ts, packages/web/src/store/errors/reportToSentry.ts
Occasionally an attestation signature returned by our services will have less than 64 bytes. When recreating this signature logic, I didn't realize that meant it could have 63 1/2 bytes 😝 
Using `Buffer.alloc()` to ensure 64 bytes was stripping the last half-byte off and pushing everything a half byte. Eg.
`d405b277dc948f97d7b7db8648cb16590d66084ba49642fedb08380ce5027a95d0a895287a3331332e7ad13daba87eed5c70820a19ca2eb6cc0ea1eb4695ba4`
would become
`00d405b277dc948f97d7b7db8648cb16590d66084ba49642fedb08380ce5027a95d0a895287a3331332e7ad13daba87eed5c70820a19ca2eb6cc0ea1eb4695ba` (note the two prepended 0s)
instead of
`0d405b277dc948f97d7b7db8648cb16590d66084ba49642fedb08380ce5027a95d0a895287a3331332e7ad13daba87eed5c70820a19ca2eb6cc0ea1eb4695ba4` (note the 4)
That was fun.
While I was at it, I …
=> Fix signature in SDK rewards

packages/common/src/models/Analytics.ts, packages/web/src/components/collections-table/CollectionsTableOverflowMenuButton.tsx, packages/web/src/pages/dashboard-page/components/ArtistContentSection.tsx, packages/web/src/pages/dashboard-page/components/ArtistDashboardAlbumsTab.tsx, packages/web/src/pages/dashboard-page/components/ArtistDashboardTracksTab.tsx, packages/web/src/pages/dashboard-page/components/EmptySearchResults.tsx, packages/web/src/pages/dashboard-page/components/EmptyTabState.tsx, packages/web/src/pages/dashboard-page/components/hooks.ts
Empty states for 2 cases:
- User has no tracks/albums
- User entered a search query that returns no results
=> [PAY-2730] Artist Dashboard empty tab states

packages/common/src/utils/timeUtil.ts, packages/mobile/src/components/lineup-tile/LineupTile.tsx, packages/mobile/src/components/lineup-tile/LineupTileActionButtons.tsx, packages/mobile/src/components/lineup-tile/LineupTileTopRight.tsx, packages/web/src/components/track/desktop/TrackTile.tsx, packages/web/src/components/track/mobile/BottomButtons.tsx, packages/web/src/components/track/mobile/PlaylistTile.tsx, packages/web/src/components/track/mobile/TrackTile.tsx
⚠️ To be cherry-picked onto release ⚠️
- Remove duplicate purchase button and replace with locked content icon
- Use `3h 5m` formatting for duration
- Fix padding on bottom buttons
local mobile web
=> [PAY-2737] Fix mobile collection tile formatting

packages/harmony/src/components/button/FilterButton/FilterButton.tsx, packages/harmony/src/components/button/FilterButton/types.ts, packages/web/src/components/upload/TrackPreview.tsx, packages/web/src/pages/dashboard-page/components/ArtistContentSection.tsx
Sets FilterButton opacity to 0.6 when `disabled` is true.
Also changes the prop name to `disabled` from `isDisabled` to match our other components.
=> [PAY-2731] Web FilterButton transparent when disabled

.changeset/violet-cups-bake.md, packages/discovery-provider/src/tasks/cache_current_nodes.py, packages/discovery-provider/src/utils/get_all_nodes.py, packages/libs/src/sdk/api/challenges/ChallengesApi.ts, packages/libs/src/sdk/config/development.ts, packages/libs/src/sdk/config/production.ts, packages/libs/src/sdk/config/staging.ts, packages/libs/src/sdk/scripts/generateServicesConfig.ts, packages/libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts, packages/libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.ts, packages/libs/src/sdk/services/DiscoveryNodeSelector/types.ts, packages/libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.test.ts
- Updates Discovery Node to expose owner wallets in service list
- Updates SDK to use owner wallets in `getUniquelyOwnedEndpoints`
- Regenerates bootstrap config in SDK to have it pick up owner wallets
- Improves logging in ChallengesApi layer to be able to trace individual claims
Ran tests
=> [PAY-2749] Use ownerWallet instead of delegateOwnerWallet for uniquely owned endpoints in SDK

.changeset/six-pens-flash.md, package-lock.json, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/health/health.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.test.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.ts, packages/spl/package.json, packages/spl/src/index.ts, packages/spl/src/reward-manager/RewardManagerProgram.test.ts, packages/spl/src/reward-manager/RewardManagerProgram.ts, packages/spl/src/secp256k1/Secp256k1Program.test.ts, packages/spl/src/secp256k1/Secp256k1Program.ts
Adds helpful methods to the Secp256k1Program from @solana/web3.js for decoding and recovering signers. Useful for us if we want to check why transactions are failing.
Stopped short of adding an override to the program to validate on creating instructions, but could see that being useful... instead, added the check to the relay itself so it'll error quickly if the instruction signature doesn't match the signer.
Also fixes some minor things when decoding the existing attestations in the verified messages account and added more tests.
=> [PAY-2747] Fix attestation decoding and add Secp256k1Program utils

packages/web/src/pages/oauth-login-page/OAuthLoginPage.module.css, packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx, packages/web/src/pages/oauth-login-page/components/ContentWrapper.tsx, packages/web/src/pages/oauth-login-page/components/PermissionsSection.tsx, packages/web/src/pages/oauth-login-page/hooks.ts, packages/web/src/pages/oauth-login-page/messages.ts
Does not implement the switching behavior, but brings app images in & some copy changes. Tried to best to some little harmonization, but it's not a ton.
```
```
Test url: http://localhost:3001/oauth/auth?scope=write&api_key=15463128bee74d365962f62f8681f829727f6334&redirect_uri=http://127.0.0.1:3000/connect/callback&response_mode=query
=> [PAY-2727] Add images to oauth popup

packages/web/src/components/collection/mobile/CollectionHeader.tsx, packages/web/src/components/track/GatedContentSection.tsx
- Added purchase button to mobile web
- Fixed wrapping inside the gated content section for narrow windows
local web
=> [PAY-2725] Add purchase button to mobile web albums

.github/workflows/publish-packages.yml, packages/libs/src/sdk/examples/signed-request/package.json, scripts/check-wildcard-deps.sh
Add a step to `publish-packages.yml` that prevents us from publishing packages containing a wildcard `*` dependency. This is to prevent consumers from getting the wrong version of a dependency when using an older version of one of our packages
Confirmed script accurately checks for wildcard deps in public package.jsons
=> [INF-670] Add check for wildcard deps in public packages

docs/docs/developers/guides/log-in-with-audius.mdx, packages/ddex/webapp/client/src/pages/Login/Login.tsx, packages/libs/src/sdk/oauth/OAuth.ts, packages/web/src/pages/oauth-login-page/OAuthLoginPage.module.css, packages/web/src/pages/oauth-login-page/OAuthLoginPage.tsx, packages/web/src/pages/oauth-login-page/components/ContentWrapper.tsx, packages/web/src/pages/oauth-login-page/hooks.ts, packages/web/src/pages/oauth-login-page/types.ts
Allow DDEX to pass a flag and use a full page oauth variant
```
```
Test url:
http://localhost:3001/oauth/auth?scope=write&api_key=92ae5d1be6a54327db811c949a3f520cf3e0aa51&redirect_uri=http://127.0.0.1:3000/connect/callback&response_mode=query&display=fullScreen
Also confirmed display=popup works correctly still!
=> [PROTO-1787] Add full screen oauth variant

packages/common/src/hooks/useAccessAndRemixSettings.test.ts, packages/common/src/hooks/useAccessAndRemixSettings.ts
Per some recent scope changes we have decided to halt some ongoing work around hidden albums. 
This PR disables the changes from this PR https://github.com/AudiusProject/audius-protocol/pull/8191 but since its so simple to disable the feature I decided it was better to leave the supporting logic in and just disable it for now.
web:stage
=> Disable hidden album upload feature

package-lock.json, packages/ddex/publisher/scratch/server.ts
See sister PR:
And also, for details on the `redirect_mode`
https://stackoverflow.com/questions/14707345/oauth2-query-string-vs-fragment
See other PR
=> Add redirect path and fix #/? issue in scratch

packages/web/src/components/track/GiantTrackTile.tsx
Fixes this bug
Also double checked other spots to make sure it looks good
=> [ONC-81] Fix giant track tile visual bug

packages/web/src/components/collections-table/CollectionsTable.module.css, packages/web/src/components/collections-table/CollectionsTable.tsx, packages/web/src/components/collections-table/CollectionsTableOverflowMenuButton.tsx, packages/web/src/components/table/components/OverflowMenuButton.module.css, packages/web/src/components/table/components/TableFavoriteButton.module.css, packages/web/src/components/table/components/TableRepostButton.module.css, packages/web/src/components/tracks-table/TracksTable.module.css, packages/web/src/components/tracks-table/TracksTable.tsx
Show content type (follow-gated, premium, hidden etc) to the far right of each row in a `TracksTable`. Disappears on hover to show the overflow menu instead.
Also updated cell width + icon sizes to more closely match mocks.
Bit of css finnagling to get the icons to all line up. Would have preferred to do it with a state var, but couldn't figure out a way without breaking the rule of hooks.
Plz ignore the wrong gray color for the icons, not sure what's going on there. I didn't change the colors so I think it's some local env thing, should be fine once it gets to stage.
https://github.com/AudiusProject/audius-protocol/assets/3893871/1b8b1925-e8ed-4298-9e2d-2331d022f5be
=> [PAY-2704] Show content type icon in last cell of row in TracksTable

packages/web/src/components/user-name-and-badges/UserNameAndBadges.module.css
Fixes bug that was clipping bottom of text in certain places like `SalesTable`.
Before:
After:
=> Fix UserNameAndBadges line-height

packages/discovery-provider/ddl/migrations/0068_refresh_sepolia_indexing.sql
For stage only, update the last scanned eth block to the block at which we migrated to Sepolia.
Previously were attempting to scan recent Goerli block numbers, which were beyond the Sepolia max block number.
Tested on stage DN5 and it worked. See logs showing the scanning of the blocks.
```
{"level": "INFO", "msg": "index_eth.py | Scanning events from blocks 5791842 - 5791859", "timestamp": "2024-04-27 23:50:28,626", "service": "worker", "otelSpanID": "0", "otelTraceID": "0", "otelServiceName": "discovery-provider", "cpu": 0.0, "memory": 407.375}
{"level": "INFO", "msg": "event_scanner.py | Saving last scanned block (5791859) to redis", "timestamp": "2024-04-27 23:50:28,692", "service": "worker", "otelSpanID": "0", "otelTraceID": "0", "otelServiceName": "discovery-provider", "cpu": 17.0, …
```
=> [ONC-83] Add stage-only migration to fix indexing the sepolia chain

packages/web/src/components/tracks-table/TracksTable.tsx
=> Fix clipped text in TracksTable name column

packages/discovery-provider/integration_tests/gated_content/test_access.py, packages/discovery-provider/src/gated_content/helpers.py
Main bug was that we were returning `False` early if `track_record.playlists_containing_track` didn't exist on line 92. After that, it seems reasonable to perform the following checks conditionally.
Local web against local stack - confirmed purchaser retains access to prem track that was removed from a prem album that the user previously purchased.
=> [PAY-2789] Bug fix for retaining access on track removal from prem album

packages/mobile/android/app/src/main/AndroidManifest.xml
While debugging android permission notifs, we found that settings were showing this for Audius:
Looking into the manifest revealed that we were missing a permission
on android:stage, after this change it now shows
=> [ONC-82] Fix android notif permissions

packages/web/src/common/store/upload/sagas.ts
Am I crazy? `trackIndex` is the order the tracks metadata come into the function as.
```
[5,4,1,2,6].sort((a, b) => a - b)
> [1, 2, 4, 5, 6]
```
=> [C-4327] Fix track ordering within playlist/album

packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
For collection page tracks tables:
- Remove artist column
- Show reposts column
Premium album
Normal album
=> [PAY-2817] Web collections show reposts, remove artist column

packages/common/src/models/Analytics.ts, packages/common/src/store/gated-content/sagas.ts, packages/web/src/components/collection/desktop/CollectionHeader.tsx, packages/web/src/components/collection/mobile/CollectionHeader.tsx, packages/web/src/components/create-playlist/PlaylistForm.tsx, packages/web/src/components/edit-playlist/desktop/EditPlaylistModal.tsx, packages/web/src/components/edit-playlist/mobile/EditPlaylistPage.tsx, packages/web/src/components/lineup/LineupProvider.tsx, packages/web/src/components/track/GatedContentSection.tsx, packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx, packages/web/src/components/track/desktop/PlaylistTile.tsx, packages/web/src/components/track/desktop/TrackTile.tsx, packages/web/src/components/track/mobile/ConnectedPlaylistTile.tsx, packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx, packages/web/src/components/track/mobile/ConnectedTrackTile.tsx, packages/web/src/components/track/mobile/PlaylistTile.tsx, packages/web/src/components/track/mobile/TrackTile.tsx, packages/web/src/components/track/types.ts, packages/web/src/pages/chat-page/components/ChatMessagePlaylist.tsx, packages/web/src/pages/chat-page/components/ChatMessageTrack.tsx, packages/web/src/pages/collection-page/CollectionPageProvider.tsx
My aim was to provide details supporting these dashboards:
- Premium album upload count
- No added metrics, in metabase we can query using existing upload success event & collection ID
- Premium album edits
- New metrics added
- Premium modal opens & where they are coming from
- Expanded metrics
- Premium album purchases
- No added metrics, in metabase we can query using existing purchase event & collection ID
- Track added to premium album
- No added metrics, in metabase we can query using existing 'added to collection' event & collection ID
Various analytics changes events related to premium albums
- Added events for collection edit & one specifically for tracking access changes
- Greatly expanded the premium modal source type, previously was using `track tile` for a ton of stuff
- DMs …
=> [PAY-2766] Analytics events for premium albums

packages/discovery-provider/ddl/functions/handle_playlist.sql, packages/discovery-provider/ddl/functions/handle_playlist_track.sql
The desired behavior:
New notification for when a user purchases an album from an artist, then the artist adds a new track to that purchased album. Think "T Swift just released a new track to the album you already own so you can listen to it for no extra cost."
The bug:
When the artist removes a track from the album, purchasers were getting notifications for each remaining track that existed in the album. This is because we were looping over every existing track in the playlist contents, and inserting a notification row for each.
Solution:
Replace with a new sql function that runs on every new row added to `playlist_tracks` table (which contains 1 row per track-playlist relationship). These rows are unique and never get deleted, which avoids duplicates.
Tested with local stack:
- …
=> [PAY-2796] Fix extra notifications on track removal from purchased album

packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/AudioMatchingRewardsModalContent.tsx, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
Fix cumulative rewards section and add cooldown summary tables in the reward drawers.
=> [C-4284] Fix rewards in mobile web

packages/common/src/hooks/purchaseContent/types.ts, packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx, packages/mobile/src/components/premium-content-purchase-drawer/PurchaseSuccess.tsx
- Change copy to say "view album"
- Navigate to album in background on purchase success
- Add helper typeguard to split between the different `PurchasableContentMetadata` types.
https://github.com/AudiusProject/audius-protocol/assets/3893871/733c3fd3-2d10-4e6b-80f7-ddd8985b262a
=> [PAY-2800] Fix mobile navigate to album on purchase success

packages/common/src/store/account/selectors.ts, packages/web/src/pages/dashboard-page/components/hooks.ts
In the artist dashboard, filter for only albums owned by the current user.
=> [PAY-2791] Show only own albums in artist dashboard

packages/common/src/hooks/useAccessAndRemixSettings.test.ts, packages/common/src/hooks/useAccessAndRemixSettings.ts, packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py, packages/web/src/common/store/cache/collections/commonSagas.ts, packages/web/src/components/create-playlist/PlaylistForm.tsx, packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx, packages/web/src/pages/upload-page/fields/AccessAndSaleMenuFields.tsx, packages/web/src/pages/upload-page/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx, packages/web/src/pages/upload-page/fields/types.ts
- Hidden albums were showing as Public in the form initial values
- Editing hidden album to premium wasn't working
- Populate splits for albums changed to premium
- Disable publishing of albums with hidden tracks
working on local web
=> [PAY-2823] Edit Album access control fixes

packages/web/e2e/editCollection.test.ts
=> Fix EditCollection playwright test

packages/web/src/components/track/mobile/PlaylistTile.tsx, packages/web/src/components/track/mobile/TrackTile.tsx
DM unfurls were showing the buy button for already purchased content. Fixed to show the unlocked icon if you own it already
local web
=> [PAY-2815] Show unlocked icon if dm content is purchased

packages/mobile/src/components/notification-reminder/NotificationReminder.tsx, packages/mobile/src/notifications.ts, packages/mobile/src/store/settings/sagas.ts
After #8279 I realized that permissions are still disabled even after the manifest change; so we needed a way to one-off trigger our notif permission modal and ask for them again
In the process I realized the existing setup wasn't working because it wasn't popping up the native Android window for some reason.
This PR fixes both.
on android:stage
1. Deleted app 
2. Built old version of code (used commit on main 1 before my previous change)
3. Verified that notifications setting is grayed out + off 
4. Signed into the app & clicked on the "enable notifs" modal
5. Rebuilt app with the manifest changes (used latest release-1.5.78 changes)
6. Verified notifications setting is no longer grayed out but still off
7. Swapped to this branch
8. Open the app again
9. Notifications modal popped up
10. …
=> Retrigger logic for android notification permissions post-manifest fix

packages/common/src/store/gated-content/sagas.ts, packages/common/src/store/purchase-content/sagas.ts
After purchasing an album, re-fetch the tracks inside of the album to update access.
Local web stage - confirmed all tracks in purchased album now show unlocked UI.
=> [PAY-2781] Poll for track access on album purchase

packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/purchase.ts, packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/sale.ts, packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseBuyer.ts, packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseSeller.ts
Small copy + formatting changes for purchase + sale emails
Not tested - test on stage
=> [PAY-2810] Purchase/Sale email fix text for albums

packages/harmony/src/components/artwork/Artwork.tsx, packages/web/src/components/avatar/Avatar.tsx, packages/web/src/components/card/Card.tsx, packages/web/src/components/card/index.ts, packages/web/src/components/collection/CollectionCard.tsx, packages/web/src/components/collection/index.ts, packages/web/src/components/upload/UploadChip.module.css, packages/web/src/components/user-card/UserCard.test.tsx, packages/web/src/components/user-card/UserCard.tsx, packages/web/src/components/user-card/index.ts, packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx, packages/web/src/pages/saved-page/components/desktop/AlbumsTabPage.tsx, packages/web/src/pages/saved-page/components/desktop/PlaylistsTabPage.tsx, packages/web/src/pages/search-page/components/desktop/SearchPageContent.jsx, packages/web/src/pages/search-page/components/desktop/SearchPageContent.module.css, packages/web/src/pages/search-page/components/mobile/SearchPageContent.module.css, packages/web/src/pages/search-page/components/mobile/SearchPageContent.tsx
- Migrates the first tranche of cards to the new system
- Adds new 'xs' variant for mobile cards that dynamically sizes
- Tons of code removed with this simplified design!
TODO: lots more cards to go, but some of them require lots of changes that i want to do separately
=> [C-4288] Migrate to new cards in profile, search, and library

packages/common/src/store/pages/audio-rewards/slice.ts, packages/common/src/store/pages/audio-rewards/types.ts, packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx, packages/mobile/src/components/challenge-rewards-drawer/ClaimAllRewardsDrawer.tsx, packages/web/src/common/store/pages/audio-rewards/sagas.ts, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ClaimAllRewardsModal.tsx
Add an action and corresponding saga to handle claiming all rewards that are claimable.
Update component to show loading state while claiming, and display confetti on success.
Also fix functionality on native mobile + add claim all button loading state on native mobile and toast on successful claim.
=> [C-4285] Add claim all rewards button functionality

mediorum/server/serve_image.go, mediorum/server/server.go
* use `http.ServeContent` for images, which will correctly set Content-Length header
* disable gzip middleware in mediorum server.  See [this](https://github.com/labstack/echo/issues/444) and [this](https://images.weserv.nl/faq/#are-images-compressed-in-any-way) for some reasoning.
Deployed to stage creator 6
=> Content-Length header for images

.circleci/src/jobs/test-audius-cmd.yml, dev-tools/audius-compose, packages/libs/scripts/check-generated-types.sh
The api diff test does not run in a container and therefore requires a modified /etc/hosts to properly query host containers
CI
=> Modify /etc/hosts on CI machines before api test

packages/discovery-provider/src/api/v1/users.py
I don't understand how this ever worked.
Cherry picked onto 0.6.93, 0.6.94 will remain abandoned
Tested on prod node
=> [QA-1215] Fix history

package-lock.json, package.json, packages/mobile/ios/Podfile.lock, packages/mobile/patches/react-native-google-cast+4.6.2.patch, packages/mobile/src/components/audio/AudioPlayer.tsx, packages/mobile/src/components/audio/GoogleCast.tsx, packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
3 bugs!
1. `useChromecast` was never called anywhere. Probably broken for a while.
2. iOS cast was broken because of this bug https://github.com/react-native-google-cast/react-native-google-cast/issues/510 hence the addition of patch-package changes. I tried a few things and found this to be the most straightforward
3. We never muted TrackPlayer when chromecast played, which was a very very jarring experience
I also tried to get iOS audio controls to work, including trying a new volume package, but it didn't work. I think the permissions may be different than what we provide and/or we may need a different cast version and it's probably not worth the investment now...!
* …
=> [QA-1212] Fix chromecast

docs/.vscode/spellright.dict, docs/docs/node-operator/setup/advanced.mdx, docs/docs/node-operator/setup/architecture.mdx, docs/docs/node-operator/setup/hardware-requirements.mdx, docs/docs/node-operator/setup/installation.mdx, docs/docs/node-operator/setup/overview.mdx, docs/sidebars.js
Documentation on how to setup an Audius Node using audius-d
- [System Requirements](https://268d77d9.docs-eaf.pages.dev/node-operator/setup/hardware-requirements)
- [Installation & Migration](https://268d77d9.docs-eaf.pages.dev/node-operator/setup/installation)
=> [PROTO-1706] - Audius-d Node Documentation

packages/web/src/pages/upload-page/components/AnchoredSubmitRow.tsx
Adds a simple error message to the track/collection upload flows
web:stage
=> Add error message to upload flow

packages/web/src/components/track/GiantTrackTile.tsx
Fix hidden tracks being allowed to add to on a public playlist
web:stage
=> [QA-1241] Fix hidden track add to playlist allowing non hidden items

packages/common/src/hooks/purchaseContent/utils.ts, packages/mobile/src/components/lineup-tile/TrackTile.tsx, packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx, packages/mobile/src/components/track-list/TrackListItem.tsx, packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx, packages/web/src/components/track/GiantTrackTile.tsx, packages/web/src/components/track/desktop/ConnectedTrackTile.tsx, packages/web/src/components/track/desktop/TrackListItem.tsx, packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx, packages/web/src/components/track/mobile/ConnectedTrackTile.tsx, packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Compare with: https://github.com/AudiusProject/audius-protocol/pull/8227
Only allow "add to playlist" + "add to album" options if user has purchased track.
=> Disable add to playlist for prem tracks if not purchased

packages/harmony/src/components/text-link/types.ts, packages/web/src/components/collection/mobile/CollectionHeader.tsx, packages/web/src/components/collections-table/CollectionsTable.tsx, packages/web/src/components/link/TextLink.tsx, packages/web/src/components/link/UserLink.tsx, packages/web/src/components/track/LockedContentDetailsTile.tsx, packages/web/src/components/tracks-table/TracksTable.tsx, packages/web/src/pages/server-track-page/mobile/ServerTrackPageHeader.tsx, packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
TextLink had textVariant = 'body' default introduced, which broke a few cases that implicitly received styles from it's parent: 
(the user name is too big)
Fixes issue introduced by setting default textVariant on text-link by removing default and updating usages.
Also improves the typing around text-link, fixing a few instances that were malformed.
=> Fix issues with text-link variant

packages/ddex/processor/PROD.md, packages/ddex/processor/README.md, packages/ddex/processor/fixtures/01_delivery.xml, packages/ddex/processor/fixtures/02_update.xml, packages/ddex/processor/fixtures/03_delete.xml, packages/ddex/processor/src/db.ts, packages/ddex/processor/src/parseDelivery.test.ts, packages/ddex/processor/src/parseDelivery.ts, packages/ddex/processor/src/parseTakedown.test.ts, packages/ddex/processor/src/publishRelease.ts, packages/ddex/processor/src/server.ts
* parse xml switches on root xml node name to call either `parsePurgeXml` or `parseReleaseXml`
* adds a status for `DeletePending` and publisher will use that to perform deletes
* adds `messageTimestamp` to `releases` table... upsert will only update `releases` row to `PublishPending` if timestamp is newer (or timestamp is same and json changed)
* tests simulate state transitions
inspired by: https://github.com/AudiusProject/audius-protocol/pull/8251
=> ddex: handle updates and deletes

packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
Bug introduced in collection card migration that renders artist content when it should render user content, and vis-versa
=> Fix profile page artist vs user

packages/mobile/src/screens/audio-screen/Panel.tsx
Noticed that the native mobile spend to earn reward says "No Recent Activity" although my reward is in cooldown.
So that it shows correct label e.g. "Pending Reward" if reward is in cooldown period.
=> [PAY-2864] Fix progress label for reward on native

packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Fix duration showing 0m 0s on native mobile track page
ios:stage
=> [PAY-2866] Fix duration showing 0m 0s

packages/web/src/components/tile/Tile.tsx
The dog ear was seemingly 1 px off of the correct position, but it was just the border of the parent covering it up. 
No amount of repositioning fixed because the real issue was there was an `overflow: hidden` in the parent not allowing it to show.
To fix I moved it to be alongside the parent container so it can properly lay over the top
web:stage
=> [PAY-2888] Fix dog ear positioning

packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
Progress labels are not being formatted because of complex logic in determining when to format. 
Tried simplifying it to match what happens in mobile. Special logic for cooldown_rewards is not necessary. 
Tested locally against staging env.
=> [C-4339] Fix rewards progress label formatting

packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx, packages/web/src/components/card-legacy/desktop/CollectionArtCard.tsx, packages/web/src/components/collection/desktop/OverflowMenuButton.tsx, packages/web/src/components/collection/desktop/ViewerActionButtons.tsx, packages/web/src/components/collection/mobile/CollectionHeader.tsx, packages/web/src/components/collections-table/CollectionsTableOverflowMenuButton.tsx
Don't show favorite and repost action buttons or menu options for purchaseable albums you don't own
buttons showing when they should and not when they shouldn't
=> [PAY-2814] Omit favorite and repost buttons for unowned albums

packages/common/src/hooks/useAccessAndRemixSettings.test.ts, packages/common/src/hooks/useAccessAndRemixSettings.ts, packages/common/src/schemas/metadata.ts, packages/common/src/schemas/upload/uploadFormSchema.ts
Disable hidden option on access & sale, set `is_private` to false by default
web:stage
=> [PAY-2881] Fix access & sale showing hidden by default

packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
New designs show this `available to claim` label is removed and the button should show the claimable amount. Mobile appears to match design.
Ran local client against stage and confirmed labels look correct.
=> [C-4338] Fix $AUDIO available to claim

docs/docs/node-operator/setup/advanced.mdx, docs/docs/node-operator/setup/architecture.mdx, docs/docs/node-operator/setup/installation.mdx
"Creator" is the deprecated term for "content" nodes and audius-d configuration has been updated accordingly.
N/A
=> Change 'creator' to 'content' where applicable for audius-ctl docs

packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts
Offline mode was migrated away from the legacy `creator_node_endpoint` but we were still checking for it and throwing when it's missing. Removed the check and now it's working 🤦
working on mobile sim
can download tracks by newly created users
=> [PAY-2806] Fix offline downloads legacy content node selection

packages/mobile/src/screens/favorites-screen/LibraryCategorySelectionMenu.tsx
It just worked. Incredible! Shoutout @nicoback2 for making it forwards compatible
working on sim. Shows my purchased albums and not others
=> [PAY-2879] Add purchased pill to mobile albums library

packages/mobile/src/components/track-list/TrackListItem.tsx
* USDC-gated tracks can now be pressed to play preview + show locked icon at right of row
* Locked icon goes away when track is unlocked
* Locked icon also appears for other gated types (for future)
* Other gated types are still grayed out + unclickable (for future)
Locked tracks
Other types of locked gated tracks
unlocked
deleted tracks
=> [PAY-2809] Mobile premium album tracklist UI updates

comms/discovery/server/server.go
WS check is doing really strange things.
I am able to run this flavor of the check and properly connect to the host https://dn2.monophonic.digital, but it fails on the node itself
```
package main
import (
"context"
"fmt"
"net/url"
"os"
"strings"
"github.com/gobwas/ws"
)
type ChatServer struct {
config ServerConfig
}
type ServerConfig struct {
MyHost string
}
func (ss *ChatServer) doWebsocketTest() error {
wsUrl, err := url.Parse(strings.Replace(ss.config.MyHost, "http", "ws", 1))
if err != nil {
return err
}
wsUrl = wsUrl.JoinPath("/comms/debug/ws")
ctx := context.Background()
con, _, _, err := ws.Dial(ctx, wsUrl.String())
fmt.Println(err)
if err != nil {
return err
}
return con.Close()
}
func main() {
// Replace with your server configuration
serverConfig := ServerConfig{
MyHost: …
```
=> Add log for ws check

packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
Fixes issue where collection screen loading state showed "empty" initially. Now we include IDLE and LOADING as the loading state.
=> [QA-1239] Fix collection loading state

packages/mobile/src/components/core/Hyperlink.tsx, packages/mobile/src/harmony-native/components/input/TextInput/types.ts, packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
Fixes issue by adding onPress dismiss + properly handle onPress in Hyperlink
=> [QA-955] Dismiss keyboard when clicking external link

packages/web/src/pages/dashboard-page/components/ArtistContentSection.tsx, packages/web/src/pages/dashboard-page/components/TotalPlaysChart.module.css
UI fix to match mocks
before:
after:
=> [PAY-2886] Fix artist dashboard border radii

packages/mobile/src/components/challenge-rewards-drawer/ClaimAllRewardsDrawer.tsx, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ClaimAllRewardsModal.tsx
Noticed that the Claim All button did not immediately update to Done after successfully claiming all rewards. It updated later after the state was refreshed. This makes is so it updated automatically.
Web and mobile.
Also, reset success status on closing modal so that re-opening does not re-trigger confetti.
Also, make sure there is no state where claim all button is loading yet not disabled.
=> [PAY-2896][PAY-2908][PAY-2907] Update claim all button text logic

packages/common/src/schemas/upload/uploadFormSchema.ts, packages/web/src/common/store/upload/sagas.ts, packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx, packages/web/src/pages/upload-page/forms/EditCollectionForm.tsx
setting album from hidden to premium would not clear the `is_private: true` value on the collection. We see both icons showing since it's `is_stream_gated: true` and `is_private: true`
we update the unlisted value to true whenever we change the access to anything besides hidden.
local web
=> [PAY-2889] Fix edit collection unlisted value

packages/harmony/src/components/button/FilterButton/FilterButton.tsx
Selection should be static white
=> [PAY-2893] Fix FilterButton dark mode selection text color

packages/libs/src/sdk/api/users/UsersApi.test.ts, packages/libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts, packages/libs/src/sdk/services/DiscoveryNodeSelector/healthChecks.ts
See PAY-2911
The UsersApi.test.ts sendTip suite is failing in CI but passes when run locally. It times out in CI and when running audius-compose test run audius-sdk 
Disabling for now as it's become a timesink investigation
Includes an earlier change that prevents timeouts from happening after the requests resolve in discovery node selection, and which also ensures handles are cleared before test completions
=> Disable failing audius-sdk test

packages/web/src/components/tracks-table/TracksTable.tsx
We were directing the link to `/` if the user doesn't have stream access. However, the track page is set up to view locked content, so we should just direct you there anyway.
local web links working
=> [PAY-2871] Track table link to track even when it's gated

packages/mobile/src/app/App.tsx, packages/mobile/src/components/audio/AudioPlayer.tsx
minBuffer: 0.1
playBuffer: 0.1,
waitForBuffer: false,
=> all should help try to make RNTP buffer less and start playing back sooner
iosCategory: IOSCategory.Playback
contentType: 'audio/mpeg',
pitchAlgorithm: PitchAlgorithm.Music,
=> no real change I think, but are all "correct" based on what we're trying to do and maybe the thought is it would help the OS decide how to handle our content
I want to try to merge this PR and see how it fares on staging for a little, and then revert if we see anything weird
Local device running against prod
=> Play with RNTP buffer settings

packages/discovery-provider/src/solana/solana_helpers.py, packages/discovery-provider/src/tasks/index_payment_router.py, packages/discovery-provider/src/utils/helpers.py
Previously we ignored the Memo V2 Program. This allows us to parse those memos as well. Also adds support for loading from the cache for indexing payment router.
Tested locally, purchased a track.
=> Index all memos (v1 and v2) and use cache in index_payment_router

packages/ddex/processor/cli.ts, packages/ddex/processor/src/db.ts, packages/ddex/processor/src/publishRelease.ts, packages/ddex/processor/src/server.ts, packages/ddex/processor/src/usersPoller.ts
Poll sdk every 5 mins to keep user names in the DDEX db from becoming stale. Thoughts on this frequency?
Note: this doesn't update the JWT user's name in the cookie, which I figured is not worth updating. Unless you think otherwise @stereosteve. /whoami will potentially show a stale name until they logout and login again.
Note 2: this will also console log an error if the sdk can't find a user id in discovery, which will create some noise when using fake user data for local testing.
Ran server locally, ensured server polls, changed my user's name, ensured ddex persisted new name
=> DDEX users poller

packages/mobile/src/screens/audio-screen/ChallengeRewards.tsx, packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
Mobile crashes on rewards page for new users. This is because it's trying to format empty challenges. This just adds a check to handle empty cases.
Also, adding logic to remove token when a user only has pending challenges in cooldown. That should only show when rewards are claimable.
Tested on local clients against staging.
=> [C-4344][C-4352] Fix empty rewards mobile crashing

packages/discovery-provider/src/utils/web3_provider.py
The healthcheck will still return 200 if the chain is syncing, so we need to check the actual block number difference.
audius-dn1.tikilabs.com now functional despite chain still catching up.
=> Make indexer properly resort to using gateway if chain isn't caught up

packages/web/src/components/collections-table/CollectionsTable.tsx, packages/web/src/components/tracks-table/TracksTable.tsx, packages/web/src/pages/dashboard-page/components/ArtistDashboardTracksTab.tsx
Per design - For owners, we want to show the type of gating on the track. For fans, we want to show whether or not they have access.
unlocked album: no icons
locked album shows lock icon:
owner on artist dashboard sees gated type icons:
ditto for albums tab:
=> [PAY-2878] Fix tracks tables right icons

packages/common/src/store/effects.ts
Reward sagas tests were failing because `getContext` was undefined. This was because `common/src/store/effects.ts` was importing `~/services` which was causing a circular dependency. Using a more narrow import solved the issue
web-test passes
=> Fix web-test by resolving circular import

packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py
Fix so indexing doesn't skip this tx. Still need to debug why this field is missing in the metadata (I can see it in the _metadata in the healthz tx explorer) but this makes testing a fix easier.
deployed to a stage node, verified tx succeeded
=> fix ddex playlist release_date parsing

packages/web/src/components/track/LockedContentDetailsTile.module.css, packages/web/src/components/track/LockedContentDetailsTile.tsx
Needed to set a min-width for image, width on parent container, and `overflow: hidden` on grandparent container
Before:
After:
=> [PAY-2985] Fix squished art in purchase modal

dev-tools/compose/docker-compose.test.yml, packages/identity-service/src/routes/authentication.js, packages/identity-service/src/utils/otp.js, packages/identity-service/test/authenticationTest.js, packages/mobile/src/screens/sign-on-screen/screens/ConfirmEmailScreen.tsx, packages/web/src/pages/sign-in-page/ConfirmEmailPage.tsx
- Helps prevent OTP spam by ensuring no more than two otp emails can be send out every 10 minutes.
- Improves UI by visually disabling resend-link
- Fixes local dev for identity-service by updating docker envs for test config.
Added new test for this feature, and fleshed out a few other related to otp
=> [QA-1259] Restrict OTP spam

packages/mobile/src/screens/app-screen/AppScreen.tsx
Fixes issue weve seen in the past where screen transition animations sometimes don't work properly on android causing some pages, in this case the tip screen, to look blank.
=> [QA-1267] Fix blank android tip screen

packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
instead of just saying track, determine if playlist is a playlist or album and set that as the content tile
npm run web:stage and look for new tracks, playlists, and albums in your feed. Each of these now have the right text.
=> QA-1260: change content title to not say track

packages/web/src/components/tile/Tile.tsx, packages/web/src/pages/collection-page/components/desktop/CollectionPage.module.css
Redoing changes from #8406 (which were reverted in #8416)
Redone with much less impactful changes; puts the dog ear back inside the container (the way it was before I messed with it), removed any added wrappers, and just moved the `overflow:hidden` one layer deeper
web:stage 
Since these changes touch less, the testing needs are lower than the previous iterations
=> Fix dog ear pt 3

packages/web/src/components/collection/desktop/CollectionHeader.tsx, packages/web/src/components/tracks-table/TracksTable.tsx, packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
- Fix conditional rendering of artwork which caused shift of other elements. Artwork already implements a placeholder loading state
- Add skeletons to relevant content sections in the header
- Fix loading state for tracks table (wasn't ever showing loading)
*NOTE: Recommend reviewing with `Hide Whitespace Changes`*
https://www.loom.com/share/c3d8f9e220ec47e6bcec49296e2c686b
=> [PAY-2786] Clean up skeletons for collection page

packages/web/src/pages/upload-page/fields/AccessAndSaleMenuFields.tsx, packages/web/src/pages/upload-page/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx
- Update copy to say 'albums' instead of 'tracks' where appropriate
- Remove Hidden option for album uploads
looks good on local web
=> [PAY-2965, PAY-2968, PAY-2963] Album upload copy fixes; remove 'hidden' option

packages/discovery-provider/src/tasks/metadata.py, packages/web/src/components/tracks-table/TracksTable.tsx
- read `release_date` from playlist metadata (sent by ddex). EM changes done in https://github.com/AudiusProject/audius-protocol/pull/8368. after this is merged, ddex albums should display as created at the parsed release date.
- fix UI for tracks in a playlist/album. EM was parsing the `ddex_app` correctly but the UI was not checking the `ddex_app` field in this particular component.
- will test the release date after this is merged
- tested UI locally. verified there are no edit buttons displayed for tracks in a ddex playlist/album. verified all edit buttons displayed for non-ddex playlist/albums
ddex album:
=> fix ddex playlists UI

packages/mobile/src/components/audio/AudioPlayer.tsx, packages/web/src/common/store/pages/ai/lineups/tracks/sagas.ts
Fixes issue where short lineups load too quickly leading to situation where player index is lower than queue index, leading to a weird skip back to the first track. The change here is to ensure playerIndex is always greater than queueIndex before we skip. This makes sense because playerIndex should naturally always be equal to or one index ahead of queueIndex.
=> [QA-1251] Fix short lineup playback issues.

packages/mobile/src/components/core/Tag.tsx, packages/mobile/src/components/details-tile/DetailsStat.tsx, packages/mobile/src/components/details-tile/DetailsTile.tsx, packages/mobile/src/components/details-tile/DetailsTileMetadata.tsx, packages/mobile/src/components/details-tile/SecondaryStats.tsx, packages/mobile/src/components/offline-downloads/DownloadStatusIndicator.tsx, packages/mobile/src/harmony-native/components/Button/PlainButton/PlainButton.tsx
Fixes various aspects of details tile:
- Improves alignment of metadata
- Refactors metadata into it's own component
- Fixes line-height for metadata when mixing label + body variants
- Fixes square block at bottom of details tile
- Fixes margin below tile
- Fixes tag alignment and spacing
- Fixes play-count formatting
- Uses full text component rather than flex for stats
- Refactors reposts + favorites to use plain-button
- Fixes plain-button text-weight
=> [QA-1253] Improve details tile layout

packages/libs/src/services/creatorNode/CreatorNode.ts, packages/libs/src/utils/types.ts
SDK allows optional `placement_hosts` field, passes thru to mediorum.
Replaces: https://github.com/AudiusProject/audius-protocol/pull/7726
=> re-do placement_hosts field

packages/common/src/store/ui/mobile-overflow-menu/types.ts, packages/mobile/src/components/overflow-menu-drawer/OverflowMenuDrawer.tsx, packages/mobile/src/components/overflow-menu-drawer/TrackOverflowMenuDrawer.tsx, packages/mobile/src/components/track-list/TrackListItem.tsx
Adds "Purchase Track" option to overflow menu for track list items in a collection screen
before purchase:
https://github.com/AudiusProject/audius-protocol/assets/3893871/1c36914a-e3f8-404b-a9ca-7afda56f993c
purchased:
=> [PAY-2966] Add purchase track to mobile collection tracklist overflow

packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx, packages/web/src/pages/audio-rewards-page/RewardsTile.module.css
Small web mobile UI fixes:
* Remove margin so Claim All tile is the same size.
* Only show token gold when there's claimable tokens.
* Make ready to claim flex horizontally not vertically.
Tested with local client against stage.
=> [C-4384][C-4383] Small web mobile UI fixes

packages/common/src/services/audius-api-client/makeActivity.ts
Fixes an issue where tracks initially loaded in library or history would result in bad `stream_conditions` values and show the wrong gated content type.
This is a temporary hack fix until @rickyrombo returns to tackle PAY-2994
working on local web
=> [PAY-2995] Fix stream_conditions in saved and library fetch

packages/common/src/schemas/upload/uploadFormSchema.ts, packages/web/src/common/store/upload/sagas.ts, packages/web/src/pages/upload-page/fields/AccessAndSaleField.tsx, packages/web/src/pages/upload-page/fields/AccessAndSaleMenuFields.tsx, packages/web/src/pages/upload-page/fields/helpers.ts, packages/web/src/pages/upload-page/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseFields.tsx
Addresses 
- [PAY-2970] - this state is no longer possible to reach (since you now cant leave the premium modal with an invalid form)
- [PAY-2967] - it's required now, but prefilled to $1
- [PAY-2794] - My recent changes to parse out `albumTrackPrice` getting sent to the backend clobbered the value too early. I refactored to hold onto it before it gets removed
=> [PAY-2794] Fix several album track price issues

packages/web/src/components/search-users-modal/SearchUsersModal.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/FindAccountManagerPage.tsx
See title!
Locally against stage - tested both the managers search and the chat search (which doesn't use an exclusion list)
=> Filter yourself and current managers out of search results list in Accounts Managing You search [PAY-2833]

packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ClaimAllRewardsModal.tsx
Web + mobile web (woo harmony!)
Tested by mocking some local data. Will want to confirm this strategy on stage with a cooldown unlock.
=> [PAY-2945] Add claimable progress bar

packages/discovery-provider/src/utils/web3_provider.py
Python uses just `abs()` and not `math.abs()`
=> No math.abs function in python

packages/harmony/src/components/text-link/TextLink.tsx, packages/web/src/components/collection/mobile/CollectionHeader.tsx, packages/web/src/components/link/UserLink.tsx, packages/web/src/components/user-card/UserCard.tsx
Fixes issue where user-links textVariants are overridden by inner text variant='body' which was added to fix a specific use case. The fix is to roll that back and update the specfic use-case to have textVariant='body'
Also went ahead and updated harmony's text-link to not set tag='a' since that happens in the child component by default.
=> [QA-1276] Fix user-links

docs/.vscode/spellright.dict, docs/docs/learn/introduction/getting-started.mdx, docs/docs/reference/eth-contracts.mdx, docs/docs/reference/solana-programs.mdx, docs/sidebars.js
adding reference Ethereum Contracts and Solana Programs
- [Ethereum Contracts](https://57f16b01.docs-eaf.pages.dev/reference/eth-contracts)
- [Solana Programs](https://57f16b01.docs-eaf.pages.dev/reference/solana-programs)
=> [DOCS] - Reference Docs for Ethereum and Solana Contracts

packages/discovery-provider/ddl/pg_migrate.sh
No need for idempotent check in test mode when we're already checking md5 to avoid applying the same migration twice. Took a while to figure out but I made a migration that was not idempotent which broke a few notification tests because it made the migrations fail early, missing the trigger functions.
https://github.com/AudiusProject/audius-protocol/pull/8419/files#diff-1f036baf6a9ac4383d09184a9df22e8dc04bb02b88ad623e65bfc4599eb27b31
Ran `audius-compose test run "discovery-provider-notifications"` locally
=> Remove idempotent check in pg migrate test

dev-tools/compose/docker-compose.pedalboard.prod.yml
During audius-compose up solana and acdc relay both have a high chance of a flaky startup. This PR adds the correct dependencies to their docker compose entries as well as increases the timeout of their health checks so they're more stable when brought up.
`audius-compose down && audius-compose up`
=> stabilize relay startup

packages/mobile/src/components/challenge-rewards-drawer/ClaimAllRewardsDrawer.tsx, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ClaimAllRewardsModal.tsx
Screenshot with dummy data:
I didn't get a screen grab, but used this to claim 2 challenges worth 4 $AUDIO today. Only nit observation is that it went to 1/4 and then zoomed to 4/4 and finished. Fine for now.
=> [PAY-2946] Mobile progress bar for multiple claimed

packages/common/src/store/pages/audio-rewards/slice.ts, packages/mobile/src/components/track-list/TrackListItem.tsx, packages/mobile/src/screens/audio-screen/AudioScreen.tsx, packages/web/src/common/store/pages/audio-rewards/sagas.ts, packages/web/src/components/track/mobile/ConnectedPlaylistTile.tsx, packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx, packages/web/src/pages/audio-rewards-page/components/ExplainerTile.tsx, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ClaimAllRewardsModal.tsx
Previously, the cumulative claiming would be in a failure state as soon as one of the calls failed, while the other calls would still be in progress, making it seem to the user that everything failed.
Now, we save the failure state temporarily and wait until all claim attempts are resolved to finally show the failure state. This way, partial failures would only show in the UI after all claim attempts, the successful claims would update accordingly, and the user can rightfully click the claim all button again as no reward claiming is in progress.
Also, previously, we only updated disbursedChallenges for aggregate challenges. This PR updates it for all types of challenges as long as they are disbursed. This should fix the issue where the Claim All rewards modal still showed the "Ready to …
=> [PAY-2991] Fix optimistic cumulative claiming

docs/package-lock.json, docs/package.json
This upgrade bumps the Audius docs from version `3.1.1` to `3.3.2`
> note
There are no user facing changes in this update.
Noable improvements for each release update identified below 👇 
- version `3.2` [release notes](https://docusaurus.io/blog/releases/3.2)
- faster builds
- faster dev server
- MDX partials table-of-contents
- version `3.3` [release notes](https://docusaurus.io/blog/releases/3.3)
- prep for React 19
=> [DOCS] - Upgrade docusaurus to latest version 3.3.2

packages/mobile/src/components/challenge-rewards-drawer/ClaimAllRewardsDrawer.tsx, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ClaimAllRewardsModal.tsx
Slightly better UX because one challenge worth a lot won't show a progress bar
=> [PAY-3002] Make progress bars only show up with specifiers > 1

packages/libs/scripts/check-generated-types.sh
Jobs that fail `verify sdk types` would take 10 additional minutes to complete because they wait for input on `git diff .` and timeout, e.g. https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/56881/workflows/3459d239-89b5-480e-a575-f79ec94dce63/jobs/815260
[Integration test is failing](https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/56894/workflows/43278911-0261-4d65-bb25-369c53faeca3/jobs/815461/parallel-runs/0/steps/0-106) due to unrelated regression, confirmed that it only takes 30s to complete instead of 10m
=> Fail check-generated-types.sh faster with git --no-pager

packages/mobile/src/app/App.tsx
The docs say
```
/**
* Maximum duration of media that the player will attempt to buffer in seconds.
* Max buffer may not be lower than min buffer.
*
* Supported on Android only.
*
* @throws Will throw if max buffer is lower than min buffer.
* @default 50
*/
maxBuffer?: number;
```
But it turns out on android that if you set minBuffer and don't set maxBuffer, it looks like maxBuffer does not get set.
Physical android device
```
npm run mobile
npm run android:prod -- --device "xxx"
```
=> Fix android playback by setting default maxBuffer

docs/docs/node-operator/migration-guide.mdx, docs/docs/node-operator/setup/installation.mdx, docs/sidebars.js
- Split `audius-d` migration guide to a separate page.
- added numbers to headings in guides for readibility
- added call out for "upgrade in place" structure
- [Installation Guide Preview](https://1ad16ba4.docs-eaf.pages.dev/node-operator/setup/installation)
- [Migration Guide Preview](https://1ad16ba4.docs-eaf.pages.dev/node-operator/migration-guide)
=> [DOCS] - Audius Node Migration Guide Page

.changeset/breezy-avocados-sip.md, packages/libs/src/sdk/api/challenges/ChallengesApi.ts, packages/web/src/common/store/pages/audio-rewards/sagas.ts
The claim reward sdk changes swallowed the aao error codes. This PR brings them back and resurfaces them to the client.
Design-wise. I tried to not re-introduce the { result } | { error } type but it seemed the most sensible here. Thought about throwing the error code itself, but we have TS rules for only throwing Error types. I think what is done here is fine, but lmk if strong opinions about the design if you have them.
Local v stage
tested the happy path. claiming still works.
https://github.com/AudiusProject/audius-protocol/assets/9600175/7d5e7e47-e34d-4768-af99-8dd4784b6713
=> [PAY-3005] Bring back aao error emojis

packages/mobile/src/hooks/useNotificationNavigation.ts, packages/mobile/src/screens/notifications-screen/Notifications/TrackAddedToPurchasedAlbumNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/USDCPurchaseBuyerNotification.tsx, packages/mobile/src/screens/notifications-screen/Notifications/USDCPurchaseSellerNotification.tsx
Navigate to purchased content when pressing on USDC purchase notification.
https://github.com/AudiusProject/audius-protocol/assets/3893871/743a7978-bb1e-4a54-8567-7e5fb7a54e16
=> [PAY-2872] Mobile purchase notifications navigate to content

packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx
Forgot to check `hasAccess` as well.
=> [PAY-3021] Remove purchase track option after purchasing on mobile web

packages/mobile/src/notifications.ts
Fixes issue where new android installs/sign-ins do not receive remote notifications, since we were only calling `registerRemoteNotifications` for ios.
=> [QA-1289] Fix broken android notifications

packages/mobile/android/app/build.gradle
Fixes issue where clicking a notification on android does nothing. Turns out it's an undocumented issue related to firebase versioning: https://github.com/wix/react-native-notifications/issues/884#issuecomment-1386792132
Tested on android simulator
=> [QA-1254] Fix android notification linking

packages/discovery-provider/ddl/migrations/0070_fix_track_price_access.sql
This track was initially uploaded as stream-gated, but then later changed to download-gated: https://audius.co/DJSKT/dj-skt-pure-cold-shaq-rayes-pelota
We weren't updating the `TrackPriceHistory` row in the case where only `access` changed. Fix in this PR: https://github.com/AudiusProject/audius-protocol/pull/8498
This migration updates the `access` to `download` for tracks affected by this.
Tested query on stage DN 4. Also ran this query to make sure everything was good:
```
SELECT tp.track_id, t.owner_id
from track_price_history tp
JOIN tracks t ON t.track_id = tp.track_id
WHERE tp.access != 'stream' and tp.access != 'download';
```
=> Fix TrackPriceHistory access for broken tracks

packages/ddex/processor/src/publishRelease.ts, packages/ddex/processor/src/sources.ts, packages/libs/src/sdk/api/tracks/TracksApi.ts, packages/libs/src/sdk/api/tracks/types.ts
A follow up to https://github.com/AudiusProject/audius-protocol/commit/0371ee2573e74f565d337babb2d9d0fd2f6d70b4.
Former PR passed thru `placement_hosts` at a lower level, this PR does the same at the higher level tracks API.
Tested on staging and confirmed it correctly sets `placement_hosts` on the resulting mediorum upload.
It is still the case that the initial upload won't respect the `placement_hosts` preference and use the currently selected CN.  For that I think we'll have to change [_makeRequestV2](https://github.com/AudiusProject/audius-protocol/blob/main/packages/libs/src/services/creatorNode/CreatorNode.ts#L419) to use specified host list and fallback to a randomized host list if not specified.
=> Ddex placement hosts

packages/discovery-provider/src/queries/get_feed_es.py, packages/discovery-provider/src/queries/query_helpers.py, packages/discovery-provider/src/queries/search_es.py
We weren't processing gated access for albums before returning from feed. This led to client having no access data and failing to render the albums.
Removed the `content_type` flag from `_populate_gated_content_metadata` since it can be easily inferred from the structure of the entity.
Works on local stack. Feed returns access for albums where it didn't before
=> [PAY-3014] Fix feed not returning access for collections

packages/mobile/src/components/track-list/TrackListItem.tsx, packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx
Add check for isDeleted to not allow purchasing deleted tracks
web:stage with chrome & ios:stage
=> [PAY-3028] Fix able to purchase deleted tracks through mobile overflow menus

packages/identity-service/src/config.js, packages/identity-service/src/routes/twitter.js
- Fixes issue where twitter handle checks were failing since we were on the old 1.1 api. Migrated to 2.0.
- Switches between two endpoints to double our rate-limit capacity
I think there is a chance that doRequest doesnt reject on 429, so may need to think more about that
=> [QA-1281] Fix twitter reserved handle check

packages/web/src/components/tile/Tile.tsx, packages/web/src/pages/collection-page/components/desktop/CollectionPage.module.css
More tile changes put the dog ear above the tile container. Same concept as I tried to do before, but no longer with an empty parent container. This works fine since the dog ear is absolutely positioned. This also allows `overflow: hidden` to be set without any issues
Made sure to go through every instance of Tile
This is unused at the moment; I believe this came from the previous "track override" feature. Probably can delete
This is unused at the moment; this came from the previous "track override" feature. Probably can delete
=> [PAY-3018] Rework tile (pt 4) to fix collection page curved border

packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx
Mobile track owner actions now match the redesign and have share/edit as the primary
ios:stage
=> [PAY-3035] Fix mobile track owner actions not correct

packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/purchase.ts, packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/sale.ts
Realized that `payExtra` is `0.00` which is not null/undefined. Need to compare with the `0.00` string directly.
Not tested, test on stage.
=> Don't show pay extra in purchase/sale email v2

packages/mobile/src/components/summary-table/SummaryTable.tsx
Converts `View` to `Flex`.
Fixes the double-border issue that was showing when collapsed.
Included a fake summaryItem to test:
Normal case:
=> [PAY-3029] Convert mobile SummaryTable to Harmony

packages/mobile/src/components/details-tile/DetailsTile.tsx, packages/mobile/src/components/lineup/Lineup.tsx
Fixed:
- CollectionScreen now has plenty of bottom spacing
- CollectionScreen tile bottom has rounded borders now
- TrackScreen now has plenty of bottom spacing
ios:stage
=> [PAY-2978] Fix mobile tile spacing

packages/mobile/src/components/lineup-tile/CollectionTile.tsx
The tile thought there was no preview so it fails
working on local sim
=> [PAY-3042] Enable mobile feed tap to preview for collections

packages/web/src/components/table/components/TablePlayButton.tsx, packages/web/src/components/track/desktop/TrackListItem.tsx, packages/web/src/components/track/mobile/TrackListItem.tsx, packages/web/src/components/tracks-table/TracksTable.tsx
Small logic fix to not show green play buttons for owner case.
owner:
locked:
unlocked:
TrackListItem locked:
TrackListItem public:
=> [PAY-3041] Fix green play button in TracksTable

packages/identity-service/default-config.json
twitterBearerToken (introduced here https://github.com/AudiusProject/audius-protocol/pull/8509) does not have the correct value for a default and the config rightfully throws an error. This adds the correct default per the default_config.json (which we should remove anyways later) like all the other default values.
anything that uses `audius-compose test ...`
=> fix integration tests

packages/mobile/src/components/details-tile/DetailsTile.tsx, packages/mobile/src/components/details-tile/DetailsTileMetadata.tsx
local sim; link works and is hidden when it should be; wrapping works when mood, genre, and link all present
=> [PAY-3003] Add album backlink to track screen

dev-tools/compose/docker-compose.test.yml, packages/discovery-provider/integration_tests/tasks/test_get_feed_es.py, packages/discovery-provider/src/queries/get_feed_es.py
Fixes issue where albums with no tracks and albums with all hidden/deleted tracks appear on the feed.
Reintroduced and added new feed_es tests
=> [C-4277] Prevent empty albums in feed

mediorum/go.mod, mediorum/go.sum, mediorum/server/serve_image.go, mediorum/server/serve_image_test.go, mediorum/server/server.go
adds a LRU in memory cache for 1000 image files, sets `x-image-cache-hit` header will be `true` when cache hit.
=> mediorum: in memory image cache

packages/mobile/src/components/details-tile/DetailsTile.tsx
Fixes a bad merge issue that resulted in double tiles
ios:stage
=> Fix double access tiles

.circleci/config.yml, .circleci/src/@continue_config.yml, .circleci/src/commands/@docker-commands.yml, .circleci/src/jobs/@ddex-jobs.yml, .circleci/src/workflows/ddex-processor.yml, .circleci/src/workflows/ddex-stage.yml, .circleci/src/workflows/discovery.yml, .circleci/src/workflows/release.yml, dev-tools/compose/docker-compose.ddex.yml, dev-tools/compose/docker-compose.yml, packages/ddex/processor/Dockerfile, packages/ddex/processor/package.json, packages/ddex/processor/src/server.ts
=> ddex yaml time

packages/web/src/common/store/lineup/sagas.ts
Filter out *ALL* premium content when `USDC_PURCHASES` flag is disabled, not just tracks.
Currently we have another filter below this one that filters out specifically albums, but on the `PREMIUM_ALBUMS_ENABLED` flag.
Not tested..
=> Filter out all premium content on USDC_PURCHASES flag

packages/common/src/hooks/purchaseContent/useChallengeCooldownSchedule.ts, packages/common/src/store/pages/audio-rewards/types.ts, packages/common/src/utils/challenges.ts, packages/discovery-provider/integration_tests/queries/test_undisbursed_challenges.py, packages/discovery-provider/src/queries/get_undisbursed_challenges.py
Use the completed timestamp instead of the created timestamp to determine when a cooldown challenge reward is claimable.
Note that this change must first be deployed to the DNs before clients so that the `completed_at` field is returned to clients for use.
Fyi, The backend fix was in [this pr](https://github.com/AudiusProject/audius-protocol/pull/8419/files).
=> [C-4402] Use completed at for cooldown check

packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx, packages/mobile/src/components/lineup-tile/CollectionTile.tsx, packages/mobile/src/components/lineup-tile/LineupTile.tsx, packages/mobile/src/components/lineup-tile/LineupTileAccessStatus.tsx, packages/mobile/src/components/lineup-tile/LineupTileActionButtons.tsx, packages/mobile/src/components/lineup-tile/LineupTileStats.tsx, packages/mobile/src/components/lineup-tile/types.ts, packages/mobile/src/screens/chat-screen/ChatMessagePlaylist.tsx, packages/mobile/src/screens/chat-screen/ChatMessageTrack.tsx, packages/mobile/src/services/analytics.ts
Port over some more metrics that were added to web in #8262
The only real relevant changes to bring over were the newer and more granular modal sources that will tell us more about where the purchases are coming from. 
Premium album edits are not currently on the mobile app and purchase events are already being tracked.
Checked the redux `modalOpened` events to make sure they were passing along the correct source
=> [PAY-2767] Premium albums mobile analytics

packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx, packages/mobile/src/components/lineup/Lineup.tsx, packages/web/src/common/store/lineup/sagas.ts
- Respect feature flags and don't show purchase buttons
- Resolve promise on `getFeatureEnabled` in feed sagas
- Correctly filters out premium content from feed instead of allowing it through
Extraneous:
- Fixes gap between feed tiles
- Note that this effectively reverts https://github.com/AudiusProject/audius-protocol/pull/8511 so we'll need another solution for the scroll padding issues there
working locally with flags off and on
=> [PAY-3049, QA-1307] filter premium albums from feed if flag off; fix feed spacing

packages/discovery-provider/ddl/migrations/0071_add_allowed_api_keys.sql, packages/discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py, packages/discovery-provider/src/models/tracks/track.py, packages/discovery-provider/src/tasks/entity_manager/entities/track.py, packages/discovery-provider/src/tasks/metadata.py
DB migration to add allowed_api_keys column and enable EntityManager to index allowed api keys. Null means all API keys are allowed.
Updated integration test.
=> [PROTO-1833] Index allowed api keys

packages/discovery-provider/src/api/v1/tracks.py
Track rows with `allowed_api_keys` require a matching api_key in the stream request. If no api_key is passed in, only tracks without `allowed_api_keys` will be streamable which is the default. 
Tested against sandbox. Confirmed no api_key, wrong api_key will not stream on a track with `allowed_api_keys`.
=> [PROTO-1835] Enforce allowed api keys for stream

packages/common/src/store/pages/collection/actions.ts, packages/web/src/common/store/pages/collection/sagas.js, packages/web/src/components/notification/Notification/TrackAddedToPurchasedAlbumNotification.tsx, packages/web/src/pages/collection-page/CollectionPageProvider.tsx
Add a `forceRefetch` flag and use it from the `TrackAddedToPurchasedAlbum` notification to make sure we've fetched the latest lineup after clicking on the notification tile.
Mobile doesn't have this bug.
Ran on local - had 2 sessions open -> added a track to an album that the other user had bought, confirmed they had latest tracklist. Also tried after loading in purchaser account from feed so the album was already loaded from that endpoint.
=> [PAY-2873] Add forceRefetch flag to collection fetching on web

packages/web/src/pages/upload-page/fields/StemsAndDownloadsMenuFields.tsx
Caused a bug where user could not untoggle full track download. No longer relevant since we provide lossless always.
=> Fix lossless validation

packages/ddex/processor/cli.ts, packages/ddex/processor/src/parseDelivery.ts, packages/ddex/processor/src/server.ts
https://linear.app/audius/issue/PROTO-1771/reprocess-prior-deliveries-on-new-artist-match
=> ddex: Rescan past xml after user upsert

mediorum/server/repair.go, mediorum/server/replicate.go
- Clean up in 50% of the tasks so we can settle the network down a bit.
- Increase boundary back up to 200GB from 100GB because some nodes seem to be falsely reporting
- Decrease over-replication factor to R+1 instead of R+2 to clean up more
Config changes...
=> Increase replication cleanup in mediorum

packages/web/src/components/usdc-purchase-details-modal/components/PurchaseModalContent.tsx, packages/web/src/components/usdc-purchase-details-modal/components/SaleModalContent.tsx
Need to close the details modal when the `UserLink` is clicked on web.
=> Close purchase/sale details modal on user click

packages/mobile/src/components/details-tile/DetailsTile.tsx, packages/web/src/components/collection/desktop/CollectionActionButtons.tsx, packages/web/src/components/collection/mobile/CollectionHeader.tsx
Show only the play button for collections if the user has access to _any_ of the collection contents.
Confirmed smart collection still works on web
Confirmed play/preview behavior is correct.
owner on track:
owner on album:
non-owner on album
=> [PAY-3045] Show play button if user has access to any of collection's contents

packages/discovery-provider/ddl/functions/handle_save.sql
Purchasing an album automatically favorites the album itself and every track within it. This causes a cascade of favorite notifications for the artist. In each of the below cases, the artist or reposter will receive only one notification per purchased item, whether it's a track or an album.
- Track has been purchased by the `favorited_by_user`
- An album containing the track has been purchased by the `favorited_by_user`
- An album containing the track has been purchased
- This means that the reposter will still receive a notification for the album or track that was favorited, but in the case where an album was purchased, we won't send one for every track therein
tested several cases on local stack:
- purchased album containing tracks
- purchased tracks separately
- saved public album
- …
=> [PAY-3024] Skip onFavorite notifications for purchased content

packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/purchase.ts, packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/sale.ts
Fixes a random `null` showing up in these emails.
Not tested - hard to test locally
=> [QA-1313] Fix purchase/sale email random null

packages/discovery-provider/integration_tests/notifications/test_manager_mode_notifs.py
Fix test that would flake if the current timestamp ended in 0 due to [Postgres truncating trailing 0s when converting timestamp to string](https://stackoverflow.com/questions/56792490/postgres-truncates-trailing-zeros-for-timestamps)
=> [Discovery] Fix flaky test

packages/web/src/common/store/pages/collection/lineups/sagas.js
The bug occurred because because, on collection creation (not after refreshing the page, which was fine) `time` was referring to the track duration and then would take that number as the timestamp for the date added to collection.
https://github.com/AudiusProject/audius-protocol/assets/9600175/cd593fab-5d54-4510-88ab-e737fe651ebd
=> [QA-1016] Fix date added

packages/web/src/components/collection/desktop/CollectionHeader.tsx
Dont show the section when no user id i.e. in smart collection pages.
=> [QA-1319] Remove empty By on collection page

packages/web/src/components/nav/desktop/AccountDetails.tsx
Mock uses small spacing (8px) for the gap. I had set them to large!
N/A
=> Fix spacing in AccountDetails

packages/discovery-provider/src/app.py
makes interval for plays more configurable and defaults to 30s to test discovery plays on stage
=> PROTO-1845: add as env var and default to 30

packages/discovery-provider/src/tasks/calculate_trending_challenges.py, packages/discovery-provider/src/tasks/entity_manager/utils.py
Trending rewards has been trying to get the block timestamp of the last indexed block however the block it gets from redis does not subtract the final poa block. This results in a block not found when attempting to index the latest trending rewards.
```
web3.exceptions.BlockNotFound: Block with id: '0x41daca0' not found.
```
This is block 68885728 which is way too far for acdc. ACDC at this time is at roughly 39871415. Subtracting the final poa block (32269859) yields a more realistic result 36615869.
This logic here is why we need to do this
```
next_block_number = latest_database_block.number - (final_poa_block or 0) + 1
try:
next_block_immutable = web3.eth.get_block(next_block_number)
next_block: BlockData = cast(BlockData, dict(next_block_immutable))
next_block["number"] = …
```
=> PROTO-1844: fix poa block for trending rewards

packages/web/src/common/store/cache/users/sagas.ts
Accidentally used a non-optional Id parse when converting this to SDK, which results in an error while attempting to fetch the profile while logged out.
Ran locally against staging
=> fix an optional Id parse that breaks when logged out

packages/mobile/src/components/audio/AudioPlayer.tsx
previousPlayerBehavior was undefined when playerBehavior was null, which triggers excessive calls to the below useAsync hook.
on device
=> Fix first track in lineup playback issue

packages/mobile/src/screens/audio-screen/AudioScreen.tsx, packages/mobile/src/screens/audio-screen/Tier.tsx
Adds missing tier info to mobile rewards page
=> [QA-1226] Add missing tier info

packages/mobile/src/components/audio/GoogleCast.tsx, packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx
Chromecast support was broken yet again due to changes to the way urls are constructed (api block track related?).
In any event, the current approach is super error prone, so utilize the content url directly from RNTP.
Fix a few other UX issues:
- Add buffering state for chromecast
- Don't move progress bar when cast is loading
- Render button when no devices found
- Handle stopping cast elegantly
local device vs. google home
=> Fix chromecast support, again

packages/embed/src/components/collection/CollectionPlayerCard.jsx, packages/embed/src/components/collection/CollectionPlayerContainer.jsx, packages/embed/src/components/pausedpopover/ListenOnAudiusCTA.jsx, packages/embed/src/components/pausedpopover/PrimaryLabel.jsx, packages/embed/src/components/track/TrackPlayerCard.jsx, packages/embed/src/components/track/TrackPlayerCompact.jsx, packages/embed/src/components/track/TrackPlayerContainer.jsx, packages/embed/src/components/track/TrackPlayerTiny.jsx
Add null-check for `streamConditions` on embed player (they are all js)
Local web
track:
album:
=> [QA-1335] Fix embed for non-premium tracks

packages/discovery-provider/plugins/notifications/src/__tests__/__snapshots__/emailRender.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/addTrackToPlaylist.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/announcement.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/challengeReward.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/cosign.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/create.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/follow.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/milestone.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/multipleMappings.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/reaction.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/remix.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/repost.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/repostOfRepost.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/save.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/saveOfRepost.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/supporterRankUp.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/supportingRankUp.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/tastemaker.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/tip.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/trendingPlaylist.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/trendingTrack.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/trendingUnderground.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/usdcPurchaseBuyer.test.ts.snap, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/usdcPurchaseSeller.test.ts.snap, packages/discovery-provider/plugins/notifications/src/email/notifications/components/BodyStyles.tsx, packages/discovery-provider/plugins/notifications/src/email/notifications/renderEmail.ts, packages/discovery-provider/plugins/notifications/src/email/notifications/sendEmail.ts, packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/create.ts
Notification emails look wonky because:
* Storage V2 stores images in a different URL. We can let the selected content node handle rendezvous.
* Responsive mobile Safari / Apple Mail changes the layout. Removing this `text-align` fixes. 
Ran with stage DN1. Confirmed layout looks good on web and mobile Chrome / Safari.
=> [C-4453] Fix notification email image and layout

.circleci/scripts/circleci-startup-script.sh
CircleCI is deprecating the original self-hosted runner setup in favor of a (hopefully) more simplified system.
Created circleci-runner-test instance and ensured it could successfully complete a CI job.
=> [PROTO-1850] Upgrade to circleci machine runner

packages/discovery-provider/plugins/pedalboard/apps/solana-relay/.eslintrc.js, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/config.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/index.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/middleware/errorHandler.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/middleware/locals.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/middleware/logging.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/middleware/signerRecovery.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/redis.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/cache.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/feePayer.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/listen.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/trackListenInstructions.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.test.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/attachLocationData.test.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/attachLocationData.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/relay.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/utils/connections.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/utils/delay.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/utils/ipData.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/utils/sortKeys.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/utils/transaction.ts
Solana relay logs would log `[Object object]` on failures because the error handling middleware neglected to have the fourth parameter. Annoyingly, when I added the fourth (unused) parameter, eslint was complaining (even with an `_`). I realized we were using a different eslint config than client, so I changed that. Which cascaded to a bunch of formatting changes (sorry).
I'll annotate the differences to help with review
=> Fix solana-relay logging, fix eslint config

mediorum/Dockerfile
Copy libkeyfinder dep to the final build stage in the prod dockerfile. currently the keyfinder is not working on stage bc this dep is missing.
(doesn't affect upload success at all)
built image but haven't been able to run it without the env configs. pretty sure this should fix it though
=> Fix prod mediorum dockerfile to have keyfinder dependency

.circleci/config.yml
Prior to this change, we were running discovery et. al on every main commit. This is just a copy/paste of the `trigger-relevant-workflows` filters so that we only run relevant things on main.
Goal here is to reduce the CI usage a bit.
=> Make main trigger the same relevant workflows as PRs

mediorum/Dockerfile
was still missing dependencies in the final build stage, so /bin/analyze-key was erroring. moved the /bin/analyze-key compilation to the final stage
built and tested this on stage, verified it works
=> fix libkeyfinder dependencies again

.circleci/src/jobs/@integration-jobs.yml
Playwright tests have been flaky and negatively impacted the reliability of our integration test. This PR will prevent errors from failing the workflow until the flakiness is resolved.
CI
=> Ignore playwright test failures until flakiness is resolved

packages/mobile/src/components/details-tile/DetailsTile.tsx
Noticed today on mobile that for a premium collection containing both premium and public tracks, we were showing both the play and preview buttons. This PR fixes that case - we should only show the play button if the user has access to _any_ of the containing tracks.
This is another +1 for splitting out the track vs collection `DetailsTile` components on mobile. The bug doesn't exist on web because they are split on web.
own album
album containing both premium + public tracks
unpurchased premium album 
own track
public track
premium track
=> Don't show preview for mobile mixed albums

packages/discovery-provider/ddl/migrations/0075_fix_trending_poa_block.sql, packages/discovery-provider/src/tasks/calculate_trending_challenges.py
Follow up: https://github.com/AudiusProject/audius-protocol/pull/8626
This fixed my previous bug but led to ACDC block being dispatched into the `user_challenges`. 
Ran on sandbox and confirmed undisbursed shows trending results
https://isaac.sandbox.audius.co/v1/challenges/undisbursed?completed_blocknumber=69663399
=> Fix trending POA Block

packages/web/bundlesize.prod.config.json, packages/web/bundlesize.stage.config.json
Bumped the max chunk size up to 60kb. This is an arbitrary max size that's really just to catch when libs is imported and the ssr bundle is too big
=> Update maxSize for bundle size check

docs/src/css/custom.css
Correct Admonition link text colors
| mode       | before                                                                                                                | after                                                                                                                |
| ---------- | --------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------- |
| light mode | ![before-light](https://github.com/AudiusProject/audius-protocol/assets/1404219/238dd08c-c467-4c02-8374-1a93c5248b31) | ![after-light](https://github.com/AudiusProject/audius-protocol/assets/1404219/bfa1fbf7-4e13-4453-9990-9b517b4cd867) |
| …
=> admonition css link color fixes

packages/discovery-provider/src/api/v1/playlists.py, packages/discovery-provider/src/queries/queries.py, packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py
I swear I tested this, must have done a change and not re-attempted
=> Fix purchasing albums w/ SDK

packages/identity-service/src/routes/user.js
Recently added userBouncer API key on prod and noticed email deliverability still looked off because of this... isEmailDeliverable should check if the status is `deliverable` instead.
Ran on staging and `isEmailDeliverable` looks correct now.
=> Flip email deliverable boolean

packages/discovery-provider/src/queries/get_support_for_user.py
This is probably a two parter. This PR filters the response formatter to not include users that don't exist (or have a handle). This will fix the rendering error and the endpoint that Reed and Randy discovered.
Second part would be to migrate bad user ids in the aggregate user tips table to their good ones and fix whatever indexing step is putting these in there.
Running on sandbox.
https://alec.sandbox.audius.co/v1/full/users/lzl4w/supporting?limit=500&offset=0&app_name=audius-client
=> QA-1347: filter query result response formatter on only users that were found

packages/discovery-provider/plugins/verified-uploads/src/handlers/tracks.js
We used to use this utility function to block old notifications that get retriggered by PG but it's actually unused at the moment. This will stop old uploads that have matching created_at and updated_at fields from showing up in the channel.
As for why they get retriggered not sure yet. Maybe a bug with indexing that isn't changing the "updated_at" field correctly or a pg trigger on some other event. This will at least make the channel correct.
Update: I believe it was this PR that triggered the old notifs because it modifies the tracks table, doesn't update "updated_at", then the bot sees that the dates for "created_at" and "updated_at" are the same. Since this guard wasn't in place it then notified the channel. 
https://github.com/AudiusProject/audius-protocol/commit/ddaa1b35950c92a2d3a1 …
=> ONC: add check for old uploads

packages/discovery-provider/integration_tests/queries/test_get_tracks.py, packages/discovery-provider/src/api/v1/access_helpers.py, packages/discovery-provider/src/queries/get_managed_users.py, packages/discovery-provider/src/queries/get_tracks.py
This updates the `get_tracks` query to include unlisted tracks when `current_user_id == user_id` and the current authenticated user is either the owner or an active manager of the owner.
fixes PAY-3071
fixes PAY-3072
Updated integration tests to verify correct behavior.
=> [PAY-3071][PAY-3072] Fix track listing in manager mode

mediorum/main.go
go will default this to an empty array with a single empty string element
=> correct default discovery listens behavior

packages/libs/src/services/solana/SolanaWeb3Manager.ts
The previous wAUDIO balance fetching was causing failures for user @jbtest1_ on staging as the associated wallet was a root wallet that didn't have an AUDIO token account. This change allows the Solana address passed into the method to be either a token account or a root wallet, and get the balance from either.
The user @jbtest1_ no longer encounters a balance fetching error when running client locally against stage
=> [PAY-3084] Fix wAUDIO balance fetching

packages/web/src/components/search-bar/ConnectedSearchBar.jsx, packages/web/src/components/search/SearchBarV2.jsx
Update the new search bar to detect if the user is viewing the search page and search after input debounce
=> [C-4360] Update SearchBarV2 to search on input

packages/web/src/components/menu/Menu.tsx, packages/web/src/components/table/components/OverflowMenuButton.tsx
Fixes issue where multiple popovers can appear on tracks table because clicking another popover overflow menu does not dismiss any active ones because of a `stopPropogation` which is needed to prevent the track from playing. The solution here is to dismiss the popup on mouse leave, which is actually much nicer
=> [QA-1287] Fix multiple popovers on tracks table

packages/web/src/components/lineup/LineupProvider.tsx, packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx, packages/web/src/pages/search-page-v2/SearchResults.tsx
Small updates to add a grid and list layout for the track tiles that defaults to the grid layout when viewing all search results
=> [C-4361] Add grid and list layouts for new search track view

packages/discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py
Add a test to ensure `playlist_id` is immutable and cannot be changed at the protocol level.
We have a similar test for `track_id` [here](https://github.com/AudiusProject/audius-protocol/blob/6a9274775f2d99932306cdff835e1473c2e40ad5/packages/discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py#L670).
Test passes locally
=> Add test to ensure updating playlist_id fails

packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
This works to get the text to be clickable and seems to be a pattern we use elsewhere.
=> [PAY-3085] Move payout wallet radio input to labeled

packages/discovery-provider/src/queries/get_extended_purchase_gate.py
there weren't defaults set for these fields if they don't exist which causes python to raise an error
testing on dn5 by execing into container
=> on call: fix search on stage

packages/web/src/components/upload/Dropzone.tsx
Not sure how exactly this got introduced, but this fixes it
=> Fix icon cloud container on drop zone

packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ClaimAllRewardsModal.tsx
Switches from using ModalDrawer to Modal and manually creating a header, passes in the onOpen and onClose events as it was previously implemented.
=> QA-1355: add exit button to web rewards modal

packages/harmony/src/foundations/color/primitive.ts
To be used in `MusicBadge` components. Don't want to keep hardcoding these. Got approval from design.
=> Add trendingBlue and aiGreen harmony colors

packages/web/src/common/store/player/sagas.ts, packages/web/src/components/collectibles/components/CollectiblesPage.tsx, packages/web/src/components/nav/desktop/PlaylistLibrary/useAddAudioNftPlaylistToLibrary.ts, packages/web/src/pages/collectibles-playlist-page/CollectiblesPlaylistPageProvider.tsx
Fixes issue with audio-nfts playlist not loading, likely due to updates to fetch-nft. The main fix is including "videoUrl" in many places, as often the audio-nfts are videos, which now only set videoUrl
=> [QA-1361] Fix audio-nfts playlist

packages/mobile/src/services/sdk/auth.ts
Fixes issue where tip reactions where unresponsive, due to our migration from identity reactions to discovery. This migration calls "signTransaction", which just wasn't implemented on mobile.
=> [QA-1288] Fix tip reactions on mobile

docs/docs/node-operator/setup/installation.mdx
reference docs for `audius-ctl` status command
[Preview](https://7979ab1f.docs-eaf.pages.dev/node-operator/setup/installation#status-command)
=> [DOCS] - audius-ctl status command

packages/mobile/src/screens/settings-screen/AccountSettingsScreen.tsx
Been broken a while, and best to just remove the feature until we fix it.
=> Temporarily remove mobile account verification

packages/common/src/models/Collection.ts, packages/common/src/utils/formatUtil.ts, packages/mobile/src/components/collection-list/CollectionCard.tsx, packages/web/src/components/collection/CollectionCard.tsx, packages/web/src/components/track/GiantTrackTile.tsx, packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
* Add `is_scheduled_release` to api marshalling
* `formatReleaseDate` util fn according to these specs:
If the release is within the next week, it will display the week name (e.g., "Releases Friday @ 12 AM").
For dates further out, it will display the full date (e.g., "Releases 5/22/24 @ 12 AM").
* Consume that fn in `CollectionCard` + "releases" badges on both web and mobile
* Bonus jsdocs
* Bonus convert from moment to dayjs
=> [C-4441][C-4503] Release date formatting + add date to CollectionCard

packages/common/src/models/Track.ts, packages/common/src/schemas/metadata.ts, packages/common/src/schemas/upload/uploadFormSchema.ts, packages/discovery-provider/ddl/migrations/0077_add_audio_analysis_columns.sql, packages/discovery-provider/integration_tests/tasks/entity_manager/test_utils.py, packages/discovery-provider/plugins/notifications/src/types/dn.ts, packages/discovery-provider/plugins/pedalboard/packages/storage/src/index.ts, packages/discovery-provider/src/api/v1/models/tracks.py, packages/discovery-provider/src/models/tracks/track.py, packages/discovery-provider/src/schemas/track_schema.json, packages/discovery-provider/src/tasks/metadata.py, packages/es-indexer/src/types/db.ts, packages/libs/src/api/Track.ts, packages/libs/src/sdk/api/tracks/types.ts, packages/libs/src/services/schemaValidator/schemas/trackSchema.json, packages/libs/src/utils/types.ts, packages/sql-ts/res/discovery-node.ts
Add key and bpm to discovery track metadata. EM will now persist key/bpm if it is included in the track metadata sent in the tx.
=> add key + bpm fields to discovery track metadata

packages/common/src/hooks/useCoinflowAdapter.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/relay.ts, packages/web/src/components/coinflow-onramp-modal/CoinflowOnrampModal.tsx, scripts/preinstall.sh
❗ _**Attention Reviewers:** It might be easier to review commit by commit_
Coinflow purchases via SDK failed due to bugs with how the Coinflow modal and adapter handle the VersionedTransaction, as well as how relay handles the Coinflow transaction. These bugs didn't affect non-Coinflow purchases.
The bugs:
- The new SDK uses `VersionedTransaction`, but when deserializing we were assuming the transaction was the legacy `Transaction` type in the `CoinflowOnrampModal`
- On relay, we were modifying the purchase transaction after the client had already signed it with the user's root wallet, which makes the signature invalid
- This was an oversight during the discussion around adding geo, I forgot that the client needs to sign the Coinflow transactions as Coinflow doesn't know how to put USDC …
=> Fix Coinflow purchases via SDK

.github/workflows/publish-packages.yml, packages/sp-actions/README.md, packages/sp-actions/claim.js, packages/sp-actions/package.json, scripts/publish-packages.sh
Since audius-docker-compose is being deprecated, we need a sensible place to put some of the utilities that node operators might still find useful. Since this utility relies on the sdk, it can't be easily incorporated into audius-ctl, so a standalone package will suffice.
Installed package locally and ensured command can be run. Relevant business logic has not been modified.
=> [PROTO-1780] Import rewards claim utility from audius-docker-compose

packages/ddex/webapp/client/src/pages/Releases/Releases.tsx, packages/web/src/components/edit-track/EditTrackForm.tsx, packages/web/src/components/edit/fields/AccessAndSaleField.tsx, packages/web/src/components/edit/fields/StemsAndDownloadsField.tsx, packages/web/src/components/edit/fields/download-availability/DownloadAvailability.tsx
Turns out the rules had all been migrated since we were using the new fields in the old form already. However, we were relying on boundary layer components like `AccessAndSaleTriggerLegacy` to pass the initial values through.
- Fixes passing of `initialValues` and `isUpload` through to the contextual menu field components
- Fix some copy
Confirmed we didn't break existing rules for track and collection edit
=> [C-4473] Enable edit rules in new edit form

mediorum/server/audio_analysis.go, mediorum/server/db.go
Checked the analysis logs, found some bugs. Most notably was accidentally using `upload.Mirrors` instead of `upload.TranscodeMirrors` in the `findMissedAnalysisJobs` function 🤦‍♀️ so there were many "file not found on node" errors bc the audio analysis uses the transcoded audio, not the original audio.
Another major issue I found was the timeout in `findMissedAnalysisJobs` is sometimes overriding real analysis results that took only a few seconds to complete... added a log to see if perhaps this is because it's finding a large number of in-progress audio analyses and the query is taking so long the data is becoming stale, or if this is because crudr is slow to synchronize the upload state between nodes. I hope it's not the latter... that would be much more annoying to work around.
Also …
=> Fix mediorum audio analysis bugs, add better logs

packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx, packages/web/src/pages/pay-and-earn-page/components/PayoutWalletCard.tsx, packages/web/src/services/solana/solana.ts
Wait for payout wallet retrieval from RPC before sending to ACDC, and show toast/spinner error if failed to load
Tested locally
=> Poll for Payout Wallet Owner

protocol-dashboard/src/components/TotalApiCallsChart/TotalApiCallsChart.tsx
variable was not initialized and resulted in a blank analytics page
`npm run start:prod`
=> initialize topNumber var

packages/web/src/components/track/GiantTrackTile.tsx
Small update to add the text links for the genre and mood labels on track tiles to route to the search page
=> Add text link for track tile genre and mood info
