AudiusProject/apps

- packages/web/src/app/AppProviders.tsx
- packages/web/src/app/SvgGradientProvider.tsx
Add hidden dom SvgGradient elements so that they can be used in our other svgs that require them as fills
> Add SvgGradientProvider

- packages/mobile/src/components/offline-downloads/OfflineStatusRow.tsx
- packages/mobile/src/screens/collection-screen/CollectionDownloadStatusRow.tsx
- packages/mobile/src/screens/collection-screen/TrackDownloadStatusRow.tsx
[PAY-2977] - Offline for tracks looks like this now:
[PAY-2986] - Don't show offline toggle for things you dont have stream access too
android:stage
> [PAY-2977] Fix offline mobile issues

- packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx
Wrap purchase modal open in authed callback
web:stage
> [PAY-3000] Don't open purchase modal for un-authed users

- packages/discovery-provider/plugins/notifications/src/__tests__/mappings/reaction.test.ts
- packages/discovery-provider/plugins/notifications/src/utils/populateDB.ts
slot no longer exists, tests were failing on insert of mock test data
audius-compose test "discovery-provider-notifications"
> fix notifs tests

- packages/web/src/components/collection/CollectionCard.tsx
- packages/web/src/components/lineup/CardLineup.module.css
- packages/web/src/components/lineup/CardLineup.tsx
- packages/web/src/pages/search-page/components/desktop/SearchPageContent.jsx
- packages/web/src/pages/search-page/components/desktop/SearchPageContent.module.css
- Fixes issue with card height differences due to line-height, which was causing background color issues.
- Improves search results page on mobile and web to lay out more appropriately
- Adds hidden cards to end of mobile lineup to improve spacing
> [PAY-2982] Address collection card fixes

- packages/discovery-provider/ddl/migrations/0067_tip_reactions_drop_old_columns.sql
this took down stage nodes because block 1 doesn't exist in the db
> allow null blocks in reactions table

- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseSeller.ts
Update subject depending on `contentType`
Not tested :(
> [PAY-3009] Fix seller email notification subject

- packages/web/src/components/table/components/TablePlayButton.tsx
- packages/web/src/components/track/desktop/TrackListItem.tsx
- packages/web/src/components/tracks-table/TracksTable.tsx
web:stage desktop web looks as expected
> [PAY-2998] Use green play buttons in lineup tracklists

- packages/discovery-provider/Dockerfile.prod
> bump pg version

- packages/mobile/src/app/App.tsx
- packages/mobile/src/components/audio/AudioPlayer.tsx
> Player fixes

- packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/purchase.ts
- packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/sale.ts
> [PAY-3025] Remove pay extra line from emails if no pay extra

- packages/discovery-provider/src/models/tracks/track_price_history.py
- packages/discovery-provider/src/tasks/entity_manager/entities/track.py
Respect changes to `access` on TrackPriceHistory
unit tests
> Fix access changes

- packages/mobile/src/components/details-tile/DetailsTile.tsx
- packages/mobile/src/components/details-tile/DetailsTileHasAccess.tsx
- packages/mobile/src/components/details-tile/DetailsTilePremiumAccess.tsx
- packages/mobile/src/components/locked-content-drawer/LockedContentDrawer.tsx
Replace all instances I could find using "this track"
ios:stage
> [PAY-3012] Fix copy for prem albums

- packages/discovery-provider/src/challenges/challenges.dev.json
- packages/discovery-provider/src/challenges/challenges.json
- packages/discovery-provider/src/challenges/challenges.stage.json
> [C-4294] Add prod rewards cooldown

- packages/mobile/src/components/drawers/RemoveDownloadedCollectionDrawer.tsx
> [PAY-3039] Fix copy for removing offline download albums

- packages/mobile/src/hooks/useNotificationNavigation.ts
- packages/mobile/src/screens/notifications-screen/Notifications/TrackAddedToPurchasedAlbumNotification.tsx
To match with existing patterns.
> Use useNotificationNavigation in TrackAddedToPurchasedAlbum noti 

- packages/discovery-provider/plugins/pedalboard/apps/crm/src/index.ts
> Fix CRM log message

- packages/mobile/src/components/add-to-collection-drawer/AddToCollectionDrawer.tsx
- packages/mobile/src/components/collection-list/AddCollectionCard.tsx
- packages/mobile/src/components/collection-list/CollectionList.tsx
- packages/mobile/src/screens/collection-screen/CollectionDownloadStatusRow.tsx
- packages/mobile/src/screens/favorites-screen/AlbumsTab.tsx
- packages/mobile/src/screens/favorites-screen/PlaylistsTab.tsx
- packages/mobile/src/screens/profile-screen/ProfileTabs/PlaylistsTab.tsx
Adds "create album" card in mobile, since there is no other way to create an album on mobile.
Also improves performance by memoizing collection cards.
> [C-4380] Add create album card

- packages/web/src/components/track/GiantTrackTile.module.css
- packages/web/src/components/track/GiantTrackTile.tsx
Fix the track page dog ear. I didn't catch this bug when testing #8510 since I needed to expand my window size to see it. 
The giant track tile was centering via `margin: 0 auto` but this doesn't work if the dog ear is absolutely positioned. So I instead added a flex wrapper around the tile
> [PAY-3047] Fix track page dog ear

- packages/common/src/store/cache/users/utils.ts
- packages/web/src/components/card-legacy/desktop/UserArtCard.tsx
Dont need to typecast now that feed_es coercing correctly now
> [C-2538] Remove follower_count typecast

- packages/web/src/components/collection/desktop/CollectionActionButtons.tsx
- packages/web/src/components/collection/mobile/CollectionHeader.tsx
- packages/web/src/pages/collection-page/CollectionPageProvider.tsx
- packages/web/src/pages/track-page/TrackPageProvider.tsx
- Don't show preview button on owned collections
- Fix play/pause state for preview
working on local web, mobile web, and simulator
> [PAY-3046] Preview button fixes

- packages/discovery-provider/src/conftest.py
- packages/discovery-provider/src/queries/get_feed.py
- packages/discovery-provider/src/queries/get_feed_es.py
- packages/discovery-provider/src/queries/get_health.py
- packages/discovery-provider/src/queries/get_health_unit_test.py
- packages/discovery-provider/src/queries/get_top_playlists.py
- packages/discovery-provider/src/queries/get_top_playlists_es.py
- packages/discovery-provider/src/queries/health_check.py
- packages/discovery-provider/src/queries/search_es.py
- packages/discovery-provider/src/utils/elasticdsl.py
Make the discovery-provider health depend on the elasticsearch health
Tested health_check endpoint on local stack with es container up and down. Added unittest.
> [PROTO-1690] Elasticsearch cluster health check

- packages/common/src/services/audius-api-client/AudiusAPIClient.ts
- packages/common/src/services/env.ts
- packages/mobile/src/env/env.dev.ts
- packages/mobile/src/env/env.prod.ts
- packages/mobile/src/env/env.stage.ts
- packages/mobile/src/services/audius-api-client/apiClient.ts
- packages/mobile/src/services/sdk/audius-sdk.ts
- packages/web/src/services/audius-api-client/apiClient.ts
- packages/web/src/services/audius-sdk/audiusSdk.ts
- packages/web/src/services/env/env.dev.ts
- packages/web/src/services/env/env.prod.ts
- packages/web/src/services/env/env.stage.ts
- packages/web/src/ssr/sdk.ts
Add app_name to all requests API client requests (and update sdk to use the same env var)
> [PROTO-1832] Add app name along with stream requests

- packages/discovery-provider/integration_tests/tasks/entity_manager/test_utils.py
> Fix allowed api key test

- packages/common/src/services/audius-api-client/AudiusAPIClient.ts
- packages/common/src/services/env.ts
- packages/libs/src/sdk/middleware/addAppInfoMiddleware.ts
- packages/libs/src/sdk/middleware/index.ts
- packages/libs/src/sdk/sdk.ts
- packages/mobile/src/env/env.dev.ts
- packages/mobile/src/env/env.prod.ts
- packages/mobile/src/env/env.stage.ts
- packages/mobile/src/services/audius-api-client/apiClient.ts
- packages/mobile/src/services/sdk/audius-sdk.ts
- packages/web/src/services/audius-api-client/apiClient.ts
- packages/web/src/services/audius-sdk/audiusSdk.ts
- packages/web/src/services/env/env.dev.ts
- packages/web/src/services/env/env.prod.ts
- packages/web/src/services/env/env.stage.ts
Realized after discussing with @isaacsolo that API app names aren't unique, but api keys are. This model will be more durable for us and allow a simpler query here https://github.com/AudiusProject/audius-protocol/pull/8565
```
```
& confirmed that api key is sent along
> [PROTO-1836] Add ApiKey with requests

- packages/harmony/src/components/layout/Paper/Paper.tsx
- packages/web/src/components/card/Card.tsx
- packages/web/src/components/track/desktop/PlaylistTile.module.css
- packages/web/src/components/track/desktop/PlaylistTile.tsx
- packages/web/src/components/track/desktop/TrackTile.module.css
- packages/web/src/components/track/desktop/TrackTile.tsx
Fixes small ui issues where collection tile and track tile have different shadow behavior. Updated to use Paper defaults
> [C-4407] Consolidate lineup tile shadows

- packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
- packages/web/src/components/track/desktop/stats/Stats.tsx
- packages/web/src/components/track/desktop/stats/StatsText.tsx
Track owner's should never see the message "be the first to repost your track"
> [C-3115] Remove owner track repost message

- packages/harmony/src/components/text-link/TextLink.tsx
- packages/harmony/src/components/text-link/types.ts
- packages/mobile/src/components/lineup-tile/LineupTile.tsx
- packages/mobile/src/components/lineup-tile/LineupTileMetadata.tsx
- packages/mobile/src/components/lineup-tile/styles.ts
- packages/mobile/src/harmony-native/components/TextLink/TextLink.tsx
- packages/mobile/src/harmony-native/components/TextLink/types.ts
Fixes verified icon sizing on track tiles by using user-link. Looking forward to removing all links app wide, but this covers most cases
> [QA-1300] Fix verified icon sizing

- packages/common/src/api/account.ts
- packages/common/src/audius-query/types.ts
- packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountListItem.tsx
- packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsManagingYouHomePage.tsx
- packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageHomePage.tsx
- packages/web/src/pages/settings-page/components/desktop/ManagerMode/RemoveManagerConfirmationContent.tsx
- packages/web/src/pages/settings-page/components/desktop/ManagerMode/sharedMessages.ts
- Fix `onQueryStarted` `dispatch` arg type
- Implement switch account functionality
- Fix/add error messaging
Locally against stage
> [Web] Various manager mode flow cleanup tasks [C-4332] [PAY-2831] [C-4331]

- packages/web/src/pages/upload-page/fields/StemsAndDownloadsField.tsx
remove lossless tag during upload
local v stage
> Remove lossless tag

- comms/discovery/server/signed_request.go
- packages/libs/src/sdk/api/generated/default/apis/TracksApi.ts
> Remove api_key query param to recover signature correctly

- packages/discovery-provider/ddl/functions/handle_manager_request.sql
- packages/discovery-provider/integration_tests/notifications/test_manager_mode_notifs.py
1. Add notification to manager when manager is requested
2. Add notification to managed account when request is accepted
Integration tests.
> Add DB triggers for manager mode notifications [PAY-2828]

- monitoring/vector/vector.toml
Include `solana-relay` logs in Axiom
> [PAY-2755] Add solana-relay logs to Axiom

- packages/mobile/src/components/tiktok-auth/TikTokAuthButton.tsx
Self-explanatory. Remove `noText` prop.
local mobile dapp v stage
> [QA-1309] Fix tiktok button

- packages/common/src/services/remote-config/feature-flags.ts
- packages/common/src/store/purchase-content/sagas.ts
Based on #8593 
Adds feature flag to purchase albums via sdk from client
TBD
> [PAY-3053] Integrate sdk.albums.purchase() into client

- packages/web/src/components/usdc-purchase-details-modal/components/PurchaseModalContent.tsx
- packages/web/src/components/usdc-purchase-details-modal/components/SaleModalContent.tsx
- packages/web/src/pages/dashboard-page/DashboardPage.tsx
Delete unused code! Even if we turn off the feature flag, this stuff is probably safe to leave.
Local web stage confirmed everything looks good
> [PAY-2716] Premium albums post-launch cleanup

- packages/discovery-provider/plugins/pedalboard/apps/mri/src/clm.ts
- packages/discovery-provider/plugins/pedalboard/apps/mri/src/csv.ts
- packages/discovery-provider/plugins/pedalboard/apps/mri/src/index.ts
- packages/discovery-provider/plugins/pedalboard/apps/mri/src/s3.ts
- packages/discovery-provider/plugins/pedalboard/apps/mri/src/server.ts
A few small fixes, comments in-line
```
npm run dev
curl -X POST "http://localhost:6003/record_now"
```
> [PROTO-1826] Address small details in mri

- packages/harmony/src/components/text/Text.tsx
- packages/mobile/src/harmony-native/components/Text/Text.tsx
Fixes issue where texts without text-variants, but changes to strength and size were not being respected. This was introduced by a change i made earlier which allows users to not specifiy variant, which greatly improves useability
> Fix harmony text without variant

- packages/embed/src/components/app.jsx
- packages/embed/src/components/collection/CollectionPlayerCard.jsx
- packages/embed/src/components/collection/CollectionPlayerCard.module.css
- packages/embed/src/components/collection/CollectionPlayerContainer.jsx
- packages/embed/src/components/pausedpopover/ListenOnAudiusCTA.jsx
- packages/embed/src/components/pausedpopover/PausePopover.jsx
- packages/embed/src/components/pausedpopover/PrimaryLabel.jsx
- packages/embed/src/components/track/TrackPlayerCard.jsx
- packages/embed/src/components/track/TrackPlayerCompact.jsx
- packages/embed/src/components/track/TrackPlayerContainer.jsx
- packages/embed/src/components/track/TrackPlayerTiny.jsx
Use the new `instanceOf` functions from sdk to determine type, as `streamConditions` now includes all the gated type keys mapped to potentially `undefined` values:
```
{
"streamConditions": {
"usdcPurchase": {
"splits": {
"AydCRLd7KrirkgbxQvrvWCw9iSpHgy5prNfXJRxXNDSB": 1000000
},
"price": 100
}
}
}
```
Also update UI for premium albums.
https://github.com/AudiusProject/audius-protocol/assets/3893871/23489006-3985-4e14-84d6-66188f346d2e
https://github.com/AudiusProject/audius-protocol/assets/3893871/6610d0b4-e249-41b6-989c-36ff63bc60ff
> Fix embed for premium tracks and albums

- packages/libs/src/sdk/config/production.ts
- packages/libs/src/sdk/config/staging.ts
- packages/libs/src/sdk/scripts/generateServicesConfig.ts
- packages/mobile/src/env/env.prod.ts
- packages/mobile/src/env/env.stage.ts
- packages/web/src/services/env/env.prod.ts
- packages/web/src/services/env/env.stage.ts
> Change frontend RPC

- packages/common/src/api/suggestedTracks.ts
> [QA-1284] Dedupe playlist suggested tracks

- packages/libs/src/sdk/config/production.ts
- packages/libs/src/sdk/config/staging.ts
- packages/libs/src/sdk/scripts/generateServicesConfig.ts
- packages/mobile/src/env/env.prod.ts
- packages/mobile/src/env/env.stage.ts
- packages/web/src/services/env/env.prod.ts
- packages/web/src/services/env/env.stage.ts
This reverts commit 055ee92013b9dfe6ca669a237fe6c471fbc4e441.
> Revert "Change frontend RPC (#8612)"

- packages/web/src/components/tipping/tip-audio/ConfirmSendTip.tsx
Small UI fix for tip-in-progress state on web
https://github.com/AudiusProject/audius-protocol/assets/3893871/5615a43c-33ad-4212-8658-5929f0bd744a
> [QA-1320] Don't show check when tip is sending on web

- packages/web/e2e/signUp.test.ts
#8568 changed the copy which the signup test was relying on
> Fix signup test

- packages/embed/src/util/BedtimeClient.js
> Remove log from bedtime

- packages/identity-service/tsconfig.json
https://github.com/mochajs/mocha/issues/4916
> Set ts-node option in tsconfig.json

- packages/discovery-provider/src/api/v1/utils/extend_notification.py
- packages/discovery-provider/src/queries/get_notifications.py
> [Discovery] Add manager mode notifications to /notifications API response

- packages/harmony/src/components/text/constants.ts
- packages/harmony/src/foundations/typography/typography.ts
Noticed some line-height differences between harmony figma and harmony storybook.
> [C-4422] Update typography line-height

- packages/common/src/models/Analytics.ts
- packages/mobile/src/components/audio/AudioPlayer.tsx
Add a metric for tracking buffer times. May undo this PR later if we get to the bottom of buffer times/solve the issues with them.
ios sim, verified with console logs for now
> [C-4417] Add a buffering metric

- packages/libs/src/services/solana/SolanaWeb3Manager.ts
- packages/web/src/common/store/wallet/sagas.ts
We were incorrectly showing a balance of 0 before.
Local web dapp vs prod
> [QA-1321] Show spinner for audio balance if rpc call fails

- mediorum/server/serve_health.go
- monitoring/healthz/src/pages/Nodes.tsx
- exposes the discovery listens enabled boolean in the health check
- adds a new column to healthz to view if it's turned on or not
> PROTO-1846: add discovery listens status to healthz

- docs/docs/distributors/introduction/overview.mdx
https://1f8ee6ac.docs-eaf.pages.dev/distributors/introduction/overview
> Add DPID and party name info to distro docs

- packages/web/src/components/link/ExternalTextLink.tsx
- packages/web/src/components/static-image/StaticImage.tsx
- packages/web/src/components/user-badges/ProfilePageBadge.tsx
- packages/web/src/pages/profile-page/DesktopServerProfilePage.tsx
- packages/web/src/pages/profile-page/MobileServerProfilePage.tsx
- packages/web/src/pages/profile-page/ServerProfilePage.tsx
- packages/web/src/ssr/profile/+onBeforeRender.tsx
- packages/web/src/ssr/profile/+onRenderHtml.tsx
Add the +onBeforeRender, +onRenderHtml, and profile page files for the new SSR flow
Manually tested and verified bundle size with analyze command
> [C-4320] Add web mobile profile page for SSR

- packages/web/src/components/static-image/StaticImage.tsx
small updates to the imports in StaticImage
> Small fix to static image imports

- packages/discovery-provider/plugins/pedalboard/apps/mri/package.json
* remove @types/cron because cron already ships with them
> Fix sdk typecheck

- packages/libs/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts
DiscoveryNodeSelector.test logs are very verbose and make parsing test results hard: https://github.com/AudiusProject/audius-protocol/actions/runs/9306839205/job/25618860371
> Swallow DiscoveryNodeSelector test logs

- packages/web/src/pages/profile-page/DesktopServerProfilePage.tsx
- packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
Add the desktop profile page for ssr with the small bundle
manual testing and bundle size analysis
> [C-4319] Add desktop profile page for ssr

- packages/libs/src/sdk/api/albums/types.ts
I introduced a type error because `getAlbumsSchema` wasn't defined
> Fix sdk types

- .circleci/src/jobs/@sdk-jobs.yml
- .circleci/src/workflows/sdk.yml
- packages/libs/.hooks/pre-push.json
- packages/libs/package.json
- packages/libs/src/services/web3Manager/Web3Manager.ts
* Add sdk-init to verify (lint & typecheck) sdk in ci
* Add pre-push hook to verify sdk
* Fix lint errors
> [INF-488] verify sdk in ci and git hooks

- packages/mobile/src/components/lineup-tile/LineupTileSkeleton.tsx
Mobile track-tile skeleton was missing artist name skeleton
> [QA-1341] Fix track-tile skeleton

- monitoring/vector/Dockerfile
Upgrade vector.dev
Will test on stage via https://github.com/AudiusProject/audius-docker-compose/pull/514
> Upgrade vector

- packages/discovery-provider/src/api/v1/helpers.py
Getting some serious deja vu, I think my earlier PR must have just missed a commit?
Tested locally
> Add legacy splits formatter to playlists

- packages/commands/src/purchase-content.mjs
- packages/discovery-provider/src/api/v1/playlists.py
- packages/discovery-provider/src/queries/get_playlists.py
I think the albums changes must have gotten lost, this piece was way outdated...
Essentially needed to use the query directly as the helper extended it too early, which would convert to legacy and remove the needed user info before doing the extension. Also somehow the SDK methods called in audius-cmd became outdated
> Fix access-info for albums

- packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
- packages/web/src/pages/pay-and-earn-page/components/PayoutWalletCard.tsx
- packages/web/src/services/solana/solana.ts
Not sure how we do the next parts with relay / exactly how we'd want that to look. Discuss. Can pair today if that's best.
```
```
> [PAY-3058] Show owner accounts for payout wallet, stub creation of ATA via relay

- packages/common/src/store/purchase-content/sagas.ts
- Remove async from generator
- Use proper `this`
- Don't double convert to dollars
- Send explicit args conforming to zod schema
> Fix coinflow purchasing with SDK

- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/redis.ts
- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.ts
> Add rate limit for ATA creation

- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/redis.ts
- packages/libs/src/sdk/sdk.ts
title
also includes changes missed in #8699
> Use signer middleware in solana-relay

- packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
Support creation of payout wallet from relay
1. Able to set USDC token account directly on this branch
2. Hit relay 500 error trying to send through to create the ATA
> Relay to create payout wallet token account

- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.test.ts
- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.ts
- packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
> Fix assertAllowedRelayInstructions, fix tests, rewrite payout wallet logic

- mediorum/Dockerfile.dev
- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/middleware/signerRecovery.ts
- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.test.ts
- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.ts
- packages/libs/src/sdk/sdk.ts
- packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
Fixes misc. issues and sets up correct auth
```
npm run web:dev
```
& created a token account, verified using solana explorer
tested rate limit case
> Finish payout wallet relay support

- packages/harmony/src/components/button/BaseButton/types.ts
- packages/harmony/src/components/button/IconButton/IconButton.tsx
- packages/web/src/components/collection/desktop/PublishButton.tsx
Fixes issue where publish button was using the legacy design by updating from button to icon-button
Adds "isLoading" feature to icon-button, which is necessary for the publishing step
> [QA-1343] Update collection page publish button

- packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
- packages/web/src/pages/pay-and-earn-page/components/PayoutWalletCard.tsx
* show spinner while updating
* avoid showing in-app wallet while page is loading in the payout wallet card
```
```
& updated payout wallet
> [PAY-3080] Misc. payout wallet UI cleanup

- packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
Add compute budget instruction to payout wallet
> Add compute budget

- packages/discovery-provider/src/queries/get_extended_purchase_gate.py
Fix non-purchase gates
Tested locally
> Hotfix: Fix non-purchase access gates

- packages/commands/Dockerfile.prod
- packages/ddex/processor/Dockerfile
- packages/ddex/publisher/Dockerfile
- packages/ddex/webapp/Dockerfile
- packages/discovery-provider/plugins/pedalboard/docker/Dockerfile.prod
- packages/identity-service/Dockerfile.prod
- packages/libs/Dockerfile
- protocol-dashboard/Dockerfile.dev
- protocol-dashboard/Dockerfile.prod
- protocol-dashboard/Dockerfile.stage
New version of turbo has a breaking change and we weren't pinning in the dockerfiles: https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/57973/workflows/051965a6-4c21-405c-a0a8-98806bd38e99/jobs/845850
> Pin turbo in docker files

- packages/web/src/ssr/collection/+onBeforeRender.ts
- packages/web/src/ssr/profile/+onBeforeRender.tsx
- packages/web/src/ssr/track/+onBeforeRender.tsx
There was a small bug when trying to index into images for users that did not have a cover photo or profile picture
> Add optional chaining to ssr render files for images

- packages/web/src/components/payout-wallet-modal/PayoutWalletModal.tsx
> Wait for the payout wallet token account creation

- packages/web/src/components/upload/Dropzone.module.css
- packages/web/src/components/upload/Dropzone.tsx
- packages/web/src/pages/upload-page/UploadPage.tsx
- packages/web/src/pages/upload-page/pages/SelectPage.tsx
Fixes issue where upload helper text was absolutely positioned in a funky way outside it's logical container
Also improves dropdown styling by using paper component
> [QA-1346] Fix select-page dropdown text alignment

- packages/web/src/pages/search-page-v2/SearchResults.tsx
Small update to only show 10 tracks in the all results page
> [C-4466] Update new search results page track preview number

- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/redis.ts
- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.ts
Allow higher rate limit for verified accounts on ATA creation in relay
existing tests pass + will confirm on stage
> [PAY-3086] Add verified user rate limit

- packages/web/src/components/search-bar/ConnectedSearchBar.jsx
Small update to make sure that the path is not reset when a search is submitted
> [C-4467] Fix path reset on search

- packages/mobile/src/components/audio/AudioPlayer.tsx
- packages/mobile/src/components/audio/RNVideoAudioPlayer.tsx
Two small bugs on my POC that I missed
> Fix small player bugs

- packages/web/src/pages/search-page-v2/SearchResults.tsx
> Small fix for search results filter button

- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/utils/connections.ts
- packages/discovery-provider/src/solana/solana_client_manager.py
https://www.notion.so/audiusproject/Solana-Connections-f7f7cce875df4302b54da888f2c38525
CI; changes do not modify existing config.
> Normalize solana connections

- packages/harmony/src/components/button/OptionsFilterButton/OptionsFilterButton.tsx
- packages/harmony/src/components/button/OptionsFilterButton/types.ts
- packages/web/src/pages/search-page-v2/SearchFilters.tsx
- packages/web/src/pages/search-page-v2/SearchResults.tsx
- packages/web/src/pages/search-page-v2/utils.tsx
Update the filter button accept the leading icon that isn't a harmony icon and add the mood filter button
> [C-4368] Add mood options filter button to track search filters

- packages/harmony/src/components/button/OptionsFilterButton/OptionsFilterButton.tsx
- packages/harmony/src/components/button/index.ts
- packages/web/src/pages/search-page-v2/SearchFilters.tsx
Add key filter for new track search results page
> [C-4365] Add key filter to new search page

- packages/web/src/components/dynamic-image/DynamicImage.tsx
Fixes issue where cover-art blur was not showing up in some cases
> [QA-1353] Fix cover art blur

- packages/web/src/components/edit/fields/MultiTrackSidebar.module.css
- packages/web/src/components/edit/fields/MultiTrackSidebar.tsx
> [QA-1358] Fix long track title in upload

- packages/harmony/src/components/music-badge/MusicBadge.tsx
Removed this from last PR, forgot that we still need it for mobile-web.
> Add small variant to web Harmony MusicBage

- packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/approveManagerRequest.test.ts.snap
Update snapshot to fix failing approve manager request notification test.
> [Notifications] Update bad snapshot

- packages/web/src/pages/search-page-v2/NoResultsTile.tsx
- packages/web/src/pages/search-page-v2/SearchCatalogTile.tsx
- packages/web/src/pages/search-page-v2/SearchResults.tsx
Add no results tile and display when there are no relevant search results
> [C-4484] Add NoResultsTile to new search page

- packages/ddex/webapp/client/src/pages/Releases/Releases.tsx
Fixes monorepo verify which is a helpful command to ensure all code is linted and typechecked correctly
> Fix monorepo verify

- packages/discovery-provider/ddl/functions/handle_usdc_purchase.sql
- packages/discovery-provider/integration_tests/notifications/test_usdc_purchase.py
- packages/discovery-provider/integration_tests/queries/test_notifications/test_usdc_purchase_notification.py
Only added vendor to buyer before and forgot to add to buyer.
> Add vendor to buyer notification

- packages/harmony/src/components/button/FilterButton/FilterButton.tsx
- packages/harmony/src/components/button/FilterButton/types.ts
- packages/harmony/src/components/button/OptionsFilterButton/OptionsFilterButton.tsx
- packages/harmony/src/components/button/OptionsFilterButton/types.ts
- packages/web/src/pages/search-page-v2/BpmFilter.tsx
- packages/web/src/pages/search-page-v2/SearchFilters.tsx
Update the BpmFilter component in the search filters and make other small updates to facilitate the change
> [C-4366] Add bpm filter for new search page tracks category

- packages/discovery-provider/src/api/v1/models/playlists.py
- packages/libs/src/sdk/api/generated/full/models/PlaylistFull.ts
- packages/libs/src/sdk/api/generated/full/models/PlaylistFullWithoutTracks.ts
Adds the above fields to sdk
Tested locally
> Add release_date, is_scheduled_release to playlist api

- packages/harmony/src/components/button/OptionsFilterButton/OptionsFilterButton.tsx
- packages/harmony/src/components/button/OptionsFilterButton/types.ts
- packages/web/src/pages/search-page-v2/BpmFilter.tsx
- packages/web/src/pages/search-page-v2/SearchFilters.tsx
- packages/web/src/pages/search-page-v2/SearchResults.tsx
- packages/web/src/pages/search-page-v2/utils.tsx
Add sort buttons to the different category views that respect the search params in the url
Also small update to add options label to the OptionsFilterButton
> [C-4371] Add sort buttons to search category views

- dev-tools/audius-compose
- dev-tools/compose/docker-compose.discovery.prod.yml
- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/config.ts
- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/index.ts
- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/middleware/assertRateLimiter.test.ts
- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/middleware/rateLimiter.ts
- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/redis.ts
- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/assertListenRateLimiter.test.ts
- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/listen.ts
- adds rate limiter for solana relay tests based on ip (hour, day, week)
`audius-compose up`
`npm run test` in solana-relay project
> add listens rate limiter with tests

- packages/discovery-provider/src/api/v1/helpers.py
- packages/discovery-provider/src/api/v1/search.py
- packages/discovery-provider/src/queries/search_es.py
Note this is only for tracks right now. Still need to figure out how to filter by genre from profiles, etc
Tested locally by hitting endpoint with and without genre param
> [C-4531] Add genre param to search api

- packages/common/src/hooks/useCoinflowAdapter.ts
- packages/libs/src/sdk/services/Solana/types.ts
- packages/mobile/package.json
- packages/mobile/src/components/coinflow-onramp-drawer/CoinflowOnrampDrawer.tsx
Add versioned transaction code to prepare for sdk support as well
on mobile device against prod w/ this code:
purchase w/ coinflow with flag off
> Upgrade mobile coinflow to 3.1.4

- packages/common/src/models/DogEar.ts
- packages/common/src/utils/dogEarUtils.ts
- packages/mobile/src/components/core/DogEar.tsx
- packages/mobile/src/components/lineup-tile/LineupTile.tsx
- packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
- packages/web/src/components/dog-ear/DogEar.tsx
- packages/web/src/components/track/desktop/TrackTile.tsx
- packages/web/src/components/track/mobile/PlaylistTile.tsx
- packages/web/src/components/track/mobile/TrackTile.tsx
Remove artist pick dog ear variant.
> [C-4544] Remove artist pick dog ear variant

- packages/web/src/app/web-player/WebPlayer.jsx
- packages/web/src/components/search-bar/ConnectedSearchBar.jsx
- packages/web/src/pages/search-page-v2/SearchPageV2.tsx
Small update to preserve route params when changing search query
> Add small search page routing fixes

- packages/mobile/tsconfig.json
This fixes typecheck on mobile
> Add "es2022.error" to react native tsconfig

- packages/mobile/src/components/audio/RNVideoAudioPlayer.tsx
> Fix double import

- packages/mobile/src/screens/profile-screen/ProfileMetrics.tsx
Super subtle mistake that only exhibits a problem if a user has exactly one track uploaded. 😆 
fixes QA-864
With my eyeballs.
> [QA-864] Use the correct field for calculating followers suffix

- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/listen.ts
> add host to logs of listens for analytics

- packages/web/src/components/search-bar/ConnectedSearchBar.jsx
- packages/web/src/pages/search-page/SearchPageProvider.jsx
Small fixes for the legacy search page searching
> Add small fix for legacy search page provider

- packages/common/src/services/remote-config/feature-flags.ts
- packages/mobile/src/screens/audio-screen/ChallengeRewards.tsx
- packages/web/src/hooks/useIsAudioMatchingChallengesEnabled.ts
- packages/web/src/pages/audio-rewards-page/AudioRewardsPage.tsx
- packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx
Remove the following feature flags:
CHALLENGE_REWARDS_UI = 'challenge_rewards_ui',
AUDIO_MATCHING_CHALLENGES = 'audio_matching_challenges',
Challenges still work on mobile/web
> Remove challenge feature flags

- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/listen.ts
> trailing comma

- packages/discovery-provider/src/queries/search_es.py
- packages/web/src/pages/search-page-v2/SearchPageV2.tsx
- packages/web/src/pages/search-page-v2/SearchResults.tsx
* Add collections search params for genre and mood
* Support empty query on SearchPageV2
> [C-4539] Add collections search filters

- packages/discovery-provider/src/tasks/entity_manager/entities/user.py
Not sure of the original intent w/ the change, but let's fix the test first
> Fix discovery test

- packages/web/src/components/search-bar/ConnectedSearchBar.jsx
Small fix to handle empty search in new search flow
> Fix empty search in new search flow

- package.json
- packages/mobile/package.json
- packages/web/package.json
Tag
https://github.com/AudiusProject/audius-protocol/releases/tag/client-v1.5.85
> Audius Client (Web and Mobile) v1.5.85

- mediorum/Dockerfile
- mediorum/Dockerfile.dev
- mediorum/cpp/bpm-analyzer.cpp
- mediorum/ddl/ddl.go
- mediorum/ddl/drop_old_audio_analyses.sql
- mediorum/server/audio_analysis.go
- mediorum/server/db.go
- mediorum/server/transcode.go
Replace aubio with essentia for BPM analysis bc essentia is much more accurate. Also parallelize the bpm / key analysis.
Had to build essentia from source bc it was not building via the pip install. Ended up having to downgrade ffmpeg from 6.0 to 4.4 and python to 3.9, as well as having to add several supporting dependencies. The downgrades required building from source bc alpine3.18 doesn't support versions that low.
ran locally, verified transcoding and audio analysis completed successfully. verified BPMs using essentia's c++ example matched the essentia python results in https://docs.google.com/spreadsheets/d/1mGKArjvdqfbjOIerSRJk0K4pDAtMCNw47tmyQG6debs/edit?usp=sharing
> Use essentia for mediorum BPM analysis

- packages/web/src/components/notification/Notification/ApproveManagerRequestNotification.tsx
- packages/web/src/components/notification/Notification/RequestManagerNotification.tsx
> [Web] Fix red icons in manager mode notifs  [PAY-3103]

- packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsManagingYouHomePage.tsx
- packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageHomePage.tsx
- packages/web/src/pages/settings-page/components/desktop/ManagerMode/ConfirmAccountManagerPage.tsx
- packages/web/src/pages/settings-page/components/desktop/ManagerMode/FindAccountManagerPage.tsx
- packages/web/src/pages/settings-page/components/desktop/ManagerMode/sharedMessages.ts
See title, discussed in feature channel
Local web against stage
> [Web] Get rid of "Learn More" link in manager mode modals [C-4346]

- packages/discovery-provider/src/queries/search_es.py
> Fix album search

- packages/web/src/common/store/cache/tracks/utils/fetchTrackStreamUrls.ts
Saw more 404s on stream prefetches than should be occurring, realized it was due to some missing logic for previews. This fixes it
web:stage
TODO: make sure unlocking content works as expected
> [C-4564] Add logic for previews & skipped tracks

- packages/libs/src/sdk/api/albums/AlbumsApi.test.ts
- packages/libs/src/sdk/api/playlists/PlaylistsApi.test.ts
- packages/libs/src/sdk/api/tracks/TrackUploadHelper.ts
- packages/libs/src/sdk/api/tracks/TracksApi.test.ts
- packages/libs/src/sdk/api/users/UsersApi.test.ts
- packages/libs/src/sdk/services/Storage/types.ts
- packages/libs/src/services/creatorNode/CreatorNode.ts
Parse from mediorum when polling for upload completion.
DO NOT MERGE until mediorum analysis is solid.
> add key + bpm track fields to sdk / libs

- packages/web/src/pages/search-page-v2/SearchHeader.tsx
Small fix to add the premium and download filters
> [C-4570] Add premium and downloads filters to album search header

- packages/web/src/app/ServerReduxProvider.tsx
- packages/web/src/components/search-bar/ConnectedSearchBar.jsx
- packages/web/src/pages/search-page-v2/NoResultsTile.tsx
- packages/web/src/pages/search-page-v2/ResultsAlbumsView.tsx
- packages/web/src/pages/search-page-v2/ResultsPlaylistsView.tsx
- packages/web/src/pages/search-page-v2/ResultsProfilesView.tsx
- packages/web/src/pages/search-page-v2/ResultsTracksView.tsx
- packages/web/src/pages/search-page-v2/SearchResults.tsx
- packages/web/src/pages/search-page-v2/types.ts
Fix tag search for the new search flow
> [C-4541] Fix tag search

- .circleci/src/commands/@docker-commands.yml
- .circleci/src/workflows/discovery.yml
- .circleci/src/workflows/release.yml
forgot to push the backfill plugin tag
> add to backfill plugin to ci

- dev-tools/compose/docker-compose.yml
> add backfill plugin to docker compose

- packages/web/src/pages/search-page-v2/BpmFilter.tsx
Add simple input validation for the bpm filter inputs
> [C-4559] Add simple BPM Filter validation

- .circleci/src/workflows/discovery.yml
- .circleci/src/workflows/release.yml
- packages/compose/package.json
> trigger push backfill ci flow

- packages/discovery-provider/nginx_conf/main.lua
I was testing verification for manager mode and discovered that this code , brought in here https://github.com/AudiusProject/audius-protocol/pull/7517/files blocks verification from working because identity sends that request. We need another solution. Going to merge this in for now though to get out tomorrow.
https://staging.audius.co/ray61924
Verified this acct
> Fix verification

- mediorum/server/placement.go
> Don't reuse hash instance.

- packages/commands/src/upload-track.mjs
- packages/mobile/src/components/premium-content-purchase-drawer/PurchaseSuccess.tsx
- packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFooter.tsx
- packages/web/src/components/tracks-table/TracksTable.tsx
- Hide share to twitter, repost buttons on purchase success
- Hide repost/favorite buttons on hover in library track row
> [C-4568] Purchase flow updates for hidden content

- packages/mobile/ios/Podfile.lock
- packages/mobile/src/app/Drawers.tsx
- packages/mobile/src/components/manager-mode-drawer/ManagerModeDrawer.tsx
- packages/mobile/src/components/manager-mode-drawer/useShowManagerModeNotAvailable.tsx
- packages/mobile/src/components/navigation-container/NavigationContainer.tsx
- packages/mobile/src/screens/settings-screen/SettingsScreen.tsx
- packages/mobile/src/store/drawers/slice.ts
Tested locally against prod on iOS sim.
> [Mobile] Add Manager Mode not available drawer [PAY-3004]

- packages/mobile/src/components/now-playing-drawer/PlayButton.tsx
Undoes the "green button" for the flagged prefetch experience.
ios:stage
> Remove green playback button

- packages/common/src/hooks/useTrackMetadata.ts
- packages/web/src/components/search/SearchTag.tsx
- packages/web/src/components/track/TrackMetadataList.tsx
- packages/web/src/utils/route.ts
Add BPM and key labels in the track metadata list
Add search page route util also
Manually tested. Will test results more thoroughly after backfill is complete
> [C-4546, C-4558] Add BPM and key track tile labels

- packages/discovery-provider/src/tasks/index_payment_router.py
- packages/discovery-provider/src/tasks/index_rewards_manager.py
- packages/discovery-provider/src/tasks/index_solana_plays.py
- packages/discovery-provider/src/tasks/index_spl_token.py
- packages/discovery-provider/src/tasks/index_user_bank.py
> [PAY-3122] Skip error transactions in indexing

- packages/common/src/store/buy-usdc/sagas.ts
Fixes bug where we were creating user banks for everyone unnecessarily
Local web against prod
> [Web] Fix issue where we create/attempt to create user bank on every page load [QA-1395]

- packages/libs/src/services/solana/SolanaWeb3Manager.ts
> [Web] Fix AUDIO balance error when user bank not created yet [QA-1394]

- packages/discovery-provider/integration_tests/tasks/entity_manager/test_user_entity_manager.py
- packages/discovery-provider/src/tasks/entity_manager/entities/user.py
Safe now that min client is 1.5.85
> Fix user verification

- packages/discovery-provider/src/api/v1/users.py
App authorization works well when you are a manager, but redirects will fail because the verify token method doesn't account for managed users.
Set changes on a stage discovery node and verified using distro.staging.audius.co
> [PAY-3116] Fix verify_token for managed users

- packages/common/src/utils/challenges.ts
- packages/discovery-provider/integration_tests/tasks/test_create_engagement_notifications.py
- packages/discovery-provider/src/tasks/create_engagement_notifications.py
Adding challenge amount and a period to make it consistent with the others.
> Fix referred challenge description

- mediorum/server/helpers.go
Not sure where invalid data comes from... but don't panic for now.
> Don't panic in apiPath helper.

- packages/web/src/store/analytics/sagas.ts
Small update to make sure that the saga is not tracking page views to the current page
> [C-4528] Prevent page views from being tracked at the same pathname

- packages/discovery-provider/src/app.py
to be merged after content node backfill completes (est. Friday)
> schedule audio analysis repair task

- docs/docs/developers/guides/hedgehog.mdx
removed duplicate lines from Hedgehog docs
> [DOCS] - De-duplicate lines

- packages/harmony/src/components/button/FilterButton/FilterButton.tsx
Adds white background to filter button, per design.
> Fix filter button background

- packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsManagingYouHomePage.tsx
- packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageHomePage.tsx
Forgot to hit save on a couple of things in my last PR 🤦
> Fix lint errors with analytics dependencies

- packages/common/src/messages/index.ts
- packages/common/src/messages/search.ts
- packages/common/src/store/search/selectors.ts
- packages/mobile/src/components/core/Screen/Screen.tsx
- packages/mobile/src/harmony-native/components/input/PasswordInput/PasswordInput.tsx
- packages/mobile/src/harmony-native/components/input/TextInput/TextInput.tsx
- packages/mobile/src/screens/app-screen/AppTabScreen.tsx
- packages/mobile/src/screens/search-screen-v2/RecentSearches.tsx
- packages/mobile/src/screens/search-screen-v2/SearchCatalogTile.tsx
- packages/mobile/src/screens/search-screen-v2/SearchFilters.tsx
- packages/mobile/src/screens/search-screen-v2/SearchScreenV2.tsx
- packages/mobile/src/screens/search-screen-v2/index.ts
- packages/mobile/src/screens/search-screen/SearchBar.tsx
- packages/web/src/pages/search-page-v2/RecentSearches.tsx
- packages/web/src/pages/search-page-v2/SearchCatalogTile.tsx
Adds basic searchv2 screen to mobile.
- Updates search input to use harmony text-input. We should just go live with this on v1 too.
> [C-4604] Mobile advanced search scaffolding

- packages/harmony/src/components/segmented-control/SegmentedControl.module.css
- packages/harmony/src/components/segmented-control/SegmentedControl.tsx
Fixes segmented control text by removing css styles and correctly using text api
> [C-4592] Fix segmented control text

- packages/mobile/src/components/collection-list/CollectionCard.tsx
- packages/mobile/src/components/image/CollectionImageV2.tsx
- packages/mobile/src/components/image/TrackImageV2.tsx
- packages/mobile/src/components/user-link/UserLink.tsx
- packages/mobile/src/screens/search-screen-v2/RecentSearches.tsx
- packages/mobile/src/screens/search-screen-v2/SearchScreenV2.tsx
- packages/web/src/pages/search-page-v2/RecentSearches.tsx
Adds mobile recent searches.
Adds TrackImageV2, similar to CollectionImageV2, just a much cleaner interface.
> [C-4605] Mobile Recent Searches

- packages/mobile/src/screens/search-screen-v2/SearchScreenV2.tsx
> Fix search params

- packages/common/src/api/search.ts
- packages/mobile/src/screens/app-screen/AppTabScreen.tsx
- packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx
- packages/mobile/src/screens/search-screen-v2/components/SelectGenreScreen.tsx
- packages/mobile/src/screens/search-screen-v2/components/SelectMoodScreen.tsx
- packages/mobile/src/screens/search-screen-v2/components/index.ts
- packages/mobile/src/screens/search-screen-v2/index.ts
Basic setup to allow search v2 to have the filter stack screens and also allow for individual search screens between app tabs
> [C-4622] Add basic setup for mobile search v2 navigation

- packages/common/src/audius-query/createApi.ts
Fixes small issue where apis that return an object of apiResponseSchema wasn't working
shoutout to @amendelsohn for the clean fix
> Fix audius-query schema key

- packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/purchase.ts
- packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/sale.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseBuyer.ts
- packages/identity-service/src/notifications/emails/welcome.js
- packages/identity-service/src/routes/welcomeEmail.js
Update copy in purchase email to include $AUDIO rewards note.
Update welcome email design to include trending.
Ran locally and sent e-mails to myself.
> Update purchase and welcome email

- packages/discovery-provider/src/queries/get_related_artists.py
Excludes input user ID from related artist results.
> exclude input user id from related artists results

- packages/web/src/components/lineup/LineupTileSkeleton.tsx
- packages/web/src/pages/search-page-v2/ResultsTracksView.tsx
- packages/web/src/pages/search-page-v2/SearchResults.tsx
* Add `LineupTileSkeleton` for better loading states for tracks
> [C-4469] Improve search v2 loading states

- packages/common/src/audius-query/createApi.ts
- packages/common/src/audius-query/types.ts
Fixes issue where audius-query fails for non-object data
> Fix audius query normalization

- .circleci/src/commands/@mobile-commands.yml
> Migrate to private rpc for saga deployment

- packages/es-indexer/src/listener.ts
es-indexer denormalizes some track data when indexing playlists.
If a track changes re-index any playlists containing that track.
> [PROTO-1873] re-index playlists containing track when track changes.

- packages/mobile/src/harmony-native/components/Button/FilterButton/FilterButton.tsx
Small update to remove the controlled state for the label for the mobile FilterButton
> Make small label update to FilterButton

- packages/web/src/components/edit-track/EditTrackForm.tsx
- packages/web/src/components/edit/fields/AdvancedField.tsx
- packages/web/src/components/edit/fields/DatePickerField.tsx
- packages/web/src/components/edit/fields/ReleaseDateField.module.css
- packages/web/src/components/edit/fields/ReleaseDateField.tsx
- packages/web/src/components/edit/fields/ReleaseDateFieldLegacy.tsx
- packages/web/src/components/edit/fields/visibility/ReleaseDateField.tsx
Adds release date field to the track edit advanced section.
Also refactored the `DatePickerField` component to include the "input-like" container that was being added externally until now.
web:stage
> [C-4555] Add release date to new track edit

- packages/web/src/components/collection/CollectionCard.tsx
- packages/web/src/components/nav/mobile/ConnectedNavBar.tsx
- packages/web/src/components/nav/mobile/NavBar.module.css
- packages/web/src/components/nav/mobile/NavBar.tsx
- packages/web/src/components/user-card/UserCard.tsx
- packages/web/src/pages/search-page-v2/NoResultsTile.tsx
- packages/web/src/pages/search-page-v2/RecentSearches.tsx
- packages/web/src/pages/search-page-v2/ResultsAlbumsView.tsx
- packages/web/src/pages/search-page-v2/ResultsPlaylistsView.tsx
- packages/web/src/pages/search-page-v2/ResultsProfilesView.tsx
- packages/web/src/pages/search-page-v2/ResultsTracksView.tsx
- packages/web/src/pages/search-page-v2/SearchCatalogTile.tsx
- packages/web/src/pages/search-page-v2/SearchHeader.tsx
- packages/web/src/pages/search-page-v2/SearchPageV2.tsx
- packages/web/src/pages/search-page-v2/SearchResults.tsx
- packages/web/src/utils/route.ts
* Clean up UI for mobile web advanced search
> [C-4621] Advanced search mobile web

- packages/common/src/api/topArtists.ts
- packages/common/src/audius-query/createApi.ts
Fixes issues with topArtists options and schemaKey issue
> [QA-1416] Fix top-artists and audius-query

- packages/common/src/utils/musicalKeys.ts
- packages/mobile/src/screens/list-selection-screen/ListSelectionScreen.tsx
- packages/mobile/src/screens/list-selection-screen/SelectionItemList.tsx
- packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx
- packages/mobile/src/screens/search-screen-v2/SearchScreenV2.tsx
- packages/mobile/src/screens/search-screen-v2/screens/FilterBpmScreen.tsx
- packages/mobile/src/screens/search-screen-v2/screens/index.ts
Split out the ListSelectionItems into their own component
Added the FilterBpmScreen component
Some other small updates
NOTE: There is a weird issue with Buttons not rerendering and displaying changes immediately. I'll look into this
> [C-4586] Add mobile FilterBpmScreen for new search screen

- packages/common/src/api/search.ts
- packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx
- packages/mobile/src/screens/search-screen-v2/screens/FilterGenreScreen.tsx
- packages/mobile/src/screens/search-screen-v2/screens/FilterMoodScreen.tsx
Small updates to connect all of the search filters and handle the boolean search filters vs the filters with screens
> Connect remaining mobile search filters

- packages/common/src/audius-query/createApi.ts
- packages/common/src/audius-query/schema.ts
- packages/common/src/audius-query/types.ts
- packages/mobile/src/components/collection-list/CollectionCard.tsx
- packages/mobile/src/screens/search-screen-v2/search-results/AlbumResults.tsx
- packages/mobile/src/screens/search-screen-v2/search-results/PlaylistResults.tsx
- packages/mobile/src/screens/search-screen-v2/search-results/SearchResults.tsx
- packages/mobile/src/screens/search-screen-v2/searchState.ts
* Add Album and Playlist results
* Add `debounce` option to audius-query hooks
> [C-4688] Add AlbumResults and PlaylistResults for advanced search

- packages/discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py
I'd added these tests while trying to track down a bug, turns out the bug was on the client but these tests are good to have anyway.
Lmk if there are any cases that would be good to test.
tests pass locally
> Add tests for updating track access conditions

- packages/web/src/components/data-entry/ContextualMenu.module.css
- packages/web/src/components/data-entry/ContextualMenu.tsx
- packages/web/src/components/edit/fields/DatePickerField.module.css
- packages/web/src/components/edit/fields/visibility/ReleaseDateField.tsx
> [C-4641 C-4654 C-4648] Edit track page fixes

- packages/mobile/src/screens/search-screen-v2/RecentSearches.tsx
- packages/mobile/src/screens/search-screen-v2/SearchItem.tsx
- packages/mobile/src/screens/search-screen-v2/SearchScreenV2.tsx
- packages/mobile/src/screens/search-screen-v2/search-results/AllResults.tsx
- packages/mobile/src/screens/search-screen-v2/search-results/SearchResults.tsx
- packages/mobile/src/screens/search-screen-v2/searchState.ts
* Add All Results screen
* Reuse recent search items
> [C-4606] Mobile advanced search All Results screen

- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/common/src/services/fingerprint/FingerprintClient.ts
- packages/identity-service/package.json
- packages/identity-service/src/app.js
- packages/identity-service/src/config.js
- packages/identity-service/src/fpClient.js
- packages/identity-service/src/models/fingerprint.js
- packages/identity-service/src/routes/authentication.js
- packages/identity-service/src/routes/fp.js
- packages/identity-service/src/routes/user.js
- packages/identity-service/src/utils/fpHelpers.js
- packages/identity-service/src/utils/otp.js
- packages/identity-service/src/utils/walletAssociation.js
- packages/identity-service/test/authenticationTest.js
- packages/identity-service/test/lib/app.js
- packages/libs/src/api/Account.ts
- packages/libs/src/sdk/services/Auth/UserAuth.ts
- packages/libs/src/services/identity/IdentityService.ts
- packages/mobile/src/screens/sign-on-screen/screens/ConfirmEmailScreen.tsx
- packages/mobile/src/screens/sign-on-screen/screens/SignInScreen.tsx
- packages/web/src/common/store/account/sagas.js
- packages/web/src/common/store/pages/signon/actions.ts
- packages/web/src/common/store/pages/signon/sagas.ts
- packages/web/src/pages/sign-in-page/ConfirmEmailPage.tsx
Added convenience allowing users to skip OTP if signing in from a trusted device.
Tested on staging identity service
> [PROTO-1867] OTP only on unfamiliar devices

- packages/web/src/components/edit/fields/visibility/VisibilityField.tsx
Fixes issue where released scheduled releases where not showing "public" in visibility field
> [C-4650] Fix visibility field when released scheduled release

- packages/common/src/utils/creativeCommons.ts
- packages/web/src/components/edit-track/types.ts
- packages/web/src/components/edit-track/utils/computeLicenseIcons.ts
- packages/web/src/components/edit/fields/AdvancedField.tsx
- packages/web/src/pages/edit-page/EditTrackPage.tsx
- packages/web/src/pages/upload-page/forms/UploadTrackForm.tsx
Fixes issue where license type wasn't set correctly on upload, and also wasn't editable on edit. Most of it came down to setting `licenseType` field without setting `license` which is the actual value. Luckily this fix also simplifies that issue by removing licenseType from the main form values by moving it into the licenseType form fields.
> [C-4647] Fix license type

- packages/mobile/src/components/details-tile/DetailsTileStats.tsx
How was this missed? i do not know.
> Hide 0 stats on mobile collection screens

- packages/web/src/components/edit-collection/EditCollectionForm.module.css
Fixes issue where edt collection form would not naturally try to take it's parent's width.
> [C-4684] Fix edit-collection width

- packages/web/src/pages/settings-page/components/desktop/ManagerMode/RemoveManagerConfirmationContent.tsx
Just a case of some bad logic :-)
> [PAY-3154] Fix accidental refresh on removing managers

- packages/mobile/src/harmony-native/components/Button/FilterButton/FilterButton.tsx
- packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
Small update to remove controlled state for value in mobile FilterButton
This fixed the late update issue for the search filter buttons
> [C-4703] Update FilterButton to remove controlled value

- packages/common/src/api/search.ts
- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/mobile/src/screens/search-screen-v2/search-results/TrackResults.tsx
- packages/web/src/common/store/pages/search-page/lineups/tracks/sagas.ts
* Implement tag search for mobile advanced search
> [C-4700] Mobile tag search

- packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx
> Lint fixes

- packages/discovery-provider/integration_tests/queries/test_get_track_library.py
- packages/discovery-provider/src/queries/get_track_library.py
> Show hidden tracks in the library purchases/all tab, hide from all other tabs

- packages/mobile/src/screens/search-screen-v2/SearchItem.tsx
- packages/mobile/src/screens/search-screen-v2/search-results/AllResults.tsx
- packages/mobile/src/screens/search-screen-v2/search-results/TrackResults.tsx
Improved the loading states for the All results and track results pages to give some feedback to the user
> [C-4697] Add loading states for the mobile search results

- packages/web/src/pages/search-page-v2/SearchPageV2.tsx
Persist common filters when switching categories in new search page
> [C-4669] Update new search page to maintain common filters between categories

- dev-tools/compose/docker-compose.discovery.prod.yml
- dev-tools/compose/nginx_ingress.conf
Fixes TRPC container and routing so that it works with local dev
Tested that album backlinks worked appropriately in local dev
> Fix TRPC server with local dev audius-compose

- packages/discovery-provider/plugins/pedalboard/apps/mri/src/config.ts
- packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/udr.ts
* Fix env variable mapping
* Need to use `.rows` with a `knex.raw` result
> Fix UDR query result

- packages/mobile/src/screens/search-screen-v2/screens/FilterBpmScreen.tsx
- packages/web/src/components/edit/fields/AdvancedField.tsx
- packages/web/src/pages/search-page-v2/BpmFilter.tsx
- packages/web/src/pages/search-page-v2/SearchPageV2.tsx
Add better validation to avoid bad cases and data from the bpm inputs
Fix alignment when there is an error on web
Add KeyboardAvoidingView to avoid keyboard covering inputs on mobile
Manually tested on web and mobile
> [C-4751, C-4746, C-4663] Add better validation for bpm inputs

- packages/web/src/pages/search-page-v2/ResultsAlbumsView.tsx
- packages/web/src/pages/search-page-v2/ResultsPlaylistsView.tsx
- packages/web/src/pages/search-page-v2/ResultsProfilesView.tsx
> [C-4666] Update skeleton counts for new search results

- packages/mobile/src/screens/search-screen-v2/RecentSearches.tsx
- packages/web/src/components/link/UserLink.tsx
- packages/web/src/pages/search-page-v2/RecentSearches.tsx
> [C-4735, C-4678] Add popover and fix close icon for recent searches

- packages/mobile/src/screens/edit-track-screen/screens/AdvancedOptionsScreen.tsx
- packages/web/src/components/edit-track/EditTrackForm.tsx
- packages/web/src/components/edit/fields/AdvancedField.tsx
> [C-4747] Update track edit form to only display key and bpm field in the edit flow

- packages/mobile/src/screens/search-screen-v2/search-results/AlbumResults.tsx
- packages/mobile/src/screens/search-screen-v2/search-results/PlaylistResults.tsx
- packages/mobile/src/screens/search-screen-v2/search-results/ProfileResults.tsx
> [C-4733, C-4738] Update mobile profile, album, and playlist search results to have consistent background and scroll padding

- packages/mobile/src/screens/search-screen-v2/RecentSearches.tsx
- packages/mobile/src/screens/search-screen-v2/SearchScreenV2.tsx
- packages/web/src/pages/search-page-v2/RecentSearches.tsx
> [C-4743] Update recent searches to display contextual items on web and mobile

- packages/discovery-provider/ddl/migrations/0080_correct_reserved_handle.sql
> Correct reserved handle

- packages/harmony/src/components/button/FilterButton/FilterButton.tsx
- packages/harmony/src/components/button/OptionsFilterButton/OptionsFilterButton.mdx
- packages/harmony/src/components/button/OptionsFilterButton/OptionsFilterButton.stories.tsx
- packages/mobile/src/harmony-native/components/Button/FilterButton/FilterButton.tsx
- packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx
Adds reset logic to web and mobile filter buttons.
These are the minimal changes needed to get things to work, but i may want to follow up with a few changes to add "oncChange" to mobile
> [C-4658] Add filter-button clear

- packages/discovery-provider/ddl/migrations/0082_fix_user_tx_hash.sql
Tested on prod dn4
https://discoveryprovider4.audius.co/comms/pubkey/RK0Kl4g?api_key=8acf5eb7436ea403ee536a7334faa5e9ada4b50f&app_name=audius-client
> Fix broken user tx hash

- packages/discovery-provider/src/queries/search_es.py
Small update to change the field that is sorted on for recent search with elastic search
> [C-4667] Update recent search to sort on created_at field

- packages/common/src/store/cache/collections/reducer.ts
- packages/harmony/src/components/popup/Popup.tsx
- packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistLibraryNavItem.tsx
- packages/web/src/components/track/OwnerActionButtons.tsx
- packages/web/src/components/track/ViewerActionButtons.tsx
- packages/web/src/components/track/desktop/PlaylistTile.tsx
1. In the new action button code, we are fetching collections with track ids and vise versa, fix that
2. Clean up some misc console issues
3. Fix popup component to skip trying to useTransition from `react-spring` before a component is mounted
```
```
> Fix misc component issues on startup

- packages/web/src/components/track/OwnerActionButtons.tsx
Woops, broken in https://github.com/AudiusProject/audius-docker-compose/commit/aa64792900b2319e23ada5b74d4d8a1128d1075a
> Fix web lint and permalink passing

- packages/web/src/components/edit-collection/CollectionNavigationPrompt.tsx
Fixes issue where navigation-prompt was showing during submit.
> [C-4776] Fix edit collection submit

- packages/discovery-provider/integration_tests/queries/test_search_track_tags.py
- packages/discovery-provider/integration_tests/queries/test_search_user_tags.py
- packages/es-indexer/README.md
* fix + re-enable some search tests
* update readme
> Update es-indexer readme, fix tests.

- packages/discovery-provider/src/tasks/repair_audio_analyses.py
remove retrigger logic, which is handled by content now.
> clean up key/bpm repairer

- packages/discovery-provider/plugins/pedalboard/apps/mri/src/config.ts
- packages/discovery-provider/plugins/pedalboard/apps/mri/src/s3.ts
> Fix MRI clm / udr s3 configs

- packages/discovery-provider/src/tasks/repair_audio_analyses.py
only a problem on stage. logger throws an error if len(tracks) == 0
> fix log error in analysis repairer

- packages/web/src/pages/modals/Modals.tsx
Think this was a mistake - common modals should be mounted on both web and mobile-web.
Modals open on local web stage
> [C-4709] Fix modals on mobile-web

- packages/discovery-provider/plugins/pedalboard/apps/mri/src/csv.ts
- packages/discovery-provider/plugins/pedalboard/apps/mri/src/date.ts
- packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/clm.ts
- packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/udr.ts
- packages/discovery-provider/plugins/pedalboard/apps/mri/src/s3.ts
> Fix misc UDR bugs

- packages/mobile/src/screens/search-screen-v2/SearchScreenV2.tsx
- packages/mobile/src/screens/search-screen-v2/screens/FilterBpmScreen.tsx
- packages/mobile/src/screens/search-screen-v2/screens/FilterGenreScreen.tsx
- packages/mobile/src/screens/search-screen-v2/screens/FilterMoodScreen.tsx
- packages/mobile/src/screens/search-screen-v2/searchState.ts
Title
Manual Testing
There are some quirks, but this was a solution that was both simple and mostly good
> [C-4772] Update mobile filter buttons to respect filter value

- packages/discovery-provider/plugins/pedalboard/apps/mri/README.md
- packages/discovery-provider/plugins/pedalboard/apps/mri/src/date.ts
- packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/udr.ts
Final fixes to UDR plugin, tested output with staging data
1. Fix quarter boundary issues
2. Fix file naming
Deployed to stage discovery node, ran 
curl -X POST "http://localhost:6003/udr/record"
Output:
[202404_AUDIUS_20240716T205530.csv](https://github.com/user-attachments/files/16256523/202404_AUDIUS_20240716T205530.csv)
> Final touches to UDR

- packages/mobile/src/screens/chat-screen/ChatUserListItem.tsx
- packages/mobile/src/screens/sign-on-screen/screens/SelectArtistScreen/FollowArtistCard.tsx
Fixes issue were avatars were to big in some contexts, due to "auto" being the default size now for avatars.
> [QA-1429] Fix avatar sizing

- packages/common/src/api/search.ts
> Fix type error

- packages/web/src/pages/search-page-v2/BpmFilter.tsx
- packages/web/src/pages/search-page-v2/SearchFilters.tsx
- packages/web/src/pages/search-page-v2/search-results/TrackResults.tsx
Updated the key and bpm filter buttons to have appropriate initial state
> [C-4789] Update web key and bpm filter buttons to respect the filter value

- packages/web/src/pages/search-page-v2/search-results/TrackResults.tsx
The web search refactor broke filters on tracks. This fixes it!
> [C-4805] Fix track filters

- packages/harmony/src/components/button/FilterButton/FilterButton.tsx
Small update to call onclick when it is set for the toggle filter buttons
> [C-4788] Update filter button to fix toggle filter button functionality

- packages/mobile/src/components/lineup-tile/TrackTile.tsx
- packages/mobile/src/components/notification-reminder/NotificationReminder.tsx
- packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx
- packages/web/src/pages/search-page-v2/SearchHeader.tsx
Simple sorting for filter buttons with values
> [C-4757] Add simple sorting for filter buttons with values

- packages/mobile/src/screens/edit-track-screen/components/ExpandableRadio.tsx
Extra description should not be there.
local mobile dapp v stage
> Remove description dupe

- packages/mobile/src/screens/search-screen-v2/RecentSearches.tsx
> [C-4744] Change clear recent search button to plain button

- packages/mobile/src/components/track-list/TrackListItem.tsx
- packages/web/src/components/track/mobile/TrackListItem.tsx
lcoal mobile web and native mobile vs stage
> [PAY-3173] Update native mobile library for locked and hidden tracks

- packages/harmony/src/components/button/OptionsFilterButton/OptionsFilterButton.tsx
> [C-4692] Fix filter button option active help text color

- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/discovery-provider/src/queries/search_es.py
- packages/discovery-provider/src/queries/search_queries.py
- packages/web/src/pages/search-page-v2/search-results/AllResults.tsx
* Include collections in tag search
* Improve loading states on All Results page
> [C-4677] Include albums and playlists in tag search

- packages/mobile/src/screens/user-list-screen/UserListItem.tsx
This fix going straight to prod
> [QA-1453] Big user-list images

- packages/mobile/src/screens/search-screen-v2/search-results/TrackResults.tsx
Update the track results to immediately display the loading state so that the previous results are not visible when search query or filters are switched
Profiles, Albums, and Playlists already have a decent loading state so no updates were done there
> [C-4740] Update loading state for new search screen track results

- packages/mobile/src/screens/list-selection-screen/SelectionItemList.tsx
- packages/mobile/src/screens/search-screen-v2/screens/FilterBpmScreen.tsx
> [C-4797] Fix BPM screen scroll clipping

- packages/web/src/components/tracks-table/TracksTable.tsx
> [QA-1456] Hide purchase button and stats on tombstoned track rows

- packages/identity-service/src/notifications/emails/recovery.html
https://www.twilio.com/docs/sendgrid/ui/analytics-and-reporting/click-tracking-html-best-practices
Ran on staging and confirmed it's disabled.
> Disable click tracking on recovery

- packages/web/src/pages/search-page-v2/SearchHeader.tsx
> Undo web filter button sorting

- packages/mobile/src/components/details-tile/DetailsTileHasAccess.tsx
- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Fix mobile track header and special access box width
* Owner with access on special access, collectible gated, and premium
* Viewer without access on special access, collectible gated, and premium
> [PAY-3183] Fix mobile track header and special access box

- packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/clm.ts
- packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/udr.ts
Add UniqueTrackIdentifier to report
will confirm on stage
> Add UniqueTrackIdentifier to UDR report

- packages/mobile/src/screens/update-required-screen/UpdateRequiredScreen.tsx
Adds solona_dapp_store url to update screen
Tested on saga
> [C-4698] Add solana dapp store update link

- mediorum/server/audio_analysis.go
- mediorum/server/legacy_audio_analysis.go
> bump num workers for audio analysis

- mediorum/server/serve_upload.go
> log when mediorum fails to process an upload

- packages/web/src/common/store/pages/search-page/lineups/tracks/sagas.ts
search v1 tag search wasn't returning results
> [QA-1461] Fix search v1 tag search

- packages/web/src/components/edit/fields/TrackMetadataFields.module.css
- packages/web/src/components/edit/fields/TrackMetadataFields.tsx
> [C-4851] Update artwork and metadata fields layout

- packages/discovery-provider/src/tasks/entity_manager/entities/track.py
> handle falsy bpm

- packages/discovery-provider/src/tasks/entity_manager/entities/track.py
> entity manager: convert all bpm vals to float

- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Fix mobile track publish button
ios v stage
https://github.com/user-attachments/assets/3705563d-2f24-417c-b184-5a00ada1a929
> [PAY-3177][PAY-3185] Fix mobile track publish button

- packages/discovery-provider/src/queries/search_es.py
- packages/es-indexer/src/indexNames.ts
- packages/es-indexer/src/indexers/PlaylistIndexer.ts
- packages/es-indexer/src/indexers/TrackIndexer.ts
> [C-4676] Filter out deleted user content from search

- .circleci/scripts/generate-slack-template.sh
Does this break another case I'm not aware of?
> Fix commit link in ci slack message

- packages/harmony/src/components/artwork/Artwork.tsx
Fixes issue where src is undefined on first paint and eventually comes in. When src is undefined, lets set loading to true.
This improves advanced search loading a lot
> [QA-1458] Fix artwork image loading

- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Fix pressing the tags when new search is enabled
> [C-4842] Fix tag press on mobile for search v2

- packages/discovery-provider/ddl/migrations/0083_fix_bad_musical_keys.sql
- packages/discovery-provider/src/tasks/repair_audio_analyses.py
drop bad keys from db and validate key/bpm before saving
merge monday after https://github.com/AudiusProject/audius-protocol/pull/9199#pullrequestreview-2188973715 runs in mediorum
> Discovery: fix bad musical keys

- packages/identity-service/src/routes/fp.js
Webhook is no longer needed as fingerprint information will now be queried from the server directly.
CI
> Remove fingerprint webhook

- packages/web/src/pages/search-page-v2/NoResultsTile.tsx
- packages/web/src/pages/search-page-v2/RecentSearches.tsx
- packages/web/src/pages/search-page-v2/SearchCatalogTile.tsx
- packages/web/src/pages/search-page-v2/SearchHeader.tsx
- packages/web/src/pages/search-page-v2/SearchPageV2.tsx
- packages/web/src/pages/search-page-v2/search-results/AlbumResults.tsx
- packages/web/src/pages/search-page-v2/search-results/PlaylistResults.tsx
- packages/web/src/pages/search-page-v2/search-results/ProfileResults.tsx
- packages/web/src/pages/search-page-v2/search-results/TrackResults.tsx
Use useIsMobile instead of useMedia
Fix padding on mobile web
> [C-4848] Remove search v2 responsiveness and fix padding on mobile web

- packages/mobile/src/components/details-tile/TrackMetadataList.tsx
- packages/web/src/utils/route.ts
> [C-4837] Fix links for the searching by electronic subgenre from track page

- packages/mobile/src/components/card/Card.tsx
- packages/mobile/src/components/collection-list/CollectionCard.tsx
- packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
- packages/mobile/src/components/offline-downloads/CollectionDownloadStatusIndicator.tsx
- packages/mobile/src/components/offline-downloads/DownloadStatusIndicator.tsx
- packages/mobile/src/components/offline-downloads/TrackDownloadStatusIndicator.tsx
- packages/mobile/src/components/track-list/TrackListItem.tsx
- packages/mobile/src/screens/collection-screen/DownloadStatusRowDisplay.tsx
Adds offline indicator to mobile collection card.
Refactors offline indicator to harmony + update references
> [QA-1442] Add offline indicator to collection card

- dev-tools/setup.sh
https://github.com/docker/compose/issues/12001
> Pin docker-compose-plugin to fix env var issue

- packages/commands/src/edit-playlist.mjs
- packages/commands/src/edit-track.mjs
Also allows changing remix parent
> Add ability to change playlist/track visibility w/ audius-cmd

- packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
Make sure profile page pull to refresh actually refreshes inner content
mobile simulator, updated track on web, pulled to refresh and it updated on mobile
> [PAY-3190] Improve profile page pull to refresh

- packages/mobile/src/harmony-native/components/input/TextInput/TextInput.tsx
- packages/mobile/src/harmony-native/components/input/TextInput/types.ts
- packages/mobile/src/screens/search-screen-v2/SearchBarV2.tsx
- packages/web/src/components/search/SearchBarV2.jsx
* Use IconButton for clear search query button
> [C-4834] Animate clear search button for search v2

- packages/web/src/components/nav/mobile/NavBar.tsx
- packages/web/src/pages/search-page-v2/RecentSearches.tsx
- packages/web/src/pages/search-page-v2/SearchCatalogTile.tsx
- packages/web/src/pages/search-page-v2/SearchHeader.tsx
- packages/web/src/pages/search-page-v2/SearchPageV2.tsx
- packages/web/src/pages/search-page-v2/search-results/AlbumResults.tsx
- packages/web/src/pages/search-page-v2/search-results/PlaylistResults.tsx
- packages/web/src/pages/search-page-v2/search-results/ProfileResults.tsx
- packages/web/src/pages/search-page-v2/search-results/TrackResults.tsx
* Don't show quotes around search query
* Fix colors on web / mobile-web
> [C-4843] [C-4846] More advanced search UI fixes

- packages/web/src/common/store/cache/collections/commonSagas.ts
Cascading publish wasn't working because `playlistBeforeEdit` was actually selected from cache after the optimistic update. This caused the `playlistBeforeEdit?.is_private && !playlist.is_private` condition to fail.
Cascade was working on publish button because it goes through its own saga without the above check (since we're always publishing).
publish working on hidden and early release cases, not triggering otherwise
> [C-4863] Fix cascading publish on edit collection

- mediorum/server/audio_analysis.go
- mediorum/server/legacy_audio_analysis.go
- mediorum/server/transcode.go
so i can toggle prod cn2 more easily.
tested locally
> mediorum configurable num workers

- mediorum/server/audio_analysis.go
- mediorum/server/legacy_audio_analysis.go
might as well let SPs pick up these jobs in addition to prod cn 2
they weren't picking up their remaining jobs past 811,000 ish done cids for the past few days, i think because of crudr issues. which shouldve been resolved by the ops migration earlier.
> placement hosts analyze legacy audio analyses in addition to storeall node

- mediorum/go.mod
- mediorum/go.sum
- mediorum/server/placement.go
- mediorum/server/placement_test.go
- mediorum/server/repair.go
mediorum:
* use sha256 ordering
* disable cleanup mode for this.
> Move to all sha256 ordering

- monitoring/vector/Dockerfile
- monitoring/vector/vector.toml
- packages/discovery-provider/plugins/notifications/src/main.ts
- packages/discovery-provider/src/solana/solana_client_manager.py
- packages/discovery-provider/src/tasks/index_solana_plays.py
Upgrade vector to 0.39.0
```
docker buildx build \
--platform linux/arm64,linux/amd64 \
--tag audius/vector:$(head -n1 Dockerfile | cut -f 2 -d ':') \
--build-arg git_sha=$(git rev-parse HEAD) \
--build-arg audius_axiom_token=${audius_axiom_token} \
--push \
.
```
> Upgrade vector to 0.39.0

- packages/mobile/src/components/edit/PriceAndAudienceField/PriceAndAudienceScreen.tsx
- packages/mobile/src/hooks/useSetTrackAvailabilityFields.ts
> Fix missing refactor bug

- packages/web/src/components/edit/fields/DatePickerField.tsx
Fixes issue setting release date to today. Setting touched triggers a useEffect that sets the time to 11:59 when choosing a same day release date.
> [C-4874] Update time to 11:59 when scheduling for same day

- packages/mobile/src/screens/edit-track-screen/screens/AdvancedScreen.tsx
Fixes issue where submenulist cant receive null. we should really fix submenulist, but doing this for release
> Fix runtime issue with advanced field

- packages/discovery-provider/plugins/pedalboard/apps/backfill-audio-analyses/src/backfill_discovery.ts
Just in case anything fell through the cracks, and to pick up anything on prod cn2 that other SPs missed bc of crudr issues.
Will run today and should complete in around 6 hours at most.
> Run discovery audio analysis backfill plugin last time (sanity run)

- packages/discovery-provider/plugins/pedalboard/apps/backfill-audio-analyses/src/backfill_discovery.ts
> aa discovery backfill: sleep for prod cn2 in err case too

- packages/web/src/components/edit/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseFields.tsx
> Update copy for preview length

- .changeset/green-deers-pretend.md
- packages/harmony/src/components/button/FilterButton/FilterButton.tsx
https://www.figma.com/design/hcVGqf35jfxueO7klqXlma/%F0%9F%A7%B0-Harmony-Component-Library?node-id=2803-15265&m=dev
> [C-4836] Adjust FilterButton active states

- packages/discovery-provider/src/api/v1/users.py
- packages/mobile/src/harmony-native/components/Radio/Radio.tsx
- packages/web/src/components/table/Table.tsx
- packages/web/src/components/table/components/TablePlayButton.tsx
- packages/web/src/pages/saved-page/SavedPageProvider.tsx
- Fix play button in tracks table
- Mobile radio input should not be clickable when selected
- Filter out delete tracks from library
local web and ios v stage
> [PAY-3236][PAY-3242][PAY-3259] Fix play button in tracks table

- packages/harmony/src/components/button/FilterButton/FilterButton.tsx
Missed one small case in https://github.com/AudiusProject/audius-protocol/pull/9289. I've already deployed to my subdomain so no rush on this
> Small FilterButton hover style tweak

- packages/discovery-provider/ddl/migrations/0085_playlists_release_date.sql
Old playlists & albums will get this set now
> [PAY-3263] add playlists & albums release date if null

- packages/discovery-provider/src/utils/elasticdsl.py
https://stackoverflow.com/a/77631602
> Silence request logs for python es client

- packages/mobile/src/components/lineup-tile/GatedTrackLabel.tsx
- packages/mobile/src/screens/search-screen-v2/SearchScreenV2.tsx
- packages/mobile/src/screens/search-screen-v2/searchState.ts
- packages/web/src/components/track/GatedTrackLabel.tsx
Updates extras logo and text
Only shows extras in search context
> Premium extras updates

- packages/mobile/src/components/edit/VisibilityField/VisibilityScreen.tsx
(this is covered already in web using the same logic)
> [PAY-3276] No scheduled playlists

- packages/harmony/src/components/button/OptionsFilterButton/OptionsFilterButton.tsx
- packages/mobile/src/screens/search-screen-v2/screens/FilterBpmScreen.tsx
- packages/web/src/components/collection/CollectionCard.tsx
- packages/web/src/pages/search-page-v2/BpmFilter.tsx
- packages/web/src/pages/search-page-v2/SearchPageV2.tsx
- packages/web/src/pages/search-page-v2/SearchResults.tsx
- packages/web/src/pages/search-page-v2/search-results/TrackResults.tsx
- packages/web/src/pages/search-page-v2/utils.tsx
* Improve bpm filter error styling by shortening copy
* Show artist popover on collection cards
* Fix bpm range helper text hover style
* Fix mobile web track lineup styling
* Prevent mobile web from showing All Results
Tested locally, web and mobile web
> [C-4885] [C-4888] [C-4889] [C-4882] [C-4883] Advanced search UI fixes pt 3

- packages/mobile/src/components/image/TrackImageV2.tsx
- packages/mobile/src/screens/edit-track-screen/components/RemixTrackPill.tsx
- packages/mobile/src/screens/edit-track-screen/fields/RemixSettingsField.tsx
- packages/mobile/src/screens/edit-track-screen/screens/RemixSettingsScreen.tsx
- packages/web/src/pages/edit-page/EditTrackPage.tsx
Fixes issues where edit remix was missing entirely on web, and remix_of linking was inconsistent on mobile
> [PAY-3254] Fix edit remix

- packages/mobile/src/screens/edit-collection-screen/EditCollectionForm.tsx
- packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx
- packages/mobile/src/screens/edit-track-screen/EditTrackModalScreen.tsx
Track:
Collection:
Note: collection doesn't have any error display logic, but I don't think it ever did.
iOS sim
> C-4894 Make edit track/edit collection use same buttons

- packages/mobile/src/app/App.tsx
- packages/mobile/src/screens/edit-track-screen/EditTrackNavigator.tsx
Moves the edit track modals to the proper navigator place so they appear above the EditTrackForm
Tested publishing/hiding a track, made free track paid
> PAY-3275 Portal drawers to the correct location

- packages/web/src/components/collection/CollectionCard.test.tsx
Test data needed to be updated because we are rendering the artist popup now
> Fix CollectionCard test

- packages/mobile/src/screens/edit-collection-screen/EditCollectionNavigator.tsx
Missing the portal for the confirmation modals
Tested iOS sim
> PAY-3288 Fix edit collection confirmations on mobile

- packages/mobile/src/components/track-list/TrackListItem.tsx
> PAY-3291 Don't show purchase in overflow menu for non-purchase-gated tracks

- packages/mobile/src/components/edit/PriceAndAudienceField/SpecialAccessRadioField.tsx
Missing disabled field on SpecialAccess ExpandableRadio
ios sim stage
> PAY-3290 Special Access should disable entirely

- packages/web/src/components/collection/desktop/CollectionActionButtons.tsx
- packages/web/src/components/collection/desktop/EditButton.tsx
- packages/web/src/components/collection/desktop/FavoriteButton.tsx
- packages/web/src/components/collection/desktop/OverflowMenuButton.tsx
- packages/web/src/components/collection/desktop/PublishButton.tsx
- packages/web/src/components/collection/desktop/RepostButton.tsx
- packages/web/src/components/collection/desktop/ShareButton.tsx
- packages/web/src/components/notification/Notification/components/icons.module.css
Fix icon size regressions for notifications and collection card action buttons
> [C-4903] Update icon sizes for collection card actions and notifications

- packages/web/public/actions.json
Will be deployed to actions.audius.co separately.
n/a
> Add actions.json for solana blink support

- packages/web/src/pages/explore-page/ExploreCollectionsPageProvider.tsx
Update an effect to not call infinitely so that the app doesn't crash
> [C-4905] Fix app crash when navigating to let them dj when signed out

- packages/web/scripts/workers-site/index.js
- packages/web/src/ssr/worker.js
Missed that this was necessary! 
works on demo site, but not prod 
https://demo.audius.co/release-client-v1.5.91/actions.json
> Add actions.json to cloudflare

- packages/create-audius-app/helpers/install.ts
Surpress warn logs in create-audius-app
> Suppress warning in caa install

- packages/common/src/messages/sign-on/pages.ts
- packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
Small update to add an empty state for the select artists page in the sign up flow
> [C-3907] Add empty state for artist results in sign up flow

- packages/discovery-provider/src/tasks/entity_manager/entities/track.py
for users to unset these values
> Allow null bpms and musical keys

- packages/common/src/services/remote-config/feature-flags.ts
> [PAY-3311] Create one_to_many_dms flag

- packages/common/src/audius-query/createApi.ts
> Fix sign in

- packages/mobile/src/screens/edit-track-screen/EditTrackScreen.tsx
- packages/mobile/src/screens/edit-track-screen/screens/IsrcIswcScreen.tsx
Adds validation to isrc and iswc.
Adds revertOnCancel and preventSubmit when there are errors
> [C-4899] Fix isrc and iswc validation

- packages/discovery-provider/src/queries/search_es.py
- packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx
- packages/web/src/pages/search-page-v2/SearchHeader.tsx
* Allow filtering albums, playlists, and tracks by verified
> [C-4798] Filter all categories by verified

- packages/web/scripts/workers-site/index.js
> Add cors headers for actions

- dev-tools/compose/docker-compose.yml
docker-compose spec needs just the generic service name to fit in with audius-compose tooling.
Ran audius-compose push locally
> Fix core in docker-compose file

- core/infra/dev_config/content-one.docker.env
- core/infra/dev_config/content-three.docker.env
- core/infra/dev_config/content-two.docker.env
- core/infra/dev_config/discovery-one.docker.env
- dev-tools/compose/docker-compose.yml
Multiple core containers on local dev environment
> Multiple cores for local dev

- packages/web/src/components/collection/components/RepostsFavoritesStats.tsx
> [PAY-3330] Fix spacing on RepostsFavoritesStats

- packages/libs/src/sdk/api/albums/AlbumsApi.ts
- packages/libs/src/sdk/api/tracks/TracksApi.ts
Will adjust in morning. Hardcoding for now to 100k microLamports
Tested against prod
> Add priority fees to purchases

- packages/libs/src/sdk/config/staging.ts
- packages/libs/src/sdk/scripts/generateServicesConfig.ts
- packages/mobile/src/env/env.stage.ts
- packages/web/src/services/env/env.stage.ts
- solana-programs/payment-router/Anchor.toml
- solana-programs/payment-router/programs/payment-router/src/lib.rs
- solana-programs/staking-bridge/Anchor.toml
- solana-programs/staking-bridge/package.json
- solana-programs/staking-bridge/programs/staking-bridge/src/lib.rs
Update to newly deployed program with IDL
adc change: https://github.com/AudiusProject/audius-docker-compose/pull/526
> [PAY-2267] Update stage payment router and program addresses

- packages/web/src/components/header/desktop/Header.tsx
- packages/web/src/components/search/SearchBar.module.css
- packages/web/src/components/search/SearchBarV2.jsx
- packages/web/src/pages/explore-page/components/desktop/CollectionsPage.tsx
- packages/web/src/pages/search-page-v2/SearchHeader.tsx
* Fix spinner overlapping clear button
* Fix search bar missing on SearchPage
* Convert `Header` to typescript
> [C-4934] Search bar fixes

- packages/web/src/components/nav/desktop/NavHeader.tsx
- packages/web/src/components/nav/desktop/NotificationsButton.tsx
- packages/web/src/components/notification-dot/NotificationDot.module.css
After chatting with @julianbaker , the color has been changed to red, but otherwise the below screenshots are accurate!
Local stage, faked numbers to produce screenshots
> [QA-1356] Improve notification UI

- packages/discovery-provider/ddl/migrations/0087_fix_slugs_with_slash.sql
> [QA-1459] Fix 0087_fix_slugs_with_slash.sql migration

- packages/common/src/models/Track.ts
- packages/common/src/schemas/metadata.ts
- packages/web/src/common/store/cache/tracks/sagas.ts
> Set is_custom_musical_key

- packages/discovery-provider/src/api/v1/tracks.py
- packages/libs/src/sdk/api/generated/default/apis/TracksApi.ts
Fixes small bug
```
TypeError: get_track_comments() missing 1 required positional argument: 'track_id'
```
> Fix pagination args

- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/listen.ts
> Format Solana Relay listens endpoint

- packages/discovery-provider/ddl/migrations/0089_fix_comment_reactions_pkey.sql
Comment reactions are unique on a comment ID and user ID. 
Ran on sandbox.
> Fix comment reactions pkey

- packages/common/src/services/remote-config/feature-flags.ts
- packages/mobile/src/screens/sign-on-screen/screens/CreateEmailScreen.tsx
Add a feature flag to disable social signup (only works on mobile for now)
> Add social signup feature flag

- .changeset/soft-games-flash.md
- packages/common/src/store/pages/chat/sagas.ts
- packages/common/src/store/pages/chat/slice.ts
- packages/libs/src/sdk/api/chats/ChatsApi.ts
- packages/libs/src/sdk/api/chats/clientTypes.ts
- packages/libs/src/sdk/api/chats/serverTypes.ts
- packages/web/src/pages/chat-page/components/ChatComposer.tsx
Hook up chat blast RPC method in sdk and connect it to an action in client.
Note some TODOs in the saga
Dispatched action in client and confirmed row was written to `chat_blast` in db.
> [PAY-3310] Chat blast function in sdk

- core/chain/node.go
- core/config/config.go
- core/config/defaults.go
- core/config/utils.go
- core/infra/Dockerfile
love a good set of core values
- the default rpc binds to localhost not 0.0.0.0 and isn't reachable on 
> core default values

- core/config/defaults.go
> use const for constants

- comms/Makefile
- comms/discovery/db/queries/get_chat_messages.go
- comms/discovery/db/queries/get_chats.go
- comms/discovery/rpcz/chat.go
- comms/discovery/rpcz/chat_blast_test.go
- comms/discovery/rpcz/chat_create_test.go
- comms/discovery/schema/schema.go
- comms/discovery/server/response_mapper.go
- packages/discovery-provider/ddl/migrations/0090_chat_last_message_is_plaintext.sql
- packages/libs/src/sdk/api/chats/serverTypes.ts
* Adds `is_plaintext` field to chat message response.
* Adds `last_message_is_plaintext` to chat response
> [PAY-3341] Add is_plaintext field for chat message

- packages/web/src/common/store/profile/sagas.js
> Fix bug in profile page 404

- comms/discovery/db/queries/get_new_blasts.go
- comms/discovery/rpcz/chat_blast.go
- comms/discovery/schema/schema.go
- packages/discovery-provider/ddl/migrations/0091_chat_audience_updates.sql
- packages/libs/src/sdk/api/chats/serverTypes.ts
audience_content_type + audience_content_id
> More explicit audience columns for chat blast.

- .circleci/config.yml
- .circleci/scripts/auto-approve-release.sh
- .circleci/src/commands/@git-commands.yml
- .circleci/src/jobs/commit-audius-docker-compose-and-notify.yml
- .circleci/src/jobs/deploy-foundation-nodes.yml
- .circleci/src/jobs/deploy-stage-nodes.yml
- .circleci/src/jobs/release-audius-docker-compose.yml
Add job that automatically triggers the release workflow, conditional on the health of the foundation tier.
shellcheck passed on new script file. Will manually test release workflow after landing.
> Auto-deploy to SPs, consolidate git configuration

- packages/common/src/api/comments.ts
Thought I had this working but I think at the last minute I removed the return for TS and accidentally broke stuff.
Also realized I had a bug with the first item in the list anyways lol
Working again.
> Fix comment delete in audius-query

- packages/common/src/store/pages/chat/sagas.ts
- packages/common/src/store/pages/chat/slice.ts
- packages/common/src/utils/chatUtils.ts
- packages/web/src/pages/chat-page/components/ChatBlastModal.tsx
- packages/web/src/pages/chat-page/components/ChatComposer.tsx
- packages/web/src/pages/chat-page/components/ChatListBlastItem.tsx
Add chat blasts to local redux state inside the corresponding chat (chatId = audience + audienceContentType + audienceContentID, colon-separated)
Working on local stack
> Optimistic add chat blasts

- core/config/defaults.go
> change pg string for regex in content (core)

- packages/common/src/context/commentsContext.tsx
- packages/mobile/src/components/comments/CommentDrawer.tsx
- packages/mobile/src/components/comments/CommentSection.tsx
- packages/mobile/src/components/comments/mock-data.ts
- packages/mobile/src/screens/track-screen/TrackScreenMainContent.tsx
- packages/mobile/src/store/drawers/slice.ts
- packages/web/src/components/comments/CommentBadges.tsx
- packages/web/src/components/comments/CommentBlock.tsx
- packages/web/src/components/comments/mock-data.ts
- packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
web:stage - used Isaac as a test tipper 👌
> [C-4940] Add comment badges (desktop web)

- packages/common/src/context/commentsContext.tsx
- packages/mobile/src/components/comments/CommentBlock.tsx
- packages/mobile/src/components/comments/CommentDrawer.tsx
- packages/mobile/src/components/comments/CommentSection.tsx
- packages/web/src/components/comments/CommentActionBar.tsx
- packages/web/src/components/comments/CommentBlock.tsx
- packages/web/src/components/comments/CommentForm.tsx
Move the mutation hooks out of the comment context, similar to useDeleteComment
> [C-4976] Refactor comment hooks

- packages/mobile/src/screens/chat-screen/ChatScreen.tsx
- packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
Don't show or trigger reaction popup if artist is in their own blast thread.
Tested locally on web stage (mobile untested...)
> [PAY-3345] Prevent artist reacting to their own blasts

- packages/libs/src/sdk/api/chats/ChatsApi.ts
- packages/libs/src/sdk/api/chats/clientTypes.ts
This is the only "stateful" part of the api and also was never being used!
> Remove listenUserId from chat api

- packages/web/src/components/search-users-modal/SearchUsersModal.tsx
CTA was missing on small screens or heavy zoom. This explicitly floats it on the bottom of the modal.
> [PAY-3366] Fix CTA hidden on small screens

- comms/discovery/rpcz/chat.go
- comms/discovery/rpcz/chat_blast_test.go
Uses the invite array to find all relevant blasts from members of the forthcoming chat before creation.
> [PAY-3342] Chat upgrade handles prior blasts from both parties.

- .circleci/config.yml
> Run dashboard ci on common changes

- packages/common/src/api/comments.ts
- packages/mobile/src/components/comments/CommentBlock.tsx
- packages/mobile/src/components/comments/CommentDrawer.tsx
- packages/mobile/src/components/comments/CommentDrawerForm.tsx
- packages/mobile/src/components/comments/CommentDrawerHeader.tsx
- packages/mobile/src/components/comments/CommentForm.tsx
- packages/mobile/src/components/comments/CommentSection.tsx
- packages/mobile/src/components/comments/CommentThread.tsx
- packages/mobile/src/screens/track-screen/TrackScreen.tsx
- packages/mobile/src/screens/track-screen/TrackScreenMainContent.tsx
* Split up CommentDrawer into multiple files
* Fix comment form submission
* Replace TouchableOpacity usages with PlainButton
* Fix optimistic react count in context
> Mobile comment fixes

- packages/discovery-provider/nginx_conf/nginx_container.conf
Seems like accidentally deleted in https://github.com/AudiusProject/audius-protocol/pull/9514/files
> Fix relay container

- comms/discovery/db/queries/get_new_blasts.go
- comms/discovery/rpcz/chat_blast.go
- comms/discovery/rpcz/chat_blast_test.go
Adds audiences: supporter, remixer, customer.
> [PAY-3363] Chat blast: support more audiences

- packages/common/src/hooks/useCollectionMetadata.ts
- packages/common/src/hooks/useTrackMetadata.ts
- packages/common/src/utils/route.ts
- packages/common/src/utils/urlUtils.ts
- packages/mobile/src/components/details-tile/CollectionMetadataList.tsx
- packages/mobile/src/components/details-tile/MetadataItem.tsx
- packages/mobile/src/components/details-tile/TrackMetadataList.tsx
- packages/web/src/components/collection/CollectionMetadataList.tsx
- packages/web/src/components/entity/MetadataItem.tsx
- packages/web/src/components/search/SearchTag.tsx
- packages/web/src/components/track/TrackMetadataList.tsx
- packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
- packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
- packages/web/src/utils/route.ts
Fixes track metadata list order and simplifies code layout.
Fixes album backlinks which were resulting in runtime error
> [C-4909] Improve track metadata list, fix album backlinks

- dev-tools/audius-compose
Second commit is autoformatting
> Pull latest solana-test-validator before running up

- packages/commands/src/create-user-bank.mjs
Did this while testing some solana-test-validator things, figured I might as well commit it.
> Update create-user-bank cmd to use SDK

- packages/web/src/common/store/cache/collections/createPlaylistSaga.ts
- packages/web/src/common/store/pages/collection/lineups/sagas.js
- packages/web/src/components/menu/TrackMenu.tsx
Track duration being used for "added time" on create playlist from track flow
https://staging.audius.co/rayddex/playlist/april-676846689
> [QA-1016] Fix playlist creation from track added time

- .circleci/src/commands/@web-commands.yml
Updated version of nodejs and installed it before installing dependencies.
[Successful web dist workflow](https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/61756/workflows/b529cd85-4ac9-4795-92fe-b29132fd176c) on recent client branch using the same commits.
> [QA-1520] Fix desktop client releases for Linux and Mac

- packages/harmony/package.json
Fix harmony types in CI https://app.circleci.com/pipelines/gh/AudiusProject/audius-protocol/61775/workflows/fcfac40e-b92b-4987-a496-8d8cfb59d976/jobs/908014
> Fix types on harmony virtualized

- packages/common/src/audius-query/utils.ts
The change here: https://github.com/AudiusProject/audius-protocol/pull/9423/files/9a8ec8a83d528346bf8adf85e0668f693469897d#r1714251433
Caused a bug with pagination
> [QA-1526] Hotfix pagination issues

- packages/discovery-provider/Dockerfile.dev
- packages/discovery-provider/Dockerfile.prod
Previous patch version was removed from alpine linux package repo, updating to fix build.
CI
> Update python package for dn dockerfile

- packages/ddex/webapp/client/src/pages/Releases/Releases.tsx
- packages/mobile/src/components/comments/CommentOverflowMenu.tsx
Fixes current lint issue on main.
Fixes issues preventing `npm run verify` from the root from passing when it should. We can rely on this now!
> Fix mobile comment overflow menu lint

- packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts
Broken here
https://github.com/AudiusProject/audius-protocol/pull/9494/files#diff-ba19b3b9d4779b557bc0ba41e5c297973e243231065d7214037faa875ac568f7R21
Offline downloads work
> Fix broken offline mode

- packages/mobile/src/screens/track-screen/DownloadRow.tsx
- packages/mobile/src/screens/track-screen/DownloadSection.tsx
Thought we removed this already. It's not in web.
Confirmed download works on ios sim
> Remove quality toggle for mobile downloads

- packages/mobile/src/screens/track-screen/TrackScreen.tsx
- packages/mobile/src/screens/track-screen/TrackScreenRemix.tsx
* Fix layout of more by artist
* Fix layout of images on remixes
> [QA-1531][QA-1535] Fix mobile track page issues

- core/config/config.go
- core/config/genesis/stage.json
- core/main.go
> As/simplify goroutines + increment stage chain id

- packages/common/src/api/search.ts
idk how I missed this in the review 🤦 
> Fix search filters

- docs/src/css/colors.css
- packages/embed/src/components/App.module.css
- packages/harmony/src/components/scrubber/Slider.module.css
- packages/harmony/src/foundations/color/primitive.css
- packages/web/src/assets/styles/colors.css
- packages/web/src/components/play-bar/TrackingBar.module.css
- packages/web/src/pages/audio-rewards-page/Tiers.module.css
> [QA-1510] Simplify hover gradient styles coming from harmony

- packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
> Center long track/collection titles on mobile

- packages/discovery-provider/Dockerfile.prod
See: https://github.com/AudiusProject/audius-protocol/pull/9290#issue-2436428489
> Pin Rust version for 'prod' DN dockerfile

- packages/mobile/src/components/comments/CommentDrawerHeader.tsx
- packages/mobile/src/components/comments/CommentSortBar.tsx
- packages/mobile/src/screens/track-screen/TrackScreen.tsx
* Add mobile comments sort ui
* Left align "More by artist" header
> [C-4956] Add mobile comments sort ui

- core/config/config.go
- core/setup.go
- the env var for discovers registry addr is incorrect
- also changes the rootDir to use the named volume and just rename beneath
> core follow-ons: use main dir and correct registry address

- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/trackListenInstructions.ts
- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/relay.ts
- packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/utils/transaction.ts
This reverts commit 96efa179594a1a86015cfdbb798c6b351293f999.
Reverting because of block not found consistency issues
> Revert "Cycle solana RPC connections better (#9147)"

- core/chain/node.go
- core/config/config.go
> fix core stage registry addr

- packages/web/src/components/edit/fields/price-and-audience/PriceAndAudienceMenuFields.tsx
- packages/web/src/components/edit/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx
Also renames feature flag to be less confusing
> [PAY-3411] Enable monetization for everyone when network cut is enabled

- comms/discovery/rpcz/chat_blast_test.go
- comms/discovery/rpcz/chat_test.go
fixes tests: schema changes and reaction signature change
> Fix chat blast tests

- packages/mobile/src/screens/create-chat-blast-screen/ChatBlastSelectAudienceFields.tsx
> fix typecheck in ChatBlastSelectAudienceFields

- packages/web/src/components/follow-artist-card/selectArtistsPreviewContext.tsx
- packages/web/src/components/user-name-and-badges/UserNameAndBadges.tsx
- packages/web/src/pages/chat-page/components/ChatBlastModal.tsx
- packages/web/src/pages/chat-page/components/ChatListBlastItem.tsx
> fix typecheck on main

- packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/libs.ts
bot is failing with this error, we need to add web3 config to the libs instance so the new code runs successfully
> add web3manager to trending rewards bot

- packages/discovery-provider/src/queries/get_skipped_transactions.py
> remove max skipped tx check

- packages/common/src/store/purchase-content/sagas.ts
- packages/libs/src/sdk/api/albums/AlbumsApi.ts
- packages/libs/src/sdk/api/tracks/TracksApi.ts
- packages/mobile/src/screens/app-screen/AppTabsScreen.tsx
- packages/mobile/src/screens/wallet-connect/WalletConnectModalScreen.tsx
- packages/mobile/src/screens/wallet-connect/WalletConnectScreen.tsx
- packages/mobile/src/screens/wallet-connect/types.ts
- packages/mobile/src/screens/wallet-connect/usePhantomConnect.ts
- packages/mobile/src/utils/navigation.ts
Fixes issues w/ pay w/ anything
Local dev
> Fix pay with anything

- packages/web/src/components/header/desktop/Header.tsx
- packages/web/src/components/header/desktop/HeaderGutter.tsx
- packages/web/src/components/page/Page.module.css
- packages/web/src/components/page/Page.tsx
Fixes issue introduced in another clean up PR. Reverts a few things and checked everywhere
> [QA-1712] Fix trending header

- packages/web/src/components/track/GiantTrackTile.tsx
> [qa-1255] Fix bg color on premium giant track tiles

- packages/web/src/components/track/GiantTrackTile.tsx
- packages/web/src/pages/profile-page/components/desktop/ProfilePage.module.css
> [QA-1410] [QA-1492] Socials icons padding

- packages/web/src/pages/audio-rewards-page/RewardsTile.module.css
Make reward claim tiles 1px borders to match live file, and make Claim All section have 1px divider
> [QA-1586] Rewards Page: 1px boder, 1px divider

- packages/common/src/messages/settings.ts
- packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
- packages/web/src/ssr/util.ts
Small updates to the copy, icon, and link for the download section in the settings page
> [QA-1143] Update settings page download section

- packages/web/src/components/track/desktop/TrackTile.tsx
Increase the margin if long form content and has the bar
> [QA-1107] Fix TrackTile title lengths for podcasts

- packages/web/src/components/modal-radio/ModalRadioItem.module.css
Just make the overflow hidden. Spot checked other usages, they look fine.
> QA-1715 Fix horizontal scrollbar in scheduled release

- packages/web/src/pages/profile-page/components/mobile/ProfileHeader.module.css
> [QA-874] Fix shadow spacing on mobile profile artist badge

- packages/web/src/components/withdraw-usdc-modal/components/Hint.module.css
- packages/web/src/components/withdraw-usdc-modal/components/Hint.tsx
Small spacing update and removed unnecessary margin
> [QA-1502] Fix Add Funds modal hint spacing

- packages/web/src/components/unload-dialog/UnloadDialog.tsx
> [QA-1588] Update reload anyway button styling

- packages/mobile/src/components/audio/AudioPlayer.tsx
> Stop music on signout

- .circleci/src/commands/@docker-commands.yml
Function call not deleted from previous pr
Ran script locally
> Fix crane script again

- mediorum/server/serve_upload.go
- mediorum/server/serve_upload_test.go
- mediorum/server/transcode.go
Move transcode to request time.
> Inline transcode

- packages/web/src/components/upload/Dropzone.tsx
As title
Local npm run web:stage
> [QA-1692] Fix inconsistent font weight in upload text

- packages/web/src/components/edit/fields/DatePickerField.module.css
As title
Tested light, dark, and matrix modes
> [QA-1134] Fix styles for date picker on scheduled release modal

- packages/web/src/components/track/CardTitle.tsx
- packages/web/src/components/track/GiantTrackTile.module.css
- packages/web/src/components/track/GiantTrackTile.tsx
- packages/web/src/components/track/TrackStats.tsx
> [QA-1472] Fix GiantTrackTile spacing

- packages/common/src/store/pages/token-dashboard/slice.ts
- packages/common/src/store/pages/token-dashboard/types.ts
- packages/mobile/src/screens/wallet-connect/components/LinkedWallets.tsx
- packages/web/src/common/store/pages/token-dashboard/sagas.ts
- packages/web/src/pages/audio-rewards-page/components/ConnectWalletsBody.tsx
Add spinner to connected wallets while loading.
Also add error states
> [QA-1652] Add loading state to connected wallets

- packages/mobile/src/components/fields/PickArtworkField.tsx
- packages/mobile/src/screens/edit-collection-screen/EditCollectionForm.tsx
- packages/mobile/src/screens/edit-collection-screen/EditCollectionScreen.tsx
Fixes pretty obvious bug with edit collection... there was no validation on mobile
> [QA-1610] Fix mobile collection edit validatation

- packages/web/src/components/add-to-collection/desktop/AddToCollectionModal.tsx
- packages/web/src/components/follow-artist-card/FollowArtistCard.tsx
- packages/web/src/components/follow-artist-card/selectArtistsPreviewContext.tsx
No more restricting hidden tracks in public playlists
Tested that the hidden track does not show up for users other than the artist
> [QA-1125] Remove add to playlist disabled option logic

- packages/web/src/pages/search-page-v2/hooks.ts
> Fix null query in search

- packages/mobile/android/app/build.gradle
> Bump android build number

- packages/mobile/src/hooks/useIsScreenReady.ts
- packages/mobile/src/screens/app-screen/AppTabScreen.tsx
- packages/mobile/src/screens/app-screen/AppTabsScreen.tsx
- packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx
- packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
- packages/mobile/src/screens/favorites-screen/TracksTab.tsx
- packages/mobile/src/screens/track-screen/TrackScreen.tsx
- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
- packages/mobile/src/screens/track-screen/TrackScreenMainContent.tsx
For live testing on real devices, will revert after demo-ing.
> App Delight POC

- packages/harmony/src/components/button/FilterButton/FilterButtonOption.tsx
Fix filter button helper text
Local
> [QA-1723] Fix filter options button helper text

- packages/web/src/components/summary-table/SummaryTable.tsx
> Fix challenge summary table

- packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
- packages/web/src/components/composer-input/ComposerInput.tsx
- packages/web/src/components/composer-input/components/AutocompleteText.tsx
Small update to add tab completion for the user mention autocomplete in the composer UI
Also a fix mobile text rendering
Testing manually
> Add tab completion for compose UI autocomplete

- packages/web/src/components/composer-input/ComposerInput.tsx
- packages/web/src/components/composer-input/types.ts
> [C-4871] Add timestamp highlighting for composer input

- packages/web/src/components/composer-input/ComposerInput.tsx
merged in github and had an error. fixing it
> Fixing lint from bad merge

- .github/ISSUE_TEMPLATE/api-sdk-bug-report.md
- .github/ISSUE_TEMPLATE/api-sdk-feature-request.md
adding templates for API/SDK bug and feature requests
> Update issue templates

- packages/web/src/components/comments/CommentForm.tsx
- packages/web/src/components/composer-input/ComposerInput.tsx
- packages/web/src/components/composer-input/types.ts
- packages/web/src/pages/chat-page/ChatPage.module.css
Small fixes for chat page:
* Fix error with comments hook used outside of comments context
* Fix styling error due to header changing css position type
> Fix composer input error and styling for DMs

- packages/libs/src/services/dataContracts/EntityManagerClient.ts
> Fix typecheck

- packages/common/src/store/purchase-content/sagas.ts
Im not sure what changed here since this had previously worked...
> Fix usdc-usdc purchase

- packages/common/src/hooks/purchaseContent/usePurchaseContentErrorMessage.ts
- packages/common/src/store/purchase-content/sagas.ts
- packages/common/src/store/purchase-content/types.ts
Add no quote error to checkout and remove direct routes only for "Pay With Anything"
Local, purchase successful w/ nubcat
> Remove direct only and add noQuote error

- packages/web/src/pages/chat-page/components/ChatBlastHeader.tsx
- packages/web/src/pages/chat-page/components/ChatHeader.module.css
Use Harmony Artwork component instead of DynamicImage
> Use Harmony Artwork for ChatBlastHeader

- comms/discovery/rpcz/chat_blast.go
- comms/discovery/rpcz/chat_blast_test.go
- comms/discovery/rpcz/websocket.go
- comms/discovery/schema/schema.go
- comms/discovery/server/response_mapper.go
- packages/libs/src/sdk/api/chats/serverTypes.ts
re-run quicktype and fix issues with drift from `serverTypes.ts` and `schema.go`
> Chat fix quicktype

- packages/common/src/api/search.ts
Added sort method back to the request for search results
> [QA-1730] Add sort back to the search query

- packages/web/src/pages/chat-page/components/ChatMessagePlaylist.tsx
- packages/web/src/pages/chat-page/components/ChatMessageTrack.tsx
Small update to check if the entity is deleted when unfurling a message
> [QA-1717] Fix empty unfurl messages for tracks and playlists

- packages/common/src/store/pages/settings/reducer.ts
- packages/common/src/store/pages/settings/types.ts
- packages/discovery-provider/plugins/notifications/src/__tests__/mappings/__snapshots__/comment.test.ts.snap
- packages/discovery-provider/plugins/notifications/src/__tests__/mappings/comment.test.ts
- packages/discovery-provider/plugins/notifications/src/email/notifications/components/Body.tsx
- packages/discovery-provider/plugins/notifications/src/email/notifications/components/notifications/Notification.tsx
- packages/discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/comment.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/mapNotifications.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/userNotificationSettings.ts
- packages/discovery-provider/plugins/notifications/src/remoteConfig.ts
- packages/discovery-provider/plugins/notifications/src/types/dn.ts
- packages/discovery-provider/plugins/notifications/src/types/notifications.ts
- packages/discovery-provider/plugins/notifications/src/utils/populateDB.ts
- packages/identity-service/sequelize/migrations/20240919161114-add-messages-to-browser-notification-settings.js
- packages/identity-service/sequelize/migrations/20240919161135-add-messages-to-mobile-notification-settings.js
- packages/identity-service/src/models/userNotificationBrowserSettings.js
- packages/identity-service/src/models/userNotificationMobileSettings.js
- packages/mobile/src/screens/settings-screen/NotificationSettingsScreen.tsx
- packages/web/src/pages/settings-page/components/desktop/NotificationSettings.tsx
- packages/web/src/pages/settings-page/store/sagas.ts
Adds email and push notifications for comments. Just going to send this to stage and see if it works
> Add comment email and push

- packages/web/src/pages/search-page-v2/SearchFilters.tsx
Small update to fix the displayed label on the key filter for the search page
> [QA-1731] Fix key filter label

- packages/common/src/api/search.ts
Accidentally committed a duplicate line
> Fix merge issue

- packages/web/src/pages/upload-page/components/ShareBanner.tsx
- Adds new functionality to share buttons post upload
- DM button opens the create chat modal with the content id loaded and will pre-fill the message with the url
- Share button opens the share modal
> [PAY-3216] Update upload share buttons

- packages/web/src/pages/chat-page/components/ChatMessageList.module.css
- original change was by design, but it was looking awkward in practice
> revert max width on chats

- comms/Makefile
- comms/discovery/db/queries/get_chat_blocked_users.go
- comms/discovery/db/queries/get_chat_permissions.go
- comms/discovery/db/queries/get_follows.go
- comms/discovery/db/queries/get_user_tips.go
- comms/discovery/rpcz/apply.go
- comms/discovery/rpcz/chat.go
- comms/discovery/rpcz/chat_block_test.go
- comms/discovery/rpcz/chat_permissions_test.go
- comms/discovery/rpcz/validator.go
- comms/discovery/schema/schema.go
- comms/discovery/server/response_mapper.go
- comms/discovery/server/server.go
- comms/discovery/server/server_test.go
- packages/discovery-provider/ddl/docker-compose.yml
- packages/discovery-provider/ddl/functions/chat_allowed.sql
- packages/discovery-provider/ddl/migrations/0096_chat_permissions_multiple.sql
- packages/discovery-provider/ddl/tests/chat_allowed_test.sql
- packages/libs/src/sdk/api/chats/serverTypes.ts
* adds optional allow boolean to the chat permission rpc
* conditional behavior for handling the single vs multi permission model (and also special case for all/none)
* SQL UDF for chat_allowed
* permission checking code uses the UDF
> UDF for chat_allowed

- packages/web/src/components/notification/Notification/components/NotificationFooter.tsx
Looks like some test code was left in. Undid to fix the 'New' pills for notifications
> [QA-1732] Undo test code to fix unread pill check for notifications

- .circleci/config.yml
> Enable audiusd workflow in main release

- mediorum/server/qm_fix_truncated.go
- mediorum/server/serve_blob.go
- mediorum/server/server.go
- mediorum/server/sniff.go
> worker to fix truncated qm audio cids

- packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
- packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
Found two issues with comments disabled 
Desktop - the "more by" section is off a bit
Mobile web  - still showing comments
web:stage
> [C-5050] Comments disabled qa fixes

- packages/discovery-provider/ddl/README.md
- packages/discovery-provider/ddl/tests/chat_allowed_test.sql
remove accidental commit in a ddl test file.
> fix ddl tests.

- packages/discovery-provider/nginx_conf/nginx_container.conf
/metabase will just gateway err if no plugin is running at $upstream
> Add metabase nginx route

- packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
> Validate parent_comment_id type

- core/config/config.go
- core/config/genesis/prod.json
- core/config/genesis/stage.json
- core/infra/dev_config/content-one.docker.env
- core/infra/dev_config/content-three.docker.env
- core/infra/dev_config/content-two.docker.env
- core/server/comet.go
- core/server/server.go
- adds matching validators (count wise) in both stage and prod networks for comparison to acdc
running on stage currently
> Comet and ACDC matching validators

- packages/ddex/processor/README.md
- packages/ddex/processor/package.json
- packages/ddex/processor/sources.example.json
- packages/ddex/processor/src/db.ts
- packages/ddex/processor/src/server.ts
Update readme with sources config notes.
Adds `ADMIN_HANDLES` url to specify users who can see processing status ui.
> Update readme, add admin required middleware.

- packages/web/src/components/notification/Notification/components/ProfilePicture.module.css
> [PAY-3454] Cursor pointer on profile picture list items

- packages/mobile/src/screens/create-chat-blast-screen/ChatBlastSelectAudienceFields.tsx
- packages/web/src/pages/chat-page/components/ChatBlastModal.tsx
Hide the count if it's 0 or undefined
> [PAY-3447] Fix empty parens on audience count

- packages/discovery-provider/src/api/v1/playlists.py
Fixes dumb error in request parsing that prevented playlists splits from including network cut.
> Fix access-info fetching for playlists to include network cut

- packages/mobile/src/components/comments/CommentDrawerForm.tsx
- packages/mobile/src/components/comments/CommentForm.tsx
- packages/mobile/src/components/composer-input/ComposerInput.tsx
- packages/mobile/src/components/composer-input/index.ts
- packages/mobile/src/components/composer-input/types.ts
- packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
Created mobile ComposerInput component and updated the places for DMs and comments to use it
> [C-4995] Create mobile ComposerInput component for DMs and comments

- .circleci/src/commands/@docker-commands.yml
- .circleci/src/workflows/release.yml
- packages/ddex/processor/package.json
- packages/ddex/processor/src/db.ts
- packages/ddex/processor/src/parseDelivery.ts
- packages/ddex/processor/src/server.ts
> ddex genre mapping

- .circleci/src/@continue_config.yml
- .circleci/src/jobs/@audiusd-jobs.yml
- Makefile
- cmd/audius-ctl/main.go
- scripts/build-audius-ctl.sh
- scripts/get-new-audius-ctl-version.sh
- scripts/install-audius-ctl.sh
- scripts/release-audius-ctl.sh
Update release and build scripts to be compatible with monorepo
Run locally, shellcheck, experiment with CI
> Get audius-ctl release/install working in monorepo

- .circleci/src/commands/@docker-commands.yml
> Restore ddex enum value in ci

- packages/web/src/components/composer-input/ComposerInput.tsx
Small update to not detect timestamps if the user does not have premium access
> [C-5067] Update ComposerInput to not highlight timestamps for users without premium access

- docs/docs/distributors/specification/deal-types/recommended.mdx
- docs/docs/distributors/specification/deal-types/supported-deal-types.mdx
- docs/docs/distributors/specification/metadata.mdx
- docs/docs/distributors/specification/overview.mdx
- docs/sidebars.js
Add recommended section for ddex deal types
```
npm run start
```
> Add recommended ddex docs

- packages/common/src/api/user.ts
- packages/common/src/hooks/chats/useRemixersAudience.ts
> fix sdk remixed tracks usage

- packages/common/src/store/purchase-content/sagas.ts
Issue arises when token account is created and immediately read. In this case, it is ok to assume zero token balance.
stage, error goes away. notably iFrame error still present
> [QA-1750] Fix race cond in cc flow with token account creation

- packages/web/src/components/tracks-table/TracksTable.tsx
- packages/web/src/pages/dashboard-page/components/ArtistDashboardTracksTab.tsx
- packages/web/src/pages/dashboard-page/components/hooks.ts
- packages/web/src/pages/dashboard-page/components/types.ts
Add comment count to artist dashboard track table
> [C-5070] Add comment count to artist dashboard

- packages/mobile/src/components/comments/CommentDrawerHeader.tsx
- packages/web/src/components/comments/CommentSectionDesktop.tsx
Hide sort buttons when 0 or 1 comments
> [C-5028] Hide sort buttons with 1 or fewer comments

- .changeset/dirty-terms-teach.md
> Bump harmony by minor version

- .changeset/spotty-garlics-doubt.md
- packages/discovery-provider/plugins/pedalboard/apps/verified-notifications/package.json
- packages/discovery-provider/plugins/pedalboard/apps/verified-notifications/src/handlers/purchases.js
- packages/discovery-provider/plugins/pedalboard/apps/verified-notifications/src/index.js
- packages/discovery-provider/plugins/pedalboard/docker/startup.sh
- packages/fixed-decimal/package.json
- packages/fixed-decimal/scripts/makePackageTypes.sh
- packages/fixed-decimal/src/FixedDecimal.ts
- packages/fixed-decimal/src/currencies.ts
- packages/fixed-decimal/src/index.ts
Looks like:
`*Seller Username* (@seller_handle) just made a sale!`
```
buyer: Buyer Username (@buyer_handle)
content_title: Playlist Name
content_type: album
price: $1.00
payExtra: $0.00
access: stream
vendor: user_bank
buyer_user_id: 91857201
seller_user_id: 861900127
content_id: 28601903
```
Required fixing `@audius/fixed-decimal` to support CJS better, and updating the local replica script to fallback to DN 1 when not a replica
> Notify Slack on new purchases

- packages/common/src/messages/comments.ts
- packages/mobile/src/components/comments/CommentOverflowMenu.tsx
- packages/web/src/components/comments/CommentActionBar.tsx
* Update comment overflow actions on web and mobile to be consistent with designs
* Update web comment action styling
> [C-5057] Make comment overflow actions consistent with designs

- packages/common/src/messages/comments.ts
- packages/mobile/src/components/comments/CommentSection.tsx
- packages/web/src/components/comments/NoComments.tsx
* Small copy update to encourage artists to leave the first comment
> [C-5002] Empty comments state for track owner

- packages/web/src/components/edit/fields/download-availability/DownloadAvailability.tsx
> [QA-1749] Fix help alignment

- packages/mobile/src/components/comments/CommentDrawer.tsx
- packages/mobile/src/components/comments/CommentForm.tsx
- packages/mobile/src/components/composer-input/ComposerInput.tsx
Update mobile composer input to highlight timestamps based on the track
> [C-4998] Add timestamp highlighting to mobile composer input

- packages/web/src/components/composer-input/ComposerInput.tsx
- packages/web/src/components/user-generated-text/UserGeneratedTextV2.tsx
- packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css
- packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
> [PAY-3453] Fix @ mentions in Dms with UserGeneratedTextV2

- packages/web/src/components/composer-input/ComposerInput.tsx
Update the autocomplete range detection to not be determined by the cursor placement so that the replacement and highlighting work better and there is no bug with the replacement if the user is not at the end of the autocomplete string
> [PAY-3489] Update web ComposerInput autocomplete range tracking

- packages/common/src/context/comments/commentsContext.tsx
- packages/mobile/src/components/comments/CommentBlock.tsx
- packages/mobile/src/components/comments/CommentText.tsx
- packages/mobile/src/components/comments/TimestampLink.tsx
- packages/mobile/src/components/core/UserGeneratedText.tsx
- packages/web/src/components/comments/CommentBlock.tsx
- packages/web/src/components/comments/CommentText.tsx
- packages/web/src/components/comments/TimestampLink.tsx
* Wire up seeking via pressing the timestamp in the comment header on web & mobile
> [C-5072] Comment timestamp seeking

- packages/web/src/components/edit/fields/StemsAndDownloadsMenuFields.tsx
Forgot to remove this as part of removing monetization waitlist
```
```
> [PAY-3493] Fix download gating on usdc feature flag

- packages/web/src/common/store/pages/signon/reducer.js
- packages/web/src/common/store/pages/signon/types.ts
- packages/web/src/pages/sign-up-page/components/AccountHeader.tsx
- packages/web/src/pages/sign-up-page/pages/CreateEmailPage.tsx
* Skipping followers step
* Profile picture empty state
* Enter key not working on email page
Ran through sign up flow many times on localhost
> [QA-1748] Fix misc sign up issues

- packages/mobile/src/components/comments/CommentDrawer.tsx
- packages/mobile/src/components/comments/CommentDrawerForm.tsx
- packages/mobile/src/components/comments/CommentDrawerHeader.tsx
- packages/mobile/src/components/comments/CommentForm.tsx
- packages/mobile/src/components/composer-input/ComposerInput.tsx
- packages/mobile/src/components/composer-input/types.ts
- packages/web/src/components/composer-input/ComposerInput.tsx
Update the composer input on mobile to handle autocomplete update the comments drawer to display the search results while the user is autocompleting
> [C-4994] Add user autocomplete and tagging to mobile ComposerInput

- packages/mobile/src/components/composer-input/ComposerInput.tsx
Weird workaround for the ios backspace issue for TextInputs
> [C-5097] Add backspace handling back to mobile ComposerInput

- packages/mobile/src/components/comments/CommentDrawerForm.tsx
- packages/mobile/src/components/comments/CommentForm.tsx
- packages/mobile/src/components/composer-input/ComposerInput.tsx
- packages/mobile/src/components/composer-input/types.ts
- packages/mobile/src/components/core/TextInput.tsx
* Need to use BottomSheetTextInput, this was dropped when adding compose ui
> Fix bottom sheet keyboard avoiding + compose ui

- packages/mobile/src/components/core/TextInput.tsx
Small update to change the ref to a useMemo to rerender and change the border color
> [C-5069] Fix mobile ComposerInput border color on focus

- packages/mobile/src/components/comments/CommentOverflowMenu.tsx
> [C-5076] Fix issue with unpin message

- packages/mobile/src/components/comments/CommentDrawerForm.tsx
* Fix issue with edit state not clearing after finishing edit
> [C-5073] Fix issue with edit state persisting

- packages/mobile/src/screens/chat-screen/ChatBlastHeader.tsx
- packages/mobile/src/screens/chat-screen/ChatListBlastItem.tsx
- packages/web/src/pages/chat-page/components/ChatBlastHeader.tsx
- packages/web/src/pages/chat-page/components/ChatListBlastItem.tsx
use `formatCount` for audienceCount display. E.g. shows `1.2K` instead of `1234`
> [PAY-3484] Format audience counts

- packages/common/src/hooks/chats/useFirstAvailableBlastAudience.ts
- packages/mobile/src/screens/create-chat-blast-screen/ChatBlastSelectAudienceScreen.tsx
- packages/mobile/src/screens/create-chat-blast-screen/CreateChatBlastNavigator.tsx
- packages/web/src/pages/chat-page/components/ChatBlastModal.tsx
if all audiences are empty, disable submit button
> [PAY-3491] Don't allow chat blast create with empty audience

- packages/harmony/src/components/button/Button/Button.tsx
- packages/mobile/src/screens/track-screen/TrackScreen.tsx
- packages/web/src/pages/track-page/components/TrackRemixes.tsx
- packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
- packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
- packages/web/src/pages/track-page/utils.ts
Tried to re-use as much mobile code as possible!
> [C-5012] Refactor web track remixes UI

- pkg/conf/override.go
- pkg/orchestration/docker.go
Be strict about using remote configuration
Spinning up stage dn1 on audius-d
> Return error when remote config not found

- packages/web/src/components/search-users-modal/SearchUsersModal.tsx
Add position: sticky to the CTA so it can't be pushed off the bottom
> [PAY-3471] ChatBlastCTA should stick to the bottom

- packages/mobile/src/screens/chat-screen/ChatListItem.tsx
- packages/mobile/src/screens/chat-screen/ChatListItemSkeleton.tsx
- Migrate `ChatListItem` to harmony-native
- Fix text overflow with long names/handles
- Handle edge cases for badge and new message indicator
> [PAY-3465] Fix text overflow on mobile ChatList

- packages/mobile/src/components/details-tile/DetailsTileStats.tsx
- packages/mobile/src/components/lineup-tile/LineupTileStats.tsx
- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
- packages/web/src/components/comments/CommentSection.tsx
- packages/web/src/components/comments/CommentSectionDesktop.tsx
- packages/web/src/components/track/GiantTrackTile.tsx
- packages/web/src/components/track/TrackStats.tsx
- packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
- packages/web/src/pages/track-page/components/mobile/StatsButtonRow.tsx
- packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
* Fix bug preventing comment stat from displaying on track tile
* Allow clicking on comment stat on track page to navigate/scroll to comments. This now works on web, mobile-web, and mobile
> [C-5114] [C-5115] Comment stat display improvements

- packages/web/src/pages/chat-page/components/ChatBlastModal.tsx
- Back button now reopens CreateChatModal with previous parameters
works on local
> [PAY-3446] Fix back button in ChatBlastCTA

- packages/web/src/components/user-generated-text/UserGeneratedTextV2.tsx
> [C-5132] Add artist popover UserGeneratedTextV2

- packages/common/src/api/tan-query/comments.ts
- packages/discovery-provider/src/api/v1/tracks.py
Fixes server error due to currentUserId not being decoded
Fixes issue with optimistic updates
> Fix track comment notification setting

- packages/web/src/components/comments/CommentBlock.tsx
- packages/web/src/components/comments/CommentForm.tsx
- packages/web/src/components/composer-input/ComposerInput.tsx
- packages/web/src/components/composer-input/types.ts
Adds autoFocus to ComposerInput and hooks up functionality to comment-form for edit and reply
> [C-5186] Add autoFocus to ComposerInput

- packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
Fixes issue where tracks are duplicated instead of updated when a comment is pinned or unpinned
> Fix comment pin track update

- packages/mobile/src/components/comments/CommentOverflowMenu.tsx
> Remove duplicate turn off notifs

- packages/common/src/messages/comments.ts
> [C-5099] Pluralize the word replies correctly

- packages/mobile/src/components/comments/CommentDrawerForm.tsx
- packages/mobile/src/components/composer-input/ComposerInput.tsx
- packages/web/src/components/composer-input/ComposerInput.tsx
* Fix timestamps and mentions on mobile comments (we weren't passing it to the postComment call)
* Set user mention when replying on web and mobile (This will now also send a mention notification to the user as well as a reply notification)
> [C-5125, C-5147, C-5148] Web and Mobile Comment QA 1

- packages/common/src/api/tan-query/comments.ts
Missed this in the tan-query move
web:stage
> [C-5145] Add comment count increment logic

- packages/web/src/components/comments/CommentText.tsx
> [C-5140] Fix too big comment container

- packages/mobile/src/components/comments/CommentDrawerForm.tsx
- packages/mobile/src/components/composer-input/ComposerInput.tsx
- packages/web/src/components/composer-input/ComposerInput.tsx
* Add space after mention autocomplete
* Fix pre-search state for mobile autocomplete
> [C-5143, C-5146] Comments QA 2

- packages/common/src/messages/comments.ts
- packages/mobile/src/components/comments/CommentOverflowMenu.tsx
- packages/web/src/components/comments/CommentActionBar.tsx
- Fixes pin-comment web action
- Updates message from "turn off notifications" to "mute this thread"
- Fixes mobile actions, preventing pin and mute actions on reply comments.
> [C-5170 C-5175] Fix web pin action, update mute thread

- packages/mobile/src/screens/settings-screen/InboxSettingsFields.tsx
- packages/web/src/components/inbox-settings-modal/InboxSettingsModalNew.tsx
- Set value to true for each checkbox when allow all is toggled on
works per spec on web and mobile
> [PAY-3502] Toggle all boxes on when allowing all chats

- packages/mobile/src/components/composer-input/ComposerInput.tsx
- packages/web/src/components/composer-input/ComposerInput.tsx
Title
Manually tested. This helps a fair amount on mobile, not as noticeable on web but still good to do probably
> [C-5153] Update ComposerInput to not render the display layer unless there is highlighted text

- pkg/core/config/genesis/prod.json
- pkg/core/core.go
- pkg/core/registry_bridge/register.go
> turn off registry bridge and start new chain

- packages/mobile/src/screens/settings-screen/CommentSettingsScreen.tsx
- packages/web/src/components/artist/ArtistChip.tsx
- packages/web/src/components/artist/ArtistChipFollowers.tsx
- packages/web/src/components/comment-settings-modal/CommentSettingsModal.tsx
A few cosmetic fixes to muting flows.
* Remove follows you badge in comment settings.
* Adjust mobile comment setting row layout. 
* Close comment settings modal when navigating to artist.
Ran through these flows against staging.
> Remove follows you badge from comment settings

- packages/harmony/src/components/popup-menu/PopupMenu.module.css
Small change to add border to the menus
> [C-5184] Add border to Harmony PopoverMenu

- packages/mobile/src/components/comments/CommentForm.tsx
- packages/mobile/src/components/composer-input/ComposerInput.tsx
- packages/mobile/src/components/composer-input/types.ts
> [C-5155] Add cancel accessory to mobile ComposerInput for comments

- packages/mobile/src/components/comments/CommentBlock.tsx
- packages/web/src/components/comments/CommentBlock.tsx
Dates were shown in UTC instead of local time so "just now" would remain for hours in PST.
Timestamps look correct on mobile and web now.
> [C-5172] Fix comments timezone

- packages/discovery-provider/plugins/pedalboard/apps/relay/src/coreRelay.ts
> fix relay core error ref

- packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
Fix indexing by calling check for dupe validations in comment reports
> Fix comment report indexing errors in staging

- packages/common/src/api/tan-query/comments.ts
Comments not working for un-authed users at the moment
web:stage
> Fix comment unauthed state

- packages/web/src/components/user-generated-text/UserGeneratedTextV2.tsx
Newlines are indexed but not displayed in web, mobile doesn't have this issue. 
> [C-5178] Show newlines in comments

- packages/mobile/src/harmony-native/components/Button/BaseButton/BaseButton.tsx
- packages/mobile/src/screens/track-screen/TrackScreen.tsx
Broken in https://github.com/AudiusProject/audius-protocol/commit/af09710dbf5308487351db68ca4a36f3df2597b3
```
npm run lint:fix
```
> Fix mobile lint

- packages/web/src/components/comments/CommentBlock.tsx
- packages/web/src/components/comments/CommentForm.tsx
- packages/web/src/components/comments/CommentText.tsx
- packages/web/src/components/composer-input/ComposerInput.tsx
- packages/web/src/components/composer-input/types.ts
- packages/web/src/components/user-generated-text/UserGeneratedTextV2.tsx
Use the work that is done by user-generated text to set the user mentions for the edit flow for comments
Also cleans up the reply highlighting a bit
> Highlight user mentions when editing comments on web

- comms/discovery/db/queries/get_new_blasts.go
- comms/discovery/rpcz/chat_blast_test.go
If you edit inbox settings at time t... only blasts after t will seed conversation.
> [PAY-3518] Get new blasts after inbox settings change

- packages/mobile/src/screens/chat-screen/ChatBlastSubHeader.tsx
- packages/mobile/src/utils/zIndex.ts
> [PAY-3519] Fix mobile ChatBlastSubHeader opacity

- packages/mobile/src/components/composer-input/ComposerInput.tsx
> [C-5191] Add background color to comment cancel accessory view

- packages/web/src/components/comments/CommentBlock.tsx
> [C-5193] Add cancel button to comment replies and edits

- packages/discovery-provider/ddl/migrations/0095_shorten_challenge_ids.sql
Should have double checked this...
Fixes #10094
> Fix typo in migration

- packages/mobile/src/components/comments/CommentDrawer.tsx
* Remove `keyboardShouldPersistTaps='handled'`
> [C-5112] Dismiss keyboard when pressing in comment drawer

- .circleci/src/jobs/@web-jobs.yml
Previous build kept running out of memory during npm install.
https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/61991/workflows/f7413f0b-44f3-4576-9964-11b61e15bdac
> Upgrade macos resource class for web build

- packages/mobile/src/components/comments/CommentForm.tsx
> Fix mobile cursor position

- packages/discovery-provider/src/api/v1/models/tracks.py
- packages/sdk/src/sdk/api/generated/full/models/SearchTrackFull.ts
- packages/sdk/src/sdk/api/generated/full/models/TrackFull.ts
`pinnedCommentId` was getting marshalled out
web:dev
> [C-5201] Fix comments not showing as pinned

- packages/web/src/components/comments/CommentSectionMobile.tsx
- packages/web/src/components/comments/CommentSkeletons.tsx
- packages/web/src/pages/track-page/TrackCommentsPage.tsx
Clean up mobile web skeletons
NOTE: I do want to refactor the skeletons across web/mboile a bit more but I want to quick ship this fix for now - there are more changes needed with web anyways so can tackle later
web:stage + chrome iphone 12 sim
> [C-5189] Fix mobile web skeletons

- packages/common/src/adapters/notification.ts
- packages/discovery-provider/integration_tests/tasks/entity_manager/test_comment.py
- packages/discovery-provider/integration_tests/utils.py
- packages/discovery-provider/src/api/v1/models/notifications.py
- packages/discovery-provider/src/api/v1/utils/extend_notification.py
- packages/discovery-provider/src/queries/get_notifications.py
- packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
- packages/mobile/src/components/comments/CommentText.tsx
- packages/sdk/src/sdk/api/generated/full/models/CommentNotificationActionData.ts
- packages/web/src/components/composer-input/ComposerInput.tsx
Fixes various elements related to comment notifications:
1. Updates "comment" notification types to use "comment_user_id"
2. Updates "comment_thread" generation to use the correct types
3. Fixes user-mentions on replies. There are still plenty of outstanding issues with mentions.
4. Fixes key errors on web
5. First step in a fix for mobile "show-more"/"show-less"
> Fix discovery comment notifications

- packages/common/src/adapters/notification.ts
- packages/mobile/src/components/core/UserGeneratedText.tsx
Fixes native show more/less collapse.
Small fix i noticed with notif parsing
> [C-5197] Fix native comment show more/less collapse

- packages/mobile/src/components/collection-list/CollectionCard.tsx
- packages/mobile/src/components/user-link/UserLink.tsx
- packages/mobile/src/components/user-list/UserCard.tsx
Small regression due to our text-link refactor, easy fix though.
> [QA-1737] Center user links in collection and user cards

- packages/mobile/src/components/comments/CommentBlock.tsx
Simple fix to prevent badges from getting pushed off screen. 
> [C-5163 Fix commenter name overflowing

- packages/mobile/src/components/comments/CommentActionBar.tsx
- packages/web/src/components/comments/CommentActionBar.tsx
Hide the 0 text for react count < 1
web:stage
> [C-5230] Hide 0 react counts

- packages/discovery-provider/src/tasks/entity_manager/entities/track.py
Existing clients that send no metadata error here
Tested via python repl. Will test against stage, easier to do than locally
> Add metadata checks to track_downloads indexing

- packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
Comment mention reverts missing
> Fix comment mention reverts

- packages/discovery-provider/src/tasks/entity_manager/entities/track.py
This reverts commit 59a6c1db69bd1deab3b4bcbeb9ce91da9bf9af6e.
Better fix in #10136
> Revert "Unblock download track geo indexing (#10135)"

- packages/common/src/api/tan-query/comments.ts
- packages/mobile/src/components/comments/CommentBlock.tsx
- packages/web/src/components/comments/CommentBlock.tsx
For now this is just the client side fixes; not fixed the backend yet
web:stage
> [C-5075] Fix tan-query not handling tombstone states

- packages/discovery-provider/src/queries/get_comments.py
Ensures artist report is part of filter in get_comments endpoint
> [C-5221] Artist report removes comment for everyone

- .changeset/strange-dolls-drive.md
- packages/sdk/src/sdk/config/production.ts
Should probably automate this on SDK release
> Update services bootstrap list

- packages/web/src/components/composer-input/ComposerInput.tsx
Small fix to ensure mentions work with existing setup. This will all be improved anyway with kj's code
> Fix issue with mentions for create/reply/edit

- packages/mobile/src/components/comments/CommentForm.tsx
- packages/mobile/src/components/composer-input/ComposerInput.tsx
- packages/mobile/src/components/composer-input/types.ts
- packages/web/src/components/comments/CommentForm.tsx
- packages/web/src/components/composer-input/ComposerInput.tsx
- packages/web/src/components/composer-input/types.ts
I had Cursor write this entire feature and probably spent more time cleaning up the code it output that it would've take me to just write it 😢 
Tested iOS, android, and web
> [C-5257] Limit mentions to 10 in ComposerInput

- pkg/core/config/genesis/prod.json
i think the mismatched genesis halted the chain on prod, this will unstick it
> new prod chain

- packages/discovery-provider/plugins/notifications/src/__tests__/mappings/comment.test.ts
- packages/discovery-provider/plugins/notifications/src/__tests__/mappings/commentMention.test.ts
- packages/discovery-provider/plugins/notifications/src/__tests__/mappings/commentThread.test.ts
Updates to comment notification plugin push notifs needed some test updates
> Fix comment notification tests

- packages/mobile/src/screens/audio-screen/Tier.tsx
- packages/web/src/components/user-badges/TierExplainerDrawer.tsx
- packages/web/src/components/user-badges/TierExplainerModal.module.css
- packages/web/src/components/user-badges/TierExplainerModal.tsx
- packages/web/src/pages/audio-rewards-page/Tiers.module.css
- packages/web/src/pages/audio-rewards-page/Tiers.tsx
Update UI for VIP $AUDIO Tier lists. Also make code a bit more "wet" to prevent bugs from component sharing. Mobile has yet to be designed, but these changes account for mobile web.
Did a brief QA run with design
```
```
> [PAY-3536] Improve $AUDIO VIP Tier UI

- packages/web/src/components/composer-input/ComposerInput.tsx
> [C-5263] Blur comment after submitting

- packages/common/src/api/tan-query/comments.ts
- packages/sdk/src/sdk/api/comments/CommentsAPI.ts
Fixes indexing issue currently on staging. 
Ye old entity id strikes again
web:stage
> Update metadata for comment edit to be trackId

- packages/common/src/api/tan-query/comments.ts
- packages/common/src/context/comments/commentsHooks.ts
- packages/mobile/src/components/comments/CommentBlock.tsx
- packages/mobile/src/components/comments/CommentDrawerForm.tsx
- packages/mobile/src/components/comments/CommentForm.tsx
- packages/mobile/src/components/comments/CommentText.tsx
- packages/mobile/src/components/composer-input/ComposerInput.tsx
- packages/mobile/src/components/composer-input/types.ts
- packages/mobile/src/components/core/UserGeneratedText.tsx
- packages/web/src/components/comments/CommentBlock.tsx
- packages/web/src/components/comments/CommentForm.tsx
- packages/web/src/components/comments/CommentText.tsx
- packages/web/src/components/composer-input/ComposerInput.tsx
- packages/web/src/components/composer-input/types.ts
- packages/web/src/components/user-generated-text/UserGeneratedTextV2.tsx
Updated web to respect the mentions coming back from the backend and pass the mentions in the new format
> [C-5185, C-5246, C-5250, C-5254] Update web and mobile comments to respect mentions being passed back from the backend

- pkg/core/core.go
- pkg/core/server/server.go
thought i did this already but i guess not, exposes pprof so we can tune core performance
> expose pprof

- packages/web/src/components/stat-banner/StatBanner.tsx
Looked for better solutions, but I think this will do.
Message button now appears on profile page when unauthed. Clicking the button redirects to signup
> [PAY-3553] Show chat button when unauthed

- packages/mobile/src/harmony-native/components/IconText/IconText.tsx
Only usage of this component is here
Before:
After:
local simulator
> [C-5277] Fix alignment of comment "artist pick" on mobile

- packages/mobile/src/components/composer-input/ComposerInput.tsx
Fix composer input for messages
locally doesn't crash anymore
> Fix composer input for chats

- packages/common/src/utils/route.ts
> [QA-1766] Update audius careers link

- packages/common/src/store/user-list/notifications/selectors.ts
Before
After
Local web vs stage
> [C-5285] Fix comment notification user list title

- packages/common/src/api/tan-query/comments.ts
Teeny logic error with artist liked and optimistic changes
web;stage
> Fix liked by artist logic error

- packages/mobile/src/components/comments/CommentDrawerForm.tsx
Use TrackPlayer.getPosition instead of selector
> [C-5276] Fix timestamp stuck on mobile comments

- packages/web/src/components/data-entry/TextAreaV2.module.css
- packages/web/src/components/user-generated-text/UserGeneratedTextV2.tsx
- packages/web/src/public-site/pages/landing-page/LandingPage.module.css
> Harmonize text selection color

- packages/web/src/components/comments/CommentHeader.tsx
> [C-5162] Fix comment mute overflow position

- packages/discovery-provider/integration_tests/tasks/entity_manager/test_comment.py
- packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
- packages/discovery-provider/src/tasks/entity_manager/utils.py
Add more comment validations to protect these rules:
- Only user and track owner can delete tracks.
- Only track owner can pin track.
- Character limit on track
- Comment metadata track must exist
Added more tests against these
> Add more comment validations

- packages/web/src/components/data-entry/TextAreaV2.module.css
> [C-5239] Fix horizontal overflow in composer input

- packages/web/src/components/data-entry/TextAreaV2.module.css
> [C-5237] Fix ComposerInput height

- .changeset/seven-mugs-bow.md
- packages/harmony/src/utils/formatTrackTimestamp.ts
- packages/web/src/utils/Moods.tsx
- Fix duration formatting for PlayBar scrubber
- Fix emoji alignment on mood
working locally
> Fix timestamp formatter + mood emoji alignment

- packages/web/src/components/track/desktop/ConnectedTrackTile.tsx
> Truncate followee reposts and saves in TrackTile

- pkg/core/server/server.go
> more useful profiling stuff

- packages/web/src/components/user-generated-text/UserGeneratedTextV2.tsx
> [C-5300] Fix import in UserGeneratedTextV2 to fix link unfurls

- packages/mobile/src/components/composer-input/ComposerInput.tsx
The default empty array here causes the component to rerender loop infinitely when not provided by parent
local with simulator
> Fix DM render loop

- packages/mobile/src/hooks/useNotificationNavigation.ts
- packages/web/src/components/notification/Notification/CommentMentionNotification.tsx
- packages/web/src/components/notification/Notification/CommentNotification.tsx
- packages/web/src/components/notification/Notification/CommentReactionNotification.tsx
- packages/web/src/components/notification/Notification/CommentThreadNotification.tsx
- packages/web/src/components/notification/Notification/components/EntityLink.tsx
Fixes notification reaction linking on mobile
Fixes linking on web
> Fix notification linking and comment reaction notifications

- packages/mobile/src/components/comments/CommentBlock.tsx
- packages/mobile/src/components/user-link/UserLink.tsx
fixes this clipping issue
before
ios:stage
> [C-5304] Fix text clipping on mobile due to emojis

- packages/discovery-provider/plugins/notifications/src/__tests__/mappings/comment.test.ts
- packages/discovery-provider/plugins/notifications/src/__tests__/mappings/commentMention.test.ts
- packages/discovery-provider/plugins/notifications/src/__tests__/mappings/commentReaction.test.ts
- packages/discovery-provider/plugins/notifications/src/__tests__/mappings/commentThread.test.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/comment.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/commentMention.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/commentReaction.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/commentThread.ts
- packages/mobile/src/hooks/useNotificationNavigation.ts
Fixes subtle issue with comment push notification data, where the entity_type is lowercase when it should be cap-case
> [C-5310] Fix comment notification deep links

- packages/mobile/src/components/core/UserGeneratedText.tsx
- packages/web/src/components/user-generated-text/UserGeneratedTextV2.tsx
> [C-5306] Update UserGeneratedText Links to show url on fetch fail

- packages/web/src/components/upload/InvalidFileType.jsx
> Not hardcoded file limit error message

- packages/mobile/android/app/build.gradle
- packages/mobile/ios/AudiusReactNative/Info.plist
> Upgrade mobile version to 1.1.121

- packages/common/src/utils/uploadConstants.ts
was 250 now is 500! 🔋 
```
```
> Bump max audio size to 500mb

- packages/harmony/src/components/button/Button/Button.tsx
- packages/mobile/src/harmony-native/components/Button/Button/Button.tsx
Fixes 'xs' variant for harmony mobile button. In most cases it's rendering normal styles when it should be rendering small styles.
> Fix mobile harmony button xs size

- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/comment.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/commentMention.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/commentReaction.ts
- packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/commentThread.ts
For some reason this.notification.data.type wasn't working, so went with explicit "Track" for now to save the headache
> [C-5310] Fix comment notifications with explicit type

- packages/discovery-provider/ddl/migrations/0102_shorten_challenge_ids.sql
🤦‍♂️  forgot to remove the rollback from the testing query
> Don't rollback the migration

- packages/discovery-provider/ddl/migrations/0102_shorten_challenge_ids.sql
Hoping this will unstick the stuck nodes by making them have a different docker compose version too
> Add more guards to the migration for idempotency

- packages/web/src/components/comments/CommentForm.tsx
- packages/web/src/components/composer-input/ComposerInput.tsx
- packages/web/src/components/composer-input/types.ts
Ooops I blurred DM chats too which should stay enabled to keep the conversation going.
Confirmed against stage.
> Blur on submit for comments but not DMs

- packages/mobile/src/screens/track-screen/DownloadSection.tsx
- packages/web/src/components/track/DownloadSection.tsx
FIxed decimal USDC toLocaleString takes care of this
Fix double $$
> [QA-1797] Fix double $

- packages/common/src/api/tan-query/comments.ts
- packages/discovery-provider/integration_tests/queries/test_get_comments.py
- packages/discovery-provider/src/queries/get_comments.py
Increase the page size from 5->15
web:stage - once this hits staging will check it out on mobile too
> [C-5338] Increase comment page size from 5->15

- comms/discovery/rpcz/apply.go
- comms/discovery/rpcz/peer_client.go
- packages/discovery-provider/ddl/migrations/0103_rewind_rpc_cursor.sql
Rewind cursor a few days to get any dropped messages.
> Use msgpack for push between comms servers

- packages/mobile/src/components/comments/CommentBlock.tsx
- packages/web/src/components/comments/CommentBlock.tsx
> [C-5061] Add fade in animation to comments

- packages/common/src/store/buy-usdc/sagas.ts
There's an edge case with the recovery flow that will cause balance to show zero.
1. Start the withdrawal flow. Once the Coinflow modal opens, click outside immediately.
2. Optionally, click again to close the withdrawal modal with the loading spinner
3. Watch the spinner where the USDC balance would normally be.
Sometimes it will refresh and show an empty balance. This is due to the fact that we don't wait for the recovery transaction to finalize before starting balance polling and balance polling was set to 3 retries spaces 1 second apart. It's possible during certain parts of the day that a Solana transaction that has been confirmed is not yet reflected in the RPC after 3 seconds. So you would poll thrice and then exit the saga, resulting in the balance showing as zero.
To solve this I …
> [PAY-3572] Wait for recovery transaction to finalize before polling balance change

- packages/libs/src/services/creatorNode/CreatorNode.ts
This should be passing the actual wallet we set on CreatorNode
N/A
> Undo temp hack used during account endpoint migration

- packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/clm.ts
Not sure what was going on. knex query builder kinda hard to test so switch to raw sql and ran the test.
Ran raw sql on prod dn database
> [PROTO-1966] Switch CLM to raw sql to fix missing Artist

- packages/mobile/src/components/core/UserGeneratedText.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeader/Bio.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeader/CollapsedSection.tsx
- packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx
* Changes to our TextLink component caused the absolute position to no longer work. Wrapping in a View fixes this
* Small rename from isExpansible to isExpanable
Tested that links get positioned properly and CommentText and dms UserGeneratedText are not impacted
> [C-5294] Fix mobile bio description links positioning

- packages/mobile/src/components/core/Screen/ScreenPrimaryContent.tsx
- packages/mobile/src/screens/track-screen/TrackScreen.tsx
- packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Small cleanup from client technical sync
Tested on android device against stage
> Cleanup TrackScreen snappiness

- pkg/core/console/uptime.go
- pkg/core/console/views/pages/uptime_page.templ
- pkg/core/console/views/pages/uptime_page_templ.go
As title
Ran prod sandbox locally to ensure correct messaging appears instead of error.
> Don't display error code when no sla rollups are available

- packages/web/src/components/comments/CommentActionBar.tsx
- packages/web/src/components/comments/CommentForm.tsx
> [C-5430] Make mobile CTA preferred over sign up CTA (mobile web)

- packages/discovery-provider/plugins/pedalboard/apps/relay/src/config/rateLimitConfig.ts
- packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimiter.ts
- packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/validator.ts
- packages/discovery-provider/plugins/pedalboard/apps/relay/src/server.ts
- packages/discovery-provider/plugins/pedalboard/apps/relay/src/utils.ts
- adds a new anonymous field to rate limits
- sets this new rate limit to reasonable values for create user, update user, downloadtrack, view notification, and viewplaylistnotification
- updates logs to have more data when rate limits are hit
- updates the determineLimit function to be more explicit about which limit is being used
> update relay rate limits

- packages/discovery-provider/src/queries/get_track_signature.py
Fix missing download signature param
> Fix download signature

- packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
I started to go down a refactor rabbit hole making the tile better flex based and stuff -
Instead this is probably just the simplest fix lol
web:prod
> [C-5305] Fix profile page tile text overflowing

- packages/common/src/utils/chatUtils.ts
> [C-5301] Update track and collectino unfurl string order

- packages/common/src/services/sdk/discovery-node-selector/DiscoveryNodeSelectorService.ts
Newlines were causing the blocklist to not be respected
> Trim whitespace in discovery node block list

- packages/discovery-provider/ddl/migrations/0104_revert_is_stream_gated_drop.sql
> Optimize revert stream gated drop

- packages/mobile/src/screens/explore-screen/ExploreScreen.tsx
- packages/mobile/src/screens/favorites-screen/FavoritesScreen.tsx
- packages/mobile/src/screens/feed-screen/FeedScreen.tsx
- packages/mobile/src/screens/notifications-screen/NotificationsScreen.tsx
- packages/mobile/src/screens/trending-screen/TrendingScreen.tsx
- Wrap all the main screens in Primary/Secondary deferred loading blocks
https://github.com/user-attachments/assets/59f19520-053c-40eb-86b9-1e9920066c1f
> [C-5360] Bottom bar screens deferred loading perf improvement

- packages/mobile/android/app/build.gradle
- packages/mobile/android/settings.gradle
- packages/mobile/ios/fastlane/Fastfile
Apple now requires lookups to be https
> Fix fastlane version number check

- .circleci/src/workflows/harmony.yml
Work needs to be done to fix harmony build. Let's add to jail entirely to prevent unnecessary work
> Harmony build to jail

- packages/mobile/patches/react-native+0.74.6.patch
> Fix react-native patch

- packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
- packages/mobile/src/screens/track-screen/TrackScreen.tsx
> Use skeletons for track and collection screens

- packages/mobile/src/screens/feed-screen/FeedScreen.tsx
We want feed loading right away
> Remove primary/secondary loading for feed screen

- .circleci/src/jobs/@mobile-jobs.yml
- .circleci/src/jobs/@web-jobs.yml
Upgrades xcode from 15x to 16x. Seeing if this is needed for the light/dark/tinted icons to work properly
> Upgrade xcode to 16.1

- packages/mobile/android/settings.gradle
- packages/mobile/ios/AudiusReactNative.xcodeproj/project.pbxproj
Attempts to fix ios build by disabling bitcode.
Fixes android build by updating radial-gradient-import
> Fix ios and android builds

- packages/mobile/src/components/comments/CommentForm.tsx
- packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
> [QA-1798] Close keyboard on submit for comments and DMs on mobile

- packages/common/src/schemas/metadata.ts
- packages/web/src/components/edit/fields/StemsAndDownloadsField.tsx
- packages/web/src/components/edit/fields/StemsAndDownloadsMenuFields.tsx
- packages/web/src/components/edit/fields/download-availability/DownloadPriceField.tsx
- packages/web/src/components/edit/fields/types.ts
Adds field to stems for direct publishing 
Upload flow -> Stems & Download -> Premium tab -> Direct publishing payments
> [PAY-3559] Add direct publishing payments to Stems

- packages/sdk/src/sdk/api/albums/types.ts
- packages/sdk/src/sdk/api/playlists/PlaylistsApi.ts
- packages/sdk/src/sdk/api/playlists/types.ts
- packages/sdk/src/sdk/api/tracks/TrackUploadHelper.ts
- packages/sdk/src/sdk/api/tracks/TracksApi.ts
- packages/sdk/src/sdk/api/tracks/types.ts
Populates previewStartSeconds + placement_hosts for premium album uploads.
> SDK: album upload populates mediorum upload options.

- packages/discovery-provider/src/tasks/entity_manager/entities/user.py
> Fix connect-verified indexing

- packages/mobile/src/components/comments/CommentBlock.tsx
- packages/mobile/src/components/comments/CommentThread.tsx
Title
There were transient issues with rerenders lowing the animation down so I'll keep an eye out for those
> [C-5220] Add comment reply animations on mobile

- packages/discovery-provider/ddl/migrations/0105_fix_durante.sql
- packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py
- packages/discovery-provider/src/tasks/entity_manager/entities/track.py
- packages/discovery-provider/src/tasks/entity_manager/utils.py
- packages/discovery-provider/src/tasks/metadata.py
Remove hard-coded list of apps, fix `ImDurante` tracks with migration
> Fix ddex ownership perms

- packages/mobile/src/screens/edit-track-screen/screens/AdvancedScreen.tsx
> Fix null error

- .changeset/twelve-wolves-leave.md
- packages/eth/package.json
@audius/eth not being published is breaking the latest version of the sdk
> Make @audius/eth public

- .github/workflows/publish-packages.yml
> Include @audius/eth in paths filter

- package-lock.json
- packages/common/package.json
- packages/mobile/package.json
Fixes sublte issue where multiple versions of formik were running at thet same time, leading to issues where useFormikContext failed, breaking sign up
> Fix sign up issue related to formik version issues

- pkg/mediorum/server/replicate.go
- pkg/mediorum/server/transcode.go
> Fix 30s preview generation

- packages/sdk/src/sdk/services/Auth/AppAuth.ts
needed for sdk to update 30s preview.
> Implements AppAuth.hashAndSign

- pkg/core/config/genesis/prod.json
- pkg/core/config/genesis/stage.json
these can't be zero, chat failed me
> fix genesis

- pkg/core/core.go
seeing some time outs on stage, boost these a little to stabilize
> increase timeouts to stabilize block production

- packages/common/src/hooks/useChangeEmailFormConfiguration.ts
- packages/identity-service/src/routes/authentication.js
Also removes guard from letting you set your email to an email you've used before.
> Add copius logs to change email flow

- packages/identity-service/test/authenticationTest.js
> Remove unnecessary identity authentication test

- packages/mobile/src/screens/profile-screen/ProfileScreen.tsx
> Fix profile screen content not rendering

- packages/discovery-provider/src/tasks/entity_manager/entities/track.py
> Set is_downloadable when download_conditions are present

- packages/common/src/api/user.ts
- packages/mobile/src/components/comments/CommentDrawer.tsx
- packages/mobile/src/components/composer-input/ComposerInput.tsx
- packages/web/src/components/composer-input/components/UserMentionAutocompleteText.tsx
Uses the followers list to show a default list of users when typing @ instead of showing "search users"
web & ios stage
> [C-5368] Default @handles list for comments

- packages/web/src/components/notification/Notification/TierChangeNotification.tsx
> [QA-1811] Fix tier change notif capitalization

- packages/common/src/utils/challenges.ts
> [QA-1812] Update referred reward progress label

- packages/mobile/src/components/skeleton/Skeleton.tsx
- packages/mobile/src/screens/profile-screen/ProfileScreenSkeleton.tsx
Make profile screen skeleton look better with white background.
> Fix mobile profile skeleton background color

- Makefile
- packages/discovery-provider/src/tasks/index_core.py
- pkg/core/core.go
> sleep in core indexing

- packages/discovery-provider/src/tasks/entity_manager/entities/track.py
> Fix is_downloadable being set erroneously

- packages/web/src/components/tracks-table/TracksTable.tsx
> [QA-1815] Render track actions for deleted tracks in tables

- .circleci/config.yml
- packages/mobile/android/app/build.gradle
- packages/mobile/ios/AudiusReactNative/Info.plist
* fix sed command to work on linux
* bump mobile versions to match current release branch, this script will bump them again when the branch is created
> Fix client release creation

- .circleci/src/commands/@docker-commands.yml
- .circleci/src/jobs/@audiusd-jobs.yml
- .circleci/src/workflows/audiusd.yml
- Makefile
- cmd/audiusd/Dockerfile
- cmd/audiusd/entrypoint.sh
- cmd/audiusd/env/dev.env
- cmd/audiusd/env/prod.env
- cmd/audiusd/env/stage.env
- cmd/audiusd/main.go
- pkg/core/config/config.go
- pkg/mediorum/mediorum.go
audiusd will soon replace mediorum, postgres, and core containers. This PR makes it functional on stage nodes in tandem with this [audius-docker-compose](https://github.com/AudiusProject/audius-docker-compose/compare/stage...phelpsdb-audiusd) branch.
Active for all stage content nodes.
> audiusd + audius-docker-compose compatibility

- packages/common/src/schemas/sign-on/finishProfileSchema.ts
- packages/common/src/utils/route.ts
- packages/web/src/common/store/pages/signon/sagas.ts
- packages/web/src/components/track/TrackTileStats.tsx
- packages/web/src/components/track/mobile/PlaylistTile.tsx
- packages/web/src/components/welcome-modal/WelcomeModal.tsx
- packages/web/src/pages/sign-up-page/SignUpPage.tsx
- packages/web/src/pages/sign-up-page/components/AccountHeader.tsx
- packages/web/src/pages/sign-up-page/components/SkipButton.tsx
- packages/web/src/pages/sign-up-page/pages/CreateEmailPage.tsx
- packages/web/src/pages/sign-up-page/pages/FinishProfilePage.tsx
- packages/web/src/pages/sign-up-page/pages/LoadingAccountPage.tsx
- packages/web/src/pages/sign-up-page/pages/PickHandlePage.tsx
- packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
- packages/web/src/pages/sign-up-page/pages/SelectGenresPage.tsx
- packages/web/src/pages/sign-up-page/utils/useDetermineAllowedRoutes.ts
When a user opens a referral link, we allow the user to skip straight to their feed without selecting genres or artists. It also makes photo and display name optional.
Some of this code has "skip-button" but that is not being used currently, just didnt want to do too much cleanup for now.
> [C-5381] Fast sign-up for referrals

- packages/discovery-provider/src/tasks/entity_manager/entities/track.py
- packages/discovery-provider/src/tasks/metadata.py
Small updates to allow a few extra fields on track editable so that we can replace track audio
Tested on local stack
> Update DiscoverProvider to handle replacing track audio

- packages/discovery-provider/src/queries/get_users_account.py
Some users don't have handles yet. They might not have finished sign up flow or they are in a guest account state. 
Tested in sandbox and user without handle works.
> Allow user lookup for guest accounts

- packages/common/src/schemas/metadata.ts
- packages/common/src/store/upload/actions.ts
- packages/discovery-provider/src/tasks/metadata.py
- packages/web/src/common/store/cache/tracks/sagaHelpers.ts
- packages/web/src/common/store/cache/tracks/sagas.ts
- packages/web/src/common/store/upload/sagas.ts
I'll update later, ask Andrew
Tested on local stack
> [C-5399] Add saga and basic setup for track audio replace

- packages/web/src/common/store/cache/tracks/sagas.ts
- packages/web/src/common/store/upload/sagas.ts
title
Tested sort of, local wasn't generating previews but we think it will work
> [C-5401] Add preview updates for track audio replace

- docs/docs/developers/subgraph/entities.mdx
- docs/docs/developers/subgraph/overview.mdx
- update graph URL
- Alphabetize and minor formatting to `entities` page
> [DOCS] - TheGraph URL update

- packages/common/src/adapters/track.ts
- packages/sdk/src/sdk/api/tracks/types.ts
Small updates to pass the proper fields to update the track audio
Manual Tested
> [C-5417] Update track audio replace for sdk change

- packages/common/src/audius-query/createApi.ts
- packages/common/src/hooks/purchaseContent/constants.ts
- packages/common/src/hooks/purchaseContent/usePurchaseContentFormConfiguration.ts
- packages/common/src/hooks/purchaseContent/validation.ts
- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/common/src/services/audius-backend/RecordIP.ts
- packages/common/src/services/remote-config/feature-flags.ts
- packages/common/src/store/account/index.ts
- packages/common/src/store/account/sagas.ts
- packages/common/src/store/cache/users/selectors.ts
- packages/common/src/store/purchase-content/sagas.ts
- packages/common/src/store/purchase-content/slice.ts
- packages/common/src/store/purchase-content/types.ts
- packages/common/src/store/ui/modals/coinflow-onramp-modal/index.ts
- packages/discovery-provider/src/queries/get_users_account.py
- packages/libs/src/api/Account.ts
- packages/libs/src/api/Users.ts
- packages/libs/src/utils/types.ts
- packages/web/src/common/store/account/sagas.js
- packages/web/src/common/store/cache/users/sagas.ts
- packages/web/src/common/store/pages/signon/sagas.ts
- packages/web/src/components/coinflow-onramp-modal/CoinflowOnrampModal.tsx
- packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
- packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx
- packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFooter.tsx
- packages/web/src/components/track/GatedContentSection.tsx
Taking the basic parts of the guest checkout demo and putting it behind a feature flag. When feature flag is disabled, clicking buy will redirect to sign up. When it's enabled, it will ask for an email input to be used for guest sign up and purchase. 
Confirmed purchase flow when feature flag is disabled and enabled works as expected.
> [C-5416] Basic guest checkout behind feature flag

- packages/web/src/components/related-artists/RelatedArtists.tsx
> Remove RELATED_ARTISTS_ON_PROFILE_ENABLED feature flag

- packages/common/src/services/remote-config/feature-flags.ts
- packages/web/src/common/store/account/sagas.js
- packages/web/src/components/related-artists/RelatedArtists.tsx
> [C-5430] Add feature flag for track audio replace

- pkg/mediorum/server/serve_upload.go
> Fix update upload endpoint

- pkg/core/chain/abci.go
- pkg/core/mempool/mempool.go
- exclude expired txs from GetBatch so the batch remains full
- every 100th block fire off async process to remove expired txs
> [PROTO-1983] rm expired txs from mempool

- docs/docs/node-operator/setup/hardware-requirements.mdx
> Bump discovery node

- packages/web/src/components/edit-track/EditTrackForm.tsx
- packages/web/src/components/file-replace-container/FileReplaceContainer.tsx
- packages/web/src/pages/edit-page/EditTrackPage.tsx
- packages/web/src/pages/upload-page/UploadPage.tsx
Make small changes to the FileReplaceContainer and add it to the upload flow
> [C-5405] Update upload flow with file replace

- dev-tools/audius-cmd
- package-lock.json
- packages/commands/package.json
- packages/commands/turbo.json
Got tired of the long startup time on each run due to all of the ES module loading, so I added ESBuild, hooked up turbo (so it actually rebuilds when SDK changes), and added a `watch` command so it's easy to dev on this locally.
TODO:
* Move it all to Typescript? 😁 
Lots of local dev, and will make sure CI works correctly
> Better audius-cmd

- packages/discovery-provider/src/api/v1/models/users.py
- packages/discovery-provider/src/api/v1/users.py
- packages/discovery-provider/src/models/users/email.py
- packages/discovery-provider/src/queries/download_csv.py
- packages/sdk/src/sdk/api/generated/default/apis/UsersApi.ts
This PR adds the necessary endpoint for accessing email data. This endpoints will be used to retrieve keys for decryption and to retrieve a complete list of emails that are associated with a specific userId 
Sample response 
```json
{
"decryption_key": "ABC123XYZ456DefBase64EncodedKey==",
"sales": [
{
"title": "TEST",
"link": "/reed/test",
"purchased by": "name 40F0",
"date": "2024-11-21T21:40:07.943031",
"sale price": 2.0,
"network fee": -0.2,
"pay extra": 0.0,
"total": 1.8,
"country": null,
"encrypted_email": "Base64EncodedEncryptedEmail1Content=="
},
{
"title": "BuyMePlease",
"link": "/reed/buymeplease",
"purchased by": "name E769",
"date": "2024-11-21T21:40:02.697436",
"sale price": 2.0,
"network fee": -0.2,
"pay extra": 0.0,
"total": 1.8,
"country": null,
"encrypted_email": …
```
> [PAY-3612] Add discovery endpoint for retrieving email data

- packages/harmony/src/components/text/Text.tsx
- packages/mobile/src/env/env.prod.ts
- packages/mobile/src/env/env.stage.ts
- packages/web/src/components/comments/CommentForm.tsx
- packages/web/src/components/comments/CommentPreview.tsx
- packages/web/src/components/comments/CommentSection.tsx
- packages/web/src/components/track/TrackTileMetrics.tsx
- packages/web/src/components/track/TrackTileStats.tsx
- packages/web/src/components/track/desktop/TrackTile.tsx
- packages/web/src/components/track/mobile/TrackTile.tsx
- packages/web/src/services/env/env.prod.ts
- packages/web/src/services/env/env.stage.ts
Bunch of misc fixes on web.
Can be reviewed commit by commit.
Local web vs. staging
> QA ticket grab bag

- packages/web/src/common/store/upload/sagas.ts
Fix the progress for the replace audio progress modal
> [C-5436] Fix-replace-progress-modal-progress

- packages/mobile/src/app/Drawers.tsx
- packages/mobile/src/screens/edit-track-screen/components/ReplaceTrackConfirmationDrawer.tsx
- packages/mobile/src/screens/edit-track-screen/components/index.ts
> [C-5442] Add mobile replace track confirmation drawer

- packages/discovery-provider/src/queries/get_top_playlists_es.py
Not sure how this didn't break during my client testing..
Tests pass locally
> Fix get_top_playlists_es

- packages/harmony/src/components/segmented-control/SegmentedControl.tsx
- packages/harmony/src/foundations/color/primitive-v2.css
- packages/harmony/src/foundations/color/primitiveV2.ts
- packages/harmony/src/foundations/color/semanticV2.ts
- packages/mobile/src/components/core/SegmentedControl.tsx
- packages/web/src/components/nav/desktop/PlaylistLibrary/PlaylistLibrary.tsx
- packages/web/src/components/tooltip/Tooltip.module.css
- packages/web/src/components/tooltip/Tooltip.tsx
- packages/web/src/pages/feed-page/components/desktop/FeedPageContent.tsx
Adds harmony theme v2 component updates. The easiest way to do this for now is to use staticWhite variable name, but change that value in v2 to actually be special.white. When this goes live, we can update all the variable names to special.white and drop the old theme.
> [C-5439] Add theme v2 component changes

- packages/web/src/pages/feed-page/components/desktop/FeedPageContent.tsx
Accident from https://github.com/AudiusProject/audius-protocol/pull/10518 probably
> Remove hello world

- packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
Just like for stems check if it already exists before inserting to prevent conflict.
https://github.com/AudiusProject/audius-protocol/blob/main/packages/discovery-provider/src/tasks/entity_manager/entities/track.py#L57-L70
> Handle duplicate comment thread records

- packages/discovery-provider/src/tasks/index_core.py
> rm logs and run indexer once every 3 seconds

- packages/web/src/index.css
Fixes ui jitter on app load. The root cause is quite interesting: the coinflow chargeback protection module must render some ui for 1 frame while initializing, causing a main-content jitter because it's rendered at the root. The solution im thinking we go with is to load this when purchase modal opens. @schottra would appreciate your review on this one because i may be missing something. This is the pr that introduced the change: https://github.com/AudiusProject/audius-protocol/pull/6975
> [QA-1544] Fix UI jitter

- packages/discovery-provider/src/queries/download_csv.py
- Added underscore to csv data for easier data handling when converting to CSV
- Renamed funciton to be more accurate
- Locally
> [TRIVIAL] Add underscores and rename

- Makefile
- monitoring/healthz/src/components/EnvironmentSelector.tsx
- monitoring/healthz/src/pages/Nodes.tsx
- monitoring/healthz/src/useServiceProviders.ts
- pkg/core/console/health.go
- pkg/core/console/routes.go
- pkg/core/console/views/pages/uptime_page.templ
- pkg/core/console/views/pages/uptime_page_templ.go
Core-specific page in healthz with associated health check
Tested on stage dn2 with local healthz, health information correctly shows up.
> [PROTO-1989] Rudimentary core health check, fix rollup page bug

- packages/mobile/src/utils/theme.ts
- packages/mobile/src/utils/themeV2.ts
Adds mappings from our legacy (non-harmony) mobile theme to harmony v2 theme.
> [C-5450] Add theme v2 compat for legacy mobile theme

- packages/common/src/hooks/useCollectionAccessTypeLabel.ts
- packages/common/src/hooks/useCollectionDogEar.tsx
- packages/common/src/hooks/useGatedContent.ts
- packages/common/src/hooks/useTrackAccessTypeLabel.ts
- packages/common/src/hooks/useTrackDogEar.tsx
- packages/mobile/src/components/collection/CollectionLockedStatusBadge.tsx
- packages/mobile/src/components/lineup-tile/CollectionTileMetrics.tsx
- packages/mobile/src/components/lineup-tile/CollectionTileStats.tsx
- packages/mobile/src/components/lineup-tile/TrackTileMetrics.tsx
- packages/mobile/src/components/lineup-tile/TrackTileStats.tsx
- packages/mobile/src/components/track/TrackLockedStatusBadge.tsx
- packages/web/src/components/collection/CollectionCard.test.tsx
Fixes performance issues on mobile. Instead of using audius-query, updated the code to select each variable directly. Long term we will use react-query
> [C-5449] Fix track tile performance

- packages/common/src/hooks/useAccessAndRemixSettings.test.ts
Fixes useAccessAndRemixSettings tests now that editable-access feature flag is removed
> Fix common tests due to feature flag removals

- packages/common/src/services/remote-config/feature-flags.ts
- packages/discovery-provider/src/api/v1/models/users.py
- packages/sdk/src/sdk/api/users/UsersApi.ts
- packages/web/src/pages/pay-and-earn-page/components/SalesTab.tsx
- packages/web/src/pages/pay-and-earn-page/desktop/PayAndEarnPage.tsx
This PR introduces a `OWN_YOUR_FANS` feature flag to facilitate the correct csv download function to the end user 
It also:
1.  Removes unused models from `users.py`
2. Removes faulty function in `UsersApi.ts` in favor of autogenerated function 
Running against staging on account with prior sales
> [PAY-3625] Add feature flag to use csv function conditionally

- comms/discovery/pubkeystore/backfill.go
- comms/discovery/server/server.go
`user_id` not monotomic, which breaks the "cursor" strategy.  This will simply retry any missing pubkeys on an interval.  This should let us shut down old POA node after a few days.
> Retry any missin pubkeys on interval.

- .circleci/src/workflows/web.yml
> Jail demo build

- packages/identity-service/sequelize/migrations/20241127191843-guest-user-state.js
- packages/identity-service/src/models/user.js
- packages/identity-service/src/routes/authentication.js
- packages/identity-service/src/routes/user.js
- packages/libs/src/api/Account.ts
Add a column to identity users to show when a user is created via guest checkout. This will only be assigned through the guest checkout flow via optional parameters that hedgehog passes to identity.
Ran guest sign up in local stack. Confirmed normal users default to isGuest false and guest purchases show isGuest true.
> [C-5448] Add isGuest column to identity users

- packages/discovery-provider/src/queries/query_helpers.py
These aren't present unless you send auth headers based on how this code is constructed
Set on a stage discovery node and tested manually
> Add stream/download URLs for anon track fetches on free content

- packages/identity-service/package.json
Main identity is blocked
```
14.95 identity-service:build: > cp ./src/notifications/browserPush/*.zip ./build/src/notifications/browserPush && cp -r ./src/notifications/browserPush/******.pushpackage ./build/src/notifications/browserPush && cp -r ./src/notifications/emails ./build/src/notifications
14.95 identity-service:build: 
14.95 identity-service:build: cp: can't stat './src/notifications/browserPush/*.zip': No such file or directory
```
from this PR https://github.com/AudiusProject/audius-protocol/pull/10531
> Unblock identity image building

- packages/common/src/services/audius-backend/AudiusBackend.ts
- packages/web/src/common/store/social/users/sagas.ts
- packages/web/src/common/store/social/users/store.test.ts
Easy one so went ahead and removed the AudiusBackend functions.
> Convert follow/unfollow to sdk
