AudiusProject/apps

packages/discovery-provider/src/queries/search_es.py, packages/web/src/pages/search-page-v2/SearchResults.tsx
* Add genre search param for profiles
* Any profile with a track matching a given genre will be included in the results
* Profiles with multiple tracks matching the genre will be boosted with a logarithm, this is to prevent profiles with tons of tracks from dominated search results
Tested locally with mock data
=> [C-4538] Add genre search param for profiles

packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts, packages/web/src/common/store/pages/collection/sagas.js
Fixes issue where albums with hidden tracks 404. We definitely do not want this with our new hidden premium albums feature.
From what i could tell, the "requiresAllTracks" was from a time during rewards, where it was possible for an album endpoint to not return all tracks. I dont think this is necessary anymore, especially since we have the "forceRefetch" option.
=> [C-4495] Fix hidden track albums

packages/libs/src/api/Account.ts, packages/web/src/components/nav/desktop/AccountDetails.tsx, packages/web/src/components/nav/desktop/AccountSwitcher/AccountSwitcher.tsx, packages/web/src/components/nav/desktop/AccountSwitcher/AccountSwitcherRow.tsx
* Use s500 for text so dark mode is better
* Fix jitter on load due to height changing when switcher pops in
* Fix account switcher load on first login. This is b/c sign in doesn't set web3 user and the hooks run before any user is signed in
Can review commit by commit
```
```
=> [PAY-3057][PAY-3099][PAY-3065] Fix misc account switcher UI issues

packages/web/src/components/nav/desktop/NavMenuButton.tsx, packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx, packages/web/src/components/stat-banner/StatBanner.tsx, packages/web/src/components/tipping/tip-audio/TipAudioButton.tsx, packages/web/src/components/tipping/tip-audio/TipAudioModal.tsx, packages/web/src/components/usdc-purchase-details-modal/components/SaleModalContent.tsx, packages/web/src/components/user-name-and-badges/UserNameAndBadges.tsx, packages/web/src/hooks/useGoToRoute.ts, packages/web/src/hooks/useManagedAccountNotAllowedRedirect.ts, packages/web/src/pages/audio-rewards-page/components/WalletManagementTile.tsx, packages/web/src/pages/chat-page/ChatPageProvider.tsx, packages/web/src/pages/chat-page/components/ChatUser.tsx, packages/web/src/pages/dashboard-page/components/ArtistDashboardAlbumsTab.tsx, packages/web/src/pages/dashboard-page/components/ArtistDashboardTracksTab.tsx, packages/web/src/pages/edit-page/components/AnchoredSubmitRowEdit.tsx, packages/web/src/pages/pay-and-earn-page/components/USDCCard.tsx, packages/web/src/pages/saved-page/components/desktop/AlbumsTabPage.tsx, packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountListItem.tsx, packages/web/src/pages/settings-page/components/desktop/NotificationSettings.tsx, packages/web/src/pages/settings-page/components/desktop/SettingsPage.tsx
Everything in the ticket + some things collected from meeting notes:
========== from ticket ===========
DMs
- Hide menu item in left nav
- Redirect to feed if we land on any chats route
- Hide DM button in artist page
- Hide "Block Messages" menu item in artist page
- Hide DM button in purchase history details modal
- Hide settings tiles that aren't applicable
- Hide "Show Private Key"
- Hide Tipping button on profiles
Show toast for:
- Attempting to open the purchase content modal
- Attempting to open the tip-to-unlock modal
========== from notes ===========
Pay & Earn
- You should be allowed to see the sales/purchases/withdrawal history
- Hide “Add Funds” and “Withdraw” buttons
Audio page
- Rewards should show audio balance, but no buttons
Messages
- Drop you back to the feed with a …
=> [PAY-2837] Handle disallowed actions when acting as managed user

.circleci/src/workflows/creator.yml
currently these missing pushes are blocking stage creator node deploys for all commits to main except releases. these pushes were all in the discovery workflow but recently we stopped running the discovery workflow on every change to the codebase, only running it on changes to the discovery code.
=> push uptime, dashboard, and healthz for creator stage deploys

mediorum/server/serve_blob.go
@raymondjacobson @dylanjeffers and I were picking apart content node code to see if we can optimize anything for better audio playback performance.
This `recordMetrics` call seems like low hanging fruit for a call that could be non-blocking. (chat GPT concurred)
going to test after it hits staging 🙈
=> Make content node metric recording non-blocking

mediorum/server/audio_analysis.go, mediorum/server/db.go, mediorum/server/legacy_audio_analysis.go, mediorum/server/serve_audio_analysis.go, mediorum/server/serve_upload.go, mediorum/server/server.go
Remembered that Qm cids do not have corresponding uploads... so wrote a separate audio analysis work queue for Qm cids for use in the backfill. 
Will only be triggered during the backfill via POSTs to /tracks/legacy/:cid/analyze. Will remove the POST endpoint and `legacy_audio_analysis.go` after the backfill completes next week.
Will test in stage.
=> Mediorum audio analysis for Qm cids

mediorum/ddl/ddl.go, mediorum/ddl/fix-qm-audio-analyses-typo.sql, mediorum/server/db.go
gorm automigrate named this col c_id instead of cid. erroneous col name is only on stage nodes rn - will remove the ddl after all stage nodes have run the migration.
tested locally
=> fix gorm automigrate typo

mediorum/server/db.go
typo again... dropped local cols and verified automigrate was recreating cid, not c_id, this time.
=> fix cid colname

packages/harmony/src/components/button/FilterButton/FilterButton.tsx, packages/harmony/src/components/button/FilterButton/types.ts, packages/harmony/src/components/button/OptionsFilterButton/OptionsFilterButton.tsx, packages/harmony/src/components/button/OptionsFilterButton/SelectPopupKeyHandler.tsx, packages/harmony/src/components/popup/Popup.tsx, packages/web/src/pages/search-page-v2/SearchFilters.tsx
* Make OptionsFilterButton navigable via keyboard
Video is keyboard only:
https://github.com/AudiusProject/audius-protocol/assets/19916043/2794cdf4-61a0-4e21-9e1f-96348cbeb8ba
* Handle focus state of the filter input
* Add a `No matches` message when all options are filtered out
* Remove margin from bottom of emojis in dropdown
Still left to do:
* Rename to `Select`
* Use an input internally so onChange accepts a `ChangeEvent`
Tested locally
=> [C-4542] OptionsFilterButton improvements

mediorum/server/repair_test.go, mediorum/server/serve_blob.go, mediorum/server/serve_image.go, mediorum/server/serve_image_test.go, mediorum/server/server.go
Set `x-took` response header to measure how long server spent processing request (wall clock time).
If `x-took` is slow we need to optimize server code.
If `x-took` is fast, but request takes long time... there is a network or proxy issue along the way.
=> Mediorum timing header

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/services/wallet-client/WalletClient.ts, packages/web/src/common/store/wallet/sagas.ts
This adds optional behavior to the functions in `WalletClient` and `AudiusBackend` to use a specific wallet address when fetching balance and updates the wallet saga to use the wallet address we load from the current user Account. Ideally, we will remove `WalletClient` and `AudiusBackend` altogether. But I wanted to limit the surface area of this change to just fixing the balance display bug when switched into a managed account.
fixes PAY-3121
Tested with local client against staging. Verified that we show the correct balance in both managed and unmanaged modes.
=> [PAY-3121] Use current user wallet to fetch AUDIO balance

packages/mobile/src/components/details-tile/DetailsTile.tsx, packages/mobile/src/components/details-tile/DetailsTileStats.tsx, packages/mobile/src/components/details-tile/MetadataItem.tsx, packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
- Forgot to add `color='subdued'` to the labels.
- Hide the stats (plays, reposts, favorites) counts if it's 0 and user is not the owner
- Fix bug where `playCount` wasn't getting passed in correctly.
Note - ugly code in the `hideX` logic. Ideally we'd calculate this inside `DetailsTileStats` itself - but this won't work since track/collection tiles are shared right now. This fix works for now.
Before repost
After repost + play
Show 0 for owners
pluralized
=> Use subdued color for mobile MetadataItem

mediorum/server/db.go, mediorum/server/serve_audio_analysis.go
- audio analaysis results not correctly getting serialized to lowercase "bpm" and "key" due to a typo
- register the qm_audio_analyses type in crudr
tested against local mediorum
=> Misc mediorum fixes

packages/web/src/components/edit-collection/desktop/EditCollectionForm.tsx, packages/web/src/components/edit/fields/AdvancedAlbumField.tsx, packages/web/src/components/form-fields/HarmonyTextField.tsx, packages/web/src/components/form-fields/TextField.tsx
Adds advanced menu and upc for albums. Not behind a feature flag
=> [C-4518] Add album advanced menu and upc

packages/common/src/models/TrackAvailabilityType.ts, packages/web/src/components/edit/fields/price-and-audience/PriceAndAudienceField.tsx, packages/web/src/components/edit/fields/price-and-audience/PriceAndAudienceMenuFields.tsx
Removes visibility options by preventing those values leaking into the experience when "HIDDEN_PAID_SCHEDULED" flag is on.
Im wondering if it's cleaner to implement all these changes without a feature flag at this point, it would help us clean up a A LOT of code if so. Right now my thinking is we get this reviewed by sammie, and then can fast follow a full removal of the old flow?
=> [C-4519] Remove visibility options

mediorum/server/audio_analysis.go, mediorum/server/legacy_audio_analysis.go
during the backfill, crudr is not updating all nodes instantly, i assume bc the crudr outbox is full, so nodes may get their analysis jobs until minutes later. which is fine. allow them to process the job whenever they process the crudr action.
=> remove audio analysis time window check

mediorum/server/serve_audio_analysis.go, packages/discovery-provider/plugins/pedalboard/apps/backfill-audio-analyses/src/backfill.ts
noticed some valid, streamable `track` records in discovery with ba `track_cid`s but no `audio_upload_id` after running the mediorum audio analysis backfill on stage. i assume this is from some intermediate state during the storage v2 migration. handle these tracks the same way as the legacy Qm track cids.
=> handle ba cids without upload id in audio analysis backfill

packages/common/src/hooks/useAccountSwitcher.ts, packages/web/src/components/share-modal/ShareModal.tsx, packages/web/src/components/share-modal/components/ShareDialog.tsx, packages/web/src/components/share-modal/types.ts, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountListItem.tsx
Hides a few menu options that don't make sense in manager mode.
Bonus: Fixes the popup trigger for the accounts in the "Accounts You Manage" modal to correctly close if clicked while it's open.
fixes PAY-3119
fixes PAY-3123
Tested manually on local client against staging.
=> [PAY-3119][PAY-3123] Hide some menu options in manager mode

packages/common/src/utils/stringUtils.ts, packages/web/src/hooks/useQueryParamConsumer.ts, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageHomePage.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/usePendingInviteValidator.ts
This updates the code in the "Accounts Managing You" modal so that the query params and deeplink route are consumed when the component mounts and replaced with the `/settings` path (leaving any other query params in place). This fixes problems with refreshing the page and/or switching into an account after accepting the invite.
This also fixes the issue of attempting to switch into another account after following a pending invite link, since that was due to the deeplink and query param being carried across into the new user context (where it's most definitely invalid).
This "consume query param" pattern is a little different and I'm open to discussion on it!
* Added utility hook for consuming a query param and optionally replacing the path
* Moved the invite validation logic into a …
=> [PAY-3115][PAY-3124] Fix issues with pending invite query param

packages/mobile/src/components/audio/AudioPlayer.tsx, packages/web/src/common/store/cache/tracks/sagas.ts, packages/web/src/common/store/cache/tracks/utils/fetchTrackStreamUrls.ts
Add another saga to watch for cache updates for stream access changes to refetch/update stream urls in the cache.
More specifically I'm only checking changes to `access.stream` and retriggering the same prefetch logic with the updated track ids.
web:stage
=> [C-4567] Fix purchase content not updating prefetch correctly

packages/common/src/hooks/useAccountSwitcher.ts, packages/web/src/components/nav/desktop/AccountSwitcher/AccountSwitcher.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/RemoveManagerConfirmationContent.tsx
This handles two scenarios:
* Loading / reloading the page while switched into an account for which you have lost management access
* Removing yourself from the managers list via the Accounts Managing You dialog while switched into an account
In both scenarios, we will switch back to the current web3 user.
fixes PAY-3109
=> [PAY-3109] Switch back to web3 account when management access is revoked

packages/discovery-provider/src/app.py, packages/discovery-provider/src/models/tracks/track.py, packages/discovery-provider/src/tasks/repair_audio_analyses.py
Repairs missing key / bpm data in discovery. Runs as a celery task on every discovery node. Will be responsible for pulling all analysis data from mediorum -> discovery after mediorum finishes backfilling, and will live on forever in discovery repairing audio analysis data. Will retry errors up to 3 times and will log to axiom if analysis is still failing.
will merge to stage on Thurs 6/20 so it can start running in prod on Friday 6/21.
will test on stage.
=> Audio analysis repair job

packages/discovery-provider/src/app.py, packages/discovery-provider/src/tasks/repair_audio_analyses.py
order by track id
also do not run task yet. found some issues that slowed down the prod backfill and would like nodes to pick up some mediorum fixes first + the backfill to complete. will put up a PR enabling this task so it can run later than originally planned - prob Friday afternoon as opposed to Friday during deploy.
=> order tracks in query in audio analysis repairer

mediorum/server/audio_analysis.go, mediorum/server/legacy_audio_analysis.go
All the workers are trying to use most of the CPUs.  This takes it down to 1 each for audio analysis.  We can maybe bump it up later, but might make sense to have a more centralized worker pool thing for resource management stuff.
=> Use 1 CPU for audio analysis

packages/discovery-provider/src/api/v1/models/challenges.py
Undisbursed response needs this completed_at field for determining claimable challenges
https://github.com/AudiusProject/audius-protocol/blob/main/packages/common/src/utils/challenges.ts#L258
Not sure how this was working before, something must've changed. 
Tested on stage. Rewards that were at an incorrect later date were now claimable.
=> Add completed at to undisbursed response

packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsManagingYouHomePage.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageHomePage.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageSettingsCard.tsx
* Force refresh on the managers/managed accounts whenever the list page of either modal mounts. This will help prevent stale state.
* Don't show the loading spinner if we have already loaded once. This prevents rapid flashes of different sizes due to jumping between the already loaded list and the loading spinner. It's fine if the list takes a second and then the items change
* Update the matching logic to use react-router location instead of the history context, since the former correctly updates and triggers the effect if changed while on the same route.
fixes PAY-3111
fixes PAY-3112
=> [PAY-3111][PAY-3112] Fixes some timing issues with invites

mediorum/server/legacy_audio_analysis.go, mediorum/server/serve_audio_analysis.go
if an analysis job is not found on the first 3 mirrors right now, it will never be terminated.
change so it checks all mirrors and terminates on any error if it reaches the last mirror, or after 45 minutes, so it doesn't get infinitely retried.
=> terminate legacy audio analysis jobs at some point so they do not get infinitely tried

.changeset/big-beers-remain.md, packages/libs/src/sdk/middleware/addRequestSignatureMiddleware.ts
This fixes a subtle class of signon/signup bugs due to the SDK signature being stale. The process is:
1. SDK is initialized with `auth` service and signature middleware signs its first request. We store the computed message and a timestamp so that we aren't trying to re-sign the same message on every request using an expensive operations
2. The underlying hedgehog wallet changes (either due to completing sign-in or completing sign-up).
3. SDK starts making request to endpoints with a new contextual user, but using the cached signature from the previous wallet address
4. DNs and Identity may reject the request because the recovered wallet from the signature doesn't match the user making the request
-- 60 seconds later.... --
5. The timestamp expires and we generate a new signature, from …
=> [PAY-3126] Refresh signature headers when wallet changes

packages/web/src/components/track/DownloadRow.tsx, packages/web/src/components/track/GatedContentLabel.tsx
Noticed that the "special access" and "collectible gated" labels on track tiles were wrapping to 2 lines.
Also sliding in a small code cleanup changing the css prop `'white-space'` to `whiteSpace` in `DownloadRow`.
=> Fix premium content label text wrap

packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountListItem.module.css, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountListItem.tsx
This removes the usage of `ArtistChip` in favor of a simplified component similar to what's used in the AccountSwitcher.
We don't need the follower/follows you information in the list (only in search for finding your manager), and the alignment/layout is different than what `ArtistChip` supports.
With my eyes. And also some DOM inspection to make sure padding values are correct :-p 
**Before**
---
**After**
---
=> [PAY-3113] Styling fixes for artist info in Manager Mode Modals

packages/discovery-provider/ddl/migrations/0079_backfill_prod_user_socials.sql
Issues:
* Current gating for prod migration does not work because we opted to do dual writes, and many users already have a website. So switch the gating onto the profile `rayjacobson` containing no donation link (which it will get after the migration)
* Lots of commas in the CSV file that were not escaped by quotes.
Note that the changes to the .sql file will cause the migration to run again because the md5 will not match
Manually ran on prod dn1
=> Fix backfill of social data

packages/common/src/hooks/purchaseContent/utils.ts, packages/mobile/src/components/lineup-tile/TrackTile.tsx, packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx, packages/mobile/src/components/track-list/TrackListItem.tsx, packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx, packages/web/src/components/track/GiantTrackTile.tsx, packages/web/src/components/track/desktop/ConnectedTrackTile.tsx, packages/web/src/components/track/desktop/TrackListItem.tsx, packages/web/src/components/track/helpers.ts, packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx, packages/web/src/components/track/mobile/ConnectedTrackTile.tsx, packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
All track types should now be able to be added to playlists.
Hidden tracks still aren't able to be added to public playlists - will follow up with that.
cc-ing @michellebrier bc i noticed the add to album option was sometimes disallowed if the track was uploaded via ddex. Noticed a few places where that was missed, just checking that this is the intention? (I think this is disallowed at the protocol level as well.)
Added a follow-gated track to a playlist, things are working and didn't notice any UI weirdness.
=> [C-4437] Allow add to playlist for all track types

packages/discovery-provider/src/tasks/repair_audio_analyses.py
GET reqs were failing because of the $ typo. also add more logs
=> fix typo in audio analysis repairer task, add more logs

packages/discovery-provider/src/app.py, packages/discovery-provider/src/tasks/repair_audio_analyses.py
also run every 3 mins instead of 2.
also catch exception when lock not held at release time - not sure why this is happening because the locking code is the same as in every other task
tested and verified batches succeeded on stage dn1
=> audio analysis repairer: handle null results

mediorum/server/legacy_audio_analysis.go
kept this logic out of the main mediorum backfill for legacy tracks' audio analyses to minimize the number of crudr updates. add it in so the repairer can read intermediate results if it retriggers any errored analyses. meaning a bpm error doesn't block a successfully key result, and vice versa.
this already happens for non-legacy uploads.
=> mediorum: update intermediate audio analysis results for legacy tracks

packages/common/src/hooks/useCollectionMetadata.ts, packages/common/src/hooks/useTrackMetadata.ts, packages/mobile/src/components/details-tile/CollectionMetadataList.tsx, packages/web/src/components/collection/CollectionMetadataList.tsx, packages/web/src/components/track/TrackMetadataList.tsx
These were still visible but with no value when the ff was off.
Already getting value out of sharing the show/hide logic between mobile+web :)
FF off:
FF on:
=> [C-4593] Hide bpm/key when SEARCH_V2 ff is off

packages/mobile/src/components/collection-list/CollectionCard.tsx, packages/web/src/components/collection/CollectionCard.tsx
Move the `LockedStatusBadge` outside the ternary so it shows in all cases where the collection is premium.
web:
mobile-web:
mobile:
=> [C-4597] Show locked badge for private premium albums

packages/web/src/components/edit-collection/desktop/EditCollectionForm.tsx, packages/web/src/components/edit-track/EditTrackForm.tsx, packages/web/src/components/edit/fields/visibility/VisibilityField.test.tsx, packages/web/src/components/edit/fields/visibility/VisibilityField.tsx, packages/web/src/pages/upload-page/forms/EditCollectionFormForUpload.tsx
In the edit redesign, it was possible to set a public track to hidden or scheduled. This change disables those options for public trakcs.
local working for upload and edit in multiple cases
=> [C-4601] Disallow hiding public tracks in edit

packages/common/src/services/audius-api-client/AudiusAPIClient.ts, packages/common/src/store/pages/search-results/actions.ts, packages/common/src/store/pages/search-results/types.ts, packages/discovery-provider/src/api/v1/helpers.py, packages/discovery-provider/src/api/v1/search.py, packages/discovery-provider/src/queries/query_helpers.py, packages/discovery-provider/src/queries/search_es.py, packages/web/src/common/store/pages/search-page/sagas.ts, packages/web/src/pages/search-page-v2/ResultsAlbumsView.tsx, packages/web/src/pages/search-page-v2/ResultsPlaylistsView.tsx, packages/web/src/pages/search-page-v2/ResultsProfilesView.tsx, packages/web/src/pages/search-page-v2/ResultsTracksView.tsx, packages/web/src/pages/search-page-v2/SearchResults.tsx
Adds option to sort search results by recency, ie "updated_at" for tracks, users and collections. I'm personally a little confused on naming conventions, whether we should use "sort" or "sort_method". Im seeing both. Any convictions here would be great.
=> [C-4557] Add sort by recency to search

packages/web/src/components/track/TrackMetadataList.tsx
Bug! Missed filling out the value when `SEARCH_V2` feature flag is disabled.
=> Fix empty genre on web track pages

dev-tools/compose/docker-compose.pedalboard.prod.yml
Solana relay can take a long time to start up for some reason, this time took 34 seconds.
```
[INFO] 02:12:41 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 5.0.4)
{"level":30,"time":"2024-06-25T02:13:02.081Z","name":"solana-relay","msg":"running on dev network"}
{"level":30,"time":"2024-06-25T02:13:12.570Z","name":"solana-relay","serverHost":"0.0.0.0","serverPort":6002,"msg":"server initialized"}
{"level":30,"time":"2024-06-25T02:13:15.481Z","name":"solana-relay","requestId":"1853f237-dbc7-48c8-ac66-5a94eac33031","path":"/solana/health_check","method":"GET","startTime":"2024-06-25T02:13:15.481Z","body":{},"msg":"incoming request"}
```
Previously this was 30 seconds so it was very likely a toss up before the health timeout would be hit and docker would think …
=> boost solana relay health check startup timeframe

packages/discovery-provider/plugins/pedalboard/apps/backfill-audio-analyses/src/backfill_content.ts, packages/discovery-provider/plugins/pedalboard/apps/backfill-audio-analyses/src/backfill_discovery.ts, packages/discovery-provider/plugins/pedalboard/apps/backfill-audio-analyses/src/index.ts, packages/discovery-provider/plugins/pedalboard/apps/backfill-audio-analyses/src/redis.ts
since the discovery celery repairer is not parallelized and in implementation is taking 15 mins/1000 tracks. which is fine when repairing just new uploads but a little slow for pulling millions of analysis results from mediorum.
use this plugin instead. run in batches of 1000 tracks at a time with 10 workers processing each batch.
tested on a stage node.
=> More quickly backfill discovery audio analyses

packages/web/src/components/edit-track/EditTrackForm.tsx, packages/web/src/pages/edit-page/EditTrackPage.tsx
- Add delete button to edit track form
- Hidden on upload
- Opens confirmation modal
- Redirects to profile page on delete
button working on edit, hidden on upload
=> [C-4602] Add delete button to edit track page

packages/web/src/components/edit/fields/price-and-audience/PriceAndAudienceField.tsx
- When `HIDDEN_PAID_SCHEDULED` feature flag is on, unlink the automatic setting of hidden/public when changing premium gates
working locally, can upload hidden premium
=> [C-4608] Allow premium hidden uploads

protocol-dashboard/src/components/UniqueUsersChart/UniqueUsersChart.tsx, protocol-dashboard/src/components/UniqueUsersStat/UniqueUsersStat.tsx
Previously the unique users top line number on the Analytics page was pulling from the wrong API -- so the number didn't align with the numbers in the chart.
Discussed solution w Ray, which is:
- Changing the top line label to be "Monthly" or "Daily" depending on the time period selected & how the data is bucketed in that time period
- Use the last data point on the chart as the top line number
Local against prod.
=> [Protodash] Fix unique users top line number on protocol dashboard [QA-1397]

packages/mobile/src/components/details-tile/types.ts, packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx, packages/mobile/src/screens/smart-collection-screen/SmartCollectionScreen.tsx, packages/web/src/components/collection/desktop/ViewerActionButtons.tsx, packages/web/src/components/collection/mobile/CollectionHeader.tsx
Hide action buttons (repost, share, save, overflow) for hidden tracks and collections.
Web track
Web collection
mobile-web track
mobile-web collection
Mobile track
Mobile collection
=> [PD-442] Hide action buttons on private content

packages/discovery-provider/plugins/pedalboard/apps/backfill-audio-analyses/src/backfill_discovery.ts
shouldnt be filtering the query and using a db offset. move the filter logic to the per-track code to ensure every track gets checked once.
=> iterate through all tracks in discovery audio analysis backfill plugin

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/identity-service/src/authMiddleware.js, packages/identity-service/src/routes/notifications.js
We support fetching and marking notifications as read in Manager Mode. Identity is getting support for this in #8844 , and this PR updates the two additional endpoints that need it.
I also fixed two issues that came up while testing this against Identity:
* We don't parse the query parameter for `user_id` into a number, so the `!==` check always fails (the user we fetch from discovery has a user_id that is a number)
* There are some usages of `announcementMap` that don't check the object is initialized before attempting to read it, and this throws an error at least locally (and likely on staging/production after a full restart of the service)
=> [PAY-3117] Fixes some issues with Identity notifications in manager mode

packages/discovery-provider/plugins/notifications/src/email/notifications/index.ts, packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/purchase.ts, packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/requestManager.ts, packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/sale.ts, packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/transfer.ts, packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/withdrawal.ts, packages/discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts, packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/claimableReward.ts, packages/discovery-provider/plugins/notifications/src/remoteConfig.ts, packages/discovery-provider/plugins/notifications/src/types/dn.ts
Adding browser and push notif for claimable rewards.
Also includes linting fixe, mostly correcting irregular whitespaces.
Ran on stage and received push
=> Add claimable rewards push notif

packages/web/src/components/collection/desktop/CollectionHeader.tsx, packages/web/src/components/collection/mobile/CollectionHeader.tsx, packages/web/src/components/track/CardTitle.tsx, packages/web/src/pages/track-page/components/mobile/TrackHeader.module.css, packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Noticed header text styling was different between tracks and albums on web. Check the linear issue to see examples of how it was broken.
=> [C-4610] Fix styling on web track header text

packages/discovery-provider/src/tasks/repair_audio_analyses.py
retrigger analysis if the cid/upload was not found on 5 random content nodes, meaning it was never successfully started during the content node migration. seeing a couple instances of this on stage, i think from the time it was running before i merged a change allowing ba cids without audio upload ids to use the legacy audio analysis path
=> trigger audio analysis if not found on content nodes

packages/common/src/api/account.ts, packages/web/src/components/notification/Notification/RequestManagerNotification.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageHomePage.tsx, packages/web/src/utils/route.ts
- Remove `invite=` query param from Manager Requested in-app notification since it was unnecessary and error-prone
- Fix issue with optimistic updates when accepting multiple manager invites (explained in comment)
Web against stage
=> [Web] Manager Mode QA - Fix caching issue when accepting multiple invites; remove query param from in app notif link [C-4615] [PAY-3135]

packages/common/src/hooks/useAccountSwitcher.ts, packages/common/src/models/Analytics.ts, packages/web/src/common/store/account/sagas.js, packages/web/src/components/edit/fields/price-and-audience/PriceAndAudienceField.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsManagingYouHomePage.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageHomePage.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/RemoveManagerConfirmationContent.tsx
* Added new fields to the `identify` phase so that Amplitude/Sentry can see current manager id/handle
* Don't link wallet info in manager mode (so that we don't overwrite managed user wallet info with the manager's wallet)
* Added events for the various interactions in manager mode
Tested locally against staging, examined payloads and debug output.
=> [PAY-2829] Add analytics for manager mode

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/discovery-provider/plugins/notifications/src/email/notifications/renderEmail.ts, packages/discovery-provider/plugins/notifications/src/types/identity.ts, packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/trending.ts, packages/discovery-provider/plugins/pedalboard/packages/storage/src/index.ts, packages/discovery-provider/plugins/verified-uploads/src/handlers/users.js, packages/identity-service/src/notifications/fetchNotificationMetadata.js, packages/identity-service/src/routes/idSignals.js, packages/mobile/src/components/share-drawer/utils.ts, packages/web/src/common/store/cache/users/sagas.ts, packages/web/src/components/notification/Notification/utils.ts, packages/web/src/components/share-modal/utils.ts
We previously left in the read and write of socials in identity in addition to discovery, for backwards compatibility with old client. We are now removing that so, where identity socials were being used, DN socials are now being used.
Note: I haven't removed identity's `socialHandles.js` file in case some old clients are still using, so that these clients don't break. But we can remove some time soon when we are either confident no clients are using, or we don't care if old clients break of this.
Local web dapp vs stage
=> [PAY-3081] Use DN socials across the stack

packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/base.ts, packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/requestManager.ts, packages/discovery-provider/plugins/notifications/src/utils/format.ts
See title.
https://linear.app/audius/issue/PAY-3134/[qa]-manager-mode-email-placeholder-profile-picture-missing
Jest snapshot testing
=> [Notifications] Use placeholder profile pic in Manager Mode transactional email if user has no profile pic [PAY-3134]

packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/middleware/errorHandler.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/middleware/locals.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/middleware/logging.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/relay.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/utils/transaction.ts, packages/web/src/store/errors/reportToSentry.ts
Small improvements to help aid in debugging errors with claiming rewards.
- Exposes the request ID to the client so that it can be reported via Sentry on failures
- JSON.stringify the RPC error so that it logs correctly instead of `[Object object]`
- Remove manual timeout and instead rely on blockhash expiry
Tested locally by sending tips with no balance and ensuring the `additionalInfo` of Sentry included the request ID and the error.
=> Improve Solana Relay error logging

packages/discovery-provider/src/tasks/entity_manager/entities/notification.py
This updates the entity indexing for notificaions/playlist views to support the same validation logic as the other entity transactions, such that a user or app with a valid grant can perform the transaction on behalf of the user in question.
fixes PAY-3146
Tested via client against local stack.
=> [PAY-3146] Allow discovery notifications to be marked as viewed by managers

packages/mobile/tsconfig.json
Small update to mobile tsconfig to ensure `@audius/common/` imports have the highest preference over `~` imports. this aids autocomplete
=> Improve mobile ts autocomplete

mediorum/server/legacy_audio_analysis.go, mediorum/server/serve_audio_analysis.go, packages/discovery-provider/src/tasks/repair_audio_analyses.py
seeing some cases where the cid isn't an audio file. checked on the storeall node and they appear to be type `text/plain; charset=utf-8` in the bucket for some reason. these files can't be analyzed so they're (correctly) erroring but the server shortcut is not incrementing the error count so the repairer keeps retrying their audio analyses. set the error count to 3 in mediorum so the repairer can move on.
=> audio analysis: handle non audio file failures

packages/web/src/pages/edit-page/EditTrackPage.tsx
Edit page back button callback wasn't implemented
TODO:
If the user navigates directly to the edit page in the browser, clicking back or cancel button will navigate back as if the user clicked the back button on their browser. This means if the previous location was external to Audius (e.g. the browser's new tab page) they will be sent back there.
I looked into trying to detect whether there was history within Audius, but the history context doesn't have the previous pathname exposed. Ideally we default to going back to the track page if there's no previous app page to return to.
One way would be to pass the previous location when opening the edit page, but that seems overly complex. Looking for ideas here.
back button works now
=> [C-4603] Fix edit page back button

packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
Missed a spot - headers should no longer read "Hidden x" as we're moving the hidden denotation over to the MusicBadges.
=> [C-4609] Fix hidden album header text on mobile

mediorum/server/audio_analysis.go, mediorum/server/legacy_audio_analysis.go
to prevent failures for extremely long files and for performance.
tested locally with normal tracks and a 45 min long track
=> only analyze the first 5 mins of audio files

packages/discovery-provider/src/tasks/repair_audio_analyses.py
found a case on stage with an upload id that doesn't exist in content nodes' `uploads` tables, which i think is an edge case from changes in the early days of storage v2. direct these cases to the legacy audio analysis path
=> audio analysis repairer: handle 404 upload ids

mediorum/server/audio_analysis.go, mediorum/server/legacy_audio_analysis.go, packages/discovery-provider/src/tasks/repair_audio_analyses.py
- have all nodes, not just the mirrors, check for and mark jobs as timed out.
- repairer: do not try to analyze podcasts and audio books.
- repairer: do not override non-null key/bpm values with the audio analysis results from content (for the future, when users may edit and save differing values)
=> misc audio analysis improvements

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/store/pages/search-results/actions.ts, packages/discovery-provider/src/queries/search_es.py, packages/discovery-provider/src/queries/search_queries.py, packages/libs/src/api/Account.ts, packages/libs/src/services/discoveryProvider/DiscoveryProvider.ts, packages/libs/src/services/discoveryProvider/requests.ts, packages/web/src/common/store/pages/search-page/sagas.ts, packages/web/src/pages/search-page-v2/SearchResults.tsx
Update sagas and elastic search for tag search to handle the filters. Reuses the track_dsl and user_dsl from the normal search
Lots of testing on local stack
=> [C-4579] Add filters to tag search

packages/discovery-provider/integration_tests/gated_content/test_access.py, packages/discovery-provider/src/gated_content/content_access_checker.py
Now that users may freely change the access type, we want to make sure that once a user has paid for content, they will always have access to it in the future.
We do this by _checking for purchase records (using already built in usdc access check)_ if content is currently gated by something other than usdc purchase and if user does not have access to that current gate.
Integration tests and manual local dn service test
=> [PAY-3141] Always allow access if user previously paid for content

mediorum/server/serve_blob.go
See this panic occasionally:
```
[PANIC RECOVER] runtime error: invalid memory address or nil pointer dereference goroutine 136680045 [running]:
github.com/AudiusProject/audius-protocol/mediorum/server.New.Recover.RecoverWithConfig.func14.1.1()
/go/pkg/mod/github.com/labstack/echo/v4@v4.10.0/middleware/recover.go:93 +0x15d
panic({0x19caa40?, 0x31bbb20?})
/usr/local/go/src/runtime/panic.go:770 +0x132
gocloud.dev/blob.(*Reader).Close(0xc00af02b40)
/go/pkg/mod/gocloud.dev@v0.34.0/blob/blob.go:200 +0x26
github.com/AudiusProject/audius-protocol/mediorum/server.(*MediorumServer).serveBlob(0xc0008f8808, {0x23c2910, 0xc01480aaa0})
/app/server/serve_blob.go:213 +0xa17
...
github.com/labstack/echo/v4.(*Echo).add.func1({0x23c2910, 0xc01480aaa0}) …
```
=> safer blob close

packages/common/src/api/search.ts, packages/mobile/src/screens/app-screen/AppTabScreen.tsx, packages/mobile/src/screens/search-screen-v2/SearchBarV2.tsx, packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx, packages/mobile/src/screens/search-screen-v2/SearchScreenV2.tsx, packages/mobile/src/screens/search-screen-v2/index.ts, packages/mobile/src/screens/search-screen-v2/searchParams.ts, packages/mobile/src/screens/search-screen-v2/searchState.ts
Adds mobile search state pattern, using a combination of state, context and hooks. Essentially it creates custom hooks for query, category, and filters that feel like `useState`, but share a single state instance.
Also establishes search params and sets them as the search state initial values.
Also thinking we could use something like this to avoid my hand-rolled implementation? https://github.com/streamich/react-use/blob/HEAD/docs/createGlobalState.md
If we are thinking something else entirely, also down with that.
=> [C-4620] Mobile Search State

packages/discovery-provider/ddl/functions/handle_challenge_disbursements.sql, packages/discovery-provider/integration_tests/notifications/test_challenge_disbursement.py, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/challengeReward.test.ts, packages/discovery-provider/plugins/notifications/src/types/dn.ts
To prevent overwhelming users with reward notifications, this change makes it so users are only notified about reward disbursements at most once an hour. Other disbursements within that window are de-duplicated.
Ran on sandbox and confirmed disbursements only notify once an hour.
Updated tests.
=> [C-4611] Debounce disbursed notification

packages/common/src/schemas/upload/uploadFormSchema.ts, packages/web/src/common/store/upload/sagas.ts
Tracks will inherit `is_scheduled_release` flag from the collection if release date is set on the collection but not the track
tested cases with release date set and not set on collection. Correct data appears on resulting track metadata
=> [C-4613] Set `is_scheduled_release` on collection track uploads

packages/web/src/components/tracks-table/TracksTable.tsx
Fix price formatting logic not accounting for prices that already include have decimals
web:prod using this album:
https://audius.co/eloquinuk/album/eloquin-dubpack
=> [QA-1405] Fix price formatting on collection screens

packages/mobile/src/components/details-tile/DetailsTileActionButtons.tsx, packages/web/src/common/store/cache/collections/commonSagas.ts, packages/web/src/common/store/pages/track/sagas.ts, packages/web/src/components/collection/desktop/PublishButton.tsx, packages/web/src/components/collection/desktop/PublishConfirmationModal.tsx
- Unlock publish button for collections with hidden tracks
- On publish, also publish all hidden tracks in the collection
publish successfully cascaded to the child tracks
=> [C-4617, C-4439] Publish tracks along with playlist

packages/discovery-provider/src/api/v1/helpers.py, packages/discovery-provider/src/api/v1/playlists.py, packages/discovery-provider/src/api/v1/tracks.py, packages/discovery-provider/src/api/v1/users.py
Non full v1 api (`v1/users/search`, `v1/tracks/search`, `v1/playlists/search`) supports search filters supported on `v1/full/search/full`.
=> non full search api parity with full

packages/web/src/common/store/pages/history/lineups/sagas.ts
Fixes listening history not queueing up properly. The reason is because `kind` was not being added to the history tracks, which makes it fall through both `if` statements [here](https://github.com/AudiusProject/audius-protocol/blob/jd/fix-listening-history-lineup/packages/web/src/common/store/queue/sagas.ts#L69)
web:stage and ios:stage
=> [QA-1389] Fix listening history not queuing up properly

packages/web/src/components/add-to-collection/mobile/AddToCollection.tsx
Fix mobile web add to playlist showing blank screen. Redux state wasnt getting updated properly
chrome mobile sim + web:stage
=> [QA-1398] Fix mobile web add to playlist showing blank screen

packages/mobile/src/components/add-to-collection-drawer/AddToCollectionDrawer.tsx, packages/web/src/components/add-to-collection/desktop/AddToCollectionModal.tsx
No longer filter out public playlists from the add to playlists modal/drawer.
ff off:
ff on:
Harder to see on ios but also tested there.
=> [C-4583] Allow hidden tracks to be added to public playlists in UI

packages/harmony/src/components/music-badge/MusicBadge.tsx, packages/web/src/components/collection/desktop/CollectionHeader.tsx, packages/web/src/components/collection/mobile/CollectionHeader.tsx
Add scheduled MusicBadges to collection headers.
Also add `white-space: nowrap` to `MusicBadge`.
=> [C-4599] Scheduled MusicBadge on web collections

packages/common/src/services/remote-config/feature-flags.ts
Simply add the new `editable_access_enabled` feature flag. It's already added to optimizely.
tested locally to get the boolean flag on client.
=> [PAY-3151] Add editable access client feature flag

packages/web/src/common/store/cache/tracks/utils/fetchTrackStreamUrls.ts
Context: To avoid tons of redux spam I batched all the stream prefetches together and had them wait till they all finish before putting them in the store. Once we got to prod though, I noticed that some calls can take a long time and this holds back all of the quick returning ones (this doesn't cause any bugs, it just ruins the point of the optimization; aka to have the prefetched urls ready before the user clicks anything).
To solve, this change tweaks the saga logic to see what's ready after 1.5s and put that into the store before waiting on the rest. This should solve for the majority of calls since most are under ~1s
web:stage
=> Optimize prefetch logic to not wait on long calls

packages/web/src/components/collections-table/CollectionsTable.tsx, packages/web/src/components/tracks-table/TracksTable.tsx
For tracks/albums scheduled to release in the future, we don't want to show the "scheduled" suffix anymore, just the future release date.
=> [C-4633] Remove scheduled suffix from artist dashboard tables

packages/web/src/components/collection/desktop/EditButton.tsx, packages/web/src/components/collection/desktop/PublishButton.tsx, packages/web/src/components/collection/desktop/ShareButton.tsx
Since we're moving to IconButtons we should always show tooltips in case the meanings of the icons aren't clear to the user.
=> [C-4552] Show tooltips for collection action buttons

packages/web/src/components/edit/fields/AdvancedField.tsx, packages/web/src/components/edit/fields/RemixSettingsField/RemixSettingsMenuFields.tsx, packages/web/src/components/edit/fields/StemsAndDownloadsMenuFields.tsx, packages/web/src/components/edit/fields/SwitchRowField.tsx, packages/web/src/components/edit/fields/download-availability/DownloadAvailability.tsx, packages/web/src/components/edit/fields/download-availability/DownloadPriceField.tsx, packages/web/src/components/edit/fields/price-and-audience/PriceAndAudienceMenuFields.tsx, packages/web/src/components/edit/fields/stream-availability/collectible-gated/CollectibleGatedRadioField.tsx, packages/web/src/components/edit/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx, packages/web/src/components/edit/fields/visibility/VisibilityField.tsx, packages/web/src/components/modal-radio/ModalRadioItem.tsx, packages/web/src/components/upload/AudioQuality.tsx
- Copy updates across the upload/edit fields. Source of truth [in ticket description](https://linear.app/audius/issue/C-4487/update-copy-for-uploadedit-flow).
- Migrate to tooltips instead of hint boxes for disabled radio items
- Includes fix for disabling access options for public tracks.
local web
=> [C-4487, C-4554, C-4523, C-4631, C-4492]Copy updates for upload/edit

packages/web/src/components/edit/fields/visibility/VisibilityField.test.tsx
We removed the scheduled release option on tracks that are not already hidden or scheduled (because you can't set a public track to scheduled or hidden).
This broke expectations in the tests. Fixed by rendering hidden state as the default test data, and setting public manually for the one test that cares.
will only merge if passing tests
=> Fix visibility field tests

packages/mobile/src/screens/app-screen/AppTabScreen.tsx, packages/mobile/src/screens/search-screen-v2/SearchBarV2.tsx, packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx, packages/mobile/src/screens/search-screen-v2/SearchScreenV2.tsx, packages/mobile/src/screens/search-screen-v2/index.ts, packages/mobile/src/screens/search-screen-v2/searchState.ts
Improves search state and search navigation by:
1. Creating a search navigator. This can help us isolate all the search screens together, which feels nice
2. Now that we have a navigator for search, we can wrap the whole thing in the state context, so search bar and all the filter screens have access to state 🔥 
Note im not liking the search stack in SearchScreenV2, should probably separate things, but we can figure out what feels best later.
=> Improve mobile search state and navigation

mediorum/server/audio_analysis.go, mediorum/server/legacy_audio_analysis.go, mediorum/server/serve_audio_analysis.go, packages/discovery-provider/src/tasks/repair_audio_analyses.py
instead of having discovery retrigger analyses, content nodes are responsible for retrying their timed out or failed analyses if they are the first mirror based on periodic db queries. discovery just polls the results.
still uses a push-based approach based on crudr ops but it should at least enqueue jobs more efficiently than discovery. if the first mirror is online querying the db for timeouts/errors, it is updating its own db with the enqueued status, so the jobs gets properly queued without relying on crudr pushing and sweeping.
ran these queries on prod cn2:
```
audius_creator_node=# select count(*) from qm_audio_analyses where (status = 'timeout' or (status = 'error' and error_count < 3)) and CAST(mirrors AS jsonb)->>0 = 'https://creatornode2.audius.co';
count
-------
9723
(1 row) …
```
=> move audio analysis retry logic to content

packages/discovery-provider/integration_tests/tasks/entity_manager/test_social_feature_entity_manager.py, packages/discovery-provider/src/tasks/entity_manager/entities/social_features.py, packages/mobile/src/components/track-list/TrackListItem.tsx, packages/web/src/components/edit-collection/mobile/EditPlaylistPage.tsx, packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx, packages/web/src/components/track/mobile/TrackList.tsx, packages/web/src/components/track/mobile/TrackListItem.tsx, packages/web/src/components/tracks-table/TracksTable.tsx, packages/web/src/pages/collection-page/components/mobile/CollectionPage.tsx, packages/web/src/pages/history-page/components/mobile/HistoryPage.tsx, packages/web/src/pages/saved-page/components/mobile/SavedPage.tsx
We currently disable the favorite/repost actions on hidden tracks/albums. But, given that we now allow artists to hide their tracks/albums after having made them public, it is possible for users to see hidden tracks/albums in their library, so we want to allow users to be able to remove those hidden tracks/albums by unfavoriting/unreposting them.
- allow social actions on hidden tracks/albums in indexing
- show favorite/repost buttons in user library if hidden and favorited/reposted so user can undo
- updated dn integration test
- tested library page local client v stage
=> [PAY-3147] Allow unsave/unrepost hidden track/album

packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
- Counting stats are not relevant for smart collections, so we will hide them
- Play button was missing on smart collections
=> [QA-1412] Show play button and hide stats on smart collections

.changeset/curly-trainers-act.md, dev-tools/compose/docker-compose.discovery.prod.yml, packages/commands/src/claim-reward.mjs, packages/commands/src/index.mjs, packages/commands/src/tip-audio.mjs, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/package.json, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/middleware/assertRateLimiter.test.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/middleware/errorHandler.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/middleware/rateLimiter.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/assertListenRateLimiter.test.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/relay.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/utils/transaction.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/tsconfig.json, packages/libs/src/sdk/api/challenges/ChallengesApi.ts, packages/libs/src/sdk/services/Solana/SolanaRelayWalletAdapter.ts, packages/spl/src/secp256k1/Secp256k1Program.ts
tl;dr -
- Makes `evaluateAttestations` skip preflight
- Makes `solana-relay` logging and error handling better
- Changes target of `solana-relay` to ES2022
- Changes runtime of `solana-relay` to use `tsx`
- Adds `audius-cmd claim-reward`
- Changes `audius-cmd tip-audio` to use SDK
- Makes `@audius/spl`'s `Secp256k1Program` less brittle when verifying `TransactionInstruction` signatures
- Changes the way `solana-relay` tests should be run (should be `docker exec -it audius-protocol-solana-relay-1 npm run test` if we want connections to Redis)
When claiming rewards, one of the common errors is "Custom error 0x3" which corresponds to "Not enough signers", meaning the 'verified messages' account doesn't have all the required attestations (3 DN and 1 AAO on prod). Notably, this error comes …
=> [QA-1403] Fix "Not enough signers" simulation error in "Claim All Rewards" flow

packages/web/src/components/track/desktop/ConnectedPlaylistTile.tsx
When navigating to a collection detail page after the collection was initially loaded as a feed tile, the tracks not shown on the tile will never load. The playlist lineup shows only the first 5 tracks (those displayed on the tile preview). This is because we cache the incomplete copy of the tracks list and hit the cache when rendering the details page.
This solution (always force fetch when navigating from a collection tile) is a bit heavy-handed. Curious if anyone can think of a more elegant solution, but this works.
The cost incurred is only when navigating from a playlist tile, and is only extra cost when that playlist has already been fully loaded in. Other solutions include:
- We could do a check for length of the loaded lineup vs the reported tracks list length
- We could refuse to …
=> [QA-1414] Force fetch playlist on navigate from playlist tile

mediorum/server/legacy_audio_analysis.go, mediorum/server/serve_audio_analysis.go, mediorum/server/server.go
Simplifies legacy audio analysis queue backlog.
Each node scrolls over all `Qm` CIDs in random order and will start a job if node `isMine` is true and job's not done.
Notes:
* Status can be checked in psql with query `select status, count(*) from qm_audio_analyses group by 1;`
* We should pause the "backfill" crawler for a bit while this runs.
* When this is getting closer to done we should update the `order by random()` query to be smarter about finding work.
Deployed on prod CN3, confirmed making much better progress.
=> Simplify legacy audio analysis queue code.

mediorum/server/audio_analysis.go, mediorum/server/serve_audio_analysis.go, mediorum/server/transcode.go
Similar to https://github.com/AudiusProject/audius-protocol/pull/9026 for ba cids.
* Moves analysis call into transocde function to ensure minimal latency (since client will wait for audio analysis anyway).
* In background, worker looks for `uploads` records that have incomplete analysis, and greedily takes jobs if it has the file.
=> Simplify audio analysis for ba cids

packages/web/src/common/store/cache/tracks/sagas.ts
The bug was that `transcodePreview` was getting set to `true` because `formFields.preview_start_seconds` was `undefined` instead of `null`.
Local web stage - tried editing access fields in many directions and things are working.
- Switch from free -> follow-gated -> usdc-gated -> follow-gated -> free
=> [C-4652] Fix track update access conditions

packages/web/src/components/edit/fields/DatePickerField.module.css
We suspect that popup height was being calculated before the date picker fully rendered, causing it to position below the input. Hard coding the height helps seed the initial calculation so it chooses the correct position from the start.
had consistent repro of the bug locally, it stopped with the fix
=> [C-4649] fix jumping date picker popup

packages/web/src/components/edit/fields/price-and-audience/PriceAndAudienceField.tsx, packages/web/src/components/edit/fields/price-and-audience/priceAndAudienceSchema.ts
Edit preview duration for usdc-gated tracks was working on upload but broken for edit track (now that we're sharing the form between both). We need to get the track duration from the metadata directly in the edit case.
Also updating the validation logic for preview - we should be checking that preview >= 0 in all cases.
=> Fix preview times longer than track duration not erroring

packages/discovery-provider/src/api/v1/models/playlists.py
`track_count` was missing in the non-full playlist endpoint which caused this subtle bug: With a hidden playlist, If I load a playlist directly from its url, things are fine. But if I start from the library page and navigate to that playlist, the publish button is grayed out with the tooltip error saying "You must add at least 1 track to publish this playlist".
Is there any reason we shouldn't have `track_count` in the non-full endpoint?
Did not test locally - local stack was messed up for some reason. Can try again next week or on stage.
=> [C-4694] Add track_count to non-full playlist endpoint

packages/mobile/src/components/add-to-collection-drawer/AddToCollectionDrawer.tsx
Tracks from feed or private playlists were not able to be added to a public playlist because of this conditional. It says if the track is hidden but the code wasn't matching up.
Confirmed against prod. Public tracks on feed and private playlists could be added to a public playlist. Private tracks could not be added to a public playlist.
=> Fix condition for adding hidden track to playlist

packages/common/src/audius-query/hooks/usePaginatedQuery.ts
Opening this PR just so we don't lose the code, but I think the real fix is somewhere upstream. This change is safe to merge in either way though if we want. Will let @amendelsohn or @dylanjeffers decide.
There are some `any` types floating around in audius query land and I suspect that is related as well.
Deployed to prod and fixed /payments page
=> Patch paginated query bug

packages/web/src/components/edit/fields/AdvancedField.tsx
Fixes issue where tracks that have blocked api streaming dont show the correct initial value, since we never set it.
=> [C-46916] Fix Block API Streaming

mediorum/server/audio_analysis.go, mediorum/server/serve_upload.go
Images for new uploads are dynamically resized at request time, so skip any "transcode" status.
=> Mediorum: skip image transcode

packages/web/src/components/user-generated-text/UserGeneratedText.tsx, packages/web/src/pages/profile-page/components/desktop/ProfileBio.tsx
Fixes issue where user-generated text-links are not receiving context from parent text element, likely due to how linkify renders stuff. Explicitly passing through textVariant, size and strength fixes this.
=> [C-4594] Fix user-generated-text links

packages/libs/src/api/Track.ts, packages/libs/src/utils/types.ts, packages/web/src/components/edit-track/EditTrackForm.tsx, packages/web/src/components/edit/fields/RemixSettingsField/RemixSettingsField.tsx, packages/web/src/components/edit/fields/RemixSettingsField/RemixSettingsMenuFields.tsx
Fixes subtle issue where remix visibility on edit. Primarily this is because the Track api schema did not contain field_visibility, which means field_visibiilty gets removed from the edit metadata before being sent as a transaction. I'm pretty sure we want to include this, even though we are now hiding the field_visibility generally? @szonana and @rickyrombo for context.
Also fixes copy and ordering of fields in the remix-settings modal
=> [C-4695] Fix remix field visibility

packages/mobile/src/screens/sign-on-screen/screens/ConfirmEmailScreen.tsx, packages/mobile/src/screens/sign-on-screen/screens/SignInScreen.tsx
Fixes OTP on mobile - we weren't sending the fingerprint on signup after OTP.
Also for some reason the response from fingerprint was just the string directly - not wrapped in any object, seems to be different from web.
Not sure this async stuff is the best pattern but it works for now. Probably `useAsync`?
Tested on local ios stage
=> Fix mobile single-OTP signup

packages/mobile/src/components/oauth/OAuthWebView.tsx
We were calling `exit()` from the polling loop which causes the auth popup to close entirely. Instead, we want to return from the polling function and wait until all the conditions are met.
Working twitter and instagram auth on mobile sim prod. Broken before change but working now.
=> [QA-1419] Fix twitter/instagram oauth exiting early

packages/common/src/audius-query/createApi.ts
We were using `typeof data === 'object'` check to determine whether to apply normalization, but that returns `true` for arrays since `typeof []` returns `'object'`
local web purchases table is working again
=> [QA-1426] Fix audius-query array normalization

packages/common/src/services/audius-api-client/AudiusAPIClient.ts, packages/web/src/common/store/cache/tracks/utils/fetchAndProcessStems.ts, packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts, packages/web/src/components/user-generated-text/UserGeneratedText.tsx, packages/web/src/store/application/ui/stemsUpload/sagas.ts
Fixes subtle issue where refetching track stems gives old data due to caching layer. The fix here is to add newly added stemIds to getStems request to ensure we get a cache miss.
This has brought up larger questions around stale data when editing content, which ill bring up to larger audience this week.
=> [C-4651] Fix stems upload refetch bug

packages/web/src/components/upload-confirmation-modal/UploadConfirmationModal.tsx, packages/web/src/pages/upload-page/UploadPage.tsx
Fixes conditional copy on upload publish confirmation modal when publishing hidden/scheduled albums.
_Note:_
The styling on the modals looks off compared to designs because the harmony modal components don't match the design spacing. Leaving this for its own separate work item, but we may want to fix it before we ship.
Also had to manually center the text in this modal, but ideally we fix it across harmony modals. Wasn't sure if we're ready to commit to that now.
Figma vs web:
local web
=> [C-4630] Update Confirm Modal copy

packages/common/src/audius-query/createApi.ts
Missed a case in https://github.com/AudiusProject/audius-protocol/pull/9060 where the api data is an array, but we want to wrap it in the schema key.
`useGetFeaturedArtists` was returning undefined but is now working
Also tested other usages of audius-query which all look good
=> Respect schema key arrays

packages/discovery-provider/plugins/notifications/src/__tests__/mappings/usdcPurchaseBuyer.test.ts, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/usdcPurchaseSeller.test.ts, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/usdcTransfer.test.ts, packages/discovery-provider/plugins/notifications/src/__tests__/mappings/usdcWithdrawal.test.ts, packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/claimableReward.ts, packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/purchase.ts, packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/rewardInCooldown.ts, packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/sale.ts, packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/transfer.ts, packages/discovery-provider/plugins/notifications/src/email/notifications/preRendered/withdrawal.ts, packages/discovery-provider/plugins/notifications/src/processNotifications/indexAppNotifications.ts, packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/rewardInCooldown.ts, packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseBuyer.ts, packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcPurchaseSeller.ts, packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcTransfer.ts, packages/discovery-provider/plugins/notifications/src/processNotifications/mappers/usdcWithdrawal.ts, packages/discovery-provider/plugins/notifications/src/remoteConfig.ts, packages/identity-service/src/notifications/emails/downloadMobileApp.html, packages/identity-service/src/notifications/emails/otp.js, packages/identity-service/src/notifications/emails/welcome.js, packages/identity-service/src/notifications/sendDownloadAppEmails.js, packages/identity-service/src/routes/recovery.js, packages/identity-service/src/routes/welcomeEmail.js, packages/identity-service/src/utils/otp.js
Includes many misc QA changes for emails.
* Add optimizely config for new reward in cooldown notification.
* Only OTP and recovery do not have un-subscription. Unsubscribe and email preferences are now linked to html template.
* Remove download icons on large images by adding a link to them.
* Add links to content for album/track art. 
* Use higher res track art for welcome page in responsive display.
* Email subject lines to match titles of emails.
* Add $ to dollar values and only show pay extra field when it's not 0.
* Update trophies for different rewards.
Ran various emails on stage for sanity check but will do full QA pass as soon as it's on stage.
=> Update all emails: updated design, manage preferences

packages/common/src/api/search.ts, packages/mobile/src/screens/search-screen-v2/NoResultsTile.tsx, packages/mobile/src/screens/search-screen-v2/search-results/AlbumResults.tsx, packages/mobile/src/screens/search-screen-v2/search-results/AllResults.tsx, packages/mobile/src/screens/search-screen-v2/search-results/PlaylistResults.tsx, packages/mobile/src/screens/search-screen-v2/search-results/ProfileResults.tsx, packages/mobile/src/screens/search-screen-v2/search-results/TrackResults.tsx, packages/mobile/src/screens/search-screen-v2/searchState.ts
* Add NoResultsTile
* Add empty state for search results screens
* Update search to not request when no filters or query are passed
* Fix TrackResults screen pass filters properly and to avoid constant rerenders
=> [C-4702] Add empty states for mobile search results and fix track search request

packages/libs/src/sdk/services/Solana/programs/BaseSolanaProgramClient.ts, packages/libs/src/sdk/services/Solana/programs/types.ts
Allows callers to specify the priority of their transaction, as a percentile of recent fees.
Modeled based on https://docs.helius.dev/solana-rpc-nodes/priority-fee-api
TBD
=> [PAY-3090] Add priority fees to SDK transactions (opt in)

packages/web/src/components/track/GatedContentLabel.tsx
Small bug I noticed - wrong color when the gated content was unlocked.
=> Fix unlocked premium content label color

packages/mobile/src/components/details-tile/TrackMetadataList.tsx, packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx, packages/mobile/src/screens/search-screen-v2/SearchScreenV2.tsx, packages/web/src/pages/search-page-v2/SearchPageV2.tsx, packages/web/src/utils/route.ts
Update Track details tile metadata items to link to the search page with the proper category and filters set
Update category buttons to clear search filters
Update search screen to update context state on params change
=> [C-4589] Add links from track tile screen to search screen

packages/harmony/src/components/modal/ModalContentPages.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountListItem/ManagerListItem.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsManagingYouHomePage.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsManagingYouSettingsModal.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageHomePage.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageSettingsModal.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/ConfirmAccountManagerPage.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/FindAccountManagerPage.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/RemoveManagerConfirmationPage.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/StopManagingConfirmationPage.tsx, packages/web/src/pages/settings-page/components/desktop/ManagerMode/types.ts
In case the overly cute but vague title didn't make it obvious... 
This updates the `ModalContentPages` component to allow manual overriding of the transition direction for special cases and then updates the modals used for Manager Mode to use a 'forward' direction when transitioning from confirmation states on the final page back to the home page.
Bonus fix: In a previous PR, I had messed up the logic for when to show the overflow menu such that you could not longer cancel a pending invite.
https://github.com/AudiusProject/audius-protocol/assets/1815175/e27500b5-c9fc-47b5-a9b6-2781cfd2f321
=> [PAY-3132] Manager Mode Modal Movement Mending

packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx, packages/mobile/src/components/premium-content-purchase-drawer/PurchaseSuccess.tsx
Make this button bigger!
+ just moving some code around for cleanliness
=> Make view content button large on mobile purchase success

packages/discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py, packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py, packages/discovery-provider/src/tasks/entity_manager/entities/track.py
Allows tracks and playlists to be unlisted in DN indexing.
Missed this when I was relaxing indexing constraints.
=> Allow unlisting tracks and playlists in DN indexing

packages/web/src/common/store/pages/trending-playlists/lineups/sagas.ts
Duplicate playlists show in playlist trending because of a pagination bug. Client side we filter out some accounts (actually, just `@audiusproject`). This change checks to see how many playlists are filtered out and increments the fetching offset by that number. Will follow up to see if we still even care about this behavior, but this change is safe.
```
```
no dupes
=> [QA-1430] Fix duplicate trending playlist

packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/config.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/index.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/health/health.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/listen.ts, packages/identity-service/package.json, packages/identity-service/src/config.js, packages/identity-service/src/routes/trackListens.js
Signs the play with the identity relayer wallet, adds the public key of this wallet to solana relay so they can be verified, and forwards listens from identity. If it fails, identity falls back and submits it to solana itself.
should be merged after https://github.com/AudiusProject/audius-docker-compose/pull/523
`npm run web:dev` against local stack and listening to an uploaded track.
=> PROTO-1847: identity discprov plays

packages/common/src/hooks/useAccessAndRemixSettings.test.ts, packages/common/src/hooks/useAccessAndRemixSettings.ts, packages/mobile/src/screens/edit-track-screen/screens/AccessAndSaleScreen.tsx, packages/web/src/components/edit/fields/price-and-audience/PriceAndAudienceMenuFields.tsx, packages/web/src/components/edit/fields/stream-availability/collectible-gated/CollectibleGatedRadioField.tsx, packages/web/src/components/edit/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseGatedRadioField.tsx, packages/web/src/components/edit/fields/visibility/VisibilityField.test.tsx, packages/web/src/components/edit/fields/visibility/VisibilityField.tsx
Remove the restriction where tracks/albums' visibility and audience could not be _more_ restricted.
This PR allows artists to freely edit track and album accessibility conditions from any option to any other.
Local web and mobile dapps vs stage.
=> [PAY-3140] Allow freely editing track/album access gate

packages/discovery-provider/src/queries/download_csv.py
Country will exist after purchasing goes through sdk & payment router. Add support to CSV download so artists can see where their fans are buying from.
Will wait to merge & test on stage after sdk purchases is turned on
=> [PROTO-1824] Add country to csv download for sales

packages/discovery-provider/src/queries/query_helpers.py
Thought I had already fixed this but turns out there is yet another old legacy endpoint that is actually the one currently used by our client.
Ideally we should migrate to the v1 endpoints but that's a deeper dive.
Confirmed `track_count` is present in the response.
Something about the way the client fetches collections is different between local stack vs stage - i couldn't figure out how to make sure the client actually reads the data from this endpoint correctly but i made a ticket to follow-up on this once it lands on stage.
=> [C-4694] Add track_count to playlists query endpoint

packages/common/src/store/cache/collections/reducer.ts, packages/common/src/store/cache/reducer.ts, packages/common/src/store/cache/tracks/reducer.ts, packages/common/src/store/cache/types.ts, packages/common/src/store/cache/users/reducer.ts
`fetchCollectionTracks` was failing in mobile because the permalink wasn't set in cache. This broke the cache's track fetching logic.
The reason permalink was missing is that the `asCache` reducer 'inheritance' was not passing the kind through properly. Additionally, the types were incorrect which led us to unpack the entity data improperly. Because of the above, the `addEntries` helper was not able to add the permalinks to the cache
- Pass `kind` through `asCache` reducers
- Fix `EntriesByKind` types
- Unpack entries properly in cache/ [collections, tracks, users] reducers
Fixed lineup example on mobile:
=> [C-4595] Fix addEntries call in asCache reducers

packages/identity-service/src/app.js, packages/identity-service/src/routes/recovery.js, packages/identity-service/src/routes/welcomeEmail.js
* needsRecoveryEmail in UserEvents is always null on sign up because recovery is what creates the UserEvents row and it's missing fields. changing it to upsert makes it reliable.
* Add email to sendgrid contacts on sign up.
Fixes C-4525.
Fixes QA-1420.
Ran on staging. Confirmed needsRecoveryEmail is false on sign up and email gets added to sendgrid contacts.
=> Fix needsRecoveryEmail flag and add emails to sendgrid contacts

packages/mobile/src/components/lineup-tile/CollectionTile.tsx, packages/web/src/components/collection/components/RepostsFavoritesStats.tsx, packages/web/src/components/collection/desktop/CollectionHeader.tsx, packages/web/src/components/collection/mobile/CollectionHeader.tsx, packages/web/src/components/track/mobile/PlaylistTile.tsx
Hide all stats in the following places:
- Collection Page
- Tiles (DMs)
track from owner's perspective still shows stats:
=> [C-4711] Hide play/repost stats for hidden content

packages/web/src/components/track/OwnerActionButtons.tsx
We forgot to update the edit (pencil) button on track tiles to navigate to the new edit page instead of opening the old modal.
=> Nav to edit page instead of edit modal from track tile

packages/mobile/src/components/track-list/TrackListItem.tsx, packages/web/src/components/table/components/OverflowMenuButton.tsx, packages/web/src/components/tracks-table/TracksTable.tsx
Never allow share and add to playlist options for hidden tracks, unless you're the track owner.
We'd overlooked the overflow menu in the tracks table inside the collection page.
public:
hidden:
owner:
public:
hidden:
owner:
=> [C-4714] Disallow share/add to playlist for hidden tracks

packages/web/src/common/store/pages/search-page/lineups/tracks/sagas.ts
Thought the feature flag check was safe to remove here but because we aren't passing in `dispatch` in search v1 things break
Tracks results page in search v1 works
=> Fix Track more results page in search v1

packages/common/src/store/cache/reducer.ts
On the cache entity update, `lodash` `mergeWith` was giving us `stream_conditions` that looked like:
```
stream_conditions: {
follow_user_id: x,
usdc_purchase: { xyz}
}
```
and ended up just accepting the first member again. We needed to special-case this to only take the new value.
https://github.com/user-attachments/assets/aa2daab2-7100-4e64-8a0f-82bb9e3acc0b
=> [C-4646] Fix stream_conditions optimistic update on track edit

packages/mobile/src/components/lineup-tile/TrackTile.tsx, packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx, packages/mobile/src/components/track-list/TrackListItem.tsx, packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx, packages/web/src/components/track/desktop/ConnectedTrackTile.tsx, packages/web/src/components/track/desktop/TrackListItem.tsx, packages/web/src/components/tracks-table/TracksTable.tsx
Spoke offline with design and confirmed we should now allow all gated content to be playlist-addable, even if it's locked.
Sliding in a feature flag cleanup while I was checking mobile allows this.
=> Allow gated content to be added to playlist

packages/web/src/components/tracks-table/TracksTable.tsx
Hide plays, saves, reposts counts for hidden tracks
non-owner
owner
library (has both hidden and purchase-gated)
=> [C-4771] Hide stats in TracksTable for hidden tracks

packages/common/src/store/search/selectors.ts
This was causing a crash for users who had Search V2 enabled, populated their recent searches, and then went back to search v1
Both search v1 and v2 work
=> Filter out searchv2 history items for search v1

comms/DockerfileFast, comms/discovery/pubkeystore/recover.go
Initially was thinking we could query eth directly, but since there is still a relay step, the outer tx is not actually signed by user's wallet.
So try other tables to find a txhash that is signed by user.
Deployed to sandbox, modified users txhash + cleared cache + tested with affected user's pubkey.
=> [PAY-3160] Try other tables for txhash if users table doesn't work.

packages/common/src/api/account.ts, packages/common/src/audius-query/schema.ts, packages/common/src/store/cache/collections/reducer.ts
Currently the `currentWeb3User` gets cached as a top level schema and the playlists under it get matched to the playlist schema. Because they are stubs, they don't get cached properly and prevent the web3 user from being cached.
The symptom of this is the account switcher doesn't load.
Account switcher now loads
=> Fix account playlists entering cache and caching of currentWeb3User

packages/common/src/store/ui/edit-access-confirmation-modal/slice.ts, packages/common/src/store/ui/edit-access-confirmation-modal/types.ts, packages/web/src/components/edit-access-confirmation-modal/EditAccessConfirmationModal.tsx, packages/web/src/components/edit/fields/visibility/VisibilityField.tsx
_Note: Some of this is pending design review. CC: @julianbaker check out the screenshots below and confirm whether we want the confirm on edit field behavior. (As opposed to on form submit)_
- Show visibility/audience change modal in all relevant cases
- Update modal copy
- Both confirmations now show on save of the ContextualMenu
working for each combination of starting and ending states
=> [C-4778, C-4786] Update visibility change confirmation

packages/mobile/src/components/offline-placeholder/OfflinePlaceholder.tsx, packages/web/src/common/store/account/sagas.js, packages/web/src/common/store/backend/sagas.ts
To some degree the idea of offline mode and the changes in https://github.com/AudiusProject/audius-protocol/pull/9121 aren't really compatible. We can't afford to clear out the current user if the fetch fails for some reason. And we also can't really count on reachability to be the reason for the failure -- it could be a spotty connection.
So, instead here just don't reset the account if the fetch fails. Confirmed offline mode works & fixed the styling which was broken since some of the harmony move.
Testing is very painful, you have to do a complete build every time you want to see your changes when the device is offline
```
npm run ios:stage -- -- --device "Raymond’s iPhone" …
```
=> Fix offline mode after fast load change

mediorum/ddl/ddl.go, mediorum/ddl/drop_audio_analysis_ops.sql
crudr storm ops still seem to be being processed. stale data is causing duplicate work and overwriting results. drop all the old ops and allow the simplified mediorum analysis repairer, which issues minimal crudr ops, to move forward.
=> drop old audio analyses ops

packages/identity-service/src/routes/user.js
Removes the PUT /user/email route because changing email is now supported through the one /POST authentication route.
Hold merge on this as it will break old clients that attempt to change emails once it goes out.
CI
=> PROTO-1879: rm PUT /user/email route

packages/web/src/components/edit/fields/download-availability/DownloadAvailability.tsx
Allow editing access for download-only gated tracks.
Local web dapp vs stage.
=> [PAY-3164] Allow editing access for download-only gated tracks

packages/common/src/store/cache/collections/selectors.ts
The user was being fetched but then overwritten if collection has a user field.
This begs the question if user should have a populated value in cache, but in normalized entities, we'll have a user id reference in that spot.
Because the returned user had `user: string`, downstream user.handle call failed.
=> [C-4719] Fix local collections selector

packages/discovery-provider/integration_tests/tasks/entity_manager/test_playlist_entity_manager.py, packages/discovery-provider/integration_tests/tasks/entity_manager/test_track_entity_manager.py, packages/discovery-provider/src/tasks/entity_manager/entities/playlist.py, packages/discovery-provider/src/tasks/entity_manager/entities/track.py, packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx, packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx, packages/web/src/components/collection/desktop/CollectionHeader.tsx, packages/web/src/components/collection/mobile/CollectionHeader.tsx, packages/web/src/components/track/GiantTrackTile.tsx
The problem: I had a scheduled album and hit the publish button. The "releases on x date" music badge at the top right was still present, indicating that the `is_scheduled_release` flag was still true, and `release_date` was still set to a future date.
- Front-end fix: don't show scheduled release music badge if `is_unlisted` and `is_scheduled_release` are false.
- Protocol fix: if publishing a track/playlist that was previously unlisted/private, set `is_scheduled_release` to false and `release_date` to now. Assuming everything is in UTC.
- Add a unit test for this change.
Note: order matters in entity manager - we update `release_date` _before_ updating `is_unlisted`, so the override for `release_date` should work correctly.
Unit tests pass, confirmed UI fix on web stage.
=> [C-4777] Prevent public track with future release date

packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/listen/trackListenInstructions.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/relay.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/utils/transaction.ts
Not sure why we hardcode connections[0] in a lot of places. Lmk if there are other insights, but we are driving too much traffic to the [0]th endpoint specified in config. Want to load balance this better.
Untested, but will see on staging
=> Cycle solana RPC connections better

packages/discovery-provider/src/api/v1/utils/extend_notification.py
The specifier looks like "1=>2" and can't be int-encoded.
Currently my notifs on stage won't load. Seems like we handle this as a string client side anyway https://github.com/AudiusProject/audius-protocol/blob/165a890c8e9ecfcfcb6367d9d5edb741da09abd4/packages/discovery-provider/plugins/notifications/src/types/notifications.ts#L131
=> Specifiers should be strings in challenge notifs

packages/mobile/src/components/now-playing-drawer/ActionsBar.tsx, packages/web/src/components/now-playing/NowPlaying.tsx, packages/web/src/components/now-playing/components/ActionsBar.tsx, packages/web/src/components/play-bar/desktop/components/SocialActions.tsx, packages/web/src/components/play-bar/mobile/PlayBar.tsx
Hide all social actions on now playing bar/drawer.
on mobile we still want to show the cast option and the overflow menu.
web
mobile-web
ios
=> [C-4794] Hide social actions on now playing drawer for hidden tracks

packages/web/src/common/store/social/tracks/sagas.ts
We intentionally show download all for mobile when there's only the full track parent. This logic gets us no benefit because we handle the case where there is only a parentTrackId below. Anyway, downloads on moweb working well for me.
Stage locally mobile web in browser
=> [QA-1443] Remove faulty download all logic

.changeset/smooth-crews-rush.md, packages/commands/README.md, packages/commands/src/account-managers.mjs, packages/commands/src/index.mjs, packages/discovery-provider/integration_tests/tasks/entity_manager/test_grant_entity_manager.py, packages/discovery-provider/src/api/v1/users.py, packages/discovery-provider/src/tasks/entity_manager/entities/grant.py, packages/libs/src/sdk/api/generated/default/apis/PlaylistsApi.ts, packages/libs/src/sdk/api/generated/default/apis/TracksApi.ts, packages/libs/src/sdk/api/generated/default/apis/UsersApi.ts, packages/libs/src/sdk/api/generated/default/models/Playlist.ts, packages/libs/src/sdk/api/generated/full/apis/SearchApi.ts, packages/libs/src/sdk/api/generated/full/apis/UsersApi.ts, packages/libs/src/sdk/api/generated/full/models/PlaylistFull.ts, packages/libs/src/sdk/api/generated/full/models/PlaylistFullWithoutTracks.ts, packages/libs/src/sdk/api/grants/GrantsApi.ts, packages/libs/src/sdk/api/grants/types.ts
This adds some basic filtering to the managers endpoints, allowing query parameters for `is_approved` and `is_revoked`. Note that the default behavior of these endpoints is a little particular. By default, the values are `is_approved=null` and `is_revoked=false`, which will return all non-revoked grants (i.e. both approved and pending requests). And if you wanted to filter it down to only approved grants, you would just do `?is_approved=true`. 
It's not actually possible to pass `is_revoked=null` to fetch all grants regardless of revocation status. But this is an edge case that isn't worth the effort to implement. The end result is that getting the full set of all grants will be two requests.
Some other related changes:
* Updated  GrantsApi to remove the `rejectGrant` call. During …
=> [PAY-2783] Add filters to manager endpoints

packages/web/src/services/analytics/amplitude.ts
Add UTM tracking to web client. Useful for tracking traffic sources like emails, ads, direct link referrals, etc.
Unfortunately the react native SDK doesn't have this option but i think it could be manually set. Will do if this proves useful.
https://community.amplitude.com/data-instrumentation-57/is-it-possible-to-track-utm-parameters-for-mobile-apps-1832
Confirmed URLs like `http://localhost:3002/feed?utm_source=isaactest2` now record UTM and referrer data.
=> Add UTM tracking in amplitude

packages/common/src/models/Analytics.ts, packages/web/src/components/table/Table.tsx, packages/web/src/components/table/components/TablePlayButton.tsx, packages/web/src/components/tracks-table/TracksTable.tsx
Show locked and premium buy buttons for locked tracks in library and allow user to unlock. Make rows unclickable until user has access.
https://github.com/user-attachments/assets/b3732b5c-1ab8-4672-bfc6-e31231f50278
=> [PAY-3148] Add better support for gated tracks in library

packages/discovery-provider/src/queries/get_collection_library.py
See this comment on line 94 of `get_collection_library.py`
```
```
But we are actually filtering by `SaveType.playlist` or `SaveType.album` in the query. We shouldn't do this until we migrate the saves to have correct save type.
Unclear how this was ever working..
Tested against local stack:
- Created 1 playlist and 1 album from user A.
- User B favorites both.
- Confirmed each of them appear in the correct tab in library.
@amendelsohn will follow up and confirm that this is good on staging.
=> Include all save types in library collections endpoints

packages/harmony/src/components/button/FilterButton/FilterButton.tsx, packages/harmony/src/components/button/FilterButton/types.ts
The #9112 changes caused only `fillContainer` variant FilterButtons to call `setIsOpen`, however the search sorting dropdowns as well as card vendor dropdown in the payment flow are `replaceLabel`. Afaict it should be fine to have these open on click
Confirmed both variants are working
=> [C-4787] Fix advanced search sort dropdowns

packages/mobile/src/screens/search-screen-v2/SearchBarV2.tsx, packages/web/src/components/search-bar/ConnectedSearchBar.jsx, packages/web/src/components/search/SearchBarV2.jsx
Add clear search button on web and mobile
=> [C-4671] Add clear search button

packages/web/src/pages/settings-page/components/desktop/ManagerMode/ManagerModeSettingsModal.tsx
This was taken out in a previous PR as the reject was just an alias for `removeManager`. I forgot to update the one place we call it.
=> Fix usage of missing SDK function for Manager Mode reject flow

packages/mobile/src/components/notification-reminder/NotificationReminder.tsx, packages/mobile/src/harmony-native/components/input/SelectablePill/SelectablePill.tsx, packages/mobile/src/harmony-native/components/input/SelectablePill/types.ts, packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx, packages/web/src/components/edit/fields/AdvancedField.tsx, packages/web/src/components/lineup/LineupProvider.tsx, packages/web/src/components/track/desktop/ConnectedTrackTile.tsx, packages/web/src/components/track/desktop/stats/Stats.module.css, packages/web/src/pages/search-page-v2/search-results/TrackResults.tsx
Fix a few UI issues:
* Don't allow multi tapping `SelectablePill`
* I removed the GestureHandler because using react-native press handlers seemed just as responsive and prevents multi taps
* Show small stats in lineup track tiles when in grid layout
* Show correct bpm label in edit bpm input
=> [C-4672] [C-4745] [C-4807] Advanced search UI qa fixes

packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/app.ts, packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/queries.ts, packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/slack.ts, packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/utils.ts
When run manually the bot will take in a custom specifier so rewards can be disbursed from past weeks with ease.
=> PROTO-1881: custom date for rewards bot

packages/common/src/store/search/selectors.ts, packages/mobile/src/components/user-list/UserCard.tsx, packages/mobile/src/harmony-native/components/Text/Text.tsx, packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx, packages/mobile/src/screens/list-selection-screen/ListSelectionScreen.tsx, packages/mobile/src/screens/search-screen-v2/SearchCatalogTile.tsx, packages/mobile/src/screens/search-screen-v2/SearchItem.tsx, packages/web/src/pages/search-page-v2/RecentSearches.tsx, packages/web/src/pages/search-page-v2/SearchHeader.tsx
Decided to knock out a bunch of the easy ones, going to tackle the more high pri / difficult ones next!
* Truncate query with ellipsis when it overflows
* Decrease padding below web search header in All category
* Reduce spacing above Select Genre input in the genre drawer
* Bigger touch target for search icon in navbar
* Artist card handles should only be a single line
* Align Search the Catalog tile margins with recent searches
* Recent searches loading state padding incorrect
=> [C-4675] [C-4665] [C-4736] [C-4732] [C-4737] [C-4734] [C-4742] Advanced search UI qa fixes part 2

packages/web/src/common/store/cache/collections/commonSagas.ts, packages/web/src/components/collection/desktop/PublishConfirmationModal.tsx, packages/web/src/components/edit-collection/EditCollectionForm.tsx, packages/web/src/components/edit-track/EditTrackForm.tsx, packages/web/src/components/edit-track/ReleaseTrackConfirmationModal.tsx, packages/web/src/components/edit/fields/visibility/VisibilityField.tsx, packages/web/src/components/publish-track-confirmation-modal/PublishTrackConfirmationModal.tsx
- Fix cascading track publish in several cases (applies to album edit and release button)
- When all tracks are scheduled AND album is scheduled, release the tracks
- In all other cases, when mixed hidden, public, and scheduled, only release the hidden tracks
- Fix publish album confirmation modal
- `isAlbum` conditional ternary rendering was backwards
- Add publish track confirmation modal to track edit onSubmit
- Remove change confirmation on VisibilityField since we do it on edit form submit now
Tested several cases with different configurations of hidden/scheduled/public tracks in each type of album. The correct modal displayed in each case.
=> [C-4810, C-4801, C-4790, PAY-3171] Fix publish album tracks behavior; update confirmation modals

packages/common/src/audius-query/createApi.ts
Fixes issue with audius-query force which was leading to infinite loop on purchases tab.
Long story short, we need a "forcing" state to prevent more fetches from happening while waiting for the fetch to return. This extra logic feels not amazing, but given this is on prod, i think this is an okay patch. Any feedback would be great though.
=> [QA-1457] Fix purchase tab

packages/common/src/api/search.ts, packages/common/src/audius-query/createApi.ts, packages/common/src/audius-query/types.ts, packages/common/src/audius-query/utils.ts, packages/mobile/src/harmony-native/components/Button/FilterButton/FilterButton.tsx, packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx, packages/mobile/src/screens/search-screen-v2/search-results/TrackResults.tsx, packages/mobile/src/screens/search-screen-v2/searchState.ts, packages/web/src/common/store/pages/search-page/lineups/tracks/sagas.ts, packages/web/src/pages/search-page-v2/search-results/AlbumResults.tsx, packages/web/src/pages/search-page-v2/search-results/AllResults.tsx, packages/web/src/pages/search-page-v2/search-results/PlaylistResults.tsx, packages/web/src/pages/search-page-v2/search-results/ProfileResults.tsx, packages/web/src/pages/search-page-v2/search-results/TrackResults.tsx, packages/web/src/pages/search-page-v2/utils.tsx
* Adjust limit and offset params so requests have the same args and we don't make superfluous requests
* Keep track of previous search params so TrackResults doesn't refetch data that was already fetched on AllResults
* Add `fetchSaga` to audius-query that supports the same caching and request skipping logic `useQuery` does
Still working on some profiling because there seems to be a lot of render jank but this should be good to review so far!
Tested web search categories, confirmed no extra requests are being made, ran react profiler
=> [C-4804] Improve search performance pt 2

packages/mobile/src/components/rate-cta-drawer/RateCtaDrawer.tsx, packages/mobile/src/screens/update-required-screen/UpdateRequiredScreen.tsx, packages/mobile/src/utils/os.ts, packages/mobile/src/utils/playStore.ts
Realized we also want to route to solana-dapp-store on rate-cta, not just update-screen
Tested on saga
=> [C-4698] Route to solana play store in rate-cta-drawer

packages/discovery-provider/src/queries/generate_unpopulated_trending_tracks.py, packages/web/src/common/store/pages/trending/lineups/trending/retrieveTrending.ts
Remove hidden tracks from trending. Need both the DN and client filters. DN because the trending generation was missing the filter, client because DN may return temporarily hidden tracks because of its cache.
Even with this change, itt is possible that trending still has hidden tracks because when DN returns the cache hidden tracks, it will return them as if they are not hidden because the value in the cache would have been `is_unlisted: false`. The only fully correct solution I can think of here is remove the cache in DN entirely. An alternative is to reduce the cache TTL. _My fix_ here is that if client already sees a track as hidden, e.g. user already visited hidden track page in same session then goes to trending, the trending list would not show that hidden track.
Please let me know …
=> [PAY-3181][PAY-3182] Remove hidden tracks from trending

packages/web/src/components/edit/fields/SwitchRowField.module.css
checked all other SwitchRowField instances for broken styling
=> [C-4849] Fullwidth AI attribution dropdown

packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx, packages/mobile/src/screens/edit-track-screen/EditTrackScreen.tsx, packages/mobile/src/screens/edit-track-screen/fields/VisibilityField/VisibilityScreen.tsx, packages/mobile/src/screens/edit-track-screen/screens/PriceAndAudienceScreen.tsx, packages/web/src/components/edit-track/EditTrackForm.tsx, packages/web/src/components/edit/fields/price-and-audience/PriceAndAudienceField.tsx
Only show the confirmation modals/drawers during edit flows.
local web and ios vs stage
=> [PAY-3174][PAY-3179] Do not show confirmation modals for edit access during upload

mediorum/server/serve_image.go
rewrite resized version if `skipCache=true` is set
=> image skipCache goes all the way

packages/common/src/audius-query/createApi.ts
Fixes issue where "force: true" option can replace the instance of the current user, leading to an issue where all the sidebar playlists disappear. This is due to a big issue adding account information in the user cache. Rather than deal with that now, since that would require a big refactor, we are adding a hack in audius-query to delete the current user from the addEntries call when force is true.
=> [QA-1455] Fix disappearing playlists in sidebar

packages/web/src/components/drawer/Drawer.module.css
Fixes issue with mobile web drawer overflow on mobile browsers. The issue was using `vh` since mobile browsers view height includes the browser ui, leading to incorrect overflow. This being corrected with an arbitrary 100px, which was inconsistent for most browsers. The fix is to ultimately just use 100% which will calculate based on the actually available space.
=> [C-4829] Fix mobile web drawer overflow

packages/discovery-provider/src/api/v1/helpers.py
1. The output marshaller for `playlist_model` expects that the type of `playlist_contents` will be the same shape as that of `added_timestamps`. This is due to the change in #5570 where we replace `playlist_contents` with `added_timestamps` as a client/SDK convenience. But we only do that in the `playlists` endpoints. `/reposts` is missing this behavior so the marshaller malfunctions on the playlist items from that endpoint.
2. Noticed that the utility function for computing `added_timestamps` incorrectly returns the entire playlist as a response if `playlist_contents` is empty. I think this was originally meant as a "decorator" method that would modify the contents in place and return the modified object, then converted to a utility that computes the value of a property and returns it. I …
=> [PAY-3192] Fix two issues with playlist_contents and added_timestamps

packages/discovery-provider/src/api/v1/playlists.py
Interesting timing, there was an outstanding issue with `get_bulk_playlists` not populating `playlist_contents`.
The logic to filter out hidden tracks #8985 expects `playlist_contents` to exist but the `get_bulk_playlists` wasn't populating it from `added_timestamps` like `get_playlist` is. Ironic that we were just discussing #9217 
Can properly fetch playlists using bulk endpoint on local stack
=> [QA-1449] [C-4808] Reassign playlist_contents in get_bulk_playlists

packages/web/src/components/menu/TrackMenu.tsx, packages/web/src/components/now-playing/NowPlaying.tsx, packages/web/src/components/track/mobile/ConnectedTrackListItem.tsx, packages/web/src/components/track/mobile/ConnectedTrackTile.tsx, packages/web/src/pages/track-page/components/mobile/TrackHeader.tsx
Gated content is allowed in playlists, but not hidden content unless you're the owner.
We missed a case on web and a few cases on mobile + mobile web
=> [C-4792] Disallow Add To Playlist for hidden tracks

packages/mobile/src/screens/search-screen-v2/SearchItem.tsx
* Change from using `Link` `to` to using our custom `useNavigation` hook. This fixes a bug where pushing to the search stack broke the navigation state and caused navigating back to go directly to the feed
* Minor styling tweaks for search items
Confirmed navigation works as expected on simulator and device
=> [C-4841] Fix search v2 navigation on mobile

packages/web/src/components/edit/fields/visibility/ScheduledReleaseDateField.tsx
Improves same day scheduled release on web by setting time to 11:59 pm when releaseDate selected for same day. This already exists on mobile.
=> Fix same day scheduled release on web

packages/common/src/api/library.ts
There is another PR in the pipeline that will update this code to use the new transformers. But until that is merged, this will fix the type error on `main`
`npm run verify -w @audius/web -w @audius/mobile -w @audius/common`
=> Fix type error from SDK update

mediorum/ddl/ddl.go, mediorum/ddl/drop_uploads_audio_analysis_ops.sql, mediorum/server/audio_analysis.go, mediorum/server/legacy_audio_analysis.go
- remove audio_analysis_status: timeout ops updates to the uploads table
- advance crudr cursors, which are currently weeks behind, to  `01J3C13JH1X7SHJYZ7PV250WPK` (`2024-07-22T01:32:42.913Z`)
- give all remaining legacy qm id work to the prod storeall node, since SPs are not picking up the remaining ~200,000 for some reason
- give ba analysis backfill jobs to prod cn2 in addition to the preferred hosts
=> prune ops. advance crudr cursors. give all audio analysis work to storeall node

packages/mobile/src/hooks/useNavigation.ts, packages/mobile/src/screens/app-screen/AppScreen.tsx, packages/mobile/src/screens/app-screen/AppTabScreen.tsx
React Navigation's native stack navigator has an issue that allows the same screen to get pushed on the stack multiple times, so we've created a custom "push" callback that prevents duplicate screens from getting pushed. However, in this case, the "back" navigation happens in the context of a different stack navigator, so the "last action" is still the "edit track screen" when the user backs out of editing their track, causing our custom override to erroneously consider it a dupe if we tried to edit the track again.
This PR follows the same logic used in the AppTabScreen to unset the lastAction on the transition end of the stack navigator, also moving the logical components to the hook file to keep them close to the usage. Additionally, to prevent white screens for the edit track screen …
=> PAY-3186 Fixes issue preventing edit screen from opening twice

packages/mobile/src/screens/search-screen-v2/SearchCategoriesAndFilters.tsx
Reset search filter scroll position when first coming to the screen (needed when navigating from a TrackScreen for example)
=> [C-4847] Reset search filters scroll position

packages/discovery-provider/plugins/pedalboard/apps/backfill-audio-analyses/src/backfill_discovery.ts, packages/discovery-provider/src/tasks/entity_manager/entities/track.py, packages/discovery-provider/src/tasks/metadata.py, packages/discovery-provider/src/tasks/repair_audio_analyses.py
add stricter musical key validation to the backend by defining an enum that matches the keys output by the c++ keyfinder https://github.com/AudiusProject/audius-protocol/blob/main/mediorum/cpp/keyfinder.cpp#L10
=> check musical key enum in EM and repairer

packages/mobile/src/components/details-tile/CollectionMetadataList.tsx, packages/mobile/src/components/details-tile/MetadataItem.tsx, packages/mobile/src/components/details-tile/TrackMetadataList.tsx
The Text component styling was overriding the visible link styling because it was nested inside. Moving the Text outside fixes the issue
=> [C-4865] Make metadata links visible

mediorum/server/audio_analysis.go
analyze faster by only analyzing the first 90s of a song. tested with sebastian's test [data](https://docs.google.com/spreadsheets/d/1mGKArjvdqfbjOIerSRJk0K4pDAtMCNw47tmyQG6debs/edit?usp=sharing) and verified key and bpm analyses were still accurate.
=> only analyze first 90s of song

packages/discovery-provider/src/queries/search_es.py, packages/web/src/pages/search-page-v2/SortMethodFilterButton.tsx, packages/web/src/pages/search-page-v2/search-results/AlbumResults.tsx, packages/web/src/pages/search-page-v2/search-results/PlaylistResults.tsx, packages/web/src/pages/search-page-v2/search-results/ProfileResults.tsx, packages/web/src/pages/search-page-v2/search-results/TrackResults.tsx
- Adds popularity sort for users, based on followers and verification status
- Adds popularity sort for collections, based on likes/reposts and artist social score
- Updates track popularity time series based on created_at, not updated_at
- Consolidates and refactors sort-method-filter-button
Open question: should we include is_verified in the track/collection social score stat?
=> [C-4634] Add popularity sort to users and collections

packages/common/src/store/purchase-content/sagas.ts
- Fixes issue where tracks purchased as part of a hidden album purchase were appearing in library during the same session they were purchased
- Also adds album tracks to logic that stops in-progress preview playback on successful purchase. When restarted, the track will play in full
Purchased hidden album on mobile, tracks did not show in library. In progress preview also stopped correctly then played full track when restarted.
=> [C-4793, C-4791] Don't favorite hidden album tracks on purchase

packages/mobile/src/components/edit/PriceAndAudienceField/PremiumRadioField/PremiumRadioField.tsx, packages/mobile/src/components/edit/PriceAndAudienceField/PriceAndAudienceScreen.tsx, packages/mobile/src/hooks/useSetTrackAvailabilityFields.ts, packages/mobile/src/screens/form-screen/FormScreen.tsx
I wish I had a bit of better fix for this, but it requires a much larger refactor that I now understand.
* Fix bug where you can brick yourself with invalid price / audience state (pay-3187)
* Fix bad initial state val for preview
* Fix isUpload check (back to what it was)
* Fix stop navigation check from failing during upload
This change works by listening to GO_BACK actions from the navigator and re-setting the changes that the inner form made on the formik context.
1. Upload track
2. Visit Price & Audience section
3. Press Premium
4. Go back
5. See that Free For Everyone sticks (previously we would get payment setting set with `null`)
Same flow, but type a number value and …
=> [PAY-3187] Fix messed up back button form state for payment settings

packages/web/src/components/edit-collection/EditCollectionForm.tsx
Fixes edit collection form submission requiring two clicks. Ultimately issue had to do with not calling onSubmit when release confirmation drawer is not necessary. I checked edit track and now both operate the same way.
=> [C-4866] Fix edit collection form submit

packages/common/src/services/audius-api-client/ResponseAdapter.ts, packages/common/src/services/audius-api-client/types.ts
Fix collection release date formatting by ensuring all release_dates are in utc format. This should be fixed in our api layer, but this is a hotfix for now.
=> [C-4867] Fix collection release date timezone

packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx, packages/mobile/src/screens/search-screen-v2/SearchBarV2.tsx, packages/mobile/src/screens/search-screen-v2/SearchScreenV2.tsx, packages/mobile/src/screens/search-screen-v2/searchParams.ts, packages/mobile/src/screens/search-screen-v2/searchState.ts
Updates to add a search screen param to autofocus the input and update the search screen to respect the param and focus the input automatically.
Interesting/hacky configuration to make sure that it focuses the first time, but not when a filter drawer is closed or when navigating back from results.
=> [C-4840] Update search screen to auto focus the input

mediorum/server/audio_analysis.go, mediorum/server/legacy_audio_analysis.go
have observed that nodes do their audio analysis backfill work for 2 hours following a release, then they all stop working / picking up jobs. with the exception of prod cn2. not sure why because they certainly still have work to do - upon the next release, they start working again - so try re-querying for work (which essentially is rebuilding the queue) every 15 minutes.
=> requery for audio analysis jobs every 15 min

packages/discovery-provider/src/queries/search_es.py, packages/es-indexer/src/indexNames.ts, packages/es-indexer/src/listener.ts
Fixes issue where tracks with deleted premium stems were being included in the "premium" search filter.
The fix is two-fold:
- Ensure when premium-conditions set for stems, we actually have stems
- Update triggers to ensure tracks with deleted/added stems are re-indexed, so `has_stems` get's recalculated
@stereosteve not sure if we need to include a reindex change?
=> [C-4670] Fix track search with deleted premium stems

packages/web/src/components/edit/fields/visibility/VisibilityField.tsx, packages/web/src/pages/edit-page/EditTrackPage.tsx
- Don't show scheduled visibility option for playlists
- Show mood placeholder when mood is `''`
=> [PAY-3265, PAY-3241] Disallow scheduled playlists in upload/edit; Fix mood placeholder

packages/discovery-provider/plugins/pedalboard/apps/backfill-audio-analyses/src/backfill_discovery.ts, packages/discovery-provider/src/tasks/repair_audio_analyses.py
merge and run on every node after mediorum 100% done backfilling
this is faster than the repairer, which is more meant for fixing 1-off failures from new uploads
=> rerun discovery backfill plugin

packages/mobile/src/components/edit/PriceAndAudienceField/PriceAndAudienceScreen.tsx
Fixes issue where we incorrectly set the price-audience initial state to "hidden", which was a holdover from when this field also handled that. the result is that none of the public/premium radio options appear selected.
=> [C-3251] Fix initial state for hidden price-audience field

packages/mobile/src/components/edit/PriceAndAudienceField/PriceAndAudienceScreen.tsx, packages/mobile/src/screens/app-screen/useAppScreenOptions.tsx, packages/mobile/src/screens/form-screen/FormScreen.tsx, packages/mobile/src/screens/form-screen/useRevertOnCancel.ts
Adds feature to revert form values back to "initialValues" when the inner form was opened.
Potential big changes here are updating default back button to use pop, which is probably good because gesture-back is pop as well. This means i needed to update onSubmit back to "goBack" so we can distinguish between "cancel" and "submit".
Gated this feature behind "revertOnCancel" prop, but will roll this out to all inner forms soon.
=> Improve mobile inner-form revert

packages/mobile/src/components/edit/VisibilityField/VisibilityScreen.tsx
Fixes issue where previously scheduled tracks and collections did not properly set visibility radio items, because it incorrectly calculated visibilityType === 'scheduled' since we weren't checking for isPrivate
=> Fix previously scheduled edit flow

packages/web/src/components/tracks-table/TracksTable.tsx, packages/web/src/pages/collection-page/components/desktop/CollectionPage.tsx, packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
Fix duplicate purchase button in TracksTable row.
The `isPremiumEnabled` feature flag wasn't being passed into TracksTable on the SavedPage which caused us to think we needed to add the button. But the button already existed so we ended up with 2 buttons on Collection pages. The fix is to strictly use the `GatedConditionsPill` and pass the flag into TracksTable
Tested Library, Album, and Playlists pages
=> [QA-1473] Fix duplicate purchase button in TracksTable row

packages/discovery-provider/Dockerfile.dev
Fixes DN failing to build with:
```
[INFO] [stdout] error[E0282]: type annotations needed for `Box<_>`
```
See: https://github.com/rust-lang/rust/issues/127343#issuecomment-2218261296
Not a true fix. True fix is updating all the deps so that the problematic `time` package is updated
=> Pin Rust version to 1.79.0

packages/web/src/components/edit/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseFields.tsx
Default values are now pre-filled for the price fields
=> [PAY-3257] Default prices for premium albums/tracks

packages/discovery-provider/ddl/migrations/0084_add_release_date_to_trending_params.sql, packages/discovery-provider/integration_tests/challenges/test_trending_challenge.py, packages/discovery-provider/integration_tests/tasks/test_update_trending.py, packages/discovery-provider/integration_tests/utils.py, packages/discovery-provider/src/queries/generate_unpopulated_trending_tracks.py, packages/discovery-provider/src/queries/get_trending_playlists.py, packages/discovery-provider/src/queries/get_underground_trending.py, packages/discovery-provider/src/queries/response_name_constants.py, packages/discovery-provider/src/tasks/index_trending.py, packages/discovery-provider/src/trending_strategies/EJ57D_trending_tracks_strategy.py, packages/discovery-provider/src/trending_strategies/base_trending_strategy.py, packages/discovery-provider/src/trending_strategies/pnagD_trending_playlists_strategy.py, packages/discovery-provider/src/trending_strategies/pnagD_trending_tracks_strategy.py, packages/discovery-provider/src/trending_strategies/pnagD_underground_trending_tracks_strategy.py, packages/discovery-provider/src/trending_strategies/trending_strategy_factory.py, packages/discovery-provider/src/trending_strategies/trending_type_and_version.py
Review commit by commit pls!
The main change of this PR is very small, just some other dead code cleanup along the way.
`k` is defined as our coefficient of decay. Our algo is `finalScore = score ^ (1 - k / time_period)`
this can be seen as decaying the final score from score to 1 based on what %age of the time period (e.g. trending this week) we have covered.
in existing trending `k` is defined as `k = now - created_at`
I update the calculation here to be
```
k = new - max(created_at, release_date if release_date < now else created_at)
```
basically, if release date is in the future, use created_at, and if release date is in the past, use max(created_at, release_date)
here's the diff
_Please describe the tests that you ran to verify your changes. Provide repro instructions & any …
=> [PAY-3249] Implement pnagD trending strategy

packages/harmony/src/components/select/Select/Select.tsx, packages/harmony/src/components/select/SelectInput/SelectInput.tsx, packages/harmony/src/components/select/SelectInput/types.ts, packages/web/src/components/edit/fields/visibility/ScheduledReleaseDateField.tsx
Adds `disableReset` prop to the `Select` component that disables the "reset" mechanism. Used in the "Visibility" field for scheduled releases AM/PM.
Also odd to me that it's got a text input at all... Maybe we're using the wrong component here? This should be a simple select imo, not like "filter button"?
=> PAY-3233 Disable reset on select field for AM/PM

packages/mobile/src/screens/edit-track-screen/screens/RemixSettingsScreen.tsx, packages/web/src/components/edit/fields/RemixSettingsField/RemixSettingsMenuFields.tsx, packages/web/src/components/remix-settings-modal/RemixSettingsModal.tsx
=> [PAY-3261] Update remix settings copy

packages/web/src/components/track/GatedContentSection.tsx, packages/web/src/components/user-badges/UserBadges.module.css, packages/web/src/components/user-badges/UserBadges.tsx
Small updates to user badge and the gated content section user link to fix the spacing
=> [QA-1448] Fix user badge spacing

packages/mobile/src/app/App.tsx, packages/mobile/src/components/core/DateTimeInput.tsx, packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx, packages/mobile/src/screens/edit-track-screen/components/ConfirmPublishDrawer.tsx, packages/mobile/src/screens/edit-track-screen/components/EditPriceAndAudienceConfirmationDrawer.tsx, packages/mobile/src/screens/form-screen/FormScreen.tsx
[[](https://github.com/AudiusProject/audius-protocol/commit/bb80a0a327ed81a94aa89a3c550b4dc4d57accd8)[PAY-3248](https://linear.app/audius/issue/PAY-3248)[] Portal out edit confirmation drawers](https://github.com/AudiusProject/audius-protocol/commit/bb80a0a327ed81a94aa89a3c550b4dc4d57accd8)
* I figured portaling was simpler than rewriting the nav order. We've done this pattern before for DMs
[[](https://github.com/AudiusProject/audius-protocol/commit/73723c576a06c48148b03f30a1d216ed040e0edf)[PAY-3256](https://linear.app/audius/issue/PAY-3256)[] Dismiss keyboard when submitting form screen](https://github.com/AudiusProject/audius-protocol/commit/73723c576a06c48148b03f30a1d216ed040e0edf)
* Form screen often leaves the keyboard open, so just try to dismiss it when we submit forms in general …
=> [PAY-3248][PAY-3256][PAY-3234] Fix misc android issues

packages/common/src/utils/formatUtil.ts
=> [PAY-3260] Use 'Today' for matching release dates

core/Makefile
Just some minor quality of life improvements and optimizations for the core Makefile.
Ran all the commands successfully.
=> Makefile improvements to core

packages/common/src/audius-query/createApi.ts, packages/common/src/services/audius-api-client/ResponseAdapter.ts, packages/web/src/pages/edit-collection-page/desktop/EditCollectionPage.tsx, packages/web/src/pages/edit-page/EditTrackPage.tsx
Fixes issue where editing a new playlist didn't work because the force-fetch would fail. Updating the status codes of the "force" path, and adding a case where the fetch fails to set force to false.
In edit-page we use the apiCollection or the localCollection if something wrong happens. def a bit complicated, so maybe this fallback logic can get wrapped up in audius-query at some point.
@rickyrombo also fixes some issues with release-date, due to a bad release-date format in common, not sure how many things this fixes
=> [PAY-3262] Fix edit new playlist

packages/common/src/hooks/useCollectionMetadata.ts, packages/common/src/hooks/useTrackMetadata.ts
When a scheduled track/album is published, we flip `is_private` or `is_unlisted` but leave `is_scheduled_release` as-is. So we shouldn't hide the release date based on this field.
=> [PAY-3277] Show release date for all public tracks/collections

packages/web/src/components/edit/fields/DatePickerField.tsx
Fixes issue where after selecting a date, we would get a "select date" error message. This is because we call `setValue` and then `setTouched` back to back, and setTouched calls validate again, which clears out the releaseDate for some reason. Passing `false` as second argument skips validation after touch.
=> Fix "date required" error when selecting date

packages/discovery-provider/src/queries/get_repost_feed_for_user.py
Fixes an issue where repost feed for user is missing contextual info about tracks/users when called from the `/full` API.
Verified locally
=> [PAY-3194] Pipe through user_id param if specified for reposts endopint

packages/mobile/src/components/sign-out-confirmation-drawer/SignOutConfirmationDrawer.tsx
The buttons right next to each other with no gap has been bugging me for a while.
Before:
After:
=> Migrate sign out confirmation drawer to harmony

packages/mobile/src/components/lineup-tile/LineupTileStats.tsx, packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx, packages/mobile/src/screens/track-screen/TrackScreenDetailsTile.tsx
Use the common release date formatter which accounts for same day release dates
=> [PAY-3274] Show 'releases today' on mobile

packages/libs/src/sdk/services/StorageNodeSelector/StorageNodeSelector.test.ts, packages/libs/src/utils/getNStorageNodes.test.ts, packages/libs/src/utils/rendezvous.test.ts, packages/libs/src/utils/rendezvous.ts
typescript version of https://github.com/AudiusProject/audius-protocol/pull/8852
see also https://github.com/AudiusProject/audius-protocol/pull/8866
=> typescript impl of R2(crc32) + R2(sha256) ordering.

packages/web/public/actions.json, packages/web/src/components/edit-collection/EditCollectionForm.tsx, packages/web/src/components/edit/fields/visibility/VisibilityField.tsx
- Edit album (hidden, public)
- Edit playlist (hidden w/ tracks, hidden w/o tracks, public)
- Edit track (hidden, public, scheduled)
=> [PAY-3282] Prevent publishing 0 length playlist

.circleci/src/jobs/@integration-jobs.yml
We disabled this when we disabled our playwright tests, but imo it should be enabled to keep us from pushing api changes without updating the sdk. 
=> Re-enable SDK type verification

packages/mobile/src/components/edit/PriceAndAudienceField/PriceAndAudienceScreen.tsx
Don't love this fix - I think the whole screen should be a separate subform that only sets values to the main form on submit - but this seems to get the job done. Stale error data lingers in the subform otherwise.
Tested on iOS stage sim
=> PAY-3287 Validate main form on submitting access gate subform mobile

packages/web/src/components/edit-collection/CollectionNavigationPrompt.tsx, packages/web/src/components/edit-collection/EditCollectionForm.tsx, packages/web/src/components/edit-track/EditTrackForm.tsx, packages/web/src/pages/edit-page/EditTrackPage.tsx
- The navigation as part of the delete handler was triggering the `NavigationPrompt`s
- Fix is to check `DeleteConfirmationModal` open state on the nav prompt
nav prompt is showing except when deleting and submitting 👍
=> [PAY-3271] Prevent navigation prompt from showing on delete

packages/common/src/store/player/selectors.ts, packages/common/src/store/player/slice.ts, packages/web/src/common/store/player/sagas.ts, packages/web/src/common/store/queue/sagas.ts, packages/web/src/pages/track-page/TrackPageProvider.tsx
Fixes switching between play/preview for owner premium track
Fixes now-playing issue where track position doesnt reset when switching between preview and full track.
=> [QA-1374] Fix play/preview logic on track page

packages/web/src/components/edit-track/EditTrackForm.tsx
When you visit the edit track page directly from a track tile, we only set initial values to the 150x150 artwork that has loaded, but don't listen to the updates to give us the 1000x1000 artwork.
Open to other ideas!
- Edit track from feed
- Track shows low res images that turns into high res quickly and seems rather nice
also tested saving artwork, editing playlists and uploading new tracks
=> [PAY-3283] Show high res artwork in edit

packages/discovery-provider/ddl/migrations/0086_add_bpm_edit_flag.sql, packages/discovery-provider/integration_tests/tasks/entity_manager/test_utils.py, packages/discovery-provider/plugins/notifications/src/types/dn.ts, packages/discovery-provider/plugins/pedalboard/packages/storage/src/index.ts, packages/discovery-provider/src/api/v1/models/tracks.py, packages/discovery-provider/src/models/tracks/track.py, packages/discovery-provider/src/schemas/track_schema.json, packages/discovery-provider/src/tasks/metadata.py, packages/libs/src/api/Track.ts, packages/libs/src/sdk/api/generated/full/models/TrackFull.ts, packages/libs/src/sdk/api/tracks/types.ts, packages/libs/src/services/schemaValidator/schemas/trackSchema.json, packages/libs/src/utils/types.ts
Client can set this field to true if a user manually edits/inputs a track bpm. If `is_custom_bpm` is true, the client will display bpm decimal points.
=> add bpm edit flag col

packages/web/src/components/edit/fields/price-and-audience/PriceAndAudienceField.tsx, packages/web/src/components/edit/fields/stream-availability/SpecialAccessFields.tsx, packages/web/src/components/edit/fields/stream-availability/collectible-gated/CollectibleGatedFields.tsx, packages/web/src/components/edit/fields/stream-availability/usdc-purchase-gated/UsdcPurchaseFields.tsx
- Use the download gate keeper context to determine where the original setting came from to prevent this UI from showing if we didn't come from stem gated
- Fix preview default to 0
local staging web
=> Fix show premium downloads message

packages/common/src/hooks/useCollectionMetadata.ts, packages/common/src/hooks/useTrackMetadata.ts
Realized these are unneeded as null values are filtered out by default.
=> Remove null checks for metadata items in useXMetadata

packages/common/src/api/search.ts, packages/common/src/hooks/useTrackMetadata.ts, packages/common/src/models/Track.ts, packages/common/src/schemas/metadata.ts, packages/common/src/utils/bpm.ts, packages/mobile/src/screens/search-screen-v2/screens/FilterBpmScreen.tsx, packages/web/src/common/store/cache/tracks/sagas.ts, packages/web/src/components/edit/fields/AdvancedField.tsx, packages/web/src/hooks/useBpmMaskedInput.ts, packages/web/src/hooks/useRegexMaskedInput.ts, packages/web/src/pages/search-page-v2/BpmFilter.tsx
1. Add a +-0.5 BPM buffer to searches
2. Set and respect `is_custom_bpm` to show decimal places when the user has edited
3. Allow clearing of bpm and musical key. This depends on #9345 
4. Fix some more bpm input issues
* Use the same BPM_REGEX everywhere
* Add `useRegexMaskedInput` and `useBpmMaskedInput` to share input logic
⚠️ Maybe we should round the analysis values instead because that would get us 1 and 2 for free, and it avoids the case where someone is searching for and exact bpm like `140` but because of the buffer they get things like `139.5` and `140.4` in their results
Tested searching and editing on web and mobile
=> [C-4896] [C-4893] [C-4913] BPM precision adjustments

packages/mobile/src/components/collection-list/AddCollectionCard.tsx
FIxes issue where create-collection-card height was incorrect on larger screens. It should be dynamically computed.
=> [C-4915] Fix create collection card height

packages/common/src/api/search.ts, packages/common/src/audius-query/AudiusQueryContext.ts, packages/common/src/models/Analytics.ts, packages/mobile/src/app/AudiusQueryProvider.tsx, packages/mobile/src/screens/search-screen-v2/search-results/AllResults.tsx, packages/mobile/src/screens/search-screen-v2/search-results/PlaylistResults.tsx, packages/mobile/src/screens/search-screen-v2/search-results/ProfileResults.tsx, packages/mobile/src/screens/search-screen-v2/search-results/TrackResults.tsx, packages/web/src/app/AudiusQueryProvider.tsx, packages/web/src/common/store/cache/tracks/sagaHelpers.ts, packages/web/src/pages/search-page-v2/search-results/AlbumResults.tsx, packages/web/src/pages/search-page-v2/search-results/PlaylistResults.tsx, packages/web/src/pages/search-page-v2/search-results/ProfileResults.tsx, packages/web/src/pages/search-page/components/desktop/SearchPageContent.jsx
* Add analytics for web and mobile search v2
* Match existing search events
* Include all search parameters in search events
* Add events for editing bpm and key
=> [C-4681] [C-4680] Add analytics for search v2

dev-tools/setup.sh
CI jobs will hang and fail if [apt is waiting for interaction](https://app.circleci.com/pipelines/github/AudiusProject/audius-protocol/60844/workflows/4ea33469-3c8f-4a9a-9a01-2af078497f36/jobs/891525) to restart services.
CI
=> Prevent service restarts when installing apt packages

packages/web/src/utils/route.ts
* Needed to add the search routes to `staticRoutes` so the profile page doesn't match it as a user route when navigating back
=> [C-4921] Fix search v2 navigating back from profile

packages/web/src/pages/sign-up-page/pages/SelectArtistsPage.tsx
`artists` needed a null check. But why don't the types represent that? Going to figure that out next
=> [QA-1486] Fix sign up select artists screen

packages/commands/src/purchase-content.mjs
`purchase-content` breaks due to purchasing via libs and not sdk.
Favor `purchase-track` and `purchase-album` instead.
`purchase-track` succeeds on local stack
=> Remove audius-cmd purchase-content

packages/discovery-provider/integration_tests/tasks/test_get_feed_es.py, packages/discovery-provider/src/queries/get_feed_es.py
When you query feed right now, you have to specify limit as `offset + limit`. We don't handle that well on the client because limit is meant to start from `offset`, e.g.
```
offset = 0
limit = 9
offset = 9
limit = 9
...
etc
```
Update test to confirm correct limit behavior
=> [QA-875] Use size for es query to fix feed pagination bug

packages/web/src/app/web-player/WebPlayer.jsx, packages/web/src/components/artist-recommendations/ArtistRecommendationsPopup.tsx, packages/web/src/components/collectibles/components/CollectiblesPage.tsx, packages/web/src/components/header/desktop/HeaderGutter.tsx, packages/web/src/components/image-selection/ImageSelectionPopup.jsx, packages/web/src/components/menu/Menu.tsx, packages/web/src/components/track/ViewerActionButtons.tsx, packages/web/src/pages/MainContentContext.tsx, packages/web/src/pages/audio-transactions-page/AudioTransactionsPage.tsx, packages/web/src/pages/pay-and-earn-page/components/PurchasesTab.tsx, packages/web/src/pages/pay-and-earn-page/components/SalesTab.tsx, packages/web/src/pages/pay-and-earn-page/components/WithdrawalsTab.tsx, packages/web/src/pages/saved-page/components/desktop/SavedPage.tsx
If you are unauthenticated, you only get 1 page of trending right now on prod. This is because when the mainContentRef is set, it doesn't cause a rerender of the inner components, which is needed for the <InfiniteScroll> component to pick up in order for scroll-based pagination to work.
The fix here is to include a state var that just triggers the top level rerender when the ref is set.
Also fix a bug where the ViewerButtons are fetching id `-1` from the API. technically, this should  be handled more elegantly at a higher level component, but that may require rewriting parts of the ConnectedTrackTile itself.
```
```
Viewed when logging out and can paginate now
=> Fix short trending bug

.changeset/thin-crabs-brake.md, packages/discovery-provider/integration_tests/queries/test_get_usdc_purchases.py, packages/discovery-provider/src/api/v1/users.py, packages/discovery-provider/src/queries/get_usdc_purchases.py, packages/libs/src/sdk/api/generated/full/apis/UsersApi.ts
We will need to filter sales/purchases by a specific content ID to support the targeted DM creation flow.
* Added a query param for content ID to filter by
* Fixed a bug in the db query
Tested all four endpoints on local stack
`/sales`
`/sales/count`
`/purchases`
`/purchases/count`
=> [PAY-3331] Purchase/sale endpoint filtering by content id

packages/es-indexer/src/indexNames.ts, packages/es-indexer/src/indexers/PlaylistIndexer.ts, packages/es-indexer/src/indexers/TrackIndexer.ts, packages/es-indexer/src/listener.ts
Previous PR wasn't fully working
* Get `is_deactivated` from sql query in indexer
* Reindex tracks and playlists when the user updates
Confirmed tracks and playlists from deactivated users don't appear in search results
=> [C-4676] Fix es search returning deactivated content

packages/harmony/src/components/popup/Popup.tsx, packages/web/src/components/menu/Menu.tsx
Popup alignment is off because we don't take into account the x/y offset of the container when checking if we would overflow 
=> [QA-1446] Fix popup alignment

packages/discovery-provider/ddl/migrations/0087_fix_slugs_with_slash.sql
About 3k broken playlists on prod :/
This bug is no longer happening though because we parse out `/` in slugs
https://github.com/AudiusProject/audius-protocol/blob/6e17e518ba7e308d6c172936c375bbc2e73cc3c4/packages/discovery-provider/src/utils/helpers.py#L368
Tested by running this on a staging node and confirming playlist are unbroken
=> [QA-1459] Fix broken slugs

packages/web/src/components/comments/CommentSectionContext.tsx, packages/web/src/components/comments/CommentSectionDesktop.tsx, packages/web/src/components/comments/CommentThread.tsx
Adding some pagination buttons for @isaacsolo to test with
=> [C-4937] Adding some pagination buttons

packages/common/src/hooks/useTrackMetadata.ts
With custom bpms, we were always showing decimals even for something like 140.00. This makes it so we only show decimals when necessary, like 140.25 or 140.5
=> [C-4920] Only show bpm decimals if necessary

packages/harmony/src/components/button/FilterButton/FilterButton.tsx, packages/harmony/src/components/button/FilterButton/FilterButtonOption.tsx
Fix a few small issues with FilterButton:
* Make the top Paper the scroll container. Having the Popup be the scroll container causes the Paper to scroll inside the Popup, which isn't the behavior we want and results in this weird margin at the top:
* Close the popup on option select
* Don't highlight the selected option in the menu. This is for parity with prod and keeps the active state backgrounds from bleeding into each other
* Make options full width
=> [C-4936] FilterButton fixes

packages/mobile/src/screens/collection-screen/CollectionScreenDetailsTile.tsx
Forgot to include `hasStreamAccess` in this biz logic. Another point for sharing this logic.
locked:
unlocked:
mocks (compare far-left (locked) vs far-right (unlocked))
=> [PAY-3294] Hide save/repost for locked albums on mobile

packages/discovery-provider/src/tasks/index_payment_router.py
This was breaking purchases on local dev.
Error:
```
{"level": "ERROR", "msg": "Task index_payment_router[b6fcc1b2-8273-4ae9-906d-5406486bff1c] raised unexpected: AttributeError(\"'NoneType' object has no attribute 'get'\")\nTraceback (most recent call last):\n  File \"/usr/lib/python3.11/site-packages/celery/app/trace.py\", line 477, in trace_task\n    R = retval = fun(*args, **kwargs)\n                 ^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.11/site-packages/celery/app/trace.py\", line 760, in __protected_call__\n    return self.run(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/packages/discovery-provider/src/utils/prometheus_metric.py\", line 57, in wrapper\n    raise e\n  File \"/app/packages/discovery-provider/src/utils/prometheus_metric.py\", line 30, …
```
=> Payment router exception for when no geo_data found in memo

packages/discovery-provider/src/tasks/repair_audio_analyses.py
- track_id is randomized. better to order by created_at
- remove 404 clause; is not be relevant after backfill
- tx is running and idle for 10mins bc of the network reqs. fix by only opening a db session for the query, then each write
will test on stage
=> Small repairer clean up

packages/libs/src/sdk/services/Storage/types.ts, packages/libs/src/services/creatorNode/CreatorNode.ts
If mediorum fails to analyze a file, it returns `undefined` for this field. So a strict-equals on `null` will allow the following statements that attempt to use the `in` operator. This updates the type in the Storage API and fixes the type check.
=> [QA-1496] fix unsafe read of audio analysis field

packages/common/src/store/gated-content/sagas.ts
Removes listening for cache updates in the gated content unlock flow. This fixes an issue where every time the polling function runs, it issues a cache update, which triggers another poller to run (firing about 100 amplitude events when unlocking a single track).
The original change was made here: https://github.com/AudiusProject/audius-client/pull/2642/files#diff-c0963e4a508d816d128ccb03764a0ccd0b61a04092b2c672f89ee778dfb15130L336
I don't understand the original intent - as in - I'm not sure when an update would need to trigger polling for content access, but @sddioulde you may know?
Unlocked a follow-gated track on stage
Also completed a purchase and an nft unlock for sanity
=> [QA-1357] Remove excessive polling and amplitude events in unlock

.changeset/unlucky-chicken-listen.md, packages/libs/src/sdk/sdk.ts, packages/libs/src/sdk/services/Solana/programs/BaseSolanaProgramClient.ts, packages/libs/src/sdk/services/Solana/programs/ClaimableTokensClient/ClaimableTokensClient.ts, packages/libs/src/sdk/services/Solana/programs/ClaimableTokensClient/getDefaultConfig.ts, packages/libs/src/sdk/services/Solana/programs/CustomInstructionError.ts, packages/libs/src/sdk/services/Solana/programs/PaymentRouterClient/getDefaultConfig.ts, packages/libs/src/sdk/services/Solana/programs/RewardManagerClient/RewardManagerClient.ts, packages/libs/src/sdk/services/Solana/programs/RewardManagerClient/getDefaultConfig.ts, packages/libs/src/sdk/services/Solana/programs/types.ts, packages/spl/src/claimable-tokens/constants.ts, packages/spl/src/index.ts, packages/spl/src/reward-manager/constants.ts, packages/web/src/common/store/tipping/sagas.ts
- Adds logger to the Solana Program Clients in SDK
- Moves error messages to `@audius/spl`
- Adds error message and custom error wrapper for Claimable Tokens
Tested manually locally by trying to send a tip with no money
=> Add better error messages for Claimable Tokens Program

packages/harmony/src/components/modal/Modal.tsx, packages/harmony/src/components/popup/Popup.tsx, packages/harmony/src/hooks/useClickOutside.ts
This block was misbehaving because ignoreClick had a default value of `() => false` which caused the ternary to always follow the truthy branch even when ignoreClick wasn't provided by the caller.
```
if (
ignoreClick
? ignoreClick(e.target)
: !ref.current || (ref.current && ref.current.contains(e.target))
) {
return
}
```
Clicking outside closes the modal while clicking inside does not. Noted that clicking inside then dragging outside does not close the modal on mouseup, but clicking outside then dragging in will still close it on mouseup inside the modal. @sliptype for context. Was this a tradeoff of the change, or has my fix regressed it?
=> Fix useClickOutside

packages/common/src/hooks/useUSDCBalance.ts, packages/common/src/services/audius-backend/solana.ts, packages/libs/src/services/solana/SolanaWeb3Manager.ts, packages/libs/src/services/solana/tokenAccount.ts, packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx, packages/mobile/src/components/usdc-balance-row/USDCBalanceRow.tsx, packages/web/src/components/add-funds/AddFunds.tsx, packages/web/src/components/address-tile/AddressTile.tsx, packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFields.tsx
Consider the following scenario:
1. I go to check out with 0 $USDC balance
2. I click "Transfer via crypto"
3. I send 1 $USDC from my external wallet to my token account using `processed` commitment level (I can't control this, phantom, etc. would)
4. The client polls for balance using `processed` commitment on the FE RPC endpoint and sees that we have 1 $USDC now
5.  I click buy and my tx fails because the RPC that relays the tx doesn't know the balance yet
To fix, introduce a commitment level from the audius-fe perspective. This should dramatically dramatically reduce the probability of this happening. Yes this does come at the cost of your balance not showing up as fast, but that's also probably the right call versus failed tx.
_Please describe the tests that you ran to verify your …
=> [QA-1491] Fix balance polling bug

packages/discovery-provider/plugins/pedalboard/apps/relay/src/txRelay.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/utils.ts
Adds retry logic to some of relay's operations, not sure this will fix the specific issue with the fluctuating chain health but it'll help with chain restarts and connectivity errors.
`audius-cmd test`
=> relay retries

packages/discovery-provider/src/tasks/repair_audio_analyses.py
currently erroring with `DetachedInstanceError('Instance <Track at ...> is not bound to a Session; attribute refresh operation cannot proceed')` after the change to fix the tx idling as the code runs through all the necessary network reqs. Fix by including everything in a session but committing after every db operation, so no tx is open during the network requests.
tested on prod dn2
=> fix repairer eager loading

packages/discovery-provider/ddl/migrations/0088_add_musical_key_edit_flag.sql, packages/discovery-provider/integration_tests/tasks/entity_manager/test_utils.py, packages/discovery-provider/plugins/notifications/src/types/dn.ts, packages/discovery-provider/plugins/pedalboard/packages/storage/src/index.ts, packages/discovery-provider/src/api/v1/models/tracks.py, packages/discovery-provider/src/models/tracks/track.py, packages/discovery-provider/src/schemas/track_schema.json, packages/discovery-provider/src/tasks/metadata.py, packages/libs/src/api/Track.ts, packages/libs/src/sdk/api/generated/full/models/TrackFull.ts, packages/libs/src/sdk/api/tracks/types.ts, packages/libs/src/services/schemaValidator/schemas/trackSchema.json, packages/libs/src/utils/types.ts
so repairer doesn't overwrite if a user has manually unset the musical key
=> add is_custom_musical_key

packages/discovery-provider/src/tasks/repair_audio_analyses.py
so that the repairer does not overwrite any manual changes unsetting the musical key.
merge after https://github.com/AudiusProject/audius-protocol/pull/9416/files has deployed across the network.
=> check is_custom_musical_key before pulling in calculated key in repairer

packages/mobile/src/screens/app-screen/AppTabScreen.tsx, packages/mobile/src/screens/search-screen-v2/SearchScreenV2.tsx, packages/mobile/src/screens/search-screen-v2/index.ts, packages/mobile/src/screens/search-screen-v2/search-results/AllResults.tsx, packages/mobile/src/screens/search-screen-v2/searchState.ts
The component restructure in #9385 caused the search input on mobile to not accept any values. For some reason calling `setQuery` from `SearchBarV2` was not causing `query` to update in `SearchPageV2`, but I couldn't figure out why. Potentially something to do with `react-navigation` and how it mounts screens.
Anyway, going back to wrapping the search screen in a stack navigator fixes the issue
=> [QA-1501] Fix mobile search input

.circleci/src/workflows/core.yml, core/Makefile, core/chain/node.go, core/config/comet.go, core/config/config.go, core/config/genesis/stage.json, core/infra/Dockerfile, core/infra/dev_config/content-one.docker.env, core/infra/dev_config/content-one.env, core/infra/dev_config/content-three.docker.env, core/infra/dev_config/content-three.env, core/infra/dev_config/content-two.docker.env, core/infra/dev_config/content-two.env, core/infra/dev_config/discovery-one.docker.env, core/infra/dev_config/discovery-one.env
Allows stage nodes to run and peer correctly
Ran successfully on stage dns 2, 3, and 5
=> Testnet configuration for cometbft core

packages/common/src/models/Analytics.ts, packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx, packages/mobile/src/components/lineup-tile/LineupTileAccessStatus.tsx, packages/web/src/components/now-playing/NowPlaying.tsx, packages/web/src/components/play-bar/desktop/components/SocialActions.tsx, packages/web/src/components/track/GatedConditionsPill.tsx, packages/web/src/components/track/GatedContentSection.tsx, packages/web/src/components/track/ViewerActionButtons.tsx, packages/web/src/components/track/mobile/BottomButtons.tsx, packages/web/src/components/track/mobile/PlaylistTile.tsx, packages/web/src/components/track/mobile/TrackTile.tsx, packages/web/src/components/tracks-table/TracksTable.tsx
Adding amplitude metrics on all buy buttons. This will help determine if a button clicked redirects to sign up or the premium purchase modal. Which may inform certain features.
Ran on mobile, web, mobile web. Confirmed all buttons are logging metrics.
=> Add buy button metrics

packages/common/src/store/upload/selectors.ts, packages/libs/src/services/discoveryProvider/DiscoveryProvider.ts, packages/mobile/src/screens/edit-track-screen/EditTrackScreen.tsx, packages/mobile/src/screens/upload-screen/screens/CompleteTrackScreen.tsx, packages/mobile/src/screens/upload-screen/screens/UploadingTracksScreen.tsx
The `relay` method doesn't throw errors when the response comes back as unsuccessful. This causes a hang in the upload process on mobile in the cases where the user gets assigned a node that is "healthy" but doesn't have a good chain connection. This PR updates the `relay` method to throw for non 2xx results so that the sagas above it can catch the error and correctly show and error screen.
Note: I am intentionally _not_ updating the internal request method in `DiscoveryProvider` to follow this pattern because there are a number of cases where this actually breaks the application due to the `ResponseError` not being handled correctly above. I'd prefer to leave these as they are and fix the unhandled errors when migrating to SDK.
Tested locally on simulator and web against prod and staging …
=> [QA-1434] Fix hanging uploads due to errors on mobile

comms/discovery/db/queries/get_chat_messages.go, comms/discovery/db/queries/get_chats.go, comms/discovery/db/queries/get_new_blasts.go, comms/discovery/misc/chat_id.go, comms/discovery/misc/hashids_util.go, comms/discovery/rpcz/apply.go, comms/discovery/rpcz/chat.go, comms/discovery/rpcz/chat_blast.go, comms/discovery/rpcz/chat_blast_test.go, comms/discovery/schema/schema.go, comms/discovery/server/server.go, comms/discovery/server/server_test.go, packages/discovery-provider/ddl/migrations/0086_chat_blast.sql, packages/libs/src/sdk/api/chats/serverTypes.ts
Adds "chat blast" RPC.  And some function around turning blasts into 1:1 messages when a dm thread exists between sender and recipient.
Also includes PAY-3202
=> [PAY-3300] Chat blast: lazy create thread

packages/web/src/common/store/pages/audio-rewards/sagas.ts, packages/web/src/common/store/tipping/sagas.ts, packages/web/src/common/store/upload/sagas.test.ts, packages/web/src/common/store/upload/sagas.ts
Was resulting in silly looking errors in Sentry like `ClaimRewards: ResponseError: ResponseError`
=> Fix duplicate error name in sentry

.changeset/silver-buttons-turn.md, packages/common/src/services/audius-backend/solana.ts, packages/common/src/store/buy-usdc/sagas.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/package.json, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/assertRelayAllowedInstructions.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/routes/relay/relay.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/utils/verifySignatures.test.ts, packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/utils/verifySignatures.ts, packages/libs/package.json, packages/libs/src/sdk/services/Solana/programs/ClaimableTokensClient/ClaimableTokensClient.ts, packages/libs/src/sdk/services/Solana/programs/ClaimableTokensClient/types.ts, packages/libs/src/sdk/services/Solana/programs/PaymentRouterClient/PaymentRouterClient.ts, packages/libs/src/sdk/services/Solana/programs/PaymentRouterClient/types.ts, packages/libs/src/sdk/services/Solana/types.ts, packages/libs/src/sdk/utils/parseMintToken.ts, packages/libs/tsconfig.json, packages/web/src/services/solana/WithdrawUSDC.ts, packages/web/src/services/solana/solana.ts, packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
- Fix for withdrawal swaps getting ratelimited on relay (currently breaking all withdrawals pretty sure)
- Fix to only check instructions are allowed if signing the transaction
- Implement proper signature verification on relay
- Changes withdrawal swap transaction to use SDK (also pigeonholes it to USDC=>SOL but I think that's ok)
- Tempted to just rip this out entirely since it's dead code now?
- Creates new method that uses simpler transactions for withdrawals
- Updates Typescript for SDK to 5.4.5 from 5.0.4 (matches my VS Code plugin, fixes error with indexing arrays using an enum string)
Still testing
=> [PAY-3106][PAY-2914] Use SDK to withdraw USDC

packages/common/src/api/comments.ts, packages/libs/src/sdk/api/comments/CommentsAPI.ts, packages/web/src/components/comments/CommentBlock.tsx, packages/web/src/components/comments/CommentForm.tsx, packages/web/src/components/comments/CommentSectionContext.tsx, packages/web/src/components/comments/CommentSectionDesktop.tsx, packages/web/src/components/comments/CommentThread.tsx
Fixes a few bugs to comments that I found after testing changes from #9423
After this PR, all the e2e logic for comment CRUD should be working now with correct optimistic/non-optimistic UI changes (no error handling tho).
Main fixes - replies work again & populate correctly in the UI, deleted comments also now remove after confirmation.
Also I made the comment input form not clear until after the form is done sending your comment
web:dev + local stack
=> [C-4910] Comments replys & deletes fixes

packages/common/src/context/commentsContext.tsx, packages/web/src/components/comments/CommentHeader.tsx, packages/web/src/components/comments/CommentSectionDesktop.tsx, packages/web/src/components/comments/CommentSkeletons.tsx, packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Changes to the CommentHeader. 
Adds a popup menu that will be used to disable notifs. It shows on hover over the comment header but only for track owners (personally I think it could potentially be nice to have for non track owners, but this isnt currently in the spec and def lower priority for non track owners). 
Also moved skeleton UI to its own component
Also need to discuss with design about the "hover" state; seems like it would be easy to miss so maybe we just skip hovering?
web:stage
=> [C-4964] Comment header changes

.changeset/few-numbers-march.md, packages/libs/src/sdk/api/chats/ChatsApi.ts
Conditionally decrypt on `is_plaintext` field.
Will still need to add this logic as well as the `is_plaintext` field to `chat.last_message` sigh.
Messages are displayed on local stack.
=> Don't decrypt plaintext messages

core/config/defaults.go
these need the tcp protocol identified here
stage wasn't peering because the tcp was missing, overriding with .env fixed it so defaulting in here
=> wrong core defaults

.changeset/chatty-cameras-yawn.md, comms/discovery/rpcz/apply.go, comms/discovery/rpcz/websocket.go, comms/discovery/schema/schema.go, packages/common/src/store/pages/chat/sagas.ts, packages/libs/src/sdk/api/chats/ChatsApi.ts, packages/libs/src/sdk/api/chats/clientTypes.ts, packages/libs/src/sdk/api/chats/serverTypes.ts
Second attempt at https://github.com/AudiusProject/audius-protocol/pull/9438
* In sdk getAll function, always fetch pending blasts and upgrade them. Note this will also get called on further pagination calls to getAll. I think this is fine? Alternative is to upgrade manually on client. Feels better to encapsulate this functionality inside sdk.
* Always include currentUserId param in calls to getAll on our client. We need this to upgrade the blasts (as Chats API in sdk was designed to be stateless).
* Modify rpc metadata to include both `senderUserId` and `receiverUserId` to support stateless chats api.
* Modify websocket server to maintain a map of userId to list of websockets, instead of just a flatlist of websockets+userId structs.
* Add websocketPushAll function to comms server that …
=> [PAY-3307] Upgrade chat blasts to chats in sdk (V2)

packages/discovery-provider/requirements.txt
transient python deps again, `eth_typing` had an issue with exporting `ContractName`, is fixed in a future web3 version so upgraded.
https://github.com/ethereum/eth-typing/issues/63
`audius-compose test discovery-provider`
=> bump web3 version for ci

.circleci/scripts/auto-approve-release.sh
jq splits tokens by `-` character
```
$ jobname='auto-approve-foundation'
$ echo '{"items":[{"name":"auto-approve-founcation","status":"on_hold","id":"abc123"}]}' | jq -r '.items[] | select(.name=='"\"$jobname\""' and .status=="on_hold") | .id'
> abc123
```
=> Use quotes to escape job name for jq

comms/discovery/rpcz/websocket.go
Whoops! mutex is held by calling function. If the websocket push fails, we'd call `removeWebsocket` and hit the deadlock condition.
DMs working on local stack again
=> Fix chat deadlock

packages/common/src/adapters/challenge.ts, packages/common/src/hooks/useAudioRewards.ts, packages/common/src/models/AudioRewards.ts, packages/common/src/store/challenges/selectors/optimistic-challenges.ts, packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx, packages/web/src/pages/audio-rewards-page/ChallengeRewardsTile.tsx, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
#9432 Made an assumption that since a lot of the code reading `max_steps` assumed it was a valid number, `0` was a safe default. What was actually happening was that the type was wrong and we were casting around it in apiClient. `max_steps` should be Nullable, since not all challenge types use it. I updated the type, removed the default value of 0, and fixed all the places in the code that were using the bad assumption that it's always a number.
The symptom exhibited by this bug was that users with no claimable challenges would see a notification dot due to challenges with `max_steps=null` getting coerced to `0` and a check of `current_step_count === max_step_count`. 
Tested locally against staging with accounts that have claimable challenges and no claimable challenges.
=> Fix bad claimable challenge state due to nullable max_steps

.circleci/scripts/auto-approve-release.sh
as title
```
$ foo="random string"
$ json_content="$(cat <<EOF
{
"blocks": [
{
"type": "section",
"text": {
"type": "mrkdwn",
"text": "$foo"
}
}
]
}
EOF
)"
$ curl -X POST https://httpbin.org/post \
-H "Content-Type: application/json" \
--data "$json_content" | jq '.json.blocks[0].text.text'
> random string
```
=> Fix malformed json in auto-approve script

core/config/config.go, core/config/defaults.go
mediorum doesn't get pg string through env var, it's hardcoded into mediorum
=> default connection strings

.changeset/cold-bees-rest.md, comms/discovery/server/response_mapper.go, packages/libs/src/sdk/api/chats/ChatsApi.ts
Don't decrypt `chat.last_message` if `chat.last_message_is_plaintext` is true
Fix bug where we forgot to pass that field along in the response.
Note: Needs changes from https://github.com/AudiusProject/audius-protocol/pull/9466 for sdk-init to pass
Working against local stack - tested both websocket case (incoming blast during live session) and fetch case (login after blast was sent)
=> Don't decrypt plaintext chat.last_message

.changeset/funny-students-prove.md, packages/common/src/store/pages/chat/sagas.ts, packages/common/src/store/pages/chat/slice.ts, packages/common/src/utils/chatUtils.ts, packages/libs/src/sdk/api/chats/ChatsApi.ts, packages/libs/src/sdk/api/chats/clientTypes.ts, packages/web/src/pages/chat-page/components/ChatComposer.tsx
Plumb values from the ChatBlastModal all the way down to sdk
Working again local stack
=> Hook up client blast params to sdk

comms/Makefile, comms/discovery/db/queries/get_chat_messages.go, comms/discovery/db/queries/get_chats.go, comms/discovery/rpcz/chat_blast_test.go
* `/chats` endpoint includes outgoing blasts from current user ID.  ID is generated as `blast:userId:audience:contentType:contentId` so e.g. `blast:1:follower_audience`
* `/chats/blast:1:follower_audience` will return outgoing blasts from current user for a specific audience.
=> [PAY-3299] Chat blast sender endpoints

comms/discovery/rpcz/apply.go, comms/discovery/rpcz/chat_blast.go, comms/discovery/rpcz/chat_blast_test.go, comms/discovery/schema/schema.go, packages/libs/src/sdk/api/chats/ChatsApi.ts, packages/libs/src/sdk/api/chats/serverTypes.ts
If artist sends a chat blast, for users who have an existing thread with the artist, the backend will insert rows to chat_message table but won't fire websocket events.
This PR:
- Formulates `ChatMessageRPC`'s for each user who has an existing chat
- Fires them off via `websocketNotify`
- Adds `is_plaintext` field to `ChatMessageRPC` so the client knows not to decrypt them. 
https://github.com/user-attachments/assets/02008afd-a1d2-4014-8560-a89a49aa588f
=> [PAY-3358] Fire chat message RPCs on blast write

packages/harmony/src/components/button/FilterButton/FilterButton.tsx, packages/harmony/src/components/button/FilterButton/types.ts, packages/web/src/pages/search-page-v2/BpmFilter.tsx
Fix an issue where typing in an input in a search filter (BPM filter) closes the popup immediately.
This was because we were setting isOpen false in `handleChange` which is called for all value changes, including typing in the bpm input. Needed to update it to only close when a FilterButtonOption is selected. Also I moved the e.stopPropagation to the root of the popup so that accidental clicks in the popup container do not close the popup
Will cherry pick and deploy to prod and cherry pick to this weeks release branch also
Confirmed all search filters work as expected
=> [QA-1514] Fix search filter typing

.changeset/forty-bags-refuse.md, packages/harmony/src/hooks/useHotKeys.ts
Hotkeys aren't working whenever you click on this `main` area, so I included in this `allowGlobalHotkeyPress` method
Clicking around app web:stage
=> [QA-1511] Fix space & arrow hotkeys not working

comms/discovery/db/queries/get_chat_messages.go
Forgot to join on `chat_blast` in this one place.
=> [PAY-3201] Fix chat blast reactions

packages/common/src/services/remote-config/defaults.ts, packages/common/src/services/remote-config/types.ts, packages/web/src/pages/chat-page/components/ChatBlastCTA.tsx
Set a remote config variable for the tier requirement that restricts chat blasts feature.
Functionality documented in description of remote config var.
Confirmed enabled on local web stage, but disabled for non-tiered user on prod
=> Remote config for chat blast tier requirement

comms/discovery/db/queries/get_chats.go, comms/discovery/rpcz/chat.go, comms/discovery/rpcz/chat_blast_test.go, packages/discovery-provider/ddl/migrations/0092_chat_member_hidden.sql
Hides a thread unless there are valid chat messages or blasts from the other party.
=> [PAY-3309] Add is_hidden column to chat_member

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/store/notifications/types.ts, packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx, packages/web/src/components/notification/Notification/ChallengeRewardNotification.tsx
AUDIO match notification amounts would default to 1 before because the amount came from the generic user challenge not the actual notification amount.
On mobile, this notification appears to be completely missing as well as others because this challege info mapping lags behind common.  
Ran on web + mobile and confirmed notification is there w correct amount.
=> Fix challenge claim notification amount

comms/discovery/rpcz/websocket.go, comms/discovery/schema/schema.go
This was causing a bug on older clients where two reactions were being shown when a user reacted to a chat message.
Old version of websocket push included `UserID` as a metadata field, and this was getting used in the reaction state updates. We changed the metadata fields to `SenderUserID` and `ReceiverUserID` but we should keep the old one around for backwards compatibility at least for a while.
=> [QA-1517] Include UserID in websocket metadata

packages/discovery-provider/plugins/pedalboard/apps/relay/src/config/antiAbuseConfig.ts
Rule 13 is only used in relays not reward attestations. 
=> Remove rule 13 from blocking relay

packages/mobile/src/screens/chat-screen/ChatBlastCTA.tsx, packages/web/src/pages/chat-page/components/ChatBlastCTA.tsx
Accidentally removed the disabled state from web instead of mobile.
This change puts it back for web and removes it on mobile as intended.
=> Fix CTA empty states reversed web/mobile

packages/common/src/adapters/track.ts, packages/common/src/api/track.ts, packages/common/src/models/Track.ts, packages/common/src/services/audius-api-client/AudiusAPIClient.ts, packages/common/src/services/audius-api-client/ResponseAdapter.ts, packages/common/src/store/gated-content/sagas.ts, packages/common/src/store/purchase-content/sagas.ts, packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts, packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/staleTrackWorker.ts, packages/web/src/common/store/cache/tracks/sagas.ts, packages/web/src/common/store/cache/tracks/utils/retrieveTracks.ts, packages/web/src/common/store/upload/sagas.test.ts
Endpoints migrated:
* `getTrack`
* `getTracks` (`getBulkTracks`)
* `getTrackByHandleAndSlug` (syntactic sugar for `getBulkTracks` using a single item `permalink` array and taking the first returned result)
Also had to modify the type for `TrackMetadata` to correctly reflect the `Nullable` nature of `create_date`, We don't actually use this field and it's slated to be removed. However it _is_ required in upload/edit metadata (even though it's always `null`), and the SDK adapter was not setting it to `null` the way it does for other nullable fields. This was causing a validation error when attempting to edit a track that was fetched via SDK.
See PAY-3364 for details on the future removal of `create_date`
Used `compareSDKResponse` against responses from prod entities to verify we get back …
=> [PAY-2918] Migrate track endpoints to SDK, Round 2

packages/web/src/pages/chat-page/components/ChatBlastCTA.tsx
`tierNumber` was coming out to `0` which was failing the boolean check.
=> Update logic for allowing chat blast sending

.changeset/five-beers-end.md, packages/harmony/src/components/popup/Popup.tsx
Right now when you scroll after opening the suggested artists popup it does weird flickering and sometimes sticks to the bottom of the screen.
The reason is because we have logic to attempt to pivot around the origin to fit inside the window if possible (i.e. if above origin has not enough real estate, go bottom, etc). This logic seems like it's only meant to trigger when the popup is first opened; not on every rerender.
SIDE NOTE: The animations (opening mainly) on this popup are still pretty janky; this bug + the still janky animation is wondering if we should swap out to a library under the hood
**before**
**after**
web:stage
=> [QA-1210] Fix popup scrolling issues

packages/common/src/hooks/chats/useAudiusLinkResolver.ts, packages/mobile/src/components/core/UserGeneratedText.tsx, packages/mobile/src/harmony-native/components/input/TextInput/types.ts, packages/mobile/src/screens/chat-screen/ChatTextInput.tsx, packages/mobile/src/screens/chat-screen/ComposePreviewInfo.tsx, packages/web/src/pages/chat-page/components/ChatComposer.tsx
Implement composer changes for message on mobile, following same patterns from web
* Unfurl display text for tracks, collections, and users inline
* Tracks and collections unfurl above with some content
* Backspace deletes entire row
* Unfurl in the messages themselves
Staging on simulator, verified sharing of all content forms. Some potential concerns I want to test on app:
* How responsive entering text is. It seemed a little slower than just the input on mobile, versus web which is near instant
* Backspace behavior (see inline comment)
=> [PAY-3228] Implement composer unfurl in mobile

packages/discovery-provider/integration_tests/tasks/entity_manager/test_comment_entity_manager.py, packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
Avoid collisions when duplicate transactions are submitted. Still a lot more to do here but this should prevent some indexing problems.
Added new tests for comments and reactions.
=> Handle dupe comment transactions

.changeset/ninety-shoes-live.md, packages/harmony/src/components/layout/Flex/Flex.tsx, packages/harmony/src/components/layout/Flex/types.ts, packages/mobile/src/harmony-native/components/layout/Flex/Flex.tsx
Adds row and column props to flex, to make it even easier to create layouts. shoutout to @amendelsohn for the idea.
Additional changes coming to flex:
flex-direction = row by default for web and mobile
=> Add row and column props to flex

packages/web/src/pages/chat-page/components/ChatList.tsx, packages/web/src/pages/chat-page/components/ChatListBlastItem.tsx
Adding active styles for the blast list item
=> Active styles for web chat blasts

packages/common/package.json
`push-protocol-dashboard` job failing because of this error 
```
107.5 ******-protocol-dashboard:build: [vite]: Rollup failed to resolve import "react-router" from "/app/packages/common/src/utils/route.ts".
107.5 ******-protocol-dashboard:build: This is most likely unintended because it can break your application at runtime.
107.5 ******-protocol-dashboard:build: If you do want to externalize this module explicitly add it to
107.5 ******-protocol-dashboard:build: `build.rollupOptions.external`
107.5 ******-protocol-dashboard:build: error during build:
107.5 ******-protocol-dashboard:build: Error: [vite]: Rollup failed to resolve import "react-router" from "/app/packages
```
which i think matches the timing of this https://github.com/AudiusProject/audius-protocol/pull/9492/files
_Please …
=> Add react-router dependency

packages/web/src/components/nav/desktop/AccountDetails.tsx
Fixes long names pushing the manager mode button out of view
web:stage with a hardcoded long name
=> [QA-1499] Fix long usernames overflowing manager mode button

.changeset/eighty-cherries-admire.md, comms/discovery/db/queries/get_chat_messages.go, comms/discovery/db/queries/get_chats.go, comms/discovery/rpcz/chat_blast_test.go, comms/discovery/schema/schema.go, comms/discovery/server/response_mapper.go, comms/discovery/server/server.go, packages/common/src/store/pages/chat/sagas.ts, packages/common/src/utils/chatUtils.ts, packages/libs/src/sdk/api/chats/ChatsApi.ts, packages/libs/src/sdk/api/chats/clientTypes.ts
- Change `chatId` for blasts to not include "blast:<userId>", only `concat_ws(':', audience, audience_content_type, audience_content_id) as chat_id`
- `getChat` and `getMessages` working for chat blasts
- Responses for above include `audience_content_type` and `audience_content_id` only when they are not null
- Add `is_blast` to `getChat` response (use this instead of "blast" prefix)
Potentially annoying to have to include `is_blast` in the request but I think this is the better pattern? open to ideas.
comms tests pass
https://github.com/user-attachments/assets/7955de52-bd1e-4ad7-a74d-9ddbfd43bb99
=> [PAY-3359] Chat blast thread UI on sender side

packages/common/src/api/purchases.ts
Fixes small issue with buyer names missing if user is not already in cache. Adding a fetch for buyer metadata like we do for track.
Mocked random buyer user IDs and confirmed uncached users IDs were then fetched.
=> [QA-1519] Fix buyer metadata caching

.changeset/tricky-cooks-sell.md, packages/libs/src/sdk/api/challenges/ChallengesApi.ts
`submitDiscoveryAttestations` should match the return type of `submitAntiAbuseOracleAttestation` otherwise it gets filtered out and not actually confirmed. Probably not the main reason for claiming instability but maybe part of it.
Ran locally against prod and confirmed that this was able to confirm then claim properly.
=> Fix challenge api tx confirming

core/config/comet.go
We didn't load the pv at the startup so when we get the address later it had a nil ref. This was a problem before because later the node actually reads the pv for it's own use. Since we use this now for the console it exposed the nil.
On main run `audius-compose up core core-content-1 core-content-2 core-content-3 db`.
Docker stop one of your core nodes `docker stop core-content-1`.
Start the container again `docker start core-content-1`. 
It will enter a crash loop on the `.getAddress()` call in `comet.go`.
After this change you can restart the node as many times as you'd like and it will correctly gather the address.
=> fix core crashloop

packages/web/src/components/table/components/OverflowMenuButton.tsx
Tweak tracks table popup behavior to not dismiss on mouse leave.
This makes for a pretty poor UX; its very easy to accidentally close the popup.
web:stage
=> [QA-1515] Remove dismiss on leave from popup

packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx
Right now the text is pressable and interfering with the long press to show the emote wheel
local ios device
TODO: verify with an android; can do on staging
=> [QA-1498] Fix long press on DMs

.changeset/popular-wombats-serve.md, packages/harmony/package.json, packages/harmony/src/components/button/FilterButton/FilterButton.stories.tsx, packages/harmony/src/components/button/FilterButton/FilterButton.tsx, packages/harmony/src/components/button/FilterButton/FilterButtonOptionsList.tsx, packages/harmony/src/components/button/FilterButton/types.ts, packages/harmony/src/components/internal/Menu.tsx, packages/web/src/pages/search-page-v2/SearchFilters.tsx
- Adds virtualized filter button based on changes introduced in pay-with-anything feature branch. In the future the virtualized option should be incorporated in the internal/menu, so all menu-openers can benefit.
- Fixes issue where selecting an option does not close the menu. this was introduced by another fix to prevent onChange from triggering menu-close. Now we just ensure all option selects trigger onChange and setIsOpen.
Tested on pay-with-anytihng branch and through new "virtualized" storybook story
=> Add virtualized filter button, Fix option select

packages/common/src/models/AudioRewards.ts, packages/common/src/utils/challenges.ts, packages/discovery-provider/ddl/functions/handle_user_challenges.sql, packages/mobile/src/screens/notifications-screen/Notifications/ChallengeRewardNotification.tsx, packages/mobile/src/utils/challenges.tsx, packages/web/src/components/notification/Notification/ChallengeRewardNotification.tsx, packages/web/src/pages/audio-rewards-page/config.tsx
* Removes trending claimable_reward notifications since these rewards are an exception and not actionable for users, they are automatically disbursed.
* Add title and icon info to trending challenge reward notifs. This is probably a longstanding bug. 
Seems like there are places in the client that use a full trending challenge name `trending-track` instead of the id `tt` so left that part alone for now. It should be using the ID like the other abbreviated IDs `s` `b`.
Ran against stage. Confirmed a new trending user challenge does not trigger a claimable_reward notif. Confirmed web and mobile include titl
e and icon.
=> Fix trending reward notifs

packages/discovery-provider/src/tasks/index_payment_router.py
Something changed on the tx we send for purchases, it now includes `geo:null` as the memo data for the geo memo. We could try to not send the memo when performing purchases on local stack, or we could skip the geo step on local stack which is what this PR does. Either way is unclean so figured it doesn't make a difference.
Local purchase successfully indexed
=> [PAY-3380] Skip geo indexing on local dev stack

comms/discovery/db/queries/get_chats.go, comms/discovery/rpcz/chat_blast_test.go
Get chat endpoint works correctly for blast audience like: `customer_audience:track:1`
=> [PAY-3375] get chat endpoint correctly filters for audience:type:id

packages/discovery-provider/src/api/v1/tracks.py
Wasn't able to test this correctly and it bit me!
The keys in the `dict` that comes back from the db query are numbers. The type we were using for marshaling (Wildcard) only works with strings. So attempting to marshal was throwing an exception.
However, since this is a very simple object that doesn't require any transformation, we can get by with just specifying the response type for documentation sake (and generating SDK code) and then return the response without attempting to marshal it. It gets `jsonify`-d anyway, and the numbers will be converted to strings as part of that process. Prior to client SDK migration, this is what we were doing.
Spun up a local stack and got a user created with an NFT-connected wallet. Uploaded a NFT-gated track. Checked access to said track to make sure …
=> Remove marshalling for nft-gated-signatures

packages/discovery-provider/src/queries/get_purchasers.py
Calling `.all()` before calling `add_query_pagination` meant we were passing a list of results as the query arg to `add_query_pagination`. Calling `.limit()` failed because it wasn't being called on a query.
Also note that we're already calling `.all()` in this line below after adding pagination:
```
rows = add_query_pagination(query, limit, offset).all()
```
working on local stack
=> Fix purchasers endpoint

packages/discovery-provider/src/api/v1/tracks.py, packages/discovery-provider/src/queries/get_extended_purchase_gate.py
- The wrong parser was being used in the `access-info` endpoint
- The wrong type was being used for the argument
- The internal `_get_extended_purchase_gate()` method was mutating the passed in "gate" info splits, causing the amounts to be wrong for the `access-info` endpoint.
Tested that the endpoint returns as expected when run locally. Still need to test E2E, but need to deploy a "staking bridge" (probably just default to the local owner wallet) locally first
=> Fix include_network_cut parameter

packages/common/src/adapters/collection.ts, packages/common/src/adapters/track.ts, packages/common/src/api/collection.ts, packages/common/src/services/audius-api-client/AudiusAPIClient.ts, packages/common/src/store/gated-content/sagas.ts, packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadCollectionWorker.ts, packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/syncCollectionWorker.ts, packages/mobile/src/store/offline-downloads/sagas/requestDownloadCollectionSaga.ts, packages/mobile/src/store/offline-downloads/sagas/requestDownloadFavoritedCollectionSaga.ts, packages/web/src/common/store/cache/collections/fixInvalidTracksInPlaylist.ts, packages/web/src/common/store/cache/collections/utils/retrieveCollections.ts, packages/web/src/common/store/pages/trending-playlists/lineups/sagas.ts
Migrates the following endpoints previously implemented in `apiClient` to their SDK counterparts
* `getPlaylist`
* `getPlaylists`
* `getCollectionMetadata` (alias for the default/public version of `getPlaylist`)
* `getPlaylistByPermalink`
* `getTrendingPlaylists`
Note: Most of our `getPlaylist` calls use AudiusBackend, which calls a non-v1 endpoint. Those will be replaced separately when I start doing the endpoints implemented in the notorious `queries` file. They need a little bit of extra work.
Used `compareSDKResponse` to verify that updated versions were functionally equivalent. Extra bonus, this process revealed a minor difference between the way `release_date` is converted on collections that would have resulted in a regression!
=> [PAY-2919] Migrate playlists endpoints from apiClient -> sdk

packages/common/src/context/commentsContext.tsx, packages/mobile/src/app/App.tsx, packages/mobile/src/components/action-drawer/ActionDrawer.tsx, packages/mobile/src/components/action-drawer/ActionDrawerWithoutRedux.tsx, packages/mobile/src/components/action-drawer/index.ts, packages/mobile/src/components/comments/CommentBlock.tsx, packages/mobile/src/components/comments/CommentOverflowMenu.tsx
Add CommentOverflowMenu via ActionDrawerWithoutRedux. Open to input on this! Added a portal at the root and then conditionally render the action drawer when needed. This makes the actual implementation in CommentOverflowMenu very clean, and we have access to all of our context and hooks 🙌 
Tested new ActionDrawer and the redux ones
=> [C-4955] Comment action drawer

packages/web/src/pages/settings-page/components/desktop/ManagerMode/AccountsYouManageSettingsCard.tsx
There was an edge case with the new manager flow:
1. Click on a deeplink to open the 'Accounts You Manage' modal
2. Do whatever in the modal and then close it
3. Switch accounts
The page will refresh with the `/accounts-you-manage` suffix still on the URL, which will trigger showing the 'Accounts You Manage' modal for the managed account. This is usually not what we want.
Easy fix: when closing the modal, remove the suffix from the route.
=> [PAY-3152] Fix Accounts You Manage modal showing after switching accounts

packages/web/src/components/data-entry/TextAreaV2.module.css
Fix highlight on composer by putting text selection on top of composer ui and settings correct css elements. Should move to harmony long term, but keeping the code where it's all defined for now.
=> [PAY-3374] Fix selection colors for composer

packages/mobile/src/components/core/UserGeneratedText.tsx
This PR
https://github.com/AudiusProject/audius-protocol/pull/9533
introduced `allowPointerEventsToPassThrough` on the DMs UserGeneratedText component, which is missing (1) link props styles and (2) absolute positioning relative to the message itself
Also paired through this with @amendelsohn (big props) and tested user bios which are the other place we pass `allowPointerEventsToPassThrough`
=> [PAY-3397] Fix mobile layout with UserGeneratedText in DMs

packages/web/src/common/store/lineup/sagas.ts, packages/web/src/common/store/pages/feed/lineup/sagas.ts
Currently if a lineup comes back from the backend with duplicates (e.g. feed because of how pagination works), we don't tally that correctly.
I think this is something we could probably address within the feed implementation itself, but I also think this is sufficient for now.
Lineup needs a rewrite.
Ran locally and can now paginate feed well. Currently we way over fetch client side.
=> [QA-875][QA-850] Fix lineup pagination when dupes are present

packages/mobile/src/screens/chat-screen/ChatTextInput.tsx, packages/mobile/src/screens/chat-screen/ComposePreviewInfo.tsx
* New lines need to be double counted for to emulate behavior of textarea
* Text overflow on the DMs unfurl UI
Locally w/ staging
=> Fix mobile composer input newlines and unfurl overflow

packages/common/src/context/commentsContext.tsx, packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
Fixes issue where front-end code dropped setting entity_type default.
The fix includes
1. Re-adding default entity_type on client
2. Add default entity_type on indexing side, since we dont want sdk/api usage to cause stall if user doesn't set entity_type
=> Set default comment entity_type in indexing

packages/mobile/src/screens/track-screen/DownloadSection.tsx, packages/web/src/components/track/DownloadSection.tsx
Per discussion, we have decided to remove the download all button as its failure rate is ~50%.
=> [QA-1536] Remove download all buttons

packages/discovery-provider/src/api/v1/models/users.py, packages/discovery-provider/src/api/v1/users.py, packages/discovery-provider/src/queries/get_sales_aggregate.py, packages/libs/src/sdk/api/generated/default/apis/UsersApi.ts
Adds `/user/<id>/sales/aggregate` endpoint which returns the following for each piece of purchasable content owned by the user
```
{
content_id: string
content_type: 'track' | 'album'
purchase_count: number
}
```
=> [PAY-3372] Add sales aggregate endpoint

packages/discovery-provider/src/queries/get_genre_metrics.py
Makes this endpoint usable as a list of official genres on Audius
cURL against a local DN at (`/v1/metrics/genres`) with edits to the allowlist to make sure the filtering works correctly.
=> Filter genre metrics endpoint by allowlist

packages/discovery-provider/src/queries/get_followees_for_user.py, packages/discovery-provider/src/queries/get_followers_for_user.py
Bug was: if user follows many other users who are deactivated, there's a possibility that the first page of followees would be almost entirely deactivated, which get filtered out on client. This wouldn't be an issue except it also breaks pagination on the client because there's no way to know when the end of the list is reached.
Note that this could be a problem with other modals that use UserList. Maybe need a bigger discussion around how to handle deactivated users, perhaps those follow counts should be omitted from `aggregate_user` as well, and all queries should filter them out by default.
But this PR fixes the immediate problem.
Local stack - created many users who logged-in user follows, checked which ones were getting returned in the first page and set some of those to deactivated, …
=> [QA-1533] Filter out deactivated users from UserList queries

.changeset/brave-games-tan.md, packages/fixed-decimal/src/FixedDecimal.test.ts, packages/fixed-decimal/src/FixedDecimal.ts, packages/fixed-decimal/src/currencies.test.ts, packages/fixed-decimal/src/currencies.ts, packages/mobile/src/screens/track-screen/DownloadSection.tsx, packages/web/src/components/add-funds/AddFunds.tsx, packages/web/src/components/address-tile/AddressTile.tsx, packages/web/src/components/track/DownloadSection.tsx, packages/web/src/components/usdc-manual-transfer/USDCManualTransfer.tsx
Prior to this change, "-0.123" would be misrepresented as "-.123" when calling `toString()` and break in `toLocaleString()`
Also adds default formatting to `toLocaleString()` for USDC to give it 2 decimal points exactly and a '$' prepended, which should make life easier when using it.
NOTE: I changed the rounding behavior in a few places from `floor` to `trunc`, but all those usages are always positive so they should work the same anyway.
=> Support negative fractional numbers in FixedDecimal, default USDC formatting

packages/discovery-provider/ddl/migrations/0093_splits_in_purchases.sql
Fixes migration from #9586 failing on stage
Tested against stage DN4 using a rollbacked transaction.
=> Fix Splits Migration: Stage has users w/o indexed user banks

.changeset/thick-sloths-rest.md, packages/common/src/models/USDCTransactions.ts, packages/libs/src/sdk/utils/preparePaymentSplits.ts, packages/web/src/components/usdc-purchase-details-modal/components/ContentLink.tsx, packages/web/src/components/usdc-purchase-details-modal/components/DetailSection.tsx, packages/web/src/components/usdc-purchase-details-modal/components/PurchaseModalContent.tsx, packages/web/src/components/usdc-purchase-details-modal/components/SaleModalContent.tsx, packages/web/src/components/usdc-purchase-details-modal/components/TransactionSummary.tsx, packages/web/src/components/usdc-purchase-details-modal/components/styles.module.css
Adds the UI components for the Purchase/Sales transaction details modal. Note that the Network fee _always_ rounds up, and the subtotal _always_ rounds down for sales, and vice versa for purchases.
Also includes important change to ensure only users get the payExtra amount, which prior to this change would be split equally between the user and the network 🤯 
**SALES DETAILS:**
Note: The table says "Value: $2.06" but the total here is "$1.95". This feels a bit awkward to me.
**PURCHASE DETAILS:**
=> [PAY-3324] Purchase/Sales details w/ take rate

.circleci/config.yml, packages/common/src/utils/formatUtil.test.ts, packages/common/src/utils/wallet.test.ts
#9600 broke some common tests, but tests for common weren't running in CI. Also noticed `@audius/spl` isn't mapped, so added both `@audius/fixed-decimal` and `@audius/spl` mappings so that things that depend on them run their workflows in CI.
(Also fixes those common tests, obviously)
=> Fix broken common tests

packages/discovery-provider/src/queries/get_remixes_of.py
The logic in `get_remixes_of` evolved over a few different tickets/features to a point where we are accidentally excluding remixes for all gated types that are _not_ usdc purchases. The original intention of this line was to fix a bug around remixes for usdc purchases. So it now appears to be unnecessary.
However, we _do_ still hide remixes in the client. And that needs to be resolved separately.
Local stack
=> [QA-1537] Remove unnecessary short circuit logic for gated tracks in get_remixes_of

packages/web/src/components/table/Table.tsx, packages/web/src/pages/pay-and-earn-page/PayAndEarnPage.module.css, packages/web/src/pages/pay-and-earn-page/components/SalesTab.tsx, packages/web/src/pages/pay-and-earn-page/components/SalesTable.tsx
=> [PAY-3324] Add copy notice around network take rate

packages/web/src/components/link/ExternalTextLink.tsx
Fixes issue where ExternalTextLink wasn't aware of it's context because it was imported as src instead of from root, which meant the "TextContext" was different.
@rickyrombo if you integrate this fix to your pr, you should be able to simplify the link definition!
=> Fix web external-text-link style propagation

.changeset/warm-spies-shake.md, packages/fixed-decimal/src/FixedDecimal.test.ts, packages/fixed-decimal/src/FixedDecimal.ts
Allows for rounding mode to be "expand", which rounds away from zero. See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat#expand
Added tests
=> Add support for expand rounding mode to FixedDecimal

comms/discovery/rpcz/chat_blast.go
This field is unneeded, was used during dev but forgot to remove it.
Tested against local stack, chat blasts working fine.
=> Remove ToUserId in blast ws fan-out

comms/discovery/rpcz/apply.go
When selecting which users to send a chat websocket rpc to, respect the `chat_member.is_hidden` field and don't fire websocket events to those users for whom it is `true`.
In this example, reed sends a blast to 2 followers, andrew and steve. andrew has responded, so the chat appears on reed's end. steve has not. notice that after blasting, on reed's side, there is still only one chat with andrew. the chat with steve remains hidden from reed (currently, the steve chat would appear but then disappear on refresh).
https://github.com/user-attachments/assets/a7e0ff5b-9d68-49e8-a155-8bbef86cc853
=> [PAY-3387] Chat ws respects chat_member.is_hidden

.changeset/spotty-ads-share.md, packages/common/src/store/pages/chat/middleware.ts, packages/libs/src/sdk/api/chats/ChatsApi.ts
- Fix bug where API was tagging blasts as always sent from current user
- Only add blast messages to store if current user is the sender - don't want to trigger blast fetches for the recipients
Tested against local stack. Previously recipients were attempting to fetch blast threads and getting 404, triggering a "something went wrong" toast.
=> Only add blasts to store for sender

comms/discovery/db/queries/get_chat_messages.go
Need to update the list of blast audience types we support for `getMessages` endpoint.
Tested locally with tipper audience, confirmed fetch works on sender side
=> Blast getMessages supports all audiences

.changeset/rare-panthers-accept.md, packages/harmony/src/components/text/Text.tsx, packages/harmony/src/components/text/constants.ts, packages/harmony/src/components/text/types.ts, packages/harmony/src/foundations/typography/typography.ts, packages/mobile/src/harmony-native/components/Comments/CommentText/CommentText.tsx, packages/mobile/src/harmony-native/components/Text/Text.tsx, packages/mobile/src/screens/chat-screen/ChatMessageListItem.tsx, packages/web/src/components/comments/CommentBlock.tsx, packages/web/src/components/user-generated-text/UserGeneratedText.tsx, packages/web/src/pages/chat-page/components/ChatMessageListItem.module.css, packages/web/src/pages/chat-page/components/ChatMessageListItem.tsx
To improve multi-line text, design has updated lineHeights for text that should be multiple lines. This covers a few UserGeneratedText situations. For now I am just updating DMs and Comments features to use multi-line text.
Note that we now have 3 line-height options for body:
1. Legacy
2. Single-line
3. Multil-line
To prevent too many style changes, we have opted to keep legacy as the default, and introduce the other two options as add-ons. In the future we will likely default to single-line line-height as the default, with multiline as a configurable option.
=> [C-5008] Add single and multi lineHeight options to Text

comms/discovery/rpcz/chat_blast.go
Bug was that in the query (line 125 in same file) we were using `blast_id || chat_id` as the message_id, but then in the fan-outs we were using `chat_id + blast_id`. We should use the same ordering everywhere and respect the ordering in the db.
Confirmed bug repro on local dev without fix, confirmed fix eliminated bug.
=> [PAY-3389] Fix duplicate blast messages in 1:1 threads

packages/mobile/src/screens/edit-track-screen/screens/RemixSettingsScreen.tsx, packages/web/src/components/edit/fields/RemixSettingsField/RemixSettingsMenuFields.tsx
- Removes the restriction preventing a track from being marked as a remix if it is access gated.
- Removes rule which forces `hide remixes` toggle to true when track is access gated
_Note: We already have a guard against remixing a track you don't have access to._
tested against local dev
=> [QA-1439] Don't block gated tracks from being remixes

packages/discovery-provider/src/queries/download_csv.py
Purchases:
```
title,link,artist,date,paid to artist,network fee,pay extra,total
title D25B,/handle8F89/title-d25b,name 8F89,2024-09-04 01:51:44.079978,1.107,0.123,3.21,4.44
```
Note: I went with "paid to artist" instead of "sale price" so that the sum of the columns could equal the total
Sales:
```
title,link,purchased by,date,sale price,network fee,pay extra,total,country
title 8D6D,/seller/title-8d6d,name F588,2024-09-04 01:35:34.730161,1.01,-0.101,3.02,3.929,
```
Adds a fair amount of technical debt we'll need to cover for credit splits. I think our whole "splits" system needs another iteration.
=> [PAY-3412] Include network splits in CSV downloads of sales/purchases

packages/common/src/utils/linking.ts, packages/web/src/pages/pay-and-earn-page/components/SalesTab.tsx, packages/web/src/pages/pay-and-earn-page/components/SalesTable.tsx
- Updates the title of the "Value" column to be "Total"
- Updates the amount shown in "Value" to be the seller's amount (will need to revisit this during credit splits)
- Updates the link and adds the help.audius.co domain to the list of allowed "external" domains. (Also updates the link to not manually style the text after #9609 got merged)
=> [PAY-3410][PAY-3406] Update Sales Table help link and "Value" => "Total"

.changeset/good-planets-give.md, packages/libs/src/sdk/utils/preparePaymentSplits.ts
Accidentally was filtering _out_ users, rather than filtering users _in_!
Tested with network split off in audius-cmd
Will cherry-pick before release!!
=> Fix purchasing without network split

.changeset/hot-dolphins-complain.md, packages/fixed-decimal/src/FixedDecimal.test.ts, packages/fixed-decimal/src/FixedDecimal.ts
Prior to this change, was erroneously "rounding down" negative numbers even when there was no remainder to round.
Added a test.
=> [PAY-3404] Fix floor() for negative numbers that are already floored

packages/web/src/components/summary-table/SummaryTable.tsx, packages/web/src/components/usdc-purchase-details-modal/components/PurchaseModalContent.tsx, packages/web/src/components/usdc-purchase-details-modal/components/SaleModalContent.tsx, packages/web/src/components/usdc-purchase-details-modal/components/TransactionSummary.tsx
- Put the Transaction explorer link back
- Switch the order so that "Total" is last and "Pay Extra" comes after the network fee
- Remove special-cased text for downloadables
- Show 'Paid to Artist' instead of 'Subtotal' on the Purchase modal
=> [PAY-3408][PAY-3409][PAY-3408][PAY-3405][PAY-3413] Update Sales/Purchase Modal

mediorum/ddl/ddl.go, mediorum/server/audio_analysis.go, mediorum/server/repair.go, mediorum/server/transcode.go
Hash migration broke some assumptions around retry logic for transcode jobs... which was causing a lot of crud spam with failures.
We were planning to get rid of all this "implicit work queue" stuff and move transcode inline to upload request... which I think makes more sense now.
This is a temporary fix to only do retry logic to StoreAll nodes so as to cut down on the crud spam.
=> [QA-1512] Mediorum transcode fixes

packages/create-audius-app/examples/react/src/App.tsx
I updated this in a previous PR to match the changes to the Tracks API in SDK. However, that version hasn't been published yet, so this change needs to wait.
N/A
=> Revert change to create-audius-app until new SDK version is published

comms/discovery/db/queries/get_chat_messages.go
Previously all purchase/remix blasts were showing the same messages even if specific contents had been selected. Update the queries to take `audience_content_type` and `audience_content_id` into account.
Tested locally, confirmed 2 purchase blast threads with different contents were separate.
=> getChatMessages respects audience content type and id

comms/discovery/db/queries/get_chat_messages.go, comms/discovery/db/queries/get_chats.go, packages/common/src/store/pages/chat/sagas.ts, packages/common/src/store/pages/chat/slice.ts, packages/mobile/src/screens/create-chat-blast-screen/ChatBlastSelectAudienceScreen.tsx, packages/web/src/pages/chat-page/components/ChatBlastModal.tsx
We should handle `audience_content_id` as encoded hash ID for all endpoints.
Tested locally, confirmed fetching chats, chat messages, and sending messages + blasts works as expected.
=> [PAY-3370] Always use encoded content IDs in chats

packages/common/src/api/user.ts, packages/web/src/pages/chat-page/components/ChatListBlastItem.tsx
Need to encode the content id before requesting the purchasers count endpoint
=> Fix purchasers count in chat blast modal

packages/discovery-provider/plugins/pedalboard/apps/trending-challenge-rewards/src/app.ts
Seems like sometimes the userbank doesn't exist yet
https://explorer.solana.com/tx/5qjyLvnWr7aTW5c4TxnxoWaAPkKmFqvUDg8iYwtTBiX27QqR5UJ9w5bq8LZz5PNj2mThFu6H37UKMzv9MMC3yvyd#ix-1
=> Add createUserBankIfNeeded call to trending rewards bug

comms/discovery/rpcz/apply.go, comms/discovery/rpcz/chat.go
On chat reaction, call `chatUpdateLatestFields` which will now set `is_hidden` to false if a reaction in that thread exists that was not created by the sender.
Tested locally, confirmed reaction from recipient causes 1-1 thread to appear on sender side.
=> [PAY-3365] Chat reaction sets chat is_hidden to false

core/chain/abci.go, core/chain/register_node.go, core/registry_bridge/bridge.go, core/registry_bridge/register.go, core/registry_bridge/registry.go, core/run.go, core/sdk/sdk.go
- node registration sometimes fails on startup as it's faster than the node catch up, this makes it retry quicker and fail after an hour
- always persists app state, even on empty blocks which was being left out before
=> core: retry registration faster and always persist app state

.changeset/strong-emus-exist.md, packages/libs/src/sdk/api/chats/ChatsApi.ts, packages/web/src/pages/chat-page/components/ChatBlastModal.tsx
Set `audienceContentType='track'` if a chat blast is created with remixer audience.
Also set a default at the API layer.
Against local web stage:
Tested the API default by not passing it in from client - confirmed backend is correct
Tested the normal case of passing in from client
=> Set audienceContentType=track for remix chat blasts

packages/web/src/components/collection/CollectionCard.test.tsx, packages/web/src/components/collection/CollectionCard.tsx
Was too low res. Box is 180x180, plus we have to account for `@2x` displays
local stage
=> [QA-1545] Fix cover art size on album search results

comms/discovery/db/queries/get_chats.go
Enforce a server-side chat sort order where chats with `is_blast = true` are sorted before non-blast chats.
Tested query against stage, confirmed they line up with sort order of client.
=> [PAY-3395] Chat sort order prefers blasts

packages/mobile/src/screens/notifications-screen/Notification/NotificationProfilePictureList.tsx, packages/mobile/src/screens/profile-screen/ProfileHeader/TopSupporters.tsx
Problem:
- The mismatch between the number of users fetched by topSupporters and the expected limit in the ProfilePictureList props caused an out of range lookup in `users`
- `NotificationProfilePicture` throws because of the undefined `profile.user_id`
Fix:
- Use the common constant for the expected user list limit
Side-effect:
- The user list now shows 5 users instead of 6. We could update the constant to fix this, but it would affect web too.
mobile no longer crashing on this profile and displays top supporters correctly
=> [QA-1542] Fix mobile top supporters crashing profile page

packages/common/src/api/collection.ts, packages/common/src/api/track.ts, packages/common/src/api/user.ts
We're getting errors where `Id.parse` fails on id `-1` values. These values shouldn't make it into audius-query fetch in the first place, but adding guards since I wasn't able to track down the caller(s).
I have suspicion about https://github.com/AudiusProject/audius-protocol/blob/main/packages/web/src/components/track/helpers.ts#L16 but wasn't able to trace it to a `useGetTrackById` usage
this is a best effort change
=> [QA-1529] Add guard for -1 ids to audius-query api hooks

packages/discovery-provider/src/tasks/entity_manager/entities/user.py
Currently if a solana RPC node that a DN uses is behind the one that the client uses, we can end up in a situation where indexing payout wallets fails.
A prior version of this PR did some retry on the validation, but the truth is I don't think we should have this at all because:
1. If you try to pay a recipient that isn't a valid USDC token account, the purchase will fail (no $ is lost)
2. If we wanted to do some validation API side we could, but that feels kind of ick to me -- slower API request and also nothing you really can do in that situation except have clients be smarter.
So... just remove the validation. We do validation on audius.co anyway.
=> [QA-1513] Remove validation on payout wallet

packages/common/src/api/account.ts, packages/common/src/api/comments.ts, packages/common/src/audius-query/createApi.ts
`useRef` does not cause a rerender on value changed. This caused `useQuery` to not rerender after `fetchData` set the force flag back to false. `useQuery` manually sets the `LOADING` status as long as `force.current === 'forcing'` but we never got a rerender trigger after the fresh data came back if the value of the data didn't actually change.
Moved the force tracking to `useState` which triggers rerenders on value update. This resolved the issue.
Also cleaned up some endpoint options:
- 'query' is the default endpoint type
- `idArgKey` was being used incorrectly. It only applies to entities available in the legacy entity cache when the `kind` option is also provided
Accounts you manage settings modal no longer infinite loads. Also checked that it does properly fetch new data on every …
=> [QA-1528] Move audius-query force ref tracking to useState

packages/common/src/adapters/user.ts
#9651 updated the type returned from SDK to include `spl_usdc_payout_wallet`, typed as a string. This need an explicit cast in our user adapter to be compatible with the type for `UserMetadata`
N/A as it's just a type fix
=> fix type for spl_usdc_payout_wallet on user adapter

packages/common/src/store/purchase-content/sagas.ts, packages/common/src/store/storeContext.ts, packages/mobile/src/components/navigation-container/NavigationContainer.tsx, packages/mobile/src/components/payment-method/PaymentMethod.tsx, packages/mobile/src/components/payment-method/TokenPicker.tsx, packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx, packages/mobile/src/screens/app-screen/AppTabsScreen.tsx, packages/mobile/src/screens/wallet-connect/ConnectNewWalletButton.tsx, packages/mobile/src/screens/wallet-connect/WalletConnectModalScreen.tsx, packages/mobile/src/screens/wallet-connect/types.ts, packages/mobile/src/screens/wallet-connect/usePhantomConnect.ts, packages/mobile/src/store/storeContext.ts, packages/mobile/src/store/utils/phantomWalletConnect.ts, packages/mobile/src/store/wallet-connect/sagas/connectNewWalletSaga.ts, packages/mobile/src/store/wallet-connect/sagas/index.ts, packages/mobile/src/store/wallet-connect/slice.ts, packages/mobile/src/store/wallet-connect/types.ts
This really needs a refactor, but it does work! Hopefully we can do that next week :-)
Purchased track w/ $AUDIO via phantom on stage
=> [PAY-3386] Implement mobile pay with anything

packages/mobile/src/components/comments/CommentDrawer.tsx, packages/mobile/src/components/comments/CommentThread.tsx, packages/web/src/components/comments/CommentSectionDesktop.tsx, packages/web/src/components/comments/CommentThread.tsx
* Add mobile comments pagination. pretty straightforward after web was completed, thanks @DejayJD !
=> [C-4954] mobile comments pagination

packages/web/src/components/data-entry/ContextualMenu.module.css
Fixes issue where remix field was not editable because there was an absolutely postioned read-only element above the input field, because it's container wasn't position: relative
=> [QA-1711] Fix remix field not editable

packages/web/src/store/application/ui/buy-audio/sagas.ts
Wraps getting the quote in a check for existing balance.
Tested locally against stage, no error quote!
=> [QA-1587] Fix empty Jupiter quote on page load

packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/validator.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/utils.ts
Allows view notifs even if blocked on relay so the notification icon on client goes away should a blocked user see their updates.
=> QA-1624: allow all view notifs through relay

packages/discovery-provider/src/queries/get_underground_trending.py
Fixes QA-1558.
Exclude all trending tracks from underground trending, not just the top 10.
Tested on sandbox prod node.
=> Remove trending tracks from underground trending

packages/mobile/src/components/details-tile/DetailsTileNoAccess.tsx
On android there's some zIndex issue so the locked content drawer actually appears above the send tip drawer.
Notice that the locked content drawer is closed in the background after i closed the send tip drawer.
https://github.com/user-attachments/assets/3892cb28-895f-4387-867b-7617b24282b2
=> [QA-1563] Close locked content drawer on CTA click

packages/web/src/pages/pay-and-earn-page/components/WithdrawalsTab.tsx
- turns off react virtualized for withdrawal page which matches how the purchase history works
- 
=> QA-1378: fix withdrawal history extra grey space

packages/discovery-provider/src/queries/get_top_user_track_tags.py
Fixes QA-966.
Deleted tracks should not show up in a user's top tags. Example: https://audius.co/lovemeback.
Tested on sandbox. Confirmed deleted tracks did not show up in tags.
=> Remove deleted tracks from top tags

packages/mobile/src/components/core/UserDisplayName.tsx
Long names were overflowing on signup flow artist cards
=> [QA-808] Clip long artist names on mobile signup

packages/web/src/pages/sign-on-page/SignOnPage.tsx
If you go to https://staging.audius.co/signin it will still show sign in even if you're already signed in.
This selector is what we already use in mobile to do the same thing.
note: sign up routes are redirecting properly, its just sign in
=> [QA-1564] Redirect to feed if user is already authed

packages/web/src/components/follow-artist-card/FollowArtistCard.tsx, packages/web/src/components/follow-artist-card/selectArtistsPreviewContext.tsx
Users with no tracks are sometimes recommended on sign up. This disables a play button for them until a track is uploaded.
`npm run web:prod`
=> QA-1028: disable artist preview on signup for users with no tracks

packages/web/src/components/track/mobile/TrackTile.tsx, packages/web/src/components/track/trackTileMessages.ts
Fixes really poor track tile loading on mobile web. This is defintely a bit of a hack, but honestly happy with it given mobile web. Essentially this ensures `Text` component always has text in it, so the skeleton can properly overlay on top of it. The "loading" text will actually never show up.
=> [QA-1714] Fix mobile web track-page loading

.circleci/src/commands/@docker-commands.yml
CI deployment to stage is failing because the dashboard docker build has been removed
CI
=> Remove dashboard from crane docker image tagging ci

packages/web/src/pages/explore-page/collections.ts
Fix according to julian designs. We were incorrectly applying smaller perspective changes on cards that were not full width
=> [QA-291] Fix explore page perspective card sensitivity

packages/web/src/pages/feed-page/components/desktop/FeedPageContent.tsx, packages/web/src/pages/feed-page/components/mobile/FeedPageContent.tsx
Fixes issue where you can set your artist pick in feed, which is a pretty silly mechanic. likely user would only do this on their profile.
=> [QA-1483] Remove artist-pick in feed

packages/web/src/common/store/pages/collection/lineups/sagas.js
`release_date` is a string, not a number, so the `dateAdded` would be undefined. We attempt to call `.unix()` on the undefined timestamp, causing an error.
Introduced in https://github.com/AudiusProject/audius-protocol/pull/9529
=> [QA-1716] Fix removing songs from playlists

packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileSocials.tsx
* margin bottom and hardcoded height was resulting in big blank space on profiles without socials. Space doesn't seem to be needed at all
=> [QA-1553] Remove extra space below mobile profile socials

packages/discovery-provider/src/queries/search_es.py
Some track titles stylistically don't include spaces. Allow searching with spaces to include/boost these tracks if they're an exact match.   
https://audius.co/search/tracks?query=pure+component for https://audius.co/stereosteve/purecomponent-453169
https://audius.co/search/tracks?query=not+so+simple for https://audius.co/sebbsolitude/notsosimple
Tested on sandbox and ensured these surfaced properly.
=> [QA-1589] Improve track search for titles without spaces

packages/trpc-server/src/routers/track-router.ts
Should be ok because we want to show these in most cases. User who moves a track into an album would already have access to the album and would voluntarily be giving their album to others w/ the private link
=> [QA-1590] Remove private filter on album backlink

packages/web/src/components/page/Page.module.css, packages/web/src/components/page/Page.tsx
Make overscrolling on a page with a header not gross
Tested in Chrome, Firefox, and Safari
=> [QA-1340] Fix page header grossness

docs/docusaurus.config.js, docs/src/css/custom.css
Added announcement bar to docs linking to amplify hackathon registration page
=> [DOCS] - amplify hackathon announcement bar

packages/harmony/src/components/button/FilterButton/FilterButton.tsx, packages/harmony/src/components/button/FilterButton/types.ts, packages/harmony/src/components/internal/Menu.tsx, packages/harmony/src/components/select/Select/Select.tsx, packages/harmony/src/components/select/Select/types.ts
Fix a couple issues with Key & BPM filters on prod:
* Extra padding
* Popup closes when clicking in input 
https://github.com/user-attachments/assets/769d68a1-fa23-435a-af6f-0e43124cd0e0
These issues were fixed in #9484 but reintroduced in #9427 . The issue is with the `Menu` abstraction. `Menu` works great for the default case of menus rendering a list of options. But it causes problems for FilterButtons with a custom menu such as BPM and Key
Fix is to use composition to conditionally nest the menu content in the flex with the list properties applied. I still wanted to keep a single `menuOptions` prop in FilterButton and Select, so there is a bit of prop mangling. But this seemed to be the cleanest option
Tested default and custom FilterButtons on web
=> [C-5020] Search filter fixes for FilterButton

docs/docs/node-operator/migration-guide.mdx, docs/docs/node-operator/setup/advanced.mdx, docs/docs/node-operator/setup/installation.mdx
Updated documentation for Node Operators wanting to run `audius-ctl` on the same machine that hosts a Node.
Preview: https://sam.audius.co/node-operator/setup/advanced#controller-on-host
```mermaid
flowchart TD
subgraph VM 3
Z2{{Controller 3}}-->C(Discovery Node 3);
end
subgraph VM 2
Z3{{Controller 2}}-->B(Content Node 2);
end
subgraph VM 1
Z1{{Controller 1}}-->A(Content Node 1);
end
```
=> [DOCS] Running audius-ctl on same Node setup documentation

packages/discovery-provider/integration_tests/queries/test_get_comments.py, packages/discovery-provider/integration_tests/utils.py, packages/discovery-provider/src/api/v1/tracks.py, packages/discovery-provider/src/queries/get_comments.py
Ensures pinned comments are sorted to the top of the sort list.
Adds test
Note, his includes all the sort changes, which have yet to be reviewed in another pr
=> [C-4968] Sort pinned comments to top

packages/mobile/src/screens/search-screen/SearchBar.tsx
Removes auto-correct and auto-capitalize from mobile search input, which is the general standard for search. Just to be explicit:
- This prevents auto-capitalization of the first element
- This prevents auto-correct changing invalid words to common mis-spelled words
- This preserves auto-complete, which are the words that appear above the keyboard, which is typically present.
=> [C-5014] Remove search input auto-correct

packages/mobile/src/components/now-playing-drawer/NowPlayingDrawer.tsx, packages/mobile/src/components/now-playing-drawer/TrackInfo.tsx, packages/mobile/src/components/user-link/UserLink.tsx, packages/mobile/src/harmony-native/components/TextLink/InternalLink.tsx, packages/mobile/src/harmony-native/components/TextLink/TextLink.tsx, packages/mobile/src/harmony-native/components/TextLink/types.ts
Fixes a few issues:
- Improves TextLink animation and layout:
- Drops GestureResponder in favor of TouchableOpacity. This helps ensure the opacity animation and text-color animation are more in sync
- Adds endAdornment, which is a modification on "children" to ensure that endAdornment renders outside of Text (since elements in Text dont render well, while ensuring they also animate (opacity only). This is most helpful for user-badges in user-text-link
- Refactors NowPlayingDrawer's artist link to use the updated TextLink/UserLink
=> [C-1601] Fix verified badge, Improve text-link

packages/discovery-provider/integration_tests/queries/test_search_track_tags.py, packages/discovery-provider/integration_tests/utils.py, packages/discovery-provider/src/queries/search_es.py, packages/es-indexer/src/indexers/TrackIndexer.ts, packages/es-indexer/src/listener.ts, packages/es-indexer/src/setup.ts, packages/es-indexer/src/types/docs.ts
Adds comment_count to es-indexer, which fixes issue where feed and search track tiles have comments = 0.
Note we are not making comment_count an index because search doesn't need to rely on it. However if we want to incorporate comment_count into "popular" ranking for search, we can introduce it.
=> [C-5011] Add comment_count to es-indexer

packages/harmony/src/components/button/FilterButton/FilterButton.tsx, packages/harmony/src/components/internal/Menu.tsx, packages/harmony/src/components/select/Select/Select.tsx
#9427 broke harmony tests because aria attributes weren't being applied like previously
=> Fix harmony tests

packages/common/src/hooks/chats/useChatBlastAudienceContent.ts, packages/common/src/utils/chatUtils.ts, packages/common/src/utils/hashIds.ts, packages/mobile/src/screens/chat-screen/ChatBlastHeader.tsx, packages/mobile/src/screens/chat-screen/ChatBlastSubHeader.tsx, packages/mobile/src/screens/chat-screen/ChatScreen.tsx, packages/mobile/src/screens/chat-screen/ChatTextInput.tsx, packages/mobile/src/screens/chat-screen/UserChatHeader.tsx
Screen header for mobile chat blast screens (from sender's perspective).
- Split out a few different header components.
- `ChatBlastSubHeader` messes with the relative position of the composer, so need to an extra offset there.
- Make `decodeHashId` accept optional arg - did this recently for web-only `decodeHashId` (why are there two implementations of the same fn..)
Notes
- reactions disabled for user's own blast threads so thankfully don't need to mess with portal height offsets
Also tested android on device and confirmed things look good!
https://github.com/user-attachments/assets/e786836f-d82b-4b60-be22-24e13eda4400
=> [PAY-3209] Chat blast mobile header

packages/mobile/src/screens/chat-screen/ChatBlastAudienceDisplay.tsx, packages/mobile/src/screens/chat-screen/ChatScreen.tsx, packages/mobile/src/screens/notifications-screen/Notification/NotificationProfilePictureList.tsx
- Adds `ChatBlastAudienceDisplay` component displayed at top of blast chat history
- Fix count wrapping on `NotificaitonProfilePictureList`
=> [PAY-3211] Chat blast audience display (mobile)

packages/mobile/src/screens/chat-screen/ChatBlastFollowersCTA.tsx, packages/mobile/src/screens/user-list-screen/FollowersScreen.tsx, packages/mobile/src/screens/user-list-screen/TopSupportersScreen.tsx
- Adds CTA to end of user list modals if you are the owner and have chat blast permissions
- Clicking the CTA creates a new blast for that audience (if not exists) and navigates to the chat screen
=> [PAY-3215] ChatBlastCTA in own followers and supporters screens

mediorum/server/peer_health.go, mediorum/server/server.go, mediorum/server/transcode.go
StoreAll node will pick up transcode jobs for servers running old code.  We can undo this when all servers are > 0.6.190
=> Handle inline-transcode for older servers.

packages/discovery-provider/plugins/pedalboard/apps/verified-notifications/package.json
changesets attemps to publish all public packages by default. caused a non-fatal error here: https://github.com/AudiusProject/audius-protocol/actions/runs/10911031900/job/30283412848
=> Make verified-notifications a private package

packages/discovery-provider/ddl/functions/handle_comment.sql, packages/discovery-provider/integration_tests/queries/test_notifications/test_comment_notification.py
Prevents issue where an artist commenting on their own track would send them a comment notification.
Also removes `new.is_delete` condition as that is uncessary.
=> [C-5033] Prevent notification when artist comments

comms/discovery/rpcz/chat.go
Update unread count when upgrading blast to real chat thread. Only update the unread count for the recipient, not the sender of the blast.
Local stack
Receiver has unread count:
Sender has no unread count:
This user both received blasts and also sent a blast. After marking the 1-1 chat thread as read, the unread count was correctly cleared.
=> [PAY-3426] Set unread count when seeding chats with blasts

packages/web/src/pages/chat-page/components/ChatMessageList.tsx
We were erroneously showing this empty state for blast threads. Already handled correctly on mobile.
=> Don't show empty chat prompt for blasts

comms/discovery/rpcz/chat.go
Update query that sets `chat_member.is_hidden` to true if there exists a chat message or reaction that's a response to a blast, so that the blast sender now also sees the 1-1 chat thread.
local stack
=> Reactions also unset is_hidden for blast sender

packages/common/src/store/pages/chat/sagas.ts, packages/common/src/store/pages/chat/slice.ts
- Incoming reaction websocket event triggers fetching chat if the chat and message that was reacted to don't exist in local state.
- Fix bug where we were getting `entities is not defined` when checking that message exists in reaction slice.
https://github.com/user-attachments/assets/4057cc0d-435b-406e-9f38-faf9b37ee3b4
=> [PAY-3419] Fetch chat if necessary on chat reaction

packages/web/src/pages/chat-page/components/ChatBlastCTA.tsx, packages/web/src/pages/chat-page/components/ChatBlastModal.tsx
`cursor: pointer` on all the relevant buttons in chat blast create flow.
Tested locally against web stage (screenshots don't capture the cursor)
=> [PAY-3441] Cursor: pointer on chat blast modal

packages/common/src/utils/urlUtils.ts, packages/mobile/src/components/core/UserGeneratedText.tsx, packages/mobile/src/harmony-native/components/TextLink/ExternalLink.tsx, packages/mobile/src/harmony-native/components/TextLink/InternalLink.tsx, packages/mobile/src/harmony-native/components/TextLink/TextLink.tsx, packages/mobile/src/harmony-native/components/TextLink/types.ts
TextLink was not laying out properly inline with other Text components. This was a problem in UserGeneratedText
* Add TextLinkFlowing that directly uses Text components instead of wrapping with TouchableOpacity. This fixes the positioning problem
* Update link styling to remove the iOS system highlight and instead use the color animation. TextLinkFlowing does not have the opacity animation like TextLink although we could add it. TextLinkFlowing also does not support endAdornment
Perhaps another refactor to follow that renames TextLinkFlowing -> TextLink and makes it the default. And then adding TextLinkWithAdornment to support the endAdornment case. This all depends on where we land on whether or not our links should have both color AND opacity animation
Tested TextLink & TextLinkFlowing, …
=> [C-5045] Fix TextLink positioning and styling

packages/web/src/pages/chat-page/components/ChatBlastAudienceDisplay.tsx
- Center the audience display
- Limit it to 1080px width
_Note: recommend viewing diff with hide whitespace changes_
=> [PAY-3433] Center the chat blast audience display

packages/mobile/src/components/challenge-rewards-drawer/ChallengeRewardsDrawerProvider.tsx, packages/mobile/src/screens/audio-screen/ChallengeRewards.tsx, packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx
Addresses missed UI updates from #9801 partially due to masked typings via `modalType`
- Updates Mobile to allow the new challenge IDs to display
- Updates referrals modal to respect the fan/friends language
- Addresses same check from `profile-completion` challenge to show the progress bar
etc.
=> Add new shortened Challenge IDs to valid ID list on mobile

packages/common/src/store/purchase-content/sagas.ts
Adds network cut to pay with anything transactions
it hasn't yet
=> PAY-3428 Support network cut in pay-with-anything

comms/discovery/misc/blast_message_id.go, comms/discovery/rpcz/chat.go, comms/discovery/rpcz/chat_blast.go
Need to enforce consistent message IDs for messages that came from blasts.
Tested on local stack - confirmed `chat_message` created from blast upgrade vs blast fan-out have consistent message IDs.
=> [PAY-3462] Fix blast message ID ordering

packages/discovery-provider/ddl/functions/handle_comment_thread.sql, packages/discovery-provider/integration_tests/tasks/entity_manager/test_comment.py, packages/discovery-provider/integration_tests/utils.py, packages/discovery-provider/src/models/comments/comment_thread.py, packages/discovery-provider/src/tasks/entity_manager/entities/comment.py, packages/discovery-provider/src/tasks/entity_manager/utils.py
Fixes a few issues i noticed with comment_threads and issues with notifications
- We were not constructing pkeys correctly, it should be (parent_comment_id, comment_id)
- We were not adding comment_threads to the records to commit correctly, resulting in them being commited before the comment was committed, which resulted in no thread notifications to be constructed.
There is also another issue where we are doing a sql query inline the `create_comment` code, shouldn't we be prefetching them efficiently like we do with other entities?
Added a new indexing test to ensure this is working as expected
=> [C-5064] Fix comment_thread keys and notifications

comms/discovery/rpcz/chat_blast.go
We need to update the `unread_count` for _only_ the recipient during chat blast fan-out.
This is getting pretty ugly.. now we have 3 places where we attempt to update unread count. Open to suggestions.
Tested locally with 2 users against local stack - observed unread count getting updated correctly on chat blast sends.
=> [PAY-3459] Chat blast fan-out updates unread count

packages/discovery-provider/src/api/v1/search.py
I made a change to the search endpoint to use `inputs.boolean` for the parser because it's more flexible. But I neglected to remove the usage of `parse_bool_param`, which returns `None` if the input value is not a string.
Removing the custom parser in favor of the built in argument parsing fixes things.
Local client against local stack
=> [QA-1733] Fix boolean search filters on discovery

packages/common/src/store/pages/chat/slice.ts
Previously, sending a blast would cause the left chat list bar to re-sort, as the blast was fanned-out to the 1-1 chat threads, causing their `last_message_at` timestamp to be updated sequentially.
This PR only updates `last_message_at` when:
- the sender of the message is the current user
- it's a blast message (using `is_plaintext` as a proxy for whether the message came from a blast or not)
- the current chat is not the blast thread itself
https://github.com/user-attachments/assets/b0bd34c9-d08f-46e0-87df-24515aef8bdf
=> [PAY-3457] Fix chat blast triggering chatlist resort

packages/discovery-provider/integration_tests/queries/test_get_extended_purchase_gate.py, packages/discovery-provider/src/api/v1/playlists.py, packages/discovery-provider/src/api/v1/tracks.py, packages/discovery-provider/src/queries/get_extended_purchase_gate.py, packages/discovery-provider/src/tasks/index_payment_router.py
Makes including a network split non-optional.
`audius-cmd` purchased content and then tried to repurchase, says already purchased. Displayed network split in debug console logs
=> PAY-3326 Remove optionality from include_network_cut

packages/mobile/src/screens/create-chat-blast-screen/ChatBlastSelectAudienceScreen.tsx
the button (`bottomSection`) was scrolled off the bottom because the content was set to 100% of the screen height.
=> [PAY-3461] Fix missing submit button on select audience (mobile)

packages/discovery-provider/src/tasks/index_rewards_manager.py
Fixes rewards indexing when lookup tables are used by not checking for the reward manager account.
Also includes fix for finding the evaluate instruction by reversing the instruction list and finding the _last_ instruction for the reward manager program. (Previously only the evaluate instruction was present in this transaction)
=> Support lookup table in rewards indexing

packages/discovery-provider/integration_tests/tasks/entity_manager/test_comment.py
Fixes race-condition where adding a comment in the initial db round leads to race conditions. By moving the create_comment step to the indexer, we have a consistent number of notifications
=> Fix comment reply test

packages/discovery-provider/integration_tests/queries/test_get_comments.py, packages/discovery-provider/integration_tests/utils.py, packages/discovery-provider/src/queries/get_comments.py
On stage right now if you go to a track with "tombstone" comments (e.g. https://staging.audius.co/dejayjdstaging/a-little-gambling-copy-15-3) 
You'll notice that the data between the sorts are different. 
Reason is because the way I implemented "tombstone" comments was incorrect; I was filtering them out in python instead of SQL - this meant sometimes the page count was less than we expected and the pagination would just stop on the client side.
Fixed by incorporating the reply count check into the SQL query
Updated test too
web:dev & pytest
=> [C-5054] Fix tombstone comments + add tests

packages/web/src/components/search-users-modal/SearchUsersModal.tsx
- Don't overlay the CTA on the dms user list
scrolling works again, and scrolls the full user list. Loading indicator is visible north of the CTA instead of hidden behind it
=> [PAY-3445] Fix Chat Blast CTA footer positioning

.changeset/healthy-chefs-boil.md, packages/libs/src/sdk/api/challenges/ChallengesApi.ts
- Prior to this change, would get an error about the instructions length needing to be > 0
- Prior to this change, RPC sync race conditions would occur where during simulation "evaluate" would fail thinking the verified messages account wasn't created
=> Fix claiming rewards w/ all attestations

packages/harmony/src/components/text/Text.tsx, packages/mobile/src/components/comments/CommentText.tsx, packages/mobile/src/components/core/UserGeneratedText.tsx, packages/web/src/components/comments/CommentBlock.tsx, packages/web/src/components/comments/CommentText.tsx, packages/web/src/components/user-generated-text/UserGeneratedTextV2.tsx
* Add `UserGeneratedTextV2` which is a hand-rolled implementation of linkify because `linkify-react` is pretty limited and doesn't allow custom matchers like `react-native-autolink`. We can probably migrate exclusively to `UserGeneratedTextV2` on web but for now I kept it contained to CommentText
* Support link, user, and timestamp linking
=> [C-4996] Linkify web comments

packages/common/src/store/upload/reducer.ts
Since we use retries under the hood and they all share the same progress callback it's possible to receive a value that's _less_ than the previous upload progress value. While that's technically correct, it's not a great UX. So we're opting to let the upload progress sit for a bit if a retry occurs, until we catch up to the latest point and make it further.
Future upload resilience improvements can make this better.
Tested in local client against staging. Used network developer tools to simulate an offline environment part way through the upload and verified that it didn't jump backwards on the next retry.
=> [QA-1740] Prevent upload progress from jumping backwards on retries

packages/discovery-provider/plugins/pedalboard/apps/relay/src/config/rateLimitConfig.ts, packages/discovery-provider/plugins/pedalboard/apps/relay/src/middleware/rateLimiter.ts
We recently made viewing notifications allowed for anonymous accounts (in order to bypass the abuse checks) which had the side effect of making viewing notifications use the "app" rate limit, as we short circuit to "app" for anonymous-allowed writes.
Instead, remove the short circuit for anonymous writes, which will fall back to "app" if not signed and not allowlisted, and bump the rate limit for viewing notifications anyway. This makes sense as owner/allowlisted limits should be higher than "app" anyway, so the short circuit isn't necessary
=> Fix rate limiting of viewing notifications

.changeset/funny-nails-enjoy.md, packages/common/src/store/purchase-content/sagas.ts, packages/libs/src/sdk/api/albums/types.ts, packages/libs/src/sdk/api/tracks/types.ts
Error occurs due to extra parameter `wallet` being passed into the `getPurchaseAlbumInstructions` call - we no longer do the transfer in that call since shipping "pay with anything" so this failed zod parsing. Notably, the `purchase` variants would also include extra parameters, so made the "instructions" variants non-strict going forward.
=> Fixes zodError when purchasing album with Coinflow

packages/harmony/src/components/artwork/Artwork.tsx, packages/web/src/components/avatar/Avatar.tsx, packages/web/src/components/comments/CommentBlock.tsx
Fixes a few isuses:
1. Fixes issue where Artwork doesn't fire onLoad when image is cached, so we first check if "complete" is true (ie cached), and trigger setLoading(false)
2. Fixes issue where web/Avatar went to sign-up screen when userId={undefined}. really not sure what i was thinking there. Additionally drops another unecessary if condition.
3. Cleans up comment avatar to use standard size, and removes the tombstone hack since the above component is fixed
=> [C-5022] Fix cached-image artwork and avatar

packages/web/src/pages/chat-page/ChatPage.module.css, packages/web/src/pages/chat-page/components/ChatMessageList.tsx
Small updates to the styling and the function that scrolls the unread messages into view. I tried doing this with refs and ids to avoid just grabbing the parent id, but they were not working well so I just left it as is.
=> [PAY-3455] Update unread element scroll function and fix chat page styling again

packages/discovery-provider/src/api/v1/playlists.py
playlist_contents is missing tracks
```
{
"artwork": {
"150x150": "https://blockdaemon-audius-content-02.bdnodes.net/content/01J8KC8NCWZ1F036HKNYANKH2Q/150x150.jpg",
"480x480": "https://blockdaemon-audius-content-02.bdnodes.net/content/01J8KC8NCWZ1F036HKNYANKH2Q/480x480.jpg",
"1000x1000": "https://blockdaemon-audius-content-02.bdnodes.net/content/01J8KC8NCWZ1F036HKNYANKH2Q/1000x1000.jpg"
},
"description": "Songs to solve a ton of errors to. Happy hacking!",
"permalink": "[/mynameiscards/playlist/trick-cheneys-hackathon-trackathon-2024](https://discoveryprovider.audius.co/mynameiscards/playlist/trick-cheneys-hackathon-trackathon-2024)",
"id": "q7OlBmM",
"is_album": false,
"is_image_autogenerated": false,
"playlist_name": "TRICK CHENEY.'s Hackathon Trackathon 2024",
"playlist_contents": [], …
```
=> Fix get playlist API playlist contents

packages/libs/rollup.config.ts
CAA changes are breaking web build
```
cd packages/web
npm run build:stage
```
=> Unblock CI

packages/libs/rollup.config.ts
`eth-sig-util` has a nested prod dependency on `debug`. This doesn't play nicely with our Vite bundling for web due to `debug`'s usage of Node functionality. Moving debug explicitly to internals allows it to be bundled the "normal" way so that the node usage is resolved correctly.
Tested in local staging app and on a prod subdomain.
=> Move debug to externals

packages/discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts, packages/discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
Previous PR (https://github.com/AudiusProject/audius-protocol/pull/9880) had a bug - we actually want to do the inverse of the query in chat blast fan-out, and send notifications only for blasts where there's no existing chat between the two users.
Added a DN notif plugin test
=> Only send blast notifs when no existing chat

comms/discovery/rpcz/chat.go
Take `cleared_history_at` into account in `chatUpdateLatestFields` when deciding whether to set `chat_member.is_hidden` to false.
Only set `is_hidden` to false if there exist messages or reactions that were sent _after_ `cleared_history_at`.
Tested on local stack:
- artist deleting convo indeed hides convo, even after sending more blasts
- fan reacting/responding still unhides chat for artist
- fan reacting to older messages than artist's `cleared_history_at` - chat remains hidden for artist
- fan clearing history - only shows blasts after `cleared_history_at`
Note: I tested one case that still is a bit off:
_fan_ clears history, artist sends blast: chat is still hidden on fan side. Then artist sends another blast, now chat is unhidden for fan. Not entirely sure why this is, but i think …
=> [PAY-3463] Chat is_hidden respects cleared_history_at

.circleci/src/commands/@docker-commands.yml
This plugin was left out of CI
=> Tag mri plugin container in discprov release

packages/web/src/components/lineup/LineupProvider.tsx
On web sign in, feed doesn't infinitely scroll. This is because of a strange bug where the scrollParent seems to be outdated and not the actual element that's rendered. I was able to prove this out by logging out the element and noticing scrollParent would only link to the element on page after refresh. 
Instead of using the scrollParent that's passed down, I'm checking if it intends on using the mainContent element and fetching it from the DOM instead to ensure the reference is up to date. This is a weird workaround but not sure what else to do. 
Confirmed feed can infinitely scroll on login. Sign up and mobile don't seem to have this issue.
=> [QA-875] Fix short feed on web sign in

comms/discovery/rpcz/chat.go, packages/discovery-provider/ddl/functions/chat_allowed.sql, packages/discovery-provider/ddl/tests/chat_allowed_test.sql
* An existing chat is allowed even if a user further restricts their inbox settings after it's creation.
* fix tests: handle null `cleared_history_at`
=> Honor existing chat

comms/discovery/rpcz/chat_blast.go
Chat blast websockets were being selected from `targ` without calling `chat_allowed`, move the `chat_allowed` call further up the query.
Local stack, confirmed if follower blocks artist, artist blasts no longer reach that follower. But a different follower still receives the blasts.
=> [PAY-3488] Blast websockets respect permissions

packages/common/src/context/comments/commentsContext.tsx, packages/mobile/src/components/comments/CommentDrawer.tsx, packages/mobile/src/components/comments/CommentDrawerForm.tsx, packages/mobile/src/components/comments/CommentForm.tsx, packages/mobile/src/components/composer-input/ComposerInput.tsx
* When posting a new comment scroll to top. Theoretically we may want to scroll for replies too but it's less likely that someone has clicked reply on a comment and then scrolled further down the list
* Fix issue with reply/edit state persisting
* Fix issue with comment form not auto focusing
=> [C-5071] Scroll to top for new comments on mobile

packages/web/src/pages/collection-page/CollectionPageProvider.tsx, packages/web/src/pages/dashboard-page/components/TracksTableContainer.module.css, packages/web/src/pages/dashboard-page/components/TracksTableContainer.tsx
This reverts commit a88b39bf4f5ce2ce36de276ab697e79110c1868b.
https://github.com/AudiusProject/audius-protocol/pull/9209
We should show tombstones on collection pages
```
```
http://localhost:3002/prexse/album/distrance
=> Revert "[C-4493] Don't show deleted track rows in collections (#9209)"

packages/discovery-provider/plugins/notifications/src/__tests__/processPushNotification.test.ts, packages/discovery-provider/plugins/notifications/src/config.ts, packages/discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts, packages/discovery-provider/plugins/notifications/src/utils/populateDB.ts, packages/discovery-provider/plugins/notifications/src/utils/redisConnection.ts
Current blast notifications were causing on oom on staging after QA. We need to batch the blast notifications that go out. Create two cursors: on for blastId, and one for userId. We paginate through the userIds for a given blast, so that max `config.blastUserBatchSize` goes out per task run.
Added new tests, all passing.
Specifically there's one test that checks a race condition when new follower whose userId is in the middle of a batch
is added in between processing a blast. We want to favor skipping the userId instead of duplicate notifs, hence using a cursor on userId instead of just limit/offset pagination.
=> Batch chat blast notifications by blastId and userId

packages/mobile/src/components/lineup-tile/LineupTileStats.tsx, packages/mobile/src/screens/app-screen/AppTabScreen.tsx, packages/mobile/src/screens/track-screen/TrackScreen.tsx, packages/web/src/components/comments/CommentSectionDesktop.tsx, packages/web/src/components/comments/CommentSectionMobile.tsx, packages/web/src/components/track/desktop/ConnectedTrackTile.tsx, packages/web/src/components/track/mobile/ConnectedTrackTile.tsx, packages/web/src/components/track/mobile/TrackTile.tsx
* Hook up pressing on TrackTile comment stat to navigate to comments
On web I used a `showComments` query param to trigger scrolling/navigating to comments
=> [C-5094] Press comment stat to navigate to comments

pkg/core/config/config.go, pkg/core/core.go
- comet defaults these to 40 and we have more nodes than that so this bumps up the default and makes it configurable
=> update default inbound and outbound peer conns

packages/mobile/src/app/App.tsx, packages/mobile/src/components/comments/CommentDrawer.tsx
On android, the action and confirmation drawers were occasionally appearing behind the comments drawer. Moving the DrawerPortal outside of the BottomSheetModalProvider fixes this. I also confirmed that drawers using commentsContext are still able to be portaled properly
Also contains changes from https://github.com/AudiusProject/audius-protocol/pull/9990 so that should be merged first
Tested comment drawer, action drawers, and confirmation drawers on android and ios
=> [C-5119] Fix android comments drawer stacking

packages/common/src/api/user.ts
The migration to the new remixers endpoint broke the options in the form.
The root cause was we weren't decoding the hashIds after receiving the data. Trying to call `encodeHashId` on the hashId resulted in `''` which was submitted as the target trackId for the chatBlast audience.
wasn't working now it's working 👍
=> [PAY-3498] Fix remix track audience targeting

packages/common/src/context/comments/commentsContext.tsx, packages/mobile/src/components/comments/CommentActionBar.tsx, packages/mobile/src/components/comments/CommentBlock.tsx, packages/mobile/src/components/comments/CommentDrawer.tsx, packages/mobile/src/components/comments/CommentDrawerForm.tsx, packages/mobile/src/components/comments/CommentForm.tsx, packages/mobile/src/components/comments/CommentOverflowMenu.tsx
* Consolidate replying and editing state into a single state var
* Store `parentCommentId` in this state var, needs to be a separate piece of state from `replyingToComment`
* Update all usages and pass parentCommentId into CommentActionBar so it can be set into `replyingAndEditingState`
Confirmed replying to root comments and replies works as expected
=> [C-5107] Fix replying to a reply on mobile

packages/discovery-provider/plugins/notifications/src/config.ts, packages/discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
We were hitting this error after sending out a test blast with 13000 recipients on stage:
```
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
```
The stacktrace pointed to `buildUserNotificationSettings` which is inside `processNotifications`. Marcus realized that that call wasn't being awaited, which is likely the culprit of the max connection limit reached. So the fix is to await them, but process them in batches so they don't take super long.
Tests pass locally. Will have to test with large recipient count again on stage.
=> Batch chat notifs to fix max connection limit reached

packages/discovery-provider/ddl/functions/chat_allowed.sql, packages/discovery-provider/ddl/tests/chat_allowed_test.sql
A pre-existing chat will take precedence over inbox settings... but if recipient clears chat history inbox settings re-apply.
=> Clearing chat history forces permission re-check.

packages/discovery-provider/plugins/notifications/src/tasks/dmNotifications.ts
Once again getting this error after sending many blasts on stage:
```
const batches = chunk(notifications, config.notificationBatchSize)
for (const batch of batches) {
await Promise.all(
batch.map((notification) => {
notification.processNotification({
isLiveEmailEnabled: false,
isBrowserPushEnabled
})
})
)
}
```
I forgot to await the inner call to `processNotification`.
=> Fix chat blast notif batching async/await

packages/mobile/src/screens/track-screen/TrackScreenRemixes.tsx
This one was kinda hard to track down because it was so non-deterministic. But I noticed in the redux debugger that the remixes lineup was being fetched & reset multiple times in a row. This was because the useEffect had a dependency on the entire `track` object, as opposed to the TrackRemixesScreen which only has a dependency on `trackId`. I updated this and now the lineup is only fetched once and it displays consistently (and is much quicker to load)
I assume the issue was a race condition between the `reset` actions being dispatched and the lineup fetch completing when it was being spammed, causing the lineup to be empty in some cases
=> [C-5105] Fix issue with remixes lineup empty on track screen

.changeset/shiny-pugs-attend.md, comms/discovery/rpcz/apply.go, comms/discovery/rpcz/chat.go, comms/discovery/schema/schema.go, packages/common/src/hooks/chats/index.ts, packages/common/src/hooks/chats/useSetInboxPermissions.ts, packages/common/src/hooks/chats/useSetInboxPermissionsLegacy.ts, packages/common/src/models/Analytics.ts, packages/common/src/store/pages/chat/selectors.ts, packages/common/src/store/pages/chat/slice.ts, packages/common/src/store/pages/chat/types.ts, packages/common/src/utils/chatUtils.ts, packages/libs/src/sdk/api/chats/ChatsApi.ts, packages/libs/src/sdk/api/chats/clientTypes.ts, packages/libs/src/sdk/api/chats/serverTypes.ts, packages/mobile/src/screens/settings-screen/InboxSettingsFields.tsx, packages/mobile/src/screens/settings-screen/InboxSettingsScreenLegacy.tsx, packages/mobile/src/screens/settings-screen/InboxSettingsScreenNew.tsx, packages/web/src/components/inbox-settings-modal/InboxSettingsModalLegacy.tsx, packages/web/src/components/inbox-settings-modal/InboxSettingsModalNew.tsx
- Update write endpoint for permissions updates to accept a list.
- New version of inbox settings hook - don't need to use local state anymore as we use formik.
- Add a status in the chats slice for permissions fetching
- UI updates
Could not sign in on mobile against local stack for some reason. Going to test once backend changes land on stage. Mobile will likely be broken right now as we need to move the formik wrapper further down the screen (but that doesn't work with FormScreen i think..)
Web functionality working! Tested against local stack
https://github.com/user-attachments/assets/f623dfbb-7a08-4414-8dcf-a9ddd9cf72e7
=> [PAY-3203] Chat permissions write updates for multi-select

packages/web/src/pages/chat-page/components/ChatBlastHeader.tsx, packages/web/src/pages/chat-page/components/ChatListBlastItem.tsx
- Fixes truncation of remixed/purchased content titles on `ChatListBlastItem` and `ChatListHeader`
=> [PAY-3499, PAY-3500] Fix truncation on blasts with content audience

packages/web/src/pages/track-page/components/TrackRemixes.tsx, packages/web/src/pages/track-page/components/desktop/TrackPage.tsx, packages/web/src/pages/track-page/components/mobile/TrackPage.tsx
Improves various comments-enabled/disabled states for remixes/remixable/track for web and mobile-web
=> [C-4958] Improve web comment disabled state

packages/discovery-provider/src/queries/get_comments.py
Small error in passing the default limit as the max limit which made limits incorrect.
Confirmed on stage
=> [C-5080] Fix comment pagination limit

packages/discovery-provider/src/queries/get_health.py
`discovery_provider_healthy` reports true in the case of chain_health being null which shouldn't happen, this messes with sdk selection
=> add check for no chain status at all in discprov

packages/common/src/messages/comments.ts, packages/mobile/src/components/comments/CommentDrawerHeader.tsx, packages/web/src/components/comments/CommentHeader.tsx, packages/web/src/components/comments/CommentSectionDesktop.tsx
=> Add New Comments button

packages/discovery-provider/src/tasks/entity_manager/entity_manager.py
```
prev_records[entity_type_table_mapping[record_type]].append(\n                 ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^\nKeyError: <EntityType.COMMENT_MENTION: 'CommentMention'>"
```
Stage indexing stall came up in QA. This part of indexing is outside of the skippable scope. The error is simply because this comment mentions table isn't in the entity type -> table mapping. 
Ran comment mentions locally and confirmed indexing is working.
=> Fix comment mention entity type to table mapping

packages/mobile/src/screens/chat-screen/ChatBlastCTA.tsx, packages/mobile/src/screens/chat-screen/ChatScreen.tsx, packages/mobile/src/screens/chat-screen/hooks/useKeyboardAvoidingPlaybarStyle.ts
- Move `getKeyboardAvoidingPlaybarStyle` to new custom hook
- Use KeyboardAwareView with the new hook to float at correct height above keyboard
=> [PAY-3481, PAY-3512] ChatBlastCTA float above mobile keyboard

.changeset/moody-squids-thank.md, packages/create-audius-app/examples/react-hono/src/index.tsx, packages/harmony/src/components/text/Text.tsx
- Fixes small bug where Harmony `Text` component overrides the theme font.
- Fixes small bug where the CreateAudiusApp was setting the secret to the API key by default
=> Fix Text component font and CAA API key

packages/mobile/src/components/composer-input/ComposerInput.tsx
Add a maxheight to the mobile ComposerInput to prevent it from overflowing the screen and soft locking the user
=> [C-5164] Add max height to mobile ComposerInput

packages/mobile/src/components/comments/CommentOverflowMenu.tsx, packages/mobile/src/harmony-native/components/Button/Button/Button.tsx, packages/mobile/src/harmony-native/components/Button/EntityActionButton/EntityActionButton.tsx, packages/mobile/src/harmony-native/components/Button/FilterButton/FilterButton.tsx, packages/mobile/src/harmony-native/components/Button/PlainButton/PlainButton.tsx, packages/mobile/src/harmony-native/icons.ts, svgr-template.js
Enables animated mobile icons, drastically improving filter-button and button icons. We can make further improvements to other pressable icons too. 
The impetus for this fix is to make the "show comments" plain button much smoother in the comments section.
This fix employs some somewhat subtle changes to the svgr-template.js. First thing it does is allow "animatedProps" passthrough for mobile, which is needed for animated icons: https://docs.swmansion.com/react-native-reanimated/docs/core/useAnimatedProps. Next, AnimatedPath is created and used only when "animatedProps" is provided. Finally, we do some subtle react-native-svg import rename: {Path as RNSVGPath), and define `Path = AnimatedPath | RNSVGPath` as needed. Note the underyling jsx looks something like this, which makes it work: …
=> [C-5040] Enable animated mobile icons

packages/mobile/src/screens/profile-screen/ProfileInfo.tsx
=> [QA-1761] Fix mobile profile page username spacing

comms/discovery/db/queries/get_chats.go
Bug symptom was loading spinner was always visible on android on ChatListScreen.
Discovered that the `doFetchLatestChats` saga was [infinite looping here](https://github.com/AudiusProject/audius-protocol/blob/4d092651b9349de875f7f5a545ab5c839291e3c4/packages/common/src/store/pages/chat/sagas.ts#L137)
The response always included the blasts regardless of the before/after cursors. Fix is to make sure the blasts part of the `getAll` query respects those cursors.
Have not tested locally, will try to do that or test on stage
=> [PAY-3458] ChatsApi.getAll blast query respects timestamp cursors

packages/web/src/store/application/ui/withdraw-usdc/sagas.ts
The Coinflow modal wasn't being rendered because the amount was unset.
Tested locally against prod.
=> Fix withdrawals not showing coinflow modal

packages/discovery-provider/src/queries/get_comments.py
Currently, there are cases of dupe comments because there's no definitive deterministic order. For example, if one user leaves a bunch of comments with no reactions, the default top sort will have no reaction count to go off of. Then, the limit and offset become non-deterministic. 
This change simply adds two tie-breakers: karma + comment creation date. Also moved the is_delete to a filter to prevent surfacing of deleted coments. 
Ran on stage and confirmed duped comments were not re-produceable.
=> [C-5144] Fix dupe comments by ensuring deterministic order

packages/mobile/src/screens/feature-flag-override-screen/FeatureFlagOverrideScreen.tsx, packages/web/src/components/feature-flag-override-modal/FeatureFlagOverrideModal.tsx, packages/web/src/components/lineup/Lineup.tsx, packages/web/src/components/lineup/LineupProvider.tsx, packages/web/src/components/lineup/types.ts, packages/web/src/components/track/mobile/BottomButtons.tsx, packages/web/src/components/track/mobile/ConnectedTrackTile.tsx, packages/web/src/components/track/mobile/TrackTile.module.css, packages/web/src/components/track/mobile/TrackTile.tsx, packages/web/src/pages/ai-attributed-tracks-page/components/desktop/AiPage.tsx, packages/web/src/pages/ai-attributed-tracks-page/components/mobile/AiPage.tsx, packages/web/src/pages/deleted-page/components/desktop/DeletedPage.tsx, packages/web/src/pages/deleted-page/components/mobile/DeletedPage.tsx, packages/web/src/pages/remixes-page/components/desktop/RemixesPage.tsx, packages/web/src/pages/remixes-page/components/mobile/RemixesPage.tsx, packages/web/src/pages/search-page-v2/search-results/TrackResults.tsx, packages/web/src/pages/track-page/components/TrackRemixes.tsx, packages/web/src/pages/track-page/components/desktop/TrackPage.tsx, packages/web/src/pages/track-page/components/useTrackPageSize.ts
Improves desktop track page sizing by condensing comments + remixes + more-by-artist to one column when appropriate. The magic variable im using is the size at which the giant-track-tile starts to shift. In the future we should improve all of this.
Updates LineupVariant types, by renaming section to grid, and using section for the comments use case. Annoyingly this requires adding a popover menu dropdown in the mobile track tile, since it can be rendered in a desktop context, ie when LineupVariant.SECTION is provided
=> [C-5161 C-5151] Improve desktop track page responsiveness

comms/discovery/rpcz/chat_blast_test.go, comms/discovery/rpcz/chat_permissions_test.go, comms/discovery/rpcz/validator.go
Reed pointed out:
> if artist has closed their inbox, then sends out blast, then fan upgrades blast.. will the chat create work? will permissions prevent that?
This changes `validateChatCreate` to skip the `chat_allowed` UDF check if user is creating a chat from a blast.
In `chat_blast_test.go` blaster closes inbox... tests will fail without change to `validateChatCreate` but pass afterwards so that's a good sign.
=> Chat create from blast validator

packages/common/src/context/comments/commentsContext.tsx
The way the cache here is set up is that the cache disappears as soon as the query using them unmounts. On web this results in every sort button resulting in a "fresh load".
On mobile however, sort by top was not being refreshed because there are two context providers and one is still holding on to the cached query data.
I made it explicitly clear the cache on sort change to fix
ios:stage
=> [C-5173] Fix sort by top comments out of date

packages/common/src/models/Analytics.ts, packages/common/src/store/pages/chat/sagas.ts, packages/mobile/src/screens/chat-screen/ChatBlastCTA.tsx, packages/web/src/pages/chat-page/components/ChatBlastCTA.tsx
- Adds amplitude tracking events for create chat blast funnel
- `CHAT_BLAST_CTA_CLICKED`
- `CREATE_CHAT_BLAST_SUCCESS`
- `CHAT_BLAST_MESSAGE_SENT`
staging amplitude
=> [PAY-3347] Analytics for create chat blast funnel

packages/common/src/hooks/chats/useSetInboxPermissions.ts, packages/common/src/store/pages/chat/sagas.ts, packages/common/src/utils/error.ts, packages/mobile/src/screens/settings-screen/InboxSettingsScreenNew.tsx, packages/web/src/components/inbox-settings-modal/InboxSettingsModalNew.tsx
- update sentry errors to all use same name
- remove console.errors (no need to send duplicate data to sentry?)
Tested with local events sending to sentry being turned on
Example sentry event: https://audius.sentry.io/issues/5991820262/?query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=1
Added alert: https://audius.sentry.io/alerts/rules/audius-client/15506983/details/
=> [PAY-3437] Add names to chats sentry reports

packages/mobile/src/components/comments/CommentActionBar.tsx, packages/mobile/src/components/comments/CommentOverflowMenu.tsx, packages/mobile/src/components/comments/CommentSection.tsx, packages/mobile/src/components/core/UserGeneratedText.tsx, packages/mobile/src/harmony-native/components/Button/BaseButton/BaseButton.tsx, packages/mobile/src/screens/track-screen/TrackScreen.tsx
* Prevent rerender of TrackScreen when drawer opens by moving drawer open state into CommentSection
* Use useSelector instead of useGetUserById in CommentOverflowMenu. For some reason audius-query incurs a render here, we should probably migrate to tan-query!
* Remove state in BaseButton that was measuring width and causing a rerender. widthToHideText wasn't used anywhere
* Prevent measuring of layout in UserGeneratedText when `allowPointerEventsToPassThrough` is not enabled
* Wrap callbacks in useCallback
Performance profile of opening the comment drawer
Before:
After:
=> [C-5167] Improve mobile comments perf

packages/mobile/src/components/composer-input/ComposerInput.tsx, packages/mobile/src/screens/chat-screen/ChatTextInput.tsx
Currently when you press a keystroke into the composer input, we trigger 3 re-renders of the input itself
1. Because `value` changes
2. Because we have state to track selection (this can be a ref)
3. Because the parent component maintains its own state for `value` which alters the `onSubmit`
Reduce this to one re-render. Should help a lot!
Tested on simulator with logs, will test on android device after it builds.
TBH i've actually noticed that this is more performant on pixel 6 than iphone 14, so that's kinda cool
=> [PAY-3466] Improve composer input responsiveness on mobile

packages/web/src/pages/chat-page/ChatPageProvider.tsx
The back button pulls the previous state from browser history. Add effect to chat page provider to clear the state after "first use" to prevent the bug.
`npm run web:stage`  - bug does not repro with steps:
1. share a track with someone from the track share dialog
2. go to the track page from the dm you just sent
3. press back
=> [PAY-3523] Fix bug where share to DM persists in input

packages/common/.eslintrc.js, packages/mobile/.eslintrc.js, packages/web/.eslintrc.js
Direct imports from the `dist` folder often cause weird build or runtime issues for us. We shouldn't ever need to do this. It is still a pattern used for libs imports. But that code is now coming from a separate package. So this rule will generate an error for any direct `dist` imports from SDK. It applies only to web/mobile/common.
Temporarily added some code that breaks the rule and verified it triggers appropriately.
=> [PAY-3424] Restrict imports from SDK 'dist' folder in client code

cmd/core/Makefile, pkg/core/console/block.go, pkg/core/console/console.go, pkg/core/console/state.go, pkg/core/console/views/layout/base.templ, pkg/core/console/views/layout/site_frame.templ, pkg/core/console/views/pages/block_page.templ, pkg/core/console/views/pages/block_page_templ.go, pkg/core/console/views/pages/nodes_page.templ, pkg/core/console/views/pages/overview_page.templ, pkg/core/console/views/pages/overview_page_templ.go, pkg/core/console/views/pages/tx_page.templ, pkg/core/console/views/pages/uptime_page.templ, pkg/core/core.go, pkg/core/db/reads.sql.go, pkg/core/db/sql/reads.sql
- mostly decouples console from the rpc
- in the core.go console is started prior to the node starting up
- it does create an http rpc connection for data like node status, we can add smarter logic around using a local instance for this later
- uses the block and tx models from the db for views, this table does not have proposer or other info. once we implement data companion we'll have more control over what's available in these models
- fixes the core-gen command with console
- adds a previous and back button to the block pages for simple nav
`make core-gen && make core-dev`
=> decouple console from rpc

.circleci/src/jobs/@audiusd-jobs.yml, cmd/audius-ctl/jump.go, cmd/audius-ctl/up.go, dev-tools/templates/test-localhost.yaml, pkg/conf/model.go, pkg/orchestration/docker.go, pkg/orchestration/run.go
Allows a node configuration to be run on localhost without the need to modify /etc/hosts. Just add `isLocalhost: true` to the node config.
Also makes running `audius-ctl up|down|restart` more convenient by not requiring `--all` or any hostname arguments if your config contains only a single node.
New tests added to CI
=> [PROTO-1951] Add localhost node configuration

packages/mobile/src/screens/chat-screen/ChatBlastCTA.tsx
We weren't changing the offset properly depending on whether the play bar is open.
<image height="500px" src="https://github.com/user-attachments/assets/44232474-7329-4d82-8679-b54bbe96282a" />
=> [PAY-3521] Fix offset calculation for Blast CTA

packages/web/src/components/stat-banner/StatBanner.tsx
The message button on web profile was disabled when the user is not permitted to dm the profile. We have logic to show the InboxUnavailable modal which shows the appropriate CTA instead, but it's being eclipsed due to the disabled button.
=> [PAY-3509] Show InboxUnavailableModal instead of disabled button

packages/web/src/pages/chat-page/components/ChatListBlastItem.tsx, packages/web/src/pages/chat-page/components/ChatListItem.module.css
This [PR](https://github.com/AudiusProject/audius-protocol/pull/10057/files) added class `messagePreview` to the blast list items, but that class caused an unexpected scroll on larger screen. 
- Navigate to message inbox
- Send a blast
- Ensure there is no horizontal scroll
=> [PAY-3526] Hide scroll on message inbox

packages/common/src/store/pages/chat/slice.ts
We were skipping the updates to the `chats` entity adapter if the `messages` entity adapter didn't contain an entry for that chatId. But we should still update the `chats` entity adapter!
https://github.com/user-attachments/assets/bf44ff23-7f34-4bf5-aa24-6e43ee508119
=> [PAY-3456] Fix chat last message sometimes wrong

packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
```
Error in indexing blocks (psycopg2.errors.NotNullViolation) null value in column \"user_id\" of relation \"comment_mentions\" violates not-null constraint\nDETAIL:  Failing row contains (448837086, null, 2024-10-16 20:43:09, 2024-10-16 20:43:09, f, 0xcb3eba85a4287a349f6f589a4d6becdf48bb2afc74c803207e375021908eb7..., 0xfacf003400b139e932071b3e2cc9c4d254e8af0bd9ae078ea203d6e3f2a4fe
```
coming from 
```
{
"cid": "",
"data": {
"entity_type": "Track",
"user_id": 283281549,
"track_id": 1549671167,
"body": "@sebastian2724 https://staging.audius.co/Rufus/middle-finger-type-beat-571",
"parent_comment_id": 4683648,
"mentions": [
null
],
"current_sort": "top",
"new_id": 489940277,
"entity_id": 1549671167,
"comment_id": 489940277
}
}
```
should check if all mentions are ints.
_Please describe the …
=> Validate comment mentions

packages/mobile/src/screens/chat-screen/UserChatHeader.tsx
Bit of a janky fix but works.. not sure what the situation is with the bounding header for screens in RN, so trying to stuff like flex-shrink and `w=100%` weren't working.
before:
after:
=> Fix chat header too long on mobile

packages/harmony/src/components/text/Text.tsx, packages/web/src/components/track/GiantTrackTile.module.css, packages/web/src/components/track/GiantTrackTile.tsx
Noticed that track pages allow for text overflow in descriptions which causes a horizontal scroll on mobile pages. This is a quick fix for that. 
On prod env starting on main branch: 
- Navigate to [this](https://audius.co/BenWest/was-len-sassaman-satoshi-a-notebooklm-pod)
- Make your screen small
- Notice the text overflow
- Switch to this branch
- Refresh 
- Notice the text overflow is gone
Before: 
After:
=> [PAY-3525] Fix text overflow

packages/mobile/src/components/composer-input/ComposerInput.tsx
The rendering of our custom elements is slower on mobile than web. I think this has to do with the React Native render cycle and bridging that paint back to the host OS. On web this isn't a problem, so when the input text behind where you're typing is transparent, things seem fast and responsive.
On mobile, it feels slow though. The transparent text is laid out almost immediately (yes, controlled inputs are fine), but the "rendered on top" text comes in a few ms later.
What makes this PR possible though ... is I've noticed that painting our rendered UI on top of the input (when transparency is removed) doesn't seem to cause any aliasing or glyph-ing that tends to happen on web (hence the original transparency change). I think that means we don't have to make the input itself have …
=> Improve mobile composer input render perf

packages/mobile/src/components/comments/CommentDrawer.tsx, packages/mobile/src/components/comments/CommentForm.tsx, packages/mobile/src/components/composer-input/ComposerInput.tsx, packages/mobile/src/components/composer-input/types.ts
* Use `onLayout` to set cursor position on android when replying/editing
* Add hitSlop to 'cancel' button in ComposeInputHelper
* Clear editing/replying state when closing drawer
=> [C-5137] Set android cursor position when replying/editing

comms/discovery/db/queries/get_new_blasts.go
We were getting this error when calling the get new blasts endpoint:
```
pq: subquery in FROM must have an alias
```
turns out it fails in postgres 15 but is ok in postgres 16 which is why it was ok in the comms tests, but not ok once deployed. @stereosteve is going to specify the version in tests docker.
Tested in local stack, get new blasts endpoint succeeds!
=> Fix get new blasts endpoint sql error

packages/web/src/components/track/GiantTrackTile.tsx
The bottom corners on GiantTrackTile were overflowing
Fixed using Paper instead of Flex for the top level container as Paper has overflow:hidden and is appropriate here anyway.
=> [QA-1773] Fix corner overflow on GiantTrackTile

package-lock.json, packages/mobile/android/app/build.gradle, packages/mobile/ios/Podfile.lock
The lockfile changes from #9830 got undone by accident with the big PR to split SDK from libs. This broke my local dev environment :-).
I manually uninstalled/re-installed the packages that were changed in that PR to get the lockfile back to a good state.
I still do not understand why NPM can't reconcile a version difference between one single `package.json` file and the repo-level `package-lock.json` file. It absolutely refuses to update the lockfile unless I manually uninstall/reinstall 🤷 .
Will confirm local dev can build and run the mobile app and that Ci passes.
=> Re-land changes to fix RN on xcode 16

packages/mobile/src/components/drawer/Drawer.tsx, packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx, packages/sdk/src/sdk/api/generated/full/models/SearchTrackFull.ts, packages/sdk/src/sdk/api/generated/full/models/TrackFull.ts
We explicitly disable keyboard hiding on tap for the FlatList so that you can scroll around in the chat and interact with items (favoriting tracks etc) without losing your in progress message composition.
I settled on implementing an optional behavior in `Drawer` that will dismiss the keyboard on mount, and then configured the purchase drawer to use that behavior. I didn't want to make this the default behavior for all drawers due to the large surface area that would impact and also the strange interaction that happens if you tap a track inside a DM to play it (player is also a drawer 😄 )
Tested on simulator against staging.
https://github.com/user-attachments/assets/dbecf068-28c8-4a9a-a851-874a002e7357
=> [PAY-3522] Hides keyboard when opening purchase drawer from a DM

packages/mobile/src/components/comments/CommentDrawer.tsx, packages/mobile/src/components/comments/CommentDrawerContext.tsx, packages/mobile/src/components/comments/CommentDrawerForm.tsx, packages/mobile/src/components/comments/CommentForm.tsx, packages/mobile/src/components/comments/CommentSection.tsx
* Pressing the comment form in the empty state opens the comment drawer and focuses the input
=> [C-5212] Open comment drawer from empty state

packages/discovery-provider/src/tasks/entity_manager/entities/track.py
```
in download_track\n    city=params.metadata.get(\"city\"),\n         ^^^^^^^^^^^^^^^^^^^\nAttributeError: 'str' object has no attribute 'get'", 
```
may want more validation on having city, or default to null
=> Unblock download track geo indexing

packages/mobile/src/components/comments/CommentDrawerHeader.tsx, packages/mobile/src/components/comments/CommentForm.tsx, packages/mobile/src/components/composer-input/ComposerInput.tsx, packages/mobile/src/components/core/TextInput.tsx
* Restrict comment input length to 400
ComposeInput is still using the legacy TextInput which did not support max length display. I attempted to migrate it to harmony TextInput but it ended up being quite a lot of work. Instead I added the max length display to the legacy TextInput. This is kinda gross because it's importing harmony components. But we can always come back and clean it up ™️ 
* Went ahead and knocked out the layout changes in C-5154 because the positioning of the max length display depended on it
* Fixed small layout issue with drawer header I caused
Tested max length on ios, tested inputs app wide to confirm no breaking changes
=> [C-5218] [C-5154] Restrict mobile comment input length

packages/discovery-provider/plugins/pedalboard/apps/mri/src/queries/udr.ts
MRI gave feedback that now instead they want a column for offering instead of zero'd out rows.
Also add country support for downloads, which will exist in >= 0.7.16 protocol release
Ran against prod db clone
=> [PAY-3538] Update UDR to match spec

pkg/core/console/block.go
when you click a tx on the block page it doesn't resolve, this is because we're hashing the full tx result not the tx itself
=> fix block page hash link

packages/mobile/src/screens/edit-collection-screen/EditCollectionScreen.tsx
We wanted to omit the existing tracks list, but tracks is required in the schema.
Need to instantiate the initial values properly
saving is working now; double checked that the empty tracks value does not result in deleting any existing tracks on save
=> [QA-1775] Fix validation error in mobile EditCollection

.circleci/src/jobs/@web-jobs.yml, packages/web/scripts/dist.js
- Fixes mac prod build which didn't have enough resources to complete
- Removes mac build warning that our minimum mac version was too low
=> Fix mac prod build, remove warnings

packages/common/src/context/comments/commentsContext.tsx, packages/mobile/src/components/comments/CommentForm.tsx
* Fix showing keyboard when autofocusing input on android
* Fix clearing of replyingAndEditingState when closing the drawer (broken in #10103 )
Confirmed keyboard opens as expected
=> [C-5229] Fix comment input focus on android

packages/discovery-provider/plugins/notifications/src/sns.ts
- Error was not getting re-thrown in `publish` fn
- Needed to unwrap the inner `Error` object
- `code` needed to be capitalized to `Code`
Tested by running the code on notifications plugin on prod DN1, confirmed we got some disabled rows in the db.
=> Fix disabling notif arn endpoints

packages/mobile/src/screens/sign-on-screen/screens/SelectGenresScreen.tsx
Fix issue where the genre pills were not re-rendering when the value changed.
Pills would become selected but not unselected.
Updated the memoization to re-render when the value changes. The comment above seems to indicate this isn't necessary, but it wasn't working in my testing. @DejayJD if you know a better fix, pls lmk
toggling on and off genres is working, produces the right values
=> [QA-1755] Fix toggling on native genre pills

packages/mobile/src/components/core/Link.tsx
Links weren't guaranteed to start with `http(s)://`
Interestingly, `Linking.canOpenURL` would return true because it would try to open the file in the local directory of the app (e.g. `"Unable to open URL: file:///.../Audius%20Music.app/www.google.com"`)
Added check to add the prefix if not present.
The link now opens properly. Checked that we don't use this Link component for internal routing that would break with http prefix.
=> [C-5252] Fix external links on mobile

packages/mobile/src/components/toasts/Toast.tsx
"Fixes" issue where android toasts stop working after the first one or two. I traced down the issue to the "dismissToast" call. It works on ios, but doesn't on android. The thing is, we dont really need to dismiss them from the store, they will just continue to be "off", even if the data stays collected in redux. Ideally we figure out a better solution, but i think this is okay for now, because i dont expect the number of toasts per session to be that much to lead to performance impacts.
@schottra added you because i remember we discussed this as while back
=> [C-5168] Fix android toasts

packages/mobile/src/screens/settings-screen/InboxSettingsScreenNew.tsx
- InboxSettings mobile was showing `ALL` permissions when db had `NONE`
- Check `chatPermissionsStatus` before initializing the form
- Because we wait to render the form until we have the data, the `initialValues` will always be populated correctly
repro'd on simulator; fixes the issue
=> [PAY-3542] Fix bad initial data in mobile inbox settings

packages/common/src/api/tan-query/comments.ts, packages/web/src/components/comments/CommentActionBar.tsx, packages/web/src/components/comments/CommentForm.tsx, packages/web/src/components/comments/CommentList.tsx, packages/web/src/components/comments/CommentSection.tsx, packages/web/src/components/comments/CommentSkeletons.tsx
Improves the load skeletons on desktop (most notably doesn't reload the whole section on a sort swap). 
Combines the code between mobile web & desktop better
Also, I found a bug with new replies having the option to "pin" - so I squeezed that fix in.
web:stage
=> [C-5053] Rework desktop comment load skeletons

packages/mobile/src/components/comments/CommentBlock.tsx, packages/mobile/src/components/comments/CommentDrawer.tsx, packages/mobile/src/components/comments/CommentForm.tsx, packages/mobile/src/components/composer-input/ComposerInput.tsx, packages/mobile/src/components/composer-input/types.ts, packages/mobile/src/components/core/TextInput.tsx
* Replace composer input overlay with Text children. This should be less fragile and allows scrolling
* Improve lineheight of userlink in comment headers
* Fix issue with compose input placeholder
* Exit autocomplete on Enter key press
* remove things related to the Cancel accessory
https://github.com/user-attachments/assets/8cc094ab-f77c-4377-bdc9-ea076365a572
Tested on ios, testing on android in progress
=> [C-5226] [C-5225] Allow ComposerInput scrolling with mentions

packages/discovery-provider/nginx_conf/nginx_container.conf
Successive comments would show as duped and then disappear because they were using conflicting comment IDs. This is because discovery is caching IDs in the openresty layer.  
Confirmed unclaimed IDs are no longer cached and spamming comments are saved as expected.
=> [C-5144] Disable caching on unclaimed comment ID

packages/web/src/components/comments/CommentSection.tsx
- Artist popovers were getting clipped by `overflow: hidden`
=> [C-5232] Fix clipped artist popovers on comments section

packages/web/src/components/comments/CommentPreview.tsx, packages/web/src/components/comments/CommentSection.tsx
- We were missing this onClick
- Moved the paper wrapper down a level so that the full area is clickable
- Only add the onClick to the case where we're showing one or more comments
- Also fixes a red icon
local web
=> [C-5232] Navigate to comments on comments preview click

comms/discovery/config/constants.go
Ty @rickyrombo and @dharit-tan for the assists
- Blast senders were hitting the rate limit on this query during future chat creates
```
const maxNumNewChatsSince = `
WITH counts AS (
SELECT COUNT(*) AS count
FROM chat
JOIN chat_member on chat.chat_id = chat_member.chat_id
WHERE chat_member.user_id IN (:Users) AND chat.created_at > :Cursor
GROUP BY chat_member.user_id
)
SELECT COALESCE(MAX(count), 0) FROM counts;
`
```
- For now, just bumping the limit up to 100k, but we'll want to circle back and update this query to ignore messages that resulted from a blast upgrade so we can put the rate limit back after
=> Bump chat create rate limit to unblock blasts

packages/discovery-provider/plugins/pedalboard/apps/solana-relay/src/utils/transaction.ts
I'm not sure when this was added or if i just missed it before, but this should solve our BlockhashNotFound errors.
https://solana.com/docs/advanced/confirmation#be-wary-of-lagging-rpc-nodes-when-sending-transactions
=> Use replaceRecentBlockhash to fix BlockhashNotFound error

packages/common/src/api/tan-query/comments.ts
While debugging comment count issues from search I noticed that I wasn't properly updating the track cache when the comment count loaded in on the comment page.
web:stage
=> Small comment count fix

packages/common/src/adapters/notification.ts, packages/common/src/store/notifications/selectors.ts, packages/web/src/components/notification/NotificationPanel.tsx
```
ERROR  Warning: Encountered two children with the same key, `283281549`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
in RCTView (created by View)
in View (created by ProfilePictureList)
in ProfilePictureList (created by CommentThreadNotification)
in RCTView (created by View)
in View (created by NotificationHeader)
in NotificationHeader (created by CommentThreadNotification)
```
This would probably fix the ticket - I don't think there should ever be a case where a notification has duplicate user ids (which would lead to a key error in the notifications `profile` component).
I couldn't get a repro though.
_Please …
=> [C-5275] Fix react dupe key error in notifs

packages/web/src/components/comments/CommentActionBar.tsx, packages/web/src/hooks/useRequiresAccount.ts
Refactor requiresAccount hook to provide a callback version in addition to the component level effect version
=> [C-5287] Require an account to reply to/flag comments

packages/discovery-provider/integration_tests/queries/test_get_comments.py, packages/discovery-provider/src/queries/get_comments.py
Filter out comments from users muted by the track owner, except if I am the one muted.
This logic is a bit dicey / hard for me to grok because I don't have the full background. I believe this what we want to do, but could use extra scrutiny.
"integration" tests via TDD
```
pytest integration_tests/queries/test_get_comments.py
```
=> [C-5279] Exclude users from comments who are muted by the owner

packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx
Crux of the issue was that mutedUsers weren't requested yet leading to state always being false. This can all get cleaned up when we move to tan-stack
=> [C-5253] Fix muted comments not showing up on profile page

packages/common/src/adapters/collection.ts, packages/mobile/src/store/offline-downloads/sagas/requestDownloadCollectionSaga.ts
All offline collection downloads were failing to enqueue because they weren't making it through the `userCollectionMetadataFromSDK` adapter .
Despite the data coming directly from sdk, the expected `input.userId` field did not exist. @schottra curious if the proper fix here is to update the data returned from sdk?
Also, neither `input.tracks` nor `input.addedTimestamps` was populated, so switched to using `input.playlistContents`
Previously, the toggle would go on, but none of the tracks would enqueue. Now collection and its tracks are downloading properly 🎉
=> [QA-1549] Fix offline collection downloads

packages/common/src/store/lineup/actions.ts, packages/common/src/store/lineup/reducer.ts, packages/mobile/src/screens/collection-screen/useFetchCollectionLineup.ts, packages/mobile/src/screens/favorites-screen/useCollectionsScreenData.ts
- Offline playlists were showing up in albums tab and vice versa
- Offline lineups were breaking and showing stuck loading state after playing a track near the end of the lineup
local sim. Lineup loading and collection tile filtering are both working properly now
=> [QA-1787, QA-1786] Fix offline collections filtering and playback

packages/harmony/src/utils/formatTrackTimestamp.ts
Need to pad minutes to 2 digits whenever hours is present.
`1h 20m -> 1:20:00`
`4m -> 4:00`
`1h 3m -> 1:03:00`
=> fix padding for duration minutes

packages/mobile/src/screens/track-screen/TrackScreenRemixes.tsx, packages/web/src/pages/track-page/components/TrackRemixes.tsx, packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
I think SDK migration may have broken this because we were using list of results to determine whether to show the button. Good thing is that the fix is easy!
=> [QA-1785] Fix remixes missing view all button

packages/discovery-provider/integration_tests/queries/test_get_comments.py, packages/discovery-provider/src/queries/get_comments.py
Replacement PR for https://github.com/AudiusProject/audius-protocol/pull/10223
It was simpler than we thought + adding more tests
```
pytest integration_tests/queries/test_get_comments.py
```
=> [C-5279] Exclude users from comments who are muted by the artist

packages/web/src/pages/track-page/components/desktop/TrackPage.tsx
Before the 'more by artist' track tiles were either too wide or too narrow.
This snaps both to the expected width
width is now correct
also checked the responsive changes where the more by section goes below comments. This looks good too.
=> [QA-1789] Fix more by artist width

comms/discovery/rpcz/peer_sweeper.go, comms/discovery/server/server.go, comms/go.mod, comms/go.sum
* Sweeper can request + receive msgpack in addition to JSON
* Other server looks for `?msgpack=t` query param and will send msgpack with `Content-Type: application/msgpack` in response header
* JSON will still work on both sides while servers upgrade
TODO:
* After 0.7.21 is on all nodes... push POST request can send msgpack too.
* Also after 0.7.21 is on all nodes... reset `rpc_cursor` to 10/23 to ensure no missed messages
=> Use msgpack between servers.

packages/discovery-provider/nginx_conf/nginx_container.conf
This reverts commit 1c91f857655026a3f3debc3d9fbf44c38d9b16fe.
The X-Forwarded-Proto being set by nginx had the unintended behavior of being set to http instead of https, because Caddy sits in front of our nginx.
See https://github.com/AudiusProject/audius-docker-compose/pull/545 for the Caddy change
=> Revert "Add X-Forwarded-Proto to nginx config to fix resolve endpoint (#10239)"

.changeset/unlucky-taxis-admire.md, packages/sdk/.eslintrc, packages/sdk/src/sdk/api/albums/AlbumsApi.ts, packages/sdk/src/sdk/api/tracks/TracksApi.ts
Prior to this change, purchasing tracks or albums with external wallet would throw a Zod error for the extra parameters being passed into `getPurcahseInstructions`
=> Fix purchases with external wallet and wallet adapter

packages/discovery-provider/integration_tests/tasks/entity_manager/test_comment.py, packages/discovery-provider/src/tasks/entity_manager/entities/comment.py
Seeing some skipped transactions because of an error where the existing comment reaction doesn't exist when un-reacting. This modification ignores those txs instead of triggering a skip.
Modified existing invalid test case.
=> Fix validations for unreact comment

packages/mobile/src/components/comments/CommentBlock.tsx, packages/web/src/components/comments/CommentBlock.tsx
When a user is loading it looks pretty jank right now, I noticed this happens a lot on prod.
web:stage & ios:stage
=> [C-5314] Add load states for comment display names & avatars

packages/discovery-provider/ddl/migrations/0102_shorten_challenge_ids.sql
Because the `challenge_id` didn't change for these, I mistakenly left them out of the migration.
For consistency across all specifiers, they should be included as well and have their specifiers hexed and delimited with a `:`
=> Include specifiers for Audio Match in migration

packages/web/src/components/comments/CommentForm.tsx
=> [C-5309] Reset comment form text on location change

packages/web/src/components/user-generated-text/UserGeneratedText.tsx
`Linkify` component wasn't rendering our component properly so React got confused when changing pages and threw an error about hooks being called inconsistently
=> [C-5308] Fix react crash in UserGeneratedText

packages/discovery-provider/src/api/v1/utils/resolve_url.py
There could be arbitrary proxies eating the {scheme} before this app code executes, so just set https if we in a stage or prod env. Could cause some issues for people running a prod config locally, but idc too much abt that given how hard this is to fix in prod.
deployed to stage dn and tested
```
await fetch('https://discoveryprovider5.staging.audius.co/v1/resolve?url=https://staging.audius.co/isaactest/large-file')
```
🤞  that this works on prod the way we hope for other nodes
=> Fix resolve scheme in url_for

packages/discovery-provider/src/tasks/index_rewards_manager.py
While other nodes still have the old formats, add a temporary mapping.
Revert this PR after nodes all have 0.7.22 and up
prod dn2 confirmed AudioTransactions are indexed ok
=> Add mapping from old rewards to new rewards

packages/commands/src/edit-track.mjs, packages/common/src/services/audius-backend/AudiusBackend.ts, packages/web/src/common/store/cache/tracks/sagas.ts
I updated `updateTrackV2` to require passing `userId` in #9673 and missed updating the usages of it in `AudiusBackend` due to libs being untyped there. 😬 
Verified edits work again on local client against staging.
=> Fix track updates missing userId

packages/discovery-provider/integration_tests/queries/test_get_comment_count.py, packages/discovery-provider/src/queries/get_track_comment_count.py, packages/web/src/components/comments/CommentPreview.tsx
- Fixes the bug where god mode reports causes comment count to be 0
- Added tests for every comment count query case that I could think of
- Fixes the mobile web bug where comments show (5) even when larger than that 
discovery tests - will test live on staging to see it in client
=> [C-5283] Fix comment count bugs + add tests

packages/web/src/components/track/GiantTrackTile.tsx
* Make track description selectable on web
We really should just remove: https://github.com/AudiusProject/audius-protocol/blob/main/packages/web/src/assets/styles/index.css#L26 and selectively have user-select: none on elements we don't want selectable. This would be better for accessibility too
=> Make track description text selectable on web

packages/common/src/schemas/upload/uploadFormSchema.ts
https://github.com/AudiusProject/audius-protocol/pull/10146 removed `is_stream_gated` and `is_download_gated` from backend and returns null when they aren't present. This caused an issue with our upload/edit form validation
Confirmed edit collection works
=> Make is_stream_gated and is_download_gated nullable in upload schema

packages/web/src/components/comments/CommentThread.tsx, packages/web/src/components/composer-input/ComposerInput.tsx
Added simple slide animation for comment replies on web
=> Add reply comment animation to web

packages/web/src/components/lineup/LineupProvider.tsx
The Profile page was broken in https://github.com/AudiusProject/audius-protocol/pull/10298 because the `totalTileHeight` object doesn't have a value for the `grid` variant.
This value is used to determine how many tracks to load based on how many fit on the screen at a time, so that we can load "pages" of tracks as they are visually needed.
Because the entry was missing, the math for that was returning `NaN`, and then the `LineupProvider` was throwing up an error `RangeError: Invalid array length` when trying to render the skeleton tiles (I think) based on the count that was supposed to be loading
=> [QA-1807] Fix Profile Page: Add entry to totalTileHeight map of 140 for grid lineup variant

.circleci/config.yml, .circleci/src/jobs/@mobile-jobs.yml, .circleci/src/workflows/mobile.yml
Adds scripts to update the mobile app versions during client release, since we always shoot for full app version each week
Also removes native change alert, since it's irrelevant and hasnt helped us
=> Update mobile app versions during client release

packages/harmony/src/components/button/FilterButton/FilterButtonOptionsList.tsx
The refactor of FilterButton to use MenuItem broke the fallback logic when label isn't provided for an option. See harmony.audius.co:
This also broke the harmony tests which is blocking npm publish currently: https://github.com/AudiusProject/audius-protocol/actions/runs/11674036614/job/32506307574
=> Fix FilterButtonOptionsList label prop

pkg/core/config/genesis/prod.json, pkg/core/config/genesis/stage.json, pkg/core/core.go
- sets new limits on block, tx, and mempool sizes for core
- blocks are limited to 15mb at the genesis level
- tx sizes are limited to 300kb
- mempool is restricted to 500mb to free up other core resources
- validator connection settings are boosted to get to faster block times
- non validator connection settings are nerfed to allow validators to create blocks with higher priority
- pex reactor is turned off because we don't need it and it's probably using unnecessary network bandwidth
- sets up new networks with these settings since there's some genesis level changes
- sets duplicate ip connections allowed to true, this will help with sandboxes
=> new config restrictions and networks

packages/mobile/src/components/core/AccessTypeLabel.tsx, packages/web/src/components/access-type-label/AccessTypeLabel.tsx
Small fix to remove the timezone section for access-type-labels
=> Remove scheduled release timezone on access-type-labels

packages/web/src/pages/settings-page/components/desktop/ManagerMode/FindAccountManagerPage.tsx
Audius query state is an empty object prior to the fetch completing, so the managers list key is undefined until the request completes as well.
=> Add undefined check for managers before mapping

packages/common/src/store/buy-usdc/sagas.ts, packages/common/src/store/buy-usdc/utils.ts, packages/common/src/store/purchase-content/sagas.ts, packages/common/src/store/purchase-content/slice.ts, packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx, packages/web/src/common/store/upload/sagaHelpers.ts, packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
We were seeing a number of failures in fetching token accounts due to the fact that we "getOrCreate" it and then immediately attempt to read the account info.
This PR fixes that. Plus a little more.
* Updated `getUSDCUserBank` to be `getOrCreateUSDCUserBank`.
* Added concurrency protection around the above saga function so that only the first entrance will kick off the async logic to create the user bank first time. Other sagas will listen for the channel event and use the result instead.
* Added a helper function for polling the token account, so we're less likely to fail in scenarios where the transaction to create the account hasn't quite finalized and it doesn't exist on whatever RPC we're talking to
* Updated the handful of sagas which use the create->immediate get pattern to use the …
=> [PAY-3580] Make user bank logic for first time buyers more robust

packages/mobile/src/components/top-tab-bar/CollapsibleTopTabNavigator.tsx, packages/mobile/src/screens/profile-screen/ProfileHeader/ProfileHeader.tsx, packages/mobile/src/screens/profile-screen/ProfileScreen.tsx, packages/mobile/src/screens/profile-screen/ProfileScreenSkeleton.tsx, packages/mobile/src/screens/profile-screen/ProfileTabs/ProfileTabNavigator.tsx
- Undo the change that pulls out the profile screen header and renders it outside the navigator. This results in the entire profile header screen being sticky as we scroll down the profile screen, which is not what we want.
- Also remove memos from profile screen skeletons (not needed)
Tested on ios stage
=> Fix mobile profile header sticky

packages/common/src/hooks/helpers.ts, packages/common/src/hooks/useGatedContent.ts, packages/mobile/src/components/core/AnimatedButton.tsx, packages/mobile/src/hooks/useRemoteConfig.ts
- Fix issue where `useFeatureFlag` hook was rerendering every time `user` changed
- This was causing every track tile on feed to rerender on favorite
- Changed default to wait for `AnimationButton` to finish animating before calling the `onPress` callback
- This makes Favorite, Repost, Play, Repeat, Repost, Shuffle buttons all feel SNAPPY AF
https://github.com/user-attachments/assets/8b3a8c10-8582-4b72-8e74-86ead925f00b
=> [C-5333, C-5334] Fix animated button perf; fix useFeatureFlag perf

packages/web/src/components/table/Table.tsx, packages/web/src/pages/collection-page/CollectionPageProvider.tsx
Two small issues causing this:
* Table was calling sort when it did not need to
* The initial sort order was not being updated when tracks were added to the playlist
=> [QA-1802] Fix add to playlist on web

packages/mobile/src/components/core/Screen/ScreenPrimaryContent.tsx, packages/mobile/src/components/core/Screen/ScreenSecondaryContent.tsx
mostly authored by @amendelsohn 
Fade in animations for screen content as content loads in.
Do not use the animations on android because the shadows are rendered natively and appear behind the `Animated.View` before the animation begins. It looks bad. They work great on ios though.
We need `flex: 1` on the secondary content so that it grows to fit the parent container.
Tested on ios sim and android device
=> [C-5378] Fade in mobile screen content on load

packages/common/src/store/pages/chat/slice.ts, packages/common/src/utils/chatUtils.ts, packages/mobile/src/screens/chat-screen/ChatScreen.tsx, packages/web/src/pages/chat-page/components/ChatMessageList.tsx
Bug: the fix from [this PR](https://github.com/AudiusProject/audius-protocol/pull/10025) in `packages/common/src/store/pages/chat/slice.ts` was breaking an assumption on mobile ChatScreen: that the loading state is only true when `messagesStatus === 'IDLE'`. After that PR, the first time loading a chat `messagesStatus` would be initialized to `IDLE` but the messages fetch was in progress. Previously it was initialized to `undefined` which would coalesce to `LOADING` [on this line](https://github.com/AudiusProject/audius-protocol/blob/ed5b59abdfba4e079211fdc8927f4d9a57dc4c44/packages/mobile/src/screens/chat-screen/ChatScreen.tsx#L260).
Solution was to add a new status: `PENDING` that's for the first time loading a chat. This draws inspiration from …
=> [PAY-3544] Fix flashing empty state on mobile chat screen

packages/web/src/components/artist-recommendations/ArtistRecommendations.tsx
The first render of the recommendations had the idsToFollow as null which, when passed to the selector, would fetch and then get the profile pictures for every single user in the cache. Not very cash money
Falling back to an empty array fixes this
=> [QA-1753] Fix Suggested Artists Popup lag

Makefile, scripts/release-core.sh
Useful for faster dev cycles, and since core is not currently vital infra.
shellcheck + dry run, although the image has not been built and published.
=> Add make targets to force release core image

packages/mobile/src/components/lineup/Lineup.tsx
- Bumped lineup batch size constants
- In practice, on my device this led to initial page of 15 items, and subsequent pages of 10. Up from 9 and 4 respectively.
Should we go higher?
android physical device, ios sim
=> [C-5336] Load more items on mobile feed/trending

packages/common/src/store/pages/profile/reducer.ts
Fixed a small boolean logic error in profile page reducers
We were doing `false ?? otherValue` but should have been doing `false || otherValue` bc false is not null
Changed it to a ternary to make it easier to read
=> [QA-1790] Fix boolean logic error in profile page reducers

packages/discovery-provider/src/queries/query_helpers.py
Was fetching mirrorCount, but using the first selected as the canonical "non-mirror" - need to fetch mirrorCount + 1 to account for this.
=> Fix off-by-one error in fetching mirrors

.changeset/stupid-pens-happen.md, packages/sdk/src/sdk/services/Solana/programs/ClaimableTokensClient/ClaimableTokensClient.ts, packages/web/src/common/store/pages/audio-rewards/sagas.ts
Inside the `claimReward` is a call to `getOrCreateUserBank` which creates a user bank if one doesn't exist. However, `claimReward` is called for each specifier there is to claim, often in parallel. If a user's user bank did not exist, multiple attempts to create it would occur. Unfortunately, the Claimable Tokens program doesn't support idempotent token account creation of these user banks, so those transactions would fail with custom error code 0x0 ("Account already allocated") on the inner system program instruction that attempts to allocate the user bank token account. (Sidenote: our SDK code would interpret that custom error code as coming from _our_ instruction, thus leading to the "Signature verification failed" misnomer for these errors in Amplitude or Sentry)
This PR attempts to …
=> Fix concurrent user bank creations at the SDK level

packages/common/src/store/pages/chat/sagas.ts
While we wait for https://github.com/AudiusProject/audius-protocol/pull/10396 to go out, this is a client fix that will always mark the chat as read (at the expense of firing off more `chat.read` requests).
We can revert this logic down the line - already made a ticket.
Tested on local stack + web
=> [PAY-3592] Always mark chat as read (temp fix)

packages/discovery-provider/src/queries/get_extended_purchase_gate.py, packages/discovery-provider/src/queries/get_trending_playlists.py
We had two (or more) playlists on trending that shared one (or more) tracks.
In the query for trending playlists, we extend the tracks which calls into `get_legacy_purchase_gate`.
However, since the track was in two or more playlists, we'd try to extend it twice, which would then call `get_legacy_purchase_gate` _again_ on the already converted purchase gate.
This PR makes it so we don't call extend track multiple times on the same track, and even if we do, `get_legacy_purchase_gate` is updated to be idempotent and return early if it sees a dict instead of a list of splits.
=> Fix trending playlists

packages/mobile/src/components/skeletons/EntitySkeleton.tsx
Don't need margins anymore as these are being rendered inside of `ScreenContent`.
Pretty sure the fallback on line 86 of `TrackScreen` won't ever happen as `user` and `track` should have been loaded already for the navigation to `TrackScreen` to be possible.
```
if (!track || !user) {
return <TrackScreenSkeleton />
}
```
https://github.com/user-attachments/assets/ef656b21-1226-492e-91a1-c4cfc5572700
=> Fix mobile Track/Collection skeleton margins

packages/mobile/src/components/user/FollowButton.tsx, packages/mobile/src/harmony-native/components/Button/FollowButton/FollowButton.tsx
2 things:
- Defer dispatching the follow actions slightly to push them to the back of the event loop.
- `onPress` was being passed in to `Pressable` via the `{...other}` props which was clobbering the explicit `onPress`. Cleaned that up by moving `onPress` into the `handlePress` inside `FollowButton`.
- Tradeoff is the subscription (bell) button takes a while to pop in, as this depends on the follow request coming back from the backend. I think this is fine for now. Ideally could do some optimistic thing but that gets hairy.
including full screen rec so you can see the keypresses
https://github.com/user-attachments/assets/027ffa0d-5144-4b86-a0c3-84a55bededde
=> [C-5335] Mobile follow button snappy

package-lock.json, packages/libs/src/NativeAudiusLibs.ts, packages/libs/src/WebAudiusLibs.ts, packages/sdk/package.json, packages/sdk/src/sdk/middleware/addRequestSignatureMiddleware.ts
Two-pronged problem:
1. I missed updating `WebAudiusLibs` and `NativeAudiusLibs` with some fixes for entity manager user state.
2. `addRequestSignatureMiddleware` continues to be prone to race conditions in the code that checks for various conditions that require updating the signature. This results in occasionally failing to fetch the user right after signup due to requests using the wrong wallet address.
First issue is an easy fix. For the latter, I decided to ditch the complicated promise-based stuff because I think what we really want here is an exclusive queue where each request has a chance to examine the current parameters determining the signature and update them if needed without fear that another request will be reading/writing at the same time. So I switched it to using a …
=> Fix user state issues with signUp breaking follows

packages/mobile/src/components/challenge-rewards-drawer/ReferralRewardContents.tsx, packages/web/src/pages/audio-rewards-page/components/modals/ChallengeRewardsModal/ChallengeRewardsModal.tsx, packages/web/src/pages/sign-on-page/SignOnPage.tsx
Telegram does not respect `ref` query param
copied referral link from challenge modal.
does mobile sign up not support this? i couldn't find any code
=> Use rf instead of ref for sign up

packages/identity-service/src/routes/authentication.js
Was seeing [these errors](https://app.axiom.co/audius-Lu52/stream/identity?q=%7B%22children%22%3A%5B%7B%22field%22%3A%22requestUrl%22%2C%22op%22%3A%22%3D%3D%22%2C%22value%22%3A%22%2Fauthentication%22%7D%2C%7B%22field%22%3A%22level%22%2C%22op%22%3A%22%3D%3D%22%2C%22value%22%3A%22error%22%7D%2C%7B%22field%22%3A%22msg%22%2C%22op%22%3A%22%21%3D%22%2C%22value%22%3A%22Missing%20otp%22%7D%2C%7B%22field%22%3A%22msg%22%2C%22op%22%3A%22not-starts-with%22%2C%22value%22%3A%22Error%20processing%20request%22%7D%5D%2C%22field%22%3A%22%22%2C%22op%22%3A%22and%22%7D) in Axiom:
```
error getting user record from existing user: user email and auth param mismatch
```
looks like on mobile people are capitalizing the first character of their email, so strict equals isn't matching their saved email.
=> Make email check case insensitive

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/web/src/common/store/cache/tracks/sagas.ts, packages/web/src/common/store/social/tracks/recordListen.ts, packages/web/src/common/store/social/tracks/store.test.ts, packages/web/src/common/store/upload/sagas.ts
A few calls in `AudiusBackend` were missed with the removal of UserStateManager and are failing to pass `userId`. This will fix it for now until we move those code paths over to SDK.
=> [QA-1819] Fix missing userId in backend calls

packages/discovery-provider/src/api/v1/playlists.py, packages/discovery-provider/src/queries/get_top_playlists_es.py, packages/discovery-provider/src/queries/get_trending_playlists.py
When calling extend playlist at the API level for top albums, we are doing it _twice_ since the query level already did so.
=> [QA-1822] Only extend playlists at the api level

packages/sdk/src/sdk/api/playlists/PlaylistsApi.ts, packages/sdk/src/sdk/api/tracks/TracksApi.ts, packages/sdk/src/sdk/api/users/UsersApi.ts, packages/sdk/src/sdk/services/Auth/UserAuth.ts, packages/sdk/src/sdk/services/EntityManager/EntityManager.ts, packages/sdk/src/sdk/services/Storage/Storage.ts, packages/sdk/src/sdk/services/Storage/types.ts, pkg/mediorum/server/serve_upload.go, pkg/mediorum/server/server_basic_auth.go
Uses the same strategy as the "edit upload" flow:  A signature query param.
Updates mediorum to read this in the create upload code path.
=> SDK adds signature query param to uploads

.changeset/quick-eels-pay.md, packages/discovery-provider/src/api/v1/models/playlists.py, packages/discovery-provider/src/api/v1/users.py, packages/sdk/src/sdk/api/generated/full/models/PlaylistFull.ts
When fetching playlists/albums by user id, we don't populate tracks (it could be quite expensive - imagine a user with 50 playlists each with 100 tracks).
Currently the type here is required, so make it not required!
Local stack
=> Do not require tracks in full playlist response type

packages/discovery-provider/src/queries/get_extended_purchase_gate.py, packages/es-indexer/src/indexNames.ts, packages/sdk/src/sdk/services/DiscoveryNodeSelector/DiscoveryNodeSelector.test.ts
A bad value in `splits.user_id` can cause problems.  We deleted the bad tracks, but some ES indexes might still have them cached, so:
* make query code more resilient to bad `user_id` values.
* bump tracks index in ES
* fix flakey SDK test also
=> Safer splits

packages/libs/src/NativeAudiusLibs.ts, packages/libs/src/WebAudiusLibs.ts
Track edits that need to retranscode the preview are failing with 
```
upload cannot be updated because it does not have an associated user wallet
```
We were not passing user wallet and id into CreatorNode in WebAudiusLibs and NativeAudiusLibs. I believe introduced with https://github.com/AudiusProject/audius-protocol/pull/9673
Confirmed can upload and edit preview
=> Fix track edit preview transcode missing wallet

packages/web/src/services/sentry.ts
Enables session replay in sentry. 
Sets it to only work when errors are triggered - although with our code this is likely to still be a lot of users 💀 
May need tweaking if we hit our recording limits way too quickly
web:stage + got a replay to show up here: https://audius.sentry.io/replays/02e2450ddfe04f77b3d7698e3d337182/?referrer=%2Fissues%2F%3AgroupId%2Fevents%2F%3AeventId%2Freplays%2F&t=5.899700000047684&t_main=errors
=> [C-5391] Add session replay to sentry

packages/common/src/store/pages/profile/reducer.ts
Profile pages were crashing due to the Lineup infinitely rendering. This is because the profileHandle was being set to undefined, since the `handle` key existed but was undefined on the action. This change fixes boolean logic introduced #10399
=> Fix Profile page crash

packages/discovery-provider/integration_tests/queries/test_get_collections_library.py, packages/discovery-provider/src/queries/get_collection_library.py
We added code to hide certain results from the library collections endpoints. But they did not take into account playlists owned by the requesting user. This adds a little bit of extra logic to make sure those are never excluded.
Tested in local client against local stack.
=> [QA-1824] Don't filter own playlists in collection library queries

.changeset/twelve-cycles-grow.md, packages/common/src/services/audius-backend/solana.ts, packages/common/src/store/buy-usdc/utils.ts, packages/sdk/src/sdk/services/Solana/programs/ClaimableTokensClient/ClaimableTokensClient.ts
- Updates `getOrCreateUSDCUserBank` to use SDK
- Prior, this was using libs and thus identity's relay, which doesn't have the same config for the RPCs and doesn't have the latest retry logic etc.
- SDK's `ClaimableTokensClient` is a singleton, and its `getOrCreateUserBank` should be concurrency safe already, so no need for saga channels.
- Fixes an extraneous bug I found along the way where we were sending the mint name as the transaction commitment
- Fixes the SDK to use the default priority fee and add a compute budget limit when calling `getOrCreateUserBank` in the `ClaimableTokensClient`
Another bug I found is the funding of Solana relayers script is failing due to outdated `@solana/web3.js`. It was missed in the audit because its source is not on GitHub. I've funded the wallets and …
=> Fix USDC user bank creation

packages/common/src/services/audius-backend/solana.ts, packages/common/src/store/buy-crypto/sagas.ts, packages/common/src/store/buy-usdc/sagas.ts, packages/common/src/store/buy-usdc/utils.ts, packages/common/src/store/purchase-content/sagas.ts
Missed in #10445 post CR comment 🤦
=> Fix usages of getTokenAccountInfo to conform to new arg type

packages/mobile/src/components/premium-content-purchase-drawer/PremiumContentPurchaseDrawer.tsx, packages/web/src/components/premium-content-purchase-modal/PremiumContentPurchaseModal.tsx
I'm not sure how this even worked before. But I suspect what was happening is:
* The intended usage of useEffect is that if you return a function, it will be invoked when the component unmounts. 
* We're returning the `resetForm` function from one of them. I believe the intended usage was to _call_ that function inside the effect when the form changes. But what actually happens is that it's called after the form unmounts. And I believe this is referencing something in Formik Context that no longer exists.
We also had another `useEffect` call in this component that was throwing warnings about returning objects, so I wrapped it in braces so we are no longer returning the result of `dispatch`.
Tested on simulator against staging.
=> Fix bad useEffects calls in PremiumContentPurchaseDrawer

packages/web/src/common/store/queue/sagas.ts
This is a fun one. The behavior exhibited is:
1. Start playing a track (from the feed is a good source)
2. Navigate to a profile with less than 3 tracks on it. Or scroll through the tracks in the profile until you've loaded the entire lineup for said profile.
3. Play a track from the profile that's less than 3 items from the end of the list
4. Watch the track feed disappear.
What's actually happening to cause this:
We have some logic in the queue saga that checks if the queue has less than 3 items in it. If so, and we're currently playing from a lineup source, it will trigger a fetch on that lineup to further populate the queue. But it uses the artist of the currently playing track as input to the lineup selector. For a profile lineup selector, that's only valid if the currently playing …
=> [QA-1827] Fix queuing short profile lineups issue

.changeset/polite-seahorses-sit.md, packages/common/src/adapters/access.ts, packages/common/src/adapters/track.ts, packages/sdk/src/sdk/api/tracks/TracksApi.ts, packages/sdk/src/sdk/api/tracks/types.ts
* Fix unsetting stream_conditions and download_conditions by sending null instead of undefined
* Fix formatting of stream_conditions and download_conditions
* update track upload/edit metadata schema AccessCondition ids to be numeric. This is because the api expects plain numbers instead of hash ids
* transform streamConditions and downloadConditions objects to snake_case in sdk uploadTrack and updateTrack. This is to match the transformation happening on the read side
* Change accessConditionsToSDK adapter to not parse number ids into hash ids
Tested setting and unsetting access conditions, including FollowGated and SupporterGated which include an id
=> Fix track edit sdk issues

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/services/remote-config/feature-flags.ts, packages/identity-service/src/featureFlag.js
Feature flag cleanup.
The flag appears to be on in optimizely:
=> Remove SOLANA_LISTEN_ENABLED feature flag

pkg/mediorum/server/db.go, pkg/mediorum/server/repair.go, pkg/mediorum/server/serve_upload.go, pkg/mediorum/server/serve_upload_test.go, pkg/mediorum/server/server.go, pkg/mediorum/server/transcode.go, pkg/mediorum/server/transcode_preview.go
```
POST /generate_preview/:cid/:second
```
Will generate 30s audio preview, replicate to peers, save a row in `audio_previews` table and return result to client.
Client should use `cid` from returned JSON.
=> [PROTO-1979] Endpoint to generate an audio preview for a CID.

packages/mobile/src/store/offline-downloads/sagas/offlineQueueSagas/workers/downloadTrackWorker.ts, packages/web/src/common/store/queue/sagas.ts
Fixes two issues with offline mode:
- Tracks were not downloading in offline mode unless marked available for download by the artist. Fix is to use the `/stream` endpoint instead for fetching the offline audio.
- Offline lineups were showing an error toast on track play near end of playlist because we were failing to fetch recommended autoplay tracks. Disabled this behavior while offline.
According to the charts, these errors spiked starting Nov 5th, around the time we shipped changes to the stream endpoint mirroring. Unsure the full root cause, but could be related?
tested on ios sim and android device
=> [QA-1840] Fix Offline Mode errors

packages/discovery-provider/Dockerfile.prod
Breaking integration test 
```
5.881 OK: 25849 distinct packages available
6.758 ERROR: unable to select packages:
6.761   libpq-15.9-r0:
6.761     breaks: world[libpq=15.8-r0]
6.761     satisfies: libpq-dev-15.9-r0[libpq=15.9-r0]
6.761                postgresql15-15.9-r0[so:libpq.so.5]
6.761                postgresql15-client-15.9-r0[so:libpq.so.5]
6.761                postgresql15-dev-15.9-r0[so:libpq.so.5]
6.761                postgresql15-contrib-15.9-r0[so:libpq.so.5]
6.761                libecpg-15.9-r0[so:libpq.so.5]
```
=> Fix libpq version dependency

packages/web/src/components/file-replace-container/FileReplaceContainer.tsx
Added the component for use later
Went with a more simple display component that does not handle the playing or downloading of the track file bc the use in the different contexts around the app would make this a bit complex, but I'm willing to change this if we feel that the logic would be better here
=> [C-5404] Add FileReplaceContainer component to web

packages/discovery-provider/src/queries/get_health.py, packages/discovery-provider/src/tasks/index_aggregate_tips.py
Was accidentally querying for `one()` instead of `first()` in the indexer, which broke for obvious reasons in stage/production.
Missed this error since `since_last_completed` was always `None` so health check always thought it was healthy.
Have not tested...
=> Fix aggregate tip indexing and improve Solana indexer health check

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/services/remote-config/feature-flags.ts
Feature flag cleanup
The primary one was turned on but the secondary one was turned off? not sure if it matters
=> Remove PREFER_HIGHER_PATCH_FOR_PRIMARY/SECONDARIES feature flags

packages/mobile/src/components/core/DateTimeInput.tsx, packages/mobile/src/screens/edit-track-screen/fields/ReleaseDateField.tsx, packages/mobile/src/screens/edit-track-screen/screens/ReleaseDateScreen.tsx, packages/web/src/components/edit/fields/DatePickerField.tsx
Reports of some tracks showing as scheduled release in feed. This is not because they are scheduled release though. The default time dayjs uses is set to noon instead of midnight so tracks released in the morning are actually in that user's local noon time. 
Also mobile date picker input placeholder has ReleaseDate as one word. It doesn't have the same issue above.
Tested on web staging. Uploaded a track while my system clock was set to the morning. Repro'd and fixed the issue.
=> [QA-1842] Fix web date picker time default

.changeset/heavy-moles-speak.md, package-lock.json, packages/commands/src/account-managers.mjs, packages/commands/src/auth-headers.mjs, packages/commands/src/claim-reward.mjs, packages/commands/src/create-user-bank.mjs, packages/commands/src/edit-user.mjs, packages/commands/src/mint-tokens.mjs, packages/commands/src/purchase-content.mjs, packages/commands/src/tip-audio.mjs, packages/commands/src/tip-reaction.mjs, packages/commands/src/unfollow.mjs, packages/commands/src/upload-track.mjs, packages/commands/src/utils.mjs, packages/libs/src/api/Users.ts, packages/sdk/rollup.config.ts, packages/sdk/src/sdk/services/Auth/UserAuth.ts
#9673 and #10311 broke audius-cmd for two reasons:
1. `UserStateManager` no longer exists. Some of the commands attempt to read the current user from libs directly.
2. Libs and SDK work more smoothly if you initialize SDK _first_ and then initialize libs with the `userId` and `wallet` of the currently logged-in user.
Additionally, our usage of SDK in audius-cmd was leveraging `AppAuth`, which doesn't really reflect how we use it in client. It should be using `UserAuth` instead, since that wraps an instance of Hedgehog.
So to get everything working again:
* Updated the initialization functions in audius-cmd to do SDK first, using a UserAuth instance, then libs after reading the current user
* Ported over the dummy password logic that we use in client to initialize Hedgehog to an ephemeral …
=> [PAY-3605] Fix audius-cmd after account/UserStateManager updates

packages/sdk/rollup.config.ts
This was throwing errors for me on local client. We only need the externals behavior for node environments, so adding it to the browserInternal list to restore status quo from before the change
Tested on local client.
=> Fix rollup for browser now that hashes is externalized

packages/discovery-provider/ddl/migrations/0107_add_email_tables.sql
This PR adds the database migration for the email tables needed to enable encrypted emails on discovery.
**Example tables** 
| id | email_address_owner_user_id | primary_access_user_id | encrypted_email | created_at | updated_at |
|----|---------------------------|----------------------|----------------|------------|------------|
| 1 | 123 | 456 | 'base64email1' | 2024-01-01 00:00:00 UTC | 2024-01-01 00:00:00 UTC |
| id | primary_access_user_id | encrypted_key | created_at | updated_at |
|----|----------------------|---------------|------------|------------|
| 1 | 456 | 'base64key1' | 2024-01-01 00:00:00 UTC | 2024-01-01 00:00:00 UTC |
| id | primary_access_user_id | delegated_access_user_id | encrypted_key | created_at | updated_at | …
=> [PAY-3604] Add migration for emails

cmd/audiusd/Dockerfile, cmd/mediorum/Dockerfile
After moving essentia to no longer build-static (https://github.com/AudiusProject/audius-protocol/pull/10398/files), we lost the ability to analyze because we were missing `MonoLoader`
Was able to get that working again by including `/usr/lib/x86_64-linux-gnu/pkgconfig` in the package config for configuring essentia. Helpful reference: https://github.com/MTG/essentia/issues/273
Tested on staging
1. Uploaded track which got correctly tagged with key/bpm
2. Edited the track from free => premium, which generated a preview correctly as well
=> Fix essentia build commit

dev-tools/README.md, dev-tools/audius-cmd, packages/commands/Dockerfile.dev, packages/commands/README.md
Something about the turbo cache is interacting poorly with identity service and causing it to restart even though turbo reports a full cache hit on all dependencies. To make this a little more usable, I updated the dev-tools script to only auto-build if the dist file doesn't exist yet. Otherwise you can now do `audius-cmd build` to explicitly build the output (for instance if you changed something or it's out of date).
It's a compromise between auto-building if deps change and breaking identity due to whatever filesystem weirdness is going on. I will come back to this later to try and find a better long term solution. But I would like to unblock devs for now.
Local stack.
=> Fix some issues with audius-cmd restarting identity

packages/harmony/src/components/popup/Popup.tsx
Fixes this circular dep
```
src/components/button/index.ts
-> src/components/button/FilterButton/FilterButton.tsx
-> src/components/internal/Menu.tsx
-> src/components/popup/Popup.tsx
-> src/components/button/index.ts
```
build passes cleanly
=> Fix harmony circular dependency

packages/web/src/public-site/PublicSite.tsx
Landing page doesn't support feature flags b/c it is not connected to the store.
This is an easy flip though, so we should just ship a new version when we're ready to launch "v2"
visit localhost:3001 in incognito
=> Fix broken landing page

packages/discovery-provider/integration_tests/tasks/entity_manager/test_email_entity_manager.py, packages/discovery-provider/integration_tests/utils.py, packages/discovery-provider/src/tasks/entity_manager/entities/email.py, packages/discovery-provider/src/tasks/entity_manager/entity_manager.py, packages/discovery-provider/src/tasks/entity_manager/utils.py, packages/discovery-provider/src/tasks/metadata.py, packages/sdk/src/sdk/api/users/UsersApi.test.ts, packages/sdk/src/sdk/api/users/UsersApi.ts, packages/sdk/src/sdk/api/users/types.ts, packages/sdk/src/sdk/services/EntityManager/types.ts
This PR adds entity manager support for uploading emails. 
_It does not handle the encryption of the emails, that will be done in a follow up PR._ 
Locally by running the below code in `ProfilePage.tsx` and checking the local db for the content 
```tsx
const userId = useGetCurrentUserId({})
useEffect(() => {
async function addEmail() {
const sdk = await audiusSdk()
console.log('calling addEmail')
try {
await sdk.users.addEmail({
emailOwnerUserId: 1234,
primaryUserId: userId.data ?? 0,
encryptedEmail: 'encryptedEmail',
encryptedKey: 'encryptedKey'
})
console.log('addEmail succesful')
} catch (error) {
console.error('Error adding email:', error)
}
}
if (userId.data) {
addEmail()
}
}, [userId])
```
=> [PAY-3614] Add entity manager support for emails

packages/web/src/common/store/upload/sagas.ts, packages/web/src/components/edit-track/EditTrackForm.tsx
* Small update to permalink that we redirect to after edit so that the audio is there right away
* Prioritize the replace confirmation modal in the edit flow
=> [C-5443, C-5444] Web track replace fixes

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/services/audius-backend/RecordIP.ts, packages/common/src/store/account/sagas.ts, packages/mobile/src/store/account/sagas.ts, packages/mobile/src/store/notifications/sagas.ts, packages/mobile/src/store/settings/sagas.ts, packages/web/src/common/store/account/sagas.js, packages/web/src/common/store/notifications/sagas.ts, packages/web/src/common/store/pages/audio-rewards/sagas.ts, packages/web/src/common/store/pages/settings/sagas.ts, packages/web/src/common/store/pages/signon/sagas.ts, packages/web/src/pages/audio-rewards-page/components/modals/HCaptchaModal.tsx, packages/web/src/pages/oauth-login-page/utils.ts, packages/web/src/pages/settings-page/store/sagas.ts, packages/web/src/services/audius-backend/Cognito.ts, packages/web/src/store/account/sagas.ts
Use sdk auth service in AudiusBackend instead of libs Web3Manager.
Seems like we might want to wrap the logic in `signData` inside sdk instead of forcing user to manage manually?
Thanks to @schottra for figuring out the logic so I could copy it from audius-cmd.
- Tested changing notification settings (identity)
- Tested manager/managee oauth flow (discovery) - is this correct? couldn't figure out how to test authorizing 3rd party app on local
=> [PAY-3608] Use sdk auth service in AudiusBackend

monitoring/healthz/src/components/EnvironmentSelector.tsx, monitoring/healthz/src/pages/Nodes.tsx, pkg/core/console/routes.go
Only the nodes that will be using discovery functionality moving forward will be displayed in the discovery healthz section.
Local healthz build
=> Hide non whitelisted nodes from healthz discovery section

packages/discovery-provider/src/queries/download_csv.py
This PR adds the white space back for the header values related to the sales CSV and adds underscores for the JSON response in order to maintain the current styling on clients
Locally
=> [TRIVIAL] Only add underscores for JSON response

packages/web/src/store/sign-out/sagas.ts
Noticed that signout on mobile-web was somewhat broken, added navigation to trending after signout to match web behavior.
Tested on local web + mobile-web
On signout, before this change:
=> Navigate to trending after signout

packages/common/src/services/remote-config/defaults.ts, packages/common/src/services/remote-config/types.ts, packages/web/src/services/sentry.ts
Add a remote config value for sentry replay sample rate that we can tweak/enable/disable sentry replay recording on the fly.
One tradeoff to call out: In order to make this work I had to make sentry wait for remote config to init, on localhost this seems to add a second or so, but seems like a negligible amount of overhead.
web stage
=> Add remote config value for sentry replay recording

packages/common/src/store/ui/modals/parentSlice.ts, packages/common/src/store/ui/modals/types.ts, packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx, packages/mobile/src/screens/edit-track-screen/EditTrackFormOverflowMenuDrawer.tsx, packages/mobile/src/screens/edit-track-screen/EditTrackFormPreviewContext.tsx, packages/mobile/src/screens/edit-track-screen/EditTrackModalScreen.tsx, packages/mobile/src/screens/edit-track-screen/components/FileReplaceContainer.tsx, packages/mobile/src/screens/edit-track-screen/types.ts, packages/mobile/src/screens/upload-screen/screens/CompleteTrackScreen.tsx, packages/mobile/src/screens/upload-screen/screens/SelectTrackScreen.tsx, packages/mobile/src/screens/upload-screen/screens/UploadFileContext.tsx, packages/mobile/src/screens/upload-screen/screens/UploadModalScreen.tsx, packages/mobile/src/store/drawers/slice.ts
Add contexts for handing previews and upload files for the mobile upload and edit flows
Add the FileReplaceContainer component and add it to the EditTrackForm component
Previews are currently not working bc they interfere with the audio player and TrackPlayer too much so another player/approach is being looked into
=> [C-5412, C-5414] Add file replace functionality to mobile upload flow

packages/web/src/components/edit-track/EditTrackForm.tsx
The file prop is no longer on the track info for some reason (lots of upload changes recently with the sdk updates and whatnot)
Updated to use the download url from the track metadata instead
=> [C-5462] Fix EditTrackForm download function

packages/common/src/services/audius-backend/AudiusBackend.ts
These are no longer needed after sdk migration
=> Remove unneeded waitForLibsInit

packages/discovery-provider/src/queries/get_extended_purchase_gate.py
Some ~10 old tracks on staging but none on prod have a missing splits field in the purchases
https://discoveryprovider2.staging.audius.co/v1/tracks/G2aojQv
It seems like indexing logic should handle this now, so this may be just an insurance policy I'm taking out, but with the change my feed loads
Stage dn1
=> Fix splits issue for old usdc_purchases

packages/common/src/hooks/content/useCollectionLockedStatusVariant.ts, packages/common/src/hooks/content/useIsCollectionUnlockable.ts, packages/common/src/hooks/content/useIsTrackUnlockable.ts, packages/common/src/hooks/content/useTrackLockedStatusVariant.ts, packages/mobile/src/components/lineup-tile/TrackTileMetrics.tsx, packages/web/src/components/collection/CollectionLockedStatusBadge.tsx, packages/web/src/components/collection/CollectionTileMetrics.tsx, packages/web/src/components/collection/CollectionTileStats.tsx, packages/web/src/components/track/TrackLockedStatusBadge.tsx, packages/web/src/components/track/TrackTileMetrics.tsx, packages/web/src/components/track/TrackTileStats.tsx
Applies same optimization techniques from mobile lineup tiles to desktop. I found a few more areas where mobile was using inneficient hooks through this pass, so mobile should also get a decent additional speedup.
=> Improve desktop track tile perf

packages/common/src/api/collection.ts, packages/common/src/api/track.ts
Just a little change to keep us from making bogus network requests if we end up with a completely empty list after filtering out invalid ids. The bulk fetch hooks will still throw errors due to us not returning anything for the invalid id requests. But that can be addressed separately if needed.
=> Adds guards to bulk fetching hooks

pkg/core/chain/auditor.go, pkg/core/config/config.go, pkg/core/config/genesis/stage.json
It takes too long to produce SLA Rollup data as block times aren't as short as originally anticipated.
=> Shorter rollup intervals for stage and prod core

packages/mobile/src/app/Drawers.tsx, packages/mobile/src/screens/edit-track-screen/EditTrackForm.tsx, packages/mobile/src/screens/edit-track-screen/EditTrackModalScreen.tsx, packages/mobile/src/screens/edit-track-screen/EditTrackNavigator.tsx, packages/mobile/src/screens/edit-track-screen/EditTrackScreen.tsx, packages/mobile/src/screens/edit-track-screen/components/ReplaceTrackConfirmationDrawer.tsx, packages/mobile/src/screens/edit-track-screen/components/ReplaceTrackProgressDrawer.tsx, packages/mobile/src/screens/edit-track-screen/components/index.ts, packages/mobile/src/screens/edit-track-screen/types.ts, packages/mobile/src/screens/edit-track-screen/util.ts, packages/mobile/src/screens/upload-screen/screens/CompleteTrackScreen.tsx
Added the ReplaceFileProgressDrawer
Updated the track edit form on mobile to handle the track replace functionality and stuff
* Previewing is still not implemented
* Downloading the original file is not implemented yet
=> [C-5413, C-5415] Add FileReplace to the mobile edit track flow

packages/web/src/pages/dashboard-page/store/sagas.ts
We were not passing in object args, and also not encoding the user id, to `getPlaylistsByUser`.
Note: not sure why i have to explicitly type `accountUserId` but without it it's `any`.
=> Fix artist dashboard page

scripts/get-release-dirs.sh
protocol dirs have moved around a bit and aren't captured in the daily release notification anymore
N/A
=> add new proto dirs to release notification

packages/identity-service/src/routes/authentication.js, packages/identity-service/test/authenticationTest.js
If you attempt to authenticate with an OTP and a mixed-case email address, we will fail to look up the OTP because we aren't applying the same lowercase logic in that code path. This updates the GET route to lowercase the email at the beginning (which we do in a lot of other routes) so we don't end up trying to apply the OTP and visitorId logic to whatever mixed-case value the user might have entered.
Wrote a unit-test and tested locally against dev stack.
=> [QA-1852] Fix case sensitivity issues in login GET route

packages/web/src/common/store/pages/signon/sagas.ts
It's always running the `isGuest` block, which attempts to fetch a user for an ephemeral wallet and explodes.
Local stack
=> Fix signup error due to missing yield statement

packages/web/src/common/store/profile/sagas.js
Missed this one in the PR that updated the signature for this function. Amazingly it doesn't crash, but it does lead to the original metadata being thrown out completely in favor of two `null` values for associated wallets :-)
=> update a missed updateCreator call with new signature

packages/mobile/src/components/fields/PickArtworkField.tsx, packages/mobile/src/screens/upload-screen/utils/processTrackFile.ts
Fix regression from https://github.com/AudiusProject/audius-protocol/pull/10581/files
For audio files without artwork, the entire image selector input is missing. This leads to 'Fix errors to continue' blocking the continue button, but not indication of why. Underlying error is 'Artwork is required' but since the whole artwork component is missing, you don't even see it.
upload working successfully now
=> Fix mobile upload image input missing

packages/web/src/common/store/cache/users/sagas.ts, packages/web/src/common/store/profile/fetchProfileCollectionsSaga.ts, packages/web/src/common/store/profile/sagas.js, packages/web/src/pages/profile-page/ProfilePageProvider.tsx, packages/web/src/pages/profile-page/components/desktop/ProfilePage.tsx, packages/web/src/pages/profile-page/components/mobile/ProfilePage.module.css, packages/web/src/pages/profile-page/components/mobile/ProfilePage.tsx
Few issues I paired through with @schottra today. We double fetch each playlist on profile pages currently, and we also have two ways of doing this between mobile and web.
=> Reduce code dupe, add spinner, fix performance on profile collections

packages/libs/src/api/Account.ts
Missed deleting this call to libs identity getUserEmail, but isn't in use anywhere.
Related to https://github.com/AudiusProject/audius-protocol/pull/10583
=> Remove getUserEmail from libs Account

packages/mobile/src/components/core/Screen/ScreenPrimaryContent.tsx, packages/mobile/src/components/skeletons/EntitySkeleton.tsx, packages/mobile/src/screens/collection-screen/CollectionScreen.tsx, packages/mobile/src/screens/track-screen/TrackScreen.tsx
Fixes issue where entity skeleton image was too small
Fixes issue where there was a flash from skeleton to main content. Now we only do the animation when there is no skeleton present
https://github.com/user-attachments/assets/9b6cb568-0d39-4ea5-a31f-9d55730d47a9
=> Improve mobile entity collection screen loading

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/store/solana/sagas.ts
Remove `getRandomFeePayer` function from `AudiusBackend` and use the feePayer from `sdk.solanaRelay` service instead.
Local web stage - observed fee payer address gets set in redux
=> Remove getRandomFeePayer

packages/commands/src/album/purchase-album.ts, packages/commands/src/misc/auth-headers.ts, packages/commands/src/misc/claim-reward.ts, packages/commands/src/misc/mint.ts, packages/commands/src/misc/withdraw-tokens.ts, packages/commands/src/track/purchase-track.ts, packages/commands/src/track/upload-track.ts, packages/commands/src/user/tip-user.ts
Casings and splits format was incorrect in audius-cmd
Also bolds all the yellow text in audius-cmd
Tested via:
```sh
audius-cmd track upload --price 1
audius-cmd track purchase <id> 1 # succeeds
audius-cmd track purchase <id> 1 # already owned!
```
=> Fix audius-cmd purchase gated content

.changeset/polite-bikes-appear.md, packages/libs/src/services/creatorNode/CreatorNode.ts, packages/sdk/src/sdk/services/Storage/Storage.ts
This is by far the most common upload failure in sentry.
It's likely that the root cause is different, since storage returning `data: []` is probably due to bad `formData`, but hopefully this at least gets us to throw something more useful.
Issue is intermittent and hard to repro, so checked that upload still works with this change
=> [C-5477] Guard against empty response from storage node

packages/common/src/store/cache/actions.ts, packages/common/src/store/cache/reducer.ts, packages/common/src/store/cache/types.ts, packages/web/src/common/store/cache/collections/addTrackToPlaylistSaga.ts, packages/web/src/common/store/cache/sagas.ts, packages/web/src/common/store/lineup/sagas.ts, packages/web/src/common/store/pages/collection/sagas.js, packages/web/src/common/store/player/sagas.ts, packages/web/src/common/store/queue/sagas.ts, packages/web/src/common/store/social/collections/sagas.ts
Playlists were broken after https://github.com/AudiusProject/audius-protocol/pull/10558
They appeared empty on the collection page. Cache subscriptions were apparently responsible for correctly setting UIDs in the cache, but aren't really used for anything else. This pr reverts some of the changes in the previous pr, keeping subscriptions around to handle UIDs. we could rename this to be more descriptive, but hopefully this all goes away soon anyway
=> [QA-1873] Add back cache subscribe so UIDs get set correctly for playlists

packages/mobile/src/app/ErrorBoundary.tsx, packages/web/src/app/AppErrorBoundary.tsx
Upgrades the error level of our "something went wrong" page error boundaries from Error to Fatal - goal is that since we care more about these errors we'll likely eventually hook up some alerting.
=> Upgrade something went wrong page error level

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/services/audius-backend/solana.ts, packages/common/src/services/wallet-client/WalletClient.ts, packages/common/src/store/buy-crypto/sagas.ts, packages/common/src/store/buy-usdc/sagas.ts, packages/common/src/store/purchase-content/sagas.ts, packages/web/src/common/store/tipping/sagas.ts, packages/web/src/common/store/wallet/sagas.ts
Convert `getWaudioBalance` to use sdk functions and solana functions via `connection` directly instead of libs SolanaWeb3Manager.
Stop using `getSolanaConnection` in favor of connection from sdk.
Notes/Todos:
* @rickyrombo I tried modifying the `getSolanaConnection` fn in `services/audius-backend/solana.ts` but it resulted in having to pipe `env` in everywhere we needed a connection. Opted to use the sdk connection instead. If this is a nono feel free to revert the last 2 commits in this PR and things should work. (I also noticed there's another `getSolanaConnection` in web services..)
* The old version of this fn in `SolanaWeb3Manager` also checked if the given address was a token account, and if not, grabbed the token account for you and did operations on those instead. I think we don't …
=> Migrate getWaudioBalance to sdk + remove getSolanaConnection

packages/commands/src/utils.ts
Fixes `audius-cmd`'s relationship with identity service:
- Throws if `Hedgehog`'s `setAuthFn` or `setUserFn` does not succeed
- Maps `username` to `email`
- Ensures `Content-Type` header is set to `application/json`
Didn't bother stripping out the wallet from the request or signing the request. This is a local-stack only utility, and there's no change email flow in `audius-cmd` or anything
=> Fix audius-cmd identity service functionality

packages/common/src/services/audius-backend/AudiusBackend.ts, packages/common/src/services/wallet-client/WalletClient.ts, packages/web/src/common/store/tipping/sagas.ts, packages/web/src/common/store/wallet/sagas.ts
* Migrate `AudiusBackend` `getAssociatedTokenAccountInfo` to use solana library directly, using sdk solana connection.
* Add a `getTokenAccount` helper function to replace libs `SolanaWeb3Manager` function.
Send wAUDIO is broken for some other reason, but I confirmed that I'm passing in the exact same args to `solanaWeb3Manager.transferwAudio` as on stage.
Also confirmed the failure case where the token account doesn't exist and the recipient account doesn't have enough sol balance to create an ATA:
=> [PAY-3640] Convert getAssociatedTokenAccountInfo to sdk

packages/common/src/store/account/selectors.ts, packages/mobile/src/screens/sign-on-screen/SignOnStack.tsx, packages/web/src/common/store/pages/signon/actions.ts, packages/web/src/common/store/pages/signon/selectors.ts, packages/web/src/components/avatar/Avatar.tsx, packages/web/src/components/nav/desktop/AccountDetails.tsx, packages/web/src/components/nav/desktop/LeftNav.tsx, packages/web/src/components/nav/desktop/LeftNavCTA.tsx, packages/web/src/components/nav/desktop/LeftNavLink.tsx, packages/web/src/components/premium-content-purchase-modal/components/PurchaseContentFormFooter.tsx, packages/web/src/components/profile-progress/ConnectedProfileCompletionPane.jsx, packages/web/src/components/profile-progress/hooks/index.js, packages/web/src/hooks/useRequiresAccount.ts, packages/web/src/pages/sign-on-page/SignOnPage.tsx, packages/web/src/pages/sign-up-page/utils/useDetermineAllowedRoutes.ts, packages/web/src/utils/route.ts
Adds mvp elements of desktop guest UI.
- Adds guest mode account details and refactors component for readability
- Adds finish-account left-nav-cta action
- Updates finish-account button in purchase modal to use a link
- Adds a "restriction" prop to useRequiresAccount hooks to distinguish between signed-out user and guest-user, and updates toast message and left-nav links appropriately (library is navigable for guest, but feed and history require full account)
- Updates sign-up code to tell when a sign-up in initiated via a logged in guest user, and jumps user to complete password flow. Note there are quite a few things to update in this area, so more changes will come later. Also im not totally in love with the approach of reading guestEmail from local storage in the useDetierminedRoutes …
=> C 5473 guest mode UI

packages/web/src/common/store/pages/audio-transactions/sagas.ts
Thank you, javascript.
Turns out this
```filteredIds.map(parseInt)```
is equivalent to this
```filteredIds.map((str, index, array) => parseInt(str, index))```
because `map` actually passes 3 params and parseInt accepts `(input: str, radix?: number)`, so it’s trying to parse each item with `index` as the base for parsing
_Note: Confirmed that this is the only place in the code where we map `parseInt` this way with no args_
repro'd consistently before, working consistently after
=> [PAY-3649] Fix something went wrong on transactions page
